apache/tvm

.gitignore
tests/scripts/git_skip_ci_globs.py

[skip ci] Add generated docs file to .gitignore

---

src/driver/driver_api.cc
src/tir/transforms/compact_buffer_region.cc
tests/python/unittest/test_tir_transform_compact_buffer_region.py

The compacted buffer's shape should be at most the same as the original shape.

[TIR] compact buffer region

---

CONTRIBUTORS.md
gallery/how_to/tune_with_autoscheduler/tune_network_arm.py

Please join us to welcome @Hzfengsy as a new PMC member. 
Siyuan has been an active TVM contributor for years.  Siyuan leads the development of TensorIR. He has contributed to TensorIR, TVMScript,  MetaSchedule, and TensorCore intrinsics.
- [Commits History](https://github.com/apache/tvm/commits?author=Hzfengsy)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:Hzfengsy)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Hzfengsy/summary)

[COMMUNITY] Siyuan -> PMC

---

docs/install/from_source.rst

Update docs to clarify minimum Visual Studio version

---

tests/python/contrib/test_cudnn.py

See #10708
cc @areusch @masahi

[ci] Relax tolerance in flaky test_cudnn test

---

python/tvm/autotvm/measure/measure.py

The check for if the error_no was valid was wrong.
@masahi @jwfromm

[FIX,AUTOTVM] Fix printing of measure results

---

tests/python/ci/test_ci.py
tests/scripts/github_cc_reviewers.py

This will re-request reviews from existing reviewers as in #10714 which is not intended, so this lists out existing reviews/requests and filters the new reviews to add based on those usernames.
cc @areusch

[ci] Check existing and requested reviews before cc-ing

---

docker/install/ubuntu_install_python_package.sh

This is needed for #10740
cc @areusch

[ci][docker] Add Jinja2 to images

---

tests/cpp/relay/backend/contrib/cmsisnn/buffer_size_test.cc

[ci] Skip flaky CMSISNN test

---

src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc
src/relay/backend/contrib/ethosu/source_module.cc
src/relay/backend/contrib/example_target_hooks/tir_to_runtime.cc
src/target/source/codegen_c_host.cc
src/target/source/codegen_c_host.h

* Eliminates all "control reaches end of non-void function" warnings
* Eliminates all "unused variable" warnings
* Eliminates some "implicit declaration of function" warnings

[microNPU] Eliminate some compiler warnings for microNPU demo app

---

python/tvm/_ffi/base.py
python/tvm/runtime/vm.py
tests/python/relay/test_vm.py

added surpport for arg type of numeric float16 and testcase

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Fix bug mentioned in #10658. cc @masahi

[PyTorch] Fix neg indexing issue for `aten::flatten`

---

docker/Dockerfile.ci_cpu
docker/install/ubuntu_install_libxsmm.sh

RFC: https://github.com/apache/tvm-rfcs/pull/47
This is the first PR in the integration plan.

[LIBXSMM] Add libxsmm to tvm ci

---

src/tir/schedule/analysis/analysis.cc
tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py

This PR fixes a bug of `NeedsMultiLevelTiling`, which didn't consider the effect of trivial block iterators (iterators whose domains are `[0, 1)`). Such iterators impacts the following analysis by overlargely counting the number of iterators that are not used to index the block read regions, and might lead to the application of multi-level tiling where the rule is supposed not to apply.
To fix the problem, we simply skip such trivial block iterators.

[BugFix] Fix NeedsMultiLevelTiling by skipping trivial block iterators

---

CONTRIBUTORS.md

Please join us to welcome @driazati as a new reviewer to TVM. He has contributes lots of improvements to our CI, build and general automation that are instrumental for us to serve our growing community.
- [Commits History](https://github.com/apache/tvm/commits?author=driazati)
- [Code Review]( https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:driazati) 
- [Community Forum Summary]( https://discuss.tvm.apache.org/u/driazati/summary) 
Congratulations @driazati!

[COMMUNITY] David Riazati -> Reviewer

---

python/tvm/relay/op/contrib/vitis_ai.py
python/tvm/testing/utils.py
src/relay/backend/contrib/vitis_ai/config_vitis_ai.cc
tests/python/contrib/test_vitis_ai/infrastructure.py
tests/python/contrib/test_vitis_ai/test_vitis_ai_codegen.py
tests/python/contrib/test_vitis_ai/test_vitis_ai_runtime_cpu_part.py

Hi @leandron,
We have fixed the vitis-ai test failure [issue ](https://github.com/apache/tvm/issues/10757)when running with USE_VITIS_AI OFF flag. Could you please review and merge it?

[CI] Fix Vitis-AI tests when USE_VITIS_AI flag set to OFF 

---

Jenkinsfile

This broke with #10778. We should figure out a better way to re-verify the Jenkinsfile before merging changes since this is the 2nd time this kind of thing has happened.
cc @areusch

[skip ci][ci] Fix outdated Jenkinsfile

---

src/tir/transforms/lower_tvm_builtin.cc

This pr add add background context for stack allocation in builtin lowering in the code comment for future developments

[DOCS] Add background context for stack allocation in builtin lowering

---

tests/python/contrib/test_ethosn/test_tanh.py

Updated test case with int8 support.

[ETHOSN] int8 support for tanh operator

---

tests/python/contrib/test_ethosn/test_mean.py

Ethos-N int8 support for the recently added mean operator

[ETHOSN] int8 support for the mean operator

---

python/tvm/relay/frontend/paddlepaddle.py

Optimize the implmentation of scale operator, remove invalid copy.
@masahi @jiangjiajun.

[Frontend] [PaddlePaddle] Optimize the implmentation of scale operator

---

src/tir/contrib/ethosu/passes.cc
tests/python/contrib/test_ethosu/test_hoist_allocates.py

Fixes a small issue which caused SeqStmts to get left behind in the body of the inner allocate after hoisting the allocates. Flattening now happens after the mutation has happened, which consequently helps simplify the pass.
The `test_outer_seq_stmt` test case already had this behavior, so a new check has been added to catch this case.
cc @NicolaLancellotti @manupa-arm @ekalda

[microNPU] Flatten after allocates have been removed in HoistAllocates pass

---

CONTRIBUTORS.md

Add @gromero to committers list.
cc @tqchen @gromero

[COMMUNITY] new committer -- gromero

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

As title. Adds imports for Gelu, BiasGelu from the com.microsoft onnx op domain.

[ONNX] Add imports for Gelu, BiasGelu

---

tests/scripts/task_lint.sh

This was erroneously added in #10895
cc @areusch

[skip ci][ci] Remove inplace flag from black script

---

docker/Dockerfile.ci_hexagon
docker/Dockerfile.ci_i386
docker/Dockerfile.ci_wasm
docker/install/ubuntu_install_rust.sh
tests/scripts/git_skip_ci_globs.py

These just need sccache installed and available on the `PATH` to start using it in CI
cc @areusch

[ci] Add sccache to remaining Docker images

---

docker/Dockerfile.demo_android
docker/install/ubuntu_install_python.sh

+ remove useless directives in install script
This PR solves issue #10221

use ubuntu18 in docker android demo 

---

Jenkinsfile
jenkins/Jenkinsfile.j2

[Hot Fix][Jenkinsfile]Fix Hexagon Parameter

---

Jenkinsfile
jenkins/Jenkinsfile.j2

cc @areusch @driazati @leandron

[CI]Update Hexagon Docker Image to v0.03

---

CONTRIBUTORS.md

Please join us to welcome @guberti as a new reviewer to TVM. Gavin has made contributions to microTVM, including Arduino support and improvements for effective microTVM testing.
- [Commits History](https://github.com/apache/tvm/commits?author=guberti)
- [Code Review]( https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:guberti)

[COMMUNITY] @guberti -> Reviewer

---

CONTRIBUTORS.md

Please join us to welcome @yzh119 as a new reviewer to TVM. Zihao has made contributions to microTVM, including TIR, TensorCore mma support.
[Commits History](https://github.com/apache/tvm/commits?author=yzh119)
[Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Ayzh119+)

[COMMUNITY] @yzh119 -> Reviewer

---

.asf.yaml

- This is to help with work on things like the merge bot and issue triage.
@tqchen @leandron @kparzysz-quic @comaniac @driazati

Add driazati to triagers

---

src/relay/transforms/inline_composites.cc

Minor refactoring on the `inline_composites` pass which undoes the output of the `merge_composites` pass. 
This PR removed the call-graph representation and simplifies checks on `kComposite` and `kCompiler` attrs.
This can be tested with:
```
python3 -m pytest -rP /home/mpapadimitriou/OctoML/tvm/tests/python/relay/test_pass_inline_composites.py
```
@mbs-octoml @mbaret @masahi

[Relay] Refactor inline_composites pass

---

Jenkinsfile
jenkins/Jenkinsfile.j2

Closes #10984
cc @areusch @driazati @gromero @leandron

[CI] Update CI Images to include `pytest-lazy-fixture`

---

.asf.yaml

- Havisha has offered to help with maintaining some of the roadmaps.
@tqchen @leandron @kparzysz-quic @comaniac @hpanda-naut

Add Havisha to triagers

---

CONTRIBUTORS.md

Please join us to welcome @wrongtest as a new committer to TVM. The contributor has contributed to TensorIR schedule primitives, arithmetic analysis and TVMScripts.
- [Commits History](https://github.com/apache/tvm/commits?author=wrongtest)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:wrongtest)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/wrongtest/summary)

[COMMUNITY] @wrongtest -> Committer

---

src/tir/schedule/primitive/reduction.cc
tests/python/unittest/test_tir_schedule_rfactor.py

[BugFix][TIR] Fix rfactor when RF block becomes spatial

---

src/tir/schedule/primitive/compute_inline.cc
tests/python/unittest/test_tir_schedule_compute_inline.py

[BugFix][TIR] Error check: Inline Block with Init Stmt

---

python/tvm/relay/frontend/paddlepaddle.py

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread. @jiangjiajun

[Frontend][Paddle] Fix pool2d op

---

tests/python/frontend/oneflow/test_forward.py

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3089/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11055/1/pipeline
Broken by https://github.com/apache/tvm/pull/11052
@leandron @Mousius @driazati

[skip ci] Hotfix CI (black check not caught by PR CI)

---

CONTRIBUTORS.md

Add ekalda to reviewers

---

Jenkinsfile
jenkins/Jenkinsfile.j2

This is the same as `GPU` so this consolidates on that to simplify reporting
Related PRs:
* https://github.com/tlc-pack/tlcpack/pull/110
* https://github.com/tlc-pack/ci-terraform/pull/17
cc @areusch

[ci] Remove TensorCore node name

---

src/tir/transforms/compact_buffer_region.cc
src/tir/transforms/storage_rewrite.cc
tests/python/unittest/test_tir_transform_compact_buffer_region.py
tests/python/unittest/test_tir_transform_storage_rewrite.py

Refer to the issue in https://github.com/apache/tvm/issues/10831#issuecomment-1086287433

[TIR] Add two possible missing visit to let stmt

---

src/runtime/opencl/texture_pool.cc

Previously, the size of the memory which should be allocated was
calculated as multiplication width on height. It doesn't work well in
case when one texture has big size in height and the next one big size
in width. We tried to reuse the allocated memory and every time when
the next texture with big size was used we reallocated the previous
one. It has huge impact on the performance.
Now we check two dimensions independently. So, in this case we will
check both dimensions and it helps us to avoid the situation with
cyclic memory reallocation.

[OpenCL Textures] Fix memory management in texture pool

---

NEWS.md
python/tvm/relay/frontend/oneflow.py
python/tvm/script/parser.py

convert full-width characters to half-width characters.

convert full-width characters to half-width characters

---

tests/python/frontend/onnx/test_forward.py

This has failed on `main`: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3068/tests

[onnx] Relax tolerance for qlinearleakyrelu test

---

docs/reference/publications.rst

This PR updates some publications that use or built on top of TVM.
@apache/tvm-committers

[docs] Update publication list

---

Jenkinsfile
jenkins/Jenkinsfile.j2

* This allows folks to retrigger Jenkins runs through the Jenkins UI
rather than requiring the author to push an empty or amended commit.
@Mousius @driazati

Include BUILD_NUMBER in rebuilt docker image

---

python/tvm/meta_schedule/relay_integration.py
python/tvm/meta_schedule/tune.py

[MetaSchedule] Allow optional params to be None

---

apps/hexagon_launcher/CMakeLists.txt
apps/hexagon_launcher/cmake/HexagonLauncher.cmake
apps/hexagon_launcher/cmake/hexagon/CMakeLists.txt
apps/hexagon_launcher/launcher_hexagon.cc

Enable USE_CUSTOM_LOGGING for Hexagon Launcher

---

Jenkinsfile
jenkins/Jenkinsfile.j2

Requested in https://github.com/apache/tvm/pull/11156
Validated in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/257/pipeline

[CI] Update GPU image to use newer CMake

---

src/relay/quantize/realize.cc
src/relay/quantize/realize.h

Closes https://github.com/apache/tvm/issues/11092

[Relay] Create header file for realize.cc

---

apps/microtvm/reference-vm/base-box-tool.py
apps/microtvm/reference-vm/zephyr/provision_setup.sh
docker/Dockerfile.ci_cpu
docker/Dockerfile.ci_qemu
docker/install/ubuntu_install_cmsis.sh
docker/install/ubuntu_install_ethosu_driver_stack.sh

This PR refactors CMSIS installation from other scripts to add it to Zephyr RVM box.
cc @gromero

[docker][RVM][microtvm] Refactor CMSIS installation to add to RVM

---

src/runtime/hexagon/hexagon_device_api.cc

This PR changes `CopyDataFromTo` to use buffer sources instead of device type.
This code was originally written by @csullivan!

[Hexagon] Remove device type dependency from DeviceAPI CopyDataFromTo

---

CONTRIBUTORS.md

Please join us to welcome @altanh as a new reviewer to TVM. Altan has made contributions to relay language.
- [Commits History](https://github.com/apache/tvm/commits?author=altanh)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:altanh)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/altanh/summary)

[COMMUNITY] Altan Haan -> Reviewers

---

docker/Dockerfile.ci_wasm

Looks like I missed this one in #11162 due to missing the cpptest call in the Jenkinsfile 🙀 
cc @areusch @driazati

[CI] Update GoogleTest in ci_wasm

---

python/tvm/relay/op/contrib/cmsisnn.py
tests/python/contrib/test_cmsisnn/test_pooling.py

This ensures that CMSIS-NN is only used when the batch size and layout are correct for the library calls.

[CMSIS-NN] Increase partitioning accuracy for pooling

---

src/relay/backend/contrib/ethosn/codegen.cc
src/relay/backend/contrib/ethosn/ethosn_api.cc

Minor issues in corner cases from static analysis and a code standard
violation fix.
@lhutton1

[ETHOSN] Minor corner case fixes

---

python/tvm/contrib/hexagon/build.py
tests/python/contrib/test_hexagon/test_models.py

This test will not run on simulator because it takes a long time but we can run it on physical hardware.

[Hexagon] Add mobilenet test with AOT

---

docker/Dockerfile.ci_lint

This is needed to verify the Jenkinsfile in the `ci_lint` image

[ci][docker] Add Jinja2 to image

---

tests/python/relay/aot/test_crt_aot_usmp.py

This PR fixes missing assert in usmp tests.
cc @manupa-arm

[USMP] Fix assert condition for TVMBackendAllocWorkspace

---

python/tvm/relay/op/contrib/ethosn.py
src/relay/backend/contrib/ethosn/codegen.cc
src/relay/backend/contrib/ethosn/codegen_ethosn.h
src/relay/backend/contrib/ethosn/ethosn_api.cc
src/relay/backend/contrib/ethosn/ethosn_api.h
tests/python/contrib/test_ethosn/test_leaky_relu.py

[ETHOSN] Adding support for Leaky ReLU

---

tests/scripts/ci.py

This allows users to specify what Docker image they want to use manually (i.e. for debugging if a user has built their own image)
cc @areusch

[ci] Add --docker-image option to ci.py

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Fixes https://github.com/apache/tvm/issues/11264
cc: @masahi

fix expand onnx conversion

---

tests/python/frontend/paddlepaddle/test_forward.py

This pull request will fix the problem reported by https://github.com/apache/tvm/issues/11251

[Frontend] [Paddle] fix testing problem

---

gallery/tutorial/autotvm_relay_x86.py

The runtime on this one varies a lot, so this tries adding a seed to get it consistent
cc @areusch

[ci][docs] Seed autotvm tutorial

---

src/relay/transforms/fold_explicit_padding.cc
tests/python/relay/test_pass_fold_explicit_padding.py

This commit adds the following:
Do not fold `nn.pad` and `qnn.conv2d` if padding value is not
equal to input zero point of qnn operation. Added unit test
to check such behaviour.

Consider pad value and input zero point in FoldExplicitPading

---

docker/Dockerfile.ci_hexagon

[Hexagon][Docker]Add HEXAGON_SDK_ROOT ENV variable

---

Jenkinsfile
jenkins/Jenkinsfile.j2

Updates ci_cpu and ci_qemu to pull in #11273
cc @areusch @ashutosh-arm @driazati @leandron

[CI] Update Docker images for new CMSIS-NN

---

src/runtime/graph_executor/graph_executor.cc

DLTensor's byte_offset is very meaningful, it should not be forgotten in ZeroCopy function.
Please review @masahi

[Runtime]Considering DLTensor's byte_offset in ZeroCopy function

---

python/tvm/relay/frontend/paddlepaddle.py
tests/python/frontend/paddlepaddle/test_forward.py

[Frontend] [PaddlePaddle] Add split operator

---

include/tvm/tir/builtin.h
src/target/source/codegen_cuda.cc
src/target/source/ptx.cc
src/target/source/ptx.h
src/tir/op/builtin.cc
tests/python/unittest/test_tir_ptx_cp_async.py

See https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-cp-async-wait-group
More configurable options can be considered, but this is a good start.
@junrushao1994 @vinx13 @Hzfengsy @yzh119

[PTX] Intrinsics for async copy from global to shared (SM80)

---

tests/python/frontend/onnx/test_forward.py

See #11375
cc @Mousius @altanh @areusch

[ci] Disable flaky quantized onnx tests

---

Jenkinsfile
jenkins/Jenkinsfile.j2
jenkins/macros.j2

[ci][easy] Fix parameters for macros

---

rust/tvm/src/ir/relay/attrs/nn.rs

With help from @gussmith23 
@masahi

[RUST] Add Conv3D Rust bindings

---

Jenkinsfile
jenkins/Jenkinsfile.j2

Requested in https://github.com/apache/tvm/pull/11140 and https://github.com/apache/tvm/pull/11346
Validated in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/259/pipeline/
@areusch @driazati @leandron @Mousius @yangulei @t-vi

[CI] Update CPU and GPU image

---

python/tvm/meta_schedule/space_generator/schedule_fn.py

Fix typo in typing of space generator

---

tests/scripts/task_ci_setup.sh
tests/scripts/task_clean.sh
tests/scripts/task_config_build_arm.sh
tests/scripts/task_config_build_cpu.sh
tests/scripts/task_config_build_gpu.sh
tests/scripts/task_config_build_gpu_other.sh
tests/scripts/task_config_build_gpu_vulkan.sh
tests/scripts/task_config_build_hexagon.sh
tests/scripts/task_config_build_i386.sh
tests/scripts/task_config_build_qemu.sh
tests/scripts/task_config_build_wasm.sh
tests/scripts/task_convert_scripts_to_python.sh
tests/scripts/task_golang.sh
tests/scripts/task_java_unittest.sh
tests/scripts/task_mypy.sh
tests/scripts/task_python_arm_compute_library.sh
tests/scripts/task_python_docs.sh
tests/scripts/task_python_ethosn_tests.sh
tests/scripts/task_python_frontend_cpu.sh
tests/scripts/task_python_hexagon.sh
tests/scripts/task_python_integration_gpuonly.sh
tests/scripts/task_python_integration_i386only.sh
tests/scripts/task_python_microtvm.sh
tests/scripts/task_python_nightly.sh
tests/scripts/task_python_topi.sh
tests/scripts/task_python_vta_fsim.sh
tests/scripts/task_python_vta_tsim.sh
tests/scripts/task_rust.sh
tests/scripts/task_show_node_info.sh

[ci] Add -x to all CI scripts

---

tests/python/unittest/test_auto_scheduler_evolutionary_search.py

[skip ci][ci][AutoScheduler] Disable flaky test_mutate_parallel test

---

tests/python/frontend/paddlepaddle/test_forward.py

[skip ci][ci][paddle] Disable flaky test_forward_group_norm

---

tests/python/contrib/test_hexagon/test_autotvm.py

Test is currently disabled. See issue: [11396](https://github.com/apache/tvm/issues/11396)
cc @mehrdadh

[Hexagon] Minimal example demonstrating how to tune.

---

include/tvm/relay/attrs/nn.h
rust/tvm/src/ir/relay/attrs/nn.rs

[RUST] Add conv3d transpose Rust bindings

---

tests/python/unittest/test_arith_solve_linear_inequality.py

[skip ci][ci] Disable `test_solution_consistency`

---

src/printer/tvmscript_printer.cc
tests/python/unittest/test_tvmscript_error_report.py

Fix structural error reporting on root block

---

include/tvm/topi/nn/softmax.h
include/tvm/topi/transform.h
src/meta_schedule/utils.h

Some if-else statements were missing braces. They have been added as per our style guide.
Surprisingly cpplint does not find these. I did a rough grep to find all instances but some could have fallen through the cracks.
@masahi @AndrewZhaoLuo

[FIX] Add braces to if-else statements

---

tests/python/frontend/paddlepaddle/test_forward.py

Solve the problem:
https://github.com/apache/tvm/issues/11435
@jiangjiajun  @driazati  @masahi

[Frontend] [PaddlePaddle] group_norm adjusts test accuracy

---

CONTRIBUTORS.md

Please join us to welcome @driazati as a new committer to TVM. He has contributes lots of improvements to our CI, build and general automation that are instrumental for us to serve our growing community.
- [Commits History](https://github.com/apache/tvm/commits?author=driazati)
- [Code Review]( https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:driazati) 
- [Community Forum Summary]( https://discuss.tvm.apache.org/u/driazati/summary) 
Congratulations @driazati!

[COMMUNITY] David Riazati -> Committer

---

tests/python/ci/test_ci.py
tests/scripts/github_tag_teams.py

This improves the parsing to avoid issues like in #11454

[ci] Add filter to teams

---

src/tir/transforms/flatten_buffer.cc
tests/python/unittest/test_tir_transform_flatten_buffer.py

This PR fixes an existing bug in TIR lowering where the TIR below triggers an error:
```python
@T.prim_func
def func(a: T.Buffer[10, "bool"], b: T.Buffer[10, "bool"]) -> None:
T.func_attr({"global_symbol": "main", "tir.noalias": True})
for i in T.serial(10):
with T.block("b"):
vi = T.axis.spatial(10, i)
b[vi] = a[vi]
tvm.build(func, target="llvm")
```
The error message is:
```
File "/root/Projects/tvm-dev/src/tir/transforms/flatten_buffer.cc", line 173
TVMError:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
Check failed: store->buffer->dtype == DataType::Int(8) (bool vs. int8) : Expected …
```

[Bugfix][TIR] Handle boolean tensor properly in Flatten-Buffer

---

tests/python/contrib/test_dnnl.py

Regular run of integration tests on MacOS (and Windows I guess) lead to fail. 
Unconditional access to Linux specific file lead to crash.
Let's wrap it to system check. Windows is not covered at this moment.
Merging of "x86 cpuid" support from this https://github.com/apache/tvm/pull/11505 will simplify ISA check.

Restore integration test on Mac and Windows

---

python/tvm/autotvm/tuner/xgboost_cost_model.py
python/tvm/testing/autotvm.py
tests/python/unittest/test_autotvm_xgboost_model.py

I'm hitting this issue when tuning `dense_pack.x86`.
@tqchen @merrymercy

[FIX] Pad feature vectors to the same size in xgboost cost model

---

python/tvm/relay/op/strategy/hexagon.py

[Hexagon] Register strategy for concatenate

---

python/tvm/tir/__init__.py
python/tvm/tir/op.py

[TIR] Expose tir.call_cpacked in python

---

docs/README.md

Fix incorrect commands in docs/readme.md.

[CI][DOC] Fix incorrect commands in docs/readme.md

---

src/meta_schedule/postproc/rewrite_tensorize.cc

Schedule primitives may cause module or prim func to be modified during `sch->Replace`. It is unsafe to iterate the functions in the module and call schedule primitives at the same time. This PR refactored `RewriteTensorize` to decompose it into two parts: find the blocks to rewrite first, and then do the actual rewrite.
cc @masahi @junrushao1994

[MetaSchedule] Refactor RewriteTensorize to prevent concurrent map updates

---

gallery/how_to/deploy_models/deploy_sparse.py
gallery/how_to/extend_tvm/bring_your_own_datatypes.py
gallery/how_to/extend_tvm/low_level_custom_pass.py
gallery/how_to/extend_tvm/use_pass_infra.py
gallery/how_to/extend_tvm/use_pass_instrument.py
gallery/how_to/optimize_operators/opt_conv_cuda.py
gallery/how_to/optimize_operators/opt_conv_tensorcore.py
gallery/how_to/optimize_operators/opt_gemm.py
gallery/how_to/tune_with_autotvm/tune_conv2d_cuda.py
gallery/how_to/work_with_relay/build_gcn.py
gallery/how_to/work_with_relay/using_relay_viz.py
gallery/how_to/work_with_schedules/extern_op.py
gallery/how_to/work_with_schedules/intrin_math.py
gallery/how_to/work_with_schedules/scan.py
gallery/tutorial/auto_scheduler_matmul_x86.py
gallery/tutorial/autotvm_matmul_x86.py
gallery/tutorial/intro_topi.py
gallery/tutorial/tensor_expr_get_started.py
gallery/tutorial/tensor_ir_blitz_course.py

I've been trying to update myself on the changes and happened to fix some spelling errors and link corrections across docs.
cc @areusch

[docs] Various content corrections

---

CONTRIBUTORS.md

Please join us to welcome @vvchernov as a new reviewer to TVM.
He made contributions to improve support for LSTMs and speech synthesis models like Tacotron2 in TVM. In addition he’s made improvements to the Relay Virtual Machine to reduce input/output copy overheads.
- [Commits History](https://github.com/apache/tvm/commits?author=vvchernov)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Avvchernov)

[COMMUNITY] Valery Chernov -> Reviewers

---

CONTRIBUTORS.md

Please join us to welcome @apeskov as a new reviewer to TVM.
Alexander has contributed to the BNNS BYOC backend, and iOS support, and has ongoing work on improving DNNL support via BYOC.
- [Commits History](https://github.com/apache/tvm/commits?author=apeskov)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Aapeskov)

[COMMUNITY] Alexander Peskov -> Reviewers

---

apps/microtvm/poetry.lock
apps/microtvm/pyproject.toml
apps/microtvm/reference-vm/arduino/provision_setup.sh
apps/microtvm/reference-vm/zephyr/provision_setup.sh

[microtvm] Add mxnet importer and update pyyaml to fix poetry error

---

python/tvm/target/target.py

Fix typos and shorten the warning statement in dnnl target.

[DNNL][Target] Fix typos in target warn of dnnl

---

python/tvm/meta_schedule/runner/rpc_runner.py
src/meta_schedule/extracted_task.cc
tests/python/unittest/test_meta_schedule_integration.py

Previously only static shape computation is allowed in our tuning
system. However, one special case is overlooked: the reduction iter vars
could still have dynamic iteration domains which depend on other data
parallel vars. This PR rules out this case by carefully checking all the
loop extents during task extraction.
Related issue: https://github.com/apache/tvm/issues/11746.

[Bugfix][MetaSchedule] Filter out dynamic extents

---

docker/install/ubuntu_install_python.sh

[skip ci] Fix CI break due to concurrent merge.

---

apps/microtvm/reference-vm/arduino/README.md
apps/microtvm/reference-vm/arduino/Vagrantfile

[skip ci][microTVM] Update Arduino RVM name and box version

---

docker/clear-stale-images.sh
docs/contribute/pull_request.rst

This utility can be used to clear stale docker images from your local machine. Would love any feedback here!
@driazati @junrushao1994 @mbs-octoml @Mousius @mehrdadh

[skip ci] Add tool to clear stale images

---

apps/microtvm/reference-vm/base-box-tool.py
apps/microtvm/reference-vm/base_box_setup_common.sh

[microTVM][RVM] Fix RVM build due to #11470

---

Jenkinsfile
jenkins/Jenkinsfile.j2

Requested by https://github.com/apache/tvm/issues/11774
Validated in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/260/
@huajsj 

[CI] Update GPU image to add DNNL

---

include/tvm/relay/attrs/transform.h
include/tvm/topi/transform.h
python/tvm/relay/op/_transform.py
src/relay/op/make_op.h
src/relay/op/tensor/transform.cc

This is part of our effort to support layout rewrite on meta schedule.

[TOPI][Relay] New Op: MetaScheduleLayoutRewrite

---

python/tvm/relay/frontend/onnx.py
python/tvm/relay/op/_transform.py
tests/python/frontend/onnx/test_forward.py

As title. Adds in the identity shape func for scatter_nd, and updates the Eyelike importer tests. 
cc @sfvaroglu @MargaretQian

[ONNX] Add more dynamism to Eyelike

---

src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc

[microTVM][CMSIS] Sort functions in codegen

---

tests/python/ci/test_ci.py
tests/scripts/github_docs_comment.py

This PR fixes the docs bot comment message. 
@driazati 

[CI] Amend docs bot comment

---

python/tvm/auto_scheduler/relay_integration.py
python/tvm/topi/cuda/conv2d_winograd.py
python/tvm/topi/nn/batch_matmul.py
python/tvm/topi/nn/conv2d.py
python/tvm/topi/nn/conv3d.py
python/tvm/topi/nn/dense.py
src/auto_scheduler/compute_dag.cc

This is part of our effort to support layout rewrite on Meta Schedule.

[TOPI] Layout Rewriting in TE

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

This PR intends to add `aten::glu` ops in the PyTorch frontend.
@masahi @junrushao1994 @zxybazh

[Relay][PyTorch] Add aten::glu

---

include/tvm/meta_schedule/arg_info.h
python/tvm/meta_schedule/arg_info.py
src/meta_schedule/arg_info.cc
src/meta_schedule/database/database.cc
src/meta_schedule/search_strategy/evolutionary_search.cc
src/meta_schedule/search_strategy/replay_func.cc
src/meta_schedule/search_strategy/replay_trace.cc

This is part of our effort to support layout rewrite on Meta Schedule.

[MetaSchedule] Introduce ArgInfo::FromEntryFunc

---

src/target/tag.cc

[Target] Add a few AWS C5 instances in target tag system

---

apps/microtvm/reference-vm/arduino/Vagrantfile
apps/microtvm/reference-vm/zephyr/Vagrantfile

[microTVM] Update RVM versions because of LLVM update due to #11808

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

This PR intends to add `aten::maximum` and `aten::minimum` in the PyTorch frontend.
@masahi @junrushao1994 @zxybazh

[Relay] [Pytorch] Add aten::maximum and aten::minimum

---

src/relay/op/nn/nn.cc
tests/python/relay/test_pass_convert_op_layout.py

Add instance norm infer_layout.

[relay][pass]add instance infer layout

---

docker/install/ubuntu_install_python_package.sh

This integrates the fixes from https://github.com/tlc-pack/tlcpack-sphinx-addon/pull/7

[docs] Update tlcpack-sphinx-addon

---

python/tvm/meta_schedule/builder/local_builder.py
python/tvm/meta_schedule/cost_model/xgb_model.py
python/tvm/meta_schedule/relay_integration.py
python/tvm/meta_schedule/testing/tune_te.py
python/tvm/meta_schedule/tune_context.py
python/tvm/relay/backend/te_compiler.py
src/meta_schedule/schedule_rule/winograd.cc

[MetaSchedule] Misc minor fix

---

python/tvm/relay/op/strategy/adreno.py
python/tvm/topi/adreno/conv2d_winograd_common.py

[OpenCL] Change winograd priority and extend split

---

tests/python/ci/test_ci.py
tests/scripts/cmd_utils.py
tests/scripts/git_skip_ci.py
tests/scripts/github_tag_teams.py

[ci] Allow skip tag anywhere in PR title

---

python/tvm/topi/x86/concat.py
tests/python/relay/test_op_level1.py

Concatenation corner case fix.

---

tests/python/ci/test_ci.py
tests/scripts/git_utils.py
tests/scripts/github_docs_comment.py

This PR improves the docs bot to edit a previous comment instead of making new comments.
Fixes #11837
@driazati @areusch

Docs bot now edits previous comments

---

python/tvm/contrib/hexagon/build.py

When a subprocess completes with a non-zero exit code, include
its stdout and stderr text in the Python exception's error message.
cc @mehrdadh

[testing][hexagon] Better subproc errors

---

python/tvm/relay/testing/yolo_detection.py
src/relay/op/tensor/transform.cc

Hi, I have two typo fixes that help improve the debugging experience.
@rkimball  for the ReshapeRel ICHECK
@huajsj for the testing/yolo_detection bbox info outputting

typo fixes

---

tests/python/contrib/test_ethosn/infrastructure.py

Keeps the tests in parity with the partition_for_ function so any changes are reflected in the tests.
cc @Leo-arm @manupa-arm

[ETHOSN] Use partition_for_ function when running tests

---

python/tvm/testing/utils.py

[tests] Fix changed var name from 'target_str' to 'target_names', NFC

---

src/tir/transforms/narrow_datatype.cc
tests/python/unittest/test_tir_transform_narrow_datatype.py

Hi, there. This change to `NarrowDataType` pass want to also narrow down int types in index conditions like in buffer indices.
Eg, `T.Int64(1) < i:int64 * T.int64(3)`  => `1 < i:int32 * 3`

[TIR] Add missing narrow down of index within conditions

---

src/meta_schedule/schedule_rule/auto_inline.cc
tests/python/unittest/test_meta_schedule_schedule_rule_auto_inline.py

Previously, Auto-Inline on CPU will only inline according to strict
conditions, for example, ordered index mapping. This is generally good
practice to do so, but on the other hand, there is no much benefit to
stop inlining only due to some restrictive conditions for pure spatial
subgraphs. By doing so, we also save some search trials on pure spatial
subgraphs so that more can be allocated to more important ones.

[MetaSchedule] Enhance AutoInline for Spatial Task

---

CONTRIBUTORS.md

Please join us to welcome @jinhongyii as a new reviewer to TVM. He has mainly contributed to MetsSchedule core infra developments and TIR improvements.
- [Commits History](https://github.com/apache/tvm/commits?author=jinhongyii)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:jinhongyii)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/jinhongyii/summary)

[COMMUNITY] Hongyi Jin -> Reviewer

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

This PR intends to add `aten::randn` for the pytorch frontned.
cc: @masahi

[PyTorch] add aten::randn

---

src/arith/iter_affine_map.cc
tests/python/unittest/test_arith_iter_affine_map.py

cc @spectrometerHBH @junrushao1994

[Arith] Allow constant values in InverseAffineIterMap

---

tests/python/contrib/test_ethosu/test_partition.py

Follow up for #11469.
cc @Mousius

[microNPU] Test averge pool partitioning

---

docs/install/from_source.rst
python/gen_requirements.py

This PR is related to issue #12009  
About this PR:
Publish an XGBoost version notice in doc & set up tutorial.

[Docs] Add xgboost version restriction

---

python/tvm/script/parser.py

Fix node.func to node.funcs on parser.py

---

python/tvm/relay/frontend/qnn_torch.py

[QNN] Replace nn.leaky_relu with qnn.leaky_relu

---

python/tvm/relay/op/strategy/cuda.py

[Relay, Op] Add conv2d generic layout op strategy when meta schedule is enabled

---

python/tvm/meta_schedule/testing/te_workload.py
tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py
tests/python/unittest/test_tir_schedule_analysis.py
tests/python/unittest/test_tir_transform_inject_software_pipeline.py

[MetaSchedule, Testing] Generalize in/out dtype of testing te workloads

---

src/target/llvm/llvm_module.cc

LLVMModule has two members that refer to llvm::Module:
1. llvm::Module* mptr_, and
2. std::unique_ptr\<llvm::Module\> module_.
The mptr_ member is always valid and it points to the llvm::Module. The unique pointer takes care of the ownership of the llvm::Module, and deletes it when no longer needed. However, once JIT is initialized, it takes over the ownership of the llvm::Module, and the module_ member becomes null.
To avoid checks for null, use the raw pointer whenever accessing the llvm::Module, and only use the unique_ptr as the owner/deleter.
The member names are changes to reflect their roles:
- module_ -> module_owning_ptr_
- mptr_   -> module_

[LLVM] Clarify the status of pointers to llvm::Module in LLVMModule

---

python/tvm/tir/schedule/schedule.py

Fix a document error reported in https://discuss.tvm.apache.org/t/cant-get-tir-tensorize-working-with-the-provided-example/13175
cc @vinx13

[skip ci][TIR][Schedule] fix tensorize example

---

python/tvm/relay/op/contrib/dnnl.py
src/runtime/contrib/dnnl/dnnl_json_runtime.cc
tests/python/contrib/test_dnnl.py
tests/python/relay/test_pass_partition_graph.py

1. Fuse `nn.pad()->nn.avg_pool2d()`, which may be encountered in inception_v3. Test case is included.
2. Support `Global_average_pooling`. The related test_cases are provided.

[BYOC-DNNL] suppport more dnnl ops

---

tests/python/contrib/test_hexagon/pytest_util.py

Provide mechanism to let unit tests initialize
input tensors with sequential element values.
Useful for debugging.
cc @mehrdadh

[hexagon][testing] sequential input tensors

---

docker/bash.sh

cc @areusch 
https://github.com/apache/tvm/issues/11952
cc @Mousius @driazati

[CI][docker] Add comment

---

.github/workflows/main.yml

[skip ci][ci] Skip broken android_rpc failures

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

[Relay][PyTorch] Add aten::lerp

---

tests/python/relay/test_conv2d_nhwc_texture.py

[Adreno] Update conv2d_nhwc test to use winograd

---

python/tvm/topi/hexagon/slice_ops/__init__.py
python/tvm/topi/hexagon/slice_ops/dwconv2d.py
tests/python/contrib/test_hexagon/topi/test_dwconv2d_slice.py

Slice Op for depthwise conv2d
cc @mehrdadh

[TOPI][HEXAGON] Implement depthwise conv2d slice op.

---

docker/install/ubuntu_install_zephyr.sh

[ci] Reinstall junintparser after zephyr deps

---

src/auto_scheduler/search_policy/sketch_policy.cc

[AutoSchedule] Fix misusage of an already-moved object

---

python/tvm/script/printer/doc_core.py

This single-file PR is automatically generated by a script that describes the Doc AST.

[TVMScript] Doc Definition

---

src/meta_schedule/postproc/rewrite_parallel_vectorize_unroll.cc
src/tir/analysis/estimate_flops.cc
tests/python/unittest/test_tir_analysis_estimate_tir_flops.py

Add flops for the right hand side of let statements to the total flops.
@junrushao1994 @Hzfengsy

[FIX,TIR] Handle LetStmt in EstimateTIRFLops

---

python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

I have no idea what I was thinking when I wrote that function....

[Fq2i][ fix output type on fq2i binary ops with constant inputs

---

Jenkinsfile
ci/jenkins/Jenkinsfile.j2

This includes a fix to `tlcpack-sphinx-addon` to fix broken card links

[ci][docker] Update GPU image

---

Jenkinsfile
ci/jenkins/Test.groovy.j2

This PR shards the QEMU python tests
Fixes #12180
@mehrdadh @driazati @areusch 
cc @Mousius

[CI] Shard Qemu python tests

---

python/tvm/meta_schedule/testing/tlcbench.py
src/meta_schedule/schedule_rule/multi_level_tiling_with_intrin.cc
src/tir/schedule/analysis.h
src/tir/schedule/analysis/analysis.cc
src/tir/schedule/ir_comparator.cc
tests/python/integration/test_meta_schedule_auto_tensorize.py
tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py

[MetaSchedule] Check auto tensorization applicability in MultiLevelTilingWithIntrin

---

python/tvm/relay/op/strategy/arm_cpu.py
python/tvm/topi/arm_cpu/dense.py

[microTVM]Fix dense_dsp schedule in autotuning

---

Jenkinsfile
ci/jenkins/Deploy.groovy.j2
ci/jenkins/DockerBuild.groovy.j2
ci/jenkins/Jenkinsfile.j2
ci/jenkins/Prepare.groovy.j2
ci/jenkins/generate.py

This was previously broken since it wouldn't pick up the new images names and there was an errant `'` floating around

[ci][docker] Fix deploy to tlcpackstaging on Docker Hub

---

src/relay/qnn/op/batch_matmul.cc
tests/python/relay/test_op_qnn_batch_matmul.py

The previous version incorrectly broadcasted across the batch dimensions which led to type errors.
I have updated tests to handle multi batch examples and updated the documentation to note the transposed nature of the operator.

[QNN] Fix multi batch matmuls

---

Jenkinsfile
ci/jenkins/Prepare.groovy.j2

[ci][docker] Add retries for docker pull

---

python/tvm/tir/schedule/_type_checker.py
python/tvm/tir/schedule/schedule.py
src/tir/schedule/concrete_schedule.cc
src/tir/schedule/instruction_traits.h
src/tir/schedule/trace.cc
tests/python/unittest/test_tir_schedule_utilities.py
tests/python/unittest/test_type_annotation_checker.py

Allow  `s.annotate(loop_rv, pragma_key, {"cfg0":  1, "cfg1": 2, ...})` .

[TIR][Schedule] Support annotate dict typed value

---

CONTRIBUTORS.md

Please join us to welcome @shingjan as a new reviewer to TVM. Yuanjing contributes a lot in Meta Scheduler, TVMScript, and TVM frontend, particularly to improve pytorch to relay conversion.
- [Commits History](https://github.com/apache/tvm/commits?author=shingjan)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:shingjan)

[COMMUNITY] Yuanjing Shi -> Reviewer

---

include/tvm/node/functor.h

fixed typos in include/tvm/node/functor.h

[Node] fix typos in include/tvm/node/functor.h

---

python/tvm/meta_schedule/default_config.py
python/tvm/tir/tensor_intrin/cuda.py

cc @AndrewZhaoLuo @gigiblender @masahi

[TIR] Add int8 CUDA tensor core intrinsics

---

python/tvm/tir/tensor_intrin/arm_cpu.py
python/tvm/tir/tensor_intrin/x86.py

@junrushao1994 @vinx13 
cc @gigiblender

[TIR] Minor fix to tensor intrin description

---

Jenkinsfile
ci/jenkins/Prepare.groovy.j2
ci/jenkins/macros.j2

Missed an existing one of these when merging #12306

[ci] De-duplicate retry functions

---

Jenkinsfile

Timing of merges resulted in the Jenkinsfile being out of sync
cc @areusch @driazati @gigiblender

[skip ci] [CI] Re-generate Jenkinsfile

---

python/tvm/relay/op/contrib/dnnl.py
tests/python/relay/test_pass_partition_graph.py

This PR add test case in `test_pass_partition_graph`, to ensure the `sum pattern` really works.

[BYOC-DNNL] add partition test on sum pattern

---

Jenkinsfile

This got out of date after merging #12178

[skip ci][ci] Fix Jenkinsfile

---

include/tvm/tir/function.h
python/tvm/tir/function.py
src/tir/ir/function.cc

cc @junrushao1994 @spectrometerHBH @tqchen @vinx13

[TIR][UX] allow override when register TensorIntrin

---

apps/microtvm/poetry.lock
apps/microtvm/pyproject.toml
tests/scripts/git_skip_ci_globs.py

[skip ci][microTVM] Add pytest-xdist to pyproject.toml

---

CONTRIBUTORS.md

Please join me in welcoming Adam Straw (@adstraw) as a new reviewer in TVM.  Adam has made significant contributions to the Hexagon backend, including DMA support, threading, on-target testing, and others.
[Commit history](https://github.com/apache/tvm/commits?author=adstraw)
[Code reviews](https://github.com/apache/tvm/pulls?q=reviewed-by:adstraw)

[COMMUNITY] Adam Straw -> Reviewer

---

CONTRIBUTORS.md

[COMMUNITY] [skip ci] MichaelJKlaiber -> reviewer

---

CONTRIBUTORS.md

Please join me in welcoming An Wang (@anwang2009) as a new reviewer in TVM. An has made significant contributions various TVM frontends and help the community.
- [Commits History](https://github.com/apache/tvm/commits?author=anwang2009)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:anwang2009)

[COMMUNITY] An Wang -> Reviewer

---

python/tvm/micro/testing/evaluation.py

This PR exposes the project options for autotuning jobs and allows users to select options such as stack size.
cc: @mehrdadh , @guberti 
cc @alanmacd @gromero

[MicroTVM] expose project options in autotuning

---

tests/python/contrib/test_arm_compute_lib/test_network.py

In Keras 2.7, one "reshape" operator was removed from
the Mobilenet model, making our test which verifies the
number of operators to be incorrect.
This patch adjusts the operator count so that it is in line
with the changes in Keras. For reference, the change in
keras repo was done in hash b6abfaed132 "Remove
unnecessary reshape layer in MobileNet architecture".
cc @lhutton1 @NicolaLancellotti @ashutosh-arm @areusch

[ACL] Adjust mobilenet test for Keras 2.9

---

CONTRIBUTORS.md

Please join me in welcoming Noah Kontur (@konturn) as a new reviewer in TVM. Noah contributes in TVM infrastructure[1] repositories is being a key contributor in making our CI reproducible/scriptable.
[1] https://github.com/tlc-pack/ci/pulls?q=+is%3Apr+author%3Akonturn

[COMMUNITY] @konturn -> Reviewer

---

src/relay/backend/contrib/ethosn/ethosn_api.cc
tests/python/contrib/test_ethosn/test_requantize.py

Fixes a small issue when converting the output information to the support library API. The `requantize_info` output datatype needed updating with the output datatype from the relay function to ensure the graph is compiled correctly by the support library. Included a test to prevent regression in the future.
cc @NicolaLancellotti @leandron

[ETHOSN] Fix requantize output conversion

---

src/relay/backend/contrib/ethosn/ethosn_api.cc
tests/python/contrib/test_ethosn/test_reshape.py

This pr adds support for the special indices values of the reshape operator for the Arm(R) Ethos(TM)-N NPU.
cc @lhutton1

[ETHOSN] Add support for special indices of Reshape

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

[PyTorch][Fix] Fix for numerically unstable logsigmoid

---

docker/Dockerfile.ci_hexagon

Needed for https://github.com/apache/tvm/pull/12587
@mehrdadh 

[CI] Install xgboost in Hexagon image

---

CONTRIBUTORS.md

Please join us to welcome Wuwei Lin (@vinx13) as a new PMC member.
Wuwei has been actively leading and contributing to the design and implementation of several components of the project in the community, including but not limited to,
- MetaSchedule
- Arithmetic analysis in TIR
- AutoTVM
- Quantization on Relay
- TOPI and performance improvement
In addition, Wuwei has been very actively participating in the design
discussion and sharing his ideas in the forum. He has also been
actively managing the PRs and issues.
* [Commits History](https://github.com/apache/tvm/commits?author=vinx13)
* [Code Review](https://github.com/apache/tvm/issues?q=reviewed-by+%40vinx13)
* [Community Forum Summary](https://discuss.tvm.apache.org/u/vinx13/summary)

[skip ci][Community] Wuwei Lin -> PMC

---

src/relay/transforms/simplify_expr.cc
tests/python/relay/test_pass_simplify_expr.py

[SimplifyExpr] Add simplify for dq->arg funcs

---

ci/jenkins/generate.py

The timestamp in the Jenkinsfile is there to prevent post-merge
conflicts from different PRs that edit the templates merging
non-sequentially. This is not an issue when a line is edited in place
though, which is often the case when Docker image tags are updated. This
PR makes it so the timestamp is not updated in these cases which should
reduce merge conflicts on these types of PRs.

[ci] Don't update Jenkinsfile timestamp on image updates

---

CONTRIBUTORS.md

Please join me in welcoming Yaxing Cai (@cyx-6) as a new reviewer in TVM. Yaxing has brought the PackedFunc into TVM object system ([RFC-051](https://github.com/apache/tvm-rfcs/pull/51)), designed and implemented the new parser infrastructure for TVMScript and meta-programming ([RFC-079](https://github.com/apache/tvm-rfcs/pull/79))
- [Commits History](https://github.com/apache/tvm/commits?author=cyx-6)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Acyx-6+)

[skip ci][COMMUNITY] Yaxing Cai -> Reviewer

---

python/tvm/relay/frontend/pytorch.py

This PR intends to fix operator `aten::arange` in the pytorch frontend. Note that this behavior of `aten::arange` only occurs in pytorch nightly >= 20220815. Also adding this change won't break the backward compatibility with pytorch version < nightly 20220815.
Models impacted by this change: `hf_Reformer` & `hf_GPT2`
cc: @masahi

[PyTorch] Fix aten::arange for pytorch

---

tests/python/contrib/test_ethosn/infrastructure.py
tests/python/contrib/test_ethosn/test_convert_equivalents.py
tests/python/contrib/test_ethosn/test_networks.py
tests/python/contrib/test_ethosn/test_reshape.py

Fixing a few more pylint issues caught when using pylint==2.9.3 locally.
cc @leandron @Liastu01 @NicolaLancellotti

[ETHOSN] Fix some more pylint issues

---

CONTRIBUTORS.md

Adding Elen to committer
cc @ekalda @tmoreau89 @leandron

[COMMUNITY] ekalda -> Committer

---

include/tvm/topi/elemwise.h

support false-positive fast math

---

.github/workflows/upload_ci_resource.yml
tests/scripts/request_hook/request_hook.py

Addresses this CI failure on `main`:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4235/pipeline/

[ci] Add onnx model to S3

---

src/tir/schedule/transform.cc
tests/python/unittest/test_tir_schedule_set_axis_separator.py

Prior to this commit, `ReplaceBufferMutator` only checks `BufferRegionNode::buffer` to determine if a `BufferRegion` needs to be replaced, and doesn't check the `BufferRegionNode::region`.  As a result, updating `T.reads(A[B[i]])` would fail to replace `B`.
This commit checks `BufferRegionNode::region` for buffer usage to resolve this issue.

[TIR] Update region min/extent in ReplaceBufferMutator

---

CONTRIBUTORS.md

Please join us to welcome Josh Fromm (@jwfromm) as a new PMC member.
Josh has been continuously working on operator support and robustness across the whole TVM stack (frontend, relay, auto scheduler).
In addition, Josh has been very actively participating in the design discussion and sharing his ideas. He has also been actively managing and reviewing the PRs and issues.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=jwfromm)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ajwfromm)
- [Community Forum Summary](https://discuss.tvm.ai/u/jwfromm/summary)

[COMMUNITY] Josh Fromm -> PMC

---

python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

[FQ2I] Quantized constant bias

---

ci/scripts/ping_reviewers.py
tests/python/ci/test_ci.py

This has been working fine for a while, this code opens it up so it's
not limited to the authors in #9983.

[ci] Remove author check from ping bot

---

include/tvm/runtime/logging.h

Fix typo in doc of logging

---

src/tir/schedule/state.cc
tests/python/unittest/test_tir_schedule_state_cached_flags.py

Added extra simplify step to eliminate false negative cases.
cc @Hzfengsy @junrushao @junrushao1994 @wrongtest-intellif

[TIR] Add extra simpliciation in region cover analysis

---

Jenkinsfile
ci/jenkins/Prepare.groovy.j2

These were broken due to this missing guard:
https://ci.tlcpack.ai/job/docker-images-ci/job/docker-image-run-tests/223/console
cc @Mousius @areusch @gigiblender @leandron

[ci][docker] Fix nightly Docker tests

---

python/tvm/contrib/hexagon/build.py
python/tvm/contrib/hexagon/pytest_plugin.py

This PR adds an pytest argument for keeping the test directories after test finishes.
cc @nverke @janetsc @jverma-quic

[Hexagon] Add debug option to hexagon pytest

---

src/tir/transforms/remove_no_op.cc
tests/python/unittest/test_tir_transform_remove_no_op.py

When after partition cascade ops, we sometimes meet some unused loops because their extents are negative. 
This PR enhance RemoveNoOp pass to remove these unused loop.
cc @Hzfengsy

[TIR] Enhance RemoveNoOp pass to remove negative loop

---

.github/workflows/pr_comment_bot.yml

Addresses #12859 
cc @masahi @driazati @leandron

Allow failures in pr_comment_bot for now

---

include/tvm/tir/stmt_functor.h
src/relay/transforms/annotate_texture_storage.cc
src/script/printer/doc.cc
src/tir/schedule/primitive/pad_einsum.cc

Fix clang warnings

---

tests/scripts/release/gather_prs.py

It appears the path has changed to the python github utils so I have refactored things.
cc @driazati @areusch

[EZ][Release] Update gather PRs Script

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Hi, tvm:
Sorry,there is another operator `aten::zero_`  just discovered that needs to be reviewed.

[frontend][pytorch]support aten::zero_ operator

---

src/tir/schedule/primitive/get_block_loop.cc
tests/python/unittest/test_tir_schedule_utilities.py

[TIR] Fix GetProducer/Consumer for duplicating dep edges

---

src/tir/schedule/primitive/cache_read_write.cc
tests/python/unittest/test_tir_schedule_reindex.py

cc @spectrometerHBH @junrushao

[TIR] Fix int64 dtype mismatch in Reindex

---

src/target/source/codegen_opencl.cc

Sample API compatibility for OpenCL version 3.0

[CODEGEN][OPENCL] Compatibility for OpenCL version 3.0

---

src/support/libinfo.cc

[Support] Add fallback definition of ccache in libinfo

---

src/runtime/hexagon/rpc/android/session.cc

Change the `NULL` to `nullptr`.

[Hexagon] Change NULL to nullptr, NFC

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/ci-problem.md
.github/ISSUE_TEMPLATE/flaky-test.md

Reduced word count in "About" section to under 200 characters 
cc: @areusch

[skip ci] Edits to the Bug & Flaky test Issue templates to reduce word count

---

src/tir/transforms/texture_flatten.cc

One line change which extends error message.

[Textures] Improve error reporting

---

src/printer/relay_text_printer.cc

Add string before doc, slow. Add string after doc, fast

[Relay] optimize dumpir time

---

Jenkinsfile
ci/jenkins/Build.groovy.j2
ci/jenkins/macros.j2

This uses templating for the build steps and fixes a few instances of
missing skip markers and timeout wrappers. This also adds a retry to
JUnit S3 uploads which was missing before.

[ci] Template build steps

---

docs/dev/how_to/debugging_tvm.rst

[Doc] Fix the typo in the debugging doc

---

docs/contribute/release_process.rst

Add a step to bump the version numbers on main. 
cc @driazati @areusch

[Docs] Update Release Process Docs -- Add Ver. Bump Step

---

src/relay/transforms/simplify_expr.cc
tests/python/relay/aot/test_crt_aot_usmp.py
tests/python/relay/test_pass_simplify_expr.py

Fixed #13048 
cc @AndrewZhaoLuo @ganler

[Relay] Fix simplifying consecutive casts when intermediate type has fewer bits

---

apps/pt_tvmdsoop/tests/test_as_torch.py
python/tvm/contrib/torch/as_torch.py
python/tvm/contrib/torch/optimize_torch.py
python/tvm/meta_schedule/__init__.py

This PR intends to fix import issues of the contrib torch lib and add warning.
cc: @masahi @yelite

[Torch] Fix torch contrib issues

---

python/tvm/ir/expr.py
python/tvm/script/tir/scope_handler.py
tests/python/unittest/test_tvmscript_syntax_sugar.py

This fixed dtype mismatch between loop begin and end when begin is not specified.
cc @junrushao @cyx-6 @Hzfengsy

[TVMScript] Fix parsing int64 loop with optional loop start

---

python/tvm/relay/op/strategy/hexagon.py

This PR registers fast softmax schedule for hexagon using the default schedule.
Also renames some schedule names to hexagon.
cc @csullivan

[Hexagon]Register fast softmax schedule with default schedule

---

src/node/structural_equal.cc

This fixed usage of pointer to local variable `tracing_data`.
cc @masahi

[Node] Fix structural equal path tracing pointer usage

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/ci-problem.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-tracking.md
.github/ISSUE_TEMPLATE/flaky-test.md

Issue Tracking RFC - https://github.com/apache/tvm/issues/12801
cc: @areusch

[skip ci] Added label tags links to the wiki page in issue templates to align with Issue Tracking RFC

---

src/runtime/hexagon/hexagon_device_api.cc
src/runtime/hexagon/hexagon_vtcm_pool.cc
tests/cpp-runtime/hexagon/hexagon_vtcm_pool_tests.cc

Quick bugfix and clarification for runtime buffers

[Hexagon] [runtime] VTCM bugfix, runtime buffer clarification

---

CONTRIBUTORS.md

Welcoming @quic-sanirudh as a reviewer!
@tqchen @tmoreau89

quic-sanirudh -> Reviewer

---

docs/contribute/release_process.rst

[Docs] Add instructions on downloads page updating on release process

---

CONTRIBUTORS.md

Add Florin Blanaru to the list of reviewers.

[skip ci][COMMUNITY] gigiblender -> Reviewer

---

docker/install/ubuntu_install_onnx.sh

Following the discussion in the thread [[frontend][pytorch] TVM compatibility with Torch 1.12.0](https://discuss.tvm.apache.org/t/frontend-pytorch-tvm-compatibility-with-torch-1-12-0/13508) try to update PyTorch to 1.12.0 and TorchVision to 0.13.0.

Update Pytorch to version 1.12.0 and TorchVision to 0.13.0

---

.asf.yaml

these two volunteered to help triage issues per [Issue Triage RFC](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0093_Issue_Triage.md).
@tqchen @driazati

[skip ci] Add Janet and Thomas to triagers to help with Issue Triage RFC

---

tests/python/frontend/onnx/test_forward.py

Remove assert to fix onnx frontent unit tests for PyTorch 1.12

---

src/runtime/hexagon/hexagon_htp.cc
src/runtime/hexagon/hexagon_htp.h
src/runtime/hexagon/hexagon_thread_manager.cc
src/runtime/hexagon/hexagon_thread_manager.h

Clarify naming for the tensor processing unit that will be power managed and acquired/released for the runtime
cc:  @csullivan, @kparzysz-quic

[Hexagon] [runtime] Clarify compute resources

---

tests/python/relay/test_pipeline_executor.py

Fix typo in test_pipeline_executor.py

---

python/tvm/topi/transform.py
tests/python/relay/test_op_level3.py

Fixes: https://github.com/apache/tvm/issues/13029
cc @masahi @jwfromm @junrushao

[Relay] fix: trilu check op for i64/i32

---

python/tvm/relay/frontend/onnx.py
python/tvm/relay/op/image/image.py
python/tvm/topi/image/grid_sample.py
src/relay/op/image/grid_sample.cc
tests/python/frontend/onnx/test_forward.py

This PR adds the GridSample operator introduced in [opset 16](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#gridsample-16) with a couple of small fixes in the mainline topi version.
@sfvaroglu @AndrewZhaoLuo

[Relay][Frontend][ONNX] Add GridSample operator

---

.github/workflows/main.yml

[ci] Temporarily disable MacOS RPC tests

---

Jenkinsfile
ci/jenkins/Jenkinsfile.j2

This updates the images to include #13183

[ci] Update Docker images

---

python/tvm/contrib/hexagon/pytest_plugin.py

This PR fix a bug with port assignment in hexagon tests.

[Hexagon] Fix port range bug and add random.seed

---

docs/install/nnpack.rst

Fixes typo in NNPACK documentation @tqchen @mbaret @mbrookhart

typo in 'build' NNPACK

---

Jenkinsfile
ci/jenkins/Build.groovy.j2

fixes #12777
@driazati @areusch

fix GPU other build

---

Jenkinsfile
ci/jenkins/Build.groovy.j2

This reverts commit e9e8c4b263aa33bfd6bd54151a4bc7eb89da8deb.

[skip ci] Revert "fix GPU other build (#13235)"

---

python/tvm/relay/frontend/tensorflow2.py

This PR Imports `graph_def` to default graph before calling `function_def_to_graph_def()`.
It is needed for `function_def_to_graph_def(func, inshape)` which is called inside `from_tensorflow(graph_def)`.
The `func` might have a reference(s) by name to another function(s) in the graph_def functions library. Internally `function_def_to_graph_def()` checks if another function is actually a function using [graph._is_function(fname)](https://github.com/tensorflow/tensorflow/blob/v2.9.0/tensorflow/python/framework/function_def_to_graph.py#L141)
We need to import `graph_def` to the default context / graph before calling `function_def_to_graph_def()`. Otherwise we might face errors such as the following
```
File "/Users/pivovaa/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/fun …
```

[Frontend][Tensorflow2] Import graph_def to default graph before calling function_def_to_graph_def

---

tests/python/unittest/test_tir_schedule_transform_layout.py

Add a unit test for dynamic parameters being used as part of a layout transformation.

[TIR] Added unit test for dynamic parameter in layout transform

---

include/tvm/relay/attrs/nn.h
python/tvm/topi/nn/dense.py
src/relay/op/nn/nn.h
tests/python/relay/test_op_level1.py

Unify the two inner dimensions in the type checker so if one is unknown it will be filled in.
@michalpiszczek @AndrewZhaoLuo

[FIX] Handle matmul where one inner dimension is unknown

---

src/relay/op/tensor/reduce.cc
tests/python/relay/test_op_level4.py

Due to the maximum value of FP16 being quite low (65536), it's very common to be unable to express large reductions using it. This occurs most commonly in simple operators like `mean` and `var`, where the sum of elements is used as a divisor. Given that the actual complexity of those operators is quite low, it makes sense to just perform them in fp32 instead of fp16. This PR adds that casting and a few tests that previously would fail in FP16.

[Relay][Op] Add support for large index fp16 mean and var

---

cmake/modules/StandaloneCrt.cmake
src/runtime/crt/host/Makefile.template
src/runtime/crt/host/main.cc
src/runtime/crt/host/microtvm_api_server.py
tests/lint/check_file_type.py

This PR changes memory size to a project option so user can set it at compile time.

[microTVM][CRT] Add memory size as project option

---

src/tir/op/op.cc
tests/cpp/arith_simplify_test.cc

cc @junrushao @spectrometerHBH

[TIR] Allow folding cast with broadcast and ramp

---

python/tvm/relay/transform/transform.py

[Doc] Add desc of keep_orig_output_dtype for ToMixedPrecision

---

ci/jenkins/README.md

Update Jenkins readme to match new directory structure.

[ci] Update Jenkins readme to match new directory structure

---

python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

**This commit fixes the following issue:**
For the sequence of `qnn.dequantize -> avg_pool2d -> conv2d -> qnn.quantize` FQ2I pass inserts qnn.requantize (or cast) to int32 unconditionally before AvgPool2d. As a result fake quantized `qnn.conv2d` gets input as int32 dtype, but it is forbidden for `qnn.conv2d` (supports only uint8/int8/int16).
**This commit adds the following:**
Add cast back to input data type after AvgPool2d. This preserve input dtype == output dtype.

[FQ2I] Add cast back to input data type after AvgPool2d

---

python/tvm/topi/x86/dense_alter_op.py
tests/python/relay/test_op_level1.py
tests/python/relay/test_op_level10.py

This added padding to make the shape of dense/batch matmul compatible with VNNI instructions.

[TOPI] Add padding for dense/batch matmul for x86 vnni

---

docs/contribute/release_process.rst

This is mostly to address https://github.com/tlc-pack/tlcpack/issues/149
and make it clear how to avoid that in the future.

[docs] Add some more release process docs

---

src/tir/usmp/algo/hill_climb.cc

This PR relaxes the size check for the "initial" layout as the later permutations could lead to a winning combination.

[usmp] Hill Climb greedy layout size check relaxed

---

docker/install/ubuntu_install_ethosn_driver_stack.sh
docker/install/ubuntu_install_ethosu_driver_stack.sh
docker/install/ubuntu_install_papi.sh

The changes are listed below.
- avoid git checkout after git clone

[CI] Update minor git options

---

python/tvm/auto_scheduler/feature.py
python/tvm/utils/roofline/__init__.py
src/auto_scheduler/feature.cc

These features may occur for extern ops.

[Fix,Roofline] Handle zero length features in roofline

---

tests/python/relay/opencl_texture/test_network.py

This PR skips a flaky test to unblock CI on main.

[Hotfix] Skip Flaky Tests (Tracked in #13443)

---

docker/bash.sh

Adding privileged option.
cc @driazati

[Docker]Add privileged option for hardware with USB access testing

---

Jenkinsfile
ci/jenkins/Build.groovy.j2
ci/jenkins/Test.groovy.j2
tests/scripts/task_config_build_minimal.sh

[ci] Enable CRT tests for CPU minimal build

---

web/.gitignore
web/package-lock.json
web/package.json

This fixes the broken wasm build (e.g.
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4810/pipeline/)
and adds the `package-lock.json` file to the repo to avoid these kinds
of issues in the future.
Successful build: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-13505/2/pipeline/142

[skip ci][ci][wasm] Add package-lock.json to git

---

Jenkinsfile
ci/jenkins/Jenkinsfile.j2

[ci][docker] Update Docker image tags

---

src/relay/qnn/op/batch_matmul.cc

There is fix of [the issue](https://github.com/apache/tvm/issues/13467)
cc @ibsidorenko @apeskov

[QNN] support zero points as variable scalar for QnnBatchMatMul op

---

src/meta_schedule/postproc/verify_gpu_code.cc

Previously, the VerifyGPUCode post-processor uses hardcoded target `Target("cuda")` for applying pass LowerIntrin. This is a bit problematic since the actual target can be other GPU target (e.g., Metal). Therefore, this PR changes the hardcoded target to be the actual target.
cc @junrushao @masahi

[Fix] Use proper target in VerifyGPUCode

---

python/tvm/relay/op/contrib/dnnl.py
src/runtime/contrib/dnnl/dnnl_json_runtime.cc
tests/python/contrib/test_dnnl.py

This patch is to enable dense_bias_sum fusion and add its relevant unittest.

[DNNL][BYOC] enable dense_bias_sum fusion

---

CONTRIBUTORS.md

Please join us to welcome @multiverstack-intellif as a new reviewer to TVM. Min contributed key features in TIR scheduling, specifically, cache_read/write that are aware of cache location. These are huge improvements that are technically profound and helpful to the overall TVM stack. Therefore, it would be good to get more opportunities for him to participate more deeply in the community.
- [Commits History](https://github.com/apache/tvm/commits?author=multiverstack-intellif)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:multiverstack-intellif)

[COMMUNITY] Min Chen -> Reviewer

---

CONTRIBUTORS.md

Please join us to welcome @blackkker as a new reviewer to TVM. @blackkker contributed extensively across different layers of the system, including layout transform, PaddlePaddle, TFLite, and ONNX frontend.
- [Commits History](https://github.com/apache/tvm/commits?author=blackkker)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:blackkker)

[COMMUNITY] @blackkker -> Reviewer

---

src/runtime/graph_executor/debug/graph_executor_debug.cc
src/runtime/graph_executor/debug/graph_executor_debug.h

We want to inherit the GraphExecutorDebug class, so we add header file

Add header files for GraphExecutorDebug

---

ci/jenkins/docker-images.ini

This PR updates the ci_cortexm image.

[CI][microTVM]Update ci_cortexm image

---

ci/jenkins/generated/docker_jenkinsfile.groovy
ci/jenkins/templates/docker_jenkinsfile.groovy.j2
docker/Dockerfile.ci_cpu

This fixes the issue encountered in #13722. Tested in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-docker/detail/PR-13738/1/pipeline

[ci][docker] Make branch names valid before using them as tags

---

CONTRIBUTORS.md

Please join us to welcome @jinhongyii as a new committer to TVM. Hongyi has been contributing in great depth to many aspects in TVM, including TIR scheduling, MetaSchedule, TOPI, Relay, as well as runtime.
- [Commits History](https://github.com/apache/tvm/commits?author=jinhongyii)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:jinhongyii)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/jinhongyii/summary)

[COMMUNITY] Hongyi Jin -> Committer

---

CONTRIBUTORS.md

Please join me in welcoming Yaxing Cai (@cyx-6) as a new committer in TVM. He has made significant enhancements across the TVM stack by implementing the following RFCs:
- RFC 0051: Bring PackedFunc into TVM Object System
- RFC 0079: TVMScript Metaprogramming
His activities:
- [Commits History](https://github.com/apache/tvm/commits?author=cyx-6)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Acyx-6)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/cyx/summary)

[skip ci][COMMUNITY] Yaxing Cai -> Committer

---

tests/python/topi/python/test_topi_transform.py

https://github.com/apache/tvm/pull/13724 caused an issue in ci_cpu testing when running the TOPI tests. This pull request sets the failing test to require a gpu to run

[TOPI] Making test_strided_set require a GPU for testing

---

ci/scripts/github/github_tvmbot.py

[CI] Update rerun list for tvm-bot

---

CMakeLists.txt
include/tvm/relax/exec_builder.h
include/tvm/runtime/relax_vm/builtin.h
include/tvm/runtime/relax_vm/bytecode.h
include/tvm/runtime/relax_vm/executable.h
include/tvm/runtime/relax_vm/memory_manager.h
include/tvm/runtime/relax_vm/vm.h
python/tvm/relax/__init__.py
python/tvm/relax/_ffi_api.py
python/tvm/relax/exec_builder.py
python/tvm/relax/testing/vm.py
python/tvm/relax/vm.py
src/relax/backend/vm/exec_builder.cc
src/runtime/relax_vm/builtin.cc
src/runtime/relax_vm/bytecode.cc
src/runtime/relax_vm/executable.cc
src/runtime/relax_vm/memory_manager.cc
src/runtime/relax_vm/naive_allocator.h
src/runtime/relax_vm/pooled_allocator.h
src/runtime/relax_vm/vm.cc
tests/python/relax/test_vm_execbuilder.py

This PR implements a flexible register-based VM to execute relax programs with dynamic shape and control flow. Design: https://github.com/tlc-pack/relax/wiki/Relax-VM-Design.
Co-Authored-by: Ziheng Jiang <ziheng@apache.org>
Co-Authored-by: Yong Wu <yongcale@gmail.com>
Co-Authored-by: Steven S. Lyubomirsky <slyubomirsky@octoml.ai>
Co-Authored-by: Hongyi Jin <3231950289@qq.com>

[Unity] Relax VM

---

python/tvm/relax/testing/runtime_builtin.py
src/relax/backend/vm/codegen_vm.cc
src/relax/op/op.cc
src/relax/op/op_common.h
src/runtime/relax_vm/builtin.cc
tests/python/relax/test_runtime_builtin.py
tests/python/relax/test_tvmscript_printer_relax.py
tests/python/relax/test_vm_codegen_only.py

This PR introduces a codegen to generate Relax VM executable from a Relax IRModule.
Co-Authored-by: Altan Haan <altanh@cs.washington.edu>
Co-Authored-by: Andrew Liu <andrewlliu@gmail.com>
Co-Authored-by: Lesheng Jin <34279105+LeshengJin@users.noreply.github.com>
Co-Authored-by: masahi <masahi129@gmail.com>
Co-Authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
Co-Authored-by: Steven S. <Lyubomirsky slyubomirsky@octoml.ai>
Co-Authored-by: Yong Wu <yongcale@gmail.com>

[Unity] Relax VM codegen

---

include/tvm/relax/attrs/index.h
python/tvm/relax/op/index.py
python/tvm/relax/op/op_attrs.py
python/tvm/script/ir_builder/relax/ir.py
src/relax/op/tensor/index.cc
src/relax/op/tensor/index.h
tests/python/relax/test_op_index.py
tests/python/relax/test_tvmscript_parser_op_index.py

This PR is about the high-level tensor computation operators in Relax.
This PR includes the tensor indexing operators.

[Unity] Relax op: index

---

tests/python/unittest/test_te_schedule.py

make easier for user to understand how tensor_intrin works

Refactor test to make it easier for user to understand how tensor_intrin works

---

include/tvm/relax/analysis.h
python/tvm/relax/analysis/analysis.py
python/tvm/relax/ir/instrument.py
src/relax/analysis/well_formed.cc
tests/python/relax/conftest.py
tests/python/relax/test_analysis_well_formed.py

This PR implements relax wellformed analysis, which checks if the IRModule is well-formed. (tests and examples are added).
Co-Authored-by: Ruihang Lai [ruihangl@cs.cmu.edu](mailto:ruihangl@cs.cmu.edu)
Co-Authored-by: Siyuan Feng [Hzfengsy@sjtu.edu.cn](mailto:Hzfengsy@sjtu.edu.cn)
Co-Authored-by: Tianqi Chen [tianqi.tchen@gmail.com](mailto:tianqi.tchen@gmail.com)
Co-authored-by: Steven S. Lyubomirsky [slyubomirsky@gmail.com](mailto:slyubomirsky@gmail.com)
Co-authored-by: Yong Wu [yongcale@gmail.com](mailto:yongcale@gmail.com)
Co-Authored-by: Yuchen Jin [yuchenj@cs.washington.edu](mailto:yuchenj@cs.washington.edu)
Co-Authored-by: Yixin Dong <ubospica@gmail.com>
Co-Authored-by: Chaofan Lin <siriusneo@sjtu.edu.cn>
Co-Authored-by: Prakalp Srivastava …

[Unity][Pass] Wellformed Analysis

---

python/tvm/relax/__init__.py
python/tvm/relax/frontend/__init__.py
python/tvm/relax/frontend/torch/__init__.py
python/tvm/relax/frontend/torch/dynamo.py
python/tvm/relax/frontend/torch/fx_translator.py
python/tvm/relax/pipeline.py
tests/python/relax/test_frontend_dynamo.py
tests/python/relax/test_frontend_from_fx.py
tests/python/relax/test_pipeline.py

This PR introduces initial pytorch frontend components of Relax, including
- a FX translator that translates a Torch FX graph module to an TVM IRModule,
- a Relax-backend of Torch Dynamo, which brings the mechanism to build PyTorch model using Relax compilation pipeline,
- a pipeline prototype that contains the collection of pre-defined pipelines that optimizes and lower IRModule before passing to minimum build.

[Unity] Initial PyTorch Frontend

---

python/tvm/relay/frontend/paddlepaddle.py
tests/python/frontend/paddlepaddle/test_forward.py

Add norm op and one_hot_v2 op for paddlepaddle frontend.
@jiangjiajun 
@heliqi 
cc @junrushao

[Frontend][Paddle] Add norm and one_hot_v2 op 

---

python/tvm/ir/function.py
src/relax/transform/remove_unused_funcs.cc
src/relax/transform/utils.h
tests/python/relax/test_transform_remove_unused_funcs.py

This PR implements a pass to clean up unused functions. 
Co-authored-by: masahi <masahi129@gmail.com>

[Unity][Pass] Remove Unused Function

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

This PR introduces a flag `keep_params_as_input` in FX importer. When it is set, weights won't be imported as constant. They will be part of function inputs. The function is annotated with attribute `num_input` to indicate the number of non-weight inputs.
cc @tqchen @MasterJH5574 @spectrometerHBH

[Unity][Frontend] Annotate number of non-static input of FX function

---

cmake/modules/contrib/TensorRT.cmake
include/tvm/ir/module.h
include/tvm/relax/transform.h
python/tvm/ir/module.py
python/tvm/relax/transform/transform.py
src/ir/module.cc
src/relax/backend/contrib/codegen_json/codegen_json.h
src/relax/backend/contrib/tensorrt/codegen.cc
src/relax/backend/contrib/utils.h
src/relax/transform/run_codegen.cc
tests/python/relax/test_codegen_tensorrt.py
tests/python/relax/test_transform_codegen_pass.py

This PR introduces the fundamental workflow for BYOC and integrate TensorRT as a demonstration. 
Co-authored-by: Masahi [masahi129@gmail.com](mailto:masahi129@gmail.com)
Co-authored-by:  Yong Wu <yongcale@gmail.com>

[Unity][BYOC][Pass] RunCodegen and TensorRT 

---

CONTRIBUTORS.md

Please join me @mkatanbaf as a new Reviewer in TVM. Mohamad has contributed to tuning on microTVM and RTOS support. Mohamad also reviewed microTVM related patches, giving constructive feedback in that area.
- [Commits History](https://github.com/apache/tvm/commits?author=mkatanbaf)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:mkatanbaf)

[COMMUNITY] mkatanbaf -> Reviewer

---

src/relax/transform/merge_composite_functions.cc

Currently `MergeCompositeFunctions` will modify the map while iterating over it, and that makes tests/python/relax/test_transform_merge_composite_functions.py does not pass. This PR fixes this bug.
cc @masahi

[Unity][Fix] Fix bug in MergeCompositeFunctions

---

include/tvm/runtime/relax_vm/vm.h
python/tvm/contrib/tvmjs.py
python/tvm/exec/rpc_proxy.py
python/tvm/relax/vm_build.py
python/tvm/rpc/proxy.py
src/runtime/relax_vm/vm.cc
web/.gitignore
web/apps/browser/rpc_server.html
web/emcc/wasm_runtime.cc
web/src/rpc_server.ts
web/src/runtime.ts
web/tests/node/test_relax_vm.js
web/tests/python/prepare_test_libs.py
web/tests/python/relax_rpc_test.py
web/tests/python/webgpu_rpc_test.py
web/tests/python/websock_rpc_test.py

This PR brings initial relax vm support on web runtime

[Unity][WEB] Relax vm on web runtime

---

python/tvm/script/ir_builder/relax/ir.py
src/script/ir_builder/relax/ir.cc
tests/python/relax/test_tvmscript_ir_builder.py

Add R.emit_te, a requested support https://github.com/tlc-pack/relax/issues/197
cc: @psrivas2 @Hzfengsy @YuchenJin @tqchen

[Unity][TVMScript] emit_te sugar

---

CONTRIBUTORS.md

Please join me @chengven027-intellif as a new Reviewer in TVM. Cheng has contributed to ONNX/PyTorch frontend and Relay passes, making TVM support more input models.
- [Commits History](https://github.com/apache/tvm/pulls?q=author%3Achengven027-intellif+)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Achengven027-intellif+)

[COMMUNITY] Cheng Wen -> Reviewer

---

python/tvm/relay/op/contrib/tensorrt.py

[TRT][BYOC] allow strided_slice ops on selected dimensions (#14142)

---

gallery/how_to/work_with_microtvm/micro_tvmc.sh
python/tvm/driver/tvmc/model.py
python/tvm/driver/tvmc/runner.py
tests/micro/common/test_tvmc.py

This PR enables AoT Executor for tvmc micro compilation.

[microTVM]Enable TVMC micro with AoT Executor 

---

src/relay/transforms/eliminate_common_subexpr.cc
tests/python/relay/test_pass_eliminate_common_subexpr.py

If an argument of a call is a Tuple, we should check its fields.
Different tuples with the same fields should be treated as same inputs

[Relay] Enhance EliminateCommonSubexpr to support Tuple argument

---

python/tvm/tir/schedule/schedule.py

[TIR] Fix typo in doc

---

include/tvm/runtime/relax_vm/memory_manager.h
python/tvm/contrib/tvmjs.py
python/tvm/exec/rpc_proxy.py
src/runtime/relax_vm/memory_manager.cc
src/runtime/relax_vm/vm.cc
src/target/intrin_rule.cc
src/target/source/codegen_webgpu.cc
src/target/source/codegen_webgpu.h
tests/lint/check_file_type.py
web/apps/browser/rpc_plugin.html
web/apps/browser/rpc_server.html
web/emcc/wasm_runtime.cc
web/src/rpc_server.ts
web/src/runtime.ts
web/src/webgpu.ts

This PR makes various improvements web codegen in relax web runtime.
Correct support of shift operators.
Update relax vm to make most use of internal allocators. Update the webgpu API to the latest spec.

[Unity][WEBGPU] Codegen improvements and WebRuntime

---

src/relax/transform/lift_transform_params.cc
tests/python/relax/test_transform_lift_transform_params.py

Previously, the LiftTransformParams pass only works on function `"main"`. This is a bit restrictive as in our recent practice on stable diffusion, there are cases where multiple Relax functions inside an IRModule all need to be transformed.
Therefore, this PR enhances the LiftTransformParams pass, so that it will now transform **all** functions **with attribute `num_input`**. For functions without this attribute, the pass will simply skip them.

[Unity][Transform] LiftTransformParams handling multiple functions

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

This PR improves the torch FX translator in the following perspectives:
* support unary op `sigmoid` and `round`,
* support in-place `fill`, `triu` and `tril`,
* support `tensor`, `arange`, `empty`,
* support `bmm` (batch matrix multiplication),
* support `astype`,
* support `chunk` and `squeeze`.
This PR also fixes `Embedding`. Previously the translation assumes that the input to Embedding will only be 1-dimensional, and will throw exception when the input has more than one dimension (i.e., batched). This PR brings the support.

[Unity][Frontend] FX translator supporting more ops

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

This PR brings the support of translating `torch.baddbmm` into combination of operators (matmul, add, multiply). Unit tests are provided accordingly.
This PR also fixes the kwarg fetching issue of `torch.interpolate`.

[Unity][Frontend] FX translator support torch.baddbmm

---

python/tvm/contrib/cutlass/build.py
python/tvm/contrib/cutlass/gen_tensor_op.py
python/tvm/relax/backend/contrib/cutlass.py
tests/python/relax/test_codegen_cutlass.py

This PR enables matmul with dynamic shape to be offloaded to CUTLASS. This is useful for batch matmul with dynamic batch size. For example, (n, 50, 100) x (100, 50).
CC @vinx13 @masahi

[Unity][BYOC] Add dynamic shape support to CUTLASS matmul

---

python/tvm/_ffi/libinfo.py
python/tvm/contrib/tvmjs.py
src/target/source/codegen_webgpu.cc

This PR simplfies webgpu codegen according to spec and also PR adds utils to allow tvmjs to export runtime from a different TVM_HOME

[Unity][WEB] Simplify WebGPU Codegen per spec

---

src/relax/transform/fuse_ops.cc
tests/python/relax/test_transform_fuse_ops.py

This PR improves implementation of fuse-ops so it is more deterministic.

[Unity] Improve implementation of FuseOps

---

src/relax/analysis/detect_recursion.cc
tests/python/relax/test_analysis_detect_recursion.py

This PR fixes a small oversight in #14149. Namely, the analysis for detecting recursion in Relax adds all reference to global vars into the dependency graph, but some global vars might refer to TIR `PrimFunc`s. Those should not be in the dependency graph, and this PR ignores any that it detects.

[Unity][Bugfix] Do not include `PrimFunc`s in the dependency graph when checking for recursion

---

python/tvm/contrib/tvmjs.py
web/src/runtime.ts

This PR improves NDArray cache with param sharding

[Unity][WEB] Improve ndarray cache

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

This PR provides some quick fixes for fx_translator to import `tanh` and fix the error when importing `torch.nn.functional.layer_norm`.

[Unity][Frontend] Import `tanh` and fix `layer_norm`

---

include/tvm/runtime/relax_vm/vm.h
python/tvm/relax/__init__.py
python/tvm/relax/testing/lib_comparator.py
python/tvm/runtime/relax_vm.py
src/runtime/relax_vm/vm.cc
src/target/source/codegen_webgpu.cc
src/target/spirv/intrin_rule_spirv.cc
tests/python/relax/test_vm_instrument.py
web/apps/browser/rpc_server.html
web/src/rpc_server.ts
web/src/runtime.ts
web/src/webgpu.ts

This PR adds an instrumentation option to the relax VM. The instrument will be called before/after each call instruction if specified.
We also include a testing utility that leverages uses instrument. LibCompareVMInstrument leverages the instrument to compare implementations on another backend.
Also updated a few places in web runtime to improve debugging.

[Unity][DEBUG] Add Instrument

---

python/tvm/relay/frontend/paddlepaddle.py
tests/python/frontend/paddlepaddle/test_forward.py

Add conv3d for paddle frontend.
5 other ops in https://github.com/apache/tvm/pull/14277

[PaddlePaddle Hackathon 4][Frontend][Paddle]add conv3d for paddle frontend

---

src/relax/transform/to_mixed_precision.cc

Resolve CI error in unity branch.
cc: @spectrometerHBH @junrushao

[Unity][Lint] Fix cpplint casting

---

include/tvm/tir/function.h
src/relax/transform/meta_schedule.cc
src/tir/transforms/default_gpu_schedule.cc
tests/python/relax/test_transform_meta_schedule_tuning.py

This pr enhances introduces tir.is_scheduled to allow default schedule pass to skip some PrimFuncs.

[Unity][Transform] DefaultSchedule pass

---

tests/python/relax/test_transform_to_mixed_precision.py

Add test cases to test out_dtype="float16"
cc @masahi @junrushao

[Unity][Transform] AMP out_dtype=float16 testcases

---

tests/python/relax/test_transform_to_mixed_precision.py

[Unity][Transform] Fix AMP tests

---

CONTRIBUTORS.md

Please join me to welcome @janetsc as a new Reviewer in TVM. Janet has contributed to the Hexagon and AoT runtime. Janet also reviewed dozens of Hexagon related patches, giving constructive feedback in that area.
- [Commits History](https://github.com/apache/tvm/commits?author=janetsc)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:janetsc)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/janetsc/summary)

[COMMUNITY] janetsc -> Reviewer

---

src/runtime/relax_vm/vm.cc
web/apps/browser/rpc_server.html
web/emcc/webgpu_runtime.cc
web/src/rpc_server.ts
web/src/runtime.ts
web/src/webgpu.ts

This PR enables async pipeline creation in webgpu module loading. This will enable us to report progress in shader compilation and leverage multi-threading on the host to compile shaders.

[Unity][WEB] Support async pipeline creation

---

3rdparty/mlperftiny/api/submitter_implemented.h
tests/micro/common/test_mlperftiny.py

This PR adds test harness for mlperftiny submission using microTVM.

[microTVM]Add MLPerfTiny test harness 

---

ci/jenkins/docker-images.ini

Passing test: 
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-lint/detail/ci-docker-staging/12/pipeline
In https://github.com/apache/tvm/tree/ci-docker-staging

[CI][EZ] Upgrade CI Lint Image

---

tests/python/unittest/test_tir_schedule_read_write_at.py

Add unittest for schedule primitive `read_at` and `write_at`.

[TIR][Schedule] Add unittest for read_write_at

---

python/tvm/topi/hexagon/qnn/nn.py
tests/python/contrib/test_hexagon/test_wo_qnn_canonicalization.py

Support Relax Constants in the QNN TOPI operations. 
@csullivan

[Unity][QNN][Hexagon]Support Relax Constants in the QNN TOPI operations

---

src/runtime/relax_vm/vm.cc

This PR updated the relax vm profiler to also include shapes of constants show up in the 'Argument Shapes' column.
cc @masahi

[Unity] Include constant shapes in the profiler result

---

apps/microtvm/poetry.lock
apps/microtvm/pyproject.toml

This PR fixes security issues with packages.
https://github.com/apache/tvm/security/dependabot/245
https://github.com/apache/tvm/security/dependabot/244
https://github.com/apache/tvm/security/dependabot/200
https://github.com/apache/tvm/security/dependabot/192
https://github.com/apache/tvm/security/dependabot/176
https://github.com/apache/tvm/security/dependabot/114

[microTVM]Fix more security issues with pyproject

---

docker/install/ubuntu_download_arm_compute_lib_binaries.sh

Changelog can be seen at https://arm-software.github.io/ComputeLibrary/v23.02.1/
cc @lhutton1 @neildhickey for reviews

[CL] Update Compute Library from v22.11 to v23.02.1

---

python/tvm/topi/hexagon/qnn/nn.py

Everything is expected to be either te.Tensor, or a PrimExpr, so make sure that function parameters conform to that. Also, remove incorrect type annotations from `qnn_requantize`.

[Unity][Hexagon] Don't pass raw scalars in hexagon/qnn/nn.py

---

src/relax/transform/lift_transform_params.cc
tests/python/relax/test_transform_lift_transform_params.py

This PR ensures that the LiftTransformParams pass will not lift bindings that involve symbolic shape, because symbolic shape computation cannot be performed at compilation time.

[Unity] LiftTransformParams with symbolic shape robustness

---

python/tvm/contrib/tvmjs.py

currently dump_ndarray_cache first convert tvm.ndarray to numpy.array and take its dtype. As bfloat16 is not supported in numpy, the dtype will become uint16, which is wrong.
This PR fixes this behavior.
cc: @tqchen

[Unity] handle bf16 in dump_ndarray_cache and load_ndarray_cache

---

src/target/tag.cc

[Target] Add A10G gpu cuda tag

---

python/tvm/exec/rpc_proxy.py
python/tvm/rpc/proxy.py
src/target/source/codegen_webgpu.cc
web/src/runtime.ts
web/src/webgpu.ts
web/tests/python/webgpu_rpc_test.py

This PR adds POD argument support in webgpu.

[Unity] Enable pod args in WebGPU

---

CONTRIBUTORS.md

Please join me in welcoming Zihao Ye (@yzh119) as a new committer in TVM.
Zihao has made significant improvements on TensorIR, TVMScript and CUDA backends, Including but not limited to:
- Introduce new features and improve performance on the CUDA backend.
- Enable L2 cache flush during CUDA evaluation
- Robustify TensorIR schedule primitive
- Add new TensorIR primitive: `set_dtype`
Additionally, Zihao extend the TensorIR to the sparse area in his new work (https://arxiv.org/pdf/2207.04606.pdf), which is accepted by ASPLOS 2023. The RFC is here (https://github.com/apache/tvm-rfcs/pull/100).
His activities:
- [Commits History](https://github.com/apache/tvm/commits?author=yzh119)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Ayzh119)
- [Community Forum …

[skip ci][COMMUNITY] Zihao Ye -> Committer

---

src/relax/transform/fuse_tir.cc
tests/python/relax/test_transform_fuse_tir.py

This PR enhances the FuseTIR pass to support explicit symbolic shape inputs.
cc @tqchen @MasterJH5574 @jinhongyii

[Unity] Enhance Dynamic-aware FuseTIR

---

ci/jenkins/generated/docker_jenkinsfile.groovy
ci/jenkins/generated/gpu_jenkinsfile.groovy
ci/jenkins/templates/utils/macros.j2

change docker deploy to user regular on demand CPU

fix: deploy ci

---

tests/python/relax/test_e2e_op_dynamic.py

This PR removes code that should have been removed in previous PR https://github.com/apache/tvm/pull/14548. 
cc. @tqchen @masahi

[Unity][Bugfix] Resolve failure on `test_e2e_op_dynamic.py`

---

CONTRIBUTORS.md

Please join me to welcome Sunghyun Park (@sunggg) as a new Reviewer in TVM. Sunghyun Park has been actively improving Meta-schedule, TIR, and runtime. Also, he continuously gives talks, and tutorials growing the impact of the community.
- [Commits History](https://github.com/apache/tvm/commits?author=sunggg)
- [Code Review](https://github.com/apache/tvm/pulls?page=1&q=reviewed-by%3Asunggg)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/sunggg/summary)

[COMMUNITY] Sunghyun Park -> Reviewer

---

python/tvm/exec/rpc_proxy.py
src/runtime/relax_vm/builtin.cc
src/runtime/relax_vm/lm_support.cc
src/target/source/codegen_webgpu.cc
tests/python/relax/test_pipeline.py
tests/python/relax/test_runtime_builtin.py
web/emcc/wasm_runtime.cc
web/src/runtime.ts

This PR updates the specific builtins for LM
and move them to lm_support.cc
The kv_create now takes an initial data and copies it instead of consumes it. This will enable us to create kv within a VM more easily.

[Unity] Update specific builtins for LM

---

python/tvm/contrib/cutlass/gemm_operation.py
tests/python/relax/test_codegen_cutlass.py

Follow-up to https://github.com/apache/tvm/pull/14317 to support batched GEMM + residual block fusion.
@vinx13

[Unity][CUTLASS] Support batched matmul + residual fusion

---

ci/jenkins/unity_jenkinsfile.groovy

Try to update both the cpu and gpu images
cc: @driazati @tqchen

[Unity][CI] Update images to include jax deps

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

Upstreaming some changes from mlc side. Add supports for:
- `torch.nn.functional.cross_entropy`
- `torch.nn.CrossEntropyLoss`
- `torch.nn.AvgPool2d`
- `torch.nn.functional.avg_pool2d`
- `torch.nn.Identity`
- torch iadd
Mainly from these two PRs:
- https://github.com/mlc-ai/relax/pull/169
- https://github.com/mlc-ai/relax/pull/159
Co-authored-by: Yixin Dong <ubospica@gmail.com>

[Unity][Frontend] Some changes on the PyTorch FX Frontend

---

python/tvm/meta_schedule/relax_integration.py
src/relax/backend/task_extraction.cc
src/relax/transform/meta_schedule.cc
tests/python/relax/test_meta_schedule_relax_integration.py
tests/python/relax/test_relay_translator.py

Allow relax tuning use different hashing and equalities

[Unity][MetaSchedule] Add the module_equality param for tune_relax flow

---

tests/scripts/release/gather_prs.py

Fix release gather_pr.py of script about ghost users or blank PR nodes.
Hi @driazati, please have a review 😄

[test][script] Fix release gather_pr.py of script about ghost users or blank PR nodes

---

python/tvm/relax/testing/lib_comparator.py
src/support/ring_buffer.h

This PR improves and reduces possible memory leak
during lib comparator and rpc debug.

[Unity] Improve and reduces possible memory leak RPC debug

---

CONTRIBUTORS.md

Please join me to welcome Qiang Zhang (@Johnson9009) as a new Reviewer in TVM. Qiang has been contributing extensively in Relay, runtime, CI and tests.
- [Commits History](https://github.com/apache/tvm/commits?author=Johnson9009)
- [Code Review](https://github.com/apache/tvm/pulls?page=1&q=reviewed-by%3AJohnson9009)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Johnson9009/summary)

[Community] Qiang Zhang -> Reviewer

---

python/tvm/relax/__init__.py
python/tvm/relax/training/__init__.py
python/tvm/relax/training/optimizer.py
tests/python/relax/test_training_optimizer.py
tests/python/relax/test_training_optimizer_numeric.py

This PR adds the optimizer library to support the Relax training workflow.
Optimizer library generates relax functions representing common optimizers, such as SGD and Adam.
Taking SGD as an example, the optimizer function is like:
```
@R.function
def SGD(
params: R.Tuple(R.Tensor((3, 3), "float32"), R.Tensor((3,), "float32")),
gradients: R.Tuple(R.Tensor((3, 3), "float32"), R.Tensor((3,), "float32")),
optim_states: R.Tuple(R.Tensor((), "int64")),
) -> R.Tuple(
R.Tuple(R.Tensor((3, 3), "float32"), R.Tensor((3,), "float32")),
R.Tuple(R.Tensor((), "int64")),
):
num_steps: R.Tensor((), "int64") = optim_states[0]
num_steps_new: R.Tensor((), "int64") = R.add(num_steps, R.const(1, "int64"))
x: R.Tensor((3, 3), "float32") = params[0]
x_grad: R.Tensor((3, 3), "float32") = …
```

[Unity][Training] Optimizer library

---

src/relax/backend/contrib/cutlass/codegen.cc

I've hit a case where an invalid signature like this is generated:
```
void fused_relax_nn_conv2d_relax_add2_cutlass_(DLTensor* lv8, DLTensor* lv7, DLTensor* lv8, DLTensor* out0){
```
This happens because for some reasons different parameter `Var`s in the same function end up having the same `name_hint`.
I fixed this by generating a unique name for each parameter.
@cyx-6 @vinx13

[Unity][CUTLASS] Fix CUTLASS codegen for occasional variable name conflict

---

python/tvm/relay/frontend/pytorch.py

fix typo in new_full
cc @shingjan, @yelite

[Torch] fix typo in new_full

---

src/runtime/relax_vm/ndarray_cache_support.cc
tests/python/relax/test_runtime_builtin.py

This PR add a smart mode of param fetching that can pass in -1 and fetches all parameters with given prefix.

[Unity] Smart parameter fetching

---

web/src/runtime.ts

Based on a [comment](https://github.com/mlc-ai/web-llm/issues/57#issuecomment-1518639252) from @tqchen I've gone ahead and made a PR for my [suggestion/question](https://github.com/mlc-ai/web-llm/issues/57) of caching `ndarray-cache.json` before caching the shards. From my point of view this change means subsequent loads will pull 100% from CacheStorage, avoiding any external requests. Also I think this might make more sense because if your `ndarrayCacheUrl` is not pinned to a specific commit then it could perhaps become out of sync with the cached shards.

[Unity] Cache ndarray-cache.json

---

src/runtime/relax_vm/lm_support.cc

This PR makes the second argument of `vm.builtin.attention_kv_cache_view` optional, making it easier when debugging without the model config (i.e. when `num_attention_heads` and `head_dim` are unknown).

[Unity] Allow KVCache Access without Shape

---

python/tvm/contrib/cc.py
python/tvm/relax/vm_build.py

This PR add system lib build option to relax
also adds an util that creates an archived static
library in compilation

[Unity] Add system lib build option to relax

---

src/relax/transform/fuse_ops.cc
tests/python/relax/test_transform_fuse_ops_by_pattern.py

This PR makes CompositeFunctionAnnotator process all Relax functions rather than just the 'main' function. This enables running cutlass partitioning on LLaMA from web-llm.
cc @masahi @sunggg

[Unity] Process all Relax functions in CompositeFunctionAnnotator

---

ci/jenkins/unity_jenkinsfile.groovy
tests/scripts/task_config_build_cpu.sh
tests/scripts/task_config_build_gpu.sh

Use the newly upgraded images for unity

[Unity][CI] Use the upgraded images

---

ci/scripts/jenkins/s3.py

Fix for the doc deploy issue: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-gpu/detail/main/617/pipeline/535

[CI] fix doc deploy issue

---

python/tvm/_ffi/runtime_ctypes.py

This utility was useful during debugging that resulted in the changes made in https://github.com/apache/tvm/pull/14771, but is not otherwise related to that PR.

[Runtime] Added __str__ for tvm._ffi.runtime_ctypes.TVMArray

---

ci/jenkins/generated/arm_jenkinsfile.groovy
ci/jenkins/generated/cortexm_jenkinsfile.groovy
ci/jenkins/generated/cpu_jenkinsfile.groovy
ci/jenkins/generated/gpu_jenkinsfile.groovy
ci/jenkins/generated/hexagon_jenkinsfile.groovy
ci/jenkins/generated/i386_jenkinsfile.groovy
ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy
ci/jenkins/generated/minimal_jenkinsfile.groovy
ci/jenkins/generated/riscv_jenkinsfile.groovy
ci/jenkins/templates/utils/macros.j2

Spot instances for Arm is failing right now so we're going to go back to on demand.

fix: use arm on demand instead of spot

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

This pr is targeted to fix the bug in the [issue-14805](https://github.com/apache/tvm/issues/14805)
cc @echuraev @Hzfengsy

[Bugfix][Relay] Fix threshold calculation logic in PyTorch frontend

---

cmake/config.cmake

This PR is trying to fix issue #14810

[BUILD] Removed the duplicated MACROs in config.cmake

---

docs/conf.py

Add v0.12.0 docs

---

ci/jenkins/unity_jenkinsfile.groovy
tests/scripts/task_config_build_cpu.sh

I sent https://github.com/apache/tvm/pull/14848 before but it was a mistake, for unity I need to modify this file. 
cc @junrushao @tqchen

[Unity][CI] Update CPU image to install PyTorch (fix)

---

CONTRIBUTORS.md

Please join me in welcoming Anirudh Sundar Subramaniam (@quic-sanirudh) as a new committer in TVM. Anirudh has been focusing on many aspects of the TVM stack, including LLVM, TIR, Hexagon, TOPI. His activities:
- [Commits History](https://github.com/apache/tvm/commits?author=quic-sanirudh)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:quic-sanirudh)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/sanirudh/summary)

[COMMUNITY] Anirudh Sundar Subramaniam -> Committer

---

src/relax/analysis/tir_op_pattern_kind.cc
tests/python/relax/test_transform_annotate_tir_op_pattern.py

This PR enhances the OpPattern detector in Relax to support mixed-precision GEMMs and convolutions.

[Unity] Support Mixed-Precision FMA Pattern

---

tests/python/relax/test_codegen_cutlass.py

One test was broken in #14807. This PR fixes it.
cc @masahi

[Unity] Fix broken test in cutlass codegen

---

python/tvm/auto_scheduler/cost_model/xgb_model.py
python/tvm/auto_scheduler/dispatcher.py
python/tvm/auto_scheduler/feature.py
python/tvm/auto_scheduler/measure.py
python/tvm/auto_scheduler/search_policy.py
python/tvm/auto_scheduler/search_task.py
python/tvm/auto_scheduler/task_scheduler.py
python/tvm/auto_scheduler/utils.py
python/tvm/auto_scheduler/workload_registry.py
python/tvm/autotvm/feature.py
python/tvm/autotvm/graph_tuner/base_graph_tuner.py
python/tvm/autotvm/graph_tuner/pbqp_tuner.py
python/tvm/autotvm/graph_tuner/utils/traverse_graph.py
python/tvm/autotvm/measure/measure_methods.py
python/tvm/autotvm/record.py
python/tvm/autotvm/task/dispatcher.py
python/tvm/autotvm/task/space.py
python/tvm/autotvm/task/task.py
python/tvm/autotvm/testing/tune_relay.py
python/tvm/autotvm/tophub.py
python/tvm/autotvm/tuner/sa_model_optimizer.py
python/tvm/autotvm/tuner/xgboost_cost_model.py

[AutoTVM] Use f-strings for string formatting, NFC

---

web/emcc/wasm_runtime.cc
web/src/runtime.ts
web/tests/node/test_object.js

This PR enables string object in webruntime.

[Unity][WEB] Enable String object

---

web/src/webgpu.ts

This PR fix a type error of adapter requiredFeatures.
Sorry that the previous PR #14904 missed this fix.

[Unity][WebGPU] Fix WebGPU adapter requiring features

---

tests/python/frontend/keras/test_forward.py

[TestCases] fix unreachable test cases due to outside the for-loop

---

web/src/index.ts
web/src/runtime.ts

This PR consolidate and exposes the artifact
cache in the web runtime.

[Unity] Improve caching logic in webruntime

---

src/runtime/relax_vm/lm_support.cc

This PR adds API `vm.builtin.attention_kv_cache_update ` to support RWKV.

[Unity] support update KV cache

---

python/tvm/relax/transform/lazy_transform_params.py
tests/python/relax/test_transform_lazy_transform_params.py

Previously the pass LazyTransformParams did not take the case where an output variable is used by other bindings inside the function. It generates wrong Relax function in this case.
This PR fixes this issue. The new test case is an example to elaborate the issue. This PR introduces a sanity assertion check to ensure we handle the case properly.
This PR also enhances variable naming. For binding variables of `set_item` and `kill_object`, we now use an underscore ("`_`") as its name, compared with the previous `lv` name.

[Unity] Fix LazyTransformParams use-def analysis and binding emission

---

src/runtime/opencl/opencl_module.cc

Print error string if it is impossible to build kernel.
cc: @masahi

[OpenCL] Improve diagnostic message

---

tests/scripts/setup-adreno-env.sh
tests/scripts/task_python_adreno.sh

Target setup shouldn't conflict while multiple users on the same target device libc++_shared.so may not be available for some android devices from system

[DOCKER][ADRENO] Docker setup changes for multi user environments

---

python/tvm/relax/backend/contrib/cutlass.py

Fixed import error introduced in https://github.com/apache/tvm/pull/15001

[Unity] Fix importing tvm.contrib.cutlass

---

python/tvm/contrib/cutlass/conv2d_operation.py
python/tvm/contrib/cutlass/gemm_operation.py

Fixed some issues after merging main.
cc @tqchen

[Unity] Fix cutlass BYOC after merge

---

python/tvm/topi/nn/dense.py

Skip comparison of input and reduce dimensions in Dense on TOPI side for dynamic ones

[TOPI] Fix dynamic dimensions support for Dense on TOPI side

---

python/tvm/relay/frontend/onnx.py

Fix bug in scatter_elements op in ONNX front-end for early version of ONNX opset.

[ONNX] Fix bug in scatter_elements

---

src/ir/si_builder.cc

Fix for https://github.com/apache/tvm/pull/14574#issuecomment-1575335623
@junrushao

[Build] Fix missing virtual destructor in SIBuilder

---

src/tir/transforms/storage_rewrite.cc
tests/python/unittest/test_tir_transform_storage_rewrite.py

Allow `tir::DeclBuffer` to appear in the input of the `StorageRewrite` transform.  Any `DeclBuffer` whose backing allocation is rewritten are updated with the new buffer object.  Any `DeclBuffer` whose backing allocation is unused has been removed by `StorageRewrite` is itself removed.
This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.

[TIR] Handle DeclBuffer in StorageRewrite

---

python/tvm/ir/supply.py
python/tvm/relax/frontend/onnx/__init__.py
python/tvm/relax/frontend/onnx/onnx_frontend.py
tests/python/relax/test_frontend_onnx.py

This PR adds a direct ONNX to relax importer and test suite. It has decent out of the box coverage and has been tested for numerous end to end use cases. I hope this will be a valuable tool for the Unity community.
This work was done by several OctoML contributors including @zxybazh @gigiblender @mikepapadim and others.

[Unity][Frontend] Add relax onnx importer and tests

---

src/runtime/relax_vm/lm_support.cc

This PR optimizes sample top p from prob to reduce its running time to about 10x or more on M1. The main observation is that we don't need full sort and can just select top p based on a filtered cap.

[Unity] Optimize SampleTopPFromProb

---

python/tvm/relay/frontend/keras.py

Fix a wrong variable name in keras frontend

[Bugfix][Relay][Keras] Fix a wrong variable name in keras frontend

---

web/emcc/webgpu_runtime.cc

This PR hotfixes webgpu runtime after merging with main

[Unity] Hotfix webgpu runtime

---

src/relax/transform/rewrite_cuda_graph.cc
tests/python/relax/test_transform_rewrite_cuda_graph.py

This PR fixed some issues in cuda graph rewriting:
* vm builtins like kv cache operations shouldn't be captured
* fix variable collection in `IsStatic`

[Unity] Fix handling of vm builtins in cuda graph

---

docker/install/ubuntu_install_ethosu_driver_stack.sh

Updating the Arm(R) Ethos(TM)-U NPU drivers to version 23.05.

[microNPU][ETHOSU] Upgrade to 23.05 version of Arm(R) Ethos(TM)-U NPU drivers

---

src/arith/iter_affine_map.cc
src/target/source/codegen_c_host.h

This PR fixes serval compilation warnings with clang-15

[Minor] Fix Compilation Warnings

---

python/tvm/relax/transform/legalize_ops/manipulate.py
tests/python/relax/test_transform_legalize_ops_manipulate.py

This pr implements layout_transform legalization mentioned in https://discuss.tvm.apache.org/t/codegen-support-for-relax-layout-transform/15187.

[Unity] Legalization for LayoutTransform

---

python/tvm/dlight/__init__.py
python/tvm/dlight/base/__init__.py
python/tvm/dlight/base/analysis.py
python/tvm/dlight/base/common_schedules.py
python/tvm/dlight/gpu/__init__.py
python/tvm/dlight/gpu/decode_gemv.py
python/tvm/dlight/gpu/fallback.py
python/tvm/dlight/gpu/reduction.py
src/tir/schedule/analysis/analysis.cc
src/tir/schedule/primitive/compute_inline.cc
src/tir/schedule/transform.cc
tests/python/dlight/test_gpu_decode_gemv.py
tests/python/dlight/test_gpu_fallback.py
tests/python/dlight/test_gpu_reduction.py
tests/python/unittest/test_tir_schedule_compute_inline.py

This PR introduces a general rule for gemv-decode

[Unity][Dlight] general reduction rule for gemv-decode

---

python/tvm/dlight/base/analysis.py
python/tvm/dlight/base/transform.py
python/tvm/dlight/gpu/__init__.py
python/tvm/dlight/gpu/fallback.py
python/tvm/dlight/gpu/matmul.py
src/tir/schedule/primitive/layout_transformation.cc
tests/python/dlight/test_gpu_matmul.py

This PR introduces default schedule rules for matmul kernels. Note that we skip GEMV-liked kernels as it would be a separate rule.
cc @tqchen @junrushao @spectrometerHBH

[Unity][Dlight] Matmul Rules

---

python/tvm/dlight/gpu/reduction.py

Fix corner cases for dlight reduction

[Unity] Fix dlight reduction rule

---

src/runtime/relax_vm/lm_support.cc
web/src/runtime.ts

This PR brings the repetition penalty functions to the lm-support part of Relax VM. The repetition penalty function is invoked at LM sampling time and is inplace.
Co-authored-by: Zihao Ye <expye@outlook.com>

[VM] Add repetition penalty functions to Relax VM

---

python/tvm/contrib/ndk.py

[Android] ndk static build

---

ci/jenkins/generated/arm_jenkinsfile.groovy
ci/jenkins/generated/cortexm_jenkinsfile.groovy
ci/jenkins/generated/cpu_jenkinsfile.groovy
ci/jenkins/generated/docker_jenkinsfile.groovy
ci/jenkins/generated/gpu_jenkinsfile.groovy
ci/jenkins/generated/hexagon_jenkinsfile.groovy
ci/jenkins/generated/i386_jenkinsfile.groovy
ci/jenkins/generated/lint_jenkinsfile.groovy
ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy
ci/jenkins/generated/minimal_jenkinsfile.groovy
ci/jenkins/generated/riscv_jenkinsfile.groovy
ci/jenkins/generated/wasm_jenkinsfile.groovy
ci/jenkins/templates/utils/Prepare.groovy.j2

Disable git merge to avoid conflict on v0.13.0

[release] Disable git merge to avoid conflict

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package.json

Fix version number on branch v0.13.0

[Release] Fix version number on branch v0.13.0

---

python/tvm/dlight/gpu/decode_gemv.py
python/tvm/dlight/gpu/matmul.py
tests/python/dlight/test_gpu_decode_gemv.py
tests/python/dlight/test_gpu_matmul.py

This PR is to improve the performance of gemm and gemv in dlight:
- gemm: use vectorized load/store and change bindings.
- gemv: apply unroll

[Unity][Dlight] Minor performance improvement for gemm and gemv

---

python/tvm/contrib/cutlass/build.py
python/tvm/contrib/cutlass/gen_tensor_op.py
python/tvm/contrib/cutlass/rms_norm_operation.py
python/tvm/relax/backend/contrib/cutlass.py
python/tvm/relax/backend/patterns.py
tests/python/relax/test_codegen_cutlass.py

I've add a simple RMS kernel to cutlass in https://github.com/NVIDIA/cutlass/pull/979. For llama workload, it is about 2x faster than MS-tuned kernels.
@vinx13 @yelite @sunggg

[Unity][CUTLASS] Offload RMS norm

---

docker/install/ubuntu_install_tensorflow_aarch64.sh

The old version was no longer available so upgrading to 2.9.3

[Docker] tensorflow_aarch64 package upgrade

---

python/tvm/dlight/gpu/fallback.py
tests/python/dlight/test_gpu_fallback.py

The current fallback dlight schedule does not decompose the reduction init blocks, which might lead to some correctness issue (observed on Metal while not CUDA).
Doing DecomposeReduction effectively resolve the issue and meanwhile provide (minor) performance improvement.

[Dlight] Enhance fallback schedule with DecomposeReduction

---

CONTRIBUTORS.md

Please join us to welcome @jikechao as a new Reviewer in TVM. He has been continuously improving frontend support and fixing bugs.
- [Commits History](https://github.com/apache/tvm/pulls?q=is%3Apr+author%3Ajikechao)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:jikechao)

[COMMUNITY] Qingchao Shen -> Reviewer

---

python/tvm/dlight/base/__init__.py
python/tvm/dlight/base/analysis.py
python/tvm/dlight/gpu/__init__.py
python/tvm/dlight/gpu/decode_gemv.py
python/tvm/dlight/gpu/transpose.py
tests/python/dlight/test_gpu_transpose.py

This PR added schedule rule for (optional) decode + transpose.
cc @spectrometerHBH @MasterJH5574 @junrushao

[Unity][Dlight] Add schedule rule for decode transpose

---

ci/jenkins/docker-images.ini

Update ci-cortexm docker image to contain Vela 3.8.0, Ethosu Drivers 23.05
cc @lhutton1, @ekalda, @leandron

[Docker] Update ci-cortexm docker image

---

python/tvm/relay/op/strategy/arm_cpu.py
python/tvm/topi/arm_cpu/mprofile/dsp/__init__.py
python/tvm/topi/arm_cpu/mprofile/dsp/pool.py
python/tvm/topi/arm_cpu/pooling.py
tests/python/topi/python/test_topi_pooling.py

Reverts apache/tvm#15311
Still seeing cyclic importing issue according to reports

Revert "[topi] Add `arm_cpu` specific pooling schedules"

---

src/target/tag.cc

cc @junrushao @zxybazh @masahi 
I have the dev board and the change works fine with it.

[Target] Add Jetson Orin Nano tag

---

python/tvm/topi/adreno/reduction.py
python/tvm/topi/adreno/utils.py
python/tvm/topi/testing/common.py
tests/python/relay/opencl_texture/test_reduction_texture.py
tests/python/topi/python/test_topi_transform.py

On several topologies, I faced compilation errors. This PR introduces small fixes for these errors.
cc: @elvin-n, @masahi

[Adreno] Small fixes in Adreno schedules

---

python/tvm/dlight/gpu/general_reduction.py
tests/python/dlight/test_gpu_general_reduction.py

Prior to this PR, the reduction dlight rule sometimes may over-normalizes the last block and removes some spatial loops, making the last block have fewer block iters than previous reduction blocks. In this case, the dlight rule is not able to apply due to assertion failure while it is supposed to apply.
This PR thus adds unit block iter to the last block when it has fewer iters than other reduction blocks in the front, so that the numbers of block iters can align.
One softmax unit test is added to ensure that dlight reduction rule can work.

[Unity][Dlight] Fix reduction rule, aligning last block's iters

---

python/tvm/relax/transform/legalize_ops/manipulate.py
tests/python/relax/test_transform_legalize_ops_manipulate.py

- Enable lowering of `AXIS_SEPARATORS` in Relax Layout Transform 
- This change has a pre-requisite PR https://github.com/apache/tvm/pull/15315

[Unity] Lowering of axis separator in Layout Transform

---

python/tvm/relax/frontend/torch/dynamo.py
tests/python/relax/test_frontend_dynamo.py

support dynamo with dynamic shape.

[Unity] dynamo with dynamic shape

---

include/tvm/relax/attrs/nn.h
python/tvm/relax/op/nn/nn.py
python/tvm/relax/transform/legalize_ops/nn.py
src/relax/op/nn/convolution.cc
src/relax/op/nn/convolution.h
tests/python/relax/test_op_nn_convolution.py
tests/python/relax/test_tvmscript_parser_op_nn.py

This PR introduces Conv1dTranspose to relax.

[Unity][Op] Conv1dTranspose

---

python/tvm/relax/transform/legalize_ops/nn.py
python/tvm/topi/nn/conv1d.py
python/tvm/topi/nn/conv2d.py
tests/python/relax/test_transform_legalize_ops_nn.py

- Enable groups as parameters of conv1d
- Update the output shape of conv2d.

[Unity][Fix][Op] Add groups to conv1d

---

src/relax/transform/fold_dataflow_block_output.cc

a minor fix for a compilation warning

[Unity][Minor] Fix compilation warning

---

src/relax/ir/dataflow_matcher.cc
tests/python/relax/test_dataflow_pattern.py

Prior to this commit, pattern matches were evaluated a single time, in the order of the block bindings.  If a pattern rewrite produced a node which would also match the pattern (e.g. recursive reordering), the pattern would still only be evaluated once.
This commit updates `PatternMatcher` to iterate until convergence when provided with a pattern, analogous to its current behavior when called through `rewrite_bindings`.

[Unity] Recursive pattern match in rewrite_call

---

python/tvm/dlight/benchmark/extract.py

This PR fixes the case when extracting input infomation from TupleStructInfo class.
Fixes https://github.com/mlc-ai/mlc-llm/issues/742
CC: @Hzfengsy

[BugFix][Unity] Fix for TupleStructInfo

---

python/tvm/relax/transform/lazy_transform_params.py
tests/python/relax/test_transform_lazy_transform_params.py

Prior to this commit, any symbolic variables found in the transform_params function that are not provided by input tensors result in undefined symbolic variables.  This commit updates LazyTransformParam to only delegate tensor parameters to `"get_item"` and `"set_item"`.
This can be useful when producing sharded transformed parameters in a multi-GPU setup, where a `rank` symbolic variable may be provided to specify a subset of the weights to be used.

[Unity] Preserve shape parameters in LazyTransformParams

---

src/relax/transform/rewrite_cuda_graph.cc
tests/python/relax/test_transform_rewrite_cuda_graph.py

fixed #15488 
cc @cyx-6 @sunggg

[Unity] Fix handling of null values in cuda graph rewriting

---

web/src/webgpu.ts
web/tsconfig.json

This PR fixes webgpu runtime build by removing the lib preset that can conflict with the webgpu types

[WEB] Fix WebGPU runtime build

---

python/tvm/relax/frontend/nn/modules.py
python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_modules.py
tests/python/relax/test_frontend_nn_op.py

This straightforward PR adds support for the GroupNorm layer equivalent to torch in relax.

[Unity][Frontend][NN] Add GroupNorm Layer

---

python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_op.py

Add op `gelu` for nn.Module.
cc: @jwfromm @junrushao @cyx-6

[Unity][Frontend][NN] gelu NN module

---

python/tvm/relax/frontend/nn/modules.py
python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_modules.py
tests/python/relax/test_frontend_nn_op.py

In this PR I add support for `Conv2D` in our torch-like nn api. I'm planning on adding quite a few other such layers but wanted to get feedback on this one to make sure there arent any mistakes that would propagate :)

[Unity][Frontend][NN] Conv2D NN module

---

docker/install/ubuntu_download_arm_compute_lib_binaries.sh

Update Compute Library to follow latest developments in 23.05.1.
Changelog: https://arm-software.github.io/ComputeLibrary/v23.05.1
cc @ashutosh-arm @Liam-Sturge @neildhickey for reviews

[ACL] Update Compute Library to v23.05.1

---

python/tvm/relax/frontend/nn/__init__.py
python/tvm/relax/frontend/nn/modules.py
python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_modules.py

Add support for Conv1D and LayerNorm in our torch-like nn api.
cc: @junrushao @cyx-6 @jwfromm

[Unity][Frontend][NN] Conv1D/LayerNorm NN module

---

python/tvm/contrib/msc/core/ir/__init__.py
python/tvm/contrib/msc/core/ir/graph.py
python/tvm/contrib/msc/core/utils/__init__.py
python/tvm/contrib/msc/core/utils/info.py
src/contrib/msc/core/ir/graph.cc
src/contrib/msc/core/ir/graph.h
src/contrib/msc/core/printer/msc_base_printer.cc
src/contrib/msc/core/printer/msc_base_printer.h
src/contrib/msc/core/printer/print_utils.cc
src/contrib/msc/core/printer/print_utils.h
src/contrib/msc/core/printer/prototxt_printer.cc
src/contrib/msc/core/printer/prototxt_printer.h
src/contrib/msc/core/printer/python_printer.cc
src/contrib/msc/core/printer/python_printer.h

This is the first part of Milestone 0: Build MSCGraph core parts. Enable translation between Relay, Relax and MSCGraph without loss information.
To limit each PR in reviewable size, the Milestone 0 will be split into 5 steps:
M0.1: Passes for set name and layout for expressions (src/contrib/msc/transform)
M0.2: MSCGraph core (src/contrib/msc/core/ir/graph && python/tvm/contrib/msc/core/ir/graph)
M0.3: MSCGraph Builder (src/contrib/msc/core/ir/graph_builder)
M0.4: Codegen (src/contrib/msc/core/codegen, src/contrib/msc/framework/tvm/codegen)
M0.5: Translation test (relax/relay test && …

[Unity][MSC][M0.2] MSCGraph core

---

src/runtime/relax_vm/vm.cc
tests/python/relax/test_vm_execbuilder.py

[Unity] Prevent Relax VM from being corrupted after getting incorrect shape

---

python/tvm/relax/op/ccl/ccl.py
python/tvm/relax/transform/legalize_ops/ccl.py
python/tvm/runtime/disco/session.py
src/relax/op/ccl/ccl.cc
src/relax/op/ccl/ccl.h
src/runtime/disco/nccl/nccl.cc
tests/python/disco/test_nccl.py
tests/python/relax/test_op_ccl.py
tests/python/relax/test_transform_legalize_ops_ccl.py

This pr introduces op broadcast_from_zero, which broadcasts input tensor from worker-0 to all other workers.
cc: @junrushao @jinhongyii @tqchen

[Disco][Op] broadcast_from_worker0

---

include/tvm/runtime/container/shape_tuple.h
python/tvm/runtime/disco/session.py
src/node/container_printing.cc
src/runtime/disco/builtin.cc
src/runtime/disco/builtin.h
src/runtime/disco/nccl/nccl.cc
tests/python/disco/test_nccl.py

This PR introduces an API:
```C++
void ScatterFromWorker0(Optional<NDArray> send, NDArray recv);
```
This mimics the MPI-style scattering primitive that divides NDArray
`send` into chunks, and send them to each worker's NDArray `recv`.

[Disco] Add `Scatter-From-Worker0`

---

python/tvm/runtime/disco/session.py
src/runtime/disco/builtin.cc
src/runtime/disco/builtin.h
src/runtime/disco/nccl/nccl.cc
tests/python/disco/test_nccl.py

This pr introduce `gather_to_worker0`, which gathers an array from all other workers to worker-0.

[Disco][Op] gather_to_worker0

---

include/tvm/relax/attrs/ccl.h
python/tvm/relax/op/ccl/ccl.py
python/tvm/relax/transform/legalize_ops/ccl.py
src/relax/op/ccl/ccl.cc
src/relax/op/ccl/ccl.h
tests/python/relax/test_op_ccl.py
tests/python/relax/test_transform_legalize_ops_ccl.py

This pr introduces op scatter_from_worker0, which performs a scatter operation from worker-0, chunking the given buffer into equal parts.

[Disco][Op] scatter_from_worker0

---

include/tvm/runtime/disco/session.h
src/runtime/relax_vm/executable.cc

add a "has_function" function in executable

[Unity] Add `has_function` to RelaxVM

---

src/runtime/disco/loader.cc
tests/python/disco/test_loader.py
tests/python/disco/test_nccl.py

This PR adds a `LoadAll` method to the Disco shard loader to load
parameters all at once.

[Disco] Add LoadAll method to Disco Shard Loader

---

src/relax/backend/vm/vm_shape_lower.cc
tests/python/relax/test_backend_transform_shape_lower.py

[Unity] Clear slots before each shape lowering

---

python/tvm/relax/frontend/nn/spec.py
python/tvm/relax/frontend/nn/torch.py
tests/python/relax/test_frontend_nn_jit.py
tests/python/relax/test_frontend_nn_modules.py

- Enable tuple/list input for models, with nesting support.
- Correct the order of inputs for JIT execution.

[Unity][Frontend][NN] Enable tuple/list input

---

python/tvm/relax/transform/legalize_ops/ccl.py
python/tvm/runtime/disco/session.py
src/runtime/disco/builtin.cc
src/runtime/disco/builtin.h
src/runtime/disco/loader.cc
src/runtime/disco/nccl/nccl.cc
tests/python/disco/test_nccl.py
tests/python/relax/test_transform_legalize_ops_ccl.py

This eliminates extra malloc in collective communication op

[Unity][disco] Change collective communication to destination-passing style 

---

src/relax/transform/run_codegen.cc
tests/python/relax/test_transform_codegen_pass.py

The backend function may support dynamic shapes. In this case, the ret sinfo of the function shouldn't be reused.
cc @sunggg @masahi

[Unity] Fix BYOC codegen for dynamic shapes

---

src/runtime/disco/nccl/nccl.cc
tests/python/disco/test_nccl.py

put computation on default stream and put communication on a new stream.

[Unity][Disco] separate computation and communication into 2 stream

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Support LESS quantization operation as part of #15148

[TFLite][Frontend] Support quantized less

---

python/tvm/relax/frontend/nn/__init__.py
python/tvm/relax/frontend/nn/modules.py
python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_modules.py

This pr introduces a new op ConvTranspose1D to nn.Module.

[NN][Op]ConvTranspose1D

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Support NOT_EQUAL quantization operation as part of #15148

[TFLite][Frontend] Support quantized NOT_EQUAL

---

src/runtime/disco/nccl/nccl.cc

This PR integrates NCCL with CUDAGraph by using the default stream that CUDAGraph uses for NCCL communication.

[Disco] Integrate NCCL with CUDAGraph

---

python/tvm/meta_schedule/testing/tune_utils.py

Added support to generate uint test data
cc @zxybazh

[MetaSchedule] Allow generating uint random data

---

src/runtime/disco/nccl/nccl.cc

This pr removes duplicate `SetDevice` in `nccl.cc`.
https://github.com/apache/tvm/blob/cb3763b84d6b17448e76541f622275e11f51ddf0/src/runtime/disco/nccl/nccl.cc#L66-L70

[Bugfix] Remove duplicate code in nccl.cc

---

python/tvm/relax/block_builder.py
python/tvm/relax/expr.py
python/tvm/relax/expr_functor.py
python/tvm/relax/op/base.py
python/tvm/relax/struct_info.py
python/tvm/relax/vm_build.py
python/tvm/runtime/relax_vm.py

This PR includes minor fixes for doc strings in Python API.

[Unity][Doc] Fix Python Docstring for Sphinx Build

---

python/tvm/relax/analysis/analysis.py
python/tvm/relax/frontend/nn/op.py
python/tvm/relax/op/base.py
python/tvm/relax/op/manipulate.py
python/tvm/relax/op/nn/nn.py
python/tvm/relax/transform/transform.py
python/tvm/te/operation.py

Following #15848, this PR continues to fix the docstring of Relax part.

[Unity][Doc] Fix Relax part fix_docstring

---

src/runtime/disco/nccl/nccl.cc

This PR contains a minor fix for RCCL integration.

[Fix] Fix Build with RCCL

---

python/tvm/relax/frontend/nn/__init__.py
python/tvm/relax/frontend/nn/modules.py
python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_modules.py
tests/python/relax/test_frontend_nn_op.py

This PR adds support for ReLU in NN module and op, also adds support for GELU in the NN modules.
cc @jwfromm @junrushao

[Unity][NN] Enhance ReLU and GELU support

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

This PR fixed the TypeError mentioned in the issue #15892

[Unity] [Bugfix] Fix TypeError in TVM PyTorch frontend for LayerNorm operator

---

python/tvm/relax/frontend/onnx/onnx_frontend.py
tests/python/relax/test_frontend_onnx.py

Add support for [Elu](https://onnx.ai/onnx/operators/onnx__Elu.html).

[Unity][Frontend][Onnx] Add support for Elu operator

---

python/tvm/dlight/gpu/matmul.py
tests/python/dlight/test_gpu_matmul_tensorize.py

cc @spectrometerHBH @MasterJH5574 @Hzfengsy

[Unity][Dlight] Add software pipeline to matmul tensorization rule

---

python/tvm/relay/backend/contrib/ethosu/legalize.py
python/tvm/relay/backend/contrib/ethosu/op/identity.py
python/tvm/relay/backend/contrib/ethosu/te/identity.py
python/tvm/relay/backend/contrib/ethosu/tir/identity.py
src/relay/op/contrib/ethosu/identity.cc
src/relay/op/contrib/ethosu/op_attrs.h
tests/python/contrib/test_ethosu/cascader/test_ethosu_identity_matcher.py
tests/python/contrib/test_ethosu/test_codegen.py

This is a try cherry-pick to v0.14.0 with new release flow (which has a unverified commit before this PR in git log).
cc @Hzfengsy @junrushao @tqchen

[cherry-pick][microNPU][ETHOSU] Fix rounding mode in requantize operation (#15929)

---

tests/python/relax/test_bind_params.py

This test was implemented in https://github.com/apache/tvm/pull/15626, but was initially disabled as it depended on functionality not introduced until https://github.com/apache/tvm/pull/15577.  Since that PR has landed, cleaning up and enabling the unit test.

[Unity][UnitTest] Enable BindParams test for R.Prim

---

tests/lint/pylint.sh
tests/python/contrib/test_cblas.py

[Pylint] fix pylint issues for cblas

---

tests/python/relax/test_vm_build.py

- Removed unused `import os`
- Used `tvm.testing.main()` inside `if __name__=="__main__"`
- Added parametrized fixture `exec_mode` instead of marking all tests.
- Replace `@pytest.mark.xfail` with `with pytest.raises`, based on intended test behavior in comments.  The `@pytest.mark.xfail` allows a test to fail, and is intended for marking known bugs or not-yet-implemented functionality.  `with pytest.raises` requires that the block throw an instead of `@pytest.mark.xfail`, and is intended for validating that error-checking paths function correctly.
- Renamed `test_save_function_time_evaluator` to `test_save_function_time_evaluator_rpc`, to avoid having two distinct definitions of `test_save_function_time_evaluator`.

[Unity][UnitTest] Cleanup test_vm_build.py

---

src/relax/transform/utils.h

Sometimes we need to retrieve the variable mapping from the old function to the new function when copying the old function. 
This PR supports retrieve this information. 
This PR is tested by #16011 
cc @yzh119

[Unity] Support getting variable mapping for FunctionCopier

---

python/tvm/dlight/gpu/gemv.py
python/tvm/dlight/gpu/utils.py
tests/python/dlight/test_gpu_gemv.py

On M2 Ultra, q4f16_1:
Llama2 7B: 74 tok/s -> 89 tok/s
Llama2 13B: 45 tok/s -> 55 tok/s

[Unity][Dlight] Metal Performance

---

src/runtime/relax_vm/ndarray_cache_support.cc

This PR adds support for loading parameters from NDArrayCache ordered by their names.

[Unity] Loading NDArrayCache by parameter names

---

include/tvm/relax/expr.h
python/tvm/ir/expr.py
python/tvm/relax/__init__.py
python/tvm/relax/expr.py
src/relax/ir/expr.cc

This PR enhances the Python annotations for the Relax Expr, adding class member variables annotations and improving docstring

[Unity] Enhance Python Annotations for Relax Expr

---

include/tvm/tir/stmt.h
python/tvm/tir/stmt.py
tests/python/unittest/test_tir_schedule_analysis.py
tests/python/unittest/test_tir_schedule_state.py
tests/python/unittest/test_tvmscript_ir_builder_tir.py

This PR enhances the Python annotations for the TIR stmt, adding class member variables annotations.

[TIR] Enhance Python Type Annotations for TIR stmt

---

python/tvm/script/_ffi_api.py

Add _ffi_api.py under script folder so that user can call script.Complete in python.

Add _ffi_api.py under script folder

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Support SQUARE quantization operation as part of #15148

[TFLite][Frontend] Support quantized SQUARE

---

docs/contribute/code_guide.rst

Add missing backtick

---

python/tvm/contrib/tvmjs.py

This PR adds a new field to ndarray cache dumped from tvmjs, `md5sum`, which gives the downloader extra info to validate weights being downloaded from git lfs.

[Unity][TVMJS] Add md5sum to weight shards

---

python/tvm/relax/backend/contrib/cublas.py
python/tvm/relax/testing/matmul.py
src/runtime/contrib/cublas/cublas.cc
tests/python/relax/test_codegen_cublas.py

This commit adds support of i8i8i32 matmul and its offloading to cuBLAS.

[Unity][BYOC] Support IGEMM in cuBLASLt

---

src/runtime/relax_vm/lm_support.cc

The current error message would be confusing:
```
src/runtime/relax_vm/lm_support.cc:421: InternalError: Check failed: sampled_index >= 0 (-1 vs. 0)
```
But most of the case is caused by NaN error. This PR improves the error message

[Unity][LLM] Add NaN checks during sampling for better error reporting

---

include/tvm/runtime/packed_func.h

This PR adds the following member method of `TVMArgs`:
```C++
class TVMArgs {
public:
...
template <typename T>
inline T At(int i) const;
};
```
This method extracts the i-th argument from `TVMArgs`, do proper type checking, and generates proper message if it fails, including the index `i`, expected type and the actual type in the error message.
Previously this type checking is more like a more fine-grained approach, which, first in `TVMArgs::operator[](int i)`, checks array boundary and returns `TVMArgValue`, a generic union type of all. Then, `TVMArgValue` has a series overloads of `operator T()` which implicitly prunes it to the desired type.
This approach has been proven working consistently well in the past few years, but due to its fine-grained nature, it is impossible for such …

[Runtime] Introduce Type-Checked `TVMArgs::At<T>(i)`

---

docs/conf.py

[DOC] Add v0.14.0 docs to site

---

python/tvm/contrib/cutlass/attention_operation.py
python/tvm/contrib/cutlass/gen_tensor_op.py
tests/python/relax/test_codegen_cutlass.py

We are not passing the correct window size parameter for variable-length Flash attention.
@vinx13 @sunggg

[Unity][BYOC] Fix Flash var_len attention with sliding window

---

python/tvm/relax/transform/optimize_layout_transform.py
python/tvm/relax/transform/remove_redundant_reshape.py

There was a small redundancy in a couple of function passes where they iterate over all passes in the mod within the transform function, while function pass itself would also do that iteration.
So we would be un-necessarily iterating through all functions and modifying them, but only one of them would be updated each time transform_function is called.

[Unity] [Transform] Remove iteration over functions in function pass

---

python/tvm/ir/module.py

There's no test on IRModule initialization with attr, and there's an error with it. This PR fixes the behavior.

Fix IRModule initialization with attrs

---

python/tvm/dlight/gpu/utils.py
tests/python/dlight/test_gpu_reduction.py

change max number of threads per block from 256 to 1024, which makes rms_norm faster

[Dlight] Change max_threads on CUDA

---

src/relax/transform/normalize.cc

The current implementation of NormalizeGlobalVar couples the `AddPublicFunction` and checks if the module needs renaming, which causes the modules that don't need renaming to run unnecessary code, such as `AddFunction` to the new module.
This patch separates the two steps so that the modules that don't need renaming can skip the `AddPublicFunction` step.
cc @Ubospica

[Unity] Speed up NormalizeGlobalVar

---

python/tvm/relax/block_builder.py
python/tvm/relax/frontend/nn/__init__.py
python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_op.py

This PR adds the summation op to the relax frontend ops.
A unit test is added accordingly.

[Unity][Frontend] Add the `sum` op to frontend ops

---

src/runtime/relax_vm/lm_support.cc
tests/python/relax/test_runtime_builtin.py

Three-line change to adapt `WindowOverride` to support sinks. Also added a correctness test.
cc @tqchen

[Unity][lm_support] window kvcache sink

---

tests/python/contrib/test_msc/test_manager.py
tests/python/contrib/test_msc/test_runner.py
tests/python/contrib/test_msc/test_tools.py

This PR change test workspace to random workspace, which fix the bug for workspace conflict.

[Unity][MSC][Bugfix] Use random workspace for test

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package.json

Make version modification twice as two commits: first to v0.15.0 on main branch; second to v0.16.dev0 on main branch in one PR.
cc @Hzfengsy @Johnson9009 @tqchen

[release][Dont Squash] Update version to 0.15.0 and 0.16.0.dev on main branch

---

python/tvm/runtime/disco/session.py

[Unity] Fix creation of disco ProcessSession

---

src/target/tag.cc

Add NVIDIA Hopper H100 target tag

---

python/tvm/contrib/msc/core/codegen/codegen.py
python/tvm/contrib/msc/framework/tvm/codegen/codegen.py
python/tvm/contrib/msc/plugin/__init__.py
python/tvm/contrib/msc/plugin/_ffi_api.py
python/tvm/contrib/msc/plugin/build.py
python/tvm/contrib/msc/plugin/codegen/__init__.py
python/tvm/contrib/msc/plugin/codegen/codegen.py
python/tvm/contrib/msc/plugin/codegen/sources.py
python/tvm/contrib/msc/plugin/op/__init__.py
python/tvm/contrib/msc/plugin/op/_ffi_api.py
python/tvm/contrib/msc/plugin/register.py
python/tvm/contrib/msc/plugin/utils.py
src/contrib/msc/core/ir/plugin.cc
src/contrib/msc/core/ir/plugin.h
src/contrib/msc/core/utils.cc
src/contrib/msc/core/utils.h
src/contrib/msc/plugin/base_codegen.h
src/contrib/msc/plugin/codegen_utils.h
src/contrib/msc/plugin/tensorrt_codegen.cc
src/contrib/msc/plugin/tensorrt_codegen.h
src/contrib/msc/plugin/torch_codegen.cc
src/contrib/msc/plugin/torch_codegen.h
src/contrib/msc/plugin/tvm_codegen.cc
src/contrib/msc/plugin/tvm_codegen.h
tests/python/contrib/test_msc/test_plugin.py

Sorry for merging this PR into `unity` after the branch switched over by mistake. I cherry-pick this PR into `main`
Co-authored-by: Archermmt <archermmt@126.com>

[Cherry-pick][MSC][M4.1] Add plugin && plugin_builder, enable build and test in different frameworks (#16397)

---

python/tvm/contrib/emcc.py

[wasm] Enlarge initial memory for emcc

---

ci/scripts/github/github_tvmbot.py

This PR supports tvm-bot to rerun tvm-unity task
cc @tqchen

[CI] Support tvm-bot rerun for tvm-unity task

---

include/tvm/runtime/data_type.h

[Runtime] Fix dtype conversion for bf16 and fp8

---

src/relax/transform/fuse_ops.cc
tests/python/relax/test_transform_fuse_ops_by_pattern.py

[BYOC] Skip processed functions in FuseOpsByPattern and RunCodegen

---

python/tvm/contrib/rocm.py

Closes [#1216](https://github.com/mlc-ai/mlc-llm/issues/1216) and [#1614](https://github.com/mlc-ai/mlc-llm/issues/1614)
cc @tqchen

[Upd] Enable lld search to include /opt/rocm/llvm/bin for rocm

---

python/tvm/exec/gpu_memory_bandwidth.py

It is possible to measure GPU bandwidth through RPC on an Android device.
cc: @junrushao, @masahi

Extend gpu memory bandwidth test to work through RPC

---

python/tvm/dlight/gpu/__init__.py
python/tvm/dlight/gpu/low_batch_gemv.py
src/driver/driver_api.cc
src/tir/transforms/hoist_expression.cc
tests/python/dlight/test_gpu_low_batch_gemv.py

1. add a dlight rule LowBatchGEMV to schedule low-batch GEMM just like GEMV.
2. fix some issues when lowering low-batch GEMM

[Dlight] Scheduling Low batch GEMM using GEMV-like rule

---

python/tvm/contrib/debugger/debug_executor.py
src/runtime/graph_executor/debug/graph_executor_debug.cc
src/runtime/graph_executor/debug/graph_executor_debug.h

This pr is to address this issue:https://github.com/apache/tvm/issues/16490

[Bugfix][Executor] fix debug_executor function debug_get_output

---

src/relax/ir/block_builder.cc

[Relax] Fix error message in BlockBuilder

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

This PR fixed the bug in https://github.com/apache/tvm/issues/16625

[Relay][ONNX] Fix the Resize operator in ONNX frontend

---

python/tvm/auto_scheduler/workload_registry.py

Fixing workload comment

---

docs/conf.py

Minor update docs instructions

Minor update docs instructions

---

src/tir/transforms/vectorize_loop.cc
tests/python/tir-transform/test_tir_transform_vectorize.py

This PR adds support for vector reinterpret calls in TIR.

[TIR] Support Vector Reinterpret Calls

---

src/runtime/crt/common/crt_runtime_api.c
src/runtime/minrpc/minrpc_server.h
tests/python/runtime/test_runtime_rpc.py

As a followup PR to #16635, this PR fixes the FreeObject in minrpc server.
cc @tqchen

[Runtime][RPC] Fix FreeObject in minrpc server

---

include/tvm/relax/attrs/nn.h
python/tvm/relax/frontend/onnx/onnx_frontend.py
python/tvm/relax/op/nn/__init__.py
python/tvm/relax/op/nn/nn.py
python/tvm/relax/transform/legalize_ops/nn.py
python/tvm/topi/nn/pooling.py
src/relax/op/nn/pooling.cc
src/topi/nn.cc
tests/python/relax/test_frontend_onnx.py

Hi, tvm：
try to add sum op and gloablavgpool1d and gloablavgpool3d。
Please have a look. thanks.

[Relax][Frontend][Onnx] add sum and globalavgpool 1d/3d op

---

include/tvm/runtime/memory/memory_manager.h

This PR adds TVM_DLL to memory manager runtime functions for windows builds.

[Runtime] Add TVM_DLL to memory manager functions

---

src/runtime/metal/metal_common.h
src/runtime/metal/metal_device_api.mm
src/runtime/metal/metal_module.mm

This PR enhances metal runtime to include more error messages when error happens.

[RUNTIME][METAL] Provide richer runtime when error happens

---

src/tir/op/op.cc

[TIR] Implement max/min_value for fp8 data types

---

src/runtime/opencl/opencl_device_api.cc
tests/cpp-runtime/opencl/opencl_nativeptr.cc

Added couple more tests for host ptr data validation

[RUNTIME][OPENCL] Bugfix for ciImage create with host ptr

---

src/runtime/contrib/cutlass/fp8_group_gemm.cu

[Cutlass] Add check for group gemm param shapes

---

tests/python/relax/test_utils.py

A follow-up PR to https://github.com/apache/tvm/pull/16756, adding an explicit unit test for `tvm.ir.assert_structural_equal` of two distinct recursive functions.

[Relax] Unit-test for structural equal of recursive function

---

3rdparty/tensorrt_llm/custom_allreduce_kernels.cu

Fix includes of custom allreduce kernel

---

src/runtime/contrib/cutlass/group_gemm_runner.cuh

[Cutlass] Fix usage of cuda stream for group gemm

---

src/target/source/codegen_c.cc
tests/python/codegen/test_target_codegen_cuda.py

[Codegen] Add check to disable invalid reinterpret

---

src/runtime/relax_vm/vm.cc
src/support/ffi_testing.cc

This PR recycles the VMFrame in VM which can help a bit when function involves large frames.

[VM] Recycle VMFrame

---

src/runtime/relax_vm/paged_kv_cache.cc

The cached KV cache auxiliary data manager turns out introducing much extra copy size due to improper handling of array offsets. Specifically, prior to this PR, the manager always align the start of each offset to the largest possible. As a result, in each copy there are quite a lot of unnecessary elements getting copied.
This PR reduces the copy size to the minimal by aligning properly. This significantly reduces the copy size.

[KVCache] Reducing CacheAuxDataManager copy size

---

src/auto_scheduler/search_policy/utils.h

This PR fix a comment in the code.

Fixing probability comment

---

src/runtime/contrib/thrust/thrust.cu

`thrust::mr::tls_disjoint_pool` return a reference to the thread local pool. This PR changes to use a pointer to prevent creating an instance of the thread pool.

[Thrust] Use pointer to tls pool to prevent creating new pool

---

python/tvm/relax/backend/dispatch_sort_scan.py
src/runtime/contrib/thrust/thrust.cu
tests/python/relax/test_backend_dispatch_sort_scan.py

[Thrust] Fix thrust workspace allocation

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package.json

Make version modification twice as two commits: first to v0.16.0 on main branch; second to v0.17.dev0 on main branch in one PR.
cc: @vinx13 @Hzfengsy

[release][Dont Squash] Update version to 0.16.0 and 0.17.0.dev on main branch

---

python/tvm/relax/frontend/nn/op.py
tests/python/relax/test_frontend_nn_op.py

Fixes errors introduced in #16851 and add test cases.

[Relax][Frontend] Fix sort, argsort and topk in nn module

---

python/tvm/dlight/gpu/matmul.py
tests/python/dlight/test_gpu_matmul.py
tests/python/dlight/test_gpu_matmul_tensorize.py

This fixed dlight matmul rule to make sure vectorization is always applied to the innermost loop
cc @Hzfengsy @tqchen

[Dlight] Enhance vectorization for gpu matmul

---

src/runtime/relax_vm/paged_kv_cache.cc

We can use OpenCL mapped pointer for these copies for improved performance.

[VM][OPENCL] Take advantage of OpenCL host ptr for improved copy

---

docker/Dockerfile.ci_gpu

[CI] Upgrade CUDA to 12.4

---

python/tvm/relax/frontend/nn/core.py
tests/python/relax/test_frontend_nn_modules.py

[Relax] Support nested ModuleList in nn.Module

---

python/tvm/dlight/gpu/gemv.py
tests/python/dlight/test_gpu_gemv.py

Improved the gemv outer fallback schedules. It improved few gemv kernel by 20%.
LLM model       ---        baseline         ---    improved
gemma-2b-it    ---       22.4 tok/sec   ---     25.2 tok/sec
Qwen-7b-chat  ---       11 tok/sec      ---     11.8 tok/sec

[DLIGHT][GPU] Improved gemv outer fallback schedule

---

CONTRIBUTORS.md

Please join me in welcoming @cbalint13 as a new committer in TVM. Balint's contribution include LLVM backend, TVM Script and Scheduler improvements for various backends.
- [Commit history](https://github.com/apache/tvm/pulls?q=is%3Apr+author%3Acbalint13)
- [Code review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Acbalint13)
- [Discuss forum](https://discuss.tvm.apache.org/u/cbalint13/summary)

[COMMUNITY] New committer: Balint Cristian

---

python/tvm/dlight/gpu/gemv.py
python/tvm/dlight/gpu/low_batch_gemv.py
python/tvm/dlight/gpu/utils.py
tests/python/dlight/test_gpu_gemv.py
tests/python/dlight/test_gpu_low_batch_gemv.py

`q4f16_0` may improve the performance of metal. To be specific, Llama-3 8B on M1 Pro:
1. Single batch 26.2 tok/s (q4f16_1) vs. 28.0 tok/s (q4f16_0)
2. low-batched serving: about 25% improvement

Introduce outer reduction for metal

---

docs/conf.py

Add docs of v0.15.0 and v0.16.0

---

src/runtime/metal/metal_common.h
src/runtime/metal/metal_device_api.mm
src/runtime/metal/metal_module.mm

This PR adds label to MTLCommandBuffer, to enable instruments profiling.

[Metal] Enable Debug Label

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

[Relax] [PyTorch] Add support for torch.nn.Hardsigmoid

---

python/tvm/relax/frontend/onnx/onnx_frontend.py
tests/python/relax/test_frontend_onnx.py

[HardSwish Documentation](https://onnx.ai/onnx/operators/onnx__HardSwish.html)
@tqchen @yongwww

[Relax] [ONNX] Add support for HardSwish

---

python/tvm/relax/frontend/onnx/onnx_frontend.py
tests/python/relax/test_frontend_onnx.py

[HardSigmoid Documentation](https://onnx.ai/onnx/operators/onnx__HardSigmoid.html)
@tqchen @yongwww

[Relax] [ONNX] Add support for HardSigmoid

---

src/target/llvm/codegen_amdgpu.cc

[Backend][ROCm] Fix error when building TVM with LLVM 19

---

src/relax/transform/fuse_ops.cc

The pass would remove functions when iterating the whole IRModule, which would cause function not found issue. 
This PR fixes this one
cc @tqchen

[Relax] Fix fuseOps via pattern 

---

tests/python/relax/test_transform_dead_code_elimination.py

Fix a bug in the test_transform_dead_code_elimination.py file about the IR construction.

[Relax][BugFix] Fix a bug about the IR construction in test file 

---

python/tvm/relax/frontend/onnx/onnx_frontend.py
tests/python/relax/test_frontend_onnx.py

Add Sign and Not support to Relax ONNX frontend.

[Relax] [ONNX] Add support for Sign and Not

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

Add support for [`torch.nn.functional.max_pool2d`](https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool2d.html)
cc @vinx13

Add support for `torch.nn.functional.max_pool2d`

---

python/tvm/contrib/cutlass/attention_operation.py

Fixed a bug in cutlass byoc during instantiation of attention template, which would cause CUDA ERROR ILLEGAL ADDRESS error.

[Bugfix][Cutlass] fix cutlass instantiate attention template bugs

---

python/tvm/dlight/gpu/matmul.py
tests/python/dlight/test_gpu_matmul.py

Fixed the matmul schedule for the case of epilog blocks

[DLIGHT][ADRENO] Fix for opencl adreno matmul schedule

---

src/runtime/disco/nccl/nccl.cc

There are some observed overhead when the communicator is split.
cc @cyx-6 @tqchen

[Disco] Disable splitting nccl communicator in single-group

---

src/runtime/disco/nccl/nccl_context.h

[Disco] Fix double free of nccl communicator

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

As per title.
https://pytorch.org/docs/stable/generated/torch.tile.html
Related to #17277
cc @tqchen @vinx13 @yongwww

[Relax][PyTorch] Add support for torch.tile

---

docs/get_started/overview.rst
docs/index.rst

Overview page for Apache TVM.
cc @tqchen 
preview at http://8.130.134.126:58000/overview/get_started/overview.html

[Doc] Overview

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

As per title.
[torch.repeat](https://pytorch.org/docs/stable/generated/torch.Tensor.repeat.html)
cc @tqchen @vinx13 @yongwww

[Relax][PyTorch] Add support for torch.repeat

---

docs/how_to/index.rst
docs/how_to/tutorials/customize_opt.py

Add tutorial for customize optimization cc @tqchen

[Doc] Customize Optimization

---

docs/conf.py
docs/deep_dive/tensor_ir/abstraction.rst
docs/deep_dive/tensor_ir/index.rst
docs/deep_dive/tensor_ir/learning.rst
docs/deep_dive/tensor_ir/tutorials/README.txt
docs/deep_dive/tensor_ir/tutorials/creation.py
docs/deep_dive/tensor_ir/tutorials/transformation.py
docs/index.rst

This PR adds a new section in the documentation to introduce the TensorIR abstraction, its learning resources, and tutorials.

[Doc] Deep Dive TensorIR

---

python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

[Relax][PyTorch] Add support for `torch.ops.aten.sym_size.int`

---

docs/how_to/dev/index.rst

This PR provides a minor fix of developer howto guide.

[DOCS] Minor fix typo in developer howto guide

---

python/tvm/contrib/msc/core/frontend/translate.py
python/tvm/contrib/msc/framework/tensorrt/frontend/translate.py
python/tvm/contrib/msc/framework/tensorrt/transform/pattern.py
python/tvm/contrib/msc/framework/tensorrt/transform/transform.py
src/contrib/msc/core/transform/rewrite_utils.cc
src/contrib/msc/core/transform/rewrite_utils.h
src/contrib/msc/core/utils.cc
src/contrib/msc/core/utils.h
src/contrib/msc/framework/tensorrt/tensorrt_opcode.cc
src/contrib/msc/framework/tensorrt/transform_tensorrt.cc
tests/python/contrib/test_msc/test_translate_tensorrt.py

This PR 
1. Reconstruct tensorrt transform pass for TVM-TensorRT BYOC
2. support gelu, erf, gelu_tanh and astype ops
cc @Hzfengsy

[MSC] Reconstruct tensorrt module

---

.github/workflows/main.yml

[CI] Upgrade github upload-artifact action

---

python/tvm/relax/frontend/nn/op.py

This commit adds wrapper for Relax NCCL `allgather` operator.

[Relax] Add new NN allgather operator

---

python/tvm/relax/frontend/torch/fx_translator.py

As per title.
It has no functional changes.
Part of https://github.com/apache/tvm/issues/17346
cc @yongwww @vinx13 @tqchen

[Relax][PyTorch] Cleanup binary op converters

---

gallery/tutorial/tvmc_command_line_driver.py

modify the sentence, remove the duplicate "as"

Update tvmc_command_line_driver.py, modify the sentence, remove the duplicate "as"

---

src/relax/transform/run_codegen.cc

This makes BYOC append to the existing external modules.
cc @tqchen

[Relax] Fix BYOC removing existing ext mods

---

python/tvm/relax/frontend/torch/fx_translator.py

As per title.
It has no functional changes.
Part of https://github.com/apache/tvm/issues/17346
cc @yongwww @vinx13 @tqchen

[Relax][PyTorch] Cleanup Neural Network op converters

---

python/tvm/relax/frontend/torch/fx_translator.py

As per title.
It has no functional changes.
Part of https://github.com/apache/tvm/issues/17346
cc @yongwww @vinx13 @tqchen

[Relax][PyTorch] Cleanup Tensor Manipulation and Creation op converters

---

web/package-lock.json
web/package.json

This PR updates `web/package.json`, adding description so that it is possible to publish as npm package.

[TVMjs] Modify web package description

---

docker/install/ubuntu_install_sphinx.sh

[CI][Docs] Upgrade Sphinx

---

CONTRIBUTORS.md

Update recent nominations about contributors

[Community] update contributors

---

python/tvm/relax/frontend/onnx/onnx_frontend.py
tests/python/relax/test_frontend_onnx.py

Add support for [Pad-2](https://onnx.ai/onnx/operators/onnx__Pad.html#pad-2).

[Relax][Frontend][Onnx] Add support for pad-2

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package-lock.json
web/package.json

Make version modification twice as two commits: 
- First, to v0.18.0 on main branch.
- Second, to v0.19.dev0 on main branch in one PR.
cc: @Hzfengsy @vinx13

[release][Dont Squash] Update version to 0.18.0 and 0.19.0.dev on main branch

---

src/meta_schedule/database/database_utils.cc

Show the record if the escape sequence is unspported. so we can find and check it.

Show the record if the escape sequence is unsupported

---

python/tvm/relax/frontend/onnx/onnx_frontend.py

Fixed a typo in the BinaryBase class that was introduced in #17427

[FIX][RELAX][ONNX] Fix typo in onnx frontend 

---

tests/python/contrib/test_clml/test_ops.py

[TEST][CLML] Clip test case updated

---

python/tvm/relay/op/contrib/clml.py

This PR removes the CLML version print during importing tvm.

[Contrib] Remove CLML version print

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package-lock.json
web/package.json

Make version modification twice as two commits: 
- First, to v0.19.0 on main branch.
- Second, to v0.20.dev0 on main branch in one PR.
cc: @Hzfengsy @vinx13

[release][Dont Squash] Update version to 0.19.0 and 0.20.0.dev on main branch

---

src/runtime/opencl/opencl_device_api.cc

Internal regression bug to fix compilation issue

[RUNTIME][OPENCL] Bugfix

---

README.md

This PR updates the README to reflect the latest state of the project.

[DOCS] Update README

---

.gitmodules
LICENSE
apps/cpp_rtvm/CMakeLists.txt
apps/cpp_rtvm/main.cc
apps/cpp_rtvm/tvm_runner.cc
licenses/LICENSE.zlib.txt
python/tvm/driver/tvmc/config_options.py

This brings in basic support for Adreno target on Windows platforms and the tools we generally use for Adreno

[ADRENO][WINDOWS] Windows build dependencies for Adreno target

---

src/relay/backend/contrib/mrvl/codegen.cc

This update addresses a bug by eliminating unused code within the project. The removed code was not contributing to the functionality and may have been causing inefficiencies, confusion, or potential errors. By streamlining the codebase, this fix enhances maintainability, readability, and overall performance of the software.

Bug Fix: Removed unused code

---

docker/install/ubuntu2004_install_python_package.sh

[skip ci][Docker] Update ml_dtypes version

---

docker/install/ubuntu2004_install_python_package.sh

[Docker] Update ml_dtypes version

---

docker/Dockerfile.ci_gpu
docker/install/ubuntu_install_onnx.sh

Use torch GPU version on GPU docker.

[Docker] Use Torch GPU on gpu device

---

ci/jenkins/docker-images.ini
ci/jenkins/unity_jenkinsfile.groovy

update the images to version 20250226-223225-63bc315f, as they are expected to include the upgraded ml_dtypes.

[CI] Update images to 20250226-223225-63bc315f

---

src/relax/transform/split_layout_rewrite_preproc.cc
tests/python/relax/test_transform_split_layout_rewrite_preproc.py

Add support for func attr inheritance in SplitLayoutRewritePreproc.

[Relax] Add support for func attr inheritance in SplitLayoutRewritePreproc

---

web/emcc/wasm_runtime.cc

Update the include for `wasm_runtime.cc` to reflect:
- https://github.com/apache/tvm/issues/17674

[WASM] Update wasm include in accordance to kv cache revamp

---

src/tir/transforms/default_gpu_schedule.cc

Add checks for vulkan and opencl targets.

[TIR] Minor fix for default GPU schedule

---

docs/conf.py

This PR removes google analytics from setup

Remove Google Analytics

---

python/tvm/meta_schedule/relax_integration.py

This PR fixed a relax comment.

BugFix: Relax comment

---

python/tvm/relax/frontend/torch/exported_program_translator.py
tests/python/relax/test_from_exported_to_cuda.py

Added support for arange.default, arange.start, and arange.start_step

[Relax][Pytorch] support for arange in exported programs translator

---

python/tvm/relax/frontend/torch/exported_program_translator.py
tests/python/relax/test_from_exported_to_cuda.py

Add stack.default and sum.default to exported programs translator

[Relax][PyTorch] Add stack.default and sum.default to exported programs translator

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package-lock.json
web/package.json

Make version modification twice as two commits: 
- First, to v0.20.0 on main branch.
- Second, to v0.21.dev0 on main branch in one PR.
cc: @Hzfengsy @vinx13

[release][Dont Squash] Update version to 0.20.0 and 0.21.0.dev on main branch

---

python/tvm/relax/frontend/torch/base_fx_graph_translator.py
python/tvm/relax/frontend/torch/exported_program_translator.py
python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_from_exported_to_cuda.py

- added support for full.default, full_like.default, ones.default in exported program translator
- added unit tests

[Relax][PyTorch] full.default, full_like.default, ones.default 

---

python/tvm/relax/frontend/torch/base_fx_graph_translator.py
python/tvm/relax/frontend/torch/fx_translator.py
tests/python/relax/test_frontend_from_fx.py

This PR supports Pytorch `norm` op for Relax

[Relax][PyTorch] Add support for norm op

---

python/tvm/topi/nn/upsampling.py

fixing incorrect docstring in upsampling.py

---

python/tvm/relax/frontend/torch/base_fx_graph_translator.py
python/tvm/relax/frontend/torch/exported_program_translator.py
tests/python/relax/test_frontend_from_exported_program.py

As per title.
cc @yongwww @Hzfengsy

[Relax][PyTorch] Support `leaky_relu_.default` and `reshape_as.default` in ExportedProgram frontend

---

python/tvm/topi/nn/softmax.py

Fix the inconsistent docstring with parameter

Fix incorrect docstring in topi softmax 

---

python/tvm/topi/nn/conv2d.py

Fix the bug in https://github.com/apache/tvm/issues/17941

[TOPI] Add shape validation to prevent negative dimensions in conv operations

---

include/tvm/node/structural_equal.h

This PR fixes the structural equality specialization for Array<Any>

[NODE] Fix structural equality for Array<Any> specialization

---

ci/jenkins/generated/arm_jenkinsfile.groovy
ci/jenkins/generated/cpu_jenkinsfile.groovy
ci/jenkins/generated/docker_jenkinsfile.groovy
ci/jenkins/generated/gpu_jenkinsfile.groovy
ci/jenkins/generated/hexagon_jenkinsfile.groovy
ci/jenkins/generated/i386_jenkinsfile.groovy
ci/jenkins/generated/lint_jenkinsfile.groovy
ci/jenkins/generated/wasm_jenkinsfile.groovy
ci/jenkins/templates/utils/Prepare.groovy.j2
ci/jenkins/templates/utils/macros.j2

This PR further robustifies is_last_build check so it does not involve getJob API which may be denied. Hopefully will resolve some of the spot not rerun issue recently.

[CI] Further robustify is_last_build check

---

src/script/ir_builder/tir/ir.cc
tests/python/tvmscript/test_tvmscript_parser_tir.py

This PR allows users to allocate buffer at anywhere in the block, but not limited to the root body of block.

[Script] Enhance alloc buffer handling in nested frames

---

python/setup.py

Delete redundant imports

---

src/relax/transform/fuse_ops.cc
tests/python/relax/test_transform_fuse_ops_by_pattern.py

This Pull Request resolves the problem described in the referenced link:
https://discuss.tvm.apache.org/t/how-to-fuseops-concat-op0-op1/18484

[Relax] Fix issue in fuse concat ops by pattern

---

python/tvm/relax/frontend/onnx/onnx_frontend.py

This updates ONNX Resize to work with relax.expr.ShapeExpr parameters.
---
I attach a use case [nnblur.onnx.gz](https://github.com/user-attachments/files/21781486/nnblur.onnx.gz) that produces relax.expr.ShapeExpr as ```Resize``` parameter.
```
ValueError: Node /Resize cannot handle ShapeExpr inputs.
```
Cc: @Hzfengsy

[ONNX][FRONTEND][Fix] Update Resize to accept ShapeExpr

---

src/runtime/disco/nccl/nccl.cc

This PR fixes the use of ShapeView in nccl.cc, which was using `Shape()->Product()`. This has been changed to `Shape().Product()` with the introduction of ShapeView.

[Fix] Update ShapeView use in nccl.cc
