- python/tvm/auto_scheduler/dispatcher.py
- python/tvm/autotvm/task/dispatcher.py
- python/tvm/relay/transform/__init__.py
- python/tvm/relay/transform/flexible_shape.py
- tests/python/relay/test_auto_scheduler_tuning.py
- tests/python/relay/test_pass_flexible_shape_dispatch.py
- tests/python/unittest/test_autotvm_record.py
This PR adds a new pass to `relay.transform` that creates a dispatcher around an input module to handle multiple input shapes. For example consider a case where I'd like to optimize my model to handle both `batch_size=1` and `batch_size=4`. I can now do so elegantly as follows:
```
shape_dict = {'data': [1, 3, 224, 224]}
model_bs1 = tvmc.load('my_model.onnx', shape_dict=shape_dict)
tvmc.tune(model, log_file='batch_1.logs')
shape_dict = {'data': [4, 3, 224, 224]}
model_bs4 = tvmc.load('my_model.onnx', shape_dict=shape_dict)
tvmc.tune(model, log_file='batch_4.logs')
flex_mod = relay.transform.FlexibleShapeDispatch(buckets=[1, 4])(model_bs1.mod)
with ApplyHistoryBest(['batch_1.logs', 'batch_4.logs']):
exe = relay.vm.compile(flex_mod, "llvm")
batch_1 = np.random.rand(1, 3, 224, …
```
> [Relay] Flexible shape dispatch transformation

- include/tvm/tir/schedule/schedule.h
- python/tvm/script/tir/__init__.pyi
- python/tvm/script/tir/special_stmt.py
- python/tvm/script/tir/ty.py
- python/tvm/tir/schedule/schedule.py
- src/printer/tvmscript_printer.cc
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/block_annotate.cc
- src/tir/schedule/primitive/layout_transformation.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- src/tir/schedule/transform.cc
- src/tir/schedule/transform.h
- tests/python/unittest/test_tir_schedule_set_axis_separator.py
- tests/python/unittest/test_tvmscript_roundtrip.py
This PR added a schedule primitive `set_axis_separator`, it modifies `axis_separators` attribute of the target buffer, which affects the physical dimension after flattening.
cc @Lunderberg @csullivan @junrushao1994
> [TIR] Add schedule primitive SetAxisSeparator

- src/relay/backend/aot_executor_codegen.cc
- src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
- src/relay/backend/contrib/ethosu/codegen.cc
- src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc
- src/relay/backend/te_compiler.cc
- src/relay/transforms/target_hooks.cc
- tests/python/relay/aot/test_crt_aot.py
The sequence of calls produced by the AOT executor codegen is arbitrary, especially in the presence of 'branchy' networks. This makes it difficult to analyze memory usage for each call. By running the ToANormalForm pass to insert a series of let bindings before the lowering and codegen stages, we can establish an ordering for the evaluation of the external calls, thus allowing reliable analysis of memory usage.
Additionally contains a couple of error message improvements and comment corrections.
cc @manupa-arm @Mousius @areusch @mbs-octoml @ashutosh-arm @ekalda @NicolaLancellotti
> [AOT] Enable A-Normal Form in the AOT executor

- include/tvm/relay/attrs/transform.h
- python/tvm/relay/frontend/pytorch.py
- python/tvm/relay/op/_transform.py
- python/tvm/relay/op/strategy/cuda.py
- python/tvm/relay/op/strategy/generic.py
- python/tvm/relay/op/transform.py
- python/tvm/topi/__init__.py
- python/tvm/topi/cuda/__init__.py
- python/tvm/topi/cuda/stft.py
- python/tvm/topi/stft.py
- src/relay/op/tensor/transform.cc
- tests/python/frontend/pytorch/test_forward.py
- tests/python/relay/test_op_level3.py
This PR adds the stft, amax, amin 
[torch.stft](https://pytorch.org/docs/stable/generated/torch.stft.html)
```  
pt Elapsed time: 0.1826983118057251
graph_runtime Elapsed time: 0.11588997602462768
```
> [Frontend][PyTorch] Add: Relay stft operator

- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
Hi, we encounter some weird problem on llvm generated codes, seems caused by current llvm tbaa annotations.
The function `AddAliasInfo` will distinguish the index of scalar form and vectorized form. If we pass a scalar index but actually it is just the head of a ramp access, there is a possibility that overlapped accesses are infered as `NoAlias` by tbaa analysis unsafely.
However, I am not sure how to reproduce the problem on common target like X86 cpu. Glad to see any suggestions:)
cc @Lunderberg
> [LLVM] Fix a possible tbaa issue

- src/target/source/codegen_opencl.cc
- src/target/stackvm/codegen_stackvm.cc
> [CodeGen] Fix two icheck typo in codegen

- src/arith/analyzer.cc
- src/arith/interval_set.h
- src/tir/schedule/primitive/compute_at.cc
- tests/python/unittest/test_tir_schedule_compute_at.py
This PR fixed `compute_at` / `reverse_compute_at` when block access regions contain constants (e.g. `A[0, vi, vj]`). 
Background:
https://github.com/apache/tvm/pull/11187 added additional simplification when creating prim func from TE. This may result in block var with constant binding values simplified.
cc @junrushao1994 @spectrometerHBH @zxybazh @shingjan
> [TIR] Fix reverse_compute_at for trivial region with trivial block var

- src/tir/transforms/legalize_packed_calls.cc
Remove unused member variable
`tvm::tir::PackedCallLegalizer::tvm_value_index_`.
This also fixes a GCC 7.5 compiler warning.
> [tir] remove unused member variable

- tests/python/contrib/test_ethosu/test_encode_constants.py
- tests/python/contrib/test_ethosu/test_replace_conv2d.py
A follow up for https://github.com/apache/tvm/pull/10251 
cc @Mousius
>  [microNPU] Remove spurious prints and improve documentation

- apps/microtvm/cmsisnn/convert_image.py
There is a latent bug in the CMSIS-NN demo app where the input and output tensors generated by the `create_image.py` script are not 16-byte aligned in memory. Although this does not cause an issue in the demo using the current `person_detect` model, if a different model is substituted with a larger output tensor, it causes the FVP to hang in certain cases.
This PR updates `create_image.py` to correct the issue.
@Mousius @ashutosh-arm @areusch
> [CMSIS-NN] Fix memory alignment bug in CMSIS-NN demo

- python/tvm/utils/roofline.py
- src/auto_scheduler/feature.cc
Refactor roofline_analysis to use a pass instrument to save TIR code from compilation for feature extraction. This should support different compilation pipelines and avoids recompiling the module twice.
@AndrewZhaoLuo @masahi @csullivan
> [ROOFLINE] Calculate roofline from existing TIR PrimFunc

- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
- tests/python/unittest/test_target_codegen_llvm.py
LLVM codegen create new function, e.g. the "_compute_" function for a compute_scope attribute, etc. These function did not have function attributes defining the target properties, specifically "target-cpu" or "target-features". Make sure this information is present on all functions created in CodeGenLLVM.
> [LLVM] Make sure all functions have target-related attributes set

- src/runtime/opencl/opencl_common.h
- src/runtime/opencl/opencl_device_api.cc
- src/runtime/opencl/opencl_module.cc
Profiling in TVM is enabled or disable in compile time by the `USE_PROFILER` switch. It means that if we enable profile in `config.cmake`, but do not use any profiling features in the app, OpenCL is forced to collect `cl_events` objects.
Build TVM with `set(USE_PROFILER ON)`.
Consider simple app, where we create module from the `.so` file:
```c
tvm::runtime::Module mod_factory = tvm::runtime::Module::LoadFromFile("model.so");
tvm::runtime::Module gmod = mod_factory.GetFunction("default")(ctx);
tvm::runtime::PackedFunc set_input = gmod.GetFunction("set_input");
tvm::runtime::PackedFunc get_input = gmod.GetFunction("get_input");
tvm::runtime::PackedFunc get_output = gmod.GetFunction("get_output");
tvm::runtime::PackedFunc run = gmod.GetFunction("run");
// set inputs and outputs
size_t …
```
> [OpenCL] Change of OpenCL profiling logic

- python/tvm/driver/tvmc/composite_target.py
- python/tvm/relay/op/contrib/ethosn.py
- tests/python/contrib/test_ethosn/test_partition_params.py
- tests/python/driver/tvmc/test_compiler.py
- tests/python/driver/tvmc/test_composite_target.py
- tests/python/driver/tvmc/test_target.py
Specifically removes some TVMC tests that are no longer necessary and some partitioning infrastructure.
cc @Leo-arm @manupa-arm
> [ETHOSN] Remove remaining support for the N77 variant

- tests/cpp-runtime/hexagon/run_all_tests.cc
- tests/scripts/task_build_hexagon_api.sh
It appears various QuRT images do not include the `pthread_key_delete` function. This fixes #11237 by providing an implementation of `pthread_key_delete`, calling the underlying QuRT API, if it's not already defined. `USE_HEXAGON_GTEST` is once again defined to enable running tests on hardware.
cc @mehrdadh
> [Hexagon] Fix running gtest on Hexagon hardware

- Jenkinsfile
- jenkins/Jenkinsfile.j2
- jenkins/macros.j2
i386 is the longest running test step by a small margin and run dangerously close to the 2hr timeout.
This also only runs the C++/Java tests on a single shard so we don't end up wasting compute minutes running the same tests twice
> [ci] Bump i386 shards from 2 -> 3

- CONTRIBUTORS.md
Please join us to welcome Michalis Papadimitriou (@mikepapadim) as a new reviewer to TVM. Michalis has contributed a lot to BYOC and TensorRT backend.
- [Commits History](https://github.com/apache/tvm/commits?author=mikepapadim)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:mikepapadim)
- [Community Forum Summary](https://github.com/apache/tvm/commits?author=mikepapadim)
> [COMMUNITY] mikepapadim -> Reviewer

- docker/Dockerfile.ci_arm
- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_gpu
- docker/Dockerfile.ci_hexagon
- docker/Dockerfile.ci_i386
- docker/Dockerfile.ci_qemu
- docker/Dockerfile.ci_wasm
- docker/install/ubuntu_install_sccache.sh
This adds `/opt/sccache` to the PATH of each of the CI docker images so when cmake looks for a C compiler it will pick up the sccache wrapper by default. This fixes some issues where compiler invocations weren't being run though sccache. With this approach the invoker doesn't need to do anything specific to set up sccache.
This will require a follow up PR to update the Docker images and remove some of the sccache logic in `task_build.py`
> [ci][docker] Use sccache everywhere by default

- python/tvm/contrib/ethosu/cascader/cascader_options.py
- python/tvm/contrib/ethosu/cascader/device_config.py
- python/tvm/contrib/ethosu/cascader/plan_generator.py
- python/tvm/relay/backend/contrib/ethosu/codegen.py
- python/tvm/relay/backend/contrib/ethosu/util.py
- src/contrib/ethosu/cascader/cascader_options.cc
- src/contrib/ethosu/cascader/cascader_options.h
- src/contrib/ethosu/cascader/plan_generator.cc
- src/relay/backend/contrib/ethosu/compiler_attrs.cc
- tests/python/contrib/test_ethosu/cascader/infra.py
- tests/python/contrib/test_ethosu/cascader/test_memory_reduction.py
- tests/python/contrib/test_ethosu/cascader/test_plan_generator.py
- tests/python/contrib/test_ethosu/cascader/test_proposal_generator.py
This commit adds a cascader option to enable
striping explicitly.
When doing so fixed a bug that is associated
with block config selection, that will be
triggered when striping is disabled.
Co-authored-by: Elen Kalda <elen.kalda@arm.com>
> [microNPU] Adding a option to enable striping

- gallery/how_to/work_with_microtvm/micro_ethosu.py
This PR adds instructions to the existing microNPU tutorial indicating how to offload operators to CMSIS-NN in addition to the microNPU. It also includes a note on how to offload operators to CMSIS-NN only, without using the microNPU.
@Mousius @ashutosh-arm @manupa-arm 
cc @lhutton1
> [microNPU] Update existing microNPU tutorial for CMSIS-NN

- tests/scripts/ci.py
- tests/scripts/task_build.py
- tests/scripts/task_ci_setup.sh
- tests/scripts/task_cpp_unittest.sh
This switches the CI build to use Ninja which has slightly nicer output and faster behavior in the face of re-runs. This also adds a `--verbose` flag to `ci.py` to control build output accordingly.
> [ci][build] Use ninja instead of Makefiles

- .github/dependabot.yml
A bunch of these just got created (e.g. https://github.com/apache/tvm/pull/11070) and are clogging up CI with 2x normal number of builds since they push to a branch and make a PR.
> [ci] Disable dependabot PRs

- tests/scripts/task_web_wasm.sh
- web/tsconfig.json
- web/typedoc.json
Fixes #11300. Tested locally via
```bash
python tests/scripts/ci.py wasm -i
bash tests/scripts/task_web_wasm.sh
```
and
```
python tests/scripts/ci.py docs -i
cd web
npm install
npm run typedoc
```
> [skip ci][wasm][ci] Fix WASM build and JS doc build

- src/node/structural_hash.cc
- tests/python/unittest/test_node_reflection.py
When `NDArray` is being stored as `ObjectRef`, the serializer won't trigger the right path for storage. Under the new serialization mode, we need to be able to leverage the `repr_bytes` mechanism to save `NDArray`.
This change is backward compatible -- ndarray saved in previous format will continue to work. And fixes the problem of serialization when `NDArray` is involved as part of `ObjectRef`. In the future, we can consider consolidate the `NDArray` save into the `repr_bytes` and remove the specialization as we evolve to newer versions
cc @tqchen @areusch
> Fix json serialization for NDArray

- src/te/operation/create_primfunc.cc
- tests/python/unittest/test_meta_schedule_tune_relay.py
- tests/python/unittest/test_te_create_primfunc.py
Simplifying unit iter vars in CreatePrimFunc changes semantics of the PrimFunc, which need different handling in analysis.
This reverts commit 26cefab5df8f24af7dc43a3239dbfd0e858fd1a2.
cc @junrushao1994 @Hzfengsy
> Prevent simplifing unit IterVar in CreatePrimFunc

- include/tvm/arith/iter_affine_map.h
- include/tvm/tir/index_map.h
- python/tvm/tir/function.py
- src/arith/iter_affine_map.cc
- src/arith/rewrite_simplify.cc
- src/tir/ir/index_map.cc
- src/tir/schedule/state.cc
- tests/python/unittest/test_index_map.py
- tests/python/unittest/test_tir_schedule_analysis.py
The goal of this PR is to allow `IndexMap` to express transformations that introduce padding in the transformed shape.  For an arbitrary input shape, the new method `IndexMap.non_surjective_inverse` determines the inverse transformation, along with a predicate specifying which coordinates in the transformed index space do not contain an inverse in the original index space.  The previous behavior of `IndexMap.inverse`, requiring transformations to be bijective over the range given, is maintained.
This functionality will be used in the future to allow buffer transformations (see #9727 and #10538) to introduce padding to the buffer.
> [TIR][Arith] Implemented padded inverses in IndexMap

- tests/python/unittest/test_runtime_profiling.py
See #10698 for some context, this test wasn't actually being skipped on i386
cc @tkonolige
> [profiler] Skip i386 skip condition

- include/tvm/relay/transform.h
- python/tvm/relay/transform/transform.py
- src/relay/backend/interpreter.cc
- src/relay/transforms/fold_constant.cc
- tests/python/relay/test_pass_fold_constant.py
This PR is an attempt to revive [PR#9164](https://github.com/apache/tvm/pull/9164) . It enables folding of constants for QNN operations. Motivation to have this feature is BYOC use cases. For some BYOC it can help to avoid weights converting at runtime and thus to improve performance.
One important thing: for the case when we call `FoldConstant` before `FakeQuantizationToInteger` pass, we can prevent `FQ2I` from converting some ops to qnn equivalent. To avoid this, folding of QNN constants is disabled by default. To enable use fold_qnn=True flag in `FoldConstant` pass.
Co-authored-by: Alexander Peskov peskovnn@gmail.com
> [QNN] Enable constant folding for QNN operations.

- src/relay/backend/te_compiler_cache.cc
- tests/python/relay/test_backend_graph_executor.py
Since users can manually build relay graph like useless cast and fuse before optimization, it is possible that the primitive function is identity when relay building process go into te compiler.
> [Relay] Fix a corner case of fused identity

- src/target/target_info.cc
- src/tir/transforms/storage_rewrite.cc
If a memory info is not defined for a used memory scope, storage_rewrite's current behavior is undefined and will segfault.
> Avoid use of MemoryInfo when undefined in StorageRewrite

- python/tvm/utils/roofline.py
- tests/python/unittest/test_runtime_profiling.py
Run roofline analysis on remote devices if requested. Peak flops and peak bandwidth estimation are done on the remote device.
@jwfromm
> [ROOFLINE] Roofline analysis over RPC

- Jenkinsfile
- jenkins/Jenkinsfile.j2
- tests/python/unittest/test_target_codegen_llvm.py
This makes sccache easier to integrate in CI so we can use it for C++ builds and tests. This also includes a small change to unconditionally skip a test on i386 that was already being skipped (since clang wasn't available on the PATH before). Since the fix doesn't change anything and it's pretty simple it seems fine to include it here while #11316 makes its way through
> [ci][docker] Update images to include sccache changes

- python/tvm/meta_schedule/tune.py
This PR allowed users to set logging level without giving a logger config. Previous implementation hard-coded `logging.INFO` as the default logging level and requires a logger config to change it. Now the logging level and handlers can be inherited from the current `tvm.meta_schedule` logger setting.
CC: @junrushao1994 @michalpiszczek
> [MetaSchedule] Allow Easy Logging Level Setting

- python/tvm/topi/vision/rcnn/roi_align.py
This PR fixes 'duplicated iterator names in the compute definition' error of roi_align,  just changes the name of 'te.reduce_axis'.
Please review @masahi @gromero
> [BugFix][Topi] Fix roi_align bug of 'duplicated iterator names'

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
When I import the onnx model efficientdet_lite.onnx. There are some ConvTranspose operator just provide `output_shape` attributes. no `pads`. As shown in the picture below:
Then i get a error is the
```
AssertionError: Output shapes (1, 256, 256, 16) and (1, 270, 270, 16) don't match
```
According the doc: https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvTranspose
```
total_padding[i] = stride[i] * (input_size[i] - 1) + output_padding[i] + ((kernel_shape[i] - 1) * dilations[i] + 1) - output_shape[i]
```
I updated how `total_padding` is calculated. And support  explicitly specified the ```output_shape```.
cc: @MatthewARM  @jwfromm  @AndrewZhaoLuo
> [frontend][ONNX]support ConvTranspose explicitly specified output_shape

- include/tvm/relay/attrs/nn.h
Just to restore consistency with other types of convolutions.
> Missed "out_layout" field of conv1d attrs

- src/tir/transforms/split_host_device.cc
- tests/python/unittest/test_tir_texture_scope.py
This propagates the storage scope from the pointer type of an undefined Var (like those produced from an alloc_buffer in a block) to the Var of the split out device function. 
Note the test added in this PR will fail until #11254 is also merged.
> [TIR] Propagate storage scope of undefined vars in SplitHostDevice.

- src/runtime/object.cc
This PR makes it easy to determine the order in which `GetOrAllocRuntimeTypeIndex` is called and to make sure it is called. Adding as VLOG(3) since we mostly don't want to do this unless something is really screwed up.
@mbs-octoml @tqchen
> Add vlogging for type-table registration

- cmake/modules/Hexagon.cmake
- src/runtime/hexagon/rpc/simulator/session.cc
[build][hexagon] fix several compiler warnings
Fix several compiler warnings for Hexagon code.
cc @mehrdadh
> [build][hexagon] fix several compiler warnings

- src/tir/schedule/primitive/compute_inline.cc
- tests/python/unittest/test_tir_schedule_compute_inline.py
ReverseComputeInline requires the consumer body to be `B[...] = g(i, j, k, A[f(i, j, k, ...)] ...)`, previously `f` can only be a permutation function over variable `i, j, k, ...`. This PR allows f to be a bijective affine function.
After `ReverseComputeInline`, `f^-1` will be applied the LHS buffer store indices in the producer site, to find the corresponding buffer store location in the consumer site. 
This allows reshape operation to be inlined.
cc @junrushao1994 @spectrometerHBH @masahi @tqchen  @tqchen
> [TIR] Support affine expressions as indices in reverse compute inline

- src/tir/schedule/primitive/layout_transformation.cc
- tests/python/unittest/test_tir_schedule_transform_layout.py
Without this, a sequence of `blockize -> transform_layout -> tensorize` would likely lead to a tensorize pattern match failure, since there is no simplification done between ` transform_layout -> tensorize` but intrinsic descriptions are always written without taking extra factors like `% 16` into account.  
Co-authored-by: Yuanjing Shi <yuanjing@octoml.ai>
@vinx13 @shingjan
> [TIR] Simplify indices in layout transform

- apps/microtvm/cmsisnn/Makefile
- apps/microtvm/ethosu/Makefile
- docker/install/ubuntu_install_cmsis.sh
- tests/python/relay/aot/corstone300.mk
Aligning CMSIS-NN to TFLu's CMSIS-NN SHA. Since the
docker update will take some time, these code changes
contain support for old and new SHA both. After the
docker image update, we can remove the support with
older CMSIS-NN. This commit updates CMSIS-NN and
micronpu demos.
> [CMSIS-NN] Align CMSIS-NN in TVM to TFLu SHA

- gallery/how_to/work_with_microtvm/micro_reference_vm.py
Fix path for test_zephyr.py in microTVM Reference Virtual Machines - Running Tests documentation
cc @gromero @mehrdadh @areusch @mkatanbaf
> [docs][microtvm] Fix path in microTVM VM running tests instructions.

- src/runtime/thread_pool.cc
- tests/cpp/threading_backend_test.cc
This commit allows to pin threads to cores when we use OpenMP. It enhances
`tvm::runtime::threading::Configure` method to work with OpenMP and "kSpecify"
affinity mode.
> [Runtime][ThreadPool] Enhance CPU Affinity configuration for OMP case

- src/runtime/contrib/json/json_runtime.h
Current implementation of "__init_XXX" method is not thread safe. So simple multi instance execution/initialization of BYOC json based runtime may lead to data race.
Simple WA is just to add mutex guard.
> Thread safe initialization for JSONRuntime module

- Jenkinsfile
- jenkins/Jenkinsfile.j2
- tests/scripts/ci.py
- tests/scripts/task_build.py
- tests/scripts/task_config_build_hexagon.sh
- tests/scripts/task_lint.sh
This uses the `CPU-SMALL` label for certain jobs in CI, which is backed by r5.large instances in EC2 rather than c4.4xlarge instances which are much more expensive. `sccache` is essential for keeping runtimes down so there are some change to get it enabled for all builds.
> [ci] Use r5.large nodes for hexagon build and some tests

- Jenkinsfile
- jenkins/Jenkinsfile.j2
Image is tested here: https://ci.tlcpack.ai/job/docker-images-ci/job/docker-image-run-tests/124/
Image is uploaded here: https://hub.docker.com/layers/ci-hexagon/tlcpack/ci-hexagon/20220516-190055-672ce3365/images/sha256-20de840d3404952b1e77663b895beee767deeaf190a3a5d9e407c8674d189cb0?context=explore
cc @areusch
> [Hexagon][Docker] Update image version

- python/tvm/auto_scheduler/dispatcher.py
- python/tvm/autotvm/task/dispatcher.py
- tests/python/relay/test_auto_scheduler_tuning.py
- tests/python/unittest/test_autotvm_record.py
I introduced a bug in #11199 that causes an error when an Iterator of records is used as the argument to ApplyHistoryBest. This small PR fixes it by more carefully checking input types.
> [Relay] Bug fix when applying history using an iterator or records.

- docker/install/ubuntu_install_python_package.sh
A recent release depends on some things we don't have installed, so don't use it.
e.g. https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11319/5/pipeline/
Skipped CI to unblock other docker PRs, successful run: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11348/1/pipeline
> [skip ci][ci][docker] Pin Pillow version

- Jenkinsfile
- jenkins/Jenkinsfile.j2
This is intended to be temporary to avoid timeouts on jobs while we work on getting some things under control like artifact upload time and shards for various jobs.
Example timeouts:
* https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11347/1/pipeline/407
> [ci] Bump job timeout to 3 hours

- docs/dev/how_to/debugging_tvm.rst
- docs/dev/how_to/how_to.rst
- src/runtime/logging.cc
- tests/cpp/runtime/logging_test.cc
This PR makes it easier to use TVM_LOG_DEBUG and documents it underneath Developer How-To.
@mbs-octoml
> Improve error messages with TVM_LOG_DEBUG and add docs

- python/tvm/script/parser.py
- tests/python/unittest/test_tvmscript_syntax_sugar.py
I came across a use case where being able to call a python function as a sugar to construct AST fragments is extremely handy. 
The attached test case illustrates two ways of describing the same TVMScript function, one of which is using the proposed syntax sugar. Here, the called function does some complicated index transformation - Calling a function to construct such mapping, rather than spelling them out by hand, significantly cleans up the TVMScript description.
Moreover, since the index map is just a normal python function, it can also be used in the layout transformation primitive in a schedule:  
```
def index_map(i, j):
return (i // 16, j // 16, *shared_16x16_to_ldmatrix_32x8_layout(i % 16, j % 16) ) 
sch.transform_layout(C_warp, 0, "read", index_map)
```
This way, we can be sure …
> [TVMScript] Support inlined function call as a sugar

- src/relay/transforms/infer_layout_utils.cc
- tests/python/relay/test_pass_alter_op_layout.py
The issue appeared after implementation of handling broadcast axis on dependent eltwise operators in alter op layout.
The pattern that I had `conv->add` and it happened that the block size was equal to the number of output channels. In one moment during network compilation we got a situation when we have already blocked layout and alter_op_layout is called one more time. During this second invocation the part dedicated for determination of the layout for second input of `add` detects `1` unconditionally as broadcast axis and puts wrong `layout_transform(->NCHW1c)`. This is wrong. In our case 1 was a reminder. Need to take into account block part as well in such cases.
I believe test `test_alter_layout_blocked_no_broadcast` shows situation clearly. The second test …
> Fix eltwise alter op layout for broadcast axis

- python/tvm/driver/tvmc/composite_target.py
- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/codegen_ethosn.h
- tests/python/contrib/test_ethosn/test_partition_params.py
- tests/python/driver/tvmc/test_compiler.py
- tests/python/driver/tvmc/test_composite_target.py
- tests/python/driver/tvmc/test_target.py
Improves the TVMC target string to avoid duplication of the NPU variant. The new target string will require just the NPU name followed by -variant=n78. The old target string is deprecated and will be removed in a subsequent version of TVM.
cc @Leo-arm @Mousius @gromero @leandron
> [TVMC][ETHOSN] Improve target string to avoid duplication

- python/tvm/relay/backend/contrib/ethosu/te/convolution.py
- python/tvm/relay/backend/contrib/ethosu/te/depthwise.py
- python/tvm/relay/backend/contrib/ethosu/te/pooling.py
- tests/python/contrib/test_ethosu/cascader/test_ethosu_conv2d_matcher.py
If the input tensor layout is in NHCWB16, we were passing W value
instead of the channels to get_valid_block_configs.
> [microNPU] Fix bug in channels extraction in the matcher

- include/tvm/tir/index_map.h
- src/arith/ir_mutator_with_analyzer.cc
- src/arith/ir_mutator_with_analyzer.h
- src/tir/ir/index_map.cc
- src/tir/schedule/primitive/layout_transformation.cc
This is a follow-up from https://github.com/apache/tvm/pull/11330.  I really like the functionality that it adds (simplification of transformed indices based on `BlockNode` iteration variables), and would like to expose the functionality for use elsewhere as well.
> [TIR] IndexMap Simplification Constraints

- include/tvm/runtime/crt/func_registry.h
- src/runtime/crt/common/func_registry.c
- src/target/func_registry_generator.cc
- tests/crt/func_registry_test.cc
Hi, @areusch  
Here is the [bug](https://discuss.tvm.apache.org/t/byoc-limited-function-numbers-on-crt-runtime/11952/2) I mentioned before.
I cast the first two byte to uint16_t to store the function number.
> Fix function number datatype from char to uint16_t

- docker/install/ubuntu_install_sccache.sh
This was causing errors with #11314 since it was making it appear as if `clang` was available when it was only the sccache wrapper.
> [ci][docker] Conditionally link sccache to clang

- conftest.py
Previously, these tests were labeled as `"unconditional skip"` in the CI logs (e.g. [here](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11294/4/pipeline/405#step-1059-log-20)), which can cause confusion during debugging.
> [CI] Added message if test is running on another shard

- docker/install/ubuntu_install_dnnl.sh
I submitted the PR to enable bfloat16 in DNNL BYOC(https://github.com/apache/tvm/pull/11111). But the PR failed to be built due to the version of the oneDNN in CI is limited to v2.2, which is a relative old one. So I update the CI script to get and build the latest oneDNN release.
I had tested the script on my own PC and it works fine, but I don't know how to test the script in CI environment. So let me know if I did something inappropriate, thanks!
> [CI] update oneDNN to v2.6

- .github/actions/setup/action.yml
- conda/condarc
- tests/lint/check_file_type.py
This should help alleviate some of the GitHub Actions failures like
* https://github.com/apache/tvm/runs/6487878471?check_suite_focus=true
* https://github.com/apache/tvm/runs/6478323571?check_suite_focus=true
Test run: https://github.com/driazati/tvm/runs/6493421090?check_suite_focus=true
> [ci][actions] Add more HTTP retries for conda

- include/tvm/runtime/crt/func_registry.h
- src/runtime/crt/common/func_registry.c
- src/target/func_registry_generator.cc
- tests/crt/func_registry_test.cc
This reverts commit f34bd22ddc4e7064eabe9fac42c4c04f54ede399 (#10014)
Located via a git bisect, likely happened since the PR is pretty old. Tested revert via
```
python3 tests/scripts/ci.py cpu --tests tests/python/unittest/test_crt.py::test_aot_executor --tests tests/python/unittest/test_crt.py::test_graph_executor
```
> [skip ci] Revert "Fix function number datatype from char to uint16_t (#10014)"

- src/relay/op/nn/nn.cc
Mark `nn.batch_flatten` as a reshape op so the executors can avoid unnecessary copying.
cc @AndrewZhaoLuo @areusch
> [Relay][Op] nn.batch_flatten is a reshape op

- Jenkinsfile
- jenkins/Jenkinsfile.j2
- jenkins/macros.j2
This takes away any need for the worker nodes to do any compression (which takes anywhere from a few to several minutes) and makes CI more scalable since there is no bottleneck of network traffic flowing to the Jenkins head node. It may also be possible in the future to make the S3 bucket public so users can download build artifacts for their own use.
> [ci] Use S3 for artifacts

- tests/python/relay/test_pipeline_executor.py
RFC: https://github.com/apache/tvm-rfcs/blob/main/rfcs/0014-pipeline-executor.md
Issue: https://github.com/apache/tvm/issues/8596
Current unit test create 3 seperate module then re-connect them to run the pipeline executor. And this is not a real use case for pipeline executor.
Adding a manually graph splitting logic which split a full network into 3 subgraph then run the pipeline executor and verify the result to simulate the real use case .
> [Runtime][PipelineExecutor] Add graph manually splitting logic into the unit test.

- src/contrib/tf_op/tvm_dso_op_kernels.cc
- src/target/metadata.h
It may be safe to release POD-types array with `delete`
operator, but `delete[]` is always better.
> Fix array pointers releasing with `delete` operator

- src/relay/qnn/op/quantize.cc
I get a segment fault when I try to apply merge_composite on a dynamic quantize model.  
This seems to be because of the qnn.quantize type function cannot handle  IncompleteType. This PR fixes this issue using the similar approach used by other type functions.
cc @mbrookhart
> [Bugfix] Fix qnn.quantize type func with incomplete type

- python/tvm/tir/schedule/_type_checker.py
- tests/python/unittest/test_type_annotation_checker.py
Previously, `typing.Tuple` annotations could not be used with `tir.schedule._type_checker.type_checked` annotations.  This allows `Tuple` type annotations to be type-checked.
> [Schedule] Allowed typing.Tuple in tir.schedule._type_checker

- docker/Dockerfile.docs
- docker/build.sh
- tests/scripts/ci.py
This image includes everything necessary to build the docs without any tutorials and is just about 1.5 GB which is significantly less than the CPU/GPU images. This lands the image so we can get the pipeline moving but it'd also benefit from upgrading Docker in the base AMI so we can use the `--squash` arg to build and compress the layers.
cc @areusch
> [docs] Add lightweight docs image

- include/tvm/tir/builtin.h
- python/tvm/tir/tensor_intrin/__init__.py
- python/tvm/tir/tensor_intrin/cuda.py
- src/target/source/codegen_cuda.cc
- src/tir/op/builtin.cc
- src/tir/transforms/lower_warp_memory.cc
- tests/python/unittest/test_tir_schedule_tensorize_ldmatrix_mma.py
MMA and ldmatrix intrinsics were respectively added in https://github.com/apache/tvm/pull/9909 and https://github.com/apache/tvm/pull/10855, this PR enables using them together in a TIR schedule. I think this is a very cool example of using `transform_layout + tensorize` together to target very low-level instructions.
Writing many variants of intrinsic descriptions and their tensorized implemenations (different shape, data type, transposed or not etc) was very tedious, but still it was reasonably manageable thanks to recent improvements in TVMScript meta programming - see https://github.com/apache/tvm/pull/11097 and https://github.com/apache/tvm/pull/11324 and how they are exploited in `tir/tensor_intrin/cuda.py`. 
Of all the possible variants of MMA + ldmatrix combinations, only 6 of …
> [TIR] Support tensorization using ldmatrix + MMA

- include/tvm/meta_schedule/mutator.h
- include/tvm/meta_schedule/postproc.h
- include/tvm/meta_schedule/schedule_rule.h
- python/tvm/meta_schedule/mutator/__init__.py
- python/tvm/meta_schedule/mutator/mutate_thread_binding.py
- python/tvm/meta_schedule/schedule_rule/auto_bind.py
- python/tvm/meta_schedule/testing/conv2d_winograd_cpu.py
- python/tvm/meta_schedule/testing/conv2d_winograd_cuda.py
- python/tvm/meta_schedule/testing/schedule_rule.py
- python/tvm/meta_schedule/tune.py
- python/tvm/topi/cuda/conv2d_nhwc_winograd.py
- python/tvm/topi/cuda/conv2d_winograd.py
- python/tvm/topi/nn/conv2d.py
- src/meta_schedule/mutator/mutate_thread_binding.cc
- src/meta_schedule/postproc/rewrite_unbound_block.cc
- src/meta_schedule/schedule_rule/auto_bind.cc
- src/meta_schedule/schedule_rule/auto_bind.h
- src/meta_schedule/schedule_rule/winograd.cc
- tests/python/unittest/test_meta_schedule_custom_rule_winograd_cuda.py
- tests/python/unittest/test_meta_schedule_mutator_mutate_thread_binding.py
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_bind.py
The current meta-schedule uses a PostProc `RewriteUnboundBlock` to auto-bind blocks to threads. However, it's a post proc, which means there are no search opportunities, and always splits with `factor=1024`. 
This PR adds a new search rule called `AutoBind` to do a similar thing to bind threads with sampled factors. Also with a corresponding mutator. 
After applying this rule, we get some positive perf results (on RTX-3080):
Element-wise: from 2.76 us to 2.48 us
Conv2d Winograd: from 29.45 us to 18.96 us (ansor 22.00 us)
Resnet18: from  0.591 ms to 0.531 ms (ansor 0.565 ms)
cc @junrushao1994 @zxybazh @comaniac
> [MetaSchedule] AutoBind rule and MutateThreadBinding

- include/tvm/ir/attrs.h
All names beginning with two underscores are reserved for the compiler and standard library, even if they occur inside a class or namespace ([relevant stackoverflow](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)).  While I'm unaware of any existing issues this would cause, this avoids potential compiler incompatibility in the future.
> [IR] Renamed __VisitAttrs__ and __fvisit__ to non-reserved names

- src/meta_schedule/postproc/rewrite_parallel_vectorize_unroll.cc
- tests/python/unittest/test_meta_schedule_postproc_rewrite_parallel_vectorize_unroll.py
Previously, our auto-vectorization rule failed to vectorize some inner loops, making our CPU performance times slower than expected. This PR fixed a typo that causes this issue.
> [MetaSchedule] Enhance CPU auto vectorization

- src/relay/backend/contrib/cmsisnn/buffer_size.cc
- src/relay/backend/contrib/cmsisnn/buffer_size.h
- src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
- tests/cpp/relay/backend/contrib/cmsisnn/buffer_size_test.cc
- tests/python/relay/aot/test_crt_aot.py
Aligned intermediate buffer sizes needed by
Conv2D layer after moving to a newer version
of CMSIS-NN. Here is the related [PR.](https://github.com/apache/tvm/pull/11273)
> [CMSIS-NN] Aligned buffer sizes for Conv2D post CMSIS-NN SHA update

- python/tvm/script/parser.py
- python/tvm/tir/schedule/schedule.py
- tests/python/unittest/test_tir_transform_compact_buffer_region.py
- tests/python/unittest/test_tir_transform_flatten_buffer.py
- tests/python/unittest/test_tvmscript_complete.py
- tests/python/unittest/test_tvmscript_roundtrip.py
This PR fixes some TVMScript typos for block, which is written in legacy syntax.
cc @spectrometerHBH @junrushao1994
> [TVMScript] fix typo for block syntax

- src/arith/iter_affine_map.cc
Follow-up from https://github.com/apache/tvm/pull/11235, all error messages should be based on expressions that are not IterMapExpr.
cc @vinx13
> [Bugfix][TIR] Removed passing of IterMapExpr into PrettyPrint

- include/tvm/topi/elemwise.h
- python/tvm/relay/op/_tensor.py
- python/tvm/topi/math.py
- python/tvm/topi/x86/__init__.py
- python/tvm/topi/x86/math_alter_op.py
- tests/python/relay/test_op_level1.py
- tests/python/topi/python/test_topi_math.py
X86 targets don't have an FP16 erf intrinsic. This causes compilation to fail when such an op is encountered. This PR adds two cases to avoid this failure. I've added an FP16 ERF legalization pass that will just cast to FP32 for the ERF call. I've also extended fast_erf to support FP16 directly. This does lose some precision compared to doing FP32 wrapping around ERF, but since the desire is to be faster I think it's acceptable behavior.
> [Topi][Relay] Support for FP16 ERF on CPU.

- tests/python/unittest/test_arith_intset.py
Follow-up from https://github.com/apache/tvm/pull/11412, adding aregression test for the bugfix.
cc @vinx13 @junrushao1994
> [TIR] Regression test for PrettyPrint/IterMapExpr bugfix

- tests/scripts/task_build_hexagon_api.sh
Cleaning up last remaining usage of deprecated HEXAGON_SDK_PATH.
cc @mehrdadh
> [Hexagon] Use HEXAGON_SDK_ROOT in gtest path

- .github/workflows/merge.yml
- .gitignore
- tests/python/ci/sample_prs/pr10786-badci.json
- tests/python/ci/sample_prs/pr10786-changes-requested.json
- tests/python/ci/sample_prs/pr10786-co-authors.json
- tests/python/ci/sample_prs/pr10786-invalid-author.json
- tests/python/ci/sample_prs/pr10786-merges.json
- tests/python/ci/sample_prs/pr10786-missing-job.json
- tests/python/ci/sample_prs/pr10786-nottriggered.json
- tests/python/ci/sample_prs/pr10786-oldreview.json
- tests/python/ci/sample_prs/pr11244-unauthorized-comment.json
- tests/python/ci/sample_prs/pr11267-no-review.json
- tests/python/ci/sample_prs/pr11276-no-review.json
- tests/python/ci/test_mergebot.py
- tests/scripts/git_utils.py
- tests/scripts/github_mergebot.py
This implements https://discuss.tvm.apache.org/t/rfc-allow-merging-via-pr-comments/12220. The bot can be invoked from a top-level review comment or via a regular PR comment. The text `@tvm-bot merge` anywhere in the body will trigger the bot. Right now it checks that the latest commit is reviewed and that all CI jobs that have run on that commit are successful. If it fails, it will leave a comment on the PR with the reason.
This is just a start and some features are left for followups:
* Various TODOs throughout the code
* "Scheduled" merges that happen once CI finishes
* Allowing committers to merge without getting a fresh review for changes after an approval
Test PRs
Description | Link
------ | -----
ci passed: no, then yes<br>approved: no, then yes  | …
> [ci] Add GitHub Actions bot to merge PRs on demand

- python/tvm/tir/schedule/_type_checker.py
- tests/python/unittest/test_type_annotation_checker.py
When type checking for params of `Union` type fails, another error occurs when printing error message. This PR fixed it.
> Fix type checking annotation for Union type

- include/tvm/runtime/c_runtime_api.h
- src/runtime/minrpc/minrpc_server.h
- src/runtime/minrpc/minrpc_server_logging.h
- src/runtime/rpc/rpc_channel_logger.h
- src/support/socket.h
- src/support/ssize.h
This PR removes the type tvm_ssize_t introduced in ([PR11232](https://github.com/apache/tvm/pull/11232/)) , and unifies the definition of ssize_t.
Initially, there was an issue with the Windows build in ([PR10967](https://github.com/apache/tvm/pull/10967)) , since the ssize_t was not properly defined in rpc_channel_logger.h 
our initial solution was to define the ssize_t in that specific file. but we got a redefinition error, since ssize_t was also defined in socket.h. We also tried to include socket.h in rpc_channel_logger.h but we got some errors on hexagon build. ([PR11223](https://github.com/apache/tvm/pull/11223))
Next attempt, we added another type, tvm_ssize_t, in c_runtime_api.h to resolve the redefinition issue ([PR11232](https://github.com/apache/tvm/pull/11232/)) and the plan …
> unify ssize_t definition

- src/tir/transforms/compact_buffer_region.cc
- tests/python/unittest/test_tir_transform_compact_buffer_region.py
When we use `EstimateRegionLowerBound` to determine allocation extents, sometimes it gives "too accurate" dynamic region extents (dependent by outer loop vars).  However, the lowering (`StorageRewrite`) would lift buffer allocation to the global scope, bring the loop vars out of it's def scope illegally.
For the padded and tiled pooling case in the test, the h-dimension's region extent could be infered as `h_o * 8 + 8 - max(h_o * 8 - 1, 0)`, it is correct since with padding, the edge tiles do not need same buffer size as others. (h_o = 0 => extent = 8, h_o > 0 => extent = 9). But the dynamic allocation for this extent expression can not get properly handled afterwards... 
Here is just one work-around, very glad to see any robust solutions. @Hzfengsy @spectrometerHBH
> [TIR] Avoid loop dependent allocation in buffer compaction

- tests/python/frontend/paddlepaddle/test_forward.py
- tests/python/unittest/test_auto_scheduler_evolutionary_search.py
- tests/scripts/ci.py
Actually tested locally this time via, both tests are successfully skipped
```bash
python tests/scripts/ci.py gpu \
--tests tests/python/frontend/paddlepaddle/test_forward.py::test_forward_group_norm \
--tests tests/python/unittest/test_auto_scheduler_evolutionary_search.py::test_mutate_parallel
```
> [skip ci][ci] Fix broken test skips

- tests/python/contrib/test_hexagon/benchmark_hexagon.py
- tests/python/contrib/test_hexagon/benchmark_util.py
Generalize the benchmark-table code to support arbitrary
independent values. This supports future changes to the benchmark
code.
cc @mehrdadh
> [hexagon][testing] refactor benchmark-table code

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
This work has mostly been done by @vdkhoi Khoi Duy Vo from ETAS Gmbh.
We add parser support for UnidirectionalSequenceLSTM layers in tflite.
A question regarding the test: 
At the moment it uses a toy model that I store in a repo in my github account.
Should we copy this to the TVM repo or what is the best way to do this?
> Add unidirectional sequence lstm

- python/tvm/relay/frontend/tflite.py
tuple cannot be set because it is immutable. I was running a network that had a dense layer with 3D input. Very minimal fix!
@mbrookhart
> fixed tuple error

- python/tvm/_ffi/_cython/base.pxi
- python/tvm/_ffi/_cython/ndarray.pxi
- python/tvm/_ffi/_cython/object.pxi
- python/tvm/_ffi/_cython/packed_func.pxi
- python/tvm/testing/popen_pool.py
- src/support/ffi_testing.cc
Unlike ctypes, Cython by default do not release GIL when
calling into C API functions. This causes problems when the
function is long running. As the particular calling thread will
block other python threads by holding the GIL.
This PR explicitly releases GIL when calling into possible
long running functions. It fixes the timeout issue in
PopenPool which previously relied on another python thread
for timeout.
This PR is covered by a regression test-case by changing time.sleep to sleep
in FFI, which previously will indefinitely block the popen tests.
> [FFI][CYTHON] Release GIL when calling into long running functions

- Jenkinsfile
- jenkins/Build.groovy.j2
- jenkins/DockerBuild.groovy.j2
- jenkins/Lint.groovy.j2
- jenkins/Prepare.groovy.j2
- jenkins/Test.groovy.j2
- jenkins/macros.j2
Before this would leave around any image that could be used in CI. This PR changes it so that the `docker rmi` knows exactly which image is being used in CI so all others (even those that are being used in the same build but not currently on that node) are deleted
This also adds some more logging so we can see what's going on and should help keep disk usage down. Skipped CI since this runs during lint.
> [skip ci][ci][docker] Prune all non-relevant images

- Jenkinsfile
- jenkins/Build.groovy.j2
- jenkins/DockerBuild.groovy.j2
- jenkins/Lint.groovy.j2
- jenkins/Prepare.groovy.j2
- jenkins/Test.groovy.j2
- jenkins/macros.j2
This reverts commit c25305354199dd9b7e29d6a92a2301638559d811.
> [skip ci] Revert "[skip ci][ci][docker] Prune all non-relevant images (#11491)"

- Jenkinsfile
- jenkins/Prepare.groovy.j2
This adds more time to the timeouts for fetching git modules and moves the logic from groovy into bash. This should help with issues like https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3375/pipeline/423#step-1396-log-1 by making them happen less often and making it more clear what went wrong (Jenkin's `retry` doesn't say what it's doing in the blueocean step logs)
> [ci] Increase timeout for git submodule update

- python/tvm/contrib/debugger/debug_executor.py
- python/tvm/meta_schedule/testing/custom_builder_runner.py
- python/tvm/meta_schedule/testing/tune_relay_auto_scheduler.py
- python/tvm/meta_schedule/testing/tune_relay_meta_schedule.py
- tests/python/unittest/test_meta_schedule_tune_tir.py
This PR intends to fix the issues in `tune_relay_meta_schedule.py` and `tune_relay_auto_schedule.py` for handling models with more than one input, like `bert`.
cc @zxybazh @junrushao1994 @AndrewZhaoLuo
> [Meta Schedule] Fix testing issues for models with more than one inputs

- python/tvm/driver/build_module.py
- python/tvm/target/target.py
It turns out build_module.py will manufacture a host out of thin air, in which case the
warning is Target.canon_target_map_and_host is wrong headed.
Also make sure we only complain if the passed target host is actually used.
> Silence unnecessary 'host' deprecation warnings

- python/tvm/testing/tir.py
- python/tvm/tir/tensor_intrin/cuda.py
- src/tir/transforms/inject_software_pipeline.cc
- tests/python/unittest/test_tir_schedule_tensorize_ldmatrix_mma.py
- tests/python/unittest/test_tir_transform_inject_software_pipeline.py
Fix a hardcoded index in `access_ptr` rewriting, which assumes that the number of stages is 2.
Refactored MMA code in [test_tir_schedule_tensorize_ldmatrix_mma.py](https://github.com/apache/tvm/pull/11495/files#diff-c57055a7e086b01384ea58abb7e2126904427357e02ec6ff5369360d344dfe0b), so that it can be used by other tests. The new test in `test_tir_transform_inject_software_pipeline.py` applies software pipelining annotations to the MMA-tensorized schedule with `software_pipeline_stage = [0, 0, 3]`, which makes global to shared load pipelined with depth 4. Without async copy, this is not useful for performance. But it does demonstrate that a multi-stage pipeline with depth > 2 works on a semi-realistic GPU schedule.
The test uses large dynamic shared memory, which serves as a test case for …
> [Software pipeline] Fix hardcoded index in `access_ptr` rewriting, add a GPU test with depth 4

- include/tvm/tir/schedule/schedule.h
- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/analysis.h
- src/tir/schedule/analysis/analysis.cc
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/layout_transformation.cc
- src/tir/schedule/primitive/loop_transformation.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- src/tir/schedule/transform.cc
- src/tir/schedule/transform.h
- tests/python/unittest/test_tir_schedule_transform_layout.py
This PR added a schedule primitive `transform_block_layout` to transform the block items and the outer loops. It can be used to perform im2col-like transformations.
cc @spectrometerHBH @junrushao1994
> [TIR] Add schedule primitive TransformBlockLayout

- include/tvm/ir/transform.h
- src/ir/transform.cc
- tests/cpp/pass_immutable_module_test.cc
This PR adds a utility for testing purposes that asserts an IRModule used as input to a pass is not modified in place.
The `testing.immutable_module` option can be set to true in a `PassContext` to enable the assertion.
> Add utility that asserts that input IRModule is not mutated in a pass.

- include/tvm/tir/op.h
- src/tir/ir/expr.cc
- src/tir/op/op.cc
- tests/cpp/expr_test.cc
var->type_annotation may be empty when only `runtime::DataType` is passed to the constructor. This PR added canonicalization during the construction of `Var` and `SizeVar`, so that `Var(dtype="float32", type_annotation=PrimType(Float(32)))` is equivalent to `Var(dtype="float32", type_annotation=None)`.
The printer side for `Var` and `SizeVar` is not affected and doesn't need update.
`ReprPrinter` always omit type information: https://github.com/apache/tvm/blob/main/src/tir/ir/expr.cc#L120
`TextPrinter` has already been implicitly converting from `runtime::DataType` to `Type`: https://github.com/apache/tvm/blob/main/src/printer/tir_text_printer.cc#L782
cc @tqchen
> Canonicalize type annotation during construction of Var and SizeVar

- python/tvm/relay/frontend/pytorch_utils.py
I encountered a quirk today when using the PyTorch importer. My local PyTorch version is 1.5.1 and it uses Cuda (10.1 on my system), so `torch.__version__` returns `1.5.1+cu101`.
When I used the importer I encountered the following error:
```
File "/home/sslyu/tvm/python/tvm/relay/frontend/pytorch.py", line 4064, in from_pytorch
_run_jit_passes(graph, enable_lower_all_tuples)
File "/home/sslyu/tvm/python/tvm/relay/frontend/pytorch.py", line 3637, in _run_jit_passes
torch._C._jit_pass_onnx_function_substitution(graph)
AttributeError: module 'torch._C' has no attribute '_jit_pass_onnx_function_substitution'
```
That is because PT version 1.5.1 doesn't have that function. In principle, the importer should check for that and not use that function for versions that don't have it, which is the …
> [Frontend][PyTorch][Bugfix] Ignore Cuda in PyTorch version number when comparing versions

- Jenkinsfile
- jenkins/Build.groovy.j2
- jenkins/DockerBuild.groovy.j2
- jenkins/Lint.groovy.j2
- jenkins/Prepare.groovy.j2
- jenkins/Test.groovy.j2
- jenkins/macros.j2
(this is a re-do of #11491)
Before this would leave around any image that could be used in CI. This PR changes it so that the `docker rmi` knows exactly which image is being used in CI so all others (even those that are being used in the same build but not currently on that node) are deleted
This also adds some more logging so we can see what's going on and should help keep disk usage down. Skipped CI since this runs during lint.
> [ci][docker] Prune all non-relevant images

- include/tvm/arith/iter_affine_map.h
- python/tvm/arith/iter_affine_map.py
- src/arith/int_set.cc
- src/arith/iter_affine_map.cc
- src/arith/pattern_match.h
- src/arith/rewrite_simplify.cc
- src/arith/rewrite_simplify.h
- src/tir/ir/buffer.cc
- src/tir/ir/index_map.cc
- src/tir/schedule/analysis/analysis.cc
- src/tir/schedule/analysis/layout.cc
- src/tir/schedule/primitive/blockize_tensorize.cc
- src/tir/schedule/primitive/compute_at.cc
- src/tir/schedule/primitive/compute_inline.cc
- src/tir/schedule/primitive/layout_transformation.cc
- src/tir/schedule/primitive/loop_transformation.cc
- tests/python/unittest/test_arith_iter_affine_map.py
- tests/python/unittest/test_arith_rewrite_simplify.py
- tests/python/unittest/test_tir_buffer.py
- tests/python/unittest/test_tir_schedule_compute_at.py
Update a simplify rule when c2 is nonzero,  original rule is covered with constant folding.
`floormod(x * c1, c2)` => 
`floormod(x * (floordiv(c1, c2) * c2 + floormod(c1, c2)), c2)` => 
`floormod(x * floormod(c1, c2)), c2)`
This is useful for certain non-perfect tiling case, where there are dynamic loop ranges which is actually constant wrt outer loop domain.
For example, `floordiv(floormod(x * 360, 16) + 359, 16)` with x in [0, 2) can finally reduce to constant `22`, since the rule could eliminate the multiply factor `360` to `360 % 16`, activating more available rules.
Unfortunately the working example on tiling encounter a region_cover related problem again.
> [Arith] Merge surjective/non-surjective iter mapping detections

- tests/python/contrib/test_ethosu/cascader/test_scheduler.py
Fixes non-deterministic test by disabling striping when running the cascader.
Previously the test was failing ~1/10 times. Tested with changes locally by repeating the test 100 times, all of which pass. Closes #11483.
cc @Mousius @NicolaLancellotti @ekalda @manupa-arm
> [microNPU] Fix flaky compute cycle annotation test

- python/tvm/meta_schedule/relay_integration.py
- python/tvm/te/__init__.py
- python/tvm/te/operation.py
- src/relay/backend/task_extraction.cc
- src/te/operation/create_primfunc.cc
- src/te/operation/create_primfunc.h
- src/tir/schedule/concrete_schedule.cc
- tests/python/unittest/test_meta_schedule_integration.py
This PR allows `relay.backend.MetaScheduleExtractTask` to take an extra argument `filter_func` which filters out unintentional tasks that don't need tuning. The counterpart of AutoScheduler is within `traverse_to_get_io_tensors`.
> [MetaSchedule] Enable Task Filtering

- include/tvm/runtime/module.h
- src/runtime/module.cc
Hi, i find ModuleNode::GetFuncFromEnv will read from and write to one std::unordered_map<std::string, std::shared_ptr<PackedFunc> > import_cache_; by multi thread. As the class instance created with constexpr const char* tvm_module_ctx = "__tvm_module_ctx";
> [BugFix] Add lock for ModuleNode::GetFuncFromEnv

- python/tvm/contrib/ethosu/cascader/device_config.py
- python/tvm/relay/backend/contrib/ethosu/te/identity.py
- tests/python/contrib/test_ethosu/cascader/test_ethosu_identity_matcher.py
- tests/python/contrib/test_ethosu/test_codegen.py
This commit adds support for the identity operator in the cascader.
@manupa-arm @ekalda @lhutton1 
cc @Mousius
> [microNPU] Add transform matrices and part matcher to identity op

- tests/python/relay/strategy/arm_cpu/test_avg_pool.py
- tests/python/relay/strategy/arm_cpu/test_conv1d_ncw.py
- tests/python/relay/strategy/arm_cpu/test_conv1d_nwc.py
- tests/python/relay/strategy/arm_cpu/test_conv2d_NCHWc.py
- tests/python/relay/strategy/arm_cpu/test_dense_dsp.py
- tests/python/relay/strategy/arm_cpu/test_depthwise_conv2d_NCHWc.py
- tests/python/relay/strategy/arm_cpu/test_max_pool.py
This PR adds relay level tests for various schedules, continuing the work started in [PR11250](https://github.com/apache/tvm/pull/11250). 
@mehrdadh
> [microTVM][ARM]Add tests for arm schedules

- src/runtime/ndarray.cc
During developing #11003 #11391 It was observed that DLTensor should satisfy some conditions (data contiguous and alignment) for correct construction of NDArray based on it to avoid problems with memory using.
Further analysis of NDArray class methods showed the same problem in other public method. There is fix of it.
@tkonolige could you check it?
> [VM] check DLManagedTensor for conditions to construct NDArray

- src/meta_schedule/task_scheduler/task_scheduler.cc
- src/te/operation/create_primfunc.cc
- tests/python/unittest/test_te_create_primfunc.py
For 0-dimensional computation, `te.CreatePrimFunc` creates an opaque block with 0 block iters, which is mistakenly passed into TVMScript auto-completion that failed to add the root block properly. As an example,
```python
>> from tvm import te
>> a = te.placeholder((), name="a", dtype="int32")
>> b = te.placeholder((), name="b", dtype="int32")
>> c = te.compute(a.shape, lambda *i: a(*i) + b(*i), name="c")
>> f = te.create_prim_func([a, b, c])
>> print(f.body.block.reads)
[a[], b[]]
>> print(f.body.block.writes)
[c[]]
```
This PR fixes this issue by enforcing the consistency that `te.CreatePrimFunc` always creates scheduleable blocks with at least 1 block iter:
```python
@T.prim_func
def func(a: T.Buffer[(), "int32"], b: T.Buffer[(), "int32"], c: T.Buffer[(), "int32"]) -> None: …
```
> [TE] Fix `tvm.te.CreatePrimFunc` for 0-dim computation

- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- src/runtime/contrib/dnnl/dnnl_tensor_requisite.h
- src/runtime/contrib/dnnl/dnnl_utils.cc
- src/runtime/contrib/dnnl/dnnl_utils.h
**Summary**
There are several limitation which prevent DNNL runtime from using in multi instance mode. This patch tries to eliminate some of them.
Multi instance mode means: call Run() method concurrently from several threads for single instance of DNNLJSONRuntime. 
Particularly changed for multi instance support:
* Do not modify DNNLJSONRuntime fields from Run method. Make it like a "const" method.
* Use explicit dnnl scratchpads where it requested.
* Make Intermediate tensors collection individual for each thread.
Other improvements:
* Zero copy handling of Input/Output tensors
* Use query API to ask DNNL about desired layouts. Prevent from using of unoptimised kernels.
* Automatic injection or reorder primitives if layout doesn't match.
* Support of different data types (int8, uint8, …
> [DNNL] Add TensorRequisite concept. Multi instance support

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
Completed with reference to the tutorial presented at tvmconf: https://www.youtube.com/watch?v=fZvNG-oKK5Q&amp;t=20s
Onnx uses an abnormal round operator where .5 is rounded to the nearest even integer, which differs comparative to other round definitions.
@MargaretQian @jwfromm @sfvaroglu
> [Onnx] Round operator

- src/meta_schedule/schedule_rule/parallel_vectorize_unroll.cc
- src/tir/schedule/analysis.h
- src/tir/schedule/analysis/analysis.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_parallel_vectorize_unroll.py
This PR skips the unrolling for purely spatial PrimFuncs and let the underlying target compiler to handle. This behavior is consistent with AutoScheduler.
> [MetaSchedule] No explicit unrolling for spatial PrimFunc

- Jenkinsfile
- jenkins/Test.groovy.j2
Keeping the files as-is lets us serve them from S3 + CloudFront e.g. https://d3f1x5ne0bf47p.cloudfront.net/tvm/PR-11528/2/docs/index.html. The tar is still around to provide an easy way to get the whole site for users / later CI jobs.
> [ci] Upload docs with folder structure to S3

- src/arith/const_int_bound.cc
- src/arith/constraint_extract.cc
- src/arith/constraint_extract.h
- src/arith/modular_set.cc
- src/arith/rewrite_simplify.cc
- src/arith/rewrite_simplify.h
- tests/python/unittest/test_tir_transform_simplify.py
This adds additional simplifications to `RewriteSimplifier` while inside a conditional statement.  These are simplifications that are expected to be necessary for simplifying conditionals for padding buffer transforms.  The main additions are below:
* Use of `RewriteSimplifier::literal_constraints_` for simplifications of boolean expressions.  Previously, this was only used for simplifications inside a `tir.likely` annotation.
* Use of `RewriteSimplifier::literal_constraints_` to identify known false constraints.  This allows a constraint of `i!=n` to simplify `i==n` to false.
* Use of `EqNode` constraints in `ConstIntBoundAnalyzer`.  Previously, inequalities were used as comparisons.  With this change an `i==5` constraint be used to reduce the bounds of `i` to `[5,5]`.
> [TIR][Arith] Additional Simplifications Inside Conditionals

- python/tvm/utils/roofline.py
- tests/python/unittest/test_runtime_profiling.py
Somehow the runtime was dropped from the percent compute bound calculation. Tolerances on the test we bumped a little bit higher to try and catch mistakes like this in the future.
@AndrewZhaoLuo
> [PROFILER] Fix percent compute bound calculation

- docker/Dockerfile.ci_gpu
- docker/install/ubuntu_install_tensorflow.sh
- docker/install/ubuntu_install_tensorflow_aarch64.sh
Context is in the attached bug.
cc @driazati @tqchen @jwfromm
> Unbreak CI image build (tensorflow 2.6.5, ci_gpu bugfix)

- .github/workflows/tvmbot.yml
- tests/scripts/git_utils.py
These weren't caught by `actionlint` for some reason but GitHub doesn't merge multiple `if`s, so this combines them into one. This also has some small code fixes to get the rerun requests sent.
> [ci] Fix action expressions for tvm-bot workflow

- include/tvm/ir/expr.h
- include/tvm/relay/attrs/call.h
- include/tvm/relay/function.h
- python/tvm/relay/transform/transform.py
- src/ir/expr.cc
- src/parser/tokenizer.h
- src/relay/backend/te_compiler.cc
- src/relay/backend/vm/compiler.cc
- src/relay/ir/function.cc
- src/relay/op/nn/nn.cc
- src/relay/transforms/compiler_function_utils.cc
- src/relay/transforms/compiler_function_utils.h
- src/relay/transforms/dead_code.cc
- src/relay/transforms/inline.cc
- tests/python/relay/transform/test_compiler_function_utils.py
(See https://discuss.tvm.apache.org/t/byoc-supporting-cutlass-byoc-with-collage/12796/6 for
context, which in turn is part of Collage (https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md).
For reasons explained in the above thread I'm moving CUTLASS to be IRModule-at-a-time external codegen
using a custom RelayToTIR pass instead of the traditional function-at-a-time external codegen using
a relay.ext.cutlass registered function. This means some of the rewriting done on-the-fly by LowerTEPass now
needs to be done by the custom pass directly. This PR supplies two passes which ease that burden:
- Before starting the extern-codegen specific processing, make sure all "Compiler" attributed functions have
unique global definitions (ie are outlined). Though functions start in this …
> [BYOC] Two helper passes for external codegen using RelayToTIR custom pass machinery

- docker/install/ubuntu_install_hexagon.sh
Update to LLVM 14.0.0 release for ci_hexagon docker image.
> [CI] Update to LLVM 14.0.0 for ci_hexagon

- apps/microtvm/arduino/template_project/microtvm_api_server.py
- apps/microtvm/pyproject.toml
- docker/install/ubuntu_install_sphinx.sh
- docs/conf.py
- gallery/how_to/work_with_microtvm/micro_train.py
- tests/scripts/ci.py
- tests/scripts/task_python_docs.sh
This PR adds a new tutorial to the microTVM how_to gallery, showing how a MobileNet V1 model can be trained with transfer learning and modified to fit on embedded devices (in this case, the Arduino Nano 33 BLE). This tutorial also addresses #10706 by showing what it would take to allow tutorials to be opened using Google Colab. See the below screenshot, or view the HTML page at the link below:
Alternatively, to make it easier I've also copied the output HTML file, and hosted it at the following link:
https://guberti.github.io/tvm-docs-proof-of-concept/
> [docs] microTVM model training tutorial with Colab support

- include/tvm/tir/schedule/schedule.h
- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/loop_transformation.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- tests/python/unittest/test_tir_schedule_split_fuse.py
In TE, a unit loop could be introduced by fusing an empty list of loops on a stage. This PR adds its counterpart in TIR, while being a bit more explicit with a new schedule primitive which adds a unit loop without impacting any existing functionalities.
> [TIR] Schedule Primitive: Add-Unit-Loop

- src/meta_schedule/schedule_rule/auto_bind.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_bind.py
Following #11575, this PR allows CUDA thread binding for TIR programs
like
```python
@T.prim_func
def zero_dim_add(
A: T.Buffer[(), "float32"],
B: T.Buffer[(), "float32"],
C: T.Buffer[(), "float32"],
) -> None:
vi = T.axis.spatial(1, 0)
C[()] = A[()] + B[()]
```
where there is no loop available to be bound to threadIdx/blockIdx.
> [MetaSchedule] Use Add-Unit-Loop in Auto-Bind

- include/tvm/arith/iter_affine_map.h
- src/arith/iter_affine_map.cc
- src/tir/schedule/primitive/loop_transformation.cc
- tests/python/unittest/test_meta_schedule_postproc_rewrite_cooperative_fetch.py
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_bind.py
- tests/python/unittest/test_tir_schedule_reorder.py
- tests/python/unittest/test_tir_schedule_split_fuse.py
- tests/python/unittest/test_tir_schedule_transform.py
@vinx13 @jinhongyii and I observe a recent regression on TVM mainline: over-simplification in `Schedule.split` leads to information loss that negatively impacts search space generation.
**Impact.** This affects common operators like `softmax` and even simpler reductions.
**Example.** Consider splitting a simple reduction loop:
```python
@T.prim_func
def main(
A: T.Buffer[2, "float32"],
B: T.Buffer[2, "float32"],
C: T.Buffer[(), "float32"],
) -> None:
for i in T.serial(2):   # <= split `i` into `i_0` and `i_1`, where `i_0` is a trivial loop
k = T.axis.reduce(2, i)
with T.init():
C[()] = T.float32(1)
C[()] = T.min(C[()], A[k] / B[k])
```
Splitting loop `i`  by factors `[1, 2]`, we get:
```python
@T.prim_func
def main(
A: T.Buffer[2, "float32"],
B: T.Buffer[2, "float32"], …
```
> [TIR] Prevent loop binding over-simplification

- src/tir/schedule/primitive/compute_at.cc
- src/tir/schedule/primitive/loop_transformation.cc
- tests/python/unittest/test_tir_schedule_compute_at.py
- tests/python/unittest/test_tir_schedule_split_fuse.py
The schedule primitives, including compute-at, fuse and split usually
generate loop variables with `dtype=int32` as default. However, in some
models, there are usecases where int64 are part of tensor shapes, which
leads to unexpected behavior in scheduling. This PR brings the fix to
existing known issues.
> [Bugfix][TIR] compute-at/fuse/split dtype mismatch

- python/tvm/meta_schedule/tune_context.py
- src/meta_schedule/tune_context.cc
I exposed the initialize() method for TuneContextNode on the C++ side and added a corresponding method to TuneContext class on the Python side, so that we do not need to call initialize_with_tune_context for every scheduling rule.
> [MetaSchedule] exposed method: TuneContextNodeInitialize

- src/meta_schedule/task_scheduler/gradient_based.cc
Previously for invalid tasks, MetaSchedule prints a huge number in
latency which is aesthetically unacceptable. For example,
```
69 |  fused_cast_add_cast_3 | 16777216 | 2 | 0.0000 | 10000000000000000019156750857346687362159551272651920111528035145993793242039887559612361451081803235328.0000 | 20000000000000000038313501714693374724319102545303840223056070291987586484079775119224722902163606470656.0000 |     64 |
```
This PR fixes this behavior and turns the huge number into "N/A".
> [Minor][MetaSchedule] Fix Summary Format for Invalid Runs

- tests/python/frontend/paddlepaddle/test_forward.py
Better verification of unit test problems:
https://github.com/apache/tvm/issues/9976#issuecomment-1144363327
> [Frontend][PaddlePaddle]split test_forward_math_api function

- src/relay/quantize/realize.cc
Fix a minor problem with batch matmul quantization realize.
If the two inputs are cast into the same data type, no vnni implementation will be added to batch_matmul x86 strategy.
(In /python/tvm/relay/op/strategy/x86.py, function batch_matmul_strategy_cpu)
> [Relay][OP] Fix batch matmul quantization implementation

- python/tvm/relay/backend/contrib/ethosu/legalize.py
- tests/python/contrib/test_ethosu/test_codegen.py
All codegen tests have been running with a representative dataset between 0,1 which masked an output mismatch in Leaky ReLU when compared to TFLite kernels. This issue can be replicated by replacing the representative dataset range with something like -1,1.
To fix this mismatch, we use the same implementation for calculating LUT values as Vela which uses arithmetic constrained to quantized values, rather than the previously used floating point calculations.
cc @Mousius @NicolaLancellotti @ekalda @manupa-arm
> [microNPU] Fix output mismatch in Leaky ReLU

- python/tvm/relay/op/contrib/ethosu.py
- tests/python/contrib/test_ethosu/infra.py
- tests/python/contrib/test_ethosu/test_codegen.py
- tests/python/contrib/test_ethosu/test_legalize.py
Optimizes a case where padding appears as a separate nn.pad operation followed by a qnn.conv2d. If possible, the nn.pad will be partitioned and offloaded together with the qnn.conv2d operation, as opposed to separately. As a fallback, both operations will be considered separately.
cc @Mousius @NicolaLancellotti @ekalda @manupa-arm
> [microNPU] Optimize separate padding operation for conv2d

- include/tvm/runtime/profiling.h
- python/tvm/runtime/profiling/__init__.py
- python/tvm/utils/roofline.py
- src/node/structural_hash.cc
- src/runtime/graph_executor/debug/graph_executor_debug.cc
- src/runtime/profiling.cc
- src/runtime/vm/profiler/vm.cc
- tests/python/unittest/test_runtime_profiling.py
Configuration is a place to store extra information related to the specific profiler run. Right now it is just the executor used and the number of threads. The roofline analysis also adds peak flops and peak bandwidth.
In the future I'd like to add information about the target, but it would have to be piped through the compiled library.
@AndrewZhaoLuo  @areusch
> [PROFILER] Add configuration information to profiler

- include/tvm/meta_schedule/search_strategy.h
- include/tvm/meta_schedule/task_scheduler.h
- include/tvm/meta_schedule/tune_context.h
- python/tvm/meta_schedule/search_strategy/search_strategy.py
- python/tvm/meta_schedule/task_scheduler/gradient_based.py
- python/tvm/meta_schedule/task_scheduler/round_robin.py
- python/tvm/meta_schedule/task_scheduler/task_scheduler.py
- src/meta_schedule/measure_callback/add_to_database.cc
- src/meta_schedule/search_strategy/evolutionary_search.cc
- src/meta_schedule/search_strategy/replay_func.cc
- src/meta_schedule/search_strategy/replay_trace.cc
- src/meta_schedule/search_strategy/search_strategy.cc
- src/meta_schedule/task_scheduler/gradient_based.cc
- src/meta_schedule/task_scheduler/round_robin.cc
- src/meta_schedule/task_scheduler/task_scheduler.cc
- tests/python/unittest/test_meta_schedule_measure_callback.py
- tests/python/unittest/test_meta_schedule_search_strategy.py
- tests/python/unittest/test_meta_schedule_task_scheduler.py
Per discussion with @Kathryn-cat, we realized that the current API
design could be verbose if we only want to tune a single task, in which
case a dummy task scheduler still needs to be established to supply
`EvolutionarySearch` with proper `CostModel` and `Database`. This PR
fixes this UX issue.
> [MetaSchedule] Evo Independence from TaskScheduler

- src/relay/transforms/fold_explicit_padding.cc
- tests/python/relay/test_pass_fold_explicit_padding.py
Fix uint-min (=0) case capture for folding pad into MaxPool in the FoldExplicitPadding pass
> [FIX] FoldExplicitPadding uint MaxPool case

- python/tvm/topi/generic/nn.py
- python/tvm/topi/nn/__init__.py
- python/tvm/topi/nn/lstm.py
- python/tvm/topi/testing/__init__.py
- python/tvm/topi/testing/lstm_python.py
- tests/python/topi/python/test_topi_lstm.py
This PR adds a TE implementation of LSTM (with optional modifications, similar to those in https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/common.py#L774), using the `te.scan` construct (so that the recurrent loop is truly a sequential loop, rather than unrolled statically). This compute should support symbolic sequence length.
Missing from this PR:
- optimized schedule for any target
- corresponding higher-level Relay op
- attempts to use metaschedule (more on this later)
I'll send a follow-up PR for the Relay op, but scheduling the LSTM might take a while (if anyone is interested, please feel free to take a stab!). The main thing to optimize is the dense operations within the kernel (the initial input-hidden dense, recurrent hidden-hidden dense, and hidden-projection …
> [TOPI] TE implementation of LSTM using scan

- python/tvm/meta_schedule/testing/tune_onnx_auto_scheduler.py
- python/tvm/meta_schedule/testing/tune_onnx_meta_schedule.py
- python/tvm/meta_schedule/testing/tune_relay_auto_scheduler.py
This PR introduces 2 tuning script for meta schedule and auto scheduler tuning support with onnx files. Now we can easily introduce onnx models benchmarking with command line scripts. Sample tuning call looks similar to the following script
For Meta Schedule ONNX tuning:
```
python3 -m tvm.meta_schedule.testing.tune_onnx_meta_schedule \
--model-name   "$MODEL_NAME"                             \
--onnx-path    "$ONNX_PATH"                              \
--input-shape  "$INPUT_SHAPE"                            \
--target       "$TARGET"                                 \
--num-trials   $NUM_TRIALS                               \
--rpc-host     $RPC_HOST                                 \
--rpc-port     $RPC_PORT                                 \
--rpc-key      $RPC_KEY …
```
> [MetaSchedule] Add Testing Script with ONNX Support

- src/relay/transforms/compiler_function_utils.cc
- src/relay/transforms/compiler_function_utils.h
Add missing virtual destructor for derived class
`tvm::relay::transforms::ExistingGlobalSymbolCache`.
Fixes a potential problem when deleting an instance
using a pointer-to-base-class.
> [relay] Fix missing virtual destructor

- python/tvm/contrib/hexagon/_ci_env_check.py
- python/tvm/contrib/hexagon/pytest_plugin.py
- python/tvm/testing/utils.py
These were enabled in https://github.com/apache/tvm/pull/11294, then erroneously disabled in https://github.com/apache/tvm/pull/11313.  This applies the same fix as in https://github.com/apache/tvm/pull/11294, checking the `ANDROID_SERIAL_NUMBER` to determine if Hexagon tests can execute at runtime, but using the refactored `pytest.skipif` messages introduced in https://github.com/apache/tvm/pull/11313.
cc @Mousius @areusch @driazati @mehrdadh
> [Hexagon][CI] Re-enable Hexagon tests in CI

- src/runtime/contrib/tensorrt/tensorrt_runtime.cc
Before the fix, after `GetCachedEnginesFromDisk()`, `max_batch_size_` is `-1` which results in the [batch_size <= max_batch_size_](https://github.com/apache/tvm/blob/main/src/runtime/contrib/tensorrt/tensorrt_runtime.cc#L258) to be `False`. Engine will be rebuilt because [find_engine_flag](https://github.com/apache/tvm/blob/main/src/runtime/contrib/tensorrt/tensorrt_runtime.cc#L276) is `False`.
Log before the fix:
```
[19:41:41] /home/ubuntu/neo-ai/apache_tvm/tvm/src/runtime/contrib/tensorrt/tensorrt_runtime.cc:356: Loading cached TensorRT engine from ./tvmgen_default_tensorrt_main_0_fp32.plan
[19:41:43] /home/ubuntu/neo-ai/apache_tvm/tvm/src/runtime/contrib/tensorrt/tensorrt_runtime.cc:379: finished saving engine and context ... 
[19:41:43] …
```
> [BYOC][TENSORRT] minor fix after loading trt engine from disk

- src/relay/ir/dataflow_matcher.cc
- src/relay/ir/dataflow_matcher_impl.h
- tests/python/contrib/test_cutlass.py
- tests/python/relay/test_dataflow_pattern.py
I goofed in #11481 in moving a dominates check to
an ICHECK (and I'm confused how it got through ci?).
It is ok to match a sub-graph which has dataflow
outside of the sub-graph, provided all such flows
eventually come back into the sub-graph.
> [Relay] Restore dominator check

- src/runtime/hexagon/rpc/simulator/rpc_server.cc
The simulator library `libhexagon_rpc_sim.so` contains TVM runtime built into it, but since it's loaded as a "local" library these symbols are not visible to shared libraries loaded by subsequent dlopens. (Same applies to symbols from the C++ runtime.)
To make these symbols visible, dlopen the defining libraries as "global". (Re-dlopeninig an already loaded library is a well-defined operation.)
cc @mehrdadh
> [Hexagon] Make local symbols visible to loaded modules in RPC server

- python/tvm/relay/op/contrib/dnnl.py
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
This patch is to enable layer normalization in DNNL BYOC by providing an out-of-box rewrite pattern for combining the operators into a single relay layer normalization operator as well as its implementation in dnnl json codegen.
After applying the rewrite pattern, we will observe the following dnnl function:
```
6202 def @tvmgen_default_dnnl_main_108(%dnnl_108_i0: Tensor[(1, 784, 128), float32], Inline=1, Compiler="dnnl", global_symbol="tvmgen_default_dnnl_main_108", Primitive=1) -> Tensor[(1, 784, 128), float32] {
6203   nn.layer_norm(%dnnl_108_i0, meta[relay.Constant][56] /* ty=Tensor[(128), float32] */, meta[relay.Constant][57] /* ty=Tensor[(128), float32] */) /* ty=Tensor[(1,  784, 128), float32] */
6204 }
```
Once you enable DNNL_VERBOSE flag, more informations are shown in log file …
> [BYOC][DNNL] Enable layer normalization in DNNL byoc.

- python/tvm/contrib/hexagon/build.py
This is to avoid workspace collision in case the test was skipped/xfailed quickly.
> [Hexagon] Add random string to workspace name

- src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
- tests/python/contrib/test_cmsisnn/test_conv2d.py
Removed input_scale and filter_scale from CMSIS-NN
wrapper function. These are not needed by CMSIS-NN
API which gets called from the generated C wrapper
function for Conv2D.
> [CMSIS-NN] Removed redudant arguments to CMSIS-NN wrapper function

- Jenkinsfile
- jenkins/macros.j2
- tests/scripts/git_utils.py
- tests/scripts/pytest_wrapper.py
This should fix #11544 and adds some more logging in case the issue persists. Unfortunately it is difficult to test for real since the case data in that PR is thrown away after Jenkins is done (Jenkins does store test data but it marshals JUnits into its own format), so this PR also uploads those to S3. This also includes a small fix to the auth logic for POSTs in git_utils
> [ci] Add guards to pytest_wrapper

- apps/microtvm/reference-vm/base-box-tool.py
This PR removes the version from the names of the microTVM reference VMs on Vagrant Cloud.
In the past, the reference VMs for microTVM had names like `microtvm-zephyr-2.7` or `microtvm-arduino-0.18.3`. This made some sense for Zephyr, as much of the functionality of Zephyr is tied only to the version number. However, it never made much sense for Arduino (as the `arduino-cli` SDK version does not affect behavior very much - only the board SDK versions do), and it is unlikely this naming scheme would make sense as we add more types of RVMs.
Even for Zephyr, this naming scheme forces us to have multiple RVMs listed on Vagrant Hub, even though we only update one (microtvm-zephyr-2.7, the least downloaded one). By changing the RVM names to `microtvm-zephyr` and `microtvm-arduino`, the naming …
> [microTVM] Remove microTVM RVM version suffix

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
I add a test about resize_nearest_neighbor op when it‘s half_pixel_centers=True，the test will not to pass.
I found out that this was caused by the rounding_method value when half_pixel_centers=True.
Therefore, I improve support for half_pixel_centers in resize.
> [Frontend][TFLite] Improve support for half_pixel_centers in resize

- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/primitive/cache_read_write.cc
- tests/python/unittest/test_tir_schedule_cache_read_write.py
- tests/python/unittest/test_tir_schedule_compute_at.py
- tests/python/unittest/test_tir_schedule_compute_inline.py
- tests/python/unittest/test_tir_schedule_reduction.py
- tests/python/unittest/test_tir_schedule_reindex.py
- tests/python/unittest/test_tir_schedule_sampling.py
- tests/python/unittest/test_tir_schedule_set_scope.py
- tests/python/unittest/test_tir_schedule_storage_align.py
- tests/python/unittest/test_tir_schedule_transform_layout.py
- tests/python/unittest/test_tir_schedule_utilities.py
As a follow-up to https://github.com/apache/tvm/pull/11269, starting to add similar quality-of-life functionality to other methods in `Schedule`.  They can only be used when it is unambiguous to do so, and translate the string name into the underlying C++ type before calling the FFI.
* Allow a block to be passed in by a name.
* Allow a buffer name to be passed to `Schedule.reindex`, with the same calling convention as `Schedule.transform_layout`.
> [TIR][Schedule] Allow named block and buffer arguments in Schedule

- Jenkinsfile
- jenkins/Build.groovy.j2
- jenkins/Deploy.groovy.j2
- jenkins/DockerBuild.groovy.j2
- jenkins/Jenkinsfile.j2
- jenkins/Lint.groovy.j2
- jenkins/Prepare.groovy.j2
- tests/python/ci/test_ci.py
- tests/scripts/cmd_utils.py
- tests/scripts/git_utils.py
- tests/scripts/http_utils.py
- tests/scripts/should_rebuild_docker.py
This sets us up to rebuild Docker images and uses them in later stages in the same build. This is not yet enabled (see the commented out code in `DockerBuild.groovy.j2`. If the build is running on `main`, then the images are uploaded to Docker Hub automatically once the run is complete. To avoid landing a complicated infra PR all at once this mostly adds the scaffolding and a follow up PR will: 1. upload images to tlcpack instead of tlcpackstaging 2. dynamically determine the docker image to use based on the latest hash 3. always rebuild docker images if an updated one hasn't been uploaded
> [ci][1/n] Rebuild Docker images if necessary

- apps/microtvm/arduino/template_project/boards.json
- apps/microtvm/reference-vm/arduino/README.md
- apps/microtvm/reference-vm/arduino/base-box/base_box_provision.sh
- python/tvm/target/target.py
Adds microTVM support for the Arduino Portenta H7, from the Arduino Pro line of boards. I've been asked about this a few times (including at TVMCon) and finally got around to it.
Unfortunately, this is not as easy as it should be, because of [a bug in the Arduino Core API](https://github.com/arduino/ArduinoCore-API/pull/163). I have a PR out to fix it, but it might take some time to get merged and included in a release. Until that occurs, I've included a workaround in `base_box_provision.sh`.
> [microTVM] Add support for Arduino Portenta H7

- include/tvm/runtime/crt/platform.h
- src/runtime/crt/common/crt_runtime_api.c
See [this thread ](https://discuss.tvm.apache.org/t/crt-add-platform-specific-pre-and-post-function-calls-in-crt-runtime/12723)for an explanation.
> [CRT runtime] Added functions TVMPlatformBeforeMeasurement and TVMPlatformAfterMeasurement

- src/relay/backend/aot_executor_codegen.cc
- src/relay/backend/graph_executor_codegen.cc
- src/relay/backend/interpreter.cc
- src/relay/backend/te_compiler.cc
- src/relay/backend/te_compiler.h
- src/relay/backend/vm/compiler.cc
- src/relay/transforms/compiler_function_utils.cc
- src/relay/transforms/compiler_function_utils.h
- tests/python/relay/backend/test_pass_lower_te.py
- tests/python/relay/transform/test_compiler_function_utils.py
In #11474 I got ready to switch CUTLASS from function-at-a-time to IRModule-at-a-time compilation.
However my approach didn't handle dynamic shape functions, so I adjust it here.
The idea is still that such passes will leave behind
calls to 'extern' functions. However, converting those
calls to 'call_lowered' form in
MarkCompilerFunctionsAsExtern is too soon since only
the TECompiler knows how to capture all the attributes
necessary to support dynamic shape functions.
So stop doing that in MarkCompilerFunctionsAsExtern and
instead support this case properly in the TECompiler.
While there try to chip away at the chronic lack of structure in te_compiler.cc. Every little bit helps.
Added a bare-bones unit test to exercise the main lowering/call-rewrite flavors, but much more is needed.
> [BYOC] RelayToTIR custom codegen passes can still depend on dynamic shape functions

- docker/install/ubuntu_install_papi.sh
- docs/how_to/profile/papi.rst
It seems that [this PR](https://bitbucket.org/icl/papi/pull-requests/251/20220111-rocm-rewrite) broke our installation of papi in the `ci_gpu` docker image.
This PR fixes it.
Edit: check [this build](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11470/16/pipeline/50) for the failure. The same error occurs when building the image locally on main. 
@areusch @driazati 
cc @Mousius
> [CI] fix ci_gpu dockerfile

- Jenkinsfile
- jenkins/Deploy.groovy.j2
We don't have a good way to tell if a file was deleted or not in a docs update, so currently we delete the entire `docs/` folder and replace it from the build. However, this includes old version docs that aren't build in the normal docs build. This excludes them from the deletion so they stick around between updates. We'll have to revisit this list at each release but it should be a simple update.
> [ci][docs] Don't delete old versions when checking out docs

- python/tvm/contrib/hexagon/build.py
- python/tvm/contrib/hexagon/pytest_plugin.py
- python/tvm/contrib/hexagon/session.py
- tests/python/contrib/test_hexagon/test_launcher.py
This PR changes Hexagon launcher in pytest config to reuse existing RPC server on Android side and only create new RPC server on the first test.
cc @Lunderberg @kparzysz-quic
> [Hexagon] Run single RPC server on Android in each testing session 

- python/tvm/relay/op/contrib/dnnl.py
- src/relay/backend/contrib/dnnl/codegen.cc
- src/relay/backend/contrib/dnnl/query_layout.cc
- src/relay/backend/utils.h
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
- tests/python/relay/test_pass_partition_graph.py
This patch is to enhance the performance of DNNL BYOC dense operators by 1) introducing gelu fusion and ~~2) introducing alter dense weight layout.~~ (Implemented after merging PR https://github.com/apache/tvm/pull/11345, Thanks @apeskov )
Why do we introduce gelu fusion:
For the model family of BERT, GELU (Gaussian Error Linear Unit) activation is used heavily so if we perform gelu fusion in those models, then we gain a better performance boost. 
Why do we introduce automatically packed dense and its altered weight layout:
Format tag::ab (aka. tag::NC) is not the best format selected by DNNL inner_product primitive. It is a drawback in current DNNL BYOC module.
For what model it fit in:
Dense intensity type such as Bert family
With this patch, I benchmarked the inference performance of a …
> [BYOC][DNNL] Improve performance of DNNL BYOC dense operator

- python/tvm/meta_schedule/tune.py
- tests/python/unittest/test_meta_schedule_tune_te.py
`tune_te` was broken because it passed a primfunc to `tune_tir`. Now it is wrapped in an IRModule. Also the test is re-enabled.
@junrushao1994 @zxybazh
> [FIX,METASCHEDULER] Fix tune_te

- python/tvm/meta_schedule/testing/dataset_collect_models.py
- python/tvm/meta_schedule/testing/dataset_extract_tasks.py
- python/tvm/meta_schedule/testing/dataset_sample_candidates.py
- python/tvm/meta_schedule/testing/relay_workload.py
- src/meta_schedule/search_strategy/evolutionary_search.cc
- src/tir/schedule/analysis/analysis.cc
In order to build a dataset for improving the cost model for MetaSchedule, I added several files including importing models to TVM, extracting tuning tasks, and sampling measure candidates. Meanwhile, I exposed some methods in C++ to the Python side to assist the process.
[update] In the file `dataset_sample_candidates.py`, I manually save tuning records to json files because `JsonDatabase` is unreasonably slow. I will update it after @junrushao1994 's PR on json parser is merged.
> [MetaSchedule] Generate MetaSchedule Dataset

- python/tvm/contrib/cutlass/__init__.py
- python/tvm/contrib/cutlass/build.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
- python/tvm/relay/op/contrib/cutlass.py
- python/tvm/testing/utils.py
- src/relay/backend/contrib/cutlass/codegen.cc
- src/relay/backend/contrib/cutlass/codegen.h
- src/relay/backend/contrib/cutlass/target.cc
- tests/python/contrib/test_cutlass.py
(See https://discuss.tvm.apache.org/t/byoc-supporting-cutlass-byoc-with-collage/12796/6 for context, which in turn is part of Collage (https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md). 
Currently CUTLASS has four entry points:
- The usual 'partition_for_cutlass' partitioning function, using the standard pattern table and pass machinery (see cutlass/build.py).
- A 'tune_cutlass_kernels' function which augments CUTLASS partition functions with the results of building and running test kernels (see cutlass/build.py).
- A 'relay.ext.cutlass' external codegen function which inspects the  turning results and generates a CSourceModule for each partitions (see cutlass/codegen.cc).
- A 'build_cutlass_kernels_vm' function which runs 'export_library' with all the nvcc compiler …
> [BYOC] Make CUTLASS BYOC integration 'Collage friendly'  

- python/tvm/meta_schedule/utils.py
- src/meta_schedule/arg_info.cc
- src/meta_schedule/database/database.cc
- src/meta_schedule/database/database_utils.cc
- src/meta_schedule/database/json_database.cc
- src/meta_schedule/utils.h
- tests/python/unittest/test_meta_schedule_database.py
This PR adds some utility to JSONDatabase to accelerate its loading/saving time.
> [MetaSchedule] JSONDatabase Utilities

- include/tvm/relay/adt.h
- include/tvm/relay/expr.h
- include/tvm/relay/expr_functor.h
- include/tvm/relay/function.h
- src/relay/backend/contrib/cutlass/codegen.cc
- src/relay/ir/expr.cc
- tests/cpp/relay/with_fields_test.cc
This has been sitting in my collage branch forever, might as well clear it into main.
I added the beginnings of a unit test, but only for the Call overload.
> [Relay] Finish implementations of WithFields

- src/relay/op/nn/convolution.cc
- tests/python/relay/test_op_level2.py
This PR fixes #11664 according to the proposal in that issue. A test case is added as requested by @ganler.
> [Bugfix] Shape inference of weight for grouped `nn.conv3d`

- src/relay/backend/contrib/cutlass/codegen.cc
Caused by https://github.com/apache/tvm/pull/11513, which introduced a new function overload and made the existing use of the function call ambiguous.
> [BUILD] Fixed cutlass BYOC build break

- docker/install/ubuntu_install_python_package.sh
- docs/conf.py
This uses the new code from https://github.com/tlc-pack/tlcpack-sphinx-addon/pull/5 with a link to the v0.8.0 docs. We can update this in the future as we add more releases. This also updates the docker image to always use the latest tlcpack-sphinx-addon. This should be relatively safe since we own that code anyways
cc @areusch
> [docs] Add links to v0.8.0 docs

- tests/python/topi/python/test_topi_argwhere.py
Refactored while debugging breakage of tests in https://github.com/apache/tvm/pull/11646.  Submitting as a separate PR, as it isn't necessary or related to the primary changes in that PR.
> [UnitTests] Parametrized test_topi_argwhere.py

- tests/python/contrib/test_cmsisnn/test_generate_constants.py
- tests/python/contrib/test_cmsisnn/utils.py
Added a missing docstring to CMSIS-NN test that checks for CMSIS-NN constants. The issue is related to https://github.com/apache/tvm/pull/11625.
> Added a docstring to missing CMSIS-NN test

- include/tvm/meta_schedule/profiler.h
- python/tvm/meta_schedule/__init__.py
- python/tvm/meta_schedule/profiler.py
- python/tvm/meta_schedule/testing/tune_relay_meta_schedule.py
- src/meta_schedule/measure_callback/add_to_database.cc
- src/meta_schedule/measure_callback/echo_statistics.cc
- src/meta_schedule/measure_callback/measure_callback.cc
- src/meta_schedule/measure_callback/remove_build_artifact.cc
- src/meta_schedule/measure_callback/update_cost_model.cc
- src/meta_schedule/profiler.cc
- src/meta_schedule/search_strategy/evolutionary_search.cc
- src/meta_schedule/tune_context.cc
- src/meta_schedule/utils.h
- tests/python/unittest/test_meta_schedule_profiler.py
- tests/python/unittest/test_meta_schedule_search_strategy.py
Similar to our current performance statistics table, a tuning efficiency statistics table could be extremely helpful. The output result looks like the following example:
```
Tuning Efficiency Statistics:
ID |                   Module Name | Time Usage(s) | Time Ratio(%) 
--------------------------------------------------------------------
0 |                    Total Time |        2.2824 |      100.0000 
1 | TaskScheduler::InitializeTask |        2.2819 |       99.9786 
--------------------------------------------------------------------
```
> [MetaSchedule] Add Profiler Support For Tuning Efficiency Optimization

- docs/install/from_source.rst
There were some extra steps needed for making these instructions work while working on a MacBook with an M1 processor. These changes should make it more clear what is needed if users are in the same situation.
> Updated install from source docs to include additional instructions for M1 macs.

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
This simple PR fixes the unhandled float64 case introduced by #11446. Without the change, TVM won't be able to import any ONNX Round operator with float64 inputs, and will complain with error `data types float64 and float32 do not match in BroadcastRel`.
cc: @AndrewZhaoLuo @jwfromm @CircleSpin
> Fix onnx round import with float64 inputs.

- tests/python/unittest/test_meta_schedule_relay_tir_compute.py
A concurrent merge breaks the unittest which imports directly from
`meta_schedule.testing`.
cc @driazati
> [Hotfix][MetaSchedule] Importing from test folder

- tests/python/contrib/test_hexagon/infrastructure.py
Fix bug where `allocate_hexagon_array` in `tests/python/contrib/test_hexagon/infrastructure.py` wasn't respecting the caller-specified `memory_scope`.
cc @mehrdadh
> [tests][hexagon] Fix `allocate_hexagon_array` bug.

- src/relay/backend/utils.cc
FlattenAtrousConv must be called before AlterOpLayout to give a performance boost. The pass must be called before the change of the layout.
> Move FlattenAtrousConv before AlterOpLayout in the default opt pipeline.

- Jenkinsfile
- jenkins/Jenkinsfile.j2
This patch updates the docker image tag used for ci_hexagon to a recent build that uses LLVM 14.0.0 release.
cc @Mousius @areusch @driazati @mehrdadh
> [CI] [Hexagon] Update docker tag in jenkins

- src/target/llvm/codegen_amdgpu.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_nvptx.cc
Today's LLVM main branch removed `AllocaInst::getAlignment`.
> [LLVM] Update uses of AllocaInst::getAlign[ment]

- python/tvm/topi/cuda/softmax.py
- tests/python/topi/python/test_topi_softmax.py
One sophisticated softmax's TE schedule assumes >= 2D input (eg, https://github.com/apache/tvm/blob/d92a7731a28d87d6644d18619f94f341250318b3/python/tvm/topi/cuda/softmax.py#L86), and raises IndexError for 1D input. This PR checks tensor rank and falls back to default schedule when rank=1.
@masahi
> Fix 1d-softmax schedule.

- include/tvm/meta_schedule/apply_history_best.h
- include/tvm/meta_schedule/extracted_task.h
- python/tvm/meta_schedule/apply_history_best.py
- python/tvm/meta_schedule/relay_integration.py
- python/tvm/meta_schedule/testing/utils.py
- src/meta_schedule/apply_history_best.cc
- src/meta_schedule/extracted_task.cc
- src/meta_schedule/utils.h
- src/relay/backend/task_extraction.cc
- src/relay/backend/te_compiler_cache.cc
- tests/python/unittest/test_meta_schedule_relay_tir_compute.py
This PR enables task filtering in Apply-History-Best, which is used in
Relay/Relax integration. Previously, even though a task is ruled out
during task extraction, it still shows up in Relay compilation due to
the lack of filtering on `Apply-History-Best`. However, TE-to-TIR
conversion `te.CreatePrimFunc` doesn't support all cases with hybrid
operators involved, which leads to post-tuning failure affecting
multiple models.
> [MetaSchedule] Apply-History-Best Task Filtering

- src/tir/transforms/narrow_datatype.cc
- tests/python/unittest/test_tir_transform_narrow_datatype.py
This PR fixes a bug in the pass Narrow-Datatype in TIR, where dtype of
certain IterVar and loop variables are adjusted to narrower ones.
The bug occurs when the dtype of thread axis is int32, while its extent
is int64, where the original behavior will not narrow the extent to
int32, which causes an assertion thrown in IterVar's constructor. An
alternative approach is to re-dtype IterVar to int64, however, the
subsequent passes do not actually respect int64 thread axes, which leads
to even more issues in lowering.
This bug prevents AutoTIR in tuning Huggingface DistilBERT.
> [Bugfix][TIR] Narrow-Datatype for thread axis

- tests/lint/pylint.sh
- tests/python/relay/aot/test_c_device_api.py
- tests/python/relay/aot/test_cpp_aot.py
- tests/python/relay/aot/test_crt_aot.py
- tests/python/relay/aot/test_crt_aot_usmp.py
This enables pylint against the AOT test cases.
One issue I found was with the `tvm.testing.parameter` which breaks the naming convention rules in pylint (constants are upper case and function parameters are lower case). It may be worth a syntax similar to:
```
tvm.testing.parameter("enable_usmp", [True, False])
```
cc @areusch @driazati
> [CI] Apply linting rules to AOT tests

- python/tvm/relay/op/contrib/cmsisnn.py
- tests/python/contrib/test_cmsisnn/test_pooling.py
In case of mixed dtypes appearing in the network,
pattern checker was not able to find correct dtype
of the input in the qnn maxpool sequence of ops.
cc @areusch
> [CMSIS-NN] Fixed error in finding input's dtype in maxpool

- python/tvm/meta_schedule/space_generator/__init__.py
- python/tvm/meta_schedule/space_generator/schedule_fn.py
- python/tvm/meta_schedule/tune.py
- python/tvm/meta_schedule/tune_context.py
- tests/python/unittest/test_meta_schedule_custom_rule_winograd_cpu.py
- tests/python/unittest/test_meta_schedule_custom_rule_winograd_cuda.py
- tests/python/unittest/test_meta_schedule_integration.py
- tests/python/unittest/test_meta_schedule_mutator_mutate_compute_location.py
- tests/python/unittest/test_meta_schedule_mutator_mutate_parallel.py
- tests/python/unittest/test_meta_schedule_mutator_mutate_thread_binding.py
- tests/python/unittest/test_meta_schedule_mutator_mutate_tile_size.py
- tests/python/unittest/test_meta_schedule_mutator_mutate_unroll.py
- tests/python/unittest/test_meta_schedule_post_order_apply.py
- tests/python/unittest/test_meta_schedule_postproc_disallow_dynamic_loop.py
- tests/python/unittest/test_meta_schedule_postproc_rewrite_cooperative_fetch.py
- tests/python/unittest/test_meta_schedule_postproc_rewrite_reduction_block.py
- tests/python/unittest/test_meta_schedule_postproc_rewrite_tensorize.py
- tests/python/unittest/test_meta_schedule_postproc_rewrite_unbound_block.py
- tests/python/unittest/test_meta_schedule_postproc_verify_gpu_code.py
- tests/python/unittest/test_meta_schedule_schedule_rule_add_rfactor.py
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_bind.py
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_inline.py
- tests/python/unittest/test_meta_schedule_schedule_rule_cross_thread_reduction.py
- tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py
- tests/python/unittest/test_meta_schedule_schedule_rule_parallel_vectorize_unroll.py
- tests/python/unittest/test_meta_schedule_schedule_rule_random_compute_location.py
- tests/python/unittest/test_meta_schedule_search_strategy.py
Follow-up of #11622, per discussion with @Kathryn-cat
rules
out template-driven scheduling on TIR.
Next PR:
- Add `TuneContext.tune` to allow directly tuning without task scheduler.
> [MetaSchedule] Developer Ergonomics Enhancement II

- python/tvm/meta_schedule/tune.py
- src/meta_schedule/measure_callback/add_to_database.cc
- src/meta_schedule/measure_callback/echo_statistics.cc
- src/meta_schedule/measure_callback/measure_callback.cc
- src/meta_schedule/measure_callback/remove_build_artifact.cc
- src/meta_schedule/measure_callback/update_cost_model.cc
- src/meta_schedule/profiler.cc
- src/meta_schedule/search_strategy/evolutionary_search.cc
- src/meta_schedule/task_scheduler/task_scheduler.cc
- tests/python/unittest/test_meta_schedule_tune_relay.py
Minor modification to scoped timers to cover 99% of all the time cost during MS tuning. Allow `ApplyHistoryBest` and `TaskExtraction` time to be counted during tune_relay.
> [MetaSchedule] Modify Profiler Timers

- apps/microtvm/arduino/template_project/boards.json
- apps/microtvm/reference-vm/arduino/README.md
- apps/microtvm/reference-vm/arduino/base-box/base_box_provision.sh
- python/tvm/target/target.py
Adds microTVM support for the Raspberry Pi Pico, which uses the Raspberry Pi foundation's RP2040 microcontroller. It worked out of the box when using the [community-built SDK](https://github.com/earlephilhower/arduino-pico), so this PR only includes changes to add it to the RVM and allow `rpipico` to be passed to TVMC.
It is worth noting that there is a [different, now-deprecated SDK](https://github.com/arduino/ArduinoCore-mbed) written by Arduino, which was also for the Raspberry Pi Pico. However, this SDK has [a major bug](https://github.com/arduino/ArduinoCore-API/pull/163) that stops microTVM from working on it. It's not an issue though, as the RP2040 version of this SDK is deprecated anyway.
This PR also fixes the ESP32 base URL to use a fixed version, instead of a floating one.
cc …
> [microTVM] Add support for the Raspberry Pi Pico via Arduino

- gallery/how_to/work_with_microtvm/micro_train.py
This PR changes the links in `micro_train.py` to read images from `tlc-pack/web-data`, instead of my personal form `guberti/web-data`. This also changes the Colab link to point to `apache/tvm-site`, which has the correct `.ipynb` file now that the `ci-gpu` version has been updated.
> [microTVM] [docs] Point micro_train tutorial links to official repos

- python/tvm/script/tir/scope_handler.py
- tests/python/unittest/test_tvmscript_roundtrip.py
Just a missing support for `tir.LetNode`
> [TVMScript] Support roundtrip of LetNode

- apps/microtvm/reference-vm/arduino/base-box/base_box_setup.sh
- apps/microtvm/reference-vm/base-box-tool.py
- apps/microtvm/reference-vm/base_box_setup_common.sh
- apps/microtvm/reference-vm/zephyr/base-box/base_box_setup.sh
- apps/microtvm/reference-vm/zephyr/base-box/base_box_test.sh
- docker/install/ubuntu_install_core.sh
- docker/install/ubuntu_install_python.sh
> [microTVM] Refactor RVM scripts and fix DNS network issue

- docker/Dockerfile.ci_lint
Upgrading pylint allows the use of `good-names-rgxs` which allows us to create regexes which match "good" names in pylint as opposed to manually listing them all out using `good-names` in the current version. 
Follow up issue: https://github.com/apache/tvm/issues/11733
See https://github.com/apache/tvm/pull/11712/files for a potential example
> [Docker][Pylint] Upgrade ci lint docker file

- python/tvm/runtime/ndarray.py
tvm.nd.array and tvm.nd.copyto make underlying calls to tvm.nd.empty, which already supports an optional mem_scope parameter. This adds the same optional parameters.
> [NDArray] Add optional mem_scope parameter to tvm.nd.array and tvm.nd.copyto

- docker/Dockerfile.ci_gpu
BYOC related tutorial like my #11557  use DNNL  and such tutorial run at docker gpu which need to install DNNL to prepare the environment.
> [ci][docker gpu] Install dnnl in docker GPU.

- src/relay/backend/te_compiler_cache.cc
- tests/python/unittest/test_link_params.py
This is a proposal to fix the bug reported here: https://discuss.tvm.apache.org/t/problem-with-allocateconstnodes-in-cmsis-nn-code/12806
Bug report: https://github.com/apache/tvm/issues/11394
A prefix "cc" had been added to the "constant_" to distinguish from the constant naming generated in aot_executor_gen.cc 
@SebastianBoblestETAS @vdkhoi @grant-arm @Mousius @manupa-arm @ashutosh-arm @MJKlaiberBosch
> Constant name prefix added

- python/tvm/relay/op/contrib/dnnl.py
- src/relay/backend/contrib/dnnl/codegen.cc
- src/relay/backend/contrib/dnnl/comp_op_matcher.h
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- src/runtime/contrib/dnnl/dnnl_tensor_requisite.h
- tests/python/contrib/test_dnnl.py
- tests/python/relay/test_pass_partition_graph.py
**Support of QNN primitives and their fused versions for DNNL**
DNNL has support of int8 convolution/dense/matmul primitives with some list of post operations. Which usually looks like next:
```
%0 = conv(src<int8>, wgh<int8>)       -> <int32>
%1 = %0 + bias                        -> <int32>
%2 = %1 * o_scl                       -> <float>
%3 = act(%2) * act_scl                -> <float> // some activate like clip/relu/gelu and others
%4 = %3 + src2 * sum_scl              -> <float>
%5 = cast<int32>(%4) + dst_zp         -> <int32>
%6 = cast<int8>(%5)                   -> <int8> 
```
Equivalent graph on relay level will looks like:
```
op = qnn.conv2d(data, weight, src_scl, src_zp, wgh_scl, wgh_zp)
op = add(op, bias)
op = qnn.requantize(op, rq_in_scl, rq_in_zp, rq_out_scl, rq_out_zp)
op = …
```
> Enable QNN primitives for DNNL runtime

- tests/python/contrib/test_hexagon/benchmark_util.py
- tests/python/contrib/test_hexagon/test_benchmark_elemwise_add.py
- Make the execution of benchmarks in `benchmark_elemwise_add.py` depend
on two environment variables: `ANDROID_SERIAL_NUMBER` and
`TVM_FORCE_RUN_BENCHMARKS`.
By default, the benchmarks are skipped when the
`ANDROID_SERIAL_NUMBER` environment variable has the value
`simulator`. (Case is significant.)
This can be overridden by setting the environment variable
`TVM_FORCE_RUN_BENCHMARKS` to the value `1`.
Maintainer note: This is a (hopefully) temporary measure to prevent
(time-consuming) benchmarking code from executing every time TVM's
pre-commit CI hook runs.
- Fix a bug where `benchmark_elemwise_add.py` was broken by an
earlier change to the `HexagonLauncherRPC` class.
- misc. small changes to
`tests/python/contrib/test_hexagon/benchmark_util.py`.
cc @mehrdadh
> [hexagon][testing] add test-skip logic; fixes

- python/tvm/relay/op/contrib/cmsisnn.py
- src/relay/backend/contrib/cmsisnn/extract_constants.cc
- src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
- src/relay/backend/contrib/cmsisnn/scalar_to_tensor_constant.cc
- tests/python/contrib/test_cmsisnn/test_binary_ops.py
- tests/python/contrib/test_cmsisnn/test_extract_constants.py
- tests/python/contrib/test_cmsisnn/test_scalar_to_tensor_constant.py
This commit is to fix issues in CMSIS-NN passes
that surface when the same operand is repeated
in QNN binary ops.
cc @areusch
>  [CMSIS-NN] Fixed the case with repeating operands in the QNN binary ops

- include/tvm/meta_schedule/database.h
- python/tvm/meta_schedule/database/database.py
- python/tvm/meta_schedule/database/memory_database.py
- python/tvm/meta_schedule/testing/dataset_sample_candidates.py
- python/tvm/meta_schedule/testing/distributed_measure_candidates.py
- python/tvm/meta_schedule/tune_context.py
- src/meta_schedule/database/database.cc
- src/meta_schedule/database/json_database.cc
- src/meta_schedule/tune_context.cc
This PR includes the distributed measurement of tuning candidates using builder and async runner, as well as some auxiliary functions. It enables multiple builders and multiple runners with a tracker connecting in between. The hierarchy of files in the database can be further compacted to make the database more concise.
> [MetaSchedule] Distributed Measurement

- tests/python/contrib/test_hexagon/benchmark_util.py
- tests/python/contrib/test_hexagon/test_benchmark_maxpool2d.py
- Add benchmarking framework for Hexagon maxpool-2d kernels,
and one (simple) kernel.
- Minor refactor hexagon benchmark utilities.
cc @mehrdadh
> [hexagon][testing] add max_pool2d benchmark

- apps/microtvm/arduino/template_project/microtvm_api_server.py
- python/tvm/driver/tvmc/model.py
- python/tvm/micro/contrib/stm32/emitter.py
- python/tvm/micro/model_library_format.py
- python/tvm/micro/testing/utils.py
- tests/micro/zephyr/test_zephyr.py
- tests/python/relay/aot/test_crt_aot.py
- tests/python/relay/strategy/arm_cpu/test_avg_pool.py
- tests/python/relay/strategy/arm_cpu/test_conv1d_ncw.py
- tests/python/relay/strategy/arm_cpu/test_conv1d_nwc.py
- tests/python/relay/strategy/arm_cpu/test_conv2d_NCHWc.py
- tests/python/relay/strategy/arm_cpu/test_dense_dsp.py
- tests/python/relay/strategy/arm_cpu/test_depthwise_conv2d.py
- tests/python/relay/strategy/arm_cpu/test_depthwise_conv2d_NCHWc.py
- tests/python/relay/strategy/arm_cpu/test_group_conv2d.py
- tests/python/relay/strategy/arm_cpu/test_max_pool.py
- tests/python/unittest/test_micro_model_library_format.py
This PR implements this RFC: https://github.com/apache/tvm-rfcs/pull/76
cc @areusch @gromero
> [MLF] Add support for multiple modules in Model Library Format

- python/tvm/contrib/pipeline_executor.py
- src/runtime/pipeline/pipeline_executor.cc
- src/runtime/pipeline/pipeline_executor.h
- src/runtime/pipeline/pipeline_struct.h
- tests/python/relay/test_pipeline_executor.py
Added a feature to PipelineExecutor to track number of Global Inputs.
> [Runtime][PipelineExecutor] Added Interface to Track Number of Global Inputs

- python/tvm/meta_schedule/runner/config.py
Pointed out by @sunggg that the description of `number` and `repeat` for evaluator configuration is not accurate, updated to a version more consistent with `TimeEvaluator`.
> [MetaSchedule][Minor] Fix EvaluatorConfig Argument Description

- python/tvm/auto_scheduler/testing/tune_onnx.py
- python/tvm/auto_scheduler/testing/tune_relay.py
- python/tvm/auto_scheduler/testing/tune_te.py
- python/tvm/meta_schedule/testing/tune_onnx.py
- python/tvm/meta_schedule/testing/tune_relay.py
- python/tvm/meta_schedule/testing/tune_te.py
This PR is based on #11751 and adds `describe` function for `tune_relay` and `tune_onnx` script on both AutoScheduler and MetaSchedule. It prints out very useful information for reproducibility as follows:
```
Python Environment
TVM version    = 0.9.dev0
Python version = 3.8.8 (default, Apr 13 2021, 19:58:26)  [GCC 7.3.0] (64 bit)
os.uname()     = Linux 5.15.5-76051505-generic #202111250933~1638201579~21.04~09f1aa7-Ubuntu SMP Tue Nov 30 02: x86_64
CMake Options:
{
"BUILD_STATIC_RUNTIME": "OFF",
"COMPILER_RT_PATH": "3rdparty/compiler-rt",
"CUDA_VERSION": "NOT-FOUND",
"DLPACK_PATH": "3rdparty/dlpack/include",
"DMLC_PATH": "3rdparty/dmlc-core/include",
"GIT_COMMIT_HASH": "3b872a0adae07b0cd60248346fd31b158cba630c",
"GIT_COMMIT_TIME": "2022-06-15 11:27:59 -0700",
"HIDE_PRIVATE_SYMBOLS": "OFF", …
```
> [MetaSchedule][Minor] Add Describe Function For Tuning Scripts

- CONTRIBUTORS.md
Please join us to welcome @denise-k as a new reviewer to TVM.
Denise is the main (co)authors of roadmap RFC and roadmap process:
- https://github.com/orgs/apache/projects/31
- https://github.com/apache/tvm-rfcs/pull/50
- https://discuss.tvm.apache.org/t/pre-rfc-tvm-roadmap/11171
And she helps to propose and (co)manage several roadmaps:
- microTVM: https://github.com/apache/tvm-rfcs/pull/53
- CI Testing: https://github.com/orgs/apache/projects/31
- Relax roadmap RFC: https://github.com/apache/tvm-rfcs/pull/69
While she also helps community avocation and involvements.
> [COMMUNITY] Denise Kutnick -> Reviewer

- python/tvm/meta_schedule/testing/te_workload.py
- python/tvm/tir/schedule/analysis.py
- src/tir/schedule/analysis.h
- src/tir/schedule/analysis/analysis.cc
- src/tir/schedule/ir_comparator.cc
- src/tir/schedule/ir_comparator.h
- tests/python/unittest/test_tir_schedule_analysis.py
This PR added a utility function `GetAutoTensorizeMappingInfo` to propose mapping from workload block iters to the iters in the tensor intrin. An example usage is conv2d, where the computation block has more iters than the matmul tensor intrin.
cc @spectrometerHBH @masahi @junrushao1994
> [TIR, analysis] Add GetAutoTensorizeMappingInfo to generate transforms for auto tensorization

- python/tvm/driver/tvmc/runner.py
- tests/python/driver/tvmc/test_runner.py
As described in #11707, the RPC mechanism does not support objects of type Map which breaks the use of tvmc run when using RPC after #9889. This commit intends to workaround this issue by providing a fallback to the old implementation when RPC is being used. Further, a test has been provided to help prevent this regression in the future.
cc @leandron @leeexyz @masahi @Mousius @gromero
> [TVMC] Fix tvmc run when using rpc

- src/meta_schedule/database/database_utils.cc
Originally, when failed with `std::stoi` and `std::stod`, the parser
disruptly stops and throw an incomprehensible error message, for
example, "stoi". This PR improves the user experience by detailing which
string causes the parsing issue.
A minor fix: out-of-range integers in parsing will now automatically fall
back to floating point numbers.
> [MetaSchedule] Enhance parsing in JSONDatabase

- python/tvm/auto_scheduler/testing/tune_onnx.py
- python/tvm/auto_scheduler/testing/tune_relay.py
- python/tvm/auto_scheduler/testing/tune_te.py
- python/tvm/meta_schedule/testing/tune_onnx.py
- python/tvm/meta_schedule/testing/tune_relay.py
- python/tvm/meta_schedule/testing/tune_te.py
Previously `cpu-flush` option existed as a boolean or integer argument, which is a bit counter-intuitive because for argparse, any non-empty string such as `False` will be parsed to `True` when using as a boolean and integer a little bit vague here IMHO. This PR used a function from `distutils` to directly parse input string to boolean, which makes the usage more stragiht-forward like `--cpu-flush True` or `--cpu-flush False`. Meanwhile it still supports usage of `0/1` and made sure the argument is always required.
CC: @junrushao1994
> [MetaSchedule][Minor] Update CPU Flush ArgParse Type

- docs/README.md
build/html get moved into _docs, update related document.
> [Doc] Fix incorrect command

- python/tvm/runtime/module.py
- src/target/codegen.cc
- src/target/llvm/codegen_blob.cc
- src/target/llvm/codegen_blob.h
- src/target/llvm/llvm_module.cc
The blob-embedding code creates a new LLVM module for which is needs more information than just the target triple. The `_get_target_triple` function in LLVMModule returned the triple with additional options appended to the string. Instead of piggy-backing those extra options on top of the triple, replace `_get_target_triple` with `_get_target_string`, which will return the entire target string.
> [LLVM] Retrieve entire target string from LLVMModule

- gallery/how_to/work_with_microtvm/micro_train.py
As part of `gallery/how_to/work_with_microtvm/micro_train.py`, we download a part of the Stanford Cars dataset from https://ai.stanford.edu/. Unfortunately, https://ai.stanford.edu/ is currently down, with no indication of when it will be back up. This PR provides a **temporary** CI fix by switching this tutorial to use a mirror link. Note that the link is not an exact mirror (containing all files, not just the train ones), so a few other lines had to be adjusted too.
> [skip ci] Use Stanford Cars mirror to fix CI docs build

- python/tvm/topi/x86/concat.py
- tests/python/unittest/test_micro_model_library_format.py
This is a proposed change to the new topi x86 concat implementation in #11341. It uses simple lists of int instead of `te.tensor.Tensor` for the array offsets and loop variable extents. I have only looked at the generated C code and made sure that the relevant unit tests pass.
New version:
```
for (int32_t j = 0; j < 4; ++j) {
concatenate_ext[j] = placeholder[j];
}
for (int32_t j1 = 0; j1 < 4; ++j1) {
concatenate_ext[(j1 + 4)] = placeholder1[j1];
}
return 0;
```
Old version: 
```
void* const_vector_let = (&(global_workspace_6_var[64]));
void* cumsum_let = (&(global_workspace_6_var[48]));
for (int32_t i = 0; i < 2; ++i) {
((int64_t*)const_vector_let)[i] = ((i == 1) ? (int64_t)4 : ((i == 0) ? (int64_t)4 : (int64_t)0));
}
for (int32_t i1 = 0; i1 < 2; ++i1) {
((int64_t*)cumsum_let)[i1] = ((i1 …
```
> Change new concat

- docs/install/from_source.rst
#10755 changed the TVM_LOG_DEBUG separator from ';' to ','.  This PR changes installation guide file accordingly.
@areusch
> [docs] Fixed the error in install/from_source.rst file

- tests/micro/zephyr/test_zephyr_aot_exec.py
Skip mps2_an521 for host-driven AoT zephyr tests.
#11831
cc @gromero @mehrdadh
> [microTVM][zephyr] skip mps2_an521 for host-driven AoT zephyr tests

- include/tvm/runtime/container/string.h
- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_hexagon.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
- src/target/llvm/llvm_common.h
We should not be declaring LLVM data structures in headers unrelated to LLVM. There are only a handful of places where such a conversion was used, it was replaced with a more local solution.
> [LLVM/String] Remove conversion operator of String to llvm::StringRef

- src/tir/transforms/unify_thread_binding.cc
- tests/python/unittest/test_tir_transform_unify_thread_binding.py
This PR fixed dtype mismatch in UnifyThreadBinding when multiple thread axes with the same thread tag have different dtype. 
cc @zxybazh @junrushao1994
> [TIR] Fix dtype mismatch in UnifyThreadBinding

- include/tvm/relay/transform.h
- src/relay/backend/build_module.cc
- src/relay/backend/vm/compiler.cc
- src/relay/transforms/meta_schedule_layout_rewrite.cc
- src/relay/transforms/meta_schedule_layout_rewrite.h
This is part of our effort to support layout rewrite on Meta Schedule.
> [Relay][Pass] Meta-Schedule-Layout-Rewrite

- docker/install/ubuntu_install_tensorflow_aarch64.sh
Update the custom repository URL used to pull TensorFlow-aarch64. The mechanism of installation is also changed to a file based, as a temporary workaround before we update to a newer version (>=2.7) that can be pulled from the official PyPI repository.
Closes #11773
cc @Mousius @areusch @lhutton1 @driazati
> [CI][arm] Fix tensorflow-aarch64 repository URL

- docker/Dockerfile.ci_lint
This reverts commit 7bfbc74c65684d1e25e235335da41c94372a561a, as it generates near 500 code violations when PyLint was updated from 2.4.4 to 2.9.3.
Issue #11785 for details.
cc @AndrewZhaoLuo @Mousius @areusch @driazati @lhutton1 @manupa-arm
> [ci] Revert "upgrade ci lint docker file (#11734)"

- src/runtime/profiling.cc
std::locale("") would failed  in some env like: LC_ALL=zh_CN.UTF-8 
`tvm._ffi.base.TVMError: locale: :facet::_S_create_c_locale name not valid>`
locale has its default constructor function, no need to set input to empty string `""`
> fix locale("")

- python/tvm/auto_scheduler/cost_model/xgb_model.py
- python/tvm/auto_scheduler/task_scheduler.py
CC: @jcf94
Thanks @octoJon for pointing out the typo!
> [python][docs] fix docstring typo

- python/tvm/auto_scheduler/relay_integration.py
- python/tvm/meta_schedule/__init__.py
- python/tvm/meta_schedule/relay_integration.py
- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/relay/op/strategy/cuda.py
- python/tvm/relay/op/strategy/generic.py
- python/tvm/relay/op/strategy/mali.py
- python/tvm/relay/op/strategy/x86.py
This is part of our effort to support layout rewrite on Meta Schedule.
> [OpStrategy] Support MetaSchedule Layout

- src/target/llvm/codegen_llvm.cc
- src/target/llvm/llvm_common.cc
- src/target/llvm/llvm_common.h
The only use of that function is commented out. `llvm::Module` can be printed directly to `llvm::raw_ostream` via <<, so it's quite easy to insert printing code when needed:
```
std::string s;
llvm::raw_string_ostream os(s);
os << module;   // s (or os.str()) has the LLVM IR text
```
> [LLVM] Remove PrintModule (defined in llvm_common.cc)

- .gitignore
- Jenkinsfile
- jenkins/Prepare.groovy.j2
- tests/python/ci/test_ci.py
- tests/scripts/determine_docker_images.py
See #11768. This adds a script to check if Docker images exist in `tlcpack` and switch to `tlcpackstaging` if not (the tags must match though). There is also a feature flag for this in jenkins in the `DETERMINE_DOCKER_IMAGES` env variable (which must be set to `yes` for this change to work)
> [ci][docker] Fall back to tlcpackstaging if images don't exist

- .github/workflows/nightly_docker_update.yml
- tests/python/ci/test_ci.py
- tests/scripts/git_utils.py
- tests/scripts/open_docker_update_pr.py
See #11768 for details. This can be merged any time but the CI runs on the automated PRs won't work until #11775 is also merged. This also requires some repo settings to be checked (which may or may not be the case already), we could merge this and wait to see if it works or have ASF check for us: https://issues.apache.org/jira/browse/INFRA-23405
This adds a GitHub Action to check for the latest images on Docker Hub via the Docker API and update the `Jenkinsfile` accordingly. It sends this in as PR for a committer to review and merge.
> [ci][docker] Send a PR to bump the Docker images nightly

- tests/python/ci/__init__.py
- tests/python/ci/test_ci.py
- tests/python/ci/test_mergebot.py
- tests/python/ci/test_script_converter.py
- tests/python/ci/test_utils.py
This fixes up the pylint issues as part of #11414 for the CI tests
> [ci] Enable pylint for tests/python/ci

- src/relay/op/tensor/transform.cc
- tests/python/relay/test_pass_convert_op_layout.py
> [realy][pass]add split infer shape with convert op layout pass

- src/relay/op/algorithm/topk.cc
- tests/python/relay/test_pass_convert_op_layout.py
Add topK FInferCorrectLayout attr.
Shape can be automatically inferred in convert op layout without using layout_transform firstly.
> [relay][pass]add topK FInferCorrectLayout attr

- tests/python/integration/test_tuning.py
Closes https://github.com/apache/tvm/issues/10489.
The issue is that autotvm can generate uncompiliable code for gpu. There is a built in pass that filters these out. Unfortunately, it is impossible to guarantee during tuning, especially for small number of trials we will grab a schedule that doesn't get filtered out. 
Therefore, we will accept records which are filtered out by the gpu verification pass as proof the system is working.
The reason it was flaky before is because once in a while when tuning, it could not find a valid schedule due to low number of kernel trials.
> [AutoTVM] Fix flaky test

- src/relay/qnn/op/quantize.cc
* move round op before `add expanded_output_zero_point`
* consistent with python description `(round(input_tensor/output_scale) + output_zero_point`
> [fix] quantize op consistent with python description

- include/tvm/meta_schedule/apply_history_best.h
- include/tvm/tir/stmt.h
- include/tvm/tir/transform.h
- python/tvm/meta_schedule/apply_history_best.py
- python/tvm/meta_schedule/builder/local_builder.py
- python/tvm/relay/backend/te_compiler.py
- python/tvm/relay/build_module.py
- python/tvm/tir/transform/transform.py
- src/meta_schedule/apply_history_best.cc
- src/meta_schedule/arg_info.cc
- src/meta_schedule/feature_extractor/per_store_feature.cc
- src/meta_schedule/utils.h
- src/relay/backend/te_compiler_cache.cc
- src/te/operation/create_primfunc.cc
- src/tir/transforms/remove_weight_layout_rewrite_block.cc
- tests/python/unittest/test_meta_schedule_postproc_rewrite_parallel_vectorize_unroll.py
- tests/python/unittest/test_te_create_primfunc.py
- tests/python/unittest/test_tir_transform_remove_weight_layout_rewrite_block.py
This is one of the last few PRs in Meta-Schedule CPU layout rewrite, which introduces a simple pass that removes layout rewrite blocks in TIR.
> [TIR][Pass] Remove-Weight-Layout-Rewrite-Block

- src/arith/domain_touched.cc
- tests/python/unittest/test_arith_domain_touched.py
Also loosen the requirement that the user provided buffer exist within the IR to match with the old behavior of DomainTouched.
Resolves #11716
> [Arith] Update BufferDomainTouched to support vector access.

- python/tvm/topi/hexagon/slice_ops/__init__.py
- python/tvm/topi/hexagon/slice_ops/softmax_slice.py
- python/tvm/topi/hexagon/utils.py
- tests/python/contrib/test_hexagon/test_softmax_slice.py
This patch adds the initial python implementation softmax slice op for hexagon.
cc @mehrdadh
> [Hexagon] Softmax slice op initial version

- .github/workflows/upload_ci_resource.yml
- jenkins/README.md
This adds a `workflow_dispatch` only GitHub Action that committers can use to upload files to the CI bucket for use like in #11839
> [ci] Add manual workflow to upload files to CI bucket

- src/arith/iter_affine_map.cc
- tests/python/unittest/test_arith_iter_affine_map.py
This PR fixed an issue preprocessing dividend for `FloorDiv / FloorMod`. When `IterSumExpr->args` is empty, it should be treated as a failure. 
cc @wrongtest @spectrometerHBH @junrushao1994
> [Arith] Fix DetectIterMap floordiv when IterSum only contains base expr

- src/runtime/profiling.cc
Change profiling::Report printing to catch any errors when setting the locale (used to add separators to large numbers). This avoids issues around misconfigured locale.
@junrushao1994 @yogurfrul
> [PROFILING] Catch any errors while setting locale for printing

- src/arith/const_int_bound.cc
- tests/python/unittest/test_tir_transform_renormalize_split_pattern.py
Previously, in `ConstIntBoundAnalyzer`, entering a conditional such as `if 2==0` could result in the expression `2` being treated as having a known value of zero within the body of the conditional.  Evaluating the range of expressions using `2` in the body of the conditional could result in exceptions being thrown, such as evaluating `expr / 2` while setting `2` to its maximum value of zero.
This issue was present for conditions with inequalities for some time, but was introduced for conditions with equalities in https://github.com/apache/tvm/pull/11524.  Both types are resolved in this PR.
> [TIR][Arith] Avoid assigning range of possible values to integers

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
This PR adds support for Onnx sequence operators introduced in opset 11. Specifically I've added converters for `SequenceConstruct`, `SequenceInsert`, and `ConcatFromSequence`, which we found sometimes show up in models exported from Pytorch. For simplicity, I handle these cases by just using Tuples. We may want to consider using the TensorArray ADT eventually instead.
> [Relay][Frontend][Onnx] Add support for onnx sequence operators.

- include/tvm/meta_schedule/postproc.h
- python/tvm/auto_scheduler/__init__.py
- python/tvm/meta_schedule/default_config.py
- python/tvm/meta_schedule/postproc/rewrite_layout.py
- src/meta_schedule/postproc/rewrite_layout.cc
- tests/python/unittest/test_meta_schedule_postproc_rewrite_layout.py
This is the last part of effort to support layout rewrite on Meta Schedule. With all the commits, we finally enable layout rewrite for end to end workloads on Meta Schedule.
> [MetaSchedule] Postproc: Rewrite-Layout

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to add `aten::broadcast_tensors` ops in the PyTorch frontend.
@masahi @junrushao1994 @zxybazh
> [Relay] [PyTorch] Add aten::broadcast_tensors

- src/target/llvm/codegen_amdgpu.cc
- src/target/llvm/codegen_arm.cc
- src/target/llvm/codegen_blob.cc
- src/target/llvm/codegen_blob.h
- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_cpu.h
- src/target/llvm/codegen_hexagon.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
- src/target/llvm/codegen_nvptx.cc
- src/target/llvm/codegen_params.cc
- src/target/llvm/codegen_params.h
- src/target/llvm/codegen_x86_64.cc
- src/target/llvm/intrin_rule_hexagon.cc
- src/target/llvm/intrin_rule_llvm.cc
- src/target/llvm/intrin_rule_llvm.h
- src/target/llvm/llvm_common.cc
- src/target/llvm/llvm_common.h
- src/target/llvm/llvm_module.cc
This is following the same principle we use everywhere else in TVM, that is, every source file includes headers that it depends on. While including unnecessary LLVM headers (which may happen by including llvm_common.h) is not actively harmful, it makes the header dependencies much less transparent.
> [LLVM] Include LLVM headers in files that use them, not in llvm_common.h

- python/tvm/topi/x86/injective.py
Modify the schedule for injective ops. All outputs of injective ops should share the same schedule optimization, e.g. outputs of OP split are all supposed to be lowered into parallel for.
```
new ir:
IRModule({GlobalVar(tvmgen_default_fused_split): PrimFunc([placeholder, T_split_sections, T_split_sections]) attrs={"from_legacy_te_schedule": (bool)1, "global_symbol": "tvmgen_default_fused_split", "tir.noalias": (bool)1} {
buffer_realize T_split_sections([0, 1], [0, 64], [0, 56], [0, 56]) {
parallel (ax0.ax1.fused, 0, 64) {
for (ax2, 0, 56) {
for (ax3.outer, 0, 4) {
vectorized (ax3.inner, 0, 16) {
if (tir.likely(((ax3.inner + (ax3.outer*16)) < 56))) {
T_split_sections[floordiv(ax0.ax1.fused, 64), floormod(ax0.ax1.fused, 64), ax2, (ax3.inner + (ax3.outer*16))] = …
```
> [Injective Schedule] make injective ops's opt schedule applied to every output tensor

- python/tvm/driver/build_module.py
Previously, if a TIR Schedule is passed to `tvm.lower`, the error message is returned `ValueError: ('Expected input to be an IRModule, PrimFunc or Schedule, but got, ', <class 'tvm.tir.schedule.schedule.Schedule'>)`.  This can cause user confusion, as the expected class name in the error message does not differentiate between between a `tvm.te.Schedule` and a `tvm.tir.Schedule`.  Updated error message to explicitly state that this should be a `te.Schedule`.
> [TIR] Improved error message if tir.Schedule passed to lower/build

- tests/python/contrib/test_hexagon/topi/test_add_subtract_multiply.py
cc @mehrdadh
Earlier CI in upstream did not have support for hexagon v69. But since now it supports it, the test can use the updated version.
For testing, we have decided not to disable assert so that it can catch if there's any assert issue.
> [HEXAGON] Change arch and do not disable assert

- python/tvm/relay/frontend/pytorch.py
Hitting this error with `vision_maskrcnn` in torchbench. Stacktrace below:
```
ERROR:torchdynamo.optimizations.backends:tvm error
File "/home/xx/torchdynamo/torchdynamo/optimizations/backends.py", line 640, in tvm_compile_inner
mod, params = relay.frontend.from_pytorch(jit_mod, shape_list)
File "/home/xx/tvm/python/tvm/relay/frontend/pytorch.py", line 4320, in from_pytorch
outputs = converter.convert_operators(_get_operator_nodes(graph.nodes()), outputs, ret_name)
File "/home/xx/tvm/python/tvm/relay/frontend/pytorch.py", line 3694, in convert_operators
relay_out = relay_op(
File "/home/xx/tvm/python/tvm/relay/frontend/pytorch.py", line 856, in new_full
dtype = _convert_dtype_value(inputs[2])
File "/home/xx/tvm/python/tvm/relay/frontend/pytorch.py", line …
```
> [PyTorch] fix unit8 in _convert_dtype_value

- python/tvm/relay/op/contrib/tensorrt.py
- python/tvm/relay/transform/transform.py
- src/relay/transforms/compiler_function_utils.cc
- src/relay/transforms/compiler_function_utils.h
- tests/python/relay/transform/test_compiler_function_utils.py
The TensorRT BYOC integration needs to 'undo' partitionings in some situations. Add an
InlineCompilerFunctions pass to make that robust. In particular, it must undo both the
'partitioning' (ie separating out the "Compiler" function) and any 'compositing' (ie separating
out small sub-graphs as "Composite" functions).
Fix misspelled nn.bias_add while there.
Note that the current implementation has been broken since #11203 (mea culpa) but was untested by CI. I have all the tests fixed in a follow-up PR and a few other bug fixes.
> [BYOC] InlineCompilerFunctions helper pass

- python/tvm/relay/frontend/pytorch.py
This PR intends to add `aten::pad` in the pytorch frontend and refactor the padding-related ops. 
cc: @masahi
> [PyTorch] [Relay] Add aten::pad

- python/tvm/contrib/dnnl.py
- src/runtime/contrib/dnnl/dnnl.cc
- tests/python/relay/test_op_level2.py
Added bfloat16 for dnnl conv2d kernel in order to coordinate with bf16/fp32 mixed precision mode, 
which implemented ny changing the type of dnnl primitive descriptor & memory descripor accoring to src/dst data format during the declaration.
Test case also modified for both bf16 & fp32.
>  [DNNL] Add bfloat16 type support for dnnl conv2d kernel

- tests/python/contrib/test_hexagon/topi/test_avg_pool2d_slice.py
> [Hexagon] Skip test_avg_pool2d_slice because of segfault

- src/tir/transforms/compact_buffer_region.cc
- tests/python/unittest/test_tir_transform_compact_buffer_region.py
Fix a bug for let support, it should not put non-index typed values into `dom_map`.
> [TIR][BugFix] Do not bind non-index type value of lets in CompactBufferAllocation

- include/tvm/tir/usmp/utils.h
- src/tir/usmp/unified_static_memory_planner.cc
- tests/python/unittest/test_tir_usmp_algo.py
This allows a user to easily provide a registered TVM function for example on the Python side and have it accessible to USMP without changing any C++ code and recompiling.
The existing algorithms are already registered functions.
@manupa-arm @d-smirnov
> [USMP] Improve algorithm extensibility

- CMakeLists.txt
- include/tvm/runtime/profiling.h
- python/tvm/auto_scheduler/testing/tune_relay.py
- python/tvm/contrib/debugger/debug_executor.py
- python/tvm/contrib/debugger/debug_result.py
- python/tvm/contrib/graph_executor.py
- python/tvm/meta_schedule/testing/tune_relay.py
- python/tvm/runtime/module.py
- python/tvm/runtime/vm.py
- src/runtime/crt/common/crt_runtime_api.c
- src/runtime/graph_executor/debug/graph_executor_debug.cc
- src/runtime/opencl/opencl_device_api.cc
- src/runtime/profiling.cc
- src/runtime/rpc/rpc_module.cc
- tests/python/unittest/test_runtime_graph_debug.py
- web/emcc/tvmjs_support.cc
- web/src/runtime.ts
**Motivation:**
Sometimes running the script several times we get a strong scatter in the results.
```
from tvm.contrib.debugger import debug_runtime as graph_executor
...
m = graph_executor.create(graph, lib, ctx)
...
time_f = m.module.time_evaluator("run", dev, number=1000, repeat=1)
mean = time_f().mean
print(mean)
```
First try:
> 0.0846912 secs/iteration
Second try:
> 0.105601 secs/iteration
In general, the devices has an acceptable temperature range. If the system heats up to the upper limit for some time, it can force cooling by available ways. For example, by lowering the frequency.
In the following example the temperature reaches 90 degrees and after some time the frequency drops and after cooling is restored.
```
from tvm.contrib.debugger import debug_runtime as graph_executor …
```
> Add cooldown interval logic for the profiling functional

- src/meta_schedule/schedule_rule/multi_level_tiling.cc
- src/meta_schedule/schedule_rule/multi_level_tiling.h
- src/meta_schedule/schedule_rule/multi_level_tiling_with_intrin.cc
This PR made `State` in `MultiLevelTiling` inherit `Object`, to allow future subclassing of `State`. Making `State` an `Object` allows instances of `State` and its subclasses to be stored in `std::vector<State>`.
cc @junrushao1994 @masahi
> [MetaSchedule] Refactor MultiLevelTiling state to allow subclassing

- tests/python/contrib/test_ethosu/test_networks.py
The network tests with striping were reported to be flaky.
This commit increases the workspace size to be generous and
also repeats the test case to make sure its not flaky.
Closes #11941 
> [microNPU] increase workspace sizes for network tests

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to add `aten::cross_entropy_loss` for the pytorch frontend. This is related to previous correctness issue of `cross_entropy_loss_with_logits` [here](https://github.com/apache/tvm/issues/9109).
cc: @masahi
> [PyTorch][Relay] Add aten::cross_entropy_loss

- include/tvm/runtime/vm/vm.h
When using the native C++ API of the `VirtualMachine`, link error occurred when building the project: `undefined symbols for the VirtualMachine`.
This is due to the fact that these symbols were not exported from `tvm.dll`.
This patch fixes this issue.
> [VM] Export symbols for VirtualMachine on Windows

- python/tvm/rpc/server.py
- python/tvm/rpc/tracker.py
I notice that the TVM RPC tracker and server's logging does not have date and time details, like the following snippet from server:
```
INFO:RPCServer:Finish serving ('172.34.51.174', 37306)
INFO:RPCServer:connection from ('172.34.51.174', 37308)
```
This PR introduces a stream handler to format the logging out with new format as follows:
```
2022-06-29 12:19:34.003 INFO bind to 172.34.54.88:4445
```
This is could help user monitor RPC traffic and workload time usage.
> [RPC] Add Data & Time For RPC Tracker / Server Logging

- include/tvm/driver/driver_api.h
- include/tvm/relay/expr.h
- include/tvm/tir/buffer.h
- src/driver/driver_api.cc
- src/relay/backend/te_compiler.cc
- src/relay/backend/te_compiler_cache.cc
- src/relay/backend/te_compiler_cache.h
- src/tir/ir/buffer.cc
Relay expressions can have assigned virtual devices with certain
memory scope. This change landing of memory scope information from
Relay level to tir
This PR is a part of origin PR11357
@csullivan @mbs-octoml
> [Relay] Handle memory scope during lowering from relay level

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to add the following five ops for the pytorch frontend:
- aten::new_ones
- aten::new_full
- aten::fill_
~~- aten::pad~~ (This op is relocated to #11922 )
- aten::reshape_as
- aten::empty_like
Note that arguments to the above ops will be changed by relay at runtime so `verify_model` won't work on them. 
cc: @masahi @junrushao1994 @zxybazh
> [Relay][Pytorch] Add aten::new_ones, aten::new_full, aten::fill_, aten::pad, aten::reshape_as and atem::empty_like

- include/tvm/tir/stmt.h
- src/meta_schedule/postproc/verify_gpu_code.cc
- tests/python/unittest/test_meta_schedule_postproc_verify_gpu_code.py
Added annotation `warp_execution` to indicates a block is executed by a warp (e.g. tensor core instructions).
Updated `VerifyGPUCode` to support the annotation implied extend of `threadIdx.x`
cc @junrushao1994 @spectrometerHBH @Hzfengsy
> [MetaSchedule] Handle 'warp_execution' implied extend of threadIdx.x in VerifyGpuCode

- python/tvm/topi/nn/softmax.py
- python/tvm/topi/testing/softmax_python.py
- python/tvm/topi/x86/nn.py
- tests/python/relay/test_op_level1.py
- tests/python/topi/python/test_topi_softmax.py
adds support for any shape and axis for `log_softmax` (this was already supported by regular `softmax`)
there's slight code duplication but it was a lot messier when I tried to reuse the `softmax_common` code in-place
cc @shingjan @masahi
> [TOPI][x86] support any shape and axis for log softmax

- include/tvm/runtime/vm/executable.h
It continues patch from #11947 
When using the native C++ API of the `Executable` of `Virtual Machine`, sometimes link error occurred when building the project: `undefined symbols for the Executable`.
This is due to the fact that these symbols were not exported from `tvm.dll`.
This patch fixes this issue.
> [VM] class Executable does not export symbols to dll

- python/tvm/testing/utils.py
- tests/python/ci/test_ci.py
This PR skips some additional tests that are failing in the nightly wheel.
@driazati @areusch 
cc @Mousius
> [CI] Skip some additional tests that are failing in the wheel

- python/tvm/relay/frontend/pytorch.py
- python/tvm/topi/nn/softmax.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to add `aten::l1_loss` and `aten::mse_loss` for the pytorch frontend.
cc: @masahi @vinx13
> [PyTorch] [Relay] Add l1 and mse loss function for pytorch frontend

- include/tvm/meta_schedule/feature_extractor.h
- python/tvm/meta_schedule/feature_extractor/per_store_feature.py
- src/meta_schedule/feature_extractor/per_store_feature.cc
This PR enables extracting the embeddings of the workload in a tuning context, which further strengthens the feature extracting process. Workload embeddings are extracted based on names of each block in the IR module. If `extract_workload` is enabled, the extracted feature vectors will have length 164 + 8 = 172.
> [MetaSchedule] Extract workload embedding

- docker/bash.sh
This uses #11775 to make local builds work if they're run in the meantime before CI tags over a new image to tlcpack
cc @areusch @mehrdadh
> [docker] Fall back to tlcpackstaging in bash.sh

- python/tvm/contrib/hexagon/build.py
It uses parameters that are not present in Python 3.6, plus it catches generic exception, which may not have `stdout` or `stderr` members.
cc @mehrdadh
> [Hexagon] Fix use of subprocess.run in _check_call_verbose

- python/tvm/topi/hexagon/injective.py
- src/target/llvm/codegen_hexagon.cc
This code is part of the effort by Qualcomm to provide operators. These changes enable several int8 elementwise operators to use Hexagon's vlut instruction. This is via the relay take operator which is essentially a lookup table. The code recognizes when a tensor is used to index into another tensor. If conditions are met, 8 bit vlut instructions are generated.
cc @mehrdadh
> [Hexagon] Enable int8 vlut codegen for Relay take (LUT) operator

- docker/bash.sh
* Use python3 to run determine_docker_images.py
* Properly detect presence of CI env var with + expansion.
@leandron @mehrdadh @driazati
> Couple patches to docker/bash.sh after #11976.

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
This code was there to stop Jenkins restarts from doing a repository
scan and scheduling a ton of builds. However, I haven't noticed this
happening during restarts lately, and repository scans are useful to
patch up PRs that didn't get CI run properly (i.e. while Jenkins was
down or something).
For example in #11914 since this code is there all the messed up PRs
needed their CI to be manually re-triggered even though they were
detected during the scan.
cc …
> [ci] Don't skip index-triggered builds

- include/tvm/runtime/module.h
- python/tvm/meta_schedule/testing/custom_builder_runner.py
- python/tvm/relay/op/contrib/tensorrt.py
- src/relay/backend/contrib/codegen_c/codegen.cc
- src/relay/backend/contrib/cutlass/codegen.cc
- src/relay/backend/contrib/tensorrt/codegen.cc
- src/relay/backend/contrib/tensorrt/codegen.h
- src/relay/backend/contrib/tensorrt/target.cc
- src/relay/transforms/compiler_function_utils.cc
- src/relay/transforms/compiler_function_utils.h
- src/runtime/const_loader_module.cc
- src/runtime/contrib/json/json_runtime.h
- src/runtime/contrib/tensorrt/tensorrt_builder.cc
- src/runtime/contrib/tensorrt/tensorrt_builder.h
- src/runtime/contrib/tensorrt/tensorrt_ops.cc
- src/runtime/contrib/tensorrt/tensorrt_runtime.cc
- src/target/metadata_module.cc
- tests/python/contrib/test_tensorrt.py
- tests/python/contrib/test_tensorrt_int8_exp.py
This does for the TensorRT integration what #11631 did for the CUTLASS integration. See https://discuss.tvm.apache.org/t/byoc-how-backwards-compatible-does-the-tensorrt-partition-for-tensorrt-function-need-to-be/12957 for discussion.
- All compilation options are captured within the attributes of a Target of   kind "tensorrt" (instead of the "relay.ext.tensorrt.options" attribute in PassContext). This means all BYOC configurations options needed by Collage can be captured uniformly by a list-of-Targets. It also means RPC boundaries (as used internally at OctoML) only need to worry about maintaining the fidelity of the Target instance(s) rather than reaching into the PassContex.
The API is now:
```
host_target = tvm.target.Target("llvm")
cuda_target = tvm.target.Target("cuda", …
```
> [BYOC] Switch TensorRT BYOC integration to IRModule-at-a-time using RelayToTIR hook

- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_cpu.h
With LLVM switching to opaque (typeless) pointer types, some functions related to handling typed pointers are being deprecated (and will be removed).
The DWARF debug information does express pointee type. When constructing this information from opaque pointers in LLVM IR, the pointee type needs to be obtained from somewhere else (not the pointer).
Change the debug info generation to use the original PrimFunc to obtain the necessary type information. This will work with older versions of LLVM as well.
> [LLVM] Remove use of deprecated `PointerType::getPointerElementType()`

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This pr intends to add `aten::tril` and `aten:triu` ops in the pytorch frontend. Fixes #11967
cc: @masahi @junrushao1994 @zxybazh @vinx13
> [Relay] [PyTorch] Add aten::tril and aten::triu

- include/tvm/tir/schedule/schedule.h
- python/tvm/tir/schedule/schedule.py
- src/meta_schedule/arg_info.cc
- src/meta_schedule/mutator/mutate_parallel.cc
- src/meta_schedule/utils.h
- src/tir/schedule/analysis.h
- src/tir/schedule/analysis/analysis.cc
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/get_block_loop.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- tests/python/unittest/test_tir_schedule_utilities.py
This PR introduces `Schedule.work_on`, which instructs
`Schedule.get_block` to find the correct PrimFunc to retrieve from
without having to specify `func_name` in every time if the PrimFunc's
name is not `main`.
> [TIR] Add sugar method `Schedule.work_on`

- python/tvm/topi/adreno/conv2d_nchw.py
- python/tvm/topi/adreno/conv2d_nhwc.py
- python/tvm/topi/adreno/depthwise_conv2d_nchw.py
- python/tvm/topi/adreno/depthwise_conv2d_nhwc.py
- python/tvm/topi/adreno/utils.py
Before having these default parameters definition we had sequential execution on GPU. Introducing even such kind simple default params, we get quite close to the optimal numbers (1.2-1.5x vs optimal) that does not exclude further improving of heuristics but for now it is quite good enough
@echuraev @masahi Could you please take a look?
> [Adreno] Modify default AutoTVM params for conv2d

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
When I import [EfficientDet_lite](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/103_EfficientDet_lite) model,  the NonMaxSuppressionV5 op is not supported yet. I implemented it with reference to [nms](https://github.com/apache/tvm/blob/5efe8b0bfdff4c9939185a7581dc77e23cbcb6d5/python/tvm/relay/frontend/tensorflow_ops.py#L729) of tensorflow and [TFLite_Detection_PostProcess](https://github.com/apache/tvm/blob/5efe8b0bfdff4c9939185a7581dc77e23cbcb6d5/python/tvm/relay/frontend/tflite.py#L3243) of TFLite. 
Also, I constructed the test case with reference to  the model.
> test_case_nms_v5
> model_nms_v5
> [Frontend][TFLite] Add support for NonMaxSuppressionV5 op

- python/tvm/relay/op/contrib/dnnl.py
- tests/python/contrib/test_dnnl.py
ReWrite rensetV1 block, to reduce the computation complexity. Examples and test cases are provided.
> [BYOC-DNNL]rewrite downsize blocks for rensetv1 to get better performance

- src/relay/transforms/transform_layout.h
- tests/python/relay/test_pass_alter_op_layout.py
This model
```python
def @main(%x: Tensor[(1, 1, 1, 1), float32] /* ty=Tensor[(1, 1, 1, 1), float32] */) -> Tensor[(1, 1, 1), float32] {
%0 = image.resize2d(%x, size=[2, 4], roi=[0f, 0f, 0f, 0f], rounding_method="") /* ty=Tensor[(1, 1, 2, 4), float32] */;
%1 = mean(%0, axis=[3]) /* ty=Tensor[(1, 1, 2), float32] */;
image.resize1d(%1, size=[1], roi=[0f, 0f], rounding_method="") /* ty=Tensor[(1, 1, 1), float32] */
}
```
fails with error `  Check failed: (tir::BijectiveLayout(new_src_layout, dst_layout).defined()) is false: Cannot insert layout transform because there are inconvertible layouts: NCW v.s. NCH`. This should be a bug introduced in https://github.com/apache/tvm/pull/10118. This line https://github.com/apache/tvm/pull/12007/commits/7805d6fb113c9a68dd4628bb136416349f211ca2#diff-c3bb …
> Fix infercorrect layout in Layoutrewrite and improve naming.

- tests/scripts/ci.py
- tests/scripts/task_cpp_unittest.sh
Previously, the `ci.py` script would execute all C++ unit tests in the `"build"` directory, regardless of the docker image being used.  This change allows a caller to specify the build directory to be used by `task_cpp_unittest.sh`, either by the command line or by using the same `TVM_BUILD_PATH environment variable as used by the top-level Makefile, and passes this argument from `ci.py`.  To preserve the existing behavior for the pre-commit CI, if no argument is passed and if the `TVM_BUILD_PATH` is undefined, `task_cpp_unittest.sh` defaults to the `"build"` directory.
Python unit tests executed through `ci.py` used the `TVM_LIBRARY_PATH` environment variable, and were not similarly affected.
> [CI] Allow command-line argument or TVM_BUILD_PATH for C++ unittests

- python/tvm/topi/hexagon/slice_ops/__init__.py
- python/tvm/topi/hexagon/slice_ops/conv2d.py
- python/tvm/topi/hexagon/utils.py
- tests/python/contrib/test_hexagon/topi/test_conv2d_slice.py
This patch adds the initial python implementation conv2d slice op for hexagon.
Slice ops are basically ops that make certain assumptions about the input and output dimensions and are expected to be called after the original op has been sliced according to those dimensions at the graph level.
cc @mehrdadh
> [Topi] [Hexagon] Conv2d slice op initial version

- src/tir/transforms/compact_buffer_region.cc
- tests/python/unittest/test_tir_transform_compact_buffer_region.py
> [TIR] Revert #11428 and move loop dependent alloc extent check after region union

- include/tvm/meta_schedule/apply_history_best.h
- python/tvm/meta_schedule/apply_history_best.py
- src/meta_schedule/apply_history_best.cc
- tests/python/unittest/test_meta_schedule_integration.py
This PR introduced a new argument for `ApplyHistoryBest`'s `Query` interface to allow direct dispatch without querying the database, would be useful for debugging and benchmarking without interference.
> [MetaSchedule] Support ApplyHistoryBest Direct Dispatch

- tests/lint/pylint.sh
- tests/python/integration/__init__.py
- tests/python/integration/test_arm_mprofile_dsp.py
- tests/python/integration/test_dot.py
- tests/python/integration/test_ewise.py
- tests/python/integration/test_ewise_fpga.py
- tests/python/integration/test_gemm.py
- tests/python/integration/test_lower.py
- tests/python/integration/test_meta_schedule_auto_tensorize.py
- tests/python/integration/test_reduce.py
- tests/python/integration/test_scan.py
- tests/python/integration/test_tuning.py
- tests/python/integration/test_winograd_nnpack.py
See https://github.com/apache/tvm/issues/11414
> [Pylint] Pylint integration_tests folder

- python/tvm/tir/expr.py
- src/tir/op/op.cc
- tests/python/unittest/test_tir_base.py
While it is generally preferred to compare to `None` by using `is not`, I don't think TVM should just crash with a segfault in that case.
The crash stack trace is:
https://github.com/apache/tvm/blob/013d5e8fcbd94fb3a0c5c0cdcaea03af43c464aa/python/tvm/tir/expr.py#L568
https://github.com/apache/tvm/blob/013d5e8fcbd94fb3a0c5c0cdcaea03af43c464aa/src/tir/op/op.cc#L984
https://github.com/apache/tvm/blob/013d5e8fcbd94fb3a0c5c0cdcaea03af43c464aa/src/tir/op/op.cc#L514
https://github.com/apache/tvm/blob/013d5e8fcbd94fb3a0c5c0cdcaea03af43c464aa/src/tir/op/op.cc#L102
where rhs is nullptr.
@tqchen @Hzfengsy @wrongtest
> [TIR] fix crash when comparing IntImm to None

- gallery/tutorial/tvmc_command_line_driver.py
The TVMC tutorial is currently broken, probably because updates in the model, so we now need to pass input shape information.
Co-Authored-By: Liam Sturge <Liam.Sturge@arm.com>
cc @Mousius @areusch @gromero @manupa-arm
> [TVMC] Updates TVMC tutorial with input shape information

- src/relay/backend/graph_executor_codegen.cc
- src/runtime/graph_executor/graph_executor.cc
- src/runtime/graph_executor/graph_executor.h
- src/target/source/codegen_opencl.cc
Co-authored-by: Chris Sullivan <csullivan@octoml.ai>
This PR is a split part of origin PR11357
@csullivan @mbs-octoml
> [Texture] Add memory scope entity into graph JSON and graph executor runtime

- python/tvm/relay/op/contrib/dnnl.py
- src/relay/backend/contrib/dnnl/codegen.cc
- src/relay/backend/utils.h
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
- tests/python/relay/test_pass_partition_graph.py
Support post-op **swish**, **clip** with dnnl backend. The related test cases are provided.
**clip** op‘s attrs are added into **conv-(bias)-clip** pattern's attrs.
> [BYOC-DNNL] support more post-ops

- include/tvm/topi/detail/broadcast.h
- python/tvm/script/parser.py
- src/te/operation/op_utils.cc
- src/te/operation/op_utils.h
- src/te/schedule/bound.cc
- src/tir/ir/stmt_functor.cc
- tests/python/relay/test_op_level10.py
- tests/python/unittest/test_arith_canonical_simplify.py
This is a follow-up to https://github.com/apache/tvm/pull/12013.  It fixes several places where type mismatches are introduced, also adds a check to `IRSubstitute` to make sure that the type of the replacement `PrimExpr` is the same as the type of the `Var` being replaced.
> Several type mismatch fixes and checks

- python/tvm/relay/op/contrib/dnnl.py
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
This patch aims to enable batch matmul support in dnnl byoc. Matmul primitive is introduced to handle this case. Both transpose_a and transpose_b cases are supported. Unittest is also being added for ensuring correctness.
Also it contains one minor fix for laynorm rewrite.
> [DNNL] Enable Batch Matmul

- python/tvm/relay/frontend/tflite.py
Reading the following model did not work for me: https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark.tflite
with the error:
```
File "tvm/python/tvm/relay/frontend/tflite.py", line 3092, in convert_prelu
self.get_tensor_value(alpha_tensor), dtype=alpha_tensor_type_str
File "tvm/python/tvm/relay/frontend/tflite.py", line 520, in get_tensor_value
return np.frombuffer(data, dtype=dtype).reshape(shape)
TypeError: memoryview: a bytes-like object is required, not 'int'
```
The input of the PreLU op is the output of a Dequantize op, so not a constant, therefore its tensor buffer is not set.
I was unable to test this successfully because the existing test failed with the following error, even before any changes.
```
The Relay type checker is unable to …
```
> [Frontend][TFLite] PreLU alpha can be an expr

- CMakeLists.txt
- src/relay/collage/README.md
- src/relay/collage/dataflow_graph.cc
- src/relay/collage/dataflow_graph.h
- src/relay/collage/index_set.cc
- src/relay/collage/index_set.h
- src/relay/collage/sub_graph.cc
- src/relay/collage/sub_graph.h
- src/relay/collage/utils.cc
- src/relay/collage/utils.h
- tests/python/relay/collage/test_sub_graph.py
See https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md.
Collage works in units of 'sub-graphs', which are potential partitions of the
overall Relay model. This PR introduces SubGraph (an arbitrary partitioning, without
any implication about how it is to be represented), it's companion SubSubGraph
(implying a representation as a function), and some supporting odds 'n ends.
> [Collage] SubGraphs

- src/target/llvm/codegen_cpu.cc
This code is guarded by TVM_LLVM_VERSION >= 50 and < 70, so the errors were not detected in local tests or in CI.
See also: https://discuss.tvm.apache.org/t/build-error-with-the-current-tvm-main-version/13108.
> [LLVM] Fix build errors in CodeGenCPU::AddDebugInformation

- src/relay/backend/contrib/codegen_c/codegen.cc
I broke AOT in #11770 since I misread the original code. Spotted by @guberti, thanks! 
cc @Mousius @alanmacd @areusch
> [AOT][BUG] Only include extra headers if the constants array is needed.

- src/relay/collage/candidate_partition.cc
- src/relay/collage/candidate_partition.h
- src/relay/collage/candidate_set.cc
- src/relay/collage/candidate_set.h
- src/relay/collage/cost.cc
- src/relay/collage/cost.h
- src/relay/collage/partition_rule.cc
- src/relay/collage/partition_rule.h
- src/relay/collage/partition_spec.cc
- src/relay/collage/partition_spec.h
- tests/cpp/relay/collage/partition_rule_test.cc
See https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md.
(Special thanks to Matthew Barrett for authoring partition_rule_test.cc and suggesting a PR partitioning strategy.)
Collage uses a small 'combinator library' of PartitionRule to decribe how candidate partitions can be extracted from a model for measurement and comparison. This introduces most of that machinery, however we defer the all important 'CombinerPartitionRule' for the next PR. Thus the rules at this stage can only express the sorts of DFPattern-based rules we find in most BYOC integrations, and cannot describe rules more traditionally associated with operator fusion.
> [Collage] PartitionRule (though without CombinePartitionRule)

- gallery/tutorial/tvmc_command_line_driver.py
- gallery/tutorial/tvmc_python.py
Fix the ResNet50 Models in both tvmc tutorials so that the commands suggested will work fine.
Co-Authored-By: @Liastu01 
cc @CircleSpin @areusch @manupa-arm @Mousius @gromero for reviews
> [docs][tvmc] Fix ResNet50 model URL in tvmc tutorials

- python/tvm/relay/op/nn/_nn.py
- src/relay/op/nn/bitserial.cc
- src/relay/op/nn/convolution.cc
- src/relay/op/nn/correlation.cc
- src/relay/op/nn/nn.cc
- src/relay/op/nn/pooling.cc
- src/relay/op/nn/sparse.cc
Some of the Collage machinery is best tested from C++, but
requires Relay ops to have their "TOpPattern" registered.
However since the nn.* ops register on the Python side tests
can't rely on those ops.
The easy fix is to just move the registration to the
RELAY_REGISTER_OP block.
There's still a few dozen more exotic ops still registered
on the Python side. I've left them be.
> [Relay] Move TOpPattern registration for nn.* to C++

- tests/python/contrib/test_hexagon/topi/test_add_subtract_multiply.py
- tests/python/contrib/test_hexagon/topi/test_argmax_slice.py
- tests/python/contrib/test_hexagon/topi/test_resize2d.py
- tests/python/contrib/test_hexagon/topi/test_softmax_slice.py
We have updated HDK boards firmware and they are passing these tests now. Fixes https://github.com/apache/tvm/issues/11957
Thanks to @supersat!
cc @csullivan
> [Hexagon] Enable broken tests

- src/tir/transforms/loop_partition.cc
Some minor updation to loop partition pass
- Use `tvm::min/tvm::max` instead of `Min/Max`
Since currently `VectorizeLoop` pass is just after `LoopPartition`, there are no extra simplifications. The loop like `T.vectorize(Min(1, 8 - 3))`  will just fail on vectorizer check. We could just fold constants immediately when we create partitioned loops.
- Remove unneccesary warning log, and do not create zero-extent loop if we could prove the extent is less or equal to zero.
> [TIR] Fold const or empty iter partition

- src/tir/schedule/primitive/blockize_tensorize.cc
- tests/python/unittest/test_tir_schedule_blockize.py
This PR refactors the key schedule primitive `tensorize`, cleaning up the logic and brings the following benefits:
1) `tensorize` is now failure-safe: previously if a failure happens between `blockize` and structural pattern matching, the sref tree is left unmaintained
2) `tensorize` is now correct if a TIR is tensorized multiple times with the same tensor intrin: previously the intrin is not deep copied, so the pointer equality used in ScheduleState will fail if the TIR is tensorized multiple times
Per discussion with @vinx13 @yzh119 @spectrometerHBH
> [TIR][Schedule] Refactor Tensorize

- src/relay/collage/candidate_function_cache.cc
- src/relay/collage/candidate_function_cache.h
- src/relay/collage/candidate_partition.cc
- src/relay/collage/candidate_partition.h
- src/relay/collage/combiner_rule.cc
- src/relay/collage/combiner_rule.h
- src/relay/collage/cost.h
- src/relay/collage/cost_estimator.cc
- src/relay/collage/cost_estimator.h
- src/relay/collage/name_supply.cc
- src/relay/collage/name_supply.h
- src/relay/collage/partition_rule.cc
- src/relay/collage/partition_rule.h
- tests/cpp/relay/collage/candidate_partition_test.cc
- tests/cpp/relay/collage/partition_rule_test.cc
See https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md.
We complete the PartitionRule sub-class hierarchy with the addition of
CombinePartitionRule, which allows disjoint candidate partitions to be
unioned based on simple rules.
- By TOpPattern kind, eg a kOutElemwiseFusable and kBroadcast.
- A tuple argument with injective fields.
- The projection from an injective group (obviously of tuple type)
- Combinations of the above.
These let us mimic many common fusion strategies, including TVMs, so that
the candidates explored during Collage search are as large as possible to
expose possible fusion opportunities but no larger.
Also completes CandidatePartition with the EstimateCost method, which is
used during search to construct a stand-alone IRModule for latency estimation. …
> [Collage] CombinerRule and CandidatePartition::EstimateCost

- include/tvm/node/object_path.h
- python/tvm/runtime/object_path.py
- src/node/object_path.cc
- tests/python/unittest/test_object_path.py
Motivation:
Same IR node object can be referenced in several different contexts inside a larger IR object. For example, a variable could be referenced in several statements within a block.
This makes it impossible to use an object pointer to uniquely identify a "location" within the larger IR object for error reporting purposes. The `ObjectPath` class addresses this problem by serving as a unique "locator".
cc @yelite @junrushao1994
> [TVMScript] Add ObjectPath class

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/relay/op/strategy/cuda.py
- python/tvm/relay/op/strategy/generic.py
- python/tvm/relay/op/strategy/hls.py
- python/tvm/relay/op/strategy/intel_graphics.py
- python/tvm/relay/op/strategy/rocm.py
- python/tvm/relay/op/strategy/x86.py
- python/tvm/topi/nn/conv1d.py
- python/tvm/topi/nn/conv2d.py
- python/tvm/topi/nn/conv3d.py
- tests/python/integration/test_winograd_nnpack.py
- tests/python/topi/python/test_topi_conv2d_nhwc.py
- vta/python/vta/top/op.py
This PR added an optional parameter `kernel_layout` to `conv`. This allows arbitrary data and kernel layout combination to be lowered from Relay, and scheduled by auto / meta schedule.
cc @junrushao1994 @masahi @tkonolige
> [TOPI] Allow conv definition to have custom kernel layout

- src/relay/transforms/device_aware_visitors.cc
- src/relay/transforms/device_aware_visitors.h
- tests/python/relay/test_pass_plan_devices.py
Device planning is halfway through the transition to using the virtual_device_
field on every expression node to capture device/target/etc info. In the meantime
it is necessary to derive from a 'device aware' visitor so as to track device
information. In Collage this is not feasible, so as a stop gap allow the map
from expression nodes to virtual devices to be reconstructed as a stand alone
map.
This code can be removed once expr->virtual_device() is the canonical representation.
> [Relay] Add RecoverVirtualDeviceMap helper

- python/tvm/relay/frontend/tensorflow_ops.py
- tests/python/frontend/tensorflow/test_forward.py
Einsum op is supported in Relay but not in the Tensorflow model importer, which will cause the below error when importing Tensorflow models with Einsum operator.
```
NotImplementedError: The following operators are not implemented: {'Einsum'}
```
This PR is adding Einsum op converter from TF to Relay
> Add tensorflow Einsum op converter

- conftest.py
This follows on #11839 to apply it outside of docs and to tests running under pytest instead
> [ci] Override `Request` in pytests

- .github/actions/setup/action.yml
This makes it so the conda setup will re-run entirely in case of failures like in https://github.com/apache/tvm/runs/7287493088. [This issue](https://github.com/conda-incubator/setup-miniconda/issues/129) has some more context but there doesn't seem to be a better way to do a retry than re-running the whole thing since the settings in `conda/condarc` are picked up but they don't help for this particular issue.
> [ci] Add a manual retry for conda setup

- docker/install/ubuntu_install_python_package.sh
- tests/scripts/setup-pytest-env.sh
This uses [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) to retry failed tests. This should help alleviate flakiness for issues like segfaults in ethosu tests or flaky numerics. This obviously isn't as good as fixing the tests themselves, but it's an easy way to fix the most pressing issue (the cost of developer time to wait for, check, and re-run CI) while keeping the signal from the times the tests do fail consistently. 
> [ci] Re-run failed tests on failure

- python/tvm/relay/op/annotation/annotation.py
Previously it was expected that python on_device accept device that is wrong, by fact real on_device op expects virtual_device. If we want to pass memory scope, we have to create explicit virtual_device, but is declined by python wrapper of on_device. Fixed this case
> [Releay] Fix on_device call for explicit virtual_device

- python/tvm/relay/__init__.py
- python/tvm/relay/collage/__init__.py
- python/tvm/relay/collage/_ffi_api.py
- python/tvm/relay/collage/collage.py
- python/tvm/relay/transform/transform.py
- src/relay/collage/candidate_partition.cc
- src/relay/collage/candidate_partition_index.cc
- src/relay/collage/candidate_partition_index.h
- src/relay/collage/collage_partitioner.cc
- src/relay/collage/collage_partitioner.h
- src/relay/collage/cost_estimator.cc
- src/relay/collage/cost_estimator.h
- src/relay/collage/gather_partition_specs.cc
- src/relay/collage/gather_partition_specs.h
- src/relay/collage/priority_queue.h
- src/relay/collage/utils.cc
- src/runtime/vm/vm.cc
- tests/python/relay/test_pass_collage_partition.py
See https://github.com/apache/tvm-rfcs/blob/main/rfcs/0062-collage.md.
This adds the main CollagePartition pass, which:
1. Inspects all the targets in the CompilationConfig and builds
PartitionSpecs describing how to generate speculative CandidatePartitions
for them.
2. Runs the above rules on the model to collect all the candidates.
3. Eliminates candidates whose target contradicts any constraints already
imposed by, eg, device planning.
4. Eagerly estimates the cost of each candidate.
5. Performs a shortest path search to chose an 'optimal' set of candidate 
partitions so as to minimize estimated model latency, such that every sub-expression
node is contained in exactly one candidate partition.
6. Coalesces adjacent optimal candidates which ended up on the same target.
7. Rewrites the …
> [Collage] CollagePartition pass

- python/tvm/target/target.py
PR #11389 introduced a bug that effectively disabled cuda integer dot products by comparing `self.kind` (which is type Target) to the string `"cuda"`. This extremely small PR fixes the check by instead using `self.kind.name`. This will lead to significant performance improvements for int8 models.
> Fix bug that disabled cuda integer dot product.

- python/tvm/relay/op/contrib/dnnl.py
- src/relay/backend/contrib/dnnl/codegen.cc
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
This patch is to enable convolution family (conv2d, conv3d, conv2d_transpose, conv3d_transpose) fused with gelu activation. Some unittests are also included.
> [DNNL] Enable conv family fused with gelu

- include/tvm/target/compilation_config.h
- src/relay/transforms/device_domains.cc
- src/relay/transforms/device_planner.cc
- src/target/compilation_config.cc
- src/target/target.cc
- tests/cpp/target/compilation_config_test.cc
- tests/cpp/target/virtual_device_test.cc
- tests/python/relay/test_pass_plan_devices.py
Previously Primitive=1 functions were not analyzed and calls to such were completely
unconstrained. With this change at least any virtual device annotation on the function
are respected and accounted for in calls, even though the body is not analyzed.
While working on the unit test noticed it is possible to end up with two structurally equal
virtual devices which are not pointer equal even after canonicalization. Fix that by
introducing target canonicalization on the CompilationConfig.
This may help with piggy-backing on PlanDevices for doing memory scope analysis, since
it is now possible to express cross-scope functions on Primitive functions. However
I believe there are other issues to deal with in addition to this one.
> [Relay] Allow Primitive functions to carry virtual device annotations in PlanDevices

- include/tvm/support/with.h
Currently the With<> template constructs an object, but gives no access to it, so it's only applicable to situations where we rely on the side-effects of creating the object.
> Add member object accessors to With<>

- include/tvm/meta_schedule/schedule_rule.h
- python/tvm/meta_schedule/schedule_rule/multi_level_tiling.py
- python/tvm/meta_schedule/testing/schedule_rule.py
- src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py
This PR made it possible to specify multiple tensor core intrinsics (for different dtype) at the same time.
cc @masahi @spectrometerHBH @junrushao1994
> [MetaSchedule] Allow MultiLevelTilingTensorCore rule to specify multiple tensor intrin groups

- include/tvm/ir/expr.h
- include/tvm/tir/op.h
- src/target/target.cc
- src/tir/usmp/analysis/extract_buffer_info.cc
If a compilation unit includes `<tvm/ir/expr.h>`, but does not include `<tvm/tir/op.h>`, the operator overloads for `ObjectRef` are declared, but the operator overloads for `PrimExpr` are not.  In this case, any use of `expr_a == expr_b` would use `ObjectRef`'s implementation and compare reference equality of the two expressions, rather than returning a `PrimExpr` that represents the comparison.  By having the operator overloads in the `<tvm/ir/expr.h>` header file, directly adjacent to the `PrimExpr` declaration, the correct overload must be available whenever the `PrimExpr` can be used.
Even though this would only impact `operator==`, `operator!=`, and `operator<`, the three operators defined for `ObjectRef`, this PR moves all operator overloads to `expr.h` for consistency.
The named …
> [TIR] Moved PrimExpr operator overload from op.h to expr.h

- src/auto_scheduler/feature.cc
In autoscheduler's featurization, arithmetic intensity was incorrectly calculated as log(FLOPs) / log(bytes). This change removes the logs so arithmetic intensity is FLOPs / bytes.
@junrushao1994 @merrymercy @octoJon
> [AUTOSCHEDULER,FIX] Calculate arithmetic intensity without log scale

- python/tvm/relay/expr.py
- src/relay/backend/graph_plan_memory.cc
- src/relay/backend/utils.cc
- tests/python/relay/test_backend_graph_executor.py
Co-authored-by: Chris Sullivan <csullivan@octoml.ai>
This PR is a split part of origin PR11357
@csullivan @mbs-octoml
> [Texture] Add 2d memory support into static memory planner

- python/tvm/relay/backend/contrib/ethosu/legalize.py
- python/tvm/relay/op/contrib/ethosu.py
- tests/python/contrib/test_ethosu/test_codegen.py
- tests/python/contrib/test_ethosu/test_legalize.py
Adds support for hard swish by populating a LUT similar to Vela's implementation.
cc @Mousius @manupa-arm
> [microNPU] Add support for hard swish

- src/arith/iter_affine_map.cc
- tests/python/unittest/test_arith_intset.py
- tests/python/unittest/test_arith_iter_affine_map.py
- tests/python/unittest/test_meta_schedule_space_cpu.py
- tests/python/unittest/test_meta_schedule_space_cuda.py
- tests/python/unittest/test_tir_schedule_reorder.py
- tests/python/unittest/test_tir_schedule_split_fuse.py
- tests/python/unittest/test_tir_schedule_state_cached_flags.py
The change wants to support detect non-bijective iteration sum like `h + kh` or `4 * i + j, j in [0, 6)` etc. Previously they would not pass `DetectIterMap` either in bijective or surjective mode.
IIUC, one of the `DetectIterMap`'s main concentration is on iteration bindings which can perfectly split/fuse from loop index vars, however, there are also a wider range of applications on memory access indices analysis and non-perfect tilings. Thus it would be great that certain index patterns could also get supported. For example,
- `h + kh`:  an index pattern common in stride=1 convolution or poolings.
-  `4 * co + ci`, `ci`'s extent is larger than `co`'s scale:  typically occurs in overlapped input tiles.
Currently they are not supported in `TryFuseIters` routine of `DetectIterMap`, since …
> [Arith] DetectIterMap support overlapped iteration sum

- tests/lint/pylint.sh
- tests/python/contrib/test_hexagon/benchmark_util.py
- tests/python/contrib/test_hexagon/conftest.py
- tests/python/contrib/test_hexagon/conv2d/test_conv2d_blocked.py
- tests/python/contrib/test_hexagon/conv2d/test_conv2d_conv2d.py
- tests/python/contrib/test_hexagon/infrastructure.py
- tests/python/contrib/test_hexagon/test_2d_physical_buffers.py
- tests/python/contrib/test_hexagon/test_benchmark_elemwise_add.py
This is the first of a few PRs I'll raise to update the hexagon tests pylint compliant.
This patch fixes the below 7 files
This is part of the larger effort tracked in #11414 to make all tests in TVM pylint compliant
> [Pylint] Making hexagon tests pylint compliant Part 1 of N

- python/tvm/driver/tvmc/frontends.py
- tests/python/driver/tvmc/conftest.py
- tests/python/driver/tvmc/test_frontends.py
This feature enables passing a textural representation of a relay module to the tvmc command line.
Example: `tvmc compile relay.txt --target c --runtime=crt --executor=aot --executor-aot-unpacked-api=1 --pass-config tir.disable_vectorize=1 -f mlf`
Currently it is not possible to supply parameters as it is mainly intended to be used for testing certain relay functions or operators. In the future (with minor changes to the tvmc frontend api) params could be passed via an additional i.e. `params.bin` file
This commit also adds minimal unit testing of the added feature.
> TVMC: Add new text/relay frontend

- apps/microtvm/arduino/template_project/microtvm_api_server.py
- python/tvm/micro/testing/evaluation.py
- python/tvm/micro/testing/utils.py
- tests/micro/common/test_autotune.py
This change makes the Arduino `read_transport` and `write_transport` methods obey the timeout parameters passed into them. This change is required if we wish to run large models multiple times to get a better average runtime. Also contains a few fixes to improve autotuning:
- Adds an optional `timeout_override` parameter to `create_aot_session`, allowing this function to be used to evaluate large models.
- Changes `tvm.micro.testing.get_target` to use `-device=arm_cpu` by default. 
> [microTVM] Make Arduino API server obey timeout

- apps/microtvm/arduino/template_project/microtvm_api_server.py
- apps/microtvm/arduino/template_project/tests/test_arduino_microtvm_api_server.py
Previously, the `flash` function would sometimes lock up indefinitely without failing, stalling for hours or more. This pull request changes it to have a 60-second timeout (more than enough time to upload a sketch), and adds the ability to retry the command if it fails.
This pull request also adds a unit test for this functionality, and also makes a few changes to `microtvm_api_server.py` to better comply with `pylint`. 
> [microTVM] Arduino retry on flash failure

- src/arith/iter_affine_map.cc
- tests/python/unittest/test_arith_intset.py
- tests/python/unittest/test_arith_iter_affine_map.py
- tests/python/unittest/test_meta_schedule_space_cpu.py
- tests/python/unittest/test_meta_schedule_space_cuda.py
- tests/python/unittest/test_tir_schedule_reorder.py
- tests/python/unittest/test_tir_schedule_split_fuse.py
- tests/python/unittest/test_tir_schedule_state_cached_flags.py
Reverts apache/tvm#12039
Seems like the CI [has been failing](https://github.com/apache/tvm/commits/main) since #12039.  Providing a quick fix for this might not be very trivial, and therefore I am opening this PR to revert the change. 
@wrongtest-intellif, @Hzfengsy, @spectrometerHBH
> [skip ci] Revert "[Arith] DetectIterMap support overlapped iteration sum"

- python/tvm/tir/schedule/_type_checker.py
- python/tvm/tir/schedule/schedule.py
We do have type annotations for tir primitives
```Python
@type_checked
def get_block(
self,
name: str,
func_name: Optional[str] = None,
) -> BlockRV:
```
However, after calling the decorator `@type_checked`, all functions become `(func: (...) -> Any) -> ((...) -> Any)`. So there are no code suggestions during programming. Please see the following screenshot:
After the fix, it becomes
> [UX][TIR][Schedule] enhance function annotation for tir primitive

- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/ethosn_api.cc
- src/relay/backend/contrib/ethosn/ethosn_api.h
- tests/python/contrib/test_ethosn/test_concatenate.py
- tests/python/contrib/test_ethosn/test_mean.py
- tests/python/contrib/test_ethosn/test_networks.py
Some operations were being offloaded when they are not supported by the NPU, for example mean could get offloaded with different quantization parameters for the input and output which is not supported. Consequently, this meant that there would be a failure during compilation or an output mismatch at runtime. Fixing this by supplying the output information to the issupported checks that determine whether an operation should be offloaded.
cc @Leo-arm @manupa-arm
> [ETHOSN] Supply output tensor to issupported checks

- src/arith/detect_linear_equation.cc
- tests/python/unittest/test_arith_detect_clip_bound.py
This patch enhance DetectClipBound function support input PrimExpr includes tir.Not or tir. Min or tir.Max.
Eg: (1)(!(a > (b*6)) && ((a - 1) > 0))
(2) ((min(a, b) > 3) && ((a - 10) < 0))
cc @wrongtest-intellif
> [arith][BugFix] Fix simplify input PrimExpr of DetectClipBound

- python/tvm/_ffi/base.py
- python/tvm/script/tir/__init__.py
- python/tvm/script/tir/ty.py
- src/printer/tvmscript_printer.cc
- tests/python/unittest/test_tvmscript_roundtrip.py
Add missing type annotation `T.void` of prim type `void`, since either `""` or `None` is not valid type generic.
This is used by PrimFunc with packed api:
```python
@T.prim_func
def default_function(args: T.handle, arg_type_ids: T.Ptr[T.int32], num_args: T.int32,
out_ret_value: T.Ptr[T.void], out_ret_tcode: T.Ptr[T.int32], resource_handle: T.handle) -> T.int32:
```
> [TVMScript] Fix T.Ptr[T.void] for packed api roundtrip

- python/tvm/topi/adreno/conv2d_winograd_common.py
Winograd schedule for x axis assumed split by 3 dimensions and required to have in some dimension value bigger than 4. If we have shape less than 4 r not dividable values, we have got an interruption of compilation on this split even if winograd is not selected
> [Adreno] Fix winograd schedule to support prime shapes > 4

- tests/python/contrib/test_hexagon/pytest_util.py
- tests/python/contrib/test_hexagon/topi/test_avg_pool2d_slice.py
- Add utility functions to allow more human-readable pytest test IDs.
Helpful when ID strings become too large for humans to easily read.
- Update the `test_avg_pool2d_slice.py` unit test to use this mechanism.
cc @mehrdadh
> [hexagon][testing] Better pytest ID strings

- python/tvm/relay/frontend/qnn_torch.py
- python/tvm/relay/qnn/op/qnn.py
- python/tvm/relay/transform/fake_quantization_to_integer.py
- src/relay/qnn/op/leaky_relu.cc
- tests/python/frontend/pytorch/qnn_test.py
- tests/python/relay/test_op_qnn_leaky_relu.py
cc @AndrewZhaoLuo @margaretqian
> [QNN] Support different qnn params between in/out tensor in leaky_relu

- tests/python/contrib/test_hexagon/pytest_util.py
- tests/python/contrib/test_hexagon/topi/test_avg_pool2d_slice.py
Add support for populating unit-test input tensors with values other than random.
cc @mehrdadh
> [hexagon][testing] nonrandom tests

- python/tvm/topi/hexagon/slice_ops/__init__.py
- python/tvm/topi/hexagon/slice_ops/tanh.py
- tests/python/contrib/test_hexagon/topi/test_tanh_slice.py
> [TOPI] [HEXAGON] Tanh Float16 Slice Op

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to add `aten::numpy_T` for the pytorch frontend, which is used in models like `moco` in torchbench. 
- Link to the pytorch doc: https://pytorch.org/docs/stable/tensors.html?highlight=tensor%20t#torch.Tensor.T
cc: @masahi
> [PyTorch] Add aten::numpy_T

- gallery/how_to/work_with_relay/using_pipeline_executor.py
> [Doc] Fix URL link error in pipeline executor tutorial

- include/tvm/tir/transform.h
- python/tvm/script/tir/scope_handler.py
- python/tvm/tir/transform/transform.py
- src/driver/driver_api.cc
- src/meta_schedule/postproc/verify_gpu_code.cc
- src/tir/transforms/flatten_buffer.cc
- src/tir/transforms/lower_opaque_block.cc
- tests/python/unittest/test_tir_buffer.py
- tests/python/unittest/test_tir_transform_flatten_buffer.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
- tests/python/unittest/test_tir_transform_loop_partition.py
- tests/python/unittest/test_tir_transform_lower_opaque_block.py
This PR intends to decouple flatten buffer pass to lower opaque block and flatten buffer passes. Test cases have been added.
Reasons for the change:
- > Lower opaque block and flatten buffer pass names can express clearly what they do.
- > It's more simply to analyze the buffer shape before flatten buffer with multi-dimension.
> [TIR Pass] Decouple flatten buffer to lower opaque block and flatten buffer.

- NOTICE
- conda/recipe/meta.yaml
- docs/conf.py
- include/tvm/runtime/c_runtime_api.h
- python/tvm/_ffi/libinfo.py
- version.py
- web/package.json
This updates the version numbers after the v0.9.0 release and adds a version selector option for the v0.9.0 docs.
cc @areusch
> Update to 0.10.0

- apps/microtvm/arduino/template_project/boards.json
- python/tvm/micro/testing/evaluation.py
- tests/micro/arduino/test_arduino_workflow.py
Fixes a small bug causing `test_arduino_workflow.py` to fail. Also updates a comment in `boards.json` to reflect a GitHub issue that has since been fininshed.
> [microTVM] Fix timeout of -1 breaking Arduino transport

- include/tvm/tir/schedule/schedule.h
- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/error.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/decompose_padding.cc
- src/tir/schedule/primitive/reduction.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- tests/python/unittest/test_tir_schedule_decompose_padding.py
Hi there, this PR wants to introduce a new TIR schedule primitive `schd.decompose_padding(block, loop)`.
For padded `conv` or `pooling` ops, there is a typical padding pattern:
`Pad[_] = T.if_then_else(pad_predicate, X[_], pad_value)` 
which could be decomposed into two parts:
- One filling pad values with `memset` routine
- One filling in-bound values with `memcpy` routine
The primitive's signature is alike `decompose_reduction`, which provides a target block and a loop position to insert newly created "init" block. It is helpful for infrastructures with high-performance memset/memcpy routines, and leverage the complexity to process padding conditions in the main compute block.
- Before
```python
@T.prim_func
def before_decompose(x: T.Buffer[128, "int32"], y: T.Buffer[140, "int32"]):
for …
```
> [TIR][Schedule] DecomposePadding

- python/tvm/topi/nn/pooling.py
A minor document fix of `topi.nn.poolxd` `dilation` arguments.
> [Doc] Fix pooling `dilation` arguments documents

- src/runtime/file_utils.cc
- src/runtime/file_utils.h
- src/runtime/hexagon/hexagon_module.cc
- Add `tvm::runtime::CopyFile` function.
- Change `HexagonModuleNode::SaveToFile` to use new function
instead of a shell `cp` invocation.
This fixes a problem where the `cp`-based implementation
couldn't handle certain valid filenames.
This also fixes a bug where `SaveToFile` simply skips the
file-copying step on Mac OSX.
cc @areusch @mehrdadh
> [runtime][hexagon] improved file-copy logic

- tests/python/contrib/test_hexagon/pytest_util.py
- Change the formula used to compute pytest test-ID strings.
The previous formula included '(' and ')' characters, which
can cause the filename to require escaping / quoting on the
Bash command line.
cc @mehrdadh
> [hexagon][testing] filesystem-friendly test IDs

- src/runtime/graph_executor/debug/graph_executor_debug.cc
- src/runtime/opencl/opencl_common.h
- src/runtime/opencl/opencl_device_api.cc
- tests/cpp-runtime/opencl/opencl_timer_test.cc
Profiling for OpenCL runs was hanging because nested timer runs were not correctly handled. This is because each call to the `Timer::Start` function on OpenCL device causes the OpenCL event queue to be cleared.
The hang was due to the fact that the minimum run time was not reached for profiling, if it is set greater than zero. Since the queue is cleared every `Start` call, the time of only one run is returned, not `number`.
It happens in this cycle:
https://github.com/apache/tvm/blob/75ec1cffa9f160dd3165fedbf4408731ebfa797a/src/runtime/profiling.cc#L876-L891
Here `pf.CallPacked(args, &temp)` call function which contains one more call `Timer::Start` and `Timer::End`.
Also profiling was hanging for `__nop` functions like `reshape` due to there are no OpenCL calls for this node. So that …
> [OpenCL] Fix profiling hang for OpenCL device

- include/tvm/runtime/builtin_fp16.h
- src/runtime/builtin_fp16.cc
- src/target/llvm/llvm_module.cc
Code that handles fp16 and fp32 may end up calling builtins that do the conversions between these types. LLVM emits calls to `__truncsfhf2`, and `__extendhfsf2`, which are not present in TVM or TVM runtime. This creates two problems:
- Problem 1: JITed code that does the conversions will fail because it calls non-existent functions.
Adding these functions to libtvm.so/libtvm_runtime.so solves this part, but there is another issue:
- Problem 2: JITed code may still not call these functions, because the generated object may not be fully resolved.
To force full resolution, try to obtain an address of a non-existent symbol.
> [JIT] Force finalization of JITed code, expose sf/hf runtime functions

- src/relay/backend/vm/manifest_lifetimes.cc
- src/relay/quantize/calibrate.cc
- src/relay/transforms/device_planner.cc
- src/te/operation/create_primfunc.cc
- src/tir/schedule/primitive/blockize_tensorize.cc
- src/tir/schedule/primitive/cache_read_write.cc
- src/tir/transforms/flatten_buffer.cc
- src/tir/transforms/remove_weight_layout_rewrite_block.cc
- src/tir/usmp/transform/assign_pool_info.cc
Returning an instance of a subclass of the return type disable copy elision, `std::move` is needed in this case.
> Use std::move to avoid warnings on clang-13

- tests/python/ci/test_ci.py
- tests/scripts/open_docker_update_pr.py
This ignores any images that don't match the pattern laid out in https://github.com/apache/tvm-rfcs/pull/66
> [ci][docker] Use RFC image tags only

- src/target/target.cc
- tests/cpp/target_test.cc
- `SplitString` now preserves escape sequences, but still observes quote characters.
- Added function `Interpret` that transforms given string according to interpretation rules:
- outermost quotes are removed (if present),
- escape sequences inside quotes are preserved verbatim,
- unquoted escape sequences produce the escaped character (the escape character (\\) is removed.
- Interpretation happens every time a value of any type is to be parsed from a string, e.g. Array<String> will first be parsed as an array, then substrings of the input will be parsed as individual elements of that array. In this case, some parts of the initial input will be parsed (and interpreted) twice.
- Implement corresponding stringification functionality.
This new scheme enabled encoding nested arrays of string …
> [Target] Improve string interpretation in Target creation

- docker/dev_common.sh
This makes `run_docker` just pass through the image name to `bash.sh`
without preprocessing it at all so that `bash.sh` can do its own
determination of which image to actually use.
> [ci][lint] Consolidate image lookup logic

- include/tvm/script/printer/doc.h
- python/tvm/script/printer/_ffi_api.py
- python/tvm/script/printer/doc.py
- python/tvm/script/printer/doc_printer.py
- src/script/printer/doc.cc
- tests/python/unittest/test_tvmscript_printer_doc.py
This PR addes:
- All StmtDoc subclasses
- Python bindings for StmtDoc
> [TVMScript] StmtDoc Definitions

- python/tvm/topi/adreno/conv2d_winograd_common.py
- tests/python/relay/test_conv2d_nchw_texture.py
- tests/python/relay/utils/adreno_utils.py
> [Adreno] Fix winograd tests and accuracy

- tests/python/frontend/tflite/test_forward.py
1. As #11356 said. The entry of the ` _test_tflite2_quantized_depthwise_convolution` has been completed.
2. And an input_node error has also been fixed, because the input name of the tflite model quantized by the `_quantize_keras_model()` will be rewritten(no longer `data_in.name.replace(":0", "")`)
> [TFLite] Fix _test_tflite2_quantized_depthwise_convolution is unused

- src/script/printer/base_doc_printer.cc
- src/script/printer/base_doc_printer.h
- src/script/printer/python_doc_printer.cc
- tests/python/unittest/test_tvmscript_printer_python_doc_printer.py
This PR addes:
- StmtDoc Printing in PythonDocPrinter
> [TVMScript] StmtDoc Printing

- tests/scripts/git_change_docker.sh
* This patch addresses #12097 by referencing the branch from the `BRANCH_NAME` environment variable, which is also used in the Jenkinsfile
* This avoids git rev-parse, which assumes the local repo contains a git branch that matches the name of the branch being merged. I think this is in spirit of what the script was trying for.
cc @Mousius @driazati @yongwww
> [ci] Attempt to fix post-merge builds on main

- docs/conf.py
- gallery/how_to/work_with_microtvm/micro_aot.py
- tests/scripts/task_python_microtvm.sh
cc @areusch @gromero @guberti @alanmacd
> [microTVM][tutorial] AOT host-driven tutorial with TFLite model

- python/tvm/utils/roofline.py
Fix a bug where roofline analysis would crash if the provided tir functions do no match the profiling report.
@AndrewZhaoLuo
> [FIX,ROOFLINE] Handle mismatched compiled and TIR hash

- apps/microtvm/zephyr/template_project/microtvm_api_server.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/common.py
Removing arm_math.h which is not available
post CMSIS upgrade and is not in use by NN
tests.
cc: @leandron
> Removing header arm_math.h which  was moved after CMSIS upgrade

- python/tvm/meta_schedule/tune.py
- src/meta_schedule/space_generator/post_order_apply.cc
This PR fixes 2 incorrect description to the functions, one is `tune_relay` api, and the other one is for post order apply space generator, which does collect the root block. CC @sunggg
> [MetaSchedule][Minor] Fix Comments

- src/tir/schedule/analysis/analysis.cc
- tests/python/unittest/test_tir_schedule_analysis.py
> [TIR] Disallow unused rhs vars in GetAutoTensorizeMapping

- .github/workflows/main.yml
android_rpc build problem: https://github.com/apache/tvm/issues/12191
The problem with the build appeared due to the fact that the `ANDROID_NDK_HOME` environment variable was removed in the current version of github actions. 
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
But this variable is used here:
https://github.com/apache/tvm/blob/ee319d9d23c80091da9c4fb764b1e6d49d462714/.github/workflows/main.yml#L122-L127
Now only `ANDROID_NDK_LATEST_HOME` is available for ndk.
> [CI] Fix build android rpc failure in CI

- docker/Dockerfile.ci_riscv
Move RISC-V related content from ci_qemu to ci_riscv
@areusch
cc @Mousius @driazati
> [ci][docker] create Dockerfile.ci_riscv

- src/relay/qnn/op/requantize.cc
Currently, lowering qnn.requantize in FP mode generates duplictated cast to float ops at the beginning, this patch removes the dpulicated cast op.
cc @masahi @AndrewZhaoLuo for code review.
> [QNN]remove duplicated cast op when lowering qnn.requantize op in float mode

- include/tvm/runtime/vm/vm.h
https://github.com/apache/tvm/blob/dff5c975a082e6f15b556914a029541b63ff1280/include/tvm/runtime/vm/vm.h#L97
Since the referenced parameter `params` and `param_device_indexes` is moved in the member initializer list, 
the assertion `ICHECK_EQ(params.size(), param_device_indexes.size())` is equivalent to `ICHECK_EQ(0, 0)` that never fails,
which makes the `ICHECK` meaningless.
PTAL @ganler @junrushao1994  ❤️
> [Relay][VM] Fix an ICHECK which never fails in ctor of VMFunction

- python/tvm/script/highlight.py
Previously we use ANSI color sequences to highlight TVM script. In jupyter notebook environments, such color sequence will be recoginized and translated to corresponding HTML to display things. 
This works fine for most notebook environments (including the jupyter notebook and the VS Code plugin). Recently, thanks to @tqchen, we found that Google Colab does not well support ansi color sequence for 24-bit colors (`JupyterLight` and `VSCDark`) that all its displayed colors are unexpectedly black/gray/white. To also bring highlighting in Colab, in this PR, we directly render the highlighted code with HTML when a notebook environment is detected.
cc: @tqchen @Hzfengsy
> [UX][TVMSciprt] Use HTML formatter in notebook environments

- tests/python/unittest/test_meta_schedule_space_cpu.py
- tests/python/unittest/test_meta_schedule_space_cuda.py
> [MetaSchedule][Test] Add unittests for GMM

- python/tvm/relay/frontend/paddlepaddle.py
fix paddle model2tvm, can't find key:
int  relay/frontend/paddlepaddle.py
self.params[name] = _nd.array(scope[name])
KeyError: 'generated_tensor_0'
@siju-samuel
cc @jiangjiajun @heliqi
> fix bug: KeyError, can't find some parameter key

- tests/python/unittest/test_meta_schedule_space_cpu.py
- tests/python/unittest/test_meta_schedule_space_cuda.py
> [MetaSchedule][Test] Add unittests for GRP

- python/tvm/relay/op/contrib/dnnl.py
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
- tests/python/relay/test_pass_partition_graph.py
This PR add `conv2d-add-sum-relu` pattern, and the corresponding test case is added.
> [BYOC-DNNL] add post_sum pattern

- include/tvm/script/printer/doc.h
- python/tvm/script/printer/doc.py
- src/script/printer/doc.cc
- src/script/printer/python_doc_printer.cc
- tests/python/unittest/test_tvmscript_printer_doc.py
- tests/python/unittest/test_tvmscript_printer_python_doc_printer.py
This PR:
- Handle expression (operator) precedence during Python code printing (`(* 1 (+ 2 3))` prints as `1 * (2 + 3)`)
- Addresses remaining feedback from previous PR https://github.com/apache/tvm/pull/12112
- Reformats Python import with isort
> [TVMScript] Python Expression Precedence

- python/tvm/relay/op/contrib/dnnl.py
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- tests/python/contrib/test_dnnl.py
Mish activation function is widely used in object detection, like yolov4, scaledYolov4. This patch is to enable dnnl to support conv+mish fusion. It will bring huge performance boost varied from 2.4x to 2.8x.
@masahi @apeskov 
> [BYOC][DNNL] Enable conv family fused with mish

- apps/cpp_rpc/rpc_env.cc
The GetPath function can only use filenames as input, not relative paths.
Assuming the workpath is `/data/local/tmp/rpc`, and when I use `GetPath("dataset/img.jpg")`,  the expected result is `/data/local/tmp/rpc/dataset/img.jpg` instead of `dataset/img.jpg`.
> [CPP-RPC] Fix GetPath to use relative file path

- tests/scripts/task_demo_microtvm.sh
`task_demo_microtvm.sh` fails when running on a container because it can't find TVM. Adding a regular `source ...task_demo_microtvm.sh` will make the proper test environment setup.
cc @Mousius @areusch @driazati for reviews.
> [CI] Add setup-pytest-env.sh call to task_demo_microtvm.sh

- python/tvm/testing/utils.py
- tests/python/unittest/test_tir_transform_simplify.py
- tests/python/unittest/test_tvm_testing_before_after.py
This PR adds `tvm.testing.CompareBeforeAfter`, a generalization of the `BaseBeforeAfter` utility previously used in `test_tir_transform_simplify.py`, which performs unit tests that perform a transformation on a TIR function and compare the results to an expected TIR output.  This arose when minimizing the boilerplate required for unit tests in the implementation of https://github.com/apache/tvm/issues/12261.
> [UnitTest][TIR] Testing utility for before/after transform tests

- tests/python/unittest/test_custom_datatypes.py
This should fix the error from #11580, the test will still get run but
the registration failing will be ignored if it happens
> Hide registration errors in `test_myfloat`

- src/meta_schedule/utils.h
The previous median number calculation util function used the wrong index which could cause out of bound issue as mentioned in #12199 . This PR fixed this issue.
CC @junrushao1994
> [MetaSchedule][Minor] Fix Median Number

- tests/lint/pylint.sh
- tests/python/contrib/test_hexagon/test_autotvm.py
- tests/python/contrib/test_hexagon/test_cache_read_write.py
- tests/python/contrib/test_hexagon/test_launcher.py
- tests/python/contrib/test_hexagon/test_maxpool2d_blocked.py
- tests/python/contrib/test_hexagon/test_models.py
- tests/python/contrib/test_hexagon/test_run_unit_tests.py
- tests/python/contrib/test_hexagon/test_thread_pool.py
- tests/python/contrib/test_hexagon/test_usmp.py
Second set of **hexagon tests** modified to be pylint compliant as part of #11414 tracking issue. The files supported in this patch are:
> [Pylint] Making hexagon tests pylint compliant Part 2 of N

- tests/python/frontend/tensorflow/test_forward.py
This pr disables TensorFlow tests that fail on AArch64. 
We need this pr because we want to enable TensorFlow tests on AArch64.
A future pr will fix the failing tests.
> [TensorFlow] Disable failing tests on AArch64

- tests/python/frontend/onnx/test_forward.py
This pr disables ONNX tests that fail on AArch64. 
We need this pr because we want to enable ONNX tests on AArch64.
A future pr will fix the failing tests.
> [ONNX] Disable failing tests on AArch64

- tests/python/frontend/pytorch/test_forward.py
This pr disables PyTorch tests that fail on AArch64. 
We need this pr because we want to enable PyTorch tests on AArch64.
A future pr will fix the failing tests.
> [PyTorch] Disable failing tests on AArch64

- python/tvm/driver/tvmc/workspace_pools.py
- tests/python/driver/tvmc/test_workspace_pools.py
After #11427, `tvmc compile` wouldn't work for external codegens that don't have a `Target` registered by `TVM_REGISTER_TARGET_KIND`. This results in the error:
```
ValueError: Target kind <codegen> is not defined. Target creation from string failed: <target-string>
```
Such external codegens can be expected to have no workspace pools and may not always have a target associated as their implementation predates this mechanism. While it is likely a `Target` is specified for all external codegens in the future, we should still support external codegens without an associated `Target` until this is enforced.
cc @Mousius @areusch @dchauhan-arm @gromero @leandron
> [TVMC] Only load extra targets when there are workspace pools

- docker/install/ubuntu_install_onnx.sh
This pr updates onnxoptimizer to 0.2.7 to support AArch64.
We need this pr because we want to enable ONNX tests on AArch64, but the current version of onnxoptimizer does not support AArch64.
> [Docker] Update onnxoptimizer to 0.2.7

- .github/workflows/main.yml
Reverts apache/tvm#12216
Addition to my previous changes.
After the previous changes, the android camera build failed because by default `PYTHONPATH` is empty, and after `set -eux` it is fails:
https://github.com/apache/tvm/blob/759a648cd5237885a8205b1ee4508dabcc3af2d5/.github/workflows/main.yml#L152-L156
This error was not noticed because the flag `continue-on-error` is true.
> Revert "[CI] Fix build android rpc failure in CI"

- docs/contribute/release_process.rst
- tests/scripts/release/.gitignore
- tests/scripts/release/README.md
- tests/scripts/release/gather_prs.py
- tests/scripts/release/list_rfcs.py
- tests/scripts/release/make_notes.py
This adds a script release managers can use to generate a list of PRs associated with commits between two hashes, which is useful for creating the release notes. It also updates some places in the release notes and includes instructions on updating the docs site too.
> [release] Follow ups from v0.9.0 - scripts, docs

- .github/workflows/main.yml
- .github/workflows/tvmbot.yml
- tests/scripts/git_utils.py
- tests/scripts/github_tvmbot.py
This adjusts some error reporting for tvm-bot and manually specifies the permissions it should run with to hopefully alleviate the 403 errors when merging PRs
> [ci] Specify permissions for tvm bot

- include/tvm/node/reflection.h
- include/tvm/node/structural_equal.h
- python/tvm/ir/base.py
- python/tvm/runtime/__init__.py
- python/tvm/runtime/object_path.py
- src/node/reflection.cc
- src/node/structural_equal.cc
- src/node/structural_hash.cc
- src/tir/analysis/deep_equal.cc
- tests/python/unittest/test_container_structural_equal.py
- tests/python/unittest/test_tir_structural_equal_hash.py
Motivation: when two IR objects fail a structural equality check, currently there is no easy way to find out which part of the IR caused the mismatch. In this PR, we modify the `StructuralEqual` infrastructure to also optionally return a pair of `ObjectPath` objects that point to the mismatch. (See https://github.com/apache/tvm/pull/11977). In the upcoming PRs, we will pass these paths to the TIR printer, so that it could highlight the mismatch location nicely.
cc @yelite @junrushao1994
> [TVMScript] Add object path tracing to StructuralEqual

- Jenkinsfile
- ci/jenkins/macros.j2
`aws s3 cp` sometimes segfaults, so retry it when the command fails
Fixes #12136 
> [ci] Add retries to S3 uploads/downloads

- python/tvm/micro/testing/evaluation.py
- python/tvm/micro/testing/pytest_plugin.py
- tests/micro/.gitignore
- tests/micro/arduino/conftest.py
- tests/micro/arduino/test_arduino_error_detection.py
- tests/micro/arduino/test_arduino_rpc_server.py
- tests/micro/arduino/test_arduino_workflow.py
- tests/micro/arduino/test_utils.py
- tests/micro/common/conftest.py
- tests/micro/common/test_autotune.py
- tests/micro/zephyr/conftest.py
- tests/micro/zephyr/test_zephyr.py
- tests/micro/zephyr/test_zephyr_aot_exec.py
- tests/micro/zephyr/test_zephyr_aot_exec_standalone.py
- tests/micro/zephyr/test_zephyr_armv7m.py
- tests/scripts/task_python_microtvm.sh
Refactoring pytest fixtures between multiple directories. Using this change, we can reuse the same fixtures in external repositories
cc @alanmacd @gromero @guberti
> [microTVM] Refactor pytest fixtures

- src/tir/transforms/lower_thread_allreduce.cc
- tests/python/unittest/test_subwarp_reduction_cuda.py
This PR proposes a fix to #12274 by adding a single range check statement in sub-warp reduction.
```cuda
extern "C" __global__ void __launch_bounds__(11) default_function_kernel0(float* __restrict__ A, float* __restrict__ B) {
float red_buf0[1];
uint mask[1];
float t0[1];
red_buf0[0] = A[((((int)blockIdx.x) * 11) + ((int)threadIdx.x))];
mask[0] = __activemask();
t0[0] = __shfl_down_sync(mask[0], red_buf0[0], 8, 32);
red_buf0[0] = max(red_buf0[0], t0[0]);
t0[0] = __shfl_down_sync(mask[0], red_buf0[0], 4, 32);
red_buf0[0] = max(red_buf0[0], t0[0]);
t0[0] = __shfl_down_sync(mask[0], red_buf0[0], 2, 32);
red_buf0[0] = max(red_buf0[0], t0[0]);
t0[0] = __shfl_down_sync(mask[0], red_buf0[0], 1, 32);
red_buf0[0] = max(red_buf0[0], t0[0]);
red_buf0[0] = __shfl_sync(mask[0], red_buf0[0], 0, 32); …
```
> [TIR][CUDA] Fix sub-warp reduction using "max"

- python/tvm/topi/cuda/conv2d_winograd.py
- src/meta_schedule/schedule_rule/winograd.cc
- tests/python/unittest/test_meta_schedule_space_cuda.py
This PR introduces some new trials to expand the search space for Winograd Conv2d Workload by writing block level schedule rules. Tests will also be included.
> [MetaSchedule] Enhance Conv2d NCHW Winograd Schedule Rules

- tests/python/topi/python/test_topi_image.py
This PR aim to fix the naming bug caused by #8346. In #8346, `test_resize()` was changed to `test_resize2d()`, but it forgot to change the function name in main block. Just fix it.
> [Test]fix type bug about topi unitest

- apps/microtvm/arduino/template_project/microtvm_api_server.py
This commit fixes two f-strings on flash timeout exception and runtime
error so the proper variables (like port, number of retries, and timeout
value) are correctly printed to the warning / error messages.
Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>
cc @alanmacd @mehrdadh
> [microTVM] Arduino: Fix f-strings on flash warning/error messages

- tests/python/contrib/test_ethosn/test_topologies.py
The mock inference functionality is only supported when the whole graph is offloaded to the NPU, otherwise it can result in undefined behavior. This patch makes sure the mock inference functionality is not run on test cases where some parts of the graph are not offloaded to the NPU, while ensuring the module is still built as a sanity check.
cc @Leo-arm @manupa-arm @leandron
> [ETHOSN] Only use mock inference when whole graph is offloaded

- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/codegen_ethosn.h
- src/runtime/contrib/ethosn/ethosn_device.cc
- src/runtime/contrib/ethosn/ethosn_device.h
- src/runtime/contrib/ethosn/ethosn_runtime.cc
- src/runtime/contrib/ethosn/ethosn_runtime.h
- tests/python/contrib/test_ethosn/test_fullyconnected.py
- tests/python/contrib/test_ethosn/test_networks.py
The NPU support library compiler sometimes adds padding to input tensors which means the buffer sizes calculated at runtime can sometimes be smaller than necessary. Instead, buffer sizes are now collected at compile time and passed to the runtime so that they match the sizes expected by the compiled network. This was seen when running a fully connected operation with an input that is not a multiple of 1024, so testing has been added to cover this case.
Additionally changed the fully connected test case to use pytest parameterization as part of a general cleanup, and fixed the fully connected testing to support output channels > 1.
cc @Leo-arm @manupa-arm @leandron
> [ETHOSN] Get buffer sizes from the compiled network

- .github/workflows/main.yml
- .github/workflows/tvmbot.yml
- tests/python/ci/test_tvmbot.py
- tests/scripts/git_utils.py
- tests/scripts/github_tvmbot.py
This adds the right permissions so anyone associated with the repo can trigger a re-run (GitHub hasn't flagged all committers as repo `COLLABORATORS` for some reason so it's difficult to determine from a username who has commit rights) and makes it so `@tvm-bot rerun` also re-runs all the Actions on a PR.
> [ci][tvmbot] Enable re-run for GitHub Actions

- python/tvm/relay/qnn/op/__init__.py
- python/tvm/relay/qnn/op/legalizations.py
- python/tvm/relay/qnn/op/qnn.py
- python/tvm/relay/transform/fake_quantization_to_integer.py
- src/relay/qnn/op/unary_elementwise_op.cc
- src/relay/transforms/pattern_utils.h
- tests/python/relay/test_pass_fake_quantization_to_integer.py
Prior implementation caused the FQI pass to produce the following graph when `abs` was used:
```
%14 = qnn.dequantize(%13, 6.4712f /* ty=float32 */, 119 /* ty=int32 */, axis=1) /* ty=Tensor[(1, 960, 512, 64), float32] */;
%15 = abs(%14) /* ty=Tensor[(1, 960, 512, 64), float32] */;
%16 = qnn.quantize(%15, 3.46196f /* ty=float32 */, 0 /* ty=int32 */, out_dtype="uint8", axis=1) /* ty=Tensor[(1, 960, 512, 64), uint8] */;
```
It seems that the output scale and zero point are different from the input scale and zero point. So, we doubled the precision. 
By adding a qnn op for `abs` we manage requantize on the right values.
```
def @main(%x: Tensor[(1, 960, 512, 64), int8] /* ty=Tensor[(1, 960, 512, 64), int8] */) -> Tensor[(1, 960, 512, 64), int8] {
%0 = qnn.abs(%x, 6.4712f /* ty=float32 */, 119 …
```
> [QNN] Add qnn op for abs to fix wrong scale on quantize

- include/tvm/script/printer/traced_object.h
- src/script/printer/traced_object.h
- tests/cpp/traced_object_test.cc
Motivation: when printing a piece of TIR, we need to track an ObjectPath from the root TIR object to the currently printed object. This means that we need a convenient way to maintain an ObjectPath whenever we access a sub-object, e.g. via an attribute.
cc @yelite @junrushao1994
> [TVMScript] TracedObject class that simplifies tracing ObjectPaths

- Jenkinsfile
- ci/jenkins/Test.groovy.j2
Fix for #12109 
This PR  increaseS the CPU integration test shards to `10` to keep runtime down.
@driazati @areusch @Mousius @gigiblender
> [CI] Increase CPU Intergration tests shards to speedup runtime

- include/tvm/tir/builtin.h
- python/tvm/script/tir/intrin.py
- python/tvm/tir/transform/transform.py
- src/printer/tvmscript_printer.cc
- src/tir/op/builtin.cc
- src/tir/transforms/remove_assume.cc
- tests/python/unittest/test_tir_transform_remove_assume.py
This PR introduces `tir::builtin::assume`, which is used to represent assumptions to be exposed to transformations, which would otherwise require out-of-scope information to prove.
This PR is part of the handling of padded buffer layout transformations ([tracking issue](https://github.com/apache/tvm/issues/12261), [rfc](https://github.com/apache/tvm-rfcs/pull/77)).  Later PRs will introduce transformations that make use of the information provided by assumptions.
> [TIR] Add tir::builtin::assume

- include/tvm/script/printer/doc.h
- python/tvm/script/printer/doc.py
- src/script/printer/doc.cc
- tests/python/unittest/test_tvmscript_printer_doc.py
This PR:
- Add the source_paths attribute to Doc base class.
- Add the corresponding Python binding for it.
This PR is depended by multiple tasks, including the diagnostic output in DocPrinter, VarTable and IRDocisifer.
Co-authored-by: Greg Bonik <gbonik@octoml.ai>
> [TVMScript] Add source_paths to Doc

- include/tvm/tir/stmt.h
- include/tvm/tir/stmt_functor.h
- python/tvm/script/tir/__init__.pyi
- python/tvm/script/tir/scope_handler.py
- python/tvm/script/tir/special_stmt.py
- python/tvm/tir/__init__.py
- python/tvm/tir/stmt.py
- src/printer/text_printer.h
- src/printer/tir_text_printer.cc
- src/printer/tvmscript_printer.cc
- src/target/source/codegen_c.cc
- src/target/source/codegen_c.h
- src/tir/ir/stmt.cc
- src/tir/ir/stmt_functor.cc
- tests/cpp/ir_functor_test.cc
- tests/python/unittest/test_tvmscript_roundtrip.py
This PR is part of https://github.com/apache/tvm/issues/11627. It added the IR node `DeclBufferNode`, IR functors and TVMScript printer / parser.
cc @tqchen @Lunderberg @Hzfengsy @junrushao1994 @wrongtest-intellif
> [TIR] Add DeclBuffer IR node and functors

- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_qemu
- tests/scripts/task_python_integration.sh
- tests/scripts/task_python_microtvm.sh
This would prevent rebuilding multiple image on each update on CMSIS, ethosu, etc.
cc @Mousius @alanmacd @areusch @gromero @leandron
> [microTVM][ARM] Keep microtvm testing only in QEMU Image

- include/tvm/tir/builtin.h
- python/tvm/tir/transform/transform.py
- src/tir/op/builtin.cc
- src/tir/transforms/remove_store_undef.cc
- tests/python/unittest/test_tir_transform_remove_undef.py
This PR introduces `tir::builtin::undef`, which is used to represent values that are an arbitrary value of a known datatype, along with a transformation to remove instances of `tir::builtin::undef`.
This PR is part of the handling of padded buffer layout transformations ([tracking issue](https://github.com/apache/tvm/issues/12261), [rfc](https://github.com/apache/tvm-rfcs/pull/77)).
> [TIR] Add tir::builtin::undef

- src/runtime/opencl/opencl_common.h
- src/runtime/opencl/opencl_device_api.cc
Resolves a few gcc warnings for comparing signed and unsigned integers.
> [OpenCL] Use size_t instead of int64_t for OpenCL timer count

- src/runtime/contrib/ethosn/ethosn_device.cc
- tests/python/contrib/test_ethosn/test_topologies.py
During compilation of an NPU subgraph, the input and output tensor ordering is determined by creating a mapping of Support Library buffers to TVM buffers. The runtime had been using this mapping incorrectly by instead interpreting it as a mapping of TVM buffers to support library buffers. This can result in undefined behavior. The runtime now interprets the mapping as Support Library buffers to TVM buffers.
A test has been added to check the correct ordering of outputs is provided correctly in the runtime.
cc @leandron @manupa-arm @Leo-arm
> [ETHOSN] Fix output tensor ordering

- Jenkinsfile
- ci/jenkins/macros.j2
- conftest.py
- tests/scripts/setup-pytest-env.sh
This PR does the following:
- When running on a shard,  removes the tests that will not run on the current shard from the suite. We'll no longer get the message `Test running on shard X of Y` in the XML reports. This will result in cleaner test reports.
- Adds the shard index or `no-shard` to the generated XML report file name. Currently, the reports generated when sharding is present are overwritten in S3 by the last shard to finish in the CI pipeline. This change is needed as part of #11670.
- Since the same tests might run on different configurations (CPU, GPU), it uploads the result of each configuration in a subdirectory in S3 (e.g `/pytest-results/frontend_aarch64`).
> [CI] Deduplicate and clean XML test reports

- Jenkinsfile
- ci/jenkins/macros.j2
Looks like #12332 broke [the CI](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3992/pipeline/389) due to a misuse in the `aws s3 cp` command. This PR fixes that.
@driazati
> [skip ci] Fix aws s3 cp command in the Jenkinsfile

- apps/microtvm/zephyr/template_project/microtvm_api_server.py
This bug was caught in the microtvm hardware in the loop CI. 
This PR changes microtvm template project to read BOARD from cmake file instead of cmake cache file.
> [microTVM][Zephyr] Fix bug: missing BOARD in CMakeCache file

- python/tvm/relay/op/contrib/dnnl.py
- tests/python/relay/test_pass_partition_graph.py
This PR fixes some bugs exist in BYOC-DNNL.
1. add checks for `bias` pattern and `sum` pattern, to ensure the catched pattern obeys the pre-defined order.
2. fix return error of `pad_pool` legalize.
3. add checks for op `pooling`. Only `ceil_mode=False` is supported. Currently, onednn pooling primitive has no attrs to support `ceil_mode=True`.
> [BYOC-DNNL] Bug Fix

- python/tvm/relay/op/strategy/x86.py
- python/tvm/topi/x86/nn.py
- tests/python/topi/python/test_topi_batch_norm.py
Follow up of https://github.com/apache/tvm/pull/9694. 
1. batch_norm returns a list and it might be tricky to 
- apply autotvm and add tiling stages. Need to unpack list object. (here node is a list)
https://github.com/apache/tvm/blob/ca46f21f5168f937cf9b1d205118c770c46aa8c5/python/tvm/autotvm/task/topi_integration.py#L168
- fuse with other kElemwise ops. I found that when batch_norm+relu, all 3 outputs [output, moving_mean, moving_var] are fused with relu and the latter 2 make no sense. Is it possible to select which node to fuse?
2. observed better perf with larger workloads due to parallism (Intel(R) Xeon(R) CPU @ 2.30GHz, 8cores)
```
shape=160, key=generic= {'mean': 0.48806950988364406, 'median': 0.02051979972748086, 'std': 1.402288376912746}
shape=160, key=cpu= {'mean': …
```
> [Topi] add x86 schedule for batch_norm

- python/tvm/utils/roofline/__init__.py
Only collect TIR PrimFuncs in roofline's SaveLoweredTIR. SaveLoweredTIR was saving the full Relay main function leading which could be excessively large. Also improve the logic to only save functions right before MakePackedAPI.
@AndrewZhaoLuo
> [FIX,ROOFLINE] Only save tir functions for roofline

- src/meta_schedule/feature_extractor/per_store_feature.cc
I fixed a bug in MetaSchedule per_store_feature.cc
> [MetaSchedule][Bugfix] Feature: Strides of buffer access

- src/tir/transforms/inject_virtual_thread.cc
- tests/python/unittest/test_tir_transform_inject_virtual_thread.py
If the injected index expressions can be simplified to Ramp nodes (e.g. `Ramp(0,1,4)` resulting in `Ramp(vthread*4, 1, 4)` instead of `Ramp(0,1,4) + Broadcast(vthread*4, 4)`), these can be identified as vector access in later passes.  Simplifying at the time of substitution avoids requiring all downstream passes to perform the simplification.
> [TIR] Simplify indices in InjectVirtualThread

- python/tvm/topi/hexagon/slice_ops/__init__.py
- python/tvm/topi/hexagon/slice_ops/max_pool2d.py
- tests/python/contrib/test_hexagon/topi/test_max_pool2d_slice.py
Add TOPI implementation of sliced max_pool2d.
cc @mehrdadh
> [hexagon][topi] add sliced max_pool2

- python/tvm/topi/generic/conv2d.py
This PR is trying to fix the wrong axis names of data_vec. As the data_vec is nchwc format, the axis names should be `batch, ic_chunk, ih, iw, ic_block`, but not `batch, ic_chunk, ih, ic_block, iw`.
Although the following code does not use these last two axises, so it does not cause some bugs for now. But I think we should fix this.
> [AutoTVM][Fix] Fix wrong axis names of data_vec

- src/target/llvm/codegen_hexagon.cc
1. Change calls to inherited functions to use `CodeGenCPU::` instead of `CodeGenLLVM::`.
2. Fix `#if` guards for `#include`s.
3. Remove `InitContextPtr` and `GetContextPtr`, use the ones from `CodeGenCPU`.
cc @mehrdadh
> [Hexagon] Minor changes/fixes in codegen_hexagon.cc

- include/tvm/meta_schedule/space_generator.h
- python/tvm/meta_schedule/space_generator/post_order_apply.py
- python/tvm/meta_schedule/tune.py
- src/meta_schedule/space_generator/post_order_apply.cc
- tests/python/unittest/test_meta_schedule_post_order_apply.py
- tests/python/unittest/test_meta_schedule_tune_tir.py
This PR extends `PostOrderApply` to allow passing in a function that filters which blocks have schedules generated. Although this could be used in many ways, I implement one example where blocks are filtered by name. This can be useful for hand optimizing part of a primfunc, and using metaschedule to tune other parts. I've added a new `Blocks` argument to `tune_tir` that allows users to optionally specify the names of blocks that should be tuned. If not provided, the behavior of `tune_tir` is exactly the same as before this PR.
> [MetaSchedule] Extend tune_tir to support tuning of specific blocks.

- python/tvm/relay/frontend/tflite.py
When importing model [yolov4](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/031_yolov4/01_float32) and [seresenet_xx](https://drive.google.com/drive/folders/1k5MtfqbNRA8ziE3f18vu00Q1FQCzk4__).
I got dynamic shape error `Check failed: (pval != nullptr) is false: Cannot allocate memory symbolic tensor shape [?, ?]`.
I firgue out that It happened  when the expression type of shape is [relay.Expr,](https://github.com/blackkker/Pic-host/blob/main/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220805112837.png) `_dyn_make.reshape` is called. Under normal circumstances, `_dyn_make.reshape`  will not be a problem, but it work incorrcetly in these case.
So i infer the value of shape expr to avoid dynamic. The code is refered to #9459 #6504 #7712
Thanks for contributing to TVM!   Please refer to …
> [Frontend][TFLite] Try Infer the value of shape expr to avoid dynamic

- python/tvm/script/tir/__init__.py
- python/tvm/script/tir/intrin.py
- python/tvm/script/tir/ty.py
- src/tir/transforms/storage_rewrite.cc
- tests/python/unittest/test_tir_transform_storage_rewrite.py
Storage rewrite was missing a visitor for let statements so buffers added in them would still refer to the pre-rewritten version. This error was originally noticed when using `global.vtcm` buffers which get changed to let statements by LowerVtcmAlloc.
Implementing the test for this change also required adding support for vectorized datatypes to tvmscript. The solution included is a little hacky and involes adding the datatypes to the `global()` table of each module they need to be defined in.
@Lunderberg @spectrometerHBH
> [FIX,STORAGE REWRITE] Rewrite buffers in let statements

- include/tvm/script/printer/traced_object.h
- include/tvm/script/printer/traced_object_functor.h
- src/script/printer/traced_object_functor.cc
- tests/cpp/tvmscript_printer_traced_object_functor_test.cc
This PR:
- Adds the registry of printing function (traced_object_layered_functor.cc)
Compared to the prototype version, this:
- Consolidates the implementation into a single class, since this class is only for the TVMScript printer.
- Deduces the TObjectRef when calling set_dispatch.
> [TVMScript] Printer Registry

- tests/python/ci/sample_prs/pr10786-ignore-jobs.json
- tests/python/ci/test_tvmbot.py
- tests/scripts/github_tvmbot.py
GitHub associates the automation run on PRs for user tagging and reviews
as CI jobs on that PR, and since these often get re-run, skipped, or may
fail in the background they prevent merges. This PR ignores all of these
jobs so only the ones defined in `main.yml` matter, which are the ones
that actually build / test TVM.
This is a simpler version of #11569
> [ci][tvmbot] Ignore irrelevant Actions jobs

- python/tvm/driver/build_module.py
**Why**
The newline in the pydoc breaks the layout of parameter `inputs` in API `tvm.build`,  as shown below,
**How**
Just remove the newline.
> [DOCS] fix `tvm.build` API doc layout.

- tests/python/ci/test_tvmbot.py
- tests/scripts/github_tvmbot.py
There was a level of unwrapping missing in the check for who is allowed to trigger re-runs causing it to always fail. This also uses a different actions API endpoint to re-run only failed GitHub jobs. This also fixes the text fixtures to match the GitHub API response, also tested live in https://github.com/driazati/tvm/pull/34#issuecomment-1205785109
> [ci][tvmbot] Fix authorization filtering

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
- ci/jenkins/macros.j2
- python/tvm/testing/utils.py
- tests/scripts/should_run_slow_tests.py
This makes it a normal pytest decorator so it doesn't incur test set up / tear down. This also makes the PR body the source of truth for skipping slow tests or not since it can be confusing sourcing it both from the PR and commit message.
> [testing] Remove wrapper from @slow

- tests/scripts/setup-pytest-env.sh
This wraps all tests in pytest-forked (with n=1) so that segfaults and other
process-terminations are properly reported by pytest. With this reporting on issues like #12311 should be much better (segfaults become like any other test failure)
> [ci] Box all tests in pytest-forked

- include/tvm/script/printer/doc_printer.h
- python/tvm/script/printer/doc_printer.py
- src/script/printer/base_doc_printer.cc
- src/script/printer/base_doc_printer.h
- src/script/printer/python_doc_printer.cc
- tests/python/unittest/test_tvmscript_printer_underlining.py
This adds an ability to print a "diagnostic marker" based on a given ObjectPath. For example, say we are printing a fragment of TIR like
```
for i in T.serial(10):
a[i] = 5
```
and we would like bring the user's attention to the bound of the loop:
```
for i in T.serial(10):
^^
a[i] = 5
```
In this case we would give the doc printer an object path that represents this loop bound, i.e. something like `path_to_underline=ObjectPath.root().attr("extent")`
cc @yelite @junrushao1994
> [TVMScript] Text underlining in DocPrinter based on Doc's source_paths

- python/tvm/contrib/hexagon/pytest_plugin.py
Adding flag to `pytest` to skip creating a new RPC server on the android device. 
@mehrdadh
> [Hexagon] Add skip option for RPC server initialization

- Jenkinsfile
- ci/jenkins/Deploy.groovy.j2
- ci/jenkins/macros.j2
See #11768, this PR changes the deploy workflow so that after a successful build with fallback images (see #11775), they get moved over to tlcpack automatically. Since the images are moving repositories we can't just rename the blobs in docker, so there needs to be a full `pull -> tag -> push` for each image
> [ci][docker] Tag tlcpackstaging images to tlcpack

- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- src/runtime/contrib/dnnl/dnnl_tensor_requisite.h
- tests/python/contrib/test_dnnl.py
This PR enable in-place post-op sum in dnnl json runtime for performance concern. This feature only enabled if the `rhs` of `sum` is not `input` nor `output` of the current dnnl partition. Thus the workloads with large dnnl partition will benefit most.
The correctness of this patch has been checked by the following 83 models from gluoncv:
`['resnet18_v1', 'resnet34_v1', 'resnet50_v1', 'resnet101_v1', 'resnet152_v1', 'resnet18_v2', 'resnet34_v2', 'resnet50_v2', 'resnet101_v2', 'resnet152_v2', 'resnest14', 'resnest26', 'resnest50', 'resnest101', 'resnest200', 'resnest269', 'vgg11', 'vgg13', 'vgg16', 'vgg19', 'vgg11_bn', 'vgg13_bn', 'vgg16_bn', 'vgg19_bn', 'alexnet', 'densenet121', 'densenet161', 'densenet169', 'densenet201', 'squeezenet1.0', 'squeezenet1.1', 'googlenet', 'inceptionv3', …
> [BYOC] [DNNL] enable in-place post-op sum in dnnl json runtime

- python/tvm/relay/op/strategy/adreno.py
- python/tvm/topi/adreno/__init__.py
- python/tvm/topi/adreno/conv2d_nchw.py
- python/tvm/topi/adreno/conv2d_nhwc.py
- python/tvm/topi/adreno/depthwise_conv2d_nchw.py
- python/tvm/topi/adreno/depthwise_conv2d_nhwc.py
- python/tvm/topi/adreno/injective.py
- python/tvm/topi/adreno/utils.py
- src/relay/backend/build_module.cc
- src/relay/transforms/annotate_texture_storage.cc
- src/runtime/opencl/opencl_device_api.cc
- tests/python/relay/test_conv2d_nchw_texture.py
- Added device_copy pass
- Support textures for all injective ops
- Avoid extra memory copy 
cc: @csullivan, @elvin-n
> [Adreno][OpenCL] Get rid of extra memory copy

- include/tvm/script/printer/frame.h
- python/tvm/script/printer/frame.py
- src/script/printer/frame.cc
- tests/python/unittest/test_tvmscript_printer_frame.py
This PR:
- Implement Frame for the TVMScript Unified Printer
Compared to the prototype version, this:
- Removes the dependency of VarTable (SymbolTable) from Frame
- Adds a callback array to the Frame base class so that VarTable can add callback to clean variable when Frame goes out scope
> [TVMScript] Printer Frame

- python/tvm/_ffi/__init__.py
- python/tvm/_ffi/_ctypes/object.py
- python/tvm/_ffi/_cython/object.pxi
- python/tvm/_ffi/registry.py
This PR adds a Python function to get type index from Python class object. It's useful when type index needs to be passed from Python to C++. For example, in #11912 we need to get the type index from Python class in order to register a printing function in Python.
> Add function to get type index from Python class

- src/target/tag.cc
>The C5 and C5d 12xlarge, 24xlarge, and metal instances feature custom 2nd generation [Intel](https://aws.amazon.com/intel/) Xeon Scalable Processors (Cascade Lake) with a sustained all-core turbo frequency of 3.6GHz and maximum single core turbo frequency of 3.9GHz. The other C5 and C5d instance sizes will either launch on the 2nd generation Intel Xeon Scalable Processor or the 1st generation Intel Xeon Platinum 8000 series (Skylake-SP) processor with a sustained all core Turbo frequency of up to 3.4GHz, and single core turbo up to 3.5 GHz using Intel Turbo Boost Technology.
>The C5 and C5d 12xlarge, 24xlarge, and metal instance sizes enable Vector Neural Network Instructions (AVX-512 VNNI*) which will help speed up typical machine learning operations like convolution, and automatically …
> [Target] Fix C5 Target Tag to Include CascadeLake Archs

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to fix the impl of `pad_common` for float pad_value found in models like `pytorch_unet` and `timm_efficientdet`, as well as add a couple new tests for the `torch.nn.functional.pad`.
> [PyTorch] Fix pad_common for float pad_value

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to fix the `all_any_common` op in the pytorch frontend for the use case that no arguments are present for those two ops in the models like `timm_vision_transformer`. 
cc: @masahi
> [PyTorch] Fix all_any_common with no default input

- .github/ISSUE_TEMPLATE/ci-problem.md
These issues are reported as part of the CI monitoring rotation and
usually reflect something contained and actionable. As such we should
track and monitor these issues and make sure that a proper mitigation or
fix is merged soon. This label helps us do this since we can easily
filter by untriaged issues and make sure each one has an assignee.
> Add needs-triage label to CI Problem template

- python/tvm/relay/backend/contrib/ethosu/tir/compiler.py
- python/tvm/relay/backend/contrib/ethosu/tir/passes.py
- src/tir/contrib/ethosu/passes.cc
- tests/python/contrib/test_ethosu/test_copy_compute_reordering.py
If the cascader is enabled and the ops in TIR have the cycle
count annotation, enabling the reorder_by_cycles option will
reorder to copies and computes based on a cycle count.
If reorder_by_cycles is enabled, max_copy_movements is ignored.
This pass is currently not part of the TIR pipeline since it
assumes that weights and bias of a compute op are merged into
one constant (which is WIP).
> [microNPU] Reorder copies and computes based on the cycle count

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
- ci/jenkins/macros.j2
- tests/scripts/setup-pytest-env.sh
This decreases the test times for most of the tests except a few that did not run under pytest-xdist with 2 worker nodes. This also doesn't decrease overall runtime since CI is still bottlenecked on other jobs. However, this could lead to savings in compute which makes CI more sustainable so this is still worthwhile, though we should revert this if we start seeing "weird" errors like OOMs more often.
> [ci] Default to n=2 for test parallelism

- include/tvm/runtime/profiling.h
- python/tvm/contrib/debugger/debug_executor.py
- python/tvm/contrib/graph_executor.py
- python/tvm/runtime/module.py
- python/tvm/runtime/vm.py
- src/runtime/crt/common/crt_runtime_api.c
- src/runtime/graph_executor/debug/graph_executor_debug.cc
- src/runtime/profiling.cc
- src/runtime/rpc/rpc_module.cc
- web/emcc/tvmjs_support.cc
- web/src/runtime.ts
For some operations such as `__nop` or `__copy` the measured inference
time is equal to 0. In this case we are in infinite loop and we won't
exit from it. Added new parameter `max_repeat_num` which specify the
maximum number of repeats then the inference time is equal to 0. When
we exceed this value then we will exit from a loop.
cc: @valmat07, @Icemist, @masahi
> [Profiler] Fix graph_executor_debug hang

- python/tvm/contrib/debugger/debug_executor.py
Sometimes you may want to disable time sorting if you want to compare some outputs with each other.
CC @echuraev
> Add sort_by_time flag to debug_executor.run method

- src/driver/driver_api.cc
- src/tir/transforms/storage_rewrite.cc
Vtcm allocations were being moved inside loops even if they were originally allocated outside of the loops. Normally PlanAndUpdateBufferAllocationLocation moves allocations as close to use as possible and then StorageRewrite moves them back out as far as possible. However, with Vtcm allocation, PlanAndUpdateBufferAllocationLocation would move the Vtcm allocation close to the compute, then LowerVtcm would convert the allocation to a LetStmt. StorageRewrite would not move this LetStmt as it only handles allocations. Moving LowerVtcmAlloc to after StorageRewrite ensures that the vtcm allocations are in their final spot before converting them to a LetStmt.
@csullivan @Lunderberg
> [LowerVTCMAlloc] Move LowerVtcmAlloc to after StorageRewrite

- src/runtime/threading_backend.cc
**Background**
Creating more threads than there are HVX units causes performance degradation when threads are unable to reserve an HVX unit and end up running vector instructions on the Scalar cores. Capping the max number of threads to be the number of available HVX units on the device prevents this from occurring and results in better performance on hexagon. 
**Testing**
Ran tests in simulator mode as well on a hexagon HDK to ensure that the expected result of …
> Cap hexagon max con to number of HVX units

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
- ci/jenkins/macros.j2
- tests/scripts/setup-pytest-env.sh
This reverts commit 369e8b283083a3440c59431a9438ca17afb73e4e.
There are certain tests that need to be serialized first (as in #8576) before this can merge or else failures like https://ci.tlcpack.ai/job/tvm/job/main/4040/display/redirect will happen based on which tests happen to be run together or not
> [skip ci] Revert "[ci] Default to n=2 for test parallelism (#12376)"

- include/tvm/tir/stmt.h
- include/tvm/tir/transform.h
- python/tvm/tir/transform/transform.py
- src/driver/driver_api.cc
- src/tir/transforms/manifest_shared_memory_local_stage.cc
- tests/python/frontend/pytorch/test_forward.py
- tests/python/unittest/test_tir_transform_manifest_shared_memory_local_stage.py
Added a pass to insert local (cache) stage for the shared memory. It's similar to cache read but bypasses the limitation of int set analysis for compacting buffer region by inferring the buffer shape from the loop extents.
cc @junrushao1994 @spectrometerHBH @masahi @jinhongyii
> [TIR] Add pass ManifestSharedMemoryLocalStage

- include/tvm/script/printer/var_table.h
- python/tvm/script/printer/var_table.py
- src/script/printer/var_table.cc
- tests/cpp/tvmscript_printer_var_table_test.cc
- tests/python/unittest/test_tvmscript_printer_var_table.py
This PR:
- Adds VarTable for the new TVMScript Printer
Compared to the prototype version, this:
- Removes unnecessary public methods.
- GetObjectName
- GetUniqueName
- Add Frame parameter for `Define` methods. VarTable will add callback to Frame to remove variable when Frame exits.
- Changes DocFactory from `ExprDoc(ObjectPath)` to `ExprDoc()` to simplify var definition.
> [TVMScript] Printer VarTable

- python/tvm/topi/image/resize.py
- tests/python/topi/python/test_topi_image.py
- tests/python/topi/python/test_topi_upsampling.py
This PR is aim to change floating point multiplication of resize operator to integer division when `method` is nearest_neighbor and `coordinate_transformation_mode` is asymmetric.
**Why this change?**  
When using `create_prim_func` to convert topi.upsampling into primfunc, tir analyzer cannot parse complex floating point operations in tir block body. In the following case, the dimensions of read buffer are inferred as 0 : 128. We expect to be `tir.reads([x[i0_1, i1_1, i2_1/scale_h, i3_1/scale_w]])`in line 18，so it can perform compute_at schedule on this prim_func.
```python
scale_h = 2
scale_w = 2
x = te.placeholder([1, 128, 128, 128], "int8", "x")
y = topi.nn.upsampling(x, scale_h , scale_w)
func = te.create_prim_func([x, y])
print(func)
```
```Python
primfn(var_x: handle, var_resize: …
```
> [TOPI][OP]change float multiplication of resize op to integer division

- docker/Dockerfile.ci_arm
This patch enables ONNX and dependencies installation on ci_arm as
a way to enable ONNX and Torch testing.
cc @Mousius @NicolaLancellotti @areusch @driazati @gigiblender
> [CI][AArch64] Enable ONNX installation in ci_arm image

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
- tests/python/ci/test_ci.py
This PR updates all images to the most recent nightly build: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/419/pipeline/63. It also adds ci_riscv which allows us to start testing RISC-V operators on simulators such as SPIKE.
cc @alter-xp @PhilippvK @driazati
> Add ci_riscv image, update all to 20220810-060142-fae79bbc3

- apps/microtvm/zephyr/template_project/CMakeLists.txt.template
- apps/microtvm/zephyr/template_project/fvp-hack/FVP_Corstone_SSE-300_Ethos-U55
- apps/microtvm/zephyr/template_project/microtvm_api_server.py
- apps/microtvm/zephyr/template_project/src/host_driven/fvp/semihost.c
- apps/microtvm/zephyr/template_project/src/host_driven/fvp/semihost.h
- apps/microtvm/zephyr/template_project/src/host_driven/main.c
- cmake/modules/Zephyr.cmake
- tests/lint/check_file_type.py
- tests/micro/zephyr/conftest.py
- tests/micro/zephyr/test_zephyr.py
- tests/micro/zephyr/test_zephyr_aot_exec.py
- tests/micro/zephyr/test_zephyr_aot_exec_standalone.py
- tests/scripts/task_python_microtvm.sh
This PR adds corstone300 FVP to the platforms supported by the zephyr. We use the Iris debugger to communicate with the emulator via semihosting, due to the FVP serial port's faulty behavior (It might drop a byte in messages longer than 1 byte).
This PR also changes the generated micro-projects build system from make to ninja.
> [microTVM] Zephyr: Add support for FVP

- src/meta_schedule/schedule_rule/multi_level_tiling.cc
- src/meta_schedule/schedule_rule/multi_level_tiling.h
- src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc
- src/meta_schedule/schedule_rule/multi_level_tiling_with_intrin.cc
cc @AndrewZhaoLuo @junrushao1994 @zxybazh
> [MetaSchedule] Add logging of usage of tensor intrinsics

- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/codegen_ethosn.h
- src/relay/backend/contrib/ethosn/ethosn_api.cc
- src/relay/backend/contrib/ethosn/ethosn_api.h
- tests/python/contrib/test_ethosn/test_requantize.py
This commit adds support for the requantize operator for the Arm(R) Ethos(TM)-N NPU.
cc @lhutton1
> [ETHOSN] Add support for Requantize

- src/tir/transforms/storage_rewrite.cc
- tests/python/unittest/test_tir_transform_storage_rewrite.py
After PR #12349 inference of some Adreno networks was broken. In the
output it was the following error:
```
TVMError: Not all Vars are passed in api_args: 'compute' is not bound
to any variables
```
cc: @tkonolige, @Lunderberg  
cc @driazati
> [HotFix] Op is not bound to any variables

- src/arith/const_int_bound.cc
- tests/python/unittest/test_arith_const_int_bound.py
Previously, only `<` and `<=` bounds were parsed, as these are the canonical form produced by the `RewriteSimplifier`.  However, the constraint may also be supplied by the user through the Python API, and may not be canonicalized prior to parsing.
> [Arith] Parse > and >= bounds in ConstIntBoundAnalyzer

- include/tvm/script/printer/ir_docsifier.h
- include/tvm/script/printer/traced_object_functor.h
- include/tvm/support/with.h
- python/tvm/script/printer/ir_docsifier.py
- src/script/printer/ir_docsifier.cc
- src/script/printer/traced_object_functor.cc
- tests/cpp/tvmscript_printer_irdocsifier_test.cc
- tests/cpp/tvmscript_printer_traced_object_functor_test.cc
- tests/python/unittest/test_tvmscript_printer_irdocsifier.py
This PR:
- Adds IRDocsifier
This PR is in draft state because it's branched off from a pending PR #12336
> [TVMScript] Printer IRDocsifier

- include/tvm/support/span.h
`std::iterator` is deprecated in C++17. It only defined some member types, and the new recommended solution is to define these members directly.
> Remove uses of std::iterator, NFC

- docs/contribute/code_guide.rst
These were missing the final step to use the uploaded resources.
> [docs] Add instructions for uploading CI resources to S3

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
According to the pytorch doc [torch.nn.MaxPool3d](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool3d.html?highlight=pool3d#torch.nn.MaxPool3d). The shape of input can be `(N,C,D,H,W) or (C,D,H,W)`. While the MaxPool3DAttrs  thinks the dimension should be 5. When importing a model contains MaxPool3d with shape (C,D,H,W)`,
https://github.com/apache/tvm/blob/bcc7cde95c1e84b85f18c07110489350865b8cfe/include/tvm/relay/attrs/nn.h#L985-L996
which could leads to out of bound error `Check failed: (0 <= i && i < p->size_) is false: IndexError: indexing 4 on an array of size 4` when `ii == 4 and dshape == 4`.
https://github.com/apache/tvm/blob/bcc7cde95c1e84b85f18c07110489350865b8cfe/src/relay/op/nn/pooling.cc#L1211-L1216
Therefore, I simply add an expand_dims op on the frontend to avoid …
> [Frontend][Pytorch] Add axis N when maxpool3d layout is (C,D,H,W)

- src/target/source/codegen_cuda.cc
- src/tir/analysis/verify_gpu_code.cc
- tests/python/unittest/test_tir_analysis_verify_gpu_code.py
There are some cases invalid `make_int8` is generated by CUDA codegen. There are `make_int8` API in CUDA. Updated `VerifyGPUCode` to check such case and also throw error when vector size is too large during codegen.
cc @junrushao1994 @masahi @spectrometerHBH @Kathryn-cat
> [TIR] Disallow vectorization with strides in VerifyGPUCode

- src/runtime/crt/memory/page_allocator.c
Fix the memset during creation of memory manager. It should clear the whole memory pool, otherwise the next invocation will create a manager with some attributes using old values.
I found this issue when trying to call `tvm_runtime_create` the second time led to error. (my codes are similar to `apps/bundle_deploy/bundle_static.c`). Internal checking would fail due to manager attributes being only partially cleared.
cc @areusch
> [CRT runtime] Fix memset of memory pool in PageMemoryManagerCreate

- Jenkinsfile
- ci/jenkins/Build.groovy.j2
- ci/jenkins/Test.groovy.j2
- ci/jenkins/generate.py
- tests/scripts/ci.py
- tests/scripts/task_config_build_riscv.sh
- tests/scripts/task_riscv_microtvm.sh
This PR adds build and test scripts for RISC-V microTVM builds. It does not add support to directly run code on RISC-V machines; only via SPIKE.
cc @alter-xp @PhilippvK #11688
> Add RISC-V build/test pipeline to Jenkins.

- python/tvm/target/target.py
- tests/python/contrib/test_hexagon/topi/test_tanh_slice.py
> [HEXAGON] Auto-vectorization (fp16) for v68

- src/tir/transforms/bf16_legalize.cc
- tests/python/relay/test_cpp_build_module.py
So far, the `softmax` in the following test
``` python
import tvm
data = relay.var("data", shape=(1, 1000), dtype="bfloat16")
expr = relay.nn.softmax(data)
mod = tvm.IRModule.from_expr(expr)
with tvm.transform.PassContext(opt_level=3):
relay.build(mod, target="llvm")
```
will be lowered to
``` swift
@tvmgen_default_fused_nn_softmax = primfn(placeholder_1: handle, T_softmax_norm_1: handle) -> ()
attr = {"from_legacy_te_schedule": True, "global_symbol": "tvmgen_default_fused_nn_softmax", "tir.noalias": True}
buffers = {placeholder: Buffer(placeholder_2: Pointer(uint16), uint16, [1000], []),
T_softmax_norm: Buffer(T_softmax_norm_2: Pointer(uint16), uint16, [1000], [])}
buffer_map = {placeholder_1: placeholder, T_softmax_norm_1: T_softmax_norm}
preflattened_buffer_map = …
```
> [TIR] [bfloat16] add bfloat16 promotion for CallNode

- src/relay/backend/contrib/cmsisnn/buffer_size.cc
- src/relay/backend/contrib/cmsisnn/buffer_size.h
- src/relay/backend/contrib/cmsisnn/compiler_attrs.cc
- src/relay/backend/contrib/cmsisnn/compiler_attrs.h
- src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
- src/relay/backend/contrib/cmsisnn/target.cc
- tests/cpp/relay/backend/contrib/cmsisnn/buffer_size_test.cc
- tests/cpp/relay/backend/contrib/cmsisnn/compiler_attrs_test.cc
- tests/python/unittest/test_target_parser_mprofile.py
Previously `CMSISNNFlags` was derived using logic specific to the external code generator, this converts the external code generator options into a `Target`.
cc @areusch
> [CMSIS-NN] Re-use CPU Target Parser

- python/tvm/target/target.py
- src/target/parsers/mprofile.cc
- src/target/target.cc
- tests/cpp/target/parsers/mprofile_test.cc
- tests/cpp/target_test.cc
This allows target parsers to provide their own target keys. Without this change, the default keys would always be appended, which may or may not be desirable.
> [Target] Only append default keys if target doesn't have any yet

- tests/scripts/github_tvmbot.py
To figure out a user's association with the repo this code before
searched the associations in the repo filtered by the relevant username.
GitHub doesn't return the exact match only though, so we have to instead
collect many results and search through all of them to avoid issues like in
https://github.com/apache/tvm/pull/12397#issuecomment-1219214243
> [ci][tvmbot] Search more users when checking usernames

- tests/micro/common/test_autotune.py
Currently, `tests/micro/common/test_autotune.py` passes on `main` when run on `qemu` or other microTVM devices (such as the Arduino Due) without the ARM DSP extension. However, when run on Cortex M4 or M7 devices with this extension, the following error is seen:
```
logs = list(map(json.loads, str_logs))
>       assert len(logs) == 1 * TUNING_RUNS_PER_OPERATOR  # One operator
E       AssertionError: assert 3 == (1 * 2)
E        +  where 3 = len([{'config': {'code_hash': None, 'entity': [['tile_co', 'sp', [-1, 8]], ['tile_oh', 'sp', [-1, 5]], ['tile_ow', 'sp', [..., 'int32'], {}], 'result': [[0.001604125], 0, 14.074790239334106, 1660810737.063845], 'tvm_version': '0.10.dev0', ...}])
```
This is because there are **two** schedules for Arm with DSP, but one of them does not have any tuning …
> [microTVM] Fix test_autotune to support schedules with no tuning space

- python/tvm/topi/arm_cpu/dense.py
- python/tvm/topi/arm_cpu/mprofile/dsp/dense.py
- tests/python/relay/strategy/arm_cpu/test_dense_dsp.py
This PR adds loop split to dense_dsp schedule. It has been tested on Anomaly detection model which significantly improves the performance.
Also modified the dense_dsp test to have bias operator as well.
> [microTVM] Add config space to dense_dsp schedule

- python/tvm/topi/x86/conv3d.py
- tests/python/frontend/onnx/test_forward.py
Hi, 
When I run group_conv3d test. I set the `group` equal `in_channel`. Then the op result is 100% error. 
The error is in 'conv3d.py.':
` in_channel // groups // ic_bn`.   the result is 0. Because it is the shape of kernel. Can`t equal 0. So I set it equal 1 if the result is 0.
Then my test successed.
cc @blackkker
> [onnx][topi]fix group_conv3d caculate error

- python/tvm/micro/testing/pytest_plugin.py
Add default value for `--test-build-only` pytest fixture.
cc @areusch
> [micro] Fix pytest fixture

- src/relay/op/nn/nn.cc
- tests/python/relay/test_pass_convert_op_layout.py
The `FInferCorrectLayout` was set to `ElemwiseArbitraryLayout` which is for layout agnostic operators. While L2norm is a lightly-layout sensitive operator with `attrs-axis`. Refered to [Convert Layout Pass](https://tvm.apache.org/docs/arch/convert_layout.html?highlight=pass).
https://github.com/apache/tvm/blob/72b0f5ee34be6acfadf7afc61264eef42b78c789/src/relay/op/nn/nn.cc#L672
When running model, I met a situation:
`%0 = layout_transform(%x, src_layout="NHWC", dst_layout="NCHW") /* ty=Tensor[(1, 64, 56, 56), float32] */;`
`%1 = layout_transform(%weight, src_layout="HWIO", dst_layout="OIHW") /* ty=Tensor[(64, 64, 3, 3), float32] */;`
`%2 = nn.conv2d(%0, %1, padding=[1, 1, 1, 1], channels=64, kernel_size=[3, 3]) /* ty=Tensor[(1, 64, 56, 56), float32] */;`
`%3 = nn.l2_normalize(%2, …
> [Relay][Layout] Add FInferCorrectLayout for L2 norm layout transform.

- src/tir/transforms/manifest_shared_memory_local_stage.cc
Just an issue of temp reference, may crash on certain environments. The actual constructor argument passed in is `std::vector<Stmt>`.
> [TIR] Fix temp obj reference typo in manifest_shared_memory_local_stage

- python/tvm/meta_schedule/testing/space_generation.py
- python/tvm/script/highlight.py
- python/tvm/tir/schedule/trace.py
- src/tir/schedule/trace.cc
- tests/python/unittest/test_meta_schedule_post_order_apply.py
- tests/python/unittest/test_tir_schedule_trace.py
Following https://github.com/apache/tvm/pull/12197, this PR introduces `Schedule.show()` which convenience the user experience in the following two aspects:
- Python syntax highlighting
- Outputs a schedule function instead of standalone instructions so that it's easier to follow.
To demonstrate this change:
- Before `Schedule.show()` is introduced:
- After this change:
cc @junrushao @junrushao1994
> [TIR][Schedule][UX] Beautify TIR Trace Printing

- include/tvm/meta_schedule/space_generator.h
- python/tvm/meta_schedule/space_generator/__init__.py
- python/tvm/meta_schedule/space_generator/schedule_fn.py
- python/tvm/meta_schedule/space_generator/space_generator.py
- python/tvm/meta_schedule/tune_context.py
- src/meta_schedule/space_generator/post_order_apply.cc
- src/meta_schedule/space_generator/schedule_fn.cc
This PR implements the existing python-based ScheduleFn in C++ for
broader usecases, for example, multi-threaded search with customized
schedule function.
> [MetaSchedule] Implement ScheduleFn as a C++ class

- include/tvm/meta_schedule/database.h
- python/tvm/meta_schedule/database/memory_database.py
- src/meta_schedule/database/memory_database.cc
This PR migrates the existing MemoryDatabase, which is implemented in
python at the moment, to C++. The original intent of having an in-memory
database that does not persist on disk is merely for testing, but as
times go on, we found it useful in production workflow, and thus decided
to migrate it C++ for potentially better performance.
> [MetaSchedule] Migrate MemoryDatabase to C++

- python/tvm/topi/x86/conv3d.py
- tests/python/frontend/onnx/test_forward.py
Related PR: #12500 
hi, 
I am sorry i made a mistake about group_conv3d.
There is three case about caculate  `in_channel // groups // ic_bn`.
1. if `in_channel // groups // ic_bn`  == 0, It means that we only need to tile to `1`
2. if `out = in_channel // groups // ic_bn` ！= 0, but  the `out * ic_bn * group < in_channel` . It means that we  need to tile to `out +1`
3.   if `out = in_channel // groups // ic_bn`  ！= 0, but  the `out * ic_bn * group == in_channel` . It means that we  need to tile to `out `
In the last PR, I didn`t consider the second case.  So this PR I fix it.
CC: @masahi
> [topi]fix group conv3d pack kernel shape error

- include/tvm/meta_schedule/apply_history_best.h
- include/tvm/meta_schedule/extracted_task.h
- python/tvm/meta_schedule/apply_history_best.py
- python/tvm/meta_schedule/relay_integration.py
- python/tvm/meta_schedule/testing/utils.py
- src/meta_schedule/extracted_task.cc
- src/printer/tvmscript_printer.cc
- src/relay/backend/task_extraction.cc
- src/relay/backend/te_compiler_cache.cc
- src/relay/backend/te_compiler_cache.h
- src/te/operation/create_primfunc.cc
- src/te/operation/create_primfunc.h
- src/tir/analysis/estimate_flops.cc
- src/tir/schedule/transform.cc
- src/tir/transforms/bind_params.cc
- src/tir/transforms/inject_software_pipeline.cc
- src/tir/transforms/ir_utils.h
- src/tir/transforms/plan_update_buffer_allocation_location.cc
- tests/python/unittest/test_link_params.py
TIR-level constants, represented by `AllocateConst` nodes, were introduced in https://github.com/apache/tvm/pull/8509. They are generated if `link-params = 1`. 
At Relay level, `link_params = True` makes constant tensors kept bound to the function body, rather than lifting them to function parameters during `FuseOps`. So we end up with the following Relay prim func, for example:
```
fn (%p0: Tensor[(128, 768), uint8]) -> Tensor[(128, 768), int32] {
nn.contrib_dense_pack(%p0, meta[relay.Constant][0], units=None, out_dtype="int32", weight_layout="NC32n4c")
} 
```
(if `link-params = False`, which is the default, the weight also becomes the parameter of the function).
I found that TensorIR related components below do not support such TIR-level constants currently:
* `CreatePrimFunc`: It …
> [TIR] Support AllocateConst nodes in TensorIR scheduling flow

- tests/python/driver/tvmc/test_frontends.py
In TVM ONNX frontend, constants are folded by default, which makes `test_load_model__onnx` to fail because it is looking for "params" that were already converted into constants.
This patch fixes the test to disable constant folding so that we can assert that "params" in the model are present as expected.
cc @ashutosh-arm @driazati @areusch @Mousius @NicolaLancellotti
> [ONNX] Fix test to disable default ONNX frontend constant folding

- tests/python/unittest/test_meta_schedule_integration.py
`test_meta_schedule_integration_extract_from_bert_base` depends on the `transformers` package, which is not currently installed in our Docker images.
When running this test currently, it fails with an ImportError. This patch makes this dependency explicit and will make the test to be skipped when the dependency is not installed.
`test_meta_schedule_integration_extract_from_bert_base` is part of the integration tests, which is currently only running on AArch64 and CPU image (both not at the moment with torch installed in the live CI system), so this is another issue to be understood/fixed.
cc @Mousius @NicolaLancellotti @areusch @ashutosh-arm @driazati @gigiblender
> [CI] Set test dependency on "transformers" package with pytest.importorskip

- include/tvm/tir/schedule/schedule.h
- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/cache_read_write.cc
- src/tir/schedule/trace.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- tests/python/unittest/test_tir_schedule_cache_read_write.py
Currently in tir, using `cache_read` will rewrite all consumer blocks of the specified buffer in the current scope. However, there may be cases where we want to apply that transformation only to a subset of consumer blocks. In the te version of cache_read, this is explicitly specified through a list of `consumer_blocks`. This PR extends the tir version of `cache_read` with an optional `consumer_blocks` argument. When provided, only blocks listed in `consumer_blocks` will be rewritten. If not provided, the current behavior of `cache_read` remains the same.
> [TIR][Schedule] Support for specific consumer block targeting in cache_read

- tests/python/relay/dyn/test_dynamic_op_level5.py
hi, In the main function,  `resize2d` case name is wrong
Fix  resize2d  case name, replace `resize` to `resize2d`,
cc  @masahi @gaurav1086
> [Relay] Fix bug in resize2d unittest func name

- python/tvm/testing/utils.py
- tests/python/contrib/test_ethosu/test_codegen.py
This adds a testing utility so we can mark parameter combinations as
xfail without having to manually match each parameter from the name into
the code. The param strings here come directly from CI logs as in
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-12389/5/pipeline
Mitigates but doesn't fix #12511 
> [ci] xfail failing ethosu codegen tests

- tests/scripts/request_hook/request_hook.py
This PR intends to move the alexnet and googlenet caffe models from the old link to s3, therefore getting rid of the flakiness in `caffe/test_forward.py` introduced by external url timeouts. 
Fixes #12465
cc: @driazati @areusch 
cc @Mousius @gigiblender
> [CI] Add alexnet and googlenet caffe model to request hook

- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
- src/target/target_kind.cc
- tests/cpp/target_test.cc
- tests/python/unittest/test_target_target.py
Add `LLVMTargetInfo` class that can be used to query the LLVM configuration without forcing an `LLVMTarget` to be created.
There is no programmatic way to obtain the actual type of an LLVM option. The type is necessary to obtain the value of the option, hence it must be provided as a part of the option string.
See `src/target/llvm/target_kind.cc` for more information about the syntax.
> [LLVM] Add "cl-opt" attribute to target_kind "llvm"

- apps/uma/_template/patterns.py
- python/tvm/relay/backend/contrib/uma/api/lower.py
- python/tvm/testing/aot.py
- tests/python/contrib/test_uma/test_uma_pipeline.py
- tests/python/contrib/test_uma/test_uma_vanilla_accelerator.py
There was a flaw in uma_lower (see issue #12410) that lead in some case to a different  argument ordering of the  cached_func and the Relay function. This results in an incorrect  lowering of the primfunc and eventually a wrong result of a run-time error, in some cases.
This commit adds code to correct the described misbehavior and a unit test case to check this end-to-end functionality with a TFLITE model.
> [BugFix][UMA] Fix order issue in uma_lower 

- include/tvm/tir/analysis.h
- python/tvm/tir/analysis/analysis.py
- src/arith/int_set.cc
- src/ir/transform.cc
- src/tir/analysis/oob_checker.cc
- src/tir/ir/transform.cc
- src/tir/schedule/error.cc
- tests/python/unittest/test_arith_intset.py
- tests/python/unittest/test_tir_analysis_oob.py
This is a conservative static analysis that checks to see if any out of bounds array access occurs. It is not enabled by default.
@Lunderberg @AndrewZhaoLuo @jwfromm 
cc @gigiblender
> [TIR] Add pass to check for out of bounds memory access

- python/tvm/meta_schedule/cost_model/mlp_model.py
Removes [mutable default arguments](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) in `python/tvm/meta_schedule/cost_model/mlp_model.py`.
> Remove mutable default arguments in mlp_model

- python/tvm/micro/testing/__init__.py
- python/tvm/micro/testing/evaluation.py
- tests/micro/common/test_autotune.py
Currently, `evaluate_model_accuracy` addresses only a very specific use case - when one only cares about the average accuracy and runtime of a host-driven AOT model. This prevents users from implementing workarounds to bugs like #12538, and means we redundantly return both model predictions and the accuracy.
This PR changes `evaluate_model_accuracy` in `python/tvm/micro/testing/evaluation.py` into `predict_labels_aot`. This function has the type signature:
```python
def predict_labels_aot(session, aot_executor, input_data, runs_per_sample=1):
```
Unlike `evaluate_model_accuracy`, `predict_labels_aot` does not take as input the true labels of the data. Instead, it returns an iterator of `(prediction, runtime)` tuples, and lets users do what they want with these.
cc @alanmacd @gromero …
> [microTVM] Rework evaluate_model_accuracy into a more generic helper function

- python/tvm/micro/testing/pytest_plugin.py
- python/tvm/micro/testing/utils.py
- tests/micro/arduino/test_arduino_workflow.py
- tests/micro/common/conftest.py
#12207 went a long way to improving microTVM code reuse, but introduced an unintentional? change. Previously, the full `pytest` names of microTVM tests included the value of `board`, prepended to any paremeterization. For example, `test_rpc_large_array` would have the name:
```
tests.micro.zephyr.test_zephyr.test_rpc_large_array[nucleo_f746zg-(4*1024)]
```
This behavior was useful, as it meant that exported Junit XML files would correctly record which board the test was run on. However, after #12207 the names of tests stopped including this information:
```
tests.micro.zephyr.test_zephyr.test_rpc_large_array[(4*1024)]
```
This prevented Junit from differentiating between the tests when they were run on different boards, and instead just overwrote results on previous boards. Additionally, …
> [microTVM] Replace static fixtures with parameterization

- docs/contribute/ci.rst
This PR documents the steps to introducing a new CI docker image, which we've been doing a lot lately.
@driazati
> Add instructions on how to add a new CI docker image

- python/tvm/relay/frontend/keras.py
- tests/python/frontend/tflite/test_forward.py
This pr fixes the tests that will be broken when we will update TFLite to the 2.9 version.
We will update TensorFlow and TFLite versions to 2.9 so that we can benefit from improvements in packaging to support multiple platforms and Operating Systems.
> [TFLite] Fix tests so that TensorFlow 2.9 is supported

- python/tvm/relay/op/contrib/cmsisnn.py
- src/relay/backend/contrib/cmsisnn/fuse_pads.cc
- tests/python/contrib/test_cmsisnn/test_conv2d.py
- tests/python/contrib/test_cmsisnn/test_fuse_pads.py
- tests/python/contrib/test_cmsisnn/utils.py
Pass that fuses nn.pad and qnn.conv2d for CMSIS-NN target.
cc @Mousius @areusch @grant-arm @lhutton1 @manupa-arm
> [CMSIS-NN] Pad fusion with QNN Conv2D

- tests/python/driver/tvmc/test_autotuner.py
- tests/python/driver/tvmc/test_frontends.py
- tests/python/driver/tvmc/test_model.py
Some integration tests are failing when running in CI machines that
have torch installed (validated only in AARch64 for now), with an
error message related to libgomp, similar to the one below:
OSError: /.../dist-packages/torch/lib/libgomp-d22c30c5.so.1: cannot
allocate memory in static TLS block
As part of enabling the integration tests in AArch64, I'm marking this
tests as skipped, so that tests can start executing and don't regress
while we take time to investigate these specific failures.
cc @Mousius @NicolaLancellotti @areusch @driazati @gigiblender @lhutton1
> [CI][AArch64] Skip libgomp failures in integration tests

- python/tvm/autotvm/record.py
- python/tvm/autotvm/task/dispatcher.py
- tests/micro/common/test_autotune.py
- tests/python/unittest/test_autotvm_record.py
Currently, AutoTVM's `ApplyHistoryBest` class does not support loading tuning logs from memory. This is a pet peeve of mine, as it requires you to work with a `tempfile` whenever writing autotuning tests. This is also just strange, as the rest of AutoTVM has support for text buffers (e.g. `tvm.autotvm.callback.log_to_file` supports passing in a text buffer, letting us write to but not read from them).
Additionally, `ApplyHistoryBest` handles input arguments very unintuitively. Before this PR, it allowed users to pass string filepaths, a list of string filepaths, or an `Iterable` (such as a list) of input and result tuples. However, it did not support taking in `StringIO` objects as mentioned above, nor `pathlib.Path` objects, nor combinations of a filepath and an `Iterable` of tuples.
In …
> [AutoTVM] Add support for text buffers to ApplyHistoryBest

- docker/Dockerfile.ci_cpu
While the dependencies for microNPU and CMSIS-NN moved into ci_cortexm,
Vela is still installed in ci_cpu. As a result, we have some of the microNPU tests outside of
test_ethosu folder failing since they use presence of Vela to decide whether to skip the
test.
This change will
* remove Vela from ci_cpu
* remove unnecessary PATH update
> [CI] Remove Vela from ci_cpu

- apps/microtvm/zephyr/template_project/boards.json
- apps/microtvm/zephyr/template_project/microtvm_api_server.py
- apps/microtvm/zephyr/template_project/src/host_driven/main.c
This PR adds heap-size to the microTVM project options. So far the heap size has been fixed (216KB) for all boards. Exposing it as a project option allows the user to modify the value based on each specific board's available memory.
A "recommended_heap_size" is added for the "stm32l4r5zi" in "boards.json". The recommended value is tested on 4 boards (10 times on each board) and the result is compared against the default value of 216KB. The average failure rate has remained almost constant for all boards.
cc @gromero , @mehrdadh , @alanmacd , @areusch
> [MicroTVM] add heap-size to project options

- src/relay/backend/annotate_used_memory.cc
- src/relay/transforms/annotate_texture_storage.cc
- src/relay/transforms/compiler_function_utils.cc
This silences warning
```
warning: 'foo' hides overloaded virtual functions [-Woverloaded-virtual]
```
typically caused by overriding only some overloads of `VisitExpr_` from a set defined in the base class.
> Add using directives for otherwise hidden virtual functions, NFC

- python/tvm/contrib/ethosu/cascader/scheduler.py
`compute_cycles` can be the size of an int64 value, however it seems that when that value is attached to the IR as a pragma from Python, it is interpreted as an `int`, rather than `int64_t`. This commit adds an explicit cast to ensure the value is interpreted correctly.
The reason these values started appearing very large and randomly is still yet to be solved, although the hope is that this fix will unblock CI.
The hope is that this will fix: #12511
cc @Mousius @ekalda @leandron @shingjan @cconvey
> [microNPU] Force compute_cycles_hint to be interpreted as an int64 value

- tests/scripts/task_python_microtvm.sh
Introducing -n auto for CMSIS-NN tests to
run them parallel with pytest-xdist. This
is needed because of additional parameterization
done over cpu variants.
cc @Mousius @areusch @driazati @gigiblender @leandron @lhutton1
> [CI][CMSIS-NN] Running tests parallel using pytest-xdist

- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/codegen_ethosn.h
- src/relay/backend/contrib/ethosn/ethosn_api.cc
- src/relay/backend/contrib/ethosn/ethosn_api.h
- tests/python/contrib/test_ethosn/test_resize.py
This commit adds support for the resize operator for the Arm(R) Ethos(TM)-N NPU.
cc @lhutton1
> [ETHOSN] Add support for Resize

- include/tvm/arith/int_set.h
- python/tvm/arith/__init__.py
- python/tvm/arith/int_set.py
- src/arith/int_set.cc
- src/tir/schedule/primitive/compute_at.cc
- src/tir/schedule/state.cc
- src/tir/schedule/utils.h
- src/tir/transforms/compact_buffer_region.cc
- tests/python/unittest/test_arith_intset.py
- tests/python/unittest/test_tir_transform_compact_buffer_region.py
Hi, this change wants to add some minor updation to region estimator used by buffer compaction:
- Add and clearify among `EstimateRegionStrictBound`, `EstimateRegionLowerBound` and `EstimateRegionUpperBound`
Originally we have `EstimateRegionLowerBound`, actually it implements strict bound estimation IMO. Now add `upper` and `strict` version for where we actually want them.
- When estimating upperbounds (eg. in buffer compaction), try estimate each dimension independently when they are dependent accesses where `EstimateRegionLowerBound` is expected to fail. 
Eg, `A[i, i], 3 < i < 16`  fails via `EstimateRegionLowerBound` who check indices be independent. But we can still try best to invoke strict bound analysis on each dimension individually.
- If range->extent == 1 for `EvalSet(range, …
> [TIR][CompactBufferAllocation] Improve upperbound estimation of buffer compaction

- tests/python/contrib/test_onnx.py
`python.contrib.test_onnx.test_resize` is failing due to a numerical
accuracy issue, reported in #12567. This patch marks that test as
an xfail, so that other tests can be enabled, while this one is
investigated separately.
cc @Mousius @NicolaLancellotti @areusch @ashutosh-arm @driazati @gigiblender @lhutton1
> [CI][ONNX] Set test python.contrib.test_onnx.test_resize as xfail

- python/tvm/relay/op/contrib/_ethosn.py
- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/convert_equivalent.cc
- src/relay/op/make_op.h
- src/relay/qnn/utils.h
- src/relay/transforms/pattern_utils.h
- tests/python/contrib/test_ethosn/test_convert_equivalents.py
- tests/python/contrib/test_ethosn/test_multiply.py
Multiply can be supported when offloaded to the NPU by a conversion to a depthwise convolution operation. This is only supported when the multiply operation has a single single variable input with the other being a constant of shape [1, ..., C]. This commit adds a new pass "ConvertEquivalents" (name subject to change) to handle this conversion before codegen.
cc @NicolaLancellotti @leandron
> [ETHOSN] Support multiply conversion to depthwise

- tests/python/contrib/test_hexagon/topi/test_cast_slice.py
Fix missing `import pytest` in a test file.
cc @driazati
> [Hexagon] Fix missing pytest import

- apps/microtvm/zephyr/template_project/microtvm_api_server.py
When you build a project from existing project directory using `tvm.micro.project.GeneratedProject.from_directory` it would show up error if build directory previously existed.
cc @alanmacd @gromero
> [microTVM] Fix `build` directory exists error

- src/runtime/crt/graph_executor/load_json.c
When compiling tvm with micro on the compiler which implements char as unsigned(such as arm-linux-gcc), there is an error:
`src/runtime/crt/graph_executor/load_json.c:218:12: error: result of comparison of constant -1 with expression of type 'char' is always false [-Werror,-Wtautological-constant-out-of-range-compare]`
`    if (ch == EOF || ch == '\r' || ch == '\n') {`
The reason is because the implementation of char is undefined, so it's better to specify here that it is signed.
> [MicroTVM] fix compile error when the compiler implements char as unsigned

- include/tvm/meta_schedule/schedule_rule.h
- python/tvm/meta_schedule/default_config.py
- python/tvm/meta_schedule/schedule_rule/multi_level_tiling.py
- python/tvm/meta_schedule/testing/schedule_rule.py
- src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_multi_level_tiling.py
cc @Hzfengsy @junrushao @junrushao1994 @masahi @spectrometerHBH
> [MetaSchedule] Add software pipeline in CUDA tensor core auto tensorization

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
This PR intends to add `aten::new_empty` which is used for model like `hf_Longformer`.
cc: @masahi
> [PyTorch] Add aten::new_empty

- apps/microtvm/zephyr/template_project/boards.json
This PR sets recommended heap size for qemu_x86 and NRF board to fix memory size with models like VWW using AoT host driven executor.
cc @alanmacd @areusch @gromero @mkatanbaf
> [microTVM][Zephyr] Add recommended heap size for NRF and qemu_x86

- .github/workflows/tests_bot.yml
- tests/python/ci/test_ci.py
- tests/scripts/github_skipped_tests_comment.py
This PR adds a script that does a diff of skipped tests between the latest successful build on the main and the current branch. Then, it posts a comment with the report on the open PR. 
#11670
@driazati @areusch
cc @Mousius
> [CI] Assert some unittests are not skipped in CI

- docs/dev/how_to/debugging_tvm.rst
The code block in part Debuggging TVM is not showing up. 
Just fix it.
> [DOC] fix code-block error in debuggging TVM part.

- tests/scripts/github_cc_reviewers.py
In a recent change, `github.post` throws `RuntimeError` instead of `HTTPError` when the requested reviewer isn't a project collaborator. This prevents other reviewers to be added to the PR, for example, https://github.com/apache/tvm/runs/8001367110?check_suite_focus=true.
This PR changes the caller to catch any exception so the execution won't be interrupted.
> [CI] github_cc_reviewers: Catch all exceptions so all reviewers can be processed

- tests/python/contrib/test_ethosu/test_codegen.py
Simply removes tests previously marked as xfail since the issue has now been resolved.
~Note: marked as draft since we should check recent CI runs after #12558 to make sure these tests are not silently failing.~
cc @Mousius
> [microNPU] Remove xfail from tests relating to #12511

- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/convert_equivalent.cc
- tests/python/contrib/test_ethosn/infrastructure.py
- tests/python/contrib/test_ethosn/test_addition.py
- tests/python/contrib/test_ethosn/test_convert_equivalents.py
- tests/python/contrib/test_ethosn/test_networks.py
In similar fashion to the conversion of mul to depthwise, this commit converts add when one input is a constant of shape [1, ..., n] to a depthwise convolution. If neither input is a constant, the add is offloaded naturally like before.
The addition testing has been improved to use pytest features.
~Note that this PR also contains the contents of #12403 until it is merged.~
cc @NicolaLancellotti @leandron @ashutosh-arm
> [ETHOSN] Support conversion of add to depthwise

- python/tvm/relay/transform/fake_quantization_to_integer.py
- tests/python/relay/test_pass_fake_quantization_to_integer.py
> [F2QI] Fix a rounding error on AvgPool when input and output affine scales differ

- src/target/source/codegen_cuda.cc
- tests/python/relay/test_op_level3.py
Try fix https://github.com/apache/tvm/issues/12566
> [CUDA][CodeGen] Fix cuda codegen's fp16 inf literal

- include/tvm/runtime/device_api.h
- python/tvm/tir/schedule/schedule.py
- python/tvm/tir/tensor_intrin/cuda.py
- src/printer/tir_text_printer.cc
- src/runtime/crt/common/crt_runtime_api.c
- tests/python/contrib/test_dlpack.py
- tests/python/contrib/test_ethosu/test_tir_to_cs_translator.py
- tests/python/contrib/test_ethosu/test_vela_api.py
- tests/python/unittest/test_tir_analysis_calculate_workspace.py
- tests/python/unittest/test_tir_intrin.py
- tests/python/unittest/test_tir_schedule_analysis.py
- tests/python/unittest/test_tir_schedule_reduction.py
- tests/python/unittest/test_tir_schedule_storage_align.py
- tests/python/unittest/test_tir_schedule_tensorize.py
- tests/python/unittest/test_tir_transform_convert_for_loops_serial.py
- tests/python/unittest/test_tir_transform_inject_rolling_buffer.py
- tests/python/unittest/test_tir_usmp_algo.py
- tests/python/unittest/test_tir_usmp_analysis_extract_bufferinfo.py
- tests/python/unittest/test_tir_usmp_transform_convert_pool_allocations_to_offsets.py
- tests/python/unittest/test_tir_usmp_transform_create_io_allocates.py
- tests/python/unittest/test_tir_usmp_utils.py
- tests/python/unittest/test_tvmscript_complete.py
- tests/python/unittest/test_tvmscript_roundtrip.py
- tests/python/unittest/test_tvmscript_syntax_sugar.py
- tests/python/unittest/test_tvmscript_type.py
One change made in https://github.com/apache/tvm/pull/5252 (which added support for Hexagon to the runtime) was increasing the byte alignment from 64 to 128. This can cause problems when interacting with dlpack. For example tests/python/contrib/test_dlpack.py has a high chance of failing when run locally due to torch returning tensors with 64 rather than 128 byte alignment. I'm not sure why it doesnt fail in CI, perhaps the consistency of the environment always returns an appropriately aligned tensor.
Changing the default alignment allows interoperability with both torch and newer versions of numpy that support dlpack. I've slightly modified the torch test to run multiple times to make sure its behavior is consistent.
See previous discussion in #12564. I chatted with @vinx13 and it seems …
> [Runtime] Change default alignment to 64 bytes.

- include/tvm/topi/transform.h
- tests/python/topi/python/test_topi_transform.py
This PR fixes #11697. The analysis of the bug is elaborated in #12400. The key problem is whether `axis` in `squeeze` means doing nothing or squeezing all one-dimensional axes. 
In #12400, I provide two possible fixes. I choose to fix TOPI finally. The meaning of `axis` is clearly described here (commit #2020):
https://github.com/apache/tvm/blob/fb7cf97fbc2cc19a7eea879a3a1598780f6aa6aa/include/tvm/relay/attrs/transform.h#L319-L327
The later commit to TOPI (#2147), however, does not follow this description. It seems that there is a mistake in this commit and should be corrected. 
CC: @masahi
> [TOPI][Bugfix] Make semantics of empty `axis` in `squeeze` consistent with Relay

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
The new image has xgboost installed, which I need for https://github.com/apache/tvm/pull/12587
Validated in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/279/pipeline
> [CI] Update Hexagon image to install boost

- src/runtime/hexagon/hexagon_buffer.cc
- src/runtime/hexagon/hexagon_device_api.cc
- src/runtime/hexagon/hexagon_user_dma.cc
- src/runtime/hexagon/hexagon_user_dma.h
- src/runtime/hexagon/hexagon_user_dma_descriptors.h
- src/runtime/hexagon/hexagon_user_dma_instructions.h
- src/runtime/hexagon/ring_buffer.h
- tests/cpp-runtime/hexagon/hexagon_user_dma_tests.cc
- tests/cpp-runtime/hexagon/ring_buffer_tests.cc
Adds adds asynchronous DMA support through the Hexagon User DMA engine with unit tests to validate basic functionality.  Asynchronous DMA support here means the ability to "kick off" asynchronously a number of DMAs using the `Copy` API and then to `Poll` for or `Wait` on a number of "in flight" (not done) DMAs.  Enables future testing and development for asynchronous memory copy on Hexagon.  For now, Hexagon DMA support remains synchronous in nature through existing `hexagon_user_dma_1d_sync` interface which uses asynchronous capable `HexagonUserDMA` class in a synchronous way --- calling `Copy` and `Wait` back to back for each request.
cc @mehrdadh
> [Hexagon] Asynchronous DMA support

- python/tvm/relay/frontend/pytorch.py
- python/tvm/relay/frontend/qnn_torch.py
Align output_scale/zero_point of sigmoid to Torch.
cc @masahi
> [QNN] Align output_scale/zero_point of sigmoid to Torch

- tests/micro/zephyr/test_zephyr_armv7m.py
This PR disables test_armv7m_intrinsic due to https://github.com/apache/tvm/issues/12619
cc @alanmacd @gromero
> [microTVM][Zephyr] Disable test_armv7m_intrinsic since it's broken

- python/tvm/tir/schedule/_type_checker.py
- tests/python/unittest/test_type_annotation_checker.py
Previously, `Callable` was handled as an atomic type.  This worked when it was included as last element of a `Union[]` annotation with no subtypes, but raised an error for other use cases, including `Optional[Callable]`.
This commit adds explicit checks for `Callable` type annotations to validate whether the argument is callable, but doesn't recursively validate the signature of the callable object, because lambda functions cannot have type annotations. (https://peps.python.org/pep-3107/#lambda)
> [Utils] Handled Callable in tir.schedule._type_checker

- src/tir/op/op.cc
Previously, type-checks in boolean operators on `PrimExpr` would state that the type is incorrect, but further investigation would be required in order to determine what expression caused the error.  After this commit, error messages for these type checks include the expression that was used, and the dtype of that expression.
> [TIR] Improved error messages for PrimExpr operator overloads

- python/tvm/topi/arm_cpu/mprofile/dsp/pool.py
When I built keyword spotting ONNX model, there was an issue with the pool schedule because certain schedules like  `broadcast` and `elemwise` do not have input tensors.
cc @alanmacd @areusch @gromero @guberti @sergey-grovety
> [microTVM][ARM-DSP] Fix pool schedule 

- python/tvm/micro/testing/evaluation.py
- python/tvm/micro/testing/utils.py
This PR: changes `get_target` to return Target instead of str and also add's logging to the predict function
> [microTVM]Fix test util functions

- apps/microtvm/zephyr/template_project/CMakeLists.txt.template
This PR adds missing CMSIS-NN source files to Zephyr cmake template file for models like keyword spotting, anomaly detection, VWW and image classification.
> [microTVM][Zephyr] Add missing CMSIS-NN source files to cmake file

- Jenkinsfile
- ci/jenkins/Prepare.groovy.j2
This makes it so changes to certain files from users not listed in
`CONTRIBUTING.md` are not tested in CI. This is necessary since these
scripts run on the baremetal EC2 instances and not inside Docker
containers, so they can affect other builds and potentially grab Jenkins
secrets. This checks out the version from the upstream for the listed
files after running `git checkout`. Tested in CI: [positive](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-12604/6/pipeline/) and [negative](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-12604/9/pipeline/)
> [ci] Add mechanism for trust on certain CI scripts

- src/tir/transforms/lower_opaque_block.cc
- tests/python/unittest/test_tir_transform_lower_opaque_block.py
Hi, there. The change aims to improve customization experience of TIR lowering using annotations.
Currently, we have `LowerOpaqueBlock` pass to convert s-tir(schedulable tir with blocks) to non-stir. All annotations are dropped then except those used by legacy TE pragma attributes, they are converted to legacy AttrStmt. For example:
```python
for i in range(10, annotations={"pragma_myattr0": 1, "my_attr0": 1}): ....
with T.attr(i, "pragma_myattr0", 1):
for i in range(10): ....
```
This introduce difficulties when we want to leverage schedule phase annotations in lowering passes.
1. `pragma_` annotations are converted to legacy AttrStmt, which only accepts `PrimExpr` typed value. But the loop/block annotations before are originally much flexible, one could use list/dict to encode more rich …
> [TIR] Preserve annotations after lower opaque block

- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/ethosn_api.cc
- tests/python/contrib/test_ethosn/test_networks.py
- tests/python/contrib/test_ethosn/test_reshape.py
This pr improves the inference of the new shape of the Reshape operator for the Arm(R) Ethos(TM)-N NPU.
cc @lhutton1
> [ETHOSN] Improve inferring new shape of the Reshape operator

- tests/python/driver/tvmc/test_frontends.py
This patch makes test_load_model___wrong_language__to_pytorch to be
skipped in AArch64 due to a bug that can be reproduced when enabling
Integration Tests in machines with Torch installed in TVM.
```
The error message seen is:
OSError: /usr/local/lib/python3.7/dist-packages/torch/lib/
libgomp-d22c30c5.so.1: cannot allocate memory in static TLS block
```
While the test needs further investigation, it is being set as
skipped so other tests can be enabled and not to regress and allow
time for the investigation to be made.
This relates to the issue described in #10673.
cc @Mousius @driazati @NicolaLancellotti @ashutosh-arm @areusch @gromero
> [Torch][AArch64] Skip test_load_model___wrong_language__to_pytorch

- Jenkinsfile
- ci/jenkins/Prepare.groovy.j2
- ci/scripts/check_pr.py
- ci/scripts/git_skip_ci.py
- tests/scripts/check_pr.py
This adds a lint step that checks the PR title and body with some of the basic checks from https://github.com/apache/tvm-rfcs/pull/88. This makes it so we can enforce the decided rules without having to rely on automated fix-ups, though for certain things those would be ideal in the future. The rules implemented here are not complete as the RFC is not fully merged but this is just supposed to be a starting point with some of the basic rules, namely that a title and body should be present. A follow up PR will enforce that there are no @ tags once #12637 is resolved.
cc @Mousius @areusch @gigiblender @gromero @leandron
> [ci] Add linter for PR title and body

- python/tvm/tir/schedule/schedule.py
- tests/python/unittest/test_tir_schedule_cache_read_write.py
Previously, the argument needed to be an integer specifying the index into the read/write regions of a block.  Now, the argument can be a string specifying the name of the buffer, or the Buffer object itself. This is a follow-up from https://github.com/apache/tvm/pull/11624.
> [TIR] Allow string/buffer arguments to Schedule cache_read/write

- tests/lint/pylint.sh
- tests/python/contrib/test_ethosn/infrastructure.py
- tests/python/contrib/test_ethosn/test_concatenate.py
- tests/python/contrib/test_ethosn/test_constant_duplication.py
- tests/python/contrib/test_ethosn/test_conv2d.py
- tests/python/contrib/test_ethosn/test_depth_to_space.py
- tests/python/contrib/test_ethosn/test_fullyconnected.py
- tests/python/contrib/test_ethosn/test_leaky_relu.py
- tests/python/contrib/test_ethosn/test_mean.py
- tests/python/contrib/test_ethosn/test_multiply.py
- tests/python/contrib/test_ethosn/test_networks.py
- tests/python/contrib/test_ethosn/test_partition_params.py
- tests/python/contrib/test_ethosn/test_pooling.py
- tests/python/contrib/test_ethosn/test_relu.py
- tests/python/contrib/test_ethosn/test_requantize.py
- tests/python/contrib/test_ethosn/test_resize.py
- tests/python/contrib/test_ethosn/test_sigmoid.py
- tests/python/contrib/test_ethosn/test_split.py
- tests/python/contrib/test_ethosn/test_tanh.py
- tests/python/contrib/test_ethosn/test_topologies.py
This pr fixes pylint errors in `tests/python/contrib/test_ethosn` as reported in #11414.
cc @lhutton1
> [ETHOSN] Fix tests pylint errors

- python/tvm/relay/analysis/analysis.py
- src/relay/analysis/extract_intermediate_expr.cc
- tests/python/relay/test_analysis_extract_intermediate_expr.py
Hi,
When I actually develop operators for some models, I often need to do some verification.
And when I encounter a situation where the input and output values of the entire model do not match the golden values, I often need to dump some intermediate nodes to confirm which node the problem starts from.
As we know, we can easily print Relay IR by `print(mod["main"])`, 
Relay IR represents each node as "%xx %10 %20", I feel comfortable if we can dump nodes with "%xx" as a parameter.  
So I develop a pass that can dump op by `dump_op_by_num(mod,xx)`.  
Because we generally use dump OP for analysis purposes, I set it as an `relay.analysis` API.  
What do you think? Do we need such an API?  
I am looking forward to your reply. Thank you!
> [Relay] Extract intermediate node by its expression ID

- python/tvm/topi/hexagon/__init__.py
- python/tvm/topi/hexagon/injective.py
- python/tvm/topi/hexagon/tensor_intrin.py
- tests/python/contrib/test_hexagon/test_fixed_point_multiply.py
This commit adds high-performance implementation of `fixed_point_multiply`
operation based on Hexagon intrinsics for vmpye/vmpyo instructions.
Benchmarking of `fixed_point_multiply` op with (1,8,56,56,32) input
tensor on Qualcomm SM8350:
* default implementation: **10.06 ms**
* optimized implementation: **1.42 ms**
* speedup: **7x** times (!!!)
Please note that this is introducing a small round-up error for some
corner cases with negative shift argument (The same as for ARM CPU, see
[PR#5980](https://github.com/apache/tvm/pull/5980)). This is because we are rounding twice instead than only once:
* original q_multiply_shift: round(x*y*2^-s)
* hexagon q_multiply_shift: round(round(x*y)*2^-s)
cc @mehrdadh
> [Hexagon] Implement fixed_point_multiply op through intrinsics.

- src/meta_schedule/schedule_rule/auto_inline.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_inline.py
This PR intends to fix the CUDA auto-inline schedule rule while processing TIR block with one single constant consumer block. 
Before this PR, the TIR added in the test will throw the following error while being auto-inlined as it shouldn't be.:
```
E           ScheduleError: An error occurred in the schedule primitive 'compute-inline'.
E           The IR with diagnostic is:
E           # from tvm.script import tir as T
E           @tvm.script.ir_module
E           class Module:
E               @T.prim_func
E               def main(T_full: T.Buffer[(1, 12, 4096), "int64"]) -> None:
E                   # function attr dict
E                   T.func_attr({"global_symbol": "main", "tir.noalias": True})
E                   # body
E                   # with T.block("root")
E …
```
> [MetaSchedule] Fix autoinline for single const consumer block

- include/tvm/runtime/vm/executable.h
- python/tvm/runtime/vm.py
- src/runtime/vm/executable.cc
- tests/python/relay/test_vm.py
This PR adds methods to both get and set late-bound constants.
The current approach for saving and restoring a model's late-bound constants is via the either `MoveLateBoundConstantsToFile` and then this file can be reloaded to the Executable by calling `LoadLateBoundConstantsFromFile`. These methods save the constants to a file `consts`.
I have a need to save and restore the constants in a pre-existing format. In order to write these I added `GetLateBoundConstants`  which returns a Map of all late-bound contants. To restore the constants back to the Executable `LoadLateBoundConstantsFromMap` was added.
The PR arranges the code so that both `GetLateBoundConstants` and `LoadLateBoundConstantsFromMap` are used in the existing methods to write and read late-bound constants. This means there …
> Add methods to get and set late-bound constants.

- python/tvm/relay/op/strategy/adreno.py
- python/tvm/topi/adreno/conv2d_alter_op.py
- python/tvm/topi/adreno/conv2d_nchw.py
- python/tvm/topi/adreno/conv2d_nchw_winograd.py
- python/tvm/topi/adreno/conv2d_nhwc.py
- python/tvm/topi/adreno/conv2d_nhwc_winograd.py
- python/tvm/topi/adreno/conv2d_winograd_common.py
- python/tvm/topi/adreno/depthwise_conv2d_nchw.py
- python/tvm/topi/adreno/depthwise_conv2d_nhwc.py
- tests/python/relay/test_conv2d_nchw_texture.py
- tests/python/relay/test_conv2d_nhwc_texture.py
The current support of mixed precision in adreno schedules  was implemented as standalone schedules having "fp32" suffix. Such kernels can be selected during compilation due to two reasons
1. We had higher priority for fp16_acc32 schedule than pure fp16 schedules
2. If we saw AutoTVM tune statistics with proper schedule name
The tune flow in its turn was not able to distinguish and point only fp16 or fp16_acc32. Both schedules are tuned and during the compilation the schedule having best time is selected. I.e. by fact without artificial approach we are not able to tune and compile pure fp16 or fp16_acc32. Only manual selection of tune statistics causes currently to execute one of this mode.
In addition to this, the conversion function to fp16 was custom made in the user's script that …
> [Adreno] Change compute/schedule for ToMixedPrecision pass

- tests/python/contrib/test_hexagon/topi/test_max_pool2d_slice.py
- Re-enable test_max_pool2d_slice.py when run on Hexagon
hardware (as opposed to hexagon-sim).
This is now safe because https://github.com/apache/tvm/issues/11928
has been fixed.
cc @mehrdadh
> [hexagon][tests] re-enable maxpool hardware test

- python/tvm/topi/hexagon/slice_ops/argmax.py
- tests/python/contrib/test_hexagon/topi/test_argmax_slice.py
This PR adds support for argmax uint8 slice op for hexagon.
cc @mehrdadh
> [HEXAGON][TOPI]Slice Op Argmax uint8

- include/tvm/meta_schedule/database.h
- python/tvm/meta_schedule/database/__init__.py
- python/tvm/meta_schedule/database/ordered_union_database.py
- python/tvm/meta_schedule/database/union_database.py
- src/meta_schedule/database/json_database.cc
- src/meta_schedule/database/ordered_union_database.cc
- src/meta_schedule/database/union_database.cc
- src/meta_schedule/utils.h
- tests/python/unittest/test_link_params.py
- tests/python/unittest/test_meta_schedule_database.py
Following up https://github.com/apache/tvm/pull/12520 and https://github.com/apache/tvm/pull/12626, this PR introduces two database classes:
`UnionDatabase` and `OrderedUnionDatabase`, both of which allow users to
organically compose multiple databases together, so that the high-level
IR (Relay, Relax) could select the best tuning records according to
running time or a preferred order given by users.
To each query, `UnionDatabase` returns the best record among all the
databases given; Instead, `OrderedUnionDatabase` returns he record from
the first database that responds to the query.
Used together, users may specify complicated dispatching patterns like
below:
Examples below demonstrate the usecases of and difference between
UnionDatabase and OrderDatabase.
Assumption:
* db1, db2 do not …
> [MetaSchedule] Introduce `Union` and `OrderedUnion` in Database

- python/tvm/meta_schedule/builder/__init__.py
- python/tvm/meta_schedule/builder/builder.py
- python/tvm/meta_schedule/database/__init__.py
- python/tvm/meta_schedule/database/database.py
- python/tvm/meta_schedule/database/json_database.py
- python/tvm/meta_schedule/runner/__init__.py
- python/tvm/meta_schedule/runner/runner.py
- python/tvm/meta_schedule/search_strategy/__init__.py
- python/tvm/meta_schedule/search_strategy/search_strategy.py
- python/tvm/meta_schedule/space_generator/__init__.py
- python/tvm/meta_schedule/space_generator/space_generator.py
- python/tvm/meta_schedule/task_scheduler/__init__.py
- python/tvm/meta_schedule/task_scheduler/task_scheduler.py
- python/tvm/meta_schedule/testing/relay_workload.py
This PR introduces a set of `.create` methods making it easier to create
MetaSchedule objects.
For example:
```python
ms.database.JSONDatabase(...)
ms.database.create("json")
ms.runner.RPCRunner(...)
ms.runner.create("rpc")
```
Besides, this PR allows `JSONDatabase` to be created via `work_dir`:
```python
db = ms.database.create("json", work_dir="/path/to/db/")
db = ms.database.create(work_dir="/path/to/db/")  # or even simpler
```
> [MetaSchedule][UX] Convenient Object Creation

- src/relay/backend/contrib/ethosn/ethosn_api.cc
- tests/python/contrib/test_ethosn/test_concatenate.py
Supports offloading concatenate with a negative axis to the NPU. In addition, parameterized the concatenate unit tests.
cc @leandron @NicolaLancellotti
> [ETHOSN] Add support for concatenate with negative axis

- python/tvm/autotvm/testing/__init__.py
- python/tvm/autotvm/testing/tune_relay.py
Example:
```bash
python -m tvm.autotvm.testing.tune_relay  \
--workload bert_base               \
--input-shape '[1,64]'             \
--target "llvm"                    \
--num-trials 800                   \
--rpc-host 192.168.6.66            \
--rpc-port 4445                    \
--rpc-key 3090ti                   \
--work-dir /logs/autotvm-bert_base \
--cache-dir /cache-workloads       \
--graph-tuner True                 \
--cpu-flush True                   \
--backend graph
```
> [AutoTVM][Testing] Add `tune_relay` scripts

- ci/scripts/check_pr.py
- tests/python/ci/test_ci.py
This adds some checks for the current usages of the PR linter and fixes the case where the script would error uncleanly when a PR body was `null`.
> [ci] Add tests for PR linter

- include/tvm/target/target_info.h
- python/tvm/topi/adreno/utils.py
There are now many warnings in the tuning process about undefined memory information when using textures. A definition is required as textures* are tagged.
> [Adreno] Define memory_info for global.texture*

- web/Makefile
As a follow-up to https://github.com/apache/tvm/pull/12337, updating the EMCC flags from `-std=c++14` to `-std=c++17`.
> [Web][Emscripten] Update EMCC C++ standard to C++17

- tests/python/contrib/test_ethosn/test_conv2d.py
- tests/python/contrib/test_ethosn/test_depth_to_space.py
- tests/python/contrib/test_ethosn/test_fullyconnected.py
- tests/python/contrib/test_ethosn/test_pooling.py
- tests/python/contrib/test_ethosn/test_relu.py
- tests/python/contrib/test_ethosn/test_resize.py
- tests/python/contrib/test_ethosn/test_sigmoid.py
- tests/python/contrib/test_ethosn/test_split.py
- tests/python/contrib/test_ethosn/test_topologies.py
Using PyTest parameterization helps identify the particular parameter combinations that are failing for a given test. Additionally, it can be useful when parallelizing the tests. This commit makes sure that "trials" have been replaced by parameterization as well as completing a general cleanup.
cc @leandron @NicolaLancellotti
> [ETHOSN] Use pytest parameterization for integration tests

- apps/android_camera/models/requirements.txt
At the moment, android camera is installing latest TF and Keras
which is causing the following issue in CI:
```
File ".../keras/dtensor/lazy_variable.py", line 26, in <module>
from tensorflow.python.trackable import base as trackable
ModuleNotFoundError: No module named 'tensorflow.python.trackable'
```
This patch fixes the versions in the last known working versions
of both: TF 2.9.1 and Keras 2.9.
cc @driazati @lhutton1 @areusch
> [Apps] Pin android_camera TensorFlow/Keras dependency version

- src/runtime/hexagon/hexagon_buffer.cc
- src/runtime/hexagon/hexagon_device_api.cc
- tests/python/contrib/test_hexagon/test_memory_alloc.py
[hexagon][runtime] better support for 2-tier memory
- Introduce 'global.ddr' memory scope:
- Like 'global', this allocates memory from the Hexagon SoC's
DDR memory.
- Like 'global.vtcm', the specified tensor shape must be 1d
or 2d, where 2d indicates Hexagon's "indirect tensor"
(i.e., discontiguous) allocation scheme.
- Change memory-alignment strategy to always be 2048-byte aligned
on Hexagon.  (This can be refined in the future, but for now it
ensures all allocations meet the strictest alignment requirements
for any Hexagon operations.)
cc @areusch @mehrdadh
> [Hexagon][Runtime] Better support for 2-tier memory

- python/tvm/relay/op/nn/_nn.py
- python/tvm/relay/op/strategy/generic.py
- python/tvm/relay/op/strategy/hexagon.py
- python/tvm/topi/hexagon/__init__.py
- python/tvm/topi/hexagon/pad.py
- tests/python/contrib/test_hexagon/topi/test_pad.py
**Motivation**:
In case of quantized models nn.pad operation typically is not fused with QNN ops and lives as a standalone operation. In this case it uses default injective schedule for Hexagon target and it is not optimized very well for some shapes/layouts (based on analysis of real models like ResNet50 INT8).
**What was done:**
New schedule for Pad operation was implemented instead of default injective schedule. For Hexagon target injective schedule does fusion of all axis and vectorization on 128/64/32 (depends on dtype). It works fine for Add, Sub, etc... but not for Pad. New optimized schedule does these steps (fusion+vectorization) only if last tensor dimension is divisible by 128/64/32 (depends on dtype). It was done only for Hexagon, for other targets (x86, cuda, etc.) there is …
> [Hexagon] Add optimized schedule for nn.pad

- docs/contribute/pull_request.rst
This commit adds the Commit Message Guideline text to Apache TVM
documentation in ./docs/contribute/pull_request.rst, under section
'Submit a Pull Request', below subsection 'Guidelines', as a subsection
named “Commit Message Guideline”. The text in the second-last item in
subsection 'Guidelines' that mentions PR tags is also updated to refer
to this guideline.
This documentation will help guide contributors on how to write good
commit messages when submitting code / creating Pull Requests, in
accordance with RFC-0088:
https://github.com/apache/tvm-rfcs/blob/main/rfcs/0088-commit-message-guideline.md
> [Docs] Add Commit Message Guideline

- src/tir/transforms/loop_partition.cc
- tests/python/unittest/test_tir_transform_loop_partition.py
Current LoopPartition doesn't check the value of attribute key "pragma_loop_partition_hint". Whatever I set pragma_loop_partition_hint to True or False, the result is same, which is confused for debug.
This PR fix pragma_loop_partition_hint attribute key should check it's value.
@Hzfengsy 
> [TIR] Fix pragma_loop_partition_hint attrs should check it's value

- python/tvm/relay/op/contrib/ethosn.py
- src/relay/backend/contrib/ethosn/codegen.cc
- src/relay/backend/contrib/ethosn/codegen_ethosn.h
- src/relay/backend/contrib/ethosn/convert_equivalent.cc
- src/relay/backend/contrib/ethosn/ethosn_api.cc
- src/relay/backend/contrib/ethosn/ethosn_api.h
- tests/python/contrib/test_ethosn/infrastructure.py
- tests/python/contrib/test_ethosn/test_conv2d.py
- tests/python/contrib/test_ethosn/test_conv2d_transpose.py
Adds support for offloading transpose convolution with an optional bias to the NPU.
Co-authored-by: Samuel Panijel <samuel.panijel@arm.com>
Co-authored-by: Leo Blonk <leo.blonk@arm.com>
cc @leandron @Leo-arm @spanijel
> [ETHOSN] Add support for transpose convolution

- python/tvm/topi/hexagon/qnn/__init__.py
- python/tvm/topi/hexagon/qnn/dequantize.py
- python/tvm/topi/hexagon/utils.py
- tests/python/contrib/test_hexagon/infrastructure.py
- tests/python/contrib/test_hexagon/topi/test_dequantize_slice.py
> [HEXAGON] [TOPI] Dequantize

- cmake/modules/contrib/TFLite.cmake
- docker/Dockerfile.ci_cortexm
- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_gpu
- docker/Dockerfile.ci_riscv
- docker/install/ubuntu_install_cmake_source.sh
- docker/install/ubuntu_install_python_package.sh
- docker/install/ubuntu_install_tensorflow.sh
- docker/install/ubuntu_install_tensorflow_aarch64.sh
- docker/install/ubuntu_install_tflite.sh
- docker/install/ubuntu_install_vela.sh
- docker/install/ubuntu_install_zephyr.sh
This updates the TF version to be used in TVM CI to 2.9.1, which brings improvements so that more platforms are supported by official packages. This PR updates the Docker images scripting to install TF and TFLite and some CMake changes required when updating from TF 2.6.x to 2.9.x.
Adding it here as a draft until we get #12130 merged.
cc @Mousius @NicolaLancellotti @areusch @driazati @gigiblender
> [TFLite][CI] Update TensorFlow dependency to 2.9.1

- Jenkinsfile
- ci/jenkins/Test.groovy.j2
- ci/jenkins/generate.py
- python/tvm/contrib/hexagon/pytest_plugin.py
- tests/scripts/setup-pytest-env.sh
This uses numbers from this script: https://github.com/tlc-pack/ci/pull/51 that determines the number of shards to use given a goal runtime (in this case 60 minutes for tests)
> [ci] Re-balance shards

- src/tir/transforms/loop_partition.cc
- tests/python/unittest/test_tir_transform_loop_partition.py
Current  LoopPartition pass, for multiple conditions, when only part conditions are satisfied, it will be partitioned together.
This PR add a unroll_loop_with_partition_hint_no_interval attr in LoopPartitionConfig, when pragma_loop_partition_hint is set and the interval doesn't exist, the loop will be marked kUnrolled and do unroll actions in the following pass.
cc @Hzfengsy @junrushao1994 @wrongtest-intellif
> [TIR] Add unroll_loop_with_partition_hint_no_interval attr in LoopPartitionConfig     to unroll loop

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/topi/arm_cpu/depthwise_conv2d.py
- python/tvm/topi/arm_cpu/mprofile/dsp/depthwise_conv2d.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/quad_channel_convolve.py
- tests/python/relay/strategy/arm_cpu/test_depthwise_conv2d.py
Currently, our microTVM implementation of `depthwise_conv2d` uses the fallback schedule, and performance is subsequently terrible. This change adds a schedule for certain cases of `depthwise_conv2d` when it is run on a Cortex M4 or M7 based chip (though I mainly thought about the M4). Almost all of the "big" performance speedups have been implemented, which should make our implementation faster than TFLite Micro and comparable to CMSIS-NN:
- Performs 4x fewer memory loads than the fallback implementation by loading four `int8` values from the kernel and input tensor at a time. This is the main source of our speedup.
- Uses a hand-written assembly micro-kernel utilizing the `__SMLAD` instruction to compute convolutions for four channels at once.
- Uses a specialized kernel packing to …
> Add Arm DSP implementation of Depthwise Conv2D

- python/tvm/relay/qnn/op/legalizations.py
Currently, Relay QNN uses its `helper_no_fast_int8_hw_legalization` to convert most `int8` convolution and dense operations into `int16` ones on Arm. This currently occurs on ARM chips except for `v8.2a` chips with `dotprod` support.
However, this behavior means that `int8` operations are replaced with `int16` ones on Cortex-M chips. On these chips `int16` is substantially slower, as while it saves a few sign extension operations, it doubles the amount of memory loads we need to perform. 
This PR changes when `helper_no_fast_int8_hw_legalization` is used on Arm, and instead makes **not** doing this replacement the standard. We will only do this replacement if we are on a chip with ASIMD support but without `v8.2a` and `dotprod`. This ensures that Cortex-M microcontrollers do not have …
> [Relay] Change when int8 operations are converted to int16 on Arm

- tests/python/unittest/test_meta_schedule_integration.py
This patch marks two tests as xfail for further investigation:
* `test_meta_schedule_integration_extract_from_resnet_with_filter_func`
* `test_meta_schedule_integration_extract_from_resnet`
The errors are reported in #12732
cc @Hzfengsy @Mousius @areusch @driazati @junrushao @junrushao1994 @lhutton1
> [MetaSchedule] Mark two tests as xfail

- src/tir/schedule/primitive/compute_inline.cc
- tests/python/unittest/test_tir_schedule_compute_inline.py
* When the producer region is larger than the consumer region, `reverse_compute_inline` should generate predicates to prevent out-of-bound access to the consumer region.
* Check the consumer block iter domains are covered by the producer after inlining.
cc @spectrometerHBH @Hzfengsy @jwfromm
> [TIR, Schedule] Check consumer in-bound and covered in reverse_compute_inline

- docker/Dockerfile.ci_cortexm
- docker/install/ubuntu_install_cmake_source.sh
The Zephyr project builds require 3.20.0 to work correctly
> [ci][docker] Use CMake 3.20.0 for cortexm

- python/tvm/relay/frontend/tensorflow_ops.py
- tests/python/frontend/tensorflow/test_forward.py
This PR adds TF [DenseBincount](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/dense-bincount) support. The code was inspired by TVM [pytorch.py bincount impl](https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/pytorch.py#L2526).
- Requires `relay.vm.compile` because internal data structures shapes depend on the input data content.
- Input array should not contain numbers outside of the range `[0, size-1]`. TVM `scatter_add` counts such values, but TF `DenseBincount` ignores them.
@masahi
> [TF] Add DenseBincount support

- Jenkinsfile
- ci/jenkins/Jenkinsfile.j2
- tests/scripts/task_config_build_cpu.sh
- tests/scripts/task_python_docs.sh
Updates Docker (all but `ci_cortexm`) images to tag
`20220908-060034-62bdc91b1`, to update TensorFlow/
TFLite/Keras to 2.9, and cascaded dependencies such as numpy.
Updates ethos-u-vela to 3.4.0.
It standardises (all but `ci_cortexm`) the minimum CMake version
required in CI to be 3.18.4.
`ci_cortexm` is updated to `20220909-090211-cb08a1251` as
it requires at least CMake 3.20 to comply with Zephyr requirements.
It also brings ONNX and PyTorch to ci_arm, to enable Integration tests
to be run in CI.
cc @Mousius @areusch @driazati @ekalda @gigiblender @lhutton1
> [CI] Update Docker images to bring TF 2.9 and integration tests

- apps/microtvm/zephyr/template_project/app-overlay/nucleo_l4r5zi.overlay
- apps/microtvm/zephyr/template_project/microtvm_api_server.py
- cmake/modules/Zephyr.cmake
- tests/lint/check_file_type.py
This PR adds a mechanism to overwrite device tree configs in zephyr project. It also adds an overlay for nucleo_l4r5zi board to change processor frequency from 80MHz which is the default to 120MHz.
> [microtvm][Zephyr] Add project overlay to overwrite device tree configs

- src/printer/tvmscript_printer.cc
- src/tir/transforms/convert_blocks_to_opaque.cc
- tests/python/unittest/test_tir_transform_convert_blocks_to_opaque.py
Previously, it was ambiguous whether `BlockNode::iter_vars` were in-scope for `BlockRealizeNode::predicate`.  `ConvertBlocksToOpaque` treated them as in-scope, and applied a mapping from `iter_vars` to `iter_values`.  Similarly, TVMScript printing places `T.where` statements below the `T.axis` statements, where `T.axis` definitions are in scope.  However, `BlockRealizeNode::SEqualReduce` and `BlockRealizeNode::SHashReduce` do not visit the block and `iter_vars` until after visiting the predicate, placing the `iter_vars` out of scope.
This commit updates the printing of `T.where` to be above `T.axis`, and updates `ConvertBlocksToOpaque` to report an error if the predicate contains references to `BlockNode::iter_vars`.  After this commit, these three usages all consistently treat …
> [TVMScript][TIR] Clarify scope of BlockNode::iter_vars

- python/tvm/relay/frontend/paddlepaddle.py
Related to #12645.
I noticed that in the front-end conversion of paddle, all operators do not pass data_format information. 
I want to know whether data_format needs to be passed, or the operators in the paddle model are all set according to the default layout of the `python/tvm/relay/op/nn/nn.py`? And the author of #12645 should not diy the layout ? 
Please let me know if anything is wrong.
> [Frontend][Paddle] Fix op in paddle did't transmit layout information

- include/tvm/tir/op.h
- python/tvm/runtime/object_generic.py
- python/tvm/script/tir/intrin.py
- src/arith/const_fold.h
- src/ir/expr.cc
- src/support/scalars.cc
- src/support/scalars.h
- tests/python/relay/test_op_level4.py
- tests/python/relay/test_pass_fuse_ops.py
- tests/python/unittest/test_arith_rewrite_simplify.py
- tests/python/unittest/test_target_codegen_cuda.py
- tests/python/unittest/test_tir_imm_values.py
- tests/python/unittest/test_tir_transform_narrow_datatype.py
Refer to issues https://github.com/apache/tvm/issues/12377 and https://github.com/apache/tvm/issues/12378. The behavior of compile time constant folding and general path computation differs.
The changes are:
- Add more strict value range checking when build IntImm object.
- For constant folding on integers
- Mimic intN arithmetic on intN folding, instead of direct int64 arithmetic.
- For constant folding on floats
- Only support float32 and float64, use float32 arithmetic on float32 folding, instead of float64 arithmetic.
- Temporarily forbid fold float16 since we do not have implemented fp16 arithmetics yet and there may exist compatibility issues on different targets.
> [TIR][Arith] Add more strict checking in imm construction and folding.

- docker/install/ubuntu_install_ethosn_driver_stack.sh
- python/tvm/relay/op/contrib/ethosn.py
- tests/python/contrib/test_ethosn/test_networks.py
- tests/python/contrib/test_ethosn/test_resize.py
- tests/python/contrib/test_ethosn/test_split.py
- tests/python/contrib/test_ethosn/test_topologies.py
Updates the driver stack used by the NPU to the latest released version (semantic version 3.1.0), while maintaining backwards compatibility for the previous version 22.05 (semantic 3.0.1) during the migration period. In addition, support for split is re introduced as this is now supported in 22.08.
cc @leandron @NicolaLancellotti
> [ETHOSN] Update driver stack version to 22.08

- python/tvm/relay/frontend/tensorflow_ops.py
- tests/python/frontend/tensorflow/test_forward.py
- tests/python/frontend/tensorflow2/test_functional_models.py
This PR adds TF [Bincount](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Bincount) support. 
Recently [DenseBincount support](https://github.com/apache/tvm/pull/12728) was added. Both `raw_ops.Bincount` and `raw_ops.DenseBincount` are used by `tf.math.bincount()` . One or another raw_op is used depending on the `tf.math.bincount()` parameters.
- Requires `relay.vm.compile` because internal data structures shapes depend on the input data content.
- Input array should not contain numbers outside of the range `[0, size-1]`. TVM `scatter_add` counts such values, but TF `DenseBincount` ignores them.
- using `tf.math.bincount()` with `weights` and `axis=None` requires operator `UnsortedSegmentSum` to be implemented.
@masahi
> [TF] Add Bincount support

- python/tvm/meta_schedule/default_config.py
A typo to check function name is "main".
> [MetaSchedule] Fix typo of compare between GlobalVar and str

- tests/python/contrib/test_hexagon/test_2d_physical_buffers.py
Previously, the test cases only tested TE-based schedules.  This commit runs the same tests for equivalent TIR-based schedules as well.  This is intended to catch Hexagon-specific regressions, such as the one resolved in https://github.com/apache/tvm/pull/12652.
cc @mehrdadh
> [Hexagon] Validate 2-d physical shapes for TIR-derived schedules

- python/tvm/autotvm/testing/tune_relay.py
- python/tvm/autotvm/tuner/xgboost_cost_model.py
- python/tvm/meta_schedule/testing/relay_workload.py
This PR introduces a couple of fixes to make AutoTVM working more robustly:
- Fixed a very rarecase that `None` could pop up in AutoTVM features;
- Fixed a misuse of `ARGS` in the testing script;
- Fixed the filename for caching.
> [AutoTVM] Fix `None` feature in AutoTVM tuning

- python/tvm/meta_schedule/testing/schedule_rule.py
- python/tvm/tir/schedule/testing.py
- src/meta_schedule/schedule_rule/add_rfactor.cc
- src/tir/schedule/primitive/sampling.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_add_rfactor.py
This PR migrates the usage of `check_trace` to `check_sketch`,
which prefers structural equality of TIRs insteda of string equalty
of traces.
> [MetaSchedule][Testing] Migrate Add-RFactor to use SEqual

- python/tvm/meta_schedule/testing/schedule_rule.py
- tests/python/unittest/test_meta_schedule_schedule_rule_auto_bind.py
- tests/python/unittest/test_meta_schedule_schedule_rule_cross_thread_reduction.py
- tests/python/unittest/test_meta_schedule_schedule_rule_parallel_vectorize_unroll.py
- tests/python/unittest/test_meta_schedule_schedule_rule_random_compute_location.py
This PR further migrates more `check_trace` (string equality of traces) to `check_sketch` (structural equality of TIR) for the following schedule rules:
- AutoBind
- RandomComputeLocation
- CrossThreadReduction
- ParallelVectorizeUnroll
The only tests that are not migrated in this PR is `MultLevelTiling`, which consists too many `check_trace`s which could bloat the PR size, so I decided to keep it as a separate one for easy review
> [MetaSchedule][Test] Migrate `check_trace` to `check_sketch`

- python/tvm/contrib/hexagon/session.py
- src/runtime/hexagon/hexagon_buffer.cc
- src/runtime/hexagon/hexagon_device_api.cc
- tests/python/contrib/test_hexagon/test_parallel_hvx_load_vtcm.py
- tests/python/contrib/test_hexagon/test_vtcm_bandwidth.py
In order to learn more about efficiently running on Hexagon, an investigation into how to properly utilize VTCM was performed. These are the initial results of that investigation and should serve as a good starting point for others looking to leverage VTCM while running on Hexagon. 
Below are the results from running a simple parallel vrmpy operation in several different configurations. Each configuration is described below. 
**Without VTCM:** This is just running the vrmpy operator without loading any data into VTCM 
**Basic VTCM Loads:** This introduces loops to copy the data into VTCM before running the compute without any scheduling of those data copy loops. 
**Vec Loads:** This applies the following scheduling to the data copy loops.  For the DDR -> VTCM loops it uses unroll_split = …
> [Hexagon] Create tests to showcase vtcm loading capabilities on Hexagon. 

- python/tvm/te/hybrid/parser.py
fixed https://github.com/apache/tvm/issues/9955, this is covered by the existing test case `tests/python/relay/test_op_level3.py::test_unique`
cc @masahi
> [Hybrid] Fix handling AST subcription for Python3.9

- CMakeLists.txt
- python/tvm/relay/backend/_aot.py
- python/tvm/relay/backend/aot.py
- src/relay/backend/aot/aot_lower_main.cc
- src/relay/backend/aot/aot_lower_main.h
- src/relay/backend/utils.cc
- src/relay/backend/utils.h
- tests/cpp/relay/backend/aot/aot_lower_main_test.cc
- tests/python/relay/aot/test_pass_aot_lower_main.py
Tracking issue: https://github.com/apache/tvm/issues/12548
This is a pass refactored out of the AOTExecutorCodegen. Instead of combining all of the functionality of the AOTExecutorCodegen into a single monolithic pass, this pass only handles the lowering of the Relay main function into TIR. Tests for the pass are included.
cc @Mousius @alanmacd @areusch
> [AOT] Add AOTLowerMain pass to lower a Relay main into TIR

- python/tvm/relay/op/contrib/clml.py
- src/relay/backend/contrib/clml/codegen.cc
- src/runtime/contrib/clml/clml_runtime.cc
- tests/python/contrib/test_clml/infrastructure.py
- tests/python/contrib/test_clml/test_network.py
- tests/python/contrib/test_clml/test_ops.py
Added operators pooling (avg, max), binary operators (add, subtract, multiply, min, max) and concat.
Clip operator with min=0 and max=6 is remapped to relu6 to take advantage of CLML acceleration
without sub graphing this to fallback path.
Added new test cases for above listed operators and also end-to-end network test cases for Resnet50
& InceptionV3.
CLML support FP16 arithmetic mode which gives significant performance boost over FP32. This PR
enhances FP16 usage based on Operator datatype in relay graph.
Co-authored-by: Krishna Raju <quic_kvegiraj@quicinc.com>
Co-authored-by: Shwetank Singh <quic_shwesing@quicinc.com>
> [OpenCLML] More ops and network coverage

- tests/scripts/task_config_build_cpu.sh
The dependencies for these have moved into ci_cortexm Docker
image, so there is not much point in building them for ci_cpu as we
can't run the associated tests.
> [CI] Set USE_CMSISNN and USE_ETHOSU off in task_config_build_cpu.sh

- python/tvm/relay/testing/darknet.py
- tests/python/frontend/darknet/test_forward.py
- tests/python/frontend/tensorflow/test_forward.py
- tests/python/frontend/tflite/test_forward.py
PR https://github.com/apache/tvm/pull/12663 introduced
virtual environment in ci_lint docker image. At present, this
is not updated on docker hub. In the old docker image prior
to the above PR, pylint picked up a different version of python
that didn't catch the issues fixed in this commit.
cc @leandron @areusch
> Fixed pylint issues after moving to venv in ci_lint docker

- apps/microtvm/zephyr/template_project/app-overlay/nucleo_l4r5zi.overlay
Commit 1d32c400f ("Add project overlay to overwrite device tree configs") added overlay for setting 'clock-frequency' property of node 'rcc' to 120 MHz, however to effectively change the PLL frequency that drivers the core it's necessary also to overlay the attributes for the 'pll' node. This commit does that.
Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>
cc @alanmacd @mehrdadh
> [microTVM][Zephyr] Fix PLL freq. in overlay for nucleo_l4r5zi board

- src/arith/canonical_simplify.cc
- src/arith/const_fold.h
- src/arith/int_set.cc
- src/arith/iter_affine_map.cc
- src/arith/pattern_match.h
- src/arith/rewrite_simplify.cc
- src/tir/op/op.cc
Prior to this commit, the templated `TryConstFold` utility returned an undefined `PrimExpr` to represent a failure to perform constant folding.  This commit makes this explicit by returning `Optional<PrimExpr>` instead.
> [Arith][Refactor] Return Optional<PrimExpr> from TryConstFold

- include/tvm/tir/schedule/schedule.h
- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/analysis.h
- src/tir/schedule/analysis/analysis.cc
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/layout_transformation.cc
- src/tir/schedule/primitive/pad_einsum.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- src/tir/schedule/transform.cc
- src/tir/schedule/transform.h
- tests/python/unittest/test_tir_schedule_pad_einsum.py
Co-authored-by: Bohan Hou <32121147+spectrometerHBH@users.noreply.github.com>
This PR adds a schedule primitive `PadEinsum`. It is used for computation in Einsum pattern specifically, which cover most cases for tensorization. Different from general cases for padding in https://github.com/apache/tvm-rfcs/blob/main/rfcs/0077-layout-transform-padding.md, this primitive pads the output blocks and the input blocks at once, which eliminates the need to extra arithmetic analysis to provide the guarantee of program correctness.
cc @Hzfengsy @wrongtest-intellif @spectrometerHBH @Lunderberg
> [TIR, Schedule] Add schedule primitive PadEinsum

- docker/Dockerfile.ci_cortexm
- docker/Dockerfile.ci_riscv
- docker/install/ubuntu_download_csinn2_compute_lib.sh
- docker/install/ubuntu_download_xuantie_gcc_linux.sh
- docker/install/ubuntu_download_xuantie_gcc_newlib.sh
- docker/install/ubuntu_download_xuantie_qemu.sh
- docker/install/ubuntu_install_arduino.sh
- docker/install/ubuntu_install_core.sh
- docker/install/ubuntu_install_spike_sim.sh
- docker/install/ubuntu_install_zephyr.sh
See Discussion in https://discuss.tvm.apache.org/t/coordination-of-risc-v-integration-in-tvm/13133
1. Update `Dockerfile.ci_riscv` to download RISC-V toolchain and compile Spike simulator (including proxy kernel)
- Using SiFives GCC toolchain for Embedded targets (See below)
- Two variants of proxy kernel (`pk`, `pk64`) are build to support `rv32gc` as well as `rv64gc` targets
2. Introduce AotTestRunner to use spike in unit tests (currently `rv32gc` only)
3. Enable spike based AoTTestRunner for AoT/CRT related test cases
I have a followup ready based on this PR, which enable usage of spike for MicroTVM deployment (ProjectAPI Server).
- Why not use existing CSI-NN GCC toolchain?
That toolchain (`Xuantie-900-gcc-linux`) is mainly targeting 64-bit devices capable of running Linux. While it …
> [Docker][CI][RISC-V] Build riscv-isa-sim (spike) in ci_riscv Docker image to enable RISC-V unit testing

- python/tvm/driver/build_module.py
Hopefully fixes #12742, as the warning should only be printed when a user passes `target_host`, in the current case if the user passes `None` as `target_host` it'll be processed by `canon_target_map_and_host` which seems to be producing a `target_host` and thus triggering the warning despite the user doing nothing wrong.
> [Target] Print deprecation warning before canonicalisation in build module

- Jenkinsfile
- ci/jenkins/Build.groovy.j2
- ci/jenkins/Deploy.groovy.j2
- ci/jenkins/DockerBuild.groovy.j2
- ci/jenkins/Prepare.groovy.j2
- ci/jenkins/Test.groovy.j2
- ci/jenkins/macros.j2
- ci/scripts/retry.sh
This should mitigate failures like in
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4274/pipeline.
This also moves the `retry` function to a script now that we have
PR #12604.
> [ci] Add retries to docker push

- docker/Dockerfile.ci_arm
- docker/Dockerfile.ci_cortexm
- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_hexagon
- docker/Dockerfile.ci_i386
- docker/Dockerfile.ci_minimal
- docker/Dockerfile.ci_riscv
- docker/Dockerfile.ci_wasm
- docker/install/ubuntu_install_core.sh
This should fix some version drift in the current cmake versions in the
Docker containers (currently running all of 3.10, 3.16, 3.18, and 3.20)
> [ci][docker] Always build cmake from source

- python/tvm/script/parser.py
- tests/python/unittest/test_tvmscript_roundtrip.py
Hi there~ the change try fix an issue due to #12515.
Previously the logic for `-2147483648` is  `parse(-literal)` = `-parse(literal)`, and all integer literals are converted to i32 (either the literal value actually overflow or not). 
Since after #12515, parse `2147483648` results to an i64 typed integer rather than i32, `-2147483648` then becomes to one i64 integer too, which is not reasonable.
> [TVMScript] Fix parse minimal i32 literal for tir script

- CONTRIBUTORS.md
These couple names were linking to 404 pages, this PR updates them to
their current counterparts.
cc @junrushao @wrongtest-intellif @manupak
> [community] Fix outdated contributor GitHub usernames

- src/meta_schedule/tune_context.cc
Following up on #12796, this PR fixes the random state to be forked when a TuneContext is cloned.
> [MetaSchedule][Minor]Fix Random State Fork in TuneContext Clone Function

- ci/scripts/github_skipped_tests_comment.py
- docker/install/ubuntu_install_caffe.sh
Fix for import caffe and import requests failures
Recently virtual environments were introduced in the
docker images which was a great contribution to
localize errors: https://github.com/apache/tvm/pull/12663. In this fix, link to the caffe is
created inside this virtual env instead of adding it
to the system path of python. This fix also removes
importing request package where not needed.
Fixes #12663
cc @leandron @areusch @driazati
> Fix for import requests and import caffe failures

- src/runtime/hexagon/hexagon_buffer_manager.h
Each thread has its own thread local storage for workspace and pool objects.  But those perform allocations from a global HexagonBufferManager.  We found a case where the map was not getting updated during AllocWorkspace, which then later caused FreeWorkspace to fail.
Added a mutex to protect all access to the map.
cc:  @nverke @JosephTheOctonaut @adstraw @supersat 
cc @areusch @mehrdadh
> [Hexagon] [runtime] Protect access to global HexagonBufferManager map

- Jenkinsfile
- ci/jenkins/Deploy.groovy.j2
This was missing a repo checkout and failing as in
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4302/pipeline.
This also adds in the changes from #12719:
Fixes #12600. The original solution there doesn't actually fix the
issue, there would need to be some job queue that could make sure to
reject old pushes. Since this case is pretty rare, generally the next
commit that comes along and builds will fix everything up so we can
ignore failures that happen on `push`es.
> [ci] Fix docs push

- python/tvm/testing/utils.py
- tests/python/unittest/test_tir_ptx_cp_async.py
- tests/python/unittest/test_tir_ptx_ldmatrix.py
- tests/python/unittest/test_tir_ptx_mma.py
- tests/python/unittest/test_tir_ptx_mma_sp.py
- tests/python/unittest/test_tir_schedule_tensorize_ldmatrix_mma.py
Previously, individual unit tests would call `tvm.contrib.nvcc.get_target_compute_version` and return early.  This was repeated boilerplate in many tests, and incorrectly reported a test as `PASSED` if the required infrastructure wasn't present.
This commit introduces `tvm.testing.requires_cuda_compute_version`, a decorator that checks the CUDA compute version and applies `pytest.mark.skipif`.  If required infrastructure isn't present, a test will be reported as `SKIPPED`.
> [Testing] Add decorator tvm.testing.requires_cuda_compute_version

- src/tir/analysis/buffer_access_lca_detector.cc
- tests/python/unittest/test_tir_analysis_detect_buffer_access_lca.py
Prior to this PR, the LCA detector of buffers in TIR didn't take buffer memory scopes and GPU hierarchy into consideration. An consequent issue is that, when an intermediate buffer is in global memory, TIR's lowering passes don't necessarily allocated the intermediate buffer outside all `blockIdx`. As a result, the global intermediate buffer is allocated under a GPU thread block, which is illegal.
This PR fixes this issue by fixing the LCA detector, making it be aware of the buffer memory scopes and GPU hierarchy. With this fix, the global intermediate buffers are all allocated outside `blockIdx`.
cc @Hzfengsy @junrushao @junrushao1994 @spectrometerHBH @tqchen
> [BugFix][TIR] Fix Buffer LCA Detector

- include/tvm/script/printer/doc.h
- include/tvm/script/printer/traced_object_functor.h
- include/tvm/script/printer/var_table.h
- src/script/printer/doc.cc
- src/script/printer/ir_docsifier.cc
- src/script/printer/utils.h
- src/script/printer/var_table.cc
- tests/cpp/tvmscript_printer_irdocsifier_test.cc
- tests/cpp/tvmscript_printer_traced_object_functor_test.cc
This PR is split from https://github.com/apache/tvm/pull/12492, to make the necessary updates to the printer infra for future PRs of TIR printer.
cc @junrushao
> [TVMScript] Add more helper functions to the printer infra 

- src/tir/schedule/analysis/analysis.cc
- tests/python/unittest/test_meta_schedule_schedule_rule_cross_thread_reduction.py
This PR relaxes the conditions of Meta-Schedule schedule rule CrossThreadReduction. The rules are previously a bit over-strict, and some workloads with small reduction loop length are unable to be optimized by cross-thread reduction automatically. In this PR, we relax the rules so that such workloads can be optimized.
cc @junrushao
> [MetaSchedule] Relax conditions of rule Cross-Thread Reduction

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
I found the value should be "True"
> [Frontend][TFLite] fix detection_postprocess's non_max_suppression_attrs["force_suppress"]

- src/arith/int_set.cc
Follow-up from https://github.com/apache/tvm/pull/11970, to improve performance.  In the initial implementation, the `analyzer->int_set` would compute the intersection of all scope-based constraints when entering the scope, even if they weren't actually used.  This commit delays the call to `Intersect` until required, following the same behavior as `ConstIntBound`.
> [Arith][TIR] IntSetAnalyzer, delay intersection of IntSet until use

- python/tvm/contrib/hexagon/session.py
- tests/python/contrib/test_hexagon/test_parallel_hvx.py
- tests/python/contrib/test_hexagon/test_parallel_scalar.py
These tests show one way to attain speedup for hexagon workloads through parallelism. Additionally, they show the speedup attained by various different workloads in the best configuration found (outer loop split into 4). This will hopefully give users an understanding of what to do and what to expect when parallelizing hexagon workloads. 
Here are some tables of the runtimes on various workloads and HDKs. 
Operation | # Operations | Single Thread (ms) | Parallel (ms) | Speedup
-- | -- | -- | -- | --
vrmpy | 128 | 0.00112 | 0.002242 | 0.5x
vrmpy | 256 | 0.001797 | 0.002505 | 0.72x
vrmpy | 512 | 0.003095 | 0.00309 | 1.0x
vrmpy | 1024 | 0.005732 | 0.00422 | 1.36x
vrmpy | 2048 | 0.011118 | 0.006515 | 1.71x
vrmpy | 4096 | 0.140888 | 0.056102 | 2.51x
vrmpy | 8192 | 0.265677 | 0.100795 | 2.64x …
> [Hexagon] Create test examples to show parallelization

- python/tvm/tir/schedule/schedule.py
- tests/python/unittest/test_tir_schedule_set_axis_separator.py
Follow-up from https://github.com/apache/tvm/pull/11269, which allowed schedule arguments of the buffer to be transformed to be specified as a string, or as a `tir::Buffer`.  The string handling worked correctly, but the `tir::Buffer` object was handled incorrectly.  This commit corrects the handling of `tir::Buffer` arguments when scheduling, and adds a unit test to validate this behavior.
> [TIR][Bugfix] Correct handling of buffer argument when scheduling

- src/target/llvm/codegen_cpu.cc
File ```src/target/llvm/codegen_cpu.cc```: The member variable ```target_c_runtime_``` is uninitialized when used in function ```CodeGenCPU::Init```. So when calling the function ```CodeGenCPU::InitGlobalContext```, the value of ```target_c_runtime_``` may be ```true``` or ```false```,  this will lead to the bug as the title described.
> [BugFix][LLVM] Fix the bug that the generated systemlib cannot register ```__tvm_module_ctx``` symbol sometimes

- include/tvm/meta_schedule/database.h
- python/tvm/meta_schedule/database/database.py
- src/meta_schedule/database/database.cc
- tests/python/unittest/test_meta_schedule_database.py
This PR follows up #12520 and completes the functions in PyDatabase class and make sure we can override the `query_tuning_records`, `query_schedule` and `query_ir_module` function. Meanwhile, user can also use `query` function or use PyDatabase as a context.
> [MetaSchedule] PyDatabase Complete Function Reload Support

- src/runtime/graph_executor/graph_executor.cc
This is to avoid fuzziness when the num of outputs per node is greater than 1. (#12672)
Hi, please refer to https://github.com/apache/tvm/issues/12672 for more details. @masahi 
> [Fix] naming outputs of graph nodes by op_name:output_index

- ci/scripts/check_pr.py
- tests/python/ci/test_ci.py
This ensures that no users are tagged directly in PR titles or
descriptions, which lets us finally turn this on
https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/
> [ci] Lint PR title/body for @ tags

- ci/scripts/check_pr.py
- tests/python/ci/test_ci.py
This reverts commit ecd003c742da85d4945c7d02e9301e07ad413136.
The check needs to ignore @ s in some cases, such as within code blocks.
> [skip ci] Revert "[ci] Lint PR title/body for @ tags (#12840)"

- include/tvm/tir/builtin.h
- include/tvm/tir/transform.h
- src/driver/driver_api.cc
- src/runtime/hexagon/hexagon_device_api.cc
- src/tir/op/builtin.cc
- src/tir/transforms/lower_async_dma.cc
- src/tir/transforms/lower_tvm_builtin.cc
- tests/python/contrib/test_hexagon/test_software_pipeline_async.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
- tests/python/unittest/test_tir_transform_inject_software_pipeline.py
Creates a 2-stage pipeline (DMA, compute) by lowering Async TIR primitives (see [RFC](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0077-async-pipeline.md)) with memory copy semantics to builtin functions for DMA `Copy` and `Wait`.  These builtins can then be lowered through the device API, with example lowering on Hexagon to the `HexagonUserDMA` class. The example test case contained in this PR creates a 2 stage pipeline which lowers to the following TIR which is built and run on Hexagon.
> [Hexagon] 2-Stage Pipeline; Lower Async TIR primitives to Hexagon User DMA

- docker/install/ubuntu_install_boost.sh
- docker/install/ubuntu_install_caffe.sh
- docker/install/ubuntu_install_python.sh
This PR fixes some of the ongoing problems we're having building docker images after merging #12663 . It links `caffe` into the venv (this was done before, but is now done via the env var) and ensures that cmake will find the venv Python by ensuring that the `python3.7` command resolves to the venv Python. Finally, it builds boost outside the venv so that development files can be found.
@leandron @driazati
> Fix caffe, boost install in Python venvs by creating python3.X link
