include/tvm/meta_schedule/schedule_rule.h, python/tvm/meta_schedule/schedule_rule/__init__.py, python/tvm/meta_schedule/schedule_rule/multi_level_tiling.py, src/meta_schedule/schedule_rule/multi_level_tiling.cc, src/meta_schedule/schedule_rule/multi_level_tiling.h, src/meta_schedule/schedule_rule/multi_level_tiling_wide_vector.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt.py
In `MultiLevelTiling`, the size of the loop that is going to be vectorized is completely random. This is not a good fit for backends with wide vector registers such as Hexagon.  
This PR introduces an extension of `MultiLevelTiling`, to effectively utilize wide vectors. The loop over the innermost spatial axis of the output buffer is always vectorized with the maximum vector length. This makes it possible to auto schedule for Hexagon successfully. 
cc @vinx13 @junrushao
=> [Metaschedule] MultiLevelTiling for wide vector architectures

src/runtime/cuda/cuda_device_api.cc, src/runtime/profiling.cc
In the switch from gpu to cuda naming, the cuda timer was passed over. Renaming it to "profiling.timer.cuda" so it is correctly picked up by the timing mechanisms.
@AndrewZhaoLuo
=> [FIX,PROFILING] Fix gpu timer name and lookup

include/tvm/support/with.h
Previously, `tvm::With` had the default compiler-provided move constructors.  If these were used (e.g. by storing a `With` into a vector), the `ExitWithScope` would be called multiple times.  ~~This commit explicitly removes the copy constructor/assignment, and explicitly implements move constructor/assignment.~~  This commit explicitly disables both copy and move constructors and assignments for `tvm::With` to avoid this failure mode.
=> [Utils] Disable automatic move constructor for tvm::With

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Hi, tvm：
When I use tvm pytorch frontend  to load  model `vovnet19`. I get a error:    `NotImplementedError: The following operators are not implemented: ['aten::relu6_']`.
I tried adding an implementation of this operator,and then i success load my model and run success.
Hope to get your advice and review. Thanks.
=> [frontend][torch] Support aten::relu6 operator

python/tvm/te/hybrid/parser.py
This is a follow-up to #12769 The check for sys version of python 3.9 is not correct.
Fixed #12814
=> [Hybrid] Fix sys version check

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Add a new test case for torch `aten::fill_` operator implementation.
This new test is testing a case of usage of a sequence of operators `aten::div()` and `aten::fill_() `that was causing a failure during the deployment of Mask R-CNN model (torchvision 0.13.0 version of the model).
Issue: #12844
=> [frontend][pytorch] Add a new test case for torch aten::fill_ operator implementation

python/tvm/autotvm/task/space.py, python/tvm/autotvm/tuner/ga_tuner.py, python/tvm/autotvm/tuner/index_based_tuner.py, python/tvm/autotvm/tuner/model_based_tuner.py, python/tvm/autotvm/tuner/sa_model_optimizer.py, python/tvm/autotvm/tuner/tuner.py, python/tvm/autotvm/utils.py, python/tvm/topi/adreno/conv2d_nchw.py, python/tvm/topi/adreno/conv2d_nhwc.py, python/tvm/topi/adreno/conv2d_winograd_common.py, python/tvm/topi/adreno/depthwise_conv2d_nchw.py, python/tvm/topi/adreno/depthwise_conv2d_nhwc.py, tests/python/topi/python/test_topi_conv2d_hwnc_tensorcore.py, tests/python/unittest/test_autotvm_ga_tuner.py, tests/python/unittest/test_autotvm_index_tuner.py, tests/python/unittest/test_autotvm_space.py
Here is a small example to show the workflow and the difference:
**Pre-requisites**
```
candidates = [[16, 64], [32, 32], [64, 16]]
filter = lambda v: v.size[0] != 16
multi_filter = lambda e: (e["tile_x"].size[0] + e["tile_y"].size[0]) <= 64
```
**Case 1 - without filtering**
```
cfg.define_split("tile_x", x, num_outputs=2, policy="candidate", candidate=candidates)
cfg.define_split("tile_y", y, num_outputs=2, policy="candidate", candidate=candidates)
```
> [('tile_x', [16, 64]), ('tile_y', [16, 64])],None,0
> [('tile_x', [32, 32]), ('tile_y', [16, 64])],None,1
> [('tile_x', [64, 16]), ('tile_y', [16, 64])],None,2
> [('tile_x', [16, 64]), ('tile_y', [32, 32])],None,3
> [('tile_x', [32, 32]), ('tile_y', [32, 32])],None,4
> [('tile_x', [64, 16]), ('tile_y', [32, 32])],None,5
> [('tile_x', …
=> [AutoTVM] Introducing multi_filter into ConfigSpace autotvm

python/tvm/topi/generic/conv2d.py, tests/python/relay/test_op_level2.py
The logic in https://github.com/apache/tvm/blob/52d6b59a39f503fe382b4d7cbac4b02f9e44aae0/python/tvm/topi/generic/conv2d.py#L480-L499 is supposed to legalize the input dtype to be able to apply target-specific intrinsics that only support one of int8 or uint8. For example, the x86 VNNI instruction only supports uint8 activation. 
But the logic is incorrect (two cases are flipped) and leads to incorrect result in the following case:
* The input activation is int8, and we want to use the x86 VNNI intrinsic which only supports uint8 activations.
* The input activation is uint8, and we want to use the ARM `sdot` intrinsic which only supports int8 activations.
The first case also applies to the Hexagon `vrmpy` intrinsic. I found this bug while testing `vrmpy` conv2d on int8 input.
To test this …
=> [TOPI] Fix dtype legalize logic for CPU dot product instruction

src/relay/backend/te_compiler_cache.cc
Because of recent updates `TransformLayout` now has 4 attrs. https://github.com/apache/tvm/blob/main/src/tir/schedule/primitive/layout_transformation.cc#L1348
cc @junrushao
=> [Relay] Fix handling of TransfromLayout in TE compiler cache

include/tvm/topi/nn/layer_norm.h, include/tvm/topi/reduction.h, python/tvm/topi/nn/__init__.py, python/tvm/topi/nn/layer_norm.py, python/tvm/topi/testing/__init__.py, python/tvm/topi/testing/layer_norm_python.py, src/tir/schedule/primitive/reduction.cc, src/topi/nn.cc, tests/python/topi/python/test_topi_layer_norm.py, tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
This PR added a tuple-sum based implementation of layer norm. It performs one-pass reduction to compute mean and variance at the same time.
Reducer pattern is also added to allow `LowerCrossThreadReduction` to handle this case.
On CUDA, it will generate two kernels: one for reduction and one for elemwise operations. Because of some limitation of `compute_at` currently we are not able to fuse them into one kernel. 
cc @MasterJH5574 @junrushao @AndrewZhaoLuo
=> [TOPI] Add layer norm operator

python/tvm/tir/tensor_intrin/cuda.py
There are some corner cases `get_wmma_fragment_index` returns wrong result when the size of shared memory is large. In practice, such case usually won't happen because the size of the shared memory is limited.
cc @spectrometerHBH
=> [TIR] Fix wmma index in CUDA tensor intrins

docker/Dockerfile.ci_cortexm
In recent test rounds with updated images, it seems Zephyr-SDK binaries such as various QEMU related files are missing from $PATH, which makes Zephyr tests to fail with, e.g. "qemu-system-i386: command not found".
This PR adds those missing binaries to $PATH.
cc @areusch @gromero @mehrdadh @driazati for reviews
=> [CI] Add Zephyr-SDK binaries to PATH env. in ci_cortexm

src/tir/schedule/primitive/cache_read_write.cc, src/tir/schedule/state.cc, tests/python/unittest/test_tir_schedule_cache_read_write.py
Currently, cache read/write requires to be stage pipeline, but it is unnecessary theoretically. 
When there is WAR, the target of cache_read could be specified by the consumer_blocks parameter. This also allows cache_write to handle the write after read of the same buffer.
cc @Hzfengsy @junrushao1994 @wrongtest-intellif
=> [TIR][Schedule] Relax cache read/write's restriction and fix unexpected behavior

include/tvm/ir/op.h
Previously, the `get()` method wasn't defined, and returned a `RelayExprNode` instead of a `Op::ContainerType*`.
=> [IR] Use TVM_DEFINE_OBJECT_REF_METHODS macro for Op

src/tir/analysis/buffer_access_lca_detector.cc, tests/python/unittest/test_tir_transform_plan_update_buffer_allocation_location.py
The pass `PlanAndUpdateBufferAllocationLocation` seems to have problem when the buffer accessed indices take a loop carried dependency. As an example,
```python
@T.prim_func
def test(A: T.Buffer[(8, 8), "int32"], B: T.Buffer[(8, 8), "int32"]):
C = T.alloc_buffer([8, 8], "int32")
for i in range(8):
for j in range(8):
with T.block("b0"):
vi = T.axis.spatial(8, i)
vj = T.axis.spatial(8, j)
C[vi, vj] = A[vi, vj] + vi
for j in range(8):
with T.block("b1"):
vi = T.axis.opaque(8, i)
vj = T.axis.spatial(8, j)
B[vi, vj] = C[vi, vj] + T.if_then_else(vi > 0, C[vi - 1, vj], vi, dtype="int32")
```
The block `b1`'s read access to intermediate buffer `C` on iteration `i`, depends `b0` write of `C` on both `i` and `i-1`, thus we should not put allocation of `C` under loop `i`, which is the LCA position …
=> [TIR] Fix plan buffer allocation location for loop carried dependencies

python/tvm/meta_schedule/cost_model/__init__.py, python/tvm/meta_schedule/cost_model/xgb_model.py, tests/python/unittest/test_meta_schedule_cost_model.py
This PR intends to update the custom callback function of xgboost in meta schedule.
This change is tested against xgboost==(1.2.0, 1.5.2 & 1.6.0) to ensure backwards compatibility on `tests/python/unittest/test_meta_schedule_cost_model.py`. 
This is related to the second action item in #12009.
cc: @zxybazh @junrushao1994
=> [Meta Schedule][XGBoost] Update the custom callback function of xgboost in meta schedule

python/tvm/meta_schedule/testing/relay_workload.py, python/tvm/meta_schedule/utils.py, src/meta_schedule/task_scheduler/gradient_based.cc, src/meta_schedule/utils.h, tests/python/unittest/test_meta_schedule_tune_relay.py
Previously the tuning process would generate significant amount of logging to screen, which would be troublesome for jupyter notebook usage. This PR proposes several changes to fit in the usage on jupyter:
- The output would [automatically clean up](http://ipython.org/ipython-doc/dev/api/generated/IPython.display.html#IPython.display.clear_output) each time a new tuning result table is generated, i.e., in the beginning of tuning after initializing all tasks, and after each task join.
- Slim version of the table is available when ipython environment is used so that the table can fit in output area of the notebook.
- Sample slim table:
```
ID |                    Name |      FLOP | Weight |   GFLOPS | Latency (us) | Wtd. Latency | Trials | Terminated …
```
=> [MetaSchedule][UX] User Interface for Jupyter Notebook

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Hi, tvm:
I add a new torch op `aten::tensor_split`.   This op is found when I load the `yolov5s` model.
Please help to review, thanks.
=> [frontend][pytorch]Support aten::Tensor_split operator

python/tvm/script/tir/special_stmt.py, tests/python/unittest/test_tir_lower_match_buffer.py, tests/python/unittest/test_tvmscript_syntax_sugar.py
When using `T.match_buffer` to define a view into another buffer, default shape and dtype parameters can be inferred.
=> [TVMScript] Infer T.match_buffer parameters for region

python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/gemm.py
Currently, dense DSP schedule has a hard coded condition where it forces the schedule to not to use the SIMD instructions. Our investigations on using this schedule with anomaly detection model (which has 5 different dense task) shows that this condition is too restricted. This PR changes these condition to apply when both N, M size are less than 2.
This will improve the performance of AD model by 33%. 
cc @areusch
=> [microTVM][ARM] Improve dense DSP micro kernel

include/tvm/tir/index_map.h, src/tir/ir/index_map.cc
The two implementations were largely identical, and had implementations that drifted apart, resulting in bugs such as https://github.com/apache/tvm/issues/12852.  This commit removes this duplication by writing `Inverse` in terms of `NonSurjectiveInverse`. The merged version of `NonSurjectiveInverse` contains bugfix https://github.com/apache/tvm/pull/11841, that were previously present only in `Inverse`.
=> [TIR] Refactor IndexMap::Inverse in terms of NonSurjectiveInverse

src/relay/backend/te_compiler_cache.cc
#10516 used the Relay parameter name when lowering to TE. However, this creates an issue when the parameter name is empty. This is legal in Relay, but results in errors during code generation. For example, this is the generated CUDA kernel for bias add:
```
extern "C" __global__ void __launch_bounds__(1024) fused_raf_op_tvm_add_kernel0(
float* __restrict__ T_add,
float* __restrict__ , /* Name is missing and it results in compile errors. */
float* __restrict__ _1) {
T_add[((((int)blockIdx.x) * 1024) + ((int)threadIdx.x))] = ([((((int)blockIdx.x) * 1024) + ((int)threadIdx.x))] + _1[((((((int)blockIdx.x) * 16) + (((int)threadIdx.x) >> 6)) % 54) / 9)]);
}
```
This PR adds "placeholder" back as a default to make sure no empty string will be passed when lowering to TE.
cc @Lunderberg @tkonolige
=> [Relay][TE] Add default param name if needed

src/runtime/builtin_fp16.cc, src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h, tests/python/unittest/test_target_codegen_llvm.py, tests/python/unittest/test_target_codegen_x86.py
For conversions between `_Float16` and `float`, LLVM uses runtime functions `__extendhfsf2` and `__truncsfhf2`.  On X86 up until version 14, LLVM used `uint16_t` for representing `_Float16`. Starting with LLVM 15, half- precision values can be passed in XMM registers (i.e. as floating-point). This happens when the compilation target has SSE2 enabled (either directly, or by enabling a feature that implies SSE2).
Because the names of the conversion functions remain unchanged, it is impossible for TVM to provide them in the runtime, and have them work in both cases. To solve this issue, emit these functions directly into the target module after detecting whether or not to use floating-point ABI. To allow the linker to remove potential duplicates (or if they are unused), they are weak and …
=> [LLVM] Emit fp16/fp32 builtins directly into target module

include/tvm/tir/transform.h, python/tvm/tir/transform/transform.py, src/driver/driver_api.cc, src/tir/transforms/make_packed_api.cc, tests/python/unittest/test_tir_transform_make_packed_api.py
Other than a single unit test, there are no usages of this parameter in TVM, and it significantly complicates the logic of `MakePackedAPI`. Similar functionality can be had by using `MakeUnpackedAPI` instead.
=> [TIR][Transform] Remove num_unpacked_args from MakePackedAPI

Jenkinsfile, ci/jenkins/Jenkinsfile.j2, tests/python/frontend/onnx/test_forward.py
RoiAlign-16 introduces `coordinate_transformation_mode`, which should be set to 'output_half_pixel' to omit the pixel shift for the input (for a backward-compatible behavior). This PR should fix the failure in https://ci.tlcpack.ai/job/docker-images-ci/job/docker-image-run-tests/231/testReport/junit/cython.tests.python.frontend.onnx/test_forward/Test___frontend__GPU_3_of_6___test_roi_align_cuda_/ 
Moved #12869 to an in-repo branch
=> [ONNX] Fix test_roi_align failure

include/tvm/runtime/container/array.h, src/te/schedule/schedule_lang.cc
Prior to this commit, the following code would compile and run without error.  This occurs because the typed `Array<T>::insert` calls the untyped `ArrayNode::InitRange`, with no type-checking done before the call.
```c++
Var x("x");
Var y("y");
Array<Var> var_arr{x, y};
Array<PrimExpr> expr_arr{x + 1, y + 2};
// Erroneously inserts static-type PrimExpr, runtime-type Add, even
// though neither PrimExpr is a type of Var.
var_arr.insert(var_arr.begin(), expr_arr.begin(), expr_arr.end());
```
After this commit, a `static_assert` in `Array<T>::insert` and in `Array<T>::Array(IterType,IterTYpe)` restricts the iterators, such that they must dereference to `T`, `Optional<T>`, a subclass of `T`, or `Optional<U>` where `U` is a subclass of `T`.
The public method `ArrayNode::SetItem` exposes a …
=> [Runtime][Bugfix] Added type-checking for Array::insert

Jenkinsfile, ci/jenkins/Deploy.groovy.j2
We rely on some utilities scripts in the deploy steps so they also need
a git checkout.
Fixes #12878
=> [ci] Initialize git during deploys

python/tvm/micro/build.py, python/tvm/micro/session.py, python/tvm/micro/testing/evaluation.py
This PR adds the option to save a generated micro project at a custom path, and to open a saved project and start communicating with it (instead of generating a new one) for debugging.
cc @alanmacd @areusch @gromero @guberti @mehrdadh
=> [microTVM] add the option to open a saved micro project for debugging

tests/python/unittest/test_slice_tir.py
Introduces (disabled) unit tests that can gradually be enabled as we make progress on primfunc slicing (a.k.a. "functionalization").
=> [TIR] add unit-tests for upcoming primfunc-slicing

python/tvm/relay/backend/contrib/ethosu/tir/utils.py, python/tvm/relay/backend/contrib/ethosu/tir_to_cs_translator.py, python/tvm/tir/transform/transform.py, src/tir/transforms/make_unpacked_api.cc
This mimics the behavior in `MakePackedAPI`, and is assumed to be the case for some codegens.
=> [TIR][Transform] Clear buffer_map during MakeUnpackedAPI

src/tir/usmp/analysis/extract_buffer_info.cc, src/tir/usmp/transform/convert_pool_allocations_to_offsets.cc, tests/python/unittest/test_tir_usmp_transform_convert_pool_allocations_to_offsets.py
This PR fixes cases where a USMP buffer is used with tensorization intrinsics. In these cases, it is common to
write schedules that pass Buffers to extern functions using `access_ptr()`. When transforming tir.allocate into
offsets into global_workspace buffers, USMP inserts a let expression that replaces the old Buffer var with a new
var named "<buffer_var>_let." It then attempts to replace all references to the old var with the new one. When
a Buffer was passed via `access_ptr`, USMP would would previously ignore such instances, producing this error
later on in codegen (dense being the name of the Buffer in use):
```
"src/target/source/codegen_source_base.cc", line 67
Check failed: (it != var_idmap_.end()) is false: Find undefined
Variable dense
```
This patch fixes the problem by …
=> [usmp] Also remap VarNode to USMP-allocated buffer

python/tvm/relay/op/contrib/ethosn.py, tests/python/contrib/test_ethosn/test_networks.py, tests/python/contrib/test_ethosn/test_split.py, tests/python/contrib/test_ethosn/test_topologies.py
After the upgrade of the driver stack to 22.08 (3.1.0), this commit removes support for the 22.05 (3.0.1) version.
cc @leandron @ashutosh-arm
=> [ETHOSN] Remove support for 22.05 version of the driver stack

src/meta_schedule/postproc/rewrite_layout.cc, tests/python/unittest/test_meta_schedule_postproc_rewrite_layout.py
Adds a regression test for using the `layout_rewrite` post-proc on a buffer with an extent of one in at least one dimension, issue https://github.com/apache/tvm/issues/12852.  This bug was resolved as part of the refactor in https://github.com/apache/tvm/pull/12904, but didn't have a regression test at that point.
CC @vinx13 @junrushao @zxybazh
=> [TIR][MetaSchedule] Add regression test for layout_rewrite extent=1

python/tvm/relay/op/strategy/arm_cpu.py, python/tvm/topi/arm_cpu/conv2d_alter_op.py, python/tvm/topi/arm_cpu/mprofile/dsp/depthwise_conv2d.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/common.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/multi_channel_convolve.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/quad_channel_convolve.py, tests/python/relay/strategy/arm_cpu/test_depthwise_conv2d.py
This pull request removes a number of restrictions on the usage of the `depthwise_conv2d` schedule for microTVM. It:
- Adds support for the `int16` input data type
- Adds support for arbitrarily-sized (including asymmetric) kernels
- Allows the `int16` version to run on Cortex-M0 and M3 (which do not have SIMD instructions)
- This is accomplished without performance loss
- Adds unit tests for these features
It also removes use of the `SMLAD` instruction, which cannot improve performance on `NHWC` layouts (discussion about why in the comments below). This results in a slight performance boost for depthwise convolutions where `kernel_width * kernel_height` is odd, and no change otherwise. It also contains some readability improvements.
Known issue: [my call to `topi.reshape` in …
=> [microTVM] Generalize depthwise_conv2d schedule

CMakeLists.txt, docs/install/from_source.rst
TVM has recently switched to C++17. CUDA support with C++17 requires CMake past version 3.18, according to @vinx13. However, the current CMake version check in `CMakeLists.txt` is not checking for a sufficiently high CMake version; this PR updates it.
Bug that prompted this: When building with CMake version 3.16 I had the following error: `CUDA_STANDARD is set to invalid value '17'`. Upgrading to the latest CMake (3.24) fixed it.
=> [Bugfix][CMake] Update the minimum CMake version to 3.18

python/tvm/relay/op/contrib/ethosn.py, src/relay/backend/contrib/ethosn/codegen.cc, src/relay/backend/contrib/ethosn/codegen_ethosn.h, src/relay/backend/contrib/ethosn/convert_equivalent.cc, src/relay/backend/contrib/ethosn/ethosn_api.cc, src/relay/backend/contrib/ethosn/ethosn_api.h, tests/python/contrib/test_ethosn/test_addition.py, tests/python/contrib/test_ethosn/test_convert_equivalents.py, tests/python/contrib/test_ethosn/test_multiply.py, tests/python/contrib/test_ethosn/test_networks.py
Add/mul operations that correspond to identity operations can be converted to a simple reinterpret quantize operation. This conversion takes place in the convert equivalents pass similar to the depthwise counter-part.
In addtion, an issue was noticed that would cause unsupported operations to raise an error rather than not being offloaded. This has been fixed by allowing the conversion to return Null when the conversion is not supported.
cc @ashutosh-arm @leandron
=> [ETHOSN] Support conversion of add/mul to requantize where possible

src/relay/op/tensor/transform.cc, tests/python/relay/test_pass_convert_op_layout.py
Previously function for converting of layout for split did properly handle blocked layout
cc @chengven027-intellif @masahi
=> [Relay] Extend split for blocked ConvertLayout pass

python/tvm/tir/schedule/schedule.py, tests/python/unittest/test_tir_schedule_transform_layout.py
Previously, a python int/float would be converted to a TIR int32/float32 in `tvm.runtime.convert`.  These types may not match the buffer's type, even though it is the closest Python representation of the buffer's type.  Therefore, the `pad_value` should be preferentially converted to the matching type of the buffer.
=> [TIR] Use buffer's dtype when converting pad_value to TIR

include/tvm/runtime/vm/vm.h, python/tvm/runtime/vm.py, src/runtime/vm/vm.cc, tests/python/relay/test_vm.py
This is a draft of implementation of 'set_output_zero_copy' method on VirtualMachine side.
Brief description of approach.
1. There is python API function 'set_output' which save external outputs in VM outputs_ field (map) for specified func name. It looks like 'set_input' method.
2. During 'invoke' outputs_ are saved in register_file. For this the register indices of output tensors are found from code_ field. I observed in tests for different models that AllocTensor and AllocADT ops are used for result tensors. Let's consider these two cases: result index is destination for AllocTensor op or AllocADT op. At the first case instead of construction new NDArray the outside output tensor is used. At the second one the fields of AllocADT are analyzed and register indices are extracted. During …
=> [Virtual Machine] Implementation of 'set_output_zero_copy'

src/tir/transforms/inject_software_pipeline.cc, tests/python/unittest/test_tir_transform_inject_software_pipeline.py
Preserve For loop annotations except the software pipeline annotations. cc @masahi @vinx13
=> [TIR] Preserve loop annotations in inject_software_pipeline pass

python/tvm/meta_schedule/testing/torchbench/__init__.py, python/tvm/meta_schedule/testing/torchbench/run.py, python/tvm/meta_schedule/testing/torchbench/utils.py
This PR adds a script to tune and benchmark TorchBench models, using torchdynamo and the pytorch importer in TVM.
=> [MetaSchedule] Add Script for TorchBench Model Tuning & Benchmarking

src/target/llvm/intrin_rule_hexagon.cc, src/tir/op/op.cc, tests/python/contrib/test_hexagon/test_sigmoid.py
HVX version of QHL(Qualcomm Hexagon Library) sigmoid generates incorrect output if the input falls outside of [-8.0, 8.0]. To fix this, we need to clip the input to sigmoid in the range between >-8.0 and <8.0.
=> [HEXAGON][QHL] Clippling the inputs of HVX version of QHL Sigmoid operation

src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc, src/tir/schedule/primitive/cache_read_write.cc, tests/python/unittest/test_tir_schedule_reindex.py
The existence of unused block iters make it difficult for block layout transformation. Previous it relies the flag `simplify_trivial_iter=true` in affine analysis, which is unsafe because simplifying trivial iterators during scheduling stage lose the information of iterators.
cc @spectrometerHBH @junrushao @Hzfengsy
=> [TIR] Remove unused iters from the result of reindex

python/tvm/meta_schedule/cost_model/xgb_model.py, tests/python/unittest/test_meta_schedule_cost_model.py
Previous upgrade introduced a import of xgboost in meta_schedule, removed in current version by using a function to return the call back class.
We've recently introduced a XGBoost Model upgrade to support new xgboost version of callback class in https://github.com/apache/tvm/pull/12141. However, in this PR it uses a function called `optional_xgboost_callback` that works to avoid compatibility issue (xgboost 1.5.2 v.s. 1.6.0). In this specific function, it tries to import the newly introduced xgboost callback class and create a new class using it as base class. This actually imported xgboost when meta_schedule is imported, which is not ideal because xgboost is not a dependency of tvm and meta_schedule, it should only be required when xgboost cost model is employed. This PR fixes the …
=> [MetaSchedule] Fix XGBoost Import Issue

src/target/llvm/codegen_llvm.cc
The CHECK_NE can cause compilation issues in some cases.
=> [LLVM] Change CHECK_NE(x, nullptr) to CHECK(x != nullptr), NFC

docs/contribute/committer_guide.rst
This PR adds an elaboration of hat and independence principle for project participation. This is a principle that by default applies to all apache projects.
See also other reference materials
- http://theapacheway.com/hats/
- https://community.apache.org/projectIndependence.html
=> [DOCS][COMMUNITY] Elaborate Independence Principle for Project Participation

python/tvm/relay/op/op_attrs.py
It is noticed that many Attrs declared in this [file](https://github.com/apache/tvm/blob/main/include/tvm/relay/attrs/transform.h) are not registered [on Python side](https://github.com/apache/tvm/blob/main/python/tvm/relay/op/op_attrs.py). This will cause these Attrs having type `Object` when running with Python.
Therefore, this PR registers the missing operators in `op_attrs.py`, to make them have right types during runtime.
cc @spectrometerHBH @vinx13
=> [Relay][Op] Register some forgotten op in Python side

python/tvm/meta_schedule/default_config.py, python/tvm/meta_schedule/tune.py, tests/python/contrib/test_hexagon/test_meta_schedule.py
Building on https://github.com/apache/tvm/pull/12845, this PR adds an initial support for template-free auto tuning on Hexagon.
Test cases demonstrate:
* Auto-scheduler style, template free tuning for fp16 conv2d in NHWC layout.
* `vrmpy` auto tensorization for TE int8 `dense` (weight pre-packed), achieving 440 GOPs on SD888. 
Known issues:
* Due to the issue explained in https://github.com/apache/tvm/pull/12706, `link-params = True`, required by Hexagon, causes identical workloads to be tuned as distinct tasks. So e2d tuning is very slow without the changes from 12706.
* Tuning `nn.dense` essentially requires metaschedule `RewriteLayout` postproc: I found that the memory access pattern of `nn.dense`, `C[i, j] += A[i, k] * B[j, k]`, where the `j` axis is vectorized, performs terribly on …
=> [Hexagon] Support template-free meta schedule tuning

src/relay/backend/contrib/cmsisnn/scalar_to_tensor_constant.cc, src/relay/ir/dataflow_matcher.cc, tests/python/relay/test_dataflow_pattern.py, tests/python/relay/test_pass_merge_composite.py
This commit adds a duplicate check for make_input in PatternGrouper::CreateGroup, fixes a bug where the partitioned function created by CreateGroup would have an unused redundant variable when multiple operators in the partition share an input.
=> [BugFix][Pattern] Fixed a bug in PatternGrouper

python/tvm/relay/op/contrib/cmsisnn.py, src/relay/backend/contrib/cmsisnn/buffer_size.cc, src/relay/backend/contrib/cmsisnn/buffer_size.h, src/relay/backend/contrib/cmsisnn/relay_to_tir.cc, src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc, tests/cpp/relay/backend/contrib/cmsisnn/buffer_size_test.cc, tests/python/contrib/test_cmsisnn/test_conv2d.py, tests/python/contrib/test_cmsisnn/utils.py
Support for int16 Conv2d via CMSIS-NN
-Pattern matching and RelayToTIR introduce int16 support
-Added new context buffer size APIs for int16 Conv2d
-Added int16 variants to integration and buffer size tests
cc @lhutton1 @Mousius @leandron @grant-arm
=> [CMSIS-NN] Support for int16 conv2d

src/runtime/hexagon/hexagon_device_api.cc, src/runtime/hexagon/hexagon_user_dma.cc, src/runtime/hexagon/hexagon_user_dma.h, src/runtime/hexagon/ring_buffer.h, tests/cpp-runtime/hexagon/hexagon_user_dma_tests.cc, tests/cpp-runtime/hexagon/ring_buffer_tests.cc, tests/python/contrib/test_hexagon/test_software_pipeline_async.py
Add `HexagonUserDMA` support for multiple virtual queues which enables Async DMA for both `cache_read` and `cache_write` while maintaining a single descriptor chain to maintain overall FIFO ordering between virtual queues.  Tested with runtime unit tests and at the python level for a simple operator.
=> [Hexagon] 3-stage pipeline; multi queue async DMA for cache read / write

apps/microtvm/arduino/template_project/Makefile.template, apps/microtvm/arduino/template_project/microtvm_api_server.py, apps/microtvm/arduino/template_project/tests/test_arduino_microtvm_api_server.py, apps/microtvm/reference-vm/base-box/base_box_test.sh, apps/microtvm/zephyr/template_project/microtvm_api_server.py, cmake/modules/Arduino.cmake, gallery/how_to/work_with_microtvm/micro_aot.py, gallery/how_to/work_with_microtvm/micro_autotune.py, gallery/how_to/work_with_microtvm/micro_reference_vm.py, gallery/how_to/work_with_microtvm/micro_tflite.py, gallery/how_to/work_with_microtvm/micro_train.py, python/tvm/micro/project_api/server.py, python/tvm/micro/testing/evaluation.py, tests/lint/check_file_type.py, tests/micro/arduino/README.md, tests/micro/arduino/test_arduino_rpc_server.py, tests/micro/arduino/test_utils.py, tests/micro/common/test_tvmc.py, tests/micro/project_api/test_arduino_microtvm_api_server.py, tests/micro/project_api/test_project_api.py, tests/micro/zephyr/README.md, tests/micro/zephyr/test_utils.py, tests/micro/zephyr/test_zephyr.py, tests/micro/zephyr/test_zephyr_aot_exec.py, tests/python/unittest/test_micro_project_api.py, tests/scripts/task_python_microtvm.sh
This PR:
- Refactors common project options to a single place for template projects
- Adds a feature to update project options for customization
- Adds a Makefile for Arduino project to make the build/flash process more standalone
- Adds CMSIS support to Arduino template project
- Refactors `zephyr_board` and `arduino_board` to `board`
=> [microTVM] Use default Project Options in template projects and add Makefile for Arduino template project

src/runtime/hexagon/rpc/simulator/session.cc
They flood the standard error, and are only useful when debugging protocol issues. Remove them, they are easy to add back if needed.
=> [Hexagon] Don't print simulator protocol messages

src/target/source/codegen_opencl.cc, src/target/source/codegen_opencl.h
Not all OpenCL compiers happy with inline sampler definition.
Specification: "The image read functions take a sampler argument. The sampler can be passed as an argument to the kernel using clSetKernelArg, or can be declared in the outermost scope of kernel functions, or it can be a constant variable of type sampler_t declared in the program source."
=> [CODEGEN][OPENCL] Sampler definition should be at outermost scope

include/tvm/tir/index_map.h, python/tvm/tir/function.py, src/tir/ir/index_map.cc, tests/python/unittest/test_index_map.py
I've hit a weird use case where I want to manually transform `runtime::NDArray` (attached to `AllocateConst` node) according to the index map used in `transform_layout`. This is needed to support `AllocateConst` node in Metaschedule `RewriteLayout` postproc.
I can define it as a free function in the file where it is actually used. Having it available as part of the `IndexMap` interface makes it convenient to expose this to python and unit-test it. Let me know if this is a reasonable API addition. 
cc @vinx13 @Lunderberg @junrushao
=> [TIR] Use IndexMap to transform NDArray

python/tvm/contrib/hexagon/session.py, src/runtime/rpc/rpc_endpoint.cc, src/runtime/rpc/rpc_endpoint.h, src/runtime/rpc/rpc_module.cc, src/runtime/rpc/rpc_session.h, tests/scripts/task_python_hexagon.sh
This PR adds a shutdown packed function to RPC module so we can force close the RPC session from python side.
cc @areusch @Lunderberg
=> [Hexagon] Fix RPC session close by adding shutdown PackedFunc

src/tir/ir/stmt.cc, src/tir/schedule/analysis.h, src/tir/schedule/analysis/analysis.cc, src/tir/schedule/ir_comparator.cc, src/tir/schedule/primitive/cache_read_write.cc, src/tir/schedule/primitive/layout_transformation.cc, src/tir/schedule/transform.cc, src/tir/schedule/transform.h, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_tc.py, tests/python/unittest/test_tir_schedule_analysis.py, tests/python/unittest/test_tir_schedule_reindex.py, tests/python/unittest/test_tir_schedule_transform_layout.py
* Update schedule primitives (ReIndex, TransformBlockLayout) to preserve unit iters. Added test cases.
* Allow workloads with unit dimensions to be detected during auto-tensorization pattern marching. This allows padding to be added for tensorizing such workloads.
cc @spectrometerHBH @Hzfengsy @junrushao
=> [TIR, MetaSchedule] Preserve unit block iters for auto-tensorization

python/tvm/auto_scheduler/feature.py, src/auto_scheduler/feature.cc, src/meta_schedule/feature_extractor/per_store_feature.cc, tests/python/unittest/test_auto_scheduler_feature.py, tests/python/unittest/test_meta_schedule_feature_extractor_per_store_feature.py
Both auto_scheduler and metaschedule featurization did not lower bound loop extents by zero, leading to negative bounds. When multiplied with element size integer underflow occurred before converting to floating point.
@vinx13 @junrushao
=> [FIX,AUTOSCHEDULER,METASCHEDULE] Handle negative extents in featurization

python/tvm/testing/utils.py, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_replace_depthwise_conv2d.py, tests/python/unittest/test_roofline.py
These are all segfaulting in main ( see #12955, #12634, and #12841) so they need to be skipped until a fix is merged
=> [ci] Disable flaky ethosu + roofline tests

python/tvm/script/tir/__init__.py, python/tvm/script/tir/ty.py, tests/python/unittest/test_tvmscript_roundtrip.py
Previously, `T.bool` could be used to define a boolean value (e.g. `b = T.bool(1)`), but required using `T.boolean` when writing a type annotation.  This can cause both user confusion, as all other TVMScript type annotations directly match their string representation in `tvm.runtime.DataType`, and failure to roundtrip, because the tvmscript printer will generate the non-existence `T.bool` type annotations.
This commit add `tvm.script.tir.ty.bool`, which can be used in TVMScript as `T.bool`. The previous
`tvm.script.tir.ty.boolean` (`T.boolean` in TVMScript) is maintained for backwards compatibility.
=> [TVMScript] Allow T.bool type annotations

python/tvm/testing/utils.py, tests/python/integration/test_meta_schedule_auto_tensorize.py, tests/python/relay/test_op_level1.py, tests/python/relay/test_op_level10.py, tests/python/relay/test_op_level2.py, tests/python/unittest/test_meta_schedule_tune_relay.py
This is a followup to https://github.com/apache/tvm/pull/12865. We have some tests that depend on a dot product instruction of the target architecture, such as VNNI (cascadelake) and ARM `sdot/udot`. These tests are currently skipped on CI, but to properly test them on an instance that does support such instructions, I'm introducing `requires_arm_dot` and `requires_cascadelake` decorator.  
@tkonolige @driazati
=> [TEST] CPU feature detection for x86 and ARM dot product instructions

cmake/modules/contrib/CMSISNN.cmake, cmake/modules/contrib/EthosN.cmake, src/relay/backend/contrib/cmsisnn/generate_constants.cc, src/relay/backend/contrib/constant_transforms.cc, src/relay/backend/contrib/constant_transforms.h, src/relay/backend/contrib/ethosn/codegen.cc, src/relay/backend/contrib/ethosn/convert_equivalent.cc, src/relay/backend/contrib/ethosn/ethosn_api.cc, src/relay/backend/contrib/ethosn/ethosn_api.h, tests/python/contrib/test_ethosn/test_fullyconnected.py, tests/python/contrib/test_ethosn/test_networks.py
The NPU driver stack expects weights in IO (HWIO) format, however, Relay uses an OI representation. Although the shape of the weight tensor was correctly changed during codegen, the values in the weights tensor were not being transposed. This lead to an output mismatch when the output "units" was > 1. The tests didn't catch this due to using a weights tensor of all 1's.
cc @leandron @ashutosh-arm
=> [ETHOSN] Transpose fully connected weights

src/runtime/hexagon/hexagon_vtcm_pool.cc, src/runtime/hexagon/hexagon_vtcm_pool.h
Update HexagonVtcmPool to use compute_resource_query_VTCM to query for the total and available blocks in VTCM.  Ensures at least 1MB is available.
Also fixes two typos in the header.
cc:  @supersat, @kparzysz-quic, @csullivan
=> [Hexagon] [runtime] Query for total and available VTCM

src/tir/ir/index_map.cc, tests/python/unittest/test_index_map.py
Prior to this commit, `IndexMap::MapShape` could produce incorrect results when the split factor is greater than the size of the dimension being split.  For example, a buffer of shape `[N]` mapped transformed with `lambda i: [i//4, i%4]` should result in shape `[ceildiv(N,4), 4]`.  However, for `N<4`, the transformed shape was instead `[1, N%4]`.  This results in unexpected shapes when attempting to prepare a buffer for vectorized access.
This commit preferentially uses the result of `arith::DetectIterMap` to determine the mapped buffer shape, similar to what is done when computing the inverse.  The old method of `MapShape`, which relied on `arith::EvalSet`, is maintained for transformations that aren't recognized by `arith::DetectIterMap`.
=> [Arith][IndexMap] Correct MapShape result for small vectorized dims

src/ir/expr.cc, tests/python/unittest/test_tir_constructor.py
Previously, a `tir::FloatImm` could have a dtype passed to it that was not a floating point value.  This commit introduces a check, similar to what is already done in `tir::IntImm`, that requires the dtype to satisfy `DataType::is_float()`.
=> [TIR] Require dtype.is_float() inside FloatImm

src/meta_schedule/feature_extractor/per_store_feature.cc, tests/python/unittest/test_meta_schedule_feature_extractor_per_store_feature.py
In meta schedule's featurization, arithmetic intensity was incorrectly calculated as log(FLOPs) / log(bytes). This change corrects it to log(FLOPs/bytes). Note that this is the same issue as in #12079.
@vinx13 @junrushao
=> [Fix,MetaSchedule] Correct log usage in arithmetic intensity feature

tests/python/contrib/test_hexagon/test_software_pipeline_async.py
Disabling the "cache_write" schedule from this test as it is failing on device.  The root cause of the failure will be addressed with additional buffer dependency analysis in the InjectSoftwarePipeline pass to come in a subsequent PR.
=> [Hexagon] disable cache_write schedule type from sw pipeline test

include/tvm/arith/analyzer.h, src/arith/analyzer.cc, src/arith/canonical_simplify.cc, src/arith/rewrite_simplify.cc, src/arith/rewrite_simplify.h, src/arith/transitive_comparison_analyzer.cc, src/tir/transforms/simplify.cc, tests/python/unittest/test_tir_transform_simplify.py
This commit adds a new sub-analyzer, `TransitiveComparisonAnalyzer`, which attempts to apply multiple known comparisons to prove an unknown.  For example, `a <= b` and `b <= c` imply that `a <= c`. These simplifications are necessary for simplifying conditionals resulting from padded layout transformations (https://github.com/apache/tvm/issues/12261).
While some of these conditions may be proven using `ConstIntBoundAnalyzer` or `IntSetAnalyzer`, each has some limitations.  `ConstIntBoundAnalyzer` can only compare against a constant, `IntSetAnalyzer` internally calls `RewriteSimplifier` which can result in infinite recursion, and neither can handle not-equal conditions because it would require tracking multiple intervals per expression.  Therefore, introducing a new sub-analyzer for these …
=> [TIR][Arith] Prove conditionals by transitively applying knowns

python/tvm/testing/utils.py, tests/python/unittest/test_tvm_testing_before_after.py
A follow-up commit from https://github.com/apache/tvm/pull/12264. This allows the before/expected fixtures generated by `tvm.testing.CompareBeforeAfter` to be `IRModule` instances as well as `PrimFunc`.  This is intended to allow testing that requires comparing more than one function (e.g. hoisting/fusing a PrimFunc).
=> [UnitTest][TIR] Support IRModule comparisons in CompareBeforeAfter

tests/python/unittest/test_roofline.py
After #12959, this re-enables the test disabled in #12955 to get a
backtrace next time it fails.
=> [ci] Re-enable roofline test

python/tvm/meta_schedule/relay_integration.py, src/meta_schedule/postproc/postproc.cc, src/meta_schedule/postproc/rewrite_layout.cc, src/meta_schedule/schedule_rule/multi_level_tiling_wide_vector.cc, src/relay/backend/te_compiler_cache.cc, src/relay/transforms/meta_schedule_layout_rewrite.cc, src/te/operation/create_primfunc.cc, src/tir/transforms/remove_weight_layout_rewrite_block.cc, tests/python/contrib/test_hexagon/test_meta_schedule.py, tests/python/integration/test_auto_tensorize.py, tests/python/unittest/test_meta_schedule_relay_integration.py, tests/python/unittest/test_meta_schedule_vnni_integration.py, tests/python/unittest/test_te_create_primfunc.py
`RewriteLayout` assumes that the "layout-free" weight to be rewritten is passed as a parameter to prim func. This doesn't hold when `link-params = True` is used, since the constant weight is directly embedded in a primfunc as `AllocateConst` node.  
Supporting RewriteLayout on AllocateConst required some nasty hacks to workaround various issues. Detailed comments are provided to explain the problem and my solution.
This lets us enable `RewriteLayout` for Hexagon.
=> [MetaSchedule] Support RewriteLayout postproc on AllocateConst 

docs/dev/tutorial/codebase_walkthrough.rst
When I was studying the "TVM Codebase Walkthrough by Example" document, I found that the code didn't work, so I fixed it.
Bind the iteration axis to threads in the GPU.
=> [docs] fixed codebase_walkthrough document bug

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/cache_read_write.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_cache_read_write.py
If a block both read and write a buffer, it cannot do cache read/write separately, otherwise dependency breaks. This primitive perform cache read & write together to keep IR correct.
cc @Hzfengsy @wrongtest-intellif
=> [TIR][Schedule] Add cache_inplace primitive to cache opaque buffer

include/tvm/node/structural_equal.h, include/tvm/node/structural_hash.h, src/node/structural_equal.cc, src/node/structural_hash.cc
When we use `StructuralEqual/Hash`, the actual equality testing / hashing work are deferred to `RemapVarSEqualHandler` and `VarCountingSHashHandler` class respectively, defined in `.cc` files. To customize equality / hash behavior, I want to be able to derive from these classes outside of `structural_equal.cc` or `structural_hash.cc`. This is the first step toward replacing my previous attempt https://github.com/apache/tvm/pull/12706 to allow ignoring NDArray raw data in `StructuralEqual/Hash`.
So I propose to expose them as the "default" handler, while still hiding their implementation details. This lets me define a custom hasher that ignores NDArray content simply by:
```
class SHashHandlerIgnoreNDArray : public SHashHandlerDefault {
protected:
void DispatchSHash(const ObjectRef& …
```
=> [Node] Expose StructuralEqual/Hash handler implemenation to header

conda/recipe/meta.yaml, docs/conf.py, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/package.json
Bumps up version in main branch to 0.11.dev0 given we are finalizing 0.10.0 release: #13026
=> Update to 0.11.dev0

src/relay/backend/te_compiler_cache.cc
Attrs were not propogated from Relay functions to the corresponding PrimFunc when lowering with MetaSchedule enabled. These attrs are not seperately copied in the MetaSchedule lowering flow.
@junrushao
=> [FIX,LOWERING] Add attrs from Relay Functions to PrimFuncs in Metaschedule Lowering

conda/build-environment.yaml
The current [build-environment.yaml](https://github.com/apache/tvm/blob/main/conda/build-environment.yaml) doesn't specify the python version for `tvm-build` conda environment and as a result, any python version might be selected depending on the available base conda. In my case, the base conda is 3.10 so tvm won't work given [tvm is unsupported for python >= 3.9](https://github.com/apache/tvm/issues/8577).
To validate run on `tvm-build` env 
```
conda env update -f conda/build-environment.yaml
```
=> [Conda] Specify python version in build-environment

docker/install/ubuntu_download_arm_compute_lib_binaries.sh
This updates Compute Library from v21.11 to v22.08.
Changelog for this version can be found at:
https://arm-software.github.io/ComputeLibrary/v22.08/
cc @lhutton1 @areusch @Mousius for reviews
=> [CI] Update Compute Library to v22.08

include/tvm/tir/transform.h, python/tvm/meta_schedule/builder/local_builder.py, python/tvm/tir/transform/transform.py, src/meta_schedule/arg_info.cc, src/meta_schedule/feature_extractor/per_store_feature.cc, src/relay/backend/te_compiler_cache.cc, src/tir/transforms/remove_weight_layout_rewrite_block.cc, tests/python/unittest/test_meta_schedule_relay_integration.py
I found that, using MS evo search + `RewriteLayout` + `link-params=True`, where the latter combination is supported by https://github.com/apache/tvm/pull/12991 and https://github.com/apache/tvm/pull/12949, is currently broken for the following reasons:
* The manual NDArray rewriting via `IndexMap::MapNDArray` is slow
* `IndexMap::MapNDArray` is called more than thousands of times during evo search **per iteration**,  by the following call sequence:
`AssembleCandidates`
https://github.com/apache/tvm/blob/6780c9f87db6620409f8f58c2c2925c7bd7b6681/src/meta_schedule/search_strategy/evolutionary_search.cc#L206-L209 
-> `ArgInfo::FromEntryFun`
https://github.com/apache/tvm/blob/111169c7df2831ab8ee40d5388ebcfcf551fd86f/src/meta_schedule/arg_info.cc#L104-L107
-> `RemoveWeightLayoutRewriteBlock` …
=> [MetaSchedule] Allow skipping exact NDArray rewrite in RemoveWeightLayoutRewriteBlock

src/relay/transforms/simplify_expr.cc, tests/python/relay/test_pass_simplify_expr.py
ConcretizeCastLikeRewrite：Concretize cast_like to cast.
Not inheriting from ConcretizeLikeRewrite because even if shape is not static, still can concretize.
=> [Relay][Pass] ConcretizeCastLikeRewrite for SimplifyExpr

include/tvm/arith/analyzer.h, src/arith/conjunctive_normal_form.cc, src/arith/conjunctive_normal_form.h, src/arith/rewrite_simplify.cc, src/arith/rewrite_simplify.h, src/tir/transforms/simplify.cc, tests/python/unittest/test_tir_transform_simplify.py
Previously, `RewriteSimplifier` inspected the top branch of each `And` and `Or` node, but didn't perform simplifications that would require inspection across branches nested structures.  This commit introduces `SimplifyAsAndOfOrs`, which converts to an internal representation as conjunctive normal form, performs simplifications while in that form, then converts back to a `PrimExpr`.
This utility is designed for data-propagation simplifications as part of https://github.com/apache/tvm/issues/12261.  To avoid increasing the CPU load unnecesarily, this utility is only used on an opt-in basis, either by using  RewriteSimplifer::SetEnabledFeatures` when called directly, or by using `PassContext` when used as part of `tir::transform::Simplify`.
=> [Arith] Optional rewriting and simplification into AND of ORs

include/tvm/tir/stmt_functor.h, src/tir/ir/data_type_rewriter.cc, src/tir/transforms/narrow_datatype.cc, tests/cpp/data_type_rewriter_test.cc
`DataTypeLegalizer` can be used for more general purpose. This PR extracts the data type legalizing logic from `NarrowDataType` into a separate base class. There are no functional changes.
cc @Hzfengsy @junrushao @wrongtest-intellif
=> [TIR] Refactor NarrowDataType into DataTypeLegalizer

tests/python/contrib/test_hexagon/test_models.py, tests/python/integration/test_auto_tensorize.py, tests/python/unittest/test_meta_schedule_vnni_integration.py
Fix the VNNI test broken by https://github.com/apache/tvm/pull/12895
And I've just ran rocm and vulkan dp4a auto tensorization tests locally and confirmed that they still worked.
@junrushao
=> [TEST] Fix the broken VNNI MetaSchedule test

python/tvm/utils/roofline/__init__.py, python/tvm/utils/roofline/cuda.py, python/tvm/utils/roofline/registry.py, python/tvm/utils/roofline/x86.py, tests/python/unittest/test_roofline.py
Support different dtypes in roofline analysis. Only x86 support for now, but the interface is there to add support on cuda.
@AndrewZhaoLuo
=> [ROOFLINE] Add support for different dtypes

include/tvm/meta_schedule/task_scheduler.h, python/tvm/meta_schedule/logging.py, python/tvm/meta_schedule/task_scheduler/task_scheduler.py, python/tvm/meta_schedule/utils.py, src/meta_schedule/task_scheduler/gradient_based.cc, src/meta_schedule/task_scheduler/task_scheduler.cc, src/meta_schedule/utils.h
This PR further addes interactive table printing functionality following #12866, now performance table are print in dataframe style if running in jupyter notebook. Sample notebook see [here](https://gist.github.com/zxybazh/f201698324c8ebd0beb10365738dd327) 
CC @junrushao
=> [MetaSchedule][UX] Support Interactive Performance Table Printing in Notebook

python/tvm/relay/frontend/qnn_torch.py
Proposed solution to fix issue #13070
=> [Frontend][PyTorch]Fix keywords to canonicalize scale and zero point access for FX-quantized graphs

Jenkinsfile, ci/jenkins/Jenkinsfile.j2
Update all Docker image tags used in CI to tag
`20221013-060115-61c9742ea` in order to bring Compute Library to v22.08.
The following link shows the proposed tags being validated in upstream CI: 
[https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdocker-image-run-tests/detail/docker-image-run-tests/255/pipeline/790/](url)
CC @leandron @driazati @areusch @Mousius for reviews
=> [CI] Update Docker Image tag to 20221013-060115-61c9742ea

include/tvm/meta_schedule/database.h, python/tvm/meta_schedule/database/json_database.py, python/tvm/meta_schedule/database/memory_database.py, python/tvm/meta_schedule/database/schedule_fn_database.py, python/tvm/meta_schedule/relay_integration.py, python/tvm/meta_schedule/tune.py, src/meta_schedule/module_equality.cc, src/meta_schedule/module_equality.h, src/node/ndarray_hash_equal.h, src/node/structural_equal.cc, src/node/structural_hash.cc, tests/python/unittest/test_meta_schedule_relay_integration.py
A follow up to https://github.com/apache/tvm/pull/13050, also builds on https://github.com/apache/tvm/pull/13001. This PR enables the functionality in https://github.com/apache/tvm/pull/12706 without changing the existing `StructuralEqual/Hash`.
A question for discussion: Should this be the default ModuleEquality used by MS? It has no effect for the `link-params = False` case, and it simplifies the MS tuning API usage for the `link-params = True` case (Hexagon etc).
=> [MetaSchedule] Introduce a variant of ModuleEquality to enable ignoring NDArray raw data

docs/install/from_source.rst
Fix typo in the document of installing from source in `tvm/docs/install/from_source.rst`: `ontain -> obtain a visual studio compiler`.
=> [Doc] Fix typo in the document of installing from_source

src/tir/analysis/estimate_flops.cc, tests/python/unittest/test_tir_analysis_estimate_tir_flops.py
This commit fix the tvm's crash during auto-tune when having a 'if' statement which doesn't have a 'else' part in TVMScript.
It's cause in tvm's tir processing, in `VisitStmt_()` for IfThenElseNode its trying to visit the 'else' part (in TVMScript) whether it is exist.
So in this commit, an if logic is added in `VisitStmt_()` for IfThenElseNode, it will not visit the 'else' part if it is not exist.
=> [TIR][FIX] Fix crash when using 'if' without 'else' in TVMScript

python/tvm/relay/frontend/onnx.py
Ref: https://github.com/onnx/onnx/blob/main/docs/IR.md
Right now we take the first imported op set as the operator version for rest of conversion. This assumes the first imported op set is the default (ai.onnx), however this is not necessarily the case.
In the future, we need to support multiple operator sets well (see https://github.com/apache/tvm/issues/10950). For now, we just try to find the default (ai.onnx) namespace and use that for the opset version.
=> [ONNX] Handle multiple imports

tests/python/contrib/test_hexagon/test_async_dma_pipeline.py
…ing on hexagon.
The purpose of this test is to show how to create a pipeline that utilizes async dma copies to vtcm for performance speedup. It compares performance results between several different schedules and should serve as a good starting point for others wishing to take advantage of the new features. 
Approximated Activation Shape | Approximated Weight Shape | Approximated complexity (GOPS) | Total Memory Transferred (MB) | N, N, N (ms) | S, S, S (ms) | B, B, B (ms) | A, B, B (ms) | B, B, A (ms) | A, B, A (ms) | Async DMA Speedup (Compared to N, N, N)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
(1, 32, 32, 128) | (1, 1, 1, 128) | 0.001 | 0.26 | 0.0547 | 0.0715 | 0.6492 | 0.6172 | 0.1398 | 0.1033 | 0.53x
(1, 32, 32, 128) | (1, 3, 3, 128) | 0.005 | 0.26 | 0.0678 | 0.085 | …
=> [Hexagon] Async DMA pipelining test suite

python/tvm/topi/utils.py
Tuning doesn't work after #12969.
It reports the following error:
```
ImportError: cannot import name 'get_const_float' from partially initialized module 'tvm.topi.utils' (most likely due to a circular import)
```
In this commit, I moved import relay to a function which used in a test. And it helps to fix this circular import.
To reproduce this issue, you can run the following [tutorial](https://github.com/apache/tvm/blob/main/gallery/tutorial/autotvm_relay_x86.py) and will see this error.
cc: @guberti, @areusch, @ekalda
=> [HotFix] Fix python import

python/tvm/contrib/hexagon/build.py, python/tvm/contrib/hexagon/pytest_plugin.py
This PR got closed when deleting my fork https://github.com/apache/tvm/pull/12894 now it does not seem to track this branch so here is a copy. 
I added some things to the hexagon pytest plugin to make working on hexagon a little bit easier sometimes.
--hexagon-debug will now copy all of the logcat logs for the time period of the test and copy them back to your device.
--sysmon-profile will start the Sysmon Profiler before your run, shut it down afterwards and then copy the data back and parse it to html for you.
cc @mehrdadh
=> [Hexagon] Add feature to copy logcat to --hexagon-debug and add new --sysmon-profile option to run sysmon profiler during the test

python/tvm/contrib/popen_pool.py, python/tvm/meta_schedule/runner/local_runner.py
This PR enables redirection of the standard output stream and standard error stream to given subprocess handler.
This function especially improves the usage of `LocalRunner` because previously a sample candidate's exception during running could print long lines of output, making console logging / notebook logging obsolete. In the meantime, any failure of the candidates are still preserved in the per-task logging files (Schedule, trace & TIR available, doesn't include the stack trace though).
Credits to @Hzfengsy's fix in https://github.com/mlc-ai/relax/pull/6.
=> [PopenPool] Enable Stdout & Stderr Redirect in PopenPool & PopenWorker

docker/Dockerfile.ci_adreno, docker/bash.sh, python/tvm/testing/utils.py, tests/python/contrib/test_clml/conftest.py, tests/python/contrib/test_clml/infrastructure.py, tests/python/contrib/test_clml/test_network.py, tests/python/contrib/test_clml/test_ops.py, tests/python/relay/opencl_texture/test_conv2d_nchw_texture.py, tests/scripts/ci.py, tests/scripts/task_build_adreno_bins.sh, tests/scripts/task_config_build_adreno.sh, tests/scripts/task_python_adreno.sh
New docker for Adreno that inherits gpu docker and amends android-sdk.
For CLML, we need to specify ADRENO_OPENCL via environment variable. CLML SDK can be downlaoded from Qualcomm Developer Network by following
https://developer.qualcomm.com/blog/accelerate-your-models-our-opencl-ml-sdk
Adreno device is shared with host, hence networking is enabled for Adreno Docker.
=> [DOCKER][Adreno]Docker infra for Adreno target with CLML support

include/tvm/runtime/ndarray.h, tests/cpp/ndarray_test.cc
Skip stride check if shape[k] is 1, where the dimension is contiguous regardless of the value of stride.
For example, PyTorch will normalize stride to 1 if shape is 1.
Related: https://github.com/pytorch/pytorch/commit/ec42ee027867e586ea1c584c7ba7e06dd8b4bcb4
=> Skip stride check if shape is 1 in IsContiguous

tests/python/contrib/test_hexagon/test_benchmark_maxpool2d.py
Fix a bug in `test_benchmark_maxpool2d.py` where pytest was unable to find a fixture defined in a different module.
=> [test][hexagon] Fix pytest fixture resolution bug

docker/with_the_same_user, tests/scripts/task_config_build_hexagon.sh
sccache chokes on the hexagon builds for some users, so this disables it
by default locally but keeps it on in CI.
cc @adstraw @janetsc
=> [ci] Skip sccache for local hexagon builds

tests/python/unittest/test_meta_schedule_relay_integration.py
Previous change https://github.com/apache/tvm/pull/12895 inherited this test of lowering from relay which can be used for lowering test but missed the functionality of detecting argument order change. This PR restores the test to use a customized verification database to detect changes in TE to PrimFunc lowering, making sure the order of argument doesn't change.
=> [MetaSchedule][Minor] Restore Relay Integration Unit Test

src/meta_schedule/schedule_rule/multi_level_tiling.cc, src/tir/schedule/primitive/cache_read_write.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt.py
Currently, trying to tune the following simple mod results in an error:
```
data = relay.var("data", shape=data_shape, dtype="float32")
weight = relay.var("weight", shape=weight_shape, dtype="float32")
dense = relay.nn.dense(data, weight)
mod = tvm.IRModule.from_expr(dense + data)
```
```
...
for ax0, ax1 in T.grid(128, 128):
with T.block("p0_shared"):
v0, v1 = T.axis.remap("SS", [ax0, ax1])
T.reads(p0[v0, v1])
T.writes(p0_shared[v0, v1])
p0_shared[v0, v1] = p0[v0, v1]
for i0_0_i1_0_fused in T.thread_binding(4, thread="blockIdx.x"):
for i0_1_i1_1_fused in T.thread_binding(16, thread="vthread.x"):
for i0_2_i1_2_fused in T.thread_binding(8, thread="threadIdx.x"):
for i2_0, i2_1, i0_3, i1_3, i2_2, i0_4, i1_4 in T.grid(1, 32, 1, 32, 4, 1, 1):
with T.block("T_matmul_NT"): …
```
=> [MetaSchedule] Fix AddReadReuse for multiple consumer block case

src/runtime/hexagon/hexagon_buffer_manager.h, src/runtime/hexagon/hexagon_device_api.cc, src/runtime/hexagon/hexagon_device_api.h
The motivation behind resource management is to ensure that we release all resources at the end of the session.
Given the session management on the client side, it is possible for ReleaseResources to be called before all client side objects have been torn down.  And, it is possible for frees to be called in the window between session end and process termination.  (After those buffers have been freed in ReleaseResources.)
Based on feedback from @adstraw and @Lunderberg on the usage of "released_runtime_buffers," we did an investigation into the post-release frees.  The cleanest solution is to keep the logic to free all buffers in ReleaseResources, and log a message on any frees that are executed outside a session.
=> [Hexagon] [runtime] Remove released buffer check for post-ReleaseResources calls to FreeDataSpace

src/meta_schedule/utils.h
The current datatype issue #12997 could cause the postproc application to fail in massive number during evolutionary search, causing tons of exception logging onto the screen via `LOG(WARN)`. This change removes the postproc application exception logging in the utility of search strategy, the reasons are:
1. The errors are triggered in multi-thread environment, the logging is hard to read anyway
2. We have a large population of candidates to mutate and apply postproc, in scenarios like the data type issue, it generates tons of logging, which is not helpful.
3. To debug we always need to run the postproc alone, which doesn’t matter in this case.
4. Without the warning log, we can still see failed postproc number count in the logging, and check for failure if necessary. If all the …
=> [MetaSchedule] Remove Exception Catch for Multithread Postproc Application

include/tvm/tir/stmt_functor.h, src/tir/ir/index_map.cc, src/tir/ir/stmt_functor.cc, tests/python/unittest/test_index_map.py, tests/python/unittest/test_tir_schedule_transform_layout.py
=> [TIR] Allow IndexMap applied to arguments with different dtypes

apps/cpp_rpc/CMakeLists.txt
With NDK>= 23 when we specify explicitly linker then we got the following error:
```
ld.gold: --no-rosegment: unknown option
```
From the github repository of NDK, I found that the only one right way to configure linker is using `-DANDROID_LD` variable: https://github.com/android/ndk/issues/1426#issuecomment-760432467
Removed setting linker manually and by default `LLD` will be used.
Checked that it works on the following versions of NDK:
- 20.0.5594570
- 21.4.7075529
- 22.1.7171670
- 23.0.7599858
- 23.1.7779620
- 24.0.8215888
- 25.1.8937393
cc: @csullivan, @elvin-n
=> [Android] Fix cpp_rpc build for android with NDK>=23

python/tvm/meta_schedule/cost_model/cost_model.py, tests/python/integration/test_tuning.py
Previously even for replay trace & replay func strategy, an xgboost cost model will be created and retrained after each iteration of building and running. This PR introduces a `none` cost model option to avoid creating cost model. Also fixed the integration test for correctness verification by using the correct tvm device.
=> [MetaSchedule] Support Tuning w/ No Cost Model & Fix Integration Test

src/target/parsers/aprofile.cc, src/target/parsers/aprofile.h, tests/cpp/target/parsers/aprofile_test.cc
This implements an initial Target Parser which aims to consolidate architecture feature detection from a few different places:
* https://github.com/apache/tvm/blob/d2db9cb0d839e32778f461b77e59f6418282a511/python/tvm/topi/arm_cpu/arm_utils.py#L24-L70
* https://github.com/apache/tvm/blob/02fbaf0ed9120a8f95155e63de42459f230584aa/python/tvm/relay/qnn/op/legalizations.py#L350-L359
* https://github.com/apache/tvm/blob/b542724873140bb051492530d97a78b9b7b7983d/python/tvm/relay/op/strategy/arm_cpu.py#L232
A further patch will remove all of the above and replace usages with the `.features` map.
=> [Target] Add Target Parser for Arm(R) Cortex(R) A-Profile CPUs

python/tvm/driver/tvmc/compiler.py, tests/python/driver/tvmc/test_compiler.py
=> [tvmc] add instruments for PassContext

python/tvm/tir/tensor_intrin/hexagon.py, src/printer/tvmscript_printer.cc, tests/python/contrib/test_hexagon/metaschedule_e2e/__init__.py, tests/python/contrib/test_hexagon/metaschedule_e2e/export_models.py, tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_fp16.py, tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_int8.py, tests/python/unittest/test_tvmscript_roundtrip.py
I've worked on a series of PRs to enable e2e MS tuning on Hexagon (mostly for supporting `link-params = True` in MS). Now that all the pieces have been upstreamed, I'm adding demo tuning scripts under `test_hexagon/metaschedule_e2e`. 
They are not run on CI, and running it locally requires PyTorch to generate fp16 and int8 resnet50. 
The scripts use a small number of tuning trials and `replay-trace` search strategy instead of the evolutionary search, to finish tuning quickly. Those interested in MS tuning can tweak these settings for better performance at the cost of more tuning times.
@csullivan @kparzysz-quic @farshidsp
=> [Hexagon] Add scripts for e2e MetaSchedule tuning demonstration

src/runtime/hexagon/ops/conv_utils.cc, tests/python/contrib/test_hexagon/topi/test_conv2d_fp16_intrin.py
The filter data is contiguous, the iteration is over 16-bit elements, not pointers.
=> [Hexagon] Fix chunk address table generation in chunkify_hwio_16b

Jenkinsfile, ci/jenkins/Jenkinsfile.j2
As requested by https://discuss.tvm.apache.org/t/frontend-pytorch-tvm-compatibility-with-torch-1-12-0/13508, updating PT to 1.12.
Validated in https://github.com/apache/tvm/tree/ci-docker-staging.
Thanks to @oviazlo for the update work!
=> [CI] Update PyTorch to v1.12 in GPU image

src/runtime/hexagon/hexagon_buffer_manager.h, src/runtime/hexagon/hexagon_device_api.cc
Refactoring `HexagonBufferManager` class with a few small changes: 1) moving mutex lock before `find` in `FreeHexagonBuffer` 2) Removing `count` method as the only caller uses it to check / log duplicate error as in `FreeHexagonBuffer` itself 3) rename to `FindHexagonBuffer` for clariry.
=> [Hexagon] refactor HexagonBufferManager class

ci/scripts/retry.sh
This bumps the wait time between failing network calls from `(10, 30)`
to `(30, 200)` seconds. A failing CI run is pretty costly so it makes
sense to wait a little longer and see if Docker/AWS/whoever starts
responding.
Motivated by
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4495/pipeline
which saw 5 `docker pull` `500` errors in a row
=> [ci] Wait longer during retries

Jenkinsfile, ci/jenkins/Prepare.groovy.j2, ci/jenkins/macros.j2
These are never really signal-carrying so there's no need for it to show
up as red on CI jobs. This also adds retries to the `git checkout` step
within Jenkins to deal with GitHub instability. This should help avoid
confusing situations like in #13136
=> [ci] Ignore JUnit upload failures

ci/scripts/git_change_docker.sh
These files have no effect on Docker image builds so if they are changed
we shouldn't be triggering a Docker image build. Right now if anything
in `docker/` is touched a build is run, this adds a short exclusion list
of some files (each of which is used for local testing or is exercised
already in CI).
=> [skip ci][ci] Ignore certain files for triggering docker builds

docker/bash.sh
This PR is for fixing an issue with CI. The issue is that we always mount the host machine `.tvm_test_data` directory to docker image to reuse the downloaded files in `${HOME}/.tvm_test_data` on the host machine. This will result in CI breakage when a file is cached but has changed recently. 
An example of that is the mobilenet model which changed recently:
https://github.com/apache/tvm/issues/13104
cc @driazati
=> [Docker][CI] Remove mounting local download path to docker

src/runtime/hexagon/hexagon_common.h, src/runtime/hexagon/hexagon_device_api.h, src/runtime/hexagon/hexagon_htp.cc, src/runtime/hexagon/hexagon_power_manager.cc, src/runtime/hexagon/hexagon_power_manager.h
This PR adds a new class, `HexagonPowerManager`, which interfaces with the `HAP_power` API to request maximum performance.
cc: @mehrdadh @csullivan @kparzysz-quic
=> [Hexagon] Add power manager

tests/scripts/task_java_unittest.sh
=> [ci] Disable flaky Java RPC tests

python/tvm/contrib/hexagon/pytest_plugin.py
ADB, the Android Debug Bridge, tries to determine if an emulator is present by looking for port 5555 being open. Unfortunately, once adb thinks there's an emulator running, it will continously try to connect to it, adding an error to its log on every failed attempt. This log file quickly grows to hundreds of gigabytes before developers notice they are completely out of disk space. This problem is further compounded by the Hexagon Launcher forwarding 10 contiguous ports from the randomly-chosen RPC base port, causing this failure to happen more often than you'd otherwise suspect.
See https://stackoverflow.com/questions/3152681/android-emulator-5554-offline/10356594#10356594
cc: @csullivan @mehrdadh @cconvey
=> [Hexagon] Adjust Hexagon pytest port range

src/runtime/hexagon/hexagon_device_api.h, src/runtime/hexagon/hexagon_thread_manager.cc, src/runtime/hexagon/hexagon_thread_manager.h, tests/cpp-runtime/hexagon/hexagon_thread_manager_tests.cc
This allows the creation of a thread manager with optional hardware resources.  This allows us to create a new object for unit tests without hardware resources.
This will fix the test instability we've seen recently, as all tests were using the global thread manager and things could be in an unknown state.
cc: @adstraw, @mehrdadh, @JosephTheOctonaut, @csullivan
=> [Hexagon] [runtime] Allow creation of thread manager without hardware resources

src/target/intrin_rule.cc, src/target/llvm/intrin_rule_nvptx.cc, src/target/llvm/intrin_rule_rocm.cc, src/target/source/intrin_rule_aocl.cc, src/target/source/intrin_rule_cuda.cc, src/target/source/intrin_rule_metal.cc, src/target/source/intrin_rule_opencl.cc, src/target/source/intrin_rule_vhls.cc, src/target/spirv/intrin_rule_spirv.cc, tests/python/frontend/pytorch/test_forward.py, tests/python/relay/test_op_level5.py, tests/python/topi/python/test_topi_image.py
During testing of this PR #13163, it turns out that the `nearbyint` intrinsic is missing despite being supported.
@junrushao
=> [TIR] Add the missing nearbyint intrinsic

python/tvm/relay/op/strategy/arm_cpu.py, python/tvm/relay/qnn/op/legalizations.py, python/tvm/topi/arm_cpu/arm_utils.py, python/tvm/topi/arm_cpu/conv2d_gemm.py, python/tvm/topi/arm_cpu/conv2d_int8.py, python/tvm/topi/arm_cpu/depthwise_conv2d.py, src/target/parsers/cpu.cc, tests/python/contrib/test_arm_compute_lib/test_network.py, tests/python/relay/test_op_level2.py, tests/python/target/test_arm_target.py, tests/python/topi/python/test_topi_conv2d_int8.py
Following on from https://github.com/apache/tvm/pull/12454 this patch removes the utility functions in favour of the centralised `target.features` property.
=> [Target] Replace utility functions with target.features

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
ONNX Runtime supports `FastGelu` in its `contrib opset` ([documentation](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.FastGelu) and [code](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/contrib_ops/cpu/bert/fast_gelu.cc)). Implementation of this operator refers to an approximation for original GELU ([article](https://arxiv.org/pdf/1606.08415.pdf)).
Previously, converter for `Gelu` was added to TVM ONNX frontend, however, there is no such converter for `FastGelu`.
This PR adds this converter to ONNX frontend.
=> [ONNX] Add converter for FastGelu from Microsoft onnxruntime contrib opset

python/tvm/relay/op/strategy/adreno.py, python/tvm/topi/adreno/__init__.py, python/tvm/topi/adreno/reduction.py, python/tvm/topi/cuda/reduction.py, tests/python/relay/opencl_texture/test_reduction_texture.py
Origin cuda schedule uses rfactor that is 10x-50x slower on Adreno than without barries
for example mean on QHD picture on Snapdragon 888 with cuda schedule is executed for 69ms while with new proposed schedule is executed for 6.2
the same for argmin: 183ms -> 3.9ms
=> [Adreno] Adapt reduction schedule for adreno

include/tvm/tir/analysis.h, python/tvm/ir/memory_pools.py, python/tvm/relay/backend/aot.py, src/relay/backend/aot/create_function_metadata.cc, src/relay/backend/aot/create_function_metadata.h, src/tir/usmp/utils.cc, tests/python/relay/aot/test_aot_create_function_metadata.py
Tracking issue: https://github.com/apache/tvm/issues/12548
AOT requires FunctionInfo to be defined for all the functions in the module. This stores information on how much memory the functions use. This commit adds a separate analysis pass to create all the FunctionInfos + some tests for the new pass.
=> [AOT] Add CreateFunctionMetadata analysis pass

docker/install/ubuntu_install_python_package.sh, docs/conf.py
This changes the 'View Source' button on the top right of each doc page
to a link that goes to a GitHub web editor for that docs page and
automatically routes to the right source of truth, be it `.rst` or
`.py`. Depends on https://github.com/tlc-pack/tlcpack-sphinx-addon/pull/10
for links.
=> [docs] Add 'Edit on GitHub' button

python/tvm/relay/transform/transform.py, src/relay/transforms/div_to_mul.cc, src/relay/transforms/fake_quantization_to_integer.cc, tests/python/unittest/test_div_to_mul.py
Convert division by a scalar constant into multiplication by the inverse of the constant. Multiplication is faster than division and also allow for more optimization opportunities. Only applies to float32 and float64.
I wrote this as a separate pass. Is there a better way to do it?
@AndrewZhaoLuo
=> [Relay] Rewrite division by constant to multiply

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
This PR 
* adds the missing CastLike op and 
* fixes proto injection issue for onnx node tests that include other types besides TensorType with Optional and Sequence types for the upcoming PRs
* fixes Cast version issue.
=> [Relay][ONNX] Resolve proto ingestion issue for non-tensor type and add CastLike op

src/auto_scheduler/utils.h
This fixes a bug in autoscheduler featurization.
=> [Fix,Auto_scheduler] Default to extent of 1 if extent cannot be determined

python/tvm/relay/frontend/onnx.py, python/tvm/runtime/vm.py, tests/python/frontend/onnx/test_forward.py
This PR adds the various Optional ops introduced in [opset 15](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#optional-15).
Note that this PR depends on #13184 and will be rebased once that is merged. 
Update: rebase is done. Ready for review. 
@AndrewZhaoLuo
=> [Relay][ONNX] Add Optional, OptionalHasElement and OptionalGetElement ops based on Sequence op

src/runtime/hexagon/hexagon_vtcm_pool.cc, tests/cpp-runtime/hexagon/hexagon_vtcm_pool_tests.cc
Previously we were failing allocations in an attempt to find the smallest allocation possible but were failing to find an allocation that worked if it was available.
=> [Hexagon] Add fix for vtcm allocation searches

python/tvm/contrib/hexagon/build.py, python/tvm/contrib/hexagon/meta_schedule.py, python/tvm/contrib/hexagon/pytest_plugin.py, python/tvm/contrib/hexagon/session.py, python/tvm/contrib/hexagon/tools.py, src/runtime/hexagon/rpc/hexagon/rpc_server.cc, src/runtime/hexagon/rpc/simulator/rpc_server.cc, tests/python/contrib/test_hexagon/README_RPC.md, tests/python/contrib/test_hexagon/benchmark_util.py, tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_fp16.py, tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_int8.py, tests/python/contrib/test_hexagon/test_benchmark_elemwise_add.py, tests/python/contrib/test_hexagon/test_benchmark_maxpool2d.py, tests/python/contrib/test_hexagon/test_meta_schedule.py, tests/python/contrib/test_hexagon/test_models.py, tests/python/contrib/test_hexagon/test_software_pipeline_async.py, tests/python/contrib/test_hexagon/topi/test_cast_slice.py
This PR adds `upload` to hexagon RPC server running on Hexagon side. This will remove the need of `adb` command for uploading/executing binary files on hexagon.
=> [Hexagon]: Add upload function to hexagon session

src/runtime/hexagon/hexagon_htp.cc, src/runtime/hexagon/hexagon_htp.h, src/runtime/hexagon/hexagon_hvx.cc, src/runtime/hexagon/hexagon_hvx.h, src/runtime/hexagon/hexagon_thread_manager.cc, src/runtime/hexagon/hexagon_thread_manager.h, tests/cpp-runtime/hexagon/hexagon_device_api_tests.cc, tests/cpp-runtime/hexagon/hexagon_thread_manager_tests.cc
Add support to lock and unlock resources on the individual threads.  Adds APIs to get a thread handle for a given resource type, and get a resource type for a given thread handle.  This will aid in asynchronous support that is sending work to dedicated threads for the hardware resources.
There are two steps to fully acquire a resource:  reserve and lock.  HTP/HVX manager objects are created on the global thread, which will reserve the resources.  The lock/unlock will occur on the thread that owns a particular instance.  The manager objects will be deconstructed when the thread manager is deconstructed.  This will release the resources.
cc:  @csullivan, @adstraw, @JosephTheOctonaut, @kparzysz-quic
=> [Hexagon] [runtime] Per-thread hardware resource management

gallery/how_to/compile_models/from_tflite.py, gallery/how_to/optimize_operators/opt_conv_tensorcore.py, gallery/how_to/tune_with_autotvm/tune_conv2d_cuda.py, gallery/how_to/tune_with_autotvm/tune_relay_arm.py, gallery/how_to/tune_with_autotvm/tune_relay_cuda.py, gallery/how_to/tune_with_autotvm/tune_relay_mobile_gpu.py, gallery/how_to/work_with_microtvm/micro_tflite.py, gallery/tutorial/autotvm_matmul_x86.py, gallery/tutorial/cross_compilation_and_rpc.py, gallery/tutorial/install.py, tests/lint/check_request_hook.py
Fixes #12343. Rather than hacking away empty code blocks with JavaScript this changes the lint for the request hook code to ensure that it is part of another code block or at the end of a tutorial `.py` (which sphinx-gallery itself removes).
=> [docs] Fix empty code blocks in tutorials

include/tvm/tir/analysis.h, python/tvm/tir/analysis/analysis.py, src/tir/analysis/stmt_finding.cc, src/tir/schedule/analysis.h, src/tir/schedule/analysis/analysis.cc, tests/python/unittest/test_tir_analysis_stmt_finding.py
I'm working on enabling "anchor block" tuning for MS. This is a utility to extract anchor blocks. 
I define the "anchor block" to be the block (1) with an init statement and (2) having the biggest flops count. The latter condition is only used when there are multiple blocks with an init statement.
For example, if the input module is conv2d + fused spatial blocks, conv2d is the anchor block. A module created from winograd convolution has multiple blocks with an init statement (input transform, batched GEMM, and output transform). We use the second condition, the flops count, to determine that the batched GEMM block is the anchor block.
cc @junrushao @Hzfengsy
=> [TIR] Add utility for anchor block extraction

src/relay/transforms/to_mixed_precision.cc, tests/python/contrib/test_dnnl.py, tests/python/relay/test_to_mixed_precision.py
This PR fixes issue https://github.com/apache/tvm/issues/12763, where some OP are marked to keep the original dtype but some of its input is `bfloat16` while a `Cast` is missing.
The AMP tests have also been refined to cover `bfloat16` **without** accuracy checking.
Update:
The accuracy checking in `test_dnnl.py` of bf16 vs fp32 is unstable and error-prone. Thus the accuracy checking is ignored if only one bf16 result present, i.e. only compare bf16 vs bf16 and fp32 vs fp32.
=> [AMP] refine AMP and the corresponding tests for bfloat16

.asf.yaml
This adds a fnmatch entry for the release branches to ensure that
changes come from PRs and that force pushes / rebased aren't allowed so
it's always possible to trace the release branch back to a mainline TVM
commit.
=> [ci] Protect release branches

src/tir/ir/stmt_functor.cc
Previously, the `IRSubstituteWithDataTypeLegalization` class implemented some virtual functions of `DataTypeLegalizer`, but not all.  As a result, some compilers gave warnings that the base class methods were being shadowed.  This commit adds the `using` declaration to avoid shadowing.
=> [IR] Remove shadowing in IRSubstituteWithDataTypeLegalization

src/arith/modular_set.cc, tests/python/unittest/test_arith_canonical_simplify.py, tests/python/unittest/test_tir_transform_simplify.py
Prior to this commit, any use of negative coefficients in `ModularSet` would result in an error.  This included cases where a constraint is being entered, such as `floormod(i, -2)==0` appearing as the condition of an if/else block.  These negative indices can also arise as intermediate simplification steps produced by `CanonicalSimplifier`, such as `floormod(-i,2)` being canonicalized to `floormod(i,-2)`.
This commit adds support for negative coefficients in `ModularSet`, using the same sign convention as is used by `CanonicalSimplifier` for negative denominators, and adds unit tests to verify that sign convention.
=> [TIR][Arith] Support negative coeff in ModularSet

src/arith/narrow_predicate_expression.cc, src/arith/narrow_predicate_expression.h, tests/python/unittest/test_arith_narrow_predicate_expression.py
Implements `tvm::arith::NarrowPredicateExpression`, a utility that removes free parameters from a boolean expression, such that the resulting expression being true implies that the original expression is true.  For example, the predicate `(0 <= i+f) && (i+f < 16)`, where `f` is a free parameter on the range `0 <= f < 2)`, can be narrowed to the expression `(0 <= i+0) && (i+2 < 16)`.
In effect, `NarrowPredicateExpression` functions as a context-sentive `tvm::tir::Substitute`, where the value substituted is selected such that the resulting expression errs on the side of being false.  This is an internal utility used as part of the simplifications for layout transformations ([tracking issue link](https://github.com/apache/tvm/issues/12261)).
=> [Arith] Add internal NarrowPredicateExpression utility

python/tvm/relay/frontend/paddlepaddle.py
Hi, I noticed missing a depthwise_conv2d_transpose, but there is a convert function, convert_conv2d_transpose, seems to support the convertion for this op.
@jiangjiajun 
@heliqi 
cc @junrushao
=> [Frontend][Paddle] Add depthwise_conv2d_transpose op mapping

python/tvm/contrib/hexagon/pytest_plugin.py, tests/python/contrib/test_hexagon/test_fixed_point_multiply.py, tests/python/contrib/test_hexagon/test_models.py, tests/python/contrib/test_hexagon/test_usmp.py, tests/python/contrib/test_hexagon/test_wo_qnn_canonicalization.py
This PR updates few hexagon tests to use AOT instead of Graph executor.
=> [Hexagon] Update tests to use AOT Executor 

include/tvm/arith/int_set.h, include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/cache_index.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_cache_index.py
Buffer load index can be precomputed and saved in an index buffer, to prevent multiple index computation.
@Hzfengsy @wrongtest-intellif
=> [TIR][Schedule] Add cache_index to precompute index of buffer load

src/tir/schedule/analysis/analysis.cc, tests/python/unittest/test_tir_schedule_state_cached_flags.py, tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
This PR fixes a bug of affine-binding check in TIR. Previously, the affine-binding check will call `DetectIterMap` with trivial iterators simplified. However, this will cause some blocks with affine bindings not recognized as having affine bindings (see the regression test for a concrete example). This PR specifies that we do not simplify the trivial iterators when checking affine bindings.
cc @spectrometerHBH @vinx13 @junrushao @wrongtest-intellif
=> [BugFix][TIR] Affine-binding check should not simplify trivial iterators

docker/install/ubuntu_install_hexagon.sh
https://github.com/apache/tvm/pull/12873 needs an updated LLVM version, as noted in https://github.com/apache/tvm/issues/12966. This PR pulls the most recent llvm patch off of main which should work with the latest tvm.
=> [Hexagon]Pull and build specific LLVM sha for hexagon docker CI

include/tvm/arith/analyzer.h, src/arith/rewrite_simplify.cc, src/tir/transforms/simplify.cc, tests/python/unittest/test_tir_transform_simplify.py
When simplifying a branch of a boolean AND or a boolean OR, the other branch may be assumed not to dominate the result of the operator.  For example, when simplifying `(A and B)`, `A` may be simplified on the assumption that `B` is true.  Similarly, when simplifying `(A or B)`, `A` may be simplified on the assumption that `B` is false.
Prior to this commit, these constraints were not used for simplifications.  This commit introduced an optional extension, `kApplyConstraintsToBooleanBranches`, which exposes these constraints for simplification.  This isn't enabled by default, as some cases require a second visit to each branch of a boolean operator.  (e.g. Simplifying the LHS of an operator, using a constraint provided by the RHS, where the sub-analyzer that uses the constraint expects it …
=> [TIR][Arith] Implement kApplyConstraintsToBooleanBranches extension

apps/android_camera/app/src/main/jni/tvm_runtime.h, apps/android_rpc/app/src/main/jni/tvm_runtime.h, apps/ios_rpc/tvmrpc/TVMRuntime.mm, include/tvm/runtime/logging.h, python/tvm/contrib/hexagon/build.py, src/meta_schedule/utils.h, src/runtime/hexagon/hexagon_common.cc, src/runtime/hexagon/rpc/android_bash.sh.template, src/runtime/hexagon/rpc/hexagon/rpc_server.cc, src/runtime/logging.cc, web/emcc/wasm_runtime.cc
Currently Hexagon logging is done with a custom `LogMessageImpl` in` hexagon_common.cc`. This ends up calling `HexagonLog `and `HEXAGON_PRINT` which uses the HAP FARF API. Unfortunately, the TVM log level is lost along the way, with logs being produced at FARF’s `ALWAYS` level. This becomes especially noisy with RPC debug logging, which generates enough noise to cause some log data to be dropped. It also introduces a lot of useless noise, as the FARF API produces its own line number information, which only points to where `hexagon_common.cc` calls `HEXAGON_PRINT`. Using the `HAP_debug_runtime` API lets us pass the log level and file line information directly, and enables runtime selection of logging levels.
This commit explicitly passes the log level to `LogMessage`/`LogMessageImpl` and …
=> [Logging][Hexagon] Improve logging on Hexagon

.asf.yaml
We have to remove and re-add this user to re-trigger the asf invitation
Follow on to #13141
=> [skip ci] Remove naut-thomas from .asf.yaml

.github/workflows/main.yml, python/tvm/contrib/xcode.py
These tests were previously disabled (see https://github.com/apache/tvm/issues/13185). The error was related to updating `MacOS` to version `12.6` and `XCode` update.
This PR fixes the error and re-enables tests for `iOS RPC`.
=> [CI] Enable iOS RPC tests

python/tvm/contrib/hexagon/hexagon_profiler.py, python/tvm/contrib/hexagon/profiling/process_lwp_data.py
Additional changes to hexagon specific lightweight profiling. 
The PR updates the search pattern for .so address since the old pattern wasn't available for everyone. In addition, it also allows for the handling of tvm.build modules.
=> [Hexagon] Update search pattern to find .so address for on device runs

.asf.yaml
This reverts commit 3149ee5a73133dd320c8ec259459a4c32b1955d8.
This is needed to re-send the invitation to the repo
=> [skip ci] Revert "[skip ci] Remove naut-thomas from .asf.yaml (#13231)"

include/tvm/runtime/registry.h
=> [runtime] Fix typo in runtime/registry.h

include/tvm/tir/stmt.h, src/arith/ir_mutator_with_analyzer.cc, src/arith/ir_visitor_with_analyzer.cc, src/contrib/hybrid/codegen_hybrid.cc, src/printer/tir_text_printer.cc, src/printer/tvmscript_printer.cc, src/target/llvm/codegen_llvm.cc, src/target/source/codegen_c.cc, src/target/spirv/codegen_spirv.cc, src/target/stackvm/codegen_stackvm.cc, src/tir/analysis/block_access_region_detector.cc, src/tir/analysis/estimate_flops.cc, src/tir/ir/stmt.cc, src/tir/ir/stmt_functor.cc, src/tir/transforms/common_subexpr_elim_tools.cc, src/tir/transforms/compact_buffer_region.cc, src/tir/transforms/coproc_sync.cc, src/tir/transforms/inject_virtual_thread.cc, src/tir/transforms/ir_utils.cc, src/tir/transforms/lift_attr_scope.cc, src/tir/transforms/profile_instrumentation.cc, src/tir/transforms/remove_no_op.cc, src/tir/transforms/simplify.cc, src/tir/transforms/storage_access.cc, src/tir/transforms/vectorize_loop.cc
This parameter is nullable for cases where the else block isn't present.  Previously, it was represented as a `Stmt` holding `nullptr`, because `IfThenElse` (https://github.com/apache/tvm/pull/3533) predates the `Optional` utility (https://github.com/apache/tvm/pull/5314).  This commit updates to use `Optional<Stmt>` instead, and updates all usages of `else_case`.
=> [TIR] Use Optional<Stmt> for IfThenElseNode::else_case

src/meta_schedule/database/json_database.cc, src/meta_schedule/database/memory_database.cc
Previously the memory database assumed the workload tokens are from `CommitWorkload` function, this PR allows the use of module equality function in `GetTopK` function to compare workloads.
Thanks to @petersalas for point it out.
=> [MetaSchedule][Minor] Fix Memory Database Module Equality

src/relay/transforms/simplify_expr.cc, tests/python/relay/test_pass_simplify_expr.py
This PR enables simplification and folding of a sub graph containing adjacent `mul`s and `add`s with constant inputs.
Workloads like [densenet-121](https://github.com/onnx/models/blob/main/vision/classification/densenet-121/model/densenet-7.onnx) has several partitions with `conv-bn-mul-add-relu` pattern, for example:
``` go
def @main(%data_0: Tensor[(1, 3, 224, 224), float32] /* ty=Tensor[(1, 3, 224, 224), float32] */) -> Tensor[(1, 1000, 1, 1), float32] {
%0 = nn.conv2d(%data_0, meta[relay.Constant][0] /* ty=Tensor[(64, 3, 7, 7), float32] */, strides=[2, 2], padding=[3, 3, 3, 3], channels=64, kernel_size=[7, 7]) /* ty=Tensor[(1, 64, 112, 112), float32] */;
%1 = nn.batch_norm(%0, meta[relay.Constant][1] /* ty=Tensor[(64), float32] */, meta[relay.Constant][2] /* ty=Tensor[(64), float32] …
```
=> [Relay][transform][SimplifyExpr] simplify adjacent muls and adds with constants

include/tvm/arith/analyzer.h, src/arith/rewrite_simplify.cc, src/arith/transitive_comparison_analyzer.cc, tests/python/unittest/test_tir_transform_simplify.py
Previously, the checks for a literal constraint would find exact matches for an inequality, but any alterations to the conditional would break this exact matching.  This commit introduces checks for constant offsets relative to a known value.  These checks are not always expressible using the existing `ConstIntSetAnalyzer`, which represents allowed values using a single contiguous region.  (e.g. `i!=5` is not representable, because it requires a region for `i<5` and another for `i>5`.)
This implementation reuses the internal representation for inequalities introduced in https://github.com/apache/tvm/pull/12863, along with much of its implementation.  However, the indirect comparisons (e.g. using `a < b` and `b < c` to prove that `a < c`) introduced in that PR still require an explicit …
=> [Arith][TIR] Check for constant offsets of known literal constraints

tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_int8.py
Demonstrates the use of a custom search space generation from a manual written schedule. In this there are no degrees of freedom so tuning will not improve the schedule currently, but the test demonstrates the schedule-time layout transformation of the conv2d primfunc to the 8x8x32 packed layout for convolution ops.
=> [Hexagon] Add E2E test demonstrating how to apply blocked layout schedule to conv2d via metaschedule

src/target/llvm/llvm_instance.cc
Pointers to constructor functions will be placed in section ".ctors" or ".init_array" in a binary file. However, the ".ctors" section is deprecated and Glibc is not going to call the constructor functions in it.
If we use GNU linker ld to link objects (by default), it will convert ".ctors" section to ".init_array" automatically, but not every linker has the compatibility. If we use lld (the LLVM linker) for better runtime performance (such as Link-Time-Optimization) and better compilation efficiency, the constructor functions will not be called, which will cause critical problems.
Adding "UseInitArray" option to target_options_ will generate ".init_array" instead of ".ctors" at compile time, which will solve this problem. This is also Clang's default behavior.
=> [BugFix][LLVM] Add UseInitArray flag in target_options_

docs/conf.py
This disables scipy intersphinx linking for the same reason that
matplotlib and numpy are disabled. Should fix failures like
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4613/pipeline,
though we should investigate if we can switch these back on for release
doc builds
=> [skip ci][docs] Disable scipy intersphinx linking

tests/scripts/ci.py
This parameter was introduced in https://github.com/apache/tvm/pull/12833, and was passed for all subcommands defined using `generate_command`.  However, this broke the `ci.py lint` subcommand.  This PR makes the `additional_flags` parameter to the `docker` function be optional, to avoid this breakage.
=> [CI] Make additional_flags parameter optional in tests/scripts/ci.py

src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc, src/meta_schedule/schedule_rule/schedule_rule.cc
Fixed https://github.com/apache/tvm/issues/13204.
cc @junrushao
=> [MetaSchedule] Fix thread bindings of MultiLevelTilingTensorCore

src/relay/transforms/simplify_expr.cc, tests/python/relay/test_pass_simplify_expr.py
This commit adds SimplifyClipAndConsecutiveCast and SimplifyCastClip to SimplifyExpr Relay pass. These simplify sequence clip->cast->cast and cast->clip based on Clip min/max attributes and Cast target data type.
1) SimplifyClipAndConsecutiveCast example:
%0 == [type=int32]
%1 = clip(%0, a_min=0f, a_max=255f) [type=int32]
%2 = cast(%1, dtype="uint8") [type=uint8]
%3 = cast(%2, dtype="int32") [type=int32]
--> Here Clip dtype == Cast2 dtype and max_value("uint8") == 255
min_value("uint8") == 0
Optimized sequence (both casts can be removed):
%1 = clip(%0, a_min=0f, a_max=255f) [type=int32]
2) SimplifyCastClip example:
%1 = cast(%0, dtype="uint8") [type=uint8]
%2 = clip(%1, a_min=0f, a_max=255f) [type=int8]
Optimized sequence (remove Clip):
%1 = cast(%0, dtype="uint8") [type=uint8]
=> [Relay] Add ClipAndConsecutiveCast and CastClip to SimplifyExpr

python/tvm/contrib/hexagon/pytest_plugin.py
This makes it so that when running tests locally you are able to get a random port. This is needed because the ports take a bit of time to free before they can be used again so repeated tests started to fail. 
cc @masahi @mehrdadh
=> [Hexagon] Make pytest use a random port if not running in CI

include/tvm/runtime/c_runtime_api.h, include/tvm/runtime/device_api.h, jvm/core/src/main/java/org/apache/tvm/Device.java, jvm/core/src/main/java/org/apache/tvm/NDArray.java, jvm/core/src/main/java/org/apache/tvm/rpc/RPCSession.java, python/tvm/_ffi/runtime_ctypes.py, python/tvm/rpc/client.py, python/tvm/runtime/ndarray.py, src/runtime/aot_executor/aot_executor.cc, src/runtime/hexagon/hexagon_common.h, src/runtime/hexagon/hexagon_device_api.cc, src/runtime/hexagon/hexagon_device_api.h
[DLPack][runtime] Update DLPack to v0.7
- Update the `3rdparty/dlpack` git submodule from v0.5 to v0.7, so that the `DLDeviceType` enumeration has an explicitly-stated underlying storage type.  This addresses a compiler warning generated by clang 15.0.3.
- Remove `kDLHexagon` and `kDLWebGPU` from `TVMDeviceExtType`, because those enumerators are now provided by `DLDeviceType`.
- Renumber the members of `TVMDeviceExtType` to reduce the chance of unnoticed collision with members of `DLDeviceType`.
=> [DLPack][runtime] Update DLPack to v0.7

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/rolling_buffer.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_rolling_buffer.py
Hi, this PR ported the rolling_buffer primitive from TE schedule to TensorIR schedule, refer to [[RFC] Introducing a ‘rolling_buffer’ scheduling primitive](https://discuss.tvm.apache.org/t/rfc-introducing-a-rolling-buffer-scheduling-primitive/9836).
The primitive performs the following steps to transform the target buffer into a 'rolling buffer':
1. Collect bound overlaps on the target buffer, and select the outermost rollable axis appeared in the block's loop nest as the 'rolling axis'.
2. Append block predicate to the producer block of the target buffer to avoid recomputation.
3. Use modulo arithmetic to modify the target buffer's read and load indices to circularize the buffer along the rolling dimension.
Note:  The region_cover property of the consumer block of the target buffer will …
=> [TIR][Primitive] Support rolling_buffer schedule primitive in TensorIR

src/relay/op/tensor/transform.cc
It seems that ir text is not parsable without set_attrs_type registry.
```python
%2 = broadcast_to(%1, shape=[128, 1, 28]);
```
=> [Relay] Add set_attrs_type registry to broadcast_to op

CONTRIBUTORS.md
Please join us to welcome @jverma-quic as a new reviewer to TVM. Jyotsna has contributed to the Hexagon TOPI library (avg_pool2d, quantized avgpool) and extended Hexagon Launcher to include custom logging.
- [Commits History](https://github.com/apache/tvm/commits?author=jverma-quic)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:jverma-quic)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/jverma/summary)
=> [COMMUNITY] Jyotsna Verma -> Reviewer

src/meta_schedule/postproc/postproc.cc
I'm working on improving tuning time on quantized models using tensor core. One of the reasons it is slow is that the function below, which is called thousands of times during each evo search initial population sampling, takes more than 50 msec (on my desktop): 
https://github.com/apache/tvm/blob/a4840e7de38c5a2000917f2101f3ec4a374bcd39/src/meta_schedule/search_strategy/evolutionary_search.cc#L506-L517
The time it takes can be broken down into the followings:
* `ApplyToTrace`: 35 msec
* `RewriteTensorize`: 7-8 msec
* `VerifyGPUCode`: 7-8 msec
`RewriteTensorize` is relatively slow because it invokes `sch->Tensorize(...)` which does some heavy lifting. Since it is called thousands of times, it quickly adds up. It is wasteful if the tensorized schedule is rejected by `VerifyGPUCode` …
=> [MetaSchedule] Swap the order of RewriteTensorize and VerifyGPUCode to reduce tuning time

tests/python/frontend/caffe/test_forward.py
=> [CI] Skip failing Caffe tests due to broken URL

python/tvm/driver/tvmc/transform.py, tests/python/driver/tvmc/test_transform.py
This commit ensures that constant folding is applied when a desired layout is selected during compilation. It ensures that `layout_transform` operations are removed where possible so that pattern matching for BYOC backends can work effectively. A test has been added.
=> [TVMC] Apply constant folding when converting layout

docker/install/ubuntu_install_python.sh
This commit applies additional write permission to the "tvm-venv" group virtual environment. Currently after entering a container from a newly built image it dosn't seem possible to install/update Python packages. E.g. updating pip will give errors such as:
```
$ pip install --upgrade pip
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/venv/apache-tvm-py3.7/bin/pip' Check the permissions.
```
Enabling write access for this group fixes this as long as the current user is a member of the "tvm-venv" group.
=> Apply group write permissions to Python virtual environment

python/tvm/rpc/client.py
This PR fixes a typo in rpc/client.py
=> Fix a typo in rpc/client.py

tests/lint/pylint.sh, tests/python/contrib/test_hexagon/pytest_util.py, tests/python/contrib/test_hexagon/test_async_dma_pipeline.py, tests/python/contrib/test_hexagon/test_benchmark_maxpool2d.py, tests/python/contrib/test_hexagon/test_cache_read_write.py, tests/python/contrib/test_hexagon/test_fixed_point_conversion.py, tests/python/contrib/test_hexagon/test_fixed_point_multiply.py, tests/python/contrib/test_hexagon/test_memory_alloc.py, tests/python/contrib/test_hexagon/test_meta_schedule.py, tests/python/contrib/test_hexagon/test_parallel_hvx.py, tests/python/contrib/test_hexagon/test_parallel_hvx_load_vtcm.py, tests/python/contrib/test_hexagon/test_parallel_scalar.py, tests/python/contrib/test_hexagon/test_run_unit_tests.py, tests/python/contrib/test_hexagon/test_sigmoid.py, tests/python/contrib/test_hexagon/test_software_pipeline_async.py, tests/python/contrib/test_hexagon/test_vtcm_bandwidth.py, tests/python/contrib/test_hexagon/test_wo_qnn_canonicalization.py
This PR adds pylint to more tests in `tests/python/contrib/test_hexagon` and enables pylint for future tests that are added to this directory.
Sub directories are not included yet except `tests/python/contrib/test_hexagon/conv2d`.
=> [Hexagon] Add pylint on tests

src/relay/backend/graph_plan_memory.cc, src/relay/backend/te_compiler_cache.cc, src/relay/transforms/remove_standalone_reshapes.cc, src/te/operation/compute_op.cc, src/tir/ir/data_type_rewriter.cc, src/tir/schedule/primitive/cache_index.cc
- Fix clang 15.0.3 `-Wunused-but-set-variable` and `-Wunused-lambda-capture` warnings by removing / commenting-out code.
=> [build][relay][te][tir] remove unused vars / args

.asf.yaml
This reverts commit 5acf3f90c63b6760cd23796b442f8ac20e645af0.
Reverting since this is causing some spam from the ASF Infra bot related
to https://issues.apache.org/jira/browse/INFRA-23834. As in that issue
the protections have been applied manually by ASF Infra so this revert
shouldn't have any real effect
=> [skip ci] Revert "[ci] Protect release branches (#13208)"

docs/install/from_source.rst
This commit indicates how to install minimal set of dependencies for building 
Apache TVM on Fedora and CentOS. It supplements existing information for
Ubuntu and MacOS.
=> [Docs] Minimal dependencies for Fedora/CentOS

src/tir/transforms/profile_instrumentation.cc
Fix code to address a valid `-Wredundant-move` clang warning.
=> [build][tir] fix clang redundant-move warning

python/tvm/relay/op/contrib/ethosn.py, src/relay/backend/contrib/ethosn/codegen_ethosn.h, src/relay/backend/contrib/ethosn/inline_partitions.cc, tests/python/contrib/test_ethosn/infrastructure.py, tests/python/contrib/test_ethosn/test_addition.py, tests/python/contrib/test_ethosn/test_concatenate.py, tests/python/contrib/test_ethosn/test_depth_to_space.py, tests/python/contrib/test_ethosn/test_inline_partitions.py, tests/python/contrib/test_ethosn/test_leaky_relu.py, tests/python/contrib/test_ethosn/test_multiply.py, tests/python/contrib/test_ethosn/test_networks.py, tests/python/contrib/test_ethosn/test_relu.py, tests/python/contrib/test_ethosn/test_requantize.py, tests/python/contrib/test_ethosn/test_reshape.py, tests/python/contrib/test_ethosn/test_split.py, tests/python/contrib/test_ethosn/test_tanh.py, tests/python/contrib/test_ethosn/test_topologies.py
Adds a pass that analyzes functions partitioned for the NPU and inlines those that are deemed "non-compute-intensive" back to the main function so that they can be considered for other backends. The current heuristic for deciding a non-compute-intensive function is to collectively check all of the operations in the function have no multiply accumulate operations. This heuristic is not optimal; optimization is left for future exploration.
This pass is inspired by the "IsComputeIntensiveGraph" pass in the TensorRT integration.
cc @ashutosh-arm @leandron
=> [ETHOSN] Inline non-compute-intensive partitions

include/tvm/meta_schedule/search_strategy.h, python/tvm/meta_schedule/search_strategy/evolutionary_search.py, src/meta_schedule/search_strategy/evolutionary_search.cc, tests/python/unittest/test_meta_schedule_search_strategy.py
This PR introduces a new argument for EvolutionarySearch that limites the failures (defined as rounds of no new generated candidate) in the `SampleInitPopulation` stage. In this way we can avoid the task to be hanging forever in special cases, e.g., some postproc always fails. This should fix #12330.
=> [MetaSchedule] Fix Task Hanging in EvolutionarySearch

python/tvm/tir/schedule/_type_checker.py
Current type checker for TIR schedule had issue with typing for Python 3.9. 
This simple patch fixes this problem. 
cc. @junrushao @Lunderberg
=> [Bugfix][TIR] Fix version conflict with `typing` for Python 3.9 

python/tvm/meta_schedule/testing/torchbench/run.py, python/tvm/meta_schedule/testing/torchbench/utils.py
This PR adds features to the `python/tvm/meta_schedule/testing/torchbench/run.py`.
- Integrate with the TVM PyTorch integration to handle boolean tensor and unaligned memory.
- Deduplicate collected tuning tasks to prevent thousands of tasks created by hundreds of subgraphs with similar structure.
- Add option to cast model to float32, which are more stable numerically than float16 and prevents inaccurate result from many models.
- Add option to choose search strategy in MetaSchedule.
- Inspect output error if the actual output doesn't match the expectation. Also save the actual output and expected output for further analysis if needed.
- Save subgraphs and their example input for debug purpose.
- Print MetaSchedule profiling information at the end of execution.
- Detach PyTorch tensor …
=> [MetaSchedule] Improve the script for TorchBench model tuning & benchmarking

src/relay/op/nn/nn.cc
This PR adds a rank check for input tensor in type inference of `nn.instance_norm`. I explain the reasons as follows:
First, according to the definition of [Instance Normalization](https://paperswithcode.com/method/instance-normalization), it only normalizes the spatial dimensions. Therefore, the input tensor must be of at least rank 3, and otherwise the operator will not produce meaningful results. 
Second, `nn.instance_norm` with tensor rank less than 2 leads to a problem in the `SimplifyInference` optimization pass. This pass finds the reduced axes before converting the operator to its lower-level computation definition:
https://github.com/apache/tvm/blob/f15afd225140e2a501b8b6aa2def0fd94d31bc54/src/relay/transforms/simplify_inference.cc#L149-L152
If the rank of the input tensor is …
=> [Relay] Add tensor rank check for `nn.instance_norm`

src/relay/analysis/util.cc, src/relay/ir/dataflow_matcher.cc, src/relay/transforms/pattern_utils.h, src/relay/transforms/simplify_expr.cc, tests/python/relay/test_pass_fold_scale_axis.py, tests/python/relay/test_pass_simplify_expr.py
* add(%1, %1) convert to multiply(%1, 2f)
* enhance fold_scale_axis to fold multiply(%1, 2f) into conv
Signed-off-by: Lei Wen <wenlei03@qiyi.com>
=> [Relay] Enhancement for fold_scale_axis and simplify_expr

CONTRIBUTORS.md
Please join me to welcome @ashutosh-arm  as a new committer. Ashutosh contributes to the CMSIS-NN code generations and code generation components.
- [Commits History](https://github.com/apache/tvm/commits?author=ashutosh-arm)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:ashutosh-arm)
=> [skip-ci][COMMUNITY] New committer Ashutosh Parkhi

src/arith/rewrite_simplify.cc, src/arith/rewrite_simplify.h, tests/python/unittest/test_arith_rewrite_simplify.py, tests/python/unittest/test_index_map.py, tests/python/unittest/test_tir_transform_inject_software_pipeline.py, tests/python/unittest/test_tir_transform_simplify.py
Prior to this commit, the result of TryCompare would only be used if it could definitively prove a conditional to be either true or false. For example, if it is known that `0 <= i`, a conditional of `i <= 0` would be left as-is.
This commit introduces rewrite rules to preferentially simplify into more restrictive conditions.  Using the same example, if it is known that `0 <= i`, a conditional of `i <= 0` would be simplified into `i == 0`.  Similarly, if it is known that `0 <= i`, a conditional of `i != 0` would be simplified into `0 < i`.
Because this change does not introduce significant overhead, as the results of `RewriteSimplifier::Impl::TryCompare` are already available, this change is enabled for all use cases and does not require a call to `RewriteSimplifier::SetEnabledExtensions`.
=> [TIR][Arith] Use TryCompare to narrow inequalities if possible

src/runtime/hexagon/rpc/simulator/session.cc
Remove unused member variable in the `SimulatorRPCChannel` class. Fixes a clang warning.
=> [build][hexagon] remove unused variable

src/relay/ir/dataflow_matcher.cc, tests/python/relay/test_dataflow_pattern.py
The PatternGroup doesn not check if the FunctionPattern is matched while processing the FunctionPattern, but when FunctionPattern is nested with AltPattern, the FunctionPattern may not be matched, resulting in a crash when looking up matched nodes.
This commit adds a check at handling FunctionPattern to fix this crash, same as the checks at handling other patterns(such as `dataflow_matcher.cc:667`)
cc @masahi @wrongtest-intellif
=> [BugFix][Pattern] Fixed a crash when AltPattern and FunctionPattern are used nested

include/tvm/tir/stmt_functor.h, src/tir/transforms/narrow_datatype.cc
Suppress a spurious `-Woverloaded-virtual` clang warning for the `tvm::tir::DataTypeRewriter` class.
I think we're safe to ignore clang _version_ for this pragma, because it's been supported for a long time now.
=> [build][tir] suppress -Woverloaded-virtual warning

src/tir/schedule/ir_comparator.cc
Pretty straight forward addition of logging to the to comparator so that its clear why tensor intrins are not matching. 
cc @csullivan
=> [Tensorize] Add logs to comparator to make debugging tensorize failures easier

python/tvm/te/operation.py, tests/python/relay/test_op_level1.py, tests/python/unittest/test_te_create_primfunc.py
Currently, when compiling MobileBERT on x86, we get a crash from https://github.com/apache/tvm/blob/11d22bdc1bd45d952eb140684e64f01438b7f516/src/tir/transforms/arg_binder.cc#L102-L106.
This is caused from the subgraph attached in the test. Since https://github.com/apache/tvm/pull/11341, `concatenate` is implemented as a TE extern on x86. `te.extern(...)` doesn't explicitly set the `elem_offset` parameter of input / output buffers it creates, which ends up `elem_offset` of these buffers being the default value, 0. This causes a problem from the above check in `BindBuffer`, since the subgraph does create a non-zero `elem_offset` slice from a buffer whose `elem_offset` is set to zero. 
Since we don't require buffers created in `te.extern(...)` to have zero `elem_offset`, we can avoid this …
=> [TE] Make `elem_offset` of the buffers created by `te.extern` a variable to avoid crash

src/tir/transforms/loop_partition.cc, tests/python/unittest/test_tir_transform_loop_partition.py
Preserve loop annotations when the loop is get partitioned. Also we bind the loop region info to the analyzer for some cases 
some partition condition could not get solved due to unknown (but trivial) loop region.
=> [TIR] Preserve loop annotation after loop partitioning

gallery/tutorial/tvmc_python.py
Update tvmc tutorial code to use correct argument for reusing tuning records. Specifically, current code uses `tuning_records`, which is meant for saving the generated tuning results, not reusing prior results. We should use `prior_records` instead.
=> [docs][tvmc] Use correct argument to reuse tuning records

cmake/modules/Hexagon.cmake
When building tvm runtime with hexagon we face the below error if USE_HEXAGON_EXTERNAL_LIBS is not defined. This happens because USE_HEXAGON_EXTERNAL_LIBS=OFF is defined as the default in CMakeLists.txt. The modified condition can check for all cases including undefined variable, empty string and OFF
```
CMake Error at cmake/modules/Hexagon.cmake:203 (message):
Invalid use of USE_HEXAGON_EXTERNAL_LIBS=OFF; USE_HEXAGON_EXTERNAL_LIBS
only supports absolute paths and git repository urls
Call Stack (most recent call first):
CMakeLists.txt:477 (include)
```
=> [Hexagon] Fix Hexagon external libs check

docs/dev/tutorial/codebase_walkthrough.rst, src/runtime/threading_backend.cc
On Android `sched_setaffinity ` should use `pid_t` instread of `pthread_t`,  
https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html
On Android 21+, there is `pid_t pthread_gettid_np(pthread_t);` to convert the `std::thread::native_handle_type`  to `pid_t`, 
```cpp
pid_t pthread_gettid_np(pthread_t __pthread) __INTRODUCED_IN(21);
```
=> [Bugfix][Runtime] Fix sched_setaffinity in Android

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Fixes https://github.com/apache/tvm/issues/12292
Fixes https://github.com/apache/tvm/issues/13296
PyTorch uses the same op, `aten::index`, to represent indexing by both integer indices and a boolean mask. In our PT converter, Relay `adv_index` op is used to convert `aten::index`, but it doesn't correctly recognize indexing by mask - it will treat True / False as indices 0 / 1. So our converter generates an invalid model if the PT model uses such indexing, see https://github.com/apache/tvm/issues/12292 and https://github.com/apache/tvm/issues/13296.
I fixed this issue by explicitly tuning the mask into integer indices using `argwhere`, which will also take care of the inherent dynamism in indexing by mask.
cc @comaniac @junrushao @shingjan @yelite
=> [Torch] Fix advanced indexing with boolean mask

python/tvm/topi/x86/tensor_intrin.py
VNNI dot product instruction vpdpbusd would add the result to the dst. There is no need to use an additional add.
=> [TOPI] Enhance VNNI dot product

src/driver/driver_api.cc
Currently one version of `tvm::LowerSchedule` doesn't pass along the input `simple_mode` flag, which causes it to default back to `false`. This commit fixes it by passing along the input flag.
=> [BugFix][Driver] Correctly propogate simple-mode flag in LowerSchedule

python/tvm/micro/project_api/client.py, python/tvm/micro/session.py
Currently, the RPC session on C/C++ side does not know if the session was closed on python side which causes extra read/write on transport while the session is already closed. This PR reuses the hexagon approach in microTVM to shutdown the RPC session.
=> [microTVM] Fix RPC session close on runtime side

src/runtime/hexagon/hexagon_htp.cc, src/runtime/hexagon/hexagon_thread_manager.cc
Temporarily moves lock/unlock for HTP to the main thread instead of its own thread, until we are fully pipelined.
cc: @csullivan
=> [Hexagon] [runtime] Move lock/unlock to HexagonHtp temporarily

src/tir/transforms/thread_storage_sync.cc, tests/python/unittest/test_tir_transform_thread_sync.py
This PR updates the `src/tir/transforms/thread_storage_sync.cc`, to make it insert storage sync if the access index doesn't depend on the innermost thread index, i.e., being constant wit respect to the innermost thread id. 
This fixes an accuracy problem on model https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models/timm_efficientdet
cc @junrushao @vinx13
=> [TIR] Add thread sync if access index doesn't depend on thread index

src/relay/backend/contrib/libtorch/libtorch_codegen.cc, tests/lint/cpplint.sh
Add clang-format disable for header to prevent reorder. Torch header file need to be put at the end since torch's dlpack is a little different with tvm's.
cc @t-vi @masahi
Signed-off-by: Lei Wen <wenlei03@qiyi.com>
=> Fixup libtorch backend build

src/printer/tvmscript_printer.cc, tests/python/unittest/test_tvmscript_roundtrip.py
Because the majority of TIR PrimFuncs operate on buffers, write their outputs to an output parameter, and do not return a value, the `-> None` in the function signature becomes visual noise. This commit removes printing of the return type in cases where the PrimFunc has no return value.
=> [TVMScript] Hide trailing return type if None

python/tvm/tir/tensor_intrin/arm_cpu.py, python/tvm/tir/tensor_intrin/x86.py, tests/python/unittest/test_meta_schedule_postproc_rewrite_tensorize.py, tests/python/unittest/test_meta_schedule_trace_apply.py
Similar to #12588 , this optimizes VNNI intrin in TIR.
In a 16x1024x1024 batch matmul on cascade lake CPU, it reduces the time from 6.97ms to 6.72ms (4% faster)
cc @masahi
=> [TIR] Remove redundant add in vnni/arm intrin

python/tvm/relay/backend/aot.py, src/relay/backend/aot/aot_lower_main.cc, src/relay/backend/aot/create_executor_metadata.cc, src/relay/backend/aot/create_executor_metadata.h, src/relay/backend/utils.h, tests/python/relay/aot/test_aot_create_executor_metadata.py, tests/python/relay/aot/test_pass_aot_lower_main.py
Tracking issue: https://github.com/apache/tvm/issues/12548
AOT requires the ExecutorCodegenMetadata object to be populated containing various pieces of information about the compiled module. This commit adds a separate analysis pass to create the metadata + some tests for the new pass.
=> [AOT] Add CreateExecutorMetadata analysis pass

docs/conf.py, gallery/how_to/work_with_microtvm/micro_aot.py, gallery/how_to/work_with_microtvm/micro_pytorch.py, src/runtime/crt/host/Makefile.template, src/runtime/crt/host/microtvm_api_server.py, tests/scripts/task_python_microtvm.sh
This PR adds a tutorial to compile/run a PyTorch model using microTVM CRT.
=> [microTVM][PyTorch][Tutorial]Adding a PyTorch tutorial for microTVM with CRT

src/meta_schedule/trace_apply.cc, tests/python/unittest/test_meta_schedule_trace_apply.py
Note: the diff is bloated due to the test case.
In anchor-block tuning, we need to manually apply `AutoInline` to some blocks (those that are not part of the anchor subgraph). Currently the order of blocks to apply `AutoInline` is undefined, but I've hit a case where this is problematic. 
For example, given these four blocks,
```
for i0_7, i1_7, i2_7, i3_7 in T.grid(16, 56, 56, 256):
with T.block("compute_2"):
i0_8, i1_8, i2_8, i3_8 = T.axis.remap("SSSS", [i0_7, i1_7, i2_7, i3_7])
T.reads(T_subtract_1[i0_8, i1_8, i2_8, i3_8])
T.writes(compute_3[i0_8, i1_8, i2_8, i3_8])
compute_3[i0_8, i1_8, i2_8, i3_8] = T.q_multiply_shift(T_subtract_1[i0_8, i1_8, i2_8, i3_8], 1457846997, 31, 0, dtype="int32")
for i0_9, i1_9, i2_9, i3_9 in T.grid(16, 56, 56, 256):
with T.block("compute_3"):
i0_10, i1_10, …
```
=> [MetaSchedule] Fix the order of applying `AutoInline` in `ScheduleUsingAnchorTrace`

python/tvm/meta_schedule/profiler.py, python/tvm/meta_schedule/testing/custom_builder_runner.py, python/tvm/meta_schedule/testing/tune_utils.py, python/tvm/meta_schedule/testing/validate_database.py
This PR introduces a validation script to check result accuracy between the scheduled IRModules and original IRModule stored in MetaSchedule database. The validate function could also be reused for other type of databases in MetaSchedule. The result would be printed out on the screen as validation passed or failed at some records.
CC @junrushao
When running checks the expected output looks like:
```bash
Progress      1 /   1003 checked.
Progress      2 /   1003 checked.
Progress      3 /   1003 checked.
Progress      4 /   1003 checked.
Progress      5 /   1003 checked.
...
```
If everything runs well, the script will print out a `Validation passed!` in the end.
If there's any unexpected error or unmatched results, it will print out the IRModules, inputs or exceptions.
```python
Progress …
```
=> [MetaSchedule] Add JSON Database Validation Scripts

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
QLinearMatMul has supported rank =2 only for both input tensors.
It was extended using _qnn.op.dense and _qnn.op.batch_matmul for all ranks
Y = X*W
Works:
1. int8 and int8 or uint8 and uint8 input data types
2. x_rank = 1, w_rank = 2
3. x_rank = 2, w_rank = 2
4. x_rank > 2, w_rank = 2
5. x_rank = any >= w_rank > 2
Note: Different types of input tensors (int8 and uint8) does not work currently
=> [QNN, ONNX] Extension of QLinearMatMul in ONNX front-end for all ranks of input tensors

src/tir/schedule/primitive/compute_inline.cc, tests/python/unittest/test_meta_schedule_trace_apply.py, tests/python/unittest/test_tir_schedule_compute_inline.py
Currently, even if a producer block has a non-trivial predicate, `ReverseComputeInline` goes ahead and produces buggy a schedule. The real-world example I've hit was the following. After `ReverseComputeInline` the  `compute_4` block, the predicate (`(ax1_0 * 4 + ax1_1) * 32 + ax1_2) * 2 + ax1_3 < 64`) disappears. See https://gist.github.com/masahi/01a80b86062122ad57b9b1fd785fb960 for a repro.
```
...
for ax0, ax1_0, ax1_1, ax1_2, ax1_3 in T.grid(32, 1, 4, 32, 2):
with T.block("conv2d_nhwc_reindex_shared"):
T.where(((ax1_0 * 4 + ax1_1) * 32 + ax1_2) * 2 + ax1_3 < 64)
v0 = T.axis.spatial(50176, ax2_0_0_ax3_0_0_fused // 4 * 6272 + ax2_0_1_ax3_0_1_fused * 32 + ax0)
v1 = T.axis.spatial(256, ax2_0_0_ax3_0_0_fused % 4 * 64 + (ax1_0 * 256 + ax1_1 * 64 + ax1_2 * 2 + ax1_3))
T.reads(p7[()], …
```
=> [TIR] Check producer predicate in `ReverseComputeInline`

python/tvm/topi/cuda/conv2d_transpose.py, tests/python/topi/python/test_topi_group_conv2d_transpose.py
Fixes the issue reported in https://discuss.tvm.apache.org/t/model-compilation-fails-on-gpu-target/13866
For certain `conv2d_transpose` workloads, we get funny allocations like
```
allocate data_pad[float32 * ((floordiv(((blockIdx.y*2) + 1), 3)*4608) + 576)], storage_scope = shared
allocate p1.shared[float32 * ((floordiv(((blockIdx.y*2) + 1), 3)*12288) + 1536)], storage_scope = shared
```
This is apparently due to trying to split a small channel by a large factor. 
cc @vinx13
=> [TOPI] Fix conv2d transpose for small channel

python/tvm/testing/__init__.py, python/tvm/testing/tir.py, tests/python/unittest/test_tvmscript_error_report.py, tests/python/unittest/test_tvmscript_syntax_sugar.py
We moved most of the IR definition into the testing methods correspondingly.
=> [Minor][Testing] Consolidate IRs into corresponding functions

python/tvm/contrib/hexagon/tools.py, tests/python/contrib/test_hexagon/infrastructure.py, tests/python/contrib/test_hexagon/test_2d_physical_buffers.py, tests/python/contrib/test_hexagon/test_benchmark_maxpool2d.py, tests/python/contrib/test_hexagon/test_memory_alloc.py, tests/python/contrib/test_hexagon/test_sigmoid.py, tests/python/contrib/test_hexagon/topi/slice_op/test_argmax_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_avg_pool2d_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_cast_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_clip_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_conv2d_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_depthwise_conv2d_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_dequantize_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_max_pool2d_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_relu_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_softmax_slice.py, tests/python/contrib/test_hexagon/topi/slice_op/test_tanh_slice.py, tests/python/contrib/test_hexagon/topi/test_add_subtract_multiply.py, tests/python/contrib/test_hexagon/topi/test_depth_to_space.py, tests/python/contrib/test_hexagon/topi/test_quantize.py, tests/python/contrib/test_hexagon/topi/test_reshape.py, tests/python/contrib/test_hexagon/topi/test_resize2d.py
Move this API to the hexagon contrib module so that it can be accessed by tests outside of TVM source control.
=> [Hexagon] Make allocate_hexagon_array a hexagon contrib API

python/tvm/relay/backend/contrib/ethosu/tir/compiler.py, src/tir/contrib/ethosu/passes.cc, tests/python/contrib/test_ethosu/test_encode_constants.py, tests/python/contrib/test_ethosu/test_merge_constants.py
This PR fixes the bug in MergeConstants pass on striped networks on Ethos-U NPU.
The issue was caused by _DivideConstants_ pass which is introducing new mod parameters and changing their order. So ethosu_write parameter in some cases is moved from the end of the list to the middle.
E.g. from:
`[ethos-u_0_i0, p1, p2, p3, p4, p5, p6, ethosu_write]`
To:
`[ethos-u_0_i0, p1, p2, ethosu_write, placeholder, placeholder, placeholder, placeholder, placeholder, placeholder, placeholder, placeholder]`
Updated version of the  _GetArgsToMergeWithoutArgsNotInConstDict_ and _MakeNewConstDict_ methods in passes.cc can now correctly modify const_dict according to the new parameter list.
cc @leandron
=> [microNPU] Fixed MergeConstants pass on striped networks

python/tvm/driver/tvmc/autotuner.py, python/tvm/driver/tvmc/compiler.py, python/tvm/driver/tvmc/transform.py, tests/python/driver/tvmc/conftest.py, tests/python/driver/tvmc/test_autotuner.py, tests/python/driver/tvmc/test_compiler.py, tests/python/driver/tvmc/test_frontends.py, tests/python/driver/tvmc/test_transform.py
Comes as a followup from conversations in #13216. By making the pass context a global value for both `compile` and `tune` commands, we can ensure the pass context is exactly as the user expected and also test components such as `convert_graph_layout` under a pass context suitable for testing (e.g. add instruments). With this change, it becomes the users responsibility to ensure the PassContext they select is suitable for the passes that will be run. By default, `opt_level` remains as 3 so current workflows that do not alter the pass context from the command line / TVMC Python API should not be affected.
=> [TVMC] Global pass context for compile and tune

apps/microtvm/reference-vm/base-box-tool.py, apps/microtvm/reference-vm/base-box/base_box_setup.sh, docker/Dockerfile.ci_arm, docker/Dockerfile.ci_cortexm, docker/Dockerfile.ci_cpu, docker/Dockerfile.ci_gpu, docker/Dockerfile.ci_hexagon, docker/Dockerfile.ci_i386, docker/Dockerfile.ci_minimal, docker/Dockerfile.ci_riscv, docker/Dockerfile.ci_wasm, docker/Dockerfile.demo_android, docker/Dockerfile.demo_rocm, docker/Dockerfile.demo_vitis_ai, docker/Dockerfile.docs, docker/install/ubuntu_install_nrfjprog.sh, docker/install/ubuntu_setup_tz.sh
This PR refactors timezone setup to a separate script that docker/install/ubuntu_install_core.sh
Also, it adds a script to install NRF and reused in both cortexm docker and RVM installation path.
=> [Docker]Refactor timezone script and NRF installation

src/arith/const_fold.h
This PR fixes the checking of devisor in constant folding of `tir::Div`. If the expression is `0. / 0.`, previous implementation directly folds it to `0.` without checking the divisor. It seems that `fb->value != 0` should not be in the `if` condition, but should be checked in the body instead. After this fix, folding `0. / 0.` leads to an assertion failure instead of `0.`. 
Here is a piece of simple testing code:`tir.FloatImm('float32', 0.) / tir.FloatImm('float32', 0.)`. And the following is the error report (which is expected):
```
File "/Users/tvm-bug/bug_divide_zero.py", line 5, in <module>
tir.PrimFunc([], tir.Evaluate(tir.FloatImm('float32', 0.) / tir.FloatImm('float32', 0.)))
File "/Users/wzh/tvm-dev/python/tvm/tir/expr.py", line 102, in …
```
=> [TIR][Arith] Fix divisor checking in `TryConstFold`

src/meta_schedule/schedule_rule/apply_custom_rule.cc, tests/python/unittest/test_meta_schedule_schedule_rule_apply_custom_rule.py
Previously this ffi registry for `ApplyCustomRule` schedule rule has a typo in #13195, which prevented it from functioning correctly. This PR fixes the typo and added a regression test.
=> [MetaSchedule][Minor] Fix Typo in ApplyCustomRule Schedule Rule

src/meta_schedule/measure_callback/update_cost_model.cc, src/meta_schedule/utils.h, tests/python/unittest/test_meta_schedule_measure_callback.py
This PR introduces a check to prevent records with run time of zero into the training data of cost model. This is because when working on microTVM there're cases where the run time of certain successful runs is very tiny, such that it got recorded as zero. In such cases, the runtime of 0 would break XGBoost model because it introduces infinite running speed in GFLOPs. A regression test was also added.
=> [MetaSchedule][Minor] Allow Zero Run Time In Benchmarking Result

python/tvm/tir/schedule/_type_checker.py
It seems like there is some inconsistency across the python versions and make PR https://github.com/apache/tvm/pull/13269 fails at Python 3.10. 
This patch fixes this issue. 
cc. @junrushao @wrongtest-intellif @vinx13
=> [Bugfix][TIR] Patch for PR#13269 to support Python 3.10

src/meta_schedule/schedule_rule/apply_custom_rule.cc, src/meta_schedule/space_generator/post_order_apply.cc, tests/python/integration/test_auto_tensorize.py
Currently, if there is a block annotated with `schedule_rule`, only the corresponding custom rule is allowed to be applied to the block. This led to the breakage of auto tensorization as discussed in https://github.com/apache/tvm/pull/13195#discussion_r1018952166.
The fix is to unannotate `schedule_rule` if the corresponding schedule func is not found, to let other schedule rules process this block.
=> [MetaSchedule] Unannotate `schedule_rule` if corresponding schedule func is not found

python/tvm/meta_schedule/testing/torchbench/run.py
This PR makes the `python/tvm/meta_schedule/testing/torchbench/run.py` script skip optimizing empty fx graph. 
This unblocks tuning models like moco and detectron for which TorchDynamo will generate empty fx graph.
=> [MetaSchedule] Skip empty fx graph in TorchBench tuning script

src/meta_schedule/postproc/rewrite_cooperative_fetch.cc, src/meta_schedule/schedule_rule/multi_level_tiling.cc, src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_tc.py
Currently, vectorization of shared to global store in tensor core auto tensorization is not done properly, since most blocks have the `T.where` predicate which disables vectorization. 
The predicate is introduced after `Split` in cooperative fetch: https://github.com/apache/tvm/blob/main/src/meta_schedule/postproc/rewrite_cooperative_fetch.cc#L159-L162
As the code says, this split is supposed to be applied to a fused loop. This is the case for cache read blocks, where `AddReadReuse` explicitly fuses loops around cache read blocks. But `AddWriteReuseTensorCore` doesn't fuse loops after cache write: https://github.com/apache/tvm/blob/main/src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc#L260-L262. 
So for cache rewrite blocks, we always try to split a single axis by large …
=> [MetaSchedule] Fuse loops around shared to global store block in `MultiLevelTilingTensorCore`

src/tir/schedule/analysis/analysis.cc, src/tir/schedule/primitive/get_block_loop.cc
Currently there are two versions of `GetConsumers()` and `GetProducers()` implementation. Make them consistent to avoid possible bug when there are WAR dependencies.
=> [TIR][Schedule] Make consistent implementation for GetProducers() & GetConsumers()

src/relay/backend/contrib/constant_transforms.cc, src/relay/backend/contrib/constant_transforms.h, src/relay/backend/contrib/ethosn/convert_equivalent.cc, src/relay/quantize/realize.cc, src/relay/quantize/realize.h, src/relay/transforms/fold_constant.cc, src/relay/transforms/fold_constant.h, src/relay/transforms/simplify_expr.cc
Refactor duplicated and low-level logic for applying constant-folding over an `Expr` into a utility function.
=> [Relay] Refactor constant folding over expr into a utility function

python/tvm/script/tir/intrin.py, src/printer/tvmscript_printer.cc, tests/python/contrib/test_hexagon/test_async_dma_pipeline.py, tests/python/contrib/test_hexagon/test_parallel_hvx_load_vtcm.py, tests/python/unittest/test_aot_legalize_packed_call.py, tests/python/unittest/test_meta_schedule_space_cuda.py, tests/python/unittest/test_tir_transform_inject_software_pipeline.py, tests/python/unittest/test_tir_transform_inject_virtual_thread.py, tests/python/unittest/test_tir_transform_thread_sync.py, tests/python/unittest/test_tvmscript_roundtrip.py
Motivation example: in the current TVMScript, the snippet below:
```python
@T.prim_func
def func(...):
A = T.match_buffer[(128 * 128), "float32"]
^^^^^^^^^^^
```
is actually different from this one:
```python
@T.prim_func
def func(...):
A = T.match_buffer[(16384, ), "float32"]
^^^^^^^^^
...
```
This is because 128 * 128 is not immediately constant-folded into 16384, but becomes an AST node: `T.Mul(128, 128)`. This can be quite error-prone if not used carefully.
As part of effort of more formal TIR semantics, we want to more explicitly differentiate TIR AST nodes (defined in `tir/expr.h`) and TIR ops (defined in `tir/op.h`). The naming convention is that:
- Lowercased methods, for example, `tvm.tir.mul` or operator `*`, means an TIR op, which will be eagerly constant-folded, i.e. `mul(1, …
=> [TIR] Make syntax of AST nodes different than ops

include/tvm/script/ir_builder/tir/frame.h, include/tvm/script/ir_builder/tir/ir.h, python/tvm/script/ir_builder/tir/frame.py, python/tvm/script/ir_builder/tir/ir.py, python/tvm/tir/op.py, src/script/ir_builder/tir/frame.cc, src/script/ir_builder/tir/ir.cc, tests/python/unittest/test_tvmscript_error_report.py, tests/python/unittest/test_tvmscript_ir_builder_tir.py
This PR adds all common TIR intrinsics like `T.int32x4`, `T.floatx4`.
=> [IRBuilder][Minor] Add intrinsics like `T.int32x4`

src/tir/schedule/primitive/cache_read_write.cc, tests/python/unittest/test_tir_schedule_cache_read_write.py
Fix 2 issues of cache related primitives:
*  Fix region_cover checking for cache related primitives
*  Fix CacheLocDetector for nested SeqStmt
cc @Hzfengsy @wrongtest-intellif
=> [TIR][Schedule] Fix cache_read loc detecting and region_cover checking

ci/scripts/github_skipped_tests_comment.py, ci/scripts/required_tests_to_run.json, tests/python/ci/test_ci.py
In this PR, the skipped tests script will also check if tests in the `required_tests_to_run.json` have not been skipped. If there are skipped tests, they will be added to the returned comment. 
I am not entirely sure where it's best to place the `required_tests_to_run` file, so I left it in `tvm/ci/scripts/`. I am happy to take suggestions.
Aims to prevent situations such as #12529
=> [ci] Assert some tests are not skipped in the CI

src/tir/schedule/primitive/layout_transformation.cc, src/tir/schedule/state.cc, tests/python/unittest/test_tir_schedule_transform_layout.py
Preivously, the block SREF reuse only included a single step of changes, and would have an incorrect mapping if multiple sequential changes to the TIR block occurred.  This could happen if a `BufferStore` was updated, followed by replacement of `Block` iter vars/values.  This commit tracks the Block replacements across each usage, to ensure the SREF instances remain valid.
=> [TIR][Bugfix] Fix AXIS_SEPARATORS in tir.Schedule.transform_layout

Jenkinsfile, ci/jenkins/Prepare.groovy.j2
Merging #13368 caused CI to pass but run more than it needed to due to
some failures in determination. This fixes the interpolation to use `"`
which should correctly pass through the variables
=> [ci] Fix Jenkins quoting

Jenkinsfile, ci/jenkins/Prepare.groovy.j2
This PR does not merge `main` if CI is running already on `main`. It aims to avoid a case where a race happens between two subsequent commits, and one of them merges the other.
Fixes #12392.
=> [CI] Do not merge before running CI on main

src/target/source/codegen_cuda.cc, tests/python/topi/python/test_topi_transform.py
CUDA codegen fails to generate `T.ramp(T.int64(0), T.int64(1), 2)]` correctly.
This is a legal IR that appears after a recent commit to simplify cast and ramp. Fixed https://github.com/apache/tvm/issues/13379.
cc @comaniac @junrushao
=> [Codegen] Fix CUDA codegen for int64 Ramp

include/tvm/meta_schedule/mutator.h, include/tvm/meta_schedule/postproc.h, include/tvm/meta_schedule/schedule_rule.h, src/meta_schedule/mutator/mutator.cc, src/meta_schedule/postproc/postproc.cc, src/meta_schedule/schedule_rule/schedule_rule.cc, src/meta_schedule/space_generator/space_generator.cc
This PR introduces default schedule rules, post processors and mutators for LLVM VNNI targets. The usage of default vnni classes will automatically be generated if using `from-target` as parameters.
Co-authored-by: Michal Piszczek <michalp@uw.edu>
=> [MetaSchedule] Add `from-target` Defaults for LLVM VNNI Targets

python/tvm/relay/frontend/tflite.py, src/relay/qnn/op/convolution_transpose.cc, src/relay/qnn/op/dense.cc, src/relay/qnn/op/requantize.cc, tests/python/contrib/test_ethosn/test_convert_equivalents.py, tests/python/frontend/tflite/test_forward.py, tests/python/relay/test_op_qnn_requantize.py
This enables int64 biases for quantized fully connected, requantize and transpose convolution in TFLite networks. It goes on top of existing int16 support for TFLite frontend.
cc @areusch for reviews
=> [TFLite] Enable int64 biases for int16 quantized operators

apps/howto_deploy/prepare_test_libs.py
Update the example with the newer API.
=> [Fix][Warning] tvm.target.create() deprecated

src/relay/backend/aot/create_function_metadata.cc, tests/python/relay/aot/test_aot_create_function_metadata.py
Device contexts created handles with no corresponding buffer which would confuse CreateFunctionMetadata causing a segfault. The logic has been changed to check that a buffer exists and a test updated to include this case.
=> [AOT][FIX] Handle device contexts properly in CreateFunctionMetadata

src/meta_schedule/measure_callback/update_cost_model.cc, src/meta_schedule/postproc/rewrite_layout.cc, src/te/operation/create_primfunc.cc, tests/python/unittest/test_meta_schedule_postproc_rewrite_layout.py, tests/python/unittest/test_te_create_primfunc.py
Currently when `CacheRead` and `RewriteLayout` are used together, the index map is derived based on the cache read block, which leads to weird result. This is because the current implementation assumes that the "layout-free" buffer is directly consumed by an "anchor" op such as conv2d or dense.
When `CacheRead` is involved, we need to find the index map for the cache-read buffer as it is consumed by an anchor op, and apply the same transformation to the layout-free buffer. My solution supports more general cases where there are multiple cache reads forming a "chain" of blocks, starting from the one that directly consumes the layout-free buffer passed as a parameter. So the layout transformation is back propagated over such chain. 
cc @vinx13 @junrushao @nverke
=> [MetaSchedule] Support schedules with cache read in RewriteLayout

tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_int8.py
Use VTCM for E2E execution of conv2d to reduce tuning time.
cc: @csullivan @masahi
=> [Hexagon] Use VTCM while scheduling conv2d op

jvm/native/osx-x86_64/pom.xml
- Add missing bracket in pom file
- Replaced JavaVM on JavaNativeFoundation. From Xcode 12.1 (macOS 11 (Big Sur)) JavaVM framework is no longer includes to the frameworks list. Necessary to use JavaNativeFoundation instead.
cc: @apeskov, @jwfromm
=> [tvm4j] Fix tvm4j build on MacOS

python/tvm/script/parser/tir/parser.py, src/printer/tvmscript_printer.cc, tests/python/unittest/test_tvmscript_roundtrip.py, tests/python/unittest/test_tvmscript_syntax_sugar.py
For the previous version of the parser, this was special-cased for some intrinsic operators.  After the new TVMScript was enabled in https://github.com/apache/tvm/pull/12496, any `PrimExpr` that appears in the body of a statement is silently ignored.  This commit updates the parser to instead wrap the bare `PrimExpr` in a `tir::Evaluate` node.
This change effectively allows [expression statements](https://docs.python.org/3/reference/simple_stmts.html#expression-statements) in TVMScript, which are converted to `tir::Evaluate` nodes during parsing.
=> [TVMScript] Use tir::Evaluate if expression is in statement context

tests/python/contrib/test_hexagon/test_async_dma_pipeline.py
These need to be global.vtcm scope in order to properly test the single dma schedule. 
cc @adstraw
=> [Hexagon] Change single dma alloc buffers to be vtcm

src/relay/backend/task_extraction.cc, src/relay/backend/te_compiler.cc, src/relay/backend/te_compiler_cache.cc, src/relay/backend/te_compiler_cache.h, src/relay/transforms/auto_scheduler_layout_rewrite.cc, src/relay/transforms/meta_schedule_layout_rewrite.cc
The `static` qualifier on the constant index causes a problem, when `TECompiler` is invoked on the same module multiple times. Since the names of constants become different in each call to `TECompiler`, anything that depends on the consistency of constant names is broken. 
In practice, MetaSchedule tuning is affected by this issue, since task extraction and the final `relay.build(...)` both invoke `TECompiler`.  So if we do `get_block("fused_constant_0_global")` during tuning,  trace application after tuning will fail because there would be no longer a block with the name "fused_constant_0_global" .
=> [TECompiler] Replace static constant index with NameSupply

include/tvm/runtime/builtin_fp16.h, src/runtime/builtin_fp16.cc, tests/python/topi/python/test_topi_math.py
__truncdfhf2 can be generated in codegen but the implementation was missing. Added the missing implementation.
=> Add support for cast double to fp16

tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
Adding in a test that covers another case that can happen when running a check in reducer.cc [here](https://github.com/apache/tvm/blob/main/src/tir/schedule/analysis/reducer.cc#L590). 
cc @junrushao
=> [TIR] Add test to cover specific case of reducer match buffer checking

python/tvm/te/operation.py, tests/python/unittest/test_tir_te_extern_primfunc.py
This fixes #13330, which was blocking my work to write TIR schedules for microTVM.
I originally thought I'd have to change the function signature of `DomainTouchedAccessMap`, but I couldn't think of a way to do that cleanly. Instead, I changed `extern_primfunc` to use `primfunc.params` to create the buffer lists in the right order.
#13330 should have been caught by `test_tir_te_extern_primfunc.py`, but one of that test's helper functions had the same bug as `extern_primfunc`. I've thus modified `test_tir_te_extern_primfunc.py` to instantiate the input tensors a different way, allowing it to catch regressions of this issue.
Would love a look from @csullivan!
=> [TIR] Fix extern_primfunc buffer order bug 

python/tvm/relay/op/contrib/ethosn.py, tests/python/contrib/test_ethosn/test_networks.py
This appears to be a historical change due to a bug in the support library. Since the tests are working without this restriction and previously not offloaded concatenate operations are now being offloaded, it seems it is no longer necessary.
=> [ETHOSN] Relax concatenate offloading requirements

ci/scripts/github/github_tvmbot.py, tests/python/ci/test_tvmbot.py
In AUTH_CHECKS, "mentionable_users" was "metionable_users".
This pull request fixes this spelling error.
=> [ci][tvmbot] Fix spelling error, metionable -> mentionable

include/tvm/topi/nn/pooling.h
- Explicit names are useful while fetching the compute during scheduling of pooling ops.
- Specify `meta_schedule` attributes to register op using `register_func`.
cc: @csullivan
=> [TOPI] Update names for pooling ops

python/tvm/tir/tensor_intrin/hexagon.py, tests/python/unittest/test_tir_schedule_tensorize.py
Hexagon tests using `vrmpy` tensorization were broken by the change in `tir/tensor_intrin/hexagon.py` from https://github.com/apache/tvm/pull/12496. The change is a correct one from the TIR perspective, but it breaks tensorize pattern matching. Actually `T.init()` block is not necessary in a tensorize description, so just removing it fixes the breakage. 
@mehrdadh
=> [Hexagon] Fix TIR vrmpy tensorization

src/meta_schedule/task_scheduler/gradient_based.cc, tests/python/unittest/test_meta_schedule_task_scheduler.py
Gradient based scheduler would segfault if no candidates can be returned by the search strategy for some workload. It's expected that the scheduler continues to tune other workloads that have candidates.
cc: @zxybazh @junrushao
=> [MetaSchedule] Fix segfault in gradient based scheduler

CMakeLists.txt
/bigobj was not correctly added to C++ targets. This caused error using cmake build.
=> [Build] Fix MSVC compile option /bigobj

include/tvm/tir/data_type_rewriter.h, include/tvm/tir/stmt.h, include/tvm/tir/stmt_functor.h, python/tvm/te/operation.py, src/relay/backend/utils.cc, src/te/operation/create_primfunc.cc, src/te/operation/create_primfunc.h, src/tir/ir/data_type_rewriter.cc, src/tir/ir/stmt_functor.cc, src/tir/schedule/primitive/blockize_tensorize.cc, src/tir/transforms/lower_match_buffer.cc, src/tir/transforms/narrow_datatype.cc, tests/cpp/data_type_rewriter_test.cc, tests/python/unittest/test_meta_schedule_relay_integration.py, tests/python/unittest/test_te_create_primfunc.py, tests/python/unittest/test_tir_schedule_tensorize.py, tests/python/unittest/test_tir_transform_narrow_datatype.py
* Added data type pass unification pass to by default promote data types of all indices and shapes to int64 when creating prim func.
* Added some fixes for lowering passes to make it compatible with int64 data type.
=> [TIR] Unify index data type when creating prim func

python/tvm/relay/op/contrib/arm_compute_lib.py, src/relay/backend/contrib/arm_compute_lib/codegen.cc, src/runtime/contrib/arm_compute_lib/acl_utils.cc, tests/python/contrib/test_arm_compute_lib/test_add.py
This enables int8 data type to be used in QNN_ADD operator within Compute Library for the Arm(r) Architecture (ACL) BYOC integration.
cc @lhutton1 @d-smirnov for reviews
=> [ACL] Enable int8 data type in QNN ADD

src/meta_schedule/measure_callback/update_cost_model.cc, tests/python/unittest/test_meta_schedule_measure_callback.py
As a follow-up fix PR for https://github.com/apache/tvm/pull/13354, which introduces a bug that the tuning will crash if the run time is empty (usually because of a runtime error).
=> [MetaSchedule][Fix] Fix Empty Run Time Issue when Benchmarking Result

CONTRIBUTORS.md
Please join us to welcome @echuraev as a new committer to TVM. Egor has made major contributions to the TVM OpenCL and Apple Metal backends. In particular he’s made prolific contributions to improving texture support (e.g. for Adreno) and Android & iOS tuning maturity.
- [Commits History](https://github.com/apache/tvm/commits?author=echuraev)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:echuraev)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/echuraev/summary)
=> [COMMUNITY] Egor Churaev -> Committer

python/tvm/relay/qnn/op/_qnn.py, python/tvm/relay/qnn/strategy/generic.py, python/tvm/relay/qnn/strategy/hexagon.py, python/tvm/topi/hexagon/qnn/nn.py, src/relay/qnn/op/add.cc, src/relay/qnn/op/mul.cc, src/relay/qnn/op/requantize.cc, src/relay/qnn/op/subtract.cc, tests/python/contrib/test_hexagon/test_wo_qnn_canonicalization.py
This commit adds compute/schedule implementation for Hexagon target for QNN ops: `qnn.mul`, `qnn.subtract`, `qnn.tanh`. It works only if QNN canonicalization pass was disabled.
=> [Hexagon][QNN] Add TOPI strategies for qnn ops mul/tanh/subtract

python/tvm/relay/backend/contrib/ethosu/tir/compiler.py, python/tvm/relay/backend/contrib/ethosu/tir/passes.py, tests/python/contrib/test_ethosu/cascader/test_memory_reduction.py, tests/python/contrib/test_ethosu/test_networks.py
This PR fixes Cascader code generation without StorageRewrite (when striping is enabled) on Ethos-U NPU.
The problem was that after the Replace Operator's pass, the buffers for partial results of the operation were replaced with a buffer with the results of the entire operation and it was indicated that the buffer needed to be allocated, summing up we received a larger size in the number of parts.
=> [microNPU] Fix Cascader code generation without StorageRewrite

src/runtime/hexagon/hexagon_device_api.cc, src/tir/transforms/lower_async_dma.cc, src/tir/transforms/lower_tvm_builtin.cc
Bug fixes for async DMA lowering with Hexagon mode bypass:
1. Bypass is currently always on.
2. The LowerAsyncDMA doesn't visit the body of an async_wait attribute. 
cc @adstraw
=> [TIR][Hexagon] Async DMA fixups

src/runtime/opencl/opencl_common.h, src/runtime/opencl/opencl_device_api.cc
As it was mentioned in #13362, it would be nice to add check when the user is using a version of libOpenCL.so that is too old.
In this PR we introduce this functionality. In the `init` method, we traverse through all OpenCL devices and check their version. If the version is older than the target version in TVM, then we notify the user that we will skip this device. We cannot throw any exception from method `init` because it is possible that you have compiled host code with OpenCL support, but the host device won't have any OpenCL device which is supported by TVM (e.g. they all have too old version of libOpenCL.so or there is no OpenCL driver installed). From OpenCL codegen we call function OpenCLModuleCreate. In the OpenCLModuleCreate init function might be called and in this case an …
=> [OpenCL] Improve OpenCL version detection

python/tvm/relay/op/contrib/clml.py, src/relay/backend/contrib/clml/codegen.cc, src/relay/backend/contrib/clml/target.cc, src/runtime/contrib/clml/clml_runtime.cc
Handled unsupported configuration for ops in clml pattern table
and updated Dense op runtime api with conv 1x1 kernel api invocation.
=> [RUNTIME][CLML] Add fixes to clml runtime api

src/te/operation/create_primfunc.cc
The call to `analyzer->Simplify` returns a `PrimExpr` object.  Binding a `const PrimExpr&` to this temporary object results in a dangling reference.
=> [TE] Remove binding to temporary variable

python/tvm/relay/frontend/tflite.py, tests/python/relay/opencl_texture/conftest.py, tests/python/relay/opencl_texture/test_conv2d_nchw_texture.py, tests/python/relay/opencl_texture/test_conv2d_nhwc_texture.py, tests/python/relay/opencl_texture/test_depthwise_conv2d_nchw_texture.py, tests/python/relay/opencl_texture/test_depthwise_conv2d_nhwc_texture.py, tests/python/relay/opencl_texture/test_network.py, tests/python/relay/opencl_texture/utils/adreno_utils.py
RPC execution fails some times when opened multiple times per test case. Making remote object initialized from pytest session instead.
Network test cases added.
dtypes enhanced to support multiple inputs.
=> [OPENCL][TEXTURE] Test case enhancements and fixes for RPC

include/tvm/meta_schedule/schedule/cuda/thread_bind.h, src/meta_schedule/schedule/cuda/thread_bind.cc, src/meta_schedule/schedule/cuda/winograd.cc, tests/python/unittest/test_meta_schedule_space_cuda_winograd.py, tests/python/unittest/test_meta_schedule_tune_tir.py
This PR fixes an issue that would cause dynamic loop when reorder is applied during auto binding incorrectly. This would cause failed cuda kernel generation. This PR provided a fix by changing the loop to fuse blocks.
Test is also added and locally tested on `nvidia/geforce-rtx-3070` target.
Thanks for @junrushao for the guidance and @yelite for reporting this issue.
=> [MetaSchedule] Fix Dynamic Loop from AutoBinding

src/printer/tvmscript_printer.cc, tests/python/unittest/test_tvmscript_roundtrip.py
When a TIR `IfThenElseNode::else_case` is itself a `IfThenElse` node, it may be printed as `elif` instead of `else: if ...`.  The `elif` syntax was already handled on the parsing side, so this commit only changes the TVMScript printer.
This change also incidentally altered the printer's output for an else block whose condition is `True`.  Previously, these were dropped from the output altogether.  Now, they are retained in the else block. Removing no-op statements should be done by a transformation pass, not a printer/parser round trip, so this change in behavior makes sense to keep.
Below are shown the same prim func, printed before and after this change.
```python
@T.prim_func
def func(i: T.int32):
if i == 0:
T.evaluate(0)
else:
if i == 1:
T.evaluate(1)
else:
if i == 2:
T.evaluate(2) …
```
=> [TVMScript] Output elif where possible

python/tvm/relay/frontend/onnx.py, src/relay/op/nn/nn.h, tests/python/frontend/onnx/test_forward.py, tests/python/relay/test_op_level1.py
This PR brings 2 bug fixes:
1. ONNX converter for matmul: ONNX matmul follows NumPy [rules](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html):
> If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
> If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.
The (my) previous fix https://github.com/apache/tvm/pull/11174 did not consider the second rule (append 1 dimension for the rhs vector).
2. Relay's `nn.matmul` takes 2-D matrices and the checker was removed in a recent PR https://github.com/apache/tvm/pull/13287. This PR puts the checker back to prevent process crashes (make it a …
=> [FIX][ONNX][Relay] onnx converter on matmul with scalar; bring back nn.matmul check

python/tvm/utils/roofline/__init__.py
Useful if users what to use a different pass for TIR extraction.
=> [Roofline] Allow user choice of pass for saving lowered TIR

Jenkinsfile, ci/jenkins/Deploy.groovy.j2, ci/scripts/jenkins/s3.py
The docs deploy is broken following #13335: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4754/pipeline
This avoids downloading the whole docs directory (which is just used to host documentation previews for PRs) and just grabs the `docs.tgz` which is actually used to deploy the docs. Tested locally that the download works successfully via:
```bash
./ci/scripts/jenkins/s3.py --action download --bucket tvm-jenkins-artifacts-prod --prefix tvm/main/4754/docs --items docs.tgz
```
Fixes #13440
=> [ci][docs] Fix docs deploy

python/tvm/utils/roofline/cuda.py, tests/python/unittest/test_roofline.py
Compute peak flops using fma instructions on CUDA targets. Supports arbitrary datatypes.
=> [Roofline] Add fma (non-tensorcore) peak flops for CUDA

python/tvm/meta_schedule/schedule_rule/auto_bind.py
Following https://github.com/apache/tvm/pull/13206, this PR brings the new parameter added to the AutoBind schedule rule to Python side.
cc @masahi @junrushao
=> [Fix][MetaSchedule] Param for rule AutoBind on Python side

python/tvm/rpc/base.py, python/tvm/rpc/proxy.py, python/tvm/rpc/server.py, python/tvm/rpc/tracker.py, tests/python/unittest/test_rpc_base.py, tests/python/unittest/test_runtime_rpc.py
In a wireless connection situation (android example below) we have a device key containing a colon character(**:**).
_ANDROID_SERIAL_NUMBER = 192.168.0.143:5555_ 
```
C:\Users\icemist>docker exec -it ice_tvm_container adb devices
List of devices attached
192.168.0.143:5555     device
```
In this case we get an error:
```
ERROR:asyncio:Exception in callback None()
handle: <Handle cancelled>
File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/venv/apache-tvm-py3.8/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
handler_func(fileobj, events)
File "/git/tvm/python/tvm/rpc/tornado_util.py", line 41, in _event_handler
self._event_handler(events)
File …
```
=> [RPC] Fix tracker connection termination

src/runtime/contrib/clml/clml_runtime.cc
Fixed the bias tensor allocation failure issue for Dense layer in CLML runtime.
=> [RUNTIME][CLML] Fix Dense layer crash issue

python/tvm/relay/op/strategy/x86.py, python/tvm/topi/x86/dense.py, tests/python/topi/python/test_topi_dense.py
Add a handwritten matrix-vector multiplication implementation for dynamic cases on cpu. This avoids crashing when a dynamic shape is present. Only supports vector LHS and float32 for now.
=> [TOPI] Add handwritten matvec for dynamic cases

src/meta_schedule/space_generator/space_generator.cc, tests/python/unittest/test_meta_schedule_space_cpu_winograd.py
Previously the ICHECK for `target_has_vnni` would seg fault if this function is not found and no debug info is given. However this patch doesn't fix #13425. Note that the test case added wouldn't fail as the function should already be imported somehow by other imports.
cc: @zxybazh
=> [Meta Schedule] Patch ICHECK for `target_has_vnni` to avoid seg fault

python/tvm/meta_schedule/testing/torchbench/run.py, python/tvm/meta_schedule/testing/torchbench/utils.py
This PR adds an option to disallow unsupported operators in the sub graphs produced by TorchDynamo. This makes TVM being able to at least partially tune models with unsupported PyTorch operators (like aten::copy_).
cc: @junrushao @zxybazh
=> [MetaSchedule] TorchBench tuning script: add option to disallow operators in sub graph

src/meta_schedule/space_generator/space_generator.cc
This PR unifies `cuda-tensorcore` and `cuda_tensorcore` to the former one to be consistent with python side `create` functions for schedule rules, post processors, and mutators.
=> [MetaSchedule][Minor] Unify Cuda-TensorCore Naming in Schedule Rule Kind

python/tvm/meta_schedule/testing/torchbench/run.py
This PR adds the task extraction mode to the TorchBench tuning script. The task extraction mode will only import PyTorch model into TVM, extract tuning tasks from it and save them for further use. 
This helps the use case where tasks should be extracted from a machine with GPU and then be tuned on a machine with powerful CPU with rpc workers.
=> [MetaSchedule] TorchBench tuning script: add task extraction mode

python/tvm/ir/module.py, python/tvm/script/highlight.py, python/tvm/tir/function.py, python/tvm/tir/schedule/trace.py
- Automatically use "black" formatter if available.
- Allow overrides of pygmentize style based on environment variable `TVM_PYGMENTIZE_STYLE`.
=> [TVMScript] Improvements tvm.script.highlight

docker/Dockerfile.ci_gpu, docker/install/ubuntu_install_googletest.sh
It is necessary to have google tests source code to build them for the GPU device and run OpenCL cpp tests. In #13400 we enable OpenCL cpp tests in CI.
=> [CI][Docker] Store GTest sources in GPU docker image

src/driver/driver_api.cc
The parameter `pass_ctx` is not used in `TIRToRuntime`.
Just remove it.
=> [tir]delete useless param in driver_api.cc

docker/Dockerfile.demo_android, docker/Dockerfile.demo_rocm, docker/Dockerfile.demo_vitis_ai
Fixes #13015. Note that vitis_ai is broken for another reason, so I couldn't test this fix, but I'll contribute it so that when vitis_ai is unbroken, the Python scripts should be on the right track.
@zuowanbushiwo @HadXu @driazati
=> Add python venvs to demo_ images that build

src/arith/analyzer.cc, src/tir/schedule/primitive/compute_at.cc, tests/python/unittest/test_tir_schedule_compute_at.py
This PR fixes an error when the result of `reverse_compute_at`/`compute_at` contains unit loop (extent is 1). This is caused by dtype mismatch when binding vars in arith analyzer. This breaks the tuning of detectron2 models.
I also add a check in `Analyzer::Bind` to prevent similar problem. If this fails too many tests we can remove it from this PR.
cc: @junrushao @zxybazh
=> [TIR] Fix an error when the result of compute_at has unit loop

src/relay/transforms/annotate_texture_storage.cc, tests/python/relay/opencl_texture/test_conv2d_nchw_texture.py
`DeviceAwareVisitExpr_` for `FunctionNode` had been modifying state of the parameters and specified memory scope for virtual device. `VisitExpr` functions shouldn't modify state of the objects. This is why this function was removed. After removing this function, the memory scope of the input tensors starts to be equal to empty line instead of "global".  But empty line and "global" will be transformed to the same memory object. This is why there is no difference between empty line and "global".
=> [OpenCL][Adreno] Remove PrimFunc parameters annotation

python/tvm/relay/op/contrib/cmsisnn.py, src/relay/backend/contrib/cmsisnn/relay_to_tir.cc, src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc, tests/python/contrib/test_cmsisnn/test_fully_connected.py
Support for int16 fully_connected via CMSIS-NN
-Pattern matching and RelayToTIR introduce int16 support 
-Added int16 variants to fully_connected tests
=> [CMSIS-NN] Support for int16 in fully connected layer

src/arith/rewrite_simplify.cc, src/tir/analysis/control_flow_graph.cc, src/tir/analysis/control_flow_graph.h, src/tir/transforms/remove_no_op.cc, tests/python/unittest/test_tir_transform_remove_no_op.py, tests/python/unittest/test_tir_transform_simplify.py
Previously, `RemoveNoOp` would remove statements that could be locally analyzed as having no effect (e.g. `For` with empty loop extents).  This commit adds opt-in use of data-flow analysis to identify two types of statements that are no-ops based on their context:
* Buffer stores that are overwritten without ever being read.
```python
buf[i] = 5 # Overwritten by next statement
buf[i] = 10
```
* Storing a value that is already known to be present.
```python
buf[0:16] = T.ramp(0, 16, 1)
buf[5] = 5 # Previous load already stored this value
```
=> [TIR][Transform] Optional data-flow analysis in RemoveNoOp

src/arith/rewrite_simplify.cc, src/printer/tvmscript_printer.cc, tests/python/unittest/test_arith_rewrite_simplify.py, tests/python/unittest/test_tir_schedule_transform_layout.py, tests/python/unittest/test_tvmscript_roundtrip.py
Even though the operator precedence of `And` has a higher precedence than `Or`, removing parentheses based on this precedence can harm readability.  This commit adds an exception to the TVMScript rules for parentheses, to always insert parentheses between `And` and `Or` operators.
In addition, adding a rewrite rule to preferentially produce And/Or chains that may be expressed in a single left-associative chain of operators.
Between these two changes, the readability of boolean expressions can be improved.  Below is the motivating example for this change.  In each case, the output had been passed through the `black` formatter. Both expressions are equivalent, but the before-case was much more difficult to read.
```python
x = (
AAA == 0
and BBB < 4
or AAA == 7
and 6 <= BBB
or (CCC == 0 and …
```
=> [TIR][TVMScript] Cleaner printing of And/Or chains

python/tvm/tir/schedule/schedule.py
The return type should be BlockRV rather than LoopRV
=> [TIR] Correct type annotation for `rfactor`

python/tvm/runtime/module.py, tests/python/unittest/test_runtime_module_export.py
Previously the `export_module` function assumes that the module and all imported modules have the same `type_key`. If we have a host llvm module and some imported c modules, it may fail to set the `llvm_target_string` and `object_format` correctly, and thus fail to continue with the llvm build flow.
In this PR, I set the object format of a mixed-type module to that of the host module, and always set `llvm_target_string` when we see a host llvm module.
cc: @tqchen @YuchenJin
=> [RUNTIME] Correctly handling export_module when exporting modules of different type

src/relay/transforms/simplify_expr.h
In the original `DFPatternRewrite` class, the default is to rewrite multiple times, I think it is necessary for the user to set whether to run the callback once.
=> [Relay][Pattern] Enable rewrite_once in class:DFPatternRewrite

python/tvm/relay/op/contrib/arm_compute_lib.py, tests/python/contrib/test_arm_compute_lib/test_dense.py
This enables `QNN_DENSE` int8 data type to be used in Compute Library for the Arm(r) Architecture (ACL) BYOC integration.
cc @lhutton1 for reviews
=> [ACL] Enable int8 data type in QNN DENSE

golang/sample/complex.go
At line132, raw code is `inSlice := make([]float32, (244 * 244 * 3))`, Howover, at line90 the input shape set `tshapeIn  := []int64{1, 224, 224, 3}`,  So there is an error.
=> Fix typo in golang sample

python/tvm/relay/op/contrib/arm_compute_lib.py, tests/python/contrib/test_arm_compute_lib/infrastructure.py, tests/python/contrib/test_arm_compute_lib/test_conv2d.py
This enables `CONV2D` int8 data type to be used in Compute Library for the Arm(r) Architecture (ACL) BYOC integration.
Note: As we have a few PRs going in parallel for these operators, I'll submit another one in the end to consolidate these auxiliary functions and constants like `QNN_DTYPES`.
cc @lhutton1 @ashutosh-arm for reviews
=> [ACL] Enable int8 data type in QNN CONV2D

python/tvm/relay/op/contrib/arm_compute_lib.py, tests/python/contrib/test_arm_compute_lib/test_pooling.py
This enables int8 data type to be used in Compute Library for the Arm(r) Architecture (ACL) BYOC integration.
This PR covers:
- `nn.max_pool2d`
- `nn.avg_pool2d`
- `nn.l2_pool2d`
- `nn.global_avg_pool2d`
- `nn.global_max_pool2d`
cc @lhutton1 for reviews.
=> [ACL] Enable int8 data type in pooling operators

src/tir/schedule/primitive/layout_transformation.cc, tests/python/unittest/test_tir_schedule_transform_layout.py
After the PR https://github.com/apache/tvm/pull/13327, I'm getting a dtype-mismatch error at https://github.com/apache/tvm/blob/b6fae9b35eff4ad1f7cc2e83d8d7da5d701d8e44/src/tir/schedule/primitive/layout_transformation.cc#L310, because `dim.dtype()` is now int64 while `virtual_var.dtype()` is int32. The dtypes of `initial_indices` in `IndexMap` are fixed to int32 (see below), this is in conflict with the above PR which made the dtypes of buffer shapes int64.
https://github.com/apache/tvm/blob/458ca81c01bd85d04ea6428e7cb4bfa021a1d37a/src/tir/ir/index_map.cc#L51
https://github.com/apache/tvm/blob/78b53221f8dd8c1d2bbeff9d34803db33ca254dd/python/tvm/tir/function.py#L395
Since `initial_indices` is used everywhere to construct `loop_var` / `iter_var` / `iter_values` of `For` and `Block` etc, I'm …
=> [TIR] Fix buffer shape and IndexMap indices dtype mismatch

python/tvm/meta_schedule/testing/validate_database.py, src/meta_schedule/measure_callback/remove_build_artifact.cc
Following up on #12948, this PR further enhances the validation script by
=> [MetaSchedule] Enhance Database Validation Script

gallery/how_to/work_with_microtvm/micro_aot.py, gallery/how_to/work_with_microtvm/micro_autotune.py, gallery/how_to/work_with_microtvm/micro_tflite.py
Add `serial_number` option to Zephyr tutorials so it's possible to run them in the hardware CI and specify the serial port by setting `TVM_MICRO_SERIAL` env. variable.
=> [microTVM] Use `serial_number` in Zephyr tutorials

python/tvm/relay/op/strategy/arm_cpu.py, python/tvm/relay/op/strategy/x86.py, python/tvm/topi/utils.py
This extends https://github.com/apache/tvm/pull/13423 schedules for ARM. Now arm targets can handle dynamic vec-mat multiplies.
tests are handled `tests/python/topi/python/test_topi_dense.py` by the arm runners, which were added in the previous PR
=> [ARM] Add dynamic matvec support

CMakeLists.txt, cmake/config.cmake, conda/recipe/build.sh, conda/recipe/meta.yaml, tests/scripts/task_config_build_arm.sh, tests/scripts/task_config_build_cortexm.sh, tests/scripts/task_config_build_cpu.sh, tests/scripts/task_config_build_gpu.sh, tests/scripts/task_config_build_gpu_other.sh, tests/scripts/task_config_build_hexagon.sh, tests/scripts/task_config_build_i386.sh, tests/scripts/task_config_build_minimal.sh, tests/scripts/task_config_build_riscv.sh, tests/scripts/task_config_build_wasm.sh
Reverts apache/tvm#13073 due to breakage of cases not covered by the CI. The cross-compile use case is particularly problematic.
Fixes #13482
@alanmacd @mehrdadh
=> Revert "[microTVM] enable building microTVM components by default"

docs/how_to/deploy/adreno.rst
Flag `-DUSE_MICRO=OFF` was added to avoid this issue #13482. In #13503 these changes were reverted.  Removed unnecessary compilation flag to avoid user confusing.
=> [docs][Adreno] Remove unnecessary compilation flag

python/tvm/relay/op/contrib/cmsisnn.py, src/relay/backend/contrib/cmsisnn/relay_to_tir.cc, src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc, tests/python/contrib/test_cmsisnn/test_pooling.py
Support for int16 pooling functions via CMSIS-NN
-Pattern matching and RelayToTIR introduce int16 support 
-Added int16 variants to fully_connected tests
=> [CMSIS-NN] Support int16 handling for pooling functions

gallery/tutorial/tvmc_command_line_driver.py
Ensure correct link is generated to the next page in the documentation.
=> [Docs][Bug] Fix broken link to tvmc python

gallery/how_to/work_with_microtvm/micro_aot.py, gallery/how_to/work_with_microtvm/micro_autotune.py
Added config_main_stack_size to autotune since running graph debugger requires more workspace. Also added to micro_aot because of KWS model.
Also removed `west_cmd` option in tutorial because of https://github.com/apache/tvm/pull/13377
=> [microTVM][Tutorial] Fix micro_aot and micro_autotune tutorials

include/tvm/ir/expr.h, include/tvm/tir/expr.h, include/tvm/tir/stmt.h
This enables copy on write methods for all nodes since some were missing
it before (see #13012 for more context)
=> [tir] Add copy on write to all nodes

src/runtime/hexagon/hexagon_device_api.cc, src/runtime/hexagon/hexagon_vtcm_pool.cc, src/runtime/hexagon/hexagon_vtcm_pool.h, tests/cpp-runtime/hexagon/hexagon_vtcm_pool_tests.cc
Expose methods so that callers can get both the size of VTCM on device as well as the allocated size of the pool for the session.
cc: @masahi
=> Add methods to get the size of VTCM on device as well as the allocated size of the HexagonVtcmPool

src/target/llvm/codegen_amdgpu.cc, src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h, src/target/llvm/codegen_nvptx.cc
LLVM 16 has removed support for the legacy pass manager, and the LLVM codegen in TVM will no longer even compile.
=> [LLVM] Switch to using New Pass Manager (NPM) with LLVM 16+

src/te/operation/create_primfunc.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt.py, tests/python/unittest/test_tir_transform_inject_software_pipeline.py
Prior to this commit, loop iterators were named `i0`, `i1`, and so on, while the `BlockNode::iter_vars` used the name from the TE `IterVar`. As a result, after `BlockNode::iter_vars` is lowered out, the resulting `PrimFunc` no longer contained the user-generated iterator names.  This commit updates the TIR conversion so that the loop iterators take the name of the TE `IterVar`, and the `BlockNode::iter_vars` are named `v_$IterVarName`.
=> [TE][TIR] Improved naming when converting TE to schedulable TIR

apps/microtvm/cmsisnn/run_demo.sh, apps/microtvm/ethosu/run_demo.sh
Previously, the `tests/scripts/task_demo_microtvm.sh` script prints the commands as they are run, but the
`apps/microtvm/ethosu/run_demo.sh` script did not.  As a result, it could be difficult to tell which step stalled or failed during CI.
=> [CI] Add `set -x` for demo scripts

src/tir/transforms/remove_no_op.cc
During a `tir.Simplify` pass, these extensions were conditionally enabled based on the `PassContext`.  Prior to this commit, they were enabled by default in the `tir.RemoveNoOp` pass, as the simplified expressions were only used to prove/disprove a no-op, and did not appear in the output TIR.  However, this caused performance issues for some nested boolean expressions.
This PR disables the analyzer extensions for the analyzer used by `tir.RemoveNoOp`.  The extensions are still used internally by `ControlFlowGraph`, including during the data-flow analysis used if `tir.transform.RemoveNoOpConfig.use_dataflow_analysis` is enabled, so the opt-in data-dependent no-op removals are unaffected.
Related to issue #13508.
=> [TIR] Disable RewriteSimplifier extensions in RemoveNoOp

cmake/modules/Hexagon.cmake, src/runtime/hexagon/ops/conv2d.h, src/runtime/hexagon/ops/conv2d_fp16_hvx.cc, src/runtime/hexagon/ops/conv2d_quant_hvx.cc, src/runtime/hexagon/ops/conv_utils.cc, tests/cpp-runtime/hexagon/hexagon_conv_utils_test.h, tests/cpp-runtime/hexagon/hexagon_quant_utils_tests.cc, tests/python/contrib/test_hexagon/infrastructure.py, tests/python/contrib/test_hexagon/topi/test_conv2d_quant_intrin.py
This patch adds a new HVX intrinsic implementation to perform quantized convolution.
It assumes that the qnn.conv2d relay op is not
canonicalized and all the quantization parameters (scales and zero points) are passed into the intrinsic implementation.
It also uses the fixed point computation function defined in hexagon topi utils to compute a fixed point (combined) scale which is used to perform the final requantization before returning the quantized output.
=> [Hexagon] Add HVX quant conv2d implementation

include/tvm/tir/analysis.h, python/tvm/autotvm/measure/measure_methods.py, python/tvm/target/target.py, python/tvm/tir/analysis/analysis.py, python/tvm/tir/transform/transform.py, src/auto_scheduler/feature.cc, src/auto_scheduler/search_policy/utils.h, src/driver/driver_api.cc, src/target/target_kind.cc, src/tir/analysis/calculate_allocated_memory.cc, tests/python/contrib/test_hexagon/infrastructure.py, tests/python/contrib/test_hexagon/test_vtcm.py, tests/python/unittest/test_tir_analysis_calculate_allocated_memory.py
The main items that have been added are:
tvm.tir.analysis.calculate_allocated_bytes() 
> to calculate allocated memory per memory scope
tir.transform.VerifyVTCMLimit(limit)
> to verify if the size of the allocated vtcm memory satisfies the limit
tvm.target.hexagon().vtcm_capacity 
> attribute to pass the limit
tir.vtcm_capacity 
> context configuration attribute to pass the limit alternatively
=> [TIR][Hexagon] Add vtcm memory capacity verification for Hexagon target

python/tvm/tir/transform/transform.py, src/arith/rewrite_simplify.cc, src/tir/transforms/reduce_branching_through_overcompute.cc, src/tir/transforms/remove_no_op.cc, src/tir/transforms/remove_no_op.h, src/tir/transforms/simplify.h, tests/python/unittest/test_tir_transform_reduce_branching_through_overcompute.py, tests/python/unittest/test_tir_transform_simplify.py
This PR introduces a new transform, which attempts to reduce branching by adding overcompute, where the overcompute has provably no effect on any observable value outside the PrimFunc.
=> [TIR] Introduce ReduceBranchingThroughOvercompute

docker/install/ubuntu_install_nrfjprog.sh
The old one began to 404, this one is taken for 10.12.1 from
https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools/download
=> [ci][docker] Update NRF command line tools URL

src/tir/transforms/loop_partition.cc, tests/python/unittest/test_tir_transform_loop_partition.py
Current LoopPartition pass, when the loop is marked kUnrolled, it returns directly
This PR enhance LoopPartition pass to continue recursive on loop with marked kUnrolled.
=> Add recursive on loop with marked kUnrolled

apps/microtvm/arduino/template_project/microtvm_api_server.py, apps/microtvm/poetry.lock, apps/microtvm/pyproject.toml, python/tvm/micro/testing/pytest_plugin.py, tests/micro/arduino/README.md, tests/micro/arduino/test_arduino_error_detection.py, tests/micro/arduino/test_arduino_rpc_server.py, tests/micro/arduino/test_arduino_workflow.py, tests/micro/arduino/test_utils.py, tests/micro/zephyr/README.md, tests/micro/zephyr/conftest.py
This PR adds serial_number as a project option to Arduino project API. In addition, it is added to micro pytest_plugin to enable testing with assigned serial number.
=> [microTVM][Arduino]Add `serial_number` to project options and tests

include/tvm/meta_schedule/postproc.h, include/tvm/tir/analysis.h, python/tvm/meta_schedule/postproc/__init__.py, python/tvm/meta_schedule/postproc/verify_vtcm_limit.py, src/meta_schedule/postproc/postproc.cc, src/meta_schedule/postproc/verify_vtcm_limit.cc, src/tir/analysis/calculate_allocated_memory.cc, tests/python/unittest/test_meta_schedule_postproc_verify_vtcm_limit.py
Building on https://github.com/apache/tvm/pull/13349, and similar to `VerifyGPUCode`, add a postproc check for the VTCM usage.
@csullivan @Icemist @nverke
=> [MetaSchedule][Hexagon] Add postproc for verifying VTCM usage

python/tvm/tir/tensor_intrin/hexagon.py, tests/python/unittest/test_tir_schedule_tensorize.py
This patch adds the `vdmpy` hexagon intrinsic and a sample tensorization test for the same.
This patch also modifies the test to use transform_layout instead of a packed tensor in the compute to make it obvious that this example is just matmul with a different data layout for one of the inputs
=> [TIR] [Hexagon] Add vdmpy intrinsic and transform_layout for tests

.github/workflows/upload_ci_resource.yml, tests/scripts/request_hook/request_hook.py
The workflow https://github.com/apache/tvm/actions/workflows/upload_ci_resource.yml uses SHA-256, not SHA-512 hashes. This  PR fixes a comment in `request_hook.py` to reflect this, and fixes some other formatting too.
It also adds a trailing quote to `upload_ci_resource.yml' to prevent it from failing (e.g. https://github.com/apache/tvm/actions/runs/3629030778/jobs/6120748470). 
@driazati can you review and merge?
=> [ci] Fix upload_ci_resource.yml and update related documentation

src/arith/iter_affine_map.cc
Apparently a left-over from https://github.com/apache/tvm/pull/13069. I have a complex test that would hit a dtype-mismatch error because of this, but I don't know how to create a simple repro test. Hopefully it is ok as this is a follow-up to 13069?
cc @vinx13
=> [TIR] Fix remaining dtype mismatch issue caused by SubspaceDivide

src/contrib/torch/base64.h
The b64strlen & b64decode API's are defined in a header and will cause linker issues if included in multiple files. We ran into this issue while attempting to use this file in our project.
=> Mark base64.h encode and decode API's as inline

include/tvm/meta_schedule/schedule_rule.h, python/tvm/meta_schedule/schedule_rule/multi_level_tiling.py, src/meta_schedule/schedule_rule/multi_level_tiling.cc, src/meta_schedule/schedule_rule/multi_level_tiling.h, tests/python/contrib/test_hexagon/test_meta_schedule.py, tests/python/unittest/test_meta_schedule_schedule_rule_mlt.py
Currently, the condition for applying `MultiLevelTiling` is given by `NeedsMultiLevelTiling` function:
https://github.com/apache/tvm/blob/5364e5a39a5e33728b7f5a26ddb40543a544ea02/src/meta_schedule/schedule_rule/multi_level_tiling.cc#L95
In practice, only multi-argument reduction operations like conv2d or dense are selected. I'm proposing to make this condition customizable for use cases where we might want to apply `MultiLevelTiling` to more ops (pooling etc).
@junrushao @csullivan @vinx13
=> [MetaSchedule] Make `MultiLevelTiling` apply condition customizable

src/tir/schedule/primitive/layout_transformation.cc, tests/python/unittest/test_meta_schedule_postproc_rewrite_layout.py
`LegalizeIndexMapDType` previously ignore pre-defined inverse map, which causes error in `TransformLayout` when the inverse index map is predefined but the arithmetic analysis fails to compute the inverse map.
cc @masahi @Lunderberg
=> [TIR] Fix predefined inverse map in layout transform dtype legalization

.asf.yaml, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/templates/docker_jenkinsfile.groovy.j2, ci/jenkins/templates/gpu_jenkinsfile.groovy.j2
The PR #13300 had a bad merge with main an undid a fix from #13442, this
adds it back in. This also fixes a missing condition where docker images
are always being built even when unnecessary.
=> [ci] Fix docs deploy

ci/scripts/github/github_tvmbot.py, ci/scripts/jenkins/git_utils.py
See #13337 for more context, this fixes `@tvm-bot rerun` to work with
the new jobs
=> [ci] Make tvm-bot aware of platform specific jobs

.github/workflows/update_nightly_branch.yml
This adds a `nightly` branch that is updated once per day with a
specific TVM commit to enable third-parties to synchronize on which TVM
commit to test. A batch of commits is added once per day and tests
should be run on the `HEAD` of that batch.
Tested in https://github.com/driazati/tvm/actions/runs/3632546266/jobs/6128517495
=> [ci] Add a workflow to update a nightly branch

python/tvm/relay/testing/tflite.py, src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc, src/relay/backend/contrib/example_target_hooks/tir_to_runtime.cc, src/relay/backend/contrib/uma/tir_to_runtime.cc, src/target/source/codegen_c.cc, src/target/source/codegen_c.h, src/target/source/codegen_c_host.cc, src/target/source/codegen_c_host.h, src/target/source/codegen_cuda.cc, src/target/source/codegen_cuda.h, src/target/source/codegen_opencl.cc, src/target/source/codegen_opencl.h, src/target/source/codegen_source_base.h, src/target/source/codegen_vhls.cc, src/target/source/codegen_vhls.h, tests/python/relay/aot/corstone300.mk, tests/python/relay/aot/test_crt_forward_declarations.py
armclang 6.19 does not support implicit function declarations. This commit adds support for generating forward function declarations in the C file generated for __tvm_main__.
=> [CodegenC] Explicit forward function declarations

tests/cpp/runtime/contrib/ethosn/inference_test.cc
This test was causing cpptest to fail without reporting the test as having failed. Looking back, this test doesn't really make much sense as we are passing a file descriptor stating that inference is running when it isn't. Therefore, removing the test.
cc @ekalda @ashutosh-arm
=> [ETHOSN] Remove inference test

CONTRIBUTORS.md
Please join us to welcome @guberti as a new committer to TVM. Gavin is a prolific microTVM contributor, tackling on complex performance issues for TVM in micro devices with high quality, well tested and documented patches.
- [Commits History](https://github.com/apache/tvm/commits?author=guberti)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:guberti)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/guberti/summary)
=> [COMMUNITY] Gavin Uberti -> Committer

.github/workflows/update_nightly_branch.yml, tests/scripts/ci.py
The docs are usually built with a GPU, so this PR simplifies some logic
that was conflating several options to automatically choose the docker
image to run. Now the CPU image is only used if the `--cpu` flag is
passed, which makes `ci.py docs` work like CI by default for the main
docs.
=> [docs] Make building the cpu-only docs build explicit

python/tvm/topi/arm_cpu/injective.py, python/tvm/topi/nn/winograd_util.py, tests/python/integration/test_arm_aprofile.py
Following on from the example conversion in ndarray.py,
in order to broaden the support for bfloat16 in the absence of
full support, this commit converts bfloat16 to uint16
in the injective schedule to enable full compilation
of Conv2D via arm_cpu schedules.
cc @leandron @ekalda
=> [bfloat16] Fixed dtype conversion in the arm_cpu injective schedule

python/tvm/relay/op/strategy/adreno.py, python/tvm/topi/adreno/pooling.py, tests/python/relay/opencl_texture/test_pool_texture.py
The parallelizm opportuninties in case of global pooling are limited by number of channels, need to change schedule to have parallelizm by reduction axis/use rfactor
=> [Adreno] Add global pooling schedule

tests/python/contrib/test_hexagon/test_launcher.py
Use the same function for consistency.
=> [Hexagon] Use get_hexagon_target in test, NFC

tests/python/contrib/test_hexagon/test_async_dma_pipeline.py
Don't use numeric values for LLVM intrinsics.
=> [Hexagon] Lookup intrinsic by name instead of using enum value

python/tvm/topi/testing/depthwise_conv2d_python.py, tests/python/contrib/test_hexagon/test_async_dma_pipeline.py, tests/python/contrib/test_hexagon/topi/slice_op/test_conv2d_slice.py, tests/python/contrib/test_hexagon/topi/test_pad.py
Add explicit "constant" as `mode` argument in `pad` and replace `default_rng` with `randint`.
=> [Test] Make tests work with older numpy versions

ci/jenkins/docker-images.ini, ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/generated/cortexm_jenkinsfile.groovy, ci/jenkins/generated/cpu_jenkinsfile.groovy, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/generated/hexagon_jenkinsfile.groovy, ci/jenkins/generated/i386_jenkinsfile.groovy, ci/jenkins/generated/lint_jenkinsfile.groovy, ci/jenkins/generated/minimal_jenkinsfile.groovy, ci/jenkins/generated/riscv_jenkinsfile.groovy, ci/jenkins/generated/wasm_jenkinsfile.groovy, ci/jenkins/templates/utils/Prepare.groovy.j2, ci/jenkins/templates/utils/base.groovy.j2, ci/scripts/jenkins/determine_docker_images.py, docker/bash.sh, docs/contribute/ci.rst, tests/lint/check_file_type.py, tests/python/ci/test_ci.py
Hardcoding the Docker images in the Jenkinsfiles has the downside that only trusted changes are actually run in CI. Since Docker image updates are pretty frequent, this makes for a pretty bad UX (e.g. CI runs but doesn't actually test the PR). The fix here makes it so the images are read from a different file during CI execution so updates from anyone are picked up.
This PR eliminates the need to use the batch jobs in Jenkins to update Docker images. Docker images are built as part of post-merge CI on `main` and anyone can trigger a validation run by filing a PR with changed Docker tags.
=> [ci][docker] Read docker image tags during CI runs

src/tir/transforms/plan_update_buffer_allocation_location.cc, tests/python/unittest/test_tir_transform_plan_update_buffer_allocation_location.py
This PR fix indeterminate order between each allocated buffer after update buffer allocation location
=> [TIR][Transform] Keep the allocate buffers order after update buffer allocation location

python/tvm/relay/frontend/onnx.py, python/tvm/relay/transform/fake_quantization_to_integer.py, src/relay/transforms/fake_quantization_to_integer.cc, tests/python/relay/test_pass_fake_quantization_to_integer.py
Closes https://github.com/apache/tvm/issues/13545
The pattern of `dense -> add`, where the add is really bias addition, can appear often as the result of converting ONNX `Gemm` op:
https://github.com/apache/tvm/blob/edfeba5c3a2caf133d2d045d1c4d99f5c34aeb69/python/tvm/relay/frontend/onnx.py#L1409
Currently, FQ2I tries to convert this `add` to `qnn.add`. But if this add is being used for bias addition, `out_t.scale` and `out_t.zero_point` variables in `fake_quantization_to_integer.py`, which are used to initialize the output scale and zp of the QNN binary operators, can be tensors rather than scalars. QNN binary operators do not support such output qparams, which led to the error reported in https://github.com/apache/tvm/issues/13545.
For this reason, apparently we haven't supported …
=> [FQ2I] Support converting `dense` -> `add` to `qnn.dense` -> `add` -> `requantize`

ci/jenkins/docker-images.ini, ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/generated/cortexm_jenkinsfile.groovy, ci/jenkins/generated/cpu_jenkinsfile.groovy, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/generated/hexagon_jenkinsfile.groovy, ci/jenkins/generated/i386_jenkinsfile.groovy, ci/jenkins/generated/lint_jenkinsfile.groovy, ci/jenkins/generated/minimal_jenkinsfile.groovy, ci/jenkins/generated/riscv_jenkinsfile.groovy, ci/jenkins/generated/wasm_jenkinsfile.groovy, ci/jenkins/templates/docker_jenkinsfile.groovy.j2, ci/jenkins/templates/utils/Prepare.groovy.j2, ci/scripts/jenkins/determine_docker_images.py
This fixes `ecr_pull` so that `docker-images.ini` can be updated with Docker images from a previous CI run for testing purposes
Example run: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-cortexm/detail/PR-13590/4/pipeline/#step-80-log-9
=> [ci][docker] Allow usage of ECR images in PRs

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/cache_read_write.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_cache_read_write.py
Hi, this change try add optional `consumer_blocks` param to `cache_write` symmetrically, following change on `cache_read` of https://github.com/apache/tvm/pull/12505.
This is helpful when there are multiple consumers to the targeting block who also write to global output, and when we do `cache_write`, we may want to control some of the consumers read data reside on cache.
As a comparation, for `s.cache_read(B, 0, "cache_scope", consumer_blocks=[B])`:
For `s.cache_write(P, 0, "cache_scope", consumer_blocks=[B])`
cc @Hzfengsy @jwfromm
=> [TIR][Schedule] Support for specific consumer block targeting in cache_write

src/target/llvm/llvm_instance.cc
It seems that `GetOrCreateTargetMachine`'s failure check would be out of `lookupTarget`' nest scope.
=> [LLVM] Fix get tm allow_missing check pos

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Simple updates to support the stable diffusion model from diffusers. Scripts at https://github.com/masahi/torchscript-to-tvm/tree/master/stable-diffusion can be used to verify that the conversion works and the output of the pipeline using TVM-compiled modules looks ok (takes ~10 mins on CPU running for 50 steps, untuned).
@comaniac @shingjan @jroesch
=> [Torch] Stable diffusion support

src/relay/transforms/combine_parallel_dense.cc, tests/python/relay/test_pass_combine_parallel_dense.py
The current implementation of `CombineParallelDense` is hardcoded to slice along the last axis after the combined dense. I hit an error using this pass on the stable diffusion UNet, since it has a combined group where the dense is followed by `expand_dims` which changes the slicing axis (see https://github.com/masahi/torchscript-to-tvm/blob/master/stable-diffusion/compile.py for repro)
```
%76 = concatenate(%74) /* ty=Tensor[(20160, 1280), float32] */;
%79 = concatenate(%77) /* ty=Tensor[(20160), float32] */;
%78 = nn.dense(%75, %76, units=20160) /* ty=Tensor[(2, 20160), float32] */;
%80 = nn.bias_add(%78, %79, axis=-1) /* ty=Tensor[(2, 20160), float32] */;
%81 = expand_dims(%80, axis=2) /* ty=Tensor[(2, 20160, 1), float32] */;
%82 = expand_dims(%81, axis=3) /* ty=Tensor[(2, 20160, 1, 1), …
```
=> [Relay] Fix `CombineParallelDense` slicing axis 

src/meta_schedule/task_scheduler/task_scheduler.cc
This PR fixes one error prompt in task scheduler. Prior to this fix, the prompt assumes the error message always comes from a build failure. However, it is possible that the error message comes from a run failure.
=> [Fix] Task scheduler error prompt upon build/run failure

src/tir/transforms/plan_update_buffer_allocation_location.cc
https://github.com/apache/tvm/pull/13560 is supposed to change only the order in which buffers are visited, but the created `buffer_alloc_recorder_` misses buffers associated with `AllocateConst` nodes. These buffers are not part of `func->buffer_map`, and appear only in `read` or `match_buffer` regions, so they are not caught by existing visitors for `BufferLoadNode` and `BufferStoreNode`.
Since constant buffers are not correctly handled by `PlanAndUpdateBufferAllocationLocation` now, tuning on Hexagon is currently broken with this error. This PR fixes this.
```
E             File "/home/fparizi/src/tvm_src/src/tir/transforms/plan_update_buffer_allocation_location.cc", line 163
E           TVMError: 
E           ---------------------------------------------------------------
E …
```
=> [TIR] Fix PlanAndUpdateBufferAllocationLocation not visiting constant buffer

python/tvm/relay/frontend/onnx.py, python/tvm/relay/op/_transform.py, tests/python/frontend/onnx/test_forward.py
This PR adds support for some new sequence operators in the onnx frontend. I made a few other small tweaks to get everything working, specifically an attempt to rectify dynamic rank in `If` statements and the removal of a superfluous check in concat's shape function. With these changes, we can import and run the latest Yolo variants which is pretty cool.
=> [Relay][Frontend][Onnx] SequenceAt and SplitToSequence Operators

python/tvm/relay/backend/contrib/ethosu/tir/scheduler.py, tests/python/contrib/test_ethosu/test_scheduler.py
In Ethos-U, CopyConstants scheduler currently copies weights for all operators. But in Vela, there are a number of scenarios where the weights are not buffered in SRAM, and FullyConnected case is one of them.
=> [microNPU] Disable copying weights to SRAM for FullyConnected ops in CopyConstants scheduler

tests/micro/common/test_tvmc.py
This PR adds stack size to run test on hardware for Zephyr. It is not added for Arduino since it is not required.
4096 is derived from experiment on nucleo_l4r5zi.
=> [microTVM][Zephyr] Fix TVMC test on hardware

src/target/llvm/codegen_llvm.cc
Pass `std::nullopt` to initialization of `PassBuilder` for `PGOOptions`. LLVM is moving away from its own `Optional` type to `std::optional`.
=> [LLVM] Use std::nullopt instead of llvm::None

tests/python/contrib/test_hexagon/test_parallel_hvx.py, tests/python/contrib/test_hexagon/test_parallel_hvx_load_vtcm.py, tests/python/contrib/test_hexagon/test_parallel_scalar.py, tests/python/contrib/test_hexagon/test_vtcm_bandwidth.py
`default_rng` was introduced in numpy 1.19, which is not present even in Ubuntu 20.04 (it comes with 1.17.4).
=> [Hexagon] Switch from default_rng to random in Hexagon tests

src/meta_schedule/database/json_database.cc, src/meta_schedule/database/memory_database.cc, tests/python/unittest/test_meta_schedule_database.py
The get_top_k implementation of JSONDatabase confuses by giving out N/A results that were supposedly sorted in a non-obvious way. 
For tuning records with no measurement results, it is not possible to determine the order and identify the top results.
=> [Metaschedule] Aligning get_top_k logic in MemoryDatabase and JSONDatabase

python/tvm/topi/cuda/tensorcore_alter_op.py, tests/python/relay/test_pass_legalize_tensorcore.py
The hardcoded shapes
```
B, M, K = x_tensor.shape
B, N, K = y_tensor.shape
```
is not valid if `transpose_b = False` or `transpose_a = True`.
@vinx13
=> [TOPI] Fix batch_matmul tensorcore legalize for transpose_b = False case

src/relay/op/nn/nn.h, tests/python/relay/test_op_level1.py
In the Relay Matmul shape relation, we are a little over enthusiastic about unifying dynamic shapes. If one of the shapes is static, it does not need to be unified. This change only rewrites dynamic shapes to required static constraints.
=> [Relay] Remove overwriting of matmul shapes when they are static

python/tvm/relay/frontend/common.py, python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Support convert sequence_lens input of GRU.
=> [Frontend] [ONNX] Support sequence_lens of GRU

python/tvm/relay/op/contrib/ethosn.py, src/relay/backend/contrib/ethosn/codegen.cc, src/relay/backend/contrib/ethosn/codegen_ethosn.h, tests/python/contrib/test_ethosn/test_codegen.py
The support library currently supports enabling the experimental cascading compiler option via an environment variable `FORCE_EXPERIMENTAL_COMPILER`. This commit exposes the ability to enable this option through TVMC.
=> [ETHOSN] Add support for experimental compiler option

src/printer/tvmscript_printer.cc, tests/python/unittest/test_tvmscript_roundtrip.py
Fix the following script with multiple kernel launch (each take standalone thread binding) which is not round-trip-able.
```python
import tvm
@T.prim_func
def main(A: T.Buffer[128, "float32"], C: T.Buffer[128, "float32"]):
B = T.alloc_buffer([128], "float32")
for i in range(128):
with T.block("B1"):
vi = T.axis.remap("S", [i])
B[vi] = A[vi] + 1.0
for i in range(128):
with T.block("B2"):
vi = T.axis.remap("S", [i])
C[vi] = B[vi] + 2.0
s = tvm.tir.schedule.Schedule(main)
b1 = s.get_block("B1")
b2 = s.get_block("B2")
i = s.get_loops(b1)[0]
s.bind(i, "threadIdx.x")
i = s.get_loops(b2)[0]
s.bind(i, "threadIdx.x")
f = tvm.lower(s.mod["main"])
print(f.script())
tvm.ir.assert_structural_equal(f, tvm.script.from_source(f.script()))
```
Since the env thread is always …
=> [TVMScript] Fix print round-tripable multi thread env binding

python/tvm/relay/op/strategy/cuda.py, tests/python/unittest/test_meta_schedule_relay_integration.py
When both AutoTVM and AS/MS winograd are applicable, the latter is never picked by the op strategy because the AutoTVM one has a higher plevel (20 vs 15)
https://github.com/apache/tvm/blob/b16a64d6edb9fd1a014fc51995dff7d0e2f4c84e/python/tvm/relay/op/strategy/cuda.py#L271-L276
This has been fixed, and now we can properly extract FP16 winograd tasks for MS tuning.
@vinx13 @junrushao @zxybazh
=> [MetaSchedule] Fix tensorcore winograd task extraction

gallery/tutorial/uma.py, python/tvm/relay/backend/contrib/uma/backend.py, src/relay/backend/contrib/uma/targets.cc, tests/python/contrib/test_uma/test_target.py
This PR address fixes for UMA target registration.
* Fix the doc issue #13304 
* Continues stalled PR #12731 
---
Changes:
* Incorporates all proposed fixes from mentioned [PR #12731](https://github.com/apache/tvm/pull/12731)
* Address test case concerns and discussions from [PR #12731](https://github.com/apache/tvm/pull/12731)
* **NEW:** Already exiting target cannot be created, explicit error on this.
* **NEW:** Attributes having special/reserved scope cannot be created explicitly.
It also address proper test cases for all the above.
Cc:  @areusch, @cgerum, @lhutton1, @manupak, @MichaelJKlaiber, please help with the review.
Thanks,
~Cristian
=> [BugFix][UMA] Protect target registration

src/arith/const_fold.h, tests/python/unittest/test_arith_canonical_simplify.py
Since https://github.com/apache/tvm/pull/12515, const folding on fp16, when both lhs and rhs are constant, is disabled. This is the case even when one of the arguments are one or zero. This leads to a real problem described in https://github.com/apache/tvm/pull/13532#issuecomment-1353715208. So in practice, compiling winograd fp16 on GPU is currently broken. 
This PR enables trivial algebraic simplification for fp16 const folding when (1) both arguments are constant and (2) one or both of the inputs are one or zero. Since we already do such simplification for any dtype when only one of the inputs are constant (for example https://github.com/apache/tvm/blob/3a639a41a830ece914df10a98f807123e46cd750/src/arith/const_fold.h#L209-L216), I just removed all early exit `return NullOpt` for fp16 …
=> [Arith] Allow const folding on fp16 involving one and zero

python/tvm/relay/testing/py_converter.py
Currently, `relay.testing.py_converter` is checking for using _exactly_ Python 3.8 in order to use certain updated signatures in the `ast` library. However, those signatures are also correct for versions _above_ 3.8. This PR changes the bounds checks so that the converter will work above 3.8.
=> [Relay][Testing][Bugfix] `py_converter` should use correct AST for versions above 3.8 too

python/tvm/script/parser/core/parser.py, tests/python/unittest/test_tvmscript_regression.py
This PR tries to fix the crash of parser when the old value of a var is an array but the new value is not. For example:
```python
def func_wrapper(shape, dtype):
@T.prim_func
def test_case():
a = T.alloc_buffer(shape, dtype=dtype)
return test_case
if __name__ == "__main__":
a = np.zeros((10, 10), dtype="int8")
print(func_wrapper((256, 256), dtype="int8").script())
```
In the above code, there are two assignment to var 'a'. In the global scope, its value is a numpy array. But it is a Buffer in the prim function. There is a table named 'name2value' to track the value of vars like 'a' here.
When the parser wants to update its value, it will compare the value between the new and the old assignment. Here the problem comes. When we use '==' to compare an array …
=> [BugFix][TVMScript] Parser crash

src/relay/transforms/device_aware_visitors.cc, tests/python/contrib/test_clml/test_compiler.py
Heterogeneous module partitioned by BYOC has functions nodes without any VirtualDevice definition (having FullyUnconstrained device). Ignoring the device here causes expr_virtual_devices_ being empty when PopVirtualDevice is called assuming above PushVirtualDevice is succeeded. PushVirtualDevice and PopVirtualDevice occurs as pairs across function body, hence it's better to insert the The Virtual Device for Uncontrained and Pop it subsequently.
=> [TRANSFORM] Fix virtual device annotation issue with BYOC subgraphs

python/tvm/script/parser/core/utils.py, tests/python/unittest/test_tvmscript_regression.py
This PR try to fix the following bug:
```python
def test_var_capturing_order():
b = 2
@T.prim_func
def test_case():
k: T.int32 = b
if __name__ == "__main__":
b = 1
```
In the prim func `test_case`, the vaule of b should be 2, rather than 1. The parser wrongly uses global vars to shadow the value of nonlocal vars, which should be reversed.
=> [BugFix][TVMScript]fix var capturing order error

python/gen_requirements.py
Temporarily constrain the version of numpy to workaround the deprecated value used in mxnet. See #13647.
=> [CI] Fix android build by constraining numpy version

cmake/utils/FindEthosN.cmake, docker/install/ubuntu_install_ethosn_driver_stack.sh, python/tvm/relay/op/contrib/ethosn.py, src/runtime/contrib/ethosn/ethosn_device.cc, src/runtime/contrib/ethosn/ethosn_device.h, src/runtime/contrib/ethosn/ethosn_runtime.cc, src/runtime/contrib/ethosn/ethosn_runtime.h, tests/python/contrib/test_ethosn/infrastructure.py, tests/python/contrib/test_ethosn/test_conv2d.py, tests/python/contrib/test_ethosn/test_conv2d_transpose.py, tests/python/contrib/test_ethosn/test_leaky_relu.py, tests/python/contrib/test_ethosn/test_tanh.py
NPU driver updated to 22.11.
New process memory allocator is used to create
buffers and networks. Support for 22.08 stack has
been kept intact in the sources and tests until the new
docker image is built and starts getting used. Tests
were modified to meet limitations imposed on input
zero point and kernel size by NPU software. Removed
defining ETHON_API_VERSION from cmake infra.
=> [ETHOSN] Update driver stack version to 22.11

src/target/parsers/mprofile.cc, tests/cpp/relay/backend/contrib/cmsisnn/compiler_attrs_test.cc
This pr adds support for Cortex-M85.
Currently, there are no Cortex-M85 tests because another reference system is needed.
@ashutosh-arm
=> [CMSIS-NN] Add Cortex-M85 support

src/runtime/contrib/ethosn/ethosn_device.cc, src/runtime/contrib/ethosn/ethosn_runtime.cc
NPU driver 22.11 supports buffer and network creation
with only process memory allocator. This change however
should be limited to the cases when the HW is available.
NPU driver update: https://github.com/apache/tvm/pull/13637
cc @lhutton1
=> [ETHOSN] Fix for the mock inference after NPU driver update

python/tvm/rpc/proxy.py, python/tvm/rpc/server.py, python/tvm/rpc/server_ios_launcher.py
This PR adds fail-guard to reduce error messages thrown during process termination time. Such error won't trigger test error but will bring extra message during exit time.
=> [RPC] Add fail-guard for termination time exception

python/tvm/testing/aot.py, tests/python/contrib/test_cmsisnn/test_binary_ops.py, tests/python/contrib/test_cmsisnn/test_conv2d.py, tests/python/contrib/test_cmsisnn/test_fully_connected.py, tests/python/contrib/test_cmsisnn/test_fuse_pads.py, tests/python/contrib/test_cmsisnn/test_generate_constants.py, tests/python/contrib/test_cmsisnn/test_invalid_graphs.py, tests/python/contrib/test_cmsisnn/test_networks.py, tests/python/contrib/test_cmsisnn/test_pooling.py, tests/python/contrib/test_cmsisnn/test_remove_reshapes.py, tests/python/contrib/test_cmsisnn/test_softmax.py, tests/python/contrib/test_cmsisnn/utils.py, tests/python/relay/aot/test_crt_forward_declarations.py
Follow up from https://github.com/apache/tvm/pull/13522#discussion_r1040157137.
Range for dtype was being sought differently from inside various CMSIS-NN tests. This commit provides
a common global function inside aot.py under tvm.testing that can provide (min, max) values based on the dtype.
In future, other AOT based targets can make use of this function to obtain the range.
cc @Mousius @lhutton1 @NicolaLancellotti
=> [CMSIS-NN] Global function that provides range based on dtype

python/tvm/relay/qnn/op/canonicalizations.py
**Motivation:**
It is possible to disable specific passes through the "disabled_pass" parameter in the Pass Context. These "disabled" passes can be optional for one target and mandatory for another one.
Since lookup table for some QNN operations (tanh, round and etc.) is calculated on the host and some of disabled passes can be required for the host, no need to disable these passes. This constant calculation/ evaluation is orthogonal to the compilation process for specific target.
**What was changed:**
This commit creates its own compilation Pass Context for lookup table
calculation and evaluation (for elemwise QNN ops: tanh, sqrt ...).
=> [QNN] Change in Pass Context for lookup table calculation

python/tvm/relay/op/contrib/clml.py, src/relay/backend/contrib/clml/codegen.cc, tests/python/contrib/test_clml/test_ops.py
Enabled clml supported nn.pad+nn.conv2d fusion pattern in clml pattern table
=> [CLML][RELAY] Enable Pad and Conv2d layer fusion

python/tvm/script/highlight.py
- Add the hint for missing "packaging" package
=> [TVMScript] More accurate hints for ImportError

include/tvm/tir/data_layout.h, python/tvm/tir/data_layout.py, src/tir/ir/data_layout.cc, tests/python/unittest/test_tir_data_layout.py
This PR brings the support for specifying axis dtype when creating `tir::Layout`.
Prior to this PR, the construction of `tir::Layout` uses int32 for every axis. With this specification, the output of `BijectiveLayout::ForwardShape/BackwardShape(...)` will always be int32 shape, no matter if the input shape is in int32 or int64.
As we will be gradually moving to int64 default dtype for tensor shapes, there are increasingly more cases where we need to handle int64 shapes. Thus, `tir::Layout` need some updates for int64 shapes. Since the creation of an `tir::Layout` instance is agnostic to the dtype of the shapes that the instance will handle later, one way of the such updates is to add a dtype parameter to the constructor of `tir::Layout`, to specify the dtype explicitly. This PR enhances …
=> [TIR] Create Layout with specified axis dtype

python/tvm/meta_schedule/relay_integration.py, tests/python/unittest/test_meta_schedule_relay_integration.py
Now there is no way to disable passes in MetaShedule tuner. This commit adds new parameter `disabled_pass` in tuning API (`tune_relay`/`compile_relay`). It can be used for different experiments and non default behavoir.
=> [MetaSchedule] Add "disabled_pass" option in tuning API

src/node/structural_hash.cc, src/support/base64.h, tests/python/unittest/test_container_structural_equal.py, tests/python/unittest/test_runtime_container.py
This PR add struct equal/hash and json serialization support for shape tuple. Testcases added.
=> [CONTAINER] Struct Hash/Equal and JSON support for ShapeTuple

python/tvm/ir/base.py
For the users who use vscode to write code, Pylance in vscode will shadow  the code below the function calls `tvm.ir.load_json/save_json` and tell users "Code is unreachable" like the picture below:
The issue maybe confuses users and make the code a little "dirty".
This PR fixes this by adding a return type hint to the functions `load_json` and `save_json`.
=> [BugFix] Pylance emits the warnning 'Code is unreachable' 

python/tvm/topi/nn/conv2d.py, tests/python/topi/python/test_topi_conv2d_int8.py
topi.arm_cpu.schedule_conv2d_NHWC_quantized_native was failing compilation in case the input channels divided by 4 was less than 4.
This was because we were splitting this axis by a factor of 4 to create appropriate loop nest for tensorize, but then tensorize was assuming that the outer axis bound was divisible by 4.
If the outer bound was less than 4, compilation failed, if it was greater than 4 but not divisible by 4, we were occasionally accessing data outside of tensor, which luckily was padded due to alignment (I think).
So here we make sure that we explicitly pad the input axis such that the outer loop will always be divisible by 4.
There are also some refactors to test_topi_conv2d_int8.py:
- decouple the tests using pytest.parametrize
- extend the NHWC int8 schedules test to test …
=> [TOPI][bugfix] Fix a bug in arm_cpu int8 dotprod schedule and modernize tests

apps/benchmark/adreno/adreno_gpu_bench_texture.py, apps/benchmark/adreno/bench.py, apps/benchmark/adreno/bench.sh, tests/scripts/ci.py
Benchmarks for various networks listed below with fp16 and fp32. resnet-18, resnet-34, resnet-50, vgg-16, vgg-19, densenet-121, inception_v3, mobilenetv1, squeezenet_v1.0, squeezenet_v1.1
=> [BENCHMARK][ADRENO] Adreno Benchmarks with texture

python/tvm/topi/generic/conv2d.py
This small PR enhances generic conv2d TOPI schedules to be even more reusable.
1. Continues [PR #6714](https://github.com/apache/tvm/pull/6714) and expose memory scope via ```mem_scope```
2. Enhanches [schedule_conv_NCHWc_cpu_common_int8](https://github.com/apache/tvm/blob/f3d3ecebe189af77ba3ac5163882591aaf67d8b3/python/tvm/topi/generic/conv2d.py#L124) and [schedule_conv_NCHWc_cpu_1x1_int8](https://github.com/apache/tvm/blob/f3d3ecebe189af77ba3ac5163882591aaf67d8b3/python/tvm/topi/generic/conv2d.py#L271)
Does **not change current behaviour**, memory scope remains "global" by default.
Flexibility and reusability of key generic schedules is desirable for targets, especially custom ISA/ASIC.
There are use-cases where cache memory is not directly visible ("local") but generic TOPI is still …
=> [TOPI] Expose mem_scope from generic conv2d variants to be more reusable

apps/benchmark/README.md
Steps to reproduce Adreno (Texture) benchmarks via adreno docker on given device.
=> [BENCHMARKS][ADRENO] Documentation for Adreno (Texture) benchmarks

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
This PR adds support for [QAttention](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.QAttention) - quantized version of [Attention](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Attention) from Microsoft onnxruntime contrib opset.
An explanation and illustration of how this layer works can be found, for example, in @lena-voita [NLP course](https://lena-voita.github.io/nlp_course/seq2seq_and_attention.html).
=> [ONNX] Add converter for QAttention from Microsoft onnxruntime contrib opset

src/tir/schedule/primitive/decompose_padding.cc, tests/python/unittest/test_tir_schedule_decompose_padding.py
This change fix a bug when `decompose_padding(blk, loop of single child)`. Also forbid decompose when the padding predicate is trivial.
=> [Schedule][Bugfix] Fix decompose padding wrt the single child subtree

src/runtime/contrib/sort/sort.cc
**Summary:**
This is a simple rewrite of hand-coded top-k function used for CPU targets. 
The old implementation sorted each axis and then took the biggest k elements.
The new implementation does a single pass of each axis, keeping a min heap to store the top-k elements up to that point. 
If n is the size of the array, and we want to find top k, the old implementation has runtime in O(nlogn) with additional memory O(n) to store the sorted array. The new implementation is O(n log k), and in practice is probably amortized to O(n / k * log k) in many scenarios and only requires O(k). Note n >> k most of the time.
In practice this new kernel led to a 20x speedup over existing one. On a Xeon Platinum 8370C CPU @ 2.80GHz for input shape [1, 3050] with k = 15, the latency went from 200us --> …
=> [Contrib][Sort] Faster Top-K Implementation

apps/microtvm/arduino/template_project/microtvm_api_server.py, apps/microtvm/zephyr/template_project/microtvm_api_server.py, python/tvm/micro/project.py, python/tvm/micro/project_api/server.py, tests/micro/arduino/conftest.py, tests/micro/arduino/test_arduino_error_detection.py, tests/micro/arduino/test_arduino_rpc_server.py, tests/micro/arduino/test_arduino_workflow.py, tests/micro/arduino/test_utils.py, tests/micro/project_api/test_arduino_microtvm_api_server.py, tests/micro/zephyr/test_zephyr.py
In current TVM, project API ignores the default values that are set for each project option in a project API server. This results in extra function handlers to specify the default value for those options in runtime.
This PR searches through available ProjectOptions for a project API server and adds default values for unspecified options before sending the `options` to API call function handler.
=> [microTVM]Add default value to unspecified project options in project API

python/tvm/relay/op/transform.py, tests/python/relay/test_op_level3.py
Fixed examples in documentation for operators:
* reverse_reshape,
* sparse_fill_empty_rows,
* sparse_reshape,
* segment_sum,
* unique,
* stft.
and fixed some typos, and change formatting of some functions to be uniform with the rest of the code.
Also, make two small changes in tests/python/relay/test_op_level3.py, related to tests for functions defined in relay/transform.py.
=> [Relay][Docs] Fixed examples in relay/transform.py documentation

src/driver/driver_api.cc, src/tir/transforms/lower_async_dma.cc, tests/python/contrib/test_hexagon/test_async_dma_pipeline.py, tests/python/contrib/test_hexagon/test_software_pipeline_async.py
Denote DMA cache bypass as experimental feature CC @janetsc
=> [Hexagon] Denote DMA cache bypass as experimental feature

apps/benchmark/README.md, apps/benchmark/adreno/adreno_gpu_bench_clml.py, apps/benchmark/adreno/bench.sh, python/tvm/relay/op/contrib/clml.py, src/runtime/contrib/clml/clml_runtime.cc, tests/scripts/ci.py
Various benchmarks enabled for CLML BYOC backend for Adreno GPU.
Networks resnet-18, resnet-34, resnet-50, densenet-121, inception_v3, mobilenetv1, squeezenet_v1.0, squeezenet_v1.1 are added with FP16 and FP32 dtypes.
Fixes added to handle batch_flatten, dropout to get largest sub graph possible.
CLML subgraphs runs under OpenCL runtime context, hence CLML execution is accounted as part of OpenCL profiling.
=> [BENCHMARKS][CLML] Adreno benchmarks with CLML BYOC path added

vta/runtime/runtime.cc
Previously, this line caused a warning for `-Wmaybe-uninitialized` when compiling in g++ 11.3.0.
=> [VTA] Provide zero-initialization for VTAGenericInsn

python/tvm/script/ir_builder/tir/ir.py, python/tvm/te/__init__.py, python/tvm/tir/__init__.py, python/tvm/tir/op.py, tests/python/unittest/test_tvmscript_roundtrip.py
Hi,
This is a bug fix discussed [here](https://github.com/apache/tvm/issues/13674). Any further suggestion is welcome.
cc @junrushao
=> [BugFix][TVMScript] Fix the roundtripability of  intrinsic pow

include/tvm/tir/data_type_rewriter.h, src/tir/ir/data_type_rewriter.cc, src/tir/transforms/narrow_datatype.cc, tests/python/unittest/test_te_create_primfunc.py
Previously, even if the dtype of the rhs of `LetStmt` is casted to int64, the bound variable doesn't get updated. This results in the following invalid IR to be generated:
```
p0_red_temp_v0 = T.alloc_buffer([T.int64(1), T.int64(56), T.int64(56)], dtype="int32")
...
for ax0, ax1, ax2, k3 in T.grid(T.int64(1), T.int64(56), T.int64(56), T.int64(64)):
with T.block("p0_red_temp"):
...
v_p0_red_temp_v0: T.int32 = T.Select(p0_red_temp_v1[v_ax0, v_ax1, v_ax2] > p0[v_ax0, v_ax1, v_ax2, v_k3] or (p0_red_temp_v1[v_ax0, v_ax1, v_ax2] == p0[v_ax0, v_ax1, v_ax2, v_k3] and T.Cast("int64", p0_red_temp_v0[v_ax0, v_ax1, v_ax2]) < v_k3), T.Cast("int64", p0_red_temp_v0[v_ax0, v_ax1, v_ax2]), v_k3)
p0_red_temp_v0[v_ax0, v_ax1, v_ax2] = v_p0_red_temp_v0
```
cc @vinx13
=> [TIR] Fix dtype mismatch error due to LetStmt

src/auto_scheduler/feature.cc, tests/python/unittest/test_auto_scheduler_feature.py
0-dim buffers get lowered to a 0-dim buffer and a 1-dim buffer decl. We explicitly check for this case and return a stride of 1.
@merrymercy @vinx13
=> [Fix,AutoScheduler] Handle 0-dim buffers in featurization

python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/avg_pool.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/common.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/gemm.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/max_pool.py, python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/multi_channel_convolve.py
This attempts to replace the CMSIS-NN header with a more portable alternative and avoid dependence on CMSIS
=> [microTVM] Replace arm_nnsupportfunctions.h with arm_acle.h

python/tvm/micro/model_library_format.py, tests/python/relay/aot/test_crt_aot.py
Follow up from: https://github.com/apache/tvm/pull/12789
-Fixed IO size map preparation in MLF export
-Added a separate test to detect output size from MLF codegen
-MLF size is not used in aot.py because its unavailable in case of packed apis
cc @Mousius
=> [AOT] Added a test for detecting output size post MLF export

python/tvm/utils/roofline/__init__.py
In the switch to multiple possible peakflops measurement, the logic to add all of them was skipped. Instead only the last was added.
@AndrewZhaoLuo
=> [Fix,Roofline] Fix roofline handling of multiple peak flops

python/tvm/micro/model_library_format.py, tests/python/unittest/test_micro_model_library_format.py
Following from #12789, this adds support for determining the output tensor name from the input model within the MLF metadata json.
Co-authored-by: Ashutosh Parkhi <ashutosh.parkhi@arm.com>
=> Add support for named outputs in MLF archive

python/tvm/relay/backend/contrib/ethosu/legalize.py, python/tvm/relay/backend/contrib/ethosu/util.py, python/tvm/relay/op/contrib/ethosu.py, tests/python/contrib/test_ethosu/test_codegen.py
A separate nn.pad relay operator is legalized to an Ethos-U depthwise_conv2d operator. For ethosu_depthwise_conv2d the hardware only supports padding up to 31, 31, 32, 32, 32, so the pad size for legalization on the NPU is within these limits.
=> [microNPU] Add support for TFLite PAD

web/package-lock.json, web/package.json, web/src/webgpu.ts
The WebGPU api calling in web runtime is pretty old, it only runs on old browsers like Chrome 83.
I have tried to upgrade these API calling to the latest, but not sure whether it is correct completely.
Jest testing is passed.
Changes:
- Upgrade WebGPU API calling.
- Update @webgpu/types to the latest version (0.1.24).
- `package-lock.json` has been migrated to v2 (This is the npm 7+ behavior when upgrade some npm package).
Notice: I didn't change the version of this package. This work should be done by TVM team.
=> [Web] Try to upgrade WebGPU API usage to the latest

python/tvm/relay/frontend/tflite.py, tests/python/frontend/tflite/test_forward.py
- Set tensor name as the source name of span during the conversion of TFLite model
- Add structural_equal comparisons with and without set_span to the existing test cases
- Add span test cases for frequent conversions
=> [Relay][Frontend] Span Filling TFLite

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_bn_dynamic.py, tests/python/frontend/tensorflow/test_control_flow.py, tests/python/frontend/tensorflow/test_debugging.py, tests/python/frontend/tensorflow/test_forward.py, tests/python/frontend/tensorflow/test_no_op.py
- Set node name as the source name of span during the conversion of Tensorflow1 model
- Add structural_equal comparison with and without set_span to the existing test cases.
- Add span test cases for frequent conversions.
=> [Relay][Frontend] Span Filling TensorFlow 1

include/tvm/meta_schedule/postproc.h, python/tvm/meta_schedule/postproc/__init__.py, python/tvm/meta_schedule/postproc/disallow_async_strided_mem_copy.py, src/meta_schedule/postproc/disallow_async_strided_mem_copy.cc, src/tir/transforms/lower_async_dma.cc, tests/python/unittest/test_meta_schedule_postproc_disallow_async_strided_mem_copy.py
…ove schedules that use async strided mem copies.
This is used to remove all of the schedules that would be created by MS that would violate the contiguous requirement of async DMA copies on hexagon. Additionally, this updates the logic checking for strided copies to cover all scenarios. This is a band aid for the issue until we can find a better way to handle this. 
@masahi @adstraw
=> Add DisallowAsyncStridedMemCopy post processor to rem 

apps/microtvm/zephyr/template_project/microtvm_api_server.py
This PR adds serial number to flash command (nrfjprog) to fix cases where multiple devices are available.
cc @gromero
=> [microTVM][Zephyr] Fix flash command for nrfjprog

python/tvm/micro/model_library_format.py
This PR fixes error introduced by #13704
cc @Mousius @driazati
=> [CI] Fix MLF input and output name map

src/te/operation/create_primfunc.cc, src/tir/ir/specialize.cc, tests/python/unittest/test_te_create_primfunc.py
Fix the issue when `te.extern` use explicit buffer load, create_primfunc would return a func with aliased buffer decls before. Also fix some minor typo bug in `specialize`.
=> [TE][PrimFunc] Fix create primfunc from te extern with explicit buffer load

src/relay/backend/name_transforms.cc, src/relay/backend/name_transforms.h, tests/cpp/name_transforms_test.cc
Adding transformations to Rust-style alongside the existing C-style transforms.
Co-authored-by: Ashutosh Parkhi <ashutosh.parkhi@arm.com>
=> Add Name Transforms for Rust style

ci/jenkins/docker-images.ini
After the NPU driver update to 22.11, changes need
to be tested with latest docker build. This commit
updates the hash for ci_cpu from tlcpackstaging.
https://github.com/apache/tvm/pull/13637
cc @lhutton1
=> [Docker update] Update ci_cpu tag to the latest from tlcpackstaging

tests/python/contrib/test_ethosu/test_legalize.py
Added a legalization test for stand-alone pad operation which is legalized to depthwise operation on the NPU.
=> [microNPU] Add a legalization test for TFLite PAD

src/tir/transforms/lower_intrin.cc, tests/python/unittest/test_target_codegen_vulkan.py
Negative numerators to modulo/remainder operations are not supported by the Vulkan API.  While the SPIR-V instructions
[`OpSRem`](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSRem) and [`OpSMod`](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSMod) have identical semantics to `tir::Mod` and `tir::FloorMod`, respectively, use of either instruction within Vulkan results in undefined behavior.  From the [Vulkan spec](https://registry.khronos.org/vulkan/specs/1.3/html/chap37.html#spirvenv-op-prec):
> For the OpSRem and OpSMod instructions, if either operand is negative the result is undefined.
>
> Note: While the OpSRem and OpSMod instructions are supported by the Vulkan environment, they require non-negative values and thus do not enable additional …
=> [Arith] Use ConstIntBound to remove negative numerator when lowering

cmake/modules/OpenCL.cmake
Previously, setting `set(USE_OPENCL ON)` would result in a warning, stating that the runtime wrapper for OpenCL would be used.  Since this is the desired behavior when OpenCL support is enabled, and is not something that a user should fix, this commit removes the warning.
=> [CMake][OpenCL] Remove warning for OpenCL wrapper

python/tvm/relay/op/strategy/x86.py, python/tvm/topi/x86/batch_matmul.py, python/tvm/topi/x86/dense.py, tests/python/relay/test_op_level10.py
This PR is to tensorize X86 int8 batch matmul  based on last AMX PR: https://github.com/apache/tvm/pull/13642
unified batch matmul VNNI and AMX to `batch_matmul_int8`, then chose different SIMD(VNNI or AMX) of the target to finish tensorizing. 
(basicly the same way to x86 dense_int8)
=> [Tensorize][TOPI] Add AMX Tensorizing for int8 batch matmul

include/tvm/relay/transform.h, include/tvm/tir/stmt.h, python/tvm/relay/qnn/op/_qnn.py, python/tvm/relay/qnn/op/legalizations.py, python/tvm/relay/qnn/strategy/hexagon.py, python/tvm/topi/hexagon/qnn/__init__.py, python/tvm/topi/hexagon/qnn/conv2d_alter_op.py, python/tvm/topi/hexagon/qnn/nn.py, python/tvm/topi/nn/qnn.py, src/meta_schedule/schedule_rule/auto_inline.cc, src/relay/qnn/op/convolution.cc, src/relay/qnn/op/requantize.cc, src/relay/qnn/pass/legalize.cc, tests/python/contrib/test_hexagon/test_wo_qnn_canonicalization.py
This commit improves performance of different models tuned with MetaScheduler for Hexagon target and without QNN canonicalization.
Benchmarking of several models on Snapdragon 8gen1 and tuned with MS:
Model               | QNN canon enabled, ms | QNN canon disabled, ms |   speedup   |
-----------------|-----------------------------|----------------------------|--------------|
ResNet, int8      |                   50                   |                     48                |     +4.2%     |
Inception, int8  |                  103                  |                    106               |      -2.8%     |
SRGAN, int8      |                 348                   |                    431               |     -19.3%    |
**What was done:**
1. Added 2 new passes: `QnnLegalize `and …
=> [Hexagon][QNN] Improve performance wo QNN canonicalization

apps/microtvm/reference-vm/base-box/base_box_setup_common.sh, docker/Dockerfile.ci_arm, docker/Dockerfile.ci_cortexm, docker/Dockerfile.ci_cpu, docker/Dockerfile.ci_gpu, docker/Dockerfile.ci_hexagon, docker/Dockerfile.ci_i386, docker/Dockerfile.ci_lint, docker/Dockerfile.ci_minimal, docker/Dockerfile.ci_riscv, docker/Dockerfile.ci_wasm, docker/Dockerfile.demo_android, docker/Dockerfile.demo_rocm, docker/Dockerfile.demo_vitis_ai, docker/install/ubuntu2004_install_llvm.sh, docker/install/ubuntu_install_nrfjprog.sh, docker/install/ubuntu_install_python.sh
This PR makes changed to update ci_cortexm to 20.04. Here is a list of changes:
- Updates nrfjprog to latest (10.18.1) to fix issues related to running microTVM tests inside docker. The main issue was that with older version commands like nrfjprog --com was not working even with docker --privileged.
- Update python install script to support python 3.7 in 20.04 -> we keep using python 3.7 in ubuntu 20.04 until its EOL
- Add script to install LLVM in ubuntu 20.04
cc @driazati @gromero
=> [CI][Docker][Cortex-M]Update scripts to update ci_cortexm to Ubuntu 20.04

docs/install/from_source.rst
Although TVM does not, but `tvmc` depends on `typing-extensions`, which is not mentioned in the documentation.
=> [Docs] Add `typing-extensions` dependency guide

python/tvm/meta_schedule/relay_integration.py
Add the `instrument` parameter from the `PassContext` api to the meta schedule tuning api.
@masahi @junrushao
=> [MetaSchedule] Add pass instrument to MetaSchedule api

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
- Set node name as the source name of span during the conversion of ONNX model.
- Assign node name to a node based on op type when it is empty.
- To get the reference of renamed nodes. Add a function to export the ONNX model after conversion.
- Add structural_equal comparisons with and without set_span to the existing test cases.
- Add span test cases for frequent conversions.
- Add span test case for exporting model parameter.
=> [Relay][Frontend] Span Filling ONNX

python/tvm/relay/op/strategy/x86.py, python/tvm/topi/nn/conv2d.py, tests/python/topi/python/test_topi_conv2d_NCHWc.py
This PR supports conv2d_NCHWc with groups.
cc @masahi @wrongtest-intellif
=> [TOPI][OP] Support grouped conv2d_NCHWc

gallery/how_to/work_with_microtvm/install_cmsis.rst, gallery/how_to/work_with_microtvm/micro_aot.py, gallery/how_to/work_with_microtvm/micro_autotune.py, gallery/how_to/work_with_microtvm/micro_tflite.py
Pr #13656 added support for CMSIS NN from a new GitHub location.
The project at the new location uses a new header `arm_acle.h` which is not always present.
This pr removes the CMSIS dependency for the tutorials in `gallery/how_to/work_with_microtvm` when the tutorials are run with Zephyr.
We need this pr, otherwise, when the docker image will be updated there will be errors, due to the missing header.
=> Remove tutorials CMSIS dependency when not needed

src/target/parsers/aprofile.cc, tests/cpp/target/parsers/aprofile_test.cc
The `key` in a target is used in dispatching to different strategies. 
In most of the code base `arm_cpu` implies also having `cpu`. E.g. in `python/tvm/target/target.py`:
```
def arm_cpu(...):
opts = ["-keys=arm_cpu,cpu", "-device=arm_cpu"] + pre_defined_opt
opts = _merge_opts(opts, options)
return Target(" ".join(["llvm"] + opts))
```
In `src/target/parsers/mprofile.cc`: 
```
static Array<String> MergeKeys(Optional<Array<String>> existing_keys) {
const Array<String> kExtraKeys = {"arm_cpu", "cpu"};
if (!existing_keys) {
return kExtraKeys;
}
Array<String> keys = existing_keys.value();
for (String key : kExtraKeys) {
if (std::find(keys.begin(), keys.end(), key) == keys.end()) {
keys.push_back(key);
}
}
return keys;
}
```
However A-series targets did not have both `arm_cpu` and `cpu` keys. …
=> [Target] Make `key=arm_cpu` --> `key=arm_cpu,cpu` on AArch64

docker/Dockerfile.ci_minimal, docker/install/ubuntu1804_install_aarch64_cross_compile.sh, docker/install/ubuntu1804_manual_install_llvm_cross_aarch64.sh
This PR is a prerequisite to #13714 and needs to be merged before. It contains the changes to the ci_minimal docker image to support minimal cross-compilation of TVM to aarch64.
=> [CI] Update ci_minimal docker image to cross-compile TVM to aarch64

tests/python/unittest/test_arith_iter_affine_map.py
Parametrization helped in the debugging of https://github.com/apache/tvm/pull/13530, but is not otherwise related to that PR.
=> [UnitTest] Parametrized test_arith_iter_affine_map::test_padding

python/tvm/relay/op/contrib/ethosn.py, src/runtime/contrib/ethosn/ethosn_device.cc, src/runtime/contrib/ethosn/ethosn_device.h, src/runtime/contrib/ethosn/ethosn_runtime.cc, src/runtime/contrib/ethosn/ethosn_runtime.h, tests/python/contrib/test_ethosn/test_conv2d.py, tests/python/contrib/test_ethosn/test_leaky_relu.py
This commit removes support for NPU driver 22.08 now
that tlcpack contains the latest docker image for
ci_cpu that comprises support for NPU driver 22.11.
cc @lhutton1
=> [ETHOSN] Remove support for NPU driver 22.08

src/meta_schedule/measure_callback/update_cost_model.cc
Runner sec is an Optional ObjectRef, so we need to check it's defined before we access its value.
=> [MeteSchedule] Bugfix: Add checks for nullable `run_secs`

python/tvm/tir/buffer.py, tests/python/unittest/test_tvmscript_regression.py
This PR fixes a bug of TIR Buffer `__getitem__` on Python side.
Whenever the `__getitem__` parameter is a multi-dim slice, on non-slice dimension a Range will be created. Prior to this PR, that range will have int32 dtype in regardless of the `start`, while the proper behavior is to generate the extent according to the dtype of `start` when `start` is a PrimExpr.
This PR fixes the issue and provides a regression test.
=> [TIR][Fix] Buffer slicing using index dtype as extent

python/tvm/tir/buffer.py, src/tir/ir/data_type_rewriter.cc, tests/python/unittest/test_te_create_primfunc.py, tests/python/unittest/test_tvmscript_regression.py
This PR fixes a bug of IndexDataTypeNormalizer that is used by CreatePrimFunc.
#13449 enhanced the normalizer by unwrapping unnecessary casts, by the rule that “if the value to be casted already has the target index dtype`, the cast will be omitted. However, there are cases where a cast here is for other purpose. Like in image resize operators, there are sometimes rounding operation for indices, like
```python
T.Cast("int64", T.round(T.float32(128) / T.Cast("float32", oh) * T.Cast("float32", v_i2), dtype="float32"))
```
is used as a final index. Note that this PrimExpr contains casts that directly operated on indices, such as `T.Cast("float32", oh)`. This cast is for division purpose, in order to have floating point division result. As a result, it is not expected to unwrap such casts, …
=> [TIR][Fix] IndexDataTypeNormalizer not unwrapping float casting

src/tir/schedule/primitive/cache_read_write.cc, tests/python/unittest/test_tir_schedule_cache_read_write.py
Applying `cache_write`, when there's a allocate_const node in the TIR causes the cache write block to be inserted at the incorrect location. This patch tries to fix that error.
Co-authored-by: Abhikrant Sharma <abhikran-quic@quicinc.com>
=> [TIR] Fix cache_write bug with allocate const node

docs/dev/how_to/debugging_tvm.rst, gallery/tutorial/autotvm_relay_x86.py, gallery/tutorial/tvmc_command_line_driver.py, include/tvm/relay/expr.h
- [[Fix] Fix Typo in relay/expr.h](https://github.com/apache/tvm/commit/12539a88b54bdf1f301810ac611c50d7ad71f65d)
- `vor` -> `var`
- [[Fix] Remove Duplicated Right Angle Bracket](https://github.com/apache/tvm/commit/e2cc3309f493c6685bb040ecd9f9d924cd0e89f9)
- `<level>>` -> `<level>`
- [[Fix] Add WhiteSpace](https://github.com/apache/tvm/commit/25ab989021f0ad09d50fe877e2c07a6110f0e6c6)
- Add space after comma
- [[Fix] Fix Parameter Values](https://github.com/apache/tvm/commit/138a8354d06adfb49ee74e7d6ee90b4495925112)
- In the above example of this comment, the number of trials is `20` and the number of early stopping is `100`.
=> [FIX] Fix Typos in Docs and Comments

include/tvm/tir/function.h, src/tir/analysis/control_flow_graph.h
This PR fixes some warnings from the latest clang compiler.
=> [FIX] Minor Compilation Warning Fixes

python/tvm/tir/tensor_intrin/hexagon.py, tests/python/contrib/test_hexagon/test_vtcm_bandwidth.py
Added some intrins for user dma on hexagon. Currently these seem to perform worse than all other options used in the test. 
@adstraw
=> [Hexagon] Add hexagon user DMA intrins for tensorization

.asf.yaml, ci/jenkins/docker-images.ini
This updates ci_minimal to use the changes following on to #13714 and makes the job required for merges. Skipping CI since the job is currently running on PRs/commits but failing since the old ci_minimal image doesn't have the cross-compilation dependencies.
=> [skip ci][ci][docker] Add cross compilation libs

python/tvm/relay/op/contrib/ethosu.py, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_legalize.py
Does not fuse min and max operations with requantize if there are different scales as it is not supported on NPU. Since there are hardware constraints, we cannot perform min or max operation fused with requantize (please look at NPU_SET_OFM_SCALE register description https://developer.arm.com/documentation/102420/0200/Programmers-model/Command-stream/cmd1-commands-) when we have different scales.
min/max operations with matching scales are offloaded to NPU as ethosu_binary_elementwise
min/max operations with different scales are offloaded to NPU as ethosu_binary_elementwise + ethosu_identity.
=> [microNPU] Add hardware constraints for binary elementwise

python/tvm/tir/schedule/_type_checker.py
I came across this bug under python3.8.0 with error from `typing.get_args()` while trying to run testcases like `tests/python/unittest/test_tir_schedule_set_axis_separator.py::test_set_axis_separator[transform_layout_named]`
```
>           if get_origin(tp) is collections.abc.Callable and res[0] is not Ellipsis:
E           IndexError: tuple index out of range
```
And the root cause here is a difference  between python3.8.0 and later version:
```diff
get_args(Callable[[], T][int]) == ([], int)
"""
-     if isinstance(tp, _GenericAlias):    // python3.8.0
+    if isinstance(tp, _GenericAlias) and not tp._special:    // python3.8.15
res = tp.__args__
if get_origin(tp) is collections.abc.Callable and res[0] is not Ellipsis:
}
```
So I added it back to …
=> [Bugfix][TIR] Fix version conflict with typing for Python 3.8.0

src/tir/transforms/remove_no_op.cc, tests/python/unittest/test_tir_transform_remove_no_op.py
This PR tries to fix the crash of the pass `RemoveNoOp` when the condition of IfThenElseNode can be statically determined. For example:
```python
@L.prim_func
def remove_no_op():
if True:
L.evaluate(0)
else:
L.evaluate(0)
```
This case will cause `Segment fault` error because `RemoveNoOp` don't cover the case the return of `Parent::VisitStmt_` is not a `IfThenElseNode`, which will result in the `stmt.as<IfThenElseNode>()`  being `null`.
=> [TIR]Fix the crash of the pass RemoveNoOp

include/tvm/relay/transform.h, src/relay/backend/build_module.cc, src/relay/transforms/annotate_texture_storage.cc
Removed redundant and unused parameter from AnnotateMemoryScope pass.
=> [Adreno] Update interface of AnnotateMemoryScope pass

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Earlier I added converter for `QAttention` (see [PR#13654](https://github.com/apache/tvm/pull/13654)).
In this PR, I've added support for `past` input and `unidirectional` attribute in `Attention`. I've also moved the common code for `QAttention` and `Attention` into a base class.
=> [ONNX] Extend converter for Attention from Microsoft onnxruntime contrib opset

docs/conf.py, gallery/how_to/work_with_microtvm/micro_mlperftiny.py, python/tvm/micro/testing/utils.py, tests/micro/zephyr/utils.py, tests/scripts/request_hook/request_hook.py, tests/scripts/task_python_microtvm.sh
This PR adds a tutorial on how to generate an MLPerftiny submission on Zephyr OS using microTVM.
cc @alanmacd @gromero @mkatanbaf
=> [microTVM] Add tutorial on how to generate MLPerfTiny submissions

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/cache_index.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_cache_index.py
Much of the index computation is duplicated, so this PR is to do common subexpression analyze when performing cache_index.
And because all block var related computation could be cached, buffer-based cache is somehow too restrictive. So here make it block-based.
A threshold number is needed when identifying a common sub expr, since we only want to cache the most frequently appeared sub expressions.  A common use case may be like this: calling _tvm.arith.detect_common_subexpr()_ and determining based on its result whether to perform cache_index and its corresponding threshold.
cc @wrongtest-intellif @Hzfengsy
=> [TIR][Schedule] Improve cache_index to cache common subexpressions

docker/install/ubuntu_init_zephyr_project.sh, docker/install/ubuntu_install_zephyr.sh, docker/install/ubuntu_install_zephyr_sdk.sh
This PR updates Zephyr version and Zephyr SDK version to the latest release only in docker build scripts.
=> [docker][microTVM]Update zephyr version to 3.2 and Zephyr SDK to 0.15.2

python/tvm/tir/schedule/_type_checker.py
This PR fixes the following issue with recent PR: https://github.com/apache/tvm/pull/13744#issuecomment-1399038390
Tested with Python 3.8.0, 3.8.15, 3.9.0, 3.10.0.
cc. @vinx13 @Ever-Kid @junrushao
=> [Bugfix][TIR] Fix version conflict with typing for different Python versions (3.8.0-3.10.0)

src/meta_schedule/schedule_rule/schedule_rule.cc
This PR adds fp16-16-32 TensorCores intrinsics to the default auto-tensorization settings.
cc @junrushao @vinx13
=> [MetaSchedule] add fp16-16-32 TensorCores rule to default settings

include/tvm/script/printer/doc.h, include/tvm/script/printer/ir_docsifier.h, python/tvm/script/printer/doc.py, src/script/printer/doc.cc, src/script/printer/ir/ir.cc, src/script/printer/ir/misc.cc, src/script/printer/legacy_repr.cc, src/script/printer/tir/block.cc, src/script/printer/tir/buffer.cc, src/script/printer/tir/expr.cc, src/script/printer/tir/for_loop.cc, src/script/printer/tir/ir.cc, src/script/printer/tir/stmt.cc, src/tir/analysis/control_flow_graph.cc
This PR adds ObjectPath to LiteralDoc to allow integer/float/string/... literals to have their own object path. This is a final preparation towards structural error rendering when SEqual fails.
=> [TVMScript] Add ObjectPath to LiteralDoc

python/tvm/contrib/hexagon/meta_schedule.py
Add the option to specify the timeout manually for the local builder of the hexagon.
=> [Hexagon][Metaschedule] Add timeout_sec arg to get_hexagon_local_builder

src/runtime/threading_backend.cc
In case of three or more cores domains we starts to treat non little cores as big ones and offload work to them as well by default. This fix current modern schemes like 1-3-4 with 1 huge, 3 big cores and 4 little cores and causes tvm to use huge and big cores for inference
=> [RUNTIME] Fix determination of big/little cores domains

docker/Dockerfile.ci_cortexm, docker/Dockerfile.ci_riscv, docker/install/ubuntu_install_zephyr.sh, docker/install/ubuntu_install_zephyr_sdk.sh
This PR fixes the SDK installation and separates SDK installation from ZephyrProject installation.
Also it separates the Zephyr python environment to 3.8 which is the required version and it is different than tvm virtual env.
=> [docker][microTVM]Fix Zephyr 0.15.2 SDK installation and separate Zephyr python environment

python/tvm/topi/adreno/reduction.py, python/tvm/topi/cuda/reduction.py, src/relay/transforms/annotate_texture_storage.cc, tests/python/relay/opencl_texture/test_reduction_texture.py
1. Extend reduction through rfactor for reduction of big numbers of elements. In other case use previous straightforward approach.
2. Inject reduction postops into main reduction kernel
=> [Adreno] Optimize reduction schedule

python/tvm/driver/tvmc/target.py, tests/python/driver/tvmc/test_target_options.py
Presently --help for vitis displays the target and option string,
it has no description.  Eg:  target vitis-ai dpu<class 'str'>
This can be made more meaningful by fetching the description from the config node of the target.  Eg: Vitis AI DPU identifier
Here, adding test cases to verify the fix
Signed-off-by: MNGanesan <mnganesan@yahoo.co.uk>
=> Enhance the --help message of composite target

python/tvm/contrib/micro/meta_schedule/rpc_runner_micro.py, python/tvm/micro/build.py, python/tvm/micro/testing/pytest_plugin.py, tests/micro/zephyr/test_ms_tuning.py
This PR adds support for running candidate projects on multiple physical boards when using meta-schedule to tune micro models, and helps reducing the tuning time.
=> [microTVM] Allow multiple runners in tuning micro models with meta-schedule

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Hi, TVM
I try to add a new onnx operator QGEMM. 
Please help to review,thanks.  @AndrewZhaoLuo
=> [ONNX] QGemm support

src/runtime/crt/aot_executor/aot_executor.c, src/target/source/source_module.cc, tests/python/unittest/test_crt.py, tests/python/unittest/test_micro_model_library_format.py
When using host-driven AOT with memory pools enabled, the workspace and constant memory were not properly supported. In order for them to work properly, the \_run function (typically tvmgen_default_run()) needed to be called instead of tvmgen_default___tvm_main__() in order to properly setup the memory workspace pointers.
fixes #13777
=> [microTVM] Fix host-driven AOT memory workspaces

python/tvm/contrib/rocm.py, python/tvm/relay/op/strategy/cuda.py
Fixes https://github.com/apache/tvm/issues/13666
* Some bitcode files need to be updated
* There is a strange, device-dependent accuracy issue when using the default topi `dense` op schedule on AMDGPU (see the issue above). I confirmed that other schedule works fine.
=> [ROCM] Fixes compiling on ROCM 5 and accuracy on dense op

src/relay/backend/te_compiler_cache.cc, tests/python/unittest/test_meta_schedule_relay_integration.py
Previously, the condition `constant.Shape().size() == index_map->initial_indices.size()` was used to decide if the constant that `TECompiler` finds has its layout write already applied or not. But for 1x1 conv2d case, there seems to be a case where the rank of the weight doesn't change after layout rewriting. For example, (1, 1, 32, 16) -> (16, 4, 2, 4). 
This bug led to the same index map being applied twice on a constant during MS tuning and the final compilation.
=> [MetaSchedule] Fix for RewriteLayout + AllocateConst when the rank of the rewritten weight doesn't change

python/tvm/relay/op/contrib/clml.py, src/runtime/contrib/clml/clml_runtime.cc, tests/python/contrib/test_clml/test_ops.py
Enable the DepthToSpace and Resize bilinear operator in CLML runtime and bug fix in concat layer.
=> [CLML][RUNTIME] Enable more ops in CLML runtime

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Currently, ONNX frontend imports Unsqueeze as a sequence of expand_dims in Relay. This works fine when the axes are positive. 
However, for negative axes we need to compute the output rank and add the negative axis value to get its equivalent positive axis value. 
This commit computes the output rank as the sum of the input rank of data and the number of axis in the axes array and convert negative axes to positive. 
This commit also adds testcases for unsqueeze with negative axes and verifies the result with onnx runtime.
=> [Relay] Convert negative axes to positive when importing ONNX Unsqueeze

python/tvm/relay/op/contrib/ethosn.py, tests/python/contrib/test_ethosn/test_addition.py, tests/python/contrib/test_ethosn/test_networks.py
Introduced FoldConstant before NPU partitioning. Added a qnn.add test where both inputs are constants. Updated the number of operators remaining in the host code for ssd_mobilenet_v1 as the FoldConstant reduces the number of operators.
cc @lhutton1
=> [ETHOSN] Apply FoldConstant before NPU partitioning

docker/install/ubuntu_install_hexagon.sh
Updated sha to deal with some codegen issues that came up with the last version.
=> [Hexagon][CI] Updated sha for builder LLVM

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Support Bernoulli op on ONNX front-end
=> [ONNX] Support Bernoulli op on ONNX front-end

src/arith/detect_linear_equation.cc, tests/python/unittest/test_arith_detect_clip_bound.py
Hi~ this is a patch to handle EqNode in `detect_clip_bound`. We got some regression failure when using this methodology as the power of upstream arithmetic simplifier grows.
Many trivial cases like `x >= 4, x in [0, 4]` seems to get well simplified to `x==4`  and certain assumptions on some condition be non-eq comparation do not hold then.
=> [Arith] Support eq in detect_clip_bound

python/tvm/topi/image/resize.py
@mbrookhart 
Hi, It seems redundant, and I removed the departed one.
=> [topi] remove comment redundancy in resize.py

src/runtime/contrib/clml/clml_runtime.cc, src/runtime/opencl/opencl_common.h
Tuning cache bin is serialized through DMLC::Stream to support multiple CLML sub graphs with in a tvm module. Individual tuning cache blobs are saved to same output file.
New API on OpenCLWorkspace to enable or disable profiling on command queue rather doing this only when Timer is invoked. This is required to perform CLML operator tuning.
CLML layer profiling now uses OpenCL Timer interface.
This PR also fix avoiding pad operator offloading at the very first layer (to be specific before at least one convolution layer) due to the limitation of CLML pad operator is concerned about layout. Please refer to CLML SDK documentation for more details.
Co-Authored-By: Krishna Raju Vegiraju <quic_kvegiraju@quicinc.com>
=> [RUNTIME][CLML] OpenCLML tuning and profiling enhanced

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Support SequenceLength op on ONNX front-end and test for it
=> [ONNX] Support SequenceLength op

ci/jenkins/docker-images.ini, tests/scripts/task_config_build_hexagon.sh
The latest image ID is ci_hexagon:20230127-185848-95fa22308.
=> [Hexagon][CI] Update the docker image ID to reflect newer LLVM

src/target/llvm/codegen_llvm.cc
This function only creates alias metadata, so there isn't anything for it to create debug location information for. If `index` is used in executable code, the debug location should be emitted then.
=> [LLVM] Remove call to EmitDebugLocation from AddAliasInfo

src/te/operation/create_primfunc.cc
default value for `index_dtype_override` is null, so it would be better if the registry block of `te.CreatePrimFunc` could check args size.
=> [TIR][FIX] check args size when creating prim_func by runtime::Registry

python/tvm/script/highlight.py, tests/python/unittest/test_tvmscript_printer_highlight.py
Current `cprint` allows `PrimFunc` and `IRModule` as input. However, after the fragment printing enabled by @junrushao, we can make it robust to support any Objects that have method `script`
cc @junrushao @cyx-6
=> [TVMScript] Robustify the Highlight Printer

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Support SequenceErase op in ONNX front-end and its test in CI
=> [ONNX] Support SequenceErase op

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Support SequenceEmpty op in ONNX front-end and its test. The test is needed SequenceLength ([PR](https://github.com/apache/tvm/pull/13863) was merged for it)
=> [ONNX] Support SequenceEmpty op

docker/install/ubuntu_install_nnpack.sh
There is currently a problem building and installing NNPACK using the script `ubuntu_install_nnpack.sh`. The build fails to complete with CMake errors, complaining about missing libraries.
This issue is due to a change in the imported dependency pytorch/cpuinfo that has moved the default branch name to 'main'.
This patch has been submitted as a workaround to the issue raised at https://github.com/apache/tvm/issues/13871
CC @ashutosh-arm @leandron @driazati @areusch
=> [CI] NNPACK build issue workaround

tests/micro/common/test_autotune.py, tests/micro/common/test_tvmc.py, tests/micro/zephyr/test_ms_tuning.py, tests/micro/zephyr/test_zephyr.py, tests/micro/zephyr/test_zephyr_aot_exec.py, tests/micro/zephyr/test_zephyr_aot_exec_standalone.py, tests/micro/zephyr/test_zephyr_armv7m.py, tests/micro/zephyr/utils.py
This PR refactors some of the Zephyr tests and adds skip for each test/board that is currently failing.
=> [microTVM]Refactor test and add skip to current failing tests/boards

python/tvm/tir/tensor_intrin/x86.py, python/tvm/topi/x86/tensor_intrin.py, tests/python/unittest/test_meta_schedule_postproc_rewrite_tensorize.py, tests/python/unittest/test_meta_schedule_trace_apply.py
All `call_llvm_pure_intrin(...)` methods were rechecked and argument corresponding number of input args was corrected for some of them. Corresponding tests were upstreamed
=> [TIR][TOPI][CI] Fix number of arguments in calls of llvm_pure_intrin

src/arith/bound_deducer.cc, tests/python/unittest/test_arith_deduce_bound.py
Hi, the patch handle floordiv `a // positive` in bound deducer. So that we could know `x >= 24` in `x // 8 >= 3`
=> [ARITH] support floordiv in deduce bound

cmake/utils/FindLLVM.cmake
Currently, in `FindLLVM.cmake`, when the `llvm-config` commands fail, the error message might be `Fatal error executing: ON --libfiles` (since `USE_LLVM=ON`), which is misleading.
In this PR, `${use_llvm}` is changed to `${LLVM_CONFIG}`, and the error messages will be more comprehensible.
=> [Build] Fix misleading error messages

src/tir/analysis/stmt_finding.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/utils.h, tests/python/unittest/test_meta_schedule_database.py
The FindEntryFunc function can return a null pointer. In development I got this situation, which appears as a segfault.
=> [TIR] Handle nullptr returned by FindEntryFunc

python/tvm/tir/tensor_intrin/cuda.py, src/meta_schedule/schedule_rule/schedule_rule.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_tc.py, tests/python/unittest/test_meta_schedule_trace_apply.py, tests/python/unittest/test_tir_schedule_compute_inline.py
This PR adds Tensor Core intrinsics with `shared.dyn` scope and changes the default rules to use `shared.dyn`.
Here are the performance improvement of GEMM 1024x1024x1024 on my device (RTX-3080)
|                     |      Use `shared`         |  Use `shared.dyn`.   | Speedup  |
| ----------- | --------------------- | -------------------- | ---------- |
fp 16-16-16 | 66399.8766 GFLOPs | 71778.3808 GFLOPs |      8.1%    |
fp 16-16-32 | 44292.5893 GFLOPs | 49070.2514 GFLOPS |  10.8%    |
cc @vinx13 @junrushao @masahi
=> [MetaSchedule] Use `shared.dyn` for Tensor Core Schedule Rules

tests/lint/pylint.sh, tests/python/unittest/test_crt.py
- normalize test_crt.py temporary directory usage
- remove test_crt.py unused code and variables
- fix test_crt.py to pass pylint and add to pylint script
=> [microTVM] Clean-up test_crt.py and add to pylint

CONTRIBUTORS.md
Please join us to welcome Wrongtest (@wrongtest-intellif) as a new PMC member.
Wrongtest has been actively improving and contributing to the TIR Schedule and arithmetic analysis implementation. He’s been actively involved in several components of the TVM top to bottom, including but not limited to,
- Relay
- TOPI
- MetaSchedule
- TIR
- TVMScript
- Arithmetic analysis in TIR
- Codegen for Cuda and LLVM
- Runtime
He has a deep understanding of the whole part of one of the compilation flows in the TVM(Relay-TIR-Codegen). He focuses on applying TVM to their NPU backend, contributing features back to the community, and cultivating more active community contributors in his company.
In addition, He has been very actively participating in the community, discussion and sharing his …
=> [COMMUNITY] Wrongtest -> PMC

src/runtime/contrib/random/mt_random_engine.cc, src/runtime/thread_pool.cc, tests/python/contrib/test_random.py
**Motivation:** Assertion failed during tuning
**Error message from _thread_pool.cc:295_:**
`Check failed: num_task <= num_workers_used_ (8 vs. 1) : Request parallel sync task larger than number of threads used  workers=1 request=8`
**Main problem description:**
Tuning of the _ARM Snapdragon 888 CPU_ architecture ends with an error above.
**Suspected reason:**
Incorrect (manual) determination of the number of threads. The number of threads is determined using _MaxConcurrency_ and returns 8 threads for this architecture, but the number of actually used threads is 4. This fix urges to use automatic determination of the number of threads by passing 'zero' as 'num_threads' attribute in 'TVMBackendParallelLaunch' to avoid the abovementioned discrepancy.
=> [RUNTIME] Fix the manual determination of cores in FillDataForMeasure

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Suppose to solve issue #12922.
=> [Torch] Fix advanced indexing with NoneType index arguments

include/tvm/ir/expr.h, include/tvm/relax/expr.h, include/tvm/relax/type.h
This PR implements Relax expressions and types.
It's designed and implemented by quite a few folks collectively, listed as co-authors alphabetically.
Co-Authored-by: Altan Haan <altanh@cs.washington.edu>
Co-Authored-by: Jared Roesch <roeschinc@gmail.com>
Co-Authored-by: Lily Orth-Smith <lilyorthsmith@gmail.com>
Co-Authored-by: mbs-octoml <mbs@octoml.ai>
Co-Authored-by: Michalis Papadimitriou <mikepapadim@users.noreply.github.com>
Co-Authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
Co-Authored-by: Steven S. Lyubomirsky <slyubomirsky@octoml.ai>
Co-Authored-by: …
=> [Unity] Relax expressions and types

python/tvm/autotvm/tophub.py, tests/python/unittest/test_autotvm_dispatch_context.py
In case of ARM we might not specify -device and in this case llvm will be used while even in this case we can determin proper filename with stat since keys have architecture defined. The same situatin must with with x86
=> [TOPHUB] use keys as a keyword for searching of existing statistics

src/tir/transforms/plan_update_buffer_allocation_location.cc, tests/python/unittest/test_tir_transform_plan_update_buffer_allocation_location.py
- Fix a bug where `buffer_decl`, combined with certain usage patterns of the resulting buffer, cause an TVM-internal assert failure during TIR-compilation.
=> [tir] fix buffer_decl buffer allocation

CMakeLists.txt, include/tvm/relax/struct_info.h, rust/tvm/src/ir/relay/mod.rs, src/relax/ir/struct_info.cc
Relax tracks structural information (such as tensor shape) via `StructInfo` about the values in Relax.
Original authors are:
Co-Authored-by: Siyuan Feng [Hzfengsy@sjtu.edu.cn](mailto:Hzfengsy@sjtu.edu.cn)
Co-Authored-by: Ruihang Lai [ruihangl@cs.cmu.edu](mailto:ruihangl@cs.cmu.edu)
Co-Authored-by: Tianqi Chen [tianqi.tchen@gmail.com](mailto:tianqi.tchen@gmail.com)
=> [Unity][IR] First-class StructInfo

python/tvm/te/operation.py
Now the tvm.te.const() is just alias for tvm.tir.const()
=> [Doc] fix doc for tvm.te.const()

apps/cpp_clml/CMakeLists.txt, apps/cpp_clml/README.md, apps/cpp_clml/clml_runner.cc, apps/cpp_clml/clml_runner.h, apps/cpp_clml/main.cc, apps/cpp_clml/scripts/clml_codegen.py, cmake/modules/contrib/CLML.cmake, docker/Dockerfile.ci_adreno, python/tvm/relay/op/contrib/clml.py, src/relay/backend/contrib/codegen_json/codegen_json.h, src/runtime/const_loader_module.cc, src/runtime/contrib/json/json_runtime.h
This util generates native CLML code given a DNN model. It does import via tvmc, extracts clml_modules, get the json source and finally generates clml_models.cc that holds source for various sub graphs. cpp_clml tool has additional infrastructure to compile it as a standalone binary that runs these models.
This PR adds symbol name to the generated json graph. Also, extends const_loader interface to get constant params.
=> [CLML][CODEGEN] CLML native codegen utility

ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/generated/cortexm_jenkinsfile.groovy, ci/jenkins/generated/cpu_jenkinsfile.groovy, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/generated/hexagon_jenkinsfile.groovy, ci/jenkins/generated/i386_jenkinsfile.groovy, ci/jenkins/generated/lint_jenkinsfile.groovy, ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy, ci/jenkins/generated/minimal_jenkinsfile.groovy, ci/jenkins/generated/riscv_jenkinsfile.groovy, ci/jenkins/generated/wasm_jenkinsfile.groovy, ci/jenkins/templates/utils/Build.groovy.j2
As the PR title states, the purpose of this PR is to pass the path parameter given to cmake_build to the task_build.py script. with this PR we will be able to control compilation in different directories.
@driazati @areusch
=> [CI] Pass the 'path' parameter passed to cmake_build to the task_build.py script

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Support BitwiseAnd, BitwiseNot, BitwiseOr and BitwiseXor and test of them.
=> [ONNX] Support Bitwise operations

python/tvm/autotvm/measure/measure_methods.py, python/tvm/driver/tvmc/autotuner.py
A simple tvmc tune command currently results in a huge wall of warnings about target_host parameter being deprecated, even when the user hasn't provided a target-host cmd line argument.
We can prevent that happening from just not providing the default target-host to tvmc. Also, ensure that when the user does provide target-host, we print the warning once, not 500 times.
=> [TVMC] Stop printing a wall of warnings with tvmc tune

src/arith/analyzer.cc, src/arith/canonical_simplify.cc, tests/python/unittest/test_arith_canonical_simplify.py, tests/python/unittest/test_arith_intset.py, tests/python/unittest/test_arith_simplify.py, tests/python/unittest/test_tir_buffer.py, tests/python/unittest/test_tir_schedule_analysis.py
This PR updates the order of arithmetic analyzer simplification, by adding a stage of canonical simplification at the very beginning so that every simplification always starts with a canonical round. This is because the rewrite simplification may destroy some PrimExpr property that the canonical simplification can make use of. Therefore, adding the canonical one in the front can maximize the use of canonical simplification.
=> [Fix][Arith] Analyzer simplification starts with canonical

python/gen_requirements.py
Issue #13911 reported that newer versions of setuptools crash with the version constraint "<=1.23.*", this commit implements the suggested fix by using "<=1.23".
cc @mikeseven @driazati @leandron @Liam-Sturge
=> Fix numpy version constraint

CMakeLists.txt, include/tvm/ir/type.h, include/tvm/relax/analysis.h, include/tvm/relax/expr.h, include/tvm/relax/expr_functor.h, include/tvm/relax/struct_info.h, include/tvm/relax/struct_info_functor.h, python/tvm/ir/expr.py, python/tvm/relax/__init__.py, python/tvm/relax/analysis/__init__.py, python/tvm/relax/analysis/_ffi_api.py, python/tvm/relax/analysis/analysis.py, python/tvm/relax/expr.py, python/tvm/relax/struct_info.py, python/tvm/relax/ty.py, python/tvm/script/parser/relax/__init__.py, src/ir/function.cc, src/ir/type.cc, src/relax/analysis/shape_analysis.cc, src/relax/analysis/struct_info_analysis.cc, src/relax/ir/expr.cc, src/relax/ir/expr_functor.cc, src/relax/ir/struct_info.cc, src/relax/ir/struct_info_functor.cc, src/relax/ir/type.cc, tests/python/relax/test_analysis_struct_info_analysis.py, tests/python/relax/test_expr.py, tests/python/relax/test_struct_info.py
This PR adds struct info analysis and expr support. These are logics to construct the IR node and perform struct info related analysis.
Testcases are added to cover the IR node construction and related struct info analysis checks.
Co-Authored-by: Altan Haan <altanh@cs.washington.edu>
Co-Authored-by: Andrew Liu <andrewlliu@gmail.com>
Co-Authored-by: Hongyi Jin <3231950289@qq.com>
Co-Authored-by: Jiawei Liu <jaway.liu@gmail.com>
Co-Authored-by: Lesheng Jin <34279105+LeshengJin@users.noreply.github.com>
Co-Authored-by: masahi <masahi129@gmail.com>
Co-Authored-by: Siyuan Feng …
=> [Unity] Basic StructInfo Analysis and Expr construction

python/tvm/script/parser/core/diagnostics.py, tests/python/unittest/test_tvmscript_parser_source.py
Leaving class definitions was not correctly handled when recreating scoping information. The fix correctly pops scope whenever the indentation level becomes less than the current scope. I believe this was introduced in #12978.
@cyx-6 @junrushao
=> [TVMScript,Fix] Fix findsource when classes are indented

src/arith/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
The rules that rewrite `min(floordiv(x + (A-1), A) * A, max(x, A))` and `min(truncdiv(x + (A-1), A) * A, max(x, A))` into `max(x, A)` did not have sufficiently tight bounds.  The `truncdiv` rule required that `x >= 0`, while the `floordiv` rule had no requirement on `x`.  In both cases, the simplification was incorrect when `x==0`, as it would result in a rewrite from `min(0, max(0, A))` into `max(0, A)`.
This commit updates the rules to require that `x >= 0` for each of these rules.
=> [Arith] Updated incorrect simplification rule

src/runtime/opencl/opencl_common.h, src/runtime/opencl/opencl_device_api.cc, src/runtime/opencl/opencl_module.cc, tests/cpp-runtime/opencl/opencl_timer_test.cc
On the platforms with several OpenCL platforms (e.g. Intel CPU and NVidia GPU) it was possible to use OpenCL device only from one platform. And in case when Intel was the first in the platforms list than it wasn't possible to run model on NVidia GPU.
In this PR the init function was modified and now it is possible to use OpenCL devices from different platforms. In case when there are several GPU accelerators then it is possible to select one of them. You can use device id to select GPU device. On the code below the device names of two OpenCL devices are printed:
```python
import tvm
print("opencl 0: ", tvm.opencl(0).device_name)
print("opencl 1: ", tvm.opencl(1).device_name)
```
In case then the machine doesn't contain any GPUs then we will try to use CPU if OpenCL runtime is available.
=> [OpenCL] Refactor OpenCL init function

.github/workflows/main.yml, tests/scripts/task_config_build_static.sh
This PR partially addresses #13526 by adding static builds of tvm_runtime.a on Windows and Linux.
Tested at https://github.com/gigiblender/tvm/actions/runs/3694697105
=> [CI] Include static builds of the runtime as part of CI

tests/python/unittest/test_arith_rewrite_simplify.py
Split out each of the simplification test cases for RewriteSimplifier into independent parametrized unit tests.
=> [Arith][UnitTest] Parametrize tests of RewriteSimplifier

python/tvm/relay/op/contrib/cmsisnn.py, src/relay/backend/contrib/cmsisnn/relay_to_tir.cc, src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc, tests/python/contrib/test_cmsisnn/test_binary_ops.py
The CMSIS-NN backend will now partition quantized `int16` additions and multiplication operators and emit calls to `arm_elementwise_add_s16` and `arm_elementwise_mul_s16` respectively during codegen.
Because `arm_elementwise_mul_s16` and `arm_elementwise_add_s16` do not handle non-zero shift parameters at present, for non-zero zero point values (which map directly to shift in the CMSIS-NN backend) partitioning fails and we fall back on the regular C codegen path.
This patch also adds `int16` tests, including testing for the non-zero zero point edge case described above.
=> [CMSIS-NN] Add int16 add and mul operator support

python/tvm/meta_schedule/__init__.py, python/tvm/meta_schedule/space_generator/__init__.py, python/tvm/relay/qnn/op/legalizations.py, python/tvm/relay/qnn/op/qnn.py, python/tvm/target/x86.py, python/tvm/topi/x86/batch_matmul.py, python/tvm/topi/x86/conv2d_avx_1x1.py, python/tvm/topi/x86/conv2d_avx_common.py, python/tvm/topi/x86/conv2d_int8.py, python/tvm/topi/x86/conv3d.py, python/tvm/topi/x86/dense.py, python/tvm/topi/x86/dense_alter_op.py, python/tvm/topi/x86/depthwise_conv2d.py, python/tvm/topi/x86/group_conv2d.py, python/tvm/topi/x86/sparse.py, python/tvm/topi/x86/tensor_intrin.py, python/tvm/utils/roofline/x86.py, src/meta_schedule/space_generator/space_generator.cc, src/relay/qnn/op/requantize.cc, src/relay/qnn/op/requantize_config.h
Metaschedule (space generation specifically) requires python functions registered in TOPI to correctly detect targets. If topi was not manually imported then we would get a crash. Fix this by moving the target feature detection to `python/tvm/target/x86.py`.
Test script:
```
import tvm
from tvm import meta_schedule as ms
@tvm.script.ir_module
class matmul:
@T.prim_func
def matmul_impl(
A: T.Buffer[(12, 196, 64), "float32"],
B: T.Buffer[(12, 64, 196), "float32"],
C: T.Buffer[(12, 196, 196), "float32"],
):
T.func_attr({"global_symbol": "main", "tir.noalias": True})
for b in range(12):
for i in range(196):
for j in range(196):
for k in range(64):
with T.block("main"):
vb, vi, vj, vk = T.axis.remap("SSSR", [b, i, j, k])
with T.init():
C[vb, vi, vj] = 0.0
C[vb, …
```
=> [Metaschedule,Fix] Move x86 feature detection to target directory for metaschedule

include/tvm/node/repr_printer.h, include/tvm/node/script_printer.h, include/tvm/script/printer/ir_docsifier.h, python/tvm/runtime/script_printer.py, python/tvm/script/ir_builder/tir/ir.py, src/node/repr_printer.cc, src/node/script_printer.cc, src/relay/ir/function.cc, src/script/printer/ir/ir.cc, src/script/printer/ir/utils.h, src/script/printer/ir_docsifier.cc, src/script/printer/tir/expr.cc, src/script/printer/tir/function.cc, src/script/printer/tir/utils.h, src/script/printer/utils.h, src/tir/ir/index_map.cc
This PR adds the functionality to roundtrip metadata during printing. Users may turn on the flag below to allow the printer to dump metadata to screen.
```python
ir_node.show(show_meta=True, ...)
```
=> [TVMScript] Support `show_meta`

include/tvm/tir/index_map.h, python/tvm/tir/schedule/trace.py, src/meta_schedule/database/database_utils.cc, src/relay/backend/te_compiler_cache.cc, src/tir/ir/index_map.cc, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/instruction.cc, src/tir/schedule/primitive/layout_transformation.cc, src/tir/schedule/trace.cc, src/tir/schedule/traced_schedule.cc, tests/python/unittest/test_tir_schedule_transform_layout.py
This changes `index_map` argument of `TransformLayout` from attr to input. It allows the index map to capture the random variables in the environment. This will allow tuning with different `index_map` applied.
cc @Hzfengsy
=> [TIR] Allow TransformLayout index_map to contain RVs

src/relay/backend/contrib/ethosn/codegen.cc, src/relay/backend/contrib/ethosn/codegen_ethosn.h, tests/python/contrib/test_ethosn/test_addition.py
After NPU driver 22.11 update, constants can be provided as inputs to addition operator.
This commit traverses constants to update operand entries for it and adds tests to verify these cases.
cc @lhutton1
=> [ETHOSN] Support for addition with constant input

python/tvm/relay/backend/contrib/ethosu/codegen.py, python/tvm/relay/backend/contrib/ethosu/te/binary_elementwise.py, python/tvm/relay/backend/contrib/ethosu/tir/binary_elementwise.py, tests/python/contrib/test_ethosu/infra.py, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_lut_optimizer.py
Add binary elementwise operator to OptimizeLUTs pass to merge LUT activation with elementwise operation. This PR is preparation for implementation of SoftMax operation.
=> [microNPU] Merge LUT activation with binary elementwise operation

python/tvm/topi/adreno/utils.py, tests/python/relay/opencl_texture/test_conv2d_nhwc_texture.py
In this PR `pack_filter` was extended to support HWIO layout. This layout can be used in winograd convolution.
=> [Adreno] Extend pack_filter for HWIO layout

tests/python/frontend/pytorch/test_forward.py
Since the fixes in matmul operator are merged, this PR should complete the coverage of test cases for torch.nn.functional.linear function marked as TODO in test_forward.py file:
TODO: Add the following cases when matmul(1D, _) is supported by TVM
- 1D input, 2D weight, 1D bias
- 1D input, 2D weight, no bias
- 1D input, 1D weight, scalar bias
- 1D input, 1D weight, no bias
=> [Torch] Added tests in test_forward_linear

python/tvm/script/ir_builder/tir/ir.py, python/tvm/tir/__init__.py, python/tvm/tir/op.py, tests/python/unittest/test_tir_op_types.py
Expose `bitwise_and`, `bitwise_or`, `bitwise_not`, `bitwise_xor` to python
=> [TIR] Expose bitwise ops to python

python/tvm/relax/expr.py, src/relax/ir/expr.cc, src/relax/ir/struct_info.cc, src/script/printer/relax/binding.cc, src/script/printer/relax/call.cc, src/script/printer/relax/expr.cc, src/script/printer/relax/function.cc, src/script/printer/relax/region.cc, src/script/printer/relax/struct_info.cc, src/script/printer/relax/tir.cc, src/script/printer/relax/type.cc, src/script/printer/relax/utils.h, tests/python/relax/test_tvmscript_printer_relax.py
This PR introduces Relax as a dialect supported by the TVMScript
Printer. Some caveats:
- Needs to rebase to mainline before merging.
- Some tests are skiped because some operators are not upstreamed to
the unity branch yet.
=> [Unity] Relax TVMScript Printer

.github/workflows/main.yml
This was added in #13612 but is failing intermittently on `main` and
PRs (#13950), so this PR disables it until we can come up with a
consistent fix
=> [ci] Disable Windows-Static-Runtime

src/runtime/contrib/tensorrt/tensorrt_ops.cc, tests/python/contrib/test_tensorrt.py
The original TensorRT BiasAdd converter does not use `axis` attribute from `nn.bias_add` so it only works with `NC, NCHW` and implicit mode (when batch dimension is removed). 
We recently found some NLP and Vision Transformer models are parsed with `axis=-1` which caused reshape error later during conversion.
```
[20:37:10] /home/ubuntu/apache_tvm/tvm/src/runtime/contrib/tensorrt/tensorrt_logger.h:51: Error: ERROR: 4: [graphShapeAnalyzer.cpp::analyzeShapes::1294] Error Code 4: Miscellaneous (IShuffleLayer (Unnamed Layer* 2) [Shuffle]: reshape changes volume. Reshaping [1,768,768,1] to [1,197,768].)
```
This CR adds support of `axis` attribute during conversion and related test case for `axis=-1`
=> [TensorRT] Fix BiasAdd with correct axis attribute

include/tvm/relax/backend.h, include/tvm/relax/transform.h, python/tvm/relax/__init__.py, python/tvm/relax/transform/__init__.py, python/tvm/relax/transform/_ffi_api.py, python/tvm/relax/transform/transform.py, src/relax/backend/vm/vm_shape_lower.cc, src/relax/ir/transform.cc, tests/python/relax/test_backend_transform_shape_lower.py
This PR introduces Relax `FunctionPass` and `DataflowBlockPass` API, and the `VMShapeLower` pass to lower the shape expression in Relax to TIR functions and VM shape heap builtin functions.
Co-Authored-by: Ziheng Jiang <ziheng@apache.org>
Co-Authored-by: Lesheng Jin <34279105+LeshengJin@users.noreply.github.com>
Co-Authored-by: Altan Haan <altanh@cs.washington.edu>
Co-Authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
Co-Authored-by: Steven S. <Lyubomirsky slyubomirsky@octoml.ai>
Co-Authored-by: Yong Wu …
=> [Unity] Relax VM shape lowering pass

docker/install/ubuntu_install_nnpack.sh
Recently NNPack SHA was modified to align with CPUInfo, which is a dependent package. Pthreadpool is another dependent library that needs SHA update to work in tandem with NNPack.
cc @Liam-Sturge @lhutton1 @neildhickey
=> [CI] Fix for NNPack error due to misalignment with pthreadpool library

src/relay/analysis/graph_partitioner.cc, src/relay/analysis/graph_partitioner.h, src/relay/transforms/fuse_ops.cc
The current `fuse_ops.cc` contains the following parts:
1. `IndexedForwardGraph` and `DominatorTree` which are used for graph partitioning
2. A Relay Expr visitor to create the `DominatorTree`
3. A Relay Expr mutator to fuse the ops
This PR separates the graph partitioning code from `fuse_ops.cc` and moves it to the analysis folder, for:
1. Better code organization and readability as the graph partitioning code is quite long and not directly related to the fusion mutator
2. Possible reuse opportunities for other fusion passes in Relax
NOTE: we won't bring relax fusion in `main` branch for now, but this pr is still reasonable for `main`.
cc @tqchen
=> [Relay][Pass] Separate out the graph partitioning code from fuse_ops.cc

src/meta_schedule/database/memory_database.cc, tests/python/unittest/test_meta_schedule_database.py
This typo was introduced a while ago, but was not uncovered until I was rebasing Relax when a unittest crashes.
=> [MetaSchedule] Fix a typo in MemoryDatabase

python/tvm/script/parser/core/entry.py, python/tvm/script/parser/ir/parser.py, src/script/printer/ir/misc.cc, src/script/printer/tir/expr.cc, src/script/printer/utils.h, tests/python/unittest/test_tvmscript_roundtrip.py
Multi-line strings might make less sense to be printed out by default, as they could be LLVM snippets, CUDA source code and anything hard to comprehend but easy to mess up with the TVMScript itself. Therefore, this PR is introduced to print them as metadata by default.
=> [TVMScript][Fix] Print Multi-line String as Metadata

src/script/printer/ir/ir.cc
This PR makes IRModule printing deterministic by fix the function ordering. The "main" function always comes last, while other functions should be ordered alphabetically.
=> [TVMScript] Deterministic function ordering

src/script/ir_builder/tir/ir.cc, src/script/ir_builder/tir/utils.h, src/tir/ir/stmt.cc, tests/python/unittest/test_tir_constructor.py
Previously, when writing a BufferStore statement in TVMScript, dtype
mismatch will not be detected but silently allowed.
For example, in the snippet below:
```python
buffer[indices] = RHS
```
even if the elements of `buffer` is floating point numbers, while RHS
is a handle, there is no mechanism to warn, fix, or error out.
This PR introduces auto casting mechanism in TVMScript to ensure that
the dtype of RHS matches LHS. When there is possible precision loss, it
will emit a warning so that the users could adjust accordingly.
=> [TVMScript] Enable Safe Autocasting in BufferStore

python/tvm/meta_schedule/runner/rpc_runner.py, tests/python/unittest/test_meta_schedule_runner.py
This PR fixes the timeout rule of MetaSchedule RPCRunner.
Prior to this PR, the RPCRunner sets a timeout threshold for jobs submitted to popen pool. As a result, the jobs are timed since the time that they are sent to the remote side.
Consider the case where there is only a single device for measurement. In this case, all jobs can only be executed serially and jobs must queue up. Therefore, the previous timeout configuration means the time spent on queueing will also be counted. This causes some jobs, in the worst cases, gets timeout without even started to execute, and has negative impacts on RPC MetaSchedule tuning, from the perspectives of both efficiency and result performance.
To address the problem, this PR
* removes the RPCRunner timeout requirement for PopenExecutor. Since now, …
=> [Fix][MetaSchedule] RPCRunner timeout when queueing up

include/tvm/runtime/ndarray.h, include/tvm/target/virtual_device.h, src/target/virtual_device.cc
This PR fixes Wenum-constexpr-conversion which is introduced in recent version of clang. Explciitly use integer instead of enum to store the device that may contain invalid options.
=> Fix out of bound enum conversion

include/tvm/script/ir_builder/tir/ir.h, python/tvm/script/ir_builder/tir/ir.py, python/tvm/script/parser/tir/entry.py, src/script/ir_builder/tir/ir.cc, src/script/printer/tir/ir.cc, tests/python/relay/aot/test_aot_create_executor_metadata.py, tests/python/relay/aot/test_pass_aot_lower_main.py, tests/python/unittest/test_tir_transform_plan_update_buffer_allocation_location.py, tests/python/unittest/test_tir_transform_storage_flatten.py, tests/python/unittest/test_tir_transform_storage_rewrite.py, tests/python/unittest/test_tir_usmp_transform_convert_pool_allocations_to_offsets.py, tests/python/unittest/test_tvmscript_parser_tir.py, tests/python/unittest/test_tvmscript_printer_tir.py, tests/python/unittest/test_tvmscript_roundtrip.py
While both represents a pointer type, `T.handle` was previously used to refer to tir variables whose `type_annotation` is `PrimType`, while `T.Ptr` instead specifically refers to `PointerType`. The divide is unnecessary if we extend `T.handle` slightly.
=> [TVMScript] Unify `T.handle` and `T.Ptr`

python/tvm/script/ir_builder/tir/__init__.py, python/tvm/script/ir_builder/tir/ir.py, python/tvm/script/parser/tir/entry.py, src/script/ir_builder/tir/ir.cc, tests/python/unittest/test_auto_scheduler_feature.py
Previously there are two equivalent ways of declaring a buffer in TVMScript:
```python
buffer = T.buffer_decl(...)
buffer = T.Buffer(...)
```
The two approaches are aliases to each other and are essentially the same in implementation. Therefore, this PR encourages to use `T.Buffer` as the recommended approach as it's a bit shorter. Meanwhile, `T.buffer_decl` will continue to be valid in TVMScript, but a deprecation warning will be emitted if its used.
=> [TVMScript] Encourage using T.Buffer directly

include/tvm/relay/attrs/transform.h, python/tvm/relay/frontend/onnx.py, python/tvm/relay/op/transform.py, python/tvm/topi/cuda/scatter.py, python/tvm/topi/scatter.py, tests/python/frontend/onnx/test_forward.py, tests/python/relay/test_op_level3.py, tests/python/topi/python/test_topi_scatter.py
Support all current opsets described in ONNX docs for ScatterND. Particularly extend supported `reduction` attribute from ["update"] to ["update", "add", "mul", "min", "max"]. Also CI tests are updated for the op.
=> [ONNX] Extend reduction types supported by ScatterND

ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy, ci/jenkins/templates/minimal_cross_isa_jenkinsfile.groovy.j2, tests/scripts/task_config_build_minimal_cross_isa.sh
This PR enables USE_MICRO in cross compilation build. This is part of ongoing efforts on enabling microTVM in default TVM build.
cc @alanmacd @driazati @gigiblender
=> [CI] Enable USE_MICRO in minimal cross ISA build

src/runtime/hexagon/hexagon_buffer.cc
Add invalidation after allocation and directional invalidation / flush around copy to improve overall HexagonBuffer cache management strategy which is necessary but not sufficient to support DMA with cache bypass enabled.
=> [Hexagon] Improve cache management strategy for HexagonBuffer

python/tvm/relax/utils.py, python/tvm/script/ir_builder/relax/ir.py, python/tvm/script/parser/relax/entry.py, src/script/printer/relax/expr.cc, src/script/printer/relax/struct_info.cc, tests/python/relax/test_backend_transform_shape_lower.py, tests/python/relax/test_transform.py, tests/python/relax/test_tvmscript_parser.py, tests/python/relax/test_tvmscript_printer_relax.py, tests/python/relax/test_vm_build.py, tests/python/relax/test_vm_codegen_only.py
As we've introduced `arg_sinfo` in CallNode, the implicit shape constructor is not widely used in TVMScript. This PR removes the implicit shape since it may cause confusion between shape and tuple.
=> [Unity][TVMScript] Use explicit `R.shape` in TVMScript

include/tvm/ir/diagnostic.h, src/ir/diagnostic.cc
This PR supports creating a diagnostic error from an arbitrary Object.
Given that we are bringing the diagnostic error for general uses in the long term, in which case
* not every Expr necessarily has a span,
* we have well-implemented elegant location-aware printer for an object itself,
* we may need to print some object other than Expr, or does even not have a span field,
we support diagnostic error with arbitrary object to denote the location.
Co-authored-by: Tianqi Chen <tianqi.tchen@gmail.com>
=> [Diagnostic] Support constructing Diagnostic Error through ObjectRef

include/tvm/topi/nn/pooling.h, tests/python/topi/python/test_topi_pooling.py
`topi.nn.poolNd` implementation does not support tiling on H, W or D dimensions. However, current implementation has a bug where no error is thrown if the layout is tiled along any of these dimensions. This PR fixes it.
=> [TOPI][Fix] Pool must return error if layout is tiled on H, W, D dimensions

include/tvm/relax/attrs/set.h, python/tvm/relax/op/__init__.py, python/tvm/relax/op/op_attrs.py, python/tvm/relax/op/set.py, python/tvm/script/ir_builder/relax/ir.py, src/relax/op/tensor/set.cc, src/relax/op/tensor/set.h, tests/python/relax/test_op_set.py, tests/python/relax/test_tvmscript_parser_op_set.py
This PR is about the high-level tensor computation operators in Relax.
This PR includes the set operators.
Co-authored-by: Prakalp Srivastava <prakalp@octoml.ai>
=> [Unity] Relax op: set

python/tvm/script/parser/tir/__init__.py
This PR makes T.prim_func typecheck as static method to reduce the set of warnings in tvmscript.
=> [UX] Make T.prim_func typecheck as staticmethod

include/tvm/relax/nested_msg.h, tests/cpp/nested_msg_test.cc
This PR introduce NestedMsg to robustly handle nested-tuple analysis.
Relax support nested tuple structures in the IR.
Nested tuple structure is important to support advanced groupings in cases such as gradient calculation and other scenarios.
The possible presence of nested tuple does mean that we need to to robustly handle analysis that contains nested tuple structures in a dataflow graph.
This PR introduces a NestedMsg<T> class that corresponds to a possibly nested message tuple for a given leaf message class T. We also introduces various helper functions to compose and decompose messages.
=> [Unity] NestedMsg Support utility

include/tvm/relax/analysis.h, include/tvm/tir/buffer.h, python/tvm/relax/transform/transform.py, src/relax/transform/annotate_tir_op_pattern.cc, src/relax/transform/fuse_ops.cc, src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_annotate_tir_op_pattern.py, tests/python/relax/test_transform_fuse_ops.py, tests/python/relax/test_transform_fuse_tir.py, tests/python/relax/test_tvmscript_parser.py
This PR introduces three passes for operator fusion:
1. AnnotateTIROpPattern: analyze the operator kind from PrimFunc.
2. FuseOps: fuse operators for Relax functions, which adds a new fused relax primitive function.
3. FuseTIR: fuse corresponding TIR PrimFuncs for the fused relax.
=> [Unity][Pass] Operator Fusion Passes

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
The issue was in the shapes mismatch when `layout=NHWC` was passed to importer. In this case kernel layout in conv2d_transpose operation was set to HWIO but in params HWOI layout was used. And we got the following error:
```
`Tensor[(2, 2, 64, 128), float32]` does not match `Tensor[(2, 2, 128, 64), float32]`
```
=> [Keras] Fix importing conv2d_transpose for NHWC layout

tests/micro/common/test_tvmc.py
These tests fail sometimes with beef3 due to small size of ring buffer. RPC client ends with
SessionTerminatedError. Skipping these tests until a permanent solution is found to https://github.com/apache/tvm/issues/14004. 
cc @Mousius @gromero @leandron
=> [CI][Flaky] Skip zephyr_qemu-x86 tests that are part of task_python_microtvm

python/tvm/_ffi/libinfo.py
When we are using TVM python package instead of building TVM from source, we are not able to find 3rdparty directory under python's site-package directory, so we cannot build module using 3rdparty in that situation. A fix is to let the user clone a TVM repo as TVM_HOME and find include path in that clone.
cc: @tqchen
=> [Build] Fix find_include_path when using TVM python package

src/meta_schedule/search_strategy/evolutionary_search.cc
This PR fixes internal object initialization in  EvolutionarySearchNode::State  class. Unfortunately there is no way to prepare test case.
=> [Metaschedule] EvolutionarySearchNode::State constructor typo fix

src/runtime/contrib/clml/clml_runtime.cc, src/runtime/opencl/opencl_common.h
OpenCL context accessing is changed while refactoring OpenCL backend.
=> [CLML] Changes corresponding to OpenCL workspace refactorization

tests/python/contrib/test_arm_compute_lib/test_conv2d.py
Parametrize the test instead of looping over a long list of configs in the test body.
=> [ACL][TESTING] Use pytest.mark.parametrize in ACL conv2d tests

include/tvm/relax/analysis.h, python/tvm/relax/transform/transform.py, src/relax/analysis/analysis.cc, src/relax/transform/lambda_lift.cc, src/relax/utils.cc, tests/python/relax/test_transform_lambda_lift.py
This pull request adds the LambdaLift pass into Relax. Local functions will be lifted into global.
=> [Unity][Pass] LambdaLift pass

include/tvm/relay/attrs/transform.h, python/tvm/relay/frontend/onnx.py, python/tvm/relay/op/_transform.py, python/tvm/relay/op/op_attrs.py, python/tvm/relay/op/strategy/cuda.py, python/tvm/relay/op/strategy/generic.py, python/tvm/relay/op/transform.py, python/tvm/topi/__init__.py, python/tvm/topi/cuda/__init__.py, python/tvm/topi/cuda/scatter_elements.py, python/tvm/topi/scatter_elements.py, src/relay/op/tensor/transform.cc, src/tir/ir/expr.cc, tests/python/frontend/onnx/test_forward.py
Support ScatterElements on ONNX front-end as described in ONNX docs. Just now Scatter op implementation is used where `reduction` attribute is not supported at all. Also CI tests are supported for the op.
P.S. In other PRs after that I plan: 1. remove scatter_add and reconnect all its using to ScatterElements(reduction="add") 2. remove scatter implementation and use ScatterElements(reduction="update") instead of it. It will remove the restriction related to input tensor rank size (just now rank <= 4)
=> [ONNX] Support ScatterElements with reduction

include/tvm/tir/builtin.h, python/tvm/script/ir_builder/tir/ir.py, python/tvm/tir/op.py, src/relax/backend/vm/codegen_vm_tir.cc, src/runtime/library_module.cc, src/target/llvm/codegen_cpu.cc, src/tir/op/builtin.cc, src/tir/op/runtime.cc, src/tir/transforms/lower_tvm_builtin.cc, tests/python/relax/test_vm_build.py, tests/python/relax/test_vm_codegen_only.py, tests/python/relax/test_vm_codegen_tir.py
This PR adds support of "compiled" mode to the VM. The compiled mode translate the relax function into TIR function and drive it through the TIR function.
It is different from the micro AOT codegen, which generate TIR code that targets the micro C runtime environment and useful for resource limited settings with smaller set of features. Both leverages the low-level TIR build that is also shared with TensorIR.
The current implementation targets full TVM (VM) runtime, that comes with PackedFunc, object, tuple, closure and all kinds of rich structure support. This also mean that we can leverage the full runtime support to handle things like allocation, dynamic shape, easy plugins and python interaction, which are not available in more limited runtime.
The user directly use the same API to …
=> [Unity][VM] Supporting "compiled" exec mode.

include/tvm/ir/function.h, include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/bind_params.cc, src/relax/transform/fold_constant.cc, tests/python/relax/test_transform_bind_params.py, tests/python/relax/test_transform_fold_constant.py
This PR introduces FoldConstant/BindParam passes.
Co-authored-by: Yong Wu [yongcale@gmail.com](mailto:yongcale@gmail.com)
Co-Authored-by: Hongyi Jin [3231950289@qq.com](mailto:3231950289@qq.com)
Co-Authored-by: Siyuan Feng [Hzfengsy@sjtu.edu.cn](mailto:Hzfengsy@sjtu.edu.cn)
=> [Unity][Pass] BindParams pass, FoldConstant pass

CMakeLists.txt, include/tvm/ir/transform.h, include/tvm/relax/transform.h, include/tvm/relax/tuning_api.h, include/tvm/relay/transform.h, include/tvm/tir/transform.h, python/tvm/ir/transform.py, python/tvm/meta_schedule/__init__.py, python/tvm/meta_schedule/relax_integration.py, python/tvm/meta_schedule/tir_integration.py, python/tvm/meta_schedule/tune_context.py, python/tvm/relax/transform/transform.py, python/tvm/relax/transform/tuning_api/__init__.py, python/tvm/relax/transform/tuning_api/_ffi_api.py, python/tvm/relax/transform/tuning_api/database.py, python/tvm/relax/transform/tuning_api/default_functions.py, python/tvm/relax/transform/tuning_api/primitives.py, python/tvm/tir/transform/function_pass.py, src/ir/transform.cc, src/relax/backend/task_extraction.cc, src/relax/ir/transform.cc, src/relax/transform/meta_schedule.cc, src/relax/transform/tuning_api/database.cc, src/relax/transform/tuning_api/primitives.cc, src/relay/ir/transform.cc, src/relay/transforms/type_infer.cc, src/tir/ir/transform.cc, tests/python/relax/test_transform_meta_schedule_tuning.py, tests/python/relax/test_tuning_api.py
This PR introduces TuningAPI that enables tuning within the pass infra and MetaSchedule pass.
=> [Unity][Pass][TuningAPI] Introduce TuningAPI and MetaSchedule pass

apps/relax_examples/e2e_auto_tir.py, apps/relax_examples/mlp.py, apps/relax_examples/nn_module.py, apps/relax_examples/resnet.py, python/tvm/relax/testing/__init__.py, python/tvm/relax/testing/relay_translator.py, python/tvm/relax/testing/transform.py, src/relay/backend/utils.cc, tests/python/relax/test_relay_translator.py
This PR implements a Relay to Relax translator, which allows us to import Relay workloads to Relax for benchmarking and development purposes (tests and examples are added).
Co-Authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
=> [Unity] Relay -> Relax translator 

python/tvm/runtime/object_generic.py, tests/python/all-platform-minimal-test/test_runtime_packed_func.py
Prior to this PR, though the `convert` function is capable of converting a single Python function/lambda to TVM func, it is not able to convert a container whose values inside are functions to TVM object.
This PR adds function conversion to `convert_to_object` and redirects `convert` to `convert_to_object`, so that now the conversion is always recursive, and therefore will work well on function container value type.
Co-authored-by: Chaofan Lin <1713833595@qq.com>
=> [FIX][RUNTIME] Convert container with function value type

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/normalize.cc, tests/python/relax/test_transform_normalize.py
This PR implements relax `Normalize` Pass, which allows users to transform Relax IR to normal form, i.e., the expressions are normalized (no nesting and hence the AST is in ANF), and all `checked_type_` and `shape_` of expressions are available. (tests are added).
Co-Authored-by: Yuchen Jin <yuchenj@cs.washington.edu>
Co-Authored-by: Ruihang Lai [ruihangl@cs.cmu.edu](mailto:ruihangl@cs.cmu.edu)
Co-Authored-by: Siyuan Feng [Hzfengsy@sjtu.edu.cn](mailto:Hzfengsy@sjtu.edu.cn)
Co-Authored-by: Tianqi Chen [tianqi.tchen@gmail.com](mailto:tianqi.tchen@gmail.com)
=> [Unity][Pass] Normalize Pass

python/tvm/relax/block_builder.py, python/tvm/topi/math.py, tests/python/relax/test_blockbuilder.py, tests/python/topi/python/test_topi_clip.py
Prior to this PR, the `call_te` of BlockBuilder is not capable of converting PrimValue arguments and directly rejects PrimValues instead. This PR fixes this behavior with PrimValue conversion support and one regression test.
Co-authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
=> [Unity][BlockBuilder] CallTE convert PrimValue args 

python/tvm/topi/math.py, tests/python/topi/python/test_topi_clip.py
Prior to this PR, TOPI clip op only accepts the min/max values with Python native float/int type, and rejects FloatImm and IntImm.
This PR enhances the clip op to allow it accept FloatImm and IntImm.
Co-authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
=> [FIX][TOPI] Clip with IntImm/FloatImm

src/tir/schedule/primitive/compute_inline.cc, tests/python/unittest/test_tir_schedule_compute_inline.py
* Add simplification after substitution to make the predicate simpler to arithmetic analysis.
* Update block flags. Since reverse-compute-inline may introduce predicates and the result block may not have affine binding.
cc @spectrometerHBH @junrushao @AndrewZhaoLuo
=> [TIR] Update block flags and simplify predicate in Reverse-Compute-Inline

tests/python/relax/test_op_manipulate.py
This PR specially checks the `relax.reshape` operator when the input is a `ShapeExpr`. 
cc @MasterJH5574
=> [Unity][Op] Add ShapeExpr Tests for Reshape Op

include/tvm/topi/transform.h
try use more proper index dtype than i64 to avoid integer arith issue in lowering.
=> [TOPI] Fix index dtype in topi strided_slice

include/tvm/relax/transform.h, python/tvm/relax/analysis/__init__.py, python/tvm/relax/analysis/estimate_memory_usage.py, python/tvm/relax/transform/transform.py, python/tvm/relax/vm.py, src/relax/transform/static_plan_block_memory.cc, tests/python/relax/test_analysis_estimate_memory_usage.py, tests/python/relax/test_transform_static_plan_block_memory.py
This PR introduces the static memory planning pass on binding block level, as well as an analysis function that estimate the memory usage after the memory planning pass. It supports the following features: nested-tuples,  reuse memory of the input of reshape ops, an estimator that returns total memory size needed to be allocated before and after memory planning, as well as the number of tensors / memory blocks to be allocated before and after memory planning.
The estimation is static -- it does not consider control flows (such as “if” and cross-function calls). It simply accumulates the size of every alloc_tensor and alloc_storage.
We will produce “`relax.memory.alloc_tensor/storage`” as the results produced by memory planning.
=> [Unity][Pass] Block-level static memory planning

python/tvm/script/parser/relax/parser.py, src/relax/analysis/well_formed.cc, src/relax/ir/block_builder.cc, tests/python/relax/test_analysis_well_formed.py, tests/python/relax/test_tvmscript_parser.py
Disallow inline PrimFunc in Relax IR, upstreaming from tlc-pack/relax.
cc: @tqchen @YuchenJin @junrushao
=> [Unity] Disallow inline prim_func in relax IR

python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_dynamo.py, tests/python/relax/test_transform.py, tests/python/relax/test_transform_annotate_tir_op_pattern.py, tests/python/relax/test_transform_attach_global_symbol.py, tests/python/relax/test_transform_fold_constant.py, tests/python/relax/test_transform_lambda_lift.py, tests/python/relax/test_transform_legalize_ops_binary.py, tests/python/relax/test_transform_legalize_ops_create_datatype.py, tests/python/relax/test_transform_legalize_ops_image.py, tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py, tests/python/relax/test_transform_legalize_ops_manipulate.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/relax/test_transform_legalize_ops_search_statistical.py, tests/python/relax/test_transform_legalize_ops_unary.py, tests/python/relax/test_transform_meta_schedule_tuning.py, tests/python/relax/test_transform_normalize.py, tests/python/relax/test_transform_static_plan_block_memory.py, tests/python/relax/test_tuning_api.py, tests/python/relax/test_tvmscript_ir_builder.py, tests/python/relax/test_tvmscript_parser.py, tests/python/relax/test_vm_build.py
Given that some latest changes of TVMScript syntax have been merged, some test files are now containing deprecated uses of TVMScript syntax. This PR updates the test files with latest TVMScript syntax so that running the tests will not trigger deprecation warnings.
=> [Unity] Update tests to adapt to latest TVMScript syntax

include/tvm/relax/analysis.h, include/tvm/relax/dataflow_matcher.h, include/tvm/relax/dataflow_pattern.h, include/tvm/relax/dataflow_pattern_functor.h, python/tvm/relax/analysis/analysis.py, python/tvm/relax/dpl/__init__.py, python/tvm/relax/dpl/_ffi.py, python/tvm/relax/dpl/context.py, python/tvm/relax/dpl/pattern.py, src/relax/analysis/udchain.cc, src/relax/analysis/var2value.cc, src/relax/ir/dataflow_matcher.cc, src/relax/ir/dataflow_matcher_impl.h, src/relax/ir/dataflow_pattern.cc, src/relax/ir/dataflow_pattern_functor.cc, tests/python/relax/test_analysis.py, tests/python/relax/test_dataflow_pattern.py
The dataflow pattern language for Relax (originally from https://github.com/tlc-pack/relax/pull/163).
The implementation splits patterns into two parts:
- Match an Expression: match an expression syntactically (MatchExprPattern, i.e., DFPatternMatcher);
- Match a Graph: match a graph (cross multiple VarBinding) topologically (MatchGraphPattern); 
Credit also given to relay pattern lang authors and reviewers of https://github.com/tlc-pack/relax/pull/163.
cc: @YuchenJin
=> [Unity] Relax dataflow pattern language (matching)

include/tvm/relax/analysis.h, include/tvm/relax/binding_rewrite.h, include/tvm/relax/utils.h, python/tvm/relax/analysis/analysis.py, python/tvm/relax/binding_rewrite.py, src/relax/ir/binding_rewrite.cc, tests/python/relax/test_analysis.py, tests/python/relax/test_binding_rewrite.py
- Implements a few APIs to quickly perform statement-level mutation: `add`/`remove_unused`/`remove_all_unused`/`replace_all_uses`.
- Implemented `remove_all_unused` to remove dead statements inside `DataflowBlock`
Credit also given reviewers in original PR (https://github.com/tlc-pack/relax/pull/210).
Listing owner of follow-up commits over the inital files as co-authors (My apology for forgeting doing so in https://github.com/apache/tvm/pull/14041).
Co-authored-by: Chaosfan <siriusneo@sjtu.edu.cn>
Co-authored-by: Junru Shao <junrushao1994@gmail.com>
Co-authored-by: Ruihang Lai <ruihangl@cs.cmu.edu>
Co-authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
Co-Authored-by: Yuchen Jin <yuchenj@cs.washington.edu>
=> [Unity] Statement rewriter for DataflowBlock

docs/install/from_source.rst, python/gen_requirements.py, python/tvm/auto_scheduler/cost_model/xgb_model.py, python/tvm/autotvm/tuner/xgboost_cost_model.py
This PR enables **tvm** to work with newer xgboost >= 1.7.x
- xgboost trivial changes here [dmlc/xgboost#7280](https://github.com/dmlc/xgboost/pull/7280)
-  the issue tracking this is here: [xgboost version conflict #12009](https://github.com/apache/tvm/issues/12009)
- this work is based on stalled PR here: [Upgrade autoscheduler xgboost callback #12144](https://github.com/apache/tvm/pull/12144)
Tested with booth AutoTVM and AutoSchedule.
Cc @Sunny-Island , @zxybazh @junrushao 
also Cc @driazati for CI xgboost>=1.7.x changes
Thanks,
~Cristian.
=> [AutoScheduler][AutoTVM] Enable xgboost >= 1.7.x new changes

src/relax/transform/fuse_ops.cc, src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_fuse_ops.py, tests/python/relax/test_transform_fuse_tir.py
This PR fixes two bugs of FuseOps and FuseTIR:
* it fixes FuseOps who only rewrites the "main" function of the IRModule. After the fix, FuseOps now goes through each non-primitive Relax function. Test cases for both FuseOps and FuseTIR sides are added so ensure that both of the two passes work for cases of multiple Relax functions.
* it fixes FuseOps and FuseTIR who did not take "call_dps_packed" style "call_tir" into account. The previous behavior will directly downcast the first argument of "call_tir" to GlobalVar, which is not right when the "call_tir" is in "call_dps_packed" stype and the first argument is a PackedFunc. With this fix, FuseOps and FuseTIR will skip such "call_tir"s. Tests for both CallTIR and CallOps are added accordingly.
=> [Unity][Pass] FuseOps FuseTIR fixes

python/tvm/relax/expr.py, tests/python/relax/test_op_misc.py, tests/python/relax/test_tvmscript_parser.py
This PR overloads `__neg__` given that `relax.negative` is now supported. Besides, it adds `test_op_misc.py` (original `test_op.py` https://github.com/mlc-ai/relax/blob/relax/tests/python/relax/test_op.py) back and brings tests for calling overloaded operators.
=> [Unity][TVMScript] Overload `__neg__` for relax expr

python/tvm/contrib/emcc.py, src/runtime/dso_library.cc, src/runtime/library_module.cc, web/.gitignore, web/Makefile, web/emcc/tvmjs_support.cc, web/src/webgpu.ts
This PR provide fixes to re-enable web build for latest emcc. WASM runtime now works. WebGPU still need some catch up to the API spec. Tested locally.
=> [WEB] Update web runtime to support latest emcc

include/tvm/tir/op.h, include/tvm/topi/elemwise.h, src/target/intrin_rule.cc, src/target/intrin_rule.h, src/target/source/codegen_c.h, src/target/source/codegen_metal.cc, src/target/source/codegen_source_base.cc, src/target/source/codegen_webgpu.cc, src/target/source/codegen_webgpu.h, src/target/source/intrin_rule_metal.cc, src/target/source/intrin_rule_webgpu.cc, src/target/spirv/build_vulkan.cc, src/target/spirv/intrin_rule_spirv.cc, src/target/spirv/ir_builder.h, src/tir/op/op.cc, web/emcc/webgpu_runtime.cc, web/src/runtime.ts, web/src/webgpu.ts, web/tests/python/webgpu_rpc_test.py
This PR provide an implementation of WebGPU codegen. Previously we relied on SPIRV codegen for WebGPU, which is deprecated in favor of the WGSL shading language. Pass limited testing on elementwise via chrome.
Likely we will do future iterations.
=> [WEB] WebGPU Codegen

include/tvm/runtime/relax_vm/vm.h, python/tvm/relax/vm.py, src/runtime/relax_vm/executable.cc, src/runtime/relax_vm/vm.cc, tests/python/relax/test_vm_profiler.py
Adds per-op profiling support to Relax VM, in a way similar to how Relay VM is instrumented via the common profiling infra in the runtime. Profiling over RPC is supported.
Example output:
```
Name                          Duration (us)  Percent    Device  Count                                 Argument Shapes  
conv2d1                          705,779.00    51.22  hexagon0      1  float32[1, 64, 56, 56], float32[1, 64, 54, 54]  
conv2d                           669,589.00    48.60  hexagon0      1  float32[1, 64, 56, 56], float32[1, 64, 56, 56]  
relu                                 683.00     0.05  hexagon0      1  float32[1, 64, 56, 56], float32[1, 64, 56, 56]  
relu1                                679.00     0.05  hexagon0      1  float32[1, 64, 54, 54], float32[1, 64, 54, 54] …
```
=> [Unity][VM] Add per-op profiling support 

python/tvm/relax/transform/transform.py, src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops_by_pattern.py
This adds a new pass, FuseOpsByPattern, which applies pattern matching to each function in the given module, and groups matched expressions into a new function. The end result is similar to FuseOps, but fusion is driven completely by
the provided patterns. The implementation also reuses OperatorFusor used by FuseOps to create grouped functions from partitioned groups, further illustrating the similarity between the two passes.
The new pass will serve the same role the MergeComposite pass plays in Relay BYOC - grouped functions are annotated with the "composite" attribute to denote what operations a given function consists of, and offloaded to external backends. But it can be also useful in non-BYOC settings, for example to support advanced fusion that the op-kind based one doesn't handle …
=> [Unity][BYOC] Add pattern-based partitioning pass

include/tvm/runtime/packed_func.h
To support register function return TVMByteArray.
=> [Runtime] Add missing Type2Str for TVMByteArray

gallery/how_to/work_with_relay/using_pipeline_executor.py, python/tvm/contrib/cutlass/_ffi_api.py, python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/conv2d_operation.py, python/tvm/contrib/cutlass/conv2d_profiler.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_gemm.py, python/tvm/contrib/cutlass/gen_tensor_op.py, src/relay/backend/contrib/codegen_c/codegen_c.h, src/relay/backend/contrib/cutlass/codegen.cc, tests/python/contrib/test_cutlass.py
The CUTLASS backend in Relay BYOC has been heavily refactored this month in the `tlcpack/relax` repo (as part of Relax BYOC effort). This PR brings the same change to `apache/main` and also adds SIMT fp32 support. All tests in `test_cutlass.py` pass.
Original PRs
Codegen clean up: https://github.com/tlc-pack/relax/pull/442, https://github.com/tlc-pack/relax/pull/451
SIMT fp32 support: https://github.com/tlc-pack/relax/pull/448
@vinx13
=> [BYOC] Update CUTLASS backend (SIMT support and codegen clean up)

gallery/tutorial/uma.py, python/tvm/relay/backend/contrib/uma/backend.py, src/relay/backend/contrib/uma/targets.cc, tests/python/contrib/test_uma/test_target.py
This PR address fixes for UMA target registration.
* Fix the doc issue #13304 
* Continues stalled PR #12731 
Changes:
* Incorporates all proposed fixes from mentioned [PR #12731](https://github.com/apache/tvm/pull/12731)
* Address test case concerns and discussions from [PR #12731](https://github.com/apache/tvm/pull/12731)
* **NEW:** Already exiting target cannot be created, explicit error on this.
* **NEW:** Attributes having special/reserved scope cannot be created explicitly.
It also address proper test cases for all the above.
=> [BugFix][UMA] Protect target registration (#13624)

src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops.py
This PR fixes a mistake of #14044. In #14044, in VisitLeaf of graph construction of FuseOps, we first check if the input node is Leaf and then check if it is Tuple. This is not right: as Tuple is not categorized as one leaf node, when the input node is a Tuple, the function will return since the input is not a LeafNode. And the check for Tuple will thereby never holds.
It is quite interesting that our existing unit tests fail to filter this mistake out. I add a regression test for this case, which can ensure that the tuple is always visited.
=> [Unity][Fix][Pass] Fix FuseOps for lack graph edges

include/tvm/relax/utils.h, python/tvm/relax/transform/transform.py, python/tvm/relax/utils.py, src/relax/transform/merge_composite_functions.cc, src/relax/utils.cc, tests/python/relax/test_transform_merge_composite_functions.py, tests/python/relax/test_utils.py
This PR adds a pass that merges neighboring calls to composite functions offloaded to the same external backend into one function. This is important for backends that want to receive as large subgraph as possible, for example TensorRT. It plays the same role as the MergeCompilerRegion pass in Relay BYOC does, and the algorithm follows the same idea described in https://discuss.tvm.apache.org/t/relay-improved-graph-partitioning-algorithm/5830. 
Original PR
https://github.com/tlc-pack/relax/pull/372
Substantial improvement by @yelite 
https://github.com/tlc-pack/relax/pull/411
Related fix PR by @yelite 
https://github.com/tlc-pack/relax/pull/406
=> [Unity][BYOC] Add pass to merge composite functions to offload large subgraphs

include/tvm/topi/nn.h, tests/python/topi/python/test_topi_loss.py
This PR supports the cases when input does not contain batches for `topi.nll_loss`.
When there is no batches, the shape of the prediction parameter is `(C,)`,  the shape of the target parameter is `()`, the shape of the target parameter is `(C,)`, and the shape of the output is always `()` no matter which reduction method it uses.
cc @junrushao @Hzfengsy
=> [TOPI] Support non-batch cases for topi.nll_loss

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/lift_transform_params.cc, tests/python/relax/test_transform_lift_transform_params.py
This PR added a pass `LiftTransformParams`. It allows to compile the end-to-end model without weights provided. The idea is annotate the input parameters that are weights, and identify and lift the transformations to weights, and compile it to a separate function `transform_params` that can be executed in runtime. Users can run `transform_params` with weights to get the weights for the optimized model as a prep step before the deployment. In this way, we perform the same optimizations and defer the weight transformations to the user side, while the overhead of the deferred weight transformation can be ignored as it only need to be run once.
This pass is integrated with the default `vm.build`. It is optional and only necessary when the parameters are kept as inputs when importing the model …
=> [Unity][Transform] Add LiftTransformParams pass

apps/android_camera/README.md, apps/android_camera/app/build.gradle, apps/android_camera/app/src/main/AndroidManifest.xml, apps/android_camera/build.gradle, apps/android_deploy/README.md, apps/android_deploy/app/build.gradle, apps/android_deploy/app/download-models.gradle, apps/android_deploy/app/src/main/AndroidManifest.xml, apps/android_deploy/build.gradle, apps/android_rpc/README.md, apps/android_rpc/app/build.gradle, apps/android_rpc/app/src/main/AndroidManifest.xml, apps/android_rpc/build.gradle
Fix CI.
The Gradle was updated to a new major version of Gradle, 8.0
https://docs.gradle.org/8.0/release-notes.html
=> [APP] Update android_rpc build tools version

src/target/tag.cc
As we are recently conducting experiments on GPU of Apple Silicon, we find it helpful to introduce the target tag for Apple Silicon GPUs, as specialized Metal targets.
At this moment, we find the size of shared memory per thread block, the maximum number of threads per thread block and the warp size useful, so each specialized chip is configured by these three parameters.
The feature numbers come from Apple's official document: https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf
=> [Target] Add target tags for Apple Silicon GPU

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/canonicalize_bindings.cc, tests/python/relax/test_transform_canonicalize_bindings.py
It may be useful for some passes to collapse chains of definitions, particularly after other compiler transformations that may reduce or simplify some expressions.
This pass will take chains of definitions and replace references to later definitions to the original one. It works by checking `LookupBinding` for each var use-site and replacing the var with its definition if the definition was another var. Additionally, `MatchCast` bindings where the LHS and the RHS are guaranteed to match at compile time are canonicalized into ordinary `VarBinding`s.
Example:
```python
y = x
z = y
w = z
o = w
p = o
```
Will be replaced with
```python
y = x
z = x
w = x
o = x
p = x
```
Original PR: https://github.com/tlc-pack/relax/pull/233
Co-authored-by: Steven S. Lyubomirsky <slyubomirsky@gmail.com>
=> [Unity][Pass] Canonicalize Bindings

python/tvm/topi/arm_cpu/conv2d_spatial_pack.py, tests/micro/arduino/test_arduino_workflow.py
No changes to the compute, various bugfixes and improvements to the corresponding NHWC schedule:
* There is currently a block that is not run as a part of tuning trials, but gets run during compilation with tuning logs. Since a lot of unrolling and vectorization happens there, for some conv2d operators the extra vectorizing and unrolling results in about 18x size increase in asm and can take around 10 minutes per operator to compile. That essentially makes whole networks uncompilable, so remove that block.
* There is no fallback config or NHWC logs in the TopHub. So add a fallback config. This significantly reduces the no tuning compile time, e.g. by about 10x for mobilenet.
* The order of axis we passed to reorder_config was different to the order that was used to define the reorder. By …
=> [TOPI] Bugfix arm_cpu schedule_conv2d_spatial_pack_nhwc schedule

tests/python/integration/test_auto_tensorize.py
The test previously had the incorrect pytest attribute skip_if, this replaces with the correct one
=> [CI] Fix test skipping pytest attribute

tests/python/relax/test_expr_args_converter.py
This is a missing test file when we added the `expr_args_converter`. This PR adds it back.
=> [Unity] Add testcases for `expr_args_converter`

src/target/source/codegen_cuda.cc
This PR added error message when wmma fragment info is missing. This happens when the wmma fragment memory scope is used but `tensorize` is not called. Previously, it shows error message like `tvm._ffi.base.TVMError: _Map_base: :at` that doesn't provide enough information.
cc @masahi
=> [Codegen][CUDA] Add error message for missing fragment info

python/tvm/relax/op/nn/nn.py, python/tvm/relax/transform/legalize_ops/nn.py, src/relax/op/nn/nn.cc, src/relax/op/nn/nn.h, tests/python/relax/test_op_nn.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/relax/test_tvmscript_parser_op_nn.py
This PR introduces two high-level operators `log_softmax` and `cross_entropy_with_logits`, which are important when we are calculating `CrossEntropyLoss` (in torch).
Co-authored-by: Yixin Dong [ubospica@gmail.com](mailto:ubospica@gmail.com)
=> [Unity][Op] `log_softmax` and `cross_entropy_with_logits`

src/meta_schedule/mutator/mutate_tile_size.cc, tests/python/unittest/test_meta_schedule_mutator_mutate_tile_size.py
When handling SampleCategorical instructions, our MutateTileSize mutator mutates it by asserting that "there should be at least one candidate other than the current decision". However, this argument fails when a SampleCategorical instruction has only one candidate, since there is no other candidate besides the unique one. On such cases, the mutator will lead to exception.
For such cases, the expected behavior is that the mutator ignores such SampleCategorical instructions. This PR updates the mutator in this way and provides a regression test.
=> [MetaSchedule] MutateTileSize skip single-candidate SampleCategorical

docker/install/ubuntu_download_arm_compute_lib_binaries.sh
This updates Compute Library from v22.08 to v22.11.
Changelog for this version can be found at:
https://arm-software.github.io/ComputeLibrary/v22.11/
cc @lhutton1 @neildhickey @ashutosh-arm
=> [CI] Update Compute Library to v22.11

src/relax/analysis/udchain.cc, src/relax/transform/fold_constant.cc, tests/python/relax/test_transform_fold_constant.py
The current FoldConstant pass does not support removing unused bindings in the post-folding function. Therefore, for large real-world models, the built executable will be overlarge because of the redundant unused constants.
This PR removes the redundant unused constant bindings in FoldConstant by using the analysis function "RemoveAllUnused".
Note that "RemoveAllUnused" only works at dataflow block level. Therefore FoldConstant will not remove unused bindings outside of dataflow block as well.
=> [Unity][Fix][Pass] FoldConstant with DCE in dataflow block

apps/relax_examples/e2e_auto_tir.py, apps/relax_examples/mlp.py, apps/relax_examples/nn_module.py, apps/relax_examples/resnet.py, python/tvm/contrib/cutlass/build.py, python/tvm/meta_schedule/relax_integration.py, python/tvm/relax/__init__.py, python/tvm/relax/exec_builder.py, python/tvm/relax/frontend/torch/dynamo.py, python/tvm/relax/transform/transform.py, python/tvm/relax/transform/tuning_api/default_functions.py, python/tvm/relax/vm_build.py, python/tvm/runtime/relax_vm.py, tests/python/relax/test_codegen_cutlass.py, tests/python/relax/test_codegen_dnnl.py, tests/python/relax/test_codegen_tensorrt.py, tests/python/relax/test_pipeline.py, tests/python/relax/test_relay_translator.py, tests/python/relax/test_transform_bind_params.py, tests/python/relax/test_transform_codegen_pass.py, tests/python/relax/test_vm_build.py, tests/python/relax/test_vm_codegen_only.py, tests/python/relax/test_vm_codegen_tir.py, tests/python/relax/test_vm_profiler.py, tests/python/relay/test_vm.py
This PR refactors relax build so it get exposed at the opt-level.
We also introduces an explicit jit functionality to handle
live loading of compiled artifacts from cutlass.
We also move relax vm to runtime so it can be clearly isolated
from the rest of the compiler stack.
=> [Unity] Refactor Relax Build JIT UX

python/tvm/relay/frontend/pytorch.py, python/tvm/topi/scatter_elements.py, tests/python/frontend/pytorch/test_forward.py
scatter_reduce operation was implemented on pytorch front-end. Test was added to CI for it.
**Note**: `mean` reduction is not supported, but will be when other PRs related to scatter-like operations will be merged.
=> [TORCH] scatter_reduce implementation

src/relax/backend/vm/vm_shape_lower.cc, tests/python/relax/test_backend_transform_shape_lower.py
This PR follows up #14020 to utilize the `is_host_func` attribute and make sure the shape function is computed on target host. Modified previous symbolic shape unit test to adopt and cover the current change.
CC: @junrushao @YuchenJin @tqchen
=> [Unity][Relax] Set Shape Function to Be Host Function

include/tvm/runtime/crt/aot_executor.h, python/tvm/micro/__init__.py, python/tvm/micro/session.py, python/tvm/relay/build_module.py, python/tvm/runtime/executor/aot_executor.py, src/runtime/aot_executor/aot_executor.cc, src/runtime/aot_executor/aot_executor.h, src/runtime/crt/aot_executor/aot_executor.c, src/runtime/crt/aot_executor_module/aot_executor_module.c, tests/python/relay/aot/test_cpp_aot.py, tests/python/unittest/test_crt.py
This PR adds get_input_name function to AoT. This functionality would help with features like TVMC where we need to set the input without asking the user to specify the input name.
This PR also adds `create_local_aot_executor` for micro and refactors that across the codebase for all CRT use cases.
In addition this PR fixes a bug in python/tvm/relay/build_module.py where `relay.build` for AotExecutor was using `graph` executor instead of `aot`.
=> [AoT]Add get_input_name function to AoT Module

include/tvm/relax/transform.h
Fix typo. Thanks @SiriusNEO for reporting this.
=> [Unity] Fix typo in the comment

apps/microtvm/zephyr/template_project/src/mlperftiny/submitter_implemented.cc, gallery/how_to/work_with_microtvm/micro_aot.py, tests/micro/common/test_mlperftiny.py, tests/micro/zephyr/test_zephyr_aot_exec_standalone.py, tests/scripts/request_hook/request_hook.py
This PR adds test for MLPerfTiny models for both `mlperftiny` project type and `host_driven`. In host drive, a single input data is used for testing but in `mlperftiny` case we only build the project.
=> [microTVM]Add test for MLPerfTiny models 

include/tvm/relax/utils.h, src/relax/backend/vm/vm_builtin_lower.cc, src/relax/utils.cc, tests/python/relax/test_relax_operators.py
This PR lowers `shape_of` op to a Relax VM builtin, and changes a utility function to take StructInfo as input.
Co-authored-by: Steven S. Lyubomirsky <slyubomirsky@gmail.com>
=> [Unity] Lower `shape_of` to a builtin

include/tvm/relax/analysis.h, include/tvm/script/ir_builder/relax/ir.h, python/tvm/script/ir_builder/relax/ir.py, python/tvm/script/parser/relax/parser.py, src/relax/analysis/analysis.cc, src/relax/analysis/well_formed.cc, src/relax/transform/lambda_lift.cc, src/script/ir_builder/relax/ir.cc, tests/python/relax/test_analysis_well_formed.py, tests/python/relax/test_transform_lambda_lift.py, tests/python/relax/test_utils.py
this pull request adds:
- TVMScript local recursive function support
- Update lambda lifting pass. Removed CalledGlobalVars, it was not used anymore.
- Update well-form pass. Previously the [well-form pass](https://github.com/tlc-pack/relax/blob/relax/src/relax/analysis/well_formed.cc#L180-L182) doesn't allow un-defined vars, which doesn't work for var used for recursive call
cc: @YuchenJin @tqchen @Hzfengsy
=> [Unity] Relax Recursive function

include/tvm/relax/analysis.h, python/tvm/relax/analysis/analysis.py, src/relax/analysis/layout_transformation.cc, src/support/array.h, tests/python/relax/test_analysis_suggest_layout_transforms.py
This change adds a PrimFunc level analysis to propose layout transformations to block and buffers in the PrimFunc based on the layout transformations to PrimFunc outputs. It analyzes buffer access to figure this out. It tries to preserve sequential access to buffers when it does this.
For example given the following PrimFunc and write buffer "relu" transformation `lambda n, c, h, w: (n, h, w, c // 4, c % 4)`, it will suggest to make the following transformations.
* Block transformation on "compute": `lambda n, c, h, w: (n, h, w, c // 4, c % 4)`
* Buffer transformation on  "relu": `lambda n, c, h, w: (n, h, w, c // 4, c % 4)`
* Buffer transformation on "arg":  `lambda n, c, h, w: (n, h, w, c // 4, c % 4)`
```python
@T.prim_func
def elemwise_relu(
arg: T.Buffer((32, 64, 224, 224), …
```
=> [Unity][Layout] Add layout transformation analysis for PrimFunc

apps/microtvm/zephyr/template_project/CMakeLists.txt.template, gallery/how_to/work_with_microtvm/micro_mlperftiny.py, tests/micro/zephyr/test_zephyr.py, tests/micro/zephyr/test_zephyr_aot_exec_standalone.py, tests/micro/zephyr/utils.py
In standalone mode we can use the generated tvmgen_default.h in model/host/include instead of regenerating it using generate_c_interface_header. 
This PR also moves test_qemu_make_fail to test_zephyr since this test is not a standalone mode test.
=> [microTVM][Zephyr] Remove unnecessary use of generate_c_interface_header

tests/python/integration/test_auto_tensorize.py
The test modified by this PR relies on onnx conversion to run successfully, skipping if onnx isn't available, which is the case for ci_cpu docker image
=> [CI] Add onnx dependency to test_auto_tensorize.py::test_vnni_bert_int8

src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h
`DeclBufferNode` was added recently in #12300, but support to traverse it in codegen_llvm was not added. Since this stmt just declares a new buffer for a body of TIR, we just need to traverse the body to properly generate code for LLVM.
=> [LLVM] Add support for DeclBufferNode

python/tvm/relay/frontend/paddlepaddle.py, tests/python/frontend/paddlepaddle/test_forward.py
Add where_index op converter for paddleapaddle frontend.
The graphexcutor cannot build the argwhere op when i try to add unitest for this converter, so i add vm for paddle frontend's unitest. 
Adding use_vm flag to verify_model func to support using vm for build.
@jiangjiajun
@heliqi
cc @junrushao
=> [Frontend][Paddle] Add where_index op and add vm for paddle frontend's unitest

CMakeLists.txt, python/tvm/relax/backend/__init__.py, python/tvm/relax/backend/_ffi_api.py, python/tvm/relax/backend/contrib/__init__.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/backend/pattern_registry.py, python/tvm/relax/backend/patterns.py, python/tvm/relax/dpl/pattern.py, src/relax/backend/pattern_registry.cc, src/relax/backend/pattern_registry.h, tests/python/relax/test_codegen_cutlass.py
This PR adds pattern registry to manage patterns used by different BYOC backends. It provides API for registering and retrieving patterns. 
The main motivation of this PR is to make it easier to do analysis in backend codegen, by making the pattern behind the partitioned function accessible to codegen.
=> [Unity][BYOC]Add relax backend pattern registry

python/tvm/relax/block_builder.py, python/tvm/relax/transform/transform.py, src/relax/transform/merge_composite_functions.cc, src/script/printer/relax/tir.cc, tests/python/relax/test_backend_transform_shape_lower.py, tests/python/relax/test_transform_canonicalize_bindings.py, tests/python/relax/test_transform_legalize_ops_manipulate.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/relax/test_transform_remove_unused_funcs.py, tests/python/relax/test_tvmscript_printer_relax.py, tests/python/relax/test_vm_codegen_only.py, tests/python/unittest/test_arith_detect_cse.py
Now IRPrinter prints `T.Var("n", "int64")` for tir Vars in Relax functions. But in the new TVMScript syntax, it should be `T.int64()`.
This PR fixes this bug and updates tests in favor of the new TVMScript syntax. To be specific, this PR modifies these:
- `T.var("...")` -> `T.dtype()`
- `T.Var(name, dtype)` -> `T.dtype()`
- `T.Buffer[...]` -> `T.Buffer(...)`
=> [Unity] Update tests again to adapt to latest TVMScript syntax

python/tvm/relay/function.py, src/runtime/c_runtime_api.cc
This PR do 2 things:
1. Fix a potential memory bug, we meet this bug because our device type is greater than 32, so the cross-border access happened in device api manager code.
2. Remove a useless decorator, it seems there isn't any code use it, and it will cause the Python function become as a packed function, so the caller can't use the key word argument when call it.
=> [Runtime] Fix Potential DeviceAPIManager Memory Bug

ci/jenkins/docker-images.ini
* This brings the update to Compute Library from v22.08 to v22.11
Validation was done in #14104.
cc @driazati @Mousius @areusch @neildhickey
=> [Docker] Update ci-cpu and ci-arm to tag 20230223-070143-a3b51f11b

docs/script_convert.py, gallery/how_to/work_with_microtvm/micro_tvmc.sh, tests/python/ci/test_script_converter.py, tests/scripts/setup-pytest-env.sh
This PR applies appropriate changes to make sure the CI fails if `micro_tvmc.sh` tutorial fails. This issue was captured in https://github.com/apache/tvm/issues/14074.
This PR also makes changes to avoid this breakage in bash script tutorials in future. In addition, this PR fixes the bug in running TVMC tutorial which happened due to renaming `zephyr_board` to `board`.
=> [microTVM] Fix tvmc tutorial

python/tvm/relax/block_builder.py, src/relax/ir/block_builder.cc, tests/python/relax/test_blockbuilder.py
This PR adds `name_hint` argument for `emit` and `emit_output` API of Relax blockbuilder. The argument exists in the C++ side but not exposed to Python side (So user who use the Python bb.emit will let `name_hint` be `""` by default).
Co-authored-by: Yixin Dong <ubospica@gmail.com>
=> [Unity][BlockBuilder] Add `name_hint` argument for `emit` and `emit_output`

src/meta_schedule/schedule_rule/multi_level_tiling.cc, src/meta_schedule/schedule_rule/multi_level_tiling.h, tests/python/unittest/test_meta_schedule_schedule_rule_mlt.py, tests/python/unittest/test_meta_schedule_space_cuda.py, tests/python/unittest/test_meta_schedule_space_cuda_async.py, tests/python/unittest/test_meta_schedule_space_cuda_winograd.py
This PR introduces async pipeline in the current TVM's MultiLevelTiling Rules. This PR is based on apache/tvm#13966, which is already merged. This is because some conv2d workload will use `tir.if_then_else` to pad the input to the correct size, and this PR uses async copy in such copy statement.
1. Add a subrule in `src/meta_schedule/schedule_rule/multi_level_tiling.h/.cc` that annotate async copy for mlt in supported arch (>= sm80).
In CUDA Core, this PR has a perf boost of around 1T GFLOP/s in most Conv2d test cases and 1T ~ 2T in most GEMM test cases.
All generated codes, scripts, and traces are available at https://github.com/Rainy-Memory/tvm-async-rule-benchmark.
Currently tested on commit `afbfb7aa7e43732cb716f8e443df696110be6afc` in conv2d NHWC workload, with a RTX 3080 GPU. …
=> [MetaSchedule] Introduce Async Pipeline in MultiLevelTiling

include/tvm/tir/op_attr_types.h, src/script/printer/tir/expr.cc, src/tir/ir/stmt.cc, src/tir/op/builtin.cc
This PR adds an op attribute `TScriptDtypePrintLocation`, and modifies the dtype printing logic of the builtin op to check this attribute. So that user defined operators can use it to specify how there dtype argument are printed by appending attributes instead of appending members to `dtype_first_arg`/`dtype_last_arg`.
@junrushao @wrongtest-intellif
=> [TVMScript] Use op attribute to control whether to print dtype in TVMScript

src/script/printer/ir_docsifier.cc, tests/python/unittest/test_tvmscript_printer_metadata.py
Currently, if the same metadata object (e.g. a multi-line `tir.StringImm`) is referenced for more than one times in an IRModule, each reference will have different indices of the metadata array. For example, this code
```
str_imm = T.StringImm("aaa\nbbb\n")
@I.ir_module
class Module:
@T.prim_func
def foo() -> None:
A = str_imm
B = str_imm
@T.prim_func
def foo1() -> None:
A = str_imm
Module.show()
```
where `str_imm` is referenced three times, will generate such output:
```
@I.ir_module
class Module:
@T.prim_func
def foo():
A: T.handle = metadata["tir.StringImm"][0]
B: T.handle = metadata["tir.StringImm"][1]
T.evaluate(0)
@T.prim_func
def foo1():
A: T.handle = metadata["tir.StringImm"][2]
T.evaluate(0)
```
Each time has a different metadata index. 
This PR fixes this problem by detecting …
=> [Fix][TVMScript] Fix index of metadata in printed script

python/tvm/relay/frontend/pytorch.py
Minor fix in pytorch frontend to compile gpt2 model, reproduce script.
torch_version = 1.13.1
transformers_version = 4.26.1
```
from transformers import GPT2LMHeadModel
import torch
import tvm
inp = torch.ones((1, 128)).to(torch.int64)
input_shapes = [("input_ids", ((1, 128), "int64"))]
model = GPT2LMHeadModel.from_pretrained('gpt2', return_dict=False)
trace_model = torch.jit.trace(model, inp, strict=False)
outputs = trace_model(inp)
mod, params = relay.frontend.from_pytorch(trace_model, input_shapes)
with tvm.transform.PassContext(opt_level=3):
lib = relay.build(mod, target='llvm', params=params)
runtime = tvm.contrib.graph_executor.GraphModule(lib["default"](tvm.device('cpu', 0)))
runtime.set_input("input_ids", inp.numpy())
runtime.run()
out = …
```
=> [Pytorch] frontend full_impl fix

docker/Dockerfile.ci_adreno, docker/Dockerfile.ci_cpu, docker/Dockerfile.ci_hexagon, docker/Dockerfile.demo_android, docker/install/ubuntu_install_androidsdk.sh
Let the Android NDK version configurable as a command line argument
=> [DOCKER] Configurable NDK version support

src/tir/schedule/primitive/sampling.cc, tests/python/unittest/test_tir_schedule_trace.py
This PR is another way to fix the issue described in #14118.
Since we do not have a standard for json file on the format of float numbers (for example, we cannot require a json file producer to print the "integer" float numbers with at least one decimal), and the json parser is not responsible for determining if an integer in a json file should be parsed to a float or an int, the most convenient way of fixing the SampleCategorical issue will be allowing both FloatImms and IntImms as input, and converting all IntImms to FloatImms accordingly.
This PR fixes the issue in this way.
=> [Fix][TIR] SampleCategorical apply-to-schedule

python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/__init__.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/dpl/pattern.py, src/relax/ir/dataflow_matcher.cc, tests/python/relax/test_codegen_cutlass.py
This PR adds support of transposed matmul to Relax CUTLASS backend. It is able to offload Relax expr like `R.nn.relu(R.matmul(x, R.permute_dims(y)) + bias)`.
Most of this PR is for handling the arg ordering in the fused function and remove the assumption of arg ordering in the CUTLASS GEMM codegen. This is because the fused function of transpose matmul will have `y` as the first argument due to how FuseOpsByPattern is implemented.
```
def fused_transposed_matmul(y, x, bias):
...
```
=> [Unity][BYOC] Add transposed matmul support to Relax CUTLASS BYOC

python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/multi_channel_convolve.py, tests/python/relay/aot/corstone300.mk
This pr has the same changes of https://github.com/apache/tvm/pull/12846.
=> [CMSIS-NN] Reduction in code size of AOT test runner binary

python/tvm/testing/aot.py, src/relay/backend/contrib/cmsisnn/compiler_attrs.cc, src/relay/backend/contrib/cmsisnn/compiler_attrs.h, src/relay/backend/contrib/cmsisnn/target.cc, src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc, tests/python/contrib/test_cmsisnn/test_last_error.py, tests/python/contrib/test_cmsisnn/utils.py, tests/python/relay/aot/corstone300.mk
This pr generates the code to catch and save, through TVMAPISetLastError, a CMSIS-NN error. 
In case an error is raised, it is retrieved with TVMGetLastError in the AOT test runner, and then it is printed.
@ashutosh-arm
=> [CMSIS-NN] Add a runtime error message

python/tvm/relay/op/_transform.py, tests/python/relay/test_any.py
This PR fix the issue https://github.com/apache/tvm/issues/14134.
Currently in squeeze shape function do not transform axis, which means negative axis such as -1 will lead to wrong result.
This PR fix this issue and add simple testcases.
=> [Fix][Relay] Fix axis transformation in squeeze shape function
