src/relax/transform/fuse_ops.cc, src/relax/transform/run_codegen.cc, tests/python/relax/test_transform_fuse_ops_by_pattern.py
This PR update `PatternBasedPartitioner` in `FuseOpsByPattern` to allow unused bindings to exist. Previously we apply `PostOrderVisit` which doesn't guarantee all LHS vars in `VarBindingNode` are visited. `FuseOpsByPattern` and `RunCodegen` are also updated to ignore `PrimFunc`
cc @sunggg @masahi @yelite
=> [Unity][BYOC] Assign group to unused bindings and ignroe PrimFunc

include/tvm/relax/transform.h, python/tvm/relax/backend/pattern_registry.py, python/tvm/relax/transform/transform.py, src/relax/backend/pattern_registry.h, src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops_by_pattern.py
This adds a callback check function to `FuseOpsByPattern` to further check whether the match result should be accepted.
cc @yelite @masahi
=> [Unity] Add callback to FuseOpsByPattern to check match result is accepted

python/tvm/relay/frontend/tflite.py, tests/python/frontend/tflite/test_forward.py
This PR fixes a bug on TFLite frontend import. Basically for conv2d group cases TFLite was only detecting group on only operators with specific `DEPTHWISE_CONV_2D` definition and ignoring group cases that happens with `CONV_2D`.
I also cleaned up test_forward for this importer.
=> [Frontend][TFLite] Fix conv2d import bug

include/tvm/node/script_printer.h, python/tvm/runtime/script_printer.py, src/node/script_printer.cc, src/script/printer/utils.h
This PR cleans up relax prefix in printer for now. While these setups are useful and do not cause any technical debts in the codebase. We remove it given requests. They can be added back to unity branch and later as part of upstream.
=> [TVMScript][Printer] Remove relax prefix for now

python/tvm/relay/backend/contrib/ethosu/legalize.py, python/tvm/relay/backend/contrib/ethosu/te/pooling.py, python/tvm/relay/backend/contrib/ethosu/tir_to_cs_translator.py, python/tvm/relay/op/contrib/ethosu.py, src/relay/op/contrib/ethosu/op_attrs.h, src/relay/op/contrib/ethosu/pooling.cc, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_legalize.py, tests/python/contrib/test_ethosu/test_replace_pooling.py
Supports legalizing a relay sum operation to an equivalent series of NPU operations. It supports case with int8 output type and channel axis.
=> [microNPU] Sum legalization support

src/meta_schedule/schedule_rule/multi_level_tiling.cc, tests/python/unittest/test_meta_schedule_space_cuda_async_multiple_initialization.py
This PR fixes redundant stages if visiting `InitializeWithTuneContext` multiple times.
=> [Fix][MetaSchedule] Fix redundant stages in async pipeline for mlt

python/tvm/relax/transform/legalize_ops/common.py, python/tvm/relax/transform/legalize_ops/creation.py, python/tvm/relax/transform/legalize_ops/datatype.py, tests/python/relax/test_transform_legalize_ops.py
This PR fixes the issue of loss of data type during Legalization. Previously, if we use a constant scalar in operators like `multiply`, it will automatically be converted to a python data type variable, which may lose its original data type. For example, `float16` may become python `float` and be interpreted as `float32` later.
This is now fixed by avoiding scalar value conversion. The conversion could be added back once we have better support for scalar prim value.
Co-authored by @sunggg and @vinx13.
CC: @MasterJH5574 @tqchen
=> [Unity][Legalize] Fix Scalar Constant Legalization

python/tvm/relax/transform/legalize_ops/common.py, src/relax/transform/fold_constant.cc, tests/python/relax/test_transform_fold_constant.py
Enhance constant folding to fold relax ops by evaluating them.
This uses the registered legalization function attached to the op to lower it to `call_tir` and uses the existing `call_tir` folding mechanism to fold it.
This kind of op folding is only allowed within dataflow block as ops could have side-effects.
Limitations:
* This currently does not support folding ops that could lower to multiple `call_tir` bindings.
* Folding by evaluating ops is not always beneficial. We need a heuristic to check if it is useful. This is not implemented yet and folding is always allowed by evaluating expressions.
=> [Unity][Pass] Enhance constant folding to fold relax ops by evaluating them.

python/tvm/relax/testing/__init__.py, python/tvm/relax/testing/ast_printer.py, tests/python/relax/test_ast_printer.py
This PR transfers over the AST printer from tlc-pack/relax. The AST printer is a debugging tool that prints out a Relax AST in a precise and human-readable format, which can be helpful for debugging the parser or various passes.
Co-authored by @YuchenJin @LeshengJin @Hzfengsy @MasterJH5574 @tqchen (everyone who contributed to https://github.com/tlc-pack/relax/blob/relax/python/tvm/relax/testing/ast_printer.py)
=> [Unity][Debugging] AST printer

python/tvm/runtime/__init__.py, python/tvm/runtime/params.py, src/runtime/file_utils.cc, tests/python/unittest/test_runtime_graph.py
https://github.com/apache/tvm/pull/13877 lowered memory usage for VM runtime load / save. The same issue observed by @AndrewZhaoLuo is still present in the graph runtime counterpart, `tvm.runtime.load_param_dict` and `tvm.runtime.save_param_dict`. In addition, we are carelessly making another copy of `ndarray`s in `save_param_dict`. 
All of this leads to absurd RAM requirement when loading / serializing stable diffusion UNet. The total size of its parameters is < 3.5G, but loading or saving these params take more than 16G of RAM (!!):
```
$ cat test_params.py
import tvm
with open("unet.params", "rb") as fi:
params_ref = tvm.runtime.load_param_dict(fi.read())
with open("unet.params", "wb") as fo:
fo.write(tvm.runtime.save_param_dict(params_ref))
$ /usr/bin/time -v python test_params.py …
```
=> [Runtime] Fix high RAM usage when saving / loading paramters of big models  

python/tvm/relay/expr.py, python/tvm/relay/frontend/common.py, python/tvm/relay/frontend/pytorch.py, python/tvm/relay/frontend/qnn_torch.py, tests/python/frontend/pytorch/qnn_test.py, tests/python/frontend/pytorch/test_forward.py, tests/python/frontend/pytorch/test_fx_quant.py, tests/python/frontend/pytorch/test_lstm.py, tests/python/frontend/pytorch/test_object_detection.py, tests/python/frontend/pytorch/test_rnns.py
- Construct debug name of C graph instruction as the source name of span for pytorch model.
- To get the reference of renamed nodes. Add a function to export the converted C graph after conversion.
- Add structural_equal comparisons with and without set_span to the existing test cases.
- Add span test cases for frequent conversions.
- Add span test case for exporting model parameter.
=> [Relay][Frontend] Span Filling PyTorch

src/relax/analysis/well_formed.cc, tests/python/relax/test_analysis_well_formed.py
The current well-formed misses the check of function return struct info, which may mistakenly pass the check if there are undefined vars in the function return struct info.
=> [Unity][Analysis] Checking function return struct info in well-formed check

python/tvm/relax/transform/legalize_ops/nn.py, tests/python/relax/test_codegen_cutlass.py, tests/python/relax/test_codegen_dnnl.py, tests/python/relax/test_codegen_tensorrt.py
Currently BYOC tests are using Relay as reference because (1) legalize was not available before or (2) tensorcore result is needed for cutlass. This PR removes the use of Relay in CUTLASS, DNNL, and TRT tests.
For cutlass, I'm using small integer inputs to workaround the accuracy issue.
@tqchen @vinx13 @yelite
=> [Unity][BYOC] Use Relax legalize + CPU build for reference in tests

include/tvm/relax/transform.h, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/transform/transform.py, src/relax/transform/fuse_ops.cc, tests/python/relax/test_codegen_cutlass.py, tests/python/relax/test_transform_fuse_ops_by_pattern.py
This PR added `lift_constants` option to FuseOpsByPattern since different BYOC backends have different requirements on whether constants should be lifted.
cc @masahi
=> [Unity] Add bind_constants option to FuseOpsByPattern

python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/backend/pattern_registry.py, src/relax/backend/pattern_registry.cc, src/relax/backend/pattern_registry.h, src/relax/transform/fuse_ops.cc, tests/python/relax/test_codegen_cutlass.py
This PR adds the support of batch matmul to Relax CUTLASS BYOC. This includes batch matmul with shape 2D x ND, ND x 2D and ND x ND. Additionally, this supports bias, transposed y and all supported epilogues from regular matmul.
This PR also includes:
1. Add check function to all APIs related to PatternRegistryEntry (a follow up of #14109)
2. Add check function to CUTLASS pattern table, blocking unsupported matmul from being partitioned.
3. Reorganize the tests related to CUTLASS matmul.
=> [Unity][BYOC] Add batch matmul support to Relax CUTLASS BYOC

apps/android_camera/README.md, apps/android_camera/app/src/main/AndroidManifest.xml, apps/android_camera/models/prepare_model.py, apps/android_deploy/README.md, apps/android_deploy/app/src/main/AndroidManifest.xml, apps/android_rpc/README.md, apps/android_rpc/app/src/main/AndroidManifest.xml
- Starting from API 31, using `uses-native-library` is required if we
want to open system library:
https://developer.android.com/about/versions/12/reference/compat-framework-changes#enforce_native_shared_library_dependencies
We should specify OpenCL library in `user-native-library` in all
applications where OpenCL backend might be used.
- Updated README files and describe how to fix synchronization issues
in Android Studio.
=> [Android] Fix using system libraries in Android apps

python/tvm/tir/tensor_intrin/cuda.py
`mma_store` has a scope field but we only supports `global`, which is problematic if we want a `mma_store` intrinsic that writes to `shared` scope.
Credit to @cyx-6 for finding this bug.
=> [bugfix] Fix the write buffer scope of `mma_store_impl`

docs/conf.py
Update the version menu in TVM documentation to add a specific `v0.11.0` release docs link.
@tqchen @leandron
=> Add v0.11.0 docs link to site

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/layout_transformation.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_transform_layout.py
TransformLayout requires the index map to have inverse map that can be calculated by the analyzer in order to check whether padding is added.
However, such check doesn't always work for all cases because of limitation of the affine analysis that can only handle a set of supported patterns. In some cases, even if the index map doesn't introduce padding, the schedule primitive throws `TransformationIntroducesPaddingError` because it fails to calculate the inverse index map.
It is safe to allow buffer being padded without providing pad_value because the original loop extent is not changed and the padded region is not accessed. This PR changes the behavior of `TransformLayout` to allow non-inversible index map.
cc @Lunderberg @Hzfengsy
=> [TIR] Allow TransformLayout with non-inversible index map

python/tvm/relax/analysis/analysis.py, tests/python/relax/test_analysis.py
This PR restores the Python bindings for several analyses related to variables, originally done in https://github.com/tlc-pack/relax/pull/265. These had been implemented in C++ but not exposed in Python.
Question: Do we also want to restore the `CalledGlobalVars` analysis? I notice the C++ implementation for that one has been removed and I am wondering if there was a reason for the removal.
=> [Unity][Analysis] Restore Python bindings for var analyses

src/meta_schedule/database/json_database.cc
At this moment, the structural hash values of IR in TVM is platform dependent (e.g., the hash values of a String may differ on different platforms). In our recent practice, we found this an obstacle for us to apply one existing database on different platforms (say we tune an IRModule with MetaSchedule on Metal, and then apply the database on CUDA, etc.)
To clear this obstacle, we decide to remove the shash value check. The purpose of that check is mainly to ensure safety, and thus turning it off will make no difference in terms of using MetaSchedule in most of the cases that we can imagine.
Meanwhile, it is equally important that we need to make our structural hash platform independent. There are plans ongoing for this target.
=> [HotFix][MetaSchedule] Turn off database shash check

python/tvm/topi/nn/batch_norm.py, python/tvm/topi/testing/batch_norm.py, tests/python/topi/python/test_topi_batch_norm.py
Prior to this PR, TOPI batch_norm only supports inference. 
This PR adds `training: bool` flag and `momentum: float` argument to support training mode (update `moving_mean / var` and return), which aligns with `torch.nn.functional.batch_norm`.
=> [TOPI] Batch Norm Training Mode

include/tvm/relax/attrs/nn.h, include/tvm/topi/nn/group_norm.h, python/tvm/relax/frontend/torch/fx_translator.py, python/tvm/relax/op/nn/nn.py, python/tvm/relax/transform/legalize_ops/nn.py, python/tvm/topi/nn/__init__.py, python/tvm/topi/nn/group_norm.py, python/tvm/topi/testing/__init__.py, python/tvm/topi/testing/group_norm_python.py, src/relax/op/nn/nn.cc, src/relax/op/nn/nn.h, src/topi/nn.cc, tests/python/relax/test_ast_printer.py, tests/python/relax/test_frontend_from_fx.py, tests/python/relax/test_op_nn.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/relax/test_tvmscript_parser_op_nn.py, tests/python/topi/python/test_topi_group_norm.py
This PR introduces the group normalization high-level operator.
Prior to this PR, the group normalization operations in frontend models are translated to a series of operations, which brings inconvenience when we want to optimize the group norm op as a whole.
With the TOPI implementation of group norm being introduced by https://github.com/apache/tvm/pull/14193, we can now use it to legalize the high-level group norm op and optimize it using cross-thread reduction or rfactor via MetaSchedule.
Full implementation credit goes to Bohan.
=> [Unity][Op] Group normalization

include/tvm/topi/nn/group_norm.h, python/tvm/topi/nn/__init__.py, python/tvm/topi/nn/group_norm.py, python/tvm/topi/testing/__init__.py, python/tvm/topi/testing/group_norm_python.py, src/topi/nn.cc, tests/python/topi/python/test_topi_group_norm.py
As more and more ML models nowadays contain the group normalization computation, we find it beneficial to introduce this op to TOPI level. It will enable us to optimize the group normalization operation as a whole in a more convenient way.
This PR introduces the group normalization op to TOPI. The group norm operation was introduced in https://arxiv.org/abs/1803.08494. The implementation uses tuple reduction, same as the implementation of layer norm. Implemented with tuple reduction, the corresponding generated TIR function can be optimized by cross-thread reduction or rfactor through MetaSchedule.
Full implementation credit goes to Bohan.
=> [TOPI] Group normalization

python/tvm/relax/transform/legalize_ops/unary.py, tests/python/relax/test_transform_legalize_ops_unary.py
This PR implements the legalization for four unary operators:
* round,
* floor,
* ceil,
* sign.
Unit tests are provided accordingly.
=> [Unity][Op] Legalize `round`, `floor`, `ceil`, `sign`

python/tvm/relax/frontend/__init__.py, python/tvm/relax/frontend/common.py, python/tvm/relax/frontend/torch/dynamo.py, python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_dynamo.py, tests/python/relax/test_frontend_from_fx.py
PR #14067 introduces the flag `keep_params_as_input` to the FX translator, in the purpose to handle to model weights outside of the translated Relax function.
This PR takes a further step, by returning the model weights as NDArrays when the flag `keep_params_as_input` is true. With this PR, the translator now can return back the weights upon requested. Otherwise, after the import we will lose the model weights in the given PyTorch model.
=> [Unity][Frontend] FX translator returning weights with `keep_params_as_input`

src/tir/transforms/lower_cross_thread_reduction.cc, tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
Prior to this PR, the cross-thread reduction lowering pass does not add a store predicate to the write-back block. This is in consideration that for a certain write-back buffer position, all values being stored (by all the threads) in the write-back block are the same. Since all threads are writing the same value, we were assuming that not having a write-back block predicate is fine, because the result will not be wrong in any way.
However, recently we noticed that some GPU backend compiler will capture this behavior (multiple threads writing a same position) as a race condition and thus throw compilation error. The compiler does not take the fact that all values being stored are the same, and insist on complaining.
This means that we will still need the write-back block predicate to make …
=> [Fix][TIR] LowerCrossThreadReduction with write-back predicate

python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_from_fx.py
This PR fixes a bug of the current FX translator when dealing with dtype.
Previously, the translator does not take the cases
```python
dtype = x.getattr("dtype")
```
into consideration. In this case, the dtype will be a fx.Node object, while the translator assumes that the dtype is either a string or a torch native datatype (e.g., torch.float32).
This PR fixes this by doing an environment table lookup before for all dtypes.
=> [Unity][Fix] FX translating dtype

include/tvm/tir/transform.h, python/tvm/tir/transform/transform.py, src/tir/transforms/force_narrow_index_to_i32.cc, tests/python/unittest/test_tir_transform_force_narrow_index_to_i32.py
This PR introduces a pass which forces every index expression in a PrimFunc to have dtype int32. Meanwhile, it also checks if all integer buffers in the PrimFunc have int32 dtype, and report error if some integer buffer has dtype other than int32.
In terms of implementation, this pass leverages the IndexDataTypeNormalizer, with the target dtype being int32.
This PR contains a few basic tests that come from
`test_tir_transform_narrow_datatype.py`, and contains some negative tests as well.
=> [Unity][TIR][Pass] ForceNarrowIndexToInt32

python/tvm/driver/tvmc/compiler.py, tests/python/driver/tvmc/test_compiler.py
Currently dumps the TIR code after the final phase of lowering (phase 3 from https://github.com/apache/tvm/blob/665dd413bc85d14f7836324daf7cc0dd9281c85a/gallery/how_to/extend_tvm/low_level_custom_pass.py#L152) before codegen. This is done by running a pass to capture the TIR module as it is not saved during the build. The result is saved to file similar to the other code dumps.
In the future it seems good to have more granularity in the IR that is being dumped, e.g. print IR before/after named pass. I thought this might be helpful in the meantime.
cc @ekalda @ashutosh-arm @neildhickey
=> [TVMC] Add option to dump TIR code to file

python/tvm/meta_schedule/testing/space_generation.py, src/meta_schedule/postproc/verify_gpu_code.cc, src/meta_schedule/schedule_rule/multi_level_tiling.cc, src/meta_schedule/schedule_rule/multi_level_tiling.h, src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc, src/meta_schedule/schedule_rule/multi_level_tiling_wide_vector.cc, src/tir/analysis/block_access_region_detector.cc, src/tir/schedule/ir_comparator.cc, src/tir/schedule/ir_comparator.h, src/tir/transforms/manifest_shared_memory_local_stage.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_tc.py, tests/python/unittest/test_tir_transform_inject_software_pipeline.py
This PR changes the meta schedule rule for CUDA tensor core. It adds additional tiling and layout transformation (pack the buffer by 16x16 accumulator shape) of the output in the shared memory. By transforming the buffer to higher rank with innermost shape of 16x16, it avoids strided access that `CompactBufferRegion` and `compute_at` cannot handle and reduces shared memory usage for the output
=> [MetaSchedule] Tile and pack intermediate output for CUDA TensorCore

docker/install/ubuntu_install_paddle.sh, tests/python/frontend/paddlepaddle/test_forward.py
Upgrade paddlepaddle to 2.4.2, and fix 2 bugs in tests
@masahi
=> [Frontend][PaddlePaddle] Fix bug in tests for upgrading paddlepaddle to 2.4.2

python/tvm/relax/frontend/common.py, python/tvm/relax/frontend/torch/dynamo.py, python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_common.py, tests/python/relax/test_frontend_dynamo.py, tests/python/relax/test_frontend_from_fx.py
The class ImporterOutput introduced by #14197 turns out introducing inconvenience for use, as it is a wrapper of IRModule and the parameters, and prevents good composability when we want to combine multiple ImporterOutput together.
From the perspective of easy use, we would like to return IRModule only. Therefore, as another approach, we can make the imported parameters as one function attribute, and detach the parameters later.
This PR implements this and provides the param detachment function. With only IRModule being manipulated, we can easily combine the results from multiple imports.
=> [Unity][Frontend] Attach imported model weights, deprecate ImporterOutput

python/tvm/relax/frontend/torch/dynamo.py, python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_dynamo.py, tests/python/relax/test_frontend_from_fx.py
Previously we found that the FX GraphModule captured by torch.dynamo will always return a tuple at the end, even if the Module being traced returns a single object. Unwrapping the unit tuple in that case can help and ease model deployment. Therefore, this PR introduces an option "unwrap_return_unit_tuple" to `from_fx`, to indicate if we caller wants to unwrap the returned unit tuple.
`dynamo_subgraph_capture` now will always use True on this option.
=> [Unity][Frontend] FX translator supports unwrapping unit return tuple

include/tvm/runtime/module.h, python/tvm/runtime/module.py, src/runtime/metal/metal_module.mm, src/runtime/module.cc, src/target/source/codegen_webgpu.cc, src/target/source/codegen_webgpu.h, web/apps/browser/rpc_server.html, web/src/rpc_server.ts, web/src/runtime.ts, web/src/webgpu.ts
Readonly detection can cause the kernel arg order
to be different from other shaders, add options to optionally skip it.
Also makes export auto use emcc for wasm target.
=> [Unity][WEB] Improve webgpu codegen options to skip readonly

python/tvm/relax/__init__.py, python/tvm/relax/frontend/common.py, python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_from_fx.py
Previously `from_fx` iterates model's `named_parameters()` to fetch all model's parameters. However, the order of iteration is not deterministic and might cause flakiness and instability in deployment.
This PR removes the undeterminism by using `sorted(named_parameters())`. In this way we are guaranteed to have a deterministic list of function parameters.
=> [Unity][Frontend] from_fx keeps parameters in order

include/tvm/node/reflection.h, include/tvm/node/structural_hash.h, include/tvm/runtime/container/string.h, src/node/structural_hash.cc, src/relay/backend/utils.h
This PR introduces the necessary change to make structural-hash platform-independent. The change includes:
- Explicitly require the hash type to be `uint64_t` rather than platform-dependent `size_t`.
- Implement structural hash for POD types including `double`, `int` by unioning them with `uint64_t` explicitly.
- Implement a platform-independent fast hashing algorithm for `std::string`
=> [IR] Platform-independent SHash

python/tvm/meta_schedule/tune_context.py
Right now seems a global symbol main will be attached to every fused prim_func after Meta Schedule tuning.
Although the problem get hidden because we will re-attach global symbols, this is a behavior that need to be fixed.
Now the transformed prim func preserves the original global symbol. If it doesn't exist, attach global symbol main.
cc: @tqchen @junrushao
=> [MetaSchedule] preseve global_symbol attached to function after applying MS

include/tvm/script/ir_builder/tir/ir.h, python/tvm/script/ir_builder/tir/frame.py, python/tvm/script/ir_builder/tir/ir.py, src/script/ir_builder/tir/ir.cc, src/script/printer/tir/stmt.cc, tests/python/unittest/test_tvmscript_roundtrip.py
This PR introduces a syntactic sugar that combines T.env_thread and T.launch_thread.
Previously, an AttrStmt that specifies thread extent or virtual thread is required to be written in two steps:
```python
bx = T.env_thread("blockIdx.x")  // creates an IterVar
with T.launch_thread(bx, 128):   // specify the iter domain
...
```
With this PR, now this behavior can be merged in a single line:
```python
with T.launch_thread("blockIdx.x", 128) as bx:
...
```
=> [TVMScript] Sugar T.env_thread + T.launch_thread

python/tvm/script/ir_builder/tir/ir.py, src/script/ir_builder/tir/ir.cc, src/script/printer/doc_printer/python_doc_printer.cc, src/script/printer/tir/buffer.cc, src/script/printer/tir/expr.cc, src/script/printer/tir/function.cc, src/script/printer/tir/utils.h, tests/python/unittest/test_tvmscript_roundtrip.py
This PR introduces sugars for TIR buffer declaration.
Sugar 1. Convenient stride definition by string.
```python
// Previous
stride = T.int32()
A = T.match_buffer(..., strides=(stride,))
// This PR
A = T.match_buffer(..., strides=("s0", ))
```
Sugar 2. Multiple definition of TIR Var from a single buffer are now merged into a single line.
```python
// Previous
m = T.int32()
n = T.int32()
stride = T.int32()
stride_1 = T.int32()
A = T.match_buffer(a, (m, n), strides=(stride, stride_1))
// This PR
m, n = T.int32(), T.int32()
A = T.match_buffer(a, (m, n), strides=("s0", "s1"))
```
=> [TVMScript] Sugar Var Definition in TIR Buffer

src/relax/transform/static_plan_block_memory.cc, tests/python/relax/test_transform_static_plan_block_memory.py
Previously the static memory planning pass only works at single function level - each function inside the an IRModule will be independently planned. This is not perfect for the VM to reuse allocated memory across different functions.
Therefore, this PR turns the static memory planning pass into a module pass. Now the plan is done across the IRModule, so that memory alloation in different functions can share the same storage token when planning. With this PR, it is hopeful that the VM will find more opportunities of memory reuse.
=> [Unity][Transform] Memory plan across the IRModule

docker/Dockerfile.ci_arm, docker/install/ubuntu_install_llvm_from_source.sh, tests/scripts/task_config_build_arm.sh, tests/scripts/task_config_build_minimal_cross_isa.sh
This allows us to use the latest llvm and make sure it builds with the same configuration as the rest of tvm
Change-Id: I004ec89700498167c632d25f4fdf667922ba4943
=> [Docker] Add script to build llvm from source

src/tir/transforms/unroll_loop.cc, tests/python/unittest/test_tir_transform_unroll_loop.py
This PR enhances the unroller with an unroll local access option. This option will detect loop variables that access local memories and unroll them independent of other options.
A test case is added. This option is by default turned off and can be useful in certain cases to improve unroller as these local memory access have to be unrolled at some time pt to be lifted as registers.
=> [TIR] Enhance loop unroll with unroll local access

python/tvm/relax/op/vm/__init__.py, python/tvm/relax/op/vm/_ffi_api.py, python/tvm/relax/op/vm/vm.py, python/tvm/relay/op/op_attrs.py, python/tvm/script/ir_builder/relax/ir.py, src/relax/op/op.cc, tests/python/relax/test_tvmscript_parser.py
- make R.memory.alloc_tensor/alloc_storage roundtrippable
- Expose relax.vm ops to python side
cc: @MasterJH5574
=> [Unity] ensure memory.alloc_tensor/storage roundtrippable

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/simplify_norm_inference.cc, src/relax/transform/utils.h, tests/python/relax/test_transform_simpilify_norm_inference.py
This PR adds a new pass SimplifyNormInference to unpack the norm operator into a sequence of operators, which is same as the pass SimplifyInference in Relay.
Co-authored-by: Siyuan Feng <hzfengsy@sjtu.edu.cn>
=> [Unity][Transform] SimplifyNormInference

include/tvm/script/ir_builder/tir/ir.h, include/tvm/tir/var.h, python/tvm/script/ir_builder/tir/ir.py, src/script/ir_builder/tir/ir.cc, src/script/printer/tir/expr.cc, src/tir/ir/expr.cc, tests/python/unittest/test_tvmscript_printer_tir.py
Previously the printer does not respect the difference between tir.Var and tir.SizeVar, which means SizeVar info will be lost during roundtripping, which is not ideal when dealing with dynamic shape workloads, where SizeVar provides additional bound information to the arithmetic analyzer.
This PR extends Var printing to support SizeVar:
```python
>>> a = tir.SizeVar("a", "int32")
>>> print(a.script(verbose_expr=True))
a = T.int32(is_size_var=True)
a
```
=> [TVMScript] Support SizeVar Roundtripping

tests/python/unittest/test_target_codegen_llvm.py
In the test `test_llvm_div`, some cases can lead to a division by 0. Consider the case when `start=-12, end=-12, dstart=-2 and dend=0`, the range of values input to clipb() will be: [-12, ..., -1, 1] (with 1 being specially selected to prevent division by 0). For the input 1, clipb evaluates to: `min(/*dend=*/0, max(/*dstart=*/-12, /*i=*/1)) = 0`, thus leading to a division by 0.
LLVM11, which runs in CI, doesn't seem to throw any kind of error, while using LLVM15 leads to a "floating point exception". Regardless, since division by 0 is undefined behaviour and the compiler can do anything, the solution here is to fix the test so division by 0 doesn't occur.
=> [TEST] Fix division by 0 in llvm codegen test

python/tvm/driver/tvmc/autotuner.py, python/tvm/driver/tvmc/compiler.py, python/tvm/driver/tvmc/transform.py, tests/python/driver/tvmc/test_compiler.py, tests/python/driver/tvmc/test_transform.py
Adds new command line options:
* `--mixed-precision` - Enable mixed precision conversion
* `--mixed-precision-ops` - List of operators to be converted to mixed precision
* `--mixed-precision-calculation-type` - Calculation precision type
* `--mixed-precision-acc-type` - Accumulator precision type
And: 
* `--desired-layout-ops` - The list of operators to be transformed with desired layout.
=> [TVMC][TRANSFORMS] ToMixedPrecision transform support with custom options enabled

src/target/llvm/codegen_blob.cc, src/target/llvm/codegen_llvm.cc
In the latest version of [llvm-project](https://github.com/llvm/llvm-project), the `llvm/ADT/Triple.h` has been moved to `llvm/TargetParser/Triple.h`. Thus, anyone who compile and install llvm from source may encounter this:
```shell
fatal error: llvm/ADT/Triple.h: No such file or directory
30 | #include <llvm/ADT/Triple.h>
```
This error can be solved by adding `LLVM_VERSION_MAJOR` judgement to include correct head file.
#14136
=> [LLVM][BugFix] Fix include Triplet.h bug when LLVM version>= 17

ci/jenkins/docker-images.ini
As requested in https://github.com/apache/tvm/pull/14206, update the CPU and GPU image for paddle 2.4.2. Verified in https://github.com/apache/tvm/tree/ci-docker-staging
@jiangjiajun 
cc @driazati to confirm if this is the correct way to update CI images
=> [CI] Update cpu and gpu image

python/gen_requirements.py
This fixes a python error that happens after running `import tvm` when you install apache-tvm-0.11.0 wheel into a pristine virtualenv.
@leandron @driazati @junrushao
=> Add typing_extensions requirement

conda/recipe/meta.yaml, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/package.json
This bumps all the version numbers following the v0.11.0 branch cut.
Fixes #14208.
=> Update to v0.12.dev0

src/relax/op/op.cc, tests/python/relax/test_ast_printer.py, tests/python/relax/test_relax_operators.py
This PR improves the `FInferStructInfo` for `shape_of`. Namely, it checks if the argument has `TensorStructInfo` and transfers over the shape information if it is present.
=> [Unity][Op][Tweak] Improve `StructInfo` inference for `shape_of`

python/tvm/contrib/hexagon/transform.py, tests/python/contrib/test_hexagon/test_relay_transforms.py
This PR contains relay pattern matching to roll a pattern containing strided_slice, qnn.dense, qnn.requantize, reshape, transpose, expand_dims and concatenate operators into batch_matmul operator.
https://discuss.tvm.apache.org/t/optimizing-qat-distilbert-int8-model/14182 contains more details.
@masahi @quic-sanirudh  @arangasa @jverma-quic @kparzysz-quic
=> Relay transform for rolling a known pattern into batch_matmul

python/tvm/relax/block_builder.py, python/tvm/relax/utils.py, python/tvm/script/ir_builder/relax/ir.py, tests/python/relax/test_tvmscript_parser.py
Allow users to specify PrimFunc attributes to be added when using `emit_te`.
`bb.emit_te` and `R.emit_te` would now have a reserved keyword arg `primfunc_attrs` which would be function attrs to be added to the generated PrimFunc.
=> [Unity] Allow user defined func attrs in emit_te

python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/conv2d_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/backend/patterns.py, tests/python/relax/test_codegen_cutlass.py
This PR adds cutlass BYOC pattern for conv2d and conv2d residual block. 
In additional to the new patterns in the cutlass pattern table, this PR:
1. Remove the assumption on fused function arg order from the conv2d codegen.
2. Restructure how the cutlass pattern table is constructed, making it more readable.
The check logic at https://github.com/apache/tvm/blob/main/python/tvm/relay/op/contrib/cutlass.py#L200 isn't implemented in this PR yet because it requires non-trivial change to the interface of FuseOpsByPattern. I will send a separate PR to do this.
=> [Unity][BYOC] Add conv2d and residual block patterns for Relax cutlass BYOC

cmake/modules/contrib/DNNL.cmake, src/relay/backend/contrib/dnnl/codegen.cc
Symptom:
After setting DNNL="C_SRC" to generate C code, the compiler reported an error that the function "BindToCallNodeArgs" was missing and there was a problem with linking "dtype_dl2dnnl". Another issue is the compile complain for ambiguous "GetRootCall".
After fixing the compilation issue, when executing relay.build, an error occurred complaining "Check failed: const_var_ndarray_ .count(var) > 0 (0 vs. 0)"
Solution:
Update the cmake file and change the codegen.cc.
=> [BYOC] DNNL C_SRC Fix

tests/python/unittest/test_target_codegen_aarch64.py
Now that ci_arm contains LLVM 15, add tests to check that code for SVE can be correctly generated.
Add tests to cover a selection of arithmetic ops and gather loads. The gather load is currently xfailed until work is completed to enable them through TVM and LLVM.
=> [SVE] Adding codegen tests for SVE

python/tvm/relax/testing/relay_translator.py
Some of Relay passes are target specific (for example, AlterOpLayout). This commit adds target information for Relay -> Relax conversion.
=> [Unity] Consider target context for Relay to Relax conversion

src/arith/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
This parallels an existing simplification rule for `x - min(x,y, z)`, applying the same cancellation for `max`.
=> [Arith] Add simplification rule for `x - max(x+y, z)`

python/tvm/ir/transform.py, python/tvm/relay/transform/transform.py, python/tvm/te/hybrid/parser.py, python/tvm/tir/transform/function_pass.py
Previously, type-checking of a callable arguments, such as to `tvm.ir.transform.module_pass`, was done using `isinstance(arg, (types.FunctionType, types.LambdaType))`.  This check can give false negatives for valid python types, such as a bound method or an instance of a class that implements `__call__`.
This commit replaces the checks with the builtin function `callable()`, which handles any Python object that can be called using function-like syntax.
=> [Transform] Use callable() instead of isinstance() for type checking

ci/jenkins/unity_jenkinsfile.groovy
We prefer these instances in CI unless there is a lot of heavy building going on (the normal tvm build is cached with sccache so this is usually just for docker builds).
=> [Unity][ci] Use CPU-SMALL instances

python/tvm/relay/frontend/paddlepaddle.py, tests/python/frontend/paddlepaddle/test_forward.py
Add grid-sample/gaussian_random/flip/fill_zeros_like/unique for paddle frontend.
=> [PaddlePaddle Hackathon 4][Frontend][Paddle]add grid-sample/gaussian_random/flip/fill_zeros_like/unique for paddle frontend

python/tvm/meta_schedule/utils.py, tests/python/unittest/test_meta_schedule_post_order_apply.py
Instance methods that exist in the user-defined class but not in the TVM base are forward using `__getattr__`.  However, this is only applied for attribute look of instances, and doesn't apply for attribute lookup on the class object itself, such as when calling a classmethod or staticmethod.
This commit exposes class methods and static methods in the wrapper class, if they are defined in the user-defined subclass.
=> [Utils] Allow classmethod and staticmethod in TVMDerivedObject

src/relax/op/op.cc, tests/python/relax/test_op_misc.py
A hot fix for the struct info deduction for `vm.alloc_tensor`
cc @jinhongyii
=> [Unity] Fix StructInfo Infer for `vm.alloc_tensor`

gallery/how_to/work_with_microtvm/micro_custom_ide.py, python/tvm/micro/testing/utils.py, tests/scripts/request_hook/request_hook.py, tests/scripts/task_config_build_gpu.sh
Adds "Bring microTVM to your own development environment" to microTVM tutorials. This tutorial describes the steps required to integrate a model compiled with microTVM into a custom development environment. We use STM32Cube IDE, the VWW model and the nucleo_l4r5zi board.
=> [microTVM] Custom IDE Tutorial

python/tvm/relay/quantize/_annotate.py, python/tvm/relay/quantize/_partition.py
When attempting to run inference with an 8-bit quantized version of [EfficientNet](https://arxiv.org/abs/1905.11946) ([PyTorch implementation](https://github.com/pytorch/vision/blob/main/torchvision/models/efficientnet.py)), I found that the quantization process crashed, which you can reproduce with [this gist](https://gist.github.com/Wheest/bd4fd601a15d6813e45c9ed5cdbae64f).
Upon closer inspection, I believe that the issue is related to the "Squeeze-and-Excitation block", where we multiply the output of a sigmoid with an earlier output.
Sample IR:
```
%363 = sigmoid(%362);
%364 = multiply(%362, %363);
%365 = nn.adaptive_avg_pool2d(%364, output_size=[1, 1]);
%366 = nn.conv2d(%365, %features.7.0.block.2.fc1.weight, padding=[0, 0, 0, 0], channels=48, kernel_size=[1, 1]);
%367 = …
```
=> [fix][relay][qnn] Bug fix for 8-bit quantized mul

docker/install/ubuntu_install_ethosn_driver_stack.sh
Some use cases of the NPU integration rely on ssh being available within the docker image in order to launch an RPC server on a remote device. This commit adds ssh as a dependency on the NPU driver stack installation.
cc @ashutosh-arm @Liam-Sturge
=> [CI][ETHOSN] Add ssh to the driver stack installation

include/tvm/te/schedule.h, python/tvm/contrib/tedd.py, src/relay/backend/te_compiler.cc, src/te/schedule/schedule_dataflow_rewrite.cc, src/te/schedule/schedule_lang.cc, tests/python/contrib/test_tedd.py, tests/python/relay/test_build_module.py, tests/python/unittest/test_te_schedule_ops.py
- Make Stage link to its Schedule via attach_sch.
- Add two array attributes, primitive_record and schedule_record to Schedule.
- Create a new class, ScheduleContext, to record primitives.
- Register a pass config variable, keep_schedule_record to enable/disable the recording.
- Add test cases for TEDD, build_module and schedule ops.
=> [TE] Record primitives of Schedule for visualization

conda/recipe/meta.yaml, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/package.json
* Adjust version numbers for source package release, which does not contain git metadata to infer the release version.
cc @areusch @driazati @Johnson9009 for reviews
=> [Release] Adjust version to 0.11.1

src/ir/module.cc
As GlobalVars are defined under IRModule, we need to define it during the IRModule SEqual/SHash step via (`DefEqual` and `DefHash`).
cc @tqchen @cyx-6
=> [IR] Enhance IRModule SEqual/SHash to support cross function calls

python/tvm/relay/frontend/paddlepaddle.py
Remove redundant `abs` op for `dist`.
Cover the case where `num_columns`  is equal -1 for `eye`.
=> [Frontend][Paddle]fix eye and dist

src/tir/transforms/narrow_datatype.cc, tests/python/unittest/test_tir_transform_narrow_datatype.py
This is enhancement of [PR#13327](https://github.com/apache/tvm/pull/13327).
**Motivation**:
Playing with MetaScheduler for Hexagon target it was found that `avg_pool2d` has rather poor performance due to lack of vectorized code. `IndexDataTypeNormalizer `pass converts all indices to "int64" format and `NarrowDataTypeRewriter` should do the opposite (back to "int32"). In case of fail, we have a lot of int64 arithmetic for average pooling that can not be vectorized.
**What was done:**
Added support of binary ops ("div", "max", "min", "+" etc.) in `NarrowDataTypeRewriter`. In case of different bitwidth of operands in binary opeation it does downcasting instead of upcasting (as it was before).
**Performance impact:**
`avg_pool2d` from quantized InceptionV3 with the shape [1, 8, 35, 35, 32] …
=> [TIR][Hexagon] Enhancement of NarrowDataType pass for binary ops

ci/jenkins/docker-images.ini
Update `ci_arm` to have support for LLVM 15, which brings better support for vectorisation.
The proposed docker tag is: `20230314-060145-ccc0b9162`.
cc @Mousius @neildhickey @lhutton1 for reviews
=> [CI] Update ci_arm docker image to have LLVM 15

python/tvm/driver/tvmc/autotuner.py, python/tvm/driver/tvmc/main.py, python/tvm/driver/tvmc/runner.py, tests/python/driver/tvmc/test_command_line.py
Three logger related changes in this patch:
* Currently we don't set the output stream on the Python logger, so it defaults to sys.stderr, which means we only get some logger output when the command fails. So set the output stream to sys.stdout
* Currently we can add -v flag to anywhere in the command line for `tvmc compile`, but only between `tvmc` and `run`/`tune` for `run` and `tune`. Unify the behaviour such that we can add the flag anywhere on the command line.
* Set the effective upper bound of `-v`s to 3 as 4 could result in NOTSET which would not output anything.
=> [TVMC] Fix logging in TVMC

src/relax/op/tensor/manipulate.cc, tests/python/relax/test_op_manipulate.py
In most definitions of Reshape, having a `0` in the `new_shape` argument means that the shape for that dimension in the output should be copied from the input. This PR extends the shape handling of `relax.op.reshape` to support this case and updates the tests accordingly.
=> [Unity][Op] Enable special dimension value 0 in reshape

src/arith/iter_affine_map.cc, src/tir/schedule/primitive/compute_at.cc, tests/python/unittest/test_tir_schedule_compute_at.py
In `compute-at` primitive currently, when estimate iteration domain to cover required buffer region, we use limited heuristic rules. The change try to improve using existing arith tool `InverseAffineIterMap`. Then theoretically, all single buffer access which is of bijective mapping from block iter vars are solvable. 
A new test case describe that if a block represents arbitary transpose/reshape ops,  `compute-at` this block would always expect to success.
```python
@T.prim_func
def NCHW16c_to_NCHW8c(A: T.Buffer((1, 3, 5, 5, 16), "float32"), C: T.Buffer((1, 6, 5, 5, 8), "float32")):
B = T.alloc_buffer((1, 3, 5, 5, 16))
for i0, i1, i2, i3, i4 in T.grid(1, 3, 5, 5, 16):
with T.block("compute"):
v_i0, v_i1, v_i2, v_i3, v_i4 = T.axis.remap("SSSSS", [i0, i1, i2, i3, i4])
B[v_i0, v_i1, v_i2, …
```
=> [TIR][Compute-at] Utilize InverseAffineIterMap for dom estimation

python/tvm/driver/tvmc/transform.py, tests/python/driver/tvmc/test_transform.py
this aims to make the `--desired-layout` argument more powerful based on the previously merged changes from #14010 (@srkreddy1238) by introducing two new features:
1. Allow passing multiple arguments to `--desired-layout` instead of only one, to specify one layout per transformed operator specified in `--desired-layout-ops`. (Number of arguments has to bei either 1 or match the number of transformed operators)
2. Optionally, you can now specify a non-default kernel layout as follows: `NHWC:HWIO`
Example Usage: `tvmc compile … --desired-layout nn.max_pool2d qnn.conv2d --desired-layout-ops NCHW NHWC:HWIO`
I also added unit tests for the new use-cases.
* It would make sense to specify individual kernel layouts for regular convolutions and depthwise ones. However since both are usually …
=> [TVMC] Improve --desired-layouts functionality

web/src/webgpu.ts
This PR specifies the maximum buffer size limit of WebGPU runtime explicitly so that the limit will not be a tight one by default.
In the future, we can analysis and detect the needed max buffer size limit and actively request the GPU.
Co-authored-by: Tianqi Chen <tianqi.tchen@gmail.com>
=> [Unity][Web] WebGPU explicit max buffer size

src/target/llvm/codegen_llvm.cc, tests/python/unittest/test_target_codegen_llvm.py
We're adding support to generate `llvm.assume` from `tir.assume` as we currently see an error when lowering code with tir.assume in certain cases.
=> [LLVM] Add support to generate llvm.assume

python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/conv2d_operation.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_gemm.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, tests/python/relax/test_codegen_cutlass.py
Residual block fusion for matmul is possible in a recent cutlass version. It is supported by `GemmUniversalWithBroadcast` API, see a usage example
https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_f16t_f16n_f16t_tensor_op_f16_broadcast_sm80.cu#L332-L367
This PR adds support for matmul + residual block fusion in the CUTLASS BYOC, by generating a `GemmUniversalWithBroadcast` kernel.
@vinx13 @yelite
=> [Unity][BYOC] Support matmul + residual block fusion in CUTLASS BYOC

python/tvm/script/parser/tir/parser.py, tests/python/unittest/test_tvmscript_syntax_sugar.py
When the TVMScript parser generates a `tir::LetStmt` to represent assignment to a variable, the name of the TVMScript variable should be used as the name of the `tir::Var` in the `tir::LetStmt`.
This bug was introduced in https://github.com/apache/tvm/pull/14207.
=> [Bugfix][TVMScript] Preserve variable names in LetStmt

docker/Dockerfile.ci_gpu
The last time we updated the CUDA version on CI was [two years ago](https://github.com/apache/tvm/pull/8119), I think it is a good time for another update.
v11.7 is the latest version officially supported by PyTorch (https://pytorch.org/get-started/locally/). Rather than jumping directly to v12, I think it is better to stay in the stable v11 line for now. 
This would unblock the PR https://github.com/apache/tvm/pull/14291 which uses a relatively new feature in cuBLAS introduced in v11.4.
=> [CI] Update CUDA to 11.7

src/arith/int_set.cc, tests/python/unittest/test_arith_intset.py
The UnionLowerBound function does not take into account the condition that  the empty set has a special representation [+inf, -inf].
cc @wrongtest-intellif
=> [Fix][TIR] Fix tvm::arith::UnionLowerBound

docs/contribute/release_process.rst
This updates the docs with some of the discussion and methods from
the v0.11.1 release issue #14260.
=> [docs] Add details about patch releases

apps/bundle_deploy/Makefile, tests/scripts/task_microtvm_cpp_tests.sh
This PR fixes https://github.com/apache/tvm/issues/13996.
=> [apps][bundle_deploy]Fix bundle build issue

src/runtime/aot_executor/aot_executor.cc, tests/python/relay/aot/test_cpp_aot.py
This PR fixes https://github.com/apache/tvm/issues/13013.
=> [AOT]Raise error when input name is not valid

include/tvm/relax/transform.h, python/tvm/contrib/cutlass/build.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/backend/pattern_registry.py, python/tvm/relax/backend/patterns.py, python/tvm/relax/transform/transform.py, src/relax/backend/pattern_registry.cc, src/relax/backend/pattern_registry.h, src/relax/transform/fuse_ops.cc, tests/python/relax/test_codegen_cutlass.py, tests/python/relax/test_transform_fuse_ops_by_pattern.py
This PR change the interface of the check function in FuseOpsByPattern, in order to make it possible to broader types of check during fusion. In particular,
1. The old check function signature is `bool(const Map<DFPattern, Expr>& match_result, const Expr& matched_expr)`, which isn't very useful because:
- The `Map<DFPattern, Expr> match_result` is hard to consume. To retrieve the wanted expr from this map, one has to either keep track of the DFPattern that matches the expr, or to iterate through the map values and filter by expr type.
- The `matched_expr` provides little help because one cannot traverse to other expressions from `matched_expr`, without the help from things like `var2val`.
2. The new signature is `bool(const PatternCheckContext&)`. A dedicated type `PatternCheckContext` is …
=> [Unity][BYOC] Improve expressiveness of the pattern check function in FuseOpsByPattern

python/tvm/tir/schedule/schedule.py, tests/python/unittest/test_tir_schedule_set_scope.py
Similar to other schedule primitives, allow the buffer argument to `Schedule.set_scope` to be passed as a human-readable name instead of a numeric index.  This change is solely in the Python API, and does not impact the internal representation of scheduling traces.
=> [TIR][Schedule] Allow buffer name argument to Schedule.set_scope

src/relax/analysis/tir_op_pattern_kind.cc, tests/python/relax/test_transform_rewrite_dataflow_reshape.py
This pr enhances the current RewriteDataflowReshape transformation.
Originally, it will use loop vars to prove the equality of addresses of LHS and RHS, which will cause some cases to fail due to the limitation of the arith module.
Instead, we can just use block vars to do the proof, which is supposed to be equivalent and the expressions are simpler, which allow us to cover more cases.
=> [Unity][Transform] Enhance RewriteDataflowReshape transform

include/tvm/topi/nn/group_norm.h, include/tvm/topi/nn/layer_norm.h, python/tvm/topi/nn/group_norm.py, python/tvm/topi/nn/layer_norm.py, python/tvm/topi/testing/group_norm_python.py, python/tvm/topi/testing/layer_norm_python.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/topi/python/test_topi_group_norm.py, tests/python/topi/python/test_topi_layer_norm.py
This pr modifies the topi implementation (which is also the legalizer's backend of Relax) of LayerNorm and GroupNorm operators to allow them to accept fp16 inputs, cast to fp32 internally, and produce fp16 outputs.
This can help eliminate unnecessary casts caused by AMP.
=> [Unity][TOPI] fp16 LayerNorm & GroupNorm

src/target/source/codegen_metal.cc, src/target/source/codegen_metal.h
Fix ramp node codegen for the metal backend.
The default C codegen can cause problem in
vector indices assignment.
=> [CODEGEN][METAL] Fix ramp codegen

include/tvm/tir/schedule/schedule.h, include/tvm/tir/schedule/state.h, python/tvm/tir/schedule/schedule.py, python/tvm/tir/schedule/state.py, src/tir/schedule/analysis/analysis.cc, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/primitive/for_kind.cc, src/tir/schedule/primitive/reduction.cc, src/tir/schedule/schedule.cc, src/tir/schedule/state.cc, src/tir/schedule/traced_schedule.cc
Currently, some of the schedule checks are too strict, which makes it hard to schedule some workloads such as FlashAttention whose reduction is two-stage and does not strictly follows our standard.
This PR adds an optional argument `disable_checks` which mutes some checks. The argument defaults to `False` and we can enable it whenever we want to disable some `soft` checks (by `soft` we mean if we violate such checks, the schedule is not necessarily invalid, and if we violate `hard` checks the schedule step is invalid).
In the future, we should collect the `soft` and `hard` checks for all schedule primitives. This PR serves for FlashAttention and only cares `bind` and some reduction primitives for now.
@spectrometerHBH @junrushao @Hzfengsy
=> [Schedule] Add an optional argument `disable_checks` for `Schedule`

include/tvm/relax/nested_msg.h, include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/op/image/resize.cc, src/relax/op/nn/convolution.cc, src/relax/op/nn/nn.cc, src/relax/op/nn/pooling.cc, src/relax/op/op_common.cc, src/relax/op/op_common.h, src/relax/op/tensor/binary.cc, src/relax/op/tensor/binary.h, src/relax/op/tensor/datatype.cc, src/relax/op/tensor/index.cc, src/relax/op/tensor/manipulate.cc, src/relax/op/tensor/statistical.cc, src/relax/op/tensor/statistical.h, src/relax/op/tensor/ternary.cc, src/relax/transform/convert_layout.cc, src/relax/transform/infer_layout_utils.cc, src/relax/transform/infer_layout_utils.h, src/relax/transform/utils.cc, src/relax/transform/utils.h, tests/python/relax/test_transform_convert_layout.py
This PR adds a new pass ConvertLayout that converts the layout of conv2d operators (NCHW->NHWC) and tries to propagate this conversion when appropriate.
see https://github.com/spectrometerHBH/tvm/blob/convert-layout/src/relax/transform/convert_layout.cc#L39 on how this pass works
It works on the op level, which is in parallel with the ongoing Layout Transformation effort that works on TIR level in the community.
=> [Unity][Transform] Automatic Layout Conversion

tests/python/unittest/test_target_codegen_metal.py
This PR adds a testcase that can be tested locally to cover metal ramp codegen
=> [METAL][CODEGEN] testcase for ramp codegen

src/relax/op/tensor/index.cc, tests/python/relax/test_op_index.py
In the case where the begin index of strided slice is out of [-ndim, dim), the strided slice operator will yield some incorrect shape inference. This PR corrected this issue by canonicalizing the begin and end index for strided slice and calculate the symbolic shape. Added some new unit tests for out of range begin locations and changed some symbolic shape tests.
I have 2 questions that we can follow up in the design:
1. Is it expected that in the case of symbolic shape input tensor we should have symbolic shape inferenced for generated tensors after strided slice? See unit test change for details, when we have different input shape at runtime we may have corresponding symbolic output shape.
2. We do have the similar function / logic in topi strided slice implementation. Should we unify …
=> [Unity][Op] Fix Strided Slice Shape Inference

include/tvm/relax/transform.h, python/tvm/relax/analysis/analysis.py, python/tvm/relax/binding_rewrite.py, python/tvm/relax/transform/transform.py, src/relax/transform/dead_code_elimination.cc, tests/python/relax/test_transform_dead_code_elimination.py
As a follow-up to https://github.com/apache/tvm/pull/14262, I just noticed that I previously implemented a function called `RemoveAllUnused` (https://github.com/apache/tvm/pull/14043) that can do function-wise DCE and should be more complete than https://github.com/apache/tvm/pull/14262 as `RemoveAllUnused` can also remove dead dataflow blocks (added two test-cases to show that). 
Sorry, I should have mentioned that earlier to avoid duplication... but still I am putting a patch here in case it is desired.
cc: @spectrometerHBH @tqchen
=> [Unity][Pass] Reuse prior infra to implement more complete DCE

src/target/source/codegen_c.cc, src/target/source/codegen_metal.cc, src/target/source/codegen_metal.h, src/target/source/codegen_opencl.cc, src/target/source/codegen_opencl.h, tests/python/unittest/test_target_codegen_metal.py
This PR fixes the implementation of unaligned vector load. Previously vector construction was printed as (float2)(v0, v1). This will cause problem as C have comma expression, and (v0, v1) will be evaluated as v1. The final result will become float2(v1, v1). The bug affects all codegen that uses the default implementation, such as metal. We added a testcase on metal to cover this case.
=> [CODEGEN][METAL] Fix unaligned vector load

python/tvm/relax/transform/transform.py, src/relax/transform/alter_op_impl.cc, src/relax/transform/to_mixed_precision.cc
The pass RemoveUnusedFunctions was renamed and enhanced to the DCE pass in #14262. This PR removes the Python interface of RemoveUnusedFunctions in transform.py.
It is surprising that this Python API was never tested in any testing file before.
This PR also fixes `alter_op_impl.cc` and `to_mixed_precision.cc` to for Clang build warnings.
=> [Unity] Remove Python interface of RemoveUnusedFunction

python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_from_fx.py
* Add the support of `exp` for the FX translator.
* Previously the way FX translator dealt with `None` in torch tensor slice (e.g., `x[:, None, None]`) is not right. This PR fixes this issue. Specifically, the `None` here means dim expansion, and the previous impl mistakenly increases the dim counter when seeing `None`, which will lead to dim counter out-of-range issue in the end.
=> [Unity][Frontend] FX exp and strided_slice fix

docs/install/from_source.rst
Update the list of python packages required to run a `tvmc` invocation after building TVM from source.
=> [Docs] Update listed tvmc python dependencies

src/tir/transforms/lower_tvm_builtin.cc, tests/python/unittest/test_tir_transform_lower_tvm_builtin.py
This PR fixes the issue of overflow when calculating the size of buffer using product of loop extents. In certain cases it could overflow to a negative number and fail to compile. Unit test is also attached.
Co-authored with Sunghyun Park <<spark@octoml.ai>>
CC: @sunggg @jwfromm @tqchen
=> [TIR] Fix Datatype in Lower TVM Builtin

python/tvm/relax/frontend/torch/dynamo.py, tests/python/relax/test_frontend_dynamo.py
This PR enables user to pass the torch model's kwargs of forward function to dynamo_capture_subgraph, which makes it more flexible. 
cc: @spectrometerHBH
=> [Unity] Support model kwargs in dynamo_capture_subgraph

docker/Dockerfile.ci_lint
Goes to the latest revision in the same major version (22.12.0). 
23.1.0 is released but it involves some style changes so we would need to reformat the entire codebase. 
I need 22.12.0 to properly deal with processing some files found in this PR: 
https://github.com/apache/tvm/pull/14167
Where black cannot parse the file in the current version, but can in the updated version.
=> [CI][Lint] Update black

include/tvm/relax/transform.h, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/transform/transform.py, src/relax/transform/fuse_ops.cc, tests/python/relax/test_codegen_cutlass.py
This PR adds new check logic to the BYOC patterns for cutlass, to ensure intermediate variables in the fused region aren't used outside.
For example, 
```python
@R.function
def main(x: R.Tensor((128, 128), "float16"), w: R.Tensor((128, 128), "float16")):
lv = R.matmul(x, w)
lv1 = R.power(lv, R.const(2.0, "float16"))
lv2 = R.add(lv, lv1)
R.output(lv2)
return lv2
```
Without the new check logic, this function would be fused as biased matmul, which isn't correct because the bias (`lv1`) depends on the result of matmul.
=> [Unity][BYOC] Check leaked intermediate variables in cutlass patterns

python/tvm/tir/schedule/analysis.py, src/tir/schedule/analysis/analysis.cc, tests/python/unittest/test_tir_schedule_analysis.py
This patch just exposes an existing analysis API `IsOutputBlock` to python. Since many schedule primitives have conditions on output blocks, this API would be really useful while scheduling
=> [TIR] [Analysis] Expose IsOutputBlock to python

src/relax/transform/static_plan_block_memory.cc, tests/python/relax/test_transform_static_plan_block_memory.py
This PR fixes the size calculation of storage tokens in Static Plan Block Memory pass. Prior to this PR the storage for a tensor  `R.Tensor((2, 3), dtype="bool")` would be calculated as `R.memory.alloc_storage(R.shape([1]), dtype="bool")` instead of `R.memory.alloc_storage(R.shape([6]), dtype="bool")`
cc @jwfromm @MasterJH5574
=> [Unity][Fix] Fix block memory plan to handle bool

src/relay/ir/dataflow_matcher.cc, tests/python/relay/test_dataflow_pattern.py
The `rewrite_once` of the current `PatternRewriter`  rewrites once only when the last callback in the callbacks list is `rewrite_once`. I don't think this is as expected.   
I think the `rewrite_once` strategy should be that the callback marked with `rewrite_once` is rewritten only once, and the rest of the callbacks are still rewritten multiple times.
=> [BugFix] Support rewrite_once when the number of callbacks > 1

python/tvm/relax/testing/relay_translator.py, tests/python/relax/test_relay_translator.py
This PR adds an argument to the relay to relax translator to append the relay Op Attrs as function attributes to the generated TIR PrimFuncs
This information is really useful in Relax as the absence of this prevents us from being able schedule efficiently for ops that are heavily sensitive to the attributes.
For example, the `groups` attribute to `conv2d` op is needed to differentiate between regular conv2d and depthwise conv2d.
=> [Unity] Add support to append relay op attrs in translator

python/tvm/contrib/hexagon/build.py, python/tvm/contrib/hexagon/session.py, python/tvm/contrib/hexagon/tools.py
**Short desc**
This changes allow my to compile and tune models for hexagon directly from my macOS laptop without full switching to linux environment.
**List of changes**
* Replace local linker call with call from docker container with Hexagon SDK. Yes, that is the only SDK tool used by TVM during compilation.
* Enhanced search of ADB. Not only in PATH, but also in ANDROID_HOME, ANDROID_SDK_ROOT and default sdk installation directory. Mac OS doesn't allow to easily change default PATH env var for UI application launched from dock bar. So adb is not available for IDE by default.
**Motivation**
Some engineers would like to continue work with comfortable macOS environment even if they have to play with hexagon devices. At this moment there is no official Hexagon SDK for macOS system. …
=> Hexagon compilation on MacOS system

src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops.py
This PR is to fix the FuseOps error if there is no output of a given group, although the pass `DeadCodeElimination` can solve the problem, it is better to enhance the robustness of the pass `FuseOps`.
reported by @jinhongyii
=> [Unity][Pass] Fix FuseOps error if there is no output of a given group

src/relax/op/tensor/statistical.cc, tests/python/relax/test_transform_convert_layout.py
This PR fixes a bug in Infer Layout for reduction ops in when `axis` has negative indices.
cc @jwfromm @spectrometerHBH
=> [Unity][Fix] Infer Layout must support negative axes

ci/jenkins/docker-images.ini, src/target/target_kind.cc, tests/python/frontend/tensorflow/test_forward.py, tests/scripts/request_hook/request_hook.py
Following the docker file update in https://github.com/apache/tvm/pull/14293, I'm doing the actual image update.
Validated in https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-gpu/detail/ci-docker-staging/10/pipeline
=> [CI] Update GPU image for CUDA 11.7 

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/block_annotate.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, src/tir/schedule/transform.cc, src/tir/schedule/transform.h, tests/python/unittest/test_tir_schedule_set_dtype.py
Currently, we miss a schedule primitive to change the data type of allocated buffer (e.g. via `cache_read`/`cache_write`), and thus we cannot perform type conversion while loading data from global to shared memory.
This PR adds a new schedule primitive `set_dtype` that follows the interface of `set_scope` and allows users to customize the allocated buffers' data type.
Before running `set_dtype`:
```python
@T.prim_func
def before_set_dtype(
A: T.Buffer((128, 128), "float32"), C: T.Buffer((128, 128), "float32")
) -> None:
B = T.alloc_buffer((128, 128), dtype="float32")
for i, j in T.grid(128, 128):
with T.block("B"):
vi, vj = T.axis.remap("SS", [i, j])
B[vi, vj] = A[vi, vj] * 2.0
for i, j in T.grid(128, 128):
vi, vj = T.axis.remap("SS", [i, j]
C[vi, vj] = B[vi, vj] + 1.0 …
```
=> [TensorIR] New schedule primitive `set_dtype`

src/script/ir_builder/ir/ir.cc, tests/python/relax/test_tvmscript_parser.py
The current GlobalVar generated by `emit_te` has empty `checked_type_`, which will fail at the well-formed check, saying
```
Warning: This IR is not well formed: The checked_type_ of Expr I.GlobalVar("add") is nullptr.
```
This PR fixes this issue and enables well-formed checks in parser tests.
cc @yongwww
=> [Unity][TVMScript] Update GlobalVar `checked_type_` when `emit_te`

src/relax/transform/infer_layout_utils.cc, tests/python/relax/test_transform_convert_layout.py
Fix assert to allow scalar (ndim=0) layout initialization.
cc @jwfromm @spectrometerHBH
=> [Unity][Fix] Allow scalar layout initialization

python/tvm/contrib/cutlass/gen_tensor_op.py
Fixes a bug where this stacktrace is generated:
```
File "/opt/scorecard/relax/python/tvm/contrib/cutlass/gen_tensor_op.py", line 189, in generate_sm75_tensor_op_1688
return generate_sm50_simt(
File "/opt/scorecard/relax/python/tvm/contrib/cutlass/gen_tensor_op.py", line 119, in generate_sm50_simt
return generate_tensor_op_common(
File "/opt/scorecard/relax/python/tvm/contrib/cutlass/gen_tensor_op.py", line 71, in generate_tensor_op_common
out = op_creator(tile_descriptions, data_type, alignment_constraints)
File "/opt/scorecard/relax/python/tvm/contrib/cutlass/gen_gemm.py", line 151, in enumerate_gemm_operators
op.procedural_name(),
File "/opt/scorecard/relax/python/tvm/contrib/cutlass/gemm_operation.py", line 110, in procedural_name
opcode_class_name = …
```
=> [Unity] Also include output dtype in simt MathInstruction

cmake/modules/CUDA.cmake, src/runtime/relax_vm/cuda/cuda_graph_builtin.cc, tests/python/relax/test_vm_cuda_graph.py
This PR added Relax VM builtin functions to execute with CUDA graph.
* `vm.builtin.cuda_graph.get_cached_alloc`: Allocate and cache storage objects for future vm invocation
* `vm.builtin.cuda_graph.run_or_capture`: Launched captured CUDA graph or capture the CUDA graph using CUDA API and save in the cache
The graph rewriting to enable CUDA graph backend will be done in a separate PR.
cc @tqchen @spectrometerHBH @MasterJH5574
=> [Unity][VM] Add CUDA graph vm builtins

src/runtime/hexagon/hexagon_device_api.cc, tests/cpp-runtime/hexagon/hexagon_device_api_tests.cc
Update assert during buffer allocation.  Zero dimensional tensors (scalars) can have a null shape.
cc: @csullivan, @farshidsp
=> [Hexagon] Allow scalar tensors to have null shape during allocation

tests/cpp/nested_msg_test.cc
The file tests/cpp/nested_msg_test.cc may fail to compile if <array> is not included explicitly.
=> [Unity] Add missing #include <array>

src/tir/transforms/inject_software_pipeline.cc
Updated the error message to state which PrimFunc has a malformed pipeline annotation, the blocks found in that primfunc, and the pipeline annotation found.
=> [TIR] Improved error message in InjectSoftwarePipeline

src/tir/transforms/make_packed_api.cc
If a variable is undefined within a PrimFunc, included the name of the PrimFunc in the error message.  Otherwise, in a IRModule with multiple functions, it may be unclear which PrimFunc is malformed.
=> [TIR] Improved MakePackedAPI error message

src/tir/analysis/estimate_flops.cc, tests/python/unittest/test_tir_analysis_estimate_tir_flops.py
FlopEstimator is run as part of the Meta Schedule as an estimate for which primfunc to spend time on; e.g. which primfunc to send more trials on.  In a case that the for loop extent is an expression, it’s getting stuck on the calculation of the FLOPS.
This PR add a function annotation to the main primfunc and then have FlopEstimator check for this annotation before visiting the function. And if the annotation exists, just use the handcoded flops instead of trying to estimate.
@Lunderberg  @csullivan
=> [TIR] not estimating the flops when there is a default estimated flops as attr

include/tvm/relax/tir_pattern.h, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/relax/backend_tir/__init__.py, python/tvm/relax/backend_tir/contrib/__init__.py, python/tvm/relax/backend_tir/contrib/cutlass.py, python/tvm/relax/backend_tir/pattern.py, python/tvm/relax/transform/transform.py, src/relax/backend/vm/codegen_vm.cc, src/relax/ir/tir_pattern.cc, src/relax/transform/split_call_tir_by_pattern.cc, tests/python/relax/test_codegen_tir_cutlass.py
Currently, the BYOC system is based on op-level pattern matching, this PR intends to provide primary support for TIR-level pattern matching based on backend registration and dispatching.
For now, it simply matches the first set of for loops in PrimFunc.
Co-authored-by: Hongyi Jin (@jinhongyii)
=> [Unity][Transform] SplitCallTIRByPattern and CUTLASS backend

conda/recipe/bld.bat, conda/recipe/build.sh
Enable USE_MICRO for mac and windows CI builds to ensure code building doesn't break for those platforms;
=> [CI][microTVM] Enable USE_MICRO for mac and windows CI builds

src/relax/analysis/well_formed.cc, src/relax/ir/expr_functor.cc, src/relax/transform/fuse_ops.cc, src/runtime/relax_vm/cuda/cuda_graph_builtin.cc, tests/python/relax/test_analysis_well_formed.py, tests/python/relax/test_transform_fuse_ops.py
This PR adds support for simple dynamic-shape-aware fusion, which is the first step towards supporting dynamic shapes. The main changes are as follows:
- Fix FuncStructInfo in well-formed checks
- Renew symbolic var defs in fuse_ops to prevent malformed functions
cc @tqchen @MasterJH5574 @jinhongyii
=> [Unity] Support simple dynamic-shape-aware fusion

python/tvm/script/parser/relax/entry.py, tests/python/relax/test_tvmscript_parser.py
Currently the script reports error
```
@I.ir_module
class Module:
@R.function
def main_adjoint(x: R.Tensor((3, 4), dtype="float32")):
s: R.Shape([3, 2, 2]) = R.shape([3, 2, 2])
lv: R.Tensor(s, dtype="float32") = R.reshape(x, s)
return lv
```
because the relax parser cannot handle Var with ShapeExpr value occuring in R.Tensor annotations.
This PR specifically checks such cases in parser.
Thanks to the observation from @SiriusNEO 
cc @Hzfengsy @tqchen
=> [Unity][TVMScript] Fix Shape Var occurrence in Tensor annotation

python/tvm/topi/hexagon/tensor_intrin.py, tests/python/contrib/test_hexagon/test_fixed_point_multiply.py
Goal is to allow to apply intrinsics "q_multiply_shift" and "q_multiply_shift_per_axis" for vector type i32x128. Originally it supports only "i32x32" which is natively supported by platform (1024 bit vector).
**Motivation** 
There are situation than we have to use vector size slightly more than supported by platform. As example consider sequence of element-wise operators: add<i32> -> q_multiply_shift<i32> -> cast<i8>. To achieve performance we have to squash it into one single loop (`sch.compute_at(...)`). First two operators would like to be vectorised with using data type "int32x32". last one cast operator want to use i32x128 as src and i8x128 as dst. As result we have to adapt all this operator to accept vector size "??x128" to successfully vectorise entire loop.
This change allows to …
=> [Hexagon] Adapt some intrinsics for high vector lanes

python/tvm/driver/tvmc/compiler.py, python/tvm/relay/analysis/operations_distribution.py, python/tvm/relay/transform/suffixes.py, src/relay/backend/contrib/cmsisnn/extract_constants.cc, src/relay/backend/contrib/cmsisnn/fuse_pads.cc, src/relay/backend/contrib/cmsisnn/generate_constants.cc, src/relay/backend/contrib/cmsisnn/scalar_to_tensor_constant.cc, src/relay/transforms/annotate_target.cc, tests/python/contrib/test_ethosu/infra.py, tests/python/contrib/test_ethosu/test_pass_operations_distribution.py, tests/python/driver/tvmc/test_compiler.py
Added an option to tvmc and Ethos-U for printing to console or to the file which operators from the initial graph are offloaded to Ethos-U and which aren't. It forms line-by-line output of initial model IR, indicating which operations ported to Ethos-U.
Compiler option "--target-ethos-u-dump_npu_functions_coverage" has been replaced by more generic "--dump-offloads" with the same meaning.
```
tvmc compile --target=ethos-u,cmsis-nn,c \
--dump-offloads=- \
........
tvmc compile --target=ethos-u,cmsis-nn,c \
--dump-offloads=<file path> \
........
```
...
Total number of operators and distribution by targets
Total: 211
target1: 198
target2: 10
generic: 3
'target1        <-     target2.qnn_conv2d'
'target1        <-          %0 = qnn.conv2d(%tfl.quantize, %v_param_1, ...'
'target1        <- …
=> [TVMC][microNPU] tvmc option for printing which operators are offloaded to Ethos-U

include/tvm/relax/attrs/nn.h, python/tvm/relax/frontend/torch/fx_translator.py, python/tvm/relax/op/nn/nn.py, python/tvm/relax/transform/legalize_ops/nn.py, src/relax/op/nn/convolution.cc, src/relax/op/nn/convolution.h, src/relax/op/op_common.h, tests/python/relax/test_frontend_from_fx.py, tests/python/relax/test_op_nn_convolution.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/relax/test_tvmscript_parser_op_nn.py
This PR implements `Conv1d`.
Unit tests are provided accordingly.
=> [Unity][Op] Conv1d

python/tvm/contrib/cutlass/build.py
This PR fixed the bug that when shapes are int64 integers, cutlass BYOC doesn't correctly stringify the shapes and the profiler can't get any valid profile results.
cc @masahi
=> [Unity] Fix getting shapes for cutlass BYOC kernels

src/meta_schedule/postproc/rewrite_parallel_vectorize_unroll.cc, tests/python/unittest/test_meta_schedule_postproc_rewrite_parallel_vectorize_unroll.py
**Motivation:**
It was found that for standalone elementwise operations (add, sub, etc.) MetaScheduler generates code with poor performance due to lack of vector code on some input tensor shapes. Current implementation is not able to vectorize if innermost loops extent is not multiple of the vector length.
**What was done:**
Core changes: it checks current loops nest, if all loops are "simple", i.e. loops without annotations, bindings, reduce axis, then it does the following:
1) Fuse all loops into single one.
2) Split this new loop into 2 parts: inner and outer. Herewith split factor for the inner loop is equal to '_max_vectorize_extent_' MetaScheduler parameter.
3) Parallelize outer loop and vectorize inner loop.
**Performance measurement**:
Measurement was done on Qualcomm Snapdragon …
=> [MetaSchedule][Hexagon] Improve vectorization for standalone elementwise op

python/tvm/contrib/hexagon/session.py, python/tvm/runtime/module.py, src/runtime/hexagon/hexagon_module.h, tests/python/contrib/test_hexagon/test_relax_integration.py
This is attempt to port missed parts of [PR#167](https://github.com/tlc-pack/relax/pull/167) (submitted by @psrivas2 and @YuchenJin) from tlc-pack/relax to enable Hexagon tests with Relax VM.
=> [Unity] Enable Relax VM for Hexagon

src/script/ir_builder/tir/utils.h
Previously, the error messasge from `FindPrimFuncFrame`, `FindBlockFrame`, and `FindIfFrame` stated that they could not find the requested frame when the top-most frame did not match the requested type.  This error message could be misinterpreted by a user as stating that the frame didn't exist at all.
This commit updates the error message to distinguish between the case of a missing frame (e.g. `T.reads()` occurring outside of any `T.block()` frame) and a frame not being top-most (e.g. `T.reads()` occurring inside a `T.block()`, but inside an `if` conditional instead of the top of the block).
=> [TVMScript] Improved error message for unexpected top frame

src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_fuse_tir.py
This fixes a bug in FuseTIR where module attributes were dropped in the transformation.
cc: @jwfromm @sunggg
=> [Unity][Fix] Copy over module attrs in FuseTIR

src/relax/transform/static_plan_block_memory.cc, tests/python/relax/test_transform_static_plan_block_memory.py
Handling of external func calls in memory planning was missing before, which disabled memory planning for all BYOC use cases. This PR added handling for external func calls, it assumes external func calls via `call_packed` doesn't retain memory.
cc @MasterJH5574 @tqchen
=> [Unity] Handle extern func calls in static memory planning

gallery/how_to/work_with_microtvm/micro_tvmc.sh, tests/micro/arduino/test_utils.py, tests/micro/common/test_autotune.py, tests/micro/common/test_tvmc.py, tests/scripts/request_hook/request_hook.py
Model magic_wand was replaced by model micro_speech since model magic_wand was removed in the [commit](https://github.com/tensorflow/tflite-micro/commit/bef8fe8bc6183cc4e1ce852579abcb7a171f8a5c). Also added commit's sha to the link to avoid this issue in the future.
cc @mehrdadh
=> [skip ci] Replace magic_wand model with micro_speech

python/tvm/relay/frontend/pytorch.py
Fixed a bug in `_get_pytorch_value_type()`: `kind` should be used to determine if it is an `OptionalType`, instead of `pt_dtype`
=> [relay][frontend][pytorch]Fix a bug in the _get_pytorch_value_type function

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Add a missing importer for quantized softmax.
=> [Frontend] Add ONNX importer for QLinearSoftmax

src/target/source/codegen_opencl.cc, src/target/source/codegen_opencl.h, tests/python/relay/opencl_texture/test_injection_texture.py, tests/python/unittest/test_target_codegen_opencl.py, tests/python/unittest/test_target_texture_codegen_opencl.py
In some cases we must use SSA for textures loading but we didn't do
that. Example of such cases:
1. Storing texture (NCHW4c) directly (w/o temporary buffer) to the
output buffer (NCHW). In this case we have to use SSA because we
need to get only one channel from the pixel. In case of storing to
the local buffer the SSA was used because the buffer was allocated
in kernel and the logic was written that if the buffer was allocated
then we should use SSA. But if we store the same texture directly to
the output buffer then SSA wasn't used and this OpenCL code wasn't
compiled.
2. Casting texture (NCHW4c) to another data type and then storing it to
the buffer (NCHW). The SSA for textures was disabled in case of cast
operation. As a result it was necessary to take a channel from the
pixel but we …
=> [OpenCL][Textures] Always use SSA for texture loading 

src/tir/transforms/storage_rewrite.cc, tests/python/unittest/test_tir_transform_storage_rewrite.py
The use case for this no longer exists, as loads and stores are no longer tracked separately. This special-casing can also introduce bugs when calling external microkernels.
This resolves #13976.
cc: @tqchen @kparzysz-quic @csullivan
=> [TIR] Remove special-casing of T.address_of in the storage rewrite pass

src/tir/transforms/lower_tvm_builtin.cc
The member variables `device_type_` and `device_id_` are tracked during `LowerTVMBuiltin`, are initially undefined, and are checked before use.  This is the usage pattern expected for `Optional<T>`, but these variables previously had the type `PrimExpr`.
This commit updates these to `Optional<PrimExpr>`, and uses the helper function `GetDeviceMethodName` to add more detail to the error messages when they are undefined.
=> [TIR] Update LowerTVMBuiltin to use Optional<T>

gallery/tutorial/tvmc_command_line_driver.py, python/tvm/driver/tvmc/autotuner.py, tests/python/driver/tvmc/test_autotuner.py
This adds a `--tasks` flag to the `tvmc tune` command to filter the lists of tasks to be tuned. See examples below.
- As auto-tuning can be quite time consuming, it is often desirable to cut down the number of tuned tasks in a session.
- If the tuning session was canceled halfway through, it would be a bad idea to start from scratch. Instead continue with the last untuned task
- Some tasks have more impact on the model performance than others, thus we should be able to train some tasks longer than others
1. Use `--task list` to show which tasks are available for tuning
```
$ tvmc tune toycar.tflite -o out.txt --task list
Available Tasks for tuning:
0. Task(func_name=dense_nopack.x86, args=(('TENSOR', (1, 640), 'int16'), ('TENSOR', (128, 640), 'int...
1. Task(func_name=dense_pack.x86, …
```
=> [TVMC] Allow selecting a subset of tasks to be used in `tvmc tune`

include/tvm/relax/binding_rewrite.h, python/tvm/relax/__init__.py, src/relax/ir/binding_rewrite.cc
* `relax/binding_rewrite.py` is not imported by default, so we get errors like `AttributeError: <class 'tvm.runtime.object.Object'> has no attribute add` if we try to pass the C++ object to python
* `DataflowBlock` member variable shouldn't be optional, but it is declared with `Optional<DataflowBlock> dfb_` and accessed via `dfb_.value()` all over the places.
* `root_fn_` **should** be optional (e.g. when `DataFlowBlockRewrite` is used inside another `ExprMutator`) , but it's always updated via `root_fn_.value()` without checking   
* Other minor style updates that hopefully improve readability.
@ganler @tqchen
=> [Unity] Minor updates to DataFlowBlockRewrite

include/tvm/relax/dataflow_pattern.h, src/relax/ir/dataflow_matcher.cc, tests/python/relax/test_dataflow_pattern.py
Graph pattern matching uses `std::map` and `std::set` keyed on pointers, which leads to non-deterministic matching result. This PR removed all non-determinism. 
For example, consider matching against QKV projection before attention. Given a sequence of bindings,
```
lv0 = R.matmul(x, w0)
lv1 = R.matmul(x, w1)
lv2 = R.matmul(x, w2)
...
```
and patterns,
```
with PatternContext() as ctx:
inp_pat = wildcard()
Q_weight_pat = wildcard()
K_weight_pat = wildcard()
V_weight_pat = wildcard()
matmul1 = is_op("relax.matmul")(inp_pat, Q_weight_pat)
matmul2 = is_op("relax.matmul")(inp_pat, K_weight_pat)
matmul3 = is_op("relax.matmul")(inp_pat, V_weight_pat)
```
intuitively I expect the following matching result:
```
Q_weight_pat - w0
K_weight_pat - w1
V_weight_pat - w2
```
But since …
=> [Unity] Remove non-deterministic behavior from graph pattern matching 

src/target/llvm/codegen_hexagon.cc
Ported from Unity PR - https://github.com/apache/tvm/pull/14378/
Updating the codegen for Hexagon call from llvm::DataLayout::getTypeSizeInBits.getFixedSize() to llvm::DataLayout::getTypeSizeInBits.getFixedValue().  This fails in the unity branch because the deprecated warning is an error.
cc: @masahi
=> [Hexagon] Fix deprecated call for data layout size in bits

include/tvm/relax/dataflow_matcher.h, include/tvm/relax/dataflow_pattern.h, python/tvm/relax/dpl/pattern.py, src/relax/ir/dataflow_pattern.cc, tests/python/relax/test_dataflow_pattern.py
Compared to the typical, structural matching (e.g. matching `is_op` based pattern against `CallNode`), graph pattern matching requires additionally specifying `used_by` constraints. This leads to an obvious redundancy in the usage:
```
matmul1 = is_op("relax.matmul")(inp_pat, Q_weight_pat)
matmul2 = is_op("relax.matmul")(inp_pat, K_weight_pat)
matmul3 = is_op("relax.matmul")(inp_pat, V_weight_pat)
inp_pat.used_by(matmul1, 0)
inp_pat.used_by(matmul2, 0)
inp_pat.used_by(matmul3, 0)
Q_weight_pat.only_used_by(matmul1, 1)
K_weight_pat.only_used_by(matmul2, 1)
V_weight_pat.only_used_by(matmul3, 1)
``` 
This PR hacks `is_op` constructor by automatically adding such `used_by` constraints between caller and callee patterns. See the simplified test case for QOL improvement.
@ganler @sunggg
=> [Unity][Graph matching] Automatically add `used-by` constraints for `is_op` pattern

include/tvm/meta_schedule/schedule_rule.h, include/tvm/runtime/container/array.h, python/tvm/tir/tensor_intrin/arm_cpu.py, src/meta_schedule/schedule_rule/schedule_rule.cc, src/meta_schedule/space_generator/space_generator.cc, tests/python/unittest/test_meta_schedule_post_order_apply.py
Motivation:
The purpose of this PR is to add support for intrinsics to optimize matrix multiplication operations (e.g. matmul, convolution) during tuning with MetaScheduler.
Information about PR:
The present PR integrates the existing neon and dotprod (namely, sdot and udot) ARM CPU intrinsics into MetaScheduler, introduces a new "hybrid" dotprod intrinsic ("hdot") working with uint8, uint8 -> int32 data types, and changes the intrinsic selection and application processes for the ARM CPU case, since we operate with multiple intrinsics, rather than with a specific one.
=> [MetaSchedule][ARM] Enable ARM CPU intrinsic for MetaSchedule

include/tvm/relax/dataflow_matcher.h, src/relax/analysis/udchain.cc, src/relax/ir/dataflow_matcher.cc, tests/python/relax/test_dataflow_pattern.py
This is a fix for the issue described in https://github.com/apache/tvm/pull/14417#issuecomment-1490049917
In graph pattern matching, backtracking behavior is implemented by undoing matchings in `undo_stack`. When an intermediate fails to match, `undo_stack`s for parent and child nodes that have matched tentatively also need to be cleaned up as well. This corner-case handling is missing in the current implementation. 
The fix is to return `undo_stack` from recursive `try_match` calls when matching succeeds, and merge parent / child `undo_stack` with the `undo_stack` for the "current" node
@ganler @sunggg @cyx-6
=> [Unity][Graph matching] Clean up undo stack for parent and child nodes properly

src/relay/transforms/fold_explicit_padding.cc
In SimplifyExplicitPad, the pad_value pointer was dereferenced before checking if it's null or not. Move the dereference to past the check.
=> [Relay] Move pad value extraction past null pointer check

python/tvm/relax/dpl/__init__.py, python/tvm/relax/dpl/pattern.py, python/tvm/relax/dpl/rewrite.py, src/relax/ir/dataflow_matcher.cc, tests/python/relax/test_dataflow_pattern.py
Compared to the existing call node based matching & rewriting that requires a common post-dominator in a pattern (introduced in https://github.com/apache/tvm/pull/14312), it lets us match a tree structure and replace leaf nodes or branches with new expression.
This can be immediately used for combining any number of multiple matmuls sharing the same LHS into one matmul. In Relay, we have a dedicated pass for that purpose (`CombineParallelDense`), but we can achieve the same thing via graph (tree) matching and rewrite. 
For example, in SD UNet we have many three parallel matmul for QKV projections. In addition, there are also highly non-obvious parallel matmuls consisting of 32 or 22 of them. Those patterns can all be matched and rewritten via the following generic pattern and rewriter. …
=> [Unity] Pattern-based rewriting for dataflow block

src/script/printer/doc_printer/python_doc_printer.cc, tests/python/relax/test_tvmscript_parser.py
This PR fixes a bug in TVMScript printer handling tuples on the RHS of an assignment, i.e.:
```python
... = (a, b, c)
^^^^^^^^^
```
The existing  sugar removes the brackets surrounding `(a, b, c)`, which makes it slightly more readable as:
```python
... = a, b, c
```
However, it overlooks a possibility where the tuple could be empty or has only one element, i.e.
```python
... = (a, ) // Case 1: The tuple has only one element
... = ()    // Case 2: The tuple is empty
```
In both cases, removing brackets may lead to wrong outcome.
This patch fixes this bug.
=> [TVMScript][Bugfix] Tuple on the RHS of AssignDoc

python/tvm/topi/x86/conv2d.py, tests/python/relay/test_any.py
make w and h of conv2d to support dynamic on x86
=> [TOPI] dynamic externsion

python/tvm/relay/frontend/oneflow.py
=> [Frontend][Oneflow] Use FLOW_2_STR_DTYPE for dtype

src/relax/backend/contrib/cutlass/codegen.cc
This PR improves cutlass compilation time, by compiling a single CSourceModule instead of creating and compiling one for each kernel.
Creating and compiling a new CSourceModule for every function is quite slow and slows down model with multiple functions offloaded to cutlass quite significantly. Instead we can generate a single CSourceModule and compile it once to produce a single `runtime::Module`.
This brings down the cutlass compilation time of large models like SD Unet significantly (~30 min to ~4 min). Similar results on other large models.
`tests/python/relax/test_codegen_cutlass.py::test_matmul_offload` is broken at HEAD. This PR passes on all other tests when tested locally.
cc @masahi @vinx13
=> [Unity][BYOC] Faster cutlass codegen

python/tvm/topi/hexagon/utils.py
- This is needed to reuse index_map functions passed to `transform_layout` in TIR
=> [Hexagon][TOPI] Use IndexMap axis separator instead of TE

ci/jenkins/unity_jenkinsfile.groovy
I tried to update the GPU image for unity CI in https://github.com/apache/tvm/pull/14291 but it doesn't seem to be working. Trying sending the change from `apache` and also including the recent `lint` image update https://github.com/apache/tvm/pull/14373. Not sure if this is the correct protocol for updating CI images for unity.
@tqchen @driazati
=> [Unity][CI] Update gpu and lint image

src/relax/transform/run_codegen.cc
BYOC tests using symbolic shapes have been broken since https://github.com/apache/tvm/pull/14396. A BYOC function's return `sinfo` refers to a sym var defined inside that function. When a call to that is replaced by an opaque `call_dps_packed`, we cannot use `func->ret_struct_info` anymore since it refers to a sym var that's gone. 
It's more mysterious why `RunCodegen` on symbolic shape had been working before 14396... Perhaps `main` happens to define the same-named sym var, which happens to capture the undefined variable in `func->ret_struct_info`. Perhaps that is exactly what https://github.com/apache/tvm/pull/14396 prevents. 
The failing cutlass test is now working but it is not tested on CI. Cublas tests will be added in https://github.com/apache/tvm/pull/14291 which run on CI. We …
=> [Unity][BYOC] Fix `RunCodegen` pass on symbolic shape

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/loop_transformation.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_merge.py
During NPU schedule, we usually encounter multiple out graphs and need do loop partition on each out then compute at other block to the different out block. But current "compute_at" primitive can't handle it.
This PR add "merge" schedule primitive to merge different loops, when cut same tiles on different out blocks by "split" primitive, we can merge these out block under an outer loop, then other blocks can "compute_at" this loop normally.
cc @Hzfengsy @wrongtest-intellif
=> [TIR] Add merge primitive for TIR schedule

python/tvm/topi/testing/poolnd_python.py
Some versions of numpy disallow the following:
```
>>> import numpy as np
>>> a = np.zeros(10)
>>> b = [slice(None)]
>>> a[b]
File "<stdin>", line 1, in <module>
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
When b is a tuple, it works fine:
```
>>> a[tuple(b)]
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```
=> [testing] Use tuples for numpy indexing

tests/python/driver/tvmc/conftest.py, tests/scripts/request_hook/request_hook.py
The path to the `cnn_s_quantized.tflite` model used in some TVMC tests was changed in https://github.com/ARM-software/ML-zoo/pull/56. The link has been updated with the new path.
=> [CI] Fix broken model link

include/tvm/relay/attrs/nn.h, python/tvm/relay/frontend/keras.py, python/tvm/relay/frontend/mxnet.py, python/tvm/relay/frontend/pytorch.py, python/tvm/relay/op/nn/nn.py, src/relay/op/nn/convolution.cc
Here is the similar issue with Conv3Dtranspose #14340. Sending a PR to fix this.
cc. @masahi
=> [Bugfix] Conv1Dtranspose default kernel layout should be IOW

src/runtime/relax_vm/attention_kv_cache.cc, tests/python/relax/test_pipeline.py, tests/python/relax/test_runtime_builtin.py, web/emcc/wasm_runtime.cc
This PR provides a simple implementation of inplace attention kv cache for relax runtime. The main goal here is to help us enable auto-regressive decoding quickly in relax.
This is likely not the only way to support attention kv-cache. We keep the implementation private for now and will continue to evolve the relevant code.
=> [Unity][VM] Add Attention KV cache builtin

tests/python/contrib/test_hexagon/test_2d_physical_buffers.py, tests/python/contrib/test_hexagon/test_maxpool2d_blocked.py
Pytest expects test functions to return None, and errors to be flagged via exceptions. It actually emits warnings for "return" statements encountered in test_ functions.
=> [pytest] Don't return values from test_* functions

python/tvm/relax/testing/nn.py, tests/python/relax/test_testing_nn.py
This PR
* supports `emit` to the Relax nn module so that we can emit arbitrary Expr instead of only having `emit_te` available,
* fixes module parameter fetching to ignore non-parameter fields of an module (the previous behavior is to throw error for unrecognized fields).
=> [Unity] Torch-like NN module enhancement

python/tvm/tir/op.py, tests/python/unittest/test_tvmscript_roundtrip.py
Prior to this commit, the python API `tvm.tir.op.tvm_struct_set` defined the return type of `builtin::tvm_struct_set` as `"handle"`, while the C++ API `tvm::tir::TVMStructSet` defined the return type as `DataType::Int(32)`.  The data type used for this builtin has no effect, because no value is returned.  However, this discrepancy can cause failure to roundtrip through TVMScript.
This commit updates the Python API to use `"int32"`, for consistency with the C++ API and with `CodeGenCPU`.
This is part of changes described in https://github.com/apache/tvm/pull/14486, to improve round-trip failures that occur in lowering.
=> [TIR] Use same DataType of builtin::tvm_struct_set in C++ and Python

python/tvm/relay/op/contrib/ethosu.py, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_legalize.py
This PR involves supporting the legalization case of RESIZE_NEAREST_NEIGHBOR where coordinate transformation mode is set to half_pixel.
=> [microNPU] Add support for ResizeNearestNeighbor with half_pixel_centers=True

src/relay/backend/contrib/ethosu/source_module.cc, src/runtime/contrib/json/json_runtime.h, src/runtime/hexagon/hexagon_module.h, src/runtime/static_library.cc, src/target/llvm/llvm_module.cc, src/target/source/source_module.cc
These functions are virtual, and some of the overrides were not marked as either `final` or `override` causing compilation warnings.
=> [LLVM] Add missing `override` to GetFormat and GetPropertyMask

include/tvm/ir/name_supply.h, include/tvm/relax/binding_rewrite.h, include/tvm/relax/block_builder.h, include/tvm/relax/utils.h, src/ir/name_supply.cc, src/relax/ir/binding_rewrite.cc, src/relax/ir/block_builder.cc
`NameTable` is used in Relax code but we now have `NameSupply` in `main`. They serve exactly the same purpose (gensym), so we should use the more standard one (`NameSupply`) for consistency. 
@tqchen @slyubomirsky
=> [Unity][Refactor] Use NameSupply for unique symbol generation and remove NameTable

python/tvm/relay/op/contrib/arm_compute_lib.py, tests/python/contrib/test_arm_compute_lib/test_add.py, tests/python/contrib/test_arm_compute_lib/test_conv2d.py, tests/python/contrib/test_arm_compute_lib/test_dense.py
Currently, only per-layer quantization is supported in the Arm Compute Library runtime. However, there is no check that prevents the offloading of per-channel quantized operators, as a consequence, tvm fails during inference if such operators are found.
This patch adds a check that prevents offloading per-channel quantized operators.
=> [ACL] Prevent offloading of per-channel quantized operators

include/tvm/tir/stmt.h
Prior to this commit, `SeqStmt::Flatten` could accept an arbitrary number of arguments, where each argument was of type `const tir::Stmt&` or an iterable.  However, if `SeqStmt::Flatten` were passed a subclass of `tir::Stmt`, the templated overload was selected as the better match.  This commit rewrites `SeqStmt::Flatten` using C++17's `"constexpr if"` feature, to handle cases of `SeqStmt`, superclasses of `SeqStmt`, and other subclasses of `Stmt`.
=> [TIR] Improved SeqStmt::Flatten utility

python/tvm/relay/qnn/op/_qnn.py
I found that some models fail to compile with tvm when the target is: `compute-library, llvm -mtriple=aarch64-linux-gnu -mattr=+v8.2a,+neon`
The error is:  `AttributeError: <class 'tvm.ir.expr.GlobalVar'> has no attribute name`.
This patch checks if the attribute `name` exists before accessing it, and solves the compilation issues that I had, producing the expected result during the following inference.
=> [Relay] Check if the attribute "name" exists before accessing it

include/tvm/relax/analysis.h, python/tvm/relax/analysis/analysis.py, src/relax/analysis/struct_info_analysis.cc, src/relax/transform/lift_transform_params.cc, tests/python/relax/test_analysis_struct_info_analysis.py
This PR adds an analysis function which helps to fetch all the TIR variables that appear in a given struct info object. This is helpful for passes that need to be aware of symbolic shape dynamism.
=> [Unity][Analysis] Get symbolic TIR vars from struct info

python/tvm/relay/transform/fake_quantization_to_integer.py, tests/python/relay/test_pass_fake_quantization_to_integer.py
Just using the vanila `take` op should be fine. I referred to how `pad` op is handled.
Note this implementation works only for constant indices. To handle non constant indices, I'm guessing we should modify `src/relay/transforms/fake_quantization_to_integer.cc` so that it allows integer inputs without dequantize. Specifically, I think it should capture the following pattern:
```
x  i
|  |
dq |
|  |
\  /
take
|
q
```
but I'm not 100% sure.
=> [QNN] Convert fake quantized take to quantized op

tests/python/relay/test_op_level5.py
The `crop_and_resize` operator uses floating-point arithmetic to determine whether an index is within a view-box.  This can cause the use of `extrapolation_value` to depend on target-dependent rounding differences.
For example, this issue was initially noticed on Vulkan during debugging of https://github.com/apache/tvm/pull/13530, and was the result of computing `0.2*223.0 + 0.8*223.0 < 223.0`.  If all intermediates are cast to float32, the left-hand side evaluates to `223.00002`.  If intermediates are kept at a higher precision, the left-hand side evaluates to `223.0`.
The floating-point indexing can't be removed, because the operator must match the API defined by TensorFlow's operator implementation. The TensorFlow documentation for …
=> [Test][Topi] Avoid depending on f32 rounding behavior for crop_and_divide tests

include/tvm/tir/function.h, src/target/build_common.h, src/target/source/codegen_metal.cc, src/tir/transforms/remap_thread_axis.cc, src/tir/transforms/split_host_device.cc
Previously, `kDeviceThreadAxis` defined the IterVar to be used for each thread/block axis, and `kUseDynamicSharedMemoryTag` defined whether dynamic memory allocations exist, which are primarily used to produce a list of strings by `tvm::codegen::ExtractFuncInfo`.  Because `kDeviceThreadAxis` is a `Array<IterVar>`, the IterVar is used prior to its definition site at `tir::attr::thread_extent`, which results in errors when attempting to round-trip through TVMScript.
This commit replaces these attributes with
`attr::kKernelLaunchParams`, which directly contains the kernel launch parameters.  These are expressed as an `Array<String>`, allowing the generated TVMScript to successfully round-trip.
This is part of changes described in https://github.com/apache/tvm/pull/14486, to improve …
=> [TIR] Merged kDeviceThreadAxis and kUseDynamicSharedMemoryTag

python/tvm/relax/op/index.py, src/relax/op/tensor/index.cc, tests/python/relax/test_op_index.py, tests/python/topi/python/test_topi_transform.py
Currently, `relax.op.take` implements semantics of [torch.take](https://pytorch.org/docs/stable/generated/torch.take.html) which has a stronger restriction than its backing `topi.take` which seems to follow the semantics of [numpy.take](https://numpy.org/doc/stable/reference/generated/numpy.take.html). 
i.e., `relax.op.take` enforces its input `indices` to be 1-d tensor. 
To match its behavior with `topi.take`, this PR extends the semantics of `relax.op.take` by removing such restriction without breaking existing test cases (except one for checking 1-d tensor restriction). 
As a result, this PR can support [onnx.gather](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Gather-13) which was the main motivation of my previous PR https://github.com/apache/tvm/pull/14457 by resolving …
=> [Unity][Op] Extend `relax.op.take` op to match behavior with `topi.take`. 

include/tvm/relax/transform.h, python/tvm/relax/analysis/estimate_memory_usage.py, python/tvm/relax/transform/transform.py, src/relax/transform/static_plan_block_memory.cc, tests/python/relax/test_transform_static_plan_block_memory.py
This PR enhances the memory planning pass with TIR var upper bound
annotation, so that it supports dynamic shape cases when we have
an estimate for the maximum values of the dynamic vars.
=> [Unity] Memory planning with TIR var upper bound

python/tvm/relay/frontend/pytorch.py
This is for resolving https://github.com/apache/tvm/issues/14461
The direct cause of this problem is that the order of input nodes found in `_analysis.free_vars(ret)` is not guaranteed in the order of names in `input_info`. From what I understand, `_analysis.free_vars(ret)` uses DFS to find input nodes from output nodes. Since DFS cannot guarantee the order in which nodes are found, it is intuitive to modify the order of input nodes after DFS, as shown in this PR.
=> [relay] preserve the order of input_info of pytorch

src/relax/transform/fuse_tir.cc, src/runtime/contrib/json/json_runtime.h, tests/python/relax/test_transform_fuse_tir.py
In the last PR https://github.com/apache/tvm/pull/14396, we enable dynamic-shape-aware fusion in FuseOps. In this PR, we support the following FuseTIR pass for simple cases.
This PR also fixes a minor compilation warning in `json_runtime.h`
=> [Unity] Support Simple Dynamic-Shape-Aware in FuseTIR

src/tir/transforms/memhammer_lower_auto_copy.cc
Fix when compiling a program with symbolic thread extent, which is important to dyn kernels.
```py
@I.ir_module
class Module:
@T.prim_func
def matmul(var_rxplaceholder: T.handle, var_rxplaceholder_1: T.handle, var_matmul: T.handle):
T.func_attr({"tir.noalias": T.bool(True)})
n = T.int64()
rxplaceholder = T.match_buffer(var_rxplaceholder, (n, T.int64(4)))
rxplaceholder_1 = T.match_buffer(var_rxplaceholder_1, (T.int64(4), n))
matmul_1 = T.match_buffer(var_matmul, (n, n))
for i0 in T.thread_binding(n, thread="blockIdx.x"):
for i1 in T.thread_binding(n, thread="threadIdx.x"):
for k in range(T.int64(4)):
with T.block("matmul"):
v_i0, v_i1, v_k = T.axis.remap("SSR", [i0, i1, k])
T.reads(rxplaceholder[v_i0, v_k], rxplaceholder_1[v_k, v_i1])
T.writes(matmul_1[v_i0, v_i1])
with T.init(): …
```
=> [Fix] symbolic thread extent program compilation

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/analysis.h, src/tir/schedule/analysis/analysis.cc, src/tir/schedule/concrete_schedule.cc, src/tir/schedule/concrete_schedule.h, src/tir/schedule/primitive.h, src/tir/schedule/primitive/get_block_loop.cc, src/tir/schedule/schedule.cc, src/tir/schedule/traced_schedule.cc, src/tir/schedule/traced_schedule.h, tests/python/unittest/test_tir_schedule_utilities.py
When scheduling fused ops, its really useful to be able to get all the output blocks and schedule other blocks in the fused op with respect to output blocks. This helps avoid hardcoding block names in manually written schedules in many cases
=> [TIR] [Schedule] Add get_output_blocks primitive

include/tvm/relax/attrs/nn.h, python/tvm/relax/op/nn/nn.py, python/tvm/relax/transform/legalize_ops/nn.py, src/relax/op/nn/nn.cc, src/relax/op/nn/nn.h, tests/python/relax/test_op_nn.py, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/relax/test_tvmscript_parser_op_nn.py
This op is widely used when we want to do training in Relax. Since we decide to upstream the Gradient pass from [mlc](https://github.com/mlc-ai/relax), we need to first upstream this operator. Its interface is similar with Relay and TOPI.
=> [Unity][Op] Negative Log Likelihood Loss

include/tvm/node/structural_equal.h, src/ir/module.cc, src/node/structural_equal.cc, tests/python/unittest/test_tir_structural_equal_hash.py
This commit adds a templated overload to `SEqualReducer::operator()` that accepts a lambda function to update the path of the LHS and RHS of the comparison.
```c++
// Usage prior to this utility function
if (equal.IsPathTracingEnabled()) {
const ObjectPathPair& self_paths = equal.GetCurrentObjectPaths();
ObjectPathPair attr_paths = {self_paths->lhs_path->Attr("value"),
self_paths->rhs_path->Attr("value")};
if (!equal(this->value, other->value, attr_paths)) return false;
} else {
if (!equal(this->value, other->value)) return false;
}
// Usage after this utility function
if (!equal(this->value, other->value,
[](const auto& path) { return path->Attr("value"); })) {
return false;
}
```
=> [Node] Utility methods for ObjectPathPair handling

include/tvm/relax/dataflow_matcher.h, python/tvm/relax/dpl/context.py, src/relax/ir/dataflow_matcher.cc, src/relax/ir/dataflow_pattern.cc, tests/python/relax/test_dataflow_pattern.py
* As discussed and agreed in https://github.com/apache/tvm/pull/14417#discussion_r1152443315, remove `start_hint` feature to simplify the API and the implementation
* To support the `start_hint` feature, the current algorithm has "bidirectional" nature: Matching can start from any node. This introduces recursive matching on both child and parent nodes, which makes the implementation complicated and reasoning about the algorithm almost impossible. Since this PR removes `start_hint`, we can now implement the algorithm in a purely one-directional manner, by starting matching from root nodes (those without parent nodes). Note that the pattern constraint graph is assumed to be a DAG. 
* The current implementation relies on side-effecting operations to maintain matchings. So when matching fails …
=> [Unity][Graph matching] Improved matching algorithm and implementation

include/tvm/script/ir_builder/base.h, include/tvm/script/ir_builder/ir/frame.h, include/tvm/script/ir_builder/ir/ir.h, python/tvm/ir/module.py, python/tvm/script/ir_builder/base.py, python/tvm/script/ir_builder/ir/__init__.py, python/tvm/script/ir_builder/ir/ir.py, python/tvm/script/parser/core/diagnostics.py, python/tvm/script/parser/core/evaluator.py, python/tvm/script/parser/core/parser.py, python/tvm/script/parser/ir/__init__.py, python/tvm/script/parser/ir/parser.py, python/tvm/script/parser/tir/entry.py, python/tvm/script/parser/tir/parser.py, rust/tvm/src/ir/module.rs, src/ir/module.cc, src/script/ir_builder/base.cc, src/script/ir_builder/ir/frame.cc, src/script/ir_builder/ir/ir.cc, src/script/ir_builder/ir/utils.h, src/script/ir_builder/tir/frame.cc, src/script/ir_builder/tir/utils.h, src/script/printer/ir/ir.cc, tests/python/unittest/test_tvmscript_roundtrip.py
This PR contains the non-relax portions of https://github.com/apache/tvm/pull/13932 and https://github.com/apache/tvm/pull/14132, which would be useful to have in the main branch of TVM.  This upstreaming is part of the TVMScript round-trip improvements described [here](https://github.com/apache/tvm/pull/14486), specifically to support the `I.module_attrs(...)` annotations.
I've preserved the co-author listing for the two Unity PRs.  Please let me know if there is anybody I missed, or if anybody would like to be removed.
=> [TVMScript] Upstream IRModule parser from unity

src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops_by_pattern.py
Previously, it has been assumed that when a fused function outputs a tuple, `TupleGetItem` needs to be attached to each output element to properly remap variables. But when an op that emits a tuple (e.g. `split`) is wrapped into a new function by this pass, that tuple can become the output of the fused function on its own. In such cases, a user of the output of such functions expects to get a tuple, so `TupleGetItem` must not be attached.
This PR also fixes a bug in the grouping algorithm, where `TupleGetItemPattern` that has been matched is not put into the matching group. 
@cyx-6
=> [Unity] Properly handle tuple-outputting function in `FuseOpsByPattern`

src/topi/einsum.cc, tests/python/topi/python/test_topi_einsum.py
=> [TOPI] Support symbolic shape in einsum

src/runtime/metal/metal_module.mm, src/runtime/vulkan/vulkan_wrapped_func.h
Following #14406, this PR adds the runtime module property mask for Metal and Vulkan backend, which were left before.
=> [Runtime] Runtime module property mask for Metal and Vulkan

python/tvm/topi/cuda/ssd/multibox.py, python/tvm/topi/vision/ssd/multibox.py, tests/python/topi/python/test_topi_vision.py
- For cpu,  currently the buffer space of `box_coord` and `pred_coord` is shared across parallel batch like
```python
for i in parallel(batch_size):
for l in range(4):
box_coord[l] = anchor[0, j, l]
pred_coord[l] = loc_pred[i, j * 4 + l]
```
- For cuda, fix two index usage error of batch idx.
=> [TOPI] Fix data race of batch multibox detection

src/arith/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
This simplification was introduced in https://github.com/apache/tvm/pull/13217, and was erroneously removed in https://github.com/apache/tvm/pull/13933.  This commit re-enables this simplification, and adds unit tests to prevent any future regression.
=> [Arith][Bugfix] Simplify "x - 1 < y" into "x <= y"

src/target/llvm/codegen_blob.cc
The latter has been deprecated since LLVM 16.
=> [LLVM] Use DataLayout::getABITypeAlign instead of getABITypeAlignment

include/tvm/tir/transform.h, src/tir/transforms/ir_utils.cc, src/tir/transforms/split_host_device.cc, tests/python/unittest/test_tir_transform_split_host_device.py
Prior to this commit, the same `tir::Var` could be defined both in the body of the host function and in a parameters of the device function.  While this is legal, as TIR only requires SSA across each `PrimFunc`, this does result in failure to round-trip through TVMScript, because the round-tripped TIR uses a new `tir::Var` in each instance.  This PR adds a `ConvertSSA()` transform that can apply to an entire `IRModule`, in addition to the existing `ConvertSSA(Stmt)` utility.
This is part of changes described in https://github.com/apache/tvm/pull/14486, to improve round-trip failures that occur in lowering.
=> [TIR] Update SplitHostDevice to post-process with ConvertSSA

docker/install/ubuntu_install_sccache.sh
As disscussed in https://github.com/apache/tvm/pull/14466 ，let's pin sccache version to v0.3.3, otherwise new docker images keeps fail with: "sccache: error: Timed out waiting for server startup."
cc @lhutton1 @driazati
=> [CI] Pin sccache version to 0.3.3

src/target/tag.cc
It has 8 cores.
[NVIDIA Jetson AGX Xavier Delivers 32 TeraOps for New Era of AI in Robotics | NVIDIA Technical Blog](https://developer.nvidia.com/blog/nvidia-jetson-agx-xavier-32-teraops-ai-robotics/)
=> [Target] Fix Jetson AGX Xavier CPU core count

src/runtime/hexagon/hexagon_module.h
1. Resolves issue with kernels linking.
2. Fixes warning generated by clang-15.
=> [hexagon] Hexagon inference fix

include/tvm/arith/analyzer.h, include/tvm/arith/int_set.h, python/tvm/arith/__init__.py, python/tvm/arith/analyzer.py, src/arith/analyzer.cc, src/arith/int_set.cc, src/arith/interval_set.h, src/arith/rewrite_simplify.cc, src/arith/rewrite_simplify.h, src/tir/analysis/block_access_region_detector.cc, src/tir/schedule/primitive/compute_at.cc, src/tir/schedule/primitive/loop_transformation.cc, tests/python/unittest/test_arith_simplify.py
This PR enhances CanProve to handle symbolic bound.
Such analysis is essential to eliminate predicates in
dynamic shape workloads.
We also the int set analysis singlepoint check to avoid recursion
and improve the overall analysis speed.
Added CanProveSinglePoint to serve previous stronger checks.
The new CanProve comes with additinal strength argument
that can only be used in top-level setting with stronger analysis.
Added comment for future implementation efficiency.
Testcases are added to cover the cases.
=> [ARITH] Enhance CanProve to handle symbolic bound

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/gradient.cc, src/relax/transform/utils.cc, src/relax/transform/utils.h, tests/python/relax/test_transform_gradient.py, tests/python/relax/test_transform_gradient_numeric.py
This PR introduces the high-level reverse-mode automatic differentiation pass  `Gradient` for Relax. It's the core component when we are trying training or fine-tuning in Relax IR.
Before upstreaming, this work is actively iterated and maintained in many forks like [mlc](https://github.com/mlc-ai/relax) and [relax-training](https://github.com/ACMClass-TVM-20/relax-training). Now it reaches a relatively stable version and it's time for us to upstream this important work to the unity branch.
The Python side API:
- `Gradient(func_name: str, require_grads: Optional[Union[Var, List[Var]]] = None, target_index: int = 0) -> tvm.ir.transform.Pass`
It will transform the given funcion in the IRModule, and adds a new function that calculates the gradient with regard to the function's output.
``` …
```
=> [Unity][Transform] High-level reverse-mode automatic differentiation pass

include/tvm/topi/reduction.h, python/tvm/topi/reduction.py, src/topi/reduction.cc, tests/python/topi/python/test_topi_reduce.py
TOPI has an implementation of `collapse_sum` internally (`tvm/topi/reduction.h`) but it is not exposed to FFI and can not be called in Python side. This patch exposes it and adds related tests. And this PR lets the implementation of `topi::collapse_sum` support symbolic shape cases.
=> [TOPI] Expose `topi::collapse_sum` to Python and support symbolic shape

src/tir/transforms/default_gpu_schedule.cc, tests/python/unittest/test_transform_default_gpu_schedule.py
Previously the DefaultGPUSchedule only works for CUDA. This PR enables it for other GPU targets like Metal.
=> [Unity] DefaultGPUSchedule working for targets other than CUDA

src/target/tag.cc
During our development and exploration on WebGPU, we noticed that the WebGPU backend on Apple Silicon machines have the restriction on the number of threads in a thread block, requiring the number of threads no more than 256, which is smaller than the native requirement of Metal.
Therefore, we introduce the restricted backend for convenience.
=> [Target] Add Apple M1 GPU tag with 256-thread restriction

conda/recipe/meta.yaml, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/package.json
This bumps all the version numbers following the `v0.12.0` branch cut.
=> Update to v0.13.dev0

include/tvm/relax/analysis.h, python/tvm/relax/analysis/analysis.py, src/relax/analysis/struct_info_analysis.cc, src/relax/transform/fuse_ops.cc, tests/python/relax/test_analysis.py, tests/python/relax/test_analysis_struct_info_analysis.py, tests/python/relax/test_transform_fuse_ops.py
The current fuse_ops pass only supports symbolic vars that are all defined in the parameter `struct_info`. This commit enhances the pass to support free symbolic vars by adding them to the parameter explicitly
=> [Unity][Pass] Enhance Dynamic-aware FuseOps

src/arith/bound_deducer.cc, src/arith/canonical_simplify.cc, src/arith/pattern_match.h, tests/python/unittest/test_arith_canonical_simplify.py, tests/python/unittest/test_arith_deduce_bound.py
This PR enhances canonical simplify to simplify product division pattern where both side involves symbolic variables.
Test cases are added.
=> [ARITH] Enhance CanonicalSimplify to Simplify ProdDiv

include/tvm/topi/nn/dilate.h, include/tvm/topi/nn/pooling.h, include/tvm/topi/transform.h, tests/python/relay/test_op_grad_level2.py, tests/python/relay/test_op_level2.py
The output shape for pooling is casted to i32, it would be good to keep it as it is
=> [TOPI] remove the i32 cast for output shape of pool

src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops.py
the pattern of the shapeexpr should be set to `kOpaque` in  GraphCreator. Previously it was not handled and will run into an error
=> [Unity] Make FuseOps work on a call_tir which has a ShapeExpr arg

python/tvm/relax/block_builder.py, python/tvm/relax/utils.py, tests/python/relax/test_blockbuilder_core.py, tests/python/relax/test_blockbuilder_emit_te.py
This PR fixes the use of emit_te with symbolic shape input.
Testcases are added
=> [Unity] Fix emit_te with symbolic input

src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_fuse_tir.py
Currently fuse_tir will remove the symbolic var args of call_tir. This PR fixes this behavior.
=> [Unity] Preserve symbolic var args when applying call_tir

ci/jenkins/docker-images.ini, tests/python/relay/test_op_level2.py, tests/scripts/task_config_build_cpu.sh
Update docker image tag as a follow up step for https://github.com/apache/tvm/pull/14303.
cc @Hzfengsy @wrongtest-intellif @elvin-n
=> [CI] Update ci_cpu image and build with llvm-15

apps/benchmark/adreno/adreno_gpu_bench_clml.py, apps/benchmark/adreno/adreno_gpu_bench_texture.py, gallery/how_to/deploy_models/deploy_model_on_adreno.py, gallery/how_to/tune_with_autotvm/tune_relay_arm.py, gallery/how_to/tune_with_autotvm/tune_relay_cuda.py, gallery/how_to/tune_with_autotvm/tune_relay_mobile_gpu.py, gallery/how_to/tune_with_autotvm/tune_relay_x86.py, gallery/tutorial/autotvm_relay_x86.py, python/tvm/autotvm/testing/tune_relay.py, python/tvm/autotvm/tuner/xgboost_cost_model.py, python/tvm/autotvm/tuner/xgboost_tuner.py, python/tvm/contrib/torch/pytorch_tvm.py, python/tvm/driver/tvmc/autotuner.py, tests/python/contrib/test_clml/test_adreno_collage_targets.py, tests/python/contrib/test_hexagon/test_autotvm.py, tests/python/relay/collage/demo_collage_partitioner.py, tests/python/unittest/test_autotvm_xgboost_model.py, vta/scripts/tune_resnet.py, vta/tutorials/autotvm/tune_alu_vta.py, vta/tutorials/autotvm/tune_relay_vta.py
This PR fix the latest xgboost >= 2.0.0 behaviour requiring binarized labels.
* The strict behaviour was introduced by https://github.com/dmlc/xgboost/pull/8931
* A possible solution here (also [suggested](https://github.com/dmlc/xgboost/pull/9007#issuecomment-1494739265)) would be to binarize by threshold at the evaluation  calls.
* This is a continuation on https://github.com/apache/tvm/pull/14036 xgboost
This address ~~both~~  only```autotune``` (~~and ```autoscheduler```~~).
**Note:**
Unsure about TVM overall tunner impact, but we can introduce more sophisticated way of measuring AP like [PASCAL evenly spaced one](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Average_precision), the advantages are unclear and would require extensive comparative tests.
--- …
=> [AutoTVM] New rank-binary loss_type for the new xgboost >= 2.0.0 behaviour

python/tvm/meta_schedule/relax_integration.py, src/tir/transforms/default_gpu_schedule.cc, tests/python/relax/test_transform_meta_schedule_tuning.py, tests/python/unittest/test_transform_default_gpu_schedule.py
<s> This PR introduced a check to skip tasks that has been thread-binded in previous passes or manually so that we can process them differently and avoid failures like for `cumsum`. </s>
This PR introduced a check to skip tasks that has been scheduled either by `DefaultGPUSchedule` pass or the `MetaScheduleApplyDatabase` pass.
CC: @sunggg @jwfromm
=> [Unity][MetaSchedule] Skip Scheduled PrimFuncs in Task Generation

docs/how_to/deploy/vitis_ai.rst
`/etc/fstab` is overwritten.
cc @zxybazh @masahi @junrushao
=> [Docs] Fix typo in the Vitis AI Integration docs

src/target/llvm/codegen_llvm.cc
This cast was initially added when `CreateBufferPtr` did not include the cast to the appropriate address space, and should no longer be necessary.  Removing the cast will not harm LLVM configurations with opaque pointers ([default in LLVM
15+](https://github.com/llvm/llvm-project/blob/main/llvm/docs/OpaquePointers.rst)), and avoids type mismatches when using LLVM configurations that use typed pointers.
=> [Codegen][LLVM] Remove cast to i8* in builtin::address_of

src/tir/schedule/analysis/reducer.cc, tests/python/unittest/test_tir_schedule_reduction.py
Previously the check of reduction block did not take the intermediate allocated buffers (that is, the buffers in `alloc_buffers` field of a block) into consideration, which will lead to exception thrown during scheduling in cases of nested block + cache read/write.
This PR fixes this issue with one unit test for the DecomposeReduction primitive.
Credit of the fix goes to Bohan.
=> [Fix][TIR][Analysis] Reduction block checking alloc_buffers

src/arith/int_constraints.cc, tests/python/unittest/test_arith_solve_linear_inequality.py
Fix an issue in `FindBestRange` where if `IntSet::max()` if inf, it could not take part in general arithmetic computations.
=> [Arith] Fix solve inequality of unbound var ranges

src/arith/iter_affine_map.cc, src/arith/rewrite_simplify.cc, tests/python/unittest/test_arith_canonical_simplify.py, tests/python/unittest/test_arith_iter_affine_map.py, tests/python/unittest/test_arith_rewrite_simplify.py, tests/python/unittest/test_tir_transform_inject_software_pipeline.py
This PR fixes a previous bug introduced in itermap detection.
Specifically, y - (x % 2) were simplified to y + (x % 2) - 1. Which is wrong. The working rule is  y + ((x + 1) % 2) - 1, but that rule will change the base iterator which is not desirable here.
=> [ARITH][BUGFIX] Fix a bug of iter map floormod(x,2) simplify

src/relay/op/tensor/math.cc, tests/python/relay/test_pass_merge_composite.py
Previously, it was reported that when using MergeComposite on a model with broadcast_to OP, an error caused by IncompleteTypeNode occurs during compiling model. See https://discuss.tvm.apache.org/t/incomplete-type-in-broadcasttorel-while-doing-mergecomposite/10439
A similar bug also occurs if the model contains einsum OP. This PR fixes this bug for einsum OP and add a test case.
=> [Bugfix] [Relay] fix a bug caused by IncompleteTypeNode in EinsumRel while doing MergeComposite

src/tir/schedule/primitive/compute_at.cc, tests/python/unittest/test_tir_schedule_compute_at.py
This PR fixes a case where we have perfect symbolic bound in compute at and can be eliminated.
Testcases are added.
=> [TensorIR] Fix ComputeAt with perfect symbolic bound

src/target/llvm/codegen_cpu.cc, tests/python/unittest/test_target_codegen_llvm.py
Prior to this commit, DWARF debug symbols for `float32`, `int8`, and `int32` could be generated, with other datatypes resulting in an error.  This commit expands the range of types with debug symbols to allow for any `DLDataTypeCode::kDLInt`, `kDLUint`, or `kDLFloat`, regardless of the bitsize.
=> [LLVM] Expand tvm::Type to DWARF conversion

src/tir/transforms/unify_thread_binding.cc, tests/python/unittest/test_tir_transform_unify_thread_binding.py
This PR fixes a behavior of the UnifyThreadBinding pass which (at one place) assumes a return value is always a ForNode, which is not right.
To be more specific, when a thread-binding loop has an annotation, the current behavior is assuming that the post-recursive-mutation value is also a ForNode, and apply the previous annotation directly to the new loop. However, the post-recursive-mutation value is also possibly not a ForNode. In this case, the current behavior is incorrect.
This PR creates a new unit-length loop in this case to preserve the annotation.
Thanks Bohan for catching this issue.
=> [Fix][TIR] UnifyThreadBinding creating unit loop with annotation

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/tir/schedule/concrete_schedule.h, src/tir/schedule/schedule.cc, tests/python/unittest/test_tir_schedule_utilities.py
PR #11999 introduces the sugar method `work_on` to TIR Schedule, with a field `func_working_on_` newly added to the ScheduleNode. In some cases we may want to know which function a ScheduleNode is working on, which is not supported previously.
Therefore, this PR introduces a method to ScheduleNode that returns the function (more accurately, GlobalVar) currently being worked on. With this we are able to know the function being worked on.
=> [TIR][Schedule] Method returning the function being worked on

include/tvm/arith/iter_affine_map.h, python/tvm/arith/__init__.py, python/tvm/arith/iter_affine_map.py, src/arith/canonical_simplify.cc, src/arith/ir_mutator_with_analyzer.cc, src/arith/ir_mutator_with_analyzer.h, src/arith/iter_affine_map.cc, src/arith/pattern_match.h, src/arith/product_normal_form.h, src/script/printer/tir/expr.cc, src/tir/schedule/primitive/loop_transformation.cc, src/tir/transforms/flatten_buffer.cc, tests/python/unittest/test_arith_iter_affine_map.py, tests/python/unittest/test_meta_schedule_postproc_rewrite_layout.py, tests/python/unittest/test_meta_schedule_postproc_rewrite_unbound_block.py, tests/python/unittest/test_meta_schedule_schedule_rule_cross_thread_reduction.py, tests/python/unittest/test_meta_schedule_schedule_rule_mlt.py, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_intrin.py, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_tc.py, tests/python/unittest/test_meta_schedule_space_cpu.py, tests/python/unittest/test_meta_schedule_space_cuda.py, tests/python/unittest/test_meta_schedule_space_cuda_async.py, tests/python/unittest/test_meta_schedule_space_cuda_winograd.py, tests/python/unittest/test_meta_schedule_trace_apply.py, tests/python/unittest/test_tir_transform_flatten_buffer.py
This PR refactors and enhances DetectIterMap and IterMapSimplify
to enable symbolic shape simplification. Specficially, we add
a routine to combine multiple IterSplitExpr into one if they
come from the same source.
It is helpful to distinguish iterator from normal constants
in the simplification process. IterMapSimplify takes advantage
of these information.
This improvements is helpful to simplify the indices in flattened buffer
when there is symbolic shape involved and normal simplifier.
Also updated FlattenBuffer to take benefit of the enhanced simplifier.
Test cases are added.
=> [ARITH] Enhance IterMapSimplify for symbolic 

python/tvm/relax/frontend/torch/dynamo.py
I got an out-of-memory error on my 16G linux system when trying to trace VAE in web-stable-diffusion https://github.com/mlc-ai/web-stable-diffusion/blob/main/build.py#L82 (this is not an issue on Mac). This simple change let me complete the build successfully. 
Using the `time -v` command to measure the peak RAM usage of a script that does VAE tracing, I got
Before: `Maximum resident set size (kbytes): 12288884`
After (disable grad): `Maximum resident set size (kbytes): 7179364`
So this is a good reduction of 5GB.
@MasterJH5574 @spectrometerHBH @junrushao
=> [Unity][PyTorch] Disable gradient during dynamo subgraph capture to save RAM

python/tvm/tir/tensor_intrin/cuda.py
This PR added int4 tensor intrinsic for CUDA tensor core.
cc @junrushao @tqchen @masahi
=> [TIR] Add CUDA int4 tensor core intrinsics

src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_fuse_tir.py
When the same buffer is read multiple times with different access patterns in a single expression, the check below fails
https://github.com/apache/tvm/blob/unity/src/relax/transform/fuse_tir.cc#L266
But this case should be allowed, for example in the following subgraph `inp_0` is used twice in different read regions. See the test case for details. This subgraph arises if we run `ConvertLayout` on SD UNet from web-stable diffusion.
```
lv: R.Tensor((2, 4, 64, 64), dtype="float32") = R.concat((inp_0, inp_0), axis=0)
lv_2: R.Tensor((2, 64, 64, 4), dtype="float32") = R.permute_dims(lv, axes=[0, 2, 3, 1])
```
@Hzfengsy
=> [Unity] Fix FuseTIR when the same buffer is read multiple times with different access pattern

docker/Dockerfile.ci_cpu, docker/Dockerfile.ci_gpu, docker/install/ubuntu_install_jax.sh
I am trying to add JAX related packages into cpu and gpu dockerfiles, then CI should be able to support JAX, Flax, StableHLO/MLIR Python Bindings, etc.
cc: @driazati @tqchen
=> [CI] Add JAX deps in Dockerfiles

include/tvm/node/object_path.h, python/tvm/runtime/object_path.py, src/node/object_path.cc, tests/python/unittest/test_object_path.py
Previously, the `ObjectPath` utility allowed tracking of an object's location within a tree-like structure.  However, the base of the path structure was hard-coded to be the string `<root>`.  For use cases such as `StructuralEqual`, there is a clear root node.  However, other cases such as using `ObjectPath` to specify an object's location relative to a known variable, would require using that known variable's name as the root, rather than the hard-coded string `<root>`.
This commit adds an optional parameter to provide an alternative name for the root node, to allow for these use cases.
=> [Node] Allow alternative root names in ObjectPath::Root()

tests/python/contrib/test_ethosu/test_pass_operations_distribution.py
This was failing locally due to an indirect import in `infra.py`. Also ensure both tests are run by using the standard `tvm.testing.main()` function to run the tests.
cc @arina-grovety @sergio-grovety @ekalda
=> [microNPU] Fix skip tests when Vela is not present

include/tvm/arith/analyzer.h, src/arith/analyzer.cc, src/arith/iter_affine_map.cc, src/tir/transforms/compact_buffer_region.cc, tests/python/unittest/test_arith_iter_affine_map.py, tests/python/unittest/test_tir_transform_compact_buffer_region.py
This PR improves compact buffer region for symbolic shape programs. We introduce a new function CanProveLessEqualThanSymbolicShapeValue which can take the extra information such that rhs is a non-negative shape.
The change is necessary to enable symbolic shape schedules. Test cases are added to cover the case
=> [ARITH][TensorIR] Improve CompactBufferRegion for symbolic shape

include/tvm/tir/schedule/schedule.h, python/tvm/tir/schedule/schedule.py, src/meta_schedule/utils.h, src/tir/schedule/concrete_schedule.h, src/tir/schedule/schedule.cc, tests/python/unittest/test_tir_schedule_utilities.py
PR #14182 introduces the default GPU schedule pass, which makes uses
of the BlockCollector in Meta-Schedule. When requested, the
BlockCollector goes through every function in the input IRModule,
while in the case of applying default GPU schedule where we apply
schedule to one PrimFunc at a time, going through every PrimFunc is
wasteful.
Therefore, this PR enhances the BlockCollector so that it only focuses
on the function being worked on.
=> [Unity][MetaSchedule] BlockCollector focusing on current func

src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h, src/target/llvm/codegen_nvptx.cc, src/target/llvm/llvm_module.cc
Because LLVM's optimizations assume that the generated module is valid, validation should be done before optimization, rather than after.  This has the additional benefit of providing error messages from LLVM that more closely relate to the TVM-generated LLVM IR, rather than the optimized LLVM IR.
=> [LLVM] Validate generated LLVM module before optimization

python/tvm/meta_schedule/cost_model/xgb_model.py, src/meta_schedule/feature_extractor/per_store_feature.cc, tests/python/unittest/test_meta_schedule_cost_model.py, tests/python/unittest/test_meta_schedule_feature_extractor_per_store_feature.py
This PR fixes the problem that ops like `topi.full` cannot be correctly tuned.
Currently, metaSchedule system adopts a XGBoost model to predict the running performance of an IRModule based on features extracted from it. 
However, Some operators like `topi.full` has so simple IRModule that no feature can be extracted. `topi.full` contains only one BufferStore node with a FloatImm value, so `PerStoreFeature` extractor cannot find any feature from it. And the XGBModel also cannot handle cases when there is no features.
This PR specifically handles this case in `PerStoreFeatureNode` and `XGBModel`.
Thanks to @junrushao
=> [MetaSchedule] Handle cases when no features found by FeatureExtractor

include/tvm/relax/dataflow_matcher.h, include/tvm/relax/dataflow_pattern.h, python/tvm/relax/transform/transform.py, src/relax/ir/dataflow_matcher.cc, src/relax/ir/dataflow_pattern.cc, src/relax/transform/combine_parallel_matmul.cc, tests/python/relax/test_dataflow_pattern.py, tests/python/relax/test_transform_combine_parallel_matmul.py
Building on pattern-based binding rewriting work https://github.com/apache/tvm/pull/14446, I'm adding a new pass for combining parallel matmul sharing the same LHS into one. In contrast to the equivalent Relay pass which is based on dedicated pattern-matching algorithm (completely separate from dataflow pattern matcher), this pass is implemented in terms of the generic binding rewriting infra.
When all matmul branches in a tree have the same set of fused ops, the fused ops are applied to the combined matmul output before slicing. So bias adds are also combined, for example. See the test cases. 
Applied to the SD UNet from web-stable-diffusion, it reduces the number of `R.matmul` from 200 to 100. See below for the IR comparison.
Before combining: …
=> [Unity] Add pass for combining parallel matmul

python/tvm/relay/frontend/paddlepaddle.py, tests/python/frontend/paddlepaddle/test_forward.py
add `dropout_prob`  and `dropout_implementation` attributes for `dropout` op.
add `offset` attribute  for `hard_sigmoid` op.
add `data_format` attribute for `pixel_shuffle` op.
=> [Frontend][Paddle] [PaddlePaddle Hackathon 4]add attribute support for dropout/hard_sigmoid/pixel_shuffle

include/tvm/tir/data_type_rewriter.h, src/tir/ir/data_type_rewriter.cc, src/tir/transforms/force_narrow_index_to_i32.cc, tests/python/relax/test_transform_legalize_ops_search_statistical.py, tests/python/relax/test_transform_legalize_ops_unary.py, tests/python/unittest/test_tir_transform_force_narrow_index_to_i32.py
This PR fixes ForceNarrowI32 for functions that comes with pod arguments.
Test cases are added
=> [Unity] Fix ForceNarrowI32 with pod arguments

python/tvm/tir/schedule/schedule.py
Looks like the `unsafe_set_dtype` docs  were not updated after the API was renamed during PR reviews, just fixing that.
=> [TIR] [Docs] Fix unsafe_set_dtype docstring

python/tvm/relax/ir/instrument.py, src/relax/analysis/well_formed.cc, src/relax/transform/fuse_ops.cc, src/relax/transform/utils.h, src/relax/utils.cc, tests/python/relax/test_analysis_well_formed.py, tests/python/relax/test_utils.py
Prior to this PR, there is no constraint to prevent user defining multiple functions which may use the same symbolic TIR var. For example, user may write the following script:
```
batch_size = tir.Var("batch_size", "int64")
@I.ir_module
class Test:
@R.function
def main(
x: R.Tensor((batch_size, 10), "float32"),
):
lv = R.sum(x, axis=1)
lv1 = R.mean(x, axis=1)
out = R.add(lv, lv1)
R.output(out)
return out
@R.function
def main1(
x: R.Tensor((batch_size, 10), "float32"),
y: R.Tensor((batch_size, 10), "float32"),
):
out = R.subtract(x, y)
R.output(out)
return out
lowered_mod = LegalizeOps()(Test)
ex = relax.build(lowered_mod, "llvm")
vm = relax.VirtualMachine(ex, tvm.cpu(0))
```
But this script can not be built because `VMShapeLower` can not handle this …
=> [Unity][UX] Symbolic Variables Used in Multiple Functions

python/tvm/relay/frontend/tensorflow_ops.py, tests/python/frontend/tensorflow/test_forward.py
If "data_format" == "NHWC", the kernel_layout for conv2d_transpose should be "HWOI" rather than "HWIO".
=> [Tensorflow] Fix conv2d_transpose for NHWC layout

python/tvm/runtime/relax_vm.py, tests/python/relax/test_vm_build.py
`relax.Tuple` was changed to backed by Python tuple, no longer by ADT, before. This PR fixes a missing place that was left unchanged accordingly.
=> [Unity][VM] Converting tuple arg to Python tuple

python/tvm/relax/testing/lib_comparator.py, tests/python/relax/test_vm_instrument.py
Previously the LibComparator omitted the dtype argument when creating a NDArray, which leads to the dtype always float32. This PR fixes this behavior.
=> [Unity][VM] LibComparator using dtype from input

src/target/source/codegen_metal.cc, src/target/source/codegen_metal.h
This PR fixes the metal introduces by a previous commit that removes the workdim remapping that caused issues for kernels with only threadIdx.x and blockIdx.x
=> [Unity][CODEGEN] Fix metal codegen when with only single working dim

python/tvm/tir/schedule/schedule.py
I forget to add docstring for the `reorder_block_iter_var` schedule primitive introduced in #14448 , this PR completes this part.
=> [TensorIR][Doc] Docstring of `reorder_block_iter_var`

src/tir/schedule/primitive/cache_read_write.cc, tests/python/unittest/test_tir_schedule_cache_read_write.py
When applying `reindex_cache_write` to the write buffer of a reduction block, the init statement would not be mutated accordingly:
```python
@T.prim_func
def reduce(A: T.Buffer((128, 128, 128, 128), "float32"), C: T.Buffer((128, 128), "float32")):
B = T.alloc_buffer((128, 128, 128), dtype="float32")
for i, j, k in T.grid(128, 128, 128):
for l in range(128):
with T.block("B"):
vi, vj, vk, vl = T.axis.remap("SSSR", [i, j, k, l])
with T.init():
B[vi, vj, vk] = T.float32(0)
B[vi, vj, vk] = B[vi, vj, vk] + A[vi, vj, vk, vl]
vi, vj, vk = T.axis.remap("SSR", [i, j, k])
with T.init():
C[vi, vj] = T.float32(0)
C[vi, vj] = C[vi, vj] + B[vi, vj, vk]
sch = tir.Schedule(reduce, debug_mask="all")
sch.reindex_cache_write("B", 0, "shared", lambda i, j, k, l: (j, i, k))
@T.prim_func
def …
```
=> [TensorIR][Bugfix] `reindex_cache_write` do not mutate init statement

src/target/source/codegen_metal.cc, src/target/source/codegen_metal.h
This PR fixes the metal introduces by a previous commit that removes the workdim remapping that caused issues for kernels with only threadIdx.x and blockIdx.x
=> [CODEGEN] Fix metal codegen when with only single working dim

python/tvm/relay/frontend/onnx.py
The attribute 'errors' is a wrong name. When code was executed at this line, It will throw an error: message `"AttributeError: module 'tvm' has no attribute 'errors'"`. This PR fix it!
=> Fix bug about wrong attribute name

src/relax/transform/infer_amp_utils.cc, tests/python/relax/test_transform_to_mixed_precision.py
In AMP, an abstract type representing "unknown" type has a string representation "". `String2DLDataType` returns `DataType::Void()`  https://github.com/apache/tvm/blob/c452e6966c33047512155f42f63aef4e0586d129/include/tvm/runtime/data_type.h#L351-L352 for such string. 
So when the abstract type is `unknown_`,  `ICHECK_EQ(a.code(), b.code())` in `NTypeMerge` always fails because we try to merge a concrete type such as "float32" with void.
@spectrometerHBH
=> [Unity][AMP] Fix merging concrete type and "unknown" type

src/relay/analysis/type_solver.cc, src/relay/analysis/type_solver.h, tests/python/relay/test_type_infer.py
Support type_infer to enable unify PrimExpr such as tir.IndexMod(relay.Any(), 5), instead of previous only relay.Any
=> [Relay] Enhance type infer for dynamic shape

src/runtime/vulkan/vulkan_device.cc, src/target/spirv/codegen_spirv.cc, src/target/spirv/codegen_spirv.h
This PR updates vulkan codegen to support for DeclBuffer. We also disabled subgroup operations.
This is because we find that on Nvidia GPU subgroup were detected to be 8 and the generated code for softmax produces wrong results.
Setting it to be 32(the typical size of CUDA warp) also does not produce the right result.
We directly hard set the value to 1 to be ensure correctness. The team can revisit this behavior later.
=> [Unity][TARGET] Updates vulkan codegen for DeclBuffer

src/meta_schedule/postproc/rewrite_parallel_vectorize_unroll.cc, tests/python/unittest/test_meta_schedule_postproc_rewrite_parallel_vectorize_unroll.py
This PR adds a behavior to the MetaSchedule post-processor RewriteParallelVectorizeUnroll, so that it does not annotate spatial blocks with the unroll annotation.
This is because the optimization for spatial blocks (standalone in a GPU kernel, for example) can be done by purely thread binding. As a result, annotating loop unrolling for spatial blocks does not help. In some case where the unroll factor is very large (e.g., 512 or 1024), unrolling the spatial blocks will consume much time during the kernel compilation and introduces unnecessary overhead.
Therefore, we turn off the behavior of unrolling spatial blocks.
=> [MetaSchedule] PostProc not rewriting unroll for purely spatial block

include/tvm/relax/transform.h, python/tvm/meta_schedule/relax_integration.py, python/tvm/relax/pipeline.py, python/tvm/relax/transform/transform.py, src/relax/transform/legalize_ops.cc, src/relax/transform/meta_schedule.cc
This PR introduces the `enable_warning` argument for the LegalizeOps pass and the MetaScheduleApplyDatabase pass. These two passes now will emit warnings only when the `enable_warning` argument is true.
We introduce this because in our recent practice of [Web LLM](https://github.com/mlc-ai/web-llm), we leverage three passes to generate the GPU code for the TIR functions in a given IRModule. The passes are MetaScheduleDatabaseApply, DispatchTIROperator (one pass that substitutes a TIR func with another handmade one or hand-scheduled one), and DefaultGPUSchedule, in order. (https://github.com/mlc-ai/web-llm/blob/514f6e3132f91a2460f012a74861cd57b43560fb/build.py#L157-L161)
In this case (and most of the cases), we always have the DefaultGPUSchedule pass as a safe guard, and it is common and …
=> [Unity] `enable_warning` option for LegalizeOps and MSApplyDatabase

python/tvm/relax/utils.py, tests/python/relax/test_blockbuilder_core.py
This PR changes the naming behavior of call_te. With this PR, all tensors created by call_te will be named in alphabetical order (`A`, `B`, `C`...). When the number of tensors exceeds 26, the trailing tensors will be named as `input26`, `input27` and so on so forth.
Prior to this PR, call_te uses the default name "rxplaceholder" for every tensor. On one hand, this name is too long and doesn't look clean in the printed TVMScript. On the other hand, using this name for every tensor is problematic from the perspective of TIR and will lead to scheduling error. For example, previously, the following code snippet will print the TIR function where two cache-read blocks having the same name, which is not a legal TIR function.
```python
bb = relax.BlockBuilder()
x = relax.Var("x", R.Tensor((2, 3), …
```
=> [Unity] BlockBuilder assigning unique tensor names in call_te

web/src/webgpu.ts
Sometimes user may get confused with an old version of browser, add more precise error message
=> [Unity] Improve error message in webgpu request

python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_from_fx.py
Previously, if we have a Torch model with multiple return values like:
```
class Mod(nn.Module):
...
def forward(...):
...
return logits, loss
```
The translator will always bind the return tuple to a Relax var and return it:
```
gv: R.Tuple(...) = (logits, loss)
return gv
```
This brings inconvenience if we want to use `Gradient` pass to set the loss as the target (i.e. set `target_index=1`). Because if the return value is a single Relax var, the `Gradient` pass will not take it as multiple return values.
This PR brings a flag to let user choose between different return styles. If the user set `no_bind_return_tuple = True`, they will get
```
return (logits, loss)
```
=> [Unity][Frontend] Add `no_bind_return_tuple` for PyTorch FX Translator

web/src/webgpu.ts
Using powerPreference with "high-performance" as value lets WebGPU use the card with the most performance.
=> Adding powerPreference argument to navigator.gpu.requestAdapter

docker/bash.sh, docker/dev_common.sh
The `docker/bash.sh` script should omit the `--pid=host` argument and `docker/with_the_same_user` arguments when the host's docker daemon is running in [rootless mode](https://docs.docker.com/engine/security/rootless/).  The `with_the_same_user` script is unnecessary in this mode, as rootless docker daemons already use the privileges of the user.
The `--pid=host` flag is required when running in CI, and while it may be useful when running tests locally, it is only supported for rootless docker in versions docker versions 22.06 or greater ([requires this commit](https://github.com/moby/moby/pull/41893)).
=> [Docker] Support rootless docker when using docker/bash.sh

src/meta_schedule/schedule_rule/auto_inline.cc, tests/python/unittest/test_meta_schedule_schedule_rule_auto_inline.py
Now the InlineConstantScalars rule will inline all blocks with no reads and only one scalar output. 
However, if such block is an output block, it should not be inlined. For example, `topi.full((), "float32", 1.0)` contains only one block, which should not be inlined.
This PR fixes this problem by skipping output blocks in the InlineConstantScalars rule.
cc @vinx13
=> [MetaSchedule] Handle output cases for InlineConstantScalars

python/tvm/relax/backend/contrib/cutlass.py, tests/python/relax/test_codegen_cutlass.py
In SD UNet, I met a pattern `conv2d -> bias_add -> residual_add` where the input shape is `(2, 16, 16, 1280)` and the residual input shape is `(2, 1, 1, 1280)`. Such general broadcast add for the residual block is not supported by cutlass. 
This was the cause of `nan` output when using the cutlass BYOC with an improved AMP pass (that allows bias add to be done in fp16, PR later).
@vinx13 @yelite @spectrometerHBH
=> [Unity][CUTLASS] Require the residual input to have the same shape as input

src/runtime/metal/metal_device_api.mm
This PR aims to fix a relatively rare flaky race issuse when we are attempting to purge memory and the buffer is still in use in command buffer
=> [METAL] Fix flaky memory issue due to racing

src/target/source/codegen_webgpu.cc, web/src/webgpu.ts, web/tests/python/webgpu_rpc_test.py
This PR improves webgpu codegen to handle large launch grid.
Background: webgpu do not allow grid size bigger than 65535 so we have to factorize the gridDim.x when it is too big and spread it across gridDim.x and gridDim.z.
This approach however is not always possible. This PR pass in extra parameter packDimX which records the original requested dim overpad if factorization is not possible and immediately returns if the index is out of bound
=> [Unity] Improve WebGPU codegen for large grid

src/runtime/vm/executable.cc
This "LOG(FATAL)" will error out when the function isn't found in “executable”, so it will prevent the recursive query the function in the imported modules of "executable".
For example, if the module hierarchy is something like below.
executable
|---LLVMModuleNode
|___NPUModuleNode
This bug will cause we can't get the function in NPUModuleNode by the call "executalbe.get_function("npu_func1", query_imports=True)".
From Arm China.
=> [Runtime] Fix Can't "query_imports" Bug of VM Executable

src/meta_schedule/module_equality.cc, src/node/ndarray_hash_equal.h, src/node/structural_hash.cc, src/relax/ir/block_builder.cc
I found that if I use `BindParams` early in my BYOC workflow, some Relax passes become extremely slow. For example, `partition_for_cutlass` takes more than 40 sec on SD UNet if parameters are bound, while otherwise it only takes 1 sec.
This massive regression is due to the `unordered_map` used by `BlockBuilder`, https://github.com/apache/tvm/blob/unity/src/relax/ir/block_builder.cc#L381-L382
This map is keyed on `BaseFunc` and it uses structural equal / hash. So if large parameters are bound on each func, those params are hashed / compared repeatedly. 
This is solved by introducing a custom struct hash that ignores NDArray content.
@tqchen @Hzfengsy @slyubomirsky
=> [Unity] Use custom hash in `BlockBuilder` to avoid hashing large constants

python/tvm/relay/frontend/tflite.py, tests/python/frontend/tflite/test_forward.py
In line with the TFLu implementation, this commit
enables mapping of quantized squared difference
to Relay's float32 squred difference.
cc @leandron
=> [TFLite][Frontend] Support for quantized squared difference

tests/scripts/task_config_build_cpu.sh
The upgrade to llvm 15 caused failures in topi tests python/topi/python/test_topi_math.py::test_cast[float64-float16-llvm]. It seems to be a miscompilation due to opaque pointers. Downgrading while working to fix the issue.
=> [CI] Downgrade ci_cpu llvm version back to 11

web/src/webgpu.ts
This is a hotfix to update webgpu runtime and fix behavior when there is no pod params.
=> [WebGPU] This PR fixes the webgpu runtime when there is no pod params

python/tvm/relax/transform/__init__.py, src/relax/transform/meta_schedule.cc, tests/python/relax/test_transform_meta_schedule_tuning.py
To track the state of transformation during joint-optimization, current TuningAPI manages two copies of IRModule in `Trace`. 
However, it becomes a problem for large models because we need to copy their parameters as well. 
As we only have a single tuning pass for MetaSchedule now, this PR temporarily disables the usage of `Trace` to unblock the tuning of large models. Upcoming PR will refactor this. 
cc. @masahi
=> [Unity][TuningAPI] Temporary patch for large models 

src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops.py
Previously, FuseOps does not take PrimValue into account and will error on PrimValues for a sanity check inside. This PR supports FuseOps with PrimValues so that FuseOps will skip the PrimValues - no need to handle them in a special way.
One regression test is added.
=> [Unity] FuseOps skipping PrimValues

src/relax/transform/combine_parallel_matmul.cc, tests/python/relax/test_transform_combine_parallel_matmul.py
A follow-up to https://github.com/apache/tvm/pull/14583. I found that using `strided_slice` #branches times is quite inefficient. `split` is a much better way to achieve the same thing.
@vinx13 @cyx-6
=> [Unity] Use split rather than slice in `CombineParallelMatmul`

python/tvm/contrib/tvmjs.py, src/runtime/relax_vm/ndarray_cache_support.cc, tests/python/relax/test_runtime_builtin.py, web/Makefile, web/emcc/wasm_runtime.cc, web/src/runtime.ts
This PR moves NDArrayCache support to relax runtime so it can be used in other native settings.
=> [Unity][WebGPU] Move NDArrayCache Support to relax runtime

cmake/utils/FindCUDA.cmake
The FindCUDA looks for the various libraries in a more or less limited set of locations.
For nvrtc we currently have the most complete search, the others are lacking one or more locations.
This makes FindCUDA look in all typical linux lib dirs (e.g. Debian's CUDA install wants that).
Thank you for considering.
=> unify search path approach to various libs

python/tvm/relax/transform/legalize_ops/linear_algebra.py, tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py
This PR changes a behavior of the legalization of matmul, so that we do not use 0 as indices in the generated TIR in certain case.
Since the matmul op supports broadcasting and batching, previously when legalizing a matmul op, for the broadcasting dimensions, we will emit indices "0" for those broadcasting dimensions with length 1. For example, the code below is a TIR produced by matmul legalization.
```python
@T.prim_func
def matmul(A: T.Buffer((T.int64(1), T.int64(1), T.int64(4), T.int64(5)), "float32"), B: T.Buffer((T.int64(1), T.int64(1), T.int64(5), T.int64(7)), "float32"), matmul_1: T.Buffer((T.int64(1), T.int64(1), T.int64(4), T.int64(7)), "float32")):
T.func_attr({"tir.noalias": T.bool(True)})
for i0, i1, i2, i3, k in T.grid(T.int64(1), T.int64(1), T.int64(4), T.int64(7), …
```
=> [Unity][Op] Avoid indices in TIR matmul being 0 in legalization

src/relax/transform/meta_schedule.cc, tests/python/relax/test_transform_meta_schedule_apply_database.py
This PR fixes an issue in MetaScheduleApplyDatabase, which uses the IRModule being queried as the base module of TIR Schedule. This will cause the inconsistency between the IRModule being scheduled and the trace of the record. For example, the trace of the record may have `get-block` instructions which tries to get block from a given name, which exists in the IRModule of the record while does not exist in the IRModule being queried (which is right the IRModule being scheduled).
Therefore, this PR adds a case discussion. When anchor-op equality is not applied, we create the TIR schedule from the IRModule of the record, so that we can prevent the issue above from happening.
This PR adds a unit test that can demonstrate the issue.
=> [Unity] MetaScheduleApplyDatabase using workload from records

src/arith/iter_affine_map.cc, src/arith/rewrite_simplify.cc, tests/python/unittest/test_arith_canonical_simplify.py, tests/python/unittest/test_arith_iter_affine_map.py, tests/python/unittest/test_arith_rewrite_simplify.py, tests/python/unittest/test_tir_transform_inject_software_pipeline.py
cherry-pick https://github.com/apache/tvm/pull/14571 to **v0.12.0**
cc @junrushao
=> [cherry-pick][ARITH][BUGFIX] Fix a bug of iter map floormod(x,2) simplify

python/tvm/relax/backend/contrib/cutlass.py, src/relax/op/nn/attention.cc, src/relax/transform/fold_constant.cc, src/relax/transform/to_mixed_precision.cc, tests/python/relax/test_transform_to_mixed_precision.py
Currently in AMP, the decision to insert a cast to fp32 is overly conservative. In particular, if the bias is fp32, the fp16 activation is cast back to fp32 instead of keeping it to fp16 and casting bias to fp16. So it results in a lot of patterns like below. 
```
lv16: R.Tensor((2, 1280), dtype="float16") = R.matmul(lv1_1, lv2_1, out_dtype="float16")
lv3_1: R.Tensor((2, 1280), dtype="float32") = R.astype(lv16, dtype="float32")
lv17: R.Tensor((2, 1280), dtype="float32") = R.add(lv3_1, unet_time_embedding_linear_1_bias)
```
This PR reduces the number of unnecessary cast to fp32 by checking the range of a constant argument. If it fits within fp16, there is no need to cast it to fp32, and if all args are fp16 or castable to fp16, we can keep activations to fp16.
Also added AMP support for …
=> [Unity] Reduce cast to fp32 for constant input in AMP

include/tvm/tir/analysis.h, python/tvm/tir/analysis/analysis.py, src/tir/analysis/calculate_allocated_memory.cc, tests/python/unittest/test_tir_analysis_calculate_allocated_memory.py
This patch modifies the existing analysis pass
`tir.calculate_allocated_bytes` to accept an IRModule as an argument and return allocated bytes for all prim_funcs in the IRModule.
=> [TIR] [Analysis] Calculate allocated memory at module level

python/tvm/relax/training/__init__.py, python/tvm/relax/training/setup_trainer.py, python/tvm/relax/training/trainer.py, tests/python/relax/test_training_setup_trainer.py, tests/python/relax/test_training_trainer_numeric.py
This PR adds two utilities to simplify the training process: Trainer and SetupTrainer.
SetupTrainer is basically a pass, transforming a backbone module to a complete, legalized trainer module. It is a combination of Gradient pass, loss function, optimizer, AppendLoss pass, LegalizeOps, etc. You can store the trainer module into a file and load it to somewhere else.
Trainer is a runtime utility that accepts the IRModule (that is the result of SetupTrainer) and the relax VM (that contains the built result of the IRModule), and helps run the VM. It maintains the parameters, the model states and the optimizer states internally.
Co-authored-by: Chaofan Lin <siriusneo@sjtu.edu.cn>
=> [Unity][Training] Trainer and SetupTrainer

ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/generated/cortexm_jenkinsfile.groovy, ci/jenkins/generated/cpu_jenkinsfile.groovy, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/generated/hexagon_jenkinsfile.groovy, ci/jenkins/generated/i386_jenkinsfile.groovy, ci/jenkins/generated/lint_jenkinsfile.groovy, ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy, ci/jenkins/generated/minimal_jenkinsfile.groovy, ci/jenkins/generated/riscv_jenkinsfile.groovy, ci/jenkins/generated/wasm_jenkinsfile.groovy, ci/jenkins/templates/arm_jenkinsfile.groovy.j2, ci/jenkins/templates/cortexm_jenkinsfile.groovy.j2, ci/jenkins/templates/cpu_jenkinsfile.groovy.j2, ci/jenkins/templates/gpu_jenkinsfile.groovy.j2, ci/jenkins/templates/hexagon_jenkinsfile.groovy.j2, ci/jenkins/templates/i386_jenkinsfile.groovy.j2, ci/jenkins/templates/minimal_cross_isa_jenkinsfile.groovy.j2, ci/jenkins/templates/minimal_jenkinsfile.groovy.j2, ci/jenkins/templates/riscv_jenkinsfile.groovy.j2, ci/jenkins/templates/utils/base.groovy.j2, ci/jenkins/templates/utils/macros.j2, ci/jenkins/templates/wasm_jenkinsfile.groovy.j2
This exposes the env var `PLATFORM` during builds so we can use it to
differentiate builds at runtime.
=> [ci] Add PLATFORM env var to builds

include/tvm/tir/analysis.h, python/tvm/tir/analysis/analysis.py, python/tvm/topi/hexagon/utils.py, src/meta_schedule/postproc/verify_vtcm_limit.cc, src/tir/analysis/calculate_allocated_memory.cc
This patch adds a utility function for getting the VTCM sizes allocated in an IRModule. In order to do that, we've exposed the list of lowering passes to python and we've refactored the PostprocVerifyVTCMLimit to be computed for whole module and the same list of lowering passes
=> [TIR] [Hexagon] Add get_vtcm_allocation_sizes with lowering

python/tvm/contrib/cutlass/attention_operation.py
We are doing `cudaMalloc` on every call to the CUTLASS attention kernel, but we are not freeing the allocated memory. This leads to a serious problem for SD UNet. Thanks @jwfromm for finding the memory leak problem.
https://github.com/apache/tvm/blob/b98ba5568eb01e54f48f0b49e232b78ce44de935/python/tvm/contrib/cutlass/attention_operation.py#L118-L123
This makes me realize that we are doing the same alloc / free on every call to attention. Instead, it is desirable to allocate once and use the same allocation throughout. AITemplate does this, apparently. 
@cyx-6 @jwfromm
=> [Unity][CUTLASS] Fixed memory leak in attention kernel offload

src/runtime/metal/metal_module.h, src/runtime/metal/metal_module.mm, src/target/opt/build_metal_off.cc, src/target/source/codegen_metal.cc
This PR updates the metal runtime storage format to directly store the kernel map.
This will enable more robust support to
leverage metallib binary format which may not
be compatible with previous string split.
It changes the binary format of the metal module.
We also added a version to enable easier future update.
=> [METAL] Update metal runtime to directly store kernel map

python/tvm/contrib/cutlass/build.py, tests/python/relax/test_codegen_cutlass.py
When a single expression, such as `R.shape([2, 4096, 8, 40])` is used by all `reshape` for QKV, the following composite function that only gets one shape parameter is generated. This is currently not handled properly by codegen.
```
@R.function
def fused_relax_split_relax_reshape_relax_reshape_relax_reshape_relax_nn_attention_cutlass(qkv: R.Tensor((4, 8, 6144), dtype="float32"), param_0: R.Shape([4, 8, 32, 64])) -> R.Tensor((4, 8, 32, 64), dtype="float32"):
R.func_attr({"Codegen": "cutlass", "global_symbol": "fused_relax_split_relax_reshape_relax_reshape_relax_reshape_relax_nn_attention_cutlass"})
@R.function
def gv_1(qkv_1: R.Tensor((4, 8, 6144), dtype="float32"), param_0_1: R.Shape([4, 8, 32, 64])) -> R.Tensor((4, 8, 32, 64), dtype="float32"):
R.func_attr({"Composite": …
```
=> [Unity][CUTLASS] Fixed stacked attention offload when QKV reshape uses the same shape expression

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/to_mixed_precision.cc, tests/python/relax/test_transform_to_mixed_precision.py
When a user doesn't want to bind params at compile time and still benefit from AMP, it is important that these params are provided at runtime as fp16 tensors. Otherwise the conservative nature of AMP kicks in and we end up with lots of cast to fp32 before bias add etc. Also when the same model is executed many times with runtime weights (e.g. SD UNet), we would end up casting input fp32 weights repeatedly in the inference loop.
To allow ingesting fp16 tensors as input, this PR lets users provide a list of parameter names whose dtype should become fp16 at runtime.
cc @spectrometerHBH
=> [Unity] Allow modifying function signature by AMP to accept fp16 inputs 

include/tvm/tir/data_type_rewriter.h, src/tir/ir/data_type_rewriter.cc, src/tir/transforms/force_narrow_index_to_i32.cc, tests/python/unittest/test_tir_transform_force_narrow_index_to_i32.py
This PR fixes the forece narrow to i32 pass so it ignores integer with smaller bitwidth
=> [Unity] Fix ForceNarrowIndexToI32 so it ignores i16

ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/generated/cortexm_jenkinsfile.groovy, ci/jenkins/generated/cpu_jenkinsfile.groovy, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/generated/hexagon_jenkinsfile.groovy, ci/jenkins/generated/i386_jenkinsfile.groovy, ci/jenkins/generated/lint_jenkinsfile.groovy, ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy, ci/jenkins/generated/minimal_jenkinsfile.groovy, ci/jenkins/generated/riscv_jenkinsfile.groovy, ci/jenkins/generated/wasm_jenkinsfile.groovy, ci/jenkins/templates/docker_jenkinsfile.groovy.j2, ci/jenkins/templates/utils/Prepare.groovy.j2, src/arith/bound_deducer.cc, src/arith/canonical_simplify.cc, src/arith/pattern_match.h, tests/python/unittest/test_arith_deduce_bound.py
This disables the merge to main behavior for this branch and includes the code #14725 to get this to pass CI. This also disables the docker GPU build which is currently broken on this branch and has no bearing on the release (and is being built erroneously anyways since this PR has no docker changes).
=> [cherry-pick][ARITH] Enhance CanonicalSimplify to Simplify ProdDiv and [ci] disable merge

python/tvm/meta_schedule/relax_integration.py, python/tvm/relax/transform/transform.py, src/relax/transform/meta_schedule.cc, tests/python/relax/test_transform_meta_schedule_tuning.py
Currently, `MetaScheduleTuneIRMod` pass only has `max_trials_global` param to control the duration of tuning. Now that we have good BYOC support and `DefaultGPUSchedule` pass, we should add more options to allow more fine-grained tuning. 
For example, in SD UNet, I want to tune only layer and group norm, for small number of trials each. And I don't want to spend any seconds "tuning" trivial ops such as `cast`, `concat` etc. 
To realize these goals, I'm adding `max_trials_per_task` and `op_names` params. The latter is used to select which op to tune. For SD UNet I'd use it like `op_names=["layer_norm", "group_norm"]`.
@sunggg @zxybazh
=> [Unity] Add options to MS tuning pass to enable more fine-grained tuning

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
The `alpha` attribute in LeakyReLU lacks exception checking. If the `alpha=nan` , the keras frontend can convert it to relay ir successful, but in the optimization stage, it will trigger an  unexpected crash and throws `TVMError: Observed 100 rewrite passes, possible conflicting passes?`
The relay IR is the following:
This patch fixes the bug!
The StackTrace:
```
model = relay.build_module.create_executor("graph", mod, tvm.cpu(0), 'llvm', params).evaluate()  # crash
File "/workplace/software/tvm/tvm/python/tvm/relay/backend/interpreter.py", line 171, in evaluate
return self._make_executor()
File "/workplace/software/tvm/tvm/python/tvm/relay/build_module.py", line 519, in _make_executor
mod = build(self.mod, target=self.target)
File …
```
=> [Keras][Bugfix] fix a bug about alpha attribute in LeakyReLU which lead to passes conflict

conda/recipe/meta.yaml, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/package.json
This bumps all the **version numbers on v0.12.0 branch** as correct **v0.12.0**.
cc @driazati @Johnson9009 @junrushao
=> [release] Bump version numbers to 0.12.0

include/tvm/tir/transform.h, python/tvm/tir/transform/transform.py, src/tir/analysis/block_access_region_detector.cc, src/tir/schedule/primitive.h, src/tir/schedule/primitive/block_annotate.cc, src/tir/transforms/compact_buffer_region.cc, src/tir/transforms/ir_utils.cc, src/tir/transforms/ir_utils.h, src/tir/transforms/lower_opaque_block.cc, tests/python/unittest/test_tir_buffer.py, tests/python/unittest/test_tir_transform_compact_buffer_region.py
Hi there, the change want to enforce the power and flexiblity of `CompactBufferAllocation` pass in two aspects:
1. Free of pass order
- It could work on both s-tir (with opaque blocks) and lowered tir. For example, now one could be able to invoke `LoopPartition` and then make partitioned tile aware buffer compactions.
- We test existing cases to ensure that 
`(LowerOpaqueBlock . CompactBufferAllocation) (mod) == (CompactBufferAllocation . LowerOpaqueBlock) (mod)` 
2. Allow "non-strict" compaction
- Add an option `is_strict` defaults to `True`, to denote that during compaction we should respect the original buffer shape bound. Thus the compacted buffer region never exceed the original.
- If set to `False`, the "compacted" shape is totally determined to cover buffer region accesses. Thus it …
=> [TIR] More flexible buffer compaction

python/tvm/contrib/cutlass/attention_operation.py, python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/contrib/cutlass/layer_norm_operation.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/backend/patterns.py, tests/python/relax/test_codegen_cutlass.py
Layer norm in SD UNet is expensive and so far we've been using MS tuning for it. CUTLASS has a layer norm kernel which I found to be more than 2x faster than a MS-tuned one on SD workloads.  
@cyx-6 @yelite
=> [Unity][CUTLASS] Add layer norm support

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
This Pr tries to fix the bug in https://github.com/apache/tvm/issues/14661
=> [Relay][Bugfix] Fix stride in LpPool for default

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
support aten::new_zeros in frontend of pytorch.
=> [PyTorch]  Add aten::new_zeros

src/relay/transforms/simplify_expr.cc, tests/python/relay/test_pass_simplify_expr.py
Simplifies the expression of form axx + bxy + cyy to (x+p*y)(x+q*y).
Also added the appropriate test.
=> [Relay] Simplify the square of a binomial

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This patch fixes a bug in ELU. when the alpha=None, It will lead to a wrong compilation and give a confusing inference result.
For example, the following script will produce inconsistent inference results between TVM and Keras. However, we hope tvm can reject it immediately in the model loading stage. Because the model is invalid (see Line 210-212 in [keras source code file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/advanced_activations.py)). 
This PR is a similar fix to the [pr-14707](https://github.com/apache/tvm/pull/14707). pr-14707 fixed a similar bug in  LeakyReLU.
```
import tvm
from tensorflow.keras import layers, models
input_shape = (1, 2, 3, 4)
input_data = …
```
=> [bugfix][relay] Fix alpha attribute with None in ELU 

src/relax/ir/py_expr_functor.cc, tests/python/relax/test_expr_functor.py
It will run into an infinite recursion if we call super().visit_var_binding_ in PyExprVisitor and PyExprMutator. This PR fixes the behavior.
cc: @tqchen @MasterJH5574
=> Fix super().visit_var_binding_ in PyExprVisitor and PyExprMutator

include/tvm/runtime/relax_vm/bytecode.h, python/tvm/relax/op/vm/vm.py, src/relax/backend/vm/codegen_vm.cc, src/relax/backend/vm/codegen_vm_tir.cc, src/relax/backend/vm/vm_builtin_lower.cc, src/relax/op/op.cc, src/runtime/relax_vm/builtin.cc, src/runtime/relax_vm/vm.cc, tests/python/relax/test_op_misc.py, tests/python/relax/test_transform_static_plan_block_memory.py, tests/python/relax/test_vm_codegen_only.py
This PR lowers `memory.kill_tensor` and `memory.kill_storage` ops to a runtime function "`kill_object`" that releases the corresponding NDArray of the "tensor" and "storage" in VM at runtime.
Previously these two ops are just ignored and skipped in VMBuiltinLower, and the "kills" didn't take effect. This PR supports the "real kill" so that the VM will release the NDArrays upon kill, and get better memory management for us.
=> [Unity][VM] `kill_tensor` and `kill_storage` releasing NDArray in VM at runtime

python/tvm/meta_schedule/logging.py
This little one liner prevents metaschedule from creating logs with names so large they are invalid for the host operating system. Here we limit to 100 characters for the function name, which should be plenty to make it clear to the user which function corresponds to the log.
=> [Unity] Limit number of characters in logger names

python/tvm/topi/arm_cpu/depthwise_conv2d.py
Depthwise Conv2D operations may consists of a convolution + an output operator e.g. Relu. This commit will:
* Apply vectorization across the inner channel loop when there is an output operator.
* Remove some unused variables in `schedule_depthwise_conv2d_nhwc`.
=> [TOPI] Vectorize depthwise conv2d output operator

python/tvm/relax/frontend/torch/fx_translator.py
PR 14639 introduces the `no_bind_return_tuple` flag to FX translator. That PR fails two unit tests in `test_frontend_dynamo.py`. This failure is not revealed in CI because CI doesn't yet have torch dynamo and does not test the file.
This PR fixes the issue. The tests can now pass at my local side.
=> [Unity] Fix FX translator no output issue

src/tir/schedule/primitive/blockize_tensorize.cc, tests/python/unittest/test_tir_schedule_tensorize.py
TIR TensorIntrin implementation may contains some annotation. Current logic will skip all existing annotations. But in some cases it may be helpful to transfer annotations to resulting schedule.
=> [TIR] Keep block annotations from tensorization

src/target/tag.cc
As per request from [tvm forum](https://discuss.tvm.apache.org/t/how-to-set-target-nvidia-a6000/14850), A6000 target tag is added together with source for future reference.
=> [Target][Minor] Add A6000 Target Tag

tests/scripts/ci.py
sccache fails to start while multiple users in same environment. Now we can export SCCACHE_SERVER_PORT with different port and use.
=> [CI] sccache support while using ci.py under multi user environments

python/tvm/script/parser/tir/parser.py, tests/python/unittest/test_arith_domain_touched.py, tests/python/unittest/test_tvmscript_syntax_sugar.py
Prior to this commit, the `bind_assign_value` implementation for TIR would treat assignment of constants (e.g. `j = 42`) as meta-variables to be inserted at their point of use.  This commit updates the parsing to treat `j = 42` as a shorthand for the TIR `LetStmt`, similar to the update made in https://github.com/apache/tvm/pull/14320.  This behavior is more consistent with the other uses of `bind_assign_value` as assignment, with `j = T.meta_var(42)` used to represent meta-variables.
=> [TVMScript] Preserve LetStmt of constants

src/driver/driver_api.cc, src/tir/transforms/primfunc_utils.cc
Prior to this commit, the `MixedModulePassManager` determined whether the module should have its entry function annotated, while the `AnnotateEntryFunc` validates that this condition was upheld, duplicating the logic applied.  This commit moves the logic to `AnnotateEntryFunc`, which is unconditionally called from the `MixedModulePassManager`, but which is a no-op for cases where no annotation is required.
=> [TIR][Driver] Move ShouldAnnotateEntryFunc logic into transform

python/tvm/meta_schedule/runner/config.py
This PR introduces a bugfix where the RPC port could be mistakenly detected as a string from environment variables, which is required to be an integer for subsequent operators. We cast the type to int in auto detection.
=> [Bugfix][MetaSchedule] RPC port needs to be an integer

src/target/source/codegen_cuda.cc
The current HEAD will emit the inlined assembly that mistakenly include type casting, which is not allowed syntax, for example:
```c++
__asm__ __volatile__("cp.async.wait_group (int64_t)2;");
````
This commit fixes this bug.
=> [Bugfix][Codegen][CUDA] Wrong casting in ASM

src/meta_schedule/utils.h
MetaSchedule clears screen by default at the moment, which means previous warnings and error messages are flushed away even if they are helpful in debugging. This PR changes the behavior by requiring the env variable `TVM_META_SCHEDULE_CLEAR_SCREEN` to enable screen clearing.
=> [MetaSchedule] Clear screen only when specified

src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level3.py
```python
import tvm
def should_pass():
data = relay.const(np.zeros([1,1,10], 'float32'))
indices = relay.const(np.ones([2,1,1,1], 'int64'))
updates = relay.const(np.random.rand(1,1,1,10).astype('float32'))
scatter_nd = relay.scatter_nd(data, indices, updates)
mod = tvm.IRModule.from_expr(scatter_nd)
mod = relay.transform.InferType()(mod)
def should_fail():
data = relay.const(np.zeros([1,1,10], 'float32'))
indices = relay.const(np.ones([2,1,1], 'int64'))
updates = relay.const(np.random.rand(1,1,5).astype('float32'))
scatter_nd = relay.scatter_nd(data, indices, updates)
mod = tvm.IRModule.from_expr(scatter_nd)
mod = relay.transform.InferType()(mod)
```
case `should_pass` will report a error
> Check failed: (0 <= i && i < p->size_) is false: …
=> [BugFix][Relay] fix `scatter_nd` type relation

python/tvm/script/parser/ir/entry.py, python/tvm/script/parser/tir/entry.py, tests/python/unittest/test_tvmscript_parser_ir.py, tests/python/unittest/test_tvmscript_parser_tir.py
This PR adds `__name__` attr to indicate the func/mod name for parsed PrimFunc and IRModule.
cc @tqchen @cyx-6
=> [TVMScript] Add `__name__` attr for parsed PrimFunc and IRModule

src/runtime/relax_vm/lm_support.cc
This PR updates the LM sample routine builtins.
Make the sample from logits aware of temperature.
Add sample from prob that samples from probablity
distribution after softmax scaling.
=> [Unity] Update LM Sample builtins

LICENSE, licenses/LICENSE.cnpy.txt
This PR improves ref of liceneses of thirdparty we depend on. Not a blocker for anything as previous state was fine, just to improve overall clarity.
=> More clear ref of thirdparty license

include/tvm/meta_schedule/database.h, python/tvm/meta_schedule/database/database.py, src/meta_schedule/database/database.cc, src/meta_schedule/database/json_database.cc, src/meta_schedule/database/memory_database.cc, src/meta_schedule/module_equality.cc, src/meta_schedule/module_equality.h
This PR introduces the `Database.dump_pruned` API, which makes possible to keep the only optimal record for the workload on disk for easy re-distribution of a MetaSchedule database.
=> [MetaSchedule] Add an API to dump a pruned database

python/tvm/contrib/torch/as_torch.py, python/tvm/meta_schedule/space_generator/space_generator.py, python/tvm/meta_schedule/testing/tune_te.py, python/tvm/meta_schedule/tir_integration.py
This PR enhances the user-facing API `tune_tir` that makes it more convenient to feed in an IRModule consists of multiple TIRs and customize the search space for them. This is widely used in our MLC-LLM project where we wanted to customize the search space for some quantization-related operators.
An example usecase:
```python
from tvm import meta_schedule as ms
ms.tir_integration.tune_tir(
...
space="cuda",  <========== by default, the space is "cuda" rather than "cuda-tensorcore"
special_space={
"fused_decode1_fused_matmul2_add1_gelu": sch_fused_decode_gemv,
"decode": sch_decode,
},
)
```
=> [MetaSchedule] Enhance `tune_tir` to tune IRModule of TIR Collections

python/tvm/relax/transform/__init__.py, python/tvm/relax/transform/lazy_transform_params.py, tests/python/relax/test_transform_lazy_transform_params.py
Currently the transform_params function lifted by LiftTransformParams will first load all inputs into memory, and transform. That may exceed memory limit. The better way is to load the input to memory on demand, and immediately free it after the last use. This PR implements such method. It replaces all `params[i]` with `get_item(i)` and inserts `set_item(i)` and `kill_object` after the last use except in return stmt.
cc: @tqchen @MasterJH5574
=> [Unity][Pass] Lazy transform params

python/tvm/relax/op/_op_gradient.py, python/tvm/relax/op/binary.py, tests/python/relax/test_op_gradient_numeric.py
This PR introduces gradient functions for the following Relax operators:
- `R.maximum`
- `R.triu`
- `R.broadcast_to`
- `R.silu`
- `R.minimum`
=> [Unity][Training] More Relax operators gradient supported

src/tir/transforms/arg_binder.cc, tests/python/unittest/test_runtime_dlpack.py
As discussed in https://github.com/pytorch/pytorch/issues/99803, as of PT 1.13, PT started to fill in a stride with 1 whenever the corresponding shape axis has size 1 during PT tensor to DLPack conversion. This breaks `tvm.runtime.ndarray.from_dlpack` when the shape is like `(1, 77)` (clip for SD) or whenever the batch size is 1 in vision models. So this is going to be a common problem that people would encounter in practice (see https://discuss.tvm.apache.org/t/a-pytorch-and-tvm-version-incompatibility-problem-while-using-from-dlpack-and-to-dlpack/14771).
This PR fixes this issue by relaxing the runtime stride check. An alternative is to modify the strides during `from_dlpack`, but since PT introduced this change for a good reason, I felt that trying to calculate the "correct" strides on …
=> [NDArray] Allow arbitrary stride when the corresponding shape is 1

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
The calculation formula of `CELU` is wrong in relay/pytorch. This pr fix it.
From the [pytorch documentation](https://pytorch.org/docs/1.7.1/generated/torch.nn.CELU.html?highlight=celu#torch.nn.CELU), we can get the calculating logic of CELU.  
```
import torch
import tvm
m = torch.nn.CELU()
input_data = torch.tensor([[-1.0, 2.0]], dtype=torch.float32)
torch_outputs = m(input_data)
trace = torch.jit.trace(m, input_data)
input_shapes = [('input0', torch.Size([1,2]))]
mod, params = relay.frontend.from_pytorch(trace, input_shapes)
with tvm.transform.PassContext(opt_level=3):
exe = relay.create_executor('graph', mod=mod, params=params, device=tvm.device('llvm', 0), target='llvm').evaluate()
input_tvm = {'input0': np.array([[-1.,  2.]], …
```
=> [bugfix][relay] fix wrong calculate logic about celu

python/tvm/contrib/cutlass/build.py
I found that adding this option brings non-trivial perf improvement to the attention kernel (2.4 vs 2.7 msec for the most heavy workload in SD UNet, see below). This results in a few msec speed up for SD UNet e2e.
Before (nvprof output on `test_attention_offload((2, (4096, 4096), 8, (40, 40), "float16)`)
```
Time (%)  Total Time (ns)  Instances   Avg (ns)     Med (ns)    Min (ns)   Max (ns)   StdDev (ns)     GridXYZ         BlockXYZ                       
Name                                                 
--------  ---------------  ---------  -----------  -----------  ---------  ---------  -----------  --------------  --------------  ------------------
----------------------------------------------------------------------------------
100.0        8,325,790          3  2,775,263.3 …
```
=> [CUTLASS] Add NDEBUG option to CUTLASS compile to speed up attention kernel

tests/lint/git-clang-format.sh
In the new clang-format, git-clang-format will exit 1 when there is diff, this PR ensures that the diff is show in ci log
=> [LINT] Fix clang-format script for newest clang-format

python/tvm/contrib/cutlass/gemm_operation.py, tests/python/relax/test_codegen_cutlass.py
This PR makes the cutlass codegen use the correct bias stride when bias has more than 2 dimensions. For example, if the input bias has shape (1, n, 4096), the original code will set ldc to 0, which produces incorrect result. This enables offloading matmul in LLaMA.
The same PR is merged in mlc relax https://github.com/mlc-ai/relax/pull/212. 
=> [Unity][BYOC] Fix incorrect bias stride in matmul cutlass offload

python/tvm/testing/utils.py
Prior to this commit, the `tvm.testing.CompareBeforeAfter` utility performed string replacement to define the names of the before/after/expected examples.  Since https://github.com/apache/tvm/pull/13934 allowed the name to be explicitly passed to the printer, this should be used instead.
=> [Testing] Use TVMScript's "name" argument for error messages

include/tvm/relax/expr.h, python/tvm/contrib/cutlass/attention_operation.py, python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/transform/transform.py, src/relax/backend/vm/codegen_vm.cc, src/relax/ir/block_builder.cc, src/relax/op/op_common.h, src/relax/transform/allocate_workspace.cc, src/relax/transform/provide_workspace.cc, tests/python/relax/test_codegen_cutlass.py, tests/python/relax/test_transform_allocate_workspace.py
As discussed in https://github.com/apache/tvm/pull/14723, some cutlass kernels, in particular the attention kernel, require temporary storage to hold intermediate results. This results in repeated calls to cudaMalloc/Free, and the bug like #14723. 
This PR adds a pass that allocate a big workspace at the beginning of `main` and threads that through all functions that need temp storage. This lets us eliminate all redundant malloc / free, and improves e2e perf slightly. 
An external function can specify its workspace requirement by the `kWorkspaceSize` attribute. See how it is done for the cutlass attention kernel for example. 
@vinx13 @cyx-6 @yelite
=> [Unity] Add pass to allocate big workspace and pass it to all functions that need temp storage  

python/tvm/relax/backend/contrib/cublas.py, python/tvm/relax/testing/matmul.py, src/runtime/contrib/cublas/cublas_json_runtime.cc, tests/python/relax/test_codegen_cublas.py, tests/python/relax/test_codegen_cutlass.py
This PR adds more logic on bias shape in cuBLAS partitioning. This prevents matmul with residual input to be offloaded to cuBLAS as matmul with bias. cuBLAS only support 1D bias input.
This PR also fixes the type key for cublas json runtime, so that it can be deserialized correctly.
cc @masahi @vinx13
=> [Unity][BYOC] Add shape validation for bias arg in cuBLAS

jvm/pom.xml, src/runtime/relax_vm/ndarray_cache_support.cc
OpenCL runtime may allocate mirror memory
for device memory that serves as host copy target.
This PR uses a staging buffer for parameter load
to avoid this problem.
Authored by Tianqi.
----
Co-authored-by: Tianqi Chen <tqchenml@gmail.com>
=> [Unity] NDArray Cache Efficient Load in OpenCL

src/tir/transforms/make_packed_api.cc, tests/python/relay/aot/test_crt_forward_declarations.py
Previously, the parameter name depending only on the TIR variable name.  In large IRModules, such as those used when executing end-to-end models, these parameter names may be resued across functions, and so the error message doesn't identify which `PrimFunc` should be investigated.
This commit updates the parameter name to include the function name (e.g. `my_function.arg.my_param`) to help debugging in these cases.
=> [TIR] Improved parameter name in DLTensor unpacking error messages

include/tvm/tir/usmp/utils.h, python/tvm/ir/memory_pools.py, src/script/printer/tir/usmp.cc
These objects may appear as part of a TIR PrimFunc following the `tir.usmp.ConvertPoolAllocationsToOffsets` transform.  Prior to this commit, any such PrimFuncs would result in errors when printing TVMScript, along with a fallback to the legacy repr.
=> [TVMScript] Handle AllocatedPoolInfo, ConstantPoolInfo, ConstantInfo

src/relax/transform/rewrite_cuda_graph.cc, src/runtime/relax_vm/cuda/cuda_graph_builtin.cc, tests/python/relax/test_transform_rewrite_cuda_graph.py
CUDA graph rewriting may result reordering of original bindings, for example when a variable is used as an input of the lifted function. If the variable comes from the output of another function, we need to make sure output unpacking is emitted.
=> [Unity] Fix CUDA graph rewrite var used before def

src/support/ring_buffer.h, tests/cpp/support/ring_buffer_test.cc
This PR bugfixes ring buffer ReadWithCallback when the callback send function read part of the data.
Also backported one robustness fix from unity.
Testcases are added
=> [SUPPORT] Fix RingBuffer ReadWithCallback

python/tvm/relax/backend/contrib/cutlass.py
This PR avoids the usage of hardcoded 'main' function in implicit attention rewrite.
cc @cyx-6 @zxybazh
=> [Unity] Cover all Relax functions in implicit attention rewrite

python/tvm/topi/arm_cpu/conv2d.py, python/tvm/topi/arm_cpu/conv2d_alter_op.py, python/tvm/topi/cuda/batch_matmul.py, python/tvm/topi/cuda/conv2d_int8.py, python/tvm/topi/cuda/conv3d_direct.py, python/tvm/topi/cuda/dense.py, python/tvm/topi/cuda/group_conv2d_nchw.py, python/tvm/topi/cuda/scan.py, python/tvm/topi/cuda/softmax.py, python/tvm/topi/cuda/sparse.py, python/tvm/topi/generic/conv2d.py, python/tvm/topi/hexagon/conv2d_alter_op.py, python/tvm/topi/hexagon/qnn/conv2d_alter_op.py, python/tvm/topi/hls/nn.py, python/tvm/topi/image/resize.py, python/tvm/topi/nn/conv2d.py, python/tvm/topi/nn/depthwise_conv2d.py, python/tvm/topi/nn/fifo_buffer.py, python/tvm/topi/nn/upsampling.py, python/tvm/topi/nn/utils.py, python/tvm/topi/nn/winograd_util.py, python/tvm/topi/reduction.py, python/tvm/topi/testing/poolnd_python.py, python/tvm/topi/testing/resize_python.py, python/tvm/topi/transform.py, python/tvm/topi/x86/conv2d_alter_op.py, python/tvm/topi/x86/conv2d_avx_1x1.py, python/tvm/topi/x86/conv2d_int8.py, python/tvm/topi/x86/conv3d.py, python/tvm/topi/x86/nn.py
=> [TOPI] Use f-strings for string formatting, NFC

src/runtime/relax_vm/ndarray_cache_support.cc
This PR introduces a minor change that asks users to check if NDArray shards are properly placed when loading fails.
=> [Unity] Improve Error Message loading NDArray Shards

python/tvm/relay/op/_tensor.py, python/tvm/relay/op/annotation/annotation.py, python/tvm/relay/op/contrib/cutlass.py, python/tvm/relay/op/contrib/dnnl.py, python/tvm/relay/op/nn/_nn.py, python/tvm/relay/op/nn/utils.py, python/tvm/relay/op/op.py, python/tvm/relay/op/strategy/adreno.py, python/tvm/relay/op/strategy/arm_cpu.py, python/tvm/relay/op/strategy/bifrost.py, python/tvm/relay/op/strategy/cuda.py, python/tvm/relay/op/strategy/generic.py, python/tvm/relay/op/strategy/hexagon.py, python/tvm/relay/op/strategy/hls.py, python/tvm/relay/op/strategy/intel_graphics.py, python/tvm/relay/op/strategy/mali.py, python/tvm/relay/op/strategy/x86.py, python/tvm/relay/op/tensor.py, python/tvm/relay/op/transform.py, python/tvm/relay/op/vision/_rcnn.py
=> [Relay/Op] Use f-strings for string formatting, NFC

python/tvm/relax/training/loss.py, tests/python/relax/test_training_loss.py
This PR adds support of categorical cross entropy loss
=> [Unity][Training] Categorical cross entropy loss

python/tvm/relay/frontend/caffe.py, python/tvm/relay/frontend/caffe2.py, python/tvm/relay/frontend/common.py, python/tvm/relay/frontend/coreml.py, python/tvm/relay/frontend/darknet.py, python/tvm/relay/frontend/keras.py, python/tvm/relay/frontend/mxnet.py, python/tvm/relay/frontend/mxnet_qnn_op_utils.py, python/tvm/relay/frontend/nnvm_common.py, python/tvm/relay/frontend/oneflow.py, python/tvm/relay/frontend/onnx.py, python/tvm/relay/frontend/paddlepaddle.py, python/tvm/relay/frontend/pytorch.py, python/tvm/relay/frontend/qnn_torch.py, python/tvm/relay/frontend/tensorflow.py, python/tvm/relay/frontend/tensorflow2.py, python/tvm/relay/frontend/tensorflow2_ops.py, python/tvm/relay/frontend/tensorflow_ops.py, python/tvm/relay/frontend/tflite.py
=> [Frontend] Use f-strings for string formatting, NFC

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Due to lacking consider of the attribute `threshold` in `Softplus`, the inference results in TVM  are different from PyTorch.
You can see the definition of Softplus in [Pytorch documentation](https://pytorch.org/docs/1.7.1/generated/torch.nn.Softplus.html?highlight=softplus#torch.nn.Softplus:~:text=threshold%20%E2%80%93%20values%20above%20this%20revert%20to%20a%20linear%20function.%20Default%3A%2020)
The TVM gives the same inference results as PyTorch.
```
import torch
import tvm
m = torch.nn.Softplus(1, 2,)
input_data = torch.tensor([[1.0, 4.0]], dtype=torch.float32)
torch_outputs = m(input_data)
trace = torch.jit.trace(m, input_data)
input_shapes = [('input0', torch.Size([1, 2]))]
mod, params = relay.frontend.from_pytorch(trace, input_shapes) …
```
=> [Bugfix][Relay] Fix softplus about the wrong calculation formula in Relay PyTorch frontend

python/tvm/relay/backend/interpreter.py, python/tvm/relay/backend/te_compiler.py, python/tvm/relay/build_module.py, python/tvm/relay/expr.py, python/tvm/relay/expr_functor.py, python/tvm/relay/frontend/tensorflow_ops.py, python/tvm/relay/loops.py, python/tvm/relay/prelude.py, python/tvm/relay/qnn/op/layout_conversions.py, python/tvm/relay/qnn/op/qnn.py, python/tvm/relay/quantize/_calibrate.py, python/tvm/relay/quantize/quantize.py, python/tvm/relay/testing/dcgan.py, python/tvm/relay/testing/densenet.py, python/tvm/relay/testing/inception_v3.py, python/tvm/relay/testing/init.py, python/tvm/relay/testing/layers.py, python/tvm/relay/testing/lstm.py, python/tvm/relay/testing/mobilenet.py, python/tvm/relay/testing/py_converter.py, python/tvm/relay/testing/resnet.py, python/tvm/relay/testing/resnet_3d.py, python/tvm/relay/testing/squeezenet.py, python/tvm/relay/testing/tf.py, python/tvm/relay/testing/tflite.py, python/tvm/relay/testing/vgg.py, python/tvm/relay/transform/fake_quantization_to_integer.py, python/tvm/relay/type_functor.py
=> [Relay] Use f-strings for string formatting, NFC

docker/Dockerfile.ci_cpu
As discussed in https://github.com/apache/tvm/pull/14841, it is desirable to install PT on cpu image as well, to remove many workarounds in tests. Even for the gpu image, we have been using the cpu-build of PT, since we only use it for reference / model import.
=> [Docker] Install PyTorch on cpu image

include/tvm/ir/module.h, include/tvm/runtime/module.h, include/tvm/target/codegen.h, python/tvm/runtime/module.py, src/runtime/library_module.h, src/runtime/system_library.cc, src/target/codegen.cc, src/target/llvm/codegen_amdgpu.cc, src/target/llvm/codegen_blob.cc, src/target/llvm/codegen_blob.h, src/target/llvm/codegen_cpu.cc, src/target/llvm/codegen_cpu.h, src/target/llvm/codegen_hexagon.cc, src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h, src/target/llvm/codegen_nvptx.cc, src/target/llvm/llvm_module.cc, tests/python/unittest/test_runtime_module_load.py, tests/python/unittest/test_runtime_rpc.py, tests/python/unittest/test_target_codegen_blob.py
This PR enables combination of multiple system lib into the same static library with a system_lib_prefix attribute. This can open doors for multiple models to be compiled separately then packaged into the same app via static library.
It resolves a previous issue that prevents multiple system lib to be linked together when they come with extra binary component such as CUDA due to symbol conflict.
=> [LLVM][RUNTIME] Enable multi systemlib with device code

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
This PR is to fix the bug in the [issue-14794](https://github.com/apache/tvm/issues/14794). 
When the `output_size`  include a None, TVM can correctly parse the `None` according to the input, but give a wrong dtype (i.e., tvm.relay.expr.Constant). This pr fixes it by converting the `tvm.relay.expr.Constant` to 'int'.
cc @echuraev @Hzfengsy
=> [Bugfix][Relay] Fix AdaptiveAvgPool2d about wrong dtype prasing

src/script/printer/ir/relay.cc
Instances of `relay::Executor`, `relay::Runtime`, and `relay::backend::FunctionInfo` may be inserted into a PrimFunc's attributes for bookkeeping purposes.  In these flows, the function should still be able to be printed for debugging purposes.
=> [TVMScript] Print Executor, Runtime, and FunctionInfo as metadata

python/tvm/script/parser/core/entry.py, python/tvm/script/parser/core/error.py, python/tvm/script/parser/core/evaluator.py, python/tvm/script/parser/core/parser.py, python/tvm/script/parser/tir/parser.py, tests/python/unittest/test_tvmscript_meta_programming.py
Consider the case below:
```python
dtype = "float32"
@T.prim_func:
def f(
A: T.Buffer((1, ), dtype),
B: T.Buffer((1, ), dtype),
):
...
```
The variable `dtype` only appears in the type annotation of the function being parsed. In this case, the python interpreter will evaluate the annotation first before invoking the decorator, and thus if `dtype` doesn't appear in the function body, it will not be considered as being captured by the function itself. As a result, `inspect` module will be unable to supply the value of `dtype` during parsing, leading to failure.
This PR fixes the bug by maintaining a copy of function annotations that are already parsed. Whenever expression evaluation fails during parsing, it falls back to using the copy that is evaluated by python interpreter.
=> [Bugfix][TVMScript] Capture fails if var appears only in annotation

ci/jenkins/docker-images.ini
Follow up to https://github.com/apache/tvm/pull/14842 to actually update the image.
=> [Unity][CI] Update CPU image to install PyTorch

src/arith/const_int_bound.cc, src/target/source/codegen_metal.cc, src/target/source/codegen_metal.h, src/tir/transforms/flatten_buffer.cc, src/tir/transforms/lower_intrin.cc, tests/python/unittest/test_arith_const_int_bound.py, tests/python/unittest/test_target_codegen_metal.py
This PR fixes the codegen for vectorized select in metal. Also enhances arithmetics to cover better constant bound.
=> [METAL] Fix vectorized select

src/target/source/codegen_opencl.cc, tests/python/unittest/test_target_codegen_opencl.py
Per OpenCL specification
https://man.opencl.org/select.html
=> [Codegen][OpenCL] fix amibiguous selection operator call

python/tvm/relay/frontend/paddlepaddle.py, tests/python/frontend/paddlepaddle/test_forward.py
This PR fixed a similar bug with #14821  in the PaddlePaddle frontend.
For the [PaddlePaddle documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/Softplus_en.html), when input * beta > threshold, Softplus(x) = x. 
TVM miss this special case handling. It would cause wrong inference results.
A patch and a Test case that can trigger this bug are submitted in this PR.
cc @Hzfengsy @echuraev @jiangjiajun
=> [bugfix][Relay] Fix softplus in paddlepaddle frontend

python/tvm/topi/cuda/scatter.py, tests/python/relay/test_any.py
When using a scatter layer for cuda target, it gives the following error:
`ValueError: Cannot use and / or / not operator to Expr, hint: use tvm.tir.all / tvm.tir.any instead`
This is due to the call to the min function here:
https://github.com/apache/tvm/blob/d32dea800baeda14d144d0524a5da435c9cb160b/python/tvm/topi/cuda/scatter.py#L228-L231
This PR fixes this bug
=> [CUDA] Fixed the call of the min function in the schedule for cuda

python/tvm/relay/frontend/tflite.py, tests/python/contrib/test_cmsisnn/test_networks.py, tests/scripts/request_hook/request_hook.py
After upgrade to TFLite 2.6, some networks have missing tensor names.
This commit generates names with prefix tvmgen_ from TFLite frontend.
cc @leandron @lhutton1 @NicolaLancellotti
=> [TFLite][Frontend] Generate name when tensor name is missing

python/tvm/relay/op/__init__.py, python/tvm/relay/op/op.py, python/tvm/relay/qnn/op/qnn.py, python/tvm/relay/transform/fake_quantization_to_integer.py, python/tvm/relay/transform/transform.py, src/relay/qnn/op/softmax.cc, src/relay/transforms/fake_quantization_to_integer.cc, src/relay/transforms/pattern_utils.h, tests/python/relay/test_pass_fake_quantization_to_integer.py
This PR implements `qnn.softmax` which is the quantized operator of `nn.softmax`.
The implementation is based on the algorithm proposed in https://arxiv.org/pdf/2207.01405.pdf.
=> [QNN] Implement 'qnn.softmax'

python/tvm/relax/frontend/torch/fx_translator.py, tests/python/relax/test_frontend_from_fx.py
diffusers started to use `scaled_dot_product_attention` as of v0.16 in SD VAE. See the doc https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html. We cannot support attention mask, dropout, and causal mask optimization for now. 
The PT attention op requires a different input format than our attention op, so we need to transpose inputs. Luckily those transpose can be canceled in practice, since diffusers does transpose on q/k/v before calling `scaled_dot_product_attention` anyway (a design mistake?): https://github.com/huggingface/diffusers/blob/909742dbd6873052995dc6cd5f4150ff238015d2/src/diffusers/models/attention_processor.py#L906-L908
I'm also doing clean up on FX test cases. We shouldn't need `@tvm.testing.requires_gpu` since the tests don't …
=> [Unity][FX] Add support for PT2.0 scaled_dot_product_attention

src/relay/transforms/simplify_expr.cc, tests/python/relay/test_pass_simplify_expr.py
With my BYOC flow, I see that during various transformations, sometimes trivial no-ops like relay.transpose(x, axes=[0, 1, 2, 3]) are created. I would expect these to be optimized out with the SimplifyExpr pass which is not happening currently. This creates issues when I try to perform pattern matching on the graph.
Currently, SimplifyExpr looks for back to back transpose ops to optimize. This PR splits the current pass into two allowing us to optimize out these trivial ops as well.
=> [relay][simplify_expr]: Add pass to remove trivial transpose ops

python/tvm/ir/instrument.py, src/tir/transforms/inject_rolling_buffer.cc, tests/python/driver/tvmc/test_parse_config_file.py
In this pr, I fix some typo in comment:
- `reister` -> `register`
- `‘operator<’` -> `'operator<'` (`‘` make MSVC compile error) 
- `existant` -> `existent`
=> [FIX] fix typo in comment

python/tvm/relay/frontend/paddlepaddle.py, tests/python/frontend/paddlepaddle/test_forward.py
Add support for converting the following Paddle OPs.
- [p_norm](https://www.paddlepaddle.org.cn/documentation/docs/en/2.2/api/paddle/norm_en.html#norm)
- [roi_align](https://www.paddlepaddle.org.cn/documentation/docs/en/2.5rc/api/paddle/vision/ops/roi_align_en.html)
- [softmax_with_cross_entropy](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/softmax_with_cross_entropy_en.html#softmax-with-cross-entropy)
cc @jiangjiajun
=> [Frontend][Paddle] [PaddlePaddle Hackathon 4] add convert support for p_norm/roi_align/softmax_with_cross_entropy

python/tvm/tir/schedule/schedule.py
Minor typo fix to introduce f-string for the assert message as probably intended by the author
=> Fix f-string typo

python/tvm/topi/arm_cpu/conv2d_spatial_pack.py, src/target/parsers/aprofile.cc, tests/cpp/target/parsers/aprofile_test.cc
This commit will:
* Expose SVE as a target feature for Arm(R) Cortex(R) A-Profile CPUs.
* Update the compute definition of `conv2d_spatial_pack_nhwc` to defer to the LLVM backend for vectorization when compiling on an SVE enabled target for data tensors with unit width and height since this has been shown to be performant for wide vector architectures.
=> [TOPI][Target] Add SVE specific convolution

src/tir/transforms/ir_utils.cc, tests/python/unittest/test_tir_transform_compact_buffer_region.py
Revert the behavior to add pending predicates not fully solved via linear solver. They are too complex to get easily handled when we estimate the predicated buffer region. Refer to https://github.com/apache/tvm/issues/14834
Eg, if the linear solver handle 
`i_j_fused_0 * 65536 + i_j_fused_1 * 256 + i_j_fused_2 < n * n` 
failed, it would give out "unresolved" relations:
`i_j_fused_0 * 65536 + 65536 <= (n * n + 65535) // 65536 * 65536 and i_j_fused_0 * 65536 < n * n - i_j_fused_2 - i_j_fused_1 * 256 and i_j_fused_1 * 256 < n * n - i_j_fused_2 and i_j_fused_2 < n * n and 1 <= n * n`
It seeems not a good idea to add them. Instead, we preserve the origin one as before #14021.
=> [TIR] Avoid too complex predicate in compaction

src/runtime/crt/host/microtvm_api_server.py
Previously, the non-existent `self.disconnect_transport()` method was called prior to raising `server.TransportClosedError()`.  This commit updates to call the `self.close_transport()` method instead.
=> [MicroTVM] Use self.close_transport() on error

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Fix batch_norm on PyTorch frontend. 
Gamma and beta should be considered separately.
=> [Bugfix] Fix batch_norm

python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/frontend/torch/fx_translator.py, python/tvm/relax/op/nn/nn.py, python/tvm/relax/transform/legalize_ops/nn.py, python/tvm/relax/transform/transform.py, src/relax/op/nn/nn.cc, src/relax/op/nn/nn.h, src/relax/transform/combine_parallel_matmul.cc, tests/python/relax/test_frontend_dynamo.py, tests/python/relax/test_transform_legalize_ops_nn.py
The gelu operator has different implementations, in [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.GELU.html), they are distinguished by `approximate='none'` or `approximate='tanh'`. Currently, Relax only implements the case where `approximate="none"`  which depends on erf function, this PR implements the gelu operator approximated by tanh. In hugging face transformers, the gelu with tanh operator is called [gelu_new](https://github.com/huggingface/transformers/blob/366a8ca09e8dd92dfb1956c8be3118b5a2b13639/src/transformers/activations.py#L49) and was used in many models.
Actually, I only observed a very slight numerical difference between the two implementations, so I'm still not sure whether it necessary to include this variant or not.
Below is a figure showing the …
=> [Unity][Relax] gelu-tanh operator

src/target/llvm/codegen_cpu.cc
This pr fixed the source code build problem found in issue #14878 
The variable 'f' is a local variable that is inviable for the outside code. This pr moved the 'f' definition to the outside of the condition and fix the crash.
cc @Lunderberg @kparzysz-quic
=> [bugfix] fix the undeclared identifier 'f'

python/tvm/contrib/cc.py, python/tvm/contrib/tar.py, tests/python/unittest/test_target_codegen_blob.py
This PR enahnces create_staticlib to take tar files which can be handy when combining multiple libs into a single a file.
=> [CONTRIB] Enable create_staticlib to take in tar files

src/runtime/system_library.cc, tests/python/unittest/test_target_codegen_blob.py
This PR enhances systemlib to make it unique per prefix. Can help reduce flaky problems in multiple loading of same lib.
=> [RUNTIME] Make systemlib unique per prefix

python/tvm/relay/backend/contrib/ethosu/legalize.py, python/tvm/relay/backend/contrib/ethosu/util.py, python/tvm/relay/op/contrib/ethosu.py, tests/python/contrib/test_ethosu/infra.py, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_legalize.py
A separate channel-dimension nn.pad relay operator is rewritten as Relay concatenate operation.
=> [microNPU][ETHOSU] Channel pad offloaded to NPU

python/tvm/relax/backend/contrib/cutlass.py
Currently it fails on IRModule with TIR functions
cc @masahi
=> [Unity] Only process relax functions in workspace annotation

src/tir/ir/data_layout.cc
This PR fixes a typo in an error message when informing the user of a shape mismatch.
=> [Fix] Fix typo in error message

python/tvm/ir/transform.py
This fixes the following error when generating docs:
```
$ make singlehtml
...
updating environment: [new config] 209 added, 0 changed, 0 removed
:3: (SEVERE/4) Incomplete section title.python/ir
-------
Trace : Optional[relax.tuning.Trace]
reST markup error:
:3: (SEVERE/4) Incomplete section title.
```
=> [TIR][Doc] Fix formatting in pop_trace docstring

python/tvm/contrib/cutlass/build.py
CUTLASS BYOC has been broken since https://github.com/apache/tvm/pull/14394. We should enable CUTLASS in CI tests.
@vinx13 @yelite @slyubomirsky
=> [Unity][CUTLASS] Fix for purity tracking

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
`broadcast_shapes` is a newly introduced operator after PyTorch 1.8.0. If you install PyTorch < 1.8.0, the usage `torch.broadcast_shapes` will lead to a crash and throw:   **AttributeError: module 'torch' has no attribute 'broadcast_shapes'**.
This PR replaces `broadcast_shapes` with an old operator `broadcast_tensors`, which was introduced since PyTorch 1.0.0.
```
import torch
import tvm
m = torch.nn.L1Loss()
input_shape_ = [10, 3]
input_data=[torch.randn(input_shape_, dtype=torch.float64), torch.randn(input_shape_, dtype=torch.float64)]
trace = torch.jit.trace(m, input_data)
#input_shapes = [('input0', torch.Size(input_shape))]
input_shapes = [('input0', torch.Size(input_shape_)), ('input1', torch.Size(input_shape_))]
mod, params = …
```
=> [bugfix] [Relay] fix broadcast in PyTorch frontend 

ci/jenkins/docker-images.ini, tests/python/driver/tvmc/test_frontends.py, tests/scripts/task_config_build_cpu.sh
Follow up to https://github.com/apache/tvm/pull/14842 to actually update the image
=> [CI] Update CPU image to install PyTorch

python/tvm/target/target.py, src/runtime/vulkan/vulkan_device.cc, src/runtime/vulkan/vulkan_device.h, src/runtime/vulkan/vulkan_device_api.cc, src/target/source/codegen_cuda.cc, src/target/spirv/codegen_spirv.cc, src/target/spirv/codegen_spirv.h, src/target/spirv/ir_builder.cc, src/target/spirv/ir_builder.h, src/target/spirv/spirv_support.cc, src/target/spirv/spirv_support.h, src/target/target_kind.cc, src/tir/transforms/ir_utils.cc, src/tir/transforms/ir_utils.h, tests/python/unittest/test_target_codegen_vulkan.py
[Vulkan] Add SPIR-V code generation for "SPV_NV_cooperative_matrix" extension
Add im2col implementation for direct Conv2D.  Currently only 16x16x16 FP16 wmma fragments with FP32 intermediates are supported.  Add "min_design_space" as a parameter to give minimum design space for meta scheduler tuning. Add "use_int32_const" as a paramter to use int32 type for constants. Allow target query to be called from the schedules so that samplings are constrained to produce legal schedules. Do not allow the reuse of buffers with different dtypes. Add a unit test test_wmma.py.
=> [Vulkan] Add cooperative matrix support

include/tvm/node/script_printer.h, python/tvm/ir/expr.py, python/tvm/script/parser/core/parser.py, python/tvm/script/parser/core/utils.py, python/tvm/script/parser/ir/parser.py, python/tvm/script/parser/tir/parser.py, python/tvm/tir/__init__.py, python/tvm/tir/op.py, src/script/printer/ir/ir.cc, src/script/printer/tir/expr.cc, src/script/printer/tir/function.cc, tests/python/unittest/test_tvmscript_roundtrip.py
Similar to `module.relax_func(args)` syntax used when parsing Relax functions, this allows `module.tir_func(args)` to be used when parsing TIR PrimFuncs.
=> [TIR][TVMScript] Added format/parsing of subroutine calls

python/tvm/contrib/clang.py, python/tvm/contrib/cudnn.py, python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/conv2d_operation.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_conv2d.py, python/tvm/contrib/cutlass/gen_gemm.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/contrib/cutlass/library.py, python/tvm/contrib/graph_executor.py, python/tvm/contrib/hexagon/profiling/process_lwp_data.py, python/tvm/contrib/nvcc.py, python/tvm/contrib/peak.py, python/tvm/contrib/pickle_memoize.py, python/tvm/contrib/pipeline_executor.py, python/tvm/contrib/pipeline_executor_build.py, python/tvm/contrib/rocm.py, python/tvm/contrib/sparse.py, python/tvm/contrib/tar.py, python/tvm/contrib/target/coreml.py, python/tvm/contrib/target/onnx.py, python/tvm/contrib/target/vitis_ai.py, python/tvm/contrib/tf_op/module.py, python/tvm/contrib/utils.py, python/tvm/contrib/xcode.py
=> [Contrib] Use f-strings for string formatting, NFC

src/script/printer/tir/block.cc, src/script/printer/tir/buffer.cc, src/script/printer/tir/function.cc, src/script/printer/tir/stmt.cc, src/script/printer/tir/utils.h, tests/python/unittest/test_tvmscript_printer_tir.py, tests/python/unittest/test_tvmscript_roundtrip.py
Previously, a `DeclBuffer` object in which `decl_buffer->buffer->data` had not been defined would be printed without the `data` argument. This was the same representation as the `Allocate`/`DeclBuffer` pattern (e.g. `buf = T.decl_buffer(shape,dtype)`), and so the `Allocate` node would be inserted when parsing.
This commit updates the printing of buffers to be aware of which variables are implicitly declared in the process of declaring a buffer.  (e.g. A buffer that occurs in `BlockNode::alloc_buffers` defines both the buffer and the data pointer, while a `DeclBuffer` only defines the buffer.)  This is used to produce a different representation for the undefined data pointer, removing the ambiguity with the `Allocate`/`DeclBuffer` sugar.
Because this change only affects malformed TIR in …
=> [TVMScript] Round-trip DeclBuffer with undefined data pointer

src/target/llvm/codegen_amdgpu.cc, src/target/llvm/codegen_cpu.cc, src/target/llvm/codegen_cpu.h, src/target/llvm/codegen_hexagon.cc, src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h, src/target/llvm/codegen_nvptx.cc, src/target/llvm/llvm_module.cc, tests/python/unittest/test_target_codegen_llvm.py
Previously, the `CallNode::op` must be a known built-in operation.  This commit allows LLVM codegen to produce a subroutine call to another function within the same IRModule, with `CallNode::op` specifying the `GlobalVar` that represents that function.
=> [LLVM] Codegen subroutine call when CallNode::op is GlobalVar

tests/python/frontend/pytorch/test_forward.py
This PR added some version checks to avoid calling the operator/attribute, which has not been introduced yet！
When the PyTorch <=1.7.1, test cases will fail.
```
FAILED frontend/pytorch/test_forward.py::test_forward_tensor_split - AttributeError: module 'torch' has no attribute 'tensor_split'
FAILED frontend/pytorch/test_forward.py::test_grid_sample - ValueError: nn.functional.grid_sample(): expected mode to be 'bilinear' or 'nearest', but got: 'bicubic'
```
cc @echuraev @Hzfengsy @shingjan
=> [Test Cases][BugFix] Add some version check to make test cases run in all PyTorch versions

python/tvm/relay/frontend/keras.py
This pr fixed a typo problem which could give an ambiguous crash message.
@echuraev @merrymercy @masahi
=> [TypoFix] fix some typo problem in keras frontend

src/target/source/codegen_webgpu.cc, src/target/source/codegen_webgpu.h, web/src/webgpu.ts
This PR try to add fp16 support to WebGPU backend by adding `enable f16` directive into WGSL codegen if necessary and requiring f16 feature when creating WebGPU device if available.
=> [Unity][WebGPU] Try F16 support for  WebGPU Backend

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/eliminate_common_subexpr.cc, tests/python/relax/test_transform_cse.py
The CSE pass eliminates expressions very eagerly. This can result in an undesirable result, for example `relax.arange(...)` op  which requires all of its inputs to be `PrimValue` complains when its inputs are CSE variables. 
https://github.com/apache/tvm/blob/unity/src/relax/op/tensor/create.cc#L248-L253
```
File "/Users/masa/projects/dev/tvm/src/relax/ir/block_builder.cc", line 138
TVMError: Arange expects the `start` to be a PrimValue, but got relax.expr.DataflowVar
```
That error can be easily fixed, but I've also hit similar issues with other ops like `strided_slice` as well. Since I only need common CallNodes to be eliminated, I'm adding an option to avoid the default fine-grained elimination.
cc @slyubomirsky @sunggg
=> [Unity] Allow eliminating only call nodes in CSE pass

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
This pr adds a dimension check to reject the non-batch dimensions <=0.
cc @echuraev @Hzfengsy
=> [Relay] add a dimension check to reject invalid input

docker/install/ubuntu2204_install_llvm.sh
llvm-16 packages did not include the polly library, but llvm-config expects it to be there, so tvm failed to build. This change adds libpolly-16-dev to the ci_cpu package
=> [Docker] Add polly package

python/tvm/relay/backend/contrib/ethosu/legalize.py, python/tvm/relay/op/contrib/ethosu.py, tests/python/contrib/test_ethosu/test_codegen.py, tests/python/contrib/test_ethosu/test_legalize.py
The nn.avg_pool2d operator with a stride size greater than 3 in any of the spatial dimensions is rewritten as ethosu avg_pool with strides=[1,1] if the case satisfies the additional conditions (no AvgPool2D padding, spatial dimensions of ifm and shape of pooling are equal).
=> [microNPU][ETHOSU] Add offloading to the NPU the nn.avg_pool2d operator with a stride > 3

python/tvm/script/ir_builder/tir/ir.py, tests/python/unittest/test_tvmscript_roundtrip.py
Prior to this commit, the `TargetNode::host` could be specified in TVMScript as part of the config dictionary, under the key `"host"`. However, this required all other device parameters to be explicitly specified, rather than using any of the short-hand string representations.  This commit forwards the `host` argument from TVMScript's `T.target` method to `tvm.target.Target`, allowing both the device and host to be specified using the shorthand string representation.
```python
@T.prim_func
def before_this_commit():
T.func_attr(
{
"target": T.target(
{
"arch": "sm_86",
"host": {"keys": ["cpu"], "kind": "llvm", "tag": ""},
"keys": ["cuda", "gpu"],
"kind": "cuda",
"max_num_threads": 1024,
"tag": "",
"thread_warp_size": 32,
}
)
}
)
T.evaluate(0)
@T.prim_func
def after_this_commit(): …
```
=> [TVMScript] Allow T.target("device", host="host") to specify host

CMakeLists.txt, include/tvm/runtime/logging.h
This PR enables log before throw in windows.
The error handling in windows sometimes can be tricky and it is helpful to be able to get as many information as possible. Turning this option on can help us detect possible errors here.
=> [BUILD] Enable log before throw message in windows

apps/ios_rpc/tests/ios_rpc_mobilenet.py, apps/ios_rpc/tests/ios_rpc_test.py, apps/topi_recipe/broadcast/test_broadcast_map.py, apps/topi_recipe/conv/depthwise_conv2d_test.py, apps/topi_recipe/conv/test_conv2d_hwcn_map.py, apps/topi_recipe/reduce/test_reduce_map.py, apps/topi_recipe/rnn/lstm.py, apps/topi_recipe/rnn/matexp.py, jvm/core/src/test/scripts/test_add_gpu.py, python/tvm/contrib/nvcc.py, python/tvm/contrib/sdaccel.py, src/target/opt/build_cuda_on.cc, src/target/source/codegen_aocl.cc, src/target/source/codegen_metal.cc, src/target/source/codegen_opencl.cc, src/target/source/codegen_vhls.cc, src/target/spirv/spirv_utils.cc, tests/python/integration/test_ewise.py, tests/python/integration/test_ewise_fpga.py, tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
This PR adds an extra parameter `target` to all `tvm_callback_*` so that the callback can decide its own behavior by querying which target to compile against.
=> [Target] Add target to all TVM callbacks

src/target/llvm/codegen_llvm.cc
A small script that exposes host CPU name, target triple and features:
<details>
```python
import tvm
def main():
get_default_target_triple = tvm._ffi.get_global_func("tvm.codegen.llvm.GetDefaultTargetTriple")
get_process_triple = tvm._ffi.get_global_func("tvm.codegen.llvm.GetProcessTriple")
get_host_cpu_name = tvm._ffi.get_global_func("tvm.codegen.llvm.GetHostCPUName")
get_host_cpu_features = tvm._ffi.get_global_func("tvm.codegen.llvm.GetHostCPUFeatures")
target_triple = get_default_target_triple()
process_triple = get_process_triple()
host_cpu_name = get_host_cpu_name()
host_cpu_features = get_host_cpu_features()
print("target_triple: {}".format(target_triple))
print("process_triple: {}".format(process_triple))
print("host_cpu_name: {}".format(host_cpu_name))
print("host_cpu_features:") …
```
=> [LLVM] Expose Host CPU Feature Detection

include/tvm/target/target.h, src/target/target.cc, src/tir/transforms/combine_context_call.cc, src/tir/transforms/ir_utils.cc, src/tir/transforms/ir_utils.h, tests/python/unittest/test_tir_transform_combine_context_call.py
Previously, the `tir.transform.CombineContextCall` pass applied to all functions in an `IRModule`, but was only applied to modules that contain only host functions.  This commit updates `tir.transform.CombineContextCall` to apply only to host functions.
=> [TIR] Restrict tir.transform.CombineContextCall to host functions

web/src/runtime.ts
This PR enhances web runtime cache with scopes.
=> [Unity] Enhance web cache to add scopes

src/tir/transforms/make_packed_api.cc, src/tir/transforms/make_unpacked_api.cc
PRs https://github.com/apache/tvm/pull/14913 and https://github.com/apache/tvm/pull/14914 made analogous changes to `MakePackedAPI` and `MakeUnpackedAPI` to handle subroutine calls. Both PRs introduced the same symbol, `tvm::tir::SubroutineCallRewriter`, a local utility to update internal calls to a modified function.  While each PR passed CI individually, and was therefore able to merge, having both changes caused a duplicate symbol.
This commit updates `MakePackedAPI` and `MakeUnpackedAPI` to place their local utilities into anonymous namespaces, avoiding the conflict.
=> [Bugfix] Avoid symbol conflicts in MakePackedAPI/MakeUnpackedAPI

include/tvm/target/target.h, src/target/target.cc, src/tir/transforms/make_packed_api.cc, src/tir/transforms/make_unpacked_api.cc, src/tir/transforms/primfunc_utils.cc, tests/python/unittest/test_tir_transform_helpers.py
Previously, if a function already has a `tvm::attr::kTarget` attribute, it will be overwritten by the `tir.BindTarget` transform. This commit updates the behavior such that `tir.BindTarget` adds annotations to functions that are missing a target annotation, but preserves any existing target annotations.
This is part of a series of commits to simplify the handling of multi-target builds.
=> [TIR] Preserve existing kTarget function attribute in BindTarget

python/tvm/script/ir_builder/tir/ir.py, src/tir/ir/stmt.cc, src/tir/transforms/make_packed_api.cc, src/tir/transforms/make_unpacked_api.cc, tests/python/unittest/test_tvmscript_printer_tir.py, tests/python/unittest/test_tvmscript_syntax_sugar.py
Previously, while literal `True` and `False` values were converted to `tvm::Bool` instances, constant-foldable expressions (e.g. `0 == 1`) would be evaluated to `True`, but were then passed directly to the FFI.  Because the FFI uses the same representation for integer and boolean values, the conversion to `PrimExpr` resulted in a `tvm::Integer` instead of `tvm::Bool`.
This commit converts the argument of `T.Assert` to a `tvm::Bool` before calling the FFI, avoiding the ambiguity.  In addition, the `AssertStmt` constructor now validates the datatype of the condition, to prevent it from re-occurring.
This was first caught in the unit test `test_debug_info.py::test_llvm_ir_debug_info`, which failed validation on some versions of LLVM due to the use of `i32` as the condition of an assert.
=> [TVMScript] Prevent bool to int conversion in T.Assert condition

src/relax/transform/fuse_ops.cc, src/relax/transform/merge_composite_functions.cc, tests/python/relax/test_transform_merge_composite_functions.py
Fix for https://discuss.tvm.apache.org/t/segfault-on-mergecompositefunctions/14999. We are not creating `Group` for non `CallNodes` that appear in the arguments of another `CallNode`. This results in a segfault when OpFuser tries to look up the group for all call node inputs.
@vinx13 @yelite
=> [Unity] Fix MergeCompositeFunctions for non-CallNode dataflow inputs 

python/tvm/relax/backend/contrib/cutlass.py, python/tvm/relax/backend/patterns.py, python/tvm/relax/op/nn/nn.py, tests/python/relax/test_codegen_cutlass.py
In practice, `partition_for_cutlass` is invoked after we run the fp16 conversion pass. The pass adds fp16 -> fp32 and fp32 -> fp16 before / after softmax, but these casts are not recognized by the attention rewriter introduced in https://github.com/apache/tvm/pull/14744. This is fixed in this PR.
I also found and fixed several bugs in the rewriting logic.
@cyx-6 @vinx13
=> [Unity][BYOC] Make CUTLASS attention rewriting aware of fp16 <-> f32 casting 

src/target/llvm/codegen_cpu.cc, src/tir/transforms/ir_utils.h, src/tir/transforms/make_packed_api.cc, src/tir/transforms/make_unpacked_api.cc, tests/python/unittest/test_target_codegen_llvm.py
Previously, calling a packed func that returns void would result in an error being raised from `tir::APIType`, as there is no runtime representation of a void type.  This commit updates `CodeGenCPU::MakeCallPackedLowered` to only read the return value and type of a `PackedFunc` when the TIR return type is non-void.
=> [Codegen][LLVM] Allow void return type from PackedFunc 

include/tvm/tir/schedule/block_scope.h, src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_fuse_tir.py
Currently fuse_tir cannot handle cases when the shape of arguments of call_tir contains tir expressions (e.g. `n-1` other than `n`). 
In this case, 
1. The tir vars in the tir expression will be collected and provided as the third parameter of call_tir
2. fuse_tir has a special logic to handle these vars. However, it wrongly checks such vars cannot already exist in `symbolic_var_remap`. In fact, the var has been stored in `symbolic_var_remap` when previously matching arguments to tir buffers, where the shape of the argument is visited.
This PR fixes this problem by using `symbolic_var_matcher.Match` instead.
=> [Unity][Transform] Fix bug for tir expression in shape in fuse_tir

src/target/source/codegen_metal.cc, tests/python/unittest/test_target_codegen_metal.py
Current codegen output `(half4)*(device uint*)A` tries to create a `int32` number and then cast it to `half4`, which is not the expected behavior.
As Metal natively supports `uchar4` and `char4` types ([ref](https://developer.apple.com/documentation/metal/mtldatatype/uchar4)), we can direct use them to solve that problem.
cc @tqchen
=> [METAL] Fix int8 vectorized cast

ci/scripts/github/update_branch.py, tests/python/ci/test_ci.py
This PR updates the CI jobs list in the update_branch script and fixes #14618. 
Once this is merged, the intent is to reenable the job at https://github.com/apache/tvm/actions/workflows/update_last_successful_branch.yml. 
I do not have the permission to reenable the workflow -- could the person who approves & merges this also reenable that? :)
=> [CI] Update the expected CI jobs list in the update_branch script

python/tvm/rpc/base.py, python/tvm/rpc/client.py, python/tvm/rpc/minrpc.py, python/tvm/rpc/proxy.py, python/tvm/rpc/server.py, python/tvm/rpc/testing.py, python/tvm/rpc/tracker.py, python/tvm/runtime/container.py, python/tvm/runtime/executor/aot_executor.py, python/tvm/runtime/module.py, python/tvm/runtime/ndarray.py, python/tvm/runtime/object.py, python/tvm/runtime/object_generic.py, python/tvm/runtime/vm.py
=> [Runtime,RPC] Use f-strings for string formatting, NFC

apps/hexagon_launcher/README.md, cmake/config.cmake, cmake/modules/HexagonSDK.cmake, python/tvm/contrib/hexagon/tools.py, python/tvm/target/target.py, src/runtime/hexagon/README.md, src/runtime/hexagon/rpc/simulator/session.cc, tests/python/contrib/test_hexagon/README.md
Snapdragon 8 Gen2 is v73, Hexagon SDK 5.2+ supports it.
=> [Hexagon] Add support for v73, make v68 default

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
Fix #14926 .
The input should be normalized with the provided running mean and running variance instead of computing the mean and variance from the input data when use_input_stats is set to false.
=> [Bugfix][PyTorch] Support use_input_stats in instance_norm

python/tvm/relax/op/_op_gradient.py, tests/python/relax/test_transform_gradient.py
This PR updates the logic of the `_fit_shape` helper function to first use BlockBuilder to acquire the shape, instead of providing the shape. 
It will make it easier for expressions that are hard to provide shapes, such as matmul.
The correctness of these op gradients are checked in `tests/python/relax/test_op_gradient_numeric.py`, and does not need additional checks.
=> [Unity][Training] Enhance op gradient

python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/conv2d_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, tests/python/relax/test_codegen_cutlass.py
So far we've been supporting residual input of the same size as the conv2d output. In SD UNet there are residual add where the shapes of residual inputs are bias-like, for example (1, 1, 1, 320).  
According to https://github.com/NVIDIA/cutlass/discussions/959#discussioncomment-6001066, CUTLASS also supports "batched bias" like shape (2, 1, 1, 320), but I was not able to get the correct output when I tested.  
@vinx13 @yelite
=> [Unity][CUTLASS] Support more residual input shape

python/tvm/script/parser/tir/parser.py, tests/python/unittest/test_tvmscript_roundtrip.py
In most cases, the IR dialect in `GlobalVar.__call__` can be inferred from the argument types.  If there are no arguments, then the returned value is ambiguous.  This commit updates the TIR parser to identify and fix this case of erroneously producing a `relay.Call` instead of `tir.Call`.
In addition, to prevent this from re-occuring, an unrecognized type resulting from `def visit_expr_stmt` now results in an error, rather than being silently ignored.
=> [TVMScript][TIR] Parse subroutine calls with no arguments

src/tir/transforms/make_packed_api.cc, tests/python/unittest/test_tir_transform_make_packed_api.py
Prior to this commit, `ArgBinder` would always introduce a new variable to represent the input argument, even if the argument already a primitive type.  This introduces trivial let bindings that are expected to be simplified out, but which can produce dangling `tir::Var` usage in some cases (see https://github.com/apache/tvm/pull/14951).
This commit updates `ArgBinder` to prefer using the original `tir::Var` when possible.  That is, when a function takes `n: T.int32` as input, the packed function should produce a binding `n: T.int32 = T.tvm_struct_get(...)`, rather than producing a binding `arg_n = T.tvm_struct_get(...)` followed by `n = arg_n`.
=> [TIR] Avoid re-defining `var = arg_var` in ArgBinder

include/tvm/ir/si_builder.h, include/tvm/ir/source_map.h, python/tvm/ir/__init__.py, python/tvm/ir/base.py, python/tvm/relay/__init__.py, python/tvm/relay/base.py, src/ir/si_builder.cc, src/ir/source_map.cc, tests/cpp/si_builder_test.cc
- Add SIBuilder to handle the span propagation between passes
- Add SequentialSpan for multiple source expressions conversion between passes
- Add test cases for SIBuilder and SequentialSpan
=> [IR][SIBuilder]

python/tvm/relax/dpl/rewrite.py, python/tvm/relax/transform/transform.py, src/relax/ir/dataflow_matcher.cc, src/relax/transform/combine_parallel_matmul.cc, tests/python/relax/test_dataflow_pattern.py, tests/python/relax/test_transform_combine_parallel_matmul.py
Currently, `CombineParallelMatmul` eagerly combines all parallel branches it finds. Sometimes, it is desirable to ignore certain patterns based on, for example, the number of matmuls.  
This PR adds a user-defined "check function" to `CombineParallelMatmul` that is used like this:
```
Var inp;
Array<Var> rhs, bias;
Map<Var, Expr> bindings; // Passed from DF rewriter
if (!check(inp, rhs, bias, bindings)) {
continue;
}
```
It also modifies the signature of the DF binding rewrite function to additionally pass the current bindings (`Map<Var, Expr>`). This can be useful for querying the attributes of the matched `CallNode` expressions. Until now, only matched `Var`s (`Map<DFPattern, Var>`) are being passed, so there has been no way to retrieve the corresponding matched expressions. 
@vinx13 …
=> [Unity] Allow filtering out unwanted branches in matmul combining pass

src/relax/op/tensor/binary.cc, src/relax/transform/convert_layout.cc, tests/python/relax/test_transform_convert_layout.py
Currently when one of the inputs to elemwise op is a scalar, `ConvertLayout` inserts NHWC -> NCHW fallback conversion, ending up the following undesirable result:
```
gv: R.Tensor((2, 26, 26, 4), dtype="float32") = R.nn.conv2d(lv, lv1, data_layout="NHWC", kernel_layout="OHWI", out_layout="NHWC")
lv2: R.Tensor((2, 4, 26, 26), dtype="float32") = R.permute_dims(gv, axes=[0, 3, 1, 2])
gv2: R.Tensor((2, 4, 26, 26), dtype="float32") = R.add(lv2, R.const(1, "float32"))
```
@spectrometerHBH
=> [Unity] Fix ConvertLayout on binary elemwise ops involving scalar input

src/relax/ir/dataflow_matcher.cc, tests/python/relax/test_dataflow_pattern.py
This PR fixes a bug where the match state isn't reset during backtracking when matching dataflow pattern.
cc @masahi
=> [Unity] Reset match state when backtracking

src/tir/transforms/split_host_device.cc, tests/python/unittest/test_tir_transform_split_host_device.py
This resolves an issue introduced by the combination of https://github.com/apache/tvm/pull/14918 and
https://github.com/apache/tvm/pull/14945.  The bug occurred for targets that do not require device-side codegen, but do require a `device_type` other than `kDLCPU`.  It wasn't caught by CI, as the issue only occurred with the combination of both PRs.
1. #14918 updated `SplitHostDevice` to only modify the `"target"` attribute when a device-side function has been extracted.
2. For VTA, there is no device-side function, as everything is done through host-side API calls.
3. From (1) and (2), the VTA examples kept the target `T.target("ext_dev", host="llvm")` after the `SplitHostDevice` pass, instead of being updated to `T.target("llvm")`.
4. #14945 restricted CombineContextCall to only apply …
=> [Bugfix][TIR][VTA] Update host-side target, even without device func

src/tir/transforms/lower_thread_allreduce.cc
Currently, the ThreadAllReduce pass would throw an error when the mask data type is uint32 and the `group_index`'s data type is int64:
```bash
1: tvm::tir::ThreadAllreduceBuilder::MakeAllreduce(tvm::tir::CallNode const*)
at /home/zhye/repos/relax/src/tir/transforms/lower_thread_allreduce.cc:362
0: tvm::tir::BufferStore::BufferStore(tvm::tir::Buffer, tvm::PrimExpr, tvm::runtime::Array<tvm::PrimExpr, void>, tvm::Span)
at /home/zhye/repos/relax/src/tir/ir/stmt.cc:477
File "/home/zhye/repos/relax/src/tir/ir/stmt.cc", line 477
TypeError: dtype mismatch on BufferStore: buffer's dtype is `uint32`, the lanes of indexing are: `1`, but RHS's dtype is `int64`
```
As int64 becomes the standard index data type for large models, we should fix the issue.
This PR resolves the issue by casting the …
=> [Bugfix] Make ThreadAllReduce pass compatible with int64

CMakeLists.txt
This PR add a dummy target that can be renamed as libtvm and can be used to create a dependency on libtvm without compiling everything. This can be useful for down stream in platforms such as windows.
=> [CMAKE] Add a dummy target to defer libtvm dep

tests/python/relax/test_op_gradient_numeric.py
This PR:
- Avoids inputs to nll_loss that make the total weight to be zero
- When the total weight is zero and the reduction method of nll_loss is "mean", there would be a division by zero error
- Change `np.random.randint` into `np.random.uniform` when generating op inputs to get better randomness
=> [Unity][Training] Avoid problematic inputs to nll_loss in test_op_gradient_numeric

python/tvm/relay/op/strategy/adreno.py, tests/python/relay/opencl_texture/test_conv2d_nchw_texture.py, tests/python/relay/opencl_texture/test_conv2d_nhwc_texture.py, tests/python/relay/opencl_texture/test_depthwise_conv2d_nchw_texture.py, tests/python/relay/opencl_texture/test_depthwise_conv2d_nhwc_texture.py, tests/python/unittest/test_te_schedule_bound_inference.py
When the number of output channels is less than 4, then we cannot pack such convolution to textures, although we can repack and extend tensors from 4d to 5d in runtime.
It is happened because function `PropBoundToInputs` is invoked for all stages in when InferBound pass or LowerSchedule function is called.
`PropBoundToInputs` has a logic in it that helps to developer to avoid out of bound access. And based on the output shape, it propagates it to inputs.
Imagine that we want to transform a 4d tensor with 3 channels to 5d, extend its number of channels to 4 and then transform it back to 4d tensor with number of channels equal to 3. Example below:
```
[1, 3, 6, 6] -> [1, 1, 6, 6, 4] -> [1, 3, 6, 6]
```
In this case, we might write a boundary check in the repacking and extending compute …
=> [OpenCL][Adreno] Fix conv2d when output channels < 4

src/target/source/codegen_opencl.cc, tests/python/unittest/test_target_codegen_opencl.py, tests/python/unittest/test_target_texture_codegen_opencl.py
This PR changes the Cast in OpenCL to always relying on convert_T to get closer to the spec and more reliable.
=> [OPENCL] Always use convert_T for type conversion

python/tvm/ir/container.py, python/tvm/ir/expr.py, python/tvm/ir/json_compact.py, python/tvm/te/hybrid/module.py, python/tvm/te/hybrid/parser.py, python/tvm/te/hybrid/preprocessor.py, python/tvm/te/hybrid/utils.py, python/tvm/te/operation.py, python/tvm/te/schedule.py, python/tvm/te/tag.py, python/tvm/te/tensor.py, python/tvm/tir/buffer.py, python/tvm/tir/ir_builder.py, python/tvm/tir/schedule/schedule.py, python/tvm/tir/schedule/state.py, python/tvm/tir/tensor_intrin/arm_cpu.py, python/tvm/tir/tensor_intrin/cuda.py
=> [IR,TE,TIR] Use f-strings for string formatting, NFC

src/runtime/vulkan/vulkan_amdrgp.cc, src/runtime/vulkan/vulkan_buffer.cc, src/runtime/vulkan/vulkan_instance.cc, src/runtime/vulkan/vulkan_stream.cc, src/runtime/vulkan/vulkan_wrapped_func.cc, src/target/llvm/codegen_cpu.cc, src/tir/schedule/primitive/blockize_tensorize.cc
This PR fixes the following compilation warnings:
- use `nullptr` instead of `NULL` and `0`
- unused variable at `src/tir/schedule/primitive/blockize_tensorize.cc`
=> [Minor] Fix compilation warnings

src/tir/transforms/split_host_device.cc, tests/cpp/c_codegen_test.cc, tests/python/unittest/test_tir_transform_split_host_device.py
Previously, this unit test generated a `Map<tvm::Target, IRModule>` whose default iteration order was not sorted by function name, built the `Map` of modules, then validated whether the resulting C code was a sorted list of 4 elements.  However, this condition was stricter than necessary, as it depended on the number of items added to the `Map` until it was unsorted.
This commit updates the test to instead validate that `std::is_sorted` returns true.
=> [CodegenC] Updated unit test for sorted CodegenC output

src/tir/transforms/unsupported_dtype_legalize.cc
I introduced a `LOG(INFO)` in a previous PR #14863 , which pollutes user output.
This PR fixes the issue.
cc @tqchen @junrushao @MasterJH5574 @Hzfengsy .
=> [Hotfix] Remove `LOG(INFO)` from unsupported dtype legalization pass

python/tvm/contrib/hexagon/pytest_plugin.py, src/target/target_kind.cc, src/tir/transforms/ir_utils.cc, src/tir/transforms/lower_tvm_builtin.cc, src/tir/transforms/split_host_device.cc, tests/python/unittest/test_tir_transform_lower_tvm_builtin.py, tests/python/unittest/test_tir_transform_split_host_device.py
Previously, the `tir.transform.LowerTVMBuiltin` pass applied to all functions in an `IRModule`, but was only applied to modules that contain only host functions.  This commit updates `tir.transform.LowerTVMBuiltin` to apply only to host functions.
=> [TIR] Restrict tir.transform.LowerTVMBuiltin to host functions

src/tir/transforms/simplify.cc, tests/python/unittest/test_tir_transform_simplify.py
Prior to this commit, any trivial let binding of `var1 = var2` is inlined.  However, buffer definitions are not updated, so this can result in dangling `tir::Var` instances.  This commit updates the `tir.Simplify` pass to keep trivial let bindings if they are used as part of a buffer definition.
Ideally, the trivial `LetStmt` variable would be inlined into the buffer definition as well as other expressions.  However, because a buffer may be implicitly declared, the first usage may be within a constrained context.  If that happens, the simplified shape/strides expression cannot be used to update the buffer definition, as that simplification is not valid at all possible usage points of the buffer.
```python
for i in range(n):
elem_offset = i
view = T.Buffer(1, data=buf, elem_offset = …
```
=> [TIR] Keep trivial LetStmt in tir.Simplify when used in buffer decl

src/tir/transforms/lower_device_kernel_launch.cc, tests/python/unittest/test_tir_transform_device_kernel_launch.py
Prior to this commit, any caller that uses a different `Target` than its callee is lowered to a device-kernel launch.  However, if the caller and callee are on the same device, despite using a different target (e.g. `Target("llvm")` and `Target("c")` both use `kDLCPU`), then the kernel launch is unnecessary.
This commit updates `LowerDeviceKernelLaunch` to produce a kernel launch only when the callee is on another device, and to produce `T.call_extern` for callees on the same device.
=> [TIR] Handle callees on same target, different codegen

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
This PR is similar to the [pr-14837](https://github.com/apache/tvm/pull/14837)
This pr fixed a type parse bug when the out_size attribute of the `AdaptiveMaxPool2d` or `AdaptiveMaxPool3d` contains `None`, which means has the same size as the input. But the op can't be parsed by Relay and throws an error message:
**"Check failed: (!checked_type.defined()) is false: Expected Array[PrimExpr], but got Array[index 1: relay.Constant]"**
The op introduction in the [PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveMaxPool3d.html)
```
import torch
m = torch.nn.AdaptiveMaxPool3d((3, None, None),)   
input_data=[torch.randn([1, 1, 3, 5, 6], dtype=torch.float32)]
trace = torch.jit.trace(m, input_data)
input_shapes = [('input0', torch.Size([1, 1, …
```
=> Fix type parse error about AdaptiveMaxPool

python/tvm/relax/backend/contrib/__init__.py
This PR adds `__init__.py` to `relax.backend.contrib`, fixing the package issue reported at https://github.com/mlc-ai/mlc-llm/issues/311
cc @yzh119 @tqchen
=> [Unity][FIX] add init file to `relax.backend.contrib`

python/tvm/contrib/cutlass/build.py
Cutlass internally may use static variables flags to control initialization. When multiple modules are loaded at runtime, duplicating symbols in the dynamic libraries cause subsequent modules failure to initialize cutlass.
cc @masahi @jwfromm @junrushao
=> [BYOC] Hide internal cutlass symbols

python/tvm/contrib/cutlass/attention_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, tests/python/relax/test_codegen_cutlass.py
This PR adds support for the dynamic sequence length in cutlass attention. 
cc @cyx-6 @masahi
=> [Unity] Cutlass attention with dynamic sequence length

src/tir/ir/buffer.cc, tests/python/unittest/test_tir_buffer.py
If buffer is already flat, then `Buffer::GetFlattenedBuffer()` should return the same object.  This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Preserve object equality in Buffer::GetFlattenedBuffer

src/target/spirv/codegen_spirv.cc, src/target/spirv/codegen_spirv.h, tests/python/unittest/test_target_codegen_vulkan.py
Part of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions. This commit allows DeclBuffer to occur in the lowered TIR passed to CodeGenSPIRV.
=> [Vulkan] Allow DeclBuffer in CodeGenSPIRV

src/target/stackvm/codegen_stackvm.cc, src/target/stackvm/codegen_stackvm.h, tests/python/unittest/test_target_codegen_vm_basic.py
Part of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions. This commit allows DeclBuffer to occur in the lowered TIR passed to CodeGenStackVM.
=> [StackVM] Updated CodeGenStackVM to handle DeclBuffer

src/tir/transforms/storage_flatten.cc, tests/python/unittest/test_tir_transform_storage_flatten.py
This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in StorageFlatten's input

src/runtime/contrib/cublas/cublas_json_runtime.cc, src/runtime/contrib/cublas/cublas_utils.cc, src/runtime/contrib/cublas/cublas_utils.h
Added `CuBlasLtThreadEntry` to cache cublasLt handle. Without it, `cudaDeviceSynchonize` is inserted and causes overhead.
cc @masahi @yelite
=> [Unity][BYOC] Cache cuBlasLt handle with thread entry

gallery/tutorial/uma.py, src/relay/printer/relay_text_printer.cc
Hi @Hzfengsy @comaniac 
This is a minor PR and it aims to fix the typo in the tutorial. I would appreciate that if you can help to review/manage it, thanks.
https://github.com/apache/tvm/issues/14992
=> [#14992][DOC][TUTORIAL] Fix typo for the 'Making your Hardware Accelerator TVM-ready with UMA'

python/tvm/utils/roofline/__init__.py, src/driver/driver_api.cc, src/tir/transforms/make_packed_api.cc, src/tir/transforms/make_unpacked_api.cc, src/tir/transforms/split_host_device.cc, tests/python/contrib/test_ethosu/test_encode_constants.py, tests/python/contrib/test_ethosu/test_tir_to_cs_translator.py, tests/python/unittest/test_tir_transform_make_packed_api.py, tests/python/unittest/test_tir_transform_make_unpacked_api.py, tests/python/unittest/test_tir_transform_split_host_device.py
This simplifies the logic used in MakePackedAPI, as it is now the last user of the host parameter in a function's target.  After MakePackedAPI, every PrimFunc has a "target" attribute without a "host".
This is part of a series of commits to simplify the handling of multi-target builds.
=> [TIR] Move SplitHostDevice to before MakePackedAPI

src/tir/ir/stmt_functor.cc, tests/python/unittest/test_tir_stmt_functor_substitute.py
Previously, occurrences of `DeclBuffer` were not handled by `IRSubstitute`, and the buffer object was left unhandled.  This commit updates `IRSubstitute` to modify the buffer object in `DeclBuffer`, similar to how it is already modified in `BufferLoad` and `BufferStore` instances.
This is a subset of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in IRSubstitute

src/tir/schedule/primitive/decompose_padding.cc, tests/python/unittest/test_tir_schedule_decompose_padding.py
Ran into a type mismatch error when the primfunc uses int64 dimensions, but the extent introduced in a particular case was just int32.
=> [TIR] [Schedule] Fix decompose_padding bug with dtypes

docker/python/bootstrap/lockfiles/constraints-3.7.txt, docker/python/bootstrap/lockfiles/constraints-3.8.txt
A change introduced in the dependencies of Poetry have introduced a bug when building Docker containers and running `ubuntu_install_python.sh`.
The problem links back to CacheControl where one of the linked dependencies is not pinned to a version.
See bug raised for TVM here: https://github.com/apache/tvm/issues/15039
A fix was released for this bug, documented here:
https://github.com/psf/cachecontrol/issues/311
The suggested solution to the problem is to upgrade to v0.12.14, so this patch sets the version constraints accordingly.
cc @areusch @neildhickey @ashutosh-arm @tqchen @Mousius
=> [Bugfix][CI] Fix CacheControl version constraint violation

ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/templates/arm_jenkinsfile.groovy.j2
In order to support SVE testing, migrating the current default AArch64 nodes to Graviton3 based nodes.
cc @areusch @leandron @Mousius @tqchen
=> [CI] Make Graviton3 default AArch64 job runner node

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This PR fixed two bugs in Conv2DTranspose and Conv3DTranspose. Both of them are caused by lacking the parsing of the `output_padding` attribute.
In addition, corresponding test cases were added to capture the bug.
```
import tvm
from tensorflow.keras import layers, models
input_shape = (2, 33,33,128)
input_data = np.random.random(size=input_shape)
x = layers.Input(shape=input_shape[1:], dtype='float32')
kwargs={'filters':2,'kernel_size':[3, 3],'strides':[2, 2],'output_padding':[1, 1],}# 'data_format':"channels_last"} 
layer = keras.layers.Conv2DTranspose(**kwargs)
layer.set_weights(layer.get_weights())
y = layer(x)
model = models.Model(x, y)
model.summary()
res_keras = model(input_data)
shape_dict = {'input_1': …
```
=> [Bugfix][Relay][keras] Fix the bug about the attribute 'output_padding' in Deconv

python/tvm/relax/testing/nn.py
Prior to this commit, use of `nn.Placeholder` or `nn.Parameter` outside of a `with block_builder.function('name'):` scope resulted in an error.  This commit updates the behavior to allow declaration prior to entering the `with` block.  This can be useful for declaring a model object, which is then used to define several related functions.
The scope was required so that `relax.BlockBuilder.current()` could de-duplicate variable names.  While two distinct variables in Relax may have identical names, for user readability it is convenient to have all names be unique within a Relax function.  This commit maintains the de-duplication of names if a `nn.Placeholder` or `nn.Parameter` is defined within an active `relax.BlockBuilder`, that context may be used to provide a unique name.
=> [Unity][NN] Allow nn.Placeholder/Parameter prior to BlockBuilder

ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/templates/arm_jenkinsfile.groovy.j2
This reverts commit 7dc1d6a99f7984855edf1a5c42b66215addeb13f, since CI ARM has been broken on `main` and PR jobs since that commit. See https://github.com/apache/tvm/pull/14983#issuecomment-1583221170 for information.
@Liam-Sturge @ekalda @leandron @tqchen
=> Revert "[CI] Make Graviton3 default AArch64 job runner node (#14983)"

python/tvm/topi/math.py, tests/python/unittest/test_target_codegen_opencl.py
On Adreno devices double type is not supported by OpenCL. Modified `ceil_log2` operation to cast value to float instead of double in case of Adreno.
=> [TOPI][Adreno] Fix problem with ceil_log2

ci/jenkins/generated/arm_jenkinsfile.groovy, ci/jenkins/generated/cortexm_jenkinsfile.groovy, ci/jenkins/generated/cpu_jenkinsfile.groovy, ci/jenkins/generated/docker_jenkinsfile.groovy, ci/jenkins/generated/gpu_jenkinsfile.groovy, ci/jenkins/generated/hexagon_jenkinsfile.groovy, ci/jenkins/generated/i386_jenkinsfile.groovy, ci/jenkins/generated/lint_jenkinsfile.groovy, ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy, ci/jenkins/generated/minimal_jenkinsfile.groovy, ci/jenkins/generated/riscv_jenkinsfile.groovy, ci/jenkins/generated/wasm_jenkinsfile.groovy, ci/jenkins/templates/utils/Prepare.groovy.j2
This is needed for https://github.com/apache/tvm/pull/15046. It has been split from the PR since changing the CI config seems to require sending a PR from `apache`.
=> [CI] Clone submodule recursively 

src/tir/analysis/estimate_flops.cc, tests/python/unittest/test_tir_analysis_estimate_tir_flops.py
Previously, any `DeclBuffer` node in the TIR passed to `FlopEstimator` would throw an error.  This is a subset of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR][Analysis] Handle DeclBuffer in FlopEstimator

src/tir/schedule/transform.cc, src/tir/transforms/ir_utils.cc, tests/python/unittest/test_tir_schedule_compute_at.py
Part of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions.  This commit allows TIR `compute_inline`, `compute_at`, and `reverse_compute_at` schedule primitives to preserve `DeclBuffer`
nodes.
=> [TIR] Handle DeclBuffer in Inline/ComputeAt/ReverseComputeAt

src/tir/transforms/lower_custom_datatypes.cc, tests/python/unittest/test_custom_datatypes.py
Preserve DeclBuffer node when transforming with `LowerCustomDatatypes` This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in LowerCustomDatatypes

.gitmodules, CMakeLists.txt, cmake/modules/contrib/CUTLASS.cmake, licenses/LICENSE.cutlass_fpA_intB_gemm.txt
I extracted fp16 A - int8/4 GEMM kernel from FasterTransformer (see https://github.com/NVIDIA/cutlass/discussions/911) to make it easier to build and integrate into TVM. The code has been extracted and cleaned in the repo under `tlc-pack` and it is being added as a submodule.
A follow-up PR will update the CUTLASS BYOC to support offloading to this kernel. It is going to be useful for weight-quantized LLM inference.
Please review the license stuff etc @tqchen @junrushao @vinx13 @sunggg
=> [BYOC] Add GEMM kernel from FasterTransformer as submodule

src/runtime/relax_vm/lm_support.cc, src/runtime/relax_vm/memory_manager.cc, tests/python/relax/test_runtime_builtin.py
This would be useful when creating multiple kv caches with the same shape. On A10G, compared to creating 64 kv caches separately in LLaMA from mlc-llm, doing a single allocation can save about 35 ms.
@tqchen @junrushao
=> [Unity] Add an API to create multiple kv caches with single allocation

docker/install/ubuntu_install_cmsis.sh
Routine update of CMSIS-NN to v4.1.0. Release notes can be found at http://github.com/ARM-software/CMSIS-NN/releases/tag/v4.1.0.
cc @leandron @NicolaLancellotti @lhutton1 @neildhickey
=> [CMSIS-NN] Update CMSIS-NN release to v4.1.0

include/tvm/relax/nested_msg.h, python/tvm/relax/expr.py, src/relax/backend/vm/vm_shape_lower.cc, src/relax/ir/expr.cc, tests/python/relax/test_blockbuilder_core.py
The index provided must be non-negative, and less than the size of the tuple.  When the tuple being accessed has `TupleStructInfo`, the upper bound can also be checked immediately.
=> [Unity] Added bounds checking on TupleGetItem index

python/tvm/relax/op/mask.py
Add masked_fill operator needed to support MPT-like models on Relax
cc @tqchen
=> [Unity][Relax] Add masked_fill operator

src/target/source/codegen_c.cc, src/target/source/codegen_c.h, src/target/source/codegen_c_host.cc, src/target/source/codegen_c_host.h, src/target/source/codegen_cuda.cc, src/target/source/codegen_opencl.cc, src/target/source/codegen_vhls.cc
Prior to this PR, the return type for `CodeGenC` was hard-coded as part of `virtual CodeGenC::PrintFuncPrefix`, regardless of the return type specified in the `PrimFunc`.  This PR updates `CodeGenC` to use `PrimFuncNode::ret_type` for the return type in the generated C code.
This change should have no effect on observable behavior, while allowing the forward declaration of external functions to be improved.  The majority of codegen classes specified a `void` return type, which matches the default `DataType::Void()` for a `PrimFunc`.  The one exception is `CodeGenCHost::PrintFuncPrefix`, which specified an `int32_t` return type, matching the `DataType::Int(32)` used for the functions generated by `MakePackedAPI` and `MakeUnpackedAPI`.
=> [CodeGenC] Use PrimFuncNode::ret_type in function signature

src/relax/transform/few_shot_tuning.cc, tests/python/relax/test_transform_few_shot_tuning.py
Previously the building of PrimFuncs in Few Shot Tuning pass will fail when the function attribute `global_symbol` is missing. This PR manually adds a global symbol of `main` for each PrimFunc to tune and the unit tests are modfied accordingly.
Thanks @masahi for identifying this issue.
=> [Unity] Fix FewShotTuning Failure When Missing Global Symbol

src/arith/iter_affine_map.cc, tests/python/unittest/test_arith_iter_affine_map.py
This PR enhances arith simplify to handle symbolic reshape patterns. Lift the CombineIters to callers of TryFuseIters so they can be used in early return simplifications. Testcases are added.
Also updates a minor spelling issue in the testcase.
=> [ARITH] Improve arith simplify to handle symbolic reshape pattern

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This PR removed the wrong assertion about UpSampling2D.
In the Keras frontend of TVM, The UpSampling2D has a wired constraint: "Height must equal width for operator Upsample." 
However,  from the [documentation about UpSampling2D](https://keras.io/api/layers/reshaping_layers/up_sampling2d/), The constraint about `size` is, " Int, or tuple of 2 integers".  Meanwhile, An official example from the Keras documentation uses the size(1, 2)
Thus, the assertion in TVM is wrong. I deleted the related statements and added a bug-triggering test case.
@echuraev @masahi @Hzfengsy
=> [Bugfix][Relay][Keras] Fix UpSampling2D about the wrong assertion about size

src/relax/analysis/tir_op_pattern_kind.cc, tests/python/relax/test_analysis.py, tests/python/relax/test_transform_rewrite_dataflow_reshape.py
This PR supports the reshape PrimFunc detection analysis with iter-map-simplify, in order to better support TIR functions with dynamic variables, which is not well handled before.
Meanwhie, this PR also keeps the existing analysis logic, so that we are still able to cover the cases like reshape with raggedness.
Unit tests for reshape are added to ensure correctness.
=> [Unity][Analysis] Reshape TIR detection with iter-map-simplify

docker/build.sh
Change to build.sh to be able to pass environment variables to a container in a similar fashion to bash.sh.
cc @leandron @neildhickey @areusch @tqchen
=> [Docker] Add build.sh environment variables

src/target/target_kind.cc
now llvm declares rocm arch in a different way, as we can observe that gfx90a/90c is not an integer only arch name which will cause some issues when generate code under the latest amd gpus:
```cpp
``EF_AMDGPU_MACH_AMDGCN_GFX801``     0x028      ``gfx801``
``EF_AMDGPU_MACH_AMDGCN_GFX802``     0x029      ``gfx802``
``EF_AMDGPU_MACH_AMDGCN_GFX803``     0x02a      ``gfx803``
``EF_AMDGPU_MACH_AMDGCN_GFX810``     0x02b      ``gfx810``
``EF_AMDGPU_MACH_AMDGCN_GFX900``     0x02c      ``gfx900``
``EF_AMDGPU_MACH_AMDGCN_GFX902``     0x02d      ``gfx902``
``EF_AMDGPU_MACH_AMDGCN_GFX904``     0x02e      ``gfx904``
``EF_AMDGPU_MACH_AMDGCN_GFX906``     0x02f      ``gfx906``
``EF_AMDGPU_MACH_AMDGCN_GFX908``     0x030      ``gfx908``
``EF_AMDGPU_MACH_AMDGCN_GFX909``     0x031      ``gfx909`` …
```
=> [Target][rocm] Replace rocm arch parsing from int to string

src/relay/backend/aot_executor_codegen.cc
Prior to https://github.com/apache/tvm/pull/14951, these can have erroneous simplifications when used in buffer definitions.  While they no longer cause issues with correct-ness, they are unnecessary in this case.  This was initially found when debugging CI failures that occured in https://github.com/apache/tvm/pull/14985, but is not otherwise related to that PR.
=> [AOT] Avoid Var-to-Var Let binding in AOTExecutorCodegen

src/target/source/codegen_c.cc, src/target/source/codegen_c.h, src/target/source/codegen_c_host.cc, src/target/source/codegen_c_host.h, src/target/stackvm/codegen_stackvm.cc, src/tir/transforms/make_packed_api.cc, src/tir/transforms/make_unpacked_api.cc, tests/python/unittest/test_tir_transform_lower_tvm_builtin.py, tests/python/unittest/test_tir_transform_make_packed_api.py, tests/python/unittest/test_tir_transform_make_unpacked_api.py
Previously, the return value of a PackedFunc was hard-coded as the string `"return 0;"` in `CodeGenCHost`, which could cause compilation errors for `PrimFunc` returning `DataType::Void()`.  This PR removes this explicit return statement from `CodeGenCHost`, replacing it with `tir::ret(Integer(0))` in the `MakePackedAPI` and `MakeUnpackedAPI` transforms.
This is related to https://github.com/apache/tvm/pull/15073, which performs an analogous change for the function signature.
=> [TIR][CodeGen] Define PackedFunc error code in MakePackedAPI

python/tvm/tir/op.py, tests/python/unittest/test_tvmscript_roundtrip.py
Previously, some operations in `tvm.tir.op` required the operand to already be a `PrimExpr`, and raised an error if the operand was instead a python object.  This could cause failures round-trip through TVMScript, as int32 and float32 types are printed as literals in TVMScript, relying on automatic conversion to convert them back into `PrimExpr` objects.  For example, `T.expr2(T.int32(0))` is printed as `T.expr2(0)`, which then passes the python object `0` into `tvm.tir.op.expr2` when parsing the TVMScript.
This commit updates the operations in `tvm.tir.op` to convert operands prior to accessing `operand.dtype`, avoiding the error and allowing these expressions to round-trip.
This issue was first noticed in https://github.com/apache/tvm/pull/15076 for `T.ret(0)`, but applied to any …
=> [TIR][TVMScript] Convert tir.op operands to PrimExpr

ci/jenkins/docker-images.ini
Update ci_arm docker image to take llvm-16 from package.
Update ci_cpu docker image to correctly named one.
=> [Docker] Update docker images for llvm-16

src/tir/analysis/var_use_def_analysis.cc, src/tir/analysis/var_use_def_analysis.h, src/tir/transforms/remove_no_op.cc, tests/python/unittest/test_tir_transform_remove_no_op.py
When `RemoveNoOp` removes an unused allocation, it should also remove all `DeclBuffer` nodes that refer to that allocation.  This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in RemoveNoOp

src/tir/transforms/inject_double_buffer.cc, tests/python/unittest/test_tir_transform_inject_double_buffer.py
Preserve DeclBuffer node when transforming with `InjectDoubleBuffer` This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in InjectDoubleBuffer

src/tir/transforms/lower_device_storage_access_info.cc, tests/python/unittest/test_tir_transform_lower_device_storage_access_info.py
Preserve DeclBuffer node when transforming with `LowerDeviceStorageAccessInfo`.  Any `DeclBuffer` nodes that refer to removed `Allocate` nodes are themselves removed.  This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in StorageAccessInfoLower

src/tir/transforms/flatten_buffer.cc, src/tir/transforms/merge_dynamic_shared_memory_allocations.cc, tests/python/unittest/test_tir_transform_merge_dynamic_shared_memory_allocations.py
Preserve DeclBuffer node when transforming with `MergeDynamicSharedMemoryAllocations`.  Any `DeclBuffer` nodes that refer to merged allocations nodes are updated to refer to the merged allocation.  This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR] Handle DeclBuffer in MergeDynamicSharedMemoryAllocations

src/tir/transforms/lower_thread_allreduce.cc, src/tir/transforms/update_pointer_storage_scope.cc, src/tir/transforms/update_pointer_storage_scope.h, tests/python/unittest/test_tir_transform_lower_thread_all_reduce.py
Part of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions. This commit allows the `LowerThreadAllreduce` pass to handle `DeclBuffer` nodes that occur within its input.
=> [TIR] Handle DeclBuffer in LowerThreadAllreduce

src/tir/usmp/transform/convert_pool_allocations_to_offsets.cc, tests/python/unittest/test_tir_usmp_transform_convert_pool_allocations_to_offsets.py
Previously, `PoolAllocationToOffsetConverter` did not remap buffer objects occurring in `DeclBuffer` nodes.  This commit updates `PoolAllocationToOffsetConverter` to handle `DeclBuffer` nodes.  This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.
=> [TIR][USMP] Preserve DeclBuffer in PoolAllocationToOffsetConverter

python/tvm/relay/backend/contrib/ethosu/tir/passes.py, src/tir/contrib/ethosu/passes.cc
This is a subset of changes, being split out from https://github.com/apache/tvm/pull/14778 into independent portions.  For the current TIR that is present at the end of lowering, no behavior changes are expected, as no `DeclBuffer` nodes are present.
=> [Ethos-U][TIR] Handle DeclBuffer in Ethos-U inputs

src/tir/schedule/primitive/cache_read_write.cc, src/tir/transforms/ir_utils.cc, tests/python/unittest/test_tir_schedule_cache_read_write.py
Part of changes being split out from https://github.com/apache/tvm/pull/14778 into independent portions.  This commit allows TIR `cache_read` and `cache_write` schedule primitives to preserve `DeclBuffer` nodes.
=> [TIR] Handle DeclBuffer in CacheReadWrite schedule primitive

src/relax/transform/fuse_tir.cc, tests/python/relax/test_transform_fuse_tir.py
As I described in https://github.com/apache/tvm/pull/14669, when `FuseTIR` gets a fused function whose input includes a tuple, it flattens all tuple fields into parameters and arguments to the call, regardless of the actual usage of the field by the function body. 
It turns out this is problematic for `DataflowReshapeRewrite`, which assumes that the input buffer to the fused reshape function always appears as the first parameter: https://github.com/apache/tvm/blob/unity/src/relax/analysis/tir_op_pattern_kind.cc#L514. As described in https://github.com/apache/tvm/pull/14669, this is not necessarily the case if multiple reshapes follow `split`, since each of the fused `reshape` func gets three buffers as input. So `DataflowReshapeRewrite` fails to eliminate a trivial reshape func like …
=> [Unity][FuseTIR] Flatten and add tuple fields to parameters / arguments only when they are used

src/script/printer/ir_docsifier.cc
This commit fix the issue about:
[Bug] [TVMScript] Progress hang on lowerTE during build dynamic Relay IR caused by endless ReprPrintTIR. https://github.com/apache/tvm/issues/15048
=> [TVMScript] Avoid visiting repetition tensor in SetCommonPrefix Visitor

python/tvm/exec/rpc_proxy.py
The option `port-end` can be used to avoid the RPC proxy start with an unexpected port number, which may cause RPC servers can't be connected correctly when the network is recovered, this is important especially for auto testing system.
=> [RPC] Add Missing Option "port_end" to RPC Proxy

include/tvm/script/ir_builder/relax/ir.h, python/tvm/script/ir_builder/relax/ir.py, python/tvm/script/parser/relax/entry.py, python/tvm/script/parser/relax/parser.py, src/script/ir_builder/relax/ir.cc, src/script/printer/relax/function.cc, src/script/printer/utils.h, tests/python/relax/test_analysis_contains_impure_call.py, tests/python/relax/test_ast_printer.py, tests/python/relax/test_pipeline.py, tests/python/relax/test_relax_operators.py, tests/python/relax/test_transform.py, tests/python/relax/test_transform_lambda_lift.py, tests/python/relax/test_transform_static_plan_block_memory.py, tests/python/relax/test_tvmscript_parser.py, tests/python/relax/test_tvmscript_printer_relax.py
This PR implements the suggestion proposed in #14899 and allows function purity to be annotated in the `@R.function` decorator instead of using a fake method call (`R.is_pure()` or `R.is_impure()`). This required various changes to the parser to support, but can be used as a template for adding further optional parameters to `@R.function`.
For example, this is how an impure function can be declared:
```python
@R.function(pure=False)
def f(...): ...
```
The default value of `pure` is `True`, so there is no need to include an annotation for a function that is already pure (which will usually be the case in Relax).
Note that it will also still be valid to use the decorator without any arguments, as here:
```python
@R.function
def f(...): ...
```
See `entry.py` for how the `function` …
=> [Unity][Relax][UX] Specify function purity in the @R.function decorator

NOTICE, docs/conf.py
Hi @yzh119 @Hzfengsy 
This is a minor PR and it aims to update the copyright year from 2020 to 2023. I would appreciate that if you can help to review/manage it, thanks.
#15043
=> [#15043][Docs] Updated the copyright year from 2020 to 2023

src/relax/transform/rewrite_dataflow_reshape.cc, tests/python/relax/test_transform_rewrite_dataflow_reshape.py
The reshape operator expects that the number of elements in the source is the same as the number of elements in the result. There are operators that could have a reshape pattern that don't meet this requirement (e.g. strided_slice), and they should not be converted to reshape.
=> [Unity][Relax] Make RewriteDataflowReshape only rewrite volume-preserving ops

python/tvm/relay/backend/contrib/ethosu/tir/compiler.py, python/tvm/relay/backend/contrib/ethosu/vela_api.py, tests/python/contrib/test_ethosu/test_encode_constants.py, tests/python/contrib/test_ethosu/test_networks.py
No arguments were passed to CopyComputeReordering pass and the same parameters were used for all targets. This fix takes arguments for CopyComputeReordering pass from Vela.
In networks tests, the amount of memory used for U65 has increased because now after CopyComputeReordering pass, the number of DMA commands executed in parallel has increased.
=> [microNPU][ETHOSU] Fix CopyComputeReordering pass arguments

src/relax/transform/allocate_workspace.cc, tests/python/relax/test_transform_allocate_workspace.py
This PR makes `AllocateWorkspace` allocate workspace in all Relax functions that doesn't have `Codegen` or `Composite` attributes.
cc @masahi
=> [Unity] Allocate workspace for all functions

python/tvm/relay/backend/contrib/ethosu/tir_to_cs_translator.py, tests/python/contrib/test_ethosu/test_tir_to_cs_translator.py
Fix minimum buffer size for DMA operations according to alignment.
=> [microNPU][ETHOSU] Fix minimum buffer size

cmake/modules/contrib/CUTLASS.cmake, python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/relax/backend/contrib/cutlass.py, src/runtime/contrib/cutlass/weight_preprocess.cc, tests/python/relax/test_codegen_cutlass.py
This PR integrates the kernel from https://github.com/tlc-pack/cutlass_fpA_intB_gemm. In addition to the original features in FasterTransformer, this derived implementation also supports residual fusion by https://github.com/tlc-pack/cutlass_fpA_intB_gemm/pull/1. 
* It only supports int4 weight for now, while the kernel supports int8 as well. 
* The kernel expects a simple symmetric quantization scheme where each column of `(K, N)` matrix is scaled by the corresponding element from a scale vector of shape `(N,)`. Each scale is calculated over the K axis.
* The weight matrix needs to be packed into int8 storage with shape `(K, N / 2)`. 
* The packed weight needs to be preprocessed by a special function defined in `contrib/cutlass/weight_preprocess.cc`, which in turn does various …
=> [Unity][BYOC] Integrate fp16 A - int4 B GEMM kernel from FasterTransformer into CUTLASS BYOC 

src/relax/transform/rewrite_dataflow_reshape.cc, tests/python/relax/test_transform_rewrite_dataflow_reshape.py
Follow-up to https://github.com/apache/tvm/pull/15112. Now `Downcast<GlobalVar>` at https://github.com/apache/tvm/blob/unity/src/relax/transform/rewrite_dataflow_reshape.cc#L83 can fail because we can now reach this line even if `call->op` is not `call_tir`.
Fixed by tweaking the reshape detection condition a bit.
@kparzysz-quic
=> [Unity] Minor fix to `RewriteDataflowReshape` condition 

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This PR fixed a bug about `dilation_rate` in SeparableConv2D.
The attribute `dilation_rate` about SeparableConv2D layer has the following constraints in [Keras documentation](https://keras.io/api/layers/convolution_layers/separable_convolution2d/#:~:text=dilation_rate%3A%20An%20integer%20or%20tuple/list%20of%202%20integers%2C%20specifying%20the%20dilation%20rate%20to%20use%20for%20dilated%20convolution.):
> **dilation_rate: An integer or tuple/list of 2 integers, specifying the dilation rate to use for dilated convolution.**
TVM always considered the `dilation_rate` as a default value. This will lead to wrong calculation results.
This PR fix this bug and added the bug-triggering test cases.
```
import tvm
from …
```
=> [Bugfix][Relay][Keras] Fix SeparableConv2D conversion in dilation_rate attribute

src/arith/int_set.cc, src/tir/schedule/state.cc, tests/python/unittest/test_tir_schedule_analysis.py
Generate empty interval sets when empty extents are encountered.
Handle empty regions when constructing ScheduleState.
The direct cause of the crash was constructing an expression `0 - pos_inf`: the latter operand is actually of type `handle`.  The root cause of the issue was that the region connected to `T.grid(0, 8, 8)` was not explicitly recognized as empty early enough, and the extent of 0 was simply used in the related arithmetic to compute further expressions.
Without the fix, the testcase fails with the following traceback:
```
[15:08:28] /w/src/aitools/tvm-upstream/src/tir/op/op.cc:174: 0 pos_inf
File "grid0.py", line 27, in <module>
sch = tvm.tir.Schedule(foo)
File "/w/src/aitools/tvm-upstream/python/tvm/tir/schedule/_type_checker.py", line 340, …
```
=> [Arith][TIR] Recognize empty extents

include/tvm/arith/iter_affine_map.h, python/tvm/arith/__init__.py, python/tvm/arith/iter_affine_map.py, src/arith/iter_affine_map.cc, src/arith/product_normal_form.h, tests/python/unittest/test_arith_iter_affine_map.py
This PR adds an arith util function NormalizeToIterSum.
This function normalizes an index to sum of iterators by scale.
The iterator splits are simplified when possible and ordered by their constant scale and number of prod symbols in descenting order.
We also ensures that each scale is in the form of symbol * const (e.g. n * m * 4). This function is useful to detect stride patterns in buffer access.
=> [ARITH] NormalizeToIterSum

src/arith/iter_affine_map.cc
This PR hotfixes a flaky test in padded matmul
=> [ARITH] Hotfix flaky test in padded matmul

src/tir/transforms/split_host_device.cc, tests/python/unittest/test_tir_transform_split_host_device.py
Previously, the names were de-duplicated within the device module. This commit updates `SplitHostDevice` to have unique names across both the host and device module.  This primarily guards against cases where the name `"func_kernel"` is already in use.
=> [TIR] Avoid duplicate GlobalVar names in SplitHostDevice

src/relay/transforms/device_planner.cc, tests/python/relay/test_pass_plan_devices.py
This PR addresses an issue #15019 I opened previously, regarding the PlanDevices pass's failure in cases where two operators share the same input but are intended to be assigned to different target devices. This scenario can often occur in the context of a neural network, where multiple layers can process the same input.
In the specific case of an operation `(a+b)*(b+c)`, where the first add operator is assigned to the CPU and the second one to the GPU, PlanDevices pass would fail as it had difficulty determining the correct device for b.
The problematic behavior seemed to be due to PlanDevices pass marking `b` for the CPU (when it first visits `a+b`), and then throwing an error when it attempts to place b on the GPU while visiting `b+c`.
The solution I've implemented in this PR is the …
=> [Bugfix] [Relay] Insertion of "device_copy" CallNode to Resolve Device Conflict on Unconstrained Nodes

include/tvm/relax/transform.h, python/tvm/relax/transform/transform.py, src/relax/transform/eliminate_common_subexpr.cc, tests/python/relax/test_transform_cse.py
This PR makes use of purity tracking to apply common subexpression elimination outside of `DataflowBlock`s, making it a `FunctionPass`. The pass checks whether subexpressions contain an impure call before deciding whether they can be safely deduplicated.
=> [Unity][Relax] Generalize CSE to work outside DataflowBlocks

src/runtime/ndarray.cc, tests/python/unittest/test_runtime_dlpack.py
Currently, `NDArray::CreateView(...)` requires the strides of the input array to be null. This makes it impossible to apply, for example, reshaping on an array which originally comes from PyTorch via `from_dlpack`.  
This PR relaxes the null check to allow non-null strides, as long as they are "compact". But after creating a view, the returned array no longer has strides.
This is a subset of new functionalities from another PR https://github.com/apache/tvm/pull/14771, which ended up causing disruptive changes across the stack. 
@Lunderberg @tqchen @vinx13 @yelite @sunggg
=> [NDArray] Allow creating a view from a strided array

tests/python/unittest/test_tir_nodes.py
The original code has
```
with pytest.raises(tvm.error.TVMError):
s.astype("int")
assert "Can't cast a handle to other types" in str(e)
```
The `astype` is expected to throw a TVMError exception, but if it does, the following assertion never gets executed.
Add try/except to the test to verify that the expected exception is thrown.
=> [Test] Improve check for TVMError exception in test_cast

src/target/llvm/llvm_module.cc
Previously, the `#if TVM_LLVM_VERSION` checks made it difficult to determine the logic of  LVMModuleNode::SaveToFile while debugging. This commit pulls out the preprocessor directives into wrapper functions that maintain the same compatibility, making it easier to follow the logic of the `SaveToFile` function.
=> [LLVM] Minor refactor to LLVMModuleNode::SaveToFile

tests/python/relax/test_transform_cse.py
The recently merged PR #15047 had a bad interaction with #15109, which was merged first. This PR includes the correct purity annotations in the CSE tests.
=> [Unity][Bugfix] Fix purity annotation in CSE test

src/target/llvm/codegen_amdgpu.cc, src/target/llvm/codegen_llvm.cc, src/target/llvm/codegen_llvm.h, src/target/llvm/codegen_nvptx.cc
Prior to this commit, the `"ret_void"` argument needed to be explicitly provided to `CodeGenLLVM::AddFunction` and `CodeGenLLVM::DeclareFunction`.  If this was inconsistent with the `builtin::ret()` usage within the `PrimFunc`, this could cause the incorrect return type in the generated LLVM-IR, resulting in LLVM IR verification failures.
This commit removes the `"ret_void"` argument, instead using the type annotation in `PrimFunc::ret_type`, removing this opportunity for inconsistency.
This PR is intended to fix a ROCm regression reported in https://github.com/apache/tvm/pull/14901#issuecomment-1598863567.
=> [LLVM] Remove the "ret_void" argument of AddFunction

apps/microtvm/cmsisnn/requirements.txt, apps/microtvm/ethosu/requirements.txt, docker/install/ubuntu_install_vela.sh, gallery/how_to/work_with_microtvm/micro_ethosu.py, python/gen_requirements.py
Upgrading ethos-u-vela version to 3.8.0.
=> [microNPU] Upgrade Vela to v3.8.0

python/tvm/dlight/__init__.py, python/tvm/dlight/base/__init__.py, python/tvm/dlight/base/schedule_rule.py, python/tvm/dlight/base/transform.py, python/tvm/dlight/gpu/__init__.py, python/tvm/dlight/gpu/fallback.py, src/tir/schedule/analysis/analysis.cc, tests/python/dlight/test_schedule_rule.py
This PR introduces a new package `tvm.dlight`. DLight provides infra to implement composable default schedules to TVM IRModule
=> [Unity] Scaffolding DLight

include/tvm/tir/block_dependence_info.h, include/tvm/tir/block_scope.h, include/tvm/tir/utils.h, python/tvm/tir/__init__.py, python/tvm/tir/block_dependence_info.py, src/tir/ir/block_dependence_info.cc, src/tir/ir/block_scope.cc, src/tir/schedule/state.cc, tests/python/unittest/test_tir_block_dependence_info.py
This work introduces a new object called `BlockDependenceInfo` that computes and returns block dependences. The idea is to be able to expose block level dependences to TIR passes without having to create an explicit schedules.
The patch introduces 2 main classes:
1. `SRefTreeCreator` - This creates and returns a new SRefTree and returns a map from original statements to corresponding srefs
2. `BlockDependenceInfo` - This object computes the actual dependences between blocks within a block scope and returns it for access in TIR passes
This is a continuation to
[PR #15034](https://github.com/apache/tvm/pull/15034) and completes the work started there to expose block level dependences to TIR passes
Note: One major difference between the SRef Tree created for dependence analysis here versus …
=> [TIR] Block dependence analysis without schedules

docker/build.sh
The build.sh script was not actually passing the environment variable to the docker image.
=> [Docker] Fix build.sh environment variables

python/tvm/te/operation.py
Fixing small typo in ‘python/tvm/te/operation.py’
=> [TIR] Fix typo in code example

python/tvm/meta_schedule/testing/space_generation.py, src/tir/schedule/primitive/compute_inline.cc, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_intrin.py, tests/python/unittest/test_meta_schedule_schedule_rule_mlt_tc.py, tests/python/unittest/test_meta_schedule_space_cuda_winograd.py, tests/python/unittest/test_tir_schedule_compute_inline.py, tests/python/unittest/test_tir_schedule_tensorize_ldmatrix_mma.py
This PR enhances `compute-inline` and `reverse-compute-inline` to handle more complicated fusion patterns where the RHS of the equation could be generic expressions rather than strict buffer indexing. This could be used in multiple cases in LLM inference.
=> [TIR][Schedule] Enhance `compute-inline` for fusion

docs/dev/how_to/how_to.rst, docs/dev/how_to/setup_rpc_system.rst
The image file is send to the 
https://github.com/tlc-pack/web-data repo, please merge it first and then the image in this PR will be shown correctly.
=> [DOC] Add RPC System Setup Document

python/gen_requirements.py
This python dependency missing problem has been reported in https://github.com/apache/tvm/pull/14244, the same code was merged before, but strangely, the relevant changes were reverted in the latest commit. @areusch
But it can be confirmed that typing_extensions is still needed by tvmc at least: [source code of tvm.meta_shedule.builder.builder](https://github.com/apache/tvm/blob/main/python/tvm/meta_schedule/builder/builder.py#L21)
It is worth mentioning that this problem affects the [tvm source code download page](https://tvm.apache.org/download), at least version 0.12.0. In fact, I encountered the **ModuleNotFoundError** error when installing tvm from source code and trying to **call tvmc**. You can reproduce this error with the following command:
```sh
wget …
```
=> [Bug] Add typing_extensions requirement again

python/tvm/relay/backend/contrib/ethosu/softmax_rewriter.py, tests/python/contrib/test_ethosu/test_legalize.py
Fix SoftMax legalization parameters according to the values in Vela.
=> [microNPU][ETHOSU] Fix SoftMax legalization parameters

python/tvm/_ffi/runtime_ctypes.py
In TVM C++, the dtype `void` is designated to represent "non-existing" data types, but this was not exposed to Python at the moment. This PR brings up such support on Python side for consistency.
=> [Runtime] Support void as dtype in FFI

src/tir/transforms/renew_defs.cc, tests/python/unittest/test_tir_renew_defs.py
There are cases where the shapes of input buffers are symbolic, but the first symbol is a composite PrimExpr rather than a TIR Var, which the original implementation does not take this into account.
Example:
```python
@T.prim_func
def main(a: T.handle, b: T.handle):
m = T.int64()
A = T.match_buffer(a, (m * 2,))  // `m` first appears as composite
B = T.match_buffer(b, (m, 2))
```
=> [TIR] Fix RenewDef for symbolic input shapes

python/tvm/tir/analysis/analysis.py, src/tir/analysis/var_use_def_analysis.cc
This PR exposes the UndefinedVars analysis to Python. This is useful for iterator and index access analysis.
=> [TIR] Expose UndefinedVars to Python

python/tvm/relay/backend/contrib/ethosu/codegen.py, python/tvm/relay/backend/contrib/ethosu/util.py, src/relay/backend/contrib/ethosu/compiler_attrs.cc, tests/python/contrib/test_ethosu/test_scheduler.py
Added the option to disable copying constants for the case when the user determines in the linker script for section ".rodata.tvm" that the constants are located in SRAM.
To activate this option, pass the `--target-ethos-u-disable_copying_constants=1` argument to tvmc.
=> [microNPU][ETHOSU] Add option to disable copying constants for case without cascader

include/tvm/runtime/logging.h, python/tvm/error.py, src/runtime/logging.cc
This PR introduces some cleanups on the stacktraces in TVM's error message by removing the meaningless frames, for example, C++ template dispatch with `std::enable_if`.
=> [Runtime] Clean TVM stacktrace in error messages

src/script/ir_builder/relax/ir.cc, tests/python/relax/test_transform_fuse_ops.py, tests/python/relax/test_transform_fuse_ops_by_pattern.py, tests/python/relax/test_transform_rewrite_cuda_graph.py, tests/python/relax/test_tvmscript_parser.py
A small follow-up to #15140, which was merged before I could make this addition: This change throws an error if a function has been annotated as private but the user manually specifies the global symbol. Since it is a contradiction to do so, it is best to detect this error rather than have it silently work (with the effect of actually making the function public).
=> [Unity][UX][Tweak] Make it an error to mark a function private and specify a global symbol

include/tvm/tir/buffer.h, python/tvm/tir/schedule/schedule.py, src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc, src/tir/schedule/analysis.h, src/tir/schedule/analysis/analysis.cc, src/tir/schedule/primitive.h, src/tir/schedule/primitive/pad_einsum.cc, src/tir/schedule/transform.cc, tests/python/unittest/test_tir_schedule_analysis.py, tests/python/unittest/test_tir_schedule_pad_einsum.py
This PR introduces a minor behavior change in Pad-Einsum that makes it support padding-by-factor instead of padding-by-constant-number.
=> [TIR][Schedule] Support padding-by-factor in PadEinsum

python/tvm/relay/frontend/tflite.py, src/relay/qnn/op/convolution_transpose.cc, tests/python/frontend/tflite/test_forward.py
Loading int16 conv transpose op in tflite model currently fails because output type is not int64.
This patch adjusts output type to int64 for int16 quantized transpose convolution operation. In addition, one typo in QnnConv2DTransposeRel is fixed.
Test script is also included to evaluate the loading of int16 quantized transpose convolution op.
=> [FRONTEND][TFLITE][BugFix] Fix int16 transpose conv loading

include/tvm/runtime/relax_vm/memory_manager.h, src/runtime/relax_vm/memory_manager.cc
This PR supports clearing up all the allocated memory in among relax VMs.
Prior to this PR, all the allocated memory are managed in the pool of memory manager. The allocated memory in the pool is never freed and the pool size always goes up monotonically.
While good to save time of memory allocation, in some cases (e.g., on mobile phones which may have running memory limit) we need to clear the pool and free all the memory in order to prevent the pool from endlessly growing up and some of allocated memory not being effectively utilized.
Therefore, this PR introduces a PackedFunc that helps clear the pool.
=> [Unity] Support clear global memory allocators

src/runtime/builtin_fp16.cc
This PR add weak symbol to remaining functions in builtin fp16. Weak is needed because such builtin function can be provided by other libraries and we only need one runtime implementation of it.
=> [RUNTIME] Add weak symbol to builtin fp16

python/tvm/testing/__init__.py, python/tvm/testing/rpc_run.py
This PR introduces `tvm.testing.rpc_run`, a utility method that allows a `runtime.Module` to run on a remote device via TVM RPC.
Example:
```python
import tvm
from tvm.testing import rpc_run
@T.prim_func
def cuda_kernel(
A: T.Buffer((128,), "float32"),
B: T.Buffer((128,), "float32"),
):
for bx in T.thread_binding(4, thread="blockIdx.x"):
for tx in T.thread_binding(32, thread="threadIdx.x"):
x = bx * 32 + tx
B[x] = A[x] + 1.0
def main():
np_a = np.random.randn(128).astype("float32")
np_b = np_a + 1.0
rt_mod = tvm.build(cuda_kernel, target="nvidia/geforce-rtx-3090-ti")
tvm_a, tvm_b = rpc_run(
rt_mod,
"cuda",
[np_a, np_b],
)
assert np.allclose(tvm_b, np_b)
```
Result:
```
Execution time summary:
mean (ms)   median (ms)    max (ms)     min …
```
=> [Testing] Utility method to run TVM on remote device

src/relax/ir/py_expr_functor.cc, tests/python/relax/test_expr_functor.py
As we discussed in https://discuss.tvm.apache.org/t/recursive-visiting-in-pyexprmutator/15224, 
It will run into an infinite recursion if we call the super() visit function in PyExprVisitor and PyExprMutator.
```python
super().visit_binding_block_()
super().visit_dataflow_block_()
super().visit_var_def_()
super().visit_dataflow_var_def_()
```
This PR fixes the behavior.
=> Fix super() visit function in PyExprVisitor and PyExprMutator

python/tvm/exec/microtvm_debug_shell.py, python/tvm/rpc/server.py, python/tvm/rpc/tracker.py
This PR fix a RPC issue on Windows by disabling socket SO_REUSEADDR flag. This flag works as expected on POSIX platforms, but will cause indeterminate behaviors on Windows sockets.
Reference: https://learn.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse#using-so_reuseaddr
=> [RPC] Disable socket SO_REUSEADDR for Windows

.github/workflows/main.yml, python/gen_requirements.py, python/setup.py
This PR allows us to package some extra directories with TVM wheels for developing other language bindings.
=> [Python] Enhance Wheel Packaging

src/tir/ir/stmt_functor.cc, src/tir/transforms/lower_match_buffer.cc, tests/python/unittest/test_tir_lower_match_buffer.py, tests/python/unittest/test_tir_transform_unify_thread_binding.py
Currently, the `elem_offset` member in `match_buffer`'s will not be visited in default block visitor functions, resulting in some passes cannot correctly rewrite the program because some fields have not been entered.
This PR fixes the issue by visiting this field in default StmtVisitor and StmtExpr.
=> [TensorIR][Visitor] Visit buffer members in `match_buffer`'s in block visitor functions

include/tvm/runtime/relax_vm/memory_manager.h, python/tvm/relax/op/vm/vm.py, python/tvm/runtime/relax_vm.py, src/relax/backend/vm/codegen_vm.cc, src/relax/backend/vm/vm_builtin_lower.cc, src/relax/op/op.cc, src/relax/op/op_common.h, src/runtime/relax_vm/builtin.cc, src/runtime/relax_vm/memory_manager.cc, src/runtime/relax_vm/naive_allocator.h, tests/python/contrib/test_hexagon/test_relax_2d_buffer_allocation.py, tests/python/relax/test_transform_static_plan_block_memory.py, tests/python/relax/test_tvmscript_parser.py, tests/python/relax/test_vm_alloc_storage_with_scope.py, tests/python/relax/test_vm_codegen_only.py, tests/python/relax/test_vm_cuda_graph.py, tests/python/relax/test_vm_execbuilder.py
This patch adds a new Allocator type called NDAllocator as discussed in [this discussion](https://discuss.tvm.apache.org/t/memory-scope-for-vm-alloc-storage-builtins/15172).
The new allocator allows allocating to other memory scopes and allows nd-allocation.
=> [Unity] Add memory scope and nd allocation support in allocators

python/tvm/error.py, python/tvm/rpc/server.py, src/runtime/rpc/rpc_endpoint.cc, src/runtime/rpc/rpc_socket_impl.cc, tests/python/unittest/test_runtime_rpc.py
By using RPC server in NPU board, at some time a compiled model will hang the NPU, because of the buggy operator libraries of NPU toolchain, so we must to use the session_timeout to ensure the board resource can be released by the hang jobs.
Currently the handling of session timeout error in RPC server is not good, it just kill the server loop sub process, then in the destructor of  class `RPCEndpoint` will send the code of `kShutdown` to the RPC client, but the RPC client expect receive the code of `kReturn` or `kException`, so users will see the error message that like the one reported in  https://github.com/apache/tvm/issues/15151, this error report will make users very confused and don't know what's happened.
When using tuning to search a good schedule for operators, we only want to …
=> [RPC] Report RPC Session Timeout to Client Instead of "kShutdown"

include/tvm/arith/analyzer.h, src/arith/analyzer.cc, src/arith/const_int_bound.cc, src/arith/ir_mutator_with_analyzer.cc, src/arith/ir_mutator_with_analyzer.h, src/tir/transforms/flatten_buffer.cc, src/tir/transforms/simplify.cc, tests/python/unittest/test_arith_const_int_bound.py, tests/python/unittest/test_tir_transform_simplify.py
This PR introduces an utility function MarkGlobalPositiveValue. This function allows analyzer to mark buffer shapes in function arguments as positive globally and opens doors for more symbolic simplification.
=> [ARITH] Allow Analyzer to MarkGlobalNonNegValue

include/tvm/tir/transform.h, include/tvm/tir/var.h, python/tvm/tir/transform/transform.py, src/driver/driver_api.cc, src/meta_schedule/postproc/verify_gpu_code.cc, src/tir/ir/expr.cc, src/tir/transforms/lift_thread_binding.cc, tests/python/unittest/test_tir_transform_lift_thread_binding.py
This PR adds a pass LiftThreadBinding to TIR.
Previously, during GPU cross-thread reduction, a temporary local buffer will be created in the RF buffer, as a concrete example:
```python
rf_local = T.alloc_buffer(..., scope="local")
// Step 1. Data parallel RF block
for tx in T.thread_binding(..., thread="threadIdx.x")
rf_local[tx, ...] =
// Step 2. Cross-thread reduction to accumuate rf_local
for ...:
for tx' in T.thread_binding(..., thread="threadIdx.x"):
... += rf_local[tx', ...]
```
In this case, the buffer `rf_local` will only be accessed by a single point `tx` or `tx'`, but during the pass `CompactBuffeRegion`, the two variables as thread bindings are treated as two separate variables, i.e. the information that `tx` and `tx'` are always identical to each other is discarded, which …
=> [TIR][Transform] Add LiftThreadBinding Pass

python/tvm/testing/aot.py
Now that #10300 and #10314 have been closed, we should be able to remove an old previous attempt to help resolve test flakiness.
=> [AOT] Remove workaround to help resolve test flakiness

src/tir/schedule/primitive/compute_at.cc, tests/python/unittest/test_tir_schedule_compute_at.py
This PR enhance the arithmetic analysis used in compute-at to further help symbolic bound simplification.
Previously, when a variable `n` appears in the shape of an input buffer `T.Buffer((n * 32), "float32")`, we could safely assume that `n` is nonnegative as it is part of the shape. This could help us simplify some bounds during scheduling as well as lowering.
For example, for integers `n` and `bx` where `bx` has a symbolic bound `[0, 32 * n)`, if `n` is nonnegative, we could simplify the following expressions to True:
```
0 <= floordiv(bx, n) < 32
0 <= floormod(bx, n) < n
```
This PR depends on #15193 to provide an interface that hints analyzer.
=> [TIR][Schedule] Derive Nonnegative Bounds from Shape Var

conda/recipe/meta.yaml, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/package.json
This bumps all the version numbers following the v0.13.0 branch cut.
cc @driazati @Hzfengsy @tqchen @spectrometerHBH
=> Update version to 0.14.dev0 on main branch

src/tir/transforms/lower_cross_thread_reduction.cc, tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
This PR enhances the LowerCrossThreadReduction pass with the thread-broadcasting block rewrite.
Specifically, previously whenever a TIR block has thread-broadcast behavior (i.e., there exists some thread var which is free for the block), we never insert a predicate for the block and therefore the generated final code has race condition, which sometimes lead to wrong computation results.
This PR enhances the pass by collecting thread var information along transformation, and rewrite the thread-broadcast TIR block with additional predicate clauses which bound the thread vars and effectively state that "only execute the block when `thread_var == 0`". Therefore, the race condition issue in such blocks is resolved.
=> [TIR] Support cross-threaad reduction lowering with thread-broadcasting rewrite

python/tvm/relay/backend/contrib/ethosu/vela_api.py, tests/python/contrib/test_ethosu/test_networks.py, tests/python/contrib/test_ethosu/test_replace_conv2d.py, tests/python/contrib/test_ethosu/test_vela_api.py
For the case when cascader is enabled, the logic of choosing the optimal configuration block from TVM will be used in other cases, the Vela's logic will be used except the cases when dev_force_block_config option is specified.
=> [microNPU][ETHOSU] Add Vela's logic to select configuration block

include/tvm/relax/expr.h, python/tvm/relax/expr.py, src/relax/ir/expr.cc
This PR allows user to specify struct_info for R.constant in its constructor. This feature will be used in distributed constant tensor.
cc: @tqchen
=> [Unity] Allow specifying struct_info for relax constant

python/tvm/contrib/emcc.py
The default EMCC "total memory" is not large enough for end-to-end applications such as Web-LLM. This PR increases the limit to 40MB for compilation.
=> [Web] Increase default EMCC compilation total memory size

src/arith/analyzer.cc, src/arith/product_normal_form.h, tests/python/unittest/test_tir_transform_simplify.py
This PR enhances buffer shape hint so shape expressions like n - 1 will deduce n >= 1
=> [ARITH] Enhance buffer shape bound deduction to include offset

pyproject.toml, python/tvm/dlight/base/analysis.py, python/tvm/dlight/gpu/__init__.py, python/tvm/dlight/gpu/decode_gemv.py, python/tvm/dlight/gpu/fallback.py, python/tvm/dlight/gpu/matmul.py, python/tvm/dlight/gpu/utils.py, tests/python/dlight/test_gpu_decode_gemv.py
This PR enhances Decode-GEMV rule with the following changes:
- Normalize the GEMV iter domain to S-R-C via transform-block-layout.
This would help with further analysis and scheduling, in cases for
example, when there was no spatial loop in the original reduction
block.
- Get rid of the ad hoc iter type analysis, including the logic calling
into a TVM packed func `tir.schedule.GetLoopIterType` using
`tvm._ffi.get_global_func`.
- Split out the logic for two separate cases of scheduling, where the
innermost dimension is spatial or reduction.
- Introduces `suggest_threads_per_block` to guess the threads to be
allocated each threadblock. This helps avoid the previous case where
dlight allocates 256 threads for a workload whose degree of parallelism
is only 128.
- Misc improvements.
This rest …
=> [Dlight] Enhance Decode-GEMV Schedule

src/tir/transforms/default_gpu_schedule.cc, tests/python/unittest/test_transform_default_gpu_schedule.py
This PR adds support for no spatial axes cases for DefaultGPUSchedule.
To be specific, this PR will add this logic
- Find all innermost loops in a tir function
- If a such loop does not have data parallel loop, add a dummy loop for it
=> [Unity][TIR][Transform] Support no spatial axes cases for DefaultGPUSchedule

python/tvm/relax/analysis/estimate_memory_usage.py, tests/python/relax/test_analysis_estimate_memory_usage.py
Previously `tvm.relax.analysis.estimate_memory_usage` will ignore `R.builtin.alloc_tensor` operators when calculating memory usage of the module **after** memory planning. However, such operators indeed increases the memory usage. 
This PR will take such operators into account so as to get correct memory statistics.
=> [Unity] Fix memory statistics issues in estimate_memory_usage

include/tvm/relax/nested_msg.h
This PR adds a helper function called `NestedMsgTo<TargetType>` to map nested message to any specified type. Also, it rewrites `NestedMsgToExpr` using `NestedMsgTo`.
=> [Unity][NestedMsg] Add NestedMsgTo helper function

tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
Prior to this commit, the tests in `test_tir_transform_inject_ptx_async_copy.py` registered the `"tvm_callback_cuda_postproc"` function during pytest collection, and used a global variable to disable its functionality outside of the tests in this file.  This had two major issues.  First, if any other test also installs a postproc function, these postproc function required by the NVPTX tests would be overwritten.  Second, if one of the NTPTX tests fails, the global variable controlling the postproc function would not be reset, causing any subsequent CUDA-related tests to also fail.
This commit updates these NVPTX tests to conditionally install the postproc function, to de-register it after the test instead of disabling its functionality, and to de-register it regardless of the test result. …
=> [UnitTest][NVPTX] Avoid cascading failures from CUDA postproc

python/tvm/dlight/gpu/decode_gemv.py, src/tir/schedule/transform.cc, tests/python/dlight/test_gpu_decode_gemv.py
This PR made two changes:
- Replace the use of `sch.transform_block_layout` with classic
split/fuse/reorder in DecodeGEMV rule. The primitive itself is
designed to be an overkill, but in fact doesn't support symbolic
bounds really well. Meanwhile, generally it wouldn't be necessary to
use this advanced primitive as it might hurt subsequent analysis,
although in our case there isn't any.
- Always make sure there is at least one spatial loop during the initial
PrimFunc normalization. This could help cases of `n -> 1` reduction
to schedule more conveniently.
NOTE: `sch.transform_block_layout` is still used in the PrimFunc
normalization to remove unit loops and ensure at least one spatial loop.
There is no reorder/fusion/split happening in this specific use and
could help with all subsequent …
=> [Unity][Dlight] Avoid TransformBlockLayout in GEMV Rule

python/tvm/tir/analysis/analysis.py, src/tir/analysis/verify_well_formed.cc, tests/python/unittest/test_tir_analysis_verify_well_formed.py
Previously, the calling code needed to iterate over all functions in a module.  This commit adds an overload that accepts `const IRModule&`, allowing it to be called more easily.  This also provides an API that can be extended to validate behavior across an entire IRModule (e.g. requiring that internal function calls have the correct argument types).
=> [TIR] Allow VerifyWellFormed to accept IRModule

src/tir/transforms/inject_double_buffer.cc, src/tir/transforms/ir_utils.cc, src/tir/transforms/lower_custom_datatypes.cc, src/tir/transforms/lower_thread_allreduce.cc, src/tir/transforms/lower_warp_memory.cc, src/tir/transforms/update_pointer_storage_scope.cc
Prior to this commit, some lowering passes would erroneously strip out the annotations from `Allocate` nodes.  This commit updates these passes to preserve the annotations where present.
=> [TIR] Preserve AllocateNode::annotations

python/tvm/dlight/base/analysis.py, python/tvm/dlight/gpu/decode_gemv.py, tests/python/dlight/test_gpu_decode_gemv.py
This PR improves the Decode-GEMV scheduling by further analyzing its epilogue pattern.
The existing behavior assumes that the outcome of cross-thread reduction stays in register files local to each thread, which is further used to calculate the epilogue in the same thread.
This strategy means the cross-thread reduction outcome is stored only on thread 0, while the other threads cannot participate in subsequent computation (i.e. epilogue). Related: https://github.com/apache/tvm/pull/15192.
When the epilogue is relatively lightweight, i.e. elementwise add, casting on scalars, this strategy is optimal. However, once the outcome needs to be broadcasted to compute over a non-trivial region, for example, act as a normalizer of `np.mean`, it would become much slower because only one thread in a …
=> [Unity][Dlight] Handle Epilogue Broadcasting

include/tvm/runtime/relax_vm/executable.h, src/runtime/relax_vm/executable.cc
This PR introduces a new field, `RELAX_VM_VERSION`, to the `Executable` struct. The VM version is more stable than the TVM version, it would be the minimum TVM version it support the current VM status.
cc @tqchen
=> [Unity] Add a Standalone VM Version Number

src/tir/schedule/primitive.h, src/tir/schedule/primitive/cache_read_write.cc, tests/python/unittest/test_tir_schedule_cache_read_write.py
This PR enhances CacheRead/Write so that when a cache operation is performed under an inner block, the generated cache buffer will have the shape as compact as possible, by region consumption analysis.
The motivation of this change comes from the needs of dynamic shape TIR scheduling, in which case we may isolate a "static shape" internal block using blockize, and do further scheduling inside the internal block. For such cases, the current CacheRead/Write inside the static-shape block will still produce dynamic-shape cache buffers, which is not ideal for analysis and subsequent scheduling.
One thing that worths noting is that, to ensure the IR correctness after inserting the cache block, we will only compact the cache buffer when all the consumer blocks of the read buffer (for CacheRead) …
=> [TIR][Schedule] Scoped CacheRead/Write producing compact region

python/tvm/tir/op.py, src/script/ir_builder/ir/ir.cc, src/tir/transforms/make_unpacked_api.cc, tests/python/unittest/test_tvmscript_roundtrip.py
Prior to this commit, the return type of all internal function calls was hard-coded as `"void"`.  After this commit, the `GlobalVar` representing the internal function has type annotation based on the callee's signature, which is then used as the return type of the internal call.
=> [TVMScript] Handle parsing of PrimFunc calls with non-void return

include/tvm/relay/qnn/attrs.h, python/tvm/relay/qnn/op/qnn.py, src/relay/qnn/op/dequantize.cc, src/relay/qnn/op/quantize.cc, src/relay/qnn/utils.h, tests/python/relay/test_op_qnn_dequantize.py, tests/python/relay/test_op_qnn_quantize.py
Current the Relay qnn.dequantize lack of the support to "float16" output, only can dequantize a quant value to "float32", this PR add the lack function, so as "uint16" of qnn.quantize.
=> [QNN] Support Dequantize to "float16" and Quantize to "uint16"

python/tvm/relay/expr_functor.py, tests/python/relay/test_expr_functor.py
The Python version of Relay ExprMutator class haven't do the copy on write operation, this will cause the pass write using Python version of Relay ExprMutator can't distinguish the nodes that is changed.
=> [Relay] ExprMutator Return Origin Expr When All Fields Isn't Changed

src/tir/ir/script/script_complete.cc, tests/python/unittest/test_meta_schedule_postproc_rewrite_parallel_vectorize_unroll.py, tests/python/unittest/test_tir_transform_memhammer_lower_auto_copy.py, tests/python/unittest/test_tvmscript_complete.py
Prior to this PR, the root block of a parsed TIR TVMScript is possible to have non-empty read/write regions, which conflicts with the design of root blocks in TIR.
This PR updates the script completion pass and ensures that the root block will no longer have read/write region.
=> [TVMScript] Ensure completed root block has no read/write

src/tir/transforms/lower_tvm_builtin.cc, tests/python/unittest/test_tir_transform_lower_tvm_builtin.py
For the `stack_shape` and `stack_tcode` buffers, generate a `DeclBuffer`.
This is a subset of the changes made in https://github.com/apache/tvm/pull/14778, broken out for ease of testing and review.
=> [TIR] Output DeclBuffer in LowerTVMBuiltin

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This PR fixed the bug proposed in #15176 and added bug-triggering test cases.
If `go_backwards=True`, the LSTM layer processes the input sequence backward and returns the reversed sequence.
Missing the support for `go_backwards` will lead to wrong inference results in TVM.
cc @Hzfengsy @echuraev
=> [bugfix][frontend][keras] Fix go_backwards attribute of LSTM in keras frontend

python/tvm/testing/__init__.py, python/tvm/testing/runner.py
This PR introduces `tvm.testing.local_run`, which serves as a convenient numpy-in numpy-out interface to quickly run a `runtime.Module` in TVM and obtain its running time and outputs.
Example:
```python
@I.ir_module
class Module:
...
n = 128
np_a = np.random.uniform(-1, 1, [1, 32, 1, 128]).astype(np.float16)
np_b = np.random.uniform(-1, 1, [1, 32, n, 128]).astype(np.float16)
np_c = np.random.uniform(-1, 1, [1, 1, 1, n]).astype(np.float16)
np_d = np.random.uniform(-1, 1, [1, 32, 1, n]).astype(np.float32)
_, _, _, np_d = local_run(
tvm.build(Module, target="llvm"),
device_type="cpu",
args=[np_a, np_b, np_c, np_d],
)
```
=> [Testing] Add tvm.testing.local_run

src/relax/analysis/layout_transformation.cc, src/relax/op/tensor/manipulate.cc, src/relax/transform/alter_op_impl.cc
Following https://github.com/apache/tvm/pull/15264, this PR makes changes accordingly to the Unity branch
to enable symbolic bounds in IndexMap analysis.
=> [Unity][TIR] Allow symbolic bounds in IndexMap analysis

apps/microtvm/arduino/template_project/microtvm_api_server.py
_get_board_from_makefile have read only one string in makefile before I add these changes
=> [BugFix] Fix function to read all file

src/tir/transforms/lower_tvm_builtin.cc, tests/python/unittest/test_tir_transform_lower_tvm_builtin.py
Prior to this commit, the call to `TVMBackendFreeWorkspace` occurred outside the `LetStmt` that defined the workspace pointer.  While works with current codegen, as the code produced for `LetStmt` does not check for out-of-scope access, this access of an out-of-scope should be avoided.
In addition, the `AttrStmt` providing the storage alignment was placed outside the `LetStmt` that defines the variable. As a result, the alignment assumption is never actually used, as `CodeGenLLVM::VisitStmt_(const AttrStmtNode*)` only creates an alignment assumption for in-scope variables.
This PR updates `LowerTVMBuiltin` to produce both the storage alignment `AttrStmt` and the call to `TVMBackendFreeWorkspace` inside the body of `LetStmt`, rather than outside.
=> [TIR] Call TVMBackendFreeWorkspace inside LetStmt

python/tvm/testing/runner.py
Return `profile_result` in `tvm.testing.local_run` and `tvm.testing.rpc_run` for further use.
=> [Testing] Return BenchmarkResult in local_run and rpc_run

python/tvm/contrib/hexagon/transform.py, tests/python/contrib/test_hexagon/test_relay_simplify_qnn_concat.py
This helps in using optimized implementations of concat; this PR also avoids redundant requantization when an input to a concat is already a requantize op.
=> [Hexagon] Propagate QNN Concat Quantization Params to Inputs

python/tvm/relay/op/strategy/arm_cpu.py, python/tvm/topi/arm_cpu/mprofile/dsp/__init__.py, python/tvm/topi/arm_cpu/mprofile/dsp/pool.py, python/tvm/topi/arm_cpu/pooling.py, tests/python/topi/python/test_topi_pooling.py
This commit:
* Adds specialized `arm_cpu` pooling schedules for both fixed width and salable vectors.
* Enables topi testing of new `arm_cpu` schedules.
=> [topi] Add `arm_cpu` specific pooling schedules

src/relax/backend/contrib/codegen_json/codegen_json.h, src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops_by_pattern.py
Currently, `PrimValue` is treated just like a tensors and `FuseOpByPattern` pass creates composite functions that have `PrimValues` as function parameters. 
For example, `param_0` and `param_1` are defined to handle `PrimValues`
```Python
@I.ir_module
class Module:
@R.function(private=True)
def fused_relax_clip(x: R.Tensor((10, 10), dtype="float32"), param_0: R.Prim("int64"), param_1: R.Prim("int64")) -> R.Tensor((10, 10), dtype="float32"):
R.func_attr({"Composite": "x.clip", "Primitive": 1})
gv: R.Tensor((10, 10), dtype="float32") = R.clip(x, param_0, param_1)
R.output(gv)
return gv
@R.function
def main(x: R.Tensor((10, 10), dtype="float32")) -> R.Tensor((10, 10), dtype="float32"):
cls = Module
gv: R.Tensor((10, 10), dtype="float32") = …
```
=> [Unity][BYOC] `PrimValue` handling in `FuseOpByPattern` for BYOC

src/relay/transforms/merge_compiler_regions.cc, tests/python/relay/test_pass_merge_compiler_regions.py
Suppose we have a graph as the image shows. In MergeCompilerRegions pass, R1 will merge to R4 because IfNode didn't propagate restriction regions to R3.
This PR supports the propagation of IfNode to avoid the invalid region merging.
=> [RELAY] Fix bug in MergeCompilerRegions pass

python/tvm/relay/op/strategy/arm_cpu.py, python/tvm/topi/arm_cpu/mprofile/dsp/__init__.py, python/tvm/topi/arm_cpu/mprofile/dsp/pool.py, python/tvm/topi/arm_cpu/pooling.py, tests/python/topi/python/test_topi_pooling.py
=> Revert "[topi] Add `arm_cpu` specific pooling schedules"

python/tvm/exec/gpu_memory_bandwidth.py
This PR adds a script to test GPU memory bandwidth in TVM. Example usage:
```bash
python -m tvm.exec.gpu_memory_bandwidth \
"nvidia/geforce-rtx-3090-ti"        \
--dtype "float32"                   \
--bx "8,16,32,64,128,256"           \
--tx "32,64,128,256,512,1024"       \
--vec "1,2,4"
```
=> [Exec] Add a script to test GPU memory bandwidth

python/tvm/script/parser/_core.py, python/tvm/script/parser/core/entry.py, python/tvm/script/parser/tir/__init__.py, python/tvm/script/parser/tir/entry.py, python/tvm/script/parser/tir/parser.py, tests/python/unittest/test_tvmscript_parser_tir.py
This patch introduces new symbol: `T.macro`. `T.macro` is a decorator that, when applied to a function, turns the body of that function into a piece of TIR that can be inserted into a PrimFunc by calling the macro the same way as a function.
For example:
```python
@T.macro
def copy_backwards(dst, src, size):
with T.block("backwards"):
for i in T.serial(size):
ai = T.axis.remap("S", [i])
T.reads(src[0:size])
T.writes(dst[0:size])
dst[ai] = src[size - ai - 1]
@T.prim_func
def foo_int32(A: T.Buffer((128,), "int32"), B: T.Buffer((128,), "int32")):
copy_backwards(A, B, 128)
@T.prim_func
def foo_int8(A: T.Buffer((128,), "int8"), B: T.Buffer((128,), "int8")):
copy_backwards(A, B, 128)
```
The above will generate two PrimFuncs that do the same backwards copy, but applied to buffers with different …
=> [TIR] Implement TIR macros

python/gen_requirements.py, src/runtime/graph_executor/graph_executor.cc, src/runtime/graph_executor/graph_executor.h, tests/python/unittest/test_set_input_zero_copy.py
As stated in https://github.com/apache/tvm/issues/14978
=> [BugFix][Relay][GraphExecutor] Fix set_input_zero_copy() precision bug

src/support/socket.h
Because `LOG(WARNING)` may invoke system calls, the errno of socket bind failure is overwrite, which make `TryBindPort` exit without any more trials.  The errno check should be put just after `bind` return.
Here is an example from strace,
```
bind(3, {sa_family=AF_INET, sin_port=htons(9200), sin_addr=inet_addr("192.168.35.133")}, 16) = -1 EADDRINUSE (Address already in use)
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
The stacktrace would be (errno became to be ENOENT):
```
terminate called after throwing an instance of 'tvm::runtime::InternalError'
what():  [05:28:22] /tvm/apps/cpp_rpc/../../src/support/socket.h:362: Socket TryBindHost Error:No such file or directory
Stack trace:
[bt] (0) …
```
=> [RPC] Fix socket bind errno on corner case

src/relax/ir/binding_rewrite.cc, tests/python/relax/test_analysis.py
Match_cast can be used to capture symbolic shapes, remove MatchCast binding will cause `Prim Expr xxx has not been computed` in build stage.
=> [Unity][Relax][Transform] Do not remove MatchCast for RemoveAllUnused

python/tvm/relax/frontend/onnx/onnx_frontend.py, tests/python/relax/test_frontend_onnx.py
Register [Trilu](https://onnx.ai/onnx/operators/onnx__Trilu.html) operator for ONNX frontend.
I've provide a test.
=> [Unity] [Relax] [ONNX frontend] [op] Add support for Trilu operator

python/tvm/contrib/cutlass/attention_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py
https://github.com/NVIDIA/cutlass/pull/992
On RTX 4080, I got modest speed up on SD (49 -> 50 it / sec), and tiny speed up on Vicuna 7b (+ 0.2 - 0.3 tok / s). 
They recommend "setting blockSize to 64x128 rather than 32x128 after Sm75". On RTX 4080 + SD, there is no perf difference. But 64x128 is slightly slower than 32x128 on the attention workload in the vicuna decoder. So I didn't change the block size.   
@vinx13 @cyx-6 @sunggg @jwfromm
=> [Unity] Update CUTLASS Attention to incorprate upstream change

src/relax/transform/fuse_ops.cc, tests/python/relax/test_transform_fuse_ops_by_pattern.py
Consider this subgraph:
```
lv_ = R.matmul(x2, y2)
lv = R.matmul(x, y)
lv1 = R.add(lv, bias)
lv2 = R.add(lv1, lv_)
out = R.add(lv2, residual)
```
This subgraph matches to two different residual patterns `matmul -> add -> add` starting from each matmul and matching two out of three `add`s. Currently we end up generating the following partition, since the second `add` matches to both residual patterns and the two groups are merged incorrectly after the second matching.  
```
@R.function
def gv(x2_1: R.Tensor((32, 8), dtype="float16"), y2_1: R.Tensor((8, 8), dtype="float16"), x_1: R.Tensor((32, 8), dtype="float16"), y_1: R.Tensor((8, 8), dtype="float16"), bias_1: R.Tensor((8,), dtype="float16"), residual_1: R.Tensor((32, 8), dtype="float16")) -> R.Tensor((32, 8), dtype="float16"): …
```
=> [Unity] Fix FuseOpsByPattern when a subgraph can be matched by multiple residual patterns

include/tvm/relax/attrs/nn.h, include/tvm/topi/nn/rms_norm.h, python/tvm/relax/op/nn/nn.py, python/tvm/relax/transform/legalize_ops/nn.py, python/tvm/topi/nn/__init__.py, python/tvm/topi/nn/rms_norm.py, python/tvm/topi/testing/__init__.py, python/tvm/topi/testing/rms_norm_python.py, src/relax/op/nn/nn.cc, src/relax/op/nn/nn.h, src/topi/nn.cc, tests/python/relax/test_transform_legalize_ops_nn.py, tests/python/topi/python/test_topi_rms_norm.py
This PR introduces the operator root mean square, `rms_norm`, into TOPI and relax, and its legalize transform.
=> [Unity][OP] Add `rms_norm`

python/tvm/contrib/cutlass/attention_operation.py, python/tvm/contrib/cutlass/conv2d_operation.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/contrib/cutlass/layer_norm_operation.py, python/tvm/contrib/cutlass/rms_norm_operation.py, src/relax/transform/lift_transform_params.cc, src/relax/transform/rewrite_cuda_graph.cc, src/runtime/cuda/cuda_device_api.cc, src/runtime/relax_vm/cuda/cuda_graph_builtin.cc, tests/python/relax/test_codegen_cutlass.py, tests/python/relax/test_transform_rewrite_cuda_graph.py
* Allow capturing input buffers passed from a user if `num_input` attribute is set. The last `func->params.size() - num_inputs` inputs are assumed to be fixed and thus they can be captured into a cuda graph. Users need to be careful if they intend to pass different parameter tensors, for example in LoRa deployment.
* Cache the instantiated `exec` object rather than the captured graph, since we assume that the graph is fixed anyway. I found that calling `cudaGraphLaunch` on every launch is super expensive.
* Support CUDA graph for CUTLASS BYOC.
@vinx13
=> [Unity] CUDA Graph update 

jvm/native/osx-x86_64/pom.xml, jvm/pom.xml
This PR fixes the pom.xml for OSX, and also updated the Maven Javadoc plugin version number to the latest.
=> [JVM] Fix the Maven pom.xml for OS X arm64 tvm4j build

src/tir/transforms/lower_thread_allreduce.cc, tests/python/unittest/test_tir_transform_lower_thread_all_reduce.py
This PR fixes a bug in the LowerThreadAllreduce pass.
Prior to this PR, in multi-group settings, the thread mask is not correctly set: when the reduction extent is 32, the thread mask will always be 0. This bug was not spotted because even when the mask is 0, the CUDA program still gives correct result. But in any way, having the zero mask is dangerous and should be fixed.
=> [Fix][TIR] LowerThreadAllreduce with correct thread mask

python/setup.py
The `cutlass_fpA_intB_gemm` has another `cutlass` dependency which has some large files we didn't exclude in `setup.py`, and it makes our python package large.
This PR fixes the issue.
cc @masahi  @tqchen @junrushao
=> [Package] Remove cutlass media/docs inside cutlass_fpA_intB_gemm

python/tvm/dlight/gpu/decode_gemv.py, tests/python/dlight/test_gpu_decode_gemv.py
This PR fixes a bug of the previous decode-GeMV dlight scheduling.
Previously, when the inner dimension of the largest tensor is spatial, in the end the fused epilogue block was not bound to any thread axis, which is wrong and will generate wrong GPU code with wrong numerical results. That is because after doing reverse-compute-at of the epilogue block, there are at lease one remaining spatial axis, and such axis is supposed to be bound to threadIdx.
This PR fixes this issue, and add three test cases which can cover both the reduction-inner and spatial-inner cases with or without broadcasting.
=> [Unity][Dlight] Fix decode-GeMV rule when spatial-inner without broadcasting

python/tvm/tir/op.py, src/te/operation/cross_thread_reduction.cc, src/tir/transforms/lower_thread_allreduce.cc, tests/python/unittest/test_tir_transform_lower_thread_all_reduce.py
This PR enhances the implementation of the LowerThreadAllreduce pass.
Prior to this PR, for CUDA backend we will leverage warp-level primitives only when
* the reducing threads are a sub-warp (i.e., size 16, 8, 4, 2), or
* the number of reducing threads is less then 32, and equals the reduction extent.
Under the requirement above, for reductions that have large number of reducing threads (e.g., reducing over 128, 256 or larger number or threads), the generated code is inefficient.
This PR improves the LowerThreadAllreduce pass, so that we now generate more efficient CUDA code in such cases, when the number of reducing threads is a multiple of warp size, with the help of warp-level primitives.
Specifically, in such cases, we first reducing 32 elements within each warp, getting the results …
=> [TIR] ThreadAllreduce warp-level primitive support with multi-warp

python/tvm/contrib/cutlass/build.py, python/tvm/contrib/cutlass/gemm_operation.py, python/tvm/contrib/cutlass/gen_tensor_op.py, python/tvm/contrib/cutlass/layer_norm_operation.py, python/tvm/relax/backend/contrib/cutlass.py, src/runtime/contrib/cutlass/weight_preprocess.cc, tests/python/relax/test_codegen_cutlass.py
Update the FT kernel integration to incorporate the following changes:
https://github.com/tlc-pack/cutlass_fpA_intB_gemm/pull/3
https://github.com/tlc-pack/cutlass_fpA_intB_gemm/pull/4
It also contains other misc changes to better support dolly and gptj (dynamic-size layer norm, residual check condition for dynamic-shape residual etc).
@vinx13 @sunggg @yzh119
=> [Unity] fp16 A x int B GEMM update - support int8, more bias shape

include/tvm/runtime/device_api.h, python/tvm/_ffi/runtime_ctypes.py, python/tvm/target/target.py, src/runtime/cuda/cuda_device_api.cc, src/runtime/metal/metal_device_api.mm, src/runtime/opencl/opencl_device_api.cc, src/runtime/rocm/rocm_device_api.cc, src/runtime/vulkan/vulkan_device_api.cc
Followup of #15305 , this PR creates API to query device L2 cache size in bytes.
Currently, the API-supported devices includes CUDA, OpenCL, and ROCM.
Note that OpenCL's API does not return the accurate device L2 cache size.
I cannot find a Vulkan API that returns L2 texture cache size, but the `vkCmdPipelineBarrier` call will flush the L2 texture cache automatically(https://zeux.io/2020/02/27/writing-an-efficient-vulkan-renderer/), thus we return 0 by default.
=> [Runtime] Device API to query L2 cache size

python/tvm/dlight/gpu/decode_gemv.py, tests/python/dlight/test_gpu_decode_gemv.py
This PR fixes a bug of DecodeGeMV dlight rule when the innermost tensor dimension is spatial with `unroll_factor` (for example, the grouping used in group quantization).
Prior to this PR, a reduction loop that is bound to threadIdx was reordered to reside outside a split spatial loop, which prevents the TIR LowerCrossThreadReduction pass to successfully apply due to some safety-guard requirement.
This PR fixes this issue by not reordering the split spatial loop after the reduction loop, so that the pass can be applied. Note that we can do this as the order of thread-binding loops does not matter.
=> [Unity][Dlight] Fix DecodeGeMV rule for spatial-inner with grouping

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This PR fixes a corner bug in the softmax converter in the Keras frontend.
If the input dimension of softmax is 1, TVM will crash unexpectedly.
```
File "test.py", line 25, in <module>
mod, params = relay.frontend.from_keras(model, shape_dict)
File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/keras.py", line 1565, in from_keras
_convert_layer(keras_layer, etab)
File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/keras.py", line 1519, in _convert_layer
layout,
File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/keras.py", line 1394, in keras_op_to_relay
outs = _convert_map[op_name](inexpr, keras_layer, etab, data_layout)
File "/workplace/software/tvm/tvm/python/tvm/relay/frontend/keras.py", line 134, in …
```
=> [Bugfix][Frontend][Keras]Fix a corner case bug in softmax converter of keras frontend

include/tvm/runtime/profiling.h, python/tvm/runtime/module.py, src/runtime/crt/common/crt_runtime_api.c, src/runtime/graph_executor/debug/graph_executor_debug.cc, src/runtime/profiling.cc, src/runtime/rpc/rpc_module.cc, web/emcc/tvmjs_support.cc
This PR introduces an optional cache flush functionality to `time_evaluator`. It is implemented by allocating two large empty NDArrays on the device so that the L2 cache are flushed. This gives us more accurate evaluation on the performance of a runtime function.
=> [Runtime] Flush L2 cache in time eval

docs/arch/index.rst
In the original code, the created array is named `arr` while `a` is used afterward. This has been fixed in this PR.
=> [skipci] Fix typo in docs/arch/index.rst

src/relay/backend/aot_executor_codegen.cc
Prior to this commit, if device initialization is required, the AOT main function produced a `call_extern()` that included the device context as input.  This commit updates the AOT main function to provide the device context only if the function being called accepts a device context as input.
If an extra device context argument is included at the call site, the C codegen would produce a function signature that includes the device context for the caller's compilation unit, but a signature without the device context for the callee's compilation unit.  While this can compile and run in some cases, it is undefined behavior for the signature to vary between compilation units, and should be avoided.
This was initially discovered while debugging https://github.com/apache/tvm/pull/14985, in which …
=> [AOT] Avoid call_extern() with incorrect argument count

tests/python/relay/test_pass_merge_compiler_regions.py
The test test_pass_merge_compiler_regions.py reused the same attribute target.test_if_else that was used by another test and caused CI issues.
Adding a unique attribute for now which resolves the test failure.
=> [CI] Update test to include unique attribute

docker/install/ubuntu_install_python_package.sh
Cython 3.0.0 was recently released, but it is incompatible with the current .pxi definitions in python/tvm/_ffi/_python. Pinning the cython version until a working fix is created.
Posting this PR as an alternative to https://github.com/apache/tvm/pull/15346.
=> [CI] Pin cython version to fix cython compilation

python/tvm/dlight/gpu/matmul.py, tests/python/dlight/test_gpu_matmul.py
Fix the dlight matmul schedule for the following case:
```
matmul(input, self.weight, out_dtype="float32") + astype(self.bias, "float32")
```
The problem is the fp32 cast of bias. The current schedule doesn't recognize such "independent block" besides matmul, so this block hasn't been scheduled when dlight attempts to reverse-inline the "last block" (bias add) into the matmul cache-write stage via `auto_inline_consumers(sch, l2g)`. The bias add block ends up having two producers, which breaks `reverse_compute_inline` and hence leaving some blocks (the last block and the bias cast block) unscheduled for GPU.   
This has been fixed by checking if `reverse_compute_inline` has succeeded (no consumer remaining), and if not, look for unscheduled, "independent" producer blocks (like bias cast) …
=> [Unity][Dlight] Fix matmul schedule when out_dtype = fp32 and bias add is fp32

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This PR fixes two types of bugs:
Bug 1. fix a typo about the wrong API name in the test case.
Bug 2-5. add an assertion to reject the invalid model, which can be constructed in the old version of Keras. The attribute `units` in LSTM, RNN, GRU, and Dense must have a positive value. Such invalid values can be used to construct a DL model successfully and can be converted to RelayIR successfully. In this pr, we reject these invalid models containing such layers.
```
import tvm
from tensorflow.keras import layers, models
input_shape = (1, 2, 4)
input_data = np.random.random(size=input_shape)
dtype = 'float32'
x = layers.Input(shape=input_shape[1:], dtype=dtype)
layer = keras.layers.LSTM(units=0)        # invalid input …
```
=> [Bugfix][Relay][Frontend][Keras] Add a assertion to reject a invalid value for attribute units in RNN layers

python/tvm/relay/frontend/keras.py, tests/python/frontend/keras/test_forward.py
This pr adds a checking for the input_shape.  If the input_shape is invalid, we will reject it immediately!
=> [Bugfix][Frontend][Keras] Add a check to reject the invalid input shape

docker/install/ubuntu2004_install_python_package.sh
The PR #15183 adds ml_dtypes as a dependency of TVM, however, some of the CI docker images do not have ml_dtypes installed, the PR fixes the issue.
cc @yongwww , would you mind also helping upload the new images with ml_dtypes installed to docker hub?
=> [CI] Add ml_dypes dependency for all docker images

python/tvm/relay/frontend/pytorch.py, tests/python/frontend/pytorch/test_forward.py
support aten::view_as op for the frontend of pytorch.  The info of this op is available at this [link](https://pytorch.org/docs/stable/generated/torch.Tensor.view_as.html).
=> [Relay][Pytorch] Add aten::view_as 

python/tvm/contrib/hexagon/transform.py, tests/python/contrib/test_hexagon/test_relay_simplify_conv_pat.py
When one of the inputs to Mul and Sub are constant scalars, we have the following algebraic identity:
Let res[p,q,r,s] denote the result of Mul(a, c1)->Sub(c2)->Conv(W) pattern
res[p,q,r,s] = Conv(a*c1 - c2, W)
= SUM{i=[0,c-1], j=[0,kh-1], k=[0,kw-1]}
{(a[p,i,r+j,s+k] * c1 - c2) * W[q,i,j,k]}
= SUM{i=[0,c-1], j=[0,kh-1], k=[0,kw-1]}
{a[p,i,r+j,s+k] * c1 * W[q,i,j,k]} - c2 * W[q,i,j,k]}
= Conv(a, W*c1) + Conv(0-c2, W)
Since Conv(0-c2,W) and W*c1 are constant terms, they could be computed during compile time.
=> [Hexagon] Simplify Mul->Sub->Conv to Conv->Add when possible

python/tvm/relax/backend/contrib/cutlass.py, tests/python/relax/test_codegen_cutlass.py
The FT kernel requires the output pointer type to be fp16, so we haven't supported offloading `matmul` with `out_dtype="float32"`. But if such matmul is immediately followed by a cast to fp16, we can match and replace the whole `matmul -> cast` with the FT kernel. 
Such case arises if a user wants to do fp32 accum during matmul. It turns out the FT kernel always does fp32 accumulation internally regardless of the output dtype, so we are not losing any precision by offloading `matmul(..., out_dtype = "float32") -> cast` to the fp16 A - int B FT kernel.
@vinx13 @sunggg @yzh119
=> [Unity][CUTLASS] Support `out_dtype = "float32"` for FasterTransformer kernel

src/relax/distributed/transform/propagate_sharding.cc, src/relax/transform/remove_purity_checking.cc
This patch fixes a couple of build warnings `-Woverloaded-virtual` that come up due to the `VisitExpr_` definitions
=> [Unity] Avoid overloaded-virtual warnings

python/tvm/dlight/benchmark/__init__.py, python/tvm/dlight/benchmark/bench.py, python/tvm/dlight/benchmark/extract.py, python/tvm/dlight/benchmark/utils.py, python/tvm/meta_schedule/testing/tune_utils.py, tests/python/dlight/test_benchmark.py
This PR introduces benchmarking tools for dynamic shape PrimFuncs and Relax. It facilitates the following functionalities:
1. Automatically benchmark PrimFunc performance with user-speicified dynamic shape sampling function and input information. E.g., `n=random.randint(50, 100)` will benchmark performance of PrimFunc with Dynamic dimension `n` between 50-100.
2. Extract self-contained PrimFunc benchmarking files from Relax Module. E.g., it can produce multiple python files for each function in a Relax Module and automatically extract dynamic shape input information from bindings.
3. Conduct Relax Function level benchmarking using the same dynamic shape sample value across the Relax Function. E.g., the same value `n` is used consistently in a Relax Function for any PrimFunction call so we …
=> [Dlight] Benchmarking Tools for Dynamic Shape PrimFuncs & Relax Function

src/tir/transforms/lower_thread_allreduce.cc, tests/python/unittest/test_tir_transform_lower_thread_all_reduce.py
PR #15327 introduces the warp-level primitive support in multi-warp allreduce. However, due to the specialty of the two-stage shuffle-down reduction implementation of the allreduce in multi-warp scenarios, PR #15327 did not broadcast the allreduce result to each reduction thread. This behavior does not align with the semantics of allreduce and is not ideal for many use cases. Therefore, this PR completes the implementation by inserting a stage of writing the reduction results to shared memory, so that each reduction thread across all the reduction warps can access the reduction results.
This shared memory write-back stage will only be inserted in multi-warp allreduce cases. In single-warp allreduce, a `shfl_sync` is used to broadcast the reduction results across reduction threads. Since …
=> [TIR] Allreduce broadcast result to each thread in multi-warp case

src/tir/transforms/lower_cross_thread_reduction.cc, tests/python/unittest/test_tir_transform_lower_cross_thread_reduction.py
This PR fixes the predicate handling logic of the cross-thread reduction lowering pass.
For the cross-thread reduction write-back block, prior to this PR, its predicate is the conjunction of `t == 0` for each reduction thread dim of the cross-thread reduction. This is problematic when the write-back buffer is stored in local memory, where each thread is supposed to have a copy of the final value, while the final value is only stored by the first thread. In this PR, the predicate is changed to be the conjunction of the clauses from the two parts:
* the clause of the original reduction block's predicate which contains spatial loop var,
* `t == 0` for each reduction thread dim **only when the write-back buffer is global or shared**.
So the first part ensures that the write-back will not go …
=> [TIR] Finer predicate handling in cross-thread reduction

src/tir/transforms/compact_buffer_region.cc
This PR found a workaround that prevents the nigthly windows pypi package of TVM Unity to be released. Basically it splits out a deeply nested method into several smaller ones so that MSVC's internal handling is supposed to be slightly simpler and less error prone.
=> [Bugfix] Work around "Internal Compiler Error" in MSVC

src/relay/transforms/simplify_expr.cc, tests/python/relay/aot/test_crt_aot_usmp.py, tests/python/relay/test_pass_simplify_expr.py
This PR improves SimplifyClipAndConsecutiveCast pass in several aspects.
First, it allows that the dtype of `clip` and the dtype of the last `cast` differ.
Second, it allows that there are arbitrary number of `cast` after `clip`. This is achieved via the recursion of patterns.
Both of the above two cases araise from the compilation of a prequantized model.
See the [pre-RFC](https://discuss.tvm.apache.org/t/on-the-applications-of-the-composition-of-dataflow-patterns/15344?u=kfeng123)
=> [Relay] improve SimplifyClipAndConsecutiveCast pass

include/tvm/relay/dataflow_pattern.h, src/relay/ir/dataflow_pattern.cc
When recursion of dataflow patterns is used, the pattern graph may not be a DAG. If recursion is encountered, ReprPrint of dataflow pattern may fall in a dead loop.
This PR solves the bug of dataflow pattern printing, and is the first PR for the [pre-RFC](https://discuss.tvm.apache.org/t/on-the-applications-of-the-composition-of-dataflow-patterns/15344?u=kfeng123).
=> [Bugfix] [Relay] fix a bug of  printing dataflow pattern

python/tvm/driver/tvmc/compiler.py, tests/python/driver/tvmc/test_command_line.py
Added a new flag `--print-pass-times` for tvmc compile to provide debugging information for tvmc users using `PassTimingInstrument`.   
Also added a test to check the printing of timing results.  
Example output:  
```
Compilation time breakdown by pass:
sequential: 431498us [48us] (88.48%; 88.48%)
RemoveUnusedFunctions: 14us [14us] (0.00%; 0.00%)
ToBasicBlockNormalForm: 66us [66us] (0.01%; 0.02%)
qnn.Legalize: 2167us [24us] (0.44%; 0.50%)
InferType: 617us [617us] (0.13%; 28.48%)
```
=> [TVMC] Add tvmc flag to print compilation time per pass

python/tvm/script/parser/core/evaluator.py, tests/python/unittest/test_tvmscript_parser_tir.py
Small change in the evaluator to allow it to handle starred expressions (i.e. list/tuple splicing).
=> [TIR] Allow starred expressions in TIR script

python/tvm/relax/frontend/nn/__init__.py, python/tvm/relax/frontend/nn/_tensor_op.py, python/tvm/relax/frontend/nn/core.py
This PR introduces the core data structure for the new `nn.Module` API, including:
- Tensor, a wrapper on top of relax.Expr whose struct_info is a TensorStructInfo, providing more convenient access shape and dtype information. Tensor is always symbolc and not bound to any concrete values.
- Parameter, a special tensor which could be bound or not bound to concrete values.
- Module, a container of nn.Parameters and sub nn.Modules.
- Effect, a non-user-facing class that encloses potential side effects, for example, IO, impure external function callings, inplace mutation, etc.
=> [Unity][Module] Add Core Data Structure

python/tvm/dlight/gpu/reduction.py, tests/python/dlight/test_gpu_reduction.py
This PR fixes a correctness issue when the epilogue length is different with the `len_tx`.
cc @junrushao @MasterJH5574
=> [Unity][DLight] Fix Reduction Rule

src/target/source/intrin_rule_metal.cc, src/tir/transforms/lower_thread_allreduce.cc, tests/python/unittest/test_tir_transform_lower_thread_all_reduce.py
This PR introduces the warp-level shuffle primitives used in Metal Shading Language, and uses them in the implementation of allreduce lowering.
The introduced primitives are:
* `simd_shuffle`,
* `simd_shuffle_up`,
* `simd_shuffle_down`.
See section 6.9.2 of https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf for details.
The correctness are validated by `test_allreduce_cuda` with the backend changed to Metal. Given we do not have Metal CI tests, the correctness is checked only locally.
Given the Metal shuffle primitives do not support (or need) masking, the pass LowerThreadAllreduce is updated to support such backend which does not have masks. One unit test for metal is added to ensure that no mask is used.
=> [Codegen][Metal] Support metal warp-level primitive

src/tir/schedule/primitive/reduction.cc, tests/python/unittest/test_tir_schedule_rfactor.py
The rfactor primitive will create/rewrite two blocks, together with the block read/write regions. However, the generated read/write region extents are invalid when it's an int64 index. This commit fixes the issue.
cc @MasterJH5574
=> [TIR] Fix Primitive Rfactor DType

include/tvm/runtime/vm/memory_manager.h, src/runtime/vm/memory_manager.cc, src/runtime/vm/naive_allocator.h, src/runtime/vm/pooled_allocator.h, tests/cpp/runtime/vm/memory_manager_tests.cc
VM memory manager is extended to support allocation memory with different memory scope. This functionality is fully implemented for naive allocator. For pooled allocator is should be implemented in the future.
cc: @masahi, @Hzfengsy
=> [VM][OpenCL] Introduce textures allocation to VM memory manager

python/tvm/relax/frontend/nn/__init__.py, python/tvm/relax/frontend/nn/core.py, python/tvm/relax/frontend/nn/modules.py, python/tvm/relax/frontend/nn/spec.py
This PR introduces ModuleSpec and SpecBuilder, which are key classes to export an nn.Module to TVM's IRModule.
Example:
```python
model.export_tvm(
spec={
"prefill": {
"inputs": spec.Tensor([batch_size, "seq_len"], "int32"),
"total_seq_len": int,
},
"decode": {
"inputs": spec.Tensor([batch_size, 1], "int32"),
"total_seq_len": int,
},
"softmax_with_temperature": {
"logits": spec.Tensor([1, 1, vocab_size], "float32"),
"temperature": spec.Tensor([], "float32"),
},
},
)
```
=> [Unity] nn.Module Spec

src/tir/transforms/unsupported_dtype_legalize.cc, tests/python/unittest/test_tir_transform_bf16_legalize.py
In the previous bf16legalize pass, the `storage_scope` of the original BufferVar was not retained, but all changed to the default value (`global`). The purpose of this PR is to ensure that Var's scope is always correct
=> [TIR][BugFix]Ensure the Var's scope is correct

python/tvm/target/target.py, tests/python/contrib/test_hexagon/test_vtcm.py
This patch adds VTCM default capacity values for different target architectures so that it can be queried at compile time from targets
=> [Hexagon] Add default vtcm capacity for targets

python/tvm/relax/frontend/nn/_tensor_op.py, python/tvm/relax/frontend/nn/op.py, python/tvm/relax/frontend/nn/spec.py, tests/python/relax/test_frontend_nn_op.py, tests/python/relax/test_frontend_nn_tensor.py
This PR introduces _TensorOp class and a collection of useful Ops, helping users build their own models in a torch-like programming style. Each Op will invoke the `_wrap_nested` function to automatically emit relax Op with BlockBuilder.
Example:
```python
class Model(Module):
def test(self, x: Tensor, y: Tensor):
z0 = op.add(x, y)
z1 = x * y
return (z0, z1)
```
cc: @junrushao @cyx-6
=> [Unity] nn.Module Op

docker/install/ubuntu_install_jax.sh
The Flax dependency `Orbax v0.1.8` has enforced the deprecation of installing Orbax as a standalone package. Flax v0.6.8 (which is currently pinned in the script `docker/install/ubuntu_install_jax.sh`) attempts to install Orbax as a standalone package and raises an error about doing so.
Going forward, the package `orbax-checkpoint` should be installed instead. Flax v0.6.8 does not recognise this and attempts to install Orbax instead of orbax-checkpoint and the installation fails.
In order to resolve Jax installation issues, bumping the version of Flax to be at least 0.6.9, which resolves the problem. Flax >= 0.6.9 does not pin the version of orbax-checkpoint that it installs and the latest version requires Jax >= 0.4.9 to be installed so the two must be updated together.
Issue: …
=> [CI] Bump Flax and Jaxlib versions to fix Jaxlib install error
