apache/tvm

- python/tvm/meta_schedule/cost_model/cost_model.py
- python/tvm/meta_schedule/cost_model/xgb_model.py
- python/tvm/meta_schedule/tir_integration.py
- python/tvm/meta_schedule/tune.py
support to set specific xgboost tree method
> [XGBoost,MetaSchedule] Support xgb set tree method

- python/tvm/relay/frontend/keras.py
- tests/python/frontend/keras/test_forward.py
Add support for swish activation in Keras frontend
> [Frontend][Keras] Add support for swish actiivation

- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/spec.py
- python/tvm/relax/frontend/nn/torch.py
This PR introduces a `nn.Module.jit` method that effectively converts an `nn.Module` to a collection of torch-in-torch-out callables for users to debug with.
> [Unity] nn.Module Torch Integration

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul_tensorize.py
Prior this PR, the tensorization rule in dlight writes back the result of matrix multiplication from shared memory to global memory without proper parallelism.
This PR fixed this issue and updated related parameters, which significantly improved the performance of LLMs.
The profiling results of various sequence length are listed as follows.
Encoding total time (ms), q3f16_0
seq len | 2000 | 1000 | 500 | 100 | 10
-- | -- | -- | -- | -- | --
prior tensorization | 1704.6145 | 653.5553 | 343.8585 | 154.8938 | 147.4646
optimized | 833.4194 | 416.1180 | 242.5826 | 129.2025 | 127.8226
> [Unity][Dlight] Improve Dlight Tensorization Rule

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
This PR updates the GEMV rules:
1. improve for large workloads, speedup Vicuna 13B from 43.0 tok/s to 60.8 tok/s
2. Fix the issue of unexpected unroll for allreduce parts.
cc @spectrometerHBH @MasterJH5574
> [Unity][DLight] Update GEMV rules

- python/tvm/relax/frontend/onnx/onnx_frontend.py
This small PR improves how the onnx importer deals with ConstantOfShape. Previously we were creating constants that could be massive if the provided shape was large. This caused an explosion in the resulting model parameter size. Using `broadcast_to` instead provides behavior closer to the intention of the source graph.
I also noticed relax now has `relax.op.image.resize2d` so i replaced our topi call with it which should help produce more readable output graphs.
> [Unity][Frontends][Onnx] Improve ConstantOfShape behavior

- python/tvm/script/parser/_core.py
- python/tvm/script/parser/core/entry.py
- python/tvm/script/parser/core/parser.py
- python/tvm/script/parser/tir/entry.py
- python/tvm/script/parser/tir/parser.py
As a background info---the script parser works by visiting a "statement" (or top-level expression) at a time. The expression parts of the statement are evaluated, and then the IR corresponding to the statement is constructed if necessary.
In TIR, macro calls can only occur at the statement level, and they don't produce any values. This means that the statement visitor (`visit_expr_stmt`) can see these calls directly in its node parameter. At this point it could simply visit the body of the macro instead, which is the basis of the existing implementation.
In other dialects there may be a need for macros to produce values. This means that macro calls can occur in the middle of complex expressions. As a result, these calls will not be present at the statement level, and the TIR approach by …
> [TIR] Generalize implementation of T.macro to work with other dialects

- src/runtime/contrib/cublas/cublas.cc
- src/runtime/contrib/cublas/cublas_json_runtime.cc
- src/runtime/contrib/cublas/cublas_utils.h
- tests/python/relax/test_codegen_cublas.py
This PR enables cuda graph with cublas.
> [Unity] cuda graph support for cublas

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
[Mish](https://onnx.ai/onnx/operators/onnx__Mish.html)  - tests pass locally for `llvm` target on a `cpu`
> [Frontend][ONNX] add onnx Mish operator

- include/tvm/relay/attrs/vision.h
- python/tvm/relay/frontend/tflite.py
- python/tvm/relay/op/strategy/generic.py
- python/tvm/relay/op/vision/_vision.py
- python/tvm/relay/op/vision/multibox.py
- python/tvm/relay/op/vision/nms.py
- python/tvm/topi/cuda/ssd/multibox.py
- python/tvm/topi/vision/nms.py
- python/tvm/topi/vision/ssd/multibox.py
- src/relay/op/vision/multibox_op.cc
- src/relay/op/vision/nms.cc
- tests/python/frontend/tflite/test_forward.py
- tests/python/relay/test_op_level5.py
- tests/scripts/request_hook/request_hook.py
This PR adds support of regular NMS operator.
Open questions:
1. How to properly test added functionality? 
Other NMS implementations, e.g., fast NMS, use a TF frozen graph from TF official website to convert a model to TFLite and keep NMS operations only. In order to create a similar test, we need to find an archive on TF official website that contains a frozen graph of a model compiled with `--use-regular-nms=True` flag. We haven't found it yet, so any help is appreciated.
3. Regular NMS requires two sort operations:
- Sorting the scores after selecting scores above `nms_score_threshold`. This PR implements this with a simple bubble sort in order to prove the algorithm's semantics. We tried to replace it with `tvm.contrib.sort.argsort`. It works well when testing the regular NMS with …
> [FRONTEND][TFLITE] Add support for TFLite's regular NMS operator

- src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc
- src/meta_schedule/schedule_rule/schedule_rule.cc
This PR fixes #15426 by:
* Fix a bug in default mma rules;
* Return empty result rather than abort the whole tuning process.
> [MetaSchedule] Fix mma default rule and disable tuning abort

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
Sometimes the vector size can be too large and introduces predicates (this happen when reduction length >= 4096, where we use tx == 128). Choosing a smaller vector size can avoid predicates.
Benchmark on 4090 using CUDA target, seq_len = gen_len = 128, results in tok/s
Model | Before | This PR
-- | -- | --
vicuna 7b q0f16 | 62.02 | 62.64
vicuna 7b q4f16_1 | 162.90 | 163.22
cc @Hzfengsy @spectrometerHBH @masahi
> [Unity][Dlight] Avoid too large vectorization factor in caching

- web/.eslintrc.json
- web/package-lock.json
- web/package.json
- web/src/rpc_server.ts
- web/src/runtime.ts
- web/src/tvmjs_runtime_wasi.d.ts
- web/src/webgpu.ts
- web/tsconfig.json
This PR contains 3 aspects:
1. Surpass the eslint error on banned types. As `runtime.ts` contains `Function` as type extensively and is suitable for FFI
2. Fix errors hinted by the new linter and type cheker, mostly about type inference.
3. Fix the typescript configuration file:
> [Unity] Eslint and TypeScript configuration fix

- include/tvm/relax/attrs/index.h
- python/tvm/relax/op/index.py
- src/relax/op/tensor/index.cc
- src/relax/op/tensor/index.h
- tests/python/relax/test_op_index.py
This PR improves two things:
1. Support symbolic `begin` and `end` for slice op.
2. Add a new attribute `assume_inbound` for slice op. If `assume_inbound` is set to True, the slice op will assume the `begin` and `end` are always inbound, which will simplify the shape deduction.
> [Unity][Op] Support symbolic shape inference for slice op.

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
This very small PR adds a check to our gemm importer to prevent inserting useless multiplies with `alpha` or `beta` when their value is `1.0`. This can produce cleaner easier to optimize graphs.
> [Unity][Frontend][Onnx] Simplify gemm

- src/runtime/rocm/rocm_module.cc
- src/target/llvm/codegen_llvm.cc
- src/tir/transforms/lower_thread_allreduce.cc
rocm bug fix:Module hip should be either dso exportable or binary serializable
rocm bug fix: llvm.amdgcn.ds.bpermute Intrinsic has incorrect return type
rocm bug fix:ptr addrspace(3) @shmem Global is external, but doesn't have external or weak linkage
Co-authored-by: zhangxiao-stack <1244360827@qq.com>
> [ROCm] Fix some ROCm codegen bugs

- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/script/parser/core/parser.py
- python/tvm/script/parser/tir/parser.py
- tests/python/unittest/test_tvmscript_error_report.py
- tests/python/unittest/test_tvmscript_parser_tir.py
An extension of https://github.com/apache/tvm/pull/15404, which allowed starred expressions in the rhs of assignments (e.g. `T.decl_buffer(shape=[*dim, 128])`), this PR also enables starred expressions in the lhs of assignments (e.g. `for *spatial,reduction in T.grid(*A.shape)`).
> [TVMScript] Support starred indices in for-loop

- src/relay/transforms/to_mixed_precision.cc
- tests/python/relay/test_to_mixed_precision.py
In some layers, e.g. `Clip`, we might have a compilation error in the case when operation takes on the input a constant which is out of target data type range.
To prevent such situation, a new method was introduced. It compares values of constant attributes with the range of the target data type. In case if the value is out of range, then float32 will be used.
cc: @AndrewZhaoLuo, @elvin-n
> [Relay] Stop ToMixedPrecision when constant is out of dtype range

- src/target/llvm/intrin_rule_rocm.cc
> [ROCm] fma intrin

- python/tvm/_ffi/libinfo.py
- python/tvm/contrib/cutlass/build.py
This PR fixes the path finding for `3rdparty/cutlass` by trying out different combinations. It is helpful when TVM is packaged differently.
> [Bugfix][CUTLASS] CUTLASS path finding

- python/tvm/_ffi/_cython/ndarray.pxi
This PR makes the cython code compatible with 3.0 also in a way that is backward compatible with older cython versions
> [CYTHON] Make cython compatible with 3.0

- src/tir/transforms/thread_storage_sync.cc
- tests/python/unittest/test_tir_transform_thread_sync.py
Cherry-picked from #15478.
This PR fixes an issue of the ThreadSync pass.
Prior to this PR, the pass is not aware of `shared.dyn` scope whose users all share a same shared memory space. This feature is not necessarily already revealed in the IR at the time of applying ThreadSync. This means that when applying ThreadSync, in the IR, each buffer of `shared.dyn` scope still uses its own data Var, and ThreadSync is thus unable to detect the conflict properly and insert the sync instructions properly.
This PR explicitly makes ThreadSync be aware of the `shared.dyn` scope, and redirect all the access vars of `shared.dyn` memory to a common var, so that ThreadSync analysis can find out the conflict and insert the sync instructions.
> [Cherry-Pick][BugFix][TIR] ThreadSync with shared.dyn awareness

- python/tvm/relax/op/mask.py
using python api of full_like instead of _ffi_api.full_like to solve the issue of missing dtype argument.
See also [mlc-ai/relax/pull/279](https://github.com/mlc-ai/relax/pull/279)
> [Unity][BugFix][Op] fix error when calling full_like in masked_fill

- src/tir/schedule/primitive/reduction.cc
- tests/python/unittest/test_tir_schedule_reduction.py
> [TIR, Schedule] Fix decompose reduction with thread binding loops

- python/tvm/relay/op/strategy/arm_cpu.py
- tests/python/relay/strategy/test_select_implementation.py
https://github.com/apache/tvm/pull/12455 slightly altered the behaviour when selecting an int8 conv2d schedule. Previously conditions that decide which schedule to select used `is_aarch64` which checks for the existance of `aarch64` in the target triple. However, the conditions now use `has_asimd` which is true if `aarch64` exists in the target triple OR `+neon` is used in the mattr.
Both `conv2d_NHWC_quantized_interleaved.arm_cpu` and `depthwise_conv2d_nhwc.arm_cpu` makes calls to LLVM intrinsics that require both `aarch64` and `+neon`. But in the case of the target `rasp4b`, the updated conditions result in compilation failure since the target has `+neon` but doesn't have `aarch64` in the target triple. The conditions have been updated to fix the compilation failure.
Likewise, the …
> [Relay][Strategy] Fix `arm_cpu` int8 conv2d schedule selection for 32-bit targets

- src/tir/transforms/arg_binder.cc
- src/tir/transforms/make_packed_api.cc
For the `buf_shape` and `buf_strides` buffers, used while unpacking, generate a `DeclBuffer`.  For each buffer that was in the `buffer_map`, generate a `DeclBuffer`.                               
This is a subset of the changes made in https://github.com/apache/tvm/pull/14778, broken out for ease of testing and review.
> [TIR] Output DeclBuffer in MakePackedAPI

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
This PR fixes the issue of the GEMV rule uses too much shared memory on llama-70B model.
May have perf regression w/o https://github.com/apache/tvm/pull/15471. (Actually not sure)
cc @cyx-6
> [Unity][DLight] Use less shared memory for gemv

- src/relay/ir/dataflow_matcher.cc
- tests/python/relay/test_dataflow_pattern.py
This PR solves Issue 1 and Issue 2 of dominator pattern as described in the [pre-RFC](https://discuss.tvm.apache.org/t/on-the-applications-of-the-composition-of-dataflow-patterns/15344)
> [Relay] [Bugfix] Fix some bugs of dominator pattern

- include/tvm/relay/dataflow_pattern.h
- python/tvm/relay/dataflow_pattern/__init__.py
- src/relay/ir/dataflow_matcher.cc
- src/relay/ir/dataflow_pattern.cc
- src/relay/ir/dataflow_pattern_functor.cc
- src/relay/ir/indexed_graph.cc
- tests/python/relay/test_dataflow_pattern.py
This PR adds the redirecting operation for dataflow pattern, which can redirect a WildcardPattern to any other DFPattern. With the redirecting operation, one can construct recursive dataflow pattern. Some test cases are added.
This PR is part of the [pre-RFC](https://discuss.tvm.apache.org/t/on-the-applications-of-the-composition-of-dataflow-patterns/15344?u=kfeng123)
> [Relay] add redirecting operation to dataflow pattern graph

- python/tvm/script/parser/core/doc.py
- tests/python/unittest/test_tvmscript_parser_tir.py
The ast.ExtSlice expects a non-empty list, otherwise evaluation fails with `error: empty dims on ExtSlice`. Also, each element in "dims" list of ExtSlice must be either Slice or Index.
In python3.8 an expression `A[()]` is parsed (by ast) as Subscript with slice being `Index(value=Tuple(elts=[]))`. When we translate a subscript from doc.AST to ast, we unconditionally convert every tuple to ast.ExtSlice, which in this case is incorrect.
The fix is to map empty tuple back to the `Index(Tuple[]))` instead of ExtSlice. In other cases, ensure that members of ExtSlice are of correct types.
> [Script] Be more careful when generating ast.ExtSlice for Subscript

- python/tvm/script/parser/core/evaluator.py
- tests/python/unittest/test_tvmscript_error_report.py
- tests/python/unittest/test_tvmscript_parser_tir.py
The builtins are already supported by `eval` (they are automatically injected in the global scope), but they are not recognized by the evaluator's checks. When the evaluator sees doc.Name, it looks it up in the current `var_table`, and flags an error if it's not there.
Make the evaluator also consult the current builtins before erroring out.
> [TVMScript] Allow use of Python builtins in script

- python/tvm/topi/arm_cpu/conv2d_gemm.py
- tests/python/topi/python/test_topi_conv2d_int8.py
`topi.arm_cpu.schedule_conv2d_NHWC_quantized_interleaved` was failing compilation with the `+i8mm` extension enabled (as done in apache/tvm#14888) whenever the output height and output width were both equal to 1, such that OH x OW = 1.
Padding was being removed during the `tir.BufferShapeLegalize` pass, causing an error in the `tir.BufferBindUnwrapper` pass. Some of the removed padding was necessary for tensorize (using the `gemm_acc_2x2_int8_int8_int32` intrinsic), which expects 2x2 output tiles. However, because of the optimisations mentioned above, the output tensor `C_interleaved` was reduced to having 1x2 tiles instead.
e.g. for A = [1x1x1x8], W = [1x1x8x24], C = [1x1x1x24]:
- Before fix: `C_interleaved = T.Buffer((1, 1, 2, 1, 6, 1, 2), "int32”)`
- After fix: `C_interleaved = …
> [Bugfix][TOPI] Fix a bug in arm_cpu int8 conv2d i8mm schedule

- docker/install/ubuntu_install_python_package.sh
After https://github.com/apache/tvm/pull/15469, we should now be able to remove the cython version pin.
> [CI] Remove cython version pin

- python/tvm/relay/op/strategy/arm_cpu.py
- tests/python/relay/strategy/test_select_implementation.py
Currently the fallback used when compiling a dense operation with targets such as `llvm -device=arm_cpu` is `dense.generic`. This results in very poor performance. Although https://github.com/apache/tvm/pull/13775 meant that x86 schedules are used in cases where no strategy is provided by arm_cpu, the dense strategy is registered due to the existence of specialized schedules for arm_cpu e.g. a schedule for embedded devices. This commit ensures x86 schedules are used inplace of a generic schedule which yields much better performance.
The commit also follows the same approach for the `dense.generic` schedule as the x86 strategy. This will only be used when auto-scheduler is enabled.
A test has been added to check the intended schedules are picked when compiling with `arm_cpu`.
cc @ekalda …
> [Relay][Strategy] Use x86 dense schedules for arm_cpu

- src/relax/ir/dataflow_matcher.cc
- tests/python/relax/test_dataflow_pattern.py
Prior to this commit, the commutative pattern matching was enabled based on the operation in the pattern.  As a result, commutative matches would only be checked if the match checked for a single operator, but not if the operator was itself a pattern that resolved to a commutative operator.
```python
pattern_add = ExprPattern(Op.get("relax.add"))
pattern_mul = ExprPattern(Op.get("relax.multiply"))
uses_commutative_matching = pattern_add(lhs, rhs)
no_commutative_matching = OrPattern(pattern_add, pattern_mul)(lhs, rhs)
```
This commit updates the pattern matcher to check against the matched operator, rather than the pattern, to determine whether to check for commutative matches.
> [Unity] Commutative pattern match based on relax.Expr op

- CMakeLists.txt
- cmake/modules/contrib/CUTLASS.cmake
- python/tvm/contrib/cutlass/attention_operation.py
- python/tvm/contrib/cutlass/build.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
- tests/python/relax/test_codegen_cutlass.py
This PR enables using the flash v2 kernel for offloading the attention op. Flash v2 is implemented in CUTLASS, so it is reasonable to integrate it into our CUTLASS BYOC.  
The flash v2 kernel is used whenever applicable, because it is expected to be faster than the xformer kernel. The xformer repo itself is now [admitting that flash is always faster](https://github.com/facebookresearch/xformers/blob/main/xformers/ops/fmha/dispatch.py#L15-L16). 
For now, flash is disabled for causal attention case, since I haven't validated its correctness thoroughly. 
UPDATE: It seems for a single-token decoding in LLM, the flash v2 kernel with `is_causal = False` is much slower than the xformer kernel. So for LLM inference, it is recommended to always use the causal mask which will disable the flash attn …
> [Unity][BYOC] Integrate Flash attention v2 kernel into CUTLASS BYOC

- python/tvm/dlight/gpu/matmul.py
Prior to this PR, TensorCore tensorization is not enabled for SM70 while SM70 devices have TensorCore support. This PR enables the tensorization.
> [Unity][Dlight] Matmul tensorization for SM70

- include/tvm/relax/utils.h
- src/relax/transform/fuse_ops.cc
- src/relax/transform/merge_composite_functions.cc
- src/relax/transform/to_non_dataflow.cc
- src/relax/transform/utils.h
- tests/python/relax/test_codegen_cutlass.py
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
- tests/python/relax/test_transform_merge_composite_functions.py
Currently, we have two paths for BYOC.
Path1: `seq = [FuseOpsByPattern(patterns, annotate_codegen=False), MergeCompositeFunctions(), RunCodegen()]`
Path2: `seq = [FuseOpsByPattern(patterns, annotate_codegen=True), RunCodegen()]`
Path1 is used for inference engines such as TensorRT, DNNL, CoreML, etc. which are more efficient with larger subgraph and thus better off merge adjacent composite functions. In constrast, Path1 is used for kernel libraries, such as Cutlass, Cublas, and not need to merge. 
For better UX, this PR aims to make both paths have same interface with various BYOC codegens. 
In addition, it removes unnecessary `kPrimitive` attribute in the function that will be offloaded to external codegen.
One remaining caveat is that two paths would have different function names of …
> [Unity][BYOC] Unify the interface between `FuseOpsByPattern(.., annotate_codegen=True)`and `MergeCompositeFunctions()`

- python/tvm/dlight/gpu/gemv.py
- python/tvm/dlight/gpu/utils.py
- tests/python/dlight/test_gpu_gemv.py
Update tunable template for (dequantize-)gemv
We can use `--eval --eval-prompt-len=1 --eval-gen-len=512` to measure
|    LLama 7B q4f16_1         | before (tok/s) | after (tok/s) |
|:-----------:|:-----------:|:-----------:|
| NVIDIA 4090 |    182.9->165.8         |      181.8->164.3       |
| NVIDIA 3090Ti |             |             |
| NVIDIA 3080 |             |             |
| NVIDIA 2070 |    80.1->66.8         |  89.4->72.7         |
| AMD 7900 xtx (ROCm)| 133.0->117.7 |155.3->134.3|
| M2 Max| | |
|    M1 pro   |             |             |
|  Adreno 740 |   1.9     |     7.0        |
| SteamDeck (AMD APU) | |
|    LLama 13B q4f16_1         | before (tok/s) | after (tok/s) |
|:-----------:|:-----------:|:-----------:|
| NVIDIA 4090 |     broken        |        103.3->94.4     |
| …
> [Unity][DLight] Update gemv rule

- python/tvm/relay/op/strategy/arm_cpu.py
- tests/python/relay/strategy/test_select_implementation.py
Similar to https://github.com/apache/tvm/pull/15470, x86 schedules are used in place of generic schedules to improve performance.
Since the pooling strategy does not use `OpStrategy`, mocking is used to ensure the relevant `schedule_pool` function is called when lowing a Relay pooling operation with respect to a given target.
cc @ekalda @ashutosh-arm @neildhickey
> [Relay][Strategy] Use x86 pool schedules for arm_cpu

- python/tvm/relay/op/contrib/cmsisnn.py
- src/relay/backend/contrib/cmsisnn/compute_luts.cc
- src/relay/backend/contrib/cmsisnn/compute_luts.h
- src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
- src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc
- tests/python/contrib/test_cmsisnn/test_softmax.py
* Support for int16 Softmax in CMSIS-NN
* Supporting integration test
> [CMSIS-NN] Support for Softmax Int16 operator

- python/tvm/contrib/cutlass/attention_operation.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
I had a typo in my flash v2 integration PR https://github.com/apache/tvm/pull/15467 that results in all flash v2 offload done with `is_causal = True`. The CI didn't catch it since we are still not running cutlass BYOC tests on CI.
Also add cuda graph support that was missing in the original PR.
> [Unity][Hot fix] Flash attention offload bug due to typo

- include/tvm/topi/x86/injective.h
Just add a missing check, for following simple case:
```
#[version = "0.0.5"]
def @main(%v: float32 /* ty=float32 */) -> float32 {
%0 = fn (%X: float32 /* ty=float32 */, Primitive=1) -> float32 {
add(%X, 1f /* ty=float32 */) /* ty=float32 */
} /* ty=fn (float32) -> float32 */;
%0(%v) /* ty=float32 */
}
```
> [TOPI] check empty array of x86 injective's iters

- src/relax/ir/expr_functor.cc
- tests/python/relax/test_dataflow_pattern.py
- tests/python/relax/test_expr_functor.py
- tests/python/relax/test_transform_combine_parallel_matmul.py
- tests/python/relax/test_transform_convert_layout.py
- tests/python/relax/test_transform_dead_code_elimination.py
- tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py
- tests/python/relax/test_transform_legalize_ops_manipulate.py
- tests/python/relax/test_transform_legalize_ops_nn.py
- tests/python/relax/test_transform_legalize_ops_search_statistical.py
- tests/python/relax/test_transform_rewrite_cuda_graph.py
- tests/python/relax/test_transform_to_mixed_precision.py
Prior to this commit, the `relax::ExprMutator` forwards the original `ret_struct_info` when visiting a `relax::Function`.  While this allows the resulting function to have a more specific return type if the mutation no longer allows the shapes to be propagated across the entire body (e.g. preserving `R.Tensor(shape=[16,16])` even if shape propagation resulted in `R.Tensor(ndim=2)`), this also preserves information that is no longer correct due to the mutation.
For example, a mutator that implements `VisitVarDef_` to replace the shape of a function parameter would expect that updated shape to propagate through to the function return type.  By retaining the original return type, the mutator produces an incorrect return type.
This commit updates `relax::ExprMutator` to only forward the …
> [Unity] Update relax.Function.ret_struct_info when mutated

- python/tvm/contrib/cutlass/build.py
- python/tvm/contrib/cutlass/gemm_operation.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
- tests/python/relax/test_codegen_cutlass.py
Similarly to https://github.com/apache/tvm/pull/15499, although the FT kernel does not support batched matmul, we can support batched A by flattening all batch axes into the M axis. 
@vinx13 @yzh119 @Hzfengsy @sunggg
> [Unity] Add batched A matrix support for FasterTransformer fp16A intB matmul

- src/relax/ir/binding_rewrite.cc
- tests/python/relax/test_analysis.py
Prior to this commit, the `relax.analysis.remove_all_unused` utility only removed variable bindings that occur within a dataflow block. This satisfies that the condition that a variable can be removed if is unused and if its computation has no side effects.  However, it doesn't include any values from a `BindingBlock`.
This commit updates the `RemoveUnusedVars` pass to also inspect `BindingBlock` instances for removeable variables.  Currently, this is limited to unused local function definitions.
> [Unity] Remove unused local function definitions

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
This PR improves ONNX importer to support symbolic shape importing. With this PR, we can import BERT with symbolic shapes into Relax.
cc @jwfromm
> [Unity][ONNX] Support ONNX Symbolic Shape Deduction

- include/tvm/topi/transform.h
- tests/python/relax/test_op_index.py
A follow-up to PR #15450, which allowed dynamic begin/end expressions in `relax.op.strided_slice`.  If the shape of the output is static, such as a slice from `index:index+slice_size`, the relax operator will delegate to `topi.strided_slice`, but that may then delegate to `topi.dynamic_strided_slice` due to the dynamic begin/end.  In this case, the topi implementation inserts an additional output variable `"dim"`, without providing a definition.
This behavior works in topi, as the output shape variable may have a definition provided from the calling scope, when the output tensor is passed in.  However, even in topi, this behavior is fragile as it assumes that the Tensor output is the same as the resulting PrimFunc output.
This commit updates the topi implementation of `strided_slice` to …
> [Unity] Propagate dynamic begin/end in strided_slice when legalizing

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
Split off from #15474: This is a simple bugfix that corrects a segfault in the `CanonicalizeBindings` pass. Namely, it did not handle the case of a non-dataflow var being bound to a dataflow var (which is permitted) and gave a segfault if it was encountered.
> [Unity][Bugfix] Handle assignment of non-dataflow var to a dataflow var in CanonicalizeBindings

- gallery/how_to/work_with_microtvm/micro_mlperftiny.py
- include/tvm/relay/transform.h
- include/tvm/tir/analysis.h
- include/tvm/tir/schedule/schedule.h
- python/tvm/relay/op/contrib/dnnl.py
- python/tvm/tir/schedule/schedule.py
- python/tvm/topi/hexagon/compute_poolarea.py
- python/tvm/topi/hexagon/slice_ops/max_pool2d.py
- src/runtime/hexagon/ops/conv2d_fp16_hvx.cc
- src/tir/schedule/primitive.h
- src/tir/transforms/inject_virtual_thread.cc
- tests/python/contrib/test_clml/infrastructure.py
- tests/python/contrib/test_ethosn/test_codegen.py
I'm thrilled to submit my first contribution to Apache! I've addressed the issue of duplicate words in the code. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Remove duplicate the word

- tests/python/relay/aot/test_c_device_api.py
- tests/python/relay/aot/test_crt_forward_declarations.py
- tests/scripts/task_python_integration.sh
- tests/scripts/task_python_microtvm.sh
The tests in `tests/python/relay/aot` were run as part of `task_python_integration.sh` which is run for `ci-cpu` and `ci-arm`, but some of tests in that folder require CMSIS-NN or FVP, so in practice they were not running anywhere in the upstream CI.
Since all the tests in that folder could run on `ci-cortexm`, change the scripts to run them there.
Also fix some tests that started failing as a result of #15103 (but didn't manifest in upstream CI) and `test_device_api_hooks_unpacked_api` that clearly hasn't been running in any CI for a while.
> [TEST] Run tests/python/relay/aot tests in ci-cortexm

- python/tvm/dlight/gpu/gemv.py
this PR updates the GEMV rule for Mali GPUs, improving the performance: 
Llama-7B: 2.2 toks/s -> 2.8 toks/s
RedPajama-3B: 4.5 toks/s -> 5.0 toks/s
> [Unity][DLight] Update GEMV Rule for Mali GPUs

- src/tir/transforms/inject_virtual_thread.cc
I'm thrilled to submit my second contribution to Apache! I've addressed the issue of typo mistake in the code. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Fix typo mistake and change whethe to whether

- include/tvm/relay/transform.h
- include/tvm/target/target.h
- include/tvm/target/target_kind.h
- include/tvm/tir/usmp/utils.h
- src/driver/driver_api.cc
- src/relay/backend/contrib/cmsisnn/target.cc
- src/relay/backend/contrib/codegen_c/target.cc
- src/relay/backend/contrib/cutlass/target.cc
- src/relay/backend/contrib/ethosu/codegen.cc
- src/relay/backend/contrib/example_target_hooks/target.cc
- src/relay/backend/contrib/tensorrt/target.cc
- src/relay/backend/contrib/uma/targets.cc
- src/target/codegen.cc
- src/target/target.cc
- tests/cpp/target_test.cc
There is a dependency of IRModule in the current Target implementation: `target.h -> module.h`. This pull request aims to decouple the dependency."
> Remove IRModule Dependency from Target

- python/tvm/meta_schedule/runner/local_runner.py
Hi folks, 
Small enhancement for catching error messages from local runners.
---
As needed by #15522, it ease to spot, pin & debug things:
* Rise the logging level:
```
import logging
logging.basicConfig(level=logging.DEBUG)
{...}
```
* Captured message from runners:
```
2023-08-11 14:05:48 [INFO] [task_scheduler.cc:193] Sending 8 sample(s) to builder
2023-08-11 14:05:51 [INFO] [task_scheduler.cc:195] Sending 8 sample(s) to runner
/usr/bin/python3: symbol lookup error: /tmp/tmpqc99dte5/tvm_tmp_mod.tar.so: undefined symbol: VEC_MACC
/usr/bin/python3: symbol lookup error: /tmp/tmpqc99dte5/tvm_tmp_mod.tar.so: undefined symbol: VEC_MACC
{...}
```
Thanks,
~Cristian.
> [MetaSchedule] Enable subprocess to stdout for DEBUG level

- src/relax/transform/merge_composite_functions.cc
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
- tests/python/relax/test_transform_merge_composite_functions.py
This PR is followup of PR https://github.com/apache/tvm/pull/15491.
By appending the codegen name at the end of function name, this PR make `MergeCompositeFunctions` explicitly show which functions are offloaded to each codegen. This will be particularly helpful when reading profiling results. 
e.g., before: `fused_relax_multiply1` -> after: `fused_relax_multiply1_cutlass`
cc. @masahi
> [Unity][BYOC] Make `MergeCompositeFunctions` append codegen name at the end of function name

- web/src/runtime.ts
- web/src/support.ts
I'm thrilled to submit my third contribution to Apache! I've addressed the issue of duplicate word inside function comment in the code. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Remove duplicate msg word and condition inside the function doc

- src/runtime/metal/metal_device_api.mm
A minor fix to suppress verbose logging in Metal device API.
cc @tqchen
> [Runtime][Minor] Suppress verbose logging in Metal device API

- src/relay/transforms/to_mixed_precision.cc
- tests/python/relay/test_to_mixed_precision.py
If topology contains while loop and we want to transform it to mixed precision then we get an exception that "ADT are not supported for mixed precision pass". It happens, because while loop implemented as a lambda which is assigned to a VarNode.
In this commit I changed the behavior of ToMixedPrecision pass and instead of generating exception, it just do nothing.
Correspondent regression test is added.
cc: @AndrewZhaoLuo
> [Relay] Disable exception for ADT in mixed precision pass

- src/relay/qnn/op/convolution.cc
- tests/python/frontend/tflite/test_forward.py
Bug observed in TFLite frontend when working with quantized conv2d operator with parameter groups != 1
> [Relay][TFLite] Fix in qnn.conv2d when parameter groups not equal to 1

- python/tvm/contrib/cc.py
Fix the typo in function _linux_compile at the file apache/tvm/blob/main/python/tvm/contrib/cc.py. Change from `--shared` to `-shared`
> [Fix] Fix the typo in compile flag

- python/tvm/auto_scheduler/search_task.py
This PR fixed a search task comment.
> Fixed search task comment

- python/tvm/relay/quantize/_annotate.py
- tests/python/relay/test_pass_auto_quantize.py
The type of add op`s output is activation, it should annotate by QAnnotateKind.ACTIVATION. If not, the graph will cast int32 into int8 directly without quantized, when quantize resnet. It will product overflow error, and it won`t prompt when infer the model. The resnet18_v1 test case is below.
before fixed
%703 = add(%701, %702) /* ty=Tensor[(1, 512, 7, 7), int32] */;
%704 = nn.relu(%703) /* ty=Tensor[(1, 512, 7, 7), int32] */;
%705 = cast(%704, dtype="int8") /* ty=Tensor[(1, 512, 7, 7), int8] */;
%706 = annotation.stop_fusion(%705) /* ty=Tensor[(1, 512, 7, 7), int8] */;
after fixed
%443 = add(%441, %442) /* ty=Tensor[(1, 512, 7, 7), int32] */;
%444 = nn.relu(%443) /* ty=Tensor[(1, 512, 7, 7), int32] */;
%445 = cast(%444, dtype="int64") /* ty=Tensor[(1, 512, 7, 7), int64] */;
%446 = …
> [quantize] fix bug of annotate for output of add op

- python/tvm/relay/frontend/pytorch.py
This fixes a typo in the Pytorch frontend.
> fixed typo [TypoFix]

- include/tvm/relax/struct_info.h
- python/tvm/relax/struct_info.py
- src/ir/global_info.cc
- src/relax/analysis/struct_info_analysis.cc
- src/relax/ir/expr.cc
- src/relax/ir/struct_info_functor.cc
- src/relax/transform/convert_layout.cc
- src/relax/transform/to_mixed_precision.cc
- src/script/ir_builder/ir/ir.cc
- src/script/printer/relax/struct_info.cc
PR https://github.com/apache/tvm/pull/15447 introduces `vDevice` and currently, it causes compilation failure on my Mac with the following error:
```
sung@spark-mbp build % gcc --version                                          
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```
/Users/sung/tvm/src/ir/global_info.cc:33:25: error: addition of default argument on redeclaration makes this constructor a default constructor
VDevice::VDevice(Target tgt = {}, int dev_id = -1, MemoryScope mem_scope = {}) {
^   ~~~~
/Users/sung/tvm/include/tvm/ir/global_info.h:97:20: note: previous declaration is here
TVM_DLL explicit VDevice(Target tgt, …
```
> [Unity] Fix the ambiguity issue in `vDevice` constructor on Mac with Apple clang version 14.0.3

- src/relax/transform/fuse_ops.cc
- tests/python/relax/test_transform_fuse_ops.py
* The var of MatchCastNode can be used as the value of subsequent VarBinding
* CollectFuncBindings will traverse the binding(VarBindingNode, MatchCastNode) of DataflowBlockNode to find its group in the OperatorFusor stage
> [Unity][Relax][FuseOps] Add MatchCastNode to node_map of IndexedForwardGraph

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- src/relax/op/tensor/manipulate.cc
- tests/python/relax/test_op_manipulate.py
While working on SDXL, I found that #15498 introduced a few issues. This PR adds better `PrimValue` handling through the onnx frontend to enable complicated shape computations. I also addressed an issue in `relax.op.reshape` that prevented special values like -1 from being passed via shape expression.
> [Unity][ONNX] Improved symbolic handling and reshape functionality

- src/relax/op/tensor/manipulate.cc
- tests/python/relax/test_op_manipulate.py
Prior to this commit, the `relax.concat` operator determined the concatenated dimension by adding together the dimension across all concatenated values.  For shapes involving symbolic variables, this can produce less readable shapes in some cases.  For example, concatenating together four arrays, each of shape `[128 // factor]` would produce an output of `[128 // factor + 128 // factor + 128 // factor + 128 // factor]`.
This commit updates the shape inference of `relax.concat` to check for the common case of equal-sized tensors being concatenated.  In the example above, the shape would instead be inferred as `[(128 // factor) * 4]`.
> [Unity] Infer concatenated shape with multiplication where possible

- src/script/printer/relax/expr.cc
Previously, values of these types would be included in the metadata of a printed module.  This commit allows them to be printed inline (e.g. `R.const(-1.0, "float16")`), analogous to the printing of float32/float64/int32/int64.
> [Unity][TVMScript] In-line literals for int8, int16, and float16

- src/script/printer/utils.h
- src/support/str_escape.h
Prior to this commit, all metadata was output as a single-quoted python string with escaped newlines.  This single line could become extremely long, which can cause some text editors to run slowly (e.g. emacs).
This commit updates the TVMScript printer to instead output the metadata using a triple-quoted python string with embedded newlines. Because the metadata is a pretty-printed JSON string, it contains frequent newlines that prevent the line length from causing editor lag.
> [TVMScript] Use triple-quoted python strings for metadata

- src/arith/iter_affine_map.cc
- tests/python/unittest/test_arith_iter_affine_map.py
When the lower bound predicate is present, `TryFuseIters` will rewrite an expression to `IterMarkWithOffset`, where the iter mark (structured form) has minimum value of zero. During rewriting, when the subexpression matches a previous rewritten result (`IterMarkWithOffset`), previously it doesn't correctly add the offset to the result `IterMarkWithOffset`, and causes inconsistency between the flattened form and the structured (normal) form.
cc @wrongtest-intellif @spectrometerHBH
> [Arith] Fix handling of overlapping predicates

- include/tvm/relax/transform.h
- python/tvm/relax/expr.py
- python/tvm/relax/transform/transform.py
- src/relax/analysis/struct_info_analysis.cc
- src/relax/ir/bind_symbolic_vars.cc
- src/relax/transform/bind_symbolic_vars.cc
- src/relax/utils.cc
- tests/python/relax/test_bind_symbolic_vars.py
- tests/python/relax/test_transform_bind_symbolic_vars.py
If a function has dynamic shape parameters, it can be useful to replace them with static parameters (e.g. when producing several models within the same family).  This commit introduces a utility function `relax.Function.bind_symbolic_vars`, which allows symbolic variables to be replaced with static values.
This is a related to the parameter binding done in `relax.transform.BindParam`, but does not require the bound parameter to be fully static data array.
> [Unity] Implement relax.Function.bind_symbolic_vars

- python/tvm/contrib/cutlass/gen_conv2d.py
- python/tvm/contrib/cutlass/gen_gemm.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
https://github.com/apache/tvm/pull/14275 was sent and merged to `unity` for no good reason, so I'm sending this to `main` now.
Also the PR makes the conv2d profiling time 4x slower by expanding the search space over the output alignments. In most cases (`profile_all_alignments = False`, the default), we just want to pick the largest-possible alignment. To prevent the conv2d profiling time from blowing up in the default path, this PR adds a fix on top of https://github.com/apache/tvm/pull/14275. Due to this difference, expect merge conflict on the next `unity` + `main` merge. 
@junrushao @spectrometerHBH @Hzfengsy @jwfromm
> [CUTLASS][Cherry-pick] Introduce several features of cutlass profiler

- tests/python/unittest/test_tir_transform_merge_dynamic_shared_memory_allocations.py
I'm thrilled to submit my sixth contribution to Apache! I've addressed the issue of duplicate word 'from' inside the python script. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Remove duplicate 'from' word inside python script

- src/tir/schedule/primitive/layout_transformation.cc
I'm thrilled to submit my fifth contribution to Apache! I've addressed the issue of duplicate word 'load' inside the error message. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Remove duplicate load word inside .cc file

- python/tvm/relay/backend/contrib/ethosu/codegen.py
- src/tir/schedule/analysis.h
I'm thrilled to submit my fourth contribution to Apache! I've addressed the issue of duplicate word 'to' inside the code. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Fix "to" duplicate word in python and C header file

- python/tvm/testing/utils.py
This PR allows to use capitalized variable name `Before` and `Expected` in `CompareBeforeAfter`. When `before / after` are classes or ir module, using capitalized variable names is more consistent with python naming convention.
cc @Lunderberg
> [Testing] Allow Capitalized name in CompareBeforeAfter

- python/tvm/dlight/benchmark/bench.py
This PR fixes the dependency on pytest as optional for mlc-llm as shown in https://github.com/mlc-ai/llm-perf-bench/issues/11.
CC @junrushao
> [Minor][BugFix] Remove PyTest Dependency

- python/tvm/tir/transform/transform.py
- src/target/spirv/codegen_spirv.cc
- src/target/spirv/codegen_spirv.h
- src/tir/transforms/storage_rewrite.cc
- tests/python/unittest/test_tir_transform_pointer_value_type_rewrite.py
Added an option `rewrite_scalar_read_to_vector_shuffle` in `PointerValueTypeRewrite` (currently
only enabled for Vulkan). When enabled, when a buffer has both scalar
and vector reads, the buffer will be vectorized if possible and scalar
reads will be achieved via T.Shuffle.
Close https://github.com/apache/tvm/issues/15463.
cc @tqchen @Lunderberg @sunggg
> [TIR] Shuffle in PointerValueTypeRewrite for scalar reads 

- src/relax/ir/dataflow_matcher.cc
- tests/python/relax/test_dataflow_pattern.py
Prior to this commit, pattern matches that returned a variable (e.g. rewriting `R.add(x, R.const(0.0))` into `x`) would result in rewriting `y = R.add(x, R.const(0.0))` to the trivial binding `y = x`.  This commit updates the pattern matcher to instead remove the `y` variable entirely in this case.
> [Unity] Avoid trivial `var2 = var1` bindings in pattern matcher

- include/tvm/runtime/packed_func.h
This PR introduces a convenient method `PackArgs` that allows packing variadic C++ parameters into TVM's PackedFunc calling convention without recursion using C++ parameter pack tricks.
As an example,
```C++
template <typename... Args>
void MyVariadicMethod(Args&&... args) {
constexpr int kNumArgs = sizeof...(Args);
TVMValue values[kNumArgs];
int type_codes[kNumArgs];
tvm::runtime::PackArgs(values, type_codes, std::forward<Args>(args)...);
...
}
```
> [Runtime] Enhance PackedFunc Metaprogramming with `PackArgs`

- include/tvm/node/script_printer.h
- python/tvm/runtime/script_printer.py
- src/node/script_printer.cc
- src/script/printer/ir_docsifier.cc
- tests/python/unittest/test_tvmscript_printer_tir.py
When debugging IRModule transformations, it can be useful to know the exact C++ address of an object.  For example, to determine whether an undefined TIR variable was caused by erroneous insertion of a new variable, or from failing to remove a previous variable.  While TVMScript does de-duplicate all names within a single print statement, there isn't a convenient way to identify which variable in TVMScript corresponds to a specific variable in C++ logging statements.
This commit adds `show_object_address` to the `PrinterConfig`.  If false (the default), no change is made to the TVMScript variable names.  If true, the address of the C++ object is appended to the variable name.  For example, printing a `tir.Var('my_name','int64')` as `"my_name_0x1234abcd"`.
> [TVMScript] Optionally output the address as part of variable names

- src/tir/analysis/estimate_flops.cc
- tests/python/unittest/test_tir_analysis_estimate_tir_flops.py
Estimates the loop range using arith::Analyzer, starting from the outermost loop.
Added appropriate test cases.
This is a code patch for fixing this issue: https://github.com/apache/tvm/issues/12139
> [MetaSchedule] Fix metaschedule flop estimation for non-integer loop dimensions

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/topi/arm_cpu/conv2d_alter_op.py
- src/relay/op/nn/convolution.cc
- tests/python/relay/strategy/test_select_implementation.py
- tests/python/relay/test_pass_alter_op_layout.py
Fixed arm_cpu strategy bug which was causing tensorization errors when using the `AlterOpLayout` pass for the quantized NHWC conv2d schedules, as discovered in https://github.com/apache/tvm/pull/10724. Therefore, we can now also enable the usage of `AlterOpLayout` for these schedules in order to transform the weight matrix at compile time, instead of runtime as before.  
I also modified the padding in `Conv2DGemmWeightTransformRel` and `interleave_transpose_weights` to reflect the changes made in https://github.com/apache/tvm/pull/13669 and updated the AlterOpLayout tests accordingly.  
cc @ekalda @lhutton1 @leandron
> [Bugfix][Relay][Strategy] Enable compile time transformation of weights matrix for arm_cpu NHWC quantized conv2d

- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This pr introduces `op.print_`, which prints runtime tensor value to the screen in one-line code.
Example:
```python
class Model(Module):
def test(self, x: Tensor):
z = op.add(x, x)
op.print_(z) # In the runtime, the value of z would be printed to screen.
return x
```
cc: @junrushao @cyx-6 @jwfromm
> [Unity][Frontend][NN] Op print_ 

- apps/cpp_rpc/rpc_env.cc
- python/tvm/rpc/client.py
This PR register `tvm.rpc.server.listdir` using `ListDir` and export it in python frontend for PRC use.
> [CPP_RPC] export listdir for RPC

- src/arith/detect_linear_equation.cc
- tests/python/unittest/test_arith_detect_linear_equation.py
Hi, the following code encounters an error while executing
```
c = te.var("c", "uint32")
m = tvm.arith.detect_linear_equation(128 - c, [c])
```
It seems that when creating coefficients for var, it always uses var's dtype, which doesn't seem very reasonable. Even if var itself is uint, its coefficient is likely to be negative.
> [Arith] Fix detect linear equation with uint var

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- src/target/source/codegen_cuda.cc
- src/target/source/codegen_cuda.h
- src/target/source/ptx.cc
- src/target/source/ptx.h
- src/tir/op/builtin.cc
- tests/python/unittest/test_tir_op_types.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
Adds codegen support only for CUDA async copy with barrier synchronization.  TVM currently uses group based synchronization for async copies through the InjectSoftwarePipeline pass but new "bulk" async copy instructions for Hopper require barrier synchronization.  This PR adds codegen for barrier synchronization as a first step towards adding support for Hopper "bulk" async copy support.
> [Hopper TMA] CUDA codegen for async copy with barrier synchronization

- include/tvm/relax/attrs/nn.h
- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/op/nn/nn.py
- python/tvm/relax/transform/legalize_ops/nn.py
- src/relax/op/nn/nn.cc
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_op_nn.py
- tests/python/relax/test_transform_legalize_ops_nn.py
This PR adds support for the huggingface diffusers `Timesteps` layer. This is useful when constructing stable diffusion like models. The definition of the layer required padding, so I also implemented `relax.op.nn.pad` using semantics as close to pytorch as possible.
> [Unity][Frontend][NN] Add Timesteps layer to NN Module API

- python/tvm/relax/transform/transform.py
- src/relax/transform/dead_code_elimination.cc
- tests/python/relax/test_transform_dead_code_elimination.py
Prior to this commit, the DeadCodeElimination pass avoided removing externally-exposed functions, only checked for callees from user-specified functions.  If an external function wasn't specified, the dead-code elimination could remove a callee resulting in a dangling `GlobalVar`.
This commit updates the dead code elimination to treat all externally-exposed functions as potential entry points. User-specified functions can still be provided, and are treated as additional entry points.
> [Unity][Transform] Track callees from external functions in DeadCodeElimination

- web/src/compact.ts
I'm thrilled to submit my eighth contribution to Apache! I've addressed the issue of weak comparing == inside the compact.ts. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
**Description:**
Change the comparison operator `==` to `===` in the `compact.ts` file for improved type checking and accuracy.
**Changes:**
- Replaced `==` with `===` operator for more strict equality comparison.
> Change == to === operator in compact.ts file

- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/frontend/nn/spec.py
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_frontend_onnx.py
This PR adds support for the `Attention` layer in the nn module API. This layer mimics the behavior of the [Attention layer used in huggingface Diffusers](https://github.com/huggingface/diffusers/blob/80871ac5971fe7e708befa3b553463c4e61b22ab/src/diffusers/models/attention_processor.py#L36). Under the hood it uses scaled dot product attention. Notably, there are still some missing features. For example I didnt add support for attention masks yet. I also am assuming 3 dimensional inputs so this likely wouldnt be useful for the VAE of stable diffusion. However, it does allow us to represent the all attention layers of the UNET. I'm hoping we can expand on the functionality more if needed in future PRs.
> [Unity][Frontend][NN] Add diffusers style Attention layer

- web/src/memory.ts
- web/src/rpc_server.ts
- web/src/runtime.ts
I'm thrilled to submit my ninth contribution to Apache! I've addressed the issue of weak comparing == inside the typescript files in `web` directory. Paying attention to such details is vital for code quality, and I'm committed to enhancing the project.
-- MAX
> Fix equality comparison and code consistency in web

- python/tvm/relax/op/mask.py
Fix is needed for correct work of masked_fill op which particularly used by MPT-like models
@masahi
> [Unity] fix masked_fill operation

- docs/contribute/community.rst
This PR updates the docs per recent community strategy decision process.
> [DOCS] community strategy decision process

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
When graph inputs are used in an inner body of If node, the original TVM ONNX
frontend did not set the span properly. Because of the wrong or partial span,
new relay.Var is introduced and failed to match identical Var. Firstly, there
was an issue where the free variable of the inner body was updated in _node but
not applied to _input. Secondly, although the free variable of the then body
successfully updated to relay.Var in _node, but this was obscured by the update
of _node in the else body.
This commit fixes the ONNX importer and adds an ONNX import testcase for the
revised code.
> [ONNX][BugFix] Support If body with free variable from graph input 

- src/runtime/module.cc
This PR exposes `Module.GetFunction` as a global PackedFunc. Previously, the only way to access this method is via TVM's C API, but the C++ PackedFunc API is missing. This PR patches this issue.
> [Runtime] Expose ModuleGetFunction as PackedFunc

- python/tvm/relax/testing/relay_translator.py
- tests/python/relax/test_relay_translator.py
Sometimes it is useful to instrument relay passes that are run during relay to relax translation, and this patch adds a new argument to relay translator to accept instruments list.
The instruments can be passed on as
```python
relay_translator.from_relay(..., instruments=[MyInstrumentsObject])
```
> [Unity] Add instruments to relay translator

- include/tvm/runtime/object.h
- src/runtime/minrpc/minrpc_server.h
- src/runtime/minrpc/minrpc_server_logging.h
- src/runtime/minrpc/rpc_reference.h
- src/runtime/rpc/rpc_endpoint.cc
This PR introduces object support in TVM RPC protocol by introducing three new interfaces in `rpc_reference.h`:
- `uint64_t GetObjectBytes(Object* obj)`, which is a required implementation that returns the length of the object during serialization;
- `void WriteObject(Object* obj)` used to serialize an object to a writable channel;
- `void ReadObject(int* type_code, TVMValue* value)`, which deserializes a TVM Object from a channel.
To serialize an object, a recommended paradigm is to write its `type_index` first, and then its content. For example, `ShapeTuple` can be serialized as:
```C++
// pseudocode
void WriteObject(Object* obj) {
if (obj is ShapeTuple) {
this->Write<uint32_t>(type_index of ShapeTuple);
this->Write<int32_t>(obj->ndim);
this->WriteArray<int64_t>(obj->shape);
} else { …
```
> [RPC] Enhance RPC Protocol to support TVM Object

- vta/python/vta/transform.py
tvm.tir.Call has no name attribute, this attribute belongs to op.
> [BugFix][VTA] tvm.tir.Call has no name attribute

- include/tvm/runtime/data_type.h
- include/tvm/runtime/device_api.h
- include/tvm/runtime/packed_func.h
- include/tvm/tir/op.h
- src/runtime/c_runtime_api.cc
- src/runtime/contrib/papi/papi.cc
- src/runtime/hexagon/hexagon_device_api.cc
- src/runtime/profiling.cc
- src/runtime/rpc/rpc_module.cc
- src/runtime/vm/memory_manager.cc
- src/tir/transforms/lower_tvm_builtin.cc
There exist some basic functionality to convert Device and DLDeviceType to std::string, but they are not following the common naming convention in TVM, and thus less discoverable. This commit makes changes accordingly:
- `runtime::DeviceName` to `runtime::DLDeviceType2Str`
- move declaration of `operator << (std::ostream&, Device)` from `runtime/device_api.h` to `runtime/packed_func.h`
> [Runtime] Utils to Stringify Device

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
Prior to this PR, the GeMV contains an assumption that "the grouped dimension of the largest tensor in GeMV must has the same iter type as the innermost dimension", which is enforced by an assertion.
Since AutoGPTQ quantization only supports KN GeMV layout, the decode-GeMV generated under the AutoGPTQ quantization has the pattern where the reduction dimension is not the innermost and is grouped. This pattern does not follow the assersion above and thus an assertion error will be thrown.
This PR updates the logic to skip transforming such cases, instead of asserting the assumption. One real AutoGPTQ decode-GeMV workload is added as a test case for future awareness.
> [Unity][Dlight] GeMV rule skip cases of "outer dim being grouped"

- src/runtime/disco/threaded_session.cc
- tests/python/disco/test_session.py
ShapeTuple is an essential item used in Relax stack as the runtime representation of shapes. It is also used as a current workaround to represent integers (1-d shape) given standalone non-constant integers are currently absent in Relax.
This PR introduces formal support for ShapeTuple in Disco's communication protocol based on the recent enhancement of TVM RPC system to support TVM Objects: https://github.com/apache/tvm/pull/15631.
> [Disco] Support ShapeTuple in Disco Protocol

- include/tvm/runtime/packed_func.h
This PR fixes an error reporting from Clang on the line below:
```
/.../include/tvm/runtime/packed_func.h:1706:3: error: no matching function for call to 'F'
detail::parameter_pack::EnumerateWithArg<Args...>::template F<TVMArgsSetterApply>(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> [Runtime] Fix ICE from Clang

- src/tir/transforms/split_host_device.cc
- tests/python/unittest/test_tir_transform_lower_warp_memory.py
- tests/python/unittest/test_tir_transform_thread_sync.py
If the generated device function uses a buffer, generate a DeclBuffer for the buffer at the top of the device function.
This is a subset of the changes made in https://github.com/apache/tvm/pull/14778, broken out for ease of testing and review.
> [TIR] Output DeclBuffer in SplitHostDevice

- src/arith/rewrite_simplify.cc
- tests/python/unittest/test_arith_rewrite_simplify.py
The expression `(x==y) && (x==z)` requires that `y==z`.  When `y` and `z` are constants, this can allow better constant folding by rewriting `(x==c1) && (x==c2)` into `(x==c1) && (c1==c2)`.
This commit adds the above rewrite, and the corresponding rewrite of the negative expression.  This was initially part of https://github.com/apache/tvm/pull/15627, but does not depend on Relax features, and is split out in order to upstream into TVM main.
> [Arith] Added simplification rule for multiple equality compares

- include/tvm/runtime/packed_func.h
Backported from #15635. This template is never instantiated on `apache:main` yet, but in case of future ICE, I backported the related fix from Unity branch.
> [Backport][Runtime] Fix ICE from Clang

- CMakeLists.txt
They are already linked into libtvm.so, and cpptests links against libtvm.so, so they are not needed again. On the other hand, linking them twice can lead to the following error:
```
CommandLine Error: Option 'print-summary-global-ids' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
> Do not link LLVM libraries into cpptest binary

- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/op/image/image.py
- src/relax/transform/rewrite_dataflow_reshape.cc
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_op_image.py
- tests/python/relax/test_transform_rewrite_dataflow_reshape.py
This PR adds a bunch of new NN operators that conform to torch semantics. I also updated a couple of existing operators like LayerNorm to be more inline with the torch equivalent. Specifically this PR adds
* unsqueeze
* concat
* subtract
* Identity
* chunk
* pad
I also fixed an issue in ReshapeDataflowRewrite when operating on scalars.
> [Unity][Frontend][NN] Collection of new NN operators

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
Prior to this PR, the GeMV dlight rule is not aware of the maximum number of threads of the backend target. This PR brings the awareness. This is mainly for the purpose of WebGPU where each thread block can have 256 threads at most.
> [Unity][Dlight] GeMV rule max_num_threads awareness

- src/runtime/relax_vm/ndarray_cache_support.cc
- src/runtime/relax_vm/ndarray_cache_support.h
Prior to this PR, `ndarray-cache.json` is loaded, parsed along with the concrete weights. This PR adds support to parse this JSON file to a structured C++ class instead for later use.
> [Runtime] Support Loading Standalone `ndarray-cache.json`

- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/frontend/nn/spec.py
- tests/python/relax/test_frontend_nn_extern_module.py
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_frontend_nn_subroutines.py
- tests/python/relax/test_frontend_nn_tensor.py
This PR adds the `debug` argument to `export_tvm`. When `debug` is `False`, effects are not included in the output graph. This can make deploying models less cumbersome since its not often theyll use effects. I also added automatic annotation of the `num_inputs` function attribute since it is useful for a few passes.
> [Unity][Frontend][NN] Make effects optional in nn module.

- python/tvm/script/ir_builder/relax/ir.py
- python/tvm/script/parser/relax/__init__.py
- python/tvm/script/parser/relax/entry.py
- src/script/ir_builder/relax/ir.cc
- tests/python/relax/test_tvmscript_parser.py
In the same way as T.macro, R.macro support hygiene (via "hygienic" keyword), but unlike TIR macros, Relax macros produce expressions, and have to return a value: the last statement in R.macro must be "return".
> [Unity] Implement R.macro for Relax macros

- include/tvm/runtime/container/shape_tuple.h
- src/node/container_printing.cc
This PR adds two convenient methods for `ShapeTuple`.
```C++
// Returns the number of elements in the shape,
// i.e. the product of all dimensions
ShapeTupleObj::index_type ShapeTupleObj::Product();
// Printing method for shape
std::ostream& operator<<(std::ostream& os, const ShapeTuple& shape);
```
> [Runtime] ShapeTuple.Product and ShapeTuple Printing

- src/runtime/relax_vm/ndarray_cache_support.cc
- src/runtime/relax_vm/ndarray_cache_support.h
This PR refactors the NDArrayCache support with the following changes:
- Support loading metadata from a string rather than a concrete JSON file on disc;
- Remove dependency to std::filesystem as it is not well supported in certain platforms yet. Details: https://github.com/apache/tvm/pull/15654#issuecomment-1703282818.
- Simplify format used in `shard-info.json` as detailed below:
```
// Existing format
[
{
"name": "x0",
"shard_dim": 0,
},
{
"name": "x1",
"shard_dim": 1,
}
]
// New format
{
"x0": 0,
"x1": 1,
}
```
> [Runtime] Refactor NDArrayCache Support

- src/runtime/disco/loader.cc
- tests/python/disco/test_loader.py
This PR introduces `ShardLoader`, an object that allows convenient
sharding of each parameter, assuming there is a single shard dimension
and the sharding strategy is even. The sharding can be performed
efficiently on device (e.g. CUDA) and scattered to each worker with
NCCL support.
The shard loading process could be further compiled to Relax IRModule
to be executed by each worker with the function signature below:
```python
@R.function
def main(loader: R.Object) -> R.Tuple(
R.Tensor((64, 64), "float32"),
R.Tensor((16, 128), "float32"),
):
R.func_attr({"global_symbol": "main"})
lv0 = R.call_pure_packed(
"runtime.disco.ShardLoaderLoad",
loader,
R.shape([0]),
sinfo_args=R.Tensor((64, 64), "float32"),
)
lv1 = R.call_pure_packed(
"runtime.disco.ShardLoaderLoad",
loader, …
```
> [Disco] Introduce ShardLoader

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul.py
- tests/python/dlight/test_gpu_matmul_tensorize.py
The current matmul implementation is targeted for NVIDIA GPU, which is not optimized for Adreno GPU (also other edge devices). This patch improves the performance, improving performance from 7170.14ms to 554.57ms for a very large kernel
> [Unity][DLight] Improve the performance of matmul on Adreno GPU

- apps/microtvm/ethosu/corstone300.ld
Fixed output_data_sec section was missing in the corstone300.ld for Ethos-U.
See more detail: https://github.com/apache/tvm/issues/15643
> Add output_data_sec section in corstone300.ld

- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_modules.py
This PR introduces `nn.MultiLinear` as an extension to `nn.Linear` which is arithmetically equivalent to applying multiple `nn.Linear` to the same input.
For example, QKV projection in attention, represented in `nn.Linear` being:
```python
q_proj = nn.Linear(hidden_dim, ...)
k_proj = nn.Linear(hidden_dim, ...)
v_proj = nn.Linear(hidden_dim, ...)
q = q_proj(x)
k = k_proj(x)
v = v_proj(x)
```
could be simplified using `nn.MultiLinear` as:
```python
qkv_proj = nn.MultiLinear((hidden_dim, hidden_dim, hidden_dim), ...)
q, k, v = qkv_proj(x)
```
The underlying implementation, by default, will fuse all the projection matrices into a single one, to allow potentially larger room for optimization.
> [Unity][Frontend][NN] Add nn.MultiLinear

- python/tvm/ir/expr.py
This PR adds a small change to verify equality of `tvm.ir.Range` as a structural equal. This assumes that in most cases, comparing two `Range`s means to compare its `min` and `extent` as opposed to the actual Range object handle.
> [IR] Use structural equal for Range equality

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- src/target/source/codegen_cuda.cc
- src/target/source/ptx.cc
- src/target/source/ptx.h
- src/tir/op/builtin.cc
- tests/python/unittest/test_tir_op_types.py
- tests/python/unittest/test_tir_ptx_cp_async.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
Adds CUDA codegen support for bulk asynchronous copy which are new instructions for Hopper.  Also includes some cleanup of PR #15616 in the form of comments and tests.  Notably this PR does not include any TIR transform work for lowering to new bulk asynchronous copy instructions; this will come in a future PR.  Also note the "workaround" and TODO regarding lack of CUDA codegen support for allocation alignment.
> [Hopper TMA] Add CUDA codegen support for bulk asynchronous copy

- docker/bash.sh
This PR adds a new flag `--cpus` in `./docker/bash.sh`, which is passed to docker command that allows limiting the number of CPU cores of a docker container.
Related materials: https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler
> [CI] Allow Limit CPUs in Docker

- src/arith/iter_affine_map.cc
- tests/python/unittest/test_arith_iter_affine_map.py
This PR fixes an issue of the IterMapRewriter. Prior to this PR, the mutation function of the rewriter class returns the mutation results even when an invalid PrimExpr pattern was detected.
Returning the mutation results when failure is not expected, and in such cases we should "abort" the mutation, and return the input PrimExpr which is not mutated, since insisting on returning the mutation results sometimes it incurs further error on other arith components like simplification.
One unit test is added to ensure the rewriter behaves as expectation.
> [BugFix][Arith] IterMapRewriter abort rewriting once failure

- python/tvm/contrib/msc/core/codegen/__init__.py
- python/tvm/contrib/msc/core/codegen/codegen.py
- python/tvm/contrib/msc/core/ir/graph.py
- python/tvm/contrib/msc/core/ir/translate.py
- python/tvm/contrib/msc/core/utils/file.py
- python/tvm/contrib/msc/core/utils/namespace.py
- python/tvm/contrib/msc/core/utils/register.py
- python/tvm/contrib/msc/framework/__init__.py
- python/tvm/contrib/msc/framework/tvm/__init__.py
- python/tvm/contrib/msc/framework/tvm/_ffi_api.py
- python/tvm/contrib/msc/framework/tvm/codegen/__init__.py
- python/tvm/contrib/msc/framework/tvm/codegen/codegen.py
- src/contrib/msc/core/codegen/base_codegen.h
- src/contrib/msc/core/codegen/code_stack.cc
- src/contrib/msc/core/codegen/code_stack.h
- src/contrib/msc/core/codegen/codegen_utils.cc
- src/contrib/msc/core/codegen/codegen_utils.h
- src/contrib/msc/core/codegen/py_codegen.h
- src/contrib/msc/core/ir/graph.cc
- src/contrib/msc/core/ir/graph.h
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/ir/graph_builder.h
- src/contrib/msc/core/transform/set_expr_name.cc
- src/contrib/msc/framework/tvm/codegen.cc
- src/contrib/msc/framework/tvm/codegen.h
- src/contrib/msc/framework/tvm/config.h
- src/contrib/msc/framework/tvm/relax_opcode.cc
- src/contrib/msc/framework/tvm/relax_opcode.h
- tests/python/contrib/test_msc/test_translate_relax.py
- tests/python/contrib/test_msc/test_translate_relay.py
This is the last part of Milestone 0: Codegen and Translation test
To limit each PR in reviewable size, the Milestone 0 will be split into 5 steps:
M0.1: Passes for set name and layout for expressions (src/contrib/msc/transform)
M0.2: MSCGraph core (src/contrib/msc/core/ir/graph && python/tvm/contrib/msc/core/ir/graph)
M0.3: MSCGraph Builder (src/contrib/msc/core/ir/graph_builder)
M0.4: Codegen (src/contrib/msc/core/codegen, src/contrib/msc/framework/tvm/codegen)
M0.5: Translation test (relax/relay test && related helper modules in python)
CodeGen is used to translate MSCGraph to …
> [Unity][MSC][M0.4 && M0.5] Codegen && Test

- tests/scripts/task_demo_microtvm.sh
This is a followup from #15649 which caught a misclassification issue when running the microNPU demo. While #15649 fixes the issue and results in the correct classification, this commit ensures the demo does not regress again in the future.
cc @ashutosh-arm @leandron
> [microTVM] Check the output of microNPU demos in CI

- src/relay/transforms/annotate_texture_storage.cc
- tests/python/relay/opencl_texture/test_conv2d_nchw_texture.py
- tests/python/relay/opencl_texture/utils/adreno_utils.py
In VM `fn->attrs` doesn't contain information about `kernel_layout`. So we can get this value from `expr_attrib`. In this PR function `CanUseBuffers` was modified to work with VM.
A new test which checks memory scope for VM was added.
> [VM][Adreno] Fix using buffers for weights in VM

- python/tvm/relax/transform/transform.py
- src/relax/transform/bundle_model_params.cc
- src/relax/transform/lift_transform_params.cc
- tests/python/relax/test_transform_bundle_model_params.py
- tests/python/relax/test_transform_lift_transform_params.py
Implemented `relax.transform.BundleModelParams`, which groups parameters into user-provided runtime parameters, and a tuple of compile-time model weights.  This functionality was previously part of `LiftTransformParams`, but is being separated to allow for composable functions which each mutate the parameters.
> [Unity] Implemented BundleModelParams transform

- include/tvm/relax/transform.h
- include/tvm/relax/utils.h
- python/tvm/relax/expr.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/bind_params.cc
- src/relax/utils.cc
- tests/python/relax/test_bind_params.py
- tests/python/relax/test_relay_translator.py
- tests/python/relax/test_transform_bind_params.py
- tests/python/relax/test_transform_fold_constant.py
Similar to `relax.Function.bind_symbolic_vars`, implemented in https://github.com/apache/tvm/pull/15509, this commit introduces `relax.Function.bind_params` to allow Relax parameters to be manipulated on a per-function basis.  This utility function and the existing `BindParams` transform both use the same underlying implementation.
> [Unity] Implement relax.Function.bind_params

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul.py
- tests/python/dlight/test_gpu_matmul_tensorize.py
Prior to this PR, the dlight matmul rule uses hardcoded `int64` as index dtype. When the input workload is `int32` dtyped and has symbolic vars like `n: T.int32`, the PrimFunc generated by the matmul rule may contain PrimExpr like
```python
T.Cast("int32", T.Cast("int64", n))
```
which is not wrong but not 100% correct.
This PR changes the hardcoded `int64` to the dtype of the input block iters in the rule, and resolves the issue above.
> [Unity][Dlight] Matmul rule on int32 workloads

- python/tvm/dlight/gpu/fallback.py
- src/tir/schedule/transform.cc
- tests/python/dlight/test_gpu_fallback.py
This PR enhances the fallback dlight GPU rule so that it can support more non-trivial spatial workloads.
Particularly, to this end, this PR makes the following changes:
* for function normalization: when a block of a TIR PrimFunc cannot be applied by "TransformLayout", it will now give up layout transformation instead of throwing the error in TransformLayout.
* for the fallback rule, if the return value of the normalization is None, it will directly return, instead of proceeding the inline attempt.
* for the fallback rule, when iterating the blocks in the PrimFunc, if the loops of a block are already bound to GPU threads, the block will be skipped so the loops will not be processed again.
> [Unity][Dlight] Fallback rule supporting more spatial workloads

- python/tvm/contrib/msc/core/ir/graph.py
- src/contrib/msc/core/ir/graph.cc
- src/contrib/msc/core/ir/graph.h
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/transform/set_expr_name.cc
This PR change the names from master_name to shared_ref. The shared_ref is the name of node who share parameters with the current node.
Nothing are changed besides name change.
> [Unity][MSC][special] Change special names

- include/tvm/relax/struct_info.h
- python/tvm/relax/struct_info.py
- python/tvm/script/parser/relax/entry.py
- src/relax/analysis/struct_info_analysis.cc
- src/relax/ir/expr.cc
- src/relax/ir/expr_functor.cc
- src/relax/ir/struct_info.cc
- src/relax/ir/struct_info_functor.cc
- src/script/printer/relax/struct_info.cc
- tests/python/relax/test_analysis_struct_info_analysis.py
- tests/python/relax/test_bind_symbolic_vars.py
- tests/python/relax/test_expr.py
- tests/python/relax/test_struct_info.py
- tests/python/relax/test_tvmscript_parser.py
- tests/python/relax/test_tvmscript_printer_relax.py
Prior to this commit, a `relax.PrimValue` could have a datatype, but couldn't have a corresponding `tir.PrimExpr`.  As a result, it could not be used to specify tensor shapes.  This makes some expressions require fallback to `R.Tensor(ndim=ndim)`, even though the shape could still be inferred.
```python
@R.function
def func(
A: R.Tensor(16, 16),
first_n_rows: R.Prim("int64"),
) -> R.Tensor([first_n_rows, 16]):
#
out = R.op.strided_slice(axis=[0], begin=[0], end=[first_n_rows])
return out
```
This commit adds a `Optional<PrimExpr> value` field to the `PrimStructInfo`.  This field acts similarly to the `PrimExpr` fields already used in `ShapeStructInfo`, and may contain symbolic variables.
```python
@R.function
def func(
A: R.Tensor(16, 16),
first_n_rows: R.prim(value="first_n_rows_tir"),
) …
```
> [Unity] Added known tir.Expr to relax.PrimValue

- tests/python/relax/test_vm_build.py
- web/tests/python/prepare_test_libs.py
- web/tests/python/relax_rpc_test.py
All parameters to `export_library` after the path are now keyword-only. Update the few remaining locations in "unity" after merge of "main" branch.
> [Unity] Update remaining calls to `export_library` with keyword arguments

- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_transform_cse.py
Prior to this commit, `R.ShapeExpr` occurring multiple times in a relax function would be de-duplicated.  If these shape expressions are de-duplicated, later use of `emit_te` may fail as it expects operations to have explicit `ShapeExpr` shapes.
> [Unity] Preserve ShapeExpr in EliminateCommonSubexpr transform

- src/relax/analysis/analysis.cc
- tests/python/relax/test_analysis.py
Prior to this commit, the `VarVisitor` used in the implementation of `all_vars` and `free_vars` only collected variable usage sites where the variable was a `const VarNode*`, and ignored usage sites of a `const DataflowVarNode*`.  When analyzing an entire function, these variables were found in the `const VisitVarBinding*`, and could pass the existing tests.  However, when analyzing a single expression, these variables would be erroneously excluded.
This commit adds a `VisitExpr_(const DataflowVarNode*)` implementation in `VarVisitor`, to collect variable usage regardless of the type of variable.
> [Unity][Analysis] Check for usage of DataflowVar in all_vars()

- src/runtime/static_library.cc
- src/target/codegen.cc
- src/target/source/source_module.cc
- tests/python/unittest/test_roundtrip_runtime_module.py
- tests/python/unittest/test_runtime_module_property.py
This PR implements `SaveToBinary` and `LoadFromBinary` methods for `CSourceModule` and `StaticLibraryModule`. 
Its new runtime module property and roundtrippablity are tested. 
cc. @tqchen
> [Runtime] Make `CSourceModule` and `StaticLibraryModule` Binary Serializable

- include/tvm/runtime/c_runtime_api.h
- include/tvm/runtime/registry.h
- python/tvm/_ffi/_ctypes/packed_func.py
- python/tvm/_ffi/_cython/base.pxi
- python/tvm/_ffi/_cython/packed_func.pxi
- python/tvm/_ffi/base.py
- src/ir/transform.cc
- src/relay/analysis/type_solver.cc
- src/runtime/c_runtime_api.cc
- src/runtime/logging.cc
- src/runtime/registry.cc
- src/support/ffi_testing.cc
- tests/python/relay/test_pass_instrument.py
- tests/python/relay/test_type_infer.py
- tests/python/unittest/test_meta_schedule_schedule_rule_apply_custom_rule.py
- tests/python/unittest/test_runtime_error.py
Prior to this commit, if a Python script passes a callback to a C++ function, and that callback raises an exception, the original exception cannot be caught in the outer python script.  As a result, interactive debugging, such as done with `pdb` or `ipdb`, could only inspect stack frames outside the first Python to C++ FFI call.
This commit updates the FFI API to propagate the Python exception through an FFI boundary.  As a result, all Python frames in the stack trace can be inspected.
> [FFI] Propagate Python errors across FFI boundaries

- tests/python/relax/test_codegen_cutlass.py
https://github.com/apache/tvm/pull/15657 modified the signature of a mod generated by `LiftTransformParams` pass to take unpacked params as input rather than tuple params. Some cutlass tests needs updating to follow this change (they don't run on CI "yet").
@Lunderberg
> [Unity] Fix CUTLASS tests following LiftTransformParams signature change

- python/tvm/runtime/script_printer.py
The new feature of printing object addresses is introduced in #15579. It's an excellent feature for debugging, but it should not be turned on by default.
cc @Lunderberg @junrushao
> [TVMScript][FIX] Disable `show_object_address` in printing by default

- python/tvm/runtime/script_printer.py
- python/tvm/script/highlight.py
- python/tvm/tir/schedule/schedule.py
- python/tvm/tir/schedule/trace.py
`Black` is a popular code formatter for Python. However, it is not suitable for TVM script. This PR tries to disable it by default.
This would change the default printing behavior, love to hear opinions from the community.
cc @tqchen @Lunderberg @junrushao @cyx-6
> [TVMScript] Disable `black_format` by default

- python/tvm/relax/transform/lazy_transform_params.py
- tests/python/relax/test_transform_lazy_transform_params.py
This PR brings the support for dynamic-shape parameters to pass LazyTransformParams.
Prior to this PR, the symbolic variables in the dynamic-shape parameters are not properly popped out. This PR uses MatchCast to make sure the symbolic variables are always popped out and thereby support the dynamic-shape parameters.
This PR also fixes a previvously failed test.
> [Unity] Dynamic-shape param support in LazyTransformParams

- python/tvm/relay/frontend/oneflow.py
- tests/python/frontend/oneflow/test_forward.py
The implementation logic of Softplus in OneFlow in  shown [here](https://start.oneflow.org/oneflow-api-cn/nn.html#:~:text=class%20oneflow.nn.Softplus(beta%3A%20int%20%3D%201%2C%20threshold%3A%20int%20%3D%2020)%C2%B6)
The original implementation of it can pass the existing test case. Thus, it skipped the corresponding test.
In this PR, I fixed the bug and made the test case runnable by canceling the comments.
cc @Hzfengsy @echuraev
> [Relay][Bugfix] fix the wrong implementation of Softplus in OneFlow

- python/tvm/relay/op/strategy/arm_cpu.py
- tests/python/relay/strategy/test_select_implementation.py
Whenever both dotprod and i8mm were available together on a target (e.g. `"llvm --device=arm_cpu --mtriple=aarch64-linux-gnu -mattr=+v8.2a,+dotprod,+i8mm"`), the native int8 conv2d implementation corresponding to the `+dotprod` attribute would be selected, but the compute definition of the conv2d operation would be constructed for the `+i8mm` attribute and its related interleaved schedule instead.  
The reason for this was a different order of conditional statements being used in 2 separate files:
- `arm_cpu.py`: When selecting the conv2d implementation, the program first checked for `dotprod` support. If present, it chose the native schedule
- `conv2d_gemm.py`: when constructing the compute definition, `i8mm` support is checked first, then `dotprod` 
To fix this, I modified the int8 …
> [Bugfix][Strategy] Fix `arm_cpu` int8 conv2d strategy for dotprod and i8mm targets

- python/tvm/topi/arm_cpu/conv2d_gemm.py
When padding the input data, the int8 conv2d interleaved schedule tries to split the `data_im2col` cols axis by a factor of 16 in order to then vectorize over those splits. However, the size of the axis is `n_size = KH x KW x IC` and the `Legalize` pass only pads the number of input channels up to a multiple of 8. Therefore, `n_size` is only guaranteed to be a multiple of 8, not 16.   
I modified the schedule to check whether a split factor of 16 is appropriate, otherwise use 8 instead, in order to ensure vectorization is performed in all cases.
cc @ekalda @lhutton1 @leandron @neildhickey
> [TOPI] Ensure vectorization of input padding in `arm_cpu` int8 conv2d interleaved schedule

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- src/target/source/codegen_cuda.cc
- src/target/source/codegen_cuda.h
- src/target/source/ptx.cc
- src/target/source/ptx.h
- src/tir/op/builtin.cc
- tests/python/unittest/test_tir_op_types.py
- tests/python/unittest/test_tir_ptx_cp_async.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
This PR adds an intrinsic to create barriers that can be used with existing barrier intrinsics for synchronization.  The prior method of barrier allocation was to use `alloc_buffer` e.g. as follows `barrier = T.alloc_buffer([1], "uint64", scope="shared")` and then pass the pointer and offset to that barrier allocation for use in the barrier intrinsics.  This was a functional interface, but also caused problems with alignment of other non-barrier shared memory allocations.  See removed workarounds marked with `TODO` in the tests in this PR.  At the expense of the additional `create_barriers` intrinsic we get a simplified interface using barrier ID rather than pointer / offset passed to the barrier intrinsics and more low-level codegen control which is used in this PR to solve the alignment …
> [Hopper TMA] Add intrinsic to create barriers for synchronization

- src/tir/transforms/lower_thread_allreduce.cc
- tests/python/unittest/test_tir_transform_lower_thread_all_reduce.py
For any local buffers allocated as part of `LowerThreadAllreduce`, generate a `DeclBuffer`.                                                                                                                                                                                                                      
This is a subset of the changes made in https://github.com/apache/tvm/pull/14778, broken out for ease of testing and review.
> [TIR] Output DeclBuffer in LowerThreadAllreduce

- include/tvm/runtime/disco/session.h
- src/relax/transform/fuse_tir.cc
- src/runtime/disco/bcast_session.cc
- src/runtime/disco/builtin.cc
- src/runtime/disco/builtin.h
- src/runtime/disco/loader.cc
- src/runtime/disco/nccl/nccl.cc
- src/runtime/disco/worker.cc
This PR contains necessary tweaks to run Llama2 in Tensor Parallelism.
> [Disco] Make Session.CallWithPacked public

- python/tvm/relay/frontend/oneflow.py
- tests/python/frontend/oneflow/test_forward.py
The implementation logic of Threshold in oneflow is as follows:
The detail information can be found [here](https://start.oneflow.org/oneflow-api-cn/nn.html#:~:text=class%20oneflow.nn.Threshold,%EF%BC%8C%E5%90%A6%E5%88%99%E8%BF%94%E5%9B%9E%20value%E3%80%82)
This PR corrects the implementation and adds a corresponding test case.
cc @Hzfengsy @echuraev @vvchernov
> [Relay][Bugfix] Fix the wrong implementation about operator Threshold in oneflow

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/optimize_layout_transform.py
- tests/python/relax/test_optimize_layout_transform.py
Relax `AlterOpImpl` pass introduces `layout_transform` operations. If the layouts match for consecutive `layout_transform` operations, they can be cancelled out. This pass tries to optimize redundant `transform_layout` operations.
This is also addressing P4 in https://github.com/apache/tvm/issues/14070
> [UNITY][Pass] Optimize redundant layout transform ops

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
As per https://github.com/apache/tvm/issues/15148, we are adding support for quantized operations one by one. This PR adds support for `floor_div`.
> [TFLite][Frontend] Support quantized floor_div

- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/avg_pool.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/gemm.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/max_pool.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/tensordot.py
- src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc
- src/relay/backend/contrib/example_target_hooks/tir_to_runtime.cc
- src/relay/backend/contrib/uma/tir_to_runtime.cc
- src/target/opt/build_cuda_on.cc
- src/target/source/codegen_aocl.cc
- src/target/source/codegen_c.cc
- src/target/source/codegen_c.h
- src/target/source/codegen_c_host.cc
- src/target/source/codegen_c_host.h
- src/target/source/codegen_cuda.cc
- src/target/source/codegen_cuda.h
- src/target/source/codegen_metal.cc
- src/target/source/codegen_metal.h
- src/target/source/codegen_opencl.cc
- src/target/source/codegen_vhls.cc
- src/target/source/codegen_webgpu.cc
- src/target/source/codegen_webgpu.h
- src/target/source/source_module.cc
- src/tir/op/op.cc
- tests/python/relay/aot/test_crt_forward_declarations.py
- tests/python/topi/python/test_topi_conv2d_tensordot_opts.py
- tests/python/unittest/test_target_codegen_c_host.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
This PR temporarily reverts a recent change that breaks the Metal backend. Happy to get this commit back once the codegen is fixed.
Reverts apache/tvm#15103
> Revert "[CodeGenC] Handle GlobalVar callee as internal function call"

- python/tvm/relay/frontend/keras.py
- tests/python/frontend/keras/test_forward.py
Fix this [issue](https://github.com/apache/tvm/issues/14868)
Just as @echuraev guessed,  `_convert_simple_rnn` has some logical errors. I'm not very sure if I fix it correctly. All in all, after this fix, running the following bug-triggered script will feedback a good compilation result, and `InferType()` can successfully infer all types/shapes in the model and the inference is correct.
```Python
import tvm
from tensorflow.keras import layers, models
input_shape = (2, 2, 2)
x = layers.Input(shape=input_shape[1:], dtype='float32')
layer = keras.layers.SimpleRNN(units=2)
layer.set_weights(layer.get_weights())
y = layer(x)
model = models.Model(x, y)
model.summary()
mod, params = relay.frontend.from_keras(model, {'input_1': input_shape}) …
```
> fix _convert_simple_rnn

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
As Adreno has poor shared memory performance, for LLM workloads, we prefer `q4f16_0` instead of `q4f16_1`.
This PR adds GEMV rule support for Adreno outer reduction, comparing with `q4f16_1`, we get a performance gain
- Prefill(not related with this PR changes): 3636.6501 ms -> 1241.9469 ms
- Decode: 211.0834 ms -> 174.9357 ms
> [DLight] Update GEMV rule to support Adreno outer reduction

- python/tvm/topi/arm_cpu/conv2d_alter_op.py
- python/tvm/topi/arm_cpu/conv2d_gemm.py
- tests/python/relay/test_pass_legalize.py
The Legalize pass was unnecessarily padding the input channels for conv2d int8 native implementations. Since the conv2d schedule itself can add padding more efficiently, I skipped padding during the pass and further optimised the schedule to deal with it.  
I also added a test to check whether or not the Legalize pass pads the conv2d input data.  
The benchmark results of a single int8 conv2d operation where input padding along the K axis is necessary, with input = (1 x 224 x 224 x 3), filter = (16 x 3 x 3 x 3), output = (1 x 112 x 112 x 16), tested for the following target `"llvm --device=arm_cpu --mtriple=aarch64-linux-gnu -mattr=+v8.2a,+dotprod"` , before and after the changes, is given below:
|  Before (ms) | After (ms) | Speedup (%) |
|-------------|------------|-------------|
| …
> [Relay][TOPI] Remove input padding for arm_cpu conv2d int8 native schedule in Legalize pass

- python/tvm/runtime/ndarray.py
- python/tvm/target/detect_target.py
- python/tvm/target/target.py
- tests/python/unittest/test_device.py
- tests/python/unittest/test_target_target.py
- Target auto detection: `Target.auto_detect()`.
- Target created from device: `Target.from_device("cuda")` or `Target.from_device(tvm.cuda())`
- create device from str: `tvm.device("cuda:0")` or tvm.device("cuda", 0)
> [Target][Device] Auto detect target and create device from str in torch style

- include/tvm/runtime/container/variant.h
- include/tvm/runtime/packed_func.h
- src/support/ffi_testing.cc
- tests/cpp/container_test.cc
- tests/python/unittest/test_ir_container.py
This commit introduces a new container, `Variant`, which is analogous to the `std::variant` introduced in C++17, the `enum` in Rust, or a tagged union in C.  The `Variant` class is templated over the types that it may contain (e.g. `Variant<String, Expr>`), where each type is a distinct option that can be stored within the container.
`Variant` is implemented as a subclass of `ObjectRef` with no additional data members, similar to the implementation of `Optional<T>`.  It can be constructed from any of its contained types, and the contents can be inspected using the usual `my_object.as<T>()` and `Downcast<T>(my_object)` methods.  This is intended to allow for drop-in replacement of `ObjectRef` with `Variant<Type1, Type2, ...>` in places that previously used a common base class.
To ensure …
> [IR] Implemented Variant<...> container

- include/tvm/relax/dataflow_pattern.h
- python/tvm/relax/dpl/pattern.py
- src/relax/ir/dataflow_matcher.cc
- src/relax/ir/dataflow_pattern.cc
- tests/python/relax/test_dataflow_pattern.py
Prior to this commit, a shape could be explicitly specified using the `ShapePattern`, but could not be specified relative to the shape of another expression.  As a result, patterns with restricted shapes became very difficult to
This commit implements `SameShapeConstraint`, which can be applied between any patterns that participate in the match.  For example, matching against `R.add(lhs,rhs)` where `lhs` and `rhs` have the same non-broadcasted shape.  Because these constraints operate between patterns that do not necessarily share a consumer/producer relationship, they could not previously be expressed using the existing `PairCons` functionality, and were instead implemented in terms of a new `DFConstraint` base class.
> [Unity] Implemented SameShapeConstraint for dataflow pattern matches

- src/runtime/relax_vm/ndarray_cache_support.cc
This commits adds `__STDC_FORMAT_MACROS` when including picojson in C++. This should fix a recent build issue as below:
```
In file included from src/runtime/relax_vm/ndarray_cache_support.cc:40:
3rdparty/picojson/picojson.h: In member function 'std::string picojson::value::to_str() const':
3rdparty/picojson/picojson.h:494:37: error: expected ')' before 'PRId64'
494 |       SNPRINTF(buf, sizeof(buf), "%" PRId64, u_.int64_);
|               ~                     ^~~~~~~
|                                     )
3rdparty/picojson/picojson.h:81:1: note: 'PRId64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
80 | #include <errno.h>
+++ |+#include <cinttypes>
81 | #include <inttypes.h>
```
> [Relax][VM] Add additional flags for picojson

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
As part of https://github.com/apache/tvm/issues/15148, this PR adds support for floor_mod.
> [TFLite][Frontend] Support quantized floor_mod

- include/tvm/runtime/disco/session.h
- python/tvm/exec/disco_worker.py
- python/tvm/runtime/disco/__init__.py
- python/tvm/runtime/disco/process_pool.py
- python/tvm/runtime/disco/session.py
- python/tvm/testing/__init__.py
- python/tvm/testing/disco.py
- src/runtime/disco/bcast_session.cc
- src/runtime/disco/bcast_session.h
- src/runtime/disco/builtin.cc
- src/runtime/disco/nccl/nccl.cc
- src/runtime/disco/nccl/utils.h
- src/runtime/disco/process_session.cc
- src/runtime/disco/protocol.h
- src/runtime/disco/session.cc
- src/runtime/disco/threaded_session.cc
- src/runtime/disco/worker.cc
- src/runtime/disco/worker.h
- src/support/process_id.h
- tests/python/disco/test_nccl.py
- tests/python/disco/test_session.py
This PR introduces `ProcessSession`, a new session implementation based
on multi-processing.
`ProcessSession` shares exactly the same communication protocol with
`ThreadedSession`, but all workers except for worker 0 are launched in a
separate process than thread. Workers communicate with the controller
via pipe provided by the OS, rather than SPSC message queue between
threads.
In our implementation, Python's `subproces.popen` is used to create
subprocesses, and the Python executable, or more specifically,
`sys.executable` calls into `tvm.exec.disco_worker` as the entrypoint.
Besides the launching logic that is only executed once in the very
beginning, the rest of the implementation resides in a C++-only
environment, including reads/writes to pipe file descriptors,
serialization and …
> [Disco] Pipe-based Multi-processing Session

- include/tvm/target/target_kind.h
- python/tvm/relay/qnn/op/legalizations.py
- python/tvm/relay/qnn/op/qnn.py
- python/tvm/target/codegen.py
- python/tvm/target/x86.py
- python/tvm/topi/x86/batch_matmul.py
- python/tvm/topi/x86/conv2d_int8.py
- python/tvm/topi/x86/dense.py
- python/tvm/topi/x86/dense_alter_op.py
- python/tvm/topi/x86/tensor_intrin.py
- src/meta_schedule/space_generator/space_generator.cc
- src/relay/qnn/op/requantize.cc
- src/relay/qnn/op/requantize_config.h
- src/target/llvm/llvm_module.cc
- tests/python/target/test_x86_features.py
Hi folks,
This PR leverage LLVM itself for CPU features lookup, replacing hard-coded lists.
In order to keep maintainability with X86 families & features we can rely on LLVM.
---
Changes:
* Introduce a single ```target_has_feature(XXX)``` replacing all ```target_has_XXX()```
* PY+FFI: expose new ```llvm_x86_get_archlist```, ```llvm_x86_get_features``` & ```llvm_x86_has_feature```
* PY:  expose new ```target_has_feature``` wrapper to ```_ffi.llvm_x86_has_feature```
---
There is a test unit for a comprehensive check with the old behaviour.
For better reliability, this way of feature checking can be implemented for other arches.
Thanks,
~Cristian.
Cc: @elvin-n , @vvchernov , @echuraev , @vinx13 , @jcf94 , @masahi
> [Target][TOPI] Use LLVM for x86 CPU feature lookup

- tests/python/unittest/test_allreduce.py
- tests/python/unittest/test_allreduce_cuda.py
As a first step to addressing the Metal codegen errors that required the reversion in https://github.com/apache/tvm/pull/15725, parametrizing the unit tests for `allreduce`.  While these tests are parametrized with `@tvm.testing.parametrize_targets("cuda", "metal")`, the automatic `tvm.testing.requires_metal` marker inserted for the metal parametrization will cause them to be skipped if the metal runtime is unavailable, which includes the current CI.
> [UnitTest][Metal] Parametrize allreduce GPU tests

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
Prior to this commit, `CanonicalizeBindings` would identify trivial bindings of `var_y = var_x` and replace subsequent usage of `var_y` with `var_x`, but bindings of the form `tuple_var = (var_x,); var_y = var_x[0]` would not be canonicalized.
This commit updates the `CanonicalizeBindings` pass to identify trivial bindings that occur across a `TupleGetItem` expression, handling them as if they were direct assignments.
> [Unity] Unwrap tuples during CanonicalizeBindings

- python/tvm/relay/transform/fake_quantization_to_integer.py
- python/tvm/topi/hexagon/qnn/avg_pool2d.py
- tests/python/contrib/test_hexagon/infrastructure.py
- tests/python/contrib/test_hexagon/test_pass_fq2i_avg_pool2d.py
- tests/python/contrib/test_hexagon/test_relay_simplify_conv_pat.py
We see an accuracy issue when FQ2I is enabled for the avg_pool2d op in the deeplab_v3 QAT model. The error seems to be happening because the underlying graph has the output of the avg_pool mapped directly to the conv2d without a quantize-dequantize layer in between.
Graph of interest
```mermaid
graph TD;
W(dequantize: A_scale, A_zero_point) --> Conv2d;
A(dequantize: B_scale, B_zero_point) --> avg_pool2d;
avg_pool2d --> Conv2d;
Conv2d --> Output(quantize: C_scale, C_zero_point);
```
Quantization parameters after Fq2i pass:
qnn.avg_pool2d	(Bs, Bz, Cs, Cz)
qnn.conv2d	        (Cs, Cz, As, Az)
qnn.requantize	(Cs*As, 0, Cs, Cz)
Proposed fix for quantization parameters:
qnn.avg_pool2d	(Bs, Bz, Bs, Bz)
qnn.conv2d	        (Bs, Bz, As, Az)
qnn.requantize	(Cs*As, 0, Cs, Cz)
where quantized …
> [Hexagon] F2qi avgpool bug fix

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
The original implementation of Flip in PyTorch converter mistaken the type of attribute `axis` in the Flip operator as an integer. Thus, It only parses the first element of the `axis` and will give a wrong calculation result when the length of `axis` is more than one.  According to the PyTorch documentation [here](https://pytorch.org/docs/stable/generated/torch.flip.html), the type of `axis` is a list or tuple.
This PR corrected the incorrect implementation of the algorithm of `torch.flip` converter and added a regression test.
cc @echuraev @Hzfengsy @MasterJH5574
> [Relay][Bugfix] fix the wrong calculate logic of operator flip in PyTorch frontend

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
The PR https://github.com/apache/tvm/pull/15730 introduced the outer_reduction for adreno gemv. This PR fixes the length issue when applying on dynamic workloads.
cc @spectrometerHBH
> [Unity][DLight] Fix outer_reduction for dynamic shape workloads

- python/tvm/tir/op.py
- tests/python/unittest/test_tir_ops.py
The `tir.op.comm_reducer` utility provides two distinct APIs, either reducing along a tensor axis or reducing along a list of arguments.
Prior to this commit, when reducing along a list of arguments, the 4th argument was silently dropped.  For example, `tvm.tir.max(1,2,3,4,3,2,1)` would return `3`.
> [TIR] Do not drop 4th argument to tir.max

- src/arith/iter_affine_map.cc
- src/arith/rewrite_simplify.cc
- tests/python/unittest/test_arith_iter_affine_map.py
- tests/python/unittest/test_arith_rewrite_simplify.py
- tests/python/unittest/test_tir_transform_compact_buffer_region.py
Previously, the optimization from `floordiv(floormod(..))` to `floormod(floordiv(..))` do not check the divisibility. Which may create wrong  iteration form. The change add a default handling and let it just fail in followup validity checks.
For example, ` (x % 255) // 16` should not get transformed to `(x // 16) % 15`. The change make it as `(x % 255) // 16 % ceildiv(255, 16)`.
It currently could not pass the surjective check though the mapping actually is surjective. We could improve it in the future.
> [Arith] Fix detect non-divisible iteration form like (x % 255) // 16

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
As per https://github.com/apache/tvm/issues/15148, adding support for div.
> [TFLite][Frontend] Support quantized div

- include/tvm/relax/expr.h
- src/relax/backend/vm/vm_shape_lower.cc
- src/relax/transform/bundle_model_params.cc
- src/relax/transform/lift_transform_params.cc
- src/relax/transform/rewrite_cuda_graph.cc
- tests/python/relax/test_backend_transform_shape_lower.py
> [Unity] Skip shape checking on transformed params

- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_tir.py
This PR fixes a bug of the FuseTIR pass in Relax.
Prior to this fix, when an IRModule has an ExternFunc in its function table, the ExternFunc will be removed by the pass and does not show up in the output IRModule.
This PR fixes this issue by forcing keeping the ExternFunc.
> [Unity][BugFix] FuseTIR not keeping ExternFunc in IRModule

- src/target/llvm/codegen_amdgpu.cc
- src/target/llvm/intrin_rule_rocm.cc
This PR fixes a ROCm codegen error that the dtype of `@llvm.amdgcn.workgroup.id*` and `@llvm.amdgcn.workitem.id.*` are always i32 when generating LLVM IR, even if it's marked as T.int64 in TIR.
An example that triggers this issue:
```python
@T.prim_func
def encode_kernel(A: T.handle("float16", "global"), max_abs_value: T.handle("float16", "global"), v: T.int64):
T.func_attr({"calling_conv": 2, "target": T.target({"host": {"keys": ["cpu"], "kind": "llvm", "tag": ""}, "keys": ["rocm", "gpu"], "kind": "rocm", "max_num_threads": 256, "max_shared_memory_per_block": 65536, "max_threads_per_block": 1024, "mcpu": "gfx1100", "mtriple": "amdgcn-amd-amdhsa-hcc", "tag": "", "thread_warp_size": 32}), "tir.is_global_func": T.bool(True), "tir.kernel_launch_params": ["blockIdx.x", "threadIdx.x"], …
```
> [Codegen][ROCm] Mismatched Dtype of Workgroup/Workitem

- src/support/pipe.h
Our cross-platform pipe support is reported to be broken on Windows. See also: https://github.com/mlc-ai/mlc-llm/issues/930.
> [Hotfix] Fix Windows Pipe

- src/relax/transform/bundle_model_params.cc
- tests/python/relax/test_transform_bundle_model_params.py
This very minor change keeps the `num_input` attribute attached to functions after applying `BundleModelParams`. This is very useful in combination with #15736, which uses `num_input` to perform runtime optimization.
> [Unity] Keep num_input attribute after ModelBundleParams

- python/tvm/relax/transform/lazy_transform_params.py
- tests/python/relax/test_transform_lazy_transform_params.py
The function produced by `LazyTransformParams` has only side effects, through the `"get_item"` and `"set_item"` PackedFunc calls, and should be marked as impure.
> [Unity] Mark result of LazyTransformParams as impure function

- src/runtime/hexagon/rpc/hexagon/rpc_server.cc
Returning "false" from `ProcessOnePacket` is not an error.
> [Hexagon] Properly handle RPC server shutdown

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
Support GREATER_EQUAL quantization operation as part of #15148
> [TFLite][Frontend] Support quantized GREATER_EQUAL

- tests/python/relax/test_transform_lazy_transform_params.py
Mark the rest of test cases as impure. This is a follow up of #15697 
cc @Lunderberg
> [Unity] Update test cases of LazyTransformParams as impure

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
Support LESS_EQUAL quantization operation as part of #15148
> [TFLite][Frontend] Support quantized LESS_EQUAL

- tests/python/frontend/tflite/test_forward.py
This unit test is failing on unrelated PRs (e.g. https://github.com/apache/tvm/pull/15762 at [CI link](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-arm/detail/PR-15762/4/tests)). Local testing resulted in a failed test 44 times out of 100 iterations.
> [SkipCI][Hotfix][TFLite] Disable test of quantized floor mod

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_frontend_nn_op.py
It turns out that using datatypes besides `float32` when calculating timestep embeddings leads to substantial errors. The diffusers library just hard casts to float32 to avoid this and we should too.
> [Unity][Frontend][NN] Switch to always using fp32 for timestep embedding calculation

- src/runtime/opencl/opencl_common.h
- src/runtime/opencl/opencl_device_api.cc
- src/runtime/opencl/opencl_module.cc
- src/runtime/opencl/opencl_module.h
After adding OpenCL wrapper, it is possible to build TVM with OpenCL support also on the host which doesn't have OpenCL libraries. But if you want to compile OpenCL module for a remote device on such host machine then you will see an error that OpenCL lib cannot be open.
To avoid such problem, we need to call OpenCL functions only in runtime. So function for initializing OpenCL workspace was removed from OpenCLModuleNode. And a new function `IsProgramCreated` was added. The last function is necessary to prepare vectors with OpenCL programs, associated with OpenCL devices. Previously it was done during OpenCLModule initialization. So, now we create such vectors only in runtime after getting list of available OpenCL devices.
> [OpenCL] Don't initialize OpenCL runtime on host

- python/tvm/driver/tvmc/compiler.py
- tests/python/driver/tvmc/test_compiler.py
Now we can dump the imported modules source too like device code.
> [TVMC] enable dumping imported modules too

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul_tensorize.py
Some blocks have failed to be inlined to the producer cache-write stage. This could be due to another producer block that has not been scheduled. This PR fixes this by using the same function in matmul rule.
> [Unity][Dlight] Fix inline consumer in matmul tensorize rule

- src/tir/ir/stmt_functor.cc
- tests/python/unittest/test_tir_lower_match_buffer.py
- tests/python/unittest/test_tir_transform_unify_thread_binding.py
This reverts commit 34637d7ee38f2636b1948548a39c15838d7a8db6.
It is better not visiting fields of buffer when visiting `MatchBufferRegion` since it's more common that the buffer is not mutated in `StmtMutator` (it can be left to the derived passes to handle case by case). It is also consistent with visitor/mutator for `BufferLoad` and `BufferStore` that do not visit buffer fields.
This fixes some broken tests in software pipelining where strides of some buffers in `MatchBufferRegion` are unintentionally mutated in-place.
cc @yzh119 @tqchen @junrushao
> Revert "[TensorIR][Visitor] Visit buffer members in `match_buffer`'s in block visitor functions (#15153)

- python/tvm/runtime/script_printer.py
- python/tvm/tir/schedule/schedule.py
- python/tvm/tir/schedule/trace.py
Prior to this commit, the default behavior of the `black_format` argument in TVMScript printing has changed back and forth, based on conflicting user preferences.  This commit allows the default to be specified by each using using the `TVM_BLACK_FORMAT` environment variable.  If unspecified in a `obj.show()` method call, this environment variable is used to determine the default.
> [TVMScript] Use environment variable TVM_BLACK_FORMAT for .show()

- src/relax/analysis/analysis.cc
- src/relax/analysis/struct_info_analysis.cc
- src/relax/analysis/udchain.cc
- src/relax/analysis/well_formed.cc
- src/relax/ir/binding_rewrite.cc
- src/relax/ir/block_builder.cc
- src/relax/ir/dataflow_matcher.cc
- src/relax/ir/expr_functor.cc
- src/relax/transform/canonicalize_bindings.cc
- src/relax/transform/convert_layout.cc
- src/relax/transform/fold_constant.cc
- src/relax/transform/gradient.cc
- src/relax/transform/lift_transform_params.cc
- src/relax/transform/to_mixed_precision.cc
- src/relax/transform/utils.h
Prior to this commit, writing a subclass of `relax::ExprVisitor` or `relax::ExprMutator` required separate overrides for visiting a `relax::DataflowVar` and a `relax::Var`.  In the majority of cases, these two types should be treated identically, and failure to handle a `DataflowVar` equivalently would be a bug.
This commit updates the `relax::ExprVisitor` and `relax::ExprMutator` base classes to visit `DataflowVar` by delegate to the visitor of `relax::Var`.  As a result, any derived class that overrides the `relax::Var` visitor will also update the behavior for `relax::DataflowVar`.  A pass that requires different behavior for `relax::Var` and `relax::DataflowVar` can still explicitly override both methods in order to provide different behavior.
> [Unity] Delegate DataflowVar visitor to Var by default

- python/tvm/script/ir_builder/relax/ir.py
- python/tvm/script/parser/ir/parser.py
- python/tvm/script/parser/relax/entry.py
- src/script/printer/ir/ir.cc
- src/script/printer/relax/binding.cc
- src/script/printer/relax/call.cc
- src/script/printer/relax/function.cc
- src/script/printer/relax/struct_info.cc
- tests/python/relax/test_tvmscript_parser.py
- tests/python/relax/test_tvmscript_printer_relax.py
Prior to this commit, any `ExternFunc` usage in a relax function would print the string name of the function on its own line, omitting any variable definition, and later use of the variable would occur without a definition.  This commit updates the printing of `R.ExternFunc` to appear as a normal relax variable.
> [Unity][TVMScript] Produce var = R.ExternFunc("") statements

- include/tvm/relax/analysis.h
- src/relax/analysis/udchain.cc
- src/relax/ir/binding_rewrite.cc
- src/relax/ir/dataflow_matcher.cc
- src/relax/transform/dead_code_elimination.cc
- src/relax/transform/fold_constant.cc
- src/relax/transform/gradient.cc
- tests/python/relax/test_analysis.py
- tests/python/relax/test_transform_fold_constant.py
- tests/python/relax/test_tuning_api.py
Prior to this commit, the `RemoveAllUnused` utility could only apply to `relax::Function` instances.  This commit extends the allowed usage to apply to any `relax::Expr` that contains variable bindings, such as `relax::SeqExpr`.
> [Unity] Extend RemoveAllUnused to support relax::Expr

- python/tvm/te/operation.py
- src/te/operation/create_primfunc.cc
- src/te/operation/create_primfunc.h
- tests/python/unittest/test_te_create_primfunc.py
- Allow `CreatePrimFunc` args to be a mixture of `te::Tensor` and `tir::Var`.
- Integrate `CreatePrimFunc` and `CreateRelaxPrimFunc` into one function.
```python
idx = te.var("idx", dtype="int64")
m = te.var("m", dtype="int64")
n = te.var("n", dtype="int64")
tensor = te.placeholder((m, n), name="tensor")
slice0 = te.compute((idx, n), lambda i, j: tensor[i, j], name="slice")
te.create_prim_func([tensor, idx, slice])
```
cc: @junrushao @Hzfengsy @yongwww
> [TE] Support using tir::Var as CreatePrimFunc args

- src/runtime/disco/nccl/nccl.cc
running on default stream and synchronizing with it is significantly faster on amd gpu than running on other stream and synchronizing that stream, so we switch to using default stream in init_ccl.
I also tested on nvidia gpu and confirmed that there's no perf regression.
> [Unity][Disco] Use default stream in disco

- docker/install/ubuntu_install_oneflow.sh
Installing oneflow from the current link (https://release.oneflow.info) seems to be broken as reported in #15754, which is impacting other unrelated changes in CI. This commit attempts to fix the install by using a version from PyPi.
> [Docker] Install oneflow from PyPi

- src/relax/analysis/layout_transformation.cc
A `PrimFunc` may contain transformations that are not affine, or that are not recognizable as being affine.  Prior to this commit, this produced a `LOG(WARNING)` stating that this was an error in the index analysis.  Because this is the expected behavior for these functions, this commit updates the message to instead write to `DLOG(INFO)`.
The other uses of `LOG(WARNING)` inside `layout_transformation.cc` are kept as-is, as they relate to limitations of the analysis, rather than being a statement about the analyzed `PrimFunc`.
> [Unity][Analysis] Change warning to info for non-affine transform

- src/relax/transform/eliminate_common_subexpr.cc
- src/relax/transform/utils.h
Prior to this commit, the `EliminateCommonSubexpr` utility could only apply to `relax::Function` instances.  This commit extends the allowed usage to apply to any `relax::Expr` that contains variable bindings. This is only included as an internal utility within the C++ implementation, and is not currently exposed for external use.
> [Unity] Extend EliminateCommonSubexpr to operate on relax::Expr

- python/tvm/relax/transform/legalize_ops/linear_algebra.py
- tests/python/relax/test_transform_legalize_ops.py
Prior to this commit, if `R.matmul` has arguments with an unknown datatype, it would produce an error from within the `R.call_te` implementation of `BlockBuilder.call_te`, stating `TVMError: cannot make const for type handle`.  While true, this is not the most easily interpreted error message.
This error message occurs due to the use of an unknown data type in Relax as a concrete data type in TE/TIR.  While Relax supports unknown datatypes, TIR does not.  When the Relax representation of an unknown datatype, `DataType::Void()`, is passed into TIR, this is interpreted as an opaque handle, which cannot have a scalar constant produced for it.
This commit validates the types being used in Relax, prior to generating the legalized implementation of `R.matmul`.  By catching the error earlier, …
> [Unity] Dtype check in legalization of R.matmul

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/remove_redundant_reshape.py
- tests/python/relax/test_remove_redundant_reshape.py
In Mobilenet float32, we see this sequence of ops:
%179 = squeeze(%178, axis=[2, 3]) /* ty=Tensor[(1, 1001), float16] span=MobilenetEdgeTPU/Logits/Squeeze:0:0 /;
%180 = reshape(%179, newshape=[-1, 1001]) / ty=Tensor[(1, 1001), float16] span=MobilenetEdgeTPU/Predictions/
Reshape:0:0 */;
which later gets transformed to
lv171 = R.call_tir(cls.primfunc_hmx_conv2d26_add20, (lv169, metadata["relax.expr.Constant"][116], metadata["relax.expr.Constant"][117]), out_sinfo=R.Tensor((1, 1001, 1, 1), dtype="float16"))
lv172: R.Tensor((1, 1001), dtype="float16") = R.reshape(lv171, R.shape([1, 1001]))
lv173: R.Tensor((1, 1001), dtype="float16") = R.reshape(lv172, R.shape([1, 1001]))
We can eliminate the redundant reshape.
lv171 = R.call_tir(cls.primfunc_hmx_conv2d26_add20, (lv169, …
> [UNITY][Pass] Remove redundant reshape

- python/tvm/script/parser/core/parser.py
Prior to this commit, exceptions raised during the parsing of TVMScript would be caught and replaced with a new exception.  While this does allow the TVMScript location of the error to be included in the exception, it also removes the stack trace of the original error. This commit updates the `Parser.report_error` function to provide the original stack trace alongside the updated exception object.
> [TVMScript] Preserve traceback across TVMScript parsing

- python/tvm/contrib/cutlass/attention_operation.py
- python/tvm/contrib/cutlass/build.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
- python/tvm/relax/backend/contrib/cutlass.py
- python/tvm/relax/backend/patterns.py
- src/relax/op/nn/attention.cc
- tests/python/relax/test_codegen_cutlass.py
MQA, as used by llama 2 70B and codellama 34B, is a common way to reduce runtime memory bandwidth for big LLMs. So far we haven't been taking advantage of this optimization: We do explicit `repeat` of KV tensors (https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/relax_model/llama.py#L384-L385) and use the regular attention, which defeats the purpose of MQA.
While CUTLASS fMHA doesn't support MQA (where `num_q_head != num_kv_head`), flash attention does support it. So I added a new option to `partition_for_cutlass` to enable pattern matching the `repeat` op during attention rewriting: When we detect an attention pattern where KV tensors are first expanded by `repeat`, we recognize it as MQA and dispatch it to flash attention. 
For now this feature is opt-in, since it would force using …
> [Unity][BYOC] Support offloading multi-query attention by Flash Attention

- apps/howto_deploy/prepare_test_libs.py
Fix bug when using `apps/howto_deploy/run_example.sh`, it will cause `core dumped`
After fixed, all test pass.
Add runtime for `tvm.build`
> [BugFix][CPP] Fix cpp deploy bug

- docs/how_to/deploy/adreno.rst
- tests/scripts/setup-adreno-env.sh
- tests/scripts/task_config_build_adreno.sh
NCHW is mandatory layout for CLML offload. Updated the docs. CI scripts will keep OpenCL enbaled as fallback always. Enable configurable device bind ports. Helps in multi user environments.
> [ADRENO] Minor changes for Adreno docs and help scripts

- python/tvm/relax/transform/transform.py
- python/tvm/relax/vm_build.py
- src/relax/transform/kill_after_last_use.cc
- src/relax/transform/utils.h
- tests/python/relax/test_kill_after_last_use.py
Prior to this commit, intermediate objects produced while executing a Relax function would persist until the end of the Relax function. While re-use of static allocations is handled by the `StaticPlanBlockMemory` transform, re-use of dynamic allocations is handled by the `relax_vm::PooledAllocator`.  For large Relax functions representing end-to-end model execution, releasing memory from the VM registers to the `relax_vm::PooledAllocator` at the end of the function call may be insufficient.
This commit introduces a new pass, `relax.transform.KillAfterLastUse`, which identifies the last usage of each Relax variable and inserts a `relax.memory.kill_tensor`, `relax.memory.kill_storage`, or `relax.vm.kill_object` call depending on the object type.  This insertion is suppressed if a Relax …
> [Unity] Implement relax.transform.KillAfterLastUse

- tests/python/frontend/keras/test_forward.py
- tests/python/frontend/oneflow/test_forward.py
Handle unnecessary pylint errors from these frontends
> [FRONTEND] Fix unnecessary pylint errors

- apps/cpp_rtvm/README.md
- apps/cpp_rtvm/main.cc
- apps/cpp_rtvm/tvm_runner.cc
- apps/cpp_rtvm/tvm_runner.h
Few fixes and enhancements that affects model loading times New options to measure performance.
> [CLI TOOLS][RTVM] Improve rtvm tool with new options to measure native performance

- python/tvm/relay/frontend/keras.py
- tests/python/frontend/keras/test_forward.py
Two similar bugs with the issue: https://github.com/apache/tvm/issues/15176
For the convert function of GRU and SimpleRNN in the Keras frontend, they overlook the parsing for `go_backwards` attribute.
Thus, they can lead to wrong inference results. 
This PR fixed them and added two corresponding regression tests.
cc @echuraev @Hzfengsy @merrymercy
> [Relay][Keras][Bugfix] fix the converters of GRU and SimpleRNN about the go_backwards attribute

- python/tvm/relax/transform/transform.py
- python/tvm/relax/vm_build.py
- src/relax/backend/vm/vm_builtin_lower.cc
- src/relax/transform/lower_alloc_tensor.cc
- tests/python/relax/test_lower_alloc_tensor.py
- tests/python/relax/test_transform.py
- tests/python/relax/test_transform_static_plan_block_memory.py
- tests/python/relax/test_vm_builtin_lower.py
The `StaticPlanBlockMemory` transform is provided a module that expresses all allocations with `R.builtin.alloc_tensor`, and produces a module that uses `R.memory.alloc_storage` and
`R.memory.alloc_tensor` to express static allocations, while dynamic allocations continue to use `R.builtin.alloc_tensor`.
Prior to this commit, this mixed output was handled as part of `VMBuiltinLower`. This commit extracts the lowering of `R.builtin.alloc_tensor` to a new pass, `LowerAllocTensor`.  This pass runs after `StaticPlanBlockMemory`, and replaces any remaining `R.builtin.alloc_tensor` with calls to `R.memory.alloc_storage` and `R.memory.alloc_tensor`.
> [Unity] Implement LowerAllocTensor to remove R.builtin.alloc_tensor

- tests/python/unittest/test_tir_schedule_rfactor.py
This PR fixes the failed 0-rank rfactor test of TIR scheduling.
The reason of the failure is dtype mismatch. To be specific, when we declare a 0-rank buffer in TVM Script using `T.Buffer(shape=())`, the buffer's `elem_offset` field will be set to `T.int64(0)`, since we are unable to infer a dtype from the shape (which is 0-rank), and therefore the dtype falls back to int64.
So in this case, the declared 0-rank buffer before rfactor has `T.int64(0)` as `elem_offset`. Because the rfactor buffer is created from this buffer, the rfactor buffer also has `T.int64(0)` as `elem_offset`.
On the other hand, the rfactor buffer has shape `(128,)` which is not empty. So the expected buffer written in TVMScript has `T.int32(0)` as its `elem_offset`. And this causes the mismatch.
After some thinking, I …
> [Unity][TIR][Unittest] Fix failed 0-rank rfactor test

- python/tvm/relax/analysis/__init__.py
- python/tvm/relax/distributed/transform/__init__.py
- python/tvm/relax/op/__init__.py
- python/tvm/relax/op/builtin/__init__.py
- python/tvm/relax/op/ccl/__init__.py
- python/tvm/relax/op/distributed/__init__.py
- python/tvm/relax/op/grad/__init__.py
- python/tvm/relax/op/image/__init__.py
- python/tvm/relax/op/memory/__init__.py
- python/tvm/relax/op/nn/__init__.py
- python/tvm/relax/op/vm/__init__.py
- python/tvm/relax/transform/__init__.py
- python/tvm/script/ir_builder/relax/__init__.py
Wildcard importing is not recommended in Python projects: https://docs.python.org/3/tutorial/modules.html#importing-from-a-package
I acknowledge that disabling it will bring extra effort to adding new operators, analysis and transforms. But it will make the code clear, also benefit the API reference doc.
cc @junrushao @tqchen
> [Unity] Avoid Using Wildcard Imports

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
Fix behaviors for importing torch.cat/concat
Now we can import Stable Diffusion XL and Real-ESRGAN more smoothly
Before fixing, we only support **torch.cat((x, y), dim=n_dim)**
Add support for importing:
1. **torch.cat((x, y))**        with defualt dim=0
2. **torch.cat((x, y), n_dim)**      when user doesn't explicitly state dim=
3. **torch.concat**       an alias of torch.cat
> [Unity][Relax]fix behaviors for importing torch.cat/concat

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
Prior to this commit, the `relax.transform.CanonicalizeBindings` transform would detect trivial bindings `var_y = var_x`, and replace later usage of `var_y` with `var_x`.  However, the trivial binding `var_y = var_x` would be left in the canonicalized function.
This commit updates the `CanonicalizeBindings` transform to remove trivial bindings.  This is not intended as a full dead-code elimination, as that is better handled as a separate pass, but is instead intended to avoid introduction of dead code during canonicalization.
> [Unity] Avoid trivial var-to-var bindings in CanonicalizeBindings

- src/relax/transform/kill_after_last_use.cc
- tests/python/relax/test_kill_after_last_use.py
The `KillAfterLastUse` pass that was implemented in https://github.com/apache/tvm/pull/15810 checked for trivial re-bindings in `VarBinding` nodes, but not in `MatchCast` nodes.  As a result, `CodeGenVM`'s de-duplication of registers resulted in the object being killed prematurely.
```python
y = R.match_cast(x, R.Tensor(...)) # Trivial rebinding here.
R.memory.kill_tensor(x)  # Kill x after last usage.
_ = R.ExternFunc("set_item")(y) # Use of the cleared register through y.
```
> [Unity][Bugfix] Check for trivial re-bindings in MatchCast nodes

- python/tvm/runtime/disco/process_pool.py
- src/runtime/disco/loader.cc
- src/runtime/relax_vm/ndarray_cache_support.cc
- src/runtime/relax_vm/ndarray_cache_support.h
- tests/python/disco/test_loader.py
In our previous implementation, parameter sharding relies on pre-quantization weight processing, meaning each set of quantized weights corresponds strictly to a hardcoded constant `num_shards`, and re-quantization is strictly required upon each change of #GPUs, e.g. from 4-GPU to 8-GPU setting. This PR makes it possible to move parameter sharding to post-quantization loading-time. During loading, we iterate over all parameters and apply the sharding operation based on the provided sharding information.
To make this happen, this PR makes an enhancement to the existing `shard_info.json` to include the sharding function being used at loading time. Each parameter is attached to a list of loading-time preprocessing methods that are serially applied to it to transform this parameter to the …
> [Disco] Loading-time sharding support

- python/tvm/contrib/cutlass/build.py
- python/tvm/contrib/cutlass/rms_norm_operation.py
- tests/python/relax/test_codegen_cutlass.py
The CUTLASS RMS kernel has been using a hard-coded epsilon value of 1e-6. I learned that recent popular language models such as llama 2 have been trained with eps = 1e-5, and using a slightly different eps can cause accuracy problems for such models on some inputs (see https://github.com/mlc-ai/mlc-llm/issues/923#issuecomment-1735066112). This has been fixed by this PR.
@zxybazh @sunggg @vinx13
> [Unity][CUTLASS] Fix hardcoded epsilon parameter in RMS norm

- python/tvm/relax/transform/optimize_layout_transform.py
- tests/python/relax/test_optimize_layout_transform.py
After PR #15679 added support for padding reversal in AlterOpImpl, a new pattern is created in graphs
`transform_layout -> remove_pad -> transform_layout`
The current change is meant to handle the pattern in `OptimizeLayoutTransform` pass
> [UNITY] Handle pattern with remove_pad

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
Support POW quantization operation as part of #15148
> [TFLite][Frontend] Support quantized Pow

- tests/scripts/release/make_notes.py
> [Script] Fix miscs of make_notes.py

- python/tvm/relax/vm_build.py
- src/relax/transform/rewrite_cuda_graph.cc
- tests/python/relax/test_transform_rewrite_cuda_graph.py
Prior to this commit, the `RewriteCUDAGraph` pass would unconditionally rewrite an `IRModule`, and was conditionally included as a lowering pass for used in `relax.build`, based on the current `PassContext`.  This commit moves the check on the `PassContext` from the `relax.build` method to the `RewriteCUDAGraph` pass itself.  This allows the pass to be part of a lowering flow that is constructed once, and is later used when the `PassContext.current()` may have changed.
> [Unity] Check the PassContext within RewriteCUDAGraph transform

- docker/install/ubuntu_install_oneflow.sh
- python/tvm/relay/frontend/oneflow.py
The PR #15819 installed oneflow from PyPi in an attempt to unblock CI failing on the gpu docker image build. However, it seems to be a placeholder package. This PR upgrades the version of oneflow to v0.8.0 in a second attempt to unblock CI.
> [Docker] Upgrade oneflow to v0.8.0

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
As the ONNX documentation description [here](https://onnx.ai/onnx/operators/onnx__ConvTranspose.html#:~:text=strides%20%2D%20INTS%20%3A%20Stride%20along%20each%20spatial%20axis.%20If%20not%20present%2C%20the%20stride%20defaults%20to%201%20along%20each%20spatial%20axis.)
The parameter `strides` in ConvTranspose is an optional attribute using '1' as default.
This PR fixed it and added a corresponding regression test.
> [Relay][Bugfix] Fix conv transpose with default strides in ONNX frontend

- src/runtime/disco/nccl/nccl.cc
This PR fixed a bug introduced in #15827 since which the cudagraph's stream is discarded.
> [Bugfix] Fix Disco-CUDAGraph Integration

- CMakeLists.txt
This commit adds `-lrt` to TVM runtime when linked against static NCCL. The static NCCL depends on symbol `shm_unlink` which comes from librt.
> [Disco] Add -lrt to TVM runtime for NCCL

- include/tvm/relax/transform.h
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/op/linear_algebra.py
- python/tvm/relax/struct_info.py
- python/tvm/relax/training/utils.py
- python/tvm/relax/transform/transform.py
- python/tvm/runtime/disco/process_pool.py
- src/relax/op/tensor/linear_algebra.h
- src/relax/training/utils.h
- src/relax/transform/fuse_ops.cc
- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_fold_constant.py
Removed instances of accidentally repeated words from comments. There are cases where duplicated words appear legitimately, those cases remain unmodified.
> [Unity][Fix] Remove duplicated words from comments, NFC

- python/tvm/relax/op/_op_gradient.py
- python/tvm/relax/op/create.py
- python/tvm/relax/transform/legalize_ops/create.py
- src/contrib/msc/core/utils.cc
- src/relax/op/op_common.h
- src/relax/op/tensor/create.cc
- src/relax/op/tensor/create.h
- tests/python/contrib/test_msc/test_translate_relay.py
- tests/python/contrib/test_msc/test_translate_torch.py
- tests/python/relax/test_op_create.py
This mirrors the support in `topi`, which supports a `PrimExpr` as the offset of the diagonal.
> [Unity] Use PrimValue as offset in R.tril and R.triu

- ci/jenkins/docker-images.ini
- tests/python/frontend/coreml/test_forward.py
The ci-gpu is updated to make changes in #15819 reflect in CI.
cc @ashutosh-arm
> [CI] Update ci-gpu image

- src/arith/iter_affine_map.cc
- tests/python/unittest/test_arith_iter_affine_map.py
This is a follow-up of https://github.com/apache/tvm/pull/15665. It simplified the special case when `floormod(floordiv(x, lower_factor), ext) == x`. This prevent nested `IterMark` being created.
cc @wrongtest-intellif @Lunderberg @junrushao
> [Arith] Simplify the result of non-divisible floordiv

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR fixed the KeyError: 'None' in the issue #15758 
The original code assigned `gamma` variable without a conditional check for None. So I added it. Additionally, the `shape_tuple` calculation for `gamma` and `beta` is modified to use normalized_shape directly instead of normalized_shape.values.
Please review and consider merging this PR. Thank you!
@jikechao @Hzfengsy @leandron
> [Unity] [Bugfix] Fix KeyError:'None' in layer_norm implementation

- docker/install/ubuntu_install_cmsis.sh
This commit removes the SHA based checkouts for CMSIS core repo.
Consequently, this solves the problems of missing SHA archives.
CMSIS_5: release 5.9.0
CMSIS-NN: release v4.1.0
cc: @leandron @lhutton1 @NicolaLancellotti @neildhickey
> [CMSIS-NN] Move CMSIS_5 from SHA to release based upgrade

- docker/install/ubuntu2204_install_llvm.sh
This commit ensures LLVM 17 is installed alongside other versions in the `ubuntu2204_install_llvm.sh` script. It also removes versions 13 and 14 as they don't appear to be used - a general cleanup of the images that use this script.
> [Docker] Add LLVM 17 to the LLVM install script

- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_tir.py
Prior to this commit, the `relax.transform.FuseTIR` transform required that the shapes arguments passed into a `PrimFunc` be structurally equivalent to the shapes of the parameters, and that any replacement of symbolic `tir.Var` be with a symbolic `tir.Var` in the fused function.
This commit updates the `SymbolicMatcher` to instead extract a `Map<tir::Var, PrimExpr>`.  As a result, a Relax tensor with statically-known shape can be passed into a TIR PrimFunc with dynamic shape.  The resulting fused TIR function is in terms of the statically-known shape, and no longer contains the symbolic variable.
> [Unity][Transform] Allow static Relax arguments to dynamic PrimFunc

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR fixed two bugs:
1. the KeyError: 'None' in the issue #15758
2. nomalized_shape doesn't have the attribute values
The original code assigned `gamma` variable without a conditional check for None. So I added it. Additionally, the `shape_tuple` calculation for `gamma` and `beta` is modified to use `normalized_shape` directly instead of `normalized_shape.values`.
Please review and consider merging this PR. Thank you!
@jikechao @Hzfengsy @leandron
> [Unity] [Bugfix] Fix KeyError:'None' in layer_norm and correctly use the normalized_shape

- python/tvm/relay/frontend/mxnet.py
Fix the bug mentioned in issue: https://github.com/apache/tvm/issues/15890
> [Relay][Bugfix] fix axis parsing of repeat converter in the MXNet frontend

- apps/cpp_clml/scripts/clml_codegen.py
- docker/Dockerfile.ci_adreno
- tests/scripts/task_config_build_adreno.sh
Enabling google tests and clang-format version update.
> [CI][ADRENO] Few updates to Adreno docker setup

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
As the ONNX documentation description [here](https://onnx.ai/onnx/operators/onnx__MaxPool.html)
The parameter strides in MaxPool2d is an optional attribute using [1, 1] as default.
This PR fixed it and added a corresponding regression test.
> [Unity] [Bugfix] Fix MaxPool TypeError in ONNX frontend

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/fast_math.py
- tests/python/relax/test_fast_math_transform.py
This PR adds FastMathTransform pass to convert the expensive non linear functions to their fast but approximate counterparts. This pass replaces relax.nn.softmax, relax.exp, relax.erf, relax.tanh with topi.nn.fast_softmax, topi.fast_exp, topi.fast_erf, topi.fast_tanh.
> [Unity]Add FastMathTransform pass to Relax

- src/relax/transform/fuse_ops.cc
This commit adds debugging information to checks in the `FuseOps` pass.  While the existing checks indicate where an error occurred in the `FuseOps` code, this adds information on the relax expressions that caused the error.
> [Unity] Improve FuseOps error messages

- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_transform_cse.py
Prior to this commit, `relax::ExternFunc` nodes would be de-duplicated as part of the `EliminateCommonSubexpr` pass.  This commit instead ignores the `relax::ExternFunc` nodes, retaining the in-line definitions.
> [Unity] Ignore R.ExternFunc in EliminateCommonSubexpr

- conda/recipe/meta.yaml
- include/tvm/runtime/c_runtime_api.h
- python/tvm/_ffi/libinfo.py
- version.py
- web/package.json
Update version to 0.14.0 on main branch
> [release] Update version to 0.14.0 and 0.15.0.dev on main branch

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_dynamo.py
Add support: allow one dynamic tensor as torch.tensor's index
In Stable Diffusion XL:
e.g.  `output = input1 [input2.argmax(dim = -1), ]`
**Before:** we can only support int, slice, elipsis, None
**Now:** we can have one dynamic torch.tensor in index, which allows us to represent SD XL correctly. 
Behaviors **aligns with torch.tensor**:
as shown in test cases
**Future TODO:** Support other "fancy indexing" methods in torch.tensor, (e.g. multiple tensors as index) which requires some new relax ops
> [Unity][Relax] Support Dynamic Tensor as Index, torch frontend

- python/tvm/tir/schedule/schedule.py
- tests/python/relax/test_optimize_layout_transform.py
In the test file tests/python/relax/test_optimize_layout_transform.py, this **fused_mode** is unused. I think it should be **fused_mod**.
> [Unity] Fix wrong variable name in test_optimize_layout_transform

- python/tvm/tir/tensor_intrin/cuda.py
This PR updated the offset factor of cuda tensor intrinsic. Now the offset factor is always the leading dimension of the fragment size and fixed some failing test cases previous not caught by CI as they are skipped
cc @spectrometerHBH @masahi
> [TIR] Fix offset_factor in cuda tensor core intrins

- python/tvm/target/codegen.py
- python/tvm/testing/utils.py
- src/target/llvm/llvm_module.cc
- tests/python/contrib/test_amx.py
- tests/python/contrib/test_gemm_acc32_vnni.py
- tests/python/integration/test_auto_tensorize.py
- tests/python/relay/test_op_level1.py
- tests/python/relay/test_op_level10.py
- tests/python/relay/test_op_level2.py
- tests/python/target/test_llvm_features_info.py
- tests/python/unittest/test_meta_schedule_cpu_dot_product.py
This PR adds helper functions to query system info from the LLVM backend.
It  enhances TVM target information handling and extends the CI coverage.
---
* Introduces ```llvm_get_system_cpu()```, ```llvm_get_system_triple()``` and ```llvm_get_system_x86_vendor()```
* Exposes both C/FFI & PY interfaces for all the functions mentioned above with proper test cases.
* Enhances CI test utils, removes old limiting checks  related to arch/system/cpu/vendor dependencies.
```
$ cat tvm-system-info.py
#!/usr/bin/python3
import tvm
from tvm.target import codegen, Target
cpu = codegen.llvm_get_system_cpu()
triple = codegen.llvm_get_system_triple()
vendor = codegen.llvm_get_system_x86_vendor()
target = "llvm -mtriple=%s -mcpu=%s" % (triple, cpu)
print("Current system CPU: [%s], VENDOR: [%s] TRIPLE: …
```
> [Target][CI] Add LLVM functions for current system info

- python/tvm/relay/frontend/keras.py
The wrong documentation about attribute layout in relay.from_keras().
By analysis the source code [Here](https://github.com/jikechao/tvm/blob/main_abc/python/tvm/relay/frontend/keras.py#:~:text=assert%20layout%20in,NHWC%20or%20NDHWC%22), we can find that input_layout has 4 valid values (e.g, 'NWC', 'NCHW', NHWC and NDHWC"). However, in the [source code comments](https://github.com/jikechao/tvm/blob/main_abc/python/tvm/relay/frontend/keras.py#:~:text=layout%3A%20str,better%20across%20TVM.) and [official documentation](https://tvm.apache.org/docs/reference/api/python/relay/frontend.html?highlight=from_keras#tvm.relay.frontend.from_keras:~:text=layout%20(str)%20%E2%80%93%20One%20of%20%E2%80%98NCHW%E2%80%99%20or%20%E2%80%98NHWC%E2%80%99%2C%20indicates%20how%20data%20should%20be%20arranged%20in …
> [Relay] fix the conflicted documentation description

- python/tvm/script/parser/tir/parser.py
- src/script/printer/relax/function.cc
- src/script/printer/tir/function.cc
- tests/python/unittest/test_tir_transform_force_narrow_index_to_i32.py
- tests/python/unittest/test_tvmscript_printer_tir.py
Due to frequent sync with upstream, some of the testcases are broken, because of the changes in the TVMScript. This PR is to fix the broken
> [Unity] Fix TVMScript Issues in Testcases

- include/tvm/relax/analysis.h
- python/tvm/relax/analysis/__init__.py
- python/tvm/relax/analysis/analysis.py
- src/relax/analysis/struct_info_analysis.cc
- src/relax/transform/lift_transform_params.cc
- src/support/ordered_set.h
- tests/python/relax/test_analysis_struct_info_analysis.py
- tests/python/relax/test_transform_lift_transform_params.py
Prior to this PR, a symbolic variable could be provided to the `LiftTransformParams`, which could then be used to produce the transformed parameters.  For example, providing the `rank` and `world_size` of a parameter set in a multi-GPU setup.  However, these symbolic variables may be left undefined in the inference function.
This PR updates `LiftTransformParams` to track the symbolic variables that are definable by the inference function, and to propagate any symbolic variables that would otherwise be undefined.
> [Unity] Propagate extra symbolic vars through LiftTransformParams

- src/script/printer/relax/call.cc
Prior to this commit, the `tvm::script::printer::AttrPrinter` class took the attribute path as a `const ObjectPath&`.  In both places where an `AttrPrinter` is called, the temporary object `n_p->Attr("attrs")` is passed for this argument.  While binding a temporary object to a const reference can extend the lifetime of the temporary, this requires the const reference to be in the same scope as the temporary, and does not apply in this case (see [this stackoverflow post](https://stackoverflow.com/a/2784304)).  Therefore, this reference is only valid through the construction of `AttrPrinter printer`, and is invalid during its usage on the following line.
This dangling reference has caused segfaults in CI for unrelated changes ([example](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-un …
> [Unity][TVMScript] Avoid dangling reference when printing Call attrs

- src/target/llvm/codegen_amdgpu.cc
- src/target/llvm/codegen_hexagon.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_nvptx.cc
- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
This patch fixes the errors caused due to recent API change from LLVM for CodeGenOpt made in [this PR](https://github.com/llvm/llvm-project/pull/66295)
> [LLVM] Fix for llvm CodeGenOpt API change

- include/tvm/runtime/relax_vm/bytecode.h
- src/relax/backend/vm/codegen_vm.cc
This was implemented while debugging CI failures in https://github.com/apache/tvm/pull/15810, but is not otherwise related to the changes in that PR.
> [Unity][VM] Improved error message in CodeGenVM::EmitKillObject

- python/tvm/relay/backend/contrib/ethosu/legalize.py
- python/tvm/relay/op/contrib/ethosu.py
- tests/python/contrib/test_ethosu/test_codegen.py
- tests/python/contrib/test_ethosu/test_legalize.py
NPU has a restriction that weights must be constant, so the matrix multiplication operation was expressed using split, elementwise multiplication, reduce sum, concatenations operations.
cc @lhutton1, @ekalda, @leandron
> [microNPU][ETHOSU] MatMul legalization support

- python/tvm/relax/transform/remove_redundant_reshape.py
- src/relax/ir/dataflow_matcher.cc
- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_dataflow_pattern.py
- tests/python/relax/test_optimize_layout_transform.py
- tests/python/relax/test_remove_redundant_reshape.py
The `PatternRewriter` is intended to iterate until no matching patterns remain, as implemented in #14446 and #15495.  Prior to this commit, this only involved repeating the pattern match rewrite rules.  However, intermediate results produced by pattern replacement could cause the iterative pattern matching to terminate early.
* If two rewrite rules each introduce the same intermediate, there will exist two copies of that intermediate, which can prevent `only_used_by` patterns from matching.  Applying `EliminateCommonSubexpr` allows the pattern matching to continue.
* Applying a rewrite rule may result in dangling intermediates that are no longer used.  These dangling intermediates may prevent the next application of a rewrite rule that uses the `only_used_by` constraint.  Applying …
> [Unity][Transform] Canonicalize and use CSE between pattern matches

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_dynamo.py
In Stable Diffusion XL,
there are some structures, like
`a = torch.arange(b) +1`
by output the emmited relax.Var, we can support them
> [Unity][Relax]support torch.arange()+ (int) in torch frontend

- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache.py
This PR introduces the PagedKVCache object to `lm_support.cc` for the KV cache value management in batching settings.
One test file is included. Note that this file does not contain the test of attention function/kernel. That part will be uploaded and tested separately.
> [Unity] Paged KV Cache as LM Support

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR fixes a bug in the interpolate operator of the PyTorch frontend in TVM. The bug was caused by incorrectly using the `method` keyword instead of the `mode` keyword when retrieving the default value for the mode parameter. This resulted in incorrect computation of `interpolate` results.
This bug can be reproduced by the below script:
```python
import torch
from torch import fx
from torch.nn import Module
import tvm
import tvm.testing
from tvm import relax
from tvm.relax.frontend.torch import from_fx
input_data = torch.randn([1, 2, 4, 4], dtype=torch.float32)
class interpolate(Module):
def forward(self, input):
return torch.nn.functional.interpolate(input, size=None, scale_factor=2.0, mode='bilinear', align_corners=False,)
model = interpolate().float()
input_data = [input_data] …
```
> [Unity] [Bugfix] Fix bug in interpolate operator's default mode parameter in PyTorch frontend

- python/tvm/relay/backend/contrib/ethosu/legalize.py
- python/tvm/relay/backend/contrib/ethosu/op/identity.py
- python/tvm/relay/backend/contrib/ethosu/te/identity.py
- python/tvm/relay/backend/contrib/ethosu/tir/identity.py
- src/relay/op/contrib/ethosu/identity.cc
- src/relay/op/contrib/ethosu/op_attrs.h
- tests/python/contrib/test_ethosu/cascader/test_ethosu_identity_matcher.py
- tests/python/contrib/test_ethosu/test_codegen.py
Before the fix, TFL rounding was used in the requantize operation, and this led to a discrepancy in the results in some cases.
cc @lhutton1, @ekalda, @leandron
> [microNPU][ETHOSU] Fix rounding mode in requantize operation

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This pull request addresses a TypeError that occurs in the interpolate function when the scale_factor parameter is of type tuple. The current implementation fails to handle cases where scale_factor is a tuple, resulting in the error message: "TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'."
This patch allows the interpolate function to handle both scalar and tuple values for the scale_factor parameter without raising a TypeError.
And this bug can be reproduced by the following script:
```python
import torch
from torch import fx
from torch.nn import Module
import tvm
from tvm import relax
from tvm.relax.frontend.torch import from_fx
input_data = torch.randn([1, 2, 4, 4], dtype=torch.float32)
class interpolate(Module):
def forward(self, input): …
```
> [Unity] [Bugfix] Fix TypeError in interpolate caused by scale_factor as tuple

- python/tvm/relay/qnn/__init__.py
- tests/python/contrib/test_hexagon/test_qnn_op_integration.py
- tests/python/contrib/test_hexagon/test_relay_simplify_qnn_concat.py
- tests/python/relay/qnn/test_clip_legalization.py
- tests/python/relay/qnn/test_qnn_channel_stripping.py
- tests/python/relay/test_op_qnn_add.py
- tests/python/relay/test_op_qnn_batch_matmul.py
- tests/python/relay/test_op_qnn_concatenate.py
- tests/python/relay/test_op_qnn_conv2_transpose.py
- tests/python/relay/test_op_qnn_conv2d.py
- tests/python/relay/test_op_qnn_dense.py
- tests/python/relay/test_op_qnn_dequantize.py
- tests/python/relay/test_op_qnn_leaky_relu.py
- tests/python/relay/test_op_qnn_mul.py
- tests/python/relay/test_op_qnn_quantize.py
- tests/python/relay/test_op_qnn_requantize.py
- tests/python/relay/test_op_qnn_simulated_dequantize.py
- tests/python/relay/test_op_qnn_simulated_quantize.py
- tests/python/relay/test_op_qnn_subtract.py
- tests/python/relay/test_op_qnn_unary_elementwise.py
- tests/python/relay/test_pass_qnn_legalize.py
- tests/python/topi/python/test_topi_qnn.py
When we access `nn` ops in relay, we can directly access them as `relay.nn.<op>` where `<op>` can be any nn op like `conv2d`, `avg_pool2d`, etc.
When we access `qnn` ops, we need to access them as `relay.qnn.op.<op>` as they're not exposed to the `relay.qnn` module. This change tries to add that.
> [Relay] Expose qnn ops directly from relay.qnn module

- python/tvm/contrib/emcc.py
As reported by mlc-ai/mlc-llm#1081, the current 40MB memory size is likely still not enough. So we further increase it to 80MB.
> [Web] Further increase default EMCC compilation total memory size

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
When multi inputs have same symbolic shape, the function **from_onnx** will cause  
> AssertionError:` For Expr having ShapeStructInfo, emit_te now only supports ShapeExpr
This PR uses a dictionary mapping from the name of ValueInfoProto to SizeVar when parse_graph_input. ValueInfoProto with same name will map to same SizeVar.
> [Unity] Fix bug in onnx_frontend when multi inputs have same symbolic shape

- python/tvm/contrib/msc/core/codegen/codegen.py
- python/tvm/contrib/msc/core/ir/translate.py
- python/tvm/contrib/msc/framework/tensorflow/frontend/translate.py
- python/tvm/contrib/msc/framework/torch/frontend/translate.py
- src/contrib/msc/core/codegen/base_codegen.h
- src/contrib/msc/core/codegen/codegen_utils.h
- src/contrib/msc/core/codegen/py_codegen.h
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/ir/graph_builder.h
- src/contrib/msc/core/transform/set_expr_name.cc
- src/contrib/msc/core/utils.cc
- src/contrib/msc/framework/tensorflow/codegen.cc
- src/contrib/msc/framework/tensorflow/codegen.h
- src/contrib/msc/framework/tensorflow/codegen_utils.h
- src/contrib/msc/framework/tensorflow/tf_v1_opcode.h
- src/contrib/msc/framework/torch/codegen.cc
- src/contrib/msc/framework/torch/codegen.h
- src/contrib/msc/framework/torch/codegen_utils.h
- src/contrib/msc/framework/torch/torch_opcode.cc
- src/contrib/msc/framework/torch/torch_opcode.h
- src/contrib/msc/framework/tvm/codegen.cc
- src/contrib/msc/framework/tvm/codegen.h
- src/contrib/msc/framework/tvm/codegen_utils.h
- src/contrib/msc/framework/tvm/relax_opcode.h
- tests/python/contrib/test_msc/test_translate_relay.py
- tests/python/contrib/test_msc/test_translate_torch.py
The trilu test from test_translate_relay.py results in failures(e.g https://github.com/apache/tvm/pull/15783). This PR fix the bugs.
Besides, I use a customized ops map to convert torch.max(x, dim=(1,2)) to relay and test the torch codegen. Neither relay nor relax support this op (when call max with dims, the outputs behavior is different, sa https://pytorch.org/docs/stable/generated/torch.max.html). The customized ops converter is not included in this PR. I may contribute the parser part after MSC, while currently I focus on MSC. To support the special ops like torch.max with dim, I reconstruct codegen a little.
cc @Lunderberg
> [Unity][MSC][Bugfix] Trilu bugfix && special ops support

- python/tvm/contrib/xcode.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/avg_pool.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/gemm.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/max_pool.py
- python/tvm/topi/arm_cpu/mprofile/dsp/micro_kernel/tensordot.py
- src/relay/backend/contrib/cmsisnn/tir_to_runtime.cc
- src/relay/backend/contrib/example_target_hooks/tir_to_runtime.cc
- src/relay/backend/contrib/uma/tir_to_runtime.cc
- src/target/opt/build_cuda_on.cc
- src/target/source/codegen_aocl.cc
- src/target/source/codegen_c.cc
- src/target/source/codegen_c.h
- src/target/source/codegen_c_host.cc
- src/target/source/codegen_c_host.h
- src/target/source/codegen_cuda.cc
- src/target/source/codegen_cuda.h
- src/target/source/codegen_metal.cc
- src/target/source/codegen_metal.h
- src/target/source/codegen_opencl.cc
- src/target/source/codegen_vhls.cc
- src/target/source/codegen_webgpu.cc
- src/target/source/codegen_webgpu.h
- src/target/source/source_module.cc
- src/tir/op/op.cc
- tests/python/relay/aot/test_crt_forward_declarations.py
- tests/python/topi/python/test_topi_conv2d_tensordot_opts.py
- tests/python/unittest/test_target_codegen_c_host.py
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
This reverts commit [`e88d0d`](https://github.com/apache/tvm/pull/15725), which itself reverted [`9ff71f`](https://github.com/apache/tvm/pull/15103) for breakages on the metal backend.  Now that the CI contains compile-time testing of the metal codegen, the original breakage should be identifiable.
> [CodeGenC][Redo] Handle GlobalVar callee as internal function call

- src/target/llvm/llvm_instance.cc
Fix compilation warnings for clang.
---
The warnings was:
```
BUILD/tvm/src/target/llvm/llvm_instance.cc:84:81: warning: reference to stack memory associated with parameter 'Obj' returned [-Wreturn-stack-address]
84 |   friend ArrayRef<SubtargetFeatureKV>& featViewer(MCSubtargetInfo Obj) { return Obj.*Member; }
|                                                                                 ^~~
BUILD/tvm/src/target/llvm/llvm_instance.cc:833:49: 
warning: cast from 'const llvm::MCSubtargetInfo *' to 'llvm::MCSubtargetInfo *' drops const qualifier [-Wcast-qual]
833 |       llvm::featViewer(*(llvm::MCSubtargetInfo*)MCInfo);
|                                                 ^
BUILD/tvm/src/target/llvm/llvm_instance.cc:84:81: 
warning: reference to stack memory associated with parameter 'Obj' …
```
> [Minor] Fix compilation warnings for clang

- src/relax/ir/block_builder.cc
- src/relax/transform/legalize_ops.cc
- tests/python/relax/test_transform_legalize_ops.py
Prior to this commit, a `FLegalize` function needed to produce an implementation that can be used as input by `relax.transform.AnnotateTIROpPattern`, and could not lower to other relax operations.  This commit allows Relax operations to be included in the output of `FLegalize`, with the result being further legalized if required.
> [Unity] Allow FLegalize to produce Relax operations

- include/tvm/relax/attrs/nn.h
- python/tvm/contrib/cutlass/attention_operation.py
- python/tvm/contrib/cutlass/build.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
- python/tvm/relax/op/nn/__init__.py
- python/tvm/relax/op/nn/nn.py
- python/tvm/relax/transform/legalize_ops/nn.py
- src/relax/op/nn/attention.cc
- src/relax/op/nn/attention.h
- tests/python/relax/test_codegen_cutlass.py
This is necessary for Mistral support. A new attribute `window_size` has been added to `nn.attention(...)` op, and such sliding-window attention runs efficiently via flash attention. I updated our flash attention submodule to pick up the support for sliding window in https://github.com/tlc-pack/libflash_attn/pull/4.
@sunggg @yelite @cyx-6 @vinx13
> [Unity][BYOC] Add support for sliding window in attention op

- ci/jenkins/docker-images.ini
Update ci_arm image to use tag tlcpack/ci-arm:20231013-060139-71caa19f9
* Update ACL to 23.05 version
Tested at https://github.com/apache/tvm/pull/15930
cc @neildhickey @leandron @ashutosh-arm @tqchen @areusch
> Update ci_arm Docker tag

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/frontend/onnx/test_forward.py
Sets the default value 0 for the k variable, if the value has not been previously set.
This is a code patch for fixing this issue: https://github.com/apache/tvm/issues/15729
> [Fix][Unity] Fix TVMError when using relax to load model with Trilu operator

- src/runtime/relax_vm/lm_support.cc
- tests/python/relax/test_runtime_builtin.py
Part of the effort on Sliding Window Attention (SWA) https://github.com/mlc-ai/mlc-llm/issues/1003. Overriding the cache is useful when computing SWA, so we can have a more efficient cache only containing the current window keys and values. Once the cache is full we start overriding the older entries.
cc @tqchen
> [Unity][SWA] Overriding windowed cache support

- tests/scripts/ci.py
build_dir is not passed to allow custom build folders
> [CI][BUGFIX] Better to pass the build folder

- python/tvm/relax/frontend/torch/dynamo.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_dynamo.py
PyTorch 2.1.0 has switched the calling convention to real tensors (https://github.com/pytorch/pytorch/pull/99320), consequently prompting an update of the `relax_dynamo` with real tensors.
Additionally, there is a new dynamic dynamo test from  [Pytorch Docs](https://pytorch.org/docs/stable/torch.compiler_dynamic_shapes.html#dynamic-shapes)  that generates dead code in the fx graph, requiring the application of `eliminate_dead_code`.
cc @Hzfengsy @MasterJH5574
> [Unity] Update relax_dynamo

- python/tvm/relax/transform/lazy_transform_params.py
This PR fix a bug that only appears on windows on symbolic var handling. For the function parameter var with Tuple struct info, directly iterate over that variable will cause out of bound error(which is properly handled in linux but not necessarily in windows due to how iteration is handled).
Note that the var itself is not iterable and likely it relied on a sugar that var[i] dispatches to tuple_getitem and when it gets out of bound the exception get caught by the python iterator.
This PR fixes it by directly iterate over the struct info array in the annotation.
> [UNITY] Fix the symbolic var handling

- python/tvm/script/parser/core/parser.py
delete `print(parser.var_table.get())` at parsing stage.
> [TVMScript] delete print extra info at parsing

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_dataflow_pattern.py
- tests/python/relax/test_optimize_layout_transform.py
- tests/python/relax/test_remove_redundant_reshape.py
- tests/python/relax/test_transform_canonicalize_bindings.py
Prior to this commit, `relax.transform.CanonicalizeBindings` removed trivial bindings `var_y = var_x` where a `var_y: relax.DataflowVar` and `var_x: relax.Var`, but did not remove trivial bindings when `var_y: relax.Var` and `var_x: relax.DataflowVar`.  This was to avoid invalid use of a `relax.DataflowVar` outside of a dataflow block.
This commit updates `CanonicalizeBindings` to handle this type of binding as well.  To ensure that no `relax.DataflowVar` instances are used outside of a dataflow block, this is done by replacing `var_y: relax.DataflowVar` at its point of definition, instead of replacing `var_x: relax.Var` at its point of use.
This commit also canonicalizes `relax.Var` definitions to `relax.DataflowVar`, if the binding occurs within a dataflow block, and the variable is …
> [Unity][Transform] Improved canonicalization of non-dataflow Var

- include/tvm/runtime/c_runtime_api.h
- src/runtime/c_runtime_api.cc
Bugfix for builds on Windows, which has missing symbol exports.
> [Hotfix] Mark python-FFI handling with TVM_DLL

- src/relax/backend/vm/codegen_vm.cc
- src/relax/backend/vm/vm_shape_lower.cc
- src/runtime/ndarray.cc
- src/runtime/relax_vm/builtin.cc
- tests/python/relax/test_vm_build.py
Prior this this commit, all symbolic variables needed to be defined either by tensor shapes, or by an explicit `tvm.runtime.ShapeTuple` argument.  This commit allows arguments `arg: R.Prim(value="n")` to serve as a source of definition for symbolic variables.
> [Unity] Support symbolic PrimValue arguments

- src/runtime/contrib/cublas/cublas_json_runtime.cc
`JSONRuntimeBase` class the cuBLAS BYOC is based on has `data_entry_` member variable which is populated with input and output `DLTensor` from `TVMArgs` at
https://github.com/apache/tvm/blob/unity/src/runtime/contrib/json/json_runtime.h#L157-L179
When cuBLAS BYOC is used by Disco with `ThreadedSession`, each gpu will populate and end up overwriting the same `data_entry_` variable with `DLTensor`s on different devices, since `data_entry_` is not thread local. This results in a runtime crash since, for example, the device 0 may try to call cuBLAS on `DLTensor`s in `data_entry_` which might live on other devices.
This PR fixes this issue and now cuBLAS BYOC can be used from Disco with `ThreadedSession`.
@vinx13 @junrushao
> [Unity][BYOC] Fix cuBLAS BYOC compatibilty with Disco + `ThreadedSession`

- python/tvm/contrib/cutlass/attention_operation.py
- python/tvm/contrib/cutlass/gen_tensor_op.py
- tests/python/relax/test_codegen_cutlass.py
Recently, I made two PRs on attention:
* https://github.com/apache/tvm/pull/15837 introduced `nn.attention_var_len`, always offloaded to cutlass fMHA
* https://github.com/apache/tvm/pull/15951 Support for sliding-window attention, always offloaded to Flash 
Now, I realized that in practice I need to use `nn.attention_var_len` with sliding-window attention, which is not possible with the two PRs since the two features require different offloading backends. I enabled offloading `nn.attention_var_len` to Flash to resolve this issue. 
@vinx13 @sunggg
> [Unity][BYOC] Support variable-length attention by flash attention

- python/tvm/relax/vm_build.py
- src/relax/transform/legalize_ops.cc
- tests/python/relax/test_codegen_cublas.py
- tests/python/relax/test_codegen_cudnn.py
- tests/python/relax/test_codegen_cutlass.py
- tests/python/relax/test_codegen_dnnl.py
- tests/python/relax/test_codegen_tensorrt.py
- tests/python/relax/test_codegen_tir_cutlass.py
- tests/python/relax/test_dataflow_pattern.py
- tests/python/relax/test_e2e_op_dynamic.py
- tests/python/relax/test_frontend_stablehlo.py
- tests/python/relax/test_op_gradient_numeric.py
- tests/python/relax/test_training_optimizer_numeric.py
- tests/python/relax/test_transform_gradient_numeric.py
- tests/python/relax/test_vm_execbuilder.py
Prior to this commit, `relax.transform.LegalizeOps` needed to be called prior to `relax.build`.  This commit adds `LegalizeOps` to the lowering flow, to simplify the calling steps for an end-user.  If the `IRModule` contains no legalizable functions, a second legalization pass has no effect.
Some test cases relied on this behavior as an implicit assertion that operator fusion patterns applied.  That is, by omitting `LegalizeOps`, a successful compilation `relax.build` would only occur if all legalizable operators have already been removed, and so an incorrect fusion pattern would result in a failure to build the module.  While these tests would be better expressed by comparing against an expected fused pattern, updating the tests is outside the scope of this PR.  To allow these tests to …
> [Unity] Include LegalizeOps in the default relax.build lowering flow

- python/tvm/relax/ir/instrument.py
Prior to this commit, the `WellFormedInstrument` showed any error messages produced by the call to `relax.analysis.well_formed`, but did not show the ill-formed module itself.  Since this instrumentation is enabled for all unit tests in the `tests/python/relax` directory, CI logs do not include the failing module, making the logs less useful for debugging.
This commit updates the `WellFormedInstrument` to display the ill-formed module prior to raising an exception.
> [Unity][Testing] Show failing module in WellFormedInstrument

- python/tvm/contrib/cutlass/attention_operation.py
- tests/python/relax/test_codegen_cutlass.py
`max_seqlen` is a parameter required by cutlass and flash batched attention kernels. In practice, we compute this value at runtime via `max_seqlen = relax.op.max(seq_lens)`. Since the result of the max op is `Tensor[(), int32]` on GPU rather than a plain int32, and currently there is no easy way to convert the scalar tensor to a plain scalar, we've been doing `cudaMemcpy` of a single int32 to get a plain int32 from `DLTensor` of shape () in each kernel call. 
To remove unnecessary `cudaMemcpy`, I'm now enforcing the scalar tensor `max_seqlen` to be on CPU, so that in a kernel we can simply do `max_seqlen->data[0]` rather than `cudaMemcpy` to get an int32 value. The test case demonstrates how to do cuda -> cpu copy in a Relax mod - it uses the "virtual device" concept.
@vinx13 @sunggg
> [Unity][BYOC] Do not use cudaMemcpy for max_seqlen in var len attention

- docker/install/ubuntu_download_arm_compute_lib_binaries.sh
Update Compute Library to follow latest developments in 23.08
Changelog: https://arm-software.github.io/ComputeLibrary/v23.08
cc @lhutton1 @neildhickey @ashutosh-arm for reviews
> [ACL] Update Compute Library to v23.08

- python/tvm/runtime/disco/session.py
- src/runtime/disco/session.cc
This PR changes how to get the `Session` from `DPackedFunc` or `DModule`. Without this, there will be data corruption in the message channel, if Python gc happens in a different thread than the thread that owns the Disco session, which is typical in a multi-thread environment like LLM inference server.
An explanation on how such data corruption could occur:
1. Every time dref.session gets called. A new Session Python object will be created, due to how FFI works https://github.com/apache/tvm/blob/ebbe38f3281776cfda4fce0b188892ab1c5c7572/python/tvm/runtime/disco/session.py#L42
2. When we want to call the model through disco, we need to first obtain the DPackedFunc through DModule . This process calls the _get_cached_method on a new Session object (follows (1)) …
> [Disco] Explicitly set the session on DPackedFunc and DModule

- src/tir/transforms/ir_utils.cc
- tests/python/unittest/test_tir_transform_lower_opaque_block.py
compact_buffer_region PASS modify shared buffer stride[0] to
T.int64(72) * T.min((n + T.int64(63)) // T.int64(64) * T.int64(64), T.int64(96)) and stride[1] is T.int64(72)
but in LowerOpaqueBlock PASS it report error:
InternalError: Check failed: (is_zero(floormod(buffer->strides[i - 1], buffer->strides[i]))) is false:
For more detaied discuss, see [here](https://discuss.tvm.apache.org/t/bug-tir-symbolic-floormod/15826)
> [Fix][TIR]fix symbolic strides lower

- include/tvm/topi/transform.h
- python/tvm/relax/__init__.py
- python/tvm/relax/dpl/pattern.py
- python/tvm/relax/pipeline.py
This commit adds `tvm.relax.register_pipeline` which allows external registration of compilation pipelines.
> [Unity] Allow Pipeline Registration

- python/tvm/_ffi/base.py
Prior to this commit, the FFI error propagation in Python assumed that any stack frame with a known file name also had a known line number. This commit updates the error propagation to instead check if a known line number is present.
Closes https://github.com/apache/tvm/issues/15880.
> [FFI][Python] Handle error propagation when line number is missing

- src/relax/transform/rewrite_cuda_graph.cc
- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
The catch-all in `relax.transform.KillAfterLastUse` can be used for releasing tensor/storage, not just those that were not previously handled.  This simplifies the `StaticPlanBlockMemory` pass, as it does not need to track the location at which `R.memory.kill_storage` and `R.memory.kill_tensor` should be inserted.
> [Unity] Remove end-of-life handling from StaticPlanBlockMemory

- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/frontend/nn/spec.py
- python/tvm/relax/frontend/nn/torch.py
- tests/python/relax/test_frontend_nn_packing.py
This PR introduces support for parameter/effect packing.
**What is parameter packing?** There are two ways to represent weights
as input(s) of Relax functions.
- Unpacked: each weight is passed in as a separate parameter:
```python
@R.function
def f(
...,
weight_0: R.Tensor(...),
weight_1: R.Tensor(...),
...,
)
```
- Packed: all weights are packed together as a Relax Tuple and passed in
as a single parameter:
```python
@R.function
def f(
...,
weights: R.Tuple((R.Tensor(...), R.Tensor(...))),
...,
)
```
**Why support parameter packing?** First of all, currently MLC LLM uses
packed parameter as the default format in its runtime. To align the new
`nn.Module` frontend with the existing behavior, we allow packing as a
non-default option to be turned on.
Second, having a calling convention …
> [Unity][nn.Module] Support Parameter Packing

- python/tvm/contrib/cc.py
- python/tvm/relax/frontend/nn/__init__.py
- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/spec.py
- tests/python/relax/test_frontend_nn_extern_module.py
Following https://github.com/apache/tvm/pull/15487, this PR introduces `nn.SourceModule` as a subclass of
`nn.ExternModule` to more convenient handling of externally implemented
operators, subgraphs and other components.
**What is `nn.ExternModule` designed for?** It is a generic design that
accepts any object file (`.o` in Linux) and combines the symbols within
into TVM-generated shared/static library. This way, TVM-generated
library will be able to call into the symbols in the object files
provided. For example, calling into `cutlass_fmha` in TVM Relax.
**What is `nn.SourceModule`?** It is a subclass that builds on top of
`nn.ExternModule`, which helps with a specific case where the external
implementation is provided as C++/CUDA source code and `SourceModule`
could conveniently take …
> [Unity][nn.Module] Support `nn.SourceModule`

- tests/python/unittest/test_runtime_module_based_interface.py
If either `TVM_NUM_THREADS` or `OMP_NUM_THREADS` the `test_num_threads` would fail because strings can not be compared with integers.
This tiny PR fixes the test by introducing type casts.
> [Tests] Fix str vs. int comparison in test_num_threads

- tests/python/unittest/test_roofline.py
Pytest param fixture for `dtype`s was not used resulting in these two test cases not being checked.
> [Tests] Check int8+int32 testcases in test_estimate_peak_flops_cpu

- python/tvm/dlight/base/transform.py
- python/tvm/dlight/benchmark/extract.py
- python/tvm/ir/module.py
- python/tvm/meta_schedule/tir_integration.py
- python/tvm/relax/analysis/estimate_memory_usage.py
- python/tvm/relax/backend/contrib/cutlass.py
- python/tvm/relax/frontend/common.py
- python/tvm/relax/testing/transform.py
- python/tvm/relax/transform/fast_math.py
- python/tvm/relax/transform/lazy_transform_params.py
- python/tvm/relax/transform/optimize_layout_transform.py
- python/tvm/relax/transform/remove_redundant_reshape.py
Prior to this PR, visiting order of the following for-loop is non-deterministic:
```python
mod: tvm.ir.IRModule
for gv, func in mod.functions.items():
...
```
This is because `IRModule` stores those functions inside a hash map `Map<GlobalVar, BaseFunc>`, which is based on pointer equality. This behavior is usually innocent and harmless given many previous workloads only have one "main" function as the primary entry point, e.g. a single Relax Function and a bunch of TIR functions. However, it is not true in LLM usecases where `prefill`, `decoding` are both equally important entrypoints, and in those cases, it is possible that the names of generated TIR functions from LegalizeOps are essentially different from each run, which is, again, harmless in basic usecases, but it does make debugging …
> [Unity] Deterministic Ordering when Iterating IRModule::functions

- tests/python/unittest/test_micro_ms_tuning.py
Converting `work_dir = tvm.contrib.utils.tempdir()` to `str` yields `"<tvm.contrib.utils.TempDirectory object at 0x7fc5322c3790>/"` which creates a so-called file in the current working directory.
This change uses `str(work_dir.path)` instead, resulting in the expected behavior.
> [Tests] Fix work_dir location used by test_micro_tuning_with_meta_schedule

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
See the testcase for more details :)
> [Unity] Avoid Emitting Redandunt Bindings in TensorExpr Op

- src/tir/transforms/inject_ptx_async_copy.cc
- tests/python/unittest/test_tir_transform_inject_ptx_async_copy.py
Another bug occurs in PASS InjectPTXAsyncCopy .
that is dst_offset.dtype could be int64, the dtype of PrimExpr(index_factor) would be set to default to int32.
cause dtype inconsistent when calling tir::Mul.
To reproduce the problem in InjectPTXAsyncCopy, see [script here](https://gist.github.com/JackWeiw/5b80956ab44c0f63d4f434f18f42cc89)
> [Fix][TIR]fix mul dtype mismatch

- src/target/source/codegen_c.cc
- src/target/source/codegen_c.h
- src/target/source/codegen_cuda.cc
- src/target/source/codegen_cuda.h
- src/target/source/codegen_metal.cc
> [Codegen] Add shuffle for cuda and metal

- python/tvm/relax/block_builder.py
- tests/python/relax/test_blockbuilder_core.py
Prior to this commit, all expressions needed to be explicitly converted from native python types to relax expressions before being emitted by the block builder.  This commit relaxes that requirement, and allows python tuples to be converted to relax tuples.
> [Unity][BlockBuilder] Allow emitting nested tuple

- include/tvm/runtime/container/shape_tuple.h
- include/tvm/runtime/disco/session.h
- src/runtime/disco/bcast_session.cc
- src/runtime/disco/bcast_session.h
- src/runtime/disco/nccl/nccl.cc
- src/runtime/disco/process_session.cc
In TVM, ShapeTuple is usually used interchangably as a tuple of integers that are not necessarily a shape. This PR introduces the following aliasing to help it more semantically clear:
```C++
using IntTuple = ShapeTuple;
using IntTupleObj = ShapeTupleObj;
```
> [Unity] Alias IntTuple <= ShapeTuple

- include/tvm/runtime/packed_func.h
- include/tvm/runtime/vm/executable.h
- src/runtime/vm/executable.cc
This PR introduces a series of macros as part of TVM's runtime::Module-based calling convention.
```C++
TVM_MODULE_VTABLE_BEGIN(TypeKey);
TVM_MODULE_VTABLE_ENTRY(Name, MemFunc);
TVM_MODULE_VTABLE_ENTRY_PACKED(Name, Func);
TVM_MODULE_VTABLE_END();
```
This way, one could conveniently define the callable symbols a TVM Module exposes, for example, `runtime::relax_vm::Exectuable`, by looking at the vtable below:
```C++
TVM_MODULE_VTABLE_BEGIN("VMExecutable"); // type key
TVM_MODULE_VTABLE_ENTRY("get_lib", &Executable::GetLib); // const member functions
...
TVM_MODULE_VTABLE_ENTRY_PACKED("vm_load_executable", Executable::Load); // non-member functions
TVM_MODULE_VTABLE_ENTRY("move_late_bound_consts", &Executable::MoveLateBoundConstantsToFile); // mutable member function …
```
> [Runtime] Introduce `TVM_MODULE_VTABLE` Macros

- python/tvm/contrib/msc/core/codegen/codegen.py
- python/tvm/contrib/msc/core/frontend/__init__.py
- python/tvm/contrib/msc/core/frontend/translate.py
- python/tvm/contrib/msc/core/ir/__init__.py
- python/tvm/contrib/msc/core/runtime/__init__.py
- python/tvm/contrib/msc/core/runtime/runner.py
- python/tvm/contrib/msc/core/utils/__init__.py
- python/tvm/contrib/msc/core/utils/dataset.py
- python/tvm/contrib/msc/core/utils/file.py
- python/tvm/contrib/msc/core/utils/info.py
- python/tvm/contrib/msc/core/utils/log.py
- python/tvm/contrib/msc/core/utils/message.py
- python/tvm/contrib/msc/core/utils/namespace.py
- python/tvm/contrib/msc/framework/__init__.py
- python/tvm/contrib/msc/framework/tensorflow/codegen/codegen.py
- python/tvm/contrib/msc/framework/tensorflow/frontend/translate.py
- python/tvm/contrib/msc/framework/tensorrt/codegen/codegen.py
- python/tvm/contrib/msc/framework/tensorrt/frontend/__init__.py
- python/tvm/contrib/msc/framework/tensorrt/frontend/translate.py
- python/tvm/contrib/msc/framework/torch/codegen/codegen.py
- python/tvm/contrib/msc/framework/torch/frontend/__init__.py
- python/tvm/contrib/msc/framework/torch/frontend/translate.py
- python/tvm/contrib/msc/framework/tvm/codegen/codegen.py
- python/tvm/contrib/msc/framework/tvm/runtime/__init__.py
- python/tvm/contrib/msc/framework/tvm/runtime/runner.py
- tests/python/contrib/test_msc/test_runner.py
- tests/python/contrib/test_msc/test_translate_tensorrt.py
This is the 3rd part of Milestone 1: Finish RuntimeManager for frameworks
To limit each PR in reviewable size, the Milestone 1 will be split into some steps:
M1.1 Add translate && codegen for torch
M1.2 Add translate && codegen for tensorflow
M1.3 Add codegen for tensorrt
**M1.4 Add Runner and test with relax**
M1.5 Add Runner and test with torch
M1.6 Add Runner and test with tensorflow
M1.7 Add Runner and test with tensorrt
Runner is the very basic part of MSC compiling pipeline. It manage tools in MSC and unify the forward process of all frameworks.
Runner also build and hold …
> [Unity][MSC][M1.4] Add Runner and test with relax

- tests/lint/pylint.sh
- tests/python/contrib/test_tflite_runtime.py
- tests/python/contrib/test_thrust.py
- tests/python/contrib/test_util.py
> [Pylint] fix pylint issues for thrust&tflite_runtime&util

- .github/workflows/main.yml
- src/target/source/codegen_metal.cc
- src/target/source/codegen_metal.h
- tests/python/unittest/test_target_codegen_metal.py
This PR restores the Metal codegen to the one before #15835. Due to there will likely be no internal function call in Metal, we think it is safe to do so.
Verified that with this PR, the metal codegen and iPhone codegen will not fail and will work properly.
The reason of the iPhone codegen failure is because the multiple declarations of a same function will lead to multiple emissions of a same structs, which is not recognizable by the metal compiler.
> [Codegen][Metal] Disable cross-function call in Metal codegen

- src/script/ir_builder/tir/ir.cc
- src/tir/transforms/lower_cross_thread_reduction.cc
- tests/python/unittest/test_tvmscript_parser_tir.py
As reported by the [community](https://discuss.tvm.apache.org/t/int32-int64-issue-when-codegen-into-llvm-function/15915), the dtype of IterVar in `T.thread_binding` is not consistent with the dtype of the corresponding value. This PR fixes this issue.
> [TVMScript] Fix mismatched dtype of IterVar in `T.thread_binding`

- src/tir/transforms/inject_software_pipeline.cc
- tests/python/unittest/test_tir_transform_inject_software_pipeline.py
cc @spectrometerHBH @Hzfengsy @junrushao
> [TIR] Fix software pipeline with dynamic loop extent

- python/tvm/relax/frontend/nn/visitor.py
When the input `name` is an empty string which means the visitor is at the top level of the module, we should not add a dot to the name of the leaf nodes. 
Before:
```
LlamaForCausalLM
- .model
- .lm_head
```
After this update:
```
LlamaForCausalLM
- model
- lm_head
```
> [Fix] Update mutator name rule

- src/tir/transforms/renew_defs.cc
- tests/python/unittest/test_tir_renew_defs.py
Pervious implementation of RenewDefs pass will fail in the case of the gather/take function. This is because the pass visit and renew the read/write regions twice. This PR fixes it and adds a regression test.
cc @cyx-6
> [TIR] Fix pass RenewDefs error in gather/take case

- src/runtime/relax_vm/lm_support.cc
- web/src/runtime.ts
This PR enhances the `SampleTopPFromProb` function, adding a new `unit_offset` parameter. With this PR, the input prob array can contain multiple prob distributions. The offset is used to specify which probability to sample from.
Prior to this PR, this function assumes the input prob array only contains a single probability distribution.
This assumption, though effective, prevents efficient sampling for batching scenarios, since it forces us to split the batched prob array before sampling.
This PR eliminates this issue by introducing the offset.
> [Unity][Support] Sample from top-p supports offset

- tests/scripts/task_config_build_arm.sh
Changes the config script to build TVM with LLVM 17.
cc @leandron @junrushao @neildhickey @Liam-Sturge
> [CI] Use LLVM 17 for tests on `ci_arm`

- include/tvm/runtime/memory/memory_manager.h
- src/runtime/memory/memory_manager.cc
This PR fixes compilation error from macOS's clang due to recent change.
```
/Users/jshao/Projects/tvm-dev/src/runtime/relax_vm/builtin.cc:357:48: note: in instantiation of function template specialization 'tvm::runtime::Registry::set_body_method<tvm::runtime::memory::Storage, tvm::runtime::memory::StorageObj, tvm::runtime::NDArray, unsigned long, tvm::runtime::ShapeTuple, DLDataType, void>' requested here
357 | TVM_REGISTER_GLOBAL("vm.builtin.alloc_tensor").set_body_method<Storage>(&StorageObj::AllocNDArray);
|                                                ^
/Users/jshao/Projects/tvm-dev/include/tvm/runtime/packed_func.h:546:3: note: candidate function
546 |   operator double() const {
|   ^
/Users/jshao/Projects/tvm-dev/include/tvm/runtime/packed_func.h:556:3: note: candidate function …
```
> [Bugfix] Compilation Error with Clang

- python/tvm/contrib/nvcc.py
- src/target/opt/build_cuda_on.cc
- tests/python/unittest/test_target_codegen_cuda.py
Several Nvidia tools such as Nsight Systems and Nsight Compute can be used for profiling cuda kernels. NVIDIA Nsight Systems collects system-wide information about your program and GPU events and might help you to understand possible bottlenecks in your topology. To profile concrete Cuda kernel, NVIDIA Nsight Compute can be used.
If you try to profile cuda kernel from TVM with Nsight Compute without this patch, then you see only SASS instructions instead of the source code. It is useful, but sometimes it might be easier to analyze generated cuda code instead of instructions. In this patch, a new pass config option was added. By using option `cuda.kernels_output_dir`, you can specify the directory where cuda source code should be stored after the build. Also, in the case of using this …
> [CUDA] Add an option for profiling cuda kernels

- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/for_kind.cc
- tests/python/unittest/test_tir_schedule_for_kind.py
As a follow up PR of #16041, this PR fixes the iter_var dtype generated by the schedule primitive `bind`. Now the iter_var dtype is the same as the loop_var.
Note that this PR changes the internal interface (tir interface) of the bind primitive. But it does not change the user interface (python side, and concrete_schedule.cc side).
cc @junrushao
> [TIR] Fix the thread binding iter_var dtype in `Bind` primitive

- src/relax/transform/fuse_tir.cc
- src/tir/transforms/renew_defs.cc
- tests/python/relax/test_transform_fuse_tir.py
- tests/python/unittest/test_tir_renew_defs.py
The current implementation of FuseTIR pass does not handle the buffer access region of the blocks, which may fail when the function is in gather or take pattern. This PR fixes the issue.
Depends on https://github.com/apache/tvm/pull/16063
cc @cyx-6
> [Unity] Fix FuseTIR pass for gather/take cases 

- src/runtime/relax_vm/lm_support.cc
- web/src/runtime.ts
This PR reverts apache/tvm#16069.
We found that there are more improvements for the sampling function. We would like to implement them and verify the functionality locally first, and upstream when the stability is confirmed.
> Revert "[Unity][Support] Sample from top-p supports offset"

- docs/how_to/deploy/tensorrt.rst
Fixed outdated module building method in tensorrt
> [TRT] fix outdated module building method in tensorrt

- python/tvm/relax/transform/lazy_transform_params.py
- tests/python/relax/test_transform_lazy_transform_params.py
A parameter transformation may output the same tensor more than once. When this occurs, the `set_item` function should be called for each output tensor.
> [Unity] Handle duplicate outputs in LazyTransformParams

- include/tvm/runtime/memory/memory_manager.h
- src/runtime/memory/memory_manager.cc
- src/runtime/memory/pooled_allocator.h
This PR supports clearing up all the allocated memory.
Prior to this PR, all the allocated memory are managed in the pool of memory manager. The allocated memory in the pool is on hold and never freed. Consequently, the pool size always goes up monotonically within a single run in a process.
While good to save time of memory allocation, in some cases (e.g., on mobile phones which may have running memory limit) we need to clear the pool and free all the memory in order to prevent the pool from endlessly growing up and some of allocated memory not being effectively utilized (fragmentation).
Therefore, this PR introduces a PackedFunc that helps clean up the memory manager, releasing all the allocated memory. Runtime apps can decide when to invoke this PackedFunc and clean up the pool. …
> [Runtime] Support clear global memory allocators

- python/tvm/_ffi/_ctypes/packed_func.py
- python/tvm/_ffi/_cython/packed_func.pxi
- src/runtime/registry.cc
Propagation of Python exceptions across C++ stack frames was introduced in https://github.com/apache/tvm/pull/15596.  This commit primarily fixes a typo in the initial implementation, where `Py_IncRef` was used instead of `Py_DecRef`.
In addition, this PR resolves errors that were exposed by this typo fix, which caused test failures in `tests/python/unittest/test_crt.py::test_compile_runtime`.  These were due to use of the `Py_IncRef` and `Py_DecRef` functions on threads that hadn't acquired the GIL.  This usage error has been corrected for both the ctypes and cython FFI handling.
> [Bugfix][FFI] Typo fix of IncRef to DecRef

- python/tvm/_ffi/base.py
- python/tvm/relax/op/_op_gradient.py
- python/tvm/relax/op/manipulate.py
- src/relax/transform/gradient.cc
- tests/python/relax/test_transform_gradient.py
- tests/python/relax/test_transform_gradient_checkpoint.py
This PR supports providing intermediate vars in require_grads argument of the gradient pass.
This is useful for debugging, since users can find the gradient value of intermediate vars.
This PR also fixes a bug when var that requires gradient is wrapped in the checkpointed range (wrapped in start_checkpoint and end_checkpoint pairs). 
cc @yzh119 @MasterJH5574 @tqchen
> [Unity][Training] Support intermediate vars as require_grads for Gradient pass

- CMakeLists.txt
- include/tvm/relax/block_builder.h
- include/tvm/relax/op_attr_types.h
- python/tvm/relax/ir/instrument.py
- python/tvm/relax/testing/transform.py
- src/relax/analysis/well_formed.cc
- src/relax/ir/block_builder.cc
- src/relax/op/op.cc
- src/relax/testing/transform.cc
- src/script/ir_builder/relax/ir.cc
- tests/python/relax/conftest.py
- tests/python/relax/test_transform_operator_specific_normalization.py
Some Relax operators have requirements regarding their AST that are stronger than are checked by the C++ types being used.  These are similar to checks that are present in the `tvm::relax::WellFormed` utility, such as checks forbidding the use of undefined variables, which are also stronger than required by the underlying C++ types. However, because every operator may have unique requirements, it would be unreasonable to expect a writer of a `relax::ExprMutator` to be aware of and to maintain all such requirements.
This PR introduces an operation operator attribute `FNormalize`.  If defined, this function is used to apply an operator-specific normalization.  The implementation of `FNormalize` has the following design decisions.
* If no change is required, `FNormalize` should return the …
> [Unity] Implement FNormalize attribute for operators

- include/tvm/relax/analysis.h
- src/relax/analysis/udchain.cc
- src/relax/ir/binding_rewrite.cc
- src/support/ordered_set.h
- tests/python/relax/test_analysis.py
Prior to this commit, pure arguments to impure functions could be erroneously removed, if the impure function's result is unused.  This commit updates the variable usage tracking in dead-code elimination to consider both function return values and arguments to impure functions as externally-exposed values.
> [Unity][Bugfix] Track variable usage from input to impure functions

- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/op.py
- src/tir/ir/expr.cc
- tests/python/unittest/test_tvmscript_roundtrip.py
This PR fixes dtype issues for 
- the strides parameter of match_buffer. 
- When stride is a tir var, it would become a string like `"A_s0"` in the printed script. 
- If the strides are int64 vars, when we parse the printed script, the dtype of the strides will be set to int32 by default. That causes dtype misalign and effects the structural_equal check. 
- We will cast the string stride to the dtype of shape (which is always a primexpr)
- ramp node. If the dtypes of base and stride of a ramp node do not match, the dtype of stride will be casted to the dtype of base.
> [Fix][TIR] Fix dtype issues for match_buffer and ramp node

- docs/contribute/release_process.rst
Update release_process.rst about version number modification
Note: [The rfcs about 0067-quarterly-releases](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation) doesn't contain concret version number modfication points, thus doesn't need change.
> [DOCs] Update release_process.rst about version number modification

- python/tvm/topi/arm_cpu/arm_utils.py
- python/tvm/topi/arm_cpu/conv2d_alter_op.py
- python/tvm/topi/nn/conv2d.py
Refactored out a piece of common functionality from the `conv2d_gemm_weight_transform` and `interleave_transpose_weights` functions, which has previously led to bugs stemming from changes made to only one but not the other, like in #15584.  
Determining the necessary padding for the interleaved and transposed weights matrix has now been separated into a new utility function, allowing future changes to be reflected in both callers.
cc @ekalda @lhutton1 @neildhickey @leandron
> [TOPI] Reduce code redundancy in conv2d weights transformation

- cmake/utils/FindLLVM.cmake
PR #16032 introduces a more stable way of zstd path finding by relying on LLVM's existing Findzstd module, but it turns out that the cmake dir from `llvm-config` is not very compatible with CMake's internal convention, and thus a conversion is required to get rid of the error message below:
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
D:/a/package/package/tvm/build/CMakeFiles/CMakeScratch/TryCompile-tnlfb1/CMakeLists.txt:2
-- Configuring incomplete, errors occurred!
when parsing string
C:\Miniconda\envs\tlcpack-build\Library\lib\cmake\llvm
Invalid character escape '\M'.
```
CC @lhutton1
> [Fix] Broken Windows Build with LLVM

- tests/lint/pylint.sh
- tests/python/contrib/test_random.py
- tests/python/contrib/test_rocblas.py
- tests/python/contrib/test_rpc_proxy.py
- tests/python/contrib/test_rpc_server_device.py
- tests/python/contrib/test_rpc_tracker.py
- tests/python/contrib/test_sort.py
- tests/python/contrib/test_sparse.py
- tests/python/contrib/test_tedd.py
According to #11414 , I fixed pylint issues for test_random, test_rocblas, test_rpc_proxy, test_rpc_server_device, test_rpc_tracker, test_sort, test_sparse, test_tedd in this PR.
> [Pylint] fix pylint issues from test_random to test_tedd

- include/tvm/target/tag.h
- src/target/tag.cc
- src/target/target_kind.cc
- tests/python/unittest/test_target_target.py
This PR supports obtain l2 cache size from target. The API is
```
target.l2_cache_size_bytes
```
The l2 cache size is hardcoded in src/target/tag.cc.
This is useful for specializing schedule rules for different targets.
This PR is followup of #15332
cc @yzh119 @zxybazh
> [Target] Support obtain l2 cache size from target

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul_tensorize.py
Main goal of this commit was not to provide highly optimized schedule, but to enable tensor core tensorization for i8i8i32 matmul. Now it supports fp16 matmul only.
Anyway, speedup is a case compared to fp16 (fp16fp16->fp16 vs i8i8->i32):
N |        M, N, K*      |   Shape type   | fp16, us | int8, us | speedup |
--|----------------------|----------------|----------|----------|---------|
1 |     256, 256, 256    |  static shapes |   15.03  |   12.55  |  1.198x |
2 |     512, 512, 4096   |  static shapes |  173.25  |  129.06  |  1.342x |
3 | N (=260), 4096, 4096 | dynamic shapes |  350.44  |  298.29  |  1.175x |
where K* - is a reduction axis.
Implementation of Matmul int8 tensorizer was derived from Matmul tensorizer with minimal changes. It is possible to join these implementations (fp16 …
> [Unity][Dlight] Enhance matmul tensorizer with Int8 support

- src/relax/analysis/tir_op_pattern_kind.cc
- tests/python/relax/test_transform_rewrite_dataflow_reshape.py
Current RewriteDataflowReshape pass cannot detect reshape from [n, 16, 128] to [1, n, 16, 128] because of simplifier is not symbolic-var-aware. This PR adds an additional IterMapSimplify to solve the problem.
> [Unity] support symbolic var in RewriteDataflowReshape

- include/tvm/ir/expr.h
- include/tvm/tir/var.h
- python/tvm/ir/expr.py
- python/tvm/tir/expr.py
This PR enhances the Python annotations for the TIR expr, adding class member variables annotations.
cc @tqchen
> [TIR] Enhance Python Type Annotations for TIR Expr

- src/relax/ir/dataflow_matcher.cc
- tests/python/relax/test_dataflow_pattern.py
When matching global var of TIR functions, sometimes we want to use regular expression to match because the TIR functions are often named like matmul_123. This PR implements this behavior.
> [Unity] Support Regular expression matching in globalvar dataflow pattern

- src/relax/transform/lift_transform_params.cc
- tests/python/relax/test_transform_lift_transform_params.py
In some cases the shape of model weight contains a symbolic var, like vocab size, but it should be treated as if it's constant in LiftTransformParams because the symbolic var does not change in each call of decode/prefill functions.
This PR implements this behavior.
> [Unity] [LiftTransformParams] Treat symbolic var in weight shape as constant

- python/setup.py
- python/tvm/_ffi/libinfo.py
Current FasterTransformer and FlashAttention BYOCs produce their own shared libraries.
This PR adds them in the list of shared libraries that is going to be packaged into the python wheel.
> [Packaging] Include BYOC dynamic libraries into wheel

- docs/contribute/pull_request.rst
The `git-clang-format.sh` requires `--rev`.
https://github.com/apache/tvm/blob/main/tests/lint/git-clang-format.sh#L39
cc @Hzfengsy
> [DOCs] Fix error on linting by adding `--rev` argument

- python/tvm/contrib/msc/core/frontend/translate.py
- python/tvm/contrib/msc/core/runtime/runner.py
- python/tvm/contrib/msc/core/transform/transform.py
- python/tvm/contrib/msc/core/utils/file.py
- python/tvm/contrib/msc/core/utils/info.py
- python/tvm/contrib/msc/framework/tensorflow/frontend/translate.py
- python/tvm/contrib/msc/framework/tensorflow/runtime/__init__.py
- python/tvm/contrib/msc/framework/tensorflow/runtime/runner.py
- python/tvm/contrib/msc/framework/tensorrt/codegen/codegen.py
- python/tvm/contrib/msc/framework/tensorrt/runtime/__init__.py
- python/tvm/contrib/msc/framework/tensorrt/runtime/runner.py
- python/tvm/contrib/msc/framework/torch/runtime/__init__.py
- python/tvm/contrib/msc/framework/torch/runtime/runner.py
- python/tvm/contrib/msc/framework/tvm/runtime/runner.py
- src/contrib/msc/core/codegen/codegen_utils.cc
- src/contrib/msc/core/ir/graph.cc
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/printer/prototxt_printer.cc
- src/contrib/msc/core/transform/set_byoc_attrs.cc
- src/contrib/msc/framework/tensorflow/codegen.cc
- src/contrib/msc/framework/tensorflow/tf_v1_opcode.cc
- src/contrib/msc/framework/tensorrt/codegen.cc
- src/contrib/msc/framework/tensorrt/codegen_utils.h
- tests/python/contrib/test_msc/test_runner.py
- tests/python/contrib/test_msc/test_translate_relay.py
To limit each PR in reviewable size, the Milestone 1 will be split into some steps:
M1.1 Add translate && codegen for torch
M1.2 Add translate && codegen for tensorflow
M1.3 Add codegen for tensorrt
M1.4 Add Runner and test with relax
**M1.5 Add Runner and test with torch
M1.6 Add Runner and test with tensorflow
M1.7 Add Runner and test with tensorrt**
This MR build runners for all left frameworks.
Runner is the very basic part of MSC compiling pipeline. It manage tools in MSC and unify the forward process of all frameworks.
Runner also build and hold model in framework format, …
> [Unity][MSC][M1.5-1.7] Add Runner and test with torch, tensorflow && tensorrt

- docs/contribute/code_guide.rst
Just noticed while reading through the Python Code Styles.
> [DOCs] Add missing backtick to contribute/code_guide.rst

- src/runtime/disco/loader.cc
- src/runtime/disco/nccl/nccl.cc
- src/runtime/disco/worker.cc
- tests/python/disco/test_loader.py
Prior to this commit, sharding of model weights was always performed when initializing the model.  This could cause slow initialization, especially for larger numbers of GPUs, as all model weights are initially transferred to GPU-0, before being scattered to all workers.
This commit updates the `tvm::runtime::ShardLoaderObj` to also allow loading of pre-sharded model weights.  With pre-sharded model weights, the tensors are sharded while the model is being built, and each worker independently loads the specific model weights that it requires.
> [Disco] Add loader for presharded params.

- include/tvm/relax/attrs/ccl.h
- python/tvm/relax/op/ccl/ccl.py
- python/tvm/relax/transform/legalize_ops/ccl.py
- src/relax/op/ccl/ccl.cc
- src/relax/op/ccl/ccl.h
- tests/python/relax/test_transform_legalize_ops_ccl.py
This PR adds an `axis` field to scatter_from_worker0, which means the tensor axis along which it is scattered. legalize_ops will automatically generate reshape and transpose to preserve the constraint of ccl that collective communication ops must be performed on contiguous memory. For example, if the tensor shape of x is [10, 20], and we have `scatter_from_worker0(x, num_workers=2, axis=1)`, then after legalization it will expand to 
```
x = reshape(x, [10, 2, 10]) # shape: [10, 2, 10]
x = permute_dims(x, [1, 0, 2]) # shape: [2, 10, 10]
x = call_dps_packed("scatter_from_worker0", x) # shape: [10, 10]
```
When axis=0, the behavior is the same as before.
Also, this PR renames ScatterFromWorker0Attrs to ScatterAttrs to enable reuse by other ops like worker-id-aware slicing …
> [Unity] Add `axis` field to scatter_from_worker0

- python/tvm/relax/transform/lazy_transform_params.py
- tests/python/relax/test_transform_lazy_transform_params.py
1. user can now customize the name of packed func get_item and set_item
2. user can now only rewrite get_item but not set_item. This is useful when we want a tuple as output.
> [Unity] make LazyTransformParam more general

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Add support for  [aten::swapaxes](https://pytorch.org/docs/stable/generated/torch.swapaxes.html) operator to support compiling the pytorch's  [maxvit model](https://pytorch.org/vision/stable/models/maxvit.html).
cc @junrushao
> [Relay][Pytorch] Add support for aten::swapaxes operator

- python/tvm/dlight/gpu/reduction.py
- tests/python/dlight/test_gpu_reduction.py
fixed https://github.com/mlc-ai/mlc-llm/issues/1105
cc @tqchen @junrushao @Hzfengsy
> [Unity][Dlight] Choose perfect spatial factor in reduction rule

- src/runtime/disco/loader.cc
In DistIR compilation flow, shard loading is implemented in a Relax func, like
```
a = LoadParamOnWorker0(loader, index=0)
b = broadcast(a)
c = LoadParamOnWorker0(loader, index=1)
d = scatter_from_worker0(c)
```
LoadWholeParamOnWorker0 loads the unsharded param on worker0, and for other workers returns an empty array.
This PR implements LoadWholeParamOnWorker0
> [Unity] Add LoadParamOnWorker0 function in shard loader

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Fix #16005
Support [aten::bitwise_and](https://pytorch.org/docs/stable/generated/torch.bitwise_and.html).
cc @jikechao @@Hzfengsy @vvchernov
> [Relay][Pytorch] Add support for `aten::bitwise_and`

- web/emcc/wasm_runtime.cc
Change import in wasm runtime to reflect new memory manager location.
> [Smallfix][WEB] Change memory manager import for web

- web/src/webgpu.ts
This PR lowers the required `maxStorageBufferBindingSize` from 1GB to 128MB when necessary.
Previously, we required 1GB, which led to errors when running on some devices (e.g. Android's Chrome, since Android has 128MB as its limit).
Now, if the device does not allow 1GB, we lower it to 128MB. We only throw an error when 128MB still exceeds the limit.
cc @tqchen
> [Unity][WebGPU] Allow lower max storage buffer binding size

- python/tvm/topi/nn/dense.py
- tests/python/topi/python/test_topi_matmul.py
This PR enhances `topi.nn.matmul` to support batch matmuls (i.e. inputs with dims larger than 2). 
This is useful in certain cases where we need to generate a batch matmul kernel.
> [TOPI] Enhance `topi.nn.matmul`

- src/driver/driver_api.cc
- src/tir/transforms/inject_permuted_layout.cc
- tests/python/unittest/test_tir_transform_inject_permuted_layout.py
This PR introduces the new `InjectPermutedLayout` pass, partially adapted from the old version.
This pass will permute the visiting indices of the shared memory with xor operations to avoid bank conflicts. For permutation details see p39 of [these slides](https://developer.download.nvidia.com/video/gputechconf/gtc/2020/presentations/s21745-developing-cuda-kernels-to-push-tensor-cores-to-the-absolute-limit-on-nvidia-a100.pdf).
The current interface is:
```
with T.block("..."):
T.block_attr({"permuted_layout": 1})
```
The load/store operation could be:
- BufferLoad node
- BufferStore node
- ptx_ldmatrix call
- mma_store call
And the InjectPermutedLayout pass is injected in the lowering process in `driver_api.cc`. So after this pass in the building stage, the visiting indices will be …
> [TIR][Transform] Introduce new `InjectPermutedLayout` pass

- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache.py
This PR supports controlling whether KV cache automatic growth is allowed through constructor parameter. Previously we always allow the KV cache to grow whenever it is full and more capacity is demanded.
Although automatic growth can be good, in practice we often want the pre-allocated memory to be static, large enough and not changeable, which will make the memory management more controllable. Hence, this PR supports to specify if growth is allowed, and will throw error when growing in unallowed cases.
This PR also adds an auxiliary function to KV cache to query the number of available pages.
> [Unity][Support] PagedKVCache support growth control

- python/tvm/relax/pipeline.py
- python/tvm/relax/vm_build.py
The existing `relax.build` method assumes the compilation follows a fixed set of passes to be used. With the introduction of Relax pipeline system, one could effectively manage which passes to use during lowering. This PR generalizes this approach by further allowing what to use during compilation.
> [Unity] Allow Customized Pipeline in `relax.build`

- src/relax/ir/block_builder.cc
Display the invalid struct info if a `Tuple` has anything other than `TupleStructInfo`.
> [Unity] Improved error message in relax::Normalizer

- src/relax/transform/dead_code_elimination.cc
- tests/python/relax/test_transform_dead_code_elimination.py
Prior to this commit, the `DeadCodeElimination` and `FuseTIR` passes treated `R.ExternFunc` differently with respect to removal of internal functions: `DeadCodeElimination` treated these functions as internal, to be removed if there are no internal callers, while `FuseTIR` treated these functions as external, to be retained in all cases.
Because the visibility of a function is determined by the `tvm::attr::kGlobalSymbol` attribute; which is present for `PrimFunc` and `relax::Function`, but missing for `relax::ExternFunc`; there is no information in the `IRModule` that can determine whether a `relax::ExternFunc` should be visible externally.
For consistency, and to allow the use of `DeadCodeElimination` in future refactors of `FuseTIR`, this commit updates `DeadCodeElimination` to retain …
> [Unity][Transform] Keep R.ExternFunc in dead-code elimination

- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_transform_cse.py
This patch modifies the CSE pass to skip all constants as [discussed here](https://discuss.tvm.apache.org/t/common-subexpr-elimination-pass-replaces-constant-args-with-vars/15971)
> [Unity] [Transform] Skip constants in CSE pass

- src/relax/analysis/well_formed.cc
- src/relax/op/op.cc
- tests/python/relax/test_transform_cse.py
- tests/python/relax/test_transform_operator_specific_normalization.py
Prior to this commit, `relax.op.call_tir` could express the TIR arguments as either an in-line tuple, or as a variable bound to a tuple.  Because several passes assume the arguments will always be an in-line tuple, this is being codified as the normal form of `relax.op.call_tir`.  Any upstream transform that produces `relax.op.call_tir` with arguments provided as a by-variable tuple will either be normalized to an in-line tuple if possible, or will produce an error during the upstream transform otherwise.
This commit is specifically to allow the current usage of `Downcast<Tuple>(call->args[1])` in passes such as `CallTIRRewrite`, `FoldConstant`, `FuseTIR`, and `RewriteDataflowReshape`.
> [Unity] Implement FNormalize for relax.op.call_tir 

- docs/reference/api/links.rst
- tests/scripts/task_python_docs.sh
As cargo is unstable and breaks the CI, we have to disable the rust docs building until we can find a way to solve that.
cc @tqchen @junrushao
> Revert "[#15157][Rust][Doc] Re-enable the Rust documentation build (#15213)"

- python/tvm/relay/op/nn/_nn.py
- python/tvm/relay/op/strategy/adreno.py
- python/tvm/topi/adreno/__init__.py
- python/tvm/topi/adreno/conv2d_transpose_alter_op.py
- python/tvm/topi/adreno/conv2d_transpose_nchw.py
- python/tvm/topi/adreno/utils.py
- python/tvm/topi/nn/conv2d.py
- src/relay/transforms/annotate_texture_storage.cc
- tests/python/relay/opencl_texture/test_conv2d_transpose_nchw_texture.py
- tests/python/relay/opencl_texture/utils/adreno_utils.py
- tests/scripts/task_config_build_adreno.sh
Added the conv2d transpose strategy for adreno target and enable the optimized schedule.
> [TOPI][ADRENO] Add conv2d transpose nchw texture schedule

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul.py
The current inline consumer rule failed on the following case, because of the missing inline of the producers of the output stage
```
A   B   D
\ /    |
matmul  C
\   /
out
```
Thanks @BBuf for finding this bug
> [Unity][DLight] Enhance the inline consumer rule

- include/tvm/runtime/threading_backend.h
- tests/cpp/threading_backend_test.cc
This PR introduces the runtime parallel-for helper function in C++ with the threading backend in TVM.
Right now the existing [parallel-for](https://github.com/apache/tvm/blob/bd67d2e5ebde1aec18bcfa74c087516579bda1ae/include/tvm/support/parallel_for.h#L48-L68) in TVM is not thread persistent,
in which case we cannot get persistent TLS for each thread.
The introduced parallel-for-with-threading-backend function leverages the threading backend in TVM and persists threads.
> [Runtime] Parallel-for with threading backend

- src/runtime/relax_vm/lm_support.cc
Clears `window_attention_current_pos` when clearing cache as well.
> [Unity][Bugfix] Reset window cache current pos when clearing

- python/tvm/autotvm/tuner/__init__.py
- python/tvm/relax/dpl/pattern.py
- python/tvm/relay/analysis/sparse_conv2d.py
- python/tvm/relay/analysis/sparse_dense.py
- python/tvm/relay/frontend/tensorflow_ops.py
- python/tvm/relay/qnn/op/legalizations.py
- python/tvm/topi/arm_cpu/qnn_legalize.py
- python/tvm/topi/cuda/sparse.py
- python/tvm/topi/nn/conv3d_transpose.py
SciPy recently got a few conflicts with numpy and emits warning messages at loading time.
> [Unity] Do not import SciPy by default

- 3rdparty/picojson/picojson.h
Existing usecases of picojson parser always require to define a macro `PICOJSON_USE_INT64`, and potentially `__STDC_FORMAT_MACROS` along with it, which could lead to misconfiguration and inconsistency in projects using TVM. To address this issue, this PR adds both flags by default.
> Always use int64 in JSON parser

- include/tvm/runtime/packed_func.h
Prior to this PR, the `TVM_MODULE_VTABLE_*` macros work by detailing the correspondence between the string names and the module methods as part, so that it declares the calling convention of a TVM Module.
For example, in the `Execuable` of `RelayVM`, the convention is specified by [link](https://github.com/apache/tvm/blob/748882aae7be1435f042e22b0fc67cb236705b6c/include/tvm/runtime/vm/executable.h#L60-L76):
```C++
TVM_MODULE_VTABLE_BEGIN("VMExecutable");
TVM_MODULE_VTABLE_ENTRY("get_lib", &Executable::GetLib);
...
TVM_MODULE_VTABLE_END();
```
Note that it supports only "unpacked" member methods so far, i.e., ordinary C++ methods with fixed number of arguments, each of which has a compile-type known type, e.g.
```C++
class MyModule : public tvm::runtime::Module {
...
int UnpackedMethod(int …
```
> [Runtime] Allowing Packed Arguments in TVM Module VTable

- include/tvm/runtime/packed_func.h
- include/tvm/runtime/relax_vm/executable.h
- include/tvm/runtime/relax_vm/vm.h
- src/runtime/relax_vm/executable.cc
- src/runtime/relax_vm/vm.cc
Following up with #16148, this PR migrates Relax Exectuable/VM to the explicit vtable introduced as part of the TVM runtime Module calling convention.
> [Unity] Migrate Relax Executable/VM to `TVM_MODULE_VTABLE` Convention

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Fix #15663
Support [torch.unflatten](https://pytorch.org/docs/stable/generated/torch.unflatten.html).
cc @jikechao @vvchernov @Hzfengsy @junrushao
> [Relay][Pytorch] Add support for `aten::unflatten`

- src/relay/op/nn/convolution.cc
- tests/python/relay/test_op_level2.py
Relay for depthwise `nn.conv3d` causes error.
`depthwise` is not fully implemented for `conv3d`.
The pytorch frontend takes care of the depthwise case and reshapes the weights.
(https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/pytorch.py#L1247).
However, this is not taken care in `Conv3DRel`.
Note that `Conv2DRel` takes care of this case. 
(https://github.com/apache/tvm/blob/main/src/relay/op/nn/convolution.cc#L273)
```
class Conv3d(nn.Module):
def __init__(self):
super(Conv3d, self).__init__()
self.conv = nn.Conv3d(16, 32, kernel_size=1, groups=16)
def forward(self, x):
x = self.conv(x)
return x
s = [1, 16, 10, 10, 10]
net = Conv3d()
input_data = torch.randn(s)
scripted_model = torch.jit.trace(net, input_data).eval()
mod = …
```
> [Relay] conv3d depthwise bug fix

- CONTRIBUTORS.md
Please join me in welcoming Shuai Yuan(@ysh329) as a new committer in TVM. 
His persistent assistance in the release process is noteworthy. Specifically, his involvement in drafting release notes and coordinating the release schedules for the recent three releases (v0.12, v0.13, and v0.14) is commendable. Although Shuai does not currently hold the position of a reviewer, his contributions significantly surpass the requirements for a committer role. It is crucial to recognize and appreciate contributions that extend beyond mere code production.
- [Github Issues](https://github.com/apache/tvm/issues?page=1&q=is%3Aissue+author%3Aysh329)
- [Commits History](https://github.com/apache/tvm/pulls?q=is%3Apr+author%3Aysh329)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=review …
> [Community] Shuai Yuan -> Committers

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Fix #16096 
Support [torch.linalg.vector_norm](https://pytorch.org/docs/stable/generated/torch.linalg.vector_norm.html).
cc @jikechao @vvchernov @Hzfengsy @junrushao
> [Relay][Pytorch] Add support for `aten::linalg_vector_norm`

- tests/scripts/ci.py
- tests/scripts/setup-pytest-env.sh
- tests/scripts/task_python_adreno.sh
RPC seem to be hanging while running bunch of tests with in single session. This enables running them individually.
Also we don't need rerun with in same session that leads to hang some times. Adding PLATFORM which is needed for run_pytest to summarize the failures.
> [CI][ADRENO] Enhancements to Adreno specific CI utils

- CONTRIBUTORS.md
Sorry for the late update, but please join me in welcoming Ruihang Lai (@MasterJH5574 ) as a new PMC member of Apache TVM.
Ruihang has been an invaluable contributor to our community since 2020 and became a committer in 2022. He has consistently demonstrated his dedication and expertise in various aspects. He has led the design of TensorIR and MetaSchedule, and has been actively contributing to areas including arithmetic analysis, and performance on Apple M1 and iOS devices. Besides, he is actively engaged with the community in the discuss forum. This year, he also contributed a talk and a tutorial session in TVMCon. He is also the co-author of [SparseTIR](https://arxiv.org/abs/2207.04606) paper, reflecting his expertise in machine learning compilation and the research interests that …
> [Community] Ruihang Lai -> PMC

- CONTRIBUTORS.md
Sorry for the late update, but please join me in welcoming Bohan Hou (@spectrometerHBH ) as a new PMC member of the Apache TVM.
Bohan has been an active TVM contributor for years. He has been leading the design and contributing to several important components of TVM, including:
- TensorIR
- MetaSchedule
- Auto Tensorization
- Arithmetic analysis
- BYOC and CUTLASS integration
- State-of-the-art performance of LLM and diffusion models
Besides he has been actively participating in the discussions in the forum and helping managing PRs and issues.
- [Commits History](https://github.com/apache/tvm/pulls?q=is%3Apr+author%3AspectrometerHBH+)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3AspectrometerHBH+)
- [Community Forum …
> [Community] Bohan Hou -> PMC

- CONTRIBUTORS.md
Sorry for the late update, but please join me to welcome Qiang Zhang (@Johnson9009) as a new committer in TVM.
Qiang has been working on variant parts of TVM, including Relay, TIR, TVMScript, QNN, runtime, and RPC. Also, he has been helping with the recent releases, which are also great contributions beyond coding.
Based on the above observation, I believe he has demonstrated the qualifications to be considered as a committer.
- [Commits History](https://github.com/apache/tvm/pulls?q=+is%3Apr+author%3AJohnson9009+)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:Johnson9009)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Johnson9009/summary)
> [Community] Qiang Zhang -> Committer

- CONTRIBUTORS.md
Let's welcome Yixin Dong @Ubospica  as a new reviewer. Yixin has been contributing to CUDA tensor
core performance and TVM training.
> [COMMUNITY] New Reviewer: Yixin Dong

- include/tvm/relax/block_builder.h
- include/tvm/relax/transform.h
- python/tvm/relax/block_builder.py
- python/tvm/relax/ir/instrument.py
- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/analysis/well_formed.cc
- src/relax/ir/block_builder.cc
- src/relax/transform/normalize.cc
- tests/python/relax/test_blockbuilder_core.py
- tests/python/relax/test_transform_normalize_global_var.py
Previously BlockBuilder would have a problem about naming of public function if we 
1) emit a private function, and then 
2) emit a public function with the same name. 
Previously, BlockBuilder would rename the latter, i.e. the public function. That led the name of the public function did not match the name of its global_symbol attribute.
To tackle this problem, this PR introduces a new pass NormalizeGlobalVar. This pass will possibly rename the GlobalVar in an IRModule to ensure these properties:
1. (Invariant) First ensure every public function has the same name as its "global_symbol" attribute ;
2. To ensure 1., we may need to rename private functions with conflicting names; 
3. Finally, the name of every GlobalVar is unique in the IRModule.
This PR adds a member function …
> [Unity][BlockBuilder] Depracate `BlockBuilder.get()` and change it to `BlockBuilder.finalize()`

- python/tvm/relay/frontend/pytorch.py
`self.infer_type()` returns [tvm.ir.TensorType](https://tvm.apache.org/docs/reference/api/python/ir.html#tvm.ir.TensorType) so we need `.dtype` to get the data type.
Fix #16126
cc @jikechao @vvchernov @Hzfengsy @masahi
> [BugFix] [Relay][Pytorch] Fix missing `.dtype` 

- python/tvm/relay/frontend/keras.py
- tests/python/frontend/keras/test_forward.py
Fixed the bug in keras frontend for inception_v3 keras in concat convertion for NCHW.
> [FRONTEND][KERAS] Fix bug concat convert for NCHW

- web/emcc/wasm_runtime.cc
Import NVTX in wasm runtime to fix missing functions in webgpu.
> [Unity][Web] Fix missing function NVTXScopedRange for web

- python/tvm/relax/backend/contrib/cublas.py
- python/tvm/relax/backend/contrib/cudnn.py
- python/tvm/relax/backend/contrib/cutlass.py
- python/tvm/relax/backend/utils.py
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
Added checks to prevent cyclic dependency between groups during fusion
cc @masahi @Hzfengsy
> [Unity, BYOC] Add check for leaking intemediate variables for cublas and cudnn

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Fix #15361
Support [torch.nn.functional.scaled_dot_product_attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) and [torch.nn.Transformer](https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html).
cc @jikechao @vvchernov @Hzfengsy @masahi
> [Relay][Pytorch] Add support for `aten::scaled_dot_product_attention`

- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_tir.py
Prior to this commit, `FuseTIR` required the symbolic shape of an argument to be a structural match to the symbolic shape of a parameter.  As a result, erroneous failures to match would occur when the dynamic shape parameter contains expressions, and the static shape argument does not.  For example, a parameter `[n, m, n*m]` is not structurally matched to an argument `[16, 16, 256]`, but is a valid substitution.  This commit updates `FuseTIR` to handle these cases.
> [Unity][Bugfix] Handle symbolic matching with non-structural match

- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/transform/legalize_ops/nn.py
- tests/python/relax/test_transform_legalize_ops_nn.py
The gelu_tanh computation (e.g. the gelu_new activation in huggingface API) is incorrect in the current relax code. This PR fixes the bug.
Correctness testing passes (which fails previously):
```
inp = torch.randn((2, 4), dtype=torch.float32)
def tanh_gelu(input):
return 0.5 * input * (1.0 + np.tanh(np.sqrt(2.0 / np.pi) * (input + 0.044715 * torch.pow(input, 3.0))))
out1 = tanh_gelu(inp)
class TanhGelu(nn.Module):
def __init__(self):
pass
def forward(self, x: nn.Tensor):
return op.gelu(x, "tanh")
forward_spec = {"forward": {"x": spec.Tensor([2, 4], dtype="float32")}}
gelu = TanhGelu().jit(forward_spec)
out2 = gelu['forward'](inp)
assert torch.allclose(out1, out2)
```
Updated unit tests
> [Unity][BugFix] Fix a bug in relax gelu_tanh computation

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Fix #16150 
cc @jikechao @vvchernov @Hzfengsy @masahi
> [Relay][Pytorch] Fix bug when converting models with torch.nn.ParameterList

- include/tvm/relax/transform.h
- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/expand_tuple_arguments.cc
- tests/python/relax/test_transform_expand_tuple_args.py
Relax functions used as subroutines may receive a tuple of arguments, but only use a subset of the arguments provided.  For externally-exposed functions, this is unavoidable, as the function signature may not be updated without breaking compatibility.  For internal functions, all callsites are contained within the `IRModule`, and can be updated at the same time as the function signature.
This PR implements `ExpandTupleArguments`, which replaces `R.Tuple` parameters with separate parameters, when they occur in a private function.
> [Unity][Transform] Implement ExpandTupleArguments

- src/runtime/metal/metal_device_api.mm
metal warp size should be 1 on x86 device, but 32 on M1/M2 device
> [Device][Metal] Fix metal warp size

- src/runtime/relax_vm/ndarray_cache_support.cc
- web/src/runtime.ts
This PR is essentially https://github.com/apache/tvm/pull/16078 but for web runtime.
Add function `getParamsFromCacheByName()` for web runtime, hence creating `CreateByName()` in ndarray cache. `Create()` to `GetParams()` is analogous to `CreateByName()` to `GetParamsByName()`.
> [Unity][WebGPU] Get params from cache by name

- src/runtime/contrib/miopen/conv_forward.cc
My env：AMD RX 7600
I debugged the MIOpen source code for a specific reason. During the model compilation phase, the Python side calls the conv2d.setup interface, invoking MIOpen's findConvForwardAlgorithm interface to find the appropriate algorithm. Subsequently, the corresponding <layer-Problem, Algorithm> pair is registered within the current invokers. Then, without terminating the current process, during the inference stage, the invoker can identify the Algorithm for the corresponding layer-problem and perform direct inference.
However, if the current process is exited and the pre-compiled model is executed without the prior invocation of findConvForwardAlgorithm during the compilation phase, the corresponding <layer-Problem, Algorithm> pair won't be registered within the invokers. As …
> [BugFix] Fix the error of reloading the model library on the ROCm platform: "MIOpen Error: No invoker was registered for convolution forward.”

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
Prior to this commit, the `CanonicalizeBindings` transform handled trivial bindings, including binding of a `DataflowVar` to a `Var`, and usage of `Var` where a `DataflowVar` should be used instead.  However, it did not handle the case where both of these occur at the same time.  That is, a binding of `var_x = dataflow_y`, where `var_x` is only used within the dataflow block.  For these cases, `CanonicalizeBindings` would need to be run repeatedly.
This commit updates `CanonicalizeBindings` to check if a trivial binding is used outside the dataflow block.  This avoids producing output that requires further canonicalization.
> [Unity] Check usage location when canonicalizing trivial bindings

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
I think it is a quite simple problem, 
`aten::concat` is just an alias of `aten::cat`, but it is not supported.
https://github.com/pytorch/pytorch/blob/3fbfa8cd0a5cefadb3f116c5cd0d60e96ab8c99e/aten/src/ATen/native/TensorShape.cpp#L667
If needed, I will add a minimal example to reproduce.
```
torch==2.1.1+cpu
numpy==1.23.5
```
> [Relay][Frontend] Add support for aten::concat

- python/tvm/relax/expr.py
- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/inline_functions.cc
- tests/python/relax/test_inline_functions.py
- tests/python/relax/test_transform_inline_private_functions.py
This commit adds the ability to inline one Relax function into another.  This is provided with two APIs, one which allows explicit specification of the functions to be inlined, and one which inlines
every private Relax function in an `IRModule`.  Function inlining with explicit replacements is intended for use by an end-user when building a model function (e.g. inlining of a rotary embedding), and the second is intended for use as part of a generic optimization pipeline.
> [Unity][Transform] Implement Relax function inlining

- python/setup.py
Previously, `python/setup.py` missed to take the inplace build case into account when doing file operations (such as finding paths or copying files), which makes command `make cython` fail.
This PR fixes the issue by checking inplace builds.
> [Python] Fix setup.py for inplace build

- python/tvm/relax/frontend/nn/modules.py
This is motivated by supporting models like GPTNeoX that have the field `ffn_out_dtype` in config, making us set it as `out_dtype`.
After the `matmul`, `x` would have type `out_dtype` (`x = op.matmul(x, w, out_dtype=self.out_dtype`).
When `bias=True`, we want `bias` to be of type `out_dtype`, even if we call `to()`; otherwise, we may have a type mismatch when computing `x + self.bias`.
Same idea applies for `nn.MultiLinear`.
> [Unity] Support out dtype for nn.Linear and nn.MultiLinear

- include/tvm/relax/struct_info.h
- src/relax/ir/struct_info.cc
- src/relax/op/ccl/ccl.cc
- src/relax/op/distributed/distributed.cc
- src/relax/op/image/resize.cc
- src/relax/op/nn/attention.cc
- src/relax/op/nn/convolution.cc
- src/relax/op/nn/nn.cc
- src/relax/op/nn/pooling.cc
- src/relax/op/tensor/binary.cc
- src/relax/op/tensor/create.cc
- src/relax/op/tensor/index.cc
- src/relax/op/tensor/manipulate.cc
- src/relax/op/tensor/search.cc
- src/relax/op/tensor/set.cc
- src/relax/op/tensor/statistical.cc
Prior to this commit, the `TensorStructInfo` constructor took as input a `VDevice`, with a default value of `VDevice()`, and then assigned it to a member of type `Optional<VDevice>`.  This commit changes the constructor signature to match the member type, which will remove unnecessary type conversions when copying a `TensorStructInfo`.
> [Unity] De-duplicate calls to TensorStructInfo constructor

- include/tvm/topi/transform.h
- rust/tvm/src/ir/module.rs
- src/ir/module.cc
- tests/python/relay/test_json_compact.py
- tests/python/relay/test_py_converter.py
- tests/python/relay/test_vm.py
- tests/scripts/task_python_integration.sh
Unity branch does not enable all upstream tests by default. This commit fixes part of the tests on the main branch.
> [Unity] Fix upstream tests that fail on unity branch

- include/tvm/tir/data_type_rewriter.h
- src/tir/ir/data_type_rewriter.cc
There is a corner case: A[i] = i for IndexDataTypeNormalizer. In current implementation, the var in buffer index will be rewritten, but the var in BufferStore value will not, which cases a conflict and produces free var. I change it to two iterations: the first collects var_remap_, and the second rewrites vars, so that in A[i] = i, both var will be rewritten.
> [Unity] Fix IndexDataTypeNormalizer so that it correctly handles corner case

- python/tvm/relay/frontend/pytorch.py
By numpy, usage of `np.int` has been deprecated in [1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).
This patch fixes from `np.int` to `int` in pytorch slice converter, makes it compatible with brand-new numpy.
> remove deprecated np.int in slice converter (pytorch)

- src/tir/transforms/ir_utils.cc
ConvertSSA is called in SplitHostDevice. The vars which only exists in T.launch_thread extent in device function must be the same as host function, so we need to let ConvertSSA process host function first to avoid var redefine.
> [TIR] ConvertSSA process entry func first

- src/tir/transforms/merge_dynamic_shared_memory_allocations.cc
- tests/python/tir-transform/test_tir_transform_merge_dynamic_shared_memory_allocations.py
The MergeDynamicSharedMemoryAllocations currently will first free and then allocate for each scope. However, when a buffer is allocated and freed within a leaf scope, it will run into a free before alloc bug.
This commit solves this bug by delaying the leaf free after the alloc is done.
A simple test case is also added
```python
import tvm
import tvm.testing
class TestLeafAllocFree(tvm.testing.CompareBeforeAfter):
transform = tvm.tir.transform.MergeDynamicSharedMemoryAllocations()
def before(self):
@T.prim_func
def func():
threadIdx_x = T.launch_thread("threadIdx.x", 128)
A_sh_data = T.allocate([128], "float32", "shared.dyn")
B_sh_data = T.allocate([128], "float32", "shared.dyn")
A_sh = T.decl_buffer([128], "float32", data=A_sh_data, scope="shared.dyn") …
```
> [BugFix][TIR] Fix dynamic smem merge leaf alloc

- include/tvm/topi/transform.h
- python/tvm/relax/transform/legalize_ops/index.py
- src/topi/transform.cc
- tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py
strided slice with symbolic bounds is supported in topi, this PR remove the check for dynamic shape in legalization. It also fixed calculation of output shape when stride != 1
cc @Lunderberg @Hzfengsy
> [Unity] Fix legalizing strided slice

- include/tvm/tir/data_type_rewriter.h
- src/tir/ir/data_type_rewriter.cc
Reverts apache/tvm#16235
To first avoid the breaking testcases
> Revert "[Unity] Fix IndexDataTypeNormalizer so that it correctly handles corner case"

- src/relax/ir/block_builder.cc
- tests/python/relax/test_blockbuilder_core.py
Prior to this commit, the normalizer printed a warning whenever a lowering pass produced a `SeqExpr` containing a non-dataflow `BindingBlock` within a `DataflowBlock`.  This intermediate is only ill-formed if the non-dataflow `BindingBlock` makes use of any `DataflowVar` instances, as the `BindingBlock` can otherwise be hoisted out.
This commit explicitly checks for use of `DataflowVar` in these cases, as this is most likely due to erroneous use of `BindingBlock` where `DataflowBlock` should be used, and changes the severity from `WARNING` to `FATAL`.  If there are no `DataflowVar` instances used in the `BindingBlock`, no warning is required.
> [Unity] Improved error checking for DataflowBlock in nested SeqExpr

- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/runtime/relax_vm.py
- src/runtime/relax_vm/builtin.cc
- tests/python/relax/test_frontend_nn_debug.py
- tests/python/relax/test_frontend_nn_op.py
This PR enhances `tvm.relax.frontend.nn.op.print_` that allows
one to call debugging methods registered in runtime.
Example:
```python
class Layer(nn.Module):
def forward(self, x: nn.Tensor):
op.print_(x)
return x
```
During runtime, whenever this line is executed, it prints:
```
/workspace/main.py:36: shape = (10, 5), dtype = float32, data =
[[9.1025043e-01 5.6659997e-01 8.7828696e-01 5.5273587e-01 1.8565023e-01]
[8.0204010e-04 5.5512893e-01 9.7184986e-01 3.2060379e-01 7.5654179e-01]
[9.5829505e-01 7.7954692e-01 1.3110173e-01 3.7674886e-01 3.3243084e-01]
[6.4045572e-01 7.4083984e-02 7.2492689e-01 4.4675517e-01 2.1010166e-01]
[2.7612233e-01 5.7471478e-01 8.5393274e-01 9.1640389e-01 1.5394652e-01]
[7.7940112e-01 2.3211378e-01 6.0200381e-01 5.9336245e-01 9.2999905e-01]
[5.0383198e-01 …
```
> [Unity] Add runtime debugging method to RelaxVM

- src/target/tag.cc
cc @junrushao @zxybazh @masahi
Looking at the [NVIDIA documentation](https://www.nvidia.com/content/dam/en-zz/Solutions/gtcf21/jetson-orin/[nvidia-jetson-agx-orin-technical-brief.pdf](https://www.nvidia.com/content/dam/en-zz/Solutions/gtcf21/jetson-orin/nvidia-jetson-agx-orin-technical-brief.pdf)), there are 32GB and 64GB models. The former has 8-core and the latter has 12-core. So, I defined them with different tags.
> [Target] Add Jetson AGX Orin tags

- python/tvm/contrib/msc/core/runtime/runner.py
- python/tvm/contrib/msc/core/tools/__init__.py
- python/tvm/contrib/msc/core/tools/quantize/__init__.py
- python/tvm/contrib/msc/core/tools/quantize/method.py
- python/tvm/contrib/msc/core/tools/quantize/quantizer.py
- python/tvm/contrib/msc/core/utils/file.py
- python/tvm/contrib/msc/core/utils/info.py
- python/tvm/contrib/msc/framework/tensorflow/tools/__init__.py
- python/tvm/contrib/msc/framework/tensorflow/tools/quantize/__init__.py
- python/tvm/contrib/msc/framework/tensorflow/tools/quantize/quantizer.py
- python/tvm/contrib/msc/framework/tensorrt/codegen/sources.py
- python/tvm/contrib/msc/framework/tensorrt/runtime/runner.py
- python/tvm/contrib/msc/framework/tensorrt/tools/quantize/__init__.py
- python/tvm/contrib/msc/framework/tensorrt/tools/quantize/method.py
- python/tvm/contrib/msc/framework/tensorrt/tools/quantize/quantizer.py
- python/tvm/contrib/msc/framework/torch/tools/__init__.py
- python/tvm/contrib/msc/framework/torch/tools/quantize/__init__.py
- python/tvm/contrib/msc/framework/torch/tools/quantize/method.py
- python/tvm/contrib/msc/framework/torch/tools/quantize/quantizer.py
- python/tvm/contrib/msc/framework/tvm/tools/__init__.py
- python/tvm/contrib/msc/framework/tvm/tools/quantize/__init__.py
- python/tvm/contrib/msc/framework/tvm/tools/quantize/method.py
- python/tvm/contrib/msc/framework/tvm/tools/quantize/quantizer.py
- python/tvm/contrib/msc/pipeline/manager.py
- tests/python/contrib/test_msc/test_tools.py
This is the Milestone 2 for MSC: Use msc.runtime.Manager to manage the compiling pipeline && tools.
To limit each PR in reviewable size, the Milestone 2 will be split into some steps:
M2.1 Add Manager for compile pipeline
M2.2 Add pruner for model pruning
M2.3 Add tracker for track layer datas
**M2.4 Add quantizer for quantize model**
Quantization is widely used as model optimization methods. MSC implementation of quantizer differs from other frameworks. The quantization process is described as a tool and dispatched to torch/tvm/tensorrt when needed. In this way, the quantization of …
> [Unity][MSC][M2.4] Add quantizer for quantize model

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
Removes the restriction on converting quantized mirror pad in the front-end and adds tests to support this change.
cc @leandron @neildhickey
> [TFLite] Add support for quantized mirror pad

- python/tvm/relax/pipeline.py
- python/tvm/relax/vm_build.py
In sophisticated usecases, developers may want full control of the relax compilation pipeline. A typical workflow looks like:
- Step 1. Apply a custom relax.pipeline to IRModule
- Step 2. Invoke `relax.build` to export relax Executable but without any additional passes;
- Step 3. Manipulate the relax Executable.
In the three steps above, both Step 1 and 3 are already supported, and this PR aims to enable Step 2, which allows `relax.build` to apply a `None` pipeline which contains no passes.
Note: as an advanced behavior, this is enabled only when explicitly setting `pipeline=None` and thus backward compatibility is fully preserved.
> [Unity][VM] Allow `pipeline=None` in `relax.build`

- src/tir/transforms/loop_partition.cc
- tests/python/tir-transform/test_tir_transform_loop_partition.py
This PR tries to fix a bug of the pass LoopPartiton. When there are one or more tensors containing a shape 1 in the concat dim, the pass will unroll the loops wrongly after partitioning. For example:
```python
@T.prim_func
def concat_func_single_point(
placeholder: T.Buffer((28, 64), "int8"),
placeholder_1: T.Buffer((28, 1), "int8"),
placeholder_2: T.Buffer((28, 63), "int8"),
T_concat: T.Buffer((28, 128), "int8"),
) -> None:
for i0 in range(28):
for i1 in T.serial(128, annotations={"pragma_loop_partition_hint": 1}):
if i1 > 63:
T_concat[i0, i1] = placeholder[i0, i1 - 64]
elif i1 == 63:
T_concat[i0, i1] = placeholder_1[i0, i1 - 63]
else:
T_concat[i0, i1] = placeholder_2[i0, i1]
```
after LoopPartition:
```python
@T.prim_func
def expected_partitioned_concat_single_point(
placeholder: …
```
> [LoopPartition] Fix a bug of LoopPartition in single point scenarioes

- src/node/script_printer.cc
- src/relax/ir/dataflow_matcher.cc
- src/runtime/contrib/cublas/cublas_json_runtime.cc
- src/runtime/contrib/cudnn/cudnn_json_runtime.cc
- tests/python/relax/test_dataflow_pattern.py
`std::regex` in TVM codebase may cause a symbol conflict with PyTorch, we temporarily disable it before we find a better solution, meanwhile the current usage of `std::regex` is not necessary.
cc @tqchen
> [Unity] Avoid to use `std::regex`

- ci/jenkins/unity_jenkinsfile.groovy
CPU-SMALL nodes are unstable and often fail to build. This patch enables spot nodes in CI to reduce the cost.
cc @tqchen
> [Unity] Enable spot nodes in CI

- python/tvm/contrib/cc.py
- python/tvm/relax/frontend/nn/__init__.py
- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/exporter.py
- python/tvm/relax/frontend/nn/extern.py
- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/frontend/nn/spec.py
- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/attach_external_modules.py
- python/tvm/relax/vm_build.py
- python/tvm/runtime/ndarray.py
- python/tvm/target/detect_target.py
- tests/python/relax/frontend_nn_extern_module.cc
- tests/python/relax/test_frontend_nn_extern_module.py
- tests/python/relax/test_frontend_nn_modules.py
`nn.ExternModule` allows incorporation of handcrafted kernels into the compilation stack and being invoked by Relax just like TIR or any other ordinary operator. This PR simplifies its workflow.
The system consists of the abstract base class `ExternModule` and its two derivatives:
- `.o` (object files) can be linked using `ObjectModule`.
- `.cpp` (C++ files) and `.cu` (CUDA files) can be compiled and linked into the system usung `SourceModule`.
**Symbols, and shape/dtype inference.** To provide the system with sufficient information about the kernels, it is required to provide all symbols of an external module, as well as a method for each symbol that tells the system about the output dtype/shape of this symbol.
Consider a case where function `my_func` accepts two tensors, `a` of shape …
> [Unity][nn.Module] Refactor `ExternModule`

- python/tvm/contrib/cutlass/gen_tensor_op.py
As dense op is not used in `relax`, the cutlass codegen is not tested. However, the codegen is broken for dense op. This PR fixes the codegen.
cc @yelite @junrushao
> [Unity] Fix Cutlass Codegen for Dense

- src/arith/ir_mutator_with_analyzer.cc
- tests/python/tir-transform/test_tir_transform_simplify.py
When constant is appearing in the else_expr, Simplifier pass is able to simplify the nested if_then_else expression and eliminate the redundant if_then_else. But, when constant is appearing in the then_expr, it is unable to simplify the nested if_then_else statements.
The changes in the PR will address the above problem.
> [ARITH] Simplify nested if_then_else when constant is appearing in then_expr

- src/runtime/contrib/cutlass/weight_preprocess.cc
- tests/scripts/task_config_build_gpu.sh
Updated preprocessing and submodule the support 3D weight for MoE.
cc @masahi
> [Unity] Bump fpA_intB_gemm

- python/tvm/relay/op/strategy/generic.py
- python/tvm/topi/generic/nn.py
- python/tvm/topi/nn/conv1d_transpose.py
- python/tvm/topi/testing/__init__.py
- python/tvm/topi/testing/conv1d_transpose_ncw_python.py
- tests/python/topi/test_topi_group_conv1d_transpose_ncw.py
This PR adds support for `group_conv1d_transpose_ncw` generic.
> [Relay][TOPI] Add support for group_conv1d_transpose_ncw for generic

- src/tir/schedule/transform.cc
Previously, TileWithTensorIntrin tried to inline all producers into padding blocks once padding happened even if only one producer was padded.
This PR fixes that.
Possibly related issue: https://github.com/apache/tvm/issues/15446
cc @tqchen  @junrushao
> [TIR][Schedule] TileWithTensorIntrin skip incorrect ComputeInline for input-padding

- python/tvm/ir/module.py
Add the missing `import ast`. @tqchen
> [Unity] Add missing library import 

- python/tvm/relay/frontend/keras.py
- python/tvm/relay/op/contrib/clml.py
- src/relay/backend/contrib/clml/codegen.cc
- src/runtime/contrib/clml/clml_runtime.cc
- tests/python/contrib/test_clml/conftest.py
- tests/python/contrib/test_clml/infrastructure.py
- tests/python/contrib/test_clml/test_network.py
- tests/python/contrib/test_clml/test_ops.py
- tests/scripts/task_python_adreno.sh
CLML multiple bug fix and restructuring
1. Fixed the dense op failure in network test case.
2. Fixed the bugs for Float16 test case
3. Restructure the test cases for CLML with more coverage.
> [RUNTIME][CLML] Fix for CLML ops and enable more test case

- python/tvm/relay/op/strategy/generic.py
- python/tvm/topi/generic/nn.py
- python/tvm/topi/nn/conv3d_transpose.py
- python/tvm/topi/testing/conv3d_transpose_ncdhw_python.py
- tests/python/topi/test_topi_group_conv3d_transpose_ncdhw.py
This PR adds support for `group_conv3d_transpose_ncdhw` generic.
(Similar to https://github.com/apache/tvm/pull/16248.)
cc @quic-sanirudh
> [TOPI] Add support for group_conv3d_transpose_ncdhw for generic

- src/script/printer/tir/stmt.cc
- tests/python/tvmscript/test_tvmscript_printer_annotation.py
cc @junrushao @cyx-6 
Hi, the change want to disable the concise scoping print on nested scope stmts, when some of the stmt is annotated. 
The annotated python comments would disappear since under consice scoping, the stmt is converted to `StmtBlockDocNode` which would not bind annotations.
> [TVMScript] Disable concise scoping when the scope stmt is explicitly annotated

- python/tvm/relax/frontend/nn/op.py
Follow-up of https://github.com/apache/tvm/pull/16247
> [Unity][nn.Module] Support Runtime-Calling Any PackedFunc via `op.extern`

- src/runtime/relax_vm/kv_cache.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache.py
This PR refactors the previous PagedAttentionKVCache, and provides a common attention KV cache interface `src/runtime/relax_vm/kv_cache.h` for efficient K/V data management and attention computation.
The refactored PagedKVCache supports common prefix caching: if two sequences have a shared prefix (e.g., a system prompt, or a context document), we can first add the prefix into KV cache, and then fork the two child sequences from the prefix, and add their respective exclusive parts to KV cache. In such case, the KV data of the shared prefix is computed only once, and can be reused for multiple times.
This PR adds tests for the refactored PagedKVCache `tests/python/relax/test_runtime_builtin_paged_attention_kv_cache.py`. The tests at this moment depends on FlashInfer …
> [Unity] Unified KV cache interface and PagedKVCache refactor

- python/tvm/contrib/msc/core/runtime/runner.py
- python/tvm/contrib/msc/core/tools/__init__.py
- python/tvm/contrib/msc/core/tools/distill/__init__.py
- python/tvm/contrib/msc/core/tools/distill/distiller.py
- python/tvm/contrib/msc/core/tools/distill/method.py
- python/tvm/contrib/msc/core/utils/expr.py
- python/tvm/contrib/msc/core/utils/file.py
- python/tvm/contrib/msc/framework/tensorflow/tools/__init__.py
- python/tvm/contrib/msc/framework/tensorflow/tools/distill/__init__.py
- python/tvm/contrib/msc/framework/tensorflow/tools/distill/distiller.py
- python/tvm/contrib/msc/framework/tensorrt/tools/__init__.py
- python/tvm/contrib/msc/framework/tensorrt/tools/distill/__init__.py
- python/tvm/contrib/msc/framework/tensorrt/tools/distill/distiller.py
- python/tvm/contrib/msc/framework/torch/tools/__init__.py
- python/tvm/contrib/msc/framework/torch/tools/distill/__init__.py
- python/tvm/contrib/msc/framework/torch/tools/distill/distiller.py
- python/tvm/contrib/msc/framework/torch/tools/distill/method.py
- python/tvm/contrib/msc/framework/tvm/tools/distill/__init__.py
- python/tvm/contrib/msc/framework/tvm/tools/distill/distiller.py
- python/tvm/contrib/msc/pipeline/manager.py
- tests/python/contrib/test_msc/test_tools.py
This is the Milestone 3 for MSC: Add MSCGym, enable auto compression. Add distiller, enable knowledge distilliation.
To limit each PR in reviewable size, the Milestone 3 will be split into some steps:
M3.1 Add distiller for distill model
M3.2 Add gym for pruning and quantization, enable auto prune/quantize
Distillation is common used method for model pruning and quantization. It optimize a student model and distill it with teacher model. Runner build the teacher model via disabling MSC tools while build student model via enabling the tools. The distiller then bind teacher and …
> [Unity][MSC][M3.1] Add distiller for distill model

- python/tvm/relay/frontend/pytorch.py
Replace the deprecated API `np.int` with `int` to avoid a crash.
In NumPy v1.20.0, the `np.int` has been deprecated as shown in the [documentation](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated)
> replace deprecated np.int with int to avoid crash

- python/tvm/relax/frontend/nn/_tensor_op.py
- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This PR adds support for `tensor_ir_op` in NNModule, which enables us to call TensorIR function in NNModule.
Also this PR adds a test case for extern op.
cc @junrushao @MasterJH5574
> [Unity][Frontend] NNModule `tensor_ir_op` support

- python/tvm/relay/frontend/pytorch.py
This PR fixes a logical bug in your code.
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [pytorch.py](https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/pytorch.py#L599), method: `tensor_split`, a logical equality check operation was performed. The operands are such that the comparison operation always returns either true or false. Such logical short circuits in code lead to unintended behavior. iCR suggested that the logical operation should be reviewed for correctness.
In the `tensor_split` method, there's a comparsion that checks if the input tensor is zero-dimensional or one-dimensional long tensor. In the comparsion, there's a typo that converts the shape of the tensor to a list and compares against integer.
Running an …
> [BugFix] Fixed Inappropriate Logical Expression

- python/tvm/relay/frontend/qnn_torch.py
This PR solves the problem of not finding the key of `param_debug_name_map` with "name", an attribute of `prim::GetAttr`, when `inline_input_quant_params_for_fx` replacing `prim::GetAttr` with `prim::Constant`. This problem occurs when the model is quantized by each sub-models with quantize_fx, and the zero point and scale variable names are different from the name, the attribute of `prim::GetAttr`. To solve this, when modifying all `prim::GetAttr` to `prim::Constant`, modify to access `param_debug_name_map` by using the `node.output.debugName()` . The reason is that `nodes.output().debugName()` as shown pattern like `.<number>` at the end of their names, which distinguishes same name and that can be found in `param_debug_name_map`
- simple example
```
import torch
import tvm.relay as …
```
> [Relay][Frontend][QNN] fix access `param_debug_name_map` to node output name in fx-quantized graph node replacement

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
Prior to this PR, the memory planning for different Relax functions are not independent -- storage tokens are shared across different Relax functions.
This will incur memory overuse sometimes. For example, tensor `A` in `func1` has 128 bytes, tensor `B` in `func2` has 2048 bytes. If the memory planning decides to share the storage token for `A` and `B`, the shared token will have size 2048 bytes.
Consider the case when at runtime only `func1` is executed, and `func2` is never invoked. In this case, only 128 bytes for tensor `A` is needed, while a total 2048-chunk is allocated in total, which is a 16x memory overuse.
This PR makes the memory planning across different Relax function independent. That means in the example above, when only `func1` is executed, only 128 bytes will be …
> [Unity] Ensure memory planning cross-function independence

- python/tvm/relax/frontend/nn/__init__.py
- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/exporter.py
- python/tvm/relax/frontend/nn/spec.py
This PR supports `Object` as a new spec/frontend type in nn.Module, so that non-tensor opaque objects (such as PagedKVCache) can be effectively represented.
One unit test for PagedKVCache is added.
> [Unity][Frontend] Introducing Object

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Recently, I worked with the Stable Video Diffusion model, which contains the `aten::broadcast_to` op， but TVM does not support it. 
Add support for it here.
> [Relay][Frontend][Torch] add aten:broadcast_to 

- web/emcc/wasm_runtime.cc
- web/src/runtime.ts
Currently when loading the params, we try to decode from bf16 to f32 regardless of the dtype of the param, since all the params are stored with "format=f32-to-bf16" in the record regardless of the dtype.
We solve it by checking the dtype as well, just like the C++ counter part:
https://github.com/apache/tvm/blob/4e66690a4d033af912f5051c0e5a16c9c10691d9/src/runtime/relax_vm/ndarray_cache_support.cc#L168-L172
> [Unity][Web][Fix] Fix fetchNDArray for f32-to-bf16

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This PR introduces an operator `op.empty` in the `nn.Module` frontend. It helps us to create an uninitialized memory from the memory pool, which could be used as temporary scratchpad memory to handcrafted operators.
> [Unity][nn.Module] Introduce operator `empty`

- src/runtime/relax_vm/paged_kv_cache.cc
This PR fixes PagedKVCache due to recent FlashInfer interface change, and also bumps FlashInfer to the latest.
> [Unity] Fix PagedKVCache per FlashInfer update

- docs/dev/how_to/relay_add_op.rst
This PR fix a minor error in doc [Add an operator to Relay](https://tvm.apache.org/docs/dev/how_to/relay_add_op.html)
> [Doc] Fix minor error in doc (Add an operator to Relay)

- python/tvm/relay/testing/yolo_detection.py
This is a pull request for Yolo detection boxes helper functions.
Tracking issue: [#16268](https://github.com/apache/tvm/issues/16268)
Update to use a replacement function for the removed function so that it can be executed in Pillow version 10 or later.
> [BugFix] Update pillow usage

- python/tvm/topi/math.py
metal does not support float64, so I change this behavior
> Change metal dtype of ceil_log2 to fp32

- docker/install/ubuntu_install_cmake_source.sh
This is to enable setting CMAKE_CUDA_ARCHITECTURES to the special value 'native'.
cc @junrushao @tqchen
> [CI] Upgrade cmake version to 3.24.0

- python/tvm/relax/frontend/nn/op.py
in call_tir's signature,  the type annotation of`tir_vars` is `Optional[Union[ShapeExpr, Tuple[PrimExpr], List[PrimExpr]]]`. This PR makes the signature consistent
> [Unity] Fix nn.op.tensor_ir_op signature

- include/tvm/tir/transform.h
- python/tvm/tir/transform/transform.py
- src/tir/ir/specialize.cc
- src/tir/transforms/inline_private_functions.cc
- tests/python/tir-base/test_tir_specialize.py
- tests/python/tir-transform/test_tir_inline_private_functions.py
The functionality to express a call from one `PrimFunc` to another was introduced in https://github.com/apache/tvm/pull/14889.  While this was initially planned to be supported at codegen for all targets (see https://github.com/apache/tvm/pull/15835), this resulted in breakage on some backends (see https://github.com/apache/tvm/pull/16033). After discussion, the plan was changed to support TIR inlining, which would enable the same high-level functionality in TIR without requiring immediate low-level support across all codegens.
This commit implements and tests a new IRModule transform `InlinePrivateFunctions`, which can be used as part of lowering in a follow-up commit.
Because this is initially implemented for use quite late in the lowering flow, many constructs are not currently …
> [TIR][Transform] Implement InlinePrivateFunctions

- include/tvm/tir/analysis.h
- src/te/operation/create_primfunc.cc
- src/tir/analysis/verify_well_formed.cc
- src/tir/ir/tir_visitor_with_path.cc
- src/tir/ir/tir_visitor_with_path.h
- src/tir/transforms/ir_utils.cc
- src/tir/transforms/split_host_device.cc
- tests/python/tir-analysis/test_tir_analysis_verify_well_formed.py
- tests/python/tir-transform/test_tir_transform_convert_ssa.py
- tests/python/tir-transform/test_tir_transform_split_host_device.py
Otherwise, they would be undefined after being de-duplicated by `ConvertSSA`.
> [TIR] In SplitHostDevice, check for variables in thread extents

- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_tir.py
Prior to this commit, the `FuseTIR` pass explicitly tracked usage of
tuple arguments, to minimize the set of arguments provided to each
kernel.  The additional tgracking and handling of partially-used
tuples makes it difficult to follow the primary changes being made by
`FuseTIR`.
This commit implements the same functionality in terms of the
`ExpandTupleArguments` and `RemoveUnusedParameters` transforms,
introduced in https://github.com/apache/tvm/pull/16115 and
https://github.com/apache/tvm/pull/16116 respectively.  By using these
passes before the main `FuseOps` changes, partial tuple usage is
already handled at that point.
This commit is intended to minimize any changes to user-facing
behavior, and so these pre-process passes are currently used
internally by `FuseTIR`.  This may be …
> [Unity][Transform] Extract partial-tuple-usage from FuseTIR

- tests/python/contrib/test_hexagon/test_pass_fq2i_avg_pool2d.py
The `test_pass_fq2i_avg_pool2d.py::test_avgpool_conv2d` test is sensitive to rounding errors, and failed about a third of the time (42 / 100 tests).  This was first noticed as CI failures in unrelated PRs (e.g. https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-hexagon/detail/PR-16184/6/tests). This commit marks the flaky portions of the test with `pytest.mark.xfail`, to avoid causing breaking CI for other PRs.
To minimize the extent of the disabled test cases, this commit breaks up each of the unit tests.  Where previously a single test performed both hardware/simulation tests and relay graph comparisons, these are now done in separate test functions.  The hardware/simulation tests use `tvm.testing.assert_allclose` and have a tolerance of `1e-02`, while the graph-comparison tests use …
> [Hexagon][UnitTest] Disable flaky quantization test

- tests/python/relax/test_frontend_onnx.py
The `tests/python/relax/test_frontend_onnx.py::test_attention` unit test currently has sporadic failures (5/200 executions), which can cause failures for unrelated changes
(e.g. [PR#16304](https://github.com/apache/tvm/pull/16304), [CI link](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-unity/detail/PR-16304/3/pipeline)).
This commit specifies a tolerance to use for comparisons, to avoid these spurious CI failures.
> [Unity][UnitTest] Increase atol to resolve flaky CI failure

- src/relax/transform/alter_op_impl.cc
- tests/python/relax/test_transform_alter_op_impl.py
This PR handles a bug in Alter op impl.
When output does not need to be transform for an op in alter op impl, segmentation fault occurs due to nullptr exception.
This exception has been handled and the corresponding test case for the same has been updated.
> [Unity] Alter op impl handling empty transform for output

- docs/reference/langref/relay_expr.rst
This PR fixes minor error in [Expressions in Relay](https://tvm.apache.org/docs/reference/langref/relay_expr.html#let-bindings)
> [Doc] Fix minor error in "Expressions in Relay"

- cmake/utils/CCache.cmake
For older versions of `ccache` that do not support `nvcc`, this has no effect.  For newer versions of `ccache`, this enables caching the compiled `nvcc` outputs.  This was tested using `ccache` versions 3.7.7 (does not cache `nvcc` output) and 4.8.3 (caches `nvcc` output).
This is primarily intended to reduce compilation time of cutlass kernels, which can take several minutes after switching branches.
> [CMake] Use ccache as CMAKE_CUDA_COMPILER_LAUNCHER

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/op.py
- src/target/source/codegen_c.cc
- src/target/source/codegen_cuda.cc
- src/tir/op/builtin.cc
- src/tir/transforms/storage_access.cc
- tests/python/codegen/test_target_codegen_cuda.py
Originally, it is not allowed to sync threads inside a condition `while, if`.
This PR introduces `tvm_thread_invariant` op to annotate the condition to be thread id invariant and get around the check.
> [TIR] Allow sync threads inside condition

- python/tvm/contrib/emcc.py
- web/Makefile
- web/emcc/tvmjs_support.cc
- web/package.json
- web/src/ctypes.ts
- web/src/runtime.ts
- web/tests/node/test_packed_func.js
This PR enables wasm exception propagation among
c++ runtime generated wasm and javascript.
Right now the error.message is passed back
this would allow us to do some handling in webgpu
related exceptions raised through FFI boundaries.
Note that this would require the latest emscripten and on the nodejs, --experimental-wasm-eh support.
> [Unity][WEBGPU] Enable wasm exception propagation

- CMakeLists.txt
The C++ standard requires two-phase name resolution for templates.  By default, MSVC uses a non-standard name resolution, in which all names are looked up when a template is instantiated.  This has caused MSVC-specific compilation errors ([example](https://github.com/apache/tvm/actions/runs/7400684492/job/20134841480?pr=16183)), which are quite difficult to debug.
This commit updates adds the `/permissive-` flag when building TVM with MSVC, disabling the non-standard name resolution.
> [CMake][MSVC] Disable permissive mode for MSVC builds

- python/tvm/dlight/base/schedule_rule.py
- python/tvm/dlight/gpu/base.py
- python/tvm/dlight/gpu/fallback.py
- python/tvm/dlight/gpu/gemv.py
- python/tvm/dlight/gpu/general_reduction.py
- python/tvm/dlight/gpu/matmul.py
- python/tvm/dlight/gpu/reduction.py
- python/tvm/dlight/gpu/transpose.py
This PR adds a check for GPU rules to skip if the target is not suitable for the rule.
> [DLight] Skip rule if target is not suitable

- python/tvm/dlight/base/__init__.py
- python/tvm/dlight/base/analysis.py
- python/tvm/dlight/gpu/gemv.py
- python/tvm/dlight/gpu/reduction.py
- src/tir/schedule/transform.cc
- tests/python/dlight/test_gpu_gemv.py
- tests/python/dlight/test_gpu_reduction.py
1. When user wants to partly specialize schedule, they can create an inner block and apply dlight on it. In the meanwhile, the user is free to schedule outer block. This PR supports such usecase on gemv rule. 
2. Fix loop order bugs in reduction rule.
> [Unity][Dlight] Support dlight gemv rule on nested inner block

- docker/install/ubuntu2004_install_python.sh
This is to fix installation error of ml_dtypes
cc @tqchen @junrushao
> [Docker] Upgrade pip in i386 container

- include/tvm/tir/transform.h
- python/tvm/tir/transform/transform.py
- src/driver/driver_api.cc
- src/meta_schedule/postproc/verify_gpu_code.cc
- src/tir/transforms/merge_shared_memory_allocations.cc
- src/tir/transforms/storage_rewrite.cc
- tests/python/tir-transform/test_tir_transform_inject_ptx_async_copy.py
- tests/python/tir-transform/test_tir_transform_merge_dynamic_shared_memory_allocations.py
- tests/python/tir-transform/test_tir_transform_merge_static_shared_memory_allocations.py
#759 proposed a pass `storage_rewrite` and provided a trivial storage reuse plan based on liveness analysis, just as #9341 mentioned, the solution has some limitations:
1. storage_rewrite can't handle buffer with different dtypes. 
```c++
int8 A_shared[32];
int8 B_shared[32];
int32 C_shared[4]; // will not be reused even we have enough workspace as different types. 
```
2. storage_rewrite can't allocate a buffer in the place of another 2 buffers.
```c++
int8 A_shared[32];
int8 B_shared[32];
int8 C_shared[64]; 
// will be reused as A_shared[32], B_shared[64],  results in 32 half elements space waste.
```
#8571 and #9341 introduced a pass `MergeDynamicSharedMemoryAllocations`, which can support efficient memory reuse solely for dynamic shared memory. However, sometimes we do not want to use …
> [CUDA] Simple extend to optimize reuse for static shared memory.

- python/tvm/relax/frontend/nn/_tensor_op.py
- tests/python/relax/test_frontend_nn_tensor.py
This PR introduces the following signature changes:
- `Tensor.reshape(shape)` to `Tensor.reshape(*shape)`
- `Tensor.permute_dims(axes)` to `Tensor.permute_dims(*axes)`
> [Unity] Enhance Torch-consistency in rehsape

- ci/jenkins/docker-images.ini
- ci/jenkins/generated/arm_jenkinsfile.groovy
- ci/jenkins/generated/cortexm_jenkinsfile.groovy
- ci/jenkins/generated/cpu_jenkinsfile.groovy
- ci/jenkins/generated/docker_jenkinsfile.groovy
- ci/jenkins/generated/gpu_jenkinsfile.groovy
- ci/jenkins/generated/hexagon_jenkinsfile.groovy
- ci/jenkins/generated/i386_jenkinsfile.groovy
- ci/jenkins/generated/lint_jenkinsfile.groovy
- ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy
- ci/jenkins/generated/minimal_jenkinsfile.groovy
- ci/jenkins/generated/riscv_jenkinsfile.groovy
- ci/jenkins/generated/wasm_jenkinsfile.groovy
- ci/jenkins/templates/utils/base.groovy.j2
- tests/scripts/task_show_node_info.sh
This is to integrate changes in #16336
> [CI] Update docker images tag to 20240105-165030-51bdaec6

- include/tvm/topi/nn/rms_norm.h
- python/tvm/dlight/gpu/__init__.py
- python/tvm/dlight/gpu/rmsnorm.py
- tests/python/dlight/test_gpu_rmsnorm.py
- tests/python/relax/test_transform_legalize_ops_nn.py
This PR introduces a specific rule for RMS norm in dlight, which allow the norm to now perform on par with CUTLASS standards.
New test case for the rule has also been added.
Below is the performance comparison for Llama-2-7b-chat-hf-q4f16_1.
New:
```
======================= Encoding Profiling =======================
Name                                              Time (ms)   Count   Total time (ms)   Pct (%)   Memory (MB)     Bandwidth (GB/s)  Shape
fused_fused_decode4_NT_matmul3                    0.3117      32      9.9759            33.93     48.67           152.4731          (22016, 512), (22016, 128), (1, 6, 4096), (1, 6, 22016)
fused_fused_decode5_fused_NT_matmul4_add          0.2671      32      8.5482            29.08     24.41           89.2261           (4096, 1376), (4096, …
```
> [Unity][DLight] Introduce Specific Rule for RMSNorm

- python/tvm/tir/tensor_intrin/arm_cpu.py
- python/tvm/tir/tensor_intrin/dot_product_common.py
- python/tvm/tir/tensor_intrin/rocm.py
- src/target/source/codegen_cuda.cc
- src/target/source/literal/cuda_int8_t.h
- tests/python/tir-schedule/test_tir_schedule_tensorize.py
* Update u8s8s32 s8u8s32 u8u8u32
> [TIR] Extend DP4A tensor intrin

- src/relax/ir/expr_functor.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
Resolve a bug that caused undefined relax variables in the output of `CanonicalizeBindings` for cases where `VisitVarDef(const Var&)` replaces a variable, and `VisitExpr_(const VarNode*)` returns a value with different struct info, both occurring within the same `VarBinding`.
The ExprMutator is only allowed to update a variable's struct info if the value bound to it has new struct info.  When CanonicalizeBindings replaces a trivial binding, this may provide better struct info as a result.
Prior to this commit, `ExprMutator::ReEmitBinding` defined a remap for `binding->var->vid`, even if the derived class defined a replacement by overriding `VisitVarDef`.  If the derived class defines a new variable binding by overriding `VisitVarDef`, and also causes a variable replacement by overriding …
> [Unity][Transform] Handle replacement at both var binding and usage

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
This PR adds a sanity check to ensure that all `tir_var_upper_bound` attrs used by static memory planning has integer as value type. This check helps avoid mistakes of using wrong value types.
The check is needed since `func->GetAttr<Map<String, IntImm>>` does not apply type check.
> [Unity][Fix] Memory planning check value type of 'tir_var_upper_bound'

- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_module.cc
Due to PR https://github.com/llvm/llvm-project/pull/74261, Host.h has been deprecated/moved to a new location in LLVM
> [LLVM] Update Host.h path

- docker/install/ubuntu_install_boost.sh
- docker/install/ubuntu_install_sccache.sh
Sccache was previously pinned at version 0.3.3, however, there has recently been an issue when installing some of its dependencies:
```
error[E0277]: expected a `Fn(reqwest::Request, &'a mut task_local_extensions::extensions::Extensions, reqwest_middleware::Next<'a>)` closure, found `RetryAfterMiddleware`
```
Upgrading the version of sccache to the latest seems to resolve this error.
In addition, the JFrog artifactory link for boost has been flaky recently, so changing to an alternative
mirror suggested in https://github.com/boostorg/boost/issues/842.
> [CI] Upgrade sccache version to 0.7.*

- src/runtime/cuda/cuda_device_api.cc
Using `cudaDeviceGetAttribute` will set the global error code when the device doesn't exist and will impact subsequent CUDA API calls.
cc @tqchen @junrushao
> [Runtime] Use cudaGetDeviceCount to check if device exists

- src/relay/transforms/pattern_utils.h
- src/relay/transforms/simplify_expr.cc
Because on Windows, "long double" is 64 bits instead of 128 bits like on Linux, to avoid overflow from "long double" to "int64_t"
> [Relay] make "ToScalar" support directly obtaining "int64_t"

- CMakeLists.txt
- cmake/modules/CUDA.cmake
- tests/scripts/task_config_build_gpu.sh
CI images should also be updated to install cmake 3.24
cc @tqchen @junrushao @Lunderberg
> [Unity] Set CMAKE_CUDA_ARCHITECTURES default to native

- python/tvm/topi/arm_cpu/arm_utils.py
- python/tvm/topi/arm_cpu/conv2d_gemm.py
- src/target/parsers/aprofile.cc
- tests/cpp/target/parsers/aprofile_test.cc
Optimised fp16 conv2d matrix tiling for Arm(R) Neon(TM) instructions and exposed `+fullfp16` as a target feature for Arm(R) Cortex(R) A-Profile CPUs.
Also, a target test was added to `cpptest` for Arm(R) Cortex(R) A-Profile CPUs which checks that the `has_fp16_simd` flag is set exclusively when the user explicitly passes the `+fullfp16` or `+sve` attributes and a supporting architecture version at target creation.
cc @ekalda @lhutton1 @neildhickey
> [TOPI][Target] Add fp16 SIMD support for conv2d on `arm_cpu` targets

- python/tvm/driver/tvmc/compiler.py
- python/tvm/ir/instrument.py
- tests/python/driver/tvmc/test_command_line.py
Add `--print-ir-before` and `--print-ir-after` options  to print IR before and after a named pass from the compiler's command line driver.
> [TVMC] Add tvmc flag to print ir before and print ir after named pass 

- src/tir/analysis/verify_well_formed.cc
- tests/python/tir-schedule/test_tir_schedule_error.py
During TensorIR scheduling, the `IterVar`s that represent environment threads may duplicate, i.e. it is legal to have two env threads with the same name tag, which may fail the `SingleEnvThreadVerifier` check during schedule creation. This PR disables this check in this case. In the future, it may be worthwhile to bring it back against post-scheduling TIR.
It's related to [this commit](https://github.com/apache/tvm/commit/eb15d04c3bff76062e26d5647fb8af0323de1bed). CC: @jinhongyii @Lunderberg
> [Bugfix] Disable SingleEnvThreadVerifier

- src/runtime/contrib/thrust/thrust.cu
- src/runtime/cuda/cuda_common.h
thrust APIs are by default synchronous unless if we explicitly pass an execution policy. This PR also changes to use caching allocator to avoid synchronous `cudaMalloc/Free` for temp buffers.
cc @junrushao @tqchen @MasterJH5574 @spectrometerHBH @masahi
> [Thrust] Use no sync exec policy and caching allocator

- python/tvm/relax/backend/dispatch_sort_scan.py
- tests/python/relax/test_backend_dispatch_sort_scan.py
This update modifies the test case to accommodate the recent merge from the main branch. The fix  #16361 is required.
cc @vinx13
> [Unity] Update dispatch test cases following the merge from main

- ci/scripts/jenkins/cmd_utils.py
Prior to this commit, the `Sh.tee` method was implemented by calling `f"{cmd} | tee"` in `subprocess.run`.  While the `check=True` flag was used, the return code was from `tee`, not from the command itself. This causes failures in the command itself to be silently ignored, such as in [this CI pipeline](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-i386/detail/PR-16183/37/pipeline) in the `ci/scripts/jenkins/s3.py` step.
This commit updates `Sh.tee` to call `subprocess.Popen` for `cmd`, tee the stdout, and check the return code.  (Roughly adapted from [this stackoverflow post](https://stackoverflow.com/a/56484734).)
> [CI] In jenkins.cmd_utils.Sh.tee, check for failing subprocess

- src/runtime/contrib/vllm/cache_kernels.cu
- tests/python/relax/test_contrib_vllm.py
This kernel is not originally coming from vllm, I wrote this for my need. Then I introduced this bug.
This is exactly an inverse of the `reshape_and_cache` kernel that vllm does have.
@vinx13
> [Unity][Contrib] Fix a bug due to typo in vllm `reconstruct_from_cache` kernel and add test

- python/tvm/rpc/server.py
Fix regression in (#15187) when multiprocessing start method is not 'fork', which prevented tuning from working. This affects macOS and Windows. Also in python 3.14 the default start method will be 'spawn'.
> [RPC] Fix tuning on macOS and Windows (#15771)

- include/tvm/relax/block_builder.h
- python/tvm/relax/block_builder.py
- tests/python/relax/test_blockbuilder_core.py
In #16090 we deprecated bb.get() since it will face name conflict issues. However, bb.get() is still useful in the middle of the building process since it will not invalidate global vars. So this PR provides these interfaces:
- `bb.get()`: used in the middle the building process to get the intermediate IRModule
- `bb.finalize()`: used at the end of the building process to finalize
cc @vinx13
> [Unity][BlockBuilder] Restore bb.get()

- include/tvm/runtime/object.h
- src/runtime/minrpc/minrpc_server.h
- src/runtime/minrpc/rpc_reference.h
- src/runtime/rpc/rpc_endpoint.cc
- src/runtime/rpc/rpc_local_session.cc
- src/runtime/rpc/rpc_module.cc
- src/runtime/rpc/rpc_session.h
- tests/python/runtime/test_runtime_rpc.py
This PR enables RPCObjectRef return object similar to the disco transporation. This allows us to do advanced remote debugging when remote vm requires advanced object input like kv cache and shape.
To keep the implementation with minRPC(used in some of the limited protocols) forn now, we only support RPCObjectRef for now and do not enable unpacking Shape and String (they can still be constructed with two step constructor, per testcase).
> [RUNTIME][RPC] Enable RPCObjectRef return in RPC

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
nonzero_numpy is not working correctly #16389
> [Relay][Frontend][Torch] fix a typo mistake in nonzero_numpy

- include/tvm/relax/attrs/nn.h
- python/tvm/relax/frontend/onnx/onnx_frontend.py
- python/tvm/relax/frontend/torch/fx_translator.py
- python/tvm/relax/op/nn/__init__.py
- python/tvm/relax/op/nn/nn.py
- python/tvm/relax/transform/legalize_ops/nn.py
- src/relax/op/nn/convolution.cc
- src/relax/op/nn/convolution.h
- src/relax/op/op_common.h
- tests/python/relax/test_frontend_from_fx.py
- tests/python/relax/test_frontend_onnx.py
- tests/python/relax/test_op_nn_convolution.py
This PR adds full support for `relax.op.nn.conv3d`, the last missing convolution dimension in the relax operator set. I've added end to end correctness tests via the onnx frontend and structural testing but let me know if there are other tests that you'd like to see!
> [Unity][Relax][Op] Add Conv3D Operator

- python/tvm/relax/frontend/onnx/onnx_frontend.py
_parse_graph_initializers should be first than _parse_graph_input.
Because the conditional statement in _parse_graph_input requires the use of self._nodes, and self._nodes is parsed and populated in _parse_graph_initializers, otherwise self._nodes will remain empty.
> [Relax][Frontend][ONNX]fix onnx frontend parse

- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR enhances PagedKVCache with the inline RoPE compute, which unblocks the movement towards sliding window and attention sink.
Both FlashInfer and TIR kernels are updated in this PR with the RoPE calculation. Note that FlashInfer is bumped in order to include the RoPE update.
The previous standalone kernel used for RoPE application are thereby removed.
---
Co-authored-by: Hongyi Jin <jinhongyi02@gmail.com>
> [Unity] PagedKVCache supporting on-the-fly RoPE calculation

- ci/jenkins/generated/arm_jenkinsfile.groovy
- ci/jenkins/generated/cortexm_jenkinsfile.groovy
- ci/jenkins/generated/cpu_jenkinsfile.groovy
- ci/jenkins/generated/docker_jenkinsfile.groovy
- ci/jenkins/generated/gpu_jenkinsfile.groovy
- ci/jenkins/generated/hexagon_jenkinsfile.groovy
- ci/jenkins/generated/i386_jenkinsfile.groovy
- ci/jenkins/generated/lint_jenkinsfile.groovy
- ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy
- ci/jenkins/generated/minimal_jenkinsfile.groovy
- ci/jenkins/generated/riscv_jenkinsfile.groovy
- ci/jenkins/generated/wasm_jenkinsfile.groovy
- ci/jenkins/templates/utils/base.groovy.j2
AMIs for CI have been upgraded to cuda 12 so `NVIDIA_DISABLE_REQUIRE` is no longer needed.
> [CI] Remove NVIDIA_DISABLE_REQUIRE

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
This PR enhances the static block memory planning pass. Prior to this PR, the memory planning only works on memory allocation that is not externally referenced. In dynamic shape settings, such memory allocation is not fully static and may lead to memory fragmentation.
This PR enhances the behavior, so that for such memory allocation, we first allocate a storage with regard to its estimated upper bound (when known), and then allocate the tensor with the actual dynamic shape out from the storage. This will ensure the static memory allocation and avoid memory fragmentation.
> [Unity][Transform] Memory planning for dynamic-shape func return

- cmake/modules/OpenCL.cmake
Found a problem when you are in a different cmake project (not TVM) and you run TVM build with OpenCL tests, then `CMAKE_SOURCE_DIR` returns the path to the `CMakeList.txt` in the current project (not to the TVM) and in this case we will see the following error: `No SOURCES given to target: opencl-cpptest`.
To be consistent with code style in `OpenCL.cmake`, I removed the usage of `CMAKE_SOURCE_DIR` variable. It also fixes the issue if TVM cmake was called from directory with another cmake project.
> [OpenCL][CMake] Fix OpenCL tests compilation

- include/tvm/runtime/device_api.h
- python/tvm/_ffi/runtime_ctypes.py
- src/runtime/cuda/cuda_device_api.cc
- src/runtime/metal/metal_device_api.mm
- src/runtime/opencl/opencl_device_api.cc
- src/runtime/rocm/rocm_device_api.cc
- src/runtime/vulkan/vulkan_device_api.cc
This PR introduces a new attribute for device backends: `total_global_memory`. This attributes returns the total available global memory on a device in bytes.
Tested locally on CUDA/ROCm/Metal/OpenCL:
```python
>>> import tvm
>>> tvm.metal().total_global_memory
154618822656
```
> [DeviceAPI] Support querying total global memory

- src/target/llvm/codegen_llvm.cc
- src/target/llvm/intrin_rule_rocm.cc
- src/tir/transforms/lower_thread_allreduce.cc
- tests/python/codegen/test_target_codegen_rocm.py
- Handle tvm_thread_invariant as no op.
- `llvm.amdgcn.ds.bpermute` requires i32 as its input, but it can handle all 32 bit types
- ocml intrinsics lead to incorrect codegen when used with vectorization, remove it and use llvm intrinsics instead
> [ROCm] Some fixes of ROCm codegen

- include/tvm/ir/transform.h
- src/ir/transform.cc
- src/relax/transform/decompose_ops.cc
- tests/python/relax/test_transform_decompose_ops.py
Prior to this commit, the `DecomposeOpsForTraining` transform directly replaced `relax.nn.batch_norm` into more primitive relax operations. This required the decomposed form of `relax.nn.batch_norm` to be duplicated with `DecomposeOpsForInference`.  This commit refactors the pass to occur in two steps, first to apply training-specific mutations, and then to decompose.
Having a clear `DecomposeOps` pass also has a clear single location for operator decomposition, which may be migrated into the operator definition in the future, similar to `FLegalize`.
> [Unity] Split DecomposeOpsForTraining into two steps

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
add logical_or op to relay pytorch frontend. #16399
> [Relay][Frontend][Torch] fix pytorch frontend not support logical or

- include/tvm/runtime/logging.h
- src/support/pipe.h
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/intrin_rule_rocm.cc
- src/target/spirv/codegen_spirv.cc
- src/target/spirv/intrin_rule_spirv.cc
- src/tir/transforms/lower_thread_allreduce.cc
- src/tir/transforms/merge_shared_memory_allocations.cc
- src/tir/transforms/storage_rewrite.cc
- tests/python/codegen/test_target_codegen_rocm.py
This PR upstreams a few commits that recovers the unity branch from broken wheel packages. It includes the following changes:
- Fix MSVC build in `pipe.h` where `DWORD` is not cast to proper return type (https://github.com/mlc-ai/relax/pull/306/);
- Fix MSVC build warnings on not recognizing "#pragma GCC" (https://github.com/mlc-ai/relax/pull/307);
- Fix NVCC build warnings where it fails to infer if "[[noreturn]]" actually does not return (https://github.com/mlc-ai/relax/pull/308);
- Fix ROCM/Vulkan backend which fails compilation for operators like group GEMM, paged attention, etc. (https://github.com/apache/tvm/pull/16404, https://github.com/apache/tvm/pull/16405)
> [Bugfix][Unity] Recover MSVC/NVCC/ROCm/Vulkan

- tests/python/integration/test_auto_tensorize.py
- tests/python/meta_schedule/test_meta_schedule_schedule_rule_mlt_intrin.py
As we introduced more dp4a intrinsics, we need to update the name in the testcases.
cc @vincentccc @tqchen
> [Unity][Fix] Fix mismatched intrinsic name

- python/tvm/relay/op/contrib/clml.py
- src/runtime/contrib/clml/clml_runtime.cc
- tests/python/contrib/test_clml/test_ops.py
- Fixed the softmax layer for 4D tensors to support for NCHW and NHWC layout types.
- Enabled relevant test cases for softmax layer
> [RUNTIME][CLML] Fix for Softmax op for 4D tensors

- docker/install/ubuntu_install_emscripten.sh
- docker/install/ubuntu_install_nodejs.sh
This PR updates the emsdk and nodejs version of docker.
> [CI][WASM] Update emsdk and nodejs version

- python/tvm/relax/backend/contrib/cutlass.py
- python/tvm/relax/frontend/nn/modules.py
- tests/python/relax/test_codegen_cutlass.py
- tests/python/relax/test_frontend_nn_modules.py
I've recently been working with dynamic shaped convolutions and found a few blockers that this PR resolves. I enable the NN frontend to work with dynamic axes and also introduce a small check to cutlass pattern matching to skip convolutions with dynamism rather than error out. I add appropriate tests to make sure the behaviors work as expected.
> [Unity][Frontend][NN] Better support for dynamic convolutions

- python/tvm/dlight/gpu/reduction.py
- tests/python/dlight/test_gpu_reduction.py
This PR fixes a bug in the dlight reduction rule, which fails to recognize the pattern of a dynamic-shape epilogue block and therefore errors out when transforming such blocks.
One regression test is provided.
> [Unity][Dlight][Fix] Reduction rule support dyn-shape epilogue

- include/tvm/tir/data_type_rewriter.h
- python/tvm/topi/cuda/scan.py
- src/tir/ir/data_type_rewriter.cc
This PR fixes a bug on attr handling in data type rewriter and enforces i32 buffer in cumsum function definition, which ensures that cumsum can be run on a machine with int32 but not int64.
> [Unity]  Support cumsum with pure int32

- src/target/intrin_rule.cc
- src/target/intrin_rule.h
- src/target/llvm/intrin_rule_llvm.cc
- src/target/source/intrin_rule_metal.cc
- src/target/source/intrin_rule_webgpu.cc
Prior to this PR, `tanh(x)`returns `NaN` on metal when `x > 45.0`.
Metal's built-in tanh is implemented as `(t - 1.0) / (t + 1.0)`, where `t = exp(2.0 * x)`. Hence for large `x`, `t` becomes `inf`, causing `tanh(x)` to be `NaN`.
A numerically stable `tanh` is implemented for `llvm`, this PR lifts it to `src/target/intrin_rule.cc` and apply the same rule for metal as well.
> [Metal] Dispatch numerically stable tanh for metal

- python/tvm/runtime/ndarray.py
If we use the bfloat16 type of ml_dtypes to create an array of tvm.ndarray, the result of the created tvm.ndarray will be wrong.
```python
x = np.random.uniform(low=0.3, high=13.3, size=shape).astype(ml_dtypes.bfloat16)
x_ndarray = tvm.nd.array(x)
```
I understand that the reason for this error is that we have not considered that the input passed in is ml_dtypes.bfloat16. The np_float2np_bf16 function that has been used in the past (this function will convert the fp32 type numpy array into a uint16 numpy array)
> [BugFix]Ensure that bf16 arrays are created as expected

- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_tir.py
Refer to this issue 
https://github.com/apache/tvm/issues/16433 , the relax Pass FuseTIR creates intermediate name by 
```c++
n->name = param->name_hint + "_intermediate";
```
which may lead to some bugs when we encounter two fused blocks with the same param name, for example what I encountered in resnet-18, the conv+add+multiply+add, the fused two add operators' block may point to the same block.
So we should provide a method to get an unique name for each in duplicate buffers.
```cpp
auto unify_name_hints = [this, &buffer, &param]() {
String base_name = buffer->name;
String unique_name = base_name + "_intermediate";
size_t unique_id = 0;
std::unordered_set<std::string> names;
for (auto& _buffer : func_info_.alloc_buffers) {
names.insert(_buffer->name);
}
while (names.find(unique_name) …
```
> [Unity] Improve buffer allocation for handling duplicated buffer names.

- src/tir/transforms/lower_cross_thread_reduction.cc
- tests/python/tir-transform/test_tir_transform_lower_cross_thread_reduction.py
This is a fix of `LowerCrossThreadReduction`: The pass will remove all the loops with thread bind under the inter thread reduction block, which will introduce some issues when we meet the case where there could be other non-reduction blocks under the reduction thread.
Before removing a thread-bound loop, check if the block(s) under this loop has reduction block var. If the block(s) under have reduction do not have any reduction block var, it means that block is not reduction, and therefore this thread-bound loop should be kept. Otherwise, we remove the thread-bound loop as usual.
related discussion: https://discuss.tvm.apache.org/t/missing-thread-bind-loops-under-block-reduction-when-transformed-with-tir/16232/6
Please CC @MasterJH5574
> [TIR] Fix of inter thread reduction with shared memory prefetch

- include/tvm/ir/transform.h
- src/ir/transform.cc
- src/relax/transform/decompose_ops.cc
- tests/python/relax/test_transform_decompose_ops.py
Reverts apache/tvm#15954
to avoid use of regex for now
> Revert "[Unity] Split DecomposeOpsForTraining into two steps"

- python/tvm/autotvm/tuner/droplet_tuner.py
- python/tvm/topi/math.py
- src/target/llvm/intrin_rule_rocm.cc
This commit fixes a few minor intrinsic dispatch issues in the ROCm and WebGPU backend that affects LLM compilation, including Mixtral, RedPajama (GPT-NeoX) and GPT-BigCode.
> [ROCm][WebGPU] Intrin Dispatch: `tanh`, `erf`, `log`

- python/tvm/topi/cuda/scatter_elements.py
- src/te/operation/op_utils.cc
A minor fix for mismatched dtype (int32 vs int64) for thread tags.
cc @tqchen
> [Unity][FIX] fix thread dtype mismatch

- python/tvm/contrib/emcc.py
- web/Makefile
- web/package.json
- web/tests/node/test_packed_func.js
This PR temp disables wasm exception which requires latest version of nodejs. We can re-enable it after the wasm CI env finishes update.
> [Unity][WEB] Temp disable wasm exception

- .asf.yaml
This PR relax the branch rule to allow us to push to main branch and run the unity transition. We will update the settings again after the transition
> [skip ci] update branch rule to prepare for unity transition

- python/tvm/contrib/msc/core/codegen/codegen.py
- python/tvm/contrib/msc/framework/tvm/codegen/codegen.py
- python/tvm/contrib/msc/plugin/__init__.py
- python/tvm/contrib/msc/plugin/_ffi_api.py
- python/tvm/contrib/msc/plugin/build.py
- python/tvm/contrib/msc/plugin/codegen/__init__.py
- python/tvm/contrib/msc/plugin/codegen/codegen.py
- python/tvm/contrib/msc/plugin/codegen/sources.py
- python/tvm/contrib/msc/plugin/op/__init__.py
- python/tvm/contrib/msc/plugin/op/_ffi_api.py
- python/tvm/contrib/msc/plugin/register.py
- python/tvm/contrib/msc/plugin/utils.py
- src/contrib/msc/core/ir/plugin.cc
- src/contrib/msc/core/ir/plugin.h
- src/contrib/msc/core/utils.cc
- src/contrib/msc/core/utils.h
- src/contrib/msc/plugin/base_codegen.h
- src/contrib/msc/plugin/codegen_utils.h
- src/contrib/msc/plugin/tensorrt_codegen.cc
- src/contrib/msc/plugin/tensorrt_codegen.h
- src/contrib/msc/plugin/torch_codegen.cc
- src/contrib/msc/plugin/torch_codegen.h
- src/contrib/msc/plugin/tvm_codegen.cc
- src/contrib/msc/plugin/tvm_codegen.h
- tests/python/contrib/test_msc/test_plugin.py
This is the Milestone 4 for MSC: Add plugin builder, enable plugin wrap in different frameworks.
To limit each PR in reviewable size, the Milestone 4 will be split into some steps:
**[M4.1] Add plugin && plugin_builder, enable build and test in different frameworks.**
[M4.2] Enable plugin with manager, test plugins in compile pipeline.
[M4.3] Enable auto generate plugin kernel with script.
Plugin Builder build the plugins from kernel source or kernel libs. Plugin will be build according to framework register style and able to be called by python api.
The plugin builder in MSC enable …
> [Unity][MSC][M4.1] Add plugin && plugin_builder, enable build and test in different frameworks

- src/relax/transform/lambda_lift.cc
- tests/python/relax/test_transform_lambda_lift.py
Prior to this commit, symbolic variables used by a lambda function would be duplicated between the caller and the lifted-out function. In addition, shape inference within the lifted-out function was performed without access to the symbolic variables, resulting in unnecessary fallback from `R.Tensor([m, n])` to `R.Tensor(ndim=2)`.
This commit updates the `LambdaLift` transform to handle symbolic variables.  All symbolic variables have unique definitions across the resulting `IRModule`, and shape inference in the lifted-out function is aware of symbolic variables that have been exposed to it.
> [Unity][Transform] Handle symbolic variables in LambdaLift

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/expand_matmul_of_sum.cc
- tests/python/relax/test_transform_expand_matmul_of_sum.py
An optimization pass that rewrites `x*(A+B)` into `x*A + x*B`, where `x`, `A`, and `B` are relax tensors.
> [Unity][Transform] Implement relax.transform.ExpandMatmulOfSum

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/reorder_take_after_matmul.cc
- tests/python/relax/test_transform_reorder_take_after_matmul.py
If `R.matmul(x, R.take(weights, indices))` occurs, with `R.take` selecting along the output feature dimension, it can be rearranged to `R.take(R.matmul(x, weights), indices)`.
> [Unity][Transform] Implement relax.transform.ReorderTakeAfterMatmul

- python/tvm/script/ir_builder/relax/ir.py
- tests/python/relax/test_tvmscript_parser.py
In low-level Relax (after the pass `CallTIRewrite`), the `call_packed` nodes do not always have explicit `sinfo_args`. This PR extends the parser to support this case.
> [Unity][TVMScript] Update `call_packed` semantics to support empty sinfo_args

- python/tvm/relax/op/nn/nn.py
Fix the multi-line array docstring during sphinx-build. We use a python code block to warp it for better display.
> [Minor] Fix Docstring for sphinx-build

- src/runtime/relax_vm/kv_cache.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR introduces two changes to the (paged) KV cache:
The first is introducing RoPE mode to PagedKVCache. Right now there are two modes: normal/inline. In "normal" mode, RoPE will be applied to input Q/K/V data before appending the K/V data to cache. In "inline" mode, the input K/V data is directly appending to cache, and the RoPE will be on-the-fly applied inside attention kernel. The main purpose of introducing RoPE mode is to balance the need of on-the-fly RoPE (in cases like Mistral where positions can cahnge) and the attention kernel performance.
The second is introducing a new interface `AttentionWithFusedQKV` to KV cache. This function takes the input QKV data that is fused along the head dimension. And the fused QKV will be split into separate Q/K/V internally (note: requiring …
> [Runtime][KVCache] AttentionWithFusedQKV and RoPE mode

- src/runtime/relax_vm/ndarray_cache_support.cc
As NDArray on RPC devices only returns a DLTensor, we add support for DLTensor in NDArray Cache.
It's not easy to add test cases as we cannot create a raw DLTensor in Python interface.
cc @tqchen
> [Relax] NDArray Cache Update with DLTensor Support

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
This PR improves the memory planning to plan for tensors with shape such as `(m, n)` where only `m` has an integer upper bound (say `m <= 20`).
Prior to this PR, the tensor is not planned even though `m` has an upper bound. This is not as ideal since it does not fully leverage the upper bound info.
This PR enhances the planning, so that a memory chunk of `20 * n` will be allocated first, and the tensor will then be allocated out from this chunk. This enables us to fully leverage the upper bound info.
A unit test is provided.
> [Relax] Memory planning for "partially dynamic" shapes

- tests/python/contrib/test_hexagon/test_dma_builtin.py
We see `no-self-argument` and `wrong-import-order` pylint errors in downstream CI. Eyeballing the file, both of these errors are legit, it's not clear why the upstream CI didn't catch them, potentially because of the inherent instability of pylint running on multiple threads.
> [LINT] Fix pylint issues in test_dma_builtin.py

- src/relax/op/op.cc
If the tensor argument does not have a valid shape, then the error message will include the expression, the argument, and the struct info of the argument.
> [Unity] Improve error message in tensor_to_shape struct inference

- src/relax/ir/struct_info.cc
If the struct info cannot be updated, provide the expression, the previous struct info, and the new struct info in the error message.
> [Unity] Improved error message in tvm::relax::UpdateStructInfo

- ci/jenkins/docker-images.ini
- ci/jenkins/generated/arm_jenkinsfile.groovy
- ci/jenkins/generated/cortexm_jenkinsfile.groovy
- ci/jenkins/generated/cpu_jenkinsfile.groovy
- ci/jenkins/generated/docker_jenkinsfile.groovy
- ci/jenkins/generated/gpu_jenkinsfile.groovy
- ci/jenkins/generated/hexagon_jenkinsfile.groovy
- ci/jenkins/generated/i386_jenkinsfile.groovy
- ci/jenkins/generated/lint_jenkinsfile.groovy
- ci/jenkins/generated/minimal_cross_isa_jenkinsfile.groovy
- ci/jenkins/generated/minimal_jenkinsfile.groovy
- ci/jenkins/generated/riscv_jenkinsfile.groovy
- ci/jenkins/generated/wasm_jenkinsfile.groovy
- ci/jenkins/templates/gpu_jenkinsfile.groovy.j2
- ci/jenkins/templates/utils/Build.groovy.j2
- ci/jenkins/unity_jenkinsfile.groovy
- tests/scripts/task_build.py
update the images to align with the latest upgrades of emsdk and nodejs.
> [CI] Update image tag to 20240126-070121-8ade9c30e

- python/tvm/relax/frontend/nn/extern.py
Fix a missing line in the docstring of `extern.py`, which would cause Sphinx to fail to build the documentation.
> [Doc] Fix Docstring in `extern.py` for Sphinx

- python/tvm/relay/frontend/paddlepaddle.py
* Support BatchNormalize operator for NHWC layout
* Support Pool2D operator for NHWC layout
* The Paddle API version has been updated to 2.6.0, but some API versions in TVM are still at 2.5.0
* When converting the Paddle MatMul operator, a crash occurs on MacOS due to the use of infer_shape to calculate rank
> [Frontend][PaddlePaddle] Fixed the bug that prevented the model from being successfully converted to microTVM on MacOS

- src/tir/transforms/storage_access.cc
- src/tir/transforms/storage_access.h
- tests/python/tir-transform/test_tir_transform_thread_sync.py
See original discuss
[LayerNorm Error in thread_storage_sync when read x into shared memory](https://discuss.tvm.apache.org/t/layernorm-error-in-thread-storage-sync-when-read-x-into-shared-memory/16269)
I try to read x into shared memory to accelerate layernorm, [script here 1](https://gist.github.com/JackWeiw/f873daaff32212b0b19cf91fda463007)
but error occurs in pass thread_sorage_sync pass.I found it is because the error in lower LetStmt ,[lowered script](https://gist.github.com/JackWeiw/6737f4faa1b486b389721cf7f3f4ad4d)
> [BugTIR] fix thread_sync occurs in letstmt

- python/tvm/ir/module.py
- python/tvm/relax/transform/transform.py
- src/ir/module.cc
- src/relax/transform/run_codegen.cc
- tests/python/relax/test_transform_codegen_pass.py
Prior to this commit, `relax.transform.RunCodegen` required a list of entry functions for a module, defaulting to `"main"` if not specified. The list of entry functions is duplicate information that could be inferred from the module, and should not be required from the user. This commit updates `RunCodegen` to treat all externally-exposed functions as entry points, in the same manner as
`DeadCodeElimination`.
For backwards compatibility, the `entry_functions` argument is still accepted, and is used to augment the list of externally-exposed functions.
> [Unity][CodeGen] RunCodegen based on externally-exposed functions

- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR supports passing pre-allocated workspace to attention kernels, so that runtime repetitive allocation or workspaces can be eliminated.
> [Runtime] KV cache providing workspace for attn kernel

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- src/target/llvm/codegen_llvm.cc
- src/tir/op/builtin.cc
- tests/python/codegen/test_target_codegen_aarch64.py
Add a `vscale` builtin and lowering to `llvm.vscale`. This will be used in subsequent patches for expressing scalable vectors in TIR.
> [SVE] Add vscale builtin

- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_transform_cse.py
- The problem is seen when an arg of relax op is dtype
> [Relax][Pass] Skip data type node for CSE pass

- python/tvm/relax/dpl/pattern.py
- src/relax/ir/dataflow_pattern.cc
- tests/python/relax/test_dataflow_pattern.py
`call_tir` op may contains the third input argument `tir_vars`. This PR updated pattern matching to allow `tir_vars` field
cc @Hzfengsy @MasterJH5574 @tqchen
> [DPL] Support tir_vars field in is_call_tir pattern

- src/runtime/relax_vm/lm_support.cc
- web/src/runtime.ts
This PR adds `ApplyPresenceAndFrequencyPenalty()` to `lm_support.cc` and exposes it to Web runtime. 
This is essentially the same as `applyRepetitionPenalty` except we follow a different way of penalizing repeating tokens, following https://platform.openai.com/docs/guides/text-generation/frequency-and-presence-penalties.
Tested end-to-end with WebLLM.
> [Relax][Web] Add ApplyPresenceAndRequencyPenalty

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_dataflow_pattern.py
- tests/python/relax/test_transform_static_plan_block_memory.py
Before this PR, dynamic shapes require upper bound of variables to be provided in order to use storage planning. We can relax this requirement, for shapes with unknown bound, we can look up other tensors with the same symbolic shapes. This can be helpful for deep learning models where the layers with the same configurations are usually repeated since there are many objects with the same shapes.
This PR changed the `StorageToken` to use `PrimExpr` bytes which can be integer or symbolic. For symbolic shapes, we put the tokens into a special buckets for looking up.
cc @MasterJH5574 @tqchen
> [Unity] Support storage reuse for dynamic shapes

- python/tvm/ir/instrument.py
- tests/python/ir/test_pass_instrument.py
A small patch to add default instruments that prints all passes before or after each pass. This is used very frequently when debugging and we don't know which pass could cause a particular change
> [Instrument] Add default instrument to print all passes

- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/op/base.py
- tests/python/relax/test_frontend_nn_op.py
This PR introduces the `tensor_ir_inplace_op` for frontend so that we can leverage our `call_tir_inplace` in SLM model definition flow.
One unit test is added. This PR also fixed a few typos in type annotations.
> [Relax][Frontent] "tensor_ir_inplace" op

- include/tvm/runtime/threading_backend.h
This PR skips launching multiple parallel threads in `parallel_for_with_threading_backend` when the input extent is 1, in which case we can just use the current thread to run the given function.
> [Runtime] ParallelFor skipping thread backend for unit extent

- src/relax/transform/fuse_tir.cc
- src/target/source/codegen_c_host.cc
- src/target/source/codegen_c_host.h
The original two warnings are:
```
[build] /Users/syfeng/tvm/src/relax/transform/fuse_tir.cc:685:48: warning: lambda capture 'param' is not used [-Wunused-lambda-capture]
[build]       auto unify_name_hints = [this, &buffer, &param]() {
[build]                                             ~~~^~~~~
[build] /Users/syfeng/tvm/src/target/source/codegen_c_host.h:47:8: warning: 'tvm::codegen::CodeGenCHost::AddFunction' hides overloaded virtual function [-Woverloaded-virtual]
[build]   void AddFunction(const GlobalVar& gvar, const PrimFunc& f, bool emit_fwd_func_decl = false);
[build]        ^
[build] /Users/syfeng/tvm/src/target/source/codegen_c.h:86:16: note: hidden overloaded virtual function 'tvm::codegen::CodeGenC::AddFunction' declared here: different number of parameters (2 vs 3)
[build] …
```
> [Minor] Fix Clang compilation warning in fuse_tir.cc and codegen_c_host.cc

- src/tir/transforms/merge_shared_memory_allocations.cc
- src/tir/transforms/storage_rewrite.cc
- tests/python/tir-transform/test_tir_transform_storage_rewrite.py
This PR fixes the StorageRewrite pass which failed to avoid shared memory reuse of different dtypes for Vulkan.
Since the Vulkan target information is required at the time of lowering, the pass `BindTarget` needs to apply before lowering, so that the functions have correct target information. Note that previously the pass checks `Target::Current`, while `tvm.build` does not set the current target.
One regression test is added.
> [TIR] Require exactly same-dtype matching for Vulkan smem reuse

- python/tvm/relax/transform/legalize_ops/nn.py
- src/tir/op/op.cc
- tests/python/relax/test_transform_legalize_ops_nn.py
This PR changes `topi.power(x,3)` in `gelu_tanh` to `x * x * x`. Subsequently, we add a warning when `pow(x, y)`, where `y >= 3`, is detected.
This is motivated by, in ROCm, `pow(x, y)` returns `NaN` when `x < 0` and `y >= 3`. This is shown below:
```python
@I.ir_module
class Module:
@T.prim_func
def pow3(A: T.Buffer((1,), "float16")):
T.func_attr({"tir.is_scheduled": 1, "tir.noalias": T.bool(True)})
for ax0_fused_0 in T.thread_binding(1, thread="blockIdx.x"):
for ax0_fused_1 in T.thread_binding(1024, thread="threadIdx.x"):
with T.block("T_multiply_3"):
T.where(ax0_fused_0 * 1024 + ax0_fused_1 < 1)
T.reads(A[0])
T.writes(A[0])
A[0] = T.pow(A[0], T.float16(3))  # gives nan
mod = Module
rt_mod = tvm.build(mod, target="rocm")
A_tvm = tvm.nd.array(np.array([-1.0], dtype="float16"), …
```
> [BugFix] Use x*x*x instead of pow(x,3)

- python/tvm/contrib/msc/core/runtime/runner.py
- python/tvm/contrib/msc/core/tools/prune/pruner.py
- python/tvm/contrib/msc/core/tools/quantize/quantizer.py
- python/tvm/contrib/msc/core/tools/tool.py
- python/tvm/contrib/msc/framework/tensorflow/codegen/codegen.py
- python/tvm/contrib/msc/framework/tensorrt/codegen/codegen.py
- python/tvm/contrib/msc/framework/tensorrt/transform/pattern.py
- python/tvm/contrib/msc/framework/torch/codegen/codegen.py
- python/tvm/contrib/msc/framework/tvm/codegen/codegen.py
- python/tvm/contrib/msc/pipeline/__init__.py
- python/tvm/contrib/msc/pipeline/manager.py
- src/contrib/msc/core/codegen/base_codegen.h
- src/contrib/msc/core/transform/set_expr_layout.cc
- src/contrib/msc/framework/tensorrt/codegen.cc
- src/contrib/msc/framework/tensorrt/codegen_utils.h
- src/contrib/msc/framework/tensorrt/tensorrt_opcode.cc
- src/contrib/msc/framework/torch/codegen.cc
- src/contrib/msc/framework/torch/torch_opcode.cc
- src/contrib/msc/framework/tvm/codegen.cc
- src/contrib/msc/framework/tvm/relax_opcode.cc
This is the Milestone 4 for MSC: Add plugin builder, enable plugin wrap in different frameworks.
To limit each PR in reviewable size, the Milestone 4 will be split into some steps:
[M4.1] Add plugin && plugin_builder, enable build and test in different frameworks.
**[M4.2] Enable plugin with manager, test plugins in compile pipeline.**
To enable using plugin in compile pipeline, the plugin manager is used together with MSC Manager. Plugin manager handles the converter of plugin from training framework to relax. Codegen parts are also modified for code generation.
This PR add …
> [Unity][MSC][M4.2][Step1] Enable plugin with manager, test plugins in compile pipeline

- docker/install/ubuntu2004_install_python_package.sh
- docker/install/ubuntu_install_python_package.sh
- tests/python/driver/tvmc/test_command_line.py
Pytest-lazy-fixture doesn't work with `pytest==8.0.0`
The following error occurs when pytest-lazy-fixture is called:
`AttributeError: 'CallSpec2' object has no attribute 'funcargs'`
This has been raised as an issue on the pytest-lazy-fixture project, but the repository is not in active development. See https://github.com/TvoroG/pytest-lazy-fixture/issues/65 for details.
TVM project code-base makes very little reference to pytest-lazy-fixture, so this patch removes the library from the project altogether, in order to resolve the problem.
CC @neildhickey @lhutton1 @tqchen
> Cut pytest-lazy-fixture

- python/tvm/contrib/emcc.py
- web/Makefile
- web/package.json
- web/tests/node/test_packed_func.js
This reverts commit 61d952c701a8c03e2e897e357e1eed4e79d3269f.
Previously this was disabled because ci-wasm wasn't updated this PR re-enable it.
> Revert "[Unity][WEB] Temp disable wasm exception (#16444)"

- src/relax/ir/block_builder.cc
- src/relax/op/tensor/manipulate.cc
- tests/python/relax/test_op_manipulate.py
- tests/python/relax/test_transform_combine_parallel_matmul.py
Prior to this commit, the `relax.op.split` did not provide a known shape if the split was performed over a dynamic-size axis.  This commit updates the shape inference to provide correct shapes in this case.  A test case is also added for `CombineParallelMatmul` to show the intended usage of this feature, to ensure that the split outputs from a combined matmul still have correct shape information.
> [Unity] Infer struct info for relax.op.split on dynamic-sized index

- include/tvm/relax/transform.h
- python/tvm/relax/transform/transform.py
- src/relax/transform/dead_code_elimination.cc
Many Relax passes that rely on dataflow blocks do not explicitly state that they do. This is relevant for the phase ordering, since `ToNonDataflow` is eventually used. Additionally, if a user did not manually insert dataflow blocks, the pass `ConvertToDataflow` can be used to automatically extract dataflow blocks. This PR adds doc comments for passes that do depend on DF blocks and also adds notes suggesting the use of `ConvertToDataflow` to ensure that there will be DF blocks for these passes (if applicable).
> [Unity][Doc] Document passes that depend on `DataflowBlock`s and encourage using `ConvertToDataflow`

- src/relax/transform/fuse_ops.cc
- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_ops.py
- tests/python/relax/test_transform_fuse_tir.py
This PR handles in-place `PrimFunc`s in `FuseTIR`, namely by propagating the in-place indices. This required a few updates in the two passes but nothing very heavy-duty.
> [Unity][Transform] Handle `call_tir_inplace` in `FuseTIR` and `FuseOps`

- python/tvm/relay/frontend/keras.py
- tests/python/frontend/keras/test_forward.py
Our dense op expects 2D, but there are no limitation in Keras on the shape of the input tensor. Reshaping of all "batch" axes into one was added in this commit. After that, it is possible to import Dense layer with ND input tensor from Keras to TVM.
cc: @masahi, @vvchernov, @Hzfengsy
> [Keras] Enable Dense operator for any input dims

- python/tvm/__init__.py
- python/tvm/contrib/debugger/debug_executor.py
- python/tvm/meta_schedule/utils.py
- src/arith/iter_affine_map.cc
- src/tir/ir/tir_visitor_with_path.cc
- src/tir/transforms/lower_tvm_builtin.cc
- tests/python/codegen/test_target_codegen_cuda.py
- tests/python/meta_schedule/test_meta_schedule_mma_m16n8k8_auto_tensorization.py
- tests/python/meta_schedule/test_meta_schedule_postproc_rewrite_tensorize.py
- tests/python/meta_schedule/test_meta_schedule_schedule_rule_mlt_tc.py
- tests/python/meta_schedule/test_meta_schedule_trace_apply.py
- tests/python/runtime/test_runtime_trace.py
- tests/python/te/test_te_create_primfunc.py
- tests/python/tir-analysis/test_tir_analysis_verify_well_formed.py
- tests/python/tir-base/test_debug_info.py
- tests/python/tir-schedule/test_tir_schedule_rfactor.py
- tests/python/tir-schedule/test_tir_schedule_transform_layout.py
- tests/scripts/task_python_unittest.sh
Thanks @liushengjiezj for pointing out the bug and initial fix. This PR fixes the broken test and make CI green again
- Related issue: https://github.com/apache/tvm/issues/16510
- Initial PR: https://github.com/apache/tvm/pull/16520
cc @tqchen @Johnson9009
> [CI] Fix CI Script and Broken Tests

- gallery/how_to/compile_models/from_mxnet.py
- gallery/how_to/deploy_models/deploy_model_on_nano.py
- gallery/how_to/deploy_models/deploy_model_on_rasp.py
- gallery/how_to/deploy_models/deploy_quantized.py
- gallery/how_to/extend_tvm/bring_your_own_datatypes.py
- gallery/how_to/tune_with_autoscheduler/tune_network_arm.py
- gallery/how_to/tune_with_autoscheduler/tune_network_cuda.py
- gallery/how_to/tune_with_autoscheduler/tune_network_mali.py
- gallery/how_to/tune_with_autoscheduler/tune_network_x86.py
- rust/tvm/examples/resnet/Cargo.toml
- rust/tvm/examples/resnet/build.rs
- rust/tvm/examples/resnet/src/main.rs
- tests/python/frontend/mxnet/test_forward.py
- tests/python/nightly/quantization/test_quantization_accuracy.py
- vta/scripts/tune_resnet.py
- vta/tutorials/autotvm/tune_alu_vta.py
- vta/tutorials/autotvm/tune_relay_vta.py
- vta/tutorials/frontend/deploy_classification.py
The mxnet project was archived in 2023-09 ([link](https://attic.apache.org/projects/mxnet.html)). Downloads from the mxnet AWS
links (e.g. `https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/resnet18_v1-a0666292.zip`) no longer can be performed.  This commit disables TVM CI steps that depend on downloading models from these locations.
> [CI] Disable testing that downloads from mxnet

- src/runtime/pack_args.h
- src/runtime/rocm/rocm_module.cc
This PR properly aligns rocm param buffer fields to avoid bug in cases like
```c
struct Param {
void *arg0;
int32_t arg1;
int64_t arg2;
};
```
In this case, we need to align arg2 by padding a i32 after arg1.
---
Co-authored-by: Tianqi Chen <tianqi.tchen@gmail.com>
> [RUNTIME][ROCM] Properly align rocm parameter buffer

- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
When compiling a TensorIR function to ROCm backends, we need to be careful to store and load local registers in a consistent approach (either using vector access or scalar access), or otherwise there will be correctness issue.
This PR fixes the attention kernel for ROCm.
Meanwhile, it adds tests for float32 dtype and head dim other than 128.
> [KVCache] Fix attention kernel for ROCm

- src/tir/analysis/block_access_region_detector.cc
- tests/python/tir-analysis/test_tir_analysis_get_block_access_region.py
The current implementation of `block_access_region_detector` does not consider the let bindings inside the block. To be more specific:
- The let bindings inside the block can be the index of buffer access indices
- The let bindings var is defined inside the block, so the block annotation cannot use those vars.
- We need to substitute the let bindings inside the block to the block annotation.
This PR fixes this problem and can create legal IRs.
> [TIR] Fix get_block_access_region for let bindings

- include/tvm/runtime/relax_vm/ndarray_cache_support.h
The `NDArrayCacheMetadata::Load` function lacks the `TVM_DLL` attribute which leads to build failure on Windows. This PR fixes the issue.
> [Runtime] Add "TVM_DLL" to NDArray cache load func

- src/runtime/relax_vm/lm_support.cc
- src/target/source/codegen_webgpu.cc
- src/target/source/codegen_webgpu.h
- src/tir/transforms/storage_rewrite.cc
- web/emcc/wasm_runtime.cc
- web/src/webgpu.ts
This PR introduces various WebGPU changes to accommodate the new `PagedKVCache` interface. All changes below are essential for making models that use PagedKVCache runnable under WebGPU:
- Require exactly same-dtype matching for WebGPU smem reuse in `storage_rewrite.cc`
- Rename `AttentionKVCache` to `AttentionKVCacheLegacy` for the old KVcache interface in `lm_support.cc`; include `paged_kv_cache.cc` when making `wasm_runtime` subsequently
- In WebGPU codegen:
- Declare local variables within the function scope rather than the module scope
- Generate `while (true)` rather than `while (1)`
- Require 10 `maxStorageBuffersPerShaderStage` rather than the default 8 from the WebGPU device when initializing runtime; this is required for new kernels introduced in PagedKVCache
- In …
> [Web] Compatibility with PagedKVCache in WebGPU

- src/runtime/ndarray.cc
Make it explicit that the quoted numbers are bytes.
> Improve error message in NDArray::CopyFromTo

- include/tvm/runtime/relax_vm/bytecode.h
- src/relax/backend/vm/exec_builder.cc
- src/runtime/library_module.cc
- src/runtime/relax_vm/bytecode.cc
- src/runtime/relax_vm/executable.cc
- src/runtime/relax_vm/vm.cc
- tests/python/relax/test_vm_callback_function.py
Prior to this commit, calls from Relax to external PackedFuncs could only be done through the TVM global registry.  While Relax functions accepting a callback could be written as `callback_arg: R.Callable(arg_struct_info, ret_struct_info)`, attempting to compile these functions would raise an error during the `CodeGenVM` step of `relax.build`.  In addition, the global registry is only queried when initializing the `relax.VirtualMachine`, and so later changes requires restarting the VM.
This commit updates both the `CodeGenVM` lowering pass and the relax VM to support callbacks.  The motivating use case is with the `LazyTransformParams` pass, to improve flexibility by avoiding use of the global registry.
> [Relax] Support callback as argument

- python/tvm/relax/frontend/nn/__init__.py
- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This PR includes two changes:
- expose GroupNorm in NN frontend
- remove `tir_vars` from `tensor_ir_op` if not necessary. Not the current implementation is correct, but it would convert into `call_tir_dyn` even if there is an empty `tir_vars` list.
> [Relax] Minor updates for NN frontend

- python/tvm/relax/utils.py
- tests/python/relax/test_blockbuilder_emit_te.py
Prior to this commit, a fused relax function could accept a `R.Prim` value, but wouldn't use it to provide symbolic variables to the fused function.
> [Unity] Check for symbolic vars in PrimValue in when lowering to TIR

- python/tvm/driver/build_module.py
- python/tvm/relax/vm_build.py
- src/driver/driver_api.cc
- tests/python/relax/test_vm_build.py
Prior to this commit, if a lowered `IRModule` does not contain any TIR functions, `tvm.relax.build` provided an empty `tir_mod`, which caused a segfault during TIR compilation.  This could occur when `tvm.relax.build` is called without an explicit target argument, for a module that does not define any virtual devices.
This commit updates the `_filter_tir` utility function to return `None` if there are no TIR functions, rather than an empty `IRModule`.  In addition, checks for an empty `IRModule` are added to `tvm.build` and `TIRToRuntime`, so that a similar failure mode would raise an exception rather than producing a segfault.
> [Bugfix][Relax] Remove call to tvm.build for empty TIR module

- include/tvm/relax/transform.h
- src/relax/transform/fuse_tir.cc
- tests/python/relax/test_transform_fuse_tir.py
Prior to this commit, private non-primitive relax functions would be discarded by `FuseTIR`.  If any calls to these functions exist, the resulting `IRModule` would be ill-formed.  This commit updates `FuseTIR` so that it only applies updates to functions with `attr::kPrimitive`, and calls into those functions.
To retain backwards compatibility, `DeadCodeElimination` is applied as a post-processing step.
> [Bugfix][Transform] Keep private non-primitive functions in FuseTIR

- include/tvm/node/script_printer.h
- src/target/source/codegen_webgpu.h
This PR fixes the following compile warnings with clang-17:
```
[build] warning: unknown command tag name [-Wdocumentation-unknown-command]
[build]    90 |    *     @R.function
[build]       |          ^~
[build] warning: 'tvm::codegen::CodeGenWebGPU::AddFunction' hides overloaded virtual function [-Woverloaded-virtual]
[build]    52 |   runtime::FunctionInfo AddFunction(const PrimFunc& f, bool skip_readonly_decl);  // NOLINT(*)
[build]       |
```
cc @Lunderberg @tqchen
> [MISC] Fix compile warnings

- include/tvm/runtime/relax_vm/bytecode.h
- src/relax/backend/vm/codegen_vm.cc
- src/relax/backend/vm/exec_builder.cc
- src/runtime/relax_vm/bytecode.cc
- src/runtime/relax_vm/executable.cc
- src/runtime/relax_vm/vm.cc
A follow-up PR from https://github.com/apache/tvm/pull/16542, after some post-merge discussion regarding the implementation.
> [Relax][VM] Re-implementation of callback functions

- src/runtime/relax_vm/kv_cache.h
- src/runtime/relax_vm/paged_kv_cache.cc
This PR adds a new function to PagedKVCache to return in-sequence positions for each location in a batch of sequences that is being forwarded. This function helps apply positional embeddings for language models that do not use Rotary positional embeddings.
> [KVCache] Support returning query positions

- src/relax/transform/run_codegen.cc
- tests/python/relax/test_transform_codegen_pass.py
The `relax.transform.RunCodegen` pass replaces calls to relax functions with the `"Codegen"` attribute with calls into a compiled module. Prior to this commit, while calls to relax functions without the `"Codegen"` attribute were ignored, calls to non-relax functions would raise an error.
This commit updates `relax.transform.RunCodegen` to also ignore calls to non-relax functions.
> [Relax] Ignore non-relax functions in relax.transform.RunCodegen

- src/relax/backend/contrib/utils.cc
If there is a mis-match between the pattern used in `FuseOpsByPattern` and the expected relax function used in a relax codegen function (e.g. `"relax.ext.cublas"`), this will raise an error when attempting to unpack the primitive relax function.  This commit improves the error message provided when this occurs, stating what pattern was expected, and what function was expected to match the pattern.
> [Debug] Improve error message for codegen pattern mismatches

- src/relax/backend/vm/vm_shape_lower.cc
- tests/python/relax/test_backend_transform_shape_lower.py
Prior to this commit, the `MatchBinding` visitor in `VMShapeLowerMutator`.  If the RHS of the `MatchBinding` is a `ShapeExpr` that uses symbolic variables, that RHS must be visited in order to have the symbolic variable updated.
> [Unity][VM] Recursively visit match bindings in VMShapeLowerMutator

- src/runtime/metal/metal_common.h
- src/runtime/metal/metal_device_api.mm
- src/runtime/metal/metal_module.mm
This PR fixes a bug where metal runtime cannot be accessed from multiple threads. This is because the ThreadLocal entry initialization happens during global workspace initialization, meaning other threads that tries to use metal runtime later cannot have the thread local entry correctly initialized.
This PR fixes the problem by always use nullptr fallback and lookup at the global workspace for default stream.
---
Co-authored-by: Tianqi Chen <tqchenml@gmail.com>
> [RUNTIME][METAL] Fix multithreading access of metal runtime

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
- tests/python/relax/test_transform_convert_dataflow.py
Prior to this commit, known tuples could be unwrapped into variables, but any constants would remain.  This commit updates `CanonicalizeBindings` to unwrap tuples containing constants.
> [Relax][Transform] Canonicalize `let var = R.const` bindings

- python/tvm/relax/block_builder.py
- src/relax/ir/block_builder.cc
- tests/python/relax/test_blockbuilder_core.py
Prior to this commit, while a `relax.VarBinding` created using `BlockBuilder.emit` could have its name explicitly specified by the user, a `relax.MatchCast` created using `BlockBuilder.match_cast` could not.  This commit updates `BlockBuilder.match_cast` to accept an optional `name_hint` parameter, which is then provided to the C++ `BlockBuilder::EmitMatchCast` method.
> [Relax] Expose name_hint field for BlockBuilder.match_cast

- python/tvm/relax/op/base.py
- python/tvm/script/ir_builder/relax/ir.py
- tests/python/relax/test_tvmscript_parser.py
Prior to this commit, `R.call_packed` and `R.call_pure_packed` had different normalization for the `sinfo_args` argument.  While `R.call_packed` checked if the struct info needed to be converted using `ObjectGeneric.asobject()`, `R.call_pure_packed` did not.
This commit updates the `R.call_pure_packed` to handle `sinfo_args` in the same manner as `R.call_packed`.
> [Unity][TVMScript] Parse R.Object return type from call_pure_packed

- web/README.md
- web/package-lock.json
- web/src/artifact_cache.ts
- web/src/index.ts
- web/src/runtime.ts
- Move old artifact cache as a interface template to support future IndexDB cache fetch
- Add deleteInCache api in cache template
- Fix one test path error
- Parallelize Downloading Process
Co-authored-by: DavidGOrtega <g.ortega.david@gmail.com> for parallel download
> [WEB] Move ArtifactCache to Interface, Support Cache delete and Batch Delete, Remove typo

- src/runtime/relax_vm/kv_cache.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
In GPT-2, attention calculation requires an additional feature `scale_attn_by_inverse_layer_idx`. It provides a scaling factor per attention layer when calculating the attention score, before applying the softmax function.
This PR supports this additional parameter in KV cache.
> [KVCache] Support passing in attn_score_scaling_factor into KV cache

- python/tvm/contrib/msc/framework/torch/frontend/translate.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/contrib/test_msc/test_plugin.py
This is the Milestone 4 for MSC: Add plugin builder, enable plugin wrap in different frameworks.
To limit each PR in reviewable size, the Milestone 4 will be split into some steps:
[M4.1] Add plugin && plugin_builder, enable build and test in different frameworks.
**[M4.2] Enable plugin with manager, test plugins in compile pipeline.**
To enable using plugin in compile pipeline, the plugin manager is used together with MSC Manager. Plugin manager handles the converter of plugin from training framework to relax. Codegen parts are also modified for code generation.
This PR add custom …
> [Unity][MSC][M4.2][Step2] Enable plugin with manager, test plugins in compile pipeline

- python/tvm/ir/attrs.py
The provided usage example for `tvm.ir.make_node` has become outdated. Creating an IR node of type `IntImm` requires the field `span`. 
Compare: [`make_node` Unit Test](https://github.com/apache/tvm/blob/main/tests/python/ir/test_node_reflection.py#L73)
> [Doc] Fixed Docstring usage example in `tvm.ir.make_node`

- src/relax/transform/fuse_ops.cc
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
Prior to this commit, calling `FuseOpsByPattern` with `annotate_codegen=True` would cause an error when encountering a lambda function.  This was caused by the `CompositeFunctionAnnotator` asserting that all `relax::Function` encountered must have the `kComposite` attribute.  While this is true for all lambda functions produced by `FuseOpsByPattern`, the user may have defined other lambda functions as well.
This commit updates `CompositeFunctionAnnotator` to ignore lambda functions that do not have a `kComposite` attribute.
> [Transform][Bugfix] Handle non-composite lambda functions in FuseOps

- src/script/ir_builder/relax/frame.cc
- src/script/ir_builder/relax/utils.h
- tests/python/relax/test_tvmscript_parser.py
Prior to this commit, using `R.match_cast` as the last binding would produce a segfault, as `var_binding->value` was used instead of `match_cast->value`.  In addition, because the last binding of each branch was removed, any changes to the struct info resulting from the match cast were silently discarded.
This commit updates the TVMScript parsing of if/else statements to remove the segfault and maintain the struct info changes produced by the `R.match_cast`.
> [Bugfix][TVMScript] Handle R.match_cast as last binding in if/else

- python/tvm/relay/frontend/paddlepaddle.py
Support conv2d when data_format is NHWC
> [Frontend][PaddlePaddle] Support conv2d when data_format is NHWC

- python/tvm/relay/frontend/onnx.py
Fix the bug: https://github.com/apache/tvm/issues/16623
the default type of attribute 'dtype' is int32 rather than int64
> [Relay][ONNX] fix the wrong default value about dtype in Multinomial converter

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
Hi， tvm:
This PR fixes a bug related to different opsets in the clip and unsqueeze operations.
My model's opset default version is 10, and there is no implementation for opset below 10 for these two operators. Therefore, there might be some issues.
> [Relax][Frontend][Onnx] fix clip unsqueeze opset implement

- python/tvm/relax/transform/lazy_transform_params.py
- tests/python/relax/test_transform_lazy_transform_params.py
* Handle non-bundled parameters in LazyTransformParams.
* Check for `"num_input"` attribute
* Handle relax.Const in LazyTransformParams
Prior to this commit, `LazyTransformParams` would only output a call to the `fset_item` function if that element of the output had a corresponding `relax.Binding`.  If `relax.Const` appeared in the output, then the call to `fset_item` would be omitted.
This commit updates `LazyTransformParams` to check for any non-`Var` elements of the output tuple.
> [Transform] Improvements to LazyTransformParams

- python/tvm/relax/transform/transform.py
- src/relax/transform/bundle_model_params.cc
- src/relax/transform/utils.h
- tests/python/relax/test_transform_bundle_model_params.py
In `BundleModelParams`, allow the user to specify a name for the tuple parameters.  If unspecified, defaults to the previous name `"model_params"`.
> [Transform] Allow explicit name of bundled model parameters

- src/relax/transform/expand_matmul_of_sum.cc
- tests/python/relax/test_transform_expand_matmul_of_sum.py
This pattern occurs whenever `relax.op.linear` is used.
> [Unity][Transform] Check for permute_dims in ExpandMatmulOfSum

- python/tvm/relax/transform/legalize_ops/nn.py
- tests/python/relax/test_transform_legalize_ops_nn.py
Prior to this commit, when using `causal_mask="BottomRight"` in `R.nn.attention`, the legalization would assume that the query and key/value sequence lengths were static integers.  This commit updates the legalization to allow dynamic shapes.
> [Relax] Handle dynamic arguments in legalization of nn.attention

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
fix the bug: https://github.com/apache/tvm/issues/16621
> [Relay][ONNX] Fix the attribute mode parse of operator Upsample 

- web/src/runtime.ts
This PR fixes an issue where the NDArrayCache loading report callback is inaccurate after parallel download support.
> [Web] Fix NDArrayCache loading report callback

- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_cpu.h
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
- src/target/llvm/llvm_module.cc
- tests/python/tir-base/test_debug_info.py
Prior to this commit, the `CodeGenLLVM` would include DWARF symbols specifying the function signature of each TIR function.  This commit expands the information exposed in the debug symbols.
* Name functions based on the name of the corresponding TIR function. This is taken either from the `attr::kGlobalSymbol` if present, or the PrimFunc's `GlobalVar` otherwise.
* Name function parameter based on their TIR variable name.
* Annotate the name, the type signature, and parameter names for the private function produced by the `tir::attr::compute_scope` attribute.
* Name local variables based on the name and type of the corresponding TIR variable.
> [TIR] Expand debug symbol output for CodeGenLLVM

- src/relax/transform/fuse_ops.cc
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
Internally, `FuseOpsByPattern` makes a mapping from relax variables to the fused group containing that variable.  If the input module violates SSA, this map may be ill-formed.  While not strictly necessary for FuseOps to handle ill-formed inputs, checking it at this level provides better error handling than propagating it to downstream passes.
This commit checks for ill-formed inputs that would produce invalid fused outputs and raises an error.
> [Unity][Transform] Raise error in FuseOpsByPattern for SSA violation

- include/tvm/relax/analysis.h
- src/relax/analysis/analysis.cc
- src/relax/analysis/well_formed.cc
- tests/python/relax/test_analysis_well_formed.py
Prior to this commit, `VerifyWellFormed` would state that a dataflow block or pure function contained an impure call, but identifying which call was impure was left to the user.
This commit updates `VerifyWellFormed` to show the impure `relax::Call` as part of the error message.
> [Unity][Analysis] Include impure call in VerifyWellFormed errors

- tests/python/relax/test_transform_remove_unused_parameters.py
Verifying behavior for subroutines that receive `R.Prim` or `R.Shape` parameters, if the symbolic variables defined by those parameters are already defined by another parameter.
> [Relax] Additional unit tests for RemoveUnusedParameters

- python/tvm/relax/frontend/nn/_tensor_op.py
- python/tvm/relax/frontend/nn/op.py
- src/runtime/relax_vm/lm_support.cc
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_vm_builtin.py
This PR introduces the `multinomial_from_uniform` into nn module for GPU case, and `vm.builtin.multinomial_from_uniform` for CPU. The `multinomial_from_uniform` returns a tensor wherein each row contains an index sampled from a multinomial probability distribution.
[The test case](https://github.com/apache/tvm/pull/16575/commits/abbe733e4af04ac1591066769d269d8c3aa95d56#diff-cd42596733b780d4b3ca6e4e66a002f6175c144821cdeabe8ebaa91bc6c16f67L907-L924) is for testing the build and run, it has been commented out to avoid overloading the nn module op tests.
----
Updated on Feb. 21, 2024
Add `sample_top_p_top_k_from_sorted_prob` and `renormalize_top_p_top_k_prob`
cc: @tqchen @vinx13 @MasterJH5574
> [Unity] GPU sampling

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/reorder_permute_dims_after_concat.cc
- tests/python/relax/test_transform_reorder_permute_dims_after_concat.py
This commit implements an optional optimization pass `relax.transform.ReorderPermuteDimsAfterConcat`, which reorder expressions of the form `R.concat(R.permute_dims(A), R.permute_dims(B))` into `R.permute_dims(R.concat(A,B))`.
This pass is intended to be used alongside `CombineParallelMatmul`. After parallel matmuls are combined, to be lifted out, and optimized `nn.Linear` kernels to find the `R.matmul(x, R.permute_dims(weights))` patterns they are looking for.
```python
@R.function
def func(x: R.Tensor, weight_query: R.Tensor, weight_key: R.Tensor, weight_value: R.Tensor):
"""Initial IRModule
The `R.permute_dims` followed by `R.matmul` is the relax
equivalent of `nn.Linear`, and will frequently have optimized
kernels.
"""
weight_query_T = R.permute_dims(weight_query)
query = R.matmul(x, …
```
> [Transform] Implement relax.transform.ReorderPermuteDimsAfterConcat

- src/relax/transform/canonicalize_bindings.cc
- src/relax/transform/lift_transform_params.cc
- tests/python/relax/test_transform_lift_transform_params.py
The `relax.transform.LiftTransformParams` pass splits apart a relax function, extracting the steps that could be performed at compile-time.  Prior to this commit, the transformed parameters were named `param0`, `param1`, and so on.
This commit updates the `LiftTransformParams` pass to preserve any human-readable parameter names.  The parameter names for the updated function are taken from the original parameter names, if no transformation is performed, or from the internal variable binding, if a transformation is applied.  This implementation uses `LambdaLift` internally, relying on the changes made in
https://github.com/apache/tvm/pull/16306.
> [Relax][Transform] Preserve param names in LiftTransformParams

- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_transform_cse.py
Update the `relax.transform.EliminateCommonSubexpr` pass to handle `R.match_cast` bindings, where the argument of the `R.match_cast` has also been de-duplicated.
> [Transform] De-duplicate MatchCast nodes in EliminateCommonSubexpr

- include/tvm/relax/expr.h
- src/relax/transform/combine_parallel_matmul.cc
- tests/python/relax/test_transform_combine_parallel_matmul.py
Prior to this commit, if the weight of a matmul a dynamic shape, and that matmul is being combined with the `CombineParallelMatmul` pass, it could cause a segfault when `dim.as<IntImmNode>()` returns a null pointer.
This commit adds explicit test cases for these dynamic shapes, and updates `CombineParallelMatmul` to handle the dynamic shapes.
> [Unity][Transform] Handle dynamic shapes in CombineParallelMatmul

- python/tvm/contrib/cutlass/build.py
This commit updates the cutlass annotator to check if `relax.Function.attrs` is `None` before attempting to access it.
> [Bugfix][Cutlass] Check if function attributes is None

- include/tvm/runtime/threading_backend.h
This PR adds the TVM_DLL attribute to the functions in `threading_backend.h` to make it work with Windows packaging.
> [Runtime] Add TVM_DLL to threading backend funcs

- python/tvm/exec/disco_worker.py
- python/tvm/runtime/disco/session.py
- python/tvm/testing/utils.py
- src/runtime/disco/builtin.cc
- tests/python/disco/test_callback.py
In addition to the PackedFunc `"runtime.disco.worker_id"`, which returns the worker ID wrapped in a `ShapeTuple`, this commit adds `"runtime.disco.worker_rank"`, which returns the worker ID without wrapping, and `"runtime.disco.device"`, which returns the device for each worker.
The unit test added in this commit simulates loading of model weights through a parameter transformation function.
> [Disco] Expose functions to query the per-worker device/rank

- python/tvm/testing/aot.py
- tests/python/relay/aot/test_aot_test_harness.py
- tests/python/relay/aot/test_crt_aot.py
This commit enhances the AOT test harness to print the "actual" and "reference" values when there is a mismatch. This helps when debugging a failing test. Sample output:
```
Actual, Reference
8.502946, 8.887751
9.810405, 9.108611
8.563767, 9.041000
10.019511, 9.190888
....
```
> [AOT][Testing] Print output values on test failure

- python/tvm/script/parser/tir/parser.py
- src/script/printer/tir/stmt.cc
- tests/python/tvmscript/test_tvmscript_printer_tir.py
- tests/python/tvmscript/test_tvmscript_syntax_sugar.py
The TIR equivalent of python's `return` statement is the `tir::builtin::ret()` operator.  Prior to this commit, this was printed as `T.ret(value)`, and any use of `return` statement in TVMScript produced an error while parsing.
This commit updates the TVMScript parsing to produce `T.ret(value)` for the python `return value` statement.  If syntax sugar is enabled, the TIR `T.ret(value)` will be printed as `return value`.
> [TVMScript] Represent tir::builtin::ret() using python "return"

- python/tvm/_ffi/runtime_ctypes.py
A default value for lanes was unintentionally removed in #16612, this PR fixes this which in turn fixes the test failure seen in `test_tensor_dtype_lanes` in CI.
cc @tqchen @Lunderberg @ekalda
> [BugFix][FFI] Add a missing default for datatype lanes

- include/tvm/relax/expr.h
- src/relax/transform/lift_transform_params.cc
- tests/python/relax/test_transform_lift_transform_params.py
- tests/python/relax/test_utils.py
Prior to this commit, `LiftTransformParams` would extract out all variable binding that have no runtime dependencies.  As a result, expressions such as `R.zeros([16], "int32")` would be extracted out into the parameter transformation, even though they do not depend on any parameters.
This commit updates `LiftTransformParams` to only output variables that depend on at least one compile-time parameter.
The unit test for this functionality also found that `relax::Call` was erroneously calling `MarkGraphNode` in `SEqualReduce` and `SHashReduce`.  This should only be called for nodes that have have reference equality, such as `relax::Var`, and not for composite objects.  This caused erroneous failures in the unit test when two instances of `R.zeros([16], "int32")` were being compared by …
> [Transform] Check for zero-param operators in LiftTransformParams

- src/relax/transform/fuse_ops.cc
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
Prior to this commit, the `CompositeFunctionAnnotator` visited the body of functions without the parameters being considered in-scope. As a result, `EraseToWellDefined` would remove known shapes from the function body's `StructInfo`.
> [Bugfix][Transform] Preserve symbolic variables in FuseOps

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
Prior to this PR, GeMV does not skip the cases of normalization failure, which leads to error. This PR fixes this issue.
A unit test is added accordingly.
> [Dlight] Skip GeMV when normalization fails

- python/tvm/topi/cuda/scan.py
The `topi.cuda.inclusive_scan` currently relies on performing an `exclusive_scan` followed by an add operation that adds the input data back in. To eliminate the overhead introduced by this extra addition, probably we should have an implementation specifically designed for `inclusive_scan`. As of now, the implementation of `inclusive_scan` is limited to `exclusive_scan_ir`, developing an `inclusive_scan_ir` will be needed for performance in the future.
In this pull request, we specifically address this efficiency for thrust by directly calling the inclusive function.
Co-authored-by: Wuwei Lin  [wuwei@apache.org](mailto:wuwei@apache.org)
> [TOPI] improve inclusive_scan for thrust

- src/runtime/relax_vm/ndarray_cache_support.cc
As `Array` cannot be transferred through RPC protocol, we introduce a new unpack API by directly passing all str through PackedFunc.
This PR also fixes a bug in `vm.builtin.ndarray_cache.update`
cc @tqchen
> [Relax][Runtime] Support Unpack API for NDArrayCache

- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
Prior to this PR, the TIR attention kernels does not cast matmul operands to fp32 before multiplying.
For models like Phi-2 which may have large Q/K/V data (at the level of a few hundreds), the fp16 multiplication exceeds the range of fp16, and lead to attention result being NAN sometimes.
This PR fixes this issue.
> [Runtime][Builtin] Using float32 accumulation in attention kernel

- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR fixes a sequence reference counter bug in the KV cache: when forking a child sequnece from an existing parent sequence, the reference counter of hte parent sequence was not increased. This leads to error when the child sequence is removed, where we will check the parent's reference counter and find it is 0 and is never changed unexpectedly.
Meanwhile, this PR updates the PagedKVCache tests with some latest changes, including target-aware tile size selection.
> [KVCache] Fix the reference counter in sequence fork

- src/tir/ir/script/script_complete.cc
- tests/python/tvmscript/test_tvmscript_complete.py
Prior to this commit, the automatic `T.reads()` and `T.writes()` annotations were only generated for buffers appearing as function arguments, as `T.alloc_buffer` in a `T.block`, or as `T.match_buffer` in a `T.block`.  However, inferred `T.reads()` for a buffer defined by the `"tir.BindParams"` pass would be erroneously missing.  These annotations may be required for correct scheduling (see discussion in [PR#16660](https://github.com/apache/tvm/pull/16660)).
This commit updates the TVMScript parsing to infer `T.reads()` and `T.writes()` annotations for buffers defined with `DeclBuffer` nodes.
> [TVMScript] Infer T.reads() for DeclBuffer nodes

- cmake/config.cmake
- docs/install/from_source.rst
This sets the arguments recommended previously in the docs as the default windows build args for the cmake generate step.
Instead of needing to say:
```bash
cmake -A x64 -Thost=x64 ..
```
Its now the same as linux and mac:
```bash
cmake ..
```
> Simplify Windows CMake Command

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
For the DFT operator (opset-17), The attribute of `axis`, `inverse`, and `onesided` is optional with a default value as shown in the [ONNX documentation](https://onnx.ai/onnx/operators/onnx__DFT.html). This PR fixed such bugs and added corresponding tests.
> [BugFix] add the default value for DFT in ONNX frontend

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
Add sample_indices into multinomial_from_uniform and sample_top_p_top_k_from_sorted_prob
> [Relax] add sample_indices in sampling

- src/relax/transform/lift_transform_params.cc
- src/runtime/relax_vm/builtin.cc
- tests/python/relax/test_transform_lift_transform_params.py
This updates `LiftTransformParams` to always free original weight in the bundled weights tuple. This prevents the issue that `transform_params` consumes memory with double weight size. See discussion https://discuss.tvm.apache.org/t/inplacetransformparams/16323.
cc @tqchen @MasterJH5574 @Lunderberg
> [Relax] Eager free original weights in transform_params

- python/tvm/contrib/emcc.py
This PR fixes the wasm exceptions flag in emcc compile export.
> [skip ci] Fix wasm exception flag

- python/tvm/relax/frontend/nn/modules.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/op/op_attrs.py
- src/relax/op/image/resize.cc
- src/tir/schedule/state.cc
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_transform_convert_layout.py
This PR expands Relax's NN frontend with operators needed to support emerging video models like SVD. The main change needed is adding support for Conv3D, but a few other minor changes were found to be helpful as well. Specifically the ability to rewrite resize2D's layout manually was quite helpful for performance, so I expanded it's convertlayout pass to support that. I also added a few more options to Conv2D in the nn frontend such as specifying layout.
> [Relax][Frontend][NN] Add support for Conv3D

- src/tir/schedule/primitive/cache_read_write.cc
- tests/python/tir-schedule/test_tir_schedule_cache_read_write.py
When inserting a `cache_read` / `cache_write` stage, the `tir.AllocateConst` statement would be duplicated if its body was not a `tir.SeqStmt` node (e.g. `tir.For`), leading to compilation failures. This happened because `tir.AllocateConst` and `tir.DeclBuffer` statements are always re-attached to the statement's body after the `cache_read` / `cache_write` stage is inserted in it, but the stage was being appended to the whole statement (which already contains the `tir.AllocateConst`) and not just its body, causing duplications.
This commit also adds a test where the first `cache_read` stage is inserted into a statement whose body is a `tir.For`, while the second stage is added to a body that is `tir.SeqStmt` to check for regressions.  
cc @Lunderberg @ekalda @lhutton1
> [Bugfix][TIR] Fix duplicate AllocateConst in CacheReadWrite schedule primitive

- src/tir/schedule/ir_comparator.cc
- src/tir/schedule/ir_comparator.h
- src/tir/schedule/primitive/blockize_tensorize.cc
- src/tir/transforms/simplify.cc
- src/tir/transforms/simplify.h
- tests/python/tir-schedule/test_tir_schedule_tensorize.py
To optimize i4_to_f16 decoding, we can use some advanced hardware instructions to do fast type conversion to alleviate the cost of decoding, we can do that by tensorize in tvm.
To tensorize decoding, this pr extends the call component of ir_comparator, which is necessary because the decode block comprises call expressions.
Moreover, currently comparator do simplification on the lhs expr, however, the tensor intrin descs are not simplified, which will be inconsistent and will fail at comparation, 
see this pr: https://github.com/apache/tvm/pull/14108. 
For example, we provide a test case for this situation:
```python
def test_tensorize_arith_simplification():
@T.prim_func
def decode_i4s_to_int32_to_f16():
B_decode_local = T.alloc_buffer((16384, 16384), "float16", scope="local")
B_local = …
```
> [TIR] Enhance and fix tensorize schedule for some case

- src/tir/transforms/ir_utils.cc
- tests/python/tir-transform/test_tir_transform_convert_ssa.py
In some cases, an `AttrStmt` may legally refer to a TIR variable that hasn't yet been defined.  For example, the
`"pragma_parallel_launch_point"` attribute, which annotates a variable that is about to occur in a ForNode.  Prior to this commit, `ConvertSSA` treated the `AttrStmt` as the usage of a variable, followed by a nested definition to be de-duplicated.  This resulted in the output `AttrStmt` containing a reference to an undefined variable.
This commit updates `ConvertSSA` to handle this case.  If an `AttrStmt` refers to a not-yet-defined variable, the body is visited before marking it as defined.
This implementation may be simplified in the future by moving "pragma_parallel_launch_point" to be an annotation on the `ForNode`, rather than an `AttrStmt`.
> [Bugfix][TIR] Handle AttrStmt of upcoming tir.Var in ConvertSSA

- python/tvm/relax/frontend/torch/fx_translator.py
torch change the description of the graph, function name isn't same as node name, cause can't find function if import torch model. So use target name instead of node name.
fix https://github.com/mlc-ai/web-stable-diffusion/issues/54
> Use target name instead of node name as function name

- include/tvm/runtime/device_api.h
- src/runtime/c_runtime_api.cc
- src/runtime/cuda/cuda_device_api.cc
- src/runtime/metal/metal_common.h
- src/runtime/metal/metal_device_api.mm
- src/runtime/minrpc/rpc_reference.h
- src/runtime/rocm/rocm_device_api.cc
- src/runtime/rpc/rpc_device_api.cc
- src/runtime/rpc/rpc_endpoint.cc
- src/runtime/vulkan/vulkan_device_api.cc
- src/runtime/vulkan/vulkan_device_api.h
- web/emcc/webgpu_runtime.cc
This PR introduces a new function `GetCurrentStream`to device API, which returns the current stream of the given device.
Meanwhile, this PR updates the "CreateStream" of CUDA to creating a non-blocking stream, so that the execution on this stream can overlap with the execution of other streams.
This PR also changes the `GPUCopy` of CUDA device API to always using `cudaMemcpyAsync`.
> [DeviceAPI] Support "GetCurrentStream"

- python/tvm/dlight/gpu/low_batch_gemv.py
- tests/python/dlight/test_gpu_low_batch_gemv.py
LowBatchGemv rule only apply to function with spatial symbolic var, so that this rule skips matmul in attention kernel which has symbolic_var `kv_seq_len`
>  [Dlight] LowBatchGemv rule only apply to function with spatial symbolic var
