- src/tir/ir/specialize.cc
- tests/python/tir-base/test_tir_specialize.py
In rare cases, a `PrimFunc` may be annotated with `StructInfo`, to indicate that it is an impure function with specific shapes for the parameters.  If struct info is present, it is invalidated when specializing a `PrimFunc`, and should be cleared.
> [Unity][TIR] Clear struct info when specializing PrimFunc

- ci/jenkins/unity_jenkinsfile.groovy
Add `merge_with_main` in unity. Adjust 5 retries with 2-minute timeout to 3 retries with 5-m timeout as cpu does.
> [CI] add merge_with_main in unity

- python/tvm/runtime/__init__.py
- python/tvm/runtime/support.py
- python/tvm/support.py
- src/ir/transform.cc
- src/relax/transform/update_param_struct_info.cc
- src/relay/backend/contrib/dnnl/codegen.cc
- src/relay/backend/contrib/dnnl/query_layout.cc
- src/relay/backend/contrib/mrvl/codegen.cc
- src/runtime/contrib/dnnl/dnnl_json_runtime.cc
- src/runtime/regex.cc
- src/runtime/regex.h
- tests/lint/cpplint.sh
Currently, the pytorch wheels available through `pip install` use the pre-C++11 ABI by setting `-DUSE_CXX11_ABI=0` [0].  If TVM were to user the pre-C++11 ABI, this would cause breakages with dynamically-linked LLVM environments.
This commit adds a lint check to search for use of `#include <regex>` in any C++ files.  Use of this header should be avoided, as its implementation is not supported by gcc's dual ABI.  This ABI incompatibility results in runtime errors either when `std::regex` is called from TVM, or when `std::regex` is called from pytorch, depending on which library was loaded first.
This restriction can be removed when a version of pytorch compiled using `-DUSE_CXX11_ABI=1` is available from PyPI.
[0] https://github.com/pytorch/pytorch/issues/51039
> [Lint] Add check to prevent usage of #include <regex>

- include/tvm/relax/analysis.h
- include/tvm/relax/dataflow_pattern.h
- include/tvm/relax/dataflow_pattern_functor.h
- python/tvm/relax/dpl/pattern.py
- python/tvm/relax/frontend/nn/core.py
- src/relax/analysis/struct_info_analysis.cc
- src/relax/ir/dataflow_matcher.cc
- src/relax/ir/dataflow_matcher_impl.h
- src/relax/ir/dataflow_pattern.cc
- src/relax/ir/dataflow_pattern_functor.cc
- tests/python/relax/test_dataflow_pattern.py
This commit implements `StructInfoPattern`, which can be applied to any existing `DFPattern`, and requires the expression to have a specific struct info.  Any symbolic variables that occur in the struct info are treated as free parameters, to be defined by the match.
> [Relax] Implement StructInfoPattern for dataflow pattern matching

- python/tvm/relax/frontend/nn/exporter.py
- python/tvm/relax/frontend/nn/modules.py
- tests/python/relax/test_frontend_nn_modules.py
Prior to this commit, the `nn.modules.KVCache` implementations used `R.call_packed(...)` to call the `"vm.builtin.attention_*"` functions. Since `nn.Module` emits all relax functions within a `relax.DataflowBlock`, where impure expressions are forbidden, this is ill-formed.
This commit updates the implementations in `nn.modules.KVCache` to use `R.call_pure_packed` instead of `R.call_packed`.  This assertation that the callee is pure allows the call to occur within a `relax.DataflowBlock`.
> [Bugfix][SLM] Produce well-formed Relax for nn.modules.KVCache

- src/runtime/relax_vm/paged_kv_cache.cc
This PR enhances PagedKVCache with the copy stream separation. In detail, for CUDA and ROCm backend, we create a standalone copy stream for the copy of auxiliary data structure from CPU to GPU. Furthermore, we move the copy from BeginForward to Attention, which means it's no longer eagerly executed, instead, becoming lazily executed when Attention computation is needed.
By making these changes, we are able to overlap the auxiliary data copy time (on the copy stream) with the model forward computation that happens before the first Attention. As a result, we can hide some of the copy latency.
This PR also bumps the version of FlashInfer for the copy stream support.
> [Runtime] PagedKVCache execute data copy on a separate stream

- python/tvm/contrib/tvmjs.py
This PR enhances the `dump_ndarray_cache` function to take generator as input. Previously it can only take a dictionary.
Sometimes, it is possible that the total ndarray size cannot fit the main CPU memory, in which case we may turn to using generators so we can free some NDArray memory on the fly. And this PR supports the NDArray cache dumping with generators.
> [Contrib] Support NDArray cache taking generator

- python/tvm/contrib/emcc.py
- src/runtime/c_runtime_api.cc
- web/Makefile
- web/apps/node/example.js
- web/emcc/decorate_as_wasi.py
- web/emcc/wasm_runtime.cc
- web/emcc/webgpu_runtime.cc
- web/src/artifact_cache.ts
- web/src/asyncify.ts
- web/src/runtime.ts
- web/src/support.ts
- web/tests/node/test_packed_func.js
This PR enables asyncify support for web runtime.
Asyncify is a feature to allow C++ to call async function in javascript. The emcc compiler will unwind and store the stack, returning control to JS runtime. The JS runtime needs to be able to await the promise and then call rewind to get to the original suspended point.
This feature can be potentially useful when we would like to call WebGPU sync in C++ runtime. As on web platform everything have to be non-blocking. Previously we simply forbid c++ runtime to call sync and have to return to javascript side and let javascript side to call async.
Because asyncify can increase the wams size by 2x, we don't enable it by default in emcc.py and still would need to pass in options.
We will confirm potential benefit tradeoffs before turning it on …
> [WEB] Initial support for asyncify

- python/tvm/relay/backend/contrib/ethosu/te/binary_elementwise.py
- python/tvm/relay/backend/contrib/ethosu/te/common.py
- python/tvm/relay/backend/contrib/ethosu/te/convolution.py
- python/tvm/relay/backend/contrib/ethosu/te/depthwise.py
- python/tvm/relay/backend/contrib/ethosu/te/identity.py
- python/tvm/relay/backend/contrib/ethosu/te/pooling.py
- tests/python/contrib/test_ethosu/test_scheduler.py
When passing the look-up table values to the TE graph, the table size value for int8 type was used, now the required value is set depending on the type of input data.
cc @lhutton1, @ekalda, @leandron
> [microNPU][ETHOSU] Fix LUT size for int16 activations

- src/relax/transform/rewrite_cuda_graph.cc
- tests/python/relax/test_transform_rewrite_cuda_graph.py
The RewriteCUDAGraph pass missed to consider StringImm as a static expression, causing some loss of CUDA graph rewrite opportunities. This PR fixes the issue.
Choosing not to add a regression test considering this is a very trivial change.
> [Relax] CUDA graph rewrite treating StringImm as static

- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
- src/target/target_kind.cc
- tests/python/runtime/test_runtime_module_based_interface.py
- tests/python/runtime/test_runtime_module_load.py
- tests/python/target/test_target_target.py
This PR introduce a new LLVM ORC JIT executor for the runtime.
The new ORCJIT may obsolete MCJIT due to better upstream maintenance.
---
* Old MCJIT is **default** , thus the previous behaviour is unchanged.
* The new ORCJIT is added as a alternative and **optional** llvm runtime engine.
* [MCJIT](https://llvm.org/docs/MCJITDesignAndImplementation.html) is the first implementation in LLVM and looks to be unmaintained by upstream.
* The new [ORCJIT](https://llvm.org/docs/ORCv2.html) is added and it shares the same flow configuration as the current MCJIT.
* Targets like RISCV, and possible others too, will not work on MCJIT see some discussions [here](https://reviews.llvm.org/D127842) .
* The new ORCJIT offers flexibile custom compilation and linkage flow that can be useful for future …
> [LLVM][RUNTIME] Add optional LLVM ORCJIT runtime executor

- python/tvm/runtime/disco/session.py
Prior to this commit, `structlog.configure(...)` would only impact log statements generated in the main process, while workers started with `disco.session.ProcessSession` would not inherit the `structlog` configuration.  While `disco.session.ThreadedSession` would inherit the `structlog` configuration, it would also inherit process-specific CUDA variables.
This commit updates `disco.session.ProcessSession` to explicitly propagate any `structlog` configuration to child processes.  This implementation intentionally avoids introducing a new dependency for TVM.  If the `structlog` package is not available, the config propagation is skipped.
> [Disco] Propagate structlog configuration to disco workers

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This PR fixes a typo in the samping kernel of top-p/top-k sampling op. Prior to this PR, the kernel has out-of-bound global memory access due to a miss when introducing `sample_indices` in #16675.
The correctness pass did not reveal this issue by directly running the test or running through pytest. But actually, if we use compute-sanitizer from NVIDIA, it will report the illegal memory access:
```
> compute-sanitizer --tool memcheck --print-limit=5 --launch-timeout 3600 python tests/python/relax/test_frontend_nn_op.py
========= COMPUTE-SANITIZER
========= Invalid __global__ read of size 8 bytes
=========     at 0x4e90 in get_index_from_sorted_kernel
=========     by thread (7,0,0) in block (0,0,0)
=========     Address 0x7fe35ac00238 is out of bounds
=========     and is 9 bytes after the …
```
> [Fix][Relax] Fix top-p/top-k sampling kernel

- python/tvm/script/parser/relax/parser.py
- src/script/printer/relax/binding.cc
- tests/python/relax/test_tvmscript_parser.py
- tests/python/relax/test_tvmscript_printer_relax.py
Prior to this commit, TVMScript required all relax expressions to be part of an explicit assignment or return statement.  While this matches the structure of the C++ IR types, this can be unexpected for functions that have no return value.  For example, needing to assign the result of `R.print(...)` to a variable.
This commit updates the TVMScript parser/printer to allow relax expressions to be used as statements, if they have a void return type. This allows use of `R.print(...)` and `R.assert_op(...)` to be called without assigning the result to an unused variable.
> [TVMScript] Allow use of relax.Expr with void type as a statement

- src/arith/canonical_simplify.cc
- tests/python/arith/test_arith_canonical_simplify.py
PR #15471 enhances the simplification for LE, while missed a case where the upper bound `kPosInf` is divisible by a factor. Therefore, prior to this PR, when simplifying `x * 1024 + y < z * 7168`, it will fails with the error message
```
InternalError: Check failed: value < 1LL << (dtype.bits() - 1)
(8589934591 vs. 2147483648) : ValueError: Literal value 8589934591
exceeds maximum of int32
```
This is just because the upper bound 7 here divides `kPosInf` the maximum value of int64, which passes an "if" condition in #15471 unexpectedly.
This PR fixes the issue.
> [Fix][Arith] Fix canonical simplification of LE

- python/tvm/dlight/gpu/low_batch_gemv.py
Add fallback for low batch gemv with outer reduction
> [Dlight] Add fallback for low batch gemv with outer reduction

- python/tvm/relax/transform/lazy_transform_params.py
- python/tvm/script/parser/relax/entry.py
- python/tvm/script/parser/relax/parser.py
- tests/python/relax/test_transform_lazy_transform_params.py
- tests/python/tvmscript/test_tvmscript_roundtrip.py
Prior to this commit, the output of `relax.transform.LazyTransformParams` would include all parameters that are not `R.Tensor`, in case they defined symbolic variables. However, this added too many unnecessary parameters, such as `R.Object` which cannot define symbolic variables.  This commit updates `relax.transform.LazyTransformParams` to only retain `R.Prim` and `R.Shape` parameters, which can define symbolic variables.
> [Transform] Remove R.Object parameters after LazyTransformParams

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This PR includes one change:
- expose `tanh`, `exp`, `negative`, and `permute` in NN frontend
> [Relax][Frontend] Add op `tanh`, `exp`, `negative`, and `permute`

- src/relax/ir/block_builder.cc
- src/script/ir_builder/relax/utils.h
- src/script/printer/relax/binding.cc
- tests/python/relax/test_transform_lift_transform_params.py
- tests/python/relax/test_transform_normalize.py
- tests/python/relax/test_tvmscript_printer_relax.py
This is a follow-up commit to https://github.com/apache/tvm/pull/16641.  While parsing of relax expressions without a variable binding could be implemented at that point (e.g. `R.assert_op(condition)` instead of `dummy_var = R.assert_op(condition)`), the corresponding printing changes could not.  This was because a variable that satisfies `relax::HasVoidStructInfo(var)` could still be used later in the function, and removing its binding would result in use of an undefined variable.
This commit normalizes use of void-type variables to an in-line `R.tuple()`.  This simplifies the relax function, and also allows the binding of void-type variables to be hidden.
> [Relax] Normalize use of void-type variable to inline R.tuple() 

- src/runtime/relax_vm/paged_kv_cache.cc
This PR fixes an issue in PagedKVCache, where a compute stream will always be fetched. For backends like WebGPU, the `GetCurrentStream` function is not implemented, which leads to an error when fetching the compute stream.
> [Fix] PagedKVCache fetching compute stream when copy stream is needed

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/topi/arm_cpu/injective.py
- src/target/parsers/cpu.cc
- tests/cpp/target_test.cc
- tests/python/auto_scheduler/test_auto_scheduler_search_task.py
- tests/python/autotvm/test_autotvm_graph_tuner_core.py
- tests/python/frontend/tflite/test_forward.py
- tests/python/integration/test_legacy_tuning.py
- tests/python/relay/aot/test_aot_create_function_metadata.py
- tests/python/relay/strategy/test_select_implementation.py
- tests/python/relay/test_any.py
- tests/python/relay/test_autotvm_task_extraction.py
- tests/python/relay/test_custom_datatypes.py
- tests/python/relay/test_op_qnn_conv2d.py
- tests/python/relay/test_op_qnn_leaky_relu.py
- tests/python/relay/test_pass_alter_op_layout.py
- tests/python/relay/test_roofline.py
- tests/python/runtime/test_runtime_module_based_interface.py
- tests/python/topi/test_topi_bitserial_dense.py
Currently, when a default compile target such as `llvm` is specified, it implies `llvm -keys=cpu` which tends to imply x86 related components being used during compilation e.g. the schedules registered in TOPI. This can be confusing for a user when compiling on other architectures, especially when other tools such as `llc` infer the default target based on the host.
When the target kind is `llvm`, this commit uses the "target.llvm_get_system_triple" functionality to automatically detect
`mtriple` when one has not been provided in the target string. The target will be updated to one that uses the `mtriple` of the host: `llvm -> llvm -mtriple=<system-triple>`. When compiling on Arm(R)-based targets, this has the added benefit of automatically introducing `-keys=arm_cpu` to the target …
> [Target] Automatically detect system triple when not specified by the user

- src/tir/analysis/verify_well_formed.cc
- src/tir/ir/tir_visitor_with_path.cc
- src/tir/ir/tir_visitor_with_path.h
- tests/python/tir-analysis/test_tir_analysis_verify_well_formed.py
- The `T.match_buffer` at the start of a function may contain repeated use of the same data var.  For example, a function that must accept two `DLTensor` objects with the same backing allocation.
- The `"buffer_bind_scope"` is an older style of match buffer, and may be the point of definition for variables.
- A `BufferRealize` node may act either as an annotation of an external buffer (which indices are used), or as a point of definition for a local buffer (allocation extents of that buffer).
> [TIR] Improve well-formed check's handling of match buffer

- include/tvm/runtime/data_type.h
- python/tvm/testing/utils.py
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
- src/tir/ir/data_type_rewriter.cc
- src/tir/ir/expr.cc
- src/tir/transforms/storage_rewrite.cc
- tests/cpp/tir_scalable_datatype.cc
- tests/python/codegen/test_target_codegen_aarch64.py
- tests/python/target/test_arm_target.py
This commit adds support for generating code for scalable loads and stores. It also adds support for the creation of scalable broadcast operations.
Co-authored-by: Elen Kalda <elen.kalda@arm.com>
Co-authored-by: Neil Hickey <neil.hickey@arm.com>
> [SVE] Add codegen support for scalable buffer accesses

- include/tvm/runtime/device_api.h
- include/tvm/runtime/ndarray.h
- src/runtime/ndarray.cc
This PR ensures that NDArray.CopyTo(Device) always sync. 
Prior to this PR, some of the behavior relied on undefined behavior,  as the per convention the underlying DeviceAPI may be async, but due to the cuda implementations was sync, we implicitly relied on that behavior.
This PR further clarifies in docs about the contract (that low-level device api is always async) as well as the sync/async nature of each NDArray API.
> [RUNTIME] Ensure NDArray.CopyTo(Device) always sync

- src/runtime/relax_vm/hexagon/builtin.cc
- tests/python/contrib/test_hexagon/test_dma_builtin.py
- While introducing dma operations at graph level, relax `KillAfterLastUse` pass introduces `kill_tensor` operation after `dma_copy`. This leads to memory being deallocated when asynchronous copy operation is in progress. Hence, moving the input/output buffers to `dma_wait` to ensure `kill_tensor` is introduced after `dma_wait` at the graph level.
- Also, the logic for size calculation is updated to use `GetDataSize` function. 
- The test case is updated to use offsets instead of allocating different storage in VTCM.
> [VM] [Hexagon] Add buffers to `dma_wait` builtin

- apps/cpp_rtvm/CMakeLists.txt
- apps/cpp_rtvm/main.cc
The original `win32_process.cc` is under `../cpp_rpc` directory, just correct it to fix build faillure on Windows.
> Fix cpp_rtvm cmake build on Windows

- src/runtime/relax_vm/kv_state.cc
- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR supports sliding window attention and attention sink for PagedKVCache, so that PagedKVCache can back models such as Mistral.
Meanwhile, this PR removes the "Attention" function (without fused-qkv) from AttentionKVCache interface, given its usage is now completely covered by the "AttentionWithFusedQKV" function. Considering the cost of maintenance, we decide to remove it for now. When in the future there is the need of this function, we will add it back.
This PR also unifies the global function names of the PagedKVCache with the KVState introduced earlier, and introduces a new KV cache raw info query function to get the current total sequence length in the KV cache.
> [Builtin] Sliding window and sink support for PagedKVCache

- python/tvm/dlight/gpu/gemv.py
Prior to this PR, there is one part missing in the shared memory estimation of the GeMV rule. The GeMV rule optimizes by using cross-thread reduction. When the target does not support warp reduction primitives, the cross-thread reduction will be further lowered to shared memory implementation, which consumes another part of shared memory.
If we do not consider this part in the GeMV rule, it is possible for the total shared memory usage to exceed the target shared memory limit. For example, mlc-ai/mlc-llm#1841 reports an issue on the Vulkan shared memory limit exceed.
This PR fixes the issue by introducing a flag `SUPPORT_WARP_SHUFFLE` to the GeMV rule. We only enable warp shuffle for CUDA and Metal backend, and turn it off for all other backends. This is basically aligned with the …
> [Dlight] Fix GeMV shared memory estimation

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- src/relax/transform/topological_sort.cc
- tests/python/relax/test_transform_topological_sort.py
This commit implements a utility `relax.transform.TopologicalSort`, which can re-order the bindings that occur in a
`relax.DataflowBlock`.  This is not intended for use in a general-purpose optimization pipeline, but instead as a utility that may be used as needed in specific cases.  For example, normalization of unit tests that should not depend on the order of variable binding.
> [Relax] Implement relax.transform.TopologicalSort

- src/tir/transforms/plan_update_buffer_allocation_location.cc
- tests/python/tir-transform/test_tir_transform_plan_update_buffer_allocation_location.py
Prior to this commit, the `tir.PlanAndUpdateBufferAllocationLocation` pass would attempt to merge buffer allocations, unless the buffer's backing allocation was found in a `Allocate`, `AllocateConst`, or `PrimFuncNode::params`.  Previous
PRs (e.g. https://github.com/apache/tvm/pull/10998) collected these locations and marked them as unmanaged.  However, this requires exhaustively checking all locations where unmanaged allocations could occur.
This PR updates `tir.PlanAndUpdateBufferAllocationLocation` to instead collect the managed buffers, and only perform rewrites of these managed buffers.  This only required inspection of `BlockNode`, and no other constructs.
The unit test added in this PR is another location where unmanaged buffers may be produced.
> [Bugfix][TIR] Avoid overwrite of unmanaged buffer allocations

- python/tvm/meta_schedule/relay_integration.py
`compile_relay()` has the same argument. It would be nice to have it to make the interface consistent across the metaschedule relay integration.
> [MetaSchedule] Make the `opt_level` of `tune_relay()` adjustable

- src/arith/const_int_bound.cc
- src/arith/rewrite_simplify.cc
- tests/python/arith/test_arith_const_int_bound.py
- tests/python/arith/test_arith_rewrite_simplify.py
Expressions of the form `(A+B)*C < (A*B)*D` can occur occur when comparing the number of operations required for two different orderings in which matrix multiplications can be performed. Proving or disproving this conditional allows an optimal order of execution to be selected, even for dynamic argument shapes.
The default behavior of `ConstIntBounds` assumes that each term in an expression is independent.  For example, the maximum value of `(A+B)*C - (A*B)*D` is determined by taking the maximum value of `(A+B)*C` and subtracting the minimum value of `(A*B)*D`.  This algorithm can be applied in all cases, but can provide a bound that is looser than strictly required.
This commit adds a check for this case in `ConstIntBounds`, to provide a tighter bound of possible values.  When `A`, `B`, …
> [Arith] Provide tighter ConstIntBounds for special cases

- python/tvm/contrib/nvcc.py
- src/target/tag.cc
- src/target/target_kind.cc
Latest GPU like H100 supports `sm_90a` arch, this breaks the previous assumption that the arch can be parsed as an integer.
Also updated the predefined arch for H100.
cc @tqchen
> [Target][CUDA] Allow non-numeric arch as needed for latest gpu

- include/tvm/runtime/memory/memory_manager.h
- src/runtime/memory/memory_manager.cc
- src/runtime/memory/naive_allocator.h
- src/runtime/memory/pooled_allocator.h
- src/runtime/relax_vm/builtin.cc
- src/runtime/vm/vm.cc
- tests/cpp/runtime/memory/memory_manager_tests.cc
Prior to this PR, each allocator is closely tied with a device. To enable using a same allocator across different devices of the same kind when needed, we lift the device to the allocator `Alloc` interface.
> [Refactor][Runtime] Always specify device in allocator interface

- cmake/modules/contrib/CLML.cmake
The first fix related to the problem when we build TVM with `USE_CLML` option and OpenCL header files were not found in the system. The second fix is for building CLML graph executor in Android build. `find_library` on MacOS is looking for libraries with `dylib` extension.  This is why OpenCL libraries from CLML SDK were not found. To fix this problem we specify paths to the libraries manually in case if they were not found by `find_library`.
cc: @srkreddy1238
> [CLML] Fix build TVM with CLML on MacOS

- include/tvm/relax/transform.h
- python/tvm/relax/transform/transform.py
- src/relax/transform/lift_transform_params.cc
- tests/python/relax/test_transform_lift_transform_params.py
This PR enables specifying a list of function names to extract shared transform parameters. A single parameter transformation function will be produced, containing the preprocessing steps common across each function whose name is in a given function name list. 
Unit tests are passing except the one that has no shared prepocessing (transpose), skipping for now, will follow-up in another PR.
Cherry-picked from @vinx13's working branch.
> Enable Shared Function in LiftTransformParam Pass

- include/tvm/arith/analyzer.h
- python/tvm/arith/__init__.py
- python/tvm/arith/analyzer.py
- src/arith/analyzer.cc
- src/arith/const_int_bound.cc
- src/arith/rewrite_simplify.cc
- src/arith/rewrite_simplify.h
- tests/python/arith/test_arith_const_int_bound.py
- tests/python/arith/test_arith_rewrite_simplify.py
This is a follow-up to https://github.com/apache/tvm/pull/16588.  Due to an incorrect rebase, the version that was merged into `main` had the tighter `ConstIntBounds` enabled by default, rather than having them implemented in `RewriteSimplifier`, gated behind a feature flag.
> [Arith][Fixup] Require feature flag for tighter inequality bounds

- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
Since #16692 introduced the copy stream separation, the function `GetQueryPositions` also needs to eagerly call sync to work properly. This PR fixes the previous wrong behavior.
> [Fix][Builtin] Fix "GetQueryPosition" of PagedKVCache

- python/tvm/runtime/disco/process_pool.py
Prior to this PR, module "psutil" is imported at the top level of the disco process pool. The pool will try to kill all the processes at the time of destruction (when `__del__` is implicitly invoked). The `__del__` function eventually calls into a function that uses `pstuil`. But it is possible that the top-level `psutil` has already been released by Python, which leads to a KeyError as follows:
```
Exception ignored in: <function DiscoPopenWorker.__del__ at 0x7f2c922bfe20>
File "/home/ruihangl/Workspace/tvm/python/tvm/runtime/disco/process_pool.py", line 67, in __del__
File "/home/ruihangl/Workspace/tvm/python/tvm/runtime/disco/process_pool.py", line 81, in kill
File "/home/ruihangl/Workspace/tvm/python/tvm/runtime/disco/process_pool.py", line 162, in …
```
> [Fix] Lazy import of "psutil" in disco process pool

- src/tir/schedule/primitive/cache_read_write.cc
- tests/python/tir-schedule/test_tir_schedule_cache_read_write.py
Prior to this commit, cache_read primitive may not update the block reads buffer region properly when there is a nested buffer access.  
```python
@T.prim_func
def cache_read_nested_buffer_access(var_A: T.handle, var_B: T.handle, var_C: T.handle):
for ax0, ax1 in T.grid(T.int64(1), T.int64(512)):
v_ax0, v_ax1 = T.axis.remap("SS", [ax0, ax1])
T.reads(A[B[v_ax0], v_ax1], B_global[v_ax0])
T.writes(C[v_ax0, v_ax1])
C[v_ax0, v_ax1] = A[B_global[v_ax0], v_ax1]
```
`T.reads(A[B[v_ax0], v_ax1])` should be updated as `T.reads(A[B_global[v_ax0], v_ax1])`
cc @Hzfengsy
> [Bugfix][TIR] Fix cache_read update buffer region

- python/tvm/relax/op/builtin/builtin.py
- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/ipc_allreduce_rewrite.py
- python/tvm/relax/transform/lower_gpu_ipc_alloc_storage.py
- src/relax/op/op.cc
- src/relax/transform/call_tir_rewrite.cc
- src/relax/transform/lower_alloc_tensor.cc
- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_ipc_allreduce_rewrite.py
- tests/python/relax/test_transform_lower_gpu_ipc_alloc_storage.py
This PR introduces the lowering passes for GPU IPC memory and all-reduce. It contains the following changes:
1. a pass `IPCAllreduceRewrite` which rewrites `"runtime.disco.allreduce"` to `"runtime.disco.cuda_ipc.custom_allreduce"`, and rewrites the storage scopes of the all-reduce inputs's from "global" to "ipc_memory" accordingly.
2. memory planning enhancement, making the planning be aware of storage scopes. So each storage scope will be planned independently.
3. a pass `LowerGPUIPCAllocStorage` that rewrites the storage allocation of IPC memory from builtin ops to calls to function `"runtime.disco.cuda_ipc.alloc_storage"`.
4. supports the op `relax.builtin.alloc_tensor` with storage scope. The default storage scope is `"global"`.
We write the new passes in Python for experiment and …
> [Relax][Pass] Lowering passes for GPU IPC memory and allreduce

- docker/Dockerfile.ci_cpu
- docker/install/ubuntu_install_aprofile_aem.sh
This commit adds the installation of the AArch64 Architecture Envelope Model (AEM) Fixed Virtual Platform (FVP) which can be used to test SME code generation functional correctness.
It also adds the installation of a baremetal toolchain which can be used to for compiling functions to run on the FVP.
> [SME][Docker] Add Fixed Virtual Platform (FVP) and toolchain install

- python/tvm/contrib/cc.py
- python/tvm/contrib/ndk.py
This PR adds nm symbol dump utils so we can use it to validate static compiled files.
> [CONTRIB] Add nm symbol dump

- ci/jenkins/docker-images.ini
- python/tvm/testing/aot.py
- tests/python/integration/test_arm_aprofile.py
- tests/python/relay/aot/aprofile_aem.mk
- tests/python/relay/aot/aprofile_extra_support_routines.c
This commit adds the infrastructure required for testing compiled functions that use SME. A more in depth discussion can be found here: https://github.com/apache/tvm-rfcs/blob/main/rfcs/0107-scalable-matrix-extension-enablement.md#testing
Specifically, this commit adds: the installation of the AArch64 Architecture Envelope Model (AEM) Fixed Virtual Platform (FVP), supporting files for compiling and running a graph on the FVP, sample tests which can be removed once TVM can generate SME and some enhancements to the AOT testing infrastructure so that TVM compiled functions can be run on the FVP.
> [SME][AOT] Add Fixed Virtual Platform (FVP) functional testing infrastructure

- src/target/llvm/codegen_llvm.cc
- tests/python/tir-base/test_debug_info.py
Prior to this commit, the `CodeGenLLVM::GetDebugType` would raise an exception if it could not convert the TIR data type to an equivalent DWARF type for debug symbols.  This commit updates the behavior to instead return `nullptr`, representing an unknown type in DWARF
> [LLVM] Lack of DWARF type is not an error

- python/tvm/relax/frontend/nn/core.py
- python/tvm/relax/frontend/nn/exporter.py
- python/tvm/relax/frontend/nn/spec.py
- tests/python/relax/test_frontend_nn_exporter.py
- tests/python/relax/test_frontend_nn_extern_module.py
- tests/python/relax/test_frontend_nn_modules.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_frontend_nn_packing.py
- tests/python/relax/test_frontend_nn_subroutines.py
Prior to this commit, the weights used by `nn.Module` instances were required to be `nn.Parameter` instances.  This commit allows the weights to instead be `nn.Tensor` instances, defined in terms of other `nn.Parameter` weights.  This allows a model to define both the original weights that would be present in an external checkpoint (e.g. a Pytorch or Safetensors file), and the pre-processing that should be performed on those weights.
> [SLM] Allow modules to define pre-processing of weights

- src/runtime/relax_vm/hexagon/builtin.cc
- tests/python/contrib/test_hexagon/test_dma_builtin.py
- This is needed as Hexagon DMA engine expects cache maintenance by applications.
- This change ensures accuracy in bypass_cache mode.
> [VM][Hexagon] Cache operations when bypass mode is enabled

- python/tvm/relax/transform/ipc_allreduce_rewrite.py
- python/tvm/relax/transform/lower_gpu_ipc_alloc_storage.py
This commit removes the redundant invocation of `remove_all_unused` function in the GPU IPC memory allocation lowering pass. This is because the pass only mutates one call at a time, and thus will not introduce new unused bindings.
> [Fix] Remove redundant "remove_all_unused" in IPC memory lowering

- python/tvm/dlight/gpu/gemv.py
- python/tvm/dlight/gpu/low_batch_gemv.py
- tests/python/dlight/test_gpu_low_batch_gemv.py
This PR fixes an issue in the dlight GeMV rule and the low-batch GeMV rule. The issue happens when the inner spatial loop has small length (e.g., in the MoE gate layer, this length is usually 8).
The error is because the GeMV scheduling does not make sure that each TIR block reads/writes the same number of local registers, and this inconsistency leads to wrong generated code. For example, in the schedule (prior to this fix), the first TIR block was scheduled to assign each thread 2 local registers, while the second block was scheduled to assign each thread 1 local register, which is incorrect. Unfortunately, this error only shows up when the spatial loop has small length.
One regression test is added.
> [Fix][Dlight] (Low-batched-)GeMV on small spatial loops

- src/relax/op/op.cc
- tests/python/relax/test_analysis.py
- tests/python/relax/test_transform_cse.py
- tests/python/relax/test_tvmscript_parser.py
This PR fixes the purity flag of `relax.vm.call_tir_dyn` and another few "kill" ops. Their purity flags were set to True, which made them possible to be removed by `remove_all_unused`.
* `relax.vm.call_tir_dyn` works by mutating the input args in place, which is not pure.
* though the "kill" ops have no actions so far, their semantics suggest that they are impure.
A regression test is added to prevent the unexpected removal from happening again.
> [Fix] Fix the purity flag of "vm.call_tir_dyn" and "kill" ops

- python/tvm/contrib/thrust.py
There has been a warning saying "Thrust is enabled when building TVM but is not specified in the input target" for years, while it is totally fine that the target does not contain thrust in `libs`, in which case we just do not dispatch.
This PR removes the warning.
> [Contrib] Remove thrust "built but not used" warning

- include/tvm/tir/transform.h
- python/tvm/tir/transform/transform.py
- src/driver/driver_api.cc
- src/tir/transforms/unsupported_dtype_legalize.cc
- tests/python/tir-transform/test_tir_transform_fp8_legalize.py
This PR cleans up the interface for the FP8 legalization passes by having them use the target attributes that are added by the `BindTarget` pass. This not only removes the need to pass the target as a parameter to those passes but also, in principle, allows for PrimFuncs with different targets to coexist and be handled correctly by the passes. Thanks to @Lunderberg for giving the suggestion.
> [TIR][Driver] Use `BindTarget` to specify target for FP8 legalization

- python/tvm/testing/aot.py
- tests/python/relay/aot/test_aot_test_harness.py
Enhanced AOT test harness to include overall mismatch percentage and the individual mismatch positions from the output tensor for debugging test failures. Both of these are still gated behind `print_output_on_mismatch == True`.  
I also added tests to check for the presence and correctness of this new debug information.  
Sample output:
```
Element [Position]: Actual, Reference
-------------------------------------
Element [0, 8, 8, 7]: 521.846313, 521.847412
Element [0, 9, 8, 51]: 478.874359, 478.875549
Element [0, 9, 9, 6]: 462.901001, 462.899658
Mismatched elements: 3 / 16384 (0.02%)
...
```
cc @lhutton1 @ekalda
> [AOT][Testing] Improve output mismatch information on test failure

- python/tvm/_ffi/runtime_ctypes.py
NumPy 2.0 removes the dtype `np.float_`, which may introduces compatibility issue for TVM.
> [Fix] Fix numpy dtype map

- src/relax/analysis/well_formed.cc
There are a few places in the malform check that prints pointers. This PR updates them to their references.
> [Relax] Improve malform error msg

- src/runtime/metadata.cc
- src/tir/analysis/identify_memcpy.cc
- src/tir/contrib/ethosu/passes.cc
This patch fixes all the build errors from VS2022. With this patch we can build tvm.dll successfully with VS2022.
> [Fix] Fix build errors with VS2022

- src/target/source/literal/cuda_half_t.h
> [Codegen, Cuda] Add overload for fp8x4 e5m2 <-> half4 conversion

- include/tvm/relax/analysis.h
- python/tvm/relax/analysis/analysis.py
- python/tvm/script/parser/core/entry.py
- src/relax/analysis/well_formed.cc
- tests/python/relax/test_analysis_well_formed.py
- tests/python/relax/test_tvmscript_parser.py
Prior to this commit, the post-parsing well-formed check performed by TVMScript allowed a call to `GlobalVar` in a `@R.function`, but only if it occurred within the context of a `@I.ir_module`.  If `@R.function` appeared on its own, calls to a `GlobalVar` would be treated as calls to an undefined function.
> [Analysis] Allow calls to GlobalVar in @R.function

- include/tvm/relax/expr.h
- src/node/structural_equal.cc
- src/relax/ir/expr.cc
- tests/python/relax/test_utils.py
Prior to this commit, `tvm.ir.assert_structural_equal` would highlight an entire `relax::BindingBlock` if the number of elements in the binding block differs.  This can result in the entire Relax function being highlighted, making it difficult to identify the location of the mismatch.
This commit makes the following changes, to improve the error messages that occur when `tvm.ir.assert_structural_equal` raises an exception.
- In `"node.StructuralEqual"`, set `defer_fails = true` when `assert_mode` is true.  This highlights the first mismatch of an `Array<relax::Binding>`, rather than the entire array, in cases where the LHS and RHS have different sizes.
- In the `SHashReduce` for `VarBinding` and `MatchCast`, visit the value first, and then the variable to which it is bound.  This …
> [IR][Relax] Improve highlighting in assert_structural_equal

- python/tvm/contrib/cutlass/build.py
Introduced in https://github.com/apache/tvm/pull/16745, should be the string `"Composite"`, not the bytes `b"Composite"`.
> [Bugfix][Cutlass] Remove a typo in cutlass build

- include/tvm/relax/dataflow_matcher.h
- src/relax/ir/dataflow_matcher.cc
Prior to this commit, the `PatternRewriter` mutator handled pattern rewriting at either the expression level (`rewrite_call`) or the dataflow block level (`rewrite_bindings`).  These two functionalities had different external APIs, defined diffierent member variables, and visited different IR nodes.  In effect, it had two entirely independent implementations, which just happened to be implemented within the same class.
This commit refactors the single `PatternRewriter` mutator into separate `BlockPatternRewriter` and `ExprPatternRewriter` mutators.
> [Relax] Refactor PatternRewriter into separate Block/Expr mutators

- web/emcc/wasm_runtime.cc
Fix the outdated `wasm_runtime` to include the `kv_state` and `rnn_state`
cc @CharlieFRuan @tqchen
> [Web] Add `kv_state` and `rnn_state` to wasm_runtime

- python/tvm/topi/arm_cpu/pstate_attributes.py
- src/target/llvm/codegen_aarch64.cc
- tests/python/codegen/test_target_codegen_aarch64.py
Execution of SME instructions requires the processor be in a certain state. This functionality can be can be controlled using LLVM function level annotations such as "aarch64_pstate_sm_enabled" or "aarch64_pstate_za_new" (see arm_utils.py for more information).
This commit exposes this functionality for AArch64 schedules where SME intrinsics will be called. The attributes are intended to be added at the block-level around the compute definition. They are prepended with "pragma" to ensure they remain in the lowering.
In order to detect these attributes and convert them to the relevant LLVM function attributes, a new AArch64 LLVM codegen backend is added. This backend extends the functionality of `codegen_llvm` for AArch64 specific compilation.
Tests to check these attributes propagate …
> [SME] Add support for inserting processor state annotations

- python/tvm/_ffi/runtime_ctypes.py
- python/tvm/relay/frontend/paddlepaddle.py
- python/tvm/relay/frontend/pytorch.py
- tests/python/contrib/test_msc/test_translate_tensorflow.py
- tests/python/frontend/pytorch/test_forward.py
- tests/python/frontend/tensorflow/test_forward.py
- tests/python/relay/test_op_level3.py
- tests/python/topi/test_topi_math.py
I checked the entire tvm codebase with `ruff check . --select NPY201` and no other deprecations were detected.
Changes are below.
- use `-np.inf` instead of `np.NINF`
- use `np.inf` instead of `np.infty`
- better attribute existence check #16780 
ref: [NumPy 2.0 migration guide — NumPy v2.1.dev0 Manual](https://numpy.org/devdocs/numpy_2_0_migration_guide.html)
> [Fix] fix for numpy 2.0 compatibility

- python/tvm/tir/schedule/schedule.py
Minor fix to update the `set_axis_separator` example to match the definition
> [Doc] Fix set_axis_separator example

- 3rdparty/tensorrt_llm/custom_allreduce_kernels.h
- python/tvm/relax/transform/ipc_allreduce_rewrite.py
- src/runtime/disco/cuda_ipc/cuda_ipc_memory.cc
- src/runtime/disco/cuda_ipc/custom_allreduce.cc
- tests/python/disco/test_custom_allreduce.py
This PR adds the automatic mode selection for customized all-reduce kernels, referring TensorRT-LLM.
Meanwhile, this PR fixes a bug that may cause customized all-reduce kernel to hang forever. Prior to this PR, each worker resets its barrier values to 0 *after using all-gather to exchange their barrier handles*. Afterwards, the customized all-reduce kernels update the barriers of all workers. So it is possible that, worker 0 updates worker 1's barrier *before* worker 1 resets its barrier to 0. This lead to the all-reduce kernel hanging forever.
This PR changes the behavior to resetting barriers before all-gather, and forcing a device synchronization after reset.
> [3rdparty] AUTO mode for custom all-reduce strategy

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
If there is a trivial binding of `Var = DataflowVar`, but the non-dataflow variable is never used outside the dataflow block in which is is declared, then we should keep the name of the upstream `DataflowVar`, as it is more likely to be the human-readable name (e.g. a function parameter).
> [Relax] Improve CanonicalizeBindings in DataflowVar edge case

- python/tvm/runtime/disco/session.py
This is a follow-up to #16618, which propagates the `structlog` configuration to disco worker processes.  For configurations that use `structlog.stdlib` to integrate `structlog` with the stdlib `logging` module, this integration must also be forwarded.
> [Disco] Propagate structlog/logging config to workers

- python/tvm/target/codegen.py
- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
- src/target/parsers/aprofile.cc
- tests/cpp/target/parsers/aprofile_test.cc
- tests/python/relay/strategy/test_select_implementation.py
- tests/python/target/test_llvm_features_info.py
Currently, target features are determined by a set of fixed checks on the target string. This works well for checking support of a small number of simple features, but it doesn't scale. Some problems include:
- There are many non-trivial conditions for which a feature may(not) be available. It is easy to miss these with the current implementation.
- The inclusion of some features in a target string can imply other features. For example, "+sve2" implies "+sve". This currently isn't taken into account.
- The tests in tests/cpp/target/parsers/aprofile_test.c suggest that targets such as "llvm -mcpu=cortex-a+neon" and "llvm -mattr=+noneon" are supported target strings. The features will be correctly parsed in TVM, however, they are not valid in LLVM. Therefore, it's possible that TVM and LLVM …
> [Target] Use LLVM target parser for determining Arm(R) A-Profile Architecture features

- src/relax/ir/dataflow_matcher.cc
- tests/python/relax/test_dataflow_pattern.py
The `rewrite_call` function accepts a `DFPattern`, and a function to
rewrite expressions matching that pattern.  Often, the rewriting
function will perform additional validation that cannot be expressed
within the `DFPattern` itself.  If this additional validation fails,
the rewriter function will return the matched expression unmodified.
Prior to this commit, an `OrPattern` that matches on the first branch,
but whose rewriter function does not apply a modification, would
prevent the second branch from being checked.  This commit updates the
`ExprPatternRewriter` to check both branches of a `OrPattern`, if the
rewriter function of the first branch does not modify the result.
> [Relax] Allow composition of DFPattern replacements 

- src/relax/transform/lift_transform_params.cc
The `LiftTransformParams` pass requires Relax functions that have the `attr::kNumInput` attribute (`"num_input"`).  By default, it collects and applies only to functions with this attribute.  If the user specifies functions that don't match this criteria, the `LiftTransformParams` will raise an error.
This commit improves the error messages that are raised when the specified function is missing, is not an IRModule, or is missing the `kNumInput` attribute.  Previously the error messages were raised implicitly by `IRModule::Lookup`, `Downcast<Function>`, or `Optional::value`, respectively.
> [Debug] Improve error messages in LiftTransformParams

- src/relax/backend/vm/vm_shape_lower.cc
If `VMShapeLower` raises an error, specify which function produced the error.
> [Debug] Improve error message in VMShapeLower

- include/tvm/tir/analysis.h
- python/tvm/error.py
- python/tvm/relax/op/base.py
- python/tvm/relax/pipeline.py
- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/transform.py
- python/tvm/script/ir_builder/relax/ir.py
- python/tvm/script/parser/tir/parser.py
- python/tvm/tir/analysis/analysis.py
- src/relax/analysis/struct_info_analysis.cc
- src/relax/backend/vm/vm_shape_lower.cc
- src/relax/op/tensor/inspect.cc
- src/relax/transform/compute_prim_value.cc
- src/relax/transform/dataflow_inplace.cc
- src/relax/utils.cc
- src/tir/analysis/is_pure_function.cc
- src/tir/ir/function.cc
- src/tir/ir/specialize.cc
- src/tir/transforms/renew_defs.cc
- tests/python/relax/test_analysis_well_formed.py
- tests/python/relax/test_backend_transform_shape_lower.py
- tests/python/relax/test_relax_operators.py
- tests/python/relax/test_transform.py
- tests/python/relax/test_transform_compute_prim_value.py
- tests/python/relax/test_tvmscript_parser.py
- tests/python/relax/test_vm_codegen_tir.py
- tests/python/tir-analysis/test_tir_analysis_is_pure_function.py
- tests/python/tir-base/test_tir_specialize.py
- tests/python/tvmscript/test_tvmscript_parser_tir.py
Prior to this commit, the condition used for `relax::If` node and the `"relax.assert_op"` operator was required to be a scalar tensor.  This made it difficult to alter behavior based on a runtime shape parameter.  For example, delegating to a vectorized implementation based on a whether a tensor shape is divisible by the vector size.
This commit adds support for expressions of type `R.Prim('bool')` as the conditional for `relax::If` and `"relax.assert_op"`, to allow these use cases.
> [Relax] Allow R.Prim('bool') in relax::If and assert_op 

- include/tvm/runtime/nvtx.h
This PR adds the `TVM_DLL` attribute to the nvtx header for windows build.
> [Runtime] Add "TVM_DLL" to NVTX header

- python/tvm/target/tag.py
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/llvm_instance.cc
- src/target/tag.cc
- tests/python/target/test_llvm_features_info.py
This PR fixes TVM loading errors when lower LLVM version does not support TVM predefined target tags.
Report and related discussions are here: https://github.com/apache/tvm/pull/16425#issuecomment-2023292845
---
* During tvm load/initialization [list_tags()](https://github.com/apache/tvm/blob/83e7e9b2eb8dbeeb16dcfdbaf3336caa81071877/python/tvm/target/tag.py#L71) checks all ```src/target/tag.cc``` target definitions
* The target tags **should be protected** against improper LLVM versions at their declaration time
* Enforce the ```mcpu=generic``` [fallback assignment](https://github.com/apache/tvm/pull/16808/files#diff-f13c79368edd27b0c05d044df267746187448906d4310d5617bce89003b8813bR230-R231), so LLVM will not noise us with improper invocation 
* Minor compilation fix for LLVM version …
> [Runtime][LLVM] Fix errors during loading of target tags

- tests/python/relax/test_frontend_nn_exporter.py
Follow-up to https://github.com/apache/tvm/pull/16777, add unit tests demonstrating desired behavior.
> [SLM] Add unit tests for SLM to Relax exporter

- docker/install/ubuntu_install_papi.sh
- docs/how_to/profile/papi.rst
- src/runtime/contrib/papi/papi.cc
Changes are below
- Change the PAPI repo URL because it has been moved to GitHub
- Add a missing closing curly bracket
> [Fix] PAPI docs

- src/target/llvm/llvm_instance.cc
This is just a minor fix where the recent [PR #16425](https://github.com/apache/tvm/pull/16425) seems to have missed this change for LLVM 18 and above case, and so we're running into a compilaion failure.
> [LLVM] Fix compilation failure due to minor change

- include/tvm/relax/utils.h
- src/relax/transform/rewrite_cuda_graph.cc
- src/relax/utils.cc
- src/runtime/relax_vm/cuda/cuda_graph_builtin.cc
- tests/python/relax/test_transform_rewrite_cuda_graph.py
> [Relax] Enable capturing symbolic shapes in cuda graph

- include/tvm/runtime/disco/builtin.h
- include/tvm/runtime/disco/session.h
This PR adds the `TVM_DLL` attribute to `Session` class in Disco for Windows builds.
> [Fix] Add TVM_DLL to Disco session

- python/tvm/contrib/emcc.py
When running `emcc` for building a wasm, we currently only pass in libraries `wasm_runtime.bc`, `tvmjs_support.bc`, and `webgpu_runtime.bc`. This PR allows users to optionally pass in their own `.bc` files by adding a kwarg `libs`.
> [Web] Allow custom bc files in emcc making

- python/tvm/auto_scheduler/task_scheduler.py
When Ansor does not find a schedule for a task in warm up, Ansor gradient gets stuck in this task, because there is no optimized schedule for this task. Hence, Ansor does not optimize any task.
Behavior before correction
Behavior after correction
> [BugFix][Ansor] Fixing Ansor Gradient Bug

- src/tir/ir/expr.cc
- tests/python/arith/test_arith_rewrite_simplify.py
- tests/python/tir-base/test_tir_nodes.py
When Ramp and Broadcast nodes are created with fixed length lanes,
they're fixed to int32 dtype since DLDataType always supports only
uint16 lanes.
> [TIR] Ramp and Broadcast lanes fixed to int32 dtype

- src/relax/ir/block_builder.cc
- tests/python/relax/test_blockbuilder_core.py
Prior to this commit, the implementation of `relax::BlockBuilder::AddFunction` implicitly assumed that the input `IRModule` does not contain duplicate copies of the same function. This commit updates the implementation, removing the reliance on this assumption.  This commit resolves the error by tracking all `GlobalVar` that map to the same function, rather than an just one.
A well-formed IRModule may contain duplicate function definitions. This is rare, as most functions can be disambiguated by the the function attribute `tvm::attr::kGlobalSymbol`.  However, private functions do not have this attribute, and a well-formed IRModule may contain multiple copies of the same function.
The regression test added in this PR calls `BlockBuilder::UpdateFunc` and `BlockBuilder::AddFunc` in a …
> [Bugfix][Relax] BlockBuilder may not assume unique input functions

- src/relax/ir/dataflow_matcher.cc
- tests/python/relax/test_dataflow_pattern.py
This resolves a bug that was introduced in https://github.com/apache/tvm/pull/16732.  If a rewriter function returned a no-op, and the pattern-match continued, then the `matches` provided to the rewriter function in subsequent calls would contain a variable to which the matched expression was bound, not the matched expression itself.  (e.g. For a match of `C = R.add(A,B)`, passing `C` to the rewriter instead of `R.add(A,B)`.)
This bug was caused by incorrect re-wrapping of `OrPattern` in `ExprPatternRewriter`.  Prior to https://github.com/apache/tvm/pull/16732, all pattern-match results were populated by `ExtractMatchExpr`, and contained the result after applying `TryGetValOfVar`.  When re-wrapping the result of an `OrPattern`, https://github.com/apache/tvm/pull/16732 populated the …
> [Relax][Bugfix] Provide the full Expr to pattern-match rewriter

- src/relax/transform/rewrite_cuda_graph.cc
- tests/python/relax/test_transform_rewrite_cuda_graph.py
This PR makes storage among different functions shared after cuda graph rewriting. Because CUDA graph cache storage, storage objects are not freed after function execution, this will increase memory usage if there are multiple functions. Making storage objects shared eliminate such overhead.
It also updates rewriting to prevent capturing storages and bindings used as function output. Previous we relies on the fact output tensors are allocated with `R.builtin.alloc_tensor`, however, this behavior changed after we enable storage planning for output tensor, which may also use `R.memory.alloc_memory`
cc @tqchen
> [Relax] Share storage allocs among functions after cuda graph rewriting

- src/runtime/disco/process_session.cc
- src/runtime/disco/threaded_session.cc
This PR reduces the number of reads and writes for the message queue of ProcessSession and ThreadSession in Disco by caching all the data to read/write.
The message queue in ThreadSession prior to this PR grabs the mutex for multiple times for a batch of data to read/write. This PR enables to read/write data from/to a local buffer first, and then read/write from/to the critical region together. This reduces the number of grabbing mutex to once.
The message queue in ProcessSession prior to this PR reads/writes the inter-process pipe for multiple times for a batch of data. This PR uses a local buffer to cache all the data first, and then issues a single read/write from/to the pipe, and effectively reduces the number of reads/writes to the pipe, which may causes extra system overhead.
> [Disco] Reduce Process/ThreadSession message queue reads and writes

- src/target/parsers/aprofile.cc
- tests/cpp/target/parsers/aprofile_test.cc
This commit adds support for recognising when the SME architecture feature is available based on the target string. A python user can use target.features.has_sme to check availability.
~This PR relies on #16425, the actual changes can be found [here](https://github.com/apache/tvm/pull/16794/commits/35c3fa633357a9b04fbd628be8a3403f3865640d)~
> [SME] Target parser support for SME

- src/runtime/disco/builtin.cc
- src/runtime/threading_backend.cc
This PR supports setting the CPU affinity for disco workers. Specifically, a global function `runtime.disco.bind_worker_to_cpu_core` is added to allow accepting a list of CPU ids, and then set the CPU affinity for workers.
This can potentially reduce the OS scheduling overhead that increases the disco worker pthread conditional waiting time before being waken up.
> [Disco] Support setting workers' CPU affinity

- src/relax/transform/rewrite_cuda_graph.cc
- tests/python/relax/test_transform_rewrite_cuda_graph.py
weights may have symbolic shapes. We assume any args in `params[num_inputs:]` to be weights (with fixed buffer address), so it's safe to capture these symbolic vars as well even if it's not provided in the hints.
cc @tqchen
> [Relax] Capture symbolic vars in struct info of weights

- src/relax/transform/dead_code_elimination.cc
- tests/python/relax/conftest.py
- tests/python/relax/test_transform_dead_code_elimination.py
The `tvm.ir.transform.ApplyPassToFunction` allows a transform to be applied selectively to some portions of a `IRModule`, without applying to the entire `IRModule`.  For example, to apply an optimization pass (e.g. `relax.transform.ExpandMatmulOfSum`) or an interface-altering pass (e.g. `relax.transform.BundleModelParams`) to specific functions.  It does so by generating an intermediate `IRModule` containing only the functions specified, applying the transform to that intermediate, then merging the results.
When using `ApplyPassToFunction` to apply `DeadCodeElimination`, or a pipeline containing `DeadCodeElimination`, this intermediate `IRModule` may contain calls to `GlobalVar` instances that are not within the intermediate `IRModule`.  Prior to this commit, this resulted in an error …
> [Relax] Allow DeadCodeElimination within ApplyPassToFunction

- src/relax/transform/lazy_transform_params.cc
- tests/python/relax/test_transform_lazy_transform_params.py
Prior to this commit, symbolic variables inferred from the parameters were retained in the output function's `ret_struct_info`.  This is ill-formed, as the parameters from which these symbolic variables are inferred are no longer part of the function signature.
This commit updates `LazyGetInput` to use `EraseToWellDefined` to remove any symbolic variables from `ret_struct_info` that cannot be inferred from the remaining arguments.
> [Relax] Provide well-formed output in `transform.LazyGetInput`

- src/runtime/disco/disco_worker.cc
Prior to this commit, attempting to execute the result of `sess.get_global_func` for a non-existing function name would result in a segfault.  While the equivalent `tvm.get_global_func` can throw an exception when looking up the function, Disco returns a `DFunction` immediately.  This `DFunction` may resolve to a null pointer, and should be checked in the worker process before calling it.
> [Debug][Disco] Check if a PackedFunc exists before calling it

- rust/tvm-graph-rt/tests/test_tvm_basic/build.rs
- src/tir/transforms/arg_binder.cc
- src/tir/transforms/arg_binder.h
- src/tir/transforms/make_packed_api.cc
- tests/python/contrib/test_hexagon/test_relax_2d_buffer_allocation.py
- tests/python/tir-base/test_debug_info.py
- tests/python/tir-transform/test_tir_transform_make_packed_api.py
Prior to this commit, the `MakePackedAPI` pass would output steps in the following order:
1. Check the number of arguments.
2. All `LetStmt` produced by the `ArgBinder`
3. `AssertStmt` for the Type code checks for each argument.
4. Additional `AssertStmt` produced by the `ArgBinder`.
This order can cause segfaults if a function was provided incorrect arguments.  For example, an integer argument passed to a function expecting a `DLTensor*` would be dereferenced to find the tensor's data pointer (step (2)) before checking if it is valid to perform that dereference (step (3)).  The same would occur when reading the size of a tensor's axes (step (2)) before checking whether the tensor is the correct dimensionality (step (4)).
This commit updates the steps to the following order.
1. Check the …
> [TIR] Fix segfaults from ordering of Let/Assert in MakePackedAPI

- python/tvm/contrib/ndk.py
- src/meta_schedule/utils.h
- tests/python/contrib/test_android/__init__.py
- tests/python/contrib/test_android/infrastructure.py
- tests/python/contrib/test_android/test_meta_schedule.py
Added OpenCL as a GPU target for Meta-Scheduler. Implemented export function for Android which can be used when MS builder is configured. Added an integration test which checks that MS tuning on Android GPU works fine.
cc: @masahi, @tqchen
> [Meta-Schedule][OpenCL] Enable MS tuning for Android OpenCL

- tests/python/relay/test_auto_scheduler_tuning.py
The `test_auto_scheduler_tuning.py::test_tuning_cuda` unit test has sporadic failures on unrelated changes.  Seems to be triggered when tuning does not find any valid candidates, and so the "best" candidate of a no-op triggers a "did you forget to bind" error message.
> [CI] Disable flaky unit test

- python/tvm/dlight/gpu/reduction.py
- tests/python/dlight/test_gpu_reduction.py
The current rule will fail when the output shape is only one element, because of missing `preserve_unit_loops`. This PR fixes it and adds a test case.
> [DLight] Fix a corner case for reduction rule

- src/relax/ir/expr.cc
- src/script/ir_builder/relax/frame.cc
- src/tir/ir/function.cc
- tests/python/relax/test_tvmscript_parser.py
A follow-up to https://github.com/apache/tvm/pull/16745.  For Relax functions produced in TVMScript, when `R.func_attrs` was not present, the default was set to `None` instead of an empty dictionary.
> [TVMScript] Produce empty DictAttrs when R.func_attrs is absent

- src/ir/apply_pass_to_function.cc
- src/ir/transform.cc
- tests/python/relax/test_transform_dead_code_elimination.py
Prior to this commit, `ApplyPassToFunction` removed functions from the `IRModule` to hide them from the inner `ir.transform.Pass`.  The dangling `GlobalVar` references to those functions meant that the intermediate `IRModule` was ill-formed This commit updates the `ApplyPassToFunction` utility to instead replace the functions with `ExternFunc` nodes.  This still prevents the inner `ir.transform.Pass` from having visibility into functions that should not be mutated, but provides a well-formed `IRModule`.
> [IR] Provide well-formed intermediate in ApplyPassToFunction

- python/tvm/relax/backend/dispatch_sort_scan.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/te/operation.py
- python/tvm/topi/cuda/scan.py
- python/tvm/topi/cuda/sort.py
- src/runtime/contrib/thrust/thrust.cu
- tests/python/relax/test_backend_dispatch_sort_scan.py
This adds an optional parameter `workspace` to thrust APIs so that a workspace can be passed to replace the internal allocations of thrust. `DispatchSortScan` pass is updated to allocate a workspace by overestimation of the workspace size.
> [Relax,Topi] Allow passing workspace to thrust to avoid allocations

- src/relax/op/op.cc
- src/relax/transform/eliminate_common_subexpr.cc
- tests/python/relax/test_transform_cse.py
This fixes a bug that CSE removing alloc tensors
cc @tqchen
> [Relax] Fix EliminiateCommonSubexpr removing alloc tensor

- src/runtime/relax_vm/paged_kv_cache.cc
This PR udpates PagedKVCache to initialize one more page than specified via constructor. The reason is that applications usually depends the number of free pages (returned from `GetNumAvailablePages`) to decide the KV cache operation policy. If there is no this extra page, the KV cache will tell "no available" pages even when the last allocated pages are not full, which may give the applications an illusion that the KV cache is already completely full, and cause further issues.
> [KVCache] Initialize one extra page than specified

- src/tir/schedule/primitive/layout_transformation.cc
- tests/python/relax/test_transform_legalize_ops_manipulate.py
Using the constructor applies all initialization steps and error-checking, where using `CopyOnWrite()` does not.  This function is used as part of the legalization of `relax.op.layout_tranform`, which relies on the annotations produced in the `PrimFunc` constructor.
> [TIR] Use constructor for new PrimFunc in TransformLayout

- python/tvm/relay/frontend/onnx.py
- tests/python/frontend/onnx/test_forward.py
Fix in interpreting auto_pad parameters SAME_UPPER and SAME_LOWER in ConvTranspose version 1 and 11 operator according to documentation on [link](https://onnx.ai/onnx/operators/onnx__ConvTranspose.html).
Tests that were failing are also added in test_forward.py.
Also, enable unsupported test for ONNX: test_convtranspose_autopad_same.
> [ONNX] Fix interpreting auto_pad parameters in ConvTranspose operator

- include/tvm/runtime/data_type.h
- include/tvm/tir/op.h
- src/tir/ir/expr.cc
- src/tir/transforms/vectorize_loop.cc
- tests/python/tir-transform/test_tir_transform_vectorize.py
This patch add support for turning loops marked for vectorizing into scalable vectors if the extent of the loop is a vscale dependent expression in a correct form.
The testing for both scalable and fixed length vectors in test_tir_transform.py has been extended and most of the tests have been converted to TVMScript based testing against expected output.
> [SVE] Support scalable vectors in LoopVectorizer

- python/tvm/target/detect_target.py
- src/arith/rewrite_simplify.cc
- src/tir/ir/data_type_rewriter.cc
- tests/python/arith/test_arith_rewrite_simplify.py
- tests/python/tir-transform/test_tir_transform_force_narrow_index_to_i32.py
CLZ (counting leading zeros) is used for improving ceil_log2 performance on vulkan. however, the current implantation is incorrect during dtype converting. This PR contains:
1. Simplify clz for index calculation (happens in vulkan sort)
2. Fix clz for data type conversion
> [VULKAN] Fix CLZ support for Vulkan

- 3rdparty/picojson/picojson.h
- 3rdparty/picojson/test_picojson.cpp
Previously picojson define `object` as an alias of `std::unordered_map`. That means when parsing json, the order of keys in objects are uncertain and dependent on implementation. This makes it inconvenient for certain applications, e.g. in LLM generation output, we wish the order of keys the same as the order in the json file.
This PR implements a ordered hashmap `ordered_hashmap` that 1) maintains the order in which the elements are inserted, and 2) have the same interface as `std::unordered_map`. Picojson will define object as an alias of `ordered_hashmap`, so the order of the input json is maintained when parsing.
Macro `PICOJSON_USE_ORDERED_OBJECT` controls whether object uses the ordered version or the unordered version. It is set by default.
> [Picojson] Let the key of objects in json be ordered by default

- python/tvm/relax/backend/dispatch_sort_scan.py
> [Relax] Dispatch sort/scan for non-cuda gpu backends

- src/target/parsers/cpu.cc
- tests/cpp/target_test.cc
- tests/cpp/tir_scalable_datatype.cc
I ran into a problem running a very simple ONNX compile, i would get a segfault at a FoldConstantExpr() call from TVMC. **This only happens if the compile flag `set(USE_LLVM OFF)` is OFF.**
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffc94ac78c in tvm::runtime::ObjectPtr<tvm::runtime::Object>::operator!=(decltype(nullptr)) const (this=0x0, null=<error reading variable: Attempt to dereference a generic pointer.>) at /home/otto/tvm/include/tvm/runtime/object.h:470
470       bool operator!=(std::nullptr_t null) const { return data_ != null; }
```
I had compiled TVM Using GCC:
```
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu …
```
> [BugFix][Target] Added null check to fix segfault at ->defined() in cpu.cc DetectSystemTriple()

- src/runtime/relax_vm/paged_kv_cache.cc
In some scenarios such as speculative decoding, it is possible to pop all the tokens in the last block. This PR allows `PopN` to pop all the tokens in the last block of KV cache.
> [PageKV] allow PopN to pop all the tokens in last block

- tests/python/micro/test_micro_ms_tuning.py
Bump flashinfer to enable compilation for group size = 6 GQA kernels
cc @tqchen
> [3rdparty] Bump flashinfer

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
This PR enhances the symbolic expression upper bound estimation in static memory planning.
Prior to this PR, we are not able to estimate the upper bound of `a * b` when `a` has an upper bound while `b` does not. This PR enhances the estimation with arith::IntSet.
We introduce another TIR attribute `tir_non_negative_var` to indicate the non-negative TIR variables for memory planning use.
A new unit test is introduced for this enhancement.
> [Relax] Enhance symbolic expr estimation in memory planning

- python/tvm/dlight/gpu/gemv.py
- tests/python/dlight/test_gpu_gemv.py
This makes weight loading from global to local vectorized. Usually for packed weight in uint32 format there is not much difference since uint32 already implies vectorization. This PR enhances vectorization when the weight is not packed.
cc @spectrometerHBH @tqchen
> [Dlight] Enhance vectorization loading weight for gemv

- python/tvm/_ffi/runtime_ctypes.py
- python/tvm/dlight/gpu/gemv.py
- python/tvm/dlight/gpu/low_batch_gemv.py
- tests/python/ir/test_dtype.py
Added a utility method `itemsize` to `DataType`, this is similar to `numpy.array.itemsize`
cc @tqchen
> [Runtime] Implemented Datatype.itemsize()

- python/tvm/tir/op.py
- src/tir/op/op.cc
- tests/python/codegen/test_target_codegen_cuda.py
- tests/python/tvmscript/test_tvmscript_parser_tir.py
`T.reinterpret` is a nop in cpp, this makes the python behavior consistent with cpp.
cc @tqchen
> [TIR] Make T.reinterpret nop when dtype is the same

- include/tvm/ir/module.h
- python/tvm/relax/frontend/nn/core.py
- src/ir/module.cc
- src/relax/transform/alter_op_impl.cc
- src/relax/transform/dead_code_elimination.cc
- src/relax/transform/fuse_ops.cc
- src/relax/transform/fuse_tir.cc
- src/relax/transform/legalize_ops.cc
The current implementation of the relax pass is not stable, to be more specific, the order of the mutation is not stable. This PR aims to stabilize the mutation order of the relax pass, and further stabilize the output of the relax pass.
Also fixes a minor doc typo in NN frontend
> [Relax] Stabilize relax pass mutation order

- include/tvm/te/schedule.h
- include/tvm/tir/schedule/schedule.h
- python/tvm/te/schedule.py
- python/tvm/tir/schedule/schedule.py
- src/arith/analyzer.cc
- src/arith/scalable_expression.cc
- src/arith/scalable_expression.h
- src/te/schedule/message_passing.cc
- src/te/schedule/schedule_lang.cc
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/loop_transformation.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- tests/python/arith/test_arith_simplify.py
- tests/python/meta_schedule/test_meta_schedule_post_order_apply.py
- tests/python/te/test_te_schedule.py
- tests/python/tir-schedule/test_tir_schedule_split_fuse.py
- tests/python/tir-schedule/test_tir_schedule_trace.py
This commit adds support for splitting via the compile-time unknown constant `vscale`. Two main changes are introduced; they are described below.
The split scheduling primitive has a new parameter disable_predication that allows the user to avoid introducing a block-level predicate when splitting with a factor of `vscale`. This feature is useful when schedule writers know that the loop they're splitting is a factor of the scalable vector length for their target. Otherwise, a predicate must be introduced due to the nature of `vscale`.
CanProve has been extended to prove expressions that use multiple instances of `vscale`. Known possible scalar values of the `vscale` intrinsic are iterated over and substituted into the expression. If the expression holds true for each possible value, we can …
> [SVE] Support splitting by vscale in `tir::split` and `te::split`

- python/tvm/dlight/gpu/matmul.py
- python/tvm/dlight/gpu/reduction.py
This adds a check of dtype before applying tensorization rule and fixes return value of reduction rule
cc @tqchen
> [dlight] Add check for matmul dtype and fix reduction rule

- include/tvm/runtime/data_type.h
- python/tvm/contrib/tvmjs.py
- python/tvm/relax/backend/contrib/cublas.py
- python/tvm/relax/transform/legalize_ops/qdq.py
- src/relax/backend/contrib/utils.h
- src/relax/op/tensor/qdq.cc
- src/runtime/contrib/cublas/cublas.cc
- src/tir/op/op.cc
- tests/python/relax/test_codegen_cublas.py
- tests/python/relax/test_op_qdq.py
This is attempt to bring [PR#63](https://github.com/octoml/tvm/pull/63) from `octoml/tvm` to `apache/tvm`.
This commit enables FP8 e4m3 matmul offloading to cuBLAS.
сс @vinx13 @JosephTheOctonaut
> [CUBLAS][FP8] Support e4m3 gemm in cuBLAS BYOC

- src/runtime/vulkan/vulkan_device.cc
- src/runtime/vulkan/vulkan_device.h
- src/runtime/vulkan/vulkan_device_api.cc
This PR supports total_global_memory query for vulkan devices.
> [RUNTIME][VULKAN] Support total_global_memory

- src/runtime/contrib/cublas/cublas.cc
This commit replaces fp16 compute dtype and scale dtype by fp32 in cublas matmul.
According to cuBLAS [docs](https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatmul) there are two possible options for compute/scale dtype when input/output dtype is fp16:
1. compute dtype is `fp16` and scale dtype is `fp16`
2. compute dtype is `fp32` and scale dtype is `fp32`
By default, we use 1) in apache/tvm and 2) in octoml/tvm. This commit aligns different behaviour and set `fp32` as default.
> [CUBLAS] Set fp32 compute and scale dtypes in fp16 matmul

- tests/python/relax/test_tvmscript_parser.py
Because Relax struct inference is performed while the function is being built, all constraints on symbolic variables that are used for simplifications must be provided to the analyzer.  This is not currently the case, nor is there a clear way to fix this issue.
This PR adds a failing unit test to document this limitation.
> [TVMScript][Bug] Add test case for missing symbolic bounds

- include/tvm/relax/expr.h
- src/relax/ir/expr.cc
Prior to this commit, the static method `relax::Function::CreateEmpty` returned a function with a nullptr as the body.  While only intended for use in bookkeeping for TVMScript, allowing nullptr in this location can cause unexpected segfaults while debugging.  For example, adding a print statement
This commit updates the `relax::Function::CreateEmpty` function to contain a placeholder body, consistent with the `ret_struct_info` argument provided.
> [QoL][Relax] Return well-formed IR from relax::Function::CreateEmpty

- src/relax/ir/expr.cc
- tests/python/relax/test_expr.py
Prior to this commit, the `relax::Tuple` constructor left the `struct_info_` field undefined.  This is inconsistent with other Relax leaf nodes, such as `relax::PrimValue`, `relax::Constant`, and `relax::ExternFunc`, which initialize their struct info on construction.
This commit updates the `relax::Tuple` constructor to define `struct_info_` as `TupleStructInfo`, if all fields have a known struct info.  If any field does not have a known struct info, the current behavior is kept, where `struct_info_` is constructed as `NullOpt`, and is later populated by the `relax::BlockBuilder`.
> [QoL][Relax] Infer StructInfo for relax::Tuple on construction

- python/tvm/script/highlight.py
The `ruff format` tool is significantly faster than the `black` formatter.  For some particularly long TVMScript modules, using it can reduce the time required to show a formatted module from ~5 minutes to ~1 minute.  This commit updates the `.show()` function to apply the optionally formatting using `ruff format` if available, falling back to `black` otherwise.
> [TVMScript] Optionally use `ruff format` instead of `black`

- python/tvm/dlight/gpu/gemv.py
HW dependent shared memory issue, which may cause nan in output result.
> [Bugfix] rocm shared memory issue on MI250

- src/runtime/cuda/cuda_device_api.cc
- tests/python/runtime/test_runtime_device_api.py
This commit resolves a bug that was introduced in
https://github.com/apache/tvm/pull/16377.  If no CUDA-capable GPUs are present, the call to `cudaGetDeviceCount` will return an error, which will be raised as an exception by the `CUDA_CALL` macro.  However, checking the `kExist` flag is valid even if no GPUs are present.
This commit removes the use of `CUDA_CALL`, and instead returns false in this case.
> [Bugfix] CudaDeviceAPI::GetAttr may check kExist when GPUs absent

- include/tvm/relax/transform.h
- python/tvm/relax/transform/transform.py
- src/relax/transform/fuse_ops.cc
- src/relax/transform/utils.h
This makes it possible to only apply BYOC to some functions
cc @tqchen
> [Relax] Allow specifying entry_funcs for BYOC

- python/tvm/relax/utils.py
- src/relax/op/op_common.h
- src/relax/op/tensor/binary.cc
- src/script/printer/relax/tir.cc
- src/te/operation/create_primfunc.cc
- tests/python/relax/test_op_binary.py
- tests/python/relax/test_op_nn_convolution.py
- tests/python/relax/test_op_search.py
- tests/python/relax/test_transform_legalize_ops_binary.py
Prior to this commit, binary operations were only defined between two tensors.  This commit allows binary operations to apply between a tensor and a `relax::PrimValue`.
When inferring the output `StructInfo`, binary operations with a `PrimValue` produce the same output as using a 0-d tensor.  When legalizing operations containing a `PrimValue`, they are lowered to primitive TIR arguments.
> [Relax] Handle binary operations between Tensor and PrimValue

- python/tvm/contrib/rocm.py
Corrected`lld` search to include `/opt/rocm/llvm/bin` for `rocm` to generate candidates like `['ld.lld-17.0', 'ld.lld-17', 'ld.lld', '/opt/rocm/llvm/bin/ld.lld-17.0', '/opt/rocm/llvm/bin/ld.lld-17', '/opt/rocm/llvm/bin/ld.lld']`
cc @tqchen
> [Upd] Fixed lld search in rocm

- include/tvm/runtime/memory/memory_manager.h
- src/runtime/relax_vm/builtin.cc
- tests/python/relax/test_vm_builtin.py
If the Relax VM attempts to allocate more memory than is available on the GPU, it should raise an exception.  Prior to this commit, an out-of-memory exception instead triggered a segfault within `"vm.builtin.alloc_storage"`.
When an allocation succeeds, the sequence of events is:
1. A `StorageObj` instance is constructed.
2. A call is made to `alloc->Alloc`, which returns the allocated buffer.
3. The allocated buffer is assigned to `StorageObj::buffer`.
4. The allocator is assigned to `StorageObj::allocator`.
However, when the GPU has insufficient memory, the sequence instead is:
1. A `StorageObj` instance is constructed.
2. A call is made to `alloc->Alloc`, which raises an out-of-memory exception.
3. In unwinding the stack, the `StorageObj` destructor is called.
4. The `StorageObj` …
> [Bugfix][Relax] Raise exception for OOM allocation

- python/tvm/relax/backend/dispatch_sort_scan.py
- tests/python/relax/test_backend_dispatch_sort_scan.py
The current pass would generate multiple PrimFuncs even if they are structural equal, which is because `bb.update_func` will not check whether the new func is already in the list.
This PR apply dlight at the end of the dispatching instead of after every function.
cc @yongwww @vinx13
> [Relax] Prevent to generate duplicate func in dispatch_sort_scan

- include/tvm/relax/expr.h
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/transform/set_expr_layout.cc
- src/relax/analysis/well_formed.cc
- src/relax/backend/contrib/utils.cc
- src/relax/ir/dataflow_matcher.cc
- src/relax/ir/expr.cc
- src/relax/training/utils.cc
- src/relax/transform/fuse_ops.cc
- src/relax/transform/fuse_tir.cc
- src/relax/transform/gradient.cc
- src/script/printer/relax/binding.cc
- src/script/printer/relax/function.cc
- tests/python/relax/test_expr_functor.py
The Relax IR requires the `FunctionNode::body`, `IfNode::true_branch`, and `IfNode::false_branch` to be instances of `relax::SeqExpr`. If these Relax requirements are violated, correctly-implemented transformations may raise an exception
(e.g. from `Downcast` in `Downcast<SeqExpr>(func->body)->blocks`), or even segfault (e.g. when `.as` returns a nullptr in `func->body.as<SeqExprNode>()->blocks`).  Debugging these failure modes is also difficult, as even the TVMScript printer relies on the body of the function being a `SeqExprNode`.
This commit updates the C++ type of `FunctionNode::body`, `IfNode::true_branch`, and `IfNode::false_branch` to be `relax::SeqExpr` instead of `relax::Expr`.  This does not impact any well-formed Relax IR, and allows this type of ill-formed Relax IR type to be …
> [QoL][Relax] Use SeqExpr in IR types when SeqExpr is required

- src/runtime/container.cc
- web/emcc/wasm_runtime.cc
- web/package-lock.json
- web/src/runtime.ts
There are two changes in this PR.
Prior to this PR, we cannot pass in `string[]` from typescript to a TVM PackedFunc and need to convert it to `TVMArray<TVMString>` (for instance in `getParamsFromCacheByName()`). This may not be the most convenient if the PackedFunc's caller is not internal to tvmjs. Thus, this PR moves the conversion to `setPackedFunc()` instead.
The second change is dealing with exceptionally long TVM arrays. In cases like passing in a token table, we need to pass in a long `string[]` (in Llama-3's case, of size 128000), leading to JS error `RangeError: Maximum call stack size exceeded` since we treat each string element as an argument, shown in `this.ctx.arrayMake(...inputs)`. 
This PR sets an empirical call stack limit of 30000 and chunks the array elements in …
> [Web] Support string[] in setPackedFunc() and exceptionally long arrays

- src/arith/analyzer.cc
- src/arith/scalable_expression.cc
- src/arith/scalable_expression.h
- src/driver/driver_api.cc
- src/tir/transforms/vectorize_loop.cc
- tests/python/tir-transform/test_tir_transform_vectorize.py
Check that we are compiling for an SVE enabled target when the extent of a loop marked for vectorizing is a vscale dependent expression.
The extent of a loop should be either a positive integer or an vscale dependent expression, in the latter case we'd expect the target to have `has_sve` feature.
> [SVE] Check for SVE target in VectorizeLoop

- src/runtime/disco/bcast_session.cc
The actual arguments from the calling site starts with `args[3:]`, this made printed error message starts with `Argument #0`
cc @tqchen
> [Disco] Improve error message for CallPacked

- tests/python/relax/test_codegen_cublas.py
- tests/python/relax/test_codegen_cudnn.py
- tests/python/relax/test_codegen_cutlass.py
- tests/python/relax/test_codegen_tensorrt.py
- tests/python/relax/test_contrib_vllm.py
- tests/python/relax/test_transform_codegen_pass.py
Unfortunately, relax GPU tests are excluded from CI right now. 
The testing script uses flag "-m gpu" to run gpu tests, but actual tests have no such mark.
> Restore "pytest.mark.gpu" for RELAX tests

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/topi/arm_cpu/arm_utils.py
- python/tvm/topi/arm_cpu/conv2d.py
- python/tvm/topi/arm_cpu/conv2d_gemm.py
- python/tvm/topi/nn/conv2d.py
- src/arith/analyzer.cc
- src/arith/const_int_bound.cc
- src/arith/int_set.cc
- src/arith/rewrite_simplify.cc
- src/arith/scalable_expression.cc
- src/arith/scalable_expression.h
- src/relay/backend/utils.cc
- src/tir/transforms/storage_rewrite.cc
- tests/python/arith/test_arith_rewrite_simplify.py
- tests/python/codegen/test_target_codegen_aarch64.py
- tests/python/tir-schedule/test_tir_schedule_split_fuse.py
- tests/python/topi/test_topi_conv2d_nhwc.py
This commit adds an `arm_cpu` conv2d NHWC schedule which generates SVE instructions by extending the hybrid GeMM approach implemented in #16106 to use scalable expressions as splitting factors.
Various vscale-related fixes needed to implement the schedule are also included, such as:
- adding vscale bounds in the `ConstIntBoundAnalyzer` and `IntervalSetEvaluator`
- simplifying `MinNode` and `MaxNode` that have scalable expression operands in `RewriteSimplifier`, which would appear when defining the shape of a buffer padded to be a multiple of vscale and in its respective buffer access indices (e.g. `C_1 = T.Buffer((1024 * (T.vscale() * 16 + 256 - 16 % T.vscale() * 16),), data=C)` instead of `C_1 = T.Buffer((1024 * (T.max(255, T.vscale() * 16 + 255 - 16 % T.vscale() * 16) + 1),), data=C)`) …
> [SVE][TOPI] Add conv2d NHWC hybrid SVE schedule for `arm_cpu`

- include/tvm/script/ir_builder/tir/ir.h
- python/tvm/script/ir_builder/tir/ir.py
- src/script/ir_builder/tir/ir.cc
- tests/python/tir-transform/test_tir_transform_inject_ptx_async_copy.py
- tests/python/tvmscript/test_tvmscript_parser_tir.py
This PR fixes the bug of mismatched dtype in `T.launch_thread` when the dtype is `i64`.
> [TVMScript] Support `T.launch_thread` with i64 dtype

- python/tvm/dlight/gpu/general_reduction.py
- tests/python/dlight/test_gpu_general_reduction.py
This PR fixes the GeneralReduction dlight rule so that it can support scheduling log-sum-exp function.
Prior to this issue, the rule makes a strong assumption on the pattern of the given function, which allows scheduling softmax, but fails to schedule log-sum-exp due to pattern mismatch. This PR enhances the rule and makes it able to match the pattern of log-sum-exp and apply subsequent scheduling.
A regression test is added.
> [Fix][Dlight] Fix GeneralReduction for log-sum-exp

- tests/scripts/setup-adreno-env.sh
- tests/scripts/task_build_adreno_bins.sh
- tests/scripts/task_config_build_adreno.sh
1. Enable CXX environment setting for empty tvm subgraph.
2. Enable clml profiling and tuning in rpc environment
3. Enable Opencl when CLML build.
> [SCRIPT][ADRENO] Fix in build config for adreno

- python/tvm/relax/backend/dispatch_sort_scan.py
- python/tvm/relax/backend_tir/__init__.py
- python/tvm/relax/backend_tir/cumsum.py
- tests/python/relax/test_backend_dispatch_sort_scan.py
New implementation for `cumsum` for `axis=-1`, which is the common case in LLM sampling and MoE inference)
Tested CUDA, Vulkan on RTX 3080, and Metal on Apple M1 Pro. The new implementation is faster or equal vendor-libraries on small size (`<128k`), and nearly 10x faster than topi implementation in all cases
|batch|size  |cuda-new|cuda-thrust|cuda-old|vulkan-new|vulkan-old|metal-new|metal-mlx|metal-old|
|-----|------|--------|-----------|--------|----------|----------|---------|---------|---------|
|1    |16    |6.25    |7.97       |67.37   |9.44      |45.86     |58.94    |177.03   |292.87   |
|1    |32    |6.12    |8.10       |82.38   |8.44      |55.43     |49.31    |174.33   |309.60   |
|1    |64    |6.39    |8.43       |97.46   |8.72      |61.21     |58.55    |165.82   |359.07   |
|1 …
> [Relax][TIR] Introduce new `cumsum` op for gpu

- python/tvm/relay/op/contrib/clml.py
- tests/python/contrib/test_clml/test_ops.py
Added more check condition to make clml path more robust.
1. Depth_to_space - CLML path only supported for mode="DCR" and NCHW layout
2. Default checks -  CLML supports less than 4D tensor dimension and with batch size =1.
> [CLML] Fix in clml pattern check condition

- python/tvm/relax/backend/dispatch_sort_scan.py
This PR increases the thrust workspace size, since in practice we found that the current workspace size can still be insufficient. Thrust sort may require larger workspace when the number of elements being sorted is large (e.g., in Llama3 that is 128k).
> [Thrust] Increase static workspace size

- python/tvm/relay/frontend/tflite.py
- tests/python/frontend/tflite/test_forward.py
This commit adds support for converting a TFLite fp32 GELU operation to Relay.
Also includes some neighbouring cleanup of version checks to silence warnings.
cc @leandron @ekalda
> [TFLite] Add support for GELU conversion

- include/tvm/relax/block_builder.h
- include/tvm/topi/transform.h
- src/relax/ir/block_builder.cc
- src/relax/op/op_common.cc
- src/relax/op/op_common.h
- src/relax/op/tensor/index.cc
- tests/python/relax/test_op_index.py
- tests/python/relax/test_op_take.py
- tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py
Prior to this commit, the `relax.op.take` only allowed tensors as the `indices` argument.  This commit extends `R.take` to also allow the index to be a `relax::PrimValue`.
> [Relax] Allow PrimValue as index in relax.op.take

- .github/actions/setup/action.yml
- .github/workflows/main.yml
- apps/ios_rpc/CMakeLists.txt
- conda/build-environment.yaml
- conda/recipe/conda_build_config.yaml
- conda/recipe/meta.yaml
This helps to mitigate the recent error.
> [CI] Enable Conda setup v3

- src/tir/schedule/primitive/compute_at.cc
- src/tir/schedule/primitive/decompose_padding.cc
- tests/python/tir-schedule/test_tir_schedule_compute_at.py
Add a simple optimization to block form after compute-at when the result loop domain and extra loop predicate could be merged.
eg, 
```python
for i in range(87):
T.where(i < 85): ...
```
Could be generated as
```python
for i in range(85): ...
```
> [tir][Compute-at] Make compute-ated block simple when the predicate could be merged

- tests/python/relay/test_op_level2.py
- tests/scripts/task_config_build_cpu.sh
Changes the config script to build TVM with LLVM17. This enables tests for #16921.
> [CI] Use LLVM17 for tests on `ci_cpu`

- ci/jenkins/docker-images.ini
- tests/micro/zephyr/test_zephyr.py
- tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_fp16.py
- tests/python/contrib/test_hexagon/metaschedule_e2e/test_resnet50_int8.py
- tests/python/contrib/test_hexagon/test_meta_schedule.py
- tests/python/contrib/test_hexagon/topi/slice_op/test_cast_slice.py
- tests/python/relax/test_codegen_cudnn.py
This pull request updates the Docker image tag to 20240428-060115-0b09ed018. This new image includes support for CUDA 12.
> [CI] Update image tag to 20240428-060115-0b09ed018

- include/tvm/runtime/ndarray.h
- python/tvm/runtime/ndarray.py
- src/runtime/ndarray.cc
- tests/python/runtime/test_runtime_nd_array.py
Prior to this commit, the `NDArray::CreateView` method could produce an aliasing view of an existing array with a different shape or datatype, but the view was required to have the same `DLTensor::byte_offset` as the existing array.  This commit updates the `NDArray::CreateView` method with an additional parameter, specifying the offset of the view relative to the existing array.
> [Runtime] Allow offset to be specified in NDArray::CreateView

- python/tvm/dlight/gpu/gemv.py
- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_gemv.py
- tests/python/dlight/test_gpu_matmul.py
Enabled new gemv schedule for opencl target, which effectively improves decode performance of mlc-llm LLM models with q4f16_0 format.
Few LLM models Decode performance on Snapdragon Gen-3 android.
Models         Baseline       Latest improved
Llama-2-7B       10 tok/sec       12.5 tok/sec
Qwen-7b          8.5 tok/sec      11 tok/sec
> Enable gemv schedule for adreno

- python/tvm/topi/arm_cpu/conv2d_gemm.py
- tests/python/topi/test_topi_conv2d_nhwc.py
This patch partly reverts the unification of scalable and non-scalable scheduling of conv2d NHWC for `arm_cpu` targets introduced in #16899.
The non-scalable schedule for float32 splits the N axis (corresponding to number of output channels) by 16 in both the unified and the nonunified schedule versions, and then additionally splits the inner partitions by 4 in only the nonunified version to which this patch is reverting (first added in #16106). The two versions' behaviour would be equivalent if none of the padding on the N axis was removed during lowering, however we allow for that to happen as it proved to increase performance for very small convolutions.
As it stands, there seems to be a regression in cases where the datatype is float32 and the number of output channels is greater than …
> [TOPI] Revert unification of conv2d NHWC hybrid scheduling for `arm_cpu` targets

- include/tvm/node/structural_equal.h
- src/node/structural_equal.cc
Override the StrucutralEqual operator () to ensure easy usage of the function. 
@jverma-quic and @quic-sanirudh can you please take a look.
> Overriding the StructuralEqual() for easy usage

- .github/workflows/main.yml
- src/target/intrin_rule.h
- src/target/source/intrin_rule_cuda.cc
- src/target/source/intrin_rule_metal.cc
- src/target/source/intrin_rule_opencl.cc
- src/tir/ir/data_type_rewriter.cc
- tests/python/codegen/test_target_codegen_gpu_common.py
Support CLZ intrinsic on CUDA/Metal/OpenCL
> [TIR] Enhance CLZ intrinsic support

- python/tvm/contrib/cutlass/gen_tensor_op.py
It seems there is an issue while generating c source of dense operation using cutlass.
Even though the dense operation contains bias parameters, the generated c code doesn't reflect that bias correctly.
Please check the change and leave feedback.
> [Unity][Cutlass] Fix C source generation of dense operation

- python/tvm/relax/backend/contrib/cublas.py
- python/tvm/relax/backend/patterns.py
- src/relax/backend/contrib/cublas/codegen.cc
- src/relax/backend/contrib/utils.h
- src/runtime/contrib/cublas/cublas.cc
- src/runtime/contrib/cublas/cublas_json_runtime.cc
- src/runtime/contrib/cublas/cublas_utils.h
- tests/python/relax/test_codegen_cublas.py
This commit enables offloading of `R.matmul` + `R.dequantize` to cuBLAS codegen. Dequantization scale is passed to runtime function and set to alpha parameter. If there is no dequantization, then alpha == 1.0.
Also, it can be used to fuse output scale to matmul in case of FP8.
cc @vinx13 @csullivan @JosephTheOctonaut @masahi @elvin-n
> [CUBLAS] Enable offloading of R.matmul + R.dequantize

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- src/target/llvm/codegen_llvm.cc
- src/tir/op/builtin.cc
- tests/python/codegen/test_target_codegen_aarch64.py
Adds a `get_active_lane_mask` builtin and lowering to `llvm.get.active.lane.mask` intrinsic. This will be used in subsequent patches for expressing predicated buffer loads/stores in TIR. Further information can be found in the [RFC](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0104-scalable-vectors-in-tir.md#predication).
Co-authored-by: Elen Kalda <elen.kalda@arm.com>
Co-authored-by: Neil Hickey <neil.hickey@arm.com>
> [SVE] Add get_active_lane_mask builtin

- python/tvm/script/parser/core/parser.py
A minor fix for TVMScript Macro parsing, which allow error reporting inside the Macro
> [TVMScript] Fix error reporting inside Macro func

- src/target/llvm/codegen_hexagon.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/llvm_instance.cc
The `startswith`/`endswith` functions in `StringRef` API were [changed](https://reviews.llvm.org/D136030) to `starts_with` and `ends_with` to be compatible with `std::string` and the older APIs were deprecated and removed.
> [LLVM] Stringref API deprecation fixes

- src/target/llvm/codegen_aarch64.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_llvm.h
- tests/python/codegen/test_target_codegen_aarch64.py
This commit adds support for the `vscale_range()` LLVM function attribute to be generated for SVE and SME targets. 
Some LLVM optimisation passes make use of the `vscale_range()` function attribute when scalable vectors are present (e.g. BasicAA llvm/llvm-project/pull/80445), so we include it alongside the "target_cpu" and "target-features" attributes.  
cc @lhutton1
> [SVE] Add codegen support for `vscale_range()` function attribute

- python/tvm/relax/backend/contrib/cublas.py
- python/tvm/relax/backend/patterns.py
- src/relax/backend/contrib/cublas/codegen.cc
- src/runtime/contrib/cublas/cublas.cc
- src/runtime/contrib/cublas/cublas_json_runtime.cc
- src/runtime/contrib/cublas/cublas_utils.h
- tests/python/relax/test_codegen_cublas.py
This commit enables offloading of the next pattern to cuBLAS:
```
mm = R.linear(data, weights)
scale = R.multiply(a_scale, w_scale)
out = R.multiply(mm, scale)
out = R.cast(out, dtype)
```
cc @csullivan @JosephTheOctonaut
> [CUBLAS][FP8] Enable R.matmul + R.multiply offloading

- python/tvm/relax/backend/contrib/cublas.py
- tests/python/relax/test_codegen_cublas.py
For workloads with a mixture of symbolic shape and concrete shape as batch sizes, we cannot directly use `int()` to obtain the batch size. Instead, we can use `arith.Analyzer` to check equality.
For example:
```
permute_dims1: R.Tensor((batch_size, 12, seq_len, 64), dtype="float16") = R.permute_dims(split_0, axes=[0, 2, 1, 3])
permute_dims2: R.Tensor((batch_size, 12, seq_len, 64), dtype="float16") = R.permute_dims(split_1, axes=[0, 2, 1, 3])
permute_dims3: R.Tensor((batch_size, 12, seq_len, 64), dtype="float16") = R.permute_dims(split_2, axes=[0, 2, 1, 3])
permute_dims4: R.Tensor((batch_size, 12, 64, seq_len), dtype="float16") = R.permute_dims(permute_dims2, axes=[0, 1, 3, 2])
matmul1: R.Tensor((batch_size, 12, seq_len, seq_len), dtype="float16") = R.matmul(permute_dims1, permute_dims4, …
```
> [Unity][BYOC] Use arith.Analyzer to check batch equality of matmul in cublas

- src/relax/transform/fuse_ops.cc
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
At first, FuseOpsByPattern for Relax used a strategy to match maximal subgraph. 
But this was changed in a previous PR https://github.com/apache/tvm/pull/15308. 
The intention was to fix a bug: in FuseOpsByPattern, when two matched subgraph are intersected, they are incorrectly merged together. 
The bug was fixed by returning only the first subgraph if multiple subgraph are intersected. 
The solution successfully solved the problem described there, but unfortunately, resulted in a minimal subgraph match strategy, probably unexpected. 
Let me clarify with a compute graph as an example:
```
lv0 = R.matmul(x, y)
lv1 = R.add(lv0, bias)
lv2 = R.clip(lv1, -128, 127)
```
Consider this pattern: `matmul->add | matmul->add->clip`. It should match both `lv0+lv1` and `lv0+lv1+lv2`. The solution in …
> [BugFix][Relax] change FuseOpsByPattern strategy to pattern-match maximal subgraph

- jvm/native/src/main/native/org_apache_tvm_native_c_api.cc
Different JDK may have different signature for AttachCurrentThread. This can cause issues for example between code for android and normal java. This PR uses a helper class to enable compact with both.
> [JVM] Automatic Compatibility of JVM AttachCurrentThread

- src/runtime/relax_vm/paged_kv_cache.cc
Fix the aux data syncing order of paged KV cache, so that `q_rope_position_map` is the first one to be synced and has a 0 byte_offset.
> [KVCache] Fix the aux data syncing order of paged KV cache

- python/tvm/testing/utils.py
- tests/python/testing/test_tvm_testing_features.py
Prior to this commit, the `tvm.testing.parameter` utility defined a fixture with the default `scope="function"`.  However, this prevents use of these parameters as arguments for other fixtures that are themselves cached using pytest.  Since these are parameters, not large values that would be expensive to compute, there is no downside to caching them at the pytest level.
This commit updates the scope of fixtures generated using `tvm.testing.parameter` to use `scope="session"` instead of the default `scope="function"`.
> [UnitTest] Use pytest's scope='session' for tvm.testing.parameter

- python/tvm/runtime/disco/session.py
- src/runtime/disco/session.cc
Prior to this commit, the `SessionObj::Shutdown` method could be called from the C++ API, but could not be called through the Python API.  While it is implicitly called when the `SessionObj` is destructed, Python's garbage collection may result in the destruction occurring later than expected.
This commit exposes `SessionObj::Shutdown` through the Python API as `disco.Session.shutdown`, allowing it to be closed cleanly.
> [Disco] Expose disco.Session.shutdown through the python API

- src/runtime/cuda/cuda_device_api.cc
Prior to this commit, the RAII handler in `NDArray` would always attempt to free a cuda memory allocation on destruction.  However, the call to `cudaFree` may throw an exception.  If this happens during stack unwinding due to a previously-thrown exception, this causes the program to immediately terminate, making it difficult to identify the source of the original error.
This can commonly occur if an async compute kernel performs an illegal memory access.  An exception is thrown from the next cuda API call following the asynchronous error, causing the stack to unwind.  If the stack contains any `NDArray` instances which reference cuda allocations, the destructor of these `NDArray` instances will attempt to free memory, triggering the segfault.
This commit updates the …
> [Cuda] Skip FreeDataSpace when CUDA driver is in inconsistent state

- python/tvm/dlight/base/transform.py
- tests/python/dlight/test_gpu_fallback.py
Prior to this commit, the `dlight` scheduling rules were applied solely based on the global `tvm.target.Target.current()`.  However, a TIR PrimFunc may be annotated with the target, rather than using the global `Target.current()`.  In this case, the `dlight` scheduling may produce a scheduled PrimFunc that is not compatible with its target.  For example, using a thread binding to `"threadIdx.x"` on a CPU target.
This commit updates `dlight` to check for a TIR PrimFunc's annotations when scheduling, matching the behavior of `tvm.build`.
> [DLight] Check for target in function attributes

- include/tvm/relax/analysis.h
- python/tvm/relax/analysis/__init__.py
- python/tvm/relax/analysis/analysis.py
- src/relax/analysis/struct_info_analysis.cc
- src/relax/ir/expr_functor.cc
- src/relax/transform/adjust_matmul_order.cc
- tests/python/relax/test_analysis_struct_info_analysis.py
- tests/python/relax/test_transform_adjust_matmul_order.py
When determining whether to evaluate matrix multiplications as `(A*B)*C` or as `A*(B*C)`, dynamic shapes may occur (e.g. a dynamic LoRA rank).  This commit tests for these cases, and improves the arithmetic bounds used to prove which order of evaluation is preferred.
As part of the implementation, this commit also adds a utility `CollectNonNegativeExpressions`, exposed to the python API as `relax.analysis.collect_non_negative_expresisons`.  This utility collects expressions within a `StructInfo` which must be non-negative, based on the location where they appear.  For example, the size of a tensor along each dimension must be non-negative.  Unlike the existing `defineable_tir_vars_in_struct_info`, this will include the `N-2` expression in `R.Tensor([N-2])`.
> [Unity] Check for transpose and dynamic shape in AdjustMatmulOrder

- src/relax/transform/legalize_ops.cc
- src/tir/transforms/ir_utils.cc
- tests/python/relax/test_transform_legalize_ops.py
Prior to this commit, if an `IRModule` contained two expressions, where the types of the arguments differed only by the `VDevice`, these would be legalized to produce a single PrimFunc.  This PrimFunc would have the a `tvm::attr::kTarget` annotation specific to one of those expressions, and would be incorrect for use in the other location.
This commit updates the `LegalizeOps` transform to handle this case, producing multiple TIR PrimFuncs if required by the `VDevice` annotations.
> [Relax][Transform] Handle identical PrimFunc with distinct VDevice

- python/tvm/runtime/disco/session.py
- src/runtime/disco/builtin.cc
- src/runtime/disco/nccl/nccl.cc
- tests/python/disco/test_ccl.py
The `disco.Session.scatter_from_worker0` function expects a `DRef` which an `NDArray` on worker 0, and `NullOpt` on all other workers. Prior to this commit, there was no method in the `disco.Session` that could be used to make such a `DRef`.  As a result, every use of `scatter_from_worker0` generated an error, stating that non-zero workers should have `NullOpt` as their `send` argument.
This commit adds a `worker0_only: bool` argument to `disco.Session.empty`.  This can be used to generate an allocation that only exists on worker zero, suitable for use in `scatter_from_worker0`.
> [Disco] Allow allocation that only exists on worker0

- include/tvm/runtime/disco/session.h
- python/tvm/runtime/disco/session.py
- src/runtime/disco/process_session.cc
- src/runtime/disco/session.cc
- src/runtime/disco/threaded_session.cc
- tests/python/disco/test_session.py
Prior to this commit, while the `num_workers` argument was provided to the `disco.Session` object, it could not be determined from an existing `disco.Session` object.  As a result, functions that interacted with a multi-GPU setup frequently required separate `num_workers` and `disco_session` argument, which could erroneously be out-of-sync (e.g. passing the incorrect `num_workers`, or omitting the `disco_session` argument when `num_workers>1`).
To remove this class of errors, this commit adds a `disco.Session.num_workers` property.  The separate `num_workers` argument is no longer necessary, as it can be determined from the `disco.Session` instance.
> [Disco] Implement `num_workers` property for `disco.Session`

- src/support/pipe.h
Prior to this commit, using `disco.Session` methods to transfer `NDArray` instances to workers could raise an exception if the `NDArray` is larger than the buffer allocated by the OS for the controller/worker pipe.  In these case, the first call to the `Read` method of `tvm::support::Pipe` would successfully return, but only with the initial bytes of the `NDArray`.  Receiving the full `NDArray` requires repeatedly calling the POSIX `read` function.
This commit updates the `Read` and `Write` methods of `tvm::support::Pipe` to repeatedly call the underlying read/write methods, until the full `NDArray` has been transferred.
This commit does not add any unit tests, as the existing unit test `tests/python/disco/test_ccl.py::test_attention[nccl-ProcessSession]` requires this change to pass.
> [Bugfix][Disco] Handle NDArray larger than OS buffer for pipe

- python/tvm/relay/expr_functor.py
[fixed to make TupleGetItem inherits the previous span](https://github.com/apache/tvm/commit/0d14b3cb16c9e0a0087d2c2dc1b82cb6023d93a2)
> [Relay] fixed to make TupleGetItem inherits the previous span

- gallery/how_to/deploy_models/deploy_prequantized.py
- include/tvm/relax/dataflow_pattern.h
- src/runtime/contrib/vllm/attention_kernels.cu
- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
> chore: remove repetitive words

- src/support/pipe.h
This resolves a conflict between two recent changes.  In https://github.com/apache/tvm/pull/16989, reads of size zero are used to identify hangups in `ProcessSession`.  In https://github.com/apache/tvm/pull/16992, reads of size zero are treated as an error to avoid infinite loops while waiting for data to be ready.
For a long-term resolution, the `dmlc::Stream` interface will need to be updated, so that the `Write` method returns the number of bytes written, just as the `Read` method currently does.  This will allow the calling scope to verify the number of bytes received.
> [Runtime][Disco] Restore checks for hangup of disco pipe

- web/src/runtime.ts
- web/src/webgpu.ts
Prior to this PR, WebGPU errors such as OOM are only logged as a warning without affecting the program. This PR handles WebGPU error using `pushErrorScope()` and `popErrorScope()` following https://github.com/gpuweb/gpuweb/blob/main/design/ErrorHandling.md. 
We replace `createBuffer()` with `tryCreateBuffer()`, in which we catch all three types of errors. For now, we treat any error occurred in `createBuffer()` fatal and hence do `device.destroy()`. When a device is initiated, we use `device.lost.then()` to listen to the event of `device.destroy()`, upon which we log the error and call `Instance.dispose()`, prompting the user to re-initialize.
See https://github.com/mlc-ai/web-llm/issues/356 for motivation.
Tested end-to-end with WebLLM.
> [WebGPU] Handle device OOM in createBuffer

- src/target/source/source_module.cc
The `.rodata*` section of any program should not be writable.
The missing `const` specifier in `static struct global_const_workspace {...}` leads to the following `readelf -e` output (shortened):
```
Section Headers:
[Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
[ 0]                   NULL            00000000 000000 000000 00      0   0  0
[ 1] .text             PROGBITS        00000000 001000 009fbe 00  AX  0   0 16
[ 2] .rodata           PROGBITS        00009fc0 00afc0 000e50 00  WA  0   0 16
[ 3] .srodata          PROGBITS        0000ae10 00be10 000068 08  AM  0   0  8
...
```
After this fix, the output looks as follows (`AW -> A`):
```
Section Headers:
[Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
[ 0] …
```
> [USMP] add missing const specifier for global_const_workspace

- include/tvm/relax/attrs/sampling.h
- python/tvm/relax/backend/__init__.py
- python/tvm/relax/backend/dispatch_sampling.py
- python/tvm/relax/backend/dispatch_sort_scan.py
- python/tvm/relax/backend/utils.py
- python/tvm/relax/backend_tir/__init__.py
- python/tvm/relax/backend_tir/cumsum.py
- python/tvm/relax/backend_tir/sampling.py
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/op/__init__.py
- python/tvm/relax/op/sampling.py
- python/tvm/relax/pipeline.py
- python/tvm/script/ir_builder/relax/ir.py
- python/tvm/script/parser/tir/parser.py
- python/tvm/target/detect_target.py
- src/relax/op/tensor/index.cc
- src/relax/op/tensor/sampling.cc
- src/relax/op/tensor/sampling.h
- tests/python/relax/test_backend_dispatch_sampling.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_op_sampling.py
- tests/python/tvmscript/test_tvmscript_parser_tir.py
This PR aims to support backend dispatching for `multinomial_from_uniform`, which includes:
-  Relax Op `multinomial_from_uniform`
- TIR gpu kernel for `multinomial_from_uniform`
- dispatching pass
- TVMScript parser support for pure-python If branch
cc @tqchen
> Support multinomial_from_uniform dispatch

- tests/python/relax/test_vm_build.py
This commit adds a unit test to verify that a single `IRModule` can contain functions that will be used on multiple distinct targets.  Previously, this test case caused errors when running the `LegalizeOps` and `ApplyDefaultSchedule` transforms.
>  [Relax][UnitTest] Validate IRModule with multiple targets

- python/tvm/dlight/gpu/low_batch_gemv.py
- tests/python/dlight/test_gpu_low_batch_gemv.py
This PR improves the performance of low_batch_gemv on Metal by changing schedule config. The performance improvement is around 2x when bucket larger than 2.
> [DLight] Perf improvement for low_batch_gemv on Metal

- web/src/webgpu.ts
This PR updates the error message returned if the client doesn't have valid WebGPU adapter to make it more readible and user-friendly.
> [WebGPU] Update error messages to be more user-friendly

- 3rdparty/picojson/picojson.h
- 3rdparty/picojson/test_picojson.cpp
This PR changes the serialization logic of objects to follow the insertion order of elements to keep the output consistent across different platforms.
> [picojson] Let objects be ordered when serializing

- web/src/runtime.ts
Change web runtime's `NDarray.view` header to include an optional `dtype`, and pass in `relative_by_offset=0` as per https://github.com/apache/tvm/pull/16938.
Tested end-to-end in WebLLM.
> [Web] Add dtype and offset for CreateView in runtime

- src/target/source/codegen_c.cc
- src/tir/transforms/storage_rewrite.cc
- tests/python/tir-transform/test_tir_transform_pointer_value_type_rewrite.py
This PR fixes the shuffle rewrite pass to handle the case where the vector lanes are larger than the data type of the input vector.
> [TIR] Fix Shuffle rewrite

- python/tvm/contrib/tvmjs.py
- tests/python/relax/test_runtime_builtin.py
This allows existing files to be updated.
cc @tqchen
> [Contrib] Implement NDArray cache update

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/testing/utils.py
- python/tvm/topi/arm_cpu/arm_utils.py
- python/tvm/topi/arm_cpu/conv2d.py
- python/tvm/topi/arm_cpu/conv2d_gemm.py
- python/tvm/topi/nn/conv2d.py
- src/arith/scalable_expression.cc
- tests/python/arith/test_arith_simplify.py
- tests/python/codegen/test_target_codegen_aarch64.py
- tests/python/relay/strategy/arm_cpu/test_conv2d.py
- tests/python/relay/strategy/test_select_implementation.py
- tests/python/topi/test_topi_conv2d_nhwc.py
This commit adds a scalable `arm_cpu` conv2d NHWC schedule for fp32 which generates SME instructions by using the tensor intrinsics introduced in #16921.
Alongside the SME schedule, the logic of the TE schedule `schedule_conv2d_gemm_native()` for both non-scalable and scalable vector implementations has also been translated into the new TIR schedule. This means that the TE compute definition `compute_conv2d_NHWC_hybrid()` is now compatible with both the original TE schedules (e.g. `schedule_conv2d_NHWC_hybrid()`) and the newly introduced TIR schedule `schedule_conv2d_NHWC_hybrid_TIR()`. The corresponding TOPI test has been extended to reflect that.
cc @ekalda @lhutton1
> [SME][TOPI] Add conv2d NHWC SME fp32 schedule

- web/src/memory.ts
- web/src/support.ts
This PR fixes passing Javascript string with special characters to C for web runtime.
Take the upside-down exclamation mark `¡` as an example. This should encode to `\xC2\xA1` according to https://mothereff.in/utf-8#%C2%A1 and other sources:
```
OldStringToUint8Array("¡") --> [161, 0]
NewStringToUint8Array("¡") --> [194, 161, 0]
```
> [Web] Fix string to uint8 array for special characters

- src/relax/ir/expr_functor.cc
- tests/python/relax/test_bind_symbolic_vars.py
Prior to this commit, variable replacement by `BindSymbolicVars` would fail to replace variables that occur within a `relax::MatchCast` node. This pattern is rare, because the `bind_symbolic_vars` method can only replace variables that are exposed as part of the function signature, and most uses of `relax::MatchCast` act as a definition for symbolic variables that are not exposed through the function signature.  This pattern is well-formed, though, since the `relax::MatchCast` node can also act as a user of previously-defined symbolic variables.
The root cause for this bug was in the `ExprMutator` visitor for `relax::MatchCast`, which did not visit the struct info field.  As a result, the virtual `ExprMutator::VisitPrimExpr` function was not called for expressions that occur within the …
> [Relax][Bugfix] Bind symbolic variables in R.match_cast

- src/relax/transform/compute_prim_value.cc
- tests/python/relax/test_transform_compute_prim_value.py
The `ComputePrimValue` transform is used to compute the value of symbolic expressions that may appear within a Relax function.  For example, to compute a boolean condition used for a `relax::If` node. These functions are used for small host-side computations, prior to launching a device kernel.
This commit updates `ComputePrimValue` to annotate the generated `PrimFunc` with `tir::attr::kIsHostFunc`.  This annotation is required for correct behavior in `tvm.dlight.ApplyDefaultSchedule`, to avoid erroneous scheduling of this function for the GPU, and for `tir::transform::BindTarget`, to ensure that the function is compiled for execution on the host.
> [Relax][Bugfix] Annotate ComputePrimValue output as host function

- src/contrib/msc/core/utils.h
- tests/python/contrib/test_msc/test_translate_relay.py
Fixes a naming mismatch in MSCGraph where tensor_name could formatted as 'string:index:index',and the corresponding node.name is 'string:index'. Splitting tensor_name from the right aligns it correctly.
For example, the TFLite default input name 'serving_default_input:0' becomes 'serving_default_input:0:0' in MSCGraph, while node.name remains 'serving_default_input:0'.
> [BugFix][MSC] split name_string with index by colon from the right

- python/tvm/topi/arm_cpu/conv2d.py
Fixes a merge conflict between #16981 and #17003.
Closes https://github.com/apache/tvm/pull/17038
cc @ekalda @Anndrey24
> [TOPI] Fix SME conv2d schedule import and intrin argument

- src/tir/transforms/vectorize_loop.cc
- tests/python/tir-transform/test_tir_transform_vectorize.py
This PR fixes a bug in vectorize loop introduced related to https://github.com/apache/tvm/pull/16966
The visit to condition can write need scalarize to true then the followup visit to then case can trigger an ICHECK.
The visit to let value can also write need scalarize flag in which case we need to immediately scalarize.
> [TIR] Fix Bug in VectorizeLoop 

- src/runtime/ndarray.cc
- src/runtime/rocm/rocm_device_api.cc
This PR enables the ROCMHost memory support in ROCm device API.
> [Runtime][ROCm] Enable ROCm host memory support

- src/support/ordered_set.h
Prior to this commit, the `support::OrderedSet<T>` utility used the default copy constructor and copy assignment, which would copy both the `OrderedSet::elements_` and `OrderedSet::elem_to_iter_` members. While this is the correct behavior for `elements_`, the copy of `elem_to_iter_` would contain references to the original's `element_`, rather than to its own.
While `elem_to_iter_` is used in both `OrderedSet::push_back` and `OrderedSet::erase`, the implementation of `OrderedSet::push_back` only depends on the keys used in `elem_to_iter_`, and does not depend on the values stored.  As a result, this bug could go undetected for append-only usage, which is the most frequent use of `OrderedSet`.
This commit updates `support::OrderedSet` to have an explicit copy constructor and copy …
> [Bugfix][Support] Fix copy constructor for support::OrderedSet

- python/tvm/runtime/disco/session.py
- tests/python/disco/test_ccl.py
Prior to this commit, use of the `disco.Session` API to broadcast or scatter an array required several steps from the caller.
1. Allocate memory on worker0
2. Transfer data from the controller to worker0
3. Allocate memory on each worker
4. Broadcast/scatter data from worker0 to all workers
While exposing these steps is necessary for performance, especially when used repeatedly, it can be tedious/error-prone to use for initialization that is only performed once.
This commit adds utility methods `Session.broadcast` and `Session.scatter`, which are implemented in terms of the existing lower-level methods `Session.broadcast_from_worker0` and `Session.scatter_from_worker0`.  These methods perform the transfer from the controller to worker0, and from worker0 to all other workers.
> [Disco][QoL] Implement broadcast/scatter methods for Session

- src/runtime/disco/process_session.cc
- src/runtime/disco/threaded_session.cc
- src/runtime/file_utils.h
- src/runtime/rpc/rpc_endpoint.cc
- src/runtime/rpc/rpc_socket_impl.cc
- src/support/base64.h
- src/support/pipe.h
This commit updates TVM implementations of `dmlc::Stream`.  With https://github.com/dmlc/dmlc-core/pull/686, this API now requires the `Write` method to return the number of bytes written.  This change allows partial writes to be correctly handled.
> [Runtime] Compatibility with dmlc::Stream API changes

- src/runtime/relax_vm/kv_state.cc
- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR fixes a bug in the PagedKVCache which may happen when the sequence removal order is not consistent with the reverse order of sequence add/fork order. With this fix, the PagedKVCache now supports removing sequences in any order without breaking.
This PR also adds an `empty` function to PagedKVCache to check if the KV cache is empty. Right now this function is only used for test purpose, where we check if everything in the KV cache is freed after removing all sequences.
> [Runtime] Fix PagedKVCache for PopN and enhance tests

- python/tvm/dlight/gpu/gemv.py
The current dlight GEMV rule require only one vector buffer, otherwise raise an error. This PR change this behavior to skip the rule.
> [DLight] Skip GEMV rules when more than one vector

- src/runtime/relax_vm/kv_state.cc
- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
- src/runtime/relax_vm/rnn_state.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR introduces the tree attention to PagedKVCache. With this feature, now the KV cache is ready for tree attention cases such as speculative decoding trees.
This PR adds tree attention tests to test the correctness.
The changes in this PR to KVState interface are backward compatible.
> [Runtime] Support PagedKVCache with tree attention

- web/package.json
- web/src/webgpu.ts
Following on https://github.com/gpuweb/gpuweb/pull/4662, this PR uses synchronous `adapter.info` when available instead of the deprecated `requestAdapterInfo()` method.
> Use adapter.info when available instead of requestAdapterInfo

- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR changes the interface of the function
`CommitAcceptedTokenTreeNodeToKVCache` introduced recently for PagedKVCache to a stateless interface. Previously the interace is a stateful one, which makes strong assumption on the caller side. This commit removes the assumption so that the interface becomes less confusing.
> [Runtime] Stateless interface of PagedKVCache leaf node commit

- python/tvm/relax/frontend/onnx/onnx_frontend.py
The Onnx model I'm working on has Cast Op with static ShapeExpr as its input. This PR updates Cast Op converter to handle this sepcial case.
> [Relax][Frontend][Onnx] Cast Op special handling for ShapeExpr input

- src/target/source/codegen_cuda.cc
- src/target/source/literal/cuda_half_t.h
- tests/python/codegen/test_target_codegen_cuda_fp8.py
This allows vectorized fp8 loading.
Co-authored-by: Chris Sullivan <[csullivan@octo.ai](mailto:csullivan@octo.ai)>
cc @yongwww @csullivan @tqchen
> [FP8][Codegen] Add make_fp8 vector constructors

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/topi/arm_cpu/arm_utils.py
- python/tvm/topi/arm_cpu/conv2d.py
- python/tvm/topi/arm_cpu/conv2d_alter_op.py
- python/tvm/topi/arm_cpu/conv2d_gemm.py
- python/tvm/topi/nn/conv2d.py
- tests/python/relay/strategy/arm_cpu/test_conv2d.py
- tests/python/relay/strategy/test_select_implementation.py
- tests/python/topi/test_topi_conv2d_nhwc.py
This commit extends the SME conv2d NHWC schedule to support convolutions with float16 inputs (data and kernel) and a float32 output using the tensor intrinsics added in #16981.
cc @ekalda @lhutton1
> [SME][TOPI] Add conv2d NHWC SME fp16->fp32 schedule

- python/tvm/tir/tensor_intrin/__init__.py
In PR #16921, an import line ([see here](https://github.com/apache/tvm/pull/16921/files#diff-226678f3b8a1a0f9e7c9e36dc6313b9ae53c88759c70f2c39b7e88d408311b20L19)) was inadvertently omitted, resulting in the following error:
`ValueError: TensorIntrin 'dot_4x4_i8i8s32_sdot' is not registered`
This patch restores the lost import.
> [BugFix][MetaSchedule] Fix TensorIntrin ‘dot_4x4_i8i8s32_sdot’ is not registered

- apps/wasm-standalone/wasm-graph/tools/build_graph_lib.py
- gallery/tutorial/autotvm_relay_x86.py
- tests/python/contrib/test_hexagon/test_models.py
- tests/python/contrib/test_hexagon/test_relax_integration.py
- tests/scripts/request_hook/request_hook.py
The ONNX pretrained ResNet model URLs have been updated in the autoTVM documentation. The previous URLs are no longer valid, and this change points to the correct URLs.
Related PR:
https://github.com/onnx/models/pull/644
> [DOC] Update Model Links to Include Commit

- src/relax/op/tensor/unary.cc
Without this fix,
```
TVMError: Check failed: (min->IsInstance<PrimValueNode>()) is false: The argument `min` of relax.clip is expected to be a PrimValue, but gotrelax.expr.Constant
```
With this fix,
```
TVMError: Check failed: (min->IsInstance<PrimValueNode>()) is false: The argument `min` of relax.clip is expected to be a PrimValue, but got relax.expr.Constant
```
cc: @yongwww @tqchen @lhutton1
> [Relax] Add missing white spaces in error messages

- src/target/source/codegen_webgpu.cc
This patch translates an `int8x4` into a `u32` in WGSL shaders as 8-bit integers are not supported in WebGPU right now and the WGSL built-in function `dot4I8Packed()` accepts `u32` as its inputs and each of the `u32` value logically represents a 4-element 8-bit integer vector.
issue: #16627
> [WebGPU] Translate `int8x4` into `u32`

- src/arith/rewrite_simplify.cc
- src/arith/rewrite_simplify.h
- tests/python/arith/test_arith_rewrite_simplify.py
This commit introduces rewrite rules for indices which can arise from splitting axes by scalable factors (e.g. `xo, xi = sch.split(x, factors = [None, 8 * T.vscale()])`):
```
(v_x_o * T.Cast("int64", T.vscale()) * T.int64(8) + v_x_i) // (T.Cast("int64", T.vscale()) * T.int64(8)) == v_x_o
(v_x_o * T.Cast("int64", T.vscale()) * T.int64(8) + v_x_i) % (T.Cast("int64", T.vscale()) * T.int64(8)) == v_x_i
```
The rewrites help prove checks needed by `sch.tensorize()` (e.g. CompareBufferRegion).
cc @ekalda @lhutton1
> [Arith][SVE] Add rewrite rules for indices split by scalable expressions

- tests/python/relay/strategy/arm_cpu/test_conv2d.py
This commit adds some tests for asymmetric height/width and strides. It also refactors the testing parameters to be more self contained so that they don't interfere with other possible tests added in the future.
cc @ekalda @Anndrey24
> [SME][Test] Add additional conv2d tests for asymmetric parameters

- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR fixes the TIR attention kernels in PagedKVCache tests, which had issues when handling uncommon GQA group size (e.g., 6).
> [KVCache][Test] Fix TIR attn kernels for uncommon group size

- python/tvm/topi/arm_cpu/matmul.py
- tests/python/codegen/test_target_codegen_aarch64.py
- tests/python/relay/strategy/arm_cpu/test_dense.py
Prior to this commit, the scheduling assumed the gemm block would be the second to last block in the function ("unpadding" step is the final block). However, when dense is fused with a bias or activation the gemm block is no longer the second to last block. This commit instead searches a single reduction block to use as the gemm block.
cc @ekalda @Anndrey24
> [SME] Extract gemm block correctly when fused with bias

- src/tir/usmp/utils.cc
- tests/python/tir-analysis/test_tir_analysis_calculate_workspace.py
When calculating the size of the workspace for a given prim func, the lanes of the data type was not being considered, meaning sizes calculated for dtypes such as "float32x4" were smaller than what they should be. This commit also considers lanes in the calculation.
> [AOT] Correctly calculate workspace for vector types

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
#17068 
This is only for the fx frontend. But ONNX has [the same HardSwish operator](https://onnx.ai/onnx/operators/onnx__HardSwish.html). I am thinking to add something like relax.nn.hardswish operator and call it from fx/onnx frontend after this PR is merged.
cc @yongwww @tqchen
> [Relax] [PyTorch] Add support for torch.nn.Hardswish

- cmake/modules/CUDA.cmake
As of cmake 3.29.5 [0], if the NVCC version is 11 or higher, cmake will generate a "options-file.rsp" containing the -I flags for include directories, rather than providing them on the command-line.  This setting exists to work around the short command-line length limits on Windows, but is enabled on all platforms.  If set, because include directories are not part of the `compile_commands.json`, the clangd LSP cannot find the include files.
Furthermore, this override cannot be specified in a user's `config.cmake` for TVM, because it must be set after CMake's built-in CUDA support.
This commit updates TVM's `CUDA.cmake` to override the `CMAKE_CUDA_USE_RESPONSE_FILE_FOR_INCLUDES` variable, to avoid this issue.
[0] https://github.com/Kitware/CMake/commit/6377a438
> [CMake] Show NVCC include directories in compile_commands.json

- src/runtime/disco/nccl/nccl.cc
- src/runtime/disco/nccl/nccl_context.h
Prior to this commit, allocations performed by `ncclCommInitRank` had no corresponding call to `ncclCommDestroy`.  While `ncclCommDestroy` does occur in the `CCLThreadLocalContext::Clear` method, there are no calls into this method.  On worker processes, the failure to call `ncclCommDestroy` typically had little effect.  Any destruction would occur shortly before the process closes, and so resources would be reclaimed by the OS when the process terminates.
However, worker0 of a Disco session is a separate thread, rather than a separate process.  While this allows it to easily receive data from the controller thread, resources allocated by worker0 are not reclaimed by the OS until the entire process terminates.  As a result, the `CCLThreadLocalContext` leaked GPU memory, as the …
> [Bugfix][NCCL] Release NCCL thread_local resources in destructor

- src/relax/analysis/tir_op_pattern_kind.cc
- src/relax/transform/rewrite_dataflow_reshape.cc
- tests/python/relax/test_transform_rewrite_dataflow_reshape.py
The Relax transform `RewriteDataflowReshape` identifies TIR functions that are equivalent to `relax.op.reshape`, and replaces them with calls to `relax.op.reshape`.  This is used as a precursor for simplifications that rely on the high-level knowledge that an operator is a reshape, but also require the low-level knowledge of the adjacent TIR PrimFuncs.
Prior to this commit, the `RewriteDataflowReshape` pass would only recognize static shapes, or dynamic shapes that could be inferred from the shapes of tensor arguments.  This commit updates `RewriteDataflowReshape` to recognize cases where an extra symbolic variable has been provided.
> [Relax] Ignore dynamic parameters in RewriteDataflowReshape

- python/tvm/script/parser/relax/parser.py
- src/script/printer/relax/tir.cc
- tests/python/tvmscript/test_tvmscript_roundtrip.py
Prior to this commit, all symbolic variables were printed identically, regardless of whether the underlying variable was a `tir.Var` or `tir.SizeVar`.  As a result, numeric simplifications that rely on a `tir.SizeVar` being non-negative may be skipped after a round-trip through TVMScript.
This commit updates the TVMScript printing and parsing of Relax functions to use `var = T.int64(is_size_var=True)` for `tir.SizeVar`, matching how `tir.SizeVar` is parsed for TIR functions.  As an added benefit, this also allows Relax functions `R.Prim` arguments other than `int64` to be benefit.  This may be useful in the future, such as to specify the fill value for `R.full`.
> [TVMScript][Relax] Preserve tir.SizeVar through TVMScript round-trip

- python/tvm/relay/op/strategy/arm_cpu.py
- python/tvm/tir/tensor_intrin/arm_cpu.py
- python/tvm/topi/arm_cpu/conv2d.py
- python/tvm/topi/arm_cpu/conv2d_gemm.py
- python/tvm/topi/arm_cpu/matmul.py
- tests/python/codegen/test_target_codegen_aarch64.py
- tests/python/topi/test_topi_conv2d_nhwc.py
Prior to this commit, the matmul and conv2d schedules required padding of the inputs to some multiple of vscale and a final "unpadding" stage.
Instead, we can leverage predicated operations to avoid the the requirement for padding. Both the transpose interleave and outer product fp32 intrinsics are updated to use predication. The `get_active_lane_mask` intrinsic is utilized to generate a variably sized mask of active lanes depending on the global position the tensor intrinsic is operating on.
For now this relies on using `offset_of` and `stride` information from the tensor we're predicating an access on. Likely we will want to build on this in the future with a more intuitive API for determining the current tile location.
Support for batched conv2d was removed since this causes numerical …
> [SME] Utilize predication in fp32 matmul and conv2d schedules

- src/tir/transforms/make_packed_api.cc
- tests/python/runtime/test_runtime_rpc.py
- tests/python/tir-transform/test_tir_transform_make_packed_api.py
The `PackedFunc` interface has arguments `int num_args` and `TVMValue* args`, which contain the number of arguments and a pointer to the array of arguments.  Prior to this commit, when implementing the `PackedFunc` interface for TIR `PrimFunc`s, the `MakePackedAPI` pass would always assert that the `args` pointer was not null.  However, the `args` pointer is allowed to be null if `num_args` is zero.  For example, this occurs when calling an RPC function with no arguments.
This commit updates the `MakePackedAPI` transform to only assert that `args` is non-null when `num_args` is greater than zero.
> [TIR][RPC] Allow RPC calls to compiled PrimFuncs with no arguments

- include/tvm/relax/transform.h
- src/relax/transform/fuse_ops.cc
Prior to this commit, `FAttrsGetter` was defined as a function that returned `Map<String, String>`.  However, it is used to define attributes in a `Map<String, ObjectRef>`, and in some cases is used to define attributes whose value is a dictionary (e.g. `msc_attrs_getter` in `python/tvm/contrib/msc/core/transform/pattern.py`).
This commit updates the type signature of `FAttrsGetter` to match its usage, returning a `Map<String, ObjectRef>`.
> [Bugfix] Update FAttrsGetter to return Map<String, ObjectRef>

- src/runtime/crt/common/crt_runtime_api.c
Prior to this commit, `ModuleGetFunction` returned zero if called with an incorrect number of arguments, or with incorrect type codes.  This incorrectly indicated that the module was inspected, and did not contain the requested function.
This commit corrects the implementation of `ModuleGetFunction` to instead call set an error message with `TVMAPISetLastError`, then to return an appropriate error code.
> [Bugfix][CRT] Return error code on error from ModuleGetFunction

- python/tvm/rpc/server.py
Prior to this PR, a local RPC server could crash without any indication in the main process.  While typically this crash would cause an error in the main process due to the lack of a `RPCCode::kReturn` from the server, the delayed error can complicate debugging.
This PR updates the local RPC server to raise an exception if the server process returns with a non-zero exit code.
> [RPC] Raise error if server process terminated

- include/tvm/runtime/container/array.h
Prior to this commit, the `Array::Map` member function could only be applied to nullable object types.  This was due to the internal use of `U()` as the default value for initializing the output `ArrayNode`, where `U` is the return type of the mapping function.  This default constructor is only available for nullable types, and would result in a compile-time failure for non-nullable types.
This commit replaces `U()` with `ObjectRef()` in `Array::Map`, removing this limitation.  Since all items in the output array are overwritten before returning to the calling scope, initializing the output array with `ObjectRef()` does not violate type safety.
> [Utility][Container] Support non-nullable types in Array::Map

- python/tvm/dlight/gpu/gemv.py
- tests/python/codegen/test_target_codegen_cuda_fp8.py
- tests/python/dlight/test_gpu_gemv.py
Change to use 16x32 spatial x reduction thread extents regardless of workload size. This works around a lowering bug which I haven't tracked down yet. 
Currently when the spatial dimension is larger than the reduction dimension, it uses a 4x64 thread layout. This implies two warps in the reduction dimension corresponding to blockDim.x=64. An illegal cuda instruction is encountered in the second warp during the __shfl_down_sync for the remainder portion of the computation (as a result of the rfactor, I believe). AFAICT the mask calculation used for this remainder shfl is incorrect and is causing the error. Specifically it occurs on the first thread of the second warp (two warps along x since blockDim.x = 64)
This is the relevant cuda causing the error:
```
if (((int)threadIdx.x) < 2) { …
```
> [Dlight] Use 16x32 spatial x reduction thread extents in GEMV scheduling

- python/tvm/script/ir_builder/tir/ir.py
Enable ParamType for TIR op, so that we can have better experience when writing TVMScript in Python with tools.
However, ParamType is introduced in Python 3.10, so we only enable it when Python version is 3.10 or above.
> [TVMScript] Better Type Annotation for TIR OP

- src/relay/ir/dataflow_matcher.cc
- tests/python/relay/test_dataflow_pattern.py
This is a patch for PR https://github.com/apache/tvm/pull/15473
That PR tried to solve the issues described in [RFC](https://discuss.tvm.apache.org/t/improving-dataflow-pattern-matching-for-relay/15344), but introduced another issue, probably unintentionally.
The new issue occurs, when there are some leaf args of some OPs along the path during matching 'path' part for dominator pattern. For example, suppose we have a dominator pattern as follows:
```python
conv2d_pat = is_op("nn.conv2d")(wildcard(), wildcard())
eltwise_pat = (wildcard().has_attr({"TOpPattern": K_ELEMWISE}))(None)
broadcast_pat = (wildcard().has_attr({"TOpPattern": K_BROADCAST}))(None)
path_pat = eltwise_pat | broadcast_pat
injective_pat = (wildcard().has_attr({"TOpPattern": K_INJECTIVE}))(wildcard())
pattern = …
```
> [BugFix][Relay] skip leaf args when matching 'path' part for dominator pattern

- include/tvm/tir/builtin.h
- python/tvm/dlight/gpu/matmul.py
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- python/tvm/tir/tensor_intrin/metal.py
- src/runtime/thread_storage_scope.h
- src/target/source/codegen_metal.cc
- src/target/source/codegen_metal.h
- src/tir/op/builtin.cc
- tests/python/dlight/test_gpu_matmul_tensorize.py
This PR adds simdgroup intrinsic and tensorization support in DLight rule for Metal backends.
Perf comparison with Kernel from Llama-3 8B
Before
```
batch_size: 16
Time (ms): 3.42 Total Bytes (MB): 225.00        Memory (GB/s): 64.17    GFLOP/s: 1022.11
batch_size: 32
Time (ms): 4.69 Total Bytes (MB): 226.00        Memory (GB/s): 47.07    GFLOP/s: 1492.82
batch_size: 64
Time (ms): 8.92 Total Bytes (MB): 228.00        Memory (GB/s): 24.96    GFLOP/s: 1569.52
```
After
```
batch_size: 16
Time (ms): 1.69 Total Bytes (MB): 225.00        Memory (GB/s): 130.40   GFLOP/s: 2077.10
batch_size: 32
Time (ms): 2.05 Total Bytes (MB): 226.00        Memory (GB/s): 107.78   GFLOP/s: 3418.39
batch_size: 64
Time (ms): 3.96 Total Bytes (MB): 228.00        Memory (GB/s): 56.17    GFLOP/s: 3531.63
```
> [TIR][DLight] Enable SimdGroup op for Metal

- python/tvm/driver/tvmc/composite_target.py
- python/tvm/driver/tvmc/target.py
- tests/python/driver/tvmc/test_target_options.py
In BYOC,  Marvell Compiler Config node defines the target compiler's  command line options, along with default values. When the user has not given any explicit command line options, these default values can be extracted from the configuration and passed to the TVM's Argument Parser.  Currently the support for extraction of default values from Config options is not there, this change introduces that support. Also this is done conditionally by interpreting the flag status of target compiler.
> [Frontend][ArgParse] Pass default values to target compiler(#13264)

- python/tvm/relax/testing/matmul.py
- src/relax/op/op_common.h
- src/relax/transform/allocate_workspace.cc
- tests/python/relax/test_codegen_cutlass.py
- tests/python/relax/test_transform_allocate_workspace.py
This makes the allocation go through memory planning and make it compatible with cuda graph.
cc @yongwww @masahi
> [Relax] Alloc BYOC workspace with R.builtin.alloc_tensor

- src/relax/backend/vm/exec_builder.cc
- src/runtime/relax_vm/vm.cc
This commit improves validation of the parameter names used for a Relax VM function definition, using the parameter names for runtime error messages.
> [Relax][VM] Improved error messages for mismatched parameter count

- src/relax/transform/lazy_transform_params.cc
- tests/python/relax/test_transform_lazy_transform_params.py
The `relax.transform.LazySetOutput` transformation updates a Relax function to produce output from a `fset_output` callback.  In the initial implementation, the `fset_output` was marked as a pure function, which allowed it to be erroneously removed from a function.
This commit updates the `relax::FuncStructInfo` used to annotate `fset_output`, marking it as an impure function.
> [Bugfix][Relax] Set purity=false for LazySetOutput

- src/meta_schedule/schedule_rule/multi_level_tiling.cc
- src/meta_schedule/schedule_rule/multi_level_tiling.h
- src/meta_schedule/schedule_rule/multi_level_tiling_tensor_core.cc
- tests/python/meta_schedule/test_meta_schedule_schedule_rule_mlt_tc.py
Below script can be used to reproduce the issue. You may need to run it multiple times to reproduce, because sample_perfect_tile may sometime to hide the issue with some decision.
```
in_type="float16"
out_type="float16"
BS = 100
MM = 32
NN = 32
KK = 32
def create_batch_matmul(
b: int = BS, m: int = MM, n: int = NN, k: int = KK, in_dtype: str = in_type, out_dtype: str = out_type
) -> Tuple[te.Tensor, te.Tensor, te.Tensor]:
A = te.placeholder((b, m, k), name="A", dtype=in_dtype)
B = te.placeholder((b, n, k), name="B", dtype=in_dtype)
C = topi.nn.batch_matmul(A, B)
return (A, B, C)
space = meta_schedule.space_generator.PostOrderApply(
sch_rules="cuda-tensorcore",
postprocs="cuda-tensorcore",
)
database = meta_schedule.tune_tir(
mod=te.create_prim_func( create_batch_matmul () ), …
```
> [BugFix][MetaSchedule] MultiLevelTilingTensorCore generates inconsistent thread-binding sketch for batched matmul

- include/tvm/relax/attrs/manipulate.h
- include/tvm/relax/transform.h
- python/tvm/relax/op/manipulate.py
- python/tvm/relax/transform/legalize_ops/manipulate.py
- python/tvm/relax/transform/transform.py
- src/relax/op/tensor/manipulate.cc
- src/relax/op/tensor/manipulate.h
- src/relax/transform/alter_op_impl.cc
- tests/python/relax/test_transform_alter_op_impl.py
- Introduce `input_axis_separator` in `relax.transform_layout` op for 2D input buffer to allow conversion of 2D buffers to 1D buffers. The conversion from 2D->1D is handled while lowering of `transform_layout` operator. 
- This is needed because once the tensor is converted into 2D via `axis_separator`, the `input_axis_separator` helps in identifying the buffers with 2 dimensions especially when the conversion is needed to 1D operation.
- Also introducing support for `input_axis_separator` in `AlterOpImpl` pass.
> [Relax] Support `input_axis_separator` to allow 2D to 1D conversion

- apps/hexagon_launcher/README.md
- cmake/config.cmake
- cmake/modules/HexagonSDK.cmake
- python/tvm/contrib/hexagon/session.py
- python/tvm/target/target.py
- src/runtime/hexagon/README.md
- src/runtime/hexagon/rpc/simulator/session.cc
- tests/python/contrib/test_hexagon/README.md
Add support for executing v75 (Snapdragon 8 gen 3). This PR just adds the support, but to build and execute for v75, the Hexagon SDK used should be 5.4+.
> [Hexagon] Add support for v75

- include/tvm/relax/expr.h
- include/tvm/runtime/object.h
- src/relax/ir/expr.cc
Prior to this commit, the `TVM_DEFINE_OBJECT_REF_COW_METHOD` could be used in any `ObjectRef` subclass to provide a `CopyOnWrite` method. However, the implementation of this method method was invalid if the object's `ContainerType` could itself be subclassed.  In that case, using `obj.CopyOnWrite()` when the object contains a subclass, and when a copy is required, would silently convert `obj` to instead contain a base class.
This commit adds a `static_assert`, to the `TVM_DEFINE_OBJECT_REF_COW_METHOD` macro, preventing the macro from being used in classes that would have incorrect usage.
Compilation with this change found two classes, `relax::Var` and `relax::BindingBlock`, that were susceptible to this error, and the macro has been removed from these classes.  For …
> [Bugfix] Restrict CopyOnWrite to _type_final

- src/tir/schedule/primitive/compute_inline.cc
- tests/python/dlight/test_gpu_matmul.py
- tests/python/dlight/test_gpu_matmul_tensorize.py
- tests/python/meta_schedule/test_meta_schedule_schedule_rule_mlt_tc.py
- tests/python/tir-schedule/test_tir_schedule_compute_inline.py
Hi, we found a kind of corner bad cases for reverse inline primitive. Currently we encode predicate produced by inlining as block compute body, like
```python
with T.block():
if pred:
body()
```
While other primitives (typically `cache_write`) currently may only respect the predicate of `T.where` for region estimation. The newly created blocks take the risk of region out-of-bound write accesses, lead to segfaults even in cpu target computations.
The change proposes to use equavalent `T.where` when possible to make it more consistent with s-tir system, like
```python
with T.block():
T.where(pred_on_loop_vars)
body()
```
> [Compute-inline] Prefer T.where for reverse compute-inlined block with predicate

- python/tvm/relax/transform/legalize_ops/manipulate.py
- python/tvm/tir/schedule/schedule.py
- The decorator is not allowing types like `Array` to be passed to set_axis_separator directive. 
- The FFI has a type checking implemented internally making this redundant.
- The discussion for this change came up in a review comment in https://github.com/apache/tvm/pull/17115
> [TIR][Schedule] Remove `@type_check` for `set_axis_separator`

- python/tvm/relay/frontend/oneflow.py
> [DOC] Fix typo for the "We utilize the intermediate representation of nn.Graph to convert the OneFlow model to Reley."

- python/tvm/relax/backend/contrib/cublas.py
Fix case when `lhs_batches` and `rhs_batches` are symbolic expressions, but not standalone variables.
> [Relax] Fix cublas dispatch for corner cases

- include/tvm/topi/detail/extern.h
The C++ implementation of `make_extern` calls a local function(`DeclExternBuffer`) which is outdated and doesn't do the same thing as the equivalent Python function.
The Python implementation of `decl_buffer` was changed in #6317 and a check was added in `buffer.cc` which fails if you try to use `make_extern` in C++.
This PR fixes this by calling the `tvm::tir::decl_buffer` function in C++ which does the same thing as the Python implementation.
> [Fix][TIR] Fix outdated call to create extern buffer in make_extern

- web/src/webgpu.ts
By default, we request 1GB of `maxStorageBufferBindingSize` and `maxBufferSize` when detecting a WebGPU device. However, low-resource devices such as iOS and Android may not be able to support 1GB.
A previous PR falls back `maxStorageBufferBindingSize` to 128MB, the default values stated in WGSL doc, motivated by Android Chrome. This PR falls back `maxBufferSize` to 256MB, the default value, motivated by iOS Safari.
> [WebGPU] Fall back to 256MB for maxBufferSize if needed

- src/runtime/graph_executor/graph_executor.cc
- src/runtime/graph_executor/graph_executor.h
- tests/python/runtime/test_runtime_module_based_interface.py
This PR is an updated version of #15121
> GraphExecutor: Fix wild pointer assign when input and output are reshape

- pyproject.toml
The `ruff format` tool is an alternative to the `black` formatter, with significantly improved performance.  This commit updates the `pyproject.toml` to include a configuration for `ruff format`, matched to the configuration of `black`.
> [Utils] Define line-length for "ruff format"

- include/tvm/ir/global_var_supply.h
- include/tvm/ir/name_supply.h
- src/auto_scheduler/feature.cc
- src/contrib/hybrid/codegen_hybrid.h
- src/driver/driver_api.cc
- src/ir/global_var_supply.cc
- src/relax/backend/contrib/cutlass/codegen.cc
- src/relax/ir/block_builder.cc
- src/relax/transform/allocate_workspace.cc
- src/relax/transform/normalize.cc
- src/relay/backend/graph_executor_codegen.cc
- src/relay/backend/task_extraction.cc
- src/relay/backend/te_compiler.cc
- src/relay/backend/te_compiler_cache.cc
- src/relay/backend/te_compiler_cache.h
- src/target/source/codegen_c.h
- src/target/source/codegen_source_base.cc
- src/target/source/codegen_source_base.h
- src/te/operation/create_primfunc.cc
- src/tir/ir/index_map.cc
- tests/cpp/build_module_test.cc
- tests/cpp/c_codegen_test.cc
- tests/cpp/name_supply_test.cc
Prior to this commit, a `tvm::NameSupply` needed to be constructed with an explicit `const String& prefix` argument.  Omitting this argument would fall back to the default constructor provided by the `TVM_DEFINE_MUTABLE_OBJECT_REF_METHODS` macro, producing a `NameSupply` holding a nullptr.  This then leads to a segfault when the null `NameSupply` is used.
The vast majority of usages of `NameSupply::NameSupply` (29 out of 31) initialize it with an empty `prefix` string.  The remaining two use cases initialize it with a non-empty `prefix` string.  There are no cases in which a null `NameSupply` is initialized.
This commit updates `NameSupply` to use the `TVM_DEFINE_MUTABLE_NOTNULLABLE_OBJECT_REF_METHODS` macro instead of `TVM_DEFINE_MUTABLE_OBJECT_REF_METHODS`.  This allows the default …
> [QoL][IR] Provide default constructor for NameSupply/GlobalVarSupply

- python/tvm/contrib/pickle_memoize.py
- tests/python/contrib/pickle_memoize_script.py
- tests/python/contrib/test_memoize.py
Prior to this commit, TVM could only be imported if the current directory had write privileges.  This was due to the use of `tvm.contrib.pickle_memoize` to cache the winograd transformation matrices.
This commit makes multiple related fixes, to ensure that (1) TVM can be imported regardless of directory permissions, (2) the working directory is not left in a cluttered state, and (3) cache files are generated in an expected location to be reused later.
* The cache directory is only generated when required, just prior to saving a cache.
* The cache directory defaults to `$HOME/.cache/tvm/pkl_memoize`, rather than `.pkl_memorize_py3` in the working directory.
* The cache directory respects `XDG_CACHE_HOME`, using `$XDG_CACHE_HOME/tvm/pkl_memoize` if set.
> [Bugfix] Allow import of TVM when current directory is read-only

- python/tvm/contrib/hexagon/session.py
This patch modifies the `get_executor_from_factory` for relax to support accepting a string that points to an already exported shared library. This allows us to run models that were already compiled through the RPC executor.
> [Hexagon] Support RPC execution of existing shared lib

- tests/python/meta_schedule/test_meta_schedule_cost_model.py
I've locally tested with the xgboost 1.4.2, 1.7.6 and 2.1.0.
Related issue and pr: #12009 #12141 
> [Meta Schedule][XGBoost] enable custom callback func test with xgboost>=1.6.0

- python/tvm/contrib/tvmjs.py
- tests/python/contrib/test_tvmjs.py
Prior to this commit, the `dtype` string used by `tvmjs.dump_ndarray_cache` was generated as `str(np_array.dtype)`. While this works in most cases, there are a few naming differences between TVM datatypes and numpy datatypes, such as `"float8_e4m3fn"` in Numpy being equivalent to `"e4m3_float8"` in TVM.
This commit updates `dump_ndarray_cache` to check `DataType.NUMPY2STR` for the datatype string, allowing round-trip save/load of float8 arrays.
> [TVMJS] Check DataType.NUMPY2STR when saving array

- python/tvm/contrib/msc/core/utils/info.py
- python/tvm/relay/frontend/pytorch_utils.py
- python/tvm/relay/op/contrib/ethosn.py
- python/tvm/relay/testing/tflite.py
- tests/python/contrib/test_arm_compute_lib/test_network.py
- tests/python/frontend/tensorflow/test_forward.py
- tests/python/frontend/tflite/test_forward.py
> Use `packaging.version.parse` instead of `distutils.version.LooseVersion`

- src/tir/schedule/transform.cc
- tests/python/meta_schedule/test_meta_schedule_schedule_rule_mlt_tc.py
For a `conv2d` workload that requires padding:
Test Script: `test_padded_conv`
Location: `tests/python/meta_schedule/test_meta_schedule_schedule_rule_mlt_tc.py` 
```Python
mod = te.create_prim_func(
te_workload.conv2d_nhwc(
1,
224,
224,
3,
64,
7,
2,
3,
in_dtype="float16",
out_dtype="float32",
)
)
```
This configuration sets up a conv2d workload where the product of reduce axes is 147. Therefore, padding is needed when applying the rule multi_level_tiling_tensorcore.
> [MetaSchedule]Add a testcase for padded conv2d in meta_schedule

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
Fix #17183 
Tensor.permute is already supported but not for torch.permute.
> [Relax][PyTorch] Add support for torch.permute

- python/tvm/_ffi/_ctypes/packed_func.py
Signal handler is only registered for cython, it was missing for ctypes FFI.
cc @tqchen
> [FFI] Add python signal handler for ctypes FFI

- apps/hexagon_api/CMakeLists.txt
- cmake/modules/Hexagon.cmake
This patch fixes the issue mentioned in #17163.
The issue was because some files that are built into the runtime depend on architecture features that are only available starting from v68. Hence, we should not link them into the runtime if the architecture mentioned is v66 or v65.
> [Hexagon] [CMake] Fix v66 build issue

- python/gen_requirements.py
since our codebase depend on it.
https://github.com/search?q=repo%3Aapache%2Ftvm+packaging&type=code
> Add `packaging` to `python/gen_requirements.py`

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
Add torch.einsum support to Relax PyTorch Frontend.
> [Relax][PyTorch] Add support for torch.einsum

- python/tvm/meta_schedule/cost_model/xgb_model.py
rabit is marked as deprecated since XGBoost v1.7 and removed in v2.0.
https://github.com/dmlc/xgboost/blob/release_1.7.0/python-package/xgboost/rabit.py#L16
> [MetaSchedule] Replace `xgboost.rabit` with `xgboost.collective` because it's deprecated

- python/tvm/auto_scheduler/testing/tune_onnx.py
- python/tvm/auto_scheduler/testing/tune_relay.py
- python/tvm/auto_scheduler/testing/tune_te.py
- python/tvm/autotvm/testing/tune_relay.py
- python/tvm/meta_schedule/testing/tune_onnx.py
- python/tvm/meta_schedule/testing/tune_relay.py
- python/tvm/meta_schedule/testing/tune_te.py
- python/tvm/meta_schedule/testing/validate_database.py
- python/tvm/testing/utils.py
#17172 
Just copied `strtobool()` into tvm.testing.util. Alternative option is to use `setuptools/_distutils/util.strtobool` as setuptools is already in our dependency.
https://github.com/pypa/setuptools/blob/08bd31115732ece3cca50bd93f338e1b90dead34/setuptools/_distutils/util.py#L334
> Remove and replace deprecated `distutils.util.strtobool()`

- python/tvm/relay/op/contrib/clml.py
- tests/scripts/setup-adreno-env.sh
- tests/scripts/task_python_adreno.sh
Fixed the few clml byoc regression issue.
> [CLML][CI] Fix for few clml regression issues

- include/tvm/runtime/disco/builtin.h
- python/tvm/relax/frontend/nn/core.py
- src/runtime/disco/builtin.cc
- src/runtime/disco/nccl/nccl.cc
- tests/python/disco/test_ccl.py
This PR introduces the disco CCL primitives for cross-group and p2p communication.
Specifically, we introduce the send/receive primitives for one group to send a buffer to its next group, where every worker in the first group sends the buffer to the corresponding worker in the second group. The p2p communication refer to the send/receive operations to/from a target global worker.
> [Disco] Cross-group and p2p send/receive primitives

- src/arith/rewrite_simplify.cc
- tests/python/arith/test_arith_rewrite_simplify.py
- tests/python/arith/test_arith_simplify.py
Prior to this commit, there was no rule to simplify `x == x` into `True`.  In some cases, despite not having an explicit rewrite rule in `RewriteSimplifier`, the `RewriteSimplifier::CanProve` function would check if `x-x` simplifies to zero, relying on the rewrite rules used for `tir::Sub`.  However, the rule to rewrite `x-x` into zero was only enabled for `int32`, `int64`, and floating-point types, so relying on this behavior was inconsistent.
This commit updates the rewrite rules for both `tir::EQ` and `tir::Sub` to check for simplification of `x-x` or `x==x`, regardless of the datatype.  This change preserves the fast-path for index data-types, in which `int32` and `int64` expressions may be simplified without checking for side effects.  For all other dtypes, the cancellation only …
> [TIR][Analyzer] Simplify `x==x` expressions for all dtypes

- include/tvm/relax/block_builder.h
- include/tvm/relax/expr_functor.h
- include/tvm/script/ir_builder/relax/frame.h
- python/tvm/relax/dpl/__init__.py
- python/tvm/relax/dpl/rewrite.py
- python/tvm/script/ir_builder/relax/ir.py
- python/tvm/script/parser/core/entry.py
- python/tvm/script/parser/core/utils.py
- src/relax/ir/block_builder.cc
- src/relax/ir/dataflow_block_rewriter.cc
- src/relax/ir/dataflow_expr_rewriter.cc
- src/relax/ir/dataflow_matcher.cc
- src/relax/ir/dataflow_matcher.h
- src/relax/ir/dataflow_rewriter.h
- src/relax/ir/expr.cc
- src/relax/ir/expr_functor.cc
- src/relax/transform/canonicalize_bindings.cc
- src/relax/transform/utils.h
- src/relax/utils.cc
- src/script/ir_builder/relax/frame.cc
- src/script/ir_builder/relax/ir.cc
- tests/python/relax/test_dataflow_rewriter.py
- tests/python/relax/test_transform_canonicalize_bindings.py
- tests/python/relax/test_transform_legalize_ops_manipulate.py
- tests/python/relax/test_tvmscript_parser.py
Prior to this commit, the pattern to be matched and the rewrite to be performed were provided as separate arguments to `rewrite_call`.  This commit introduces a new class `ExprRewriter`, which contains both parts.  This abstraction makes it easier to combine multiple independent rewrite rules, then apply them all in a IRModule pass.
This implementation also allows pattern rewrite rule to be written using TVMScript, by representing both the pattern to be matched, and the replacement to be applied as functions.  For example:
```python
@R.rewriter
class Rewriter:
@R.function
def pattern(
A: R.Tensor([16], "float32"),
B: R.Tensor([16], "float32"),
):
C = R.add(A, B)
return C
@R.function
def replacement(
A: R.Tensor([16], "float32"),
B: R.Tensor([16], "float32"),
):
C = R.call_pure_packed( …
```
>  [Relax] Implement Rewriter class for pattern-rewrite

- include/tvm/tir/transform.h
- python/tvm/tir/transform/transform.py
- src/tir/transforms/using_assume_to_reduce_branches.cc
- tests/python/relax/test_eliminate_pad_branch_using_buffer_assumption.py
This C++ pass iterates through the primfunc and finds if there is an if_then_else branch related to layout specific padding where we can leverage from assume statement, remove the extra branch and over-compute.
This pass works if the branch has the buffer present in its then_clause or else_clause for which buffer assumption exists. If there are intermediate buffers, then we need to inline the code to use the pass. This pass first parses the assume statement and then uses the information to simplify the expression in the then_clause and else_clause in then_condition_context and else_condition_context. It then decides to eliminate the branch if then_clause and else_clause evaluates to same value in then_condition_context (since then_clause will be true in this context and if else_clause is …
> Pass to eliminate redundant branch and overcompute

- CMakeLists.txt
- include/tvm/runtime/disco/disco_worker.h
- include/tvm/runtime/disco/session.h
- python/tvm/exec/disco_remote_socket_session.py
- python/tvm/runtime/disco/session.py
- src/runtime/disco/bcast_session.h
- src/runtime/disco/disco_worker.cc
- src/runtime/disco/distributed/socket_session.cc
- src/runtime/disco/message_queue.h
- src/runtime/disco/nccl/nccl.cc
- src/runtime/disco/process_session.cc
- src/runtime/disco/socket_session.cc
- src/runtime/disco/threaded_session.cc
- src/support/socket.h
- tests/python/disco/test_session.py
Implements SocketSession that connects multiple local worker processes/threads over multiple distributed nodes via TCP socket.
cc @tqchen @cyx-6
> [Disco] Implement SocketSession

- src/target/llvm/codegen_llvm.cc
`getHostCPUFeatures` returns the features array instead of a bool now.
> [LLVM] Fix for getHostCPUFeatures API change

- src/runtime/hexagon/profiler/lwp_handler.S
This PR solves a known issue with Lightweight Profiling (LWP) on Hexagon that we have fixed in our downstream repo and that I'd like to upstream for the community. The issue appeared with the operator maxpool. When using LWP it gave incorrect results (i.e. with the accuracy terribly bad).
The problem was that the LWP handler was forgetting to save p0 (used by the handler). This predicate register needs to be saved too, just like r0-r5, as it had been decided that it was the responsibility of the handler to save everything (even these theoretically caller-saved registers). Said differently, since it had been decided that calling the LWP handler would not follow the normal ABI, and that the LWP handler would save everything it touches (even normally caller-saved registers like r0-r15 and …
> [Hexagon] Fix LWP assembly handler (predicate register)

- src/relax/transform/fuse_ops.cc
- tests/python/relax/test_transform_fuse_ops.py
The order of bindings in the fusion result is determined by the first binding in each partition group. When the packed param tuple is used, the function usually begins with a numbers of `TupleGetItem` to unpack the param tuple. Previously `TupleGetItem` is treated as `kInjective`, this causes any operation that relies purely on these params to be moved to the beginning of the function and increases the memory usage of the intermediate results.
cc @tqchen
> [Relax] Disable fusion for fetching from the packed params in FuseOps

- web/src/artifact_cache.ts
- web/src/runtime.ts
This PR changes the interface of function `fetchNDArrayCache` of TVM runtime to accept an additional optional parameter of `signal: AbortSignal` to allow clients to use `AbortController` to abort a given fetch.
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
Related issues:
https://github.com/mlc-ai/web-llm/issues/484
https://github.com/mlc-ai/web-llm/issues/499
> [Runtime] Allow aborting fetchNDArray through AbortSignal

- tests/lint/pylintrc
Prior to this commit, the regex used for pylint to identify dummy variables would correctly identify variables that start with an underscore (e.g. `_scale`), unless they have an underscore elsewhere in the name (e.g. `_scale_factor`).  This leads to false positives from pylint for unused variables, as prefixing a variable with an underscore should mark a variable as intentionally unused.
This commit updates the regex in TVM's `pylintrc` to match the current default value for `dummy-variables-rgx`, to allow unused variables to be named with a leading underscore, even if they also contain another underscore.
> [CI] Update dummy-variable regex for pylint

- python/tvm/relax/transform/ipc_allreduce_rewrite.py
- tests/python/relax/test_transform_ipc_allreduce_rewrite.py
The `relax.transform.IPCAllReduceRewrite` pass rewrites calls to `"runtime.disco.allreduce"` to instead call an optimized `"runtime.disco.cuda_ipc.custom_allreduce"` version.  When the legalization of `R.ccl.allreduce` was updated in https://github.com/apache/tvm/pull/17180 to provide an `in_group` argument, the `IPCAllReduceRewrite` pass was not updated.
This commit updates the `IPCAllReduceRewrite` to be handle the additional `in_group` argument.
> [Transform][Relax] Handle `is_group` argument in IPC AllReduce

- ci/scripts/jenkins/determine_docker_images.py
Prior to this commit, the `image_exists` utility in `determine_docker_images.py` logged the full response for success, and the full HTTP error if an exception is caught.  However, this is the expected behavior when loading a docker image from `tlcpackstaging`, such as the current images tagged with `20240428-060115-0b09ed018`. Logging this fallback as an error makes it difficult to find the first actual error that occurred in CI.
This commit updates these logging statments `logging.info` and `logging.exception` to instead use `logging.debug`.
> [CI] Reduce logging level when checking if docker image exists

- src/relax/ir/dataflow_block_rewriter.cc
- tests/python/relax/test_dataflow_pattern.py
Prior to this commit, the `tvm.relax.dpl.rewrite_bindings` utility would segfault if its input contained a `DataflowBlock` whose first binding was a `MatchCast`.
The root cause is use of an unintialized `const VarNode* cur_user_;` when collecting the variable usage.  This variable is only initialized for `VarBinding` nodes, and may be used uninitialized if a `MatchCast` node is encountered before the first `VarBinding`.  This uninitialized value is later dereferenced during while pattern-matching, causing a segfault.
This commit provides a default value of `nullptr` for `MatcherUseDefAnalysis::cur_user_`, preventing the segfault.
> [Relax] Fix segfault in rewrite_bindings for MatchCast node

- web/src/artifact_cache.ts
This is a follow-up for a previous change https://github.com/apache/tvm/pull/17208.
This Pull Request updates function `fetchWithCache()` in TVM runtime class to accept an optional parameter `signal: AbortSignal`, so that users could use `AbortController` to abort the fetch process if needed.
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
Related issues:
https://github.com/mlc-ai/web-llm/issues/484
https://github.com/mlc-ai/web-llm/issues/499
> [Runtime] Allow aborting fetchWithCache through AbortSignal

- python/tvm/relax/transform/__init__.py
- python/tvm/relax/transform/fuse_transpose_matmul.py
- tests/python/relax/test_transform_fuse_transpose_matmul.py
Introduce a new pass to fuse transpose and matmul, which specially for `Linear` ops in PyTorch and NNModule. Note that this pass is migrated from MLC-LLM.
> [Relax] FuseTransposeMatmul Pass

- web/src/artifact_cache.ts
This is a patch for a missing change in https://github.com/apache/tvm/pull/17227, where we updated the function parameters of the `fetchWithCache` function implementations but not the interface.
This tiny patch updated the function signature in the interface as well to make it consistent with the implementation and also to expose it to clients.
> [Runtime Patch] Add AbortSignal to fetchWithCache in ArtifactCacheTemplate interface

- src/relax/transform/fuse_ops.cc
- src/runtime/relax_vm/paged_kv_cache.cc
This PR reorganizes the attention kernel invocation logic in the PagedKVCache, so that in cases of sequence fork, we can effectively merge one ragged-prefill kernel and a decode kernel into a single decode kernel.
> [Runtime] Reorganize PagedKVCache attn kernel invocation

- src/relax/op/op.cc
- tests/python/relax/test_transform.py
Prior to this commit, the error message produced when validating `R.call_tir_inplace` included the shape of the argument that will be mutated in-place.  This correctly caught and raised an error when the argument is a tensor with known shape that is incompatible with the output tensor's shape.  However, this same error message could be also be reached if the input does not have `TensorStructInfo` at all, which would trigger a segfault.
This commit updates the validation to print the argument's `StructInfo` directly, rather than a field from the struct info.  This correctly raises an error for the cases where the argument is not a tensor, or is a tensor with unknown dimensionality, while still printing the explicit shape of the mismatched tensor when avalable.
> [Relax] Remove segfault in R.call_tir_inplace validation

- python/tvm/contrib/hexagon/generate_take_op.py
- python/tvm/contrib/hexagon/hexagon_unary_ops.py
- tests/python/contrib/test_hexagon/test_take.py
**Motivation :** Unary ops calculate the value during runtime which is costly. Since we are handling quantized data hence, it is better to pre compute the value during compile time (for 0 -256 value) and store in a Look Up Table which is accessed during the runtime.
**Implementation :** This pass generates the Look Up Table for each unary op during compile time. It iterates over the original graph and replaces the unary ops call node, (example tanh, sqrt) to a call node that accesses a Look Up Table corresponding to the unary op, and return the value.
**Testing :** The test_take checks for both value correctness and structural correctness of the output generated after the pass.
Reference: https://github.com/apache/tvm/pull/15614
> Replacing unary ops with LookUpTable and Take op to improve performance

- src/contrib/torch/pt_call_tvm/tvm_class.cc
- src/contrib/torch/tvm_module_wrapper/RuntimeModuleWrapperTVM.cc
1. modify the relative path of base64.h
2. modify namespace of base64 and AllocatorType
> [CompileBugfix][contrib] meet 'base64.h: No such file or directory' and '‘tvm::runtime::vm::AllocatorType’ has not been declared' while compiling

- src/relax/transform/to_mixed_precision.cc
- tests/python/relax/test_transform_to_mixed_precision.py
Prior to this commit, while an operator with the `MixedPrecisionPolicyKind::kNever` attribute would not be updated from `float32` to `float16`, it would be erroneously updated from `float16` to `float32`.
This commit updates `ToMixedPrecision` to preserve the datatype of any arguments used in a `kNever` operation, rather than forcing them to a `float32` datatype.
> [Relax][Bugfix] Preserve dtype in ToMixedPrecision for kNever ops

- python/tvm/relay/op/strategy/adreno.py
- python/tvm/topi/adreno/__init__.py
- python/tvm/topi/adreno/group_conv2d_nchw.py
- tests/python/relay/opencl_texture/test_group_conv2d_nchw_texture.py
Implemented the adreno schedule for group conv2d op with texture enablement.
> [TOPI][ADRENO] Add Group Conv2d texture schedule

- .github/actions/setup/action.yml
- conda/build-environment.yaml
- conda/build_win.bat
- conda/recipe/bld.bat
- conda/recipe/install_libtvm.bat
- conda/recipe/install_tvm_python.bat
The build on main failed [link](https://github.com/apache/tvm/actions/runs/10351996240/job/28661217963) with the following error message.  This first occurred in the post-merge build of #17257, but the failure mode (error message below) doesn't appear related to the changes in that commit.
```
conda.exceptions.CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized.
```
> [CI] Resolve CI compilation failures on MacOSX

- python/tvm/relay/frontend/pytorch.py
- tests/python/frontend/pytorch/test_forward.py
Support [torch.tile](https://pytorch.org/docs/stable/generated/torch.tile.html).
cc @vinx13 @yongwww
> [Relay][Pytorch] Add support for `aten::tile`

- include/tvm/node/structural_equal.h
- include/tvm/node/structural_hash.h
- tests/python/tir-base/test_tir_structural_equal_hash.py
Prior to this commit, `NaN` values did not have any special handling in either `StructuralEqual` or `StructuralHash`.
`StructuralEqual` checked whether the LHS and RHS were within some tolerance of each other.  If the LHS and RHS are both `NaN`, this would evaluate to false.  The updated `StructuralEqual` now checks for this case, and returns true if both sides are `NaN`.
`StructuralHash` used the bit-pattern of a floating-point number to compute the hash.  A `NaN` value may have any non-zero value in its mantissa, and so this could produce distinct hashes for ASTs that differ only by the choice of non-zero value.  The updated `StructuralHash` uses the same `std::numeric_limits<double::quiet_NaN()` value for all `NaN` values.
With these changes, `StructuralEqual` and `StructuralHash` can …
> [IR] Handle NaN in StructuralEqual and StructuralHash

- python/tvm/contrib/cc.py
- python/tvm/dlight/gpu/gemv.py
Windows compiler options for targets
> [WINDOWS] Compiler options for non x86 targets

- python/tvm/relax/frontend/nn/op.py
- src/target/source/codegen_c.cc
- tests/python/relax/test_frontend_nn_op.py
Prior to this PR, the PrimExpr `tir::Let` is treated as inlining during codegen, which makes any common subexpression elimination (CSE) efforts using `tir::Let` at TIR level effectless.
This PR updates codegen so that the `tir::Let` will have an explicit var assignment and thus can effectively reflect the CSE efforts.
> [Codegen] Emit `tir::Let` as var assignment explicitly

- src/relax/analysis/udchain.cc
- tests/python/relax/test_transform_dead_code_elimination.py
Prior to this commit, the `relax::analysis::CollectVarUsage` utility treated a local function definition as in-scope after visiting the body of the local function.  As a result, recursive calls from a local function were incorrectly identified as calls to an undefined variable.
This commit updates the `CollectVarUsage` to treat a local function definition as in-scope when inspecting the function body.  This change is similar to the change made for structural equality in https://github.com/apache/tvm/pull/16756.
> [Relax][Analysis] Handle recursive functions in CollectVarUsage

- src/contrib/msc/core/ir/graph_builder.h
- src/relay/backend/vm/compiler.h
- src/relay/parser/parser.cc
- src/relay/parser/token.h
- src/relay/parser/tokenizer.h
- src/runtime/contrib/cblas/gemm_common.h
- src/runtime/contrib/json/json_node.h
- src/runtime/contrib/nnpack/nnpack_utils.h
- src/runtime/contrib/verilator/verilator_runtime.h
Prior to this commit, various header files had `using namespace tvm::runtime`, which imports all names from `tvm::runtime` into the current namespace.
These imports can cause compilation errors depending on the order of `#include` statements.  For example, the `#include <tvm/relay/attrs/transform.h>` file uses the unqualified name `Bool` to refer to `::tvm::Bool`, a subclass of `PrimExpr`.  If a different header file specifies `using namespace tvm::runtime` within the `tvm::relay` namespace, then the unqualified name `Bool` ambiguously refers to either `::tvm::Bool` or `::tvm::runtime::Bool`.
In MSVC, this can cause even further compilation errors.  By default, MSVC does not follow the C++ standard for name resolution in templates.  The standard requires that any names in a template that …
> [Cleanup] Remove `using namespace tvm::runtime` from headers

- docs/get_started/tutorials/ir_module.py
- docs/index.rst
preview at http://8.130.134.126:58000/ir_module/get_started/tutorials/ir_module.html
cc @tqchen
> [Doc] IRModule

- web/src/ctypes.ts
- web/src/runtime.ts
In a recent PR https://github.com/apache/tvm/pull/16183, `TVMArgTypeCode` introduced `TVMArgBool`. This PR is needed for the web runtime when a TVM packed function returns a bool.
> [Web] Add TVMArgBool to ArgTypeCode

- python/tvm/contrib/rocm.py
- src/runtime/rocm/rocm_device_api.cc
> [Rocm] Fix non-standard rocm path

- python/tvm/contrib/msc/core/frontend/translate.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/contrib/test_msc/test_graph_build.py
- tests/python/contrib/test_msc/test_pipeline.py
- tests/python/contrib/test_msc/test_translate_relax.py
- tests/python/contrib/test_msc/test_translate_relay.py
- tests/python/contrib/test_msc/test_translate_tensorrt.py
- tests/python/contrib/test_msc/test_translate_torch.py
- tests/python/relax/test_frontend_from_fx.py
1.support unbind op and add unit tests. unbind op:https://pytorch.org/docs/stable/generated/torch.unbind.html
example:
torch.unbind(torch.tensor([[1, 2, 3], [4, 5, 6],[7, 8, 9]]))
-> (tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))
2.bug fix for expand op, when -1 is given as expand dim(keep the same dim):
https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html
3.support split op with split sections
cc @mshr-h 
Could you please help to review? thanks in advance
> [Relax][Bugfix] Support torch.unbind op and fix bugs for expand && split

- python/tvm/relax/op/base.py
- tests/python/relax/test_tvmscript_parser.py
Prior to this commit, the different `R.call_tir*` variations would wrap the arguments into an in-line `relax.Tuple`, if it is not already a `relax.Tuple`.  While this allows a tensor to be passed into these functions as a single argument (`R.call_tir(func, arg, ...)` instead of `R.call_tir(func, [arg], ...)`), the wrapped Relax variable may already refer to a tuple.
This use of a variable to refer to an argument tuple rather than an in-line argument tuple is not allowed by Relax.  (See discussion on https://github.com/apache/tvm/pull/15916 for details.)  However, by wrapping a variable `args: R.Tuple(R.Tensor, R.Tensor, ...)` into a tuple-of-tuples, the error occurs after the expression has already been generated, and refers to an expression `R.Tuple(R.Tuple(R.Tensor, R.Tensor, ...))` …
> [Relax] Avoid wrapping TupleStructInfo into a Tuple for R.call_tir

- src/te/operation/create_primfunc.cc
- tests/python/te/test_te_create_primfunc.py
Fix missing recursion for reduction's init value in `te.create_prim_func`
Refer to https://discuss.tvm.apache.org/t/te-create-prim-func-vs-tvm-lower/17633
When the initial value depends on spatial iterators, we should also transform the initial value and remapping the vars.
> [TE][CreatePrimFunc] Fix create reduce block with spatial iter dependent init value

- src/relax/utils.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
If a Relax function contains an `R.match_cast` that defines a symbolic shape, and the value provided to the `R.match_cast` has a known static shape, the `relax.transform.CanoncalizeBindings()` pass can in-line the known static shape.  However, while these known TIR values were only collected if the expression used in `R.match_cast` was a `R.Tensor`, `R.Shape`, and `R.Prim` (Relax types which may contain symbolic TIR values), they were not collected if the `R.match_cast` expression was a `R.Tuple`.
For example, while using `R.match_cast` to convert from `R.Tensor([16])` to `R.Tensor([batch_size])` would identify that `batch_size` must be `16`, using `R.match_cast` to convert from `R.Tuple(R.Tensor([16]))` to `R.Tuple(R.Tensor([batch_size]))` would not.
This commit updates the …
> [Relax][Bugfix] Infer TIR values from shapes inside a tuple

- src/relax/transform/canonicalize_bindings.cc
- tests/python/relax/test_transform_canonicalize_bindings.py
Prior to this commit, the `CanonicalizeBindings` pass could identify and simplify a value that had been packed into a tuple, then extracted from it.  (e.g. Simplifying `tup = (x,y); z = tup[0]` into `z = x`.)  However, it could not identify a value that had been expanded from a tuple, and then re-bundled.  (e.g. Simplifying `new_tuple = (tup[0], tup[1])` into `new_tuple = tup`.)
This commit updates `CanonicalizeBindings` to identify and remove unnecessary tuple unpacking/repacking.
> [Relax] Identify tuple unpack/repack in CanonicalizeBindings

- src/tir/transforms/lower_thread_allreduce.cc
- tests/python/tir-transform/test_tir_transform_lower_thread_all_reduce.py
The warp reduction implemented by "shuffle down" primitive takes a mask denoting the active threads within the warp that participate in this shuffle.
Previously we compute the mask, while in practice we find that it results in "CUDA illegal instruction" error on NVIDIA H100 GPU when the mask is set, and the issue is gone if we do not update the mask. Therefore, this PR updates the allreduce lowering to remove the mask update.
Confirmed the correctness on the following devices:
* NVIDIA H100,
* NVIDIA RTX 4090,
* AMD Radeon 7900 XTX,
* Apple M2 Ultra.
> [Fix][TIR] LowerThreadAllreduce warp reduction mask

- docs/how_to/tutorials/e2e_opt_model.py
The `sys.exit` may stop the whole sphinx build process, but not the single script execution.
> [Doc] Fix doc build error in e2e_opt_model.py

- docker/README.md
As per title.
cc @tqchen @Hzfengsy
> [Fix] Remove `tvm.` prefix from image name when `./docker/build.sh`

- src/relax/transform/lift_transform_params.cc
- src/relax/transform/utils.cc
- src/relax/transform/utils.h
- tests/python/relax/test_transform_lift_transform_params.py
The `LiftTransformParams` pass produces additional functions, either named `$FOO_transform_params` when generating one transformation function per inference function, or `transform_params` when generating a single shared transformation function.  Prior to this commit, if the `IRModule` already contained a function with that name, an error would be raised.
After this commit, the `LiftTransformParams` pass will instead check for existing functions, and compose the previous transformation function with the newly-lifted transformation.  This allows `LiftTransformParams` to be used alongside a hand-written parameter transformation.
Closes https://github.com/apache/tvm/issues/17200
> [Relax][Transform] Compose preproc functions in LiftTransformParams 

- src/target/target_kind.cc
- tests/python/target/test_target_target.py
The change propose to ensure the TargetKind instances to be singleton on serialization.
We encounter the issue when we try to establish distributed tools to accelerate the lowering. Though `TargetKind` are generally singleton instances for each registered kind, the workload serialization would also create new `TargetKind` instances (which mostly lay in `kTarget` func attr). 
One simple test workflow is like below:
```python
target = Target("llvm")
mod = tvm.IRModule({"main": func})
target2 = tvm.ir.load_json(tvm.ir.save_json(target))
lib = tvm.build({target2: mod}, target_host=target)
lib["func"]()  # oops, no "func" found in the host module.
```
> [Target] Refine equality check on TargetKind instances

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
Added the following supports
- `torch.nn.functional.conv1d`
- `torch.nn.functional.conv_transpose1d`
- `torch.nn.functional.conv_transpose2d`
- `torch.nn.functional.conv3d`
cc @vinx13 @yongwww @Hzfengsy @tqchen
> [Relax][PyTorch] Add support for `torch.nn.functional.conv*`

- python/tvm/relax/frontend/nn/llm/kv_cache.py
- python/tvm/relax/frontend/nn/llm/tree_attn.py
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This adds support for tree attention with tokens in the kv cache. KVCache is now stateful w.r.t the tree state, multiple decoding rounds can be performed with tree mask and the accepted tokens can be committed at once at the end.
cc @MasterJH5574 @tqchen
> [KVCache] Add tree attention with paged cache support

- src/relax/backend/vm/lower_runtime_builtin.cc
- tests/python/relax/test_vm_builtin_lower.py
Prior to this commit, the `shape` argument to `R.reshape` was required to either be an in-line `relax::ShapeExpr`, or a variable that had been bound to a `relax::ShapeExpr` within the current function.  As a result, shapes that were provided as function arguments or that were produced by another operation (e.g. `R.tensor_to_shape`) would unnecessarily trigger an error.
This commit updates the `VMBuiltinLower` pass to instead check that the argument has `relax::ShapeStructInfo`.
Closes https://github.com/apache/tvm/issues/17217
> [Relax] Allow dynamic shape argument to R.reshape

- python/tvm/relax/frontend/torch/fx_translator.py
With torch==2.4, the `normalized_shape` argument of the `torch.nn.functional.layer_norm` can be `torch.fx.immutable_collections.immutable_list`.
This PR update the layer_norm conveter to cast it to tuple when the `normalized_shape` is `immutable_list`.
```
>       verify_model(model, input_info, binding, expected3)
tests/python/relax/test_frontend_from_fx.py:1323: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/python/relax/test_frontend_from_fx.py:36: in verify_model
mod = from_fx(graph_model, input_info)
python/tvm/relax/frontend/torch/fx_translator.py:1770: in from_fx …
```
> [Relax][PyTorch][Bugfix] Update `layer_norm` converter to support `immutable_list` for `normalized_shape`

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
As per title.
[torchvision.ops.stochastic_depth](https://pytorch.org/vision/main/generated/torchvision.ops.stochastic_depth.html) isn't a pytorch core ops, but some pytorch image classification models such as convnext, inception_v3, and maxvit_t are using it. So I think it's worth supporting it.
> [Relax][PyTorch] Add support for torchvision.ops.stochastic_depth

- rust/tvm/README.md
- rust/tvm/examples/resnet/README.md
- rust/tvm/examples/resnet/build.rs
- rust/tvm/examples/resnet/src/build_resnet.py
- rust/tvm/examples/resnet/src/main.rs
Replace mxnet's resnet18 with torchvision.
Clean up import statements in `rust/tvm/examples/resnet/src/build_resnet.py`.
Related PR and Issue:
- #16546 
- #16572 
- #16547 
cc: @Hzfengsy @tqchen @cgerum
> [Rust] Remove mxnet dependency and re-enable rust example

- python/tvm/relax/frontend/torch/fx_translator.py
> [Relax][PyTorch][Fix] use`_convert_torch_tensor_to_relax()` where possible

- tests/python/contrib/test_hexagon/test_run_unit_tests.py
Prior to this commit, all Hexagon test cases in `tests/cpp-runtime/hexagon` were executed as part of a single unit test in pytest.  This can take a significant portion of the total timeout in CI (~50 minutes out of a 2-hour timeout).  While the hexagon tests are split out onto 8 separate runners, having a single large test can cause timeouts on whichever runner happens to receive it.
This commit exposes each unit test from `tests/cpp-runtime/hexagon` into a separate unit test in pytest, to avoid these timeouts.
> [CI][Hexagon] Forward gtest tests into pytest as separate tests

- src/contrib/msc/core/codegen/base_codegen.h
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/transform/bind_named_params.cc
- src/contrib/msc/core/utils.cc
- src/contrib/msc/core/utils.h
- tests/python/contrib/test_msc/test_graph_build.py
- tests/python/contrib/test_msc/test_translate_relax.py
- tests/python/contrib/test_msc/test_translate_tensorflow.py
- tests/python/contrib/test_msc/test_translate_torch.py
This PR fix the bugs in strided_slice and enables the unit test in MSC.
> [MSC][BugFix] Bugfix for strided_slice op

- include/tvm/ir/analysis.h
- include/tvm/ir/replace_global_var.h
- python/tvm/ir/__init__.py
- python/tvm/ir/_ffi_analysis_api.py
- python/tvm/ir/analysis.py
- src/ir/analysis.cc
- src/ir/replace_global_var.cc
- src/relax/analysis/collect_call_map.cc
- src/relax/transform/attach_global_symbol.cc
- src/relax/transform/dead_code_elimination.cc
- src/relax/transform/replace_global_var.cc
- src/tir/analysis/collect_call_graph.cc
- src/tir/analysis/collect_call_map.cc
- src/tir/transforms/replace_global_var.cc
- tests/python/ir/analysis/test_collect_call_map.py
- tests/python/relax/test_transform_attach_global_symbol.py
- tests/python/relax/test_transform_dead_code_elimination.py
Prior to this commit, the `relax.transform.AttachGlobalSymbol` pass could produce a PrimFunc whose `"global_symbol"` attribute does not match the name of the `GlobalVar`.  As a result, the PackedFunc that is provided by the compiled module (defined by the `"global_symbol"`) does not match the PackedFunc that is required by the Relax VM (defined by the `GlobalVar` name).
This commit updates `AttachGlobalSymbol` to replace the `GlobalVar` of any function whose `"global_symbol"` is updated.
Closes https://github.com/apache/tvm/issues/17176
> [Relax] Update GlobalVar name in AttachGlobalSymbol

- include/tvm/relax/op_attr_types.h
- src/relax/analysis/well_formed.cc
- src/relax/op/op.cc
- src/relax/transform/fuse_tir.cc
- tests/python/relax/distributed/test_distributed_transform_propagate_sharding.py
- tests/python/relax/test_analysis_well_formed.py
- tests/python/relax/test_ast_printer.py
- tests/python/relax/test_dataflow_inplace.py
- tests/python/relax/test_dataflow_pattern.py
- tests/python/relax/test_frontend_dynamo.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_transform.py
- tests/python/relax/test_transform_dead_code_elimination.py
- tests/python/relax/test_transform_fuse_ops.py
- tests/python/relax/test_transform_fuse_ops_by_pattern.py
- tests/python/relax/test_transform_lazy_transform_params.py
- tests/python/relax/test_transform_rewrite_dataflow_reshape.py
- tests/python/relax/test_tvmscript_parser.py
- tests/python/relax/test_vm_build.py
Prior to this commit, the Relax well-formed checker validated arguments provided to Relax functions, but did not validate arguments provided to `R.call_tir`.  As a result, incorrect arguments from Relax to TIR would not be checked until runtime, if at all.
This commit updates the well-formed checker to verify that `R.call_tir` has received the correct arguments, and has the correct output shape specified in the `out_sinfo` parameter.
> [Relax] Require correct input/output shapes `R.call_tir`

- src/relax/backend/vm/codegen_vm.cc
- src/relax/backend/vm/codegen_vm_tir.cc
- src/relax/transform/legalize_ops.cc
- tests/python/relax/test_relax_operators.py
Prior to this commit, an operator's `FCallPacked` attribute, used to specify a 1:1 mapping between a relax operator and a `PackedFunc` that implements it, was only checked in `CodegenVM`.  Any operator with `FCallPacked` would raise an error when compiled using `CodegenVMTIR`.
This commit removes the `FCallPacked` handling from `CodegenVM` altogether, and instead checks for this attribute as part of `LegalizeOps`.  This provides the same functionality across both backends.
> [Relax][Bugfix] FCallPacked not checked in CodegenVMTIR

- apps/android_camera/models/prepare_model.py
- apps/android_camera/models/requirements.txt
As per title.
I'll leave mobilenet_v2 part as it is but we could remove keras dependency since torchvision provides a mobilenet_v2 pretrained model. Not sure which is better.
Related issue and pr:
- #16547 
- #17293 
cc: @Hzfengsy @tqchen
> [Apps] Remove mxnet dependency from /apps/android_camera/models

- src/relax/transform/remove_unused_outputs.cc
- tests/python/relax/test_transform_remove_unused_outputs.py
Prior to this commit, the `relax.transform.RemoveUnusedOutputs` pass only marked a tuple element as used if it occurred in a `TupleGetItem` node.  This ignored use cases where a tuple is used as an aggregate object, such as returning a tuple from a function.  This would collect incorrect results for a Relax function that calls a subroutine, receives a tuple as the return value of the subroutine, then returns that tuple.
This commit updates `RemoveUnusedOutputs` to look for usage of a tuple object, not just for usage in `TupleGetItem`.
Closes https://github.com/apache/tvm/issues/17247
> [Relax][Transform] Handle tuple return in RemoveUnusedOutputs

- src/relax/transform/realize_vdevice.cc
- tests/python/relax/test_transform_realize_vdevice.py
Prior to this commit, the `relax.transform.RealizeVDevice` pass performed in-place update on expressions appearing in its input `IRModule`, overwriting their struct info.  In-place mutation of TVM's IR types is only legal when the scope has sole ownership of the IR object, such as through the `CopyOnWrite` functionality, and is not allowed when the object is shared.  As a result, applying `RealizeVDevice` would cause unexpected updates in unrelated expressions.  Most noticeably, the `IRModule` used as input to `RealizeVDevice` would have its variable erroneously updated.
This commit refactors the `RealizeVDevice` transform to remove all in-place mutation.  The same propagation rules are followed, with known `VDevice` annotations propagated forward from the output of `R.hint_on_device`, …
> [Relax] Refactor RealizeVDevice to remove in-place mutation

- python/tvm/relax/frontend/nn/llm/kv_cache.py
This PR fixes the TIRPagedKVCache construction issue, which is caused by missing the tree-attention with paged KV cache kernel.
> [Fix][Relax] Add the missing tree-attn func arg for KV cache creation

- src/relay/qnn/op/avg_pool2d.cc
- tests/python/relay/test_pass_convert_op_layout.py
**Issue:**
Currently the qnn.avg_pool2d operator does not take the layout specified with the Convert Layout pass.
**Cause:**
The layout of the zero point and scale tensors are specified as "undefined". This causes the Convert Layout pass to bail and maintain the original layout.
**Fix:**
The fix updates the layouts for the scale and zero point tensors to be "channel" layout, similar to how it is done for qnn.conv2d.
**Testing:**
Added unit test
> [relay][qnn]: Fix qnn.avg_pool2d layout inference

- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
This PR fixes ORCJIT link failures for RISC-V targets by properly setting the code model on the executor.
---
Initial bug report is here: https://discuss.tvm.apache.org/t/run-tvm-software-stack-on-risc-v/17683
* RISC-V recommended and required code model was set already here, but was ignored: https://github.com/apache/tvm/blob/e468426bfd43fadb555ef0e561b9047a5d89852e/src/target/llvm/llvm_instance.cc#L276-L280
* RISC-V targets will work only with the newer ORCJIT engine as described in [PR#15964]( https://github.com/apache/tvm/pull/15964)
* This PR adds missing code model settings for the ORCJIT engine.
In case of RISC-V, by not setting the code model to explicit ```Medium``` may give ralocation ```R_RISCV_HI20``` errors.
Cc: @Lunderberg , @ekalda , @lhutton1 , @quic-sanirudh ,  @tqchen …
> [LLVM][RUNTIME] Fix RISC-V CodeModel propagation to ORCJIT runtime executor

- python/tvm/relax/frontend/nn/extern.py
When the source is provided as inline string literal, creating `Path` object causes path too long error.
cc @tqchen
> [Relax] Fix inline source module cause path too long error

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
1. In onnx_frontend.py, for parameters with names starting with "onnx::", a strip processing is performed. In self._params, they should be stored as the new var_name.
```python
if self._keep_params_in_input:
var_name = init_tensor.name.strip("onnx::")
init_var = self._new_var(var_name, shape=array.shape, dtype=array.dtype)
self._nodes[init_tensor.name] = init_var
self._params[init_tensor.name] = (init_var, array)
```
2. In ONNX models, a param can be used many times. As a result, we should not use pop in get_constant.
```python
graph_nodes, params = params
if isinstance(var, relax.Var) and var.name_hint in params:
_, value = params.pop(var.name_hint)
const_value = relax.const(value)
graph_nodes[var.name_hint] = const_value
return const_value
```
> [Relax][Frontend][Onnx] fix params name bug in onnx frontend

- src/relax/analysis/struct_info_analysis.cc
- src/relax/analysis/well_formed.cc
- src/relax/transform/normalize.cc
- tests/python/relax/test_analysis_struct_info_analysis.py
- tests/python/relax/test_analysis_well_formed.py
In Relax, both the variable and the expression in a `VarBinding` may contain `StructInfo` annotations.  Prior to this commit, these `StructInfo` annotations could be inconsistent, assigning an expression to a variable of incompatible type.
This commit updates the Relax well-formed checker to verify that the `StructInfo` of Relax variables accurately describes their contents.
> [Relax] Validate StructInfo of variable bindings

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_conv.py
Currently, the matmul rule for Conv3D is incorrect, due to the incorrect reindexing of the input tensor. This commit fixes the issue by correctly
The `index map` of `transform_layout` should be calculated after the `reindex` process
cc @MasterJH5574
> [DLight] Fix Matmul rule for Conv3D

- include/tvm/ir/replace_global_vars.h
- python/tvm/ir/module.py
- src/ir/replace_global_vars.cc
- src/relax/transform/attach_global_symbol.cc
- src/relax/transform/replace_global_vars.cc
- src/tir/transforms/replace_global_vars.cc
- tests/python/ir/test_transform_replace_global_var.py
This is a follow-up PR to https://github.com/apache/tvm/pull/17202, which added a general utility to replace `GlobalVar` instances across all TVM IR types.  This PR exposes this new utility through the Python API, and explicitly tests its functionality.
> [IR] Expose ReplaceGlobalVars utility in the Python API

- web/src/webgpu.ts
This PR updates webgpu runtime code to remove
deprecated API. unblocks the CI.
> [WEBGPU] Update runtime to remove deprecated API

- src/arith/iter_affine_map.cc
- tests/python/arith/test_arith_iter_affine_map.py
If an iter has been normalized with a lower bound, and then try to normalize with a new lower bound, the iter_min need to be updated only when the new lower bound is smaller than the original one.
> [FIX] fix bug when normalize iter with different lower bounds

- src/relax/transform/fuse_tir.cc
This PR added support for handling SelectNode in the SymbolicMatcher class by modifying the VisitExpr_ function to match the true_value and false_value expressions between the current SelectNode and the other expression. If the other expression is not a SelectNode, the matching condition is updated to ensure the current SelectNode expression is equivalent to the other expression.
> [Relax][Transform] Add SelectNode handling in SymbolicMatcher

- python/tvm/relax/frontend/torch/fx_translator.py
As per title.
It has no functional changes.
Part of https://github.com/apache/tvm/issues/17346
cc @yongwww @vinx13 @tqchen
> [Relax][PyTorch] Cleanup Statistical, Search and DataType op converters

- docs/conf.py
Make the project-specific information more prominent.
This project-specific page already links to the general ASF information at https://apache.org/security/
> [DOCS] Link to project-specific security page

- cmake/modules/contrib/TFLite.cmake
- docker/Dockerfile.ci_adreno
- docker/Dockerfile.ci_cpu
- docker/Dockerfile.ci_gpu
- docker/Dockerfile.ci_hexagon
- docker/Dockerfile.demo_vitis_ai
- docker/install/ubuntu_install_androidsdk.sh
- docker/install/ubuntu_install_java.sh
- tests/scripts/task_config_build_cpu.sh
- tests/scripts/task_config_build_gpu.sh
> [CI] Disable NNPACK build and fix error on Android SDK installaion

- docker/install/ubuntu_install_onnx.sh
PyTorch 2.3 has some changes to the `ExportedProgram` so we would like to update it at least 2.3 or above.
https://github.com/pytorch/pytorch/releases/tag/v2.3.0
> [CI] Upgrade PyTorch to 2.4.1

- python/tvm/script/parser/core/evaluator.py
- python/tvm/script/parser/core/parser.py
- python/tvm/script/parser/relax/parser.py
- python/tvm/script/parser/tir/parser.py
- src/ir/diagnostic.cc
- tests/python/relax/test_tvmscript_parser.py
- tests/python/tvmscript/test_tvmscript_printer_highlight.py
Prior to this commit, after the `DiagnosticContext` prints its error, it overwrites the `DiagnosticRenderer` with a NULL renderer.  If a second call to `DiagnosticContext::Render` occurs, it will segfault. This appears to be intended to prevent double-printing of error messages, but double-printing error messages is much worse than a segfault.
In addition, `DiagnosticContext::Render` should only be called once. There's a common pattern in the parser where it will wrap exceptions in `DiagnosticError`, but re-raise exceptions that are already a `DiagnosticError`.  This requires every such location to include `except DiagnosticError: raise`, and can easily be missed.
This PR makes two changes: First, the `DiagnosticRenderer` is updated to have a no-op callback rather than a NULL callback. …
> [TVMScript] Avoid segfault from invalid TVMScript

- src/script/ir_builder/relax/frame.cc
- src/script/ir_builder/relax/ir.cc
- tests/python/relax/test_tvmscript_parser.py
Prior to this commit, TVMScript required the return value of a Relax to be specified outside of any `with R.dataflow()` blocks.  This resulted in a common pattern, where the return value of a function was first called with `R.output(ret_value)`, to mark `ret_value` as a `tvm::relax::Var` instead of a `tvm::relax::DataflowVar`, followed immediately by a `return ret_value` statement.
This commit updates the TVMScript parser to allow a `return` statement inside a `with R.dataflow()` block.  This is syntactic sugar that is equivalent to calling `R.output`, followed by a `return`.
With this change, the following two TVMScript examples are now equivalent.  (Prior to this change, the `return_inside_dataflow` example would raise an error during parsing.)
```python
@R.function(private=True)
def …
```
> [TVMScript][Relax] Allow return statement in DataflowBlock

- src/relax/analysis/well_formed.cc
- src/relax/op/op.cc
- tests/python/relax/test_analysis_well_formed.py
- tests/python/relax/test_ast_printer.py
- tests/python/relax/test_frontend_from_fx.py
- tests/python/relax/test_transform_decompose_ops.py
- tests/python/relax/test_transform_ipc_allreduce_rewrite.py
- tests/python/relax/test_transform_legalize_ops_ccl.py
- tests/python/relax/test_transform_legalize_ops_create_datatype.py
- tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py
- tests/python/relax/test_transform_legalize_ops_manipulate.py
- tests/python/relax/test_transform_legalize_ops_nn.py
- tests/python/relax/test_transform_legalize_ops_search_statistical.py
- tests/python/relax/test_transform_realize_vdevice.py
- tests/python/relax/test_transform_static_plan_block_memory.py
- tests/python/relax/test_transform_to_mixed_precision.py
- tests/python/relax/test_tvmscript_parser.py
- tests/python/relax/test_vm_cuda_graph.py
- tests/python/relax/test_vm_multi_device.py
Prior to this commit, the Relax well-formed checker verified that each expression had a non-null `StructInfo` annotation, but did not perform any validation on the contents of the `StructInfo` annotation.
This commit updates the Relax well-formed check to verify that the `StructInfo` annotations are accurate by comparing against the `StructInfo` that would be inferred for an expression.  (This only requires that the information is accurate, not that it is complete. For example, an expression that is inferred to be `R.Tensor(shape=[128,8], dtype="float32")` may have annotation of `R.Tensor(ndim=2, dtype="float32"`, but may not have an annotation of `R.Tensor(shape=[128,8], dtype="int32")`.)
> [Relax] Validate StructInfo annotations in well-formed check

- python/tvm/rpc/__init__.py
- python/tvm/rpc/server.py
This PR updates the python docstrings to include
more clarity on RPC server security model.
> [DOCS] More clarity on security model of RPC server

- python/tvm/contrib/msc/core/transform/pattern.py
- python/tvm/relax/frontend/torch/fx_translator.py
- src/contrib/msc/framework/tvm/relax_opcode.cc
- tests/python/contrib/test_msc/test_graph_build.py
- tests/python/relax/test_frontend_from_fx.py
[torch.nn.functional.scaled_dot_product_attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) outputs in the shape of `(N, ..., L, E_v)` but [`relax.op.nn.attention`](https://github.com/apache/tvm/blob/4ab3f82669fb20d77cae47704c857ab39a577417/python/tvm/relax/op/nn/nn.py#L1747) does `(N, L, ..., E_v)` so the output should also be transposed.
Maybe we should add E2E tests in `tests/python/nightly/` to check the relax torch frontend.
cc: @yongwww
> [Relax][PyTorch] Fix output shape of `torch.nn.functional.scaled_dot_product_attention`

- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR bumps FlashInfer to reduce the size of required temporary workspace.
> [3rdparty] Bump FlashInfer for tmp workspace reduction

- src/runtime/relax_vm/paged_kv_cache.cc
This PR enhances the `AttentionWithFusedQKV` function of `PagedKVCache` so that it can now accept input `qkv_data` and `o_data` that have padding along the sequence dimension.
We introduce this enhancement to allow more flexibility for the caller of PagedKVCache to decide whether to pad the input qkv/o NDArrays or not.
> [KVCache] Attention func accepting over-padded qkv and output NDArray

- src/target/llvm/codegen_llvm.cc
This PR fixes the LLVM version cutoff for `llvm::sys::getHostCPUFeatures`. Previously the cutoff version is set to 20.0, assuming that the signature change happens since LLVM 20.0.
While actually the signature change happens at 19.0.
Reference:
* LLVM 18.1.8 https://github.com/llvm/llvm-project/blob/llvmorg-18.1.8/llvm/include/llvm/TargetParser/Host.h#L56
* LLVM 19.1.0 https://github.com/llvm/llvm-project/blob/llvmorg-19.1.0-rc1/llvm/include/llvm/TargetParser/Host.h#L55
> [Fix][LLVM] Fix getHostCPUFeatures LLVM version cutoff

- ci/jenkins/docker-images.ini
- tests/python/frontend/pytorch/test_fx_quant.py
- tests/python/relax/test_frontend_onnx.py
- tests/python/tir-transform/test_tir_transform_simplify.py
- tests/scripts/task_build_hexagon_api.sh
> [CI] Update image tag to 20240917-153130-9f281758

- src/target/source/codegen_webgpu.cc
- web/emcc/wasm_runtime.cc
- web/src/runtime.ts
This PR implements `tvmjs.runtime.ConcatEmbeddings` in C++ and exposes it to `runtime.ts`'s `Instance` class as `concatEmbeddings()`.
The method takes in a vector of `NDArray`, each array `i` has shape `(m_i, hidden_size)`, returning an NDArray of shape `(\sum_{i} {m}, hidden_size)`.
Besides, this PR also:
- Add reserved name `std` for WebGPU codegen
- Allow `copyFrom()`'s `data` argument to be different types of typed array
- Allow `this.dtype === uint32` for `copyFrom()`
> [WASM] Implement concat embeddings

- python/tvm/relax/vm_build.py
- python/tvm/script/ir_builder/ir/__init__.py
- python/tvm/script/ir_builder/ir/ir.py
- python/tvm/script/ir_builder/tir/external_kernel.py
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/script/ir_builder/tir/triton.py
- src/script/ir_builder/ir/ir.cc
- tests/python/contrib/test_tir_triton_integration.py
Added a macro `T.call_triton` in TIR script parser, which expands to AOT compilation of the kernel and the host TIR code to launch the kernel.
cc @tqchen @cyx-6
> [TIR, TVMScript] Add TIR - Triton integration

- src/tir/transforms/narrow_datatype.cc
- tests/python/tir-transform/test_tir_transform_narrow_datatype.py
Fix an issue in `NarrowDataType` pass. When we perform narrowing on buffer indices, the integer bits constraint is irrelevant to buffer load value's integer bits. Thus it looks like we should reset the context bit info when traverse into the indices field.
Another small change is in cast node rewrite, skip node construction when dtype actually matches.
> [TIR][NarrowDataType] Bufferload's index should not inherit bits constraint of value

- cmake/utils/FindLLVM.cmake
- tests/python/all-platform-minimal-test/test_runtime_ndarray.py
This is a workaround for an upstream LLVM issue [0], in which the `CMAKE_INSTALL_LIBDIR` variable is used before definition. While there is an LLVM PR to resolve this fix [1], as of 2024-08-19 it has not yet been merged to LLVM.
[0] https://github.com/llvm/llvm-project/issues/83802
[1] https://github.com/llvm/llvm-project/pull/83807
Co-authored-by: Eric Lunderberg <Lunderberg@users.noreply.github.com>
> [CI][Windows] Workaround for error in FindLLVM

- python/tvm/relax/vm_build.py
- python/tvm/runtime/module.py
> [Runtime] Add property Module.is_device_module

- ci/jenkins/unity_jenkinsfile.groovy
- src/contrib/msc/plugin/torch_codegen.cc
- tests/python/relax/test_frontend_dynamo.py
- tests/python/relax/test_frontend_stablehlo.py
> [CI] Upgrade unity image tag to `20240917-153130-9f281758`

- python/tvm/_ffi/_cython/base.pxi
- python/tvm/_ffi/_cython/packed_func.pxi
- src/runtime/registry.cc
- src/support/ffi_testing.cc
This PR updates the CheckSignals function to grab GIL. This is needed because we now explicitly release gil when calling any C functions. GIL will need to be obtained otherwise we will run into segfault when checking the signal.
The update now enables us to run ctrl + C in long running C functions.
> [FFI][BUGFIX] Grab GIL when check env signals

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relay/test_to_mixed_precision.py
> [Relax][PyTorch] Support more unary ops for ExportedProgram importer

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
> [Relax][PyTorch] Support binary, statistical and search ops for ExportedProgram importer

- python/tvm/dlight/gpu/matmul.py
- tests/python/dlight/test_gpu_matmul.py
Improved matmul schedule with layout transpose approach, which improves as follows -
----Model-------prefill baseline ---------prefill optimized
--Llama-2-7b-------51 tok/sec --------------86 tok/sec
--Llama-3-8b-------48 tok/sec --------------79 tok/sec
--gemma-2b -------140 tok/sec -------------245 tok/sec
> [DLIGHT][GPU] Improve matmul schedule for adreno

- docs/how_to/tutorials/e2e_opt_model.py
- python/tvm/relax/pipeline.py
- python/tvm/relax/transform/transform.py
This PR introduces a static shape tuning pipeline for Relax. It is designed to work with the MetaSchedule tuning framework to optimize the performance of the model.
Together with a minor typo fix
> [Relax] Introduce static shape tuning pipeline

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
With this PR, I verified that the following torchvision models can be executed.
- convnext_tiny
- densenet121
- efficientnet_b0
- efficientnet_v2_s
- inception_v3
- maxvit_t
- mnasnet0_5
- mobilenet_v2
- mobilenet_v3_small
- regnet_x_400mf
- resnet18
- resnext50_32x4d
- shufflenet_v2_x0_5
- squeezenet1_0
- swin_t
- swin_v2_t
- vgg11
- vgg11_bn
- vit_b_32
- wide_resnet50_2
> [Relax][PyTorch] Support tensor manipulation and creation ops for ExportedProgram importer

- python/tvm/relax/frontend/nn/llm/kv_cache.py
Improvements
* Added Tranpose to K for better Vectorization during Matmul.
* Improved Load Schedule.
* Improved a bit more than 2x is most cases.
Llama-2 7B observation
-----------kernel----------------baseline----------optimized-
---batch_prefill_ragged_kv------15 ms-------------7.1 ms
> [KVCACHE] Improved schedule for prefill attention

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- python/tvm/relax/op/set.py
- python/tvm/relax/transform/legalize_ops/nn.py
- tests/python/relax/test_frontend_onnx.py
- tests/python/relax/test_relax_operators.py
- tests/python/relax/test_transform_legalize_ops_nn.py
This PR adds a variety of ONNX ops to the Relax frontend, including:
- Acos
- Acosh
- And
- Asin
- Asinh
- Atan
- Atanh
- BitwiseAnd
- BitwiseOr
- BitwiseXor
- Ceil
- ConcatFromSequence
- ConvTranspose
- Cosh
- DepthToSpace
- FastGelu
- Floor
- GlobalLpPool
- GlobalMaxPool
- GreaterOrEqual
- IsInf
- IsNaN
- LeakyRelu
- LogSoftmax
- MaxUnpool
- Mean
- MeanVarianceNormalization
- Mish
- Or
- PRelu
- Round
- Scatter
- ScatterElements
- Selu
- SequenceAt
- SequenceConstruct
- SequenceEmpty
- SequenceErase
- SequenceInsert
- SequenceLength
- Shrink
- Sinh
- Size
- Softplus
- Softsign
- SpaceToDepth
- SplitToSequence
- Tan
- ThresholdedRelu
- TopK
- Unique
- Xor
Also remains a few ops that are not supported yet, see the commented out ops in the ONNX frontend.
> [Relax][ONNX] Expand op support for ONNX frontend

- include/tvm/runtime/c_runtime_api.h
- include/tvm/runtime/data_type.h
- include/tvm/topi/elemwise.h
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/intrin_rule_hexagon.cc
- src/tir/analysis/verify_gpu_code.cc
This pull request introduces a new method `is_vector` to the `DataType` class and updates various parts of the codebase to use this method for checking if a type is a vector.
> [TIR] Add `is_vector` Method to DataType class and update usages across Codebase

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/frontend/onnx/test_forward.py
- tests/python/relax/test_frontend_onnx.py
There are a few relax tests in `tests/python/frontend/onnx/test_forward.py`, which is used for relay frontend. This commit moves them to the correct file.
> [ONNX] Move relax related tests to the correct file

- docs/get_started/tutorials/ir_module.py
- docs/how_to/tutorials/e2e_opt_model.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
> [Relax][PyTorch][Docs] Use `torch.export` insteamd of `fx.symbolic_trace` for tutorial

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- python/tvm/relax/op/__init__.py
- python/tvm/relax/op/set.py
- src/relax/op/tensor/set.cc
- src/relax/op/tensor/set.h
- tests/python/relax/test_frontend_onnx.py
- tests/python/relax/test_op_set.py
this PR adds the NonZero op to Relax, together with ONNX frontend support
> [Relax] Add NonZero op

- conda/build-environment.yaml
This PR fixes the Windows conda build issue on CI by pining conda version `<24.9.0`
> Try to fix windows CI conda build issue

- jvm/core/src/main/java/org/apache/tvm/Function.java
- jvm/core/src/main/java/org/apache/tvm/LibInfo.java
- jvm/core/src/main/java/org/apache/tvm/contrib/GraphModule.java
- jvm/native/src/main/native/jni_helper_func.h
- jvm/native/src/main/native/org_apache_tvm_native_c_api.cc
Java API is still using the outdated initialization method for `GraphModule`, which has led to issues where the old API no longer works as expected.
This PR updates the Java API for `GraphModule` initialization to match the simplified method used in the Python API.
In the Python API, `GraphModule` can be initialized in a more concise way:
```python
gm = graph_executor.GraphModule(lib["default"](dev))
```
However, the Java API still uses the older approach:
```python
gm = graph_executor.create(graph_json, lib, dev);
gm.load_params(params);
```
The old API is not only more verbose (two additional files need to be saved and loaded), but also appears to no longer be functional as expected.
---
Here is an example of deploying [DepthAnything](https://github.com/DepthAnything/Depth-Anything-V2) …
> [JVM] Align Java GraphModule Initialization with Python API

- python/tvm/relax/frontend/nn/llm/kv_cache.py
This PR reverts apache/tvm#17432 as we observe a correctness issue
when `num_attention_heads` is 28.
The correctness issue leads to incorrect end-to-end results in LLM inference.
> Revert "[KVCACHE] Improved schedule for prefill attention"

- include/tvm/tir/schedule/schedule.h
- include/tvm/tir/stmt.h
- python/tvm/tir/schedule/schedule.py
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/primitive.h
- src/tir/schedule/primitive/annotate_buffer_access.cc
- src/tir/schedule/schedule.cc
- src/tir/schedule/traced_schedule.cc
- src/tir/schedule/traced_schedule.h
- src/tir/transforms/compact_buffer_region.cc
- tests/python/tir-schedule/test_tir_schedule_annotate_buffer_access.py
This PR introduces a new TIR schedule primitive **annotate_buffer_access** that allows explicit annotation of buffer access regions for both reads and writes. 
TVM currently does not support inferring the numerical range of floating-point calculations. As a result, buffer access regions involving floating-point calculations cannot be accurately inferred and default to the full extent of the buffer. This new primitive addresses this limitation by allowing manual specification of access regions.
This primitive is particularly useful for operations where the default buffer region inference may not capture the precise access patterns, such as in resize operations. It overrides the automatically inferred region for the specified buffer.
before:
```python
@T.prim_func
def before(x: T.Buffer((1, …
```
> [TIR][Schedule] Add annotate_buffer_access primitive

- src/tir/schedule/analysis/analysis.cc
- src/tir/schedule/concrete_schedule.cc
- src/tir/schedule/concrete_schedule.h
- src/tir/schedule/trace.cc
- src/tir/schedule/traced_schedule.cc
- tests/python/tir-schedule/test_tir_schedule_sampling.py
- tests/python/tir-schedule/test_tir_schedule_split_fuse.py
Below script would either segfault or report primitive error in `MetaScheduleTuneIRMod` with dynamic dim.
```python
import tvm
from tvm import relax
from tvm.relax.frontend import nn
from tvm.relax.transform import *
class NNModule(nn.Module):
def __init__(self):
super().__init__()
self.fc2 = nn.Linear(784, 128)
def forward(self, x):
x = self.fc2(x)
return x
mod, params = NNModule().export_tvm({"forward": {"x": nn.spec.Tensor(("n", 784), "float32")}})
mod.show()
with tvm.target.Target("llvm -num-cores 32"):
mod = LegalizeOps()(mod)
mod = AnnotateTIROpPattern()(mod)
mod = FoldConstant()(mod)
mod = FuseOps()(mod)
mod = FuseTIR()(mod)
mod = MetaScheduleTuneIRMod({}, "myworkingdir", 3)(mod)
application_pass = MetaScheduleApplyDatabase( "myworkingdir")
mod = application_pass(mod)
print(mod)
m …
```
> [MetaSchedule] Fix a multilevel tiling error on dynamic relax workload

- src/arith/presburger_set.cc
Compile fixes for the optional mlir presburger module using latest LLVM 19.x branch.
```
tvm-0.18-build/tvm/src/arith/presburger_set.cc:219:33: error: no member named 'MPInt' in namespace 'mlir::presburger'
219 |   SmallVector<mlir::presburger::MPInt> coeffs;
|               ~~~~~~~~~~~~~~~~~~^
tvm-0.18-build/tvm/src/arith/presburger_set.cc:227:40: error: no member named 'MPInt' in namespace 'mlir::presburger'
227 |     coeffs.push_back(mlir::presburger::MPInt(*as_const_int(it)));
|                      ~~~~~~~~~~~~~~~~~~^
[ 18%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/feature.cc.o
2 errors generated.
```
> [LLVM][Arith] Presburger compile fix for MLIR/LLVM 19.x

- docker/Dockerfile.ci_lint
Part of #17451 
Because [hundreds of lint errors](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-lint/detail/PR-17451/4/pipeline) are generated with cpplint==2.0.0. So, we temporarily pin the cpplint version to what we've been using.
> [CI] Pin cpplint==1.6.1

- docker/install/ubuntu2004_install_python_package.sh
- docker/install/ubuntu_install_python_package.sh
Part of #17451
pytest-profiling==1.8.0 was yanked so we'll pin to 1.7.0
https://pypi.org/project/pytest-profiling/1.8.0/
> Pin pytest-profiling==1.7.0

- docker/install/ubuntu_install_jax.sh
- docker/install/ubuntu_install_tensorflow.sh
- docker/install/ubuntu_install_tensorflow_aarch64.sh
- docker/install/ubuntu_install_tflite.sh
Revert part of #17425 because the changes in jax, keras, tensorflow, and tflite are larger than I expected so we can work those upgrades separately.
> [CI] Revert jax, keras, tensorflow, and tflite upgrades introduced #17425 

- tests/python/topi/test_topi_depthwise_conv2d_back_input.py
Because it's deprecated.
https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
> Replace `np.int` with `np.int32`

- python/tvm/relay/op/contrib/mrvl.py
- src/relay/backend/contrib/mrvl/codegen.cc
- tests/python/contrib/test_mrvl/test_mrvl.py
Added support for global_max_pool2d and squeeze op for Marvell BYOC.
Also added unit tests for Maxpool, Avgpool, Global AvgPool, Global Maxpool and Squeeze operators
> [Marvell BYOC]: global_max_pool2d and squeeze op support

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
I added a tuple wrapping around axis when sending it to _np.squeeze since it does not support list objects. I added an additional check to see if the data is a ShapeExpr. If this is the case I perform the inverse of the operations done in the Unsqueeze operation. 
I fixed a bug where the dimensions were assumed to be of IntImm data type by adding an additional check to handle the constant and dynamic case separately.
I fixed a bug where the dimensions were assumed to be of IntImm data type by adding an additional check to handle the constant and dynamic case separately.
I replaced asnumpy with numpy since asnumpy is deprecated. I added a call to .item() to convert from numpy data types to python primitives. 
I extracted generate_random_value function from generate_random_inputs.
I added …
> [FIX][ONNX][RELAX] Add support for dynamic ShapeExpr in Slice, Squeeze and Flatten

- cmake/modules/contrib/Mrvl.cmake
- docs/how_to/deploy/mrvl.rst
- python/tvm/relay/op/contrib/mrvl.py
- src/relay/backend/contrib/mrvl/codegen.cc
- src/runtime/contrib/mrvl/mrvl_hw_runtime.cc
This PR adds support for the Marvell Hardware runtime, which enables executing compiled models on the Octeon target device. 
This change is part of Phase 3 as outlined in the pre-RFC documentation: https://discuss.tvm.apache.org/t/prerfc-byoc-integrating-marvell-ml-ai-accelerator-to-the-tvm-byoc-framework/16155
The user can specify whether to compile for the simulator or for the hardware using a command line option. The documentation has been updated as well to describe the new feature.
> [mrvl][runtime]: Support Marvell Hardware Runtime

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
Updated Expand converter in onnx frontend to to handle dynamic shape expressions by matching data and target_shape
dimension lengths and converting any target shape elements assigned to -1 to the data shape dimension.
Added regression test to onnx frontend testing Expand with a dynamic shape 
I replaced int(k.data.numpy()[0]) with int(k.data.numpy().item()) in Trilu since sometimes the data shape is a zero dimensional scalar
I added a function converting from PrimExpr to PrimValue before sending in starts, ends, steps to relax.op.strided_slice since it does not accept PrimeExpr as inputs.
> [RELAX][ONNX] Add support for dynamic shape expression in Expand

- docker/Dockerfile.ci_gpu
- docker/install/ubuntu_install_oneflow.sh
Because `oneflow==0.8.0` is incompatible with `numpy==1.24.*`
Also remove the duplicate cmake installation and fix the pip config.
Link: https://github.com/Oneflow-Inc/oneflow/issues/9660
> [CI] Upgrade `oneflow==0.9.0`

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
The shape names in an ONNX model can contain expressions such as the shape `int64[batch_size,past_sequence_length + sequence_length]` of the attention mask of an LLM. In this case, the second dimension contains an expression `past_sequence_length + sequence_length` where `past_sequence_length` and `sequence_length` should be individual variables added together. However, currently, a new variable named `"past_sequence_length + sequence_length"` is instead created when translating the graph. 
I added a simple parser that creates individual size variables for the variable names and generates the resulting prim expression. Note, in order to keep the parser simple, it evaluates expressions left to right. Not accounting for operator precedence. 
I added regression tests to verify that the onnx …
> [RELAX][ONNX][FIX] add a parser to handle expression in the shape dim names 

- python/tvm/contrib/msc/core/codegen/codegen.py
- python/tvm/contrib/msc/core/utils/dataset.py
- python/tvm/contrib/msc/framework/torch/frontend/translate.py
- python/tvm/contrib/msc/pipeline/pipeline.py
- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- src/contrib/msc/framework/torch/torch_opcode.cc
- src/contrib/msc/framework/tvm/relax_opcode.cc
- tests/python/contrib/test_msc/test_graph_build.py
- tests/python/contrib/test_msc/test_translate_relax.py
- tests/python/contrib/test_msc/test_translate_relay.py
- tests/python/contrib/test_msc/test_translate_tensorrt.py
- tests/python/contrib/test_msc/test_translate_torch.py
- tests/python/relax/test_frontend_from_fx.py
scatter ops are widely used in multi-modal models, such as A[B]=C to mix input_embeddings and image embeddings.
This PR:
1. support stack via concat + reshape
2. support scatter via scatter_elements
3. support index put via scatter_nd
> [Relax] support scatter ops

- include/tvm/topi/transform.h
- python/tvm/relax/transform/legalize_ops/distributed.py
- python/tvm/relax/transform/legalize_ops/index.py
- python/tvm/topi/transform.py
- src/relax/op/tensor/index.cc
- src/topi/transform.cc
- tests/python/relax/test_op_index.py
- tests/python/relax/test_transform_legalize_ops_index_linear_algebra.py
Fixed inconsistency between relax.strided_slice output shape and topi.strided_slice output shape when assume_inbound 
is set to false.
I added an assume_inbound flag to topi.strided_slice. If it is false then the begin and end indices are canonicalized before the dimension length is calculated. To avoid introducing duplicate code i removed the corresponding functions from relax/../index.cc and instead reference the new functions defined in include/tvm/topi/transform.h.
I added a regression test for the case with assume_inbound = false when the end of the slice is at infinity, e.g. v[begin:], which previously caused an incorrect output shape.
> [FIX][TOPI][strided_slice] Fix topi.strided_slice output shape

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- python/tvm/relax/op/set.py
- src/relax/op/tensor/set.cc
- tests/python/relax/test_frontend_onnx.py
- tests/python/relax/test_op_set.py
This PR updates the ONNX frontend:
- Add match cast for unique and nonzero operators, enabling further import of ONNX models.
- Add support for compress operator.
- Fix the shape of the output tensor for nonzero operator.
> [Relax] Update ONNX frontend for unique, nonzero and compress

- src/relax/transform/static_plan_block_memory.cc
- tests/python/relax/test_transform_static_plan_block_memory.py
This PR fixes an internal error #17488 
This error happens because the visitor class StorageAllocatorBaseVisitor does not correctly handle DataflowBlockNode instances. Specifically, the VisitBindingBlock_ method is not overridden for DataflowBlockNode, leading to an empty block_stack_ when it is expected to contain the current block.
To fix this issue, we need to override the VisitBindingBlock_ method for const DataflowBlockNode* in the StorageAllocatorBaseVisitor class. By doing so, we ensure that the block_stack_ is correctly managed when visiting dataflow blocks, similar to how it is managed for regular binding blocks.
> Fix InternalError in StaticPlanBlockMemory when visiting DataflowBlockNode

- docs/dev/how_to/debugging_tvm.rst
This pull request provides a fix typo in Debugging TVM docs.
> [DOCS] Fix Typo in Debugging TVM

- docs/deep_dive/tensor_ir/learning.rst
This pull request provides a fix typo in TensorIR Docs.
> [DOCS] Fix typo in TensorIR

- python/tvm/script/ir_builder/tir/ir.py
- src/te/operation/create_primfunc.cc
- tests/python/te/test_te_create_primfunc.py
If the loop domain depends on other loops, currently there is missing transformations in `CreatePrimFunc`, which lead to undefined variables in lowering.
https://discuss.tvm.apache.org/t/compilation-error-for-adaptive-avg-pool2d-relax-op-in-mlc-llm/17784
> [TE][CreatePrimFunc] Fix loop carried dependency case with nested block levels

- gallery/how_to/deploy_models/deploy_model_on_adreno_tvmc.py
Updated to PyTorch model as the other is broken now.
> [DOCS] Few fixes for broken Adreno docs

- docker/bash.sh
- python/tvm/relay/op/contrib/clml.py
- src/relay/backend/contrib/clml/codegen.cc
- src/runtime/contrib/clml/clml_runtime.cc
- src/runtime/contrib/clml/clml_runtime.h
- src/runtime/contrib/clml/clml_utils.cc
- src/runtime/contrib/clml/clml_utils.h
- tests/scripts/ci.py
We can now build one binary and use across targets Compiler pass config to choose target clml support version
Introducing compiler config "relay.ext.clml.target_version".
Partition pass will choose offloading ops based on target support.
This config enables choosing target version on python api as well as tvmc.
> [RUNTIME][CLML] Dynamic backward compatibility

- python/tvm/relax/frontend/torch/fx_translator.py
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/transform/set_expr_layout.cc
- src/contrib/msc/framework/torch/torch_opcode.cc
- tests/python/contrib/test_msc/test_graph_build.py
- tests/python/contrib/test_msc/test_translate_relax.py
- tests/python/contrib/test_msc/test_translate_torch.py
- tests/python/relax/test_frontend_from_fx.py
This PR support masked_scatter op in torch
> [Relax] support masked_scatter

- docker/install/ubuntu_install_zephyr_sdk.sh
Part of #17451 
Zephyr SDK 0.16.9 is compatible with Zephyr 3.6, which we use for CI.
https://github.com/zephyrproject-rtos/sdk-ng/wiki/Zephyr-SDK-Version-Compatibility-Matrix
> [CI] Upgrade zephyr-sdk to 0.16.9

- python/tvm/relax/frontend/common.py
- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
Add auto_pad support for conv.
> [Relax][Frontend][Onnx] Add auto_pad support for conv

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
adding support for ONNX LPPool and refactoring frontend tests
> [Relax] Add support for ONNX LPPool

- python/tvm/relax/frontend/nn/llm/kv_cache.py
This PR fixes two bugs of the attention prefill ragged kernel.
* The first bug is the unroll of loop `ki`, which causes the TIR build failure in the PointerValueTypeRewrite pass due to vector size.
* The second is the tile sizes of `tile_z` and `tile_y` may violate the assertion check in `get_tile_size`.
> [KVCache] Fix attention prefill kernel for Metal and Android

- python/tvm/arith/analyzer.py
- python/tvm/topi/scatter.py
The following assert in the `_verify_scatter_nd_inputs` function could fail if the shapes contain prim expressions: `assert indices.shape[i + 1] == updates.shape[i]`. I updated it to `analyzer.can_prove_equal(indices.shape[i + 1], updates.shape[i])` using the arithmetic analyzer instead.
> [FIX][topi.scatter_nd] fixed shape equality assert by using analyzer to prove equality

- src/relax/transform/convert_layout.cc
When using `layouts[0].LeafValue()->layout->name`, I got a segment fault when `layouts[0].LeafValue()->layout` is `__undef__`. `layouts[0].LeafValue()->layout.name()` can judge and handle this case.
> [Relax] Fix bug in convert_layout pass

- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
- tests/python/runtime/test_runtime_module_based_interface.py
- tests/python/runtime/test_runtime_module_load.py
This PR propose to make ORCJIT the default LLVM runtime executor (engine).
* Currently [ORCJIT](https://llvm.org/docs/ORCv2.html) is a optional executor under ```llvm -jit=orcjit``` flag, introduced [here](https://github.com/apache/tvm/pull/15964).
* Targets like RISCV, and possible others too, will not work on MCJIT see some discussions [here](https://reviews.llvm.org/D127842) .
* As a live example, similar project Halide already use ORCJIT completley replacing the old MCJIT engine.
TVM disscussions and recent issues on the subject:
* https://discuss.tvm.apache.org/t/run-tvm-software-stack-on-risc-v/17683/4
* https://github.com/apache/tvm/issues/17508
Since ORCJIT was poorly exposed within TVM until now (being optional) any rising issues will need attention.
> [LLVM][RUNTIME] Make ORCJIT LLVM executor the default one

- src/target/tag.cc
This PR address a fix for https://github.com/apache/tvm/issues/17492
* It seems that LLVM version >= 19 misses the mcpu ```apple-latest``` in the llvm backend.
* Relevant [LLVM change](https://github.com/llvm/llvm-project/commit/f07d30072ac0dd0e10a4684335d5f464db627049#diff-4d527cab186c06e9ffbbb5c76af64c13394ef424e72b62ee0c807f44895690f4R215-R216) makes this [alias unavailable](https://github.com/llvm/llvm-project/blob/f07d30072ac0dd0e10a4684335d5f464db627049/llvm/utils/TableGen/ARMTargetDefEmitter.cpp#L215-L217), but works from llc/clang higher frontends.
```
llvm_instance.cc:226: Error: Using LLVM 19.1.2 with `-mcpu=apple-latest` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
llvm_instance.cc:226: Error: Using LLVM 19.1.2 with `-mcpu=apple-latest` is not …
```
> [FIX][LLVM] Workaround -mcpu=apple-latest for llvm above 18.0 (#17492)

- src/target/llvm/codegen_amdgpu.cc
- src/target/llvm/codegen_blob.cc
- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_hexagon.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/codegen_nvptx.cc
- src/target/llvm/codegen_x86_64.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
Hello All,
this PR adapts for LLVM-20 changes. Please feel free to let me know if there is a better way to do it.
Thank you!
> [LLVM] Make compilable with LLVM-20

- web/src/webgpu.ts
This PR adds the `powerPreferece` argument to `detetectGPUDevice()`, while keeping the previous functionality as default, without breaking older code.
In hybrid GPU systems (mainly laptops) is sometimes needed to select the low-power integrated GPU in order to test model inference on https://github.com/mlc-ai/web-llm/ for other low-power devices or just to save on battery.
Here's the related line of code on the `web-llm` repository that references this function:
https://github.com/mlc-ai/web-llm/blob/082f04e4941ff4f6ef70731d244c69228948c7a1/src/service_worker.ts#L117
> [Web]Allows setting powerPreference on webgpu

- tests/python/meta_schedule/test_meta_schedule_runner.py
Skip the flaky tests to unblock CI.
> [Test] Skip flaky test to unblock CI

- src/meta_schedule/feature_extractor/per_store_feature.cc
**Bug Description: Incorrect Assignment of `is_gpu` Property**
**Summary:**
In the context of feature extraction using `meta_schedule`, the `is_gpu` property was incorrectly assigned by directly comparing the target kind name to `"cuda"`. This approach is not only too specific but also potentially unsafe, as it does not account for different GPU types or handle cases where the target might be undefined.
**Incorrect Code:**
https://github.com/apache/tvm/blob/567eeed38bdbcefb68e36328af6ab1501a81d51e/src/meta_schedule/feature_extractor/per_store_feature.cc#L1395
```cpp
bool is_gpu = tune_context->target.value()->kind->name == "cuda";
```
**Problems with the Incorrect Code:**
1. **Lack of Generality:** Not all GPUs use CUDA (e.g., AMD GPUs may use ROCm or OpenCL).
2. **Specificity Issue:** …
> Fix GPU detection in PerStoreFeatureNode

- python/tvm/relax/frontend/nn/llm/kv_cache.py
This PR fixes the tile size calculation in the TIR attention kernels, where the computed tile sizes may not divide the total loop extent.
> [Fix][KVCache] Fix incorrect tile size calculation

- python/tvm/relax/frontend/onnx/onnx_frontend.py
Added prim expression handling in the Neg operator converter
Updated Arange operator converter to use relax.op.arange instead of topi.arange
> [RELAX][ONNX] Add prim experssion support to Neg converter and update Arange converter to use relax.op.arange

- python/tvm/contrib/graph_executor.py
- src/runtime/graph_executor/graph_executor.cc
- tests/python/relay/test_backend_graph_executor.py
New API ``get_output_index`` added
Existing OutPut Info is exposed via graph runtime interface.
> [GRAPH RT] Additional API support

- python/tvm/script/ir_builder/tir/ir.py
- src/relax/op/image/resize.cc
- src/relax/op/nn/convolution.cc
- src/relax/op/nn/nn.cc
- src/relax/op/nn/pooling.cc
- src/relax/op/op_common.cc
- src/relax/op/op_common.h
- src/relax/op/tensor/binary.cc
- src/relax/op/tensor/index.cc
- src/relax/op/tensor/manipulate.cc
- src/relax/op/tensor/statistical.cc
- src/relax/transform/convert_layout.cc
- src/relax/transform/infer_layout_utils.cc
- src/relax/transform/infer_layout_utils.h
- tests/python/relax/test_transform_convert_layout.py
Majority of the operations made compatible with custom layouts. Incompatible ops will fallback to regular layout.
Conv1D, Conv3D, Pool1D, Pool3D, AdaptiveAvgPool1D, AdaptiveAvgPool3D are left unchanged now. 2D networks are expected to work now.
> [RELAX][PASS] Convert layout pass and ops enhanced to support sub indexing

- include/tvm/tir/builtin.h
- python/tvm/script/ir_builder/tir/ir.py
- python/tvm/tir/__init__.py
- python/tvm/tir/op.py
- src/tir/op/builtin.cc
- src/tir/transforms/loop_partition.cc
- tests/python/tir-transform/test_tir_transform_loop_partition.py
The change wants to merge set of finegrained control improvement on loop partition pass.
1) Add an annotation intrinsic `T.ignore_loop_partition`, which mark the wrapped predicate not to take part in the loop partition phase. Since in sometimes loop partition would enlarge the generated code size and we want to preserve some predicates intentionally.
2) Add patch for EQ predicate partition. Try solve `a <= b && b <= a` instead if solve `a==b` directly failed.
3) Fix `TryPartition`'s return statement. Since the caller handle the return value by
- If undef, try recursive solving.
- If defined, treat as a successfully partioned result stmt.
> [TIR][LoopPartition] enforcement on loop partition control

- python/tvm/driver/tvmc/compiler.py
Multiple sub graphs of same BYOC is possible.
Append them to the same dump file and also ignore any errors while dump.
> [TVMC] Bug fix

- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
add two missing args `rope_ext_factors` and `enable_kv_transfer` in func:`create_kv_cache -> vm.builtin.paged_attention_kv_cache_create_reduced`
> [Flashinfer][Fix] fix missing args in flashinfer test

- src/relay/ir/dataflow_matcher.cc
This optimization allows to speedup PatternRewriter transformations by reusing of previous type inferred expression instead of perform InferType multiple times
The test_pass_simplify_expr.py tests on my machine started to pass for 40 seconds vs 116 seconds main branch state
> [Relay]Disable InferType if it was done and no changes after previous pass

- docker/install/ubuntu_install_tensorflow.sh
- docker/install/ubuntu_install_tflite.sh
- docker/install/ubuntu_install_wasmtime.sh
upgrade TF to latest version and fixup tflite build issue accordingly.
> [DOCKER] Tensorflow upgrade to 2.18.0

- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
This PR introduces the initial KV cache interface setup for multi-head latent attention in DeepSeek models.
Some interface implementations are marked todo for implementation in the soon future.
> [Runtime][KVCache] Initial interface setup for MLA

- python/tvm/relax/frontend/nn/llm/kv_cache.py
- python/tvm/relax/frontend/nn/llm/tree_attn.py
- src/runtime/cpu_device_api.cc
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_cpu.py
This PR introduces KV Cache support for the CPU runtime:
* Implementation of KV Cache TIR for CPU-based processing.
* Updates to the relevant runtime components to integrate KV Cache.
> [KVCache] Add KV Cache for CPU Runtime

- docker/install/ubuntu2004_install_python_package.sh
- docker/install/ubuntu_install_python_package.sh
#17476
pytest-profiling==1.8.1 was released so we can upgrade to it.
> [CI] Unpin pytest-profiling

- python/tvm/relax/frontend/nn/llm/kv_cache.py
- python/tvm/relax/frontend/nn/llm/tree_attn.py
- src/runtime/relax_vm/kv_state.cc
- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_mla_tir.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR introduces the MLA attention kernels written in TIR. It also implements the KV cache MLA computation logic.
A new unit test file is added to ensure the correctness of the TIR kernels.
This PR also fixes a few TIR prefill kernel tile size initialization.
> [KVCache] TIR attention kernel support for MLA

- python/tvm/relax/backend/__init__.py
- python/tvm/relax/backend/cpu_generic/__init__.py
- python/tvm/relax/backend/cpu_generic/pipeline.py
- python/tvm/relax/backend/cuda/__init__.py
- python/tvm/relax/backend/cuda/pipeline.py
- tests/python/relax/test_pipeline.py
This PR sets up the initial relax backend pipeline, as per thread in https://discuss.tvm.apache.org/t/relax-target-default-pipeline.
Particularly, we organized default list of passes in the default pipeline into four stages:
* library dispatch passes,
* legalize passes,
* dataflow lower passes,
* finalize passes.
The expectation is to have the default pipeline work out of the box, while users can still choose to customize the pipeline by importing these lists and combining them together, with customized passes inserted at proper locations.
In this PR, we set up the initial pipelines for CUDA and LLVM backends. The pipelines for both backends will be enhanced and completed in the near future, and meanwhile the default pipeline for more backends (e.g., generic GPUs) will be added.
The …
> [Relax] Initial setup of relax backend pipeline

- src/tir/transforms/inject_software_pipeline.cc
- tests/python/tir-transform/test_tir_transform_inject_software_pipeline.py
The MR try fix a corner case in software pipeline injection.
When the loop num is too few to fill the pipeline main body, the setup phase and draining phase's loop indices should not overlap. Currently the decomposition is
- prologue: [0, num_stage - 1)
- body: [num_stage - 1, loop_num)
- epilogue: [loop_num, loop_num+ num_stage - 1)
Thus we should also ensure that `i >= max(loop_num, num_stage - 1)` for epilogue part.
> [TIR][SoftwarePipeline] Ensure pipeline epilogue and prologue do not overlap

- python/tvm/meta_schedule/__init__.py
- python/tvm/meta_schedule/post_optimization/__init__.py
- python/tvm/meta_schedule/post_optimization/droplet.py
- python/tvm/meta_schedule/post_optimization/post_opt.py
- python/tvm/meta_schedule/post_optimization/space.py
- python/tvm/meta_schedule/post_optimization/utils.py
- python/tvm/meta_schedule/relay_integration.py
- python/tvm/meta_schedule/tir_integration.py
- python/tvm/meta_schedule/tune.py
- tests/python/meta_schedule/test_meta_schedule_space_post_opt.py
Description
This pull request aims to enhance model optimization by adding post optimization in MetaSchedule. The proposed approach involves the following steps:
1. Execution of MetaSchedule over an end-to-end model that requires optimization. 
2. Selection of the best implementation identified by MetaSchedule for the given model. 
3. Utilization of Droplet Search to exploit the selected candidate.
By using Droplet Search as a post optimization ([Droplet paper](https://homepages.dcc.ufmg.br/~fernando/publications/papers/DropletSearch.pdf)), we have been able to reduce the number of trials explored by MetaSchedule while still achieving faster kernel performance. We have observed this improvement on the following architectures: Nvidia A100, Nvidia 3080, AMD x86, and ARM A64FX. The results …
> [MetaSchedule] Adding post optimization in MetaSchedule to Improve Scheduling

- src/target/source/literal/cuda_half_t.h
- tests/python/meta_schedule/test_meta_schedule_mma_m16n8k8_auto_tensorization.py
This PR removes htanh from the list of unsupported CUDA half operators, as it is started to be supported since CUDA 12.8 (https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-math-release-12-8).
Specifically, we added a CUDA version check in the generated CUDA code, so that when the CUDA version is older than 12.8, htanh will still be treated as an unsupported operator and fall back to the packed operation. While for newer CUDA versions, we directly use the function that is defined in `cuda_fp16.h`.
> [CUDA] Remove htanh from unsupported math ops for CUDA 12.8

- CMakeLists.txt
- Makefile
- apps/benchmark/adreno/bench.sh
- python/setup.py
- tests/scripts/setup-pytest-env.sh
- tests/scripts/task_python_adreno.sh
- tests/scripts/task_python_arm_compute_library.sh
- tests/scripts/task_python_docs.sh
- tests/scripts/task_python_hexagon.sh
- tests/scripts/task_python_integration.sh
- tests/scripts/task_python_nightly.sh
- tests/scripts/task_python_topi.sh
- tests/scripts/task_python_unittest.sh
- tests/scripts/task_python_unittest_gpuonly.sh
- tests/scripts/unity/task_python_relax.sh
Historically we have been maintaining cython and ctypes for FFI. One reason was cython was not that available in all platforms then. Cython have quite good availability now and also enjoys great perf benefit. This PR changes the CMake to make cython as required dependency of the python package and build cython by default. It also removes ctypes testcases in favor of all cython tests.
If things go well, we can consider remove ctypes and focus on cython support onward.
> [PYTHON] Build cython by default

- conda/recipe/meta.yaml
- docker/install/ubuntu2004_install_python_package.sh
- docker/install/ubuntu_install_python_package.sh
- docs/install/from_source.rst
- python/gen_requirements.py
- python/tvm/relay/transform/memory_plan.py
This pull request includes several changes aimed at removing the `attrs` library and replacing its usage with a python 3.7+ builtin `dataclasses` in the codebase. Additionally, it updates various dependency lists and installation scripts to reflect this removal.
Code refactoring:
* [`python/tvm/relay/transform/memory_plan.py`](diffhunk://#diff-09be5ffb3fcaecb371823a1802185d034f224c41d91c7e257784942b318ad92fL23-R23): Replaced `attr.s` with `dataclass` for defining the `Region` class. [[1]](diffhunk://#diff-09be5ffb3fcaecb371823a1802185d034f224c41d91c7e257784942b318ad92fL23-R23) [[2]](diffhunk://#diff-09be5ffb3fcaecb371823a1802185d034f224c41d91c7e257784942b318ad92fL44-L52)
Dependency updates:
* [`conda/recipe/meta.yaml`](diffhunk://#diff-eba2917991959691cc8fe3f70bcc7a181ec4b806191e3b3ded427f …
> [Refactor] Phase out python dependency attrs

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- python/tvm/relax/transform/legalize_ops/manipulate.py
- src/relax/op/tensor/manipulate.cc
- tests/python/relax/test_op_manipulate.py
Replaces topi.split with relax.op.split in the ONNX frontend to align with the Relax operator API.
Fixes related ONNX frontend unit tests by:
- Updating InferStructInfoSplit to return a TensorStructInfo instead of a TupleStructInfo if the operator produces only one split, to be consistent with topi.split
- Updating the relax.split legalize callback to only perform the modulo != 0 check when the modulo result is a constant expression
Fixes split unit tests when only one tensor is returned by changing the expected struct info from a TupleStructInfo to a TensorStructInfo.
The reason why it is necessary to update InferStructInfoSplit to return a TensorStructInfo instead of a TupleStructInfo when the  split operator only returns a single tensor is because the MakeCallTIR api will unpack any …
> [ONNX][RELAX] replace topi.split with relax.op.split in the onnx frontend

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports several Pytorch binary ops for Relax and refactors some special(bool type) unary ops tests.
> [Relax][PyTorch] Add support for ge, gt, le, mod, ne ops

- src/arith/scalable_expression.cc
- src/arith/scalable_expression.h
pull request #16893 refactored the TargetHasSVE function to support target assignment instead of using Target::Current(). This introduces a breaking API change for older projects that rely on TVM. However, the issue can be easily fixed by adding an Optional tag and a default value.
> [Refactor] Improve TargetHasSVE function with optional target handling

- python/tvm/target/codegen.py
- python/tvm/testing/utils.py
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
- tests/python/codegen/test_target_codegen_riscv.py
- tests/python/target/test_riscv_features.py
This PR is an enhancement for #17631.
---
New functionality:
* This also parses optional 'zvlXXXb' attribute from ```-mattr``` arguments, if user would supply such.
Enhanchements:
* Separate ```GetVectorWidth()``` @LLVMTargetInfo a shared **public function**, reachable from python side too.
* A basic **codegen testcase** for riscv{32,64} targets is introduced, for now it checks RVV presence/absence.
* A target **parser testcase** for riscv{32,64} is also introduced, it checks sanity and VLEN relations.
---
This not alter any behavior except riscv targets.
This work here is a preliminary before enable TVM's SVE for riscv too.
> Pick up vector length from 'zvlXXXb' (RVV) mattr for riscv

- python/tvm/tir/__init__.py
- python/tvm/tir/build.py
- python/tvm/tir/pipeline.py
This PR enables target dependent default tir pipeline dispatch in tir.build().
> [REFACTOR] Allow target dependent default tir pipeline dispatch in tir.build()

- ci/scripts/github/github_tvmbot.py
This PR updates github tvmbot to remove the stale pipeline checks.
> [skip ci][CI] Update github tvmbot

- python/pyproject.toml
Fix #17667 
related link:
- https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
> [BugFix] Declare build backend for python package

- ci/jenkins/docker-images.ini
- ci/jenkins/unity_jenkinsfile.groovy
- docs/how_to/tutorials/e2e_opt_model.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_dynamo.py
- tests/python/relax/test_frontend_from_exported_program.py
Update the CI Docker images to the latest built versions, and the torch gpu is supposed to be installed on gpu container.
cc: @MasterJH5574 @tqchen @mshr-h
> [CI] update images to 20250225-035137-aeadc31c

- docker/install/ubuntu_install_python_package.sh
This is follow-up https://github.com/apache/tvm/pull/17643, the cpu and gpu dockers are actually using docker/install/ubuntu_install_python_package.sh.
> [Docker] Update ml_dtypes to 0.5.1+

- docs/how_to/tutorials/optimize_llm.py
- python/tvm/relax/__init__.py
- python/tvm/relax/backend/cuda/__init__.py
- python/tvm/relax/backend/cuda/flashinfer.py
- python/tvm/relax/frontend/nn/llm/kv_cache.py
- python/tvm/relax/frontend/nn/llm/tree_attn.py
- src/runtime/relax_vm/attn_backend.cc
- src/runtime/relax_vm/attn_backend.h
- src/runtime/relax_vm/attn_utils.h
- src/runtime/relax_vm/kv_state.cc
- src/runtime/relax_vm/kv_state.h
- src/runtime/relax_vm/paged_kv_cache.cc
- tests/python/relax/nvshmem/test_runtime_builtin_kv_cache_transfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_cpu.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_mla_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_tir.py
This PR consists of the following parts:
* We reorganized `paged_kv_cache.cc` by moving some of the utilities to `attn_utils.h`.
* To integrate with the JIT kernel compilation in the latest FlashInfer project, while still being able to support attention kernels written with TIR, we introduced `AttnBackendFunc` in `attn_backend.h`, which exposes attention interfaces (e.g., `MHA`, `MLA`) to PagedKVCache. We subclass `AttnBackendFunc` and implement FlashInfer backends and TIR backends respectively.
* With `AttnBackendFunc`, we refactored the PagedKVCache constructor. The new constructor is not backward compatible, and will break the existing compiled model libraries.
* For both TIR and FlashInfer attention implementations, now we require an explicit attention softmax scale factor `sm_scale` …
> [KVCache] PagedKVCache refactor, FlashInfer JIT and MLA integration

- src/relax/op/ccl/ccl.cc
The current code asserts that floormod(input_dims[0], num_shards) can not be proven to be true, which has two problems:
- It is unclear what it means to prove floormod(..). Prove that floormod's return value is truthy, i.e. non-zero?
- It always checks the 0th dimension of the input shape, but the dimension index to be sharded is given by the "axis" parameter.
This commit fixes both of the above.
> Fix relax.ccl.scatter_from_worker0 assert

- src/meta_schedule/profiler.cc
This PR fixes an include problem in profiler.cc, which uses namespace `std::chrono` without including the header. This leads to compilation failure on Windows platform.
> [Fix] Include `<chrono>` for `std::chrono`

- python/tvm/relax/frontend/nn/llm/tree_attn.py
Fix the compilation error(https://github.com/mlc-ai/mlc-llm/issues/3143) for Qwen2-1.5 models in the tree attention implementation for vulkan backend.
cc @spectrometerHBH @vinx13
> [relax] Fix tree attention for Qwen2-1.5 models

- python/tvm/relax/transform/transform.py
The c++ implementation of BindParams can accept tvm.relax.Constants, however the python interface assert only allows ndarrays. I added tvm.relax.Constant to the assert.
By allowing tvm.relax.Constants as input arguments to BindParams it is possible to avoid duplicating weights if there are several functions in the module that are using the same weight as an input parameter, such as prefill and decode in an LLM.
> updated the assert in BindParams to allow tvm.relax.Constant

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This pr supports Pytorch `celu`, `selu`, `is_floating_point` for Relax.
> [Relax][PyTorch] Add support for celu, selu, is_floating_point ops

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This pr supports Pytorch `gather`, `flip` and `take` for Relax.
> [Relax][PyTorch] Add support for gather, flip and take ops

- python/tvm/contrib/nvcc.py
- python/tvm/relax/vm_build.py
The sm_100 or larger will be parsed to 1.0.0, breaking some dependent passes. The expected major version should be 10.
ref: the GPU Compute Capability: https://developer.nvidia.com/cuda-gpus
cc: @MasterJH5574 @cyx-6
> Fix the get_target_compute_version for sm >= 100

- python/tvm/dlight/gpu/reduction.py
- tests/python/dlight/test_gpu_reduction.py
Added an explicit check in DLight Reduction to verify that the block has a reduction loop since this is assumed  in later stages.
> [Fix][dlight] add an explicit reduction loop check in Reduce

- include/tvm/runtime/object.h
This PR sets the dynamic index to the original value in past versions so we can have stable compatibility when we phase out static objects.
> [FFI] Fix dynamic FFI index to ensure compatibility

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This pr supports Pytorch `numel`, `empty_like` and `one_hot` for Relax.
> [Relax][PyTorch] Add support for numel, empty_like and one_hot ops

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
Implement Tensor.contiguous() as a no-op in the exported program translator and added a unit test
cc: @MasterJH5574
> [Relax] ingest Tensor.contiguous from torch export

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_from_exported_to_cuda.py
- tests/python/relax/test_frontend_from_exported_program.py
- Implement torch's vector_norm as a function of existing relax ops
- add a unit test
cc: @MasterJH5574
> [Relax] Allow ingesting vector_norm from torch.export

- apps/ios_rpc/tvmrpc/RPCServer.mm
- apps/ios_rpc/tvmrpc/TVMRuntime.mm
- docs/contribute/document.rst
- include/tvm/relax/expr_functor.h
- include/tvm/relax/op_attr_types.h
- include/tvm/relax/type.h
- include/tvm/tir/analysis.h
- include/tvm/tir/block_dependence_info.h
- include/tvm/tir/builtin.h
- include/tvm/tir/op.h
- web/emcc/tvmjs_support.cc
- web/emcc/wasm_runtime.cc
Fix typos in comments and strings
> Fix typos in comments and strings

- include/tvm/arith/iter_affine_map.h
- include/tvm/ir/expr.h
- include/tvm/ir/type_functor.h
- include/tvm/node/functor.h
- include/tvm/relax/dataflow_pattern.h
- include/tvm/relax/dataflow_pattern_functor.h
- include/tvm/relax/expr.h
- include/tvm/relax/expr_functor.h
- include/tvm/relax/struct_info_functor.h
- include/tvm/tir/expr_functor.h
- include/tvm/tir/stmt_functor.h
- src/ir/attr_functor.h
- src/relax/ir/py_expr_functor.cc
- src/runtime/object.cc
This PR add a finalize routine to optionally compact functor vtable dynamically. Also updates child_slots for key types to make sure the IR node type index stay within range and such compact happens based on `runtime.DumpTypeTable`
> [IR] Compact Functor vtable

- python/tvm/runtime/ndarray.py
- tests/python/codegen/test_target_codegen_llvm.py
Support ndarray.asnumpy() to bfloat16 tensor natively using ml_dtypes.
> [BF16] Support ndarray.asnumpy() to bfloat16 tensor natively using ml_dtypes

- python/tvm/runtime/ndarray.py
- src/target/source/codegen_cuda.cc
- src/target/source/literal/cuda_half_t.h
- tests/python/codegen/test_target_codegen_cuda_fp8.py
- tests/python/codegen/test_target_codegen_llvm.py
This PR fixes the CUDA code generation for fp8 (also fp4) and bfloat16. We added a few vector data conversion util functions.
> [Codegen][CUDA] Fix codegen of cast among vector bfloat16, fp8 and fp4

- python/tvm/relax/backend/cuda/flashinfer.py
- tests/python/relax/nvshmem/test_runtime_builtin_kv_cache_transfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_flashinfer.py
- tests/python/relax/test_runtime_builtin_paged_attention_kv_cache_mla_flashinfer.py
In this PR I have added support for caching the flash infer binaries during the JIT flow in TVM.
> [Attention] Added caching for flashinfer binaries during JIT

- src/target/source/codegen_c.cc
- src/target/source/literal/cuda_half_t.h
- src/tir/ir/expr_functor.cc
- src/tir/transforms/vectorize_loop.cc
- tests/python/codegen/test_target_codegen_cuda_fp4.py
This PR introduces the support for vectorized tir.ShuffleNode, which is useful for extracting bits and converting to float4, since float4 is sub-byte.
Prior to this PR, ShuffleNode is not supported in vectorization. This PR allows vectorizing ShuffleNode subject to special patterns, and still throws error for ShuffleNodes that don't meet the pattern requirements.
> [Codegen] Support codegen for vectorized tir.ShuffleNode

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This PR supports `one_hot`, `empty_like` ops for ExportedProgram importer and writes test for `select` op.
> [Relax][PyTorch] Support one_hot, empty_like ops for ExportedProgram importer

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports Pytorch `lerp`, `select` and `clone` ops for Relax
> [Relax][PyTorch] Add support for lerp, select and clone ops

- python/tvm/relax/transform/fuse_transpose_matmul.py
- tests/python/relax/test_transform_fuse_transpose_matmul.py
Applying the FuseTransposeMatmul pass on a matmul with a constant weight  would fail since the bind_constants defaults to true in the FuseOpsByPattern pass . This would lead the constant to be moved in to the fused function instead of being an input param, however on line 168 in /tvm/relax/transform/fuse_transpose_matmul.py
```pyhton
out_dtype = function.ret_struct_info.dtype
return self.builder_.call_te(
te_transposed_matmul,
call.args[1],
call.args[0],
primfunc_name_hint="NT_matmul",
)
```
, called later in the FuseTransposeMatmul pass, both input and weight are expected to be inputs to the fused function leading to a crash.
I fixed it by explicitly setting bind_constants to false and I added a unit test to verify correct behavior when the weight is a constant.
> [FIX][RELAX] fix fusion of transpose + matmul when constant  weight 

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This pr supports Pytorch `log2`, `log10` and `log1p` ops for Relax.
> [Relax][PyTorch] Add support for log2, log10 and log1p ops

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports Pytorch `prod`, `std` and `var` ops for Relax.
> [Relax][PyTorch] Add support for prod, std and var ops

- python/tvm/relax/frontend/torch/exported_program_translator.py
Ran into an example of a pytorch program for which a user input to the forward() function has a node matching (node.name == name_hint) but that node's meta dict does not have a "tensor_meta" key, hence the translation would crash. Let me know if you think this is worth adding a unit test.  
cc: @MasterJH5574
> [Relax] check for tensor_meta in exported_program_translator

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This pr supports `log2`, `log10` and `log1p` ops for ExportedProgram importer
> [Relax][PyTorch] Support log2, log10 and log1p ops for ExportedProgram importer

- include/tvm/tir/expr.h
- include/tvm/tir/expr_functor.h
- include/tvm/topi/detail/strided_slice.h
- python/tvm/contrib/msc/framework/tensorrt/transform/pattern.py
- python/tvm/contrib/msc/plugin/codegen/sources.py
- python/tvm/tir/__init__.py
- python/tvm/tir/expr.py
- python/tvm/topi/nn/pad.py
- python/tvm/topi/utils.py
- src/contrib/msc/core/utils.h
- src/script/printer/legacy_repr.cc
- src/script/printer/tir/expr.cc
- src/tir/analysis/deep_equal.cc
- src/tir/ir/expr.cc
- src/tir/ir/expr_functor.cc
- src/tir/ir/tir_visitor_with_path.cc
- src/tir/ir/tir_visitor_with_path.h
- tests/python/arith/test_arith_rewrite_simplify.py
- tests/python/tvmscript/test_tvmscript_printer_tir.py
This PR removes legacy tir::any which was used to represent unknown shape in relay. As we move toward first class symbolic shape, we no longer need the ? shape in the system.
> [REFACTOR][TIR] remove legacy tir::any

- 3rdparty/tensorrt_llm/custom_allreduce_kernels.cu
This PR enables the datatype bfloat16 for the 3rdparty custom allreduce kernel. Prior to this PR, bfloat16 was disabled by macro.
> [3rdparty] Enable bfloat16 for custom allreduce kernel

- python/tvm/relax/frontend/nn/op.py
- tests/python/relax/test_frontend_nn_op.py
This PR adds the min/max reduction operators to the relax nn frontend operators, which were missing before this PR.
> [Relax][Frontend] Support max/min in frontend op interface

- src/relax/op/nn/nn.cc
- tests/python/relax/test_op_nn.py
This PR supports inferring structure info for datatype bfloat16 in softmax/log-softmax operators.
> [Relax] Enable bfloat16 for softmax struct-info inference

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This pr supports `prod`, `std` and `var` ops  for ExportedProgram importer
> [Relax][PyTorch] Support prod, std and var ops for ExportedProgram importer

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports Pytorch `where`, `cumprod` and `reciprocal` ops for Relax.
> [Relax][PyTorch] Add support for where, cumprod and reciprocal ops

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
Added softshrink operator support in the TVM Relax exported program and test script code to validate the relax module.
> [Relax][PyTorch] Support softshrink op for ExportedProgram

- cmake/modules/contrib/CUTLASS.cmake
- src/runtime/contrib/cutlass/blockwise_scaled_gemm_runner.cuh
- src/runtime/contrib/cutlass/fp8_blockwise_scaled_gemm.cu
- src/runtime/contrib/cutlass/group_gemm_runner.cuh
- tests/python/contrib/test_cutlass_gemm.py
This PR introduces blockwise scale matmul and batch matmul CUTLASS kernels, adapted from SGLang (http://github.com/sgl-project/sglang), vLLM (https://github.com/vllm-project/vllm) and
https://github.com/soundOfDestiny/cutlass.
We add unit tests for gemm and bmm. This PR also restores some cutlass gemm tests that were removed before during Relay phasing out.
> [CUTLASS] Add blockwise scale gemm/bmm kernels

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This PR supports Pytorch `where`, `cumprod` and `reciprocal` ops for ExportedProgram importer
> [Relax][PyTorch] Support where, cumprod and reciprocal ops for ExportedProgram importer

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- python/tvm/relax/op/nn/__init__.py
- python/tvm/relax/op/nn/nn.py
- python/tvm/relax/transform/legalize_ops/nn.py
- src/relax/op/nn/nn.cc
- src/relax/op/nn/nn.h
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR refactors the SELU activation function to be implemented at the core level using decomposed operations. It allows SELU to be accessed directly via R.nn.selu, making it more efficient and easier to use in TVM models.
> [Relax][Pytorch] Update SELU Implementation Using Decomposed Core-Level Ops

- src/tir/analysis/buffer_access_lca_detector.cc
- tests/python/tir-analysis/test_tir_analysis_detect_buffer_access_lca.py
- tests/python/tir-transform/test_tir_transform_plan_update_buffer_allocation_location.py
The change modify lca detector to ensure the reduction buffer allocation position dominates all reduce related loops. This behavior is also compatible with same logic in `DecomposeReduction`.
Below is a working case with wrong cpu compile results. We just build a simple reduce-sum function, with outer tiling loops in order "SRS".
```python
import tvm
from tvm import tir, te, topi
x = te.placeholder(name="x", shape=[256, 256, 256], dtype="float32")
y = topi.sum(x, axis=1)
f = te.create_prim_func([x, y])
origin_mod = tvm.IRModule.from_expr(f)
s = tir.schedule.Schedule(f)
blk = s.get_child_blocks(s.get_block("root"))[-1]
i, j, k = s.get_loops(blk)
i0, i1 = s.split(i, factors=[4, 64])
j0, j1 = s.split(j, factors=[4, 64])
k0, k1 = s.split(k, factors=[4, 64])
s.reorder(i0, …
```
> [TIR] Fix reduce buffer allocation position

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
> [Relax][PyTorch] Fix torch 2.6 compatibility issues

- python/tvm/relax/frontend/torch/fx_translator.py
Follow-up PR for #17807 
Just forgot to delete `_to` function from the fx_translater
cc @Hzfengsy
> [Relax][PyTorch] Delete duplicate converter function `_to`

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports Pytorch `argsort`, `sort`, `topk` ops for Relax.
> [Relax][PyTorch] Add support for argsort, sort, topk ops

- src/runtime/relax_vm/rnn_state.cc
- src/tir/transforms/renew_defs.cc
- tests/python/tir-transform/test_tir_transform_simplify.py
This patch only corrects some `explict` typos. No changes visible to the user.
> [NFC] Fix `explict` typo

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This pr supports `argsort`, `topk` ops for ExportedProgram importer
> [Relax][PyTorch] Support argsort, topk ops for ExportedProgram importer

- python/tvm/relax/backend/cuda/flashinfer.py
- tests/python/relax/test_runtime_sampling_flashinfer.py
In this PR I have added jit support for sampling flashinfer kernel. I have also added a unit test to test the jit compiled flashinfer kernel.
> [Flashinfer] Added jit flow for sampling kernel

- python/tvm/relax/backend/cuda/cublas.py
- src/runtime/contrib/cublas/cublas.cc
- src/runtime/contrib/cublas/cublas_utils.h
- tests/python/relax/test_codegen_cublas.py
In this PR I have made changes so that we can support CUBLAS dispatch operations for bfloat16 data type.
> [Cublas] Added support for bfloat16 while dispatching to cublas kernels

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
As per title
cc @Hzfengsy @yongwww @tqchen
> [Relax][PyTorch] Support dynamic shapes in ExportedProgram frontend

- include/tvm/relax/attrs/nn.h
- python/tvm/relax/frontend/nn/op.py
- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- python/tvm/relax/op/nn/__init__.py
- python/tvm/relax/op/nn/nn.py
- python/tvm/relax/transform/legalize_ops/nn.py
- python/tvm/topi/nn/elemwise.py
- src/relax/op/nn/nn.cc
- src/relax/op/nn/nn.h
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
- tests/python/relax/test_frontend_nn_op.py
- tests/python/relax/test_op_nn.py
This PR adds support for the Softplus operation in both the Exported Program and FX graph Relax frontend pipeline.
> [Relax][PyTorch] Add Softplus Op Support for Exported Program and FX graph

- python/setup.py
- python/tvm/_ffi/libinfo.py
"pip install -e /path-to-tvm/python" successfully installs the TVM package as documented on https://tvm.apache.org/docs/install/from_source.html#
~~If "libtvm.so" and "libtvm_runtime.so" remain in "python/tvm" for some reason,~~
If a previous pip installation was unsuccessful and the cleanup was not performed, running "pip install -e /path-to-tvm/python" fails because shutil.copy() and shutil.copytree() raise exceptions due to the remaining temporary files.
I ran "pip install" without "sudo" first, and it failed without "sudo". (probably because I was not in a virtual environment)
Here the cleanup code couldn't be executed
```
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [21 lines of output]
Use git describe based version 0.20.dev125+g8ad9bffb1 …
```
> [Install] Fix error during python/tvm installation

- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
This PR fixes error handling in from_fx and from_exported_program to detect unsupported ops more effectively. Instead of stopping at the first missing op due to an assertion error, it now collects all missing function-type ops first, which helps identify all unsupported operations at once.
> [Relax] Fix Torch frontends to report all the missing ops

- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This pr supports `narrow` and `broadcast_to` ops for ExportedProgram importer
> [Relax][PyTorch] Support narrow and broadcast_to ops for ExportedProgram importer

- src/tir/schedule/primitive/compute_inline.cc
- tests/python/tir-schedule/test_tir_schedule_compute_inline.py
This PR fixes a bug in reverse-compute-inline of tir Schedule, which generates incorrect TIR after inlining a transpose block into a reduction block.
> [BugFix][TIR] Schedule support reverse-inline with reduction blocks

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
This PR refactors the logic for detecting unsupported ops by moving _check_unsupported_func_type into a shared utility in base_fx_graph_translator.py file. Previously, this logic was implemented separately in both from_fx and from_exported_program. By centralizing this function, we reduce duplication and ensure consistent missing op reporting across Torch frontends.
> [Relax] Refactor missing op check into shared utility for Torch frontends

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This PR adds support for the masked_fill operation in the Exported Program frontend, aligning it with the existing support in the FX graph. With this enhancement, models such as bert-base-uncased (Model type: QuestionAnswering) can now execute successfully.
> [Relax][Pytorch] Add masked_fill op support in ExportedProgram

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR adds support for the rsub operation in exported program and fx graph translator torch frontend. By adding this support, the following models are now able to run successfully:
| Model Type                       | Models                                                                 |
|-----------------------------|------------------------------------------------------------------------|
| **Text Generation**         | - gpt2<br>- facebook-opt 125M<br>- distillgpt2                        |
| **Question Answering**      | - bert-base-cased<br>- Indobert-QA                                    |
| **Summarisation**           | - text_summarisation                                                  |
| **Text Classification**     | - ProsusAI/finbert<br>- ms-marco-MiniLM-L6-v2<br>- …
> [Relax][PyTorch] Add RSub Op Support for Exported Program and FX graph

- include/tvm/runtime/data_type.h
- python/tvm/_ffi/runtime_ctypes.py
This PR bumps the 3rdparty dlpack version to v1.1, which brings the support of float8, float6 and float4.
> [3rdparty] Bump DLPack to v1.1 for float8/6/4 dtype supports

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- python/tvm/relax/op/nn/nn.py
- python/tvm/relax/transform/legalize_ops/nn.py
- python/tvm/topi/nn/pad.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR adds support for the pad operation in Relax with handling for all common padding modes (constant, reflect, replicate, and circular).  By adding this support, the following models are now able to run successfully:
1. facebook/mask2former-swin-tiny-coco-instance (Image Segmentation)
2. briaai/RMBG-2.0 (Background Removal)
3. Intel/dpt-hybrid-midas (Depth Estimation)
> [Relax][PyTorch] Add Pad Op Support for Exported Program and FX graph

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
Added roll operator support in the TVM Relax exported program and fx graph and test script code to validate the relax module.  By adding this support, the following models are now able to run successfully:
1. facebook/mask2former-swin-tiny-coco-instance
2. briaai/RMBG-2.0
> Add op support for roll op

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This pr supports `eye` op for ExportedProgram importer.
> [Relax][PyTorch] Support eye op for ExportedProgram importer

- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR adds support for the bitwise OR operation used in the Mistral/Mistral-3B-Instruct model.
> [Relax][Pytorch] Add support for bitwise_or op support

- python/tvm/relax/frontend/torch/fx_translator.py
This PR resolves #17874. Currently, only one in-place operation (bitwise_or_) is affected, and it has been remapped to use self._binary_op_inplace instead of self._binary_op. Going forward, any additional in-place operations (e.g., bitwise_and_, bitwise_xor_, etc.) should also be explicitly mapped to self._binary_op_inplace to ensure correct handling.
> [BugFix][Relax][Pytorch] Incorrect Handling of In-Place Ops in FX-Based TVM Frontend

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR adds support for the isin operation in exported program and fx graph translator torch frontend. By adding this support, the following models are now able to run successfully:
| Model Type             | Model Name                                                       |
|------------------------|------------------------------------------------------------------|
| Summarisation          | - text_summarisation                                               |
| Text Classification    | - ms-marco-MiniLM-L6-v2<br> - twitter-roberta-base-sentiment-latest     |
| Text2Text Generation   | - google/flan-t5-small                                             |
> [Relax][PyTorch] Add torch.isin Op Support for Exported Program and FX graph

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
> Fix onnx expand op

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
> [Relax][PyTorch] Support torch.bfloat16 dtype in pytorch frontend

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
> [Relax][FRONTEND][Pytorch] Add fmod support

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR adds support for the following operations in the exported program frontend for TVM Relax: zeros_like and fill_. By adding these ops the following models run successfully.
| Operation   | Supported Models |
|-------------|------------------|
| `zeros_like` | - mdeberta-v3-base <br> - ms-marco-MiniLM-L6-v2 <br> - grammar_error_correcter_v1 <br> - google/byt5-base <br> - google/flan-t5-small <br> - DeBERTa-v3-base-mnli-fever-anli <br> - Political_DEBATE_large_v1.0 <br> - microsoft/table-transformer-detection <br> - facebook/detr-resnet-50 <br> - facebook/mask2former-swin-tiny-coco-instance|
| `fill_`      | - microsoft/beit-base-patch16-224-pt22k-ft22k <br> - google-mt5/small |
> Add op support for zeros_like and fill_

- docker/install/ubuntu_install_onnx.sh
PyTorch 2.7 depends on CUDA 12.6 by default, so we explicitly install PyTorch compatible with CUDA 11.8.
#17891
cc @yongwww @Hzfengsy @MasterJH5574
> [CI] Install PyTorch 2.7 compatible with CUDA 11.8

- python/tvm/rpc/proxy.py
The network between our RPC proxy machine and RPC tracker is not very good, when the connect is broken, the RPC proxy will hang with the below error message.
```
RuntimeError: dictionary changed size during iteration
```
> [RPC] Fix Bug That Change Dict When Iterate The Keys

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
This PR adds support for the new_zeros operation in exported program and fx graph translator torch frontend. By adding this support, the following models are now able to run successfully:
1. grammar_error_correcter_v1
2. google/byt5-base
3. facebook/mask2former-swin-tiny-coco-instance
4. google/mt5-small
5. facebook/bart-large-cnn
6. Angel0J/distilbart-multi_news-12-6_2
> Add op support for new_zeros op in Exported Program and fx graph frontend

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports Pytorch `eye` op for Relax.
> [Relax][PyTorch] Add support for eye op in fx graph

- include/tvm/runtime/object.h
This PR fixes an off-by-one error in the type index range check within `Object::IsInstance()`, an example and steps to reproduce it are at Issue https://github.com/apache/tvm/issues/17901.
> [BugFix] Fix off-by-one error in the type index range check within Object::IsInstance()

- python/tvm/script/ir_builder/tir/triton.py
This PR updates the Triton JIT compilation so that it supports the latest `triton.compile` interface introduced in Triton 3.3.0.
> [Triton] Support latest `triton.compile` interface

- src/target/source/codegen_webgpu.cc
- src/target/source/codegen_webgpu.h
This PR overrides `PrintVecElemLoad()` and `PrintVecElemStore()` for the WebGPU backend.
Otherwise, we would generate things like `(QK_local[0i].s0)` for WebGPU, which is not a valid syntax in WGSL. Instead, we generate `(QK_local[0i][0])` after this PR. `QK_local` here is a `array<vec4<f32>, 1>`. 
This issue prevented WebLLM from generating the correct kernel after https://github.com/apache/tvm/pull/17748
> [WebGPU][CodeGen] Override PrintVecElemLoad and Store for WebGPU

- python/tvm/relax/frontend/torch/fx_translator.py
- tests/python/relax/test_frontend_from_fx.py
This PR supports Pytorch `linspace` op for Relax.
> [Relax][PyTorch] Add support for linspace op in fx graph

- ffi/scripts/benchmark_dlpack.py
- python/tvm/ffi/convert.py
- python/tvm/ffi/cython/function.pxi
- python/tvm/ffi/cython/ndarray.pxi
- tests/python/ffi/test_ndarray.py
This PR introduces autodlpack feature to the tvm ffi. When an ffi Function takes Tensor argument that conforms to DLPack it automatically imports into NDArray and pass as argument.
The feature will allow compiled function to directly take torch.Tensor as input argument without extra set of changes.
We also added a benchmark script to measure the overall ffi overhead. One thing to note is that there is still continuguous and alignment requirement that is needed by underlying DSL compiler, as of now we use a global value. So x.continugous is still needed before passing the argument if tranpose or other ops are performed.
> [FFI][FEAT] AutoDLPack for taking external tensor objects

- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
> [Relax][PyTorch] Add tests for all the dtypes supported in the PyTorch frontend

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- python/tvm/relax/frontend/torch/fx_translator.py
- python/tvm/relax/op/nn/nn.py
- tests/python/relax/test_frontend_from_exported_program.py
- tests/python/relax/test_frontend_from_fx.py
- tests/python/relax/test_op_nn_pooling.py
This PR adds support for avg_pool1d and avg_pool3d operations, extending the existing avg_pool2d functionality to handle 1D and 3D pooling. It includes the necessary mappings, and comprehensive tests for these new operations. Additionally, avgpool2d was refactored to match the result of pytorch implementation. By adding this support, the following models are now able to run successfully.
1. X3D
2. 3D ResNet
> [Relax][PyTorch] Add AvgPool 1D and 3D Op Support for Exported Program and FX graph

- ffi/include/tvm/ffi/any.h
- ffi/include/tvm/ffi/base_details.h
- ffi/include/tvm/ffi/container/container_details.h
- ffi/include/tvm/ffi/container/variant.h
- ffi/tests/cpp/test_any.cc
- ffi/tests/cpp/test_map.cc
- ffi/tests/cpp/test_variant.cc
This PR specializes Variant when all members are ObjectRef, in such case, Variant<V...> is backed by ObjectRef which saves the storage space of the Object.
> [FFI] Variant specialize for all ObjectRef

- ffi/include/tvm/ffi/c_api.h
- ffi/include/tvm/ffi/dtype.h
- ffi/include/tvm/ffi/error.h
- ffi/src/ffi/dtype.cc
- python/tvm/ffi/cython/base.pxi
- python/tvm/ffi/cython/dtype.pxi
- web/.eslintignore
- web/apps/node/example.js
- web/emcc/tvmjs_support.cc
- web/emcc/wasm_runtime.cc
- web/emcc/webgpu_runtime.cc
- web/package.json
- web/src/asyncify.ts
- web/src/ctypes.ts
- web/src/environment.ts
- web/src/memory.ts
- web/src/rpc_server.ts
- web/src/runtime.ts
- web/tests/node/test_ndarray.js
- web/tests/node/test_object.js
- web/tests/node/test_packed_func.js
- web/tests/python/webgpu_rpc_test.py
This PR refactors the web runtime to the new FFI protocol. Tested through rpc tests and local tests.
> [REFACTOR][FFI][Web] Upgrade Web Runtime to new FFI

- ffi/include/tvm/ffi/string.h
- src/target/llvm/intrin_rule_llvm.cc
Small tiny fixes  for the refactored FFI backend & LLVM math macros.
* FFI related compilation error:
```
{...}
In file included from tvm-0.20-build/tvm/ffi/include/tvm/ffi/container/array.h:29:
In file included from tvm-0.20-build/tvm/ffi/include/tvm/ffi/any.h:27:
tvm-0.20-build/tvm/ffi/include/tvm/ffi/string.h:214:10: error: field has incomplete type 'String'
214 |   String(nullptr_t) = delete;  // NOLINT(*)
{...}
clang-20.1.2-3.fc42.riscv64
```
* Inclusion fix for MSWIN (introduced @ https://github.com/apache/tvm/pull/17945):
```
intrin_rule_llvm.cc(185,48): error C2065: 'M_PI': undeclared identifier
```
> [FFI][LLVM] Fix compilation errors with clang20

- src/target/llvm/llvm_instance.cc
- src/target/llvm/llvm_module.cc
- tests/python/target/test_riscv_features.py
This fixes the issue described in https://github.com/apache/tvm/issues/17916
---
* Fall to a standard ORCJIT linker (from RTDyldLinker, introduced by MSWIN case), but still cope with COFF cases.
* Incorporates [#17853](https://github.com/apache/tvm/pull/17853#issuecomment-2816105844), that prior info also allows parser simplification, to just read all infos from LLVM side.
---
The basic **relax** demo now runs fine, tested with llvm = {19,20}:
```
$ git diff docs/get_started/tutorials/quick_start.py
{...}
-target = tvm.target.Target("llvm")
+target = tvm.target.Target("llvm -mattr=+m,+a,+f,+d,+zfh,+v,+c")
{...}
$ python3 docs/get_started/tutorials/quick_start.py
@I.ir_module
class Module:
@R.function
def forward(x: R.Tensor((1, 784), dtype="float32"), fc1_weight: R.Tensor((256, 784), …
```
> [LLVM] Fix JIT unknown reloc issue for case of RISCV

- src/arith/analyzer.cc
- src/arith/const_int_bound.cc
- src/arith/scalable_expression.cc
- src/arith/scalable_expression.h
- src/target/llvm/codegen_aarch64.cc
- src/tir/transforms/vectorize_loop.cc
- tests/python/arith/test_arith_simplify.py
- tests/python/codegen/test_target_codegen_aarch64.py
- tests/python/codegen/test_target_codegen_llvm_vla.py
- tests/python/tir-schedule/test_tir_schedule_split_fuse.py
- tests/python/tir-transform/test_tir_transform_vectorize.py
This PR enables VLA (Vector-Length-Agnostic / Variable-Length-Array) predication for RISCV targets.
---
New functionality:
* Enables existing SVE as generic VLA predication, extending the support done for ```aarch64``` to ```riscv{32,64}```
Changes:
* Vscale rage is now computed from arch specific vector_width (see [disscuss](https://github.com/apache/tvm/pull/16921#discussion_r1600048788)), adapting to any vector ISA
* Split SVE related test cases between **arch** specific {riscv, aarch64} and llvm VLA **generic** (common) ones
UPDATE:
* Changed terms to generic ```VLA``` for common or non AArch64 parts (```SVE``` remains ARM specific, ```RVV``` is riscv specific).
> [LLVM][Codegen] Enable SVE/VLA for RISCV targets

- src/tir/analysis/estimate_flops.cc
Fix https://github.com/apache/tvm/issues/17960.
This PR fixes a bug where MetaSchedule fails on kernels containing `tir.While` due to missing FLOP estimation. The patch adds conservative handling by:
+ Evaluating the loop condition and body once (since static iteration count is unknown)
+ Adding a TODO for future improvements with bounded loop analysis
This unblocks compilation while being transparent about limitations. Future work can enhance accuracy via loop analysis or annotations.
cc @Hzfengsy @tqchen @vinx13
> Fix basic FLOP estimation for WhileNode

- python/tvm/topi/math.py
Fix https://github.com/apache/tvm/issues/17952.
Since TVM's LLVM backend does not support sqrt for integer types (e.g., int16), we explicitly cast the input to float32 at the TOPI operator level before computing sqrt. This ensures compatibility with hardware-accelerated floating-point sqrt instructions.
cc @Hzfengsy @tqchen
> Fix sqrt/rsqrt Compatibility with Integer Data Types

- python/tvm/meta_schedule/cost_model/xgb_model.py
Before this PR, I encountered the following error when tuning a resnet_18 task:
`
/home/thais/Dev/tvm/python/tvm/meta_schedule/cost_model/xgb_model.py:543: RuntimeWarning: invalid value encountered in divide
[g.min_cost / g.costs for g in self.data.values()],
`
> Fix g.costs

- src/target/llvm/intrin_rule_llvm.cc
The PR is designed to support the operators asinh/acosh/atanh. Meanwhile, it can fix https://github.com/apache/tvm/issues/17967.
cc @Hzfengsy @tqchen @vinx13
> Add registion for the operator asinh, acosh, atanh in llvm

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- tests/python/relax/test_frontend_onnx.py
This PR resolves issue [#17899](https://github.com/apache/tvm/issues/17966) where an error occurs converting operator LayerNormalization.
According to the [ONNX documentation for the LayerNormalization operator (opset 17)](https://onnx.ai/onnx/operators/onnx__LayerNormalization.html), the operator accepts between 2 and 3 inputs:
- **X**: Input tensor to be normalized.
- **Scale**: Scale tensor.
- **B** (optional): Bias tensor.
This means that the bias input (B) is optional. The operator is designed to function correctly even when the bias is not provided.
This change updates the LayerNormalization converter to support ONNX models where the optional bias input is not provided. When bias is missing, an empty bias tensor is generated.
> [FRONTEND][ONNX] Make bias input optional in LayerNormalization

- jvm/README.md
- jvm/core/src/main/java/org/apache/tvm/Base.java
- jvm/core/src/main/java/org/apache/tvm/Device.java
- jvm/core/src/main/java/org/apache/tvm/Function.java
- jvm/core/src/main/java/org/apache/tvm/LibInfo.java
- jvm/core/src/main/java/org/apache/tvm/Module.java
- jvm/core/src/main/java/org/apache/tvm/NDArray.java
- jvm/core/src/main/java/org/apache/tvm/NDArrayBase.java
- jvm/core/src/main/java/org/apache/tvm/TVMObject.java
- jvm/core/src/main/java/org/apache/tvm/TVMValue.java
- jvm/core/src/main/java/org/apache/tvm/TVMValueBytes.java
- jvm/core/src/main/java/org/apache/tvm/TVMValueDouble.java
- jvm/core/src/main/java/org/apache/tvm/TVMValueHandle.java
- jvm/core/src/main/java/org/apache/tvm/TVMValueLong.java
- jvm/core/src/main/java/org/apache/tvm/TVMValueNull.java
- jvm/core/src/main/java/org/apache/tvm/TVMValueString.java
- jvm/core/src/main/java/org/apache/tvm/TypeIndex.java
- jvm/core/src/main/java/org/apache/tvm/rpc/Client.java
- jvm/core/src/main/java/org/apache/tvm/rpc/RPCSession.java
- jvm/core/src/test/java/org/apache/tvm/FunctionTest.java
- jvm/core/src/test/java/org/apache/tvm/ModuleTest.java
- jvm/core/src/test/java/org/apache/tvm/rpc/RPCTest.java
- jvm/core/src/test/scripts/prepare_test_libs.py
- jvm/native/linux-x86_64/pom.xml
- jvm/native/osx-x86_64/pom.xml
- jvm/native/src/main/native/jni_helper_func.h
- jvm/native/src/main/native/org_apache_tvm_native_c_api.cc
- tests/scripts/task_java_unittest.sh
This PR updates TVM4J to use the latest FFI
> [FFI][JVM] Upgrade tvm4j to latest FFI

- src/meta_schedule/feature_extractor/per_store_feature.cc
The patch gracefully handles zero-extent loops (like those from empty indices in `take()` ops) by returning `Evaluate(0)` in PerStoreFeature, preventing `CHECK(p < n_loops)` crashes.
This restores auto-tuning for empty-input edge cases while perfectly preserving existing feature extraction for normal loops.
Fix https://github.com/apache/tvm/issues/17994
cc @Hzfengsy @tqchen @vinx13 @MasterJH5574
> Fix zero-extent loops in PerStoreFeature to prevent crashes

- src/target/spirv/intrin_rule_spirv.cc
- tests/python/codegen/test_target_codegen_vulkan.py
This change adds SPIR-V builtin intrinsic definitions for several trigonometric and hyperbolic operations that were previously unimplemented.
> [Vulkan] Add TIR unary trigonometric/hyperbolic intrinsic definitions

- include/tvm/topi/nn/pooling.h
- tests/python/te/test_te_create_primfunc.py
This PR fixes an issue where pooling window size calculations incorrectly used the input dtype, which could lead to:
- Division truncation artifacts with small integer types (e.g., int8)
- Potential divide-by-zero errors in certain cases
The fix ensures proper window size calculation independent of input type and fixed #17938. In addition, I also added a CI test.
> Fix division truncation in window size calculation for small dtypes in average_pool

- python/tvm/topi/math.py
Adds support for integer inputs in topi.log10 by automatically converting them to float32, aligning with NumPy's implicit float promotion behavior.
Fix https://github.com/apache/tvm/issues/17996
cc @Hzfengsy @masahi @yongwww @tqchen
> [TOPI] Support integer type input for log10

- ffi/include/tvm/ffi/container/container_details.h
- ffi/include/tvm/ffi/container/tuple.h
- ffi/tests/cpp/test_tuple.cc
This PR fixes a case where tuple constructor mismatches during vector forwarding. In this case UType&& was mistakenly matched and used. A testcase is added.
> [FFI] More strict tuple constructor checking

- python/tvm/libinfo.py
This PR fixes the library lookup path for tvm installed via pip.
> [Python] Fix library lookup path for pip installed packages

- src/arith/canonical_simplify.cc
- src/runtime/pack_args.h
- tests/python/arith/test_arith_canonical_simplify.py
- tests/python/dlight/test_gpu_low_batch_gemv.py
- tests/python/dlight/test_gpu_matmul.py
Fix a bug in canonical simplification of less-than expressions where the algorithm incorrectly assumed variables could have negative values when simplifying expressions of the form `ax + b < c`.
The previous implementation checked if `-d < xn < d` before simplifying, but this was incorrect when variables are constrained to non-negative ranges. For example, with constraints `0 < x, y < 2` and expression `2x + y < 8`, the algorithm would incorrectly check if `-2 < y < 2` and then simplify to `x < 4`. However, when x=4 and y=-1, we get 2*4 + (-1) = 7 < 8, which satisfies the original constraint but violates the intended variable bounds.
The fix changes the range check to `0 <= xn < d`, ensuring that simplification only occurs when variables are properly bounded from below at zero.
> [ARITH] Fix canonical simplify for LE with incorrect range assumptions

- python/tvm/topi/transform.py
Fix https://github.com/apache/tvm/issues/17947
This PR fixes an index calculation bug in `topi.expand_like` where incorrect indexing could lead to out-of-bounds access when expanding along specified axes.
If `a.shape[src_dim] == 1`, we use `indice=0` because broadcasting rules require replicating the single value across the expanded dimension, and indexing with 0 ensures correct behavior without bounds violations.
> [TOPI] Fix index handling in expand_like operator for axis expansion

- python/tvm/topi/utils.py
Fix https://github.com/apache/tvm/issues/17847.
As described in https://github.com/apache/tvm/issues/17847, the current topi.nn.simplify function incorrectly reuses input buffer names when simplifying `te.Tensor`, causing IR generation conflicts in storage_rewrite.
This PR modifies simplify to explicitly handle `te.Tensor` inputs by generating a new output tensor (avoiding buffer aliasing), while preserving the original behavior for PrimExpr and scalar inputs.
cc @tqchen @Hzfengsy @vinx13
> Fix IR generation conflict in topi.nn.simplify by separating Tensor and PrimExpr handling

- src/target/llvm/intrin_rule_llvm.cc
- tests/python/tir-base/test_tir_intrin.py
This PR resolves issue [#17965](https://github.com/apache/tvm/issues/17965) where the same model produces different outputs on the LLVM (CPU) and CUDA (GPU) backends.<br>
The problem lies with inverse trigonometric functions and `MaxPool` ops in this issue.
Two root causes were identified and addressed:
1. **Missing `asin` domain check**
The Taylor-series approximation of `asin` did not validate its input domain, allowing values outside [-1, 1] to silently produce numeric results.
- **Fix:**  Updated `tir.asin` to return quiet-NaN if the input is outside of [-1, 1].
2. **LLVM backend and CUDA backend follow different NaN policies for float `max`/`min`**
- **LLVM:** propagates NaNs (if any operand is NaN, the result is NaN)
- **CUDA:** treats NaN as missing data as described in the [CUDA …
> [Codegen] Resolve issue #17965 where the same model produces different outputs on the LLVM (CPU) and CUDA (GPU) backends

- src/target/source/codegen_cuda.cc
As titled, a newer PR to perform rerun on update-to-date setting from apache/tvm#17530, co-authored with @SerodioJ.
> [BugFix][CUDA] Fix: Update settings for rerun on Increase FloatImm precision when printing 64 bit values in CUDA codegen

- CMakeLists.txt
- ffi/cmake/Utils/Library.cmake
- src/runtime/metal/metal_module.mm
This PR fixes a bug in `MetalModuleNode::GetFunction`.
The lambda passed to autoreleasepool is supposed to return nothing. Prior to this PR, it returns a function at an early exit branch, which may cause the error of `EXC_BREAKPOINT` in Metal.
> [Metal] Fix `GetFunction` of metal runtime

- python/tvm/relax/op/nn/__init__.py
- python/tvm/relax/op/nn/nn.py
Given suggestions from Dr. Chen in #17883 , some commits are withdrawn. And #17486  is solved.
> Resolving inconsistency between attention/attention_bias

- python/tvm/contrib/utils.py
- tests/python/codegen/test_target_codegen_llvm.py
- tests/python/relax/test_transform_codegen_pass.py
- tests/python/relax/test_vm_build.py
This PR refactors some pytests so the temp files always go into tempdir
> [TEST] Move temp files into tempdir

- ffi/include/tvm/ffi/c_api.h
- ffi/include/tvm/ffi/function.h
- ffi/include/tvm/ffi/object.h
- ffi/include/tvm/ffi/reflection/reflection.h
- ffi/include/tvm/ffi/string.h
- ffi/include/tvm/ffi/type_traits.h
- ffi/src/ffi/object.cc
- ffi/tests/cpp/test_any.cc
- ffi/tests/cpp/test_array.cc
- ffi/tests/cpp/test_reflection.cc
- ffi/tests/cpp/test_tuple.cc
- ffi/tests/cpp/test_variant.cc
- ffi/tests/cpp/testing_object.h
This PR enhances and refactors the reflection module to support nanobind/pybind style reflection definition.
This is one step to upgrade the overall reflection mechanism in the project.
> [FFI][REFACTOR] Enhance reflection

- ffi/CMakeLists.txt
- ffi/include/tvm/ffi/base_details.h
- ffi/include/tvm/ffi/c_api.h
- ffi/include/tvm/ffi/cast.h
- ffi/include/tvm/ffi/function.h
- ffi/include/tvm/ffi/optional.h
- ffi/include/tvm/ffi/reflection/reflection.h
- ffi/include/tvm/ffi/type_traits.h
- ffi/src/ffi/error.cc
- ffi/src/ffi/function.cc
- ffi/src/ffi/object.cc
- ffi/src/ffi/traceback.cc
- ffi/src/ffi/traceback.h
- ffi/tests/cpp/test_reflection.cc
- src/runtime/library_module.cc
- src/runtime/thread_pool.cc
- src/target/llvm/codegen_cpu.cc
- src/target/llvm/codegen_cpu.h
- src/target/source/codegen_c_host.cc
- web/src/ctypes.ts
- web/src/runtime.ts
This PR updates the FFI type registry structures and API to be future compatible to reflection needs.
- Introduce TVM_FFI_STATIC_INIT_BLOCK for all registration purposes.
- Updates the MethodInfo and FieldInfo to contain complete ABI information.
- Removes the dependency on unordered_map in the registry.
- Updates TVMFFIErrorSetRaisedByCStr to TVMFFIErrorSetRaisedFromCStr to be more idiomatic
> [FFI][REFACTOR] Update registry to have complete meta-data

- python/tvm/relax/expr_functor.py
- python/tvm/runtime/support.py
- python/tvm/tir/__init__.py
- python/tvm/tir/functor.py
- src/tir/analysis/buffer_access_lca_detector.cc
- src/tir/ir/py_functor.cc
- tests/python/tir-transform/test_tir_functor.py
This commit introduces Python interfaces for TIR functors, enabling Python-side customization of expression and statement visiting and mutation operations.
Key changes:
- Add PyStmtExprVisitorNode and PyStmtExprMutatorNode classes in C++
- Implement Python bindings for all TIR expression and statement types
- Support both visitor (read-only) and mutator (transforming) patterns
- Add comprehensive dispatch mechanisms for Python callbacks
- Include FFI registrations for Python-C++ interoperability
This enables users to write custom TIR transformations and analysis passes directly in Python while maintaining performance through selective Python callback dispatch.
> Add Python functor support for TIR expressions and statements

- src/runtime/contrib/cutlass/fp16_group_gemm_runner_sm90.cuh
- src/runtime/contrib/cutlass/fp16_group_gemm_sm90.cu
- src/runtime/contrib/cutlass/fp8_group_gemm_sm90.cu
The cutlass kernel build on Hopper GPU was broken since #18033. This PR fixes the issue.
> [CUTLASS] Fix CUTLASS kernel build on Hopper

- python/tvm/tir/op.py
- tests/python/tvmscript/test_tvmscript_roundtrip.py
This commit enhances the address_of function to accept both Buffer and BufferLoad objects. When a Buffer is passed, it automatically creates a BufferLoad with zero indices to get the base address.
> [TIR] Extend address_of to support Buffer objects

- ffi/include/tvm/ffi/memory.h
- ffi/include/tvm/ffi/reflection/reflection.h
- ffi/include/tvm/ffi/string.h
- ffi/src/ffi/object.cc
- ffi/src/ffi/testing.cc
- ffi/tests/cpp/test_reflection.cc
- python/tvm/ffi/__init__.py
- python/tvm/ffi/cython/base.pxi
- python/tvm/ffi/cython/error.pxi
- python/tvm/ffi/cython/function.pxi
- python/tvm/ffi/cython/ndarray.pxi
- python/tvm/ffi/registry.py
- python/tvm/ffi/testing.py
- tests/python/ffi/test_object.py
This PR brings up new reflection support in python. The new reflection now directly attaches property
and methods to the class object themselves, making more efficient accessing than old mechanism.
It will also support broader set of value types
that are compatible with the FFI system.
For now the old mechanism and new mechanism will co-exist, and we will phase out old mechanism as we migrate most needed features into new one.
> [FFI] Introduce FFI reflection support in python

- .github/workflows/main.yml
- conda/recipe/bld.bat
Updates the windows ci to 2025 since windows-2019 runner will be phased out
> [CI] Update windows to 2025

- src/runtime/contrib/nvshmem/memory_allocator.cc
This PR updates the NVSHMEM-based NDArray allocation, which was missed in the recent FFI refactor and thus fails to compile when building tvm with NVSHMEM.
> [NVSHMEM] Update NDArray allocation

- ffi/include/tvm/ffi/base_details.h
- ffi/include/tvm/ffi/object.h
This PR optimizations the atomic decref in Object so it only do release instead of release acquire. Acquire is only needed for deleter.
> [FFI] Optimize atomic decref in Object

- ffi/include/tvm/ffi/container/array.h
- ffi/include/tvm/ffi/container/map.h
- ffi/include/tvm/ffi/container/tuple.h
This PR stabliizes the container ABI and implementation.
- Introduce data field so both MapObj/ArrayObj can be future compact with mutable container
- Make sure the data delete behavior in DenseMap is cross shared lib safe
We also updated DenseMap impl so that n_slots now directly corresponds to number of slots instead of n_slots - 1, the implementation also no longer depend on slots is power of two.
> [FFI][REFACTOR] Stablize container ABI and implementation

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
closes https://github.com/apache/tvm/issues/18070
Added Softsign  operator support in the TVM Relax exported program and test script code to validate the relax module.
> add support for softsign op

- ffi/include/tvm/ffi/reflection/reflection.h
- include/tvm/ir/attrs.h
- include/tvm/relax/attrs/ccl.h
- src/contrib/msc/core/ir/graph_builder.cc
- src/contrib/msc/core/ir/graph_builder.h
- src/node/reflection.cc
- src/node/serialization.cc
- src/node/structural_equal.cc
- src/relax/backend/contrib/codegen_json/codegen_json.h
- src/relax/op/ccl/ccl.cc
- src/script/printer/ir_docsifier.cc
- src/script/printer/relax/call.cc
- src/support/ffi_testing.cc
- tests/python/ir/test_ir_attrs.py
This PR provides functions that adapts old VisitAttrs reflection utilities to use new reflection mechanism when available.
These adapter would allow us to gradually transition the object def from old VisitAttrs based mechanism to new mechanism.
- For all objects
- Replace VisitAttrs with static void RegisterReflection() that registers the fields
- Call T::ReflectionDef() in TVM_STATIC_INIT_BLOCK in cc file
- For subclass of AttrsNode<T>: subclass AttrsNodeReflAdapter<T> instead
- Do the same steps as above and replace TVM_ATTRS
- Provide explicit declaration of _type_key and TVM_FFI_DEFINE_FINAL_OBJECT_INFO
We will send followup PRs to do the gradual transition. Once all transition is completed, we will remove AttrsVisitor and only go through the new mechanism.
> [FFI] Provide Field Visit bridge so we can do gradual transition

- src/meta_schedule/postproc/verify_gpu_code.cc
> [Fix] Replace dmlc::Error with std::exception in VerifyGPUCode

- ffi/include/tvm/ffi/reflection/reflection.h
- ffi/src/ffi/container.cc
- ffi/src/ffi/function.cc
- ffi/src/ffi/ndarray.cc
- ffi/src/ffi/object.cc
- ffi/src/ffi/testing.cc
- ffi/tests/cpp/test_function.cc
- ffi/tests/cpp/test_reflection.cc
This PR introduces reflection::GlobalDef for function registration, which makes the global function registration API more closely aligned with the new reflection style.
We will send followup PRs to transition some of the existing mechanisms to the new one.
> [FFI] Introduce GlobalDef for function registration

- ffi/include/tvm/ffi/base_details.h
Currently the `for_each` is implemented recursively, we can replace it by fold expression to make it more simple : )
> [FFI] Use fold expression to simplify for_each

- src/target/llvm/codegen_llvm.cc
This PR fixes the codegen llvm version requirement. Prior to this PR, we use `dbg_info_->di_builder_->insertDeclare` when LLVM version is at least 19.0, while the new `insertDeclare` interface starts with LLVM 20:
* 19.1.0: https://github.com/llvm/llvm-project/blob/llvmorg-19.1.0/llvm/include/llvm/IR/DIBuilder.h#L95-L98
* 20.1.0: https://github.com/llvm/llvm-project/blob/llvmorg-20.1.0/llvm/include/llvm/IR/DIBuilder.h#L950-L952
As a result, we may run into the following compilation error if the LLVM version happens to be 19:
```
/home/ruihangl/Workspace/tvm/src/target/llvm/codegen_llvm.cc:2251:42: error: no matching function for call to 'llvm::DIBuilder::insertDeclare(llvm::AllocaInst*&, llvm::DILocalVariable*&, llvm::DIExpression*, llvm::DebugLoc, llvm::BasicBlock::iterator)'
2251 | …
```
> [Codegen] Update LLVM version requirement for `insertDeclare`

- python/tvm/relax/frontend/nn/llm/kv_cache.py
This PR fixes a few kernel dispatch issues due to the recent introduction of `mha_sliding` as a new attention kind.
Tested on Qwen3 1.7B with MLC-LLM.
> [KVCache] Fix kernel dispatch based on attention kinds

- src/relax/analysis/graph_partitioner.cc
- src/relax/ir/expr.cc
- src/relax/op/nn/attention.cc
- src/relax/op/nn/convolution.cc
- src/relax/op/nn/nn.cc
- src/relax/op/tensor/grad.cc
- src/relax/transform/convert_layout.cc
- src/relax/transform/fuse_tir.cc
- src/relax/transform/legalize_ops.cc
- src/relax/transform/remove_purity_checking.cc
- src/relax/transform/to_mixed_precision.cc
- src/script/printer/relax/function.cc
- src/script/printer/tir/function.cc
- src/tir/ir/data_type_rewriter.cc
- src/tir/schedule/primitive/cache_read_write.cc
- src/tir/schedule/primitive/compute_inline.cc
- src/tir/schedule/primitive/loop_transformation.cc
- src/tir/transforms/profile_instrumentation.cc
Fix compilation warnings of "moving a temporary object prevents copy elision"
> [MISC] Fix compilation warnings of unnecessary `std::move()` calls

- python/tvm/ffi/cython/base.pxi
- python/tvm/ffi/cython/error.pxi
- python/tvm/ffi/error.py
This PR improves the traceback generation in python by bringing a more precise caching of the code object
> [FFI][PYTHON] Improve the traceback generation in python

- python/tvm/relax/frontend/onnx/onnx_frontend.py
- python/tvm/relax/op/image/image.py
- tests/python/relax/test_frontend_onnx.py
This PR fixes https://github.com/apache/tvm/issues/18133 (constant ROI handling in resize2d):
- Add support for Constant ROI input by converting to numpy array
- Improve type checking with explicit error for unsupported dynamic ROI
- Add proper error messaging:
- Clear NotImplementedError for unsupported ROI types
- Explicit dynamic ROI limitation notice
> [Fix][ONNX] Fixed constant ROI handling in resize2d when loading onnx models

- tests/python/relax/test_frontend_onnx.py
This PR replaces the hardcoded [0.0, 0.0, 0.0, 0.0] values with the roi_list variable when creating the ROI tensor, addressing an issue from the previous PR (https://github.com/apache/tvm/pull/18138) where the ROI values weren't properly configurable.
> [Test] Use roi_list variable instead of hardcoded values in ROI tensor creation

- src/relax/backend/contrib/nnapi/codegen.cc
- tests/python/nightly/test_nnapi/test_ops.py
This PR includes two small fixes for the Relax NNAPI backend introduced in PR #17385:
1. Fix a type mismatch in `NNAPICompiler` by casting `tvm::ffi::Any` to `tvm::runtime::Module`.
2. Correct a mismatched annotation in the Relax IR used in `test_mean`.
Verified locally with successful compilation and test run.
Co-authored-by: HMZ <mzhuang@pllab.cs.nthu.edu.tw>
> [BugFix][NNAPI] Fix type mismatch and test_mean annotation

- ffi/CMakeLists.txt
- ffi/include/tvm/ffi/c_api.h
- ffi/include/tvm/ffi/object.h
- ffi/include/tvm/ffi/reflection/access_path.h
- ffi/include/tvm/ffi/reflection/registry.h
- ffi/include/tvm/ffi/reflection/structural_equal.h
- ffi/include/tvm/ffi/reflection/structural_hash.h
- ffi/include/tvm/ffi/string.h
- ffi/src/ffi/container.cc
- ffi/src/ffi/reflection/access_path.cc
- ffi/src/ffi/reflection/structural_equal.cc
- ffi/src/ffi/reflection/structural_hash.cc
- ffi/tests/cpp/test_reflection_accessor.cc
- ffi/tests/cpp/test_reflection_structural_equal_hash.cc
- ffi/tests/cpp/testing_object.h
This PR add initial support for structural equal and hash via the new reflection mechanism.
It will helps us to streamline the structural equality/hash with broader support and clean error reports via AccessPath. It also gives us ability to unify all struct equal/hash registration into the extra meta-data in reflection registration.
> [FFI] Structural equal and hash based on reflection

- ffi/include/tvm/ffi/c_api.h
- ffi/include/tvm/ffi/reflection/accessor.h
- ffi/include/tvm/ffi/reflection/registry.h
- ffi/src/ffi/object.cc
- ffi/src/ffi/reflection/structural_equal.cc
- ffi/src/ffi/reflection/structural_hash.cc
- ffi/tests/cpp/test_reflection_accessor.cc
- ffi/tests/cpp/testing_object.h
- python/tvm/ffi/cython/base.pxi
- src/contrib/msc/core/ir/graph_builder.h
- src/node/reflection.cc
- src/node/serialization.cc
- src/relax/backend/contrib/codegen_json/codegen_json.h
- src/script/printer/ir_docsifier.cc
- src/script/printer/relax/call.cc
This PR introduces TypeAttr to reflection to bring extra optional attribute registration that can be used to extend behaviors such as structural equality. Also renames TypeExtraInfo to TypeMetadata for better clarity.
> [FFI][REFACTOR] Introduce TypeAttr in reflection

- web/src/runtime.ts
This PR fixes the tvmjs parts incompatible with the recent FFI updates.
Due to recent FFI updates, some existing functions are not present or have been replaced.
In the case of tvmjs, some changes are not reflected, which causes errors when trying to use wasm and js files built via the newer tvm.
Therefore, changes to this PR are required.
> [Web] Fix incompatible part after FFI updates

- ffi/include/tvm/ffi/any.h
- ffi/include/tvm/ffi/base_details.h
- ffi/include/tvm/ffi/string.h
- ffi/tests/cpp/test_string.cc
This PR improves the string equal hash handling
by improving some of the efficiencies.
> [FFI] Improve string equal/hash handling

- ffi/CMakeLists.txt
- ffi/include/tvm/ffi/c_api.h
- ffi/include/tvm/ffi/extra/base.h
- ffi/include/tvm/ffi/extra/structural_equal.h
- ffi/include/tvm/ffi/extra/structural_hash.h
- ffi/include/tvm/ffi/reflection/access_path.h
- ffi/src/ffi/extra/structural_equal.cc
- ffi/src/ffi/extra/structural_hash.cc
- ffi/tests/cpp/extra/test_structural_equal_hash.cc
- src/meta_schedule/module_equality.cc
- src/node/structural_equal.cc
- src/node/structural_hash.cc
- src/relax/ir/block_builder.cc
- src/relax/transform/lift_transform_params.cc
This PR formalizes the extra API in FFI. The extra APIs are minimal set of APIs that are not required in core mechanism, but still helpful.
Move structural equal/hash to extra API.
> [FFI][REFACTOR] Isolate out extra API

- ffi/include/tvm/ffi/container/map.h
- ffi/tests/cpp/test_map.cc
This PR fixes Small map init when there are duplicated keys
> [FFI] Fix SmallMapInit with duplicated keys

- src/relax/transform/fuse_ops.cc
This pr fix the wrong check for tuple node in #18163
> [Fix] Fix the wrong check for tuple node in #18163

- include/tvm/relax/nested_msg.h
- tests/cpp/nested_msg_test.cc
This PR upgrades NestedMsg<T> to use the new ffi::Any mechanism, which will enable us to get better support and enable NestedMsg for POD types.
> [REFACTOR] Upgrade NestedMsg<T> to use new ffi::Any mechanism

- ffi/CMakeLists.txt
- ffi/include/tvm/ffi/extra/json.h
- ffi/src/ffi/extra/json_parser.cc
- ffi/src/ffi/extra/json_writer.cc
- ffi/tests/cpp/extra/test_json_parser.cc
- ffi/tests/cpp/extra/test_json_writer.cc
This PR adds a lightweight json parser/writer to extra component.
> [FFI] Lightweight json parser/writer

- ffi/CMakeLists.txt
- ffi/include/tvm/ffi/extra/base64.h
- ffi/include/tvm/ffi/extra/json.h
- ffi/include/tvm/ffi/extra/serialization.h
- ffi/src/ffi/extra/serialization.cc
- ffi/tests/cpp/extra/test_serialization.cc
- ffi/tests/cpp/extra/test_structural_equal_hash.cc
- ffi/tests/cpp/testing_object.h
This PR implements serialization function for generic ffi::Any based on the reflection that is preserves the overall object graph reference relation. These extra APIs are implemented through the reflection system.
They can be used to further modernize and unify the serialization mechanisms in the project.
> [FFI][EXTRA] Serialization To/From JSONGraph

- docs/reference/api/python/relax/op.rst
- docs/reference/api/python/tir/transform.rst
- ffi/src/ffi/extra/serialization.cc
- include/tvm/relax/attrs/op.h
- include/tvm/script/printer/doc.h
- python/tvm/arith/iter_affine_map.py
- python/tvm/contrib/msc/core/ir/graph.py
- python/tvm/ffi/__init__.py
- python/tvm/ffi/cython/function.pxi
- python/tvm/ffi/cython/object.pxi
- python/tvm/ffi/serialization.py
- python/tvm/ir/attrs.py
- python/tvm/relax/dpl/pattern.py
- python/tvm/relax/expr.py
- python/tvm/relax/op/_op_gradient.py
- python/tvm/relax/op/manipulate.py
- python/tvm/relax/op/op_attrs.py
- python/tvm/runtime/object.py
- python/tvm/script/printer/doc.py
- python/tvm/te/tensor.py
- python/tvm/testing/__init__.py
- python/tvm/testing/attrs.py
- python/tvm/tir/transform/transform.py
- src/node/reflection.cc
- src/relax/ir/emit_te.h
- src/tir/transforms/hoist_expression.cc
- tests/python/ffi/test_container.py
- tests/python/ir/test_ir_attrs.py
- tests/python/relax/test_transform_legalize_ops_manipulate.py
- tests/python/runtime/test_runtime_rpc.py
This PR phases out getattar based attribute handling as they are slower and introduces extra code path.
This does mean that if an Object is not explicitly registered in python side, we will no longer be able to access the field by name. Likely this is also desirable as we would like to enable faster use that updates the python end and do not rely on these behavior.
> [FFI][REFACTOR] Phase out getattr based attribute handling

- python/tvm/relax/frontend/onnx/onnx_frontend.py
> The `resize2d` operator in Relax already covers the functionality, so there’s no need to introduce a dedicated upsampling op at the Relax level.
1. Model-wise, only YOLO v3 Tiny currently uses this op, and I haven’t seen any other models that require it. The op originates from Darknet.
2. although it becomes an ONNX `Upsample` op during conversion, the node name still ends with `/resize`.
From ONNX version 10 onward, the `Upsample` op is no longer supported (`This version of the operator has been deprecated since version 10`. ref: https://onnx.ai/onnx/operators/onnx__Upsample.html)
3. `resize2d` provides a superset of `upsample` (2-D) capabilities, and end-to-end model results are correct, so `resize2d` fully covers the need. 
4. During ONNX-to-Relay conversion, the old frontend maps …
> [Relax][ONNX] Parse ONNX Upsample to Relax resize2d

- ffi/include/tvm/ffi/any.h
- ffi/include/tvm/ffi/cast.h
- ffi/tests/cpp/test_string.cc
- include/tvm/node/cast.h
- include/tvm/node/node.h
- include/tvm/runtime/disco/session.h
- include/tvm/runtime/object.h
- include/tvm/runtime/vm/vm.h
- src/node/container_printing.cc
- src/node/repr_printer.cc
- src/runtime/profiling.cc
- src/runtime/vm/attn_backend.cc
- src/runtime/vm/cuda/cuda_graph_builtin.cc
- src/runtime/vm/vm.cc
- src/target/source/codegen_metal.cc
- src/tir/transforms/memhammer_coalesce.cc
Downcast was added for backward compact reasons and it have duplicated features as Any.cast. This PR moves it out of ffi to node for now so the ffi part contains minimal set of implementations.
> [FFI][REFACTOR] Move Downcast out of ffi for now

- ffi/include/tvm/ffi/container/map.h
This PR updates the Map ABI to use MSB in slots_ to indicate SmallMap. The change would open doors for future changes to small map boundary switch.
> [FFI][REFACTOR] Update Map ABI to enable flexible smallMap switch

- python/tvm/contrib/cutlass/conv2d_operation.py
- python/tvm/contrib/cutlass/gemm_operation.py
- src/relax/backend/contrib/codegen_c/codegen_c.h
- src/relax/backend/contrib/cutlass/codegen.cc
Seems the migration from TVMValue to PackedArgs/AnyView missed the codegen part when I tried to test relax cutlass.
With this fix, now the codegened cutlass .cu can pass nvcc compile.
BTW, the relax/cutlass part has not been guarded by CI?
> [Fix] Codegen fix for relax cutlass

- tests/cpp/target/parsers/aprofile_test.cc
- tests/cpp/tir_scalable_datatype.cc
This PR updates **cpptest** to run on LLVM >= 20.
It also fixes [issue#17823](https://github.com/apache/tvm/issues/17823), and checks [pr#18182](https://github.com/apache/tvm/pull/18182) .
> [LLVM][CPPTEST] Small fixes for LLVM >= 20

- include/tvm/tir/builtin.h
- include/tvm/tir/stmt.h
- python/tvm/tir/tensor_intrin/arm_cpu.py
- python/tvm/tir/tensor_intrin/hexagon.py
- python/tvm/tir/tensor_intrin/rocm.py
- python/tvm/tir/tensor_intrin/x86.py
- src/target/llvm/codegen_arm.cc
- src/target/llvm/codegen_llvm.cc
- src/target/llvm/intrin_rule_llvm.cc
- src/target/llvm/intrin_rule_llvm.h
- src/target/llvm/llvm_instance.h
- src/target/llvm/llvm_module.cc
- src/tir/transforms/vectorize_loop.cc
- tests/python/codegen/test_target_codegen_llvm.py
- tests/python/contrib/test_hexagon/test_async_dma_pipeline.py
- tests/python/contrib/test_hexagon/test_meta_schedule.py
- tests/python/contrib/test_hexagon/test_parallel_hvx.py
- tests/python/contrib/test_hexagon/test_parallel_hvx_load_vtcm.py
- tests/python/meta_schedule/test_meta_schedule_postproc_rewrite_tensorize.py
- tests/python/meta_schedule/test_meta_schedule_trace_apply.py
- tests/python/tir-base/test_tir_ops.py
- tests/python/tir-transform/test_tir_transform_lower_cross_thread_reduction.py
- tests/python/tir-transform/test_tir_transform_vectorize.py
- tests/python/tvmscript/test_tvmscript_printer_tir.py
- tests/python/tvmscript/test_tvmscript_roundtrip.py
This PR refactors the tir.call_llvm_intrin to omit the first nargs argument in the beginning. Previously the nargs was introduced when prefetch have different number of signature. The previous reason no longer stands as of now, and it is less intuitive to attach nargs for the call_llvm_intrin, where nargs directly appears in number of argument.
After the update, tir.call_llvm_intrin can directly pass in the arguments as it is.
> [CODEGEN][REFACTOR] tir.call_llvm_intrin to remove nargs

- src/target/tag.cc
Added NVIDIA RTX 5060 Ti as a supported target device，so we can use it like the following code
```python
target = tvm.target.Target("nvidia/geforce-rtx-5060-ti")
```
> [TARGET]add target for nvidia rtx 5060ti

- ffi/src/ffi/extra/json_parser.cc
- ffi/src/ffi/extra/json_writer.cc
- ffi/tests/cpp/extra/test_json_parser.cc
This PR adds fallbacks for nan and inf
detection/creation under fastmath mode.
> [FFI] Make JSON Parser/Write fastmath safe

- ffi/scripts/benchmark_dlpack.py
- python/tvm/ffi/cython/base.pxi
- python/tvm/ffi/cython/function.pxi
This PR updates the autodlpack path to automatically update the env stream to be consistent with torch stream context.
The change would help to make FFI functions to be compatible in stream based executions.
Specifically, TVMFFIEnvSetStream will be called to set the stream from the torch cuda context so the callee can query the stream via TVMFFIEnvGetCurrentStream. The stream will be recovered after the function call ends
We leverage torch cpp_extension load_inline to create an efficient stream query function so it won't slow down the call, the first time loading might take more time to build the jit module and things should be fast after the torch jit module is cached.
> [FFI] AudoDLPack compatible with torch stream context

- python/tvm/contrib/popen_pool.py
- python/tvm/meta_schedule/builder/local_builder.py
Fix #18157 by:
- Add explicit shutdown flag in PopenPoolExecutor
- Replace del with explicit shutdown() calls in LocalBuilder
A minimal reproducible example can be found in the original issue.
> [Fix] Resolve deadlock in PopenPoolExecutor and LocalBuilder

- python/tvm/contrib/nvcc.py
- src/runtime/contrib/nvshmem/init.cc
This PR fixes two bugs that cause normal TIR functions (ones that don't use any NVSHMEM API) not being able to compile and run, in cases where `set(USE_NVSHMEM xxx)` is enabled.
Co-authored-by: Bohan Hou <bohanhou@andrew.cmu.edu>
> [NVSHMEM] Fix compatibility with CUDA code without nvshmem use

- ffi/src/ffi/extra/json_parser.cc
- ffi/src/ffi/extra/json_writer.cc
This PR fixes the JSON parser and writer for the support of the fast-math flag.
Prior to this PR, there would be the following error when compiling TVM with fast-math. This PR fixes this issue.
```
/home/ruihangl/Workspace/tvm/ffi/src/ffi/extra/json_writer.cc: In static member function ‘static bool tvm::ffi::json::JSONWriter::FastMathSafeIsNaN(double)’:
/home/ruihangl/Workspace/tvm/ffi/src/ffi/extra/json_writer.cc:69:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
69 |     uint64_t bits = *reinterpret_cast<const uint64_t*>(&x);
|                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ruihangl/Workspace/tvm/ffi/src/ffi/extra/json_writer.cc: In static member function ‘static bool …
```
> [FFI] Fix JSON parser/writer for the fast-math flag

- ci/jenkins/generated/arm_jenkinsfile.groovy
- ci/jenkins/generated/cpu_jenkinsfile.groovy
- ci/jenkins/generated/gpu_jenkinsfile.groovy
- ci/jenkins/generated/hexagon_jenkinsfile.groovy
- ci/jenkins/generated/i386_jenkinsfile.groovy
- ci/jenkins/generated/wasm_jenkinsfile.groovy
- ci/jenkins/templates/utils/macros.j2
Exit the build if we met AbortException. Previously, AbortExceptions were caught by the generic Throwable handler, which could trigger unnecessary retry logic on on-demand instances.
cc: @tqchen @yzh119
> [CI] Exit the build for AbortException

- src/runtime/contrib/cutlass/fp16_group_gemm.cuh
- src/runtime/contrib/cutlass/fp8_groupwise_scaled_group_gemm_sm100.cu
This PR fixes a few places in the current CUTLASS kernel AOT compilation.
> [CUTLASS] Fix CUTLASS kernel compilation

- python/tvm/libinfo.py
- python/tvm/relax/backend/cuda/flashinfer.py
This PR fixes the tvm/dlpack/dmlc header lookup in the FlashInfer kernel JIT compilation.
Prior to this fix, the JIT compilation assumes the environment variable `TVM_SOURCE_DIR` is always defined, which is not always true. This PR fixes the behavior and considers multiple cases, including TVM source builds and pip-installed packages.
> [Fix] Update FlashInfer JIT header lookup

- src/target/llvm/llvm_module.cc
This PR fix compile builds on MS-WIN observed during #18243.
---
* CI errors, ~~likely due to MSVC version upgrade~~ llvm upgrade to 21:
```
llvm_module.cc
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\memory(3630,35): error C2665: 'llvm::orc::RTDyldObjectLinkingLayer::RTDyldObjectLinkingLayer': no overloaded function could convert all the argument types [C:\Users\runneradmin\miniconda3\envs\tvm-build\conda-bld\tvm-package_1756327853683\work\build\tvm_objs.vcxproj]
(compiling source file '../src/target/llvm/llvm_module.cc')
C:\Users\runneradmin\miniconda3\envs\tvm-build\conda-bld\tvm-package_1756327853683\_h_env\Library\include\llvm\ExecutionEngine\Orc\RTDyldObjectLinkingLayer.h(58,3):
could be …
```
> [LLVM][MSWIN][CI] Fix LLVM module build with latest CI update

- src/relay/backend/contrib/mrvl/codegen.cc
- tests/python/contrib/test_mrvl/test_mrvl.py
[legacy-v0.19.post][mrvl] Remove unused code to improve stability and maintainability
This commit targets the legacy-v0.19.post branch of Apache TVM and removes unused code segments that were causing unintended issues during execution and integration.
The cleanup enhances maintainability and reduces potential sources of error.
> Removal of unused code that is causing unnecessary issues.

- version.py
This PR updates the `version.py`, so every time when running this file, it also bumps the version number in `pyproject.toml` automatically.
> [Python] Update version.py to bump pyproject.toml automatically

- CMakeLists.txt
- ffi/CMakeLists.txt
- pyproject.toml
Following #18239, this PR fixes a few issues we ran into during testing the packaging flow through scikit-build-core.
> [Python] Complete Python packaging with scikit-build-core

- ffi/CMakeLists.txt
- ffi/cmake/tvm_ffi-config.cmake
- ffi/examples/get_started/README.md
- ffi/examples/packaging/CMakeLists.txt
- ffi/examples/packaging/README.md
- ffi/examples/packaging/pyproject.toml
- ffi/examples/packaging/python/tvm_ffi_extension/__init__.py
- ffi/examples/packaging/python/tvm_ffi_extension/_ffi_api.py
- ffi/examples/packaging/python/tvm_ffi_extension/base.py
- ffi/pyproject.toml
- ffi/python/tvm_ffi/cython/function.pxi
- ffi/python/tvm_ffi/libinfo.py
This PR add an example about wheel packaging.
Also fixes various source packaging minor nits.
> [FFI][DOCS] Wheel Packaging

- ffi/python/tvm_ffi/cython/function.pxi
- include/tvm/ir/expr.h
- Allow i64 any value convert to `Integer` of proper bitwidth.
```python
import tvm
from tvm import relax
x = relax.Var("x", relax.TensorStructInfo((5, 784), "float32"))
x = relax.op.flip(x, 2**63-1).attrs.axis
``` 
- Ensure None any value's v_int64=0, since `AnyHash` depends on the repr value.
```python
m = tvm.ir.Map({None: 1})
assert None in m   # get False if v_int64 not const initialized.
```
> [FFI] fix two seemingly migration issue

- python/tvm/relax/base_py_module.py
- tests/python/relax/test_base_py_module_printer.py
This PR implements TVMScript printer to format IRModules containing @I.pyfunc decorated Python functions.
Example:
```
@I.ir_module
class MyModule(BasePyModule):
@I.pyfunc
def python_func(self, x, y):
x_tvm = self._convert_pytorch_to_tvm(x)
y_tvm = self._convert_pytorch_to_tvm(y)
result = self.call_tir(self.add_tir, [x_tvm, y_tvm], 
out_sinfo=R.Tensor((5,), "float32"))
return self._convert_tvm_to_pytorch(result)
@T.prim_func
def add_tir(a: T.handle, b: T.handle, c: T.handle):
A = T.match_buffer(a, (5,), "float32")
B = T.match_buffer(b, (5,), "float32")
C = T.match_buffer(c, (5,), "float32")
for i in range(5):
C[i] = A[i] + B[i]
print(MyModule.script())  # Print formatted TVMScript
MyModule.show()           # Display formatted output
```
> [Relax] Building TVMScript printer for IRModules with Python functions

- ffi/pyproject.toml
- ffi/python/tvm_ffi/cython/function.pxi
This PR updates the torch stream getter to use  _cuda_getCurrentRawStream in the torch C API that is also used by dynamo, saves us from load_inline the custom module.
> [FFI] Update torch stream getter to use native torch c api

- ffi/examples/inline_module/main.py
- ffi/python/tvm_ffi/cpp/load_inline.py
- ffi/tests/python/test_load_inline.py
This PR update the interface of `ffi.load_inline` to match `torch.utils.cpp_extensions.load_inline`:
1. Rename `cpp_source` to `cpp_sources`, `cuda_source` to `cuda_sources`.
2. Unify the `cpp_functions` and `cuda_functions` into `functions`. 
3. Add `build_directory` to allow the user to specify the build directory directly.
Example:
```python
mod: Module = tvm_ffi.cpp.load_inline(
name="hello",
cpp_sources=r"""
void add_one_cpu(DLTensor* x, DLTensor* y) {
// implementation of a library function
TVM_FFI_ICHECK(x->ndim == 1) << "x must be a 1D tensor";
DLDataType f32_dtype{kDLFloat, 32, 1};
TVM_FFI_ICHECK(x->dtype == f32_dtype) << "x must be a float tensor";
TVM_FFI_ICHECK(y->ndim == 1) << "y must be a 1D tensor";
TVM_FFI_ICHECK(y->dtype == f32_dtype) << "y must be a float tensor"; …
```
> [FFI] Update the interface of `ffi.load_inline` to match torch

- ffi/pyproject.toml
- ffi/tests/python/test_load_inline.py
This PR temp skip load_inline tests on nonlinux before we enhance and improve for other platforms.
> [FFI] Temp skip load_inline tests nonlinux

- include/tvm/meta_schedule/postproc.h
- include/tvm/meta_schedule/schedule_rule.h
- python/tvm/target/target.py
- python/tvm/tir/tensor_intrin/__init__.py
- python/tvm/tir/tensor_intrin/riscv_cpu.py
- src/meta_schedule/postproc/postproc.cc
- src/meta_schedule/schedule_rule/schedule_rule.cc
- src/meta_schedule/space_generator/space_generator.cc
This PR adds RISCV kernel templates in compliance with RVV v1.0 specifications
---
* Enables high performance kernels covering majority of usual [ML datatype inputs](https://github.com/apache/tvm/compare/main...cbalint13:tvm:riscv-rvv-metasch?expand=1#diff-7330d34376acbd4172bbc2ed08b7238486f27fdfc32efa3188b172845996e87bR191-R193)
* It is currently compliant with [RVV specs version v1.0](https://github.com/riscvarchive/riscv-v-spec/releases/tag/v1.0) (does not work with older v0.7.1)
* TIR kernels implemented here are using recently added VLA extension support
Like all other CPU intrisics only a limited set of operators, currently dense (linear) works with metaschedule.
The list of operators will be revisited and extended in the near future to transposed flavours and convs.
The performance …
> [LLVM][METASCHEDULE] Add RISCV V-extension v1.0 kernels to metaschedule

- ffi/python/tvm_ffi/cpp/load_inline.py
- ffi/tests/python/test_load_inline.py
This PR fix the bug to enable `tvm_ffi.cpp.load_inline` on macos. We need to link the `libtvm_ffi.dylib` to the custom module.
> [FFI][Bugfix] Enable `load_inline` on macos

- src/runtime/metal/metal_module.mm
This PR fixes a type mismatch in MetalModuleCreate when initializing a MetalModule.  The error does not show up until the recent ObjectRef null safety enhancement.
> [Metal] Fix MetalModuleCreate

- ffi/pyproject.toml
- ffi/tests/python/test_load_inline.py
This PR temp skips windows tests as we may need some more investigation to ensure cl.exe is found.
> [FFI] Temp skip windows tests

- .github/workflows/main.yml
- cmake/utils/FindLLVM.cmake
- conda/build-environment.yaml
This pr add libxml2 dependency to fix Windows CI LNK1181 linking error.
> [Fix] Add libxml2 dependency to fix Windows CI build failure

- ffi/src/ffi/extra/library_module_system_lib.cc
This PR fixes a bug in the current system library symbol lookup.
Prior to this PR, the lookup key always concatenates `symbol_prefix_` and `name`. However, the `name` may or may not have already contained the symbol prefix. And when it does contain the symbol prefix, the concantenated string will have duplicate symbol prefix, which leads to the lookup failure, because in the compiled library the symbol prefix only appears once.
This PR changes the lookup behavior to check both cases.
> [FFI] Fix system library symbol lookup

- ffi/include/tvm/ffi/c_api.h
- ffi/pyproject.toml
- ffi/python/tvm_ffi/_convert.py
- ffi/python/tvm_ffi/_optional_torch_c_dlpack.py
- ffi/python/tvm_ffi/cython/base.pxi
- ffi/python/tvm_ffi/cython/function.pxi
- ffi/python/tvm_ffi/cython/object.pxi
- ffi/python/tvm_ffi/cython/string.pxi
- ffi/python/tvm_ffi/cython/tvm_ffi_python_helpers.h
- ffi/src/ffi/object.cc
- ffi/tests/python/test_function.py
- ffi/tests/python/test_load_inline.py
- src/runtime/disco/protocol.h
- src/runtime/minrpc/rpc_reference.h
- src/runtime/rpc/rpc_endpoint.cc
This PR improves the overall String/Bytes and nested container handling
It also fixes a bug for temp object recycling when temp object.
- Introduce formal API for string/bytes creation
- Updates the tuple/dict conversion to also preserve the torch stream
- So if a function takes a list of torch.Tensor, stream will be setup in context
- Optimizes recursive argument conversion by moving most logic into c++
> [FFI][ABI] Better String and Nested Container handling

- .gitmodules
- Makefile
This PR removes the TVM dependency on dlpack and libbacktrace, as tvm-ffi being separated to https://github.com/apache/tvm-ffi.
> [3rdparty] Remove dlpack/libbacktrace from 3rdparty

- CMakeLists.txt
This PR updates the CMakeLists to install the web subdirectory when building Python package, so that people do not need to clone TVM source code to build web package.
> [CMake][Web] Install `web/` directory in cmake for Python package

- apps/android_rpc/app/src/main/jni/tvm_runtime.h
- include/tvm/runtime/logging.h
- python/tvm/relax/transform/transform.py
- src/target/target.cc
- src/tir/schedule/error.h
- web/emcc/wasm_runtime.cc
This PR bumps the version of tvm-ffi to latest, which involves an ABI change.
> [FFI][ABI] Bump version ffi to latest

- python/tvm/relax/base_py_module.py
- tests/python/relax/test_base_py_module.py
- tests/python/relax/test_base_py_module_printer.py
This PR enhances `BasePyModule` by integrating a faster DLPack converter for efficient tensor conversion between TVM and PyTorch following #18306
> [Relax] Update BasePyModule with faster DLPack converter for tensor conversion

- python/tvm/script/parser/core/evaluator.py
- tests/python/tvmscript/test_tvmscript_parser_tir.py
Implement proper parsing and evaluation of chained comparison operators (e.g., `0 < i < 128`) in TVMScript. The sequence comparisons are now correctly expanded to their logical equivalents (e.g., `(0 < i and i < 128)`).
cc @LeiWang1999
> [TIR] Support sequence comparisons in TVMScript

- web/src/memory.ts
This PR bumps tvm-ffi version. The latest version contains a change to the RC ABI that also needs web runtime update.
> [FFI][ABI] Bump tvm-ffi version to reflect RC ABI Update

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- python/tvm/relax/frontend/torch/exported_program_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
This pr supports `lstm.input` for ExportedProgram importer.
This links to issue #18340
> [Relax][PyTorch] Support lstm op for ExportedProgram importer

- python/tvm/relax/frontend/torch/base_fx_graph_translator.py
- tests/python/relax/test_frontend_from_exported_program.py
As per title, this PR resolves the issue #18337
> [Relax][PyTorch] Fix the segfault in from_exported_program when model returns (Tensor, None) tuple
