docs/how_to/install.md
Add install prerequisites of customized building
=> [DOC] Add install prerequisites

src/codegen/llvm/codegen_arm.cc, src/codegen/llvm/codegen_cpu.cc, src/codegen/llvm/codegen_cpu.h, src/codegen/llvm/codegen_llvm.cc, src/codegen/llvm/codegen_llvm.h
This makes it cleaner to use CodeGenLLVM as base class for virtual ISA like NVPTX or AMDGPU cc @adityaatluri
=> [CODEGEN][LLVM] Refactor cpu runtime related code to CodeGenCPU

docs/how_to/install.md
Add some notes about LLVM before building TVM
=> [DOC] Add some notes about LLVM

tutorials/python/cross_compilation_and_rpc.py
Add Build TVM Runtime on Device section
=> [DOC] Add Build TVM Runtime on Device section

tests/ci_build/Dockerfile.gpu
=> [TEST] Add rocm library to library path

python/tvm/_ffi/ndarray.py, src/codegen/llvm/codegen_llvm.cc, src/codegen/llvm/codegen_llvm.h, src/codegen/llvm/codegen_nvptx.cc, src/codegen/llvm/llvm_common.cc, src/runtime/module.cc, tests/python/integration/test_gemm.py, tests/python/unittest/test_codegen_device.py
Note: currently the NVPTX backend is slow due to the fact that seems the local to register promotion does not work very correctly, need to investigate a bit more
=> [CODEGEN] NVPTX backend.

tests/python/unittest/test_schedule_schedule_ops.py, topi/python/topi/cuda/conv2d_nchw.py
Lib | End-to-end time(s)
-- | --
MXNet (w/ CUDNN) | 0.00665194
TVM(w/ fusion and simplified bn) | 0.00660499
Speedup | 1.007108262
=> Conv2d updated 

topi/python/topi/nn/softmax.py, topi/tests/python/test_topi_softmax.py
cc @Laurawly reduce_axis cannot be reused across two reductions
=> [TOPI] Fix softmax bug

Makefile
https://github.com/dmlc/tvm/issues/440
=> disable fopen64 in dmlc-core

src/runtime/pack_args.h, src/runtime/rocm/rocm_module.cc
=> [RUNTIME] Add function to pack arguments

topi/python/topi/broadcast.py, topi/python/topi/cuda/__init__.py, topi/python/topi/cuda/broadcast.py, topi/recipe/broadcast/test_broadcast_map.py, topi/tests/python/test_topi_broadcast.py
Add binary op with auto-broadcasting. Support add, sub, mul, div, maximum, minimum
@tqchen
=> [TOPI] add binary broadacst

apps/cpp_deploy/run_example.sh
add lib folder, or it will not generate the objects
=> fix cpp deploy

topi/python/topi/cuda/reduction.py, topi/tests/python/test_topi_reduce.py
@sxjscience 
For now fusion with ewise output is not supported. reference https://github.com/dmlc/tvm/blob/master/tests/python/integration/test_reduce.py#L131 later to add that
=> [TOPI] Fix reduction fusion with injective input

apps/README.md
Link is broken due to this typo :(
=> fixing typo in apps/README.md

src/codegen/intrin_rule_metal.cc
=> [CODEGEN] Use correct math intrin for metal

topi/tests/python/test_topi_broadcast.py, topi/tests/python/test_topi_conv2d_hwcn.py, topi/tests/python/test_topi_conv2d_nchw.py, topi/tests/python/test_topi_conv2d_transpose_nchw.py, topi/tests/python/test_topi_dense.py, topi/tests/python/test_topi_depthwise_conv2d.py, topi/tests/python/test_topi_depthwise_conv2d_back_input.py, topi/tests/python/test_topi_depthwise_conv2d_back_weight.py, topi/tests/python/test_topi_pooling.py, topi/tests/python/test_topi_reduce.py, topi/tests/python/test_topi_relu.py, topi/tests/python/test_topi_softmax.py, topi/tests/python/test_topi_transform.py
as per @adityaatluri's request.
=> add helpful message to topi test

topi/python/topi/nn/pooling.py, topi/tests/python/test_topi_pooling.py
=> [TOPI] Support ceil_mode in pooling

python/tvm/intrin.py, src/codegen/llvm/codegen_llvm.cc, src/codegen/llvm/intrin_rule_llvm.cc, tests/python/integration/test_ewise.py
I am not sure whether this is the proper way to add support for popcount intrin, though it works.
=> [INTRIN] Enable popcount

topi/python/topi/cuda/conv2d_transpose_nchw.py
so that conv2d_transpose can fuse output_padding
=> [TOPI] modify conv2d_transpose schedule

include/tvm/buffer.h, python/tvm/schedule.py, src/api/api_lang.cc, src/codegen/llvm/codegen_llvm.cc, src/codegen/llvm/codegen_llvm.h, src/lang/buffer.cc, src/pass/ir_util.h
Adding support for external functions that use vector types e.g., half4
=> Support vector operations for AMD (llvm IR)

docs/how_to/nnpack.md
greatly inspired by https://mxnet.incubator.apache.org/how_to/nnpack.html
I need to add preformance benchmark 
Erwan
=> WIP: Add how_to readme to install tvm with nnpack support

python/conda/build.sh, python/conda/meta.yaml, topi/python/conda/meta.yaml
This makes the tvm package buildable for me and also adds a topi package.
=> Fix conda packages

topi/python/topi/cuda/conv2d_nchw.py, topi/tests/python/test_topi_conv2d_nchw.py
=> conv2d perf improved for conv2d_56_64_128, super resolution workloads added

src/codegen/build_metal.cc, src/codegen/build_opencl.cc, src/codegen/codegen.cc, src/codegen/codegen_source_base.h, src/codegen/source_module.cc, src/runtime/opencl/opencl_module.h
=> [RUNTIME] support limited save without cross compile

topi/python/topi/cuda/conv2d_nchw.py
https://github.com/dmlc/nnvm/issues/239 solved
=> Fixed nnvm issue #239

include/tvm/ir_pass.h, src/api/api_pass.cc, src/arithmetic/canonical.cc, src/arithmetic/canonical.h, tests/python/unittest/test_arith_simplify.py
=> [ARITH] Upgrade CanonicalSimplify to Simplify Mod

python/tvm/contrib/rpc.py, src/codegen/codegen_cuda.cc, tests/python/integration/test_ewise.py, tests/scripts/task_python_docs.sh, tutorials/deployment/cross_compilation_and_rpc.py
=> [CUDA] Enable int64

src/arithmetic/canonical.cc, src/op/tensorize.cc
I'm not totally happy with some aspects of my patch. Please see my comments in the code review part and let me know if you have any suggestions.
=> Consider variable range information during simplification of tensorize expressions

src/codegen/codegen_c.cc, src/codegen/codegen_c.h, src/codegen/codegen_cuda.cc, src/codegen/codegen_cuda.h, src/codegen/codegen_metal.cc, src/codegen/codegen_metal.h, src/codegen/codegen_opencl.cc, src/codegen/codegen_opencl.h
=> [CODEGEN] add fp16 and fp64 enable pragma for opencl

include/tvm/expr.h, include/tvm/ir.h, include/tvm/ir_operator.h, include/tvm/packed_func_ext.h, include/tvm/runtime/packed_func.h, include/tvm/tensor.h, src/api/api_ir.cc, src/arithmetic/bound_deducer.cc, src/arithmetic/canonical.cc, src/arithmetic/compute_expr.h, src/arithmetic/int_set.cc, src/arithmetic/int_set_internal.h, src/lang/expr.cc, src/lang/ir.cc, src/lang/reflection.cc, src/lang/tensor.cc, src/op/compute_op.cc, src/op/extern_op.cc, src/op/scan_op.cc, src/pass/inject_prefetch.cc, src/pass/ir_deep_compare.cc, src/pass/ir_mutator.cc, src/pass/storage_flatten.cc, src/schedule/message_passing.cc, tests/cpp/ir_mutator_test.cc, tests/cpp/ir_simplify_test.cc, tests/cpp/ir_ssa_test.cc, tests/cpp/ir_visitor_test.cc
To make it possible to use Halide and tvm in the same project.
=> Halide -> HalideIR

python/tvm/target.py, src/codegen/llvm/llvm_common.cc, tests/python/contrib/test_cudnn.py, topi/python/topi/cuda/__init__.py, topi/python/topi/cuda/conv2d.py, topi/python/topi/cuda/conv2d_hwcn.py, topi/python/topi/cuda/conv2d_nchw.py, topi/python/topi/rocm/conv2d.py
The follow up to #724 for cudnn.
=> [TOPI] CUDNN integration

topi/python/topi/reduction.py, topi/tests/python/test_topi_broadcast.py, topi/tests/python/test_topi_reduce.py, topi/tests/python/test_topi_transform.py
=> [TOPI]Support dim-0 tensor in topi broadcast/reduce

Makefile, make/config.mk, make/contrib/cublas.mk, python/tvm/contrib/cblas.py, python/tvm/contrib/cublas.py, python/tvm/target.py, src/contrib/cblas/cblas.cc, src/contrib/cublas/cublas.cc, tests/python/contrib/test_cublas.py, tests/python/contrib/test_cudnn.py, topi/python/topi/cuda/__init__.py, topi/python/topi/cuda/dense.py, topi/python/topi/nn/dense.py
rocBLAS integration will follow.
=> [CONTRIB] cuBLAS integration

topi/tests/python/test_topi_reduce.py
Fix https://github.com/dmlc/tvm/issues/771
@tqchen
=> Revise the test of argmax/argmin

src/codegen/codegen_c.cc, src/codegen/codegen_c.h, src/codegen/codegen_opencl.cc, src/codegen/codegen_opencl.h, src/pass/split_host_device.cc, topi/python/topi/nn/depthwise_conv2d.py, topi/python/topi/testing/depthwise_conv2d_python.py, topi/tests/python/test_topi_depthwise_conv2d.py
1. fix vector conversion for opencl
2. add more argument type in depthwise_conv2d
3. when mark pointer type as 'restrict', use 'float32' as default type. I am not sure whether I do it correctly.
=> [CODEGEN] fix vector conversion for opencl

python/tvm/target.py, topi/python/topi/__init__.py, topi/python/topi/mali/__init__.py, topi/python/topi/mali/conv2d.py, topi/python/topi/mali/dense.py, topi/python/topi/mali/depthwise_conv2d.py
* conv2d
* dense
* depthwise_conv2d
for FP32 and FP16
=> [TOPI] add schedule for ARM Mali GPU

topi/tests/python/test_topi_reduce.py
=> Fix argmax/argmin test

topi/python/topi/mali/conv2d.py
=> [TOPI] fix mali topi for python3

topi/python/topi/nn/upsampling.py, topi/python/topi/util.py
=>  simplify expr in get_const_tuple

python/tvm/__init__.py, python/tvm/build_module.py, tests/python/unittest/test_pass_unroll.py
with build or lower, you can enable it like:
```
with tvm.build_config(dump_pass_ir=True):
run()
```
=> Support dump ir for each pass (#693)

tutorials/optimize/opt_gemm.py
Added more optimization with help from @yidawang , current matrix mutiplication speed is about 60% of MKL.
=> [TUTORIAL] Improve gemm tutorial

docs/dev/runtime.md
fix some grammatical and expression issues
=> minor tweak of the runtime doc

python/tvm/module.py, src/runtime/rpc/rpc_module.cc, src/runtime/rpc/rpc_session.cc, src/runtime/rpc/rpc_session.h, tests/python/integration/test_ewise.py
=> [TIMER] Enhance time evaluator to create multiple results

src/pass/inject_copy_intrin.cc
Support pattern x[i] = cast<int8>(array_int32[i])
=> copy intrinsic now can include typecast

src/codegen/spirv/ir_builder.cc
> **OpConstant**
> Declare a new integer-type or floating-point-type scalar constant.
> *Result Type* must be a scalar integer type or floating-point type.
Boolean type should be created using `OpConstantTrue` and `OpConstantFalse`.
=> SPIR-V Boolean types

src/codegen/codegen_c.h
=> Note about CodeGenC's Range of Use

include/tvm/operation.h, include/tvm/schedule_pass.h, src/api/api_schedule.cc, src/codegen/build_module.cc, src/op/compute_op.cc, src/op/compute_op.h, src/op/cross_thread_reduction.cc, src/op/extern_op.cc, src/op/op_util.cc, src/op/op_util.h, src/op/placeholder_op.cc, src/op/scan_op.cc, src/op/tensorize.cc, src/schedule/schedule_ops.cc
NOTE: This is useful for building analysis that reflects the original dataflow's iterator
=> [PASS] Support keeping trivial loops with extent of 1

include/tvm/ir.h, include/tvm/schedule.h, python/tvm/target.py, src/codegen/codegen_opengl.cc, src/codegen/codegen_opengl.h, src/codegen/intrin_rule_opengl.cc, src/pass/storage_flatten.cc, src/runtime/opengl/opengl_device_api.cc, src/schedule/schedule_lang.cc, src/schedule/schedule_ops.cc, tests/webgl/test_local_topi_conv2d_nchw.py, tests/webgl/test_local_topi_dense.py, tests/webgl/test_local_topi_pooling.py, tests/webgl/test_local_topi_softmax.py, topi/python/topi/__init__.py, topi/python/topi/opengl/__init__.py, topi/python/topi/opengl/conv2d_nchw.py, topi/python/topi/opengl/dense.py, topi/python/topi/opengl/injective.py, topi/python/topi/opengl/pooling.py, topi/python/topi/opengl/softmax.py
=> [TOPI][GL] OpenGL topi.

topi/python/topi/x86/conv2d.py
#883 introduced changes that that are only applicable to resnet18 and mobilenet workloads. For other workloads, it aborts with exception.
This PR allows non resnet18 or mobilenet workload to use a fall back schedule.
@yzhliu
=> [TOPI, x86] allow fall back path to non imagenet workloads

topi/python/topi/nn/conv2d.py, topi/python/topi/nn/pooling.py, topi/python/topi/nn/softmax.py, topi/python/topi/nn/upsampling.py
Add NHWC layout support to conv, pool, upsampling, and softmax.
=> [TOPI] Initial NHWC layout support

topi/python/topi/reduction.py
The parameter description is updated for max, min, argmax and argmin
=> [Documentation Changes] Parameter description change for reduction apis

topi/python/topi/x86/nn.py, topi/src/topi.cc
Basic dense scheduler for x86. This PR deals with the case of batch size 1. Some test results from vgg dense workloads on c5.xlarge:
| Data size  | Weight size | TVM | mklml|
| ---------- | -------------- | ------- | ------ |
| 1 x 25088 | 4096 x 25088 | 15 ms  | 17 ms  |
| 1 x 4096   | 4096 x 4096   | 3 ms    | 5 ms   |
| 1 x 4096   | 1000 X 4096   | 0.6 ms | 1.3 ms |
@yidawang @yuruofeifei @yzhliu
=> Add dense base scheduler

src/codegen/llvm/llvm_common.cc, src/runtime/metal/metal_device_api.mm, src/runtime/opencl/opencl_device_api.cc, src/runtime/registry.cc, src/runtime/vulkan/vulkan_device_api.cc
Otherwise the lock guards get destructed immediately.
=> Name all the lock guards.

python/tvm/target.py
There are typos in comment.
This patch fixes them.
=> Fix a typo for Target class

web/tvm_runtime.js
Example usage:
```js
var tvm = tvm_runtime.create(Module);
var syslib = tvm.systemLib();
var graph_json_str = "...";
var ctx = tvm.context("opengl", 0);
var loaded_module = tvm.createGraphRuntime(graph_json_str, syslib, ctx);
var x = tvm.empty(4, "float32", ctx).copyFrom([1, 2, 3, 4]);
loaded_module.set_input("x", x);
base64_params = "...";
loaded_module.load_base64_params(base64_params);
loaded_module.run();
var z = tvm.empty(4, "float32", ctx);
loaded_module.get_output(0, z);
```
=> Add the equivalence of graph_runtime.py in tvm_runtime.js

src/codegen/llvm/codegen_llvm.cc, tests/python/unittest/test_codegen_llvm.py
Alignment for load/store wasn't generated properly in the previous version due to bug introduced by a refactor. Added test cases to prevent it from happening again
=> [CODEGEN] Fix alignment generation

src/runtime/c_runtime_api.cc
Small attempt to clarify the implementation of ArrayCopyFromTo.
Separate correctness check from choice of device context to use in Get method.
If no one agrees then I will close.
=> Array copy code cleanup

apps/sgx/tvm_runtime_pack.cc, sgx/sgx_runtime.cc
This PR consolidates the SGX runtime into a single file that also provides a stub for parallel.
=> Add SGX runtime

sgx/sgx_runtime.cc
I see what was meant by
> directly launch the callback with master thread and provide num_tasks=1
in #963
=> Use single-threaded SGX parallel

src/schedule/schedule_ops.cc
=> [PASS] Fix keeping trivial loop

python/tvm/_ffi/_ctypes/function.py, python/tvm/_ffi/_ctypes/node.py
Try to solve cases like https://github.com/dmlc/tvm/pull/985
cc @ZihengJiang
=> [FFI] Fix global free destruction

python/tvm/contrib/util.py
=> [CONTRIB] windows compatiblity

tutorials/optimize/opt_gemm.py
Documentation issues fixed for better readability
=> Documentation issues fixed

include/tvm/build_module.h
fix the issue #1033 "converting to ‘const std::unordered_set<std::basic_string<char> >’from initializer"
=> Fix the issue #1033

python/tvm/_ffi/_cython/base.pxi, python/tvm/_ffi/_cython/function.pxi
fix issue in https://github.com/dmlc/tvm/pull/1044
=> [CYTHON] Fix exception propagation for cython3

src/runtime/graph/graph_runtime.cc
This PR allows `graph_runtime.set_inputs(**params)` when there might be extra params. This happens often when constructing helpers for unit tests.
Someday there should be a `strict` flag that allows configuring between warning or error.
=> Warn, not error, when unable to find a graph input

src/pass/lower_warp_memory.cc
=> [PASS] More reliable error message for lower warp

topi/python/topi/x86/conv2d.py, topi/python/topi/x86/conv2d_avx_common.py
=> [TOPI] Fix x86 schedule for conv out_dtype

topi/include/topi/nn.h
Signed-off-by: Janboe Ye <janboe.ye@gmail.com>
=> [TOPI] fix bug of leaky_relu type issue

python/tvm/contrib/rpc/base.py, python/tvm/contrib/rpc/client.py, python/tvm/contrib/rpc/server.py, python/tvm/contrib/rpc/tracker.py, python/tvm/exec/query_rpc_tracker.py, python/tvm/exec/rpc_tracker.py, tests/python/contrib/test_rpc_tracker.py
=> [RPC] Tracker status query

python/tvm/contrib/rpc/base.py, python/tvm/contrib/rpc/client.py, python/tvm/contrib/rpc/proxy.py, python/tvm/contrib/rpc/server.py, python/tvm/contrib/rpc/tornado_util.py, python/tvm/contrib/rpc/tracker.py, tests/python/contrib/test_rpc_tracker.py
=> [RPC] More robust tracker protocol

src/runtime/rpc/rpc_device_api.cc, src/runtime/rpc/rpc_module.cc
=> [RPC] safe destructor when remote server get killed

src/runtime/vulkan/vulkan_device_api.cc
=> [RUNTIME] Fault tolerant vulkan init error

python/tvm/contrib/rpc/tracker.py
=> [RPC] Fix tracker fault handling

make/contrib/random.mk, src/contrib/random/mt_random_engine.cc, src/contrib/random/random.cc, src/contrib/random/sgx_random_engine.cc, src/runtime/sgx/common.h, src/runtime/sgx/trusted/runtime.h
This PR allows using trusted `sgx_read_rand` when inside of an enclave.
=> Add SGX random engine

include/tvm/build_module.h, include/tvm/ir_pass.h, python/tvm/build_module.py, python/tvm/target.py, src/api/api_pass.cc, src/codegen/build_module.cc, src/pass/remap_thread_axis.cc, tests/python/integration/test_ewise.py
=> [PASS] Remap thread axis.

python/tvm/contrib/rpc/proxy.py, python/tvm/contrib/rpc/server.py, python/tvm/exec/rpc_server.py, src/codegen/codegen_source_base.h, src/codegen/llvm/codegen_amdgpu.cc, src/codegen/source_module.cc, src/runtime/module.cc, topi/tests/python/test_topi_l2norm.py, topi/tests/python/test_topi_lrn.py, topi/tests/python_cpp/test_topi_dense.py, topi/tests/python_cpp/test_topi_pooling.py, topi/tests/python_cpp/test_topi_reduce.py, topi/tests/python_cpp/test_topi_transform.py
=> [CODEGEN] Enable cross compile of AMDGPU without rocm, update rpc 

src/runtime/thread_pool.cc
Address #1142 
I didn't check if this change will affect SGX in any way. cc @nhynes
=> make ThreadPool thread local

topi/include/topi/transform.h, topi/python/topi/transform.py, topi/src/topi.cc, topi/tests/python/test_topi_transform.py
Reverse operator added to support tensor flow reverse(equivalent to numpy flip)
=> [TOPI] flip

topi/include/topi/transform.h, topi/python/topi/transform.py, topi/src/topi.cc, topi/tests/python/test_topi_transform.py, topi/tests/python_cpp/test_topi_transform.py
* add take
Take operator added to tvm.topi to support Tensorflow Gather operator in future.
=> [TOPI] add take

topi/include/topi/broadcast.h, topi/include/topi/detail/broadcast.h, topi/include/topi/detail/constant_utils.h, topi/include/topi/nn.h, topi/include/topi/transform.h, topi/python/topi/transform.py, topi/tests/python_cpp/test_topi_transform.py
This PR solves the issues referred in #1106.
=> Added equality check and upgraded concatenate op

nnvm/python/nnvm/top/nn.py
************* Module nnvm.top.nn
E:141, 8: Assigning to function call which doesn't return (assignment-from-no-return)
=> [LINT] Expected, hence disable for a while.

docs/how_to/install.md
I've spent about 4-5 hours today figuring out these things.
The problem with the python modules is especially nasty since it leads to a corrupted backtrace in most cases.
=> Add some tips for building on macOS.

nnvm/python/nnvm/frontend/darknet.py, nnvm/tests/python/frontend/darknet/test_forward.py
Elu support added in darknet frontend
~/A.T.
=> [NNVM] Elu support added in darknet frontend

tests/python/unittest/test_codegen_extern.py, tests/python/unittest/test_ir_builder.py
add test to ir_builder for gpu execution, solved issue #1180 .
=> add test to irbuilder for gpu execution

nnvm/src/top/nn/nn.cc, nnvm/tests/python/compiler/test_top_level1.py
=> [NNVM] Fix softmax gradient

docs/api/python/topi.rst, topi/include/topi/detail/constant_utils.h, topi/include/topi/transform.h, topi/python/topi/transform.py, topi/src/topi.cc, topi/tests/python/test_topi_transform.py
Slice operator added along with stride support.
Source: https://github.com/dmlc/nnvm/issues/488
=> [TOPI] Slice operator

Makefile, docs/install/index.rst
This PR allows us to build nnvm with `make nnvm`.
=> Add nnvm target to Makefile

nnvm/python/nnvm/frontend/mxnet.py, nnvm/tests/python/frontend/mxnet/test_forward.py
=> [NNVM][FRONTEND][MXNET] PReLU Support

tests/ci_build/Dockerfile.lint
@tqchen this is to support Relay as we discussed on Slack.
=> Add MyPy to lint

CONTRIBUTORS.md
This PR adds @srkreddy1238 as a reviewer of TVM. Siva contributes the tensorflow frontend of the tvm. He also contributed to the image operators and help reviews the vision modules.
- [Siva's Contribution history ](https://github.com/dmlc/tvm/commits?author=srkreddy1238)
- [Recent code reviews SIva involves in](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Asrkreddy1238)
=> [MAINTAINER] add srkreddy1238 as reviewer

topi/python/topi/nn/pooling.py
=> Documentation error fixed

src/api/api_pass.cc, tests/python/unittest/test_hybrid_script.py
- Simplify test cases
- Expose CPP Substitute in Python
- Add GPU shared memory test case
=> [FRONTEND] [HYBIRD] [TEST] Add GPU shared memory test!

python/tvm/_ffi/base.py, python/tvm/hybrid/api.py, python/tvm/tag.py
=> [PYTHON] Make decorator optional for runtime

cmake/util/FindLLVM.cmake
change regex to match all symbol except for space. fix #1342
=> update include regex to work for path with symbol

nnvm/include/nnvm/top/nn.h, nnvm/python/nnvm/top/nn.py, nnvm/src/top/nn/convolution.cc, nnvm/tests/python/compiler/test_top_level2.py, nnvm/tests/python/unittest/test_infer_shape.py, topi/python/topi/nn/depthwise_conv2d.py
Add out_dtype argument to conv2d to support mixed precision computations
=> [NNVM] Initial mixed precision support of conv2d

nnvm/src/top/nn/nn.cc, topi/include/topi/nn.h, topi/src/topi.cc, topi/tests/python/test_topi_relu.py, topi/tests/python_cpp/test_topi_relu.py
1:> Prelu does not take axis as input.
2:> Test case also updated.
=> Prelu bug fix

CONTRIBUTORS.md
This PR add @alex-weaver as reviewer. Alex actively pushes the C++ API compatibility and improves TVM's platform compatibility on windows, he also has deep knowledge of dll problems.
- [Alex's commit history](https://github.com/dmlc/tvm/commits?author=alex-weaver)
- Technical discussions and RFCs alex involved in 
- https://github.com/dmlc/tvm/issues/1184
- https://github.com/dmlc/tvm/issues/1363
=> [TEAM] Add alex-weaver as reviewer

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
=> [NNVM][TENSORFLOW] Sigmoid op support #1367

nnvm/python/nnvm/testing/darknet.py, topi/python/topi/nn/conv2d.py, topi/python/topi/rasp/conv2d.py
to be consistent with the docstring and common API
=> [TOPI] Update parameter name of conv2d

tutorials/topi/intro_topi.py
This PR is small tutorial fix to follow the conv2d change in #1380 
@tqchen please review
=> Fix tutorial to follow the conv2d change

include/tvm/ir_operator.h, python/tvm/expr.py, src/api/api_ir.cc, tests/python/unittest/test_lang_basic.py, tests/python/unittest/test_pass_inject_copy_intrin.py
=> [OP] Improve bitwise op type checks

apps/android_rpc/app/src/main/jni/tvm_runtime.h
Fix build error of android packed runtime caused by recent change #1418
=> [ANDROID] Fix android build error

apps/android_deploy/app/src/main/jni/tvm_runtime.h, apps/howto_deploy/tvm_runtime_pack.cc, apps/ios_rpc/tvmrpc/TVMRuntime.mm
=> [TVM][RUNTIME] dependencies update for ndarray.

tutorials/autotvm/tune_simple_template.py, tutorials/cross_compilation_and_rpc.py, tutorials/language/tuple_inputs.py
=> Minor doc fixes

docker/install/ubuntu_install_python_package.sh, docker/install/ubuntu_install_sphinx.sh
Add dependencies needed by Relay to install scripts to update our shared Docker image.
=> Add dependencies for Relay

python/tvm/hybrid/parser.py, python/tvm/hybrid/var_decl.py, tests/python/unittest/test_hybrid_script.py
The augmented operators like `+=`, `-=`, and etc. are supported now!
=> [FRONTEND] [HYBRID] Augmented assign operator supported!

python/tvm/hybrid/parser.py, python/tvm/hybrid/var_decl.py, tests/python/unittest/test_hybrid_script.py
=> Revert "[FRONTEND] [HYBRID] Augmented assign operator supported!"

apps/android_rpc/README.md, apps/android_rpc/tests/android_rpc_test.py
Move some leftover references to the proxy server to the RPC Tracker, thanks to @merrymercy for the catch in #1457.
=> [DOCS] Android RPC Update

docker/install/ubuntu_install_python_package.sh
=> [CI] Update dependency

docker/install/ubuntu_install_python_package.sh
=> Revert "[CI] Update dependency"

nnvm/include/nnvm/layout.h, vta/python/vta/top/arm_conv2d.py
=> [NNVM] Fix check in layout parsing

CONTRIBUTORS.md
This PR adds @yzhliu as a committer of TVM.  
- [Yizhi's commit history](https://github.com/dmlc/tvm/commits?author=yzhliu)
- [Code reviews by yizhi](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Ayzhliu)
- [Community forum summary](https://discuss.tvm.ai/u/yzhliu/summary)
- Yizhi has demonstrates area of expertise in the following areas
- graph optimizer
- jvm package
- intel cpu backend
- Major technical contributions by yzhi
- initiates and owns the tvm4j package
- layout transformation optimization
- intel CPU optimization
- Community involvements, tutorials/blogs contributed by yizhi
- https://github.com/yzhliu/tvm4j-example
- https://tvm.ai/2017/11/08/android-rpc-introduction.html
=> [TEAM] New committer yzhliu 

nnvm/python/nnvm/frontend/keras.py, nnvm/tests/python/frontend/keras/test_forward.py
#https://github.com/dmlc/tvm/issues/1529
=> [KERAS]keras.layers.ReLU added

apps/android_rpc/README.md, docs/api/python/autotvm.rst, docs/install/from_source.rst, docs/vta/dev/hardware.rst, python/tvm/autotvm/measure/measure_methods.py, python/tvm/autotvm/record.py, python/tvm/exec/rpc_tracker.py, python/tvm/rpc/__init__.py, tutorials/autotvm/tune_conv2d_cuda.py, tutorials/autotvm/tune_nnvm_arm.py, tutorials/cross_compilation_and_rpc.py
Fix unnecessary 'tornado' dependency introduced by #1487 
Improve docs
=> [DOC] Fix docs and dependencies

python/tvm/autotvm/measure/__init__.py, python/tvm/autotvm/measure/measure_methods.py, python/tvm/autotvm/record.py, python/tvm/autotvm/task/dispatcher.py, python/tvm/autotvm/tophub.py, python/tvm/autotvm/tuner/callback.py, python/tvm/autotvm/tuner/sa_model_optimizer.py, python/tvm/autotvm/tuner/tuner.py, python/tvm/autotvm/tuner/xgboost_cost_model.py, python/tvm/autotvm/util.py, python/tvm/rpc/base.py, python/tvm/rpc/proxy.py, python/tvm/rpc/server.py, python/tvm/rpc/tracker.py, tutorials/autotvm/tune_conv2d_cuda.py, tutorials/autotvm/tune_nnvm_arm.py, tutorials/autotvm/tune_simple_template.py
1. use a separate logger for autotvm module
2. improve error handling 
3. improve tutorial (add debug help)
=> [AUTOTVM] Improve tutorial and logging

nnvm/python/nnvm/frontend/tensorflow.py
Some cleanup by combining depthwise with convolution.
Cleanup Const, Placeholder, _input_shapes.
=> [NNVM][TENSORFLOW] Cleanup redundant code.

docs/deploy/nnvm.md
=> [DOCS] Neural network Deployment Guide with System Module Mode #1523

nnvm/include/nnvm/top/nn.h, nnvm/python/nnvm/testing/dcgan.py, nnvm/python/nnvm/top/nn.py, nnvm/src/top/nn/convolution.cc, nnvm/tests/python/frontend/mxnet/model_zoo/dcgan.py, python/tvm/autotvm/measure/measure_methods.py, python/tvm/autotvm/task/dispatcher.py, python/tvm/autotvm/task/nnvm_integration.py, python/tvm/autotvm/tophub.py, python/tvm/autotvm/tuner/callback.py, topi/python/topi/arm_cpu/__init__.py, topi/python/topi/arm_cpu/conv2d.py, topi/python/topi/arm_cpu/conv2d_transpose.py, topi/python/topi/arm_cpu/depthwise_conv2d.py, topi/python/topi/nn/conv2d_transpose.py, topi/tests/python/test_topi_conv2d.py, topi/tests/python/test_topi_conv2d_transpose_nchw.py, tutorials/autotvm/tune_nnvm_arm.py, tutorials/nnvm_quick_start.py
* Add conv2d transpose for arm cpu
* Support fallback in autotvm. But it is disabled by default.
=> [TOPI] Add conv2d transpose for arm cpu

docs/nnvm_top.rst
=> [NNVM][DOC] Update NNVM symbol documentation to latest. Ref. #1591

nnvm/src/top/nn/pooling.cc
=> [NNVM][POOL] bug fix. Remove the hardcode.

nnvm/python/nnvm/testing/__init__.py, nnvm/python/nnvm/testing/inception_v3.py, nnvm/python/nnvm/testing/squeezenet.py, nnvm/src/compiler/graph_hash.cc, nnvm/tests/python/frontend/mxnet/model_zoo/__init__.py, nnvm/tests/python/frontend/mxnet/model_zoo/inception_v3.py, nnvm/tests/python/frontend/mxnet/test_graph.py
This symbol is mainly used for performance benchmark
=> [NNVM] Add symbol for inception v3

apps/benchmark/README.md, python/tvm/target.py, tutorials/nnvm/deploy_model_on_rasp.py
=> Add -mattr=+neon for all arm cpu targets

nnvm/python/nnvm/testing/yolo2_detection.py
remove PIL dependency when import nnvm.testing
=> [NNVM] Remove PIL dependency when importing nnvm.testing

nnvm/python/nnvm/top/nn.py, nnvm/python/nnvm/top/transform.py, nnvm/src/top/tensor/transform.cc, nnvm/tests/python/unittest/test_correct_layout.py, topi/include/topi/nn/pooling.h, topi/python/topi/cuda/pooling.py, topi/python/topi/generic/injective.py, topi/python/topi/generic/nn.py, topi/python/topi/opengl/pooling.py, topi/python/topi/x86/injective.py, topi/python/topi/x86/pooling.py, topi/tests/python/test_topi_pooling.py
Improve pooling and concatenate schedule for x86.
1. Change concatenate layout correction to avoid unnecessary layout transformation. Add vectorization to concatenate schedule.
2. Put avg pooling dividing factor inline. Change pooling schedule to use vectorization.
@yidawang @yzhliu
=> Improve x86 Inception

include/tvm/attrs.h, src/lang/attrs.cc
=> [ATTRS] change AttrFiledInfo->Node

nnvm/python/nnvm/frontend/keras.py, nnvm/tests/python/frontend/keras/test_forward.py
This change also supports compiling NASNet.
@Huyuwei Can you review this one?
=> [NNVM][KERAS] Add cropping support

nnvm/python/nnvm/frontend/coreml.py, nnvm/tests/python/frontend/coreml/test_forward.py
The following ops and their corresponding testcases are added to COREML Frontend
=> [FRONTEND][COREML]More ops are added

tutorials/autotvm/tune_conv2d_cuda.py
fix a typo in tutorial found by https://discuss.tvm.ai/t/tune-conv2d-cuda-py-erro/713/6 
@eqy can you review?
=> [AUTOTVM][TUTORIAL] Fix conv2d tutorial

nnvm/python/nnvm/frontend/onnx.py, nnvm/tests/python/frontend/onnx/test_forward.py
The following ops support is added to ONNX
=> [FRONTEND][ONNX]HardSigmoid, min, max, mean ops support

topi/python/topi/testing/conv2d_nhwc_python.py
=> [TEST] Fix incorrect stride in conv2d_nhwc_python

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
This patch adds support for tf.transpose() in tensorflow frontend
=> [FRONTEND][TENSORFLOW] Add Transpose support.

nnvm/src/top/tensor/elemwise.cc
=> Fix comment of binary op 'elemwise_div'

nnvm/python/nnvm/frontend/onnx.py, nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/onnx/test_forward.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
The following ops are merged in tensorflow and onnx
**Onnx**
- Argmax
- Argmin
**Tensorflow**
- Ceil
- Floor
- Elu
- LeakyRelu
- Selu
- Tanh
=> [NNVM]Tensorflow and Onnx basic ops

apps/android_deploy/README.md, apps/android_deploy/build.gradle, apps/android_deploy/dev_tools/sign_apk.sh, apps/android_rpc/build.gradle, apps/android_rpc/dev_tools/sign_apk.sh, docker/Dockerfile.demo_android, docker/bash.sh, docker/build.sh, docker/install/ubuntu_install_androidsdk.sh, docker/install/ubuntu_install_gradle.sh, docker/install/ubuntu_install_java.sh
This PR aims at adding demo_android Dockerfile to the set of other environments. At this stage, I was able to walk through jvm manual and build `app/android_deploy` with this image so I consider it is ready for review. The discussion branch is available at https://discuss.tvm.ai/t/dockerfile-for-mobile-development/629/4
=> Add demo_android Dockerfile

include/tvm/runtime/packed_func.h, python/tvm/_ffi/_ctypes/function.py, python/tvm/_ffi/_ctypes/types.py, src/api/api_test.cc, tests/python/unittest/test_runtime_packed_func.py
=> [RUNTIME] Support TVMContext

src/codegen/codegen_c.cc, topi/tests/python/test_topi_transform.py
fix https://discuss.tvm.ai/t/tvm-cast-int-32-z-does-not-yield-in-opencl-codegen/784/8
=> [CODEGEN] Fix let expression

include/tvm/runtime/c_runtime_api.h, src/codegen/build_module.cc, src/runtime/c_runtime_api.cc, vta/src/device_api.cc
=> [SUBMODULE] update submodule to latest

nnvm/src/top/tensor/reduce.cc, topi/include/topi/reduction.h, topi/src/topi.cc
=> [NNVM] Recover reduction behavir, fix CI

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py, tutorials/nnvm/from_tensorflow.py
By layout conversion of incompatible operations (conv, pool  ..etc) to NCHW.
=> [FRONTEND][TENSORFLOW] GPU support for tensorflow models.

nnvm/tests/python/frontend/keras/test_forward.py
To compare the outputs of Keras and TVM, we should convert the TVM output format from channels_first to channels_last.  Otherwise, the tests of the keras frontend will fail when the target model doesn't contain flatten operators.
=> [TEST][KERAS] convert tvm output to channels_last format

CONTRIBUTORS.md
This PR welcomes @jroesch as a Reviewer of TVM stack. @jroesch leads the proposal and implementations of the high level IR. He is also worked on rust compiler and helps to review the TVM rust binding.
- [Commit history](https://github.com/dmlc/tvm/commits?author=jroesch)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Ajroesch)
- [Relay RFC](https://github.com/dmlc/tvm/issues/1673)
=> [TEAM] jroesch -> Reviewer

CONTRIBUTORS.md
This PR welcomes @siju-samuel  as a Reviewer of TVM stack. He contributed to various aspect, including the TVM runtime as well as various frontend support.
- [Commit history](https://github.com/dmlc/tvm/commits?author=siju-samuel)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Asiju-samuel)
- [Community forum summary](https://discuss.tvm.ai/u/siju-samuel/summary)
=> [TEAM] siju-samuel -> Reviewer

include/tvm/node/node.h, include/tvm/relay/base.h, include/tvm/relay/expr.h, include/tvm/relay/expr_functor.h, src/relay/ir/environment.cc, src/relay/ir/expr_functor.cc, src/relay/pass/type_visitor.h, tests/cpp/expr_test.cc
=> [NODE][RELAY] Move most of the reference related code to node

nnvm/python/nnvm/frontend/keras.py, nnvm/tests/python/frontend/keras/test_forward.py
SimpleRNN and GRU support is added which are required for NLP models.
=> [NNVM]Keras SimpleRnn and GRU support

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
- NCHW end to end support.
- Resnet V1/V2 work fine, added an end to end test case.
- Mean, FusedBatchNormV2 ops added for Resnet.
=> [FRONTEND][TENSORFLOW] NCHW layout support (Resnet V1/V2).

nnvm/src/top/tensor/transform.cc
=> [DOC] Argument name correction.

include/tvm/ir_pass.h, python/tvm/_ffi/runtime_ctypes.py, python/tvm/schedule.py, python/tvm/tensor_intrin.py, src/codegen/codegen_c.cc, src/codegen/verilog/codegen_verilog.cc, src/op/tensorize.cc, src/runtime/pack_args.h, src/runtime/rpc/rpc_session.cc, vta/python/vta/ir_pass.py
=> [DOC]Documentation Errors corrected

docker/Dockerfile.ci_gpu, docker/Dockerfile.demo_gpu, docker/install/ubuntu_install_tensorflow.sh
=> [DOCKER] CUDA upgrade to 9.0 to acommodate tensorflow-gpu (1.10.1).

nnvm/python/nnvm/frontend/onnx.py, nnvm/tests/python/frontend/onnx/test_forward.py
=> [ONNX][FRONTEND] Constantfill - #1539

docker/Dockerfile.demo_opencl, docker/Dockerfile.ocl
Simple, documented, Dockerfile for demonstrating installation with OpenCL & OpenGL enabled.
=> Added Dockerfile demonstrating OpenCL & OpenGL installation

nnvm/tests/python/frontend/tensorflow/test_forward.py
This PR will fix the lstm testcase issue while using get_output with out passing the output size.
=> [NNVM][TENSORFLOW]Fix lstm testcase to support get_output without size input

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
Implements mappings for the TF binary relational operators 'Less', 'LessEqual', 'Greater' and 'GreaterEqual' to NNVM operators and contributes the corresponding tests.
=> Feature: Tensorflow relational operators

include/tvm/relay/pass.h, python/tvm/relay/ir_pass.py, src/relay/pass/type_visitor.h, src/relay/pass/util.cc, tests/python/relay/test_free_vars.py
original: https://github.com/dmlc/tvm/pull/1785
=> [Relay] Free Variables

python/tvm/autotvm/tophub.py, tutorials/nnvm/deploy_ssd.py
* Support multiple targets load in tophub
* improve ssd tutorial
=> [AUTOTVM] Support multiple targets load in tophub

python/tvm/ir_builder.py, tutorials/language/tensorize.py
@cowanmeg @anijain2305 @ZihengJiang @tqchen Pls help to review.
=> [Tutorial] tutorial for tensorize

tests/python/contrib/test_cblas.py, tests/python/contrib/test_cublas.py, tests/python/contrib/test_mps.py, tests/python/contrib/test_nnpack.py, tests/python/contrib/test_random.py, tests/python/contrib/test_rocblas.py, topi/include/topi/nn.h
=> [Doc] Correction in documentation

src/runtime/graph/debug/graph_runtime_debug.cc
=> [RUNTIME] Fix debug runtime i386 build

docker/Dockerfile.ci_cpu, docker/Dockerfile.demo_opencl, docker/install/ubuntu_install_rust.sh, docker/install/ubuntu_install_sgx.sh
=> [DOCKER] Fix CI script

nnvm/Makefile
Updating dmlc-core path in nnvm Makefile. 
CC @tqchen @merrymercy
=> Fix dmlc-core path in nnvm Makefile

docs/langref/relay_op.rst, python/tvm/relay/op/tensor.py, src/relay/op/tensor/unary.cc, tests/python/relay/test_op_level1.py
=> [RELAY] Add sigmoid relay operator

docs/langref/relay_op.rst, python/tvm/relay/op/tensor.py, src/relay/op/tensor/binary.cc, tests/python/relay/test_op_level4.py
=> [RELAY][OP] Left shift operator

docs/langref/relay_op.rst, python/tvm/relay/op/tensor.py, src/relay/op/tensor/binary.cc, src/relay/pass/let_list.h, tests/python/relay/test_op_level4.py
=> maximum relay op V2

docs/langref/relay_op.rst, python/tvm/relay/op/tensor.py, src/relay/op/tensor/unary.cc, tests/python/relay/test_op_level3.py
=> [Relay] [Op] zeros_like and ones_like

docker/Dockerfile.ci_cpu, docker/install/ubuntu_install_golang.sh
=> [DOCKER][GOLANG] Fix golang compiler version to 0.10

apps/sgx/README.md, apps/sgx/enclave/build.rs, apps/sgx/enclave/src/build_model.py
The gitignore was updated in #1597 which was merged after #1825 was created.
=> [SGX] Add ignored files to sgx example

docs/langref/relay_op.rst, include/tvm/relay/attrs/image.h, include/tvm/relay/attrs/nn.h, include/tvm/relay/attrs/vision.h, python/tvm/relay/__init__.py, python/tvm/relay/image.py, python/tvm/relay/op/__init__.py, python/tvm/relay/op/image/__init__.py, python/tvm/relay/op/image/_make.py, python/tvm/relay/op/image/image.py, python/tvm/relay/op/nn/nn.py, python/tvm/relay/op/tensor.py, python/tvm/relay/op/vision/__init__.py, python/tvm/relay/op/vision/_make.py, python/tvm/relay/vision.py, src/relay/op/image/resize.cc, src/relay/op/nn/nn.cc, src/relay/op/nn/pooling.cc, src/relay/op/nn/upsampling.cc, src/relay/op/tensor/binary.cc, src/relay/op/tensor/unary.cc, tests/python/relay/test_ir_op.py, tests/python/relay/test_op_level1.py, tests/python/relay/test_op_level2.py, tests/python/relay/test_op_level3.py, tests/python/relay/test_op_level4.py, tests/python/relay/test_op_level5.py, tests/python/relay/test_type_infer.py
=> [RELAY][OP] Operators.  	 pool2d, global_pool2d, batch_flatten, tanh, sigmoid, floor, ceil, trunc, abs, negative, multiply, mod, pow,  resize

docs/langref/relay_op.rst, python/tvm/relay/op/nn/nn.py, src/relay/op/nn/nn.cc, src/relay/op/op_common.h, src/relay/op/tensor/binary.cc, src/relay/op/tensor/unary.cc, tests/python/relay/test_op_level1.py
I had lifted RELAY_REGISTER_UNARY_OP as I found relu also needing it.
=> [Relay] [Op] add relu

docs/langref/relay_op.rst, include/tvm/relay/attrs/transform.h, nnvm/src/top/tensor/transform.cc, python/tvm/relay/op/transform.py, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level3.py
=> [RELAY][OP] take

docs/contribute/pull_request.rst
I run:
````bash
TVM_TUTORIAL_EXEC_PATTERN=/contribute make html
````
And the page renders correctly.
Also in order to build gtest, we need this commit: https://github.com/dmlc/dmlc-core/commit/bb5e6c271e50ef9442912694adf41548f3c452d8
=> Add instructions to run tests locally

docs/langref/relay_op.rst, include/tvm/relay/attrs/transform.h, python/tvm/relay/op/transform.py, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level3.py
Pretty straightforward operators to add, but would appreciate any guidelines on style and on having negative test cases (really unsure about how to set those up).
=> [Relay][Op] Add operators full and full_like

apps/sgx/Makefile, apps/sgx/README.md, apps/sgx/enclave/Cargo.toml, apps/sgx/enclave/Makefile, apps/sgx/enclave/Xargo.toml, apps/sgx/enclave/enclave_config.xml.in, apps/sgx/enclave/sgx-deps.diff, apps/sgx/enclave/x86_64-unknown-linux-sgx.json, apps/sgx/run_example.sh, docker/install/ubuntu_install_rust.sh, docker/install/ubuntu_install_sgx.sh, rust/src/lib.rs
You'd think that I would have ensured that things worked properly, right?
This is bad and I do feel bad.
I'll rebase #1851 and #1855 once this is merged since it updates the `rustc` version (not that it actually changes anything, though).
=> Update SGX example

docs/api/python/nnvm/frontend.rst
=> [Doc] Update frontend.rst

docs/langref/relay_op.rst, python/tvm/relay/op/transform.py, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level4.py
Add the `where` operator. BTW, I think **where** is not good name for this operator. It actually performs similarly what `blend` instruction does in x86 (https://www.felixcloutier.com/x86/BLENDVPS.html).
CC @tqchen @yzhliu
=> Add relay.where

docs/langref/relay_op.rst, include/tvm/relay/attrs/nn.h, python/tvm/relay/op/nn/nn.py, src/relay/op/nn/pad.cc, tests/python/relay/test_op_level2.py
This was not very conceptually difficult; please review to ensure that all is in order and according to proper conventions.
=> [Relay][Op] Pad operator

include/tvm/tensor_intrin.h, python/tvm/contrib/clang.py
Expose TensorIntrin::make and search clang.exe
=> Fixes for tensorize in Windows build

docs/langref/relay_op.rst, include/tvm/relay/attrs/transform.h, python/tvm/relay/op/tensor.py, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level3.py
Right now no default are use for them. Maybe we should change that...
Another thing is I dont think it is possible to do backward inference on zeros/ones. Is it so?
=> [Relay] [Op] Zeros, Ones

src/pass/storage_flatten.cc, tests/python/unittest/test_pass_storage_flatten.py
=> Support double buffer to use in ir builder DSL

python/tvm/contrib/debugger/debug_runtime.py, src/runtime/graph/debug/graph_runtime_debug.cc, tests/python/unittest/test_runtime_graph_debug.py
=>  [RUNTIME][DEBUG]Support remote graph debugging via rpc

tests/scripts/task_python_docs.sh
@tqchen please take a look, it should fix the integration test failure: http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-1912/1/pipeline
=> [DOC]Clear javadoc directory everytime

docs/dev/index.rst
Update debugger in index to reflect in [docs.tvm.ai](https://docs.tvm.ai/dev/index.html) under the **Design and Developer Guide**
=> [DOCS]Update debugger in docs.tvm.ai

docs/langref/relay_op.rst, include/tvm/relay/type.h, python/tvm/relay/__init__.py, python/tvm/relay/op/__init__.py, python/tvm/relay/op/reduce.py, src/relay/op/tensor/reduce.cc, src/relay/pass/type_solver.cc, tests/python/relay/test_op_level4.py
#1799 
After this review, I will do **sum,  max,  & prod** which are similar
=> [RELAY][OP]Reduction operator framework, argmax, argmin

tutorials/autotvm/tune_nnvm_x86.py
@kevinthesun Could you verify?
=> Fix x86 Conv tuning tutorial

python/tvm/module.py
=> Fix typo in module.py line 90

src/relay/ir/text_printer.cc
=> [Relay] format text_printer.cc

src/lang/buffer.cc, tests/python/unittest/test_lang_buffer.py
=> Fix non-zero extent of access_ptr out of range

python/tvm/relay/ty.py
=> [Relay] fix format in ty.py

python/tvm/autotvm/tophub.py
=> update tophub for x86

CONTRIBUTORS.md
This PR welcomes @xqdan as a Reviewer of the TVM stack. He contributed mostly to low-level IR improvement and AI chip backend (WIP). His expertise on low-level optimization and hardwares, especially ASICs will help reviewing related features in TVM.
* [Commit history](https://github.com/dmlc/tvm/commits?author=xqdan)
* [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Axqdan)
* [Community forum summary](https://discuss.tvm.ai/u/xqdan/summary)
=> [TEAM] xqdan -> Reviewer

include/tvm/relay/type.h
=> [Relay] visit the span

include/tvm/relay/expr.h, include/tvm/relay/type.h
=> [Relay] remove dead definition

src/relay/pass/type_solver.cc, tests/cpp/relay_pass_type_infer_test.cc, tests/python/relay/test_type_infer.py
I also added a cpp test file to demonstrate cpp API and facilitate easier debugging. 
Following test [guide](https://docs.tvm.ai/contribute/pull_request.html), cpp tests all pass. some python tests failed but I think they are preexisting. 
@tqchen @MarisaKirisame @jroesch welcome to review.
=> [RELAY] Add occurs check before unification

include/tvm/relay/expr.h
=> [Relay] visit span

nnvm/python/nnvm/frontend/tensorflow.py
TF 1.11.0 somehow add an attr "Truncate" in cast, results failure: http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/detail/PR-1993/5/pipeline/233/
@srkreddy1238 @tqchen Pls double check.
=> [Frontend][Tensorflow] ignore Truncate in cast

docker/README.md, docker/install/ubuntu_install_golang.sh, tests/scripts/task_golang.sh
=> [DOCKER][GOLANG] fix golang version.

python/tvm/relay/testing/__init__.py, python/tvm/relay/testing/dqn.py, tests/python/relay/test_ir_text_printer.py
=> [Relay] DQN Port

src/relay/op/tensor/transform.cc, src/relay/pass/type_infer.cc, tests/python/relay/test_op_level1.py
THanks @siju-samuel for reporting this
=> [RELAY][OP]  Maketuple to be resolved when containing incompleteType

CONTRIBUTORS.md
This PR welcomes @zhiics as a Reviewer of the TVM stack. He contributed mostly to the heterogeneous runtime. He is also very active on reviewing PRs and answering questions on the forum. I am glad to nominate him as a reviewer member of TVM community.
- [Commit history](https://github.com/dmlc/tvm/commits?author=zhiics)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Azhiics)
- [Community forum summary](https://discuss.tvm.ai/u/zhiics/summary)
=> [TEAM] New Reviewer: zhiics

python/tvm/relay/testing/__init__.py, python/tvm/relay/testing/mobilenet.py, tests/python/relay/test_ir_text_printer.py
Pattern-matching port of NNVM MobileNet to Relay.
This is not yet deeply tested (e.g., using TVM Runtime or end2end evaluation).
=> [RELAY] MobileNet Port

docs/api/python/topi.rst, docs/nnvm_top.rst, nnvm/python/nnvm/frontend/mxnet.py, nnvm/python/nnvm/top/transform.py, nnvm/src/top/tensor/transform.cc, nnvm/tests/python/compiler/test_top_level1.py, nnvm/tests/python/unittest/test_infer_shape.py, topi/include/topi/transform.h, topi/python/topi/testing/__init__.py, topi/python/topi/testing/gather_nd_python.py, topi/python/topi/transform.py, topi/src/topi.cc, topi/tests/python/test_topi_transform.py
Add gather_nd op into NNVM and Topi.
=> [NNVM/TOPI][OP] gather_nd

tutorials/language/tensorize.py
According to suggestion from @yidawang Please review.
=> Print import_llvm ir in tensorize tutorial

topi/tests/python/test_topi_conv2d_int8.py
=> [TOPI][TEST] Add a testcase of dilated int8 conv2d on cuda

nnvm/python/nnvm/frontend/onnx.py, nnvm/tests/python/frontend/onnx/test_forward.py
fixed issue #2037 
cc @nishi-t @siju-samuel @yzhliu welcome to review. thanks
=>  [FRONTEND][ONNX] fixed operator converter for Split in onnx frontend

topi/include/topi/reduction.h
@tqchen @yzhliu is it ok without a case?
=> Fix asan check heap-use-after-free

nnvm/include/nnvm/top/tensor.h, nnvm/python/nnvm/frontend/mxnet.py, nnvm/src/top/tensor/reduce.cc, nnvm/tests/python/frontend/mxnet/test_forward.py, topi/python/topi/cuda/reduction.py
This PR supports argmax and argmin for MXNet. Since output dtype is fp32, I added dtype interface to nnvm.
@tqchen @nishi-t @masahi could you review? Thanks!
=> [Frontend][MXNet] argmax, argmin ops support

topi/python/topi/cuda/conv2d_int8.py
I found that condition of vectorization is unnecessary because we can always use vectorization here. Now this schedule should be faster.
cc @merrymercy
=> [TOPI] Improve conv2d int8 schedule on CUDA

Jenkinsfile
Follow up from https://github.com/dmlc/tvm/pull/2085.
=> [Jenkinsfile] Build NNPACK and run tests in `ci-cpu`

src/relay/pass/fuse_ops.cc
=> [Relay] Fix error in fuse_ops.cc

src/relay/pass/fuse_ops.cc
=> Fix error in fuse_ops.cc

src/relay/pass/fuse_ops.cc, tests/python/relay/test_pass_fuse_ops.py
Fix a problem where previously broadcast op to the input of conv2d can be mistakenly fused into conv2d (forbidden in the current rule). A regression test is added
cc @jroesch
=> [RELAY][PASS] FuseOps, fix input fusion rule for conv2d

src/relay/ir/type_functor.cc
=> [RELAY] bugfix type functor caching

tests/python/contrib/test_nnpack.py
to avoid problems in CI, until the fix mentioned by @ajtulloch
=> [NNPACK] temporary disable nnpack test

docs/install/from_source.rst
=> Docs: Fix links

python/tvm/contrib/nnpack.py, src/contrib/nnpack/nnpack_utils.cc, tests/python/contrib/test_nnpack.py
This fixes issues with failing tests on PowerPC. Fixes #2109.
=> [NNPACK] Add check for NNPACK being available (`nnp_initialize()` succeeding)

python/tvm/relay/op/nn/_nn.py, src/relay/op/nn/nn.cc, tests/python/relay/test_op_level1.py
Please help to review @jroesch @tqchen 
https://github.com/dmlc/tvm/issues/2051
=> [Relay] compute & schedule for relu, softmax

python/tvm/autotvm/tophub.py, topi/python/topi/x86/conv2d.py
=> [TOPHUB] fix x86 backend after introducing dilation

README.md
=> Update README.md due to typo

include/tvm/relay/attrs/nn.h, python/tvm/relay/op/nn/_nn.py, src/relay/op/nn/nn.cc, tests/python/relay/test_op_level2.py, tests/python/relay/test_op_level3.py
=> [RELAY]sch & comp for ops in nn.py

CONTRIBUTORS.md
This PR welcomes @Laurawly as committer of TVM stack. She creates the topi support for CUDA and intel graphics. 
- [Commit history](https://github.com/dmlc/tvm/commits?author=Laurawly)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3ALaurawly)
- [Community forum summary](https://discuss.tvm.ai/u/Laurawly/summary)
=> [TEAM] Laurawly -> committer

topi/python/topi/x86/conv2d.py
Fixed the issue in https://discuss.tvm.ai/t/the-latest-master-cant-find-depthwise-conv2d-op/1163
Please review @yzhliu
=> [TOPI] Fix relative import in x86 conv2d

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
Added support for multiple outputs in TensorFlow frontend. Made fixes to test_forward.py.
=> [TensorFlow] User can provide list of outputs to from_tensorflow()

nnvm/python/nnvm/frontend/tensorflow.py, nnvm/tests/python/frontend/tensorflow/test_forward.py
=> [FRONTEND][TENSORFLOW] Enable strided_slice with fix.

nnvm/python/nnvm/frontend/tensorflow.py
=> [FRONTEND][TENSORFLOW] Fix a typo in _matmul

nnvm/python/nnvm/top/nn.py, topi/python/topi/cuda/conv2d_winograd.py
=> [TOPI][CUDA] Alter op layout for group_conv2d

apps/howto_deploy/cpp_deploy.cc, docs/faq.md
fix link (https://docs.tvm.ai/faq.html)
=> [DOCS] fix link

python/tvm/relay/base.py, python/tvm/relay/build_module.py, python/tvm/relay/op/nn/_nn.py, src/relay/op/nn/upsampling.cc, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level2.py
@srkreddy1238 @siju-samuel  @yzhliu please review.
=> [Relay] Register compute and schedule for upsampling, with miscellaneous fixes

python/tvm/relay/testing/__init__.py, python/tvm/relay/testing/densenet.py, tests/python/relay/test_ir_text_printer.py
This contains a port of the MxNet implementation of Densenet (https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/vision/densenet.py) to Relay. Is there more that should be included to indicate the attribution?
=> [Relay] Densenet benchmark

python/tvm/relay/op/image/__init__.py, python/tvm/relay/op/image/_image.py, src/relay/op/image/resize.cc, tests/python/relay/test_op_level5.py
=> [Relay]resize op compute and schedule

tutorials/nnvm_quick_start.py
=> fixing nnvm tutorial typo

nnvm/python/nnvm/frontend/tensorflow.py
@srkreddy1238 Could you please review this, thanks.
=> [FRONTEND][TENSORFLOW] Support AttrValue that has different types of value in a list

topi/include/topi/transform.h, topi/python/topi/transform.py, topi/src/topi.cc, topi/tests/python/test_topi_matmul.py
=> [TOPI] Add tensor multiplication.

python/tvm/build_module.py
tvm.Schedule ==> tvm.schedule.Schedule
=> [DOCS] Update comments for the API tvm.lower

CONTRIBUTORS.md
This PR welcomes @grwlf as a reviewer to TVM.  He has contributed to several improvements in terms of TF and docker. He is also quite active in the forum in helping out answering questions. More importantly, by looking at code-reviews that he has done so far. I find that he has good knowledge of system level programming and provided helpful comments to ensure a high-quality code.
- [Commits History](https://github.com/dmlc/tvm/commits?author=grwlf)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Agrwlf)
- [Community Forum Summary](https://discuss.tvm.ai/u/grwlf/summary)
=> [COMMUNITY] @grwlf -> Reviewer

docker/Dockerfile.ci_cpu
=> [Relay] Install ANTLR on CPU Docker

python/tvm/relay/op/_transform.py, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level10.py
=> [Relay]collapse_sum and broadcast_to compute & schedule

src/arithmetic/canonical.cc, tests/python/unittest/test_arith_simplify.py
=> [TVM] Fix segfault for CanonicalSimplify(x % -1)

python/tvm/contrib/cc.py, python/tvm/module.py
=> fix llvm dependency bug

src/op/compute_op.cc, tests/python/unittest/test_schedule_schedule_ops.py
=> [SCHEDULE] Fix code lowering when loop condition depends on outer axis.

docker/with_the_same_user
=> [DOCKER] inheritate javahome

python/tvm/relay/op/transform.py, tests/python/relay/test_op_level3.py
=> [RELAY] bugfix.

src/relay/ir/alpha_equal.cc, src/relay/ir/text_printer.cc, tests/python/relay/test_ir_parser.py
=> [Relay] Parser Tests

python/tvm/contrib/debugger/debug_result.py
@siju-samuel Please help review, thanks!
=> [DEBUG]Fix debugger message mess in display_debug_result

python/tvm/relay/build_module.py, src/relay/pass/fold_scale_axis.cc, src/relay/pass/pattern_util.h, tests/python/relay/test_pass_fold_scale_axis.py
=> [RELAY][PASS] Check Positiveness in FoldScaleAxis

include/tvm/runtime/c_backend_api.h
=> [typo] fucntion ==> function

include/tvm/runtime/util.h
=> [typo] sin ==> in

python/tvm/build_module.py
@tqchen this fix a problem of missing dump ir for passes except scheduleOps and custom passes.
=> fix dump ir

tutorials/cross_compilation_and_rpc.py
=> Fix misprint

nnvm/src/pass/infer_shape_type.cc, python/tvm/relay/ty.py, python/tvm/relay/ty.pyi, rust/src/runtime/c_runtime_api.rs, src/api/api_test.cc, src/relay/backend/compile_engine.cc, src/runtime/cuda/cuda_module.cc, src/runtime/metal/metal_module.mm, src/runtime/rocm/rocm_module.cc, src/runtime/vulkan/vulkan_module.cc
=> [typo] fucn => func

python/tvm/hybrid/parser.py, python/tvm/hybrid/util.py, python/tvm/hybrid/var_decl.py, tests/python/unittest/test_hybrid_script.py
@kevinthesun 
Last time augmented op was rolled back because of the test failure.
As you wanted, using `tvm.const(1, 'int32')` in parameter list is allowed now, and this const is not required to be passed to the built module. It is already embedded in the IR body.
=> [HYBRID FRONTEND] Augmented op added; const parameter enabled

src/schedule/message_passing.cc
=> Generate predicates for non-root iteration variables as well

CONTRIBUTORS.md
This PR welcomes @ajtulloch as a reviewer to TVM. He has contributed to several improvements in terms of Caffe and NNPack. He is also quite active in the forum in helping out answering questions and participating in discussion for new features and roadmap. He also has good knowledge of high performance kernel implementation and provided helpful comments to ensure a high-quality code.
- [Commits History](https://github.com/dmlc/tvm/commits?author=ajtulloch)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aajtulloch)
- [Community Forum Summary](https://discuss.tvm.ai/u/ajtulloch/summary)
=> [COMMUNITY] @ajtulloch -> Reviewer

python/tvm/hybrid/parser.py, tests/python/unittest/test_hybrid_script.py
@kevinthesun Can you have a look?
=> [Hybrid Script] Support logical and/or; support 0 < a < 5 clause

src/lang/reflection.cc, src/relay/ir/op.cc, tests/python/relay/test_ir_nodes.py
This PR fixes two serialization issues I encountered while trying to save Relay models to disk. 
Provides two repros and fixes to them cc @tqchen @ZihengJiang.
=> [RELAY] Fix serialization issue

nnvm/python/nnvm/frontend/onnx.py, nnvm/tests/python/frontend/onnx/test_forward.py
Onnx was lacking many testcases. This will b helpful to validate onnx ops once we transform onnx to relay.
=> Update onnx testcases

nnvm/python/nnvm/frontend/tensorflow.py
=> [FRONTEND][TENSORFLOW] Bugfix 

python/tvm/contrib/sdaccel.py
=> 【typo】Xlinx => Xilinx

docs/install/from_source.rst
=> [DOC] fix installation doc

Jenkinsfile
=> [CI] Golang unit test trigger for Jenkins

nnvm/python/nnvm/to_relay.py
=> [RELAY] Support concatenate from nnvm

docs/langref/relay_op.rst, python/tvm/relay/op/_transform.py, python/tvm/relay/op/transform.py, src/relay/op/nn/pooling.cc, src/relay/op/tensor/transform.cc, tests/python/relay/test_op_level10.py
Add broadcast_to operator for Relay.  cc @siju-samuel @MarisaKirisame @tqchen
=> [RELAY] Add broadcast_to operator

include/tvm/relay/attrs/vision.h, python/tvm/relay/op/vision/multibox.py, src/relay/op/vision/multibox_op.cc, tests/python/relay/test_op_level5.py
It looks that multibox_transform_loc op is missing. 
@tqchen @yzhliu @kevinthesun
=> [relay][op] multibox_transform_loc

CONTRIBUTORS.md
This PR welcomes Eddie Yan @eqy to become a committer to TVM. He has contributed to many areas in TVM, including AMD GPU optimization, AutoTVM, RPC, runtime, Android, and Relay. He has been very active in answering questions in the forum and performing code reviews.
- [Commits](https://github.com/dmlc/tvm/commits?author=eqy)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aeqy)
- [Forum](https://discuss.tvm.ai/u/eqy/summary)
=> [COMMUNITY] @eqy -> Committer

src/relay/backend/graph_plan_memory.cc
=> [BUGFIX] Seg fault in memory planing for symbolic shape

topi/python/topi/cuda/conv2d_int8.py
This makes reduction order and cache size more flexible . Tested on resnet layers, it provides ~7% speedup.
cc @tqchen @merrymercy @masahi
=> [TOPI][CUDA] Add reorder option in int8 conv2d

CONTRIBUTORS.md
This PR welcomes @srkreddy1238 as a new Committer of the TVM stack. He has been actively contributing to the frontends, including TF and DarkNet, and more recently the golang binding. He is also active in the community forum to help members in the community. Finally, he holds a high standard and provides helpful feedbacks during his code reviews 
- [Commits](https://github.com/dmlc/tvm/commits?author=srkreddy1238)
- [Code Reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Asrkreddy1238)
- [Community Forum Summary](https://discuss.tvm.ai/u/srkreddy1238/summary)
=> [COMMUNITY] @srkreddy1238 -> Committer

Jenkinsfile, tests/scripts/task_python_frontend.sh, tests/scripts/task_python_integration.sh
=> [TEST] Setup frontend stage

topi/include/topi/image/resize.h, topi/python/topi/cuda/vision.py, topi/python/topi/generic/vision.py, topi/python/topi/testing/__init__.py, topi/python/topi/testing/roi_align_python.py, topi/python/topi/vision/__init__.py, topi/python/topi/vision/rcnn/__init__.py, topi/python/topi/vision/rcnn/roi_align.py, topi/src/topi.cc, topi/tests/python/test_topi_vision.py
Please review @merrymercy @masahi @FrozenGene @tqchen
=> [TOPI] Add roi align

python/tvm/relay/op/op.py, src/relay/backend/compile_engine.cc
=> [Relay] Fix typos in Relay

src/contrib/nnpack/convolution.cc
This PR preallocates workspace buffer for input/output winograd transform, which can take a significant amount of time on android.
@ajtulloch, please review
=> [nnpack] Preallocate workspace buffer

Makefile, python/tvm/exec/rpc_proxy.py, tests/web/prepare_test_libs.py, tests/web/test_basic.js, tests/web/test_module_load.js, tests/web/test_packed_func.js, web/README.md, web/web_runtime.cc
=> Fix Web Build after CMake transition.

src/codegen/llvm/llvm_common.cc, tests/python/unittest/test_codegen_llvm.py
=> [LLVM CodeGen] Partially disable unsafe fp math

python/tvm/hybrid/parser.py
=> [Hybrid Script] [Quick Fix] allow const_range allocation; preprove if-then-else

python/tvm/relay/backend/interpreter.py
Add simplify inference pass in the Relay interpreter so that it can execute models with batch norm and dropout.
=> [Relay][Runtime] Add simplify inference pass in the Relay interpreter

python/tvm/hybrid/parser.py, tests/python/unittest/test_hybrid_script.py
=> [Hybrid Script] allow const_range allocation; allow const_range lazy compilation

tutorials/relay/from_onnx.py
Fixed a minor bug in the onnx relay frontend.
=> [Relay][ONNX] fix bug in from_onnx

nnvm/python/nnvm/frontend/tensorflow.py
Ref. https://discuss.tvm.ai/t/solved-tensorflow-frontend-resize-bilinear-infer-shape-wrong/1484
=> [NNVM][TENSORFLOW] bugfix.

docs/api/python/contrib.rst, docs/api/python/relay/frontend.rst, docs/api/python/topi.rst
docs for some new modules has been updated.
=> Update docs for some new modules

python/tvm/relay/build_module.py, tests/python/relay/test_pass_annotation.py
This PR refactors the build interface for heterogeneous compilation by moving `fallback_device` from the interface to `build_config`. See #2449 for details.
CC' @tqchen @jroesch @yzhliu
=> [relay][compilation] refactoring: move fallback out of the build interface

docker/Dockerfile.ci_gpu, docker/Dockerfile.demo_cpu, docker/Dockerfile.demo_gpu, docker/install/ubuntu_install_gluoncv.sh
=> [DOCKER] Add gluoncv installation

python/tvm/exec/rpc_server.py, python/tvm/rpc/base.py, python/tvm/rpc/proxy.py, python/tvm/rpc/server.py, python/tvm/rpc/tracker.py, src/common/socket.h, src/runtime/rpc/rpc_socket_impl.cc
We mainly make the auto-tuning work under both IPV4 and IPV6 network.
=> [RPC] Add the IPV6 support for server side auto tuning

rust/tests/test_nnvm/build.rs
=> [RUST] Fix NNVM test build failure condition

tutorials/nnvm/deploy_model_on_rasp.py
=> fix deploy_model_on_rasp.py spell error.

src/relay/op/nn/pooling.cc, src/relay/op/tensor/transform.cc, tests/python/relay/test_pass_alter_op_layout.py
* Add missing `FInferCorrectLayout` register 
* Support packed layout in pooling
please review @merrymercy
=> [RELAY] Fix ops in packed layout

include/tvm/runtime/packed_func.h
=> Remove an obsolete comment

tutorials/autotvm/tune_nnvm_mobile_gpu.py
Fix typo in Evaluate inference time cost code
=> Fix typo in Evaluate inference time cost code

CONTRIBUTORS.md
This PR add @FrozenGene to the reviewer list of tvm. FrozenGene has been actively involved in discussions and contribution on the frontend of TVM, also has made some great feedbacks on document improvements.
- [Commits History](https://github.com/dmlc/tvm/commits?author=FrozenGene)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3AFrozenGene)
- [Community Forum Summary](https://discuss.tvm.ai/u/frozengene/summary)
=> [COMMUNITY] @FrozenGene -> Reviewer

include/tvm/runtime/device_api.h, src/relay/op/layout.h, src/runtime/graph/debug/graph_runtime_debug.cc, src/runtime/graph/graph_runtime.h, topi/tests/python/test_topi_math.py, vta/src/runtime.cc
Thanks to @alexeyr  and @cloudhan for comments. Normally we should wait for the contributor to send in the patch. Given that we are close to 0.5, I take the deliberation to quickly fix them so they can be included as 0.5
Also, tag the original authors @tmoreau89 @siju-samuel 
fixes #2555 #2541 #2540 #2538 #2551
=> Misc refactor on graph runtime, layout node

CONTRIBUTORS.md
This is the pull request to bring Lianmin Zheng @merrymercy as a PMC member of TVM. One of the PMC duties is to grow the community and oversee the long term direction of the project. As one of the authors of AutoTVM, Lianmin has been actively using his expertise to manage the project lately and help to shepherd new contributors, besides a large number of code contributions.
Commits:
https://github.com/dmlc/tvm/commits?author=merrymercy
Code Review:
https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Amerrymercy
Forum:
https://discuss.tvm.ai/u/merrymercy/activity
@dmlc/tvm-committer
=> [COMMUNITY] @merrymercy -> PMC

python/tvm/build_module.py, python/tvm/contrib/debugger/debug_runtime.py, src/runtime/thread_storage_scope.h, tutorials/dev/low_level_custom_pass.py, tutorials/get_started.py
Hi, pals!
those are some fixes and improvements I found setting up my development with TVM. Please, consider them and review this PR. @tqchen please take a look. Honestly, I don't know if I picked up right person to address this PR, so reassign it if appropriate
=> A couple of fixes for GEN

nnvm/python/nnvm/to_relay.py
@icemelon9 @anijain2305 Please review.
=> [Bugfix] get layout in to_relay

src/relay/pass/device_annotation.cc, tests/python/relay/test_pass_annotation.py
This PR fixes a bug in heterogeneous annotation that it mistakenly steps into the fused op.
@yzhliu @jroesch @kazum @imorinaga please review, thanks.
=> [Relay]fix heterogenous annotation bug

python/tvm/autotvm/measure/measure_methods.py, tutorials/autotvm/tune_relay_arm.py, tutorials/autotvm/tune_relay_cuda.py, tutorials/autotvm/tune_relay_mobile_gpu.py
Fix https://github.com/dmlc/tvm/issues/2617
Note: In future we should get avoid using ```localhost``` to avoid similar issue
=> [autotvm] fix #2617

python/tvm/relay/expr_functor.py, tests/python/relay/test_expr_functor.py
Follow up PR with tests for #2601.
=> Add follow up test case for #2601

nnvm/python/nnvm/frontend/mxnet.py, nnvm/tests/python/frontend/mxnet/test_forward.py, python/tvm/relay/frontend/mxnet.py, tests/python/frontend/mxnet/test_forward.py
...for both NNVM and Relay. Corresponding tests added. @icemelon9 @yzhliu
=> [Frontend][MXNet] Add MXNet frontend converter for where operator

src/relay/pass/mac_count.cc, tests/python/relay/test_pass_mac_count.py
=> [RELAY][PASS]use attribute registration style in the mac count pass

src/relay/pass/to_anf.cc, tests/python/relay/test_to_anf.py
=> [Relay] fix anf for reference and pattern matching

CONTRIBUTORS.md
This PR welcomes @jroesch as a new Committer of the TVM stack. He is one of the major contributors to Relay and he also participates in the design of many modules around Relay such as automatic differentiation, interpreters, optimization passes, etc. He performs many code reviews, and participates in TVM discussion board actively.
* [Commits](https://github.com/dmlc/tvm/commits?author=jroesch)
* [Code Reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ajroesch)
* [Community Forum Summary](https://discuss.tvm.ai/u/jroesch/summary)
=> [COMMUNITY] @jroesch -> Committer

python/tvm/relay/backend/interpreter.py, python/tvm/relay/prelude.py, src/relay/ir/module.cc, src/relay/pass/type_solver.cc, tests/python/relay/test_adt.py
=> [Relay] add more function to prelude

include/tvm/relay/expr.h, src/relay/ir/expr.cc
=> [Relay] add more descriptive error for checked_type

tutorials/frontend/from_coreml.py
@zhreshold @zhiics, please help to review.
=> [DOC] CoreML frontend tutorial

nnvm/python/nnvm/to_relay.py
Support mean in NNVM to Relay converter.
=> Support mean in NNVM to Relay converter.

src/arithmetic/int_set.cc
This is to fix #2686.
@tqchen , @sgrechanik-h,, and/or @ZihengJiang please review. It's a very small fix.
=> [TVM][ARITH] Handle Select in IntSetEvaluator

src/relay/op/type_relations.cc
=> [Relay][Doc] Separate arguments types formatting with comma

tutorials/frontend/from_mxnet.py
@zhreshold @jroesch @yzhliu, please help to review.
=> [DOC] MXNet frontend tutorial

docs/install/from_source.rst
=> Few docs fixes

nnvm/python/nnvm/frontend/mxnet.py, nnvm/tests/python/frontend/mxnet/test_forward.py
...for NNVM. @icemelon9 @yzhliu
=> [Frontend] [MXNet] MXNet converter for _minimum and _maximum

tutorials/relay/deploy_model_on_rasp.py
@ZihengJiang @zhreshold @jroesch @yzhliu @kazum, please help to review.
=> [DOC][Relay] Deploy the Pretrained Model on Raspberry Pi

python/tvm/relay/frontend/mxnet.py, tests/python/frontend/mxnet/test_forward.py
=> [Relay][Frontend] Add a few mxnet ops in relay frontend

docs/install/from_source.rst, tutorials/relay_quick_start.py
1. attrs is required for relay.
2. link is broken.
https://docs.tvm.ai/tutorials/index.html
=> [DOCS] Fix tutorial

docs/contribute/pull_request.rst
=> Docs: pip dependencies for testing

CONTRIBUTORS.md
This PR add @sgrechanik-h to the reviewer list of tvm. sgrechanik-h has been actively involved in discussions and contribution on the high-level IR.
- [Commits History](https://github.com/dmlc/tvm/commits?author=sgrechanik-h)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Asgrechanik-h)
- [Community Forum Summary](https://discuss.tvm.ai/u/sgrechanik-h/summary)
=> [COMMUNITY] @sgrechanik-h -> Reviewer

python/tvm/relay/frontend/mxnet.py, tests/python/frontend/mxnet/test_forward.py
Bug fix in Relay MxNet frontend converter for slice_axis when axis is negative.
Thanks @kevinthesun reporting the bug.
=> [Relay][Frontend][Bugfix] Fix bug in converting slice_axis when axis is negative

conda/nnvm/meta.yaml, conda/topi/meta.yaml, conda/tvm-libs/meta.yaml, conda/tvm/meta.yaml, include/tvm/runtime/c_runtime_api.h, python/tvm/_ffi/libinfo.py, version.py, web/tvm_runtime.js
=> [VERSION] Update to 0.6.dev

python/tvm/_ffi/_ctypes/ndarray.py
=> [DLPACK] fix flaky ctypes support

CONTRIBUTORS.md
This PR add @wweic to the reviewer list of tvm, he has been actively involved in discussions and contribution to the high-level IR.
- [Commits History](https://github.com/dmlc/tvm/commits?author=wweic)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Awweic)
- [Community Forum Summary](https://discuss.tvm.ai/u/wweic/summary)
=> [COMMUNITY] @wweic -> Reviewer

python/tvm/relay/backend/graph_runtime_codegen.py, src/runtime/graph/graph_runtime.h
=> [GRAPH] Include default metadata description in graph.

apps/ios_rpc/init_proj.py
=> Fix init_proj.py: Team ID expected

apps/ios_rpc/tvmrpc/TVMRuntime.mm
=> tvmrpc: Fix includes

CONTRIBUTORS.md
Please join us to welcome @kazum as a new committer to the TVM community. He has been actively contributing to the frontend, tutorials, opencl runtime as well as providing helpful code reviews for the community,
- [Commits](https://github.com/dmlc/tvm/commits?author=kazum)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Akazum)
- [Forum summary](https://discuss.tvm.ai/u/kazum/summary)
=> [COMMUNITY] @kazum -> committer

python/tvm/contrib/xcode.py
=> xcode.py: Decode bytes before output

python/tvm/contrib/xcode.py
=> Fix Xcode 10 metal compile error

Jenkinsfile, docker/Dockerfile.ci_gpu
cc @hlu1 , need to retrigger your PR after this is merged
=> [DOCKER] Update ci-gpu to include NNPack

apps/ios_rpc/README.md, apps/ios_rpc/tests/ios_rpc_test.py
=> Update iOS RPC README

docker/install/ubuntu_install_rust.sh
=> Pin rust version used to compile tools

Jenkinsfile
@tqchen, the Jenkinsfile needs to be updated as well
=> [Docker] Enable NNPACK for ci_gpu

cmake/config.cmake
=> fix typos: 4x "disbale" to "disable"

src/lang/data_layout.cc
=> Fix error reporting for missing axis

include/tvm/relay/pass.h
=> [Relay] Add TVM_DLL for ANF/GNF conversion

python/tvm/relay/op/nn/_nn.py
Added missing dispatch to int8 group_conv2d_nchw in relay.
=> [Relay][Op] Add group conv2d dispatch to topi function

Jenkinsfile
=> [DOCKER] Upgrade ci-cpu to latest v0.50

CONTRIBUTORS.md
Dear Community:
Please join us to welcome the Apache incubator mentors. They are
- Markus Weimer @markusweimer 
- Sebastian Schelter @sscdotopen
- Byung-Gon Chun @bgchun
- Henry Saputra @hsaputra
- Timothy Chen @tnachen
- Furkan KAMACI @kamaci
Mentors are members of Apache incubator that will help us go through the incubation process, together with the PMC members. They help to shape up the proposals and provide guidance over community development. 
NOTE: this thread will be cross-posted automatically to dev@
=> [COMMUNITY] Welcome Apache Incubator Mentors

cmake/config.cmake, tutorials/frontend/deploy_ssd_gluoncv.py
=> Turn on USE_SORT by default

python/tvm/relay/op/_tensor_grad.py, tests/python/relay/test_pass_gradient.py
=> [Relay] add test for second order ad

python/tvm/relay/op/_tensor_grad.py, tests/python/relay/test_pass_gradient.py
Reverts dmlc/tvm#2754
cc @MarisaKirisame  please send another PR to fix things and add it back
=> Revert "[Relay] add test for second order ad"

python/tvm/autotvm/measure/measure_methods.py, python/tvm/contrib/cc.py, python/tvm/contrib/tar.py, python/tvm/contrib/xcode.py
Followup on #2909 
- Add output_format to build_func
- Only require the LocalBuilder to take a fcompile function instead.
=> [AUTOTVM] Refactor measure build func

python/tvm/exec/measure_peak.py, python/tvm/exec/query_rpc_tracker.py, python/tvm/exec/rpc_proxy.py, python/tvm/exec/rpc_server.py, python/tvm/exec/rpc_tracker.py
=> Fix PRC typo

python/tvm/relay/__init__.py, python/tvm/relay/expr_functor.py, tests/python/relay/test_expr_functor.py
@wweic @icemelon9 @vinx13 @junrushao1994 @zhiics can you guys review?
=> [Relay] Add expr_visitor, fix expr_functor exponential blowup problem

src/relay/pass/let_list.h
@ZihengJiang @jroesch  @srkreddy1238 @wweic @icemelon9 can you guys review?
=> [Relay] [Bugfix] make LetList.h insert empty Type instead of IncompleteType

jvm/core/pom.xml
https://discuss.tvm.ai/t/tvm4j-unittest-failure-in-docker-image/2142
@wweic @tqchen
=> Fix java checkstyle version

src/relay/pass/type_solver.cc
Extremely minor nit, but this is one of the most common error messages people see...
=> [NIT] fix relay invariant error message

src/arithmetic/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
=> [ARITH] Fix x||!x for comparisons in rewrite simplifier

include/tvm/relay/expr.h
=> [Relay] fix typo in expr.h

src/relay/ir/pretty_printer.cc
=> [Relay] Add printing for ADT Type

src/relay/backend/graph_runtime_codegen.cc
Fix missing target options in build modules.
=> [Relay] fix target string

.gitignore
CC @jroesch @joshpoll @tqchen @antinucleon
=> Add VSCode directories to gitignore

tests/python/frontend/tensorflow/test_forward.py
=> [TEST][FLAKY] fix for #3099

topi/python/topi/rocm/conv2d.py
=> [ROCM] Fix conv2d

nnvm/include/nnvm/graph.h, nnvm/include/nnvm/op.h, nnvm/src/core/graph.cc, nnvm/src/pass/gradient.cc
=> Check that the node is not null, add contains to OpMap

topi/tests/python/test_topi_group_conv2d.py
=> [TOPI] Fix group_conv2d unit test

Jenkinsfile, docker/Dockerfile.ci_lint, docker/install/ubuntu_install_rat.sh, tests/lint/check_file_type.py, tests/scripts/task_lint.sh
Add script to check extension types, to avoid check-in additional binary files
=> [CI] Add file type check

tests/python/frontend/onnx/test_forward.py
porting new upsample test case from nnvm to relay.
=> porting new upsample test case from nnvm to relay

include/tvm/data_layout.h, src/lang/data_layout.cc, src/relay/pass/alter_op_layout.h, tests/python/relay/test_pass_alter_op_layout.py, tests/python/unittest/test_lang_data_layout.py
@merrymercy @tqchen Please review
=> [Lang] Fix undef BijectiveLayout and add scalar layout support

docs/dev/codebase_walkthrough.rst, python/tvm/container.py, src/codegen/build_module.cc, src/codegen/codegen_c_host.cc, src/codegen/codegen_c_host.h, src/codegen/llvm/llvm_common.cc, tutorials/autotvm/tune_simple_template.py
=> [DOC] various assorted grammar fixes

src/runtime/graph/debug/graph_runtime_debug.cc
Print op names in `RunIndividual` function of graph runtime debug.
@Laurawly
=> Minor addition to graph runtime debug

src/codegen/build_module.cc
=> [DOC] Add missing targets to target_name documentation.

Jenkinsfile
=> [CI] Always run cpptest during build to ensure library correctness

src/relay/backend/build_module.cc
=> [BuildModule] Fix AlterLayout Pass

topi/python/topi/cuda/nms.py
Reported in Issue #3142 
@eqy @masahi Please lemme know if this fixes the problem.
=> [Bugfix] Add more syncs to fix flaky test caused by get_valid_counts

golang/src/bytearray.go, golang/src/function.go, golang/src/module.go, golang/src/ndarray.go
Ref. https://github.com/aai/go-face/commit/7c338c5174282cd92d9d46e81dc7a2a456be0cdd 
Enforces not to use mangled C names.
=> [GOLANG] Some fixes for golang latest version compiler. #3119

src/pass/loop_partition.cc
Removed a piece of code that was marked to be removed after HalideIR submodule is updated
=> [TVM] loop partition cleanup

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Fix #3177 add onnx elemwise greater/less converter
=> [Frontend] add onnx elemwise greater/less converter

docs/vta/install.md
Just a quick fix I noticed while reading the docs.
r? @tqchen
=> [Doc] Quick fix of "VTA FPGA Toolchain Installation" documentation

.gitignore
=> Add pipenv file in .gitignore

src/api/api_pass.cc
I think this might have been missing in #3222.
=> Register SkipVectorize

python/tvm/autotvm/record.py
I've made a small change to how autotvm.record.pick_best works to prevent it from accidentally deleting autotuning results. Previously, the output file would be overwritten with the best records of the input file. Although this is fine in many cases, if the output file already exists and contains records itself (as might be the case if an autotuning script is run a few times), it is actually much better to choose the best records from both the input and output files. This update simply attaches the input and output records and finds the best records from both to write.
=> [AutoTVM] Change to record.pick_best to prevent overwriting previous results.

tests/lint/add_asf_header.py
(Handle some file types for android apps)
=> [LINT] handle more file types in ASF header

src/relay/pass/gradient.cc
=> [Relay] remove unneeded VisitExpr

include/tvm/relay/transform.h, src/relay/pass/pass_manager.cc
Main ergonomic changes to make API cleaner and easy to use.
- directly use ptr in operator->
- Remove the positional constructor of PassContext in C++, instead allow the creation of a default one and mutate the corresponding fields. (This allows arguments to be explicit, like keyword arguments). This is done given that we might grow the PassContext in the future.
```c++
auto ctx = PassContext::Create();
ctx->opt_level = 2;
ctx->fallback_device = kDLCPU;
With<PassContext> scope(ctx);
// pass context in effect.
```
- Add overload of operator() to Pass as well, so we can directly do seq(mod)
- Remove LOG(INFO), use ```DLOG(INFO)``` for debug logging
=> [C++][RELAY][PASS] Cleanup transform API nits

src/arithmetic/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
This is a bugfix which adds additional positiveness checks for several mod-related rewriting rules.
@tqchen @derisavi please review
=> [ARITH] Bugfix: check arg positiveness for mod rules

docker/install/ubuntu_install_onnx.sh
cc @tqchen for https://github.com/dmlc/tvm/pull/3043
=> [Frontend][Onnx] Bump ONNX version

docs/install/from_source.rst
See https://discuss.tvm.ai/t/trouble-enabling-antlr/2783.
=> [Relay][Docs] Add parser dependency install instructions.

topi/python/topi/cuda/nms.py
This PR improves non_max_suppression memory accessing not coalesced problem. @vinx13 @kevinthesun plz review.
=> [IR] Try to improve nms and get_valid_count

nnvm/include/nnvm/node.h, nnvm/src/core/graph.cc
improve error message, remove unnecessary check
=> Minor improve to assertion

topi/python/topi/x86/conv2d.py, topi/python/topi/x86/conv2d_avx_1x1.py, topi/python/topi/x86/conv2d_avx_common.py, topi/tests/python/test_topi_conv2d_NCHWc.py, tutorials/frontend/deploy_ssd_gluoncv.py
=> Support x86 dilation conv2d and improve multi-batch conv2d

Jenkinsfile, tests/scripts/task_python_legacy.sh
Might help alleviate https://github.com/dmlc/tvm/issues/3334
=> [CI] separate out legacy as a stage

include/tvm/relay/attrs/transform.h, python/tvm/relay/op/transform.py, tests/python/relay/test_op_level3.py, topi/include/topi/transform.h, topi/python/topi/transform.py, topi/tests/python/test_topi_transform.py
RFC https://github.com/dmlc/tvm/issues/3303
@antinucleon, @icemelon9, @ajtulloch please review.
=> [Topi] Fast mode in take op

topi/python/topi/cuda/nms.py
@kevinthesun @vinx13 Please review.
=> Non_maximum_suppression and get_valid_counts add new parameters

CONTRIBUTORS.md
We are glad to welcome @were as a new committer of TVM.
Jian is the major author of Hybrid Script for TVM. The tool enables people write complicated compute logic in pure Python and then be transformed to TVM tensor IR directly. It makes life much easier for
implementing operators like non-maximum suppression, etc.
Commits:
https://github.com/dmlc/tvm/commits?author=were
Code Review:
https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Awere
Forum:
https://discuss.tvm.ai/u/were/activity
=> [Community] Jian Weng -> Committer

tests/python/frontend/tflite/test_forward.py
Address review comments for PR 3357, 
In tflite front-end UT, keep underline with comments in same length.
=> [Relay] tflite frontend, keep underline with comments in same length.

tests/python/relay/test_op_level6.py, tests/python/relay/test_pass_quantize.py, topi/tests/python/test_topi_sort.py
=> [TEST][FLAKY] Fix flaky test on topk and quantize pass

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
=> [Relay][hotfix] hotfix for onnx

src/arithmetic/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
Uncovered during debugging of #3368 , cc @sgrechanik-h @kazum @derisavi
=> [ARITH] Bugfix min/max const canonicalize rule

Jenkinsfile, docker/install/ubuntu_install_nodejs.sh
https://github.com/dmlc/tvm/issues/3373
=> [CI] Update ci-gpu to v0.52

tests/python/frontend/tensorflow/test_forward.py
* clean up code
* enable ConcatV2 test
* update Gather & GatherV2 test
=> [TEST][TENSORFLOW] clean up code

tutorials/autotvm/tune_relay_arm.py, tutorials/autotvm/tune_relay_cuda.py, tutorials/autotvm/tune_relay_mobile_gpu.py, tutorials/autotvm/tune_relay_x86.py
#3399
@antinucleon  Am I still missing other place? I greped "evaluate" and missed these ones. Probably should have greped "from_*".
=> [relay][fix] return mod from frontend for autotvm

jvm/README.md
A follow-up PR for https://github.com/dmlc/tvm/pull/3403
=> to fix issue Target llvm is not enabled[followup]

python/tvm/relay/prelude.py
=> Fix global var in prelude

.gitignore
=> add nix to gitignore

nnvm/python/nnvm/frontend/onnx.py
Discovered via: __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
=> Undefined name: Typo in variable name sotrage_order --> storage_order

python/tvm/autotvm/graph_tuner/base_graph_tuner.py, tests/python/unittest/test_graph_tuner_core.py
=> GraphTuner supports relay.module as input

tests/python/relay/test_op_level3.py
=> [Relay] fix deprecation warning

src/relay/pass/gradient.cc, tests/python/relay/test_pass_gradient.py
=> [Relay] Fix ad for conditional expression

3rdparty/compiler-rt/builtin_fp16.h, README.md, src/common/socket.h, tests/azure-pipelines/main.yml
- Fixes the windows build #3426 
- Added Azure pipeline to check windows and mac build.
=> [CI] Fix windows build, add azure pipeline

python/tvm/autotvm/tuner/sa_model_optimizer.py
Fix #3461 
@merrymercy Could you take a look? I think you meant to filter out the items of which score is less than 0.
=> [Bugfix] Fix AutoTVM bug

python/tvm/relay/op/nn/nn.py, src/relay/pass/mac_count.cc, tests/python/relay/test_pass_mac_count.py
Add mac count support for `conv_2d_transpose`
@yzhliu @tqchen
=> [ANALYSIS] Mac count deconv

python/tvm/autotvm/graph_tuner/utils/traverse_graph.py, python/tvm/autotvm/task/relay_integration.py, python/tvm/relay/backend/interpreter.py, python/tvm/relay/build_module.py, python/tvm/relay/module.py, tests/python/relay/test_autotvm_task_extraction.py, tests/python/relay/test_backend_compile_engine.py, tests/python/relay/test_backend_graph_runtime.py, tests/python/relay/test_cpp_build_module.py, tests/python/relay/test_pass_fuse_ops.py
=> [Relay] fix 'please use input parameter mod warning' triggered in build_module

docker/install/ubuntu_install_python_package.sh
Needed for:
- https://github.com/dmlc/tvm/blob/287078c33db85d4f312d8d2457a064442d9d18c3/tutorials/frontend/deploy_model_on_android.py#L30
- https://github.com/dmlc/tvm/blob/287078c33db85d4f312d8d2457a064442d9d18c3/tutorials/frontend/deploy_model_on_android.py#L37
- https://github.com/dmlc/tvm/blob/287078c33db85d4f312d8d2457a064442d9d18c3/python/tvm/contrib/download.py#L58
@tqchen Please review
=> Docker: Install Python packages 'requests' and 'Pillow'

tutorials/frontend/deploy_model_on_android.py
=> Tutorial: Use Python 3

docker/Dockerfile.demo_android, tutorials/frontend/deploy_model_on_android.py
- Install OpenCL headers
- Set ANDROID_HOME environment variable
@tqchen Please review
=> Android demo: Docker improvements

apps/android_rpc/README.md
- Fix APK path
- Add ADB install/uninstall instructions
@tqchen Please review
=> Android RPC README improvements

src/arithmetic/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
=> [ARITH] Bugfix div subtract rewrite rule

python/tvm/relay/op/_tensor_grad.py, tests/python/relay/test_op_grad_level3.py
Registering the gradient function for a level 3 operator: tvm.relay.clip and adding a testcase for it in test_op_grad_level3.py: test_clip()
=> [Relay] Register clip gradient: grad * (select(x < min || max < x , 0, 1))

docs/dev/virtual_machine.rst
cc @jroesch @MarisaKirisame @zhiics @icemelon9
=> [Relay][Doc] Docs for new op code

tests/python/relay/test_pass_to_a_normal_form.py
=> [Relay] fix ANF test

.gitmodules
=> [DEP] Remove HalideIR from submodule

src/relay/pass/gradient.cc, tests/python/relay/test_pass_gradient.py
Also change the test code to cover first order gradient
=> [Bugfix] Fix the bug for first-order gradient

src/relay/backend/vm/compiler.cc
fix https://github.com/dmlc/tvm/issues/3564
cc @jroesch @icemelon9 @tqchen
=> [Relay][VM]Fix debug statement

src/arithmetic/modular_set.cc, src/arithmetic/rewrite_simplify.cc, src/arithmetic/rewrite_simplify.h, src/arithmetic/stmt_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py, tests/python/unittest/test_arith_stmt_simplify.py
=> [ARITH] Simplify let

python/tvm/tensor.py, src/lang/data_layout.cc
@tqchen @kevinthesun Please review.
=> Add printer for Layout/BijectiveLayout

python/tvm/relay/op/_tensor_grad.py, src/relay/pass/gradient.cc, tests/python/relay/test_feature.py, tests/python/relay/test_op_grad_level1.py, tests/python/relay/test_op_grad_level3.py, tests/python/relay/test_pass_gradient.py, tests/python/relay/test_pass_partial_eval.py, tests/python/relay/test_pass_to_cps.py
This also add the grads for zeros and ones. since they do not have parameters, they do not have gradients.
=> [Relay] add some check for the ad algorithm

vta/hardware/chisel/src/main/scala/core/Compute.scala, vta/hardware/chisel/src/main/scala/core/Fetch.scala, vta/hardware/chisel/src/main/scala/core/Load.scala, vta/hardware/chisel/src/main/scala/core/LoadUop.scala, vta/hardware/chisel/src/main/scala/core/Store.scala, vta/hardware/chisel/src/main/scala/core/TensorAlu.scala, vta/hardware/chisel/src/main/scala/core/TensorGemm.scala, vta/hardware/chisel/src/main/scala/core/TensorLoad.scala, vta/hardware/chisel/src/main/scala/core/TensorStore.scala, vta/hardware/chisel/src/main/scala/core/TensorUtil.scala
=> [VTA] [Chisel] cleanup remove tabs

python/tvm/relay/op/_tensor_grad.py, python/tvm/relay/op/nn/_nn.py, python/tvm/relay/op/nn/nn.py, python/tvm/relay/op/op_attrs.py, src/relay/op/nn/pooling.cc, topi/include/topi/detail/ravel_unravel.h, topi/include/topi/nn/pooling.h, topi/include/topi/reduction.h, topi/include/topi/transform.h, topi/python/topi/generic/nn.py, topi/python/topi/nn/pooling.py, topi/python/topi/testing/__init__.py, topi/python/topi/testing/pool_grad_python.py, topi/src/topi.cc, topi/tests/python/test_topi_pooling.py
Part of this PR from #2373 by @nhynes 
cc @MarisaKirisame @junrushao1994 @SWu @jroesch
=> [TOPI][Relay] max_pool2d & avg_pool2d gradient

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_forward.py
Enhance test to cover this case
=> [TensorFlow] Fix a bug output index is ignored

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_forward.py
issue: https://github.com/dmlc/tvm/issues/3414
@srkreddy1238 @kevinthesun @zhiics @yzhliu
=> [Relay][TF] add BatchMatMul

topi/tests/python/test_topi_conv2d_winograd.py
=> Hotfix for issue #3641.

python/tvm/relay/transform.py
=> [Relay] Fix typo in ChangeBatch

src/runtime/rocm/rocm_module.cc, tests/python/unittest/test_codegen_device.py
...and add rocm module_save to the tests.
@masahi generously allowed me to tag him for ROCm, thank you!
=> ROCm: Add SaveToFile and LoadFile

CONTRIBUTORS.md
This PR adds @slyubomirsky to the reviewer list of tvm. He has been contributing to many core features in Relay.
- [Commits](https://github.com/dmlc/tvm/commits?author=slyubomirsky)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aslyubomirsky)
- [Community Engagement](https://discuss.tvm.ai/u/slyubomirsky/summary)
=> [Community] slyubomirsky -> Reviewer

tutorials/frontend/from_darknet.py
This adds yolov3-tiny option to the tutorial.
@siju-samuel,
Please help with the review.
=> Add yolov3-tiny to the tutorial.

tests/python/frontend/tensorflow/test_forward.py
Stick to python 3.5 according to code_guide.rst
@srkreddy1238 Could you please take a look?
=> [TEST] Comptiable with python3.5

src/relay/pass/partial_eval.cc, tests/python/relay/test_pass_partial_eval.py
=> [Relay] [Error] Fix error in partial evaluator

src/relay/op/tensor/transform.cc, tests/python/frontend/mxnet/test_forward.py, tests/python/relay/test_op_level3.py
=> Fix gather_nd in Relay

Jenkinsfile
=> [CI] Update GPU docker

include/tvm/relay/op.h
This may be used by downstream repos.
CC: @vinx13 @tqchen
=> [Minor] Export `OpRegistry::OpRegistry`

python/tvm/relay/backend/interpreter.py, src/relay/pass/pass_manager.cc, tests/python/relay/test_pass_fuse_ops.py
@zhiics Could you help review this PR?
=> [Bugfix] Fix the issue that function pass modifies original module

python/tvm/relay/frontend/common.py, python/tvm/relay/frontend/mxnet.py, python/tvm/relay/frontend/tensorflow.py
This PR cleans some duplicated code used in the frontends, mainly tf.
cc @srkreddy1238 @icemelon9 @tqchen @jroesch
=> [relay][frontend] clean up tf frontend

tests/python/relay/test_pass_partial_eval.py
=> [Relay] [Test] fix Partial Eval test name

Jenkinsfile
=> [CI] Update docker image ci_cpu,i386 to include verilator

vta/hardware/chisel/src/main/scala/shell/VME.scala
Bug fix for ready signal is only high for 1 cycle when sending data where len==0. (corner case)
=> [VTA] [Chisel] Bug fix for VME Shell

include/tvm/ir_pass.h
=> Fix typo in ir_pass.h

python/tvm/relay/op/_tensor_grad.py, src/relay/ir/alpha_equal.cc, src/relay/pass/gradient.cc, tests/python/relay/test_pass_gradient.py
@srkreddy1238 @wweic @icemelon9 @junrushao1994 can you guys help review?
=> [Relay] [Training] Fix ad for concatenate

CONTRIBUTORS.md
This PR adds @MarisaKirisame to the reviewer list of TVM. He has been contributing to Relay IR, passes, and ADT.
- [Commits](https://github.com/dmlc/tvm/commits?author=MarisaKirisame)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3AMarisaKirisame)
- [Community Engagement](https://discuss.tvm.ai/u/MarisaKirisame/summary)
=> [Community] MarisaKirisame -> Reviewer

tutorials/cross_compilation_and_rpc.py
=> Fix Mistyping

vta/hardware/chisel/src/test/scala/unittest/MvmTest.scala
Small fix for scala naming convention
=> [VTA][Chisel] Scala Style Fix

vta/scripts/tune_dense.py
Collects best schedule for a list of dense operators to run on VTA. Lets us easily update tophub library for new shapes of dense.
=> [VTA][AutoTVM] Dense operator tuning on VTA fix

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Adds support for Sign and Equal operators to the ONNX frontend.
@zhreshold @jroesch would you mind taking a look?
=> [Relay][Frontend][ONNX] Add Sign and Equal operators to ONNX frontend

python/tvm/relay/quantize/_partition.py
=> [BUGFIX] Fix for NoneType Target

CONTRIBUTORS.md
Please join us to welcome @hlu1  as a Committer of the TVM stack. Her contributions spans caffe2 frontends, NNPack integration and graph runtime, and has been active in reviewing PRs.
- [Commit history](https://github.com/dmlc/tvm/commits?author=hlu1)
- [Code reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=type%3Apr+reviewed-by%3Ahlu1)
- [Community forum summary](https://discuss.tvm.ai/u/hlu1/summary)
=> [Community] Hao Lu -> Committer

topi/python/topi/cuda/conv2d_transpose_nchw.py
Added tilting on batch dimension. There are significant speedup for large batch size.
=> [TOPI, CUDA] Improve conv2d_transpose schedule template

python/tvm/relay/_parser.py
=> [Relay] Fix typo in parser

include/tvm/dtype.h, include/tvm/expr_operator.h, include/tvm/schedule.h, src/arithmetic/int_set.h
https://github.com/dmlc/tvm/issues/3822 cc @abadams
=> [CODE] Halide attributions

docs/dev/hybrid_script.rst
=> Minor typo fixes in docs 

python/tvm/relay/frontend/onnx.py
Hi @masahi @jroesch  @zhiics @vinx13 
I Improve the comment for some operators, I would appreciate if you can help to review it, thanks.
=> [Relay][Frontend][ONNX] Fix code comment for some operators

conda/tvm/meta.yaml
=> Improvements in conda recipe

vta/src/runtime.cc
Issue:
RewriteForceSerial is a debug function to force instructions
to be serialize instead of parrallel running, by doing so we
can isolate some parallel problem or do performance compare
between parallel and serialize. But this function have some
problem, once get enabled by set debug flag, vta would stuck
when running on pynq board.
Reproduce:
set vta.build_config(debug_flag=32), then run vta resnet on FPGA, issue would reproduce.
Analysis:
once enable RewriteForceSerial, the dependency logic is different
with default one, but we still use same logic to generate FINISH
and other logic, this would cause dead lock.
Solution:
give a different dependency settings when enable RewriteForceSerial.
=> [VTA] Fix RewriteForceSerial Function logic issue.

nnvm/python/nnvm/frontend/onnx.py
=> [NNVM][FRONTEND][ONNX] Fix PReLU conversion

src/relay/qnn/op/requantize.cc, tests/python/relay/test_qnn_requantize.py
Skips many instructions for the corner case.
@jackwish @vinx13 @zhiics
=> [QNN] Requantize - Optimize lowering for some corner cases.

python/tvm/relay/_parser.py, tests/python/relay/test_ir_text_printer.py
@weberlo @joshpoll @slyubomirsky please review.
=> [Relay] [Parser] fix parser for cast.

docs/langref/relay_type.rst
=> Reveal hidden code snippets by inserting newline

python/tvm/relay/op/_tensor_grad.py
@SWu @vinx13 @Ruinhuang can you guys help review? this is a part of the upstream of #3506 .
=> [Relay][Training] Small refactoring

docs/install/from_source.rst, tutorials/frontend/deploy_ssd_gluoncv.py
=> [DOC] Fix doc rendering 

src/relay/backend/vm/compiler.cc
=> [bugfix] remove duplicate resize

src/relay/op/op_common.h, src/relay/op/tensor/transform.cc
@weberlo @icemelon9 can you guys help review?
=> [Relay][Op] Make Type Relation catch more errors

python/tvm/relay/op/_tensor_grad.py, tests/python/relay/test_op_grad_level4.py
=> [Relay][Training] Add gradient for max.

python/tvm/autotvm/graph_tuner/base_graph_tuner.py, tests/python/unittest/test_graph_tuner_core.py
Fix a case of block with concatenation for PBQP tuner.
@yzhliu
=> [Graph Tuner] Fix benchmark layout in graph tuner

tests/lint/pylintrc
adjust pylint output to show file location to make it possible to locate errors
=> adjust pylint output

docs/api/python/relay/analysis.rst
This PR adds the doc for the analysis namespace to help user read it from the website.
=> [doc] Add docs for analysis namespace

tests/python/relay/test_type_solver.py
See issue #3946 . This PR adds more tests for new changes to unifying quantified function types from #3559 .
Unfortunately, one of these unit tests crashes because of a unification bug whose solution is not obvious. I have included the case described in #3946 here so we could make progress towards a fix here.
=> [Relay][Types][Tests] Add type solver unit tests for unifying quantified funcs

python/tvm/relay/frontend/tflite.py, tests/python/frontend/tflite/test_forward.py
=> add parser support for TANH tflite operator

python/tvm/relay/frontend/tflite.py, tests/python/frontend/tflite/test_forward.py
=> add parser support for GREATER tflite operator

CONTRIBUTORS.md
Please join me to welcome Yong Wu(@yongwww) as a new reviewer. He has been contributing to the TF frontends and TOPI. 
- [Commits](https://github.com/dmlc/tvm/commits?author=yongwww)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ayongwww)
- [Community Engagement](https://discuss.tvm.ai/u/yongwww/summary)
=> [COMMUNITY] @yongwww-> reviewer

docs/vta/install.md
cc #3951 
r? @tqchen @tmoreau89
=> [Doc][VTA] Change Vivado install instructions to version 2018.3

src/relay/qnn/op/convolution.cc
Earlier, we were performing Avg_pool2d + Reduce_on_C.
This PR reorders to Reduce_on_C + Avg_pool2d
This reduces the total number of operations, while keeping functionality same.
@jackwish @zhiics
=> [QNN][Conv2D] Optimize lowering.

docker/Dockerfile.ci_gpu, docker/Dockerfile.demo_cpu, docker/Dockerfile.demo_gpu, docker/install/install_tvm_cpu.sh, docker/install/install_tvm_gpu.sh
https://github.com/dmlc/tvm/issues/4020
=> [DOCKER] make demo images consistent with ci images when possible.

tests/python/frontend/mxnet/test_forward.py
Add different batch sizes and channel numbers to
MXNet Convolution and Deconvolution tests.
=> Additional MXNet Convolution and Deconvolution tests

src/op/tensorize.cc, src/relay/pass/well_formed.cc
please see https://stackoverflow.com/a/26949099
=> make tvm compilable by gcc 4.9.2

CONTRIBUTORS.md
Please join us to welcome @ajtulloch  as a new committer to TVM. Andrew has contributed several aspects to the projects. His most notable contributions includes:
- New vulkan runtime
- Minimum runtime for ARM
- NNPack support
- initial low level optimizations for winograds
He is also quite vocal in the discuss forums and shares their insights about using TVM in production.
- [Commits History](https://github.com/dmlc/tvm/commits?author=ajtulloch)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aajtulloch)
- [Community Forum Summary](https://discuss.tvm.ai/u/ajtulloch/summary)
=> [COMMUNITY] ajtulloch -> committer

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_forward.py
@yongwww  @srkreddy1238 @zhiics Please take a look.
=> [TF][Op] Op where

python/tvm/relay/frontend/tensorflow_parser.py
=> [Bugfix][TF] reset graph after getting tag of savedmodel

topi/python/topi/x86/conv2d_alter_op.py
With broadcast layout support in AlterOpLayout merged (#4040), we can now convert NHWC to NCHWc for conv2d automatically.
@kevinthesun @yzhliu @yidawang
=> [AlterOpLayout][x86] NHWC to NCHWc conv support.

src/relay/backend/build_module.cc, src/relay/backend/vm/compiler.cc
#3579 
Extract the first target from the map instead of loop around when there is only one item in it.
CC @tqchen @gussmith23
=> [relay] Small refactor for context

topi/python/topi/intel_graphics/conv2d.py
@kevinthesun @merrymercy  Could you review?
=> [TOPI] Add valid auto tvm for Intel Graphics

topi/python/topi/x86/bitserial_conv2d.py
Fixing tensor not found issue in bitserial operator
=> Fixing tensor not found issue in bitserial operator

topi/python/topi/intel_graphics/conv2d.py
@kevinthesun @merrymercy Could you review? Thanks
=> [TOPI] Fix bug in intel graphics auto tune

CONTRIBUTORS.md
Please join me in welcoming @soiferj as a new reviewer of the Apache TVM project.  Jon has extended TOPI with new operators, extended coverage of ONNX and TensorFlow Relay frontends, added IR passes to combine dense ops in parallel among other contributions.
- [Commits](https://github.com/dmlc/tvm/commits?author=soiferj)
- [Reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&amp;q=reviewed-by%3Asoiferj+)
- [Community forum engagement](https://discuss.tvm.ai/u/jonso/summary)
=> [COMMUNITY] soiferj -> reviewer

Jenkinsfile
=> Revert ci-cpu due to nnpack issue

src/pass/lower_intrin.cc
=> [ARITH] Fix lowering of floormod(x, y) != 0

docker/install/ubuntu_install_nnpack.sh
=> [CI] Pin NNPack pthreadtools version

docs/vta/install.md
FIX "After connecting he usb" with "After connecting the usb"
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.
=> Fix missspelling

src/relay/pass/device_annotation.cc
=> [Pass] Remove dead code

topi/include/topi/nn/pooling.h, topi/python/topi/x86/pooling.py
https://github.com/dmlc/tvm/issues/4167
@tqchen
=> Split adaptive_pool2d_avg into sum and div

python/tvm/build_module.py
=> [Documentation]Fix example code in comment of tvm.build_module.build()

topi/tests/python/test_topi_math.py
https://github.com/dmlc/tvm/issues/4210
=> [TOPI] Fix flaky testcase for check round

include/tvm/runtime/packed_func.h
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.
=> Fix typo in packed_func.h

src/arithmetic/rewrite_simplify.cc, tests/python/unittest/test_arith_rewrite_simplify.py
=> [ARITH] Fix the rule y < x && x <= y

python/setup.py
@tqchen @jroesch @joshpoll @apivovarov 
This fixes https://github.com/dmlc/tvm/issues/4225.
=> [Relay] Install Relay Prelude program in package install

docs/install/from_source.rst
@tqchen @apivovarov 
Thanks for the discussion on https://discuss.tvm.ai/t/relay-from-tensorflow-failed-couldnt-find-antlr-parser/4529/9
=> [Doc] Update ANTLR instruction

python/tvm/contrib/graph_runtime.py
=> Fix typo in get_output doc-string

Jenkinsfile, cmake/config.cmake
=> [BUILD] Disable utvm standalone runtime by default

apps/android_rpc/app/src/main/java/ml/dmlc/tvm/tvmrpc/RPCProcessor.java
Signed-off-by: qinqiuping <autumnqin@126.com>
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.
=> Fix the problem that android_rpc compilation failed.

python/tvm/relay/prelude.py, tests/python/frontend/tensorflow/test_forward.py
@jroesch @icemelon9 @yongwww @zhiics @joshpoll @weberlo 
Reported by https://discuss.tvm.ai/t/relay-frontend-prelude-object-has-no-attribute-tensor-array-uint8/4553
=> [Relay][Prelude] Add more dtypes to tensor_t

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_forward.py
Support reshape for dynamic shape in tf converter.
@yongwww @wweic
=> Support reshape for dynamic shape in tf converter

src/relay/pass/type_infer.cc
=> Fix typo in err msg

tests/python/frontend/tensorflow/test_forward.py
@yongwww @icemelon9 @srkreddy1238 @zhiics
=> [Test][TF][Relay] Fix argument preparation for vm test mode

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_forward.py
Move symbolic related logic after infer value is failed.
=> Fix tf reshape

tutorials/dev/relay_pass_infra.py
Need the colon to help sphinx parse tutorial title.
=> [doc][fix] fix sphinx parsing for pass infra tutorial

Jenkinsfile
Already verified via jenkins staging.
=> [CI][DOCKER] Upgrade image to include onnx runtime

nnvm/python/nnvm/__init__.py
per discussion in https://github.com/apache/incubator-tvm/issues/4259#issuecomment-552027579
@tqchen
=> Deprecate NNVM warning msg

tests/python/relay/test_pass_lambda_lift.py
cc @jroesch @icemelon9 @zhiics @MarisaKirisame
=> [Test][Relay][Pass] Add test case for lambda lift

python/tvm/autotvm/tophub.py
=> Bump up CUDA log version in tophub.py

DISCLAIMER, KEYS, NOTICE, tests/lint/check_file_type.py
=> [COMMUNITY] Add DISCLAIMER, KEYS for ASF release

docker/install/install_tvm_cpu.sh, docker/install/install_tvm_gpu.sh
Fix the install scripts with mismatch folder names.
cc @tqchen
=> fix install script

src/runtime/object.cc
per https://discuss.tvm.ai/t/i-spent-5hr-today-add-a-new-node/4754/9
@tqchen @hcho3
=> reminding message for TVM_REGISTER_NODE_TYPE

apps/benchmark/README.md, apps/benchmark/arm_cpu_imagenet_bench.py, apps/benchmark/gpu_imagenet_bench.py, apps/benchmark/mobile_gpu_imagenet_bench.py, apps/benchmark/util.py
=> [tutorial][benchmark] nnvm -> relay

docs/dev/codebase_walkthrough.rst, python/tvm/relay/backend/__init__.py
=> [doc] fix typo, codege to codegen

src/codegen/llvm/codegen_amdgpu.cc, src/codegen/llvm/codegen_nvptx.cc, src/codegen/llvm/llvm_module.cc
[The recent change](https://github.com/llvm/llvm-project/commit/1dfede3122eec83b885d788553e3620806d54650) in the LLVM trunk introduced build break. @yzhliu @petrex please review.
=> [BUILD] Fix build with LLVM trunk

Jenkinsfile
Isolate each worker's workspace into a separate per executor folder, print more worker node related information at the beginning of each stage.
=> [CI] Add more info, per exec ws isolation

src/relay/backend/vm/removed_unused_funcs.cc, tests/python/relay/test_pass_remove_unused_functions.py
Currently the args of the call nodes are not checked when removing functions. It causes function undefined problem when a global function is invoked by a call as its argument because the definition will be removed.
cc @wweic @icemelon9
=> [fix][pass] Save the function when it is used as a call arg

python/tvm/relay/backend/compile_engine.py
=> [Doc] Fix doc-string in `compile_engine.py`

CONTRIBUTORS.md
This PR welcomes @weberlo as a new reviewer of the TVM. He contributed to uTVM and Relay ADT.
- [Commits](https://github.com/dmlc/tvm/commits?author=weberlo)
- [Reviews](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aweberlo)
- [Community forum engagement](https://discuss.tvm.ai/u/weberlo/summary)
=> [Community] @weberlo -> reviewer

topi/tests/python/test_topi_broadcast.py
#4378
@tqchen @kevinthesun am I understanding correctly?
=> [TOPI] Fix flaky testcase for floor div

Jenkinsfile
This PR updates the Jenkinsfile to enable the example external runtime for #4280 .
=> Update Jenkinsfile for external runtime

README.md
=> [DOCS] Mention incubating in readme

include/tvm/runtime/module.h
=> [RUNTIME] Move module export to the function level.

3rdparty/picojson/picojson.h, LICENSE, apps/android_rpc/app/src/main/jni/Android.mk, apps/android_rpc/app/src/main/jni/make/config.mk, apps/ios_rpc/tvmrpc/Base.lproj/LaunchScreen.storyboard, docs/_static/css/tvm_theme.css, include/tvm/relay/expr.h, licenses/LICENSE.builtin_fp16.txt, licenses/LICENSE.concurrentqueue.txt, licenses/LICENSE.picojson.txt, nnvm/make/config.mk, nnvm/tests/cpp/unittest.mk, vta/src/de10nano/cma_api.cc
=> [Release] resolve license issues

include/tvm/runtime/memory.h, src/runtime/vm/vm.cc
=> [RUNTIME] allocator.make -> allocator.make_object for term consistency

python/tvm/relay/op/_tensor.py
=> [Fix][Relay] Remove schedule register for nonexisting log1p op

python/tvm/contrib/debugger/debug_result.py
=> [Debugger] Tweak debugger result API

docs/dev/relay_pass_infra.rst, docs/dev/runtime.rst
@tqchen @weberlo 
This PR is trying to fix some broken links in dev documents, I would appreciate that if you can help to review and manage it, thanks.
=> [Doc] Fix broken link

tests/python/frontend/tflite/test_forward.py
* Add a function to set the qnn output range wrt each elemwise operation.
* Add comments warning for nonsense clamped output in the tflite/tvm results comparison.
A separate output range for each operation has to be defined since if we specify a single range that to work in general for all elemwise operations it will result in a lower accuracy and clamped outputs when we test those elemwise operators whose possible output range is much smaller.
The warning comments point to the the problem with clamping that can be easily overlooked because  once tflite clipps the ouput tensor values to 0 or 255 then that output tensor get consumed by tvm and as a result the tflite_ouput and tvm_ouput are the same... so they pass the assertion.
**The only things that the future testwriter has to do are: …
=> [Relay][Frontend][TFlite] Add test for qnn_mul operator

cmake/config.cmake
=> [build] a tiny typo

python/tvm/relay/op/_tensor.py, tests/python/relay/test_any.py
cc: @icemelon9 @kevinthesun @zhiics
=> [Relay] shape func for zeros, zeros_like, ones, ones_like

src/pass/make_api.cc
=> [doc] fix typo

python/tvm/intrin.py, src/api/api_pass.cc, src/pass/lower_warp_memory.cc, topi/python/topi/arm_cpu/bitserial_dense.py, topi/python/topi/bifrost/depthwise_conv2d.py, topi/python/topi/cuda/dense.py, topi/python/topi/cuda/depthwise_conv2d.py, topi/python/topi/cuda/pooling.py, topi/python/topi/cuda/reduction.py, topi/python/topi/hls/nn.py, topi/python/topi/intel_graphics/depthwise_conv2d.py, topi/python/topi/opengl/conv2d_nchw.py, topi/python/topi/opengl/dense.py, topi/python/topi/opengl/pooling.py, topi/python/topi/x86/binary_dense.py, topi/python/topi/x86/bitserial_dense.py, topi/python/topi/x86/pooling.py, topi/python/topi/x86/reduction.py
=> Fix typo in travserse

src/relay/ir/hash.cc, tests/python/relay/test_pass_alpha_equal.py
This PR adds function attrs for hash.
@jroesch @icemelon9 @wweic @MarisaKirisame
=> [Relay] Check function attr for hash

CONTRIBUTORS.md
=> [Team] Jared Roesch -> PPMC

vta/hardware/chisel/Makefile
This PR tries to increase TSIM performance by introducing multi-threading support.
=> [VTA] Speedup TSIM by Multi-threading

src/runtime/opencl/aocl/aocl_module.cc, src/runtime/opencl/sdaccel/sdaccel_module.cc
#4289 missed updating the OpenCL FPGA backends.
@tqchen Could you take a look?
=> [RUNTIME] Fix compile errors of OpenCL FPGA backend

src/codegen/llvm/codegen_amdgpu.cc, src/codegen/llvm/codegen_nvptx.cc, src/codegen/llvm/llvm_module.cc
=> Revert [Codegen] fix bug on LLVM 10.0 #4480

python/tvm/relay/frontend/tensorflow.py, tests/python/frontend/tensorflow/test_forward.py
I have TF model with dynamic input size - summary:
```
Found 1 possible inputs: (name=input, type=float(1), shape=[1,?,?,3]) 
No variables spotted.
Found 1 possible outputs: (name=Tanh, op=Tanh) 
Found 2007162 (2.01M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: ..., 3 ResizeNearestNeighbor, ...
```
I compiled the model using fixed input shape
```
shape_dict = {'input': (1, 224, 224, 3)}
relay.frontend.from_tensorflow(graph_def, layout='NCHW', shape=shape_dict)
```
The compilation gave me the following error
```
oshape [None]
File "./compile_tensorflow.py", line 18, in <module>
sym, params = relay.frontend.from_tensorflow(graph_def, layout='NCHW', shape=shape_dict)
File …
```
=> Fix TF resize for dynamic size models

CONTRIBUTORS.md
Please join me to welcome @cchung100m as a new reviewer. He has been quite active in the community answering questions and help fix quite a few help wanted threads
- [Commits History](https://github.com/dmlc/tvm/commits?author=cchung100m)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Acchung100m)
- [Community Forum Summary](https://discuss.tvm.ai/u/cchung100m/summary)
=> [COMMUNITY] @cchung100m -> reviewer

vta/src/vmem/virtual_memory.cc
This PR improves virtual memory mapping in VTA drivers. The feature could be helpful in debugging data inputs and outputs in VTA hardware.
=> [VTA] improved virtual memory mapping

python/tvm/relay/frontend/onnx.py, tests/python/frontend/onnx/test_forward.py
Hi @tqchen @vinx13 @zhiics 
Following issue #3645 and @abuccts 's work, I add the test case for Supporting auto_pad in Conv and ConvTranspose. I would appreciate that if you can help me to review/manage this PR, thanks.
=> [Relay][Frontend][ONNX] Support auto_pad in Conv and ConvTranspose

vta/hardware/chisel/src/main/scala/core/TensorAlu.scala
This PR brings end-to-end inference capability to Chisel version of VTA.
=> [VTA][Chisel] End-to-end Inference with Chisel VTA

python/tvm/api.py
=> [DOC] fix doc in api.py

python/tvm/_ffi/base.py, src/runtime/c_runtime_api.cc
ref: https://github.com/apache/incubator-tvm/issues/4529
=> Some Windows and MSVC fixes

python/tvm/relay/quantize/_calibrate.py, tests/python/relay/test_pass_auto_quantize.py
When tvm.target.current_target() is not None, I get the following error. I also hope that the test case would serve as an example of using kl based data aware calibration. (took me some time to figure out how to use it)
@vinx13 please review.
```
File "/home/masa/projects/tvm/python/tvm/relay/quantize/_calibrate.py", line 182, in wrapped_func
stats = collect_stats(mod, dataset)
File "/home/masa/projects/tvm/python/tvm/relay/quantize/_calibrate.py", line 72, in collect_stats
runtime = graph_runtime.create(graph, lib, tvm.context(target))
File "/home/masa/projects/tvm/python/tvm/_ffi/ndarray.py", line 85, in context
return TVMContext(dev_type, dev_id)
File "/home/masa/projects/tvm/python/tvm/_ffi/runtime_ctypes.py", line 170, in __init__
self.device_type = device_type
TypeError: an integer …
```
=> [Quantization, Calibrate] Fix context creation when current_target is explicitly set

docs/langref/relay_op.rst, include/tvm/relay/attrs/nn.h, python/tvm/relay/op/nn/_nn.py, python/tvm/relay/op/nn/nn.py, python/tvm/relay/op/op_attrs.py, src/relay/op/nn/upsampling.cc, tests/python/relay/test_op_level2.py, topi/python/topi/image/resize.py, topi/python/topi/nn/upsampling.py, topi/python/topi/testing/__init__.py, topi/python/topi/testing/trilinear_resize3d_python.py, topi/python/topi/testing/upsampling_python.py, topi/tests/python/test_topi_resize.py, topi/tests/python/test_topi_upsampling.py
This is a part of attempts to implement #4009
The implemation in this PR is for  3d upsampling.
@masahi
=> [TOPI] add 3D upsampling Op.

src/pass/ir_functor.cc, tests/cpp/ir_functor_test.cc
=> Bugfix StmtMutator IfThenElse

vta/hardware/chisel/src/main/scala/core/TensorAlu.scala
=> Added declare of aluBits for TensorAlu

CONTRIBUTORS.md
Please join us to welcome Marisa Kirisame(@MarisaKirisame) as a committer of TVM. Marisa has strong background and knowledge in programming language and compiler. He contributed to many aspects to relay and TVM, including high-level relay IR, partial evaluator, high-order/first-order AD pass, ADT, relay interpreter, etc.
- [Commits History](https://github.com/dmlc/tvm/commits?author=MarisaKirisame)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3AMarisaKirisame)
- [Community Forum Summary](https://discuss.tvm.ai/u/MarisaKirisame/summary)
=> [COMMUNITY] @MarisaKirisame -> committer

docker/install/ubuntu_install_chisel.sh
=> [CI] Update deps for chisel

.github/workflows/main.yml
https://github.com/actions/checkout/releases
=> GitHub actions/checkout@v1 --> v2

rust/frontend/tests/basics/src/tvm_add.py
=> os.path --> osp to match the import

apps/vta_rpc/start_rpc_server_to_tracker.sh
This is a shell file, not a Python file.
=> Rename start_rpc_server_to_tracker.py to start_rpc_server_to_tracker.sh

include/tvm/ir/error.h, include/tvm/relay/expr_functor.h, include/tvm/relay/pattern_functor.h, include/tvm/relay/transform.h, src/ir/error.cc, src/relay/backend/vm/compiler.cc, src/relay/backend/vm/compiler.h, src/relay/op/tensor/transform.cc, src/relay/op/tensor/transform.h, src/relay/op/type_relations.cc, src/relay/op/type_relations.h, src/relay/pass/kind_check.cc, src/relay/pass/match_exhaustion.cc, src/relay/pass/type_infer.cc, src/relay/pass/type_solver.cc, src/relay/pass/type_solver.h, src/relay/qnn/op/concatenate.cc
We will use a single ErrorReporter to report errors during program transformations.
cc @ZihengJiang @jroesch @zhiics @yzhliu
=> [REFACTOR][IR] Move error.h into ir

python/tvm/autotvm/tophub.py, python/tvm/relay/op/nn/_nn.py, tests/python/relay/test_op_level2.py, topi/python/topi/arm_cpu/conv2d_transpose.py, topi/python/topi/cuda/conv1d_transpose_ncw.py, topi/python/topi/cuda/conv2d_transpose_nchw.py, topi/python/topi/nn/conv1d_transpose.py, topi/python/topi/nn/conv2d_transpose.py, topi/python/topi/testing/conv1d_transpose_ncw_python.py, topi/python/topi/testing/conv2d_transpose_python.py, topi/python/topi/x86/conv2d_transpose.py, topi/tests/python/test_topi_conv1d_transpose_ncw.py, topi/tests/python/test_topi_conv2d_transpose_nchw.py, vta/python/vta/top/vta_conv2d_transpose.py, vta/scripts/tune_conv2d_transpose.py, vta/tests/python/integration/test_benchmark_topi_conv2d_transpose.py
Reverts apache/incubator-tvm#4318
Bugs in the PR. details see https://github.com/apache/incubator-tvm/pull/4318#issuecomment-574434976
=> Revert "[Relay][TOPI]Fix meaning of conv2d_transpose output_padding parameter"

python/tvm/contrib/ndk.py
Https://discuss.tvm.ai/t/cannot-locate-symbol-expf-error-on-android-host-system-ubuntu/5387 
@FrozenGene link the math library by default
=> link the math library by default

CONTRIBUTORS.md
Please join us to welcome @FrozenGene  as a new committer
He as been an active advocator of TVM. He has helped reviewed many code related to backend codegen and TFLite support. He also contributed to various areas of the codebase including C++ RPC, Arm support and LLVM related code. He recently lead the push for the new unified heterogeneous runtime packaging
- [Commits](https://github.com/apache/incubator-tvm/commits?author=FrozenGene)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3AFrozenGene)
- [Community Forum Summary](https://discuss.tvm.ai/u/FrozenGene/summary)
=> [COMMUNITY] @FrozenGene -> committer

python/tvm/relay/frontend/tflite.py, tests/python/frontend/tflite/test_forward.py
=> [Relay][Frontend][TFLite] Add parser support for squared difference

docs/dev/convert_layout.rst, docs/dev/index.rst
@yzhliu @zhiics @tqchen @trevor-m
=> [Docs] Convert Layout pass.

topi/python/topi/cuda/conv2d.py, topi/tests/python/test_topi_conv2d_nhwc.py
=> Add CUDA conv2d for NHWC layout

docs/dev/relay_bring_your_own_codegen.rst
This continues #4602. Do not merge before #4602.
cc @zhiics
=> [Docs] Bring Your Own Codegen Guide -- Part 2

python/tvm/relay/frontend/tensorflow.py, topi/tests/python/test_topi_conv3d_ndhwc.py
=> Fix Tensorflow conv3d pad bug, add non-cubic data and kernel tests

topi/python/topi/nn/conv3d.py, topi/python/topi/x86/__init__.py, topi/python/topi/x86/conv3d.py
=> conv3d_ndhwc schedule

python/tvm/relay/testing/mobilenet.py
=> fix #4670: add bias for fc layer

topi/python/topi/image/resize.py, topi/python/topi/testing/bilinear_resize_python.py, topi/python/topi/testing/upsampling_python.py, topi/python/topi/util.py, topi/tests/python/test_topi_upsampling.py
some hardware accelerator ask packed format data like NCHWinic to fit the
hardware resource, here add 'upsample' 'NCHWinic' format support to help
such requirement.
=> [TOPI] upsample operator 'NCHWinic' format support.

python/tvm/rpc/server.py
=> Fixed subprocess creation under windows

docs/dev/relay_pass_infra.rst, docs/dev/runtime.rst
Some docs need to be refactored after moving to the object protocol and unified IR.
https://discuss.tvm.ai/t/where-is-pass-manager-cc/5579
@tqchen @icemelon9 @yzhliu @jroesch
=> [doc] Fix doc after moving to unified IR

topi/tests/python/test_topi_pooling.py
https://github.com/apache/incubator-tvm/issues/4444
=> Improve tol to resolve flaky case

CONTRIBUTORS.md
Please join me to welcome @comaniac  as a new reviewer. He has been working on improving operators in topi and quite active in code review for the community.
- [Commits History](https://github.com/dmlc/tvm/commits?author=comaniac)
- [Code Review](https://github.com/dmlc/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Acomaniac)
- [Community Forum Summary](https://discuss.tvm.ai/u/comaniac/summary)
=> [COMMUNITY] comaniac -> reviewer

tests/python/contrib/test_cudnn.py
https://github.com/apache/incubator-tvm/issues/4640
=> [TEST] test_cuddn flaky

Jenkinsfile
=> [CI] Update ci-lint to v0.60

python/tvm/relay/frontend/tflite.py
Use qnn helper function in softmax to make calculation logic more centralized.
=> [Frontend][TFlite] use qnn helper function in softmax

tests/scripts/task_python_docs.sh
=> [CI] Cleanup logfile before tutorial runs
