Jenkinsfile

source https://github.com/apache/incubator-tvm/pull/4902

[CI] Update ci docker to add autodocsumm

---

docker/install/ubuntu_install_sphinx.sh

autodocsumm can generate a summary table for functions in a module automatically.

[CI] Add autodocsum as dep

---

topi/python/topi/x86/depthwise_conv2d.py

[Fix] remove unnecessary spliting in the cached chunk

---

conda/tvm-libs/meta.yaml
conda/tvm/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/tvm_runtime.js

Not for release purpose. This is only for convenience purposes to differentiate TVM with and w/o op strategy.
cc @tqchen @comaniac

Bump up dev version

---

docker/Dockerfile.ci_cpu

Remove SGX toolchain installation from CI Dockerfile

---

python/tvm/ir/transform.py

[RELAY] fix error message

---

docs/langref/relay_op.rst

Fix doc warnings introduced by #4942 
cc @tqchen

[DOCS] Fix Warnings from #4942

---

docs/langref/relay_adt.rst
docs/langref/relay_expr.rst
docs/langref/relay_type.rst
tests/scripts/task_sphinx_precheck.sh

cc @icemelon9 @comaniac @ZihengJiang

[DOCS] Fix sphinx precheck

---

python/tvm/te/tag.py
python/tvm/tir/op.py

Try to make the API used in example description clearer.

[Doc] Refine the example description of max/min/sum/tag_scope

---

CONTRIBUTORS.md

Congratulations to @huajsj for joining TVM's list of reviewers.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=huajsj)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ahuajsj)
- [Community Forum Summary](https://discuss.tvm.ai/u/huajsj/summary)

[COMMUNITY] @huajsj -> Reviewer

---

CONTRIBUTORS.md

Please join us to welcome @optima2005 as a new reviewer. He has been quite active to add 3D support as well as asymmetric padding to the TVM and helps to review quite a few PRs
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=optima2005)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aoptima2005)
- [Community Forum Summary](https://discuss.tvm.ai/u/optima2005/summary)

[COMMUNITY] @optima2005 -> reviewer

---

tutorials/frontend/from_mxnet.py

kill from tvm import te

---

python/tvm/relay/op/strategy/cuda.py

Fix issue https://discuss.tvm.ai/t/performance-has-been-too-slow-since-the-tvm-update/5865

[Relay] Reduce plevel of conv2d winograd implementation on cuda

---

docs/deploy/aocl_fpga.md
docs/deploy/aws_fpga.md
docs/dev/codebase_walkthrough.rst
docs/dev/inferbound.rst
docs/dev/runtime.rst
docs/langref/hybrid_script.rst
jvm/README.md
rust/frontend/README.md
web/README.md

Docs and Readme updated as per new namespace change

---

src/te/schedule/message_passing.cc
tests/python/unittest/test_schedule_bound_inference.py

Reverts apache/incubator-tvm#4931
Reason: #5015

Revert "Tighten split's extent"

---

src/relay/backend/vm/compiler.cc
tests/python/relay/test_vm.py

fixes https://github.com/apache/incubator-tvm/issues/4997

[Relay][VM] Fix compilation of If-Elses

---

src/relay/ir/alpha_equal.cc
tests/cpp/relay_pass_alpha_equal.cc
tests/python/relay/test_pass_alpha_equal.py

Conditions updated to cover better user scenarios[Re-raised]

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

@wyc-ruiker @anijain2305 @FrozenGene Please help to review and merge this PR. TIA

[TFLITE]Round op parsing support added

---

tests/python/relay/test_op_level4.py

[1] Test case modified for int type

---

python/tvm/_ffi/_pyversion.py

[PY] Require python3.6

---

CONTRIBUTORS.md

Please welcome Arnaud Bergeron (@abergeron) as a TVM reviewer. He has been an active user of Relay and has contributed quite a few bug fixes and helped discuss and shape some of the Relay APIs as a user, as well as contributing Conda support and numerous ops.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=abergeron)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aabergeron)
- [Community Forum Summary](https://discuss.tvm.ai/u/abergeron/summary)

[COMMUNITY] Add @abergeron -> reviewer

---

CONTRIBUTORS.md

Please welcome Josh Fromm ( @jwfromm ) as a TVM reviewer. He has been working on operator and frontend support and actively reviewing other people's work. Josh did a good job help the project grows.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=jwfromm)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ajwfromm)
- [Community Forum Summary](https://discuss.tvm.ai/u/jwfromm/summary)

[COMMUNITY] Add @jwfromm -> reviewer

---

python/tvm/relay/frontend/tensorflow.py
python/tvm/relay/frontend/tensorflow_parser.py
python/tvm/relay/testing/tf.py
tests/python/frontend/keras/test_forward.py
tests/python/frontend/tensorflow/test_control_flow.py
tests/python/frontend/tensorflow/test_debugging.py
tests/python/frontend/tensorflow/test_forward.py
tests/python/frontend/tensorflow/test_no_op.py
tests/python/frontend/tflite/test_forward.py
tutorials/frontend/from_tflite.py

Tensorflow/TFLite test scripts updated so that i can run in both 1.13.1 and 2.0.0(for future 2.0 
@FrozenGene @srkreddy1238 Please review.

[TEST]Tensorflow/lite scripts upgrade from 1.13.1 to 2.0.0

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

@FrozenGene @wyc-ruiker @masahi @yzhliu Please help to review this PR.

[TFLITE]DepthToSpace and SpaceToDepth support

---

python/tvm/relay/op/op_attrs.py

[RELAY][PY] Fix relay node registration after refactor

---

vta/python/vta/top/graphpack.py

[TUTORIAL] Fix vta tutorial after relay function refactor

---

python/tvm/relay/op/op_attrs.py
src/relay/op/annotation/annotation.cc

#5108 
cc @windclarion @comaniac @tqchen

[Fix] Fix CompilerAttrs

---

python/tvm/relay/frontend/keras.py
tests/python/frontend/keras/test_forward.py

@FrozenGene please help to review conv3d for keras frontend. TIA

[KERAS] conv3d frontend operator support

---

Jenkinsfile

Update the tarball deployment.

---

docker/install/ubuntu_install_rust.sh

My recent changes to the Rust packages convert them to work on stable Rust. This PR updates the Docker image.

[Rust][CI] Change Rust version to stable in Docker

---

Jenkinsfile

[CI] Update rust docker

---

tutorials/frontend/deploy_quantized.py

[Tutorial][Quantization] Fix incorrect name of calibration mode

---

docs/contribute/index.rst
docs/contribute/release_process.rst

[Doc] TVM release process

---

python/tvm/relay/qnn/op/qnn.py
src/relay/qnn/op/add.cc
src/relay/qnn/op/mul.cc
src/relay/qnn/op/op_common.h
src/relay/qnn/op/subtract.cc
src/relay/qnn/util.h
tests/python/relay/test_op_qnn_add.py
tests/python/relay/test_op_qnn_subtract.py

* Adding support for QNN subtract operator.
* Refactoring the code for QNN Binary operators to use a common infrastructure.

Adding support for QNN subtract op

---

Jenkinsfile
cmake/modules/VTA.cmake
tests/scripts/task_config_build_cpu.sh
tests/scripts/task_config_build_gpu.sh
tests/scripts/task_config_build_gpu_vulkan.sh
tests/scripts/task_config_build_i386.sh
vta/python/vta/environment.py
vta/vta-hw/config/vta_config.py

These changes will make local reproduction of the ci env tests easier.

[CI] Move build configuration to shell scripts

---

cmake/modules/VTA.cmake
tests/lint/check_file_type.py
tests/scripts/task_clean.sh
tests/scripts/task_python_vta_fsim.sh
tests/scripts/task_python_vta_tsim.sh
vta/vta-hw/hardware/chisel/Makefile

[CI] Improve VTA build message and scripts.

---

src/te/schedule/schedule_dataflow_rewrite.cc

Check r!=nullptr before deferencing : r->source.size()

[Dataflow]: nullptr check

---

tests/python/relay/test_annotate_target.py
tests/python/relay/test_pass_merge_compiler_regions.py
vta/python/vta/environment.py

cc @tmoreau89 @dpankratz 
related https://github.com/apache/incubator-tvm/pull/5156

[TEST] Various CI fixes for the VTA and Relay 

---

python/tvm/relay/frontend/keras.py
tests/python/frontend/keras/test_forward.py

Max_pool3d and Averagepool3d frontend operator support in keras.
@FrozenGene @masahi @yzhliu  Please help to review. TIA

[FRONTEND][KERAS]Max_pool3d and Averagepool3d operator support 

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Some activation functions and their test cases for Torch
@masahi  Please help to review this PR, TIA

[PYTORCH]Activations for pytorch

---

src/relay/transforms/partition_graph.cc

Follow-up PR for codestyle changes for PR #5143
cc : @masahi @zhiics @comaniac

[RELAY] Partition graph codestyle fixes

---

python/tvm/relay/frontend/tensorflow.py
tests/python/frontend/tensorflow/test_forward.py

@jwfromm @FrozenGene Please help to review and merge. TIA

[BUGFIX]bugfix in tensorflow space_to_batch_nd

---

docs/conf.py
tests/scripts/task_python_docs.sh

[DOCS] Reduce artifcats generated by sphinx gallery

---

README.md
tests/scripts/task_python_docs.sh

- Reduce CI docs task log size.
- Update the relation to halide to the latest state.

[DOCS] Misc docs improvements

---

python/tvm/relay/op/nn/nn.py

@FrozenGene please check and help to merge. TIA

[DOCSTRING]missing function parameters updated

---

python/tvm/relay/frontend/keras.py
tests/python/frontend/keras/test_forward.py

UpSample3d & ZeroPadding3d Frontend op for Keras
@FrozenGene please help to review this PR.
TIA

[KERAS]Upsample3d & ZeroPadding3d op

---

src/runtime/vm/vm.cc

[Fix][VM] Fix copy constructor

---

docker/install/ubuntu_install_mxnet.sh
tests/python/frontend/mxnet/test_forward.py

cc @eric-haibin-lin @shoubhik @anijain2305

[CI] Update MxNet to 1.6.0 with MKL

---

src/te/schedule/message_passing.cc

[TE] Minor bugfix in message_passing.cc

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

```
- Hard swish op in tflite
- MobilnetV3 and Quantized mobilnet model
```
@jwfromm @FrozenGene @masahi  Please help to review this PR. TIA

[TFLITE]Hard Swish & MobilnetV3 model testing

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

- layernorm bug fixed
- layernorm testcase updated
- assert condition missing bug fixed
@masahi please help to review this PR. Thanks a lot.

[Pytorch]layernorm bug fix and testcase updated

---

python/tvm/driver/build_module.py
python/tvm/testing.py
src/driver/driver_api.cc
tests/python/unittest/test_target_codegen_static_init.py
tests/python/unittest/test_target_codegen_vm_basic.py
tests/python/unittest/test_tir_transform_make_packed_api.py

cc @kevinthesun @zhiics @yzhliu

[TIR] Fix perf regression of tir refactor

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

@masahi please help to review activations of pytorch. Thanks in advance.
-celu
-gelu
-selu
-some datatype conversion issues also fixed.
-testcase coverage added

[PYTORCH]celu, gelu, selu activations

---

Makefile

[LINT] Remove scalalint from lint deps

---

docs/install/from_source.rst

The following updates the compiler version in docs

[TVM][docs] compiler version in docs

---

tests/scripts/task_python_integration.sh

Due to problems under the 32bit platform, need more investigation
cc @liangfu @mehrdadhe  @tmoreau89 
#5298

[CI] Temporary disable CRT test

---

src/node/structural_equal.cc

[Node] Provide guide to user who has difficulty register SEqualReduce

---

src/target/target.cc

[CI] Fix the hexagon string

---

python/tvm/relay/frontend/caffe2.py

Hi, 
I add Mul and ConvTranspose operator to caffe2 frontend for support centerface model. 
@yzhliu please help to review.

[RELAY][FRONTEND][CAFFE2] add Mul and ConvTranspose operator

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

- Abs
- Arange
- Softplus
@masahi please help to review and merget these pytorch ops. Thanks a lot.

[PYTORCH]Abs, Arange, Softplus ops

---

python/tvm/relay/op/strategy/generic.py

write wrong name of OpStrategy's method add_implementation

[REALY][OP] fix typo

---

CONTRIBUTORS.md

Please join us to welcome @mbaret as a new reviewer to TVM. He contributes to the areas of the ARM GPUs, custom graph partitioning and high level graph optimization.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=mbaret)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ambaret)
- [Community Forum Summary](https://discuss.tvm.ai/u/matt-arm/summary)

[COMMUNITY] @mbaret -> Reviewer

---

tests/scripts/task_config_build_gpu.sh

[CI] Enable tsim and fsim for GPU build to avoid pack_lib error

---

python/tvm/relay/frontend/tflite.py

Common out tflite.Operator in the tflite frontend. 
@FrozenGene , could you please review this. 
Thanks,
Ramana

Factor out import of common tflite.Operator in tflite frontend.

---

src/target/llvm/codegen_amdgpu.cc

This fixes two things in the AMDGPU LLVM codegen.
- pointer lifetime of the LLVM context passed to codegen as a pointer
- the runtime::String refactor caused typing issues for one of the nodes

misc fixes for ROCm

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

- rsub
- embedded
- one_hot
#5133
@masahi  please help me to review this pytorch frontend ops. Thanks.

[PYTORCH]Rsub, Embedded, OneHot ops support

---

python/tvm/relay/frontend/keras.py
tests/python/frontend/keras/test_forward.py

@FrozenGene Please help to review the embedding layer op in Keras. Thanks

[KERAS]Embedding layer

---

docs/vta/install.rst

[Docs] VTA install doc migration from md to rst

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

- GatherND
- Round
- IsNaN
- IsInf
@masahi @FrozenGene Please help me to review and merge these ONNX frontend ops. 
Thanks

[ONNX]GatherNd, Round, IsNaN, IsInf

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Supported Logical Not for TFLite frontend.
@FrozenGene  @masahi  Please help to review and merge this PR.
TIA

[FRONTEND][TFLITE]Logical not op support

---

include/tvm/runtime/packed_func.h
tests/cpp/build_module_test.cc
tests/cpp/container_test.cc

Allows Optional<NDArray> and module to be passed with the right type code.

[RUNTIME] Improved Packed FFI for optional.

---

src/arithmetic/canonical_simplify.cc
tests/python/unittest/test_arith_canonical_simplify.py

[BUGFIX][BACKPORT-0.6][ARITH] Fix FloorMod Simplifier

---

python/tvm/relay/frontend/tflite.py

Some nits in TFLITE. Inconsistencies in the function names in tflite is removed.
@u99127 Could you please review this. Thanks in advance.

[TFLITE]Nit: Function names made consistent

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Add unit tests for ONNX PRelu and fix importer to pass them.

---

src/runtime/rpc/rpc_endpoint.cc
src/runtime/rpc/rpc_local_session.h
src/runtime/rpc/rpc_session.h
tests/python/unittest/test_runtime_rpc.py

cc @areusch @tmoreau89 @ZihengJiang

[RPC] Fix the multihop cpu case

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Update one test to hit the broken usecase.
@masahi another small onnx bug, if you don't mind. Thank you!

Fix an issue with ONNX Upsample

---

python/tvm/relay/frontend/onnx.py
src/relay/op/tensor/transform.cc
src/relay/op/tensor/unary.cc

fix a few bugs with shape inference and types in the ONNX importer

---

src/runtime/rpc/rpc_device_api.cc
tests/python/unittest/test_runtime_rpc.py

[RPC][BUGFIX] Fix remote device sync

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

@masahi Another ONNX op. Thanks!

Add Onnx Pad v11

---

docker/install/ubuntu_install_rust.sh

This is necessary to add tests for #5489.
@jroesch @nhynes @ehsanmok @tqchen Please help to review.

[CI] Install wasmtime for WebAssembly tests

---

topi/python/topi/arm_cpu/conv2d_alter_op.py

https://discuss.tvm.ai/t/autotuner-fails-for-cnn-in-new-dev-branch/6099

[Fix] Fix conv2d alter op for arm cpu

---

Jenkinsfile

cc @zhiics @tmoreau89 @ZihengJiang

[CI] Update ci-lint to use the latest image that contains clang-format

---

tests/python/frontend/tflite/test_forward.py

Signed-off-by: Giuseppe Rossini <giuseppe.rossini@arm.com>
I am adding a conv2/quantized test case in `tests/python/frontend/tflite/test_forward.py`
@anijain2305 Could you please review this? Thanks!

Add a quantized conv2 unit test for the tflite front-end

---

src/relay/transforms/merge_composite.cc

Found while reviewing some recent changes!

[Relay][Transform] Safe check added for Merge Composite Call Node

---

include/tvm/runtime/device_api.h

Fix a typo.

---

apps/ios_rpc/tvmrpc.xcodeproj/project.pbxproj
apps/ios_rpc/tvmrpc/TVMRuntime.mm

This PR fixes build error of the iOS RPC.
- Update to C++14
- Use the latest RPC protocol
- Resolve CoreML dependency
@tqchen @ZihengJiang @FrozenGene Please help to review.

[IOS] Fix build error of iOS RPC

---

include/tvm/runtime/c_backend_api.h
include/tvm/runtime/object.h

Fix three typos

---

python/tvm/relay/frontend/mxnet.py
tests/python/frontend/mxnet/test_forward.py

MaxPool3D and AvgPool3D op support added in mxnet.
@FrozenGene @masahi Please help to review this PR. TIA
First need to merge #5098 as im using global pool api from this PR.

[MXNET]MaxPool3d and AvgPool3d Ops support added

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Added support for below ops.
aten::reflection_pad2d
aten::elu_
https://github.com/apache/incubator-tvm/issues/5133#issuecomment-630673045
@masahi please help to review this PR. TIA

[PYTORCH]ReflectionPad2d op

---

docs/conf.py
tests/scripts/task_python_docs.sh
tests/scripts/task_sphinx_precheck.sh

cc @zhiics @yzhliu @tmoreau89 @ZihengJiang

[DOCS] Move the api docs to the api subfolder

---

tests/scripts/task_sphinx_precheck.sh

Fix typo in test script

---

tutorials/frontend/deploy_prequantized_tflite.py

QNN Tutorial series on tflite. Continuation of PRs #5321(PyTorch) & #5362(MxNet)
This PR can be merged after #5362
@anijain2305 @masahi Please help to review this PR.

[TUTORIAL]TFLite QNN Tutorial

---

src/relay/ir/dataflow_matcher.cc

[PatternLang] Remove unnecessary print

---

include/tvm/relay/attrs/nn.h
python/tvm/relay/frontend/mxnet.py
python/tvm/relay/op/nn/_nn.py
python/tvm/relay/op/nn/nn.py
python/tvm/relay/op/op_attrs.py
python/tvm/relay/op/strategy/cuda.py
python/tvm/relay/op/strategy/generic.py
src/relay/op/nn/correlation.cc
tests/python/frontend/mxnet/test_forward.py
tests/python/relay/test_op_level2.py
topi/python/topi/cuda/__init__.py
topi/python/topi/cuda/correlation.py
topi/python/topi/generic/nn.py
topi/python/topi/nn/__init__.py
topi/python/topi/nn/correlation.py
topi/python/topi/testing/__init__.py
topi/python/topi/testing/correlation_nchw_python.py
topi/tests/python/test_topi_correlation.py

Reference APIs:
Pytorch https://github.com/NVIDIA/flownet2-pytorch/blob/master/networks/correlation_package/correlation.py#L46-L54
MxNet https://beta.mxnet.io/api/ndarray/_autogen/mxnet.ndarray.Correlation.html
please review @icemelon9 @yzhliu @masahi

[Relay, Topi][OP] Correlation

---

python/tvm/autotvm/tuner/xgboost_cost_model.py

cc @liangfu @hcho3 @merrymercy

[AutoTVM] Update XGBoost verbosity option

---

src/relay/ir/dataflow_matcher.cc
tests/python/relay/test_dataflow_pattern.py

Fixes https://github.com/apache/incubator-tvm/issues/5647
@comaniac @masahi Thanks!

[PatternLang] Convert PatternGrouper to do pre-order, non-recursive analysis

---

topi/python/topi/mali/conv2d.py

Hi @FrozenGene @kevinthesun @comaniac
I am interested in issue #5215, however, I am not familiar with `TOPI` and `backend`. I would appreciate that if you can guide me to complete this work, thank you in advance. :)

[AutoTVM][TOPI] AutoTVM incorrect measurement

---

docs/api/python/index.rst
docs/api/python/micro.rst

add tvm.micro pydoc to sphinx

---

tests/python/relay/test_dataflow_pattern.py

Add a regression testcase for #5674

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Added support of 1D/2D/3D LpPool for ONNX Frontend
@masahi @FrozenGene please help me to review and merge this PR. TIA.

[ONNX]LpPool Support added

---

python/tvm/autotvm/tophub.py

Avoid downloading when TOPHUB_LOCATION is NONE

---

topi/tests/python/test_topi_pooling.py

https://ci.tvm.ai/job/tvm/job/master/1081/execution/node/336/log/

[TEST][FLAKY] Fix flaky test_topi_pooling.py:test_adaptive_pool

---

tests/cpp/relay_transform_sequential_test.cc

#5744 
Thanks @junrushao1994 for reporting this.
cc @icemelon9

[FIX][TEST] Fix sequential cpp test

---

include/tvm/relay/attrs/transform.h
python/tvm/relay/frontend/onnx.py
python/tvm/relay/op/_transform.py
python/tvm/relay/op/strategy/generic.py
python/tvm/relay/op/transform.py
src/relay/op/tensor/transform.cc
tests/python/frontend/onnx/test_forward.py
tests/python/relay/test_op_level3.py
tests/python/relay/test_op_level5.py
topi/python/topi/__init__.py
topi/python/topi/generic/search.py
topi/python/topi/scatter.py

cc: @jwfromm @tqchen @masahi 
The actual hybrid script implementation is kind of gross, I can't seem to figure out a way to clean it up without causing very opaque errors in the hybrid script module. If anyone has suggestions on cleaning that up, I'd love to hear them.

Add Scatter to Topi/Relay/ONNX via hybrid script

---

src/arithmetic/rewrite_simplify.cc
tests/python/unittest/test_arith_rewrite_simplify.py

[ARITH][BACKPORT-0.6] fix a min/max simplify bug

---

tests/scripts/task_web_wasm.sh

Per https://github.com/apache/incubator-tvm/pull/5748#issuecomment-641526616

[Minor][Test] Clean WASM environment before build

---

python/tvm/relay/frontend/darknet.py

Fix the issue of batch size reported in https://discuss.tvm.ai/t/yolov3-tiny-batch-input-test-failed/6796
@FrozenGene Please help to review this PR. TIA.

[FRONTEND]Darknet support batch size for yolo

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Support added for the below ops.
-- aten::norm
-- aten::frobenius_norm
https://github.com/apache/incubator-tvm/issues/5133#issuecomment-642632617
@masahi Please help to review this PR. TIA
cc @SJTU-yys

[PYTORCH]aten::norm support added

---

python/tvm/relay/frontend/tensorflow.py
tests/python/frontend/tensorflow/test_forward.py

@kevinthesun Could you please take a look? Thanks

[TF] Support symbolic inputs of Fill

---

CONTRIBUTORS.md

Please join us to welcome @wpan11nv as a new reviewer :) He has been quite active
contributing to the CUDA backend and reviewed many non-trival code related to tensor core and warp level parallelism.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=wpan11nv)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Awpan11nv)
- [Community Forum Summary](https://discuss.tvm.ai/u/wpan11nv/summary)

[COMMUNITY] @wpan11nv -> Reviewer

---

topi/python/topi/cuda/sparse.py
topi/tests/python/test_topi_sparse.py

@antinucleon @vinx13 please review! ty:)

[topi] fix sparse dense schedule on cuda

---

tests/scripts/task_cpp_unittest.sh
tests/scripts/task_golang.sh
tests/scripts/task_java_unittest.sh
tests/scripts/task_python_docs.sh
tests/scripts/task_python_integration.sh
tests/scripts/task_python_topi.sh
tests/scripts/task_python_vta_fsim.sh
tests/scripts/task_python_vta_tsim.sh
tests/scripts/task_rust.sh

To reduce pressure on a crowded CI setting.

[CI] Limit number of threads in all jobs

---

CONTRIBUTORS.md

Please join us to welcome @siju-samuel  as a new committer of the TVM community. He has been actively contributing to various frontends to the TVM including TFLite, darknet and qnn.
- [Commits](https://github.com/apache/incubator-tvm/commits?author=siju-samuel)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Asiju-samuel)
- [Community](https://discuss.tvm.ai/u/siju-samuel/summary)

[COMMUNITY] Siju Samuel -> Committer

---

include/tvm/node/container.h
src/ir/expr.cc
tests/python/unittest/test_target_custom_datatypes.py

Error msg update

---

Jenkinsfile

Fix v0.6 CI

---

src/relay/pass/fold_constant.cc
tests/python/relay/test_pass_fold_constant.py

[BACKPORT-0.6] Add ConstantNode to IsAtomic

---

src/relay/backend/vm/removed_unused_funcs.cc
src/relay/ir/alpha_equal.cc
tests/python/relay/test_ir_nodes.py
tests/python/relay/test_pass_alpha_equal.py
tests/python/relay/test_pass_fuse_ops.py
tests/python/relay/test_pass_remove_unused_functions.py

[BACKPORT-0.6] Fix alpha_equal bug

---

src/relay/backend/vm/removed_unused_funcs.cc
src/relay/ir/alpha_equal.cc
tests/python/relay/test_ir_nodes.py
tests/python/relay/test_pass_alpha_equal.py
tests/python/relay/test_pass_fuse_ops.py
tests/python/relay/test_pass_remove_unused_functions.py

[BACKPORT-0.6] fix RemoveUnusedFunctions pass

---

python/tvm/relay/frontend/tensorflow.py
tests/python/frontend/tensorflow/test_forward.py

Fix tf parsing dynamic shape placeholder.
@zhiics @yongwww @lixiaoquan

[Frontend][TensorFlow]Fix TF Dynamic input shape

---

python/tvm/relay/frontend/mxnet.py
python/tvm/relay/frontend/nnvm_common.py
tests/python/frontend/mxnet/test_forward.py

Thanks the help from @eric-haibin-lin.

[Frontend][MXNet] Support a few contrib ops in mxnet

---

python/tvm/_ffi/libinfo.py
topi/python/topi/cpp/impl.py

[BACKPORT-0.6][BUGFIX] Fix search path for libtvm_topi.so

---

python/tvm/_ffi/base.py

[BACKPORT-0.6][BUGFIX] Fix Python debugger segfaults with TVM built with LLVM

---

python/tvm/relay/frontend/keras.py
tests/python/frontend/keras/test_forward.py

- RepeatVector 
- Conv3DTranspose
The above 2 ops support is added for keras frontend.
@masahi @FrozenGene Please help to review this PR. TIA.

[KERAS]RepeatVector, Conv3DTranspose op support added

---

python/tvm/rpc/server.py

[BACKPORT-0.6][BUGFIX] Fixed process termination routine in windows

---

python/tvm/relay/quantize/_annotate.py
src/relay/pass/quantize/realize.cc
tests/python/relay/test_pass_auto_quantize.py

https://github.com/apache/incubator-tvm/pull/4458
@yzhliu

[BACKPORT-0.6][Quantization] Fix annotation for multiply op (#4458)

---

src/tir/transforms/bf16_legalize.cc

Fix for a minor issue due to concurrent merge of #5601 and #5740

Fix map assign issue in CI test

---

docs/langref/relay_pattern.rst

#5760 introduces new patterns (dtype and shape). This PR updates the document to reflect those updates.
cc @mbrookhart

[DOCS] Update has_dtype/has_shape to pattern lang doc

---

src/node/serialization.cc

https://github.com/apache/incubator-tvm/pull/4503

[BACKPORT-0.6][Serialization]fix serialization precision loss in float

---

python/tvm/relay/frontend/tensorflow.py
tests/python/frontend/tensorflow/test_debugging.py

Co-authored-by: LiangHao <hliangac@connect.ust.hk>
#4711

[BACKPORT-0.6][Frontend][TF] fix _parse_param bug

---

python/tvm/relay/op/_tensor_grad.py
tests/python/relay/test_op_grad_level1.py

Co-authored-by: SWu <SWu@users.noreply.github.com>
#4516

[BACKPORT-0.6]Fix bias_add gradient

---

src/relay/backend/vm/inline_primitives.cc

Co-authored-by: abergeron <abergeron@gmail.com>
#4783

[BACKPORT-0.6] Make sure to visit the arguments of inlined functions

---

src/runtime/vm/vm.cc

[BACKPORT-0.6][Fix][VM] Fix copy constructor

---

python/tvm/relay/op/_tensor_grad.py
tests/python/relay/test_op_grad_level2.py

[BACKPORT-0.6] fix small bug about dense_grad

---

src/runtime/opencl/aocl/aocl_module.cc
src/runtime/opencl/sdaccel/sdaccel_module.cc

[BACKPORT-0.6][RUNTIME] Fix compile errors of OpenCL FPGA backend

---

topi/src/topi.cc
topi/tests/python/test_topi_pooling.py

[BACKPORT-0.6] fix topi.nn.global_pool layout=NHWC

---

python/tvm/_ffi/base.py

[BACKPORT-0.6] Fix hasattr by extracting Python error type from Windows error message

---

src/runtime/graph/graph_runtime.h

[BACKPORT-0.6][Runtime] Export GraphRuntime in tvm_runtime.dll

---

src/common/base64.h

[BACKPORT-0.6] Fix Base64OutStream portability issue

---

python/tvm/autotvm/task/space.py
tests/python/unittest/test_autotvm_space.py

[BACKPORT-0.6][AUTOTVM] Fix a bug in generating the search space

---

python/tvm/relay/frontend/tensorflow.py

[BACKPORT-0.6][TENSORFLOW] Fix FuseBatchNorm output cast error if need_cast is True

---

vta/hardware/chisel/src/main/scala/core/LoadUop.scala

[BACKPORT-0.6][Bugfix][VTA] Fix multiple transfer issue in LoadUop module

---

CONTRIBUTORS.md

Please join us to welcome @mbrookhart as a new reviewer of the TVM community. He has been actively contributing to non-recursive graph visitor, Relay pattern language and matcher, and ONNX frontend conversions.
- [Commits](https://github.com/apache/incubator-tvm/commits?author=mbrookhart)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ambrookhart)
- [Community Forum Summary](https://discuss.tvm.ai/u/mbrookhart/summary)

[COMMUNITY] Matthew Brookhart -> Reviewer

---

src/target/source/source_module.cc

Per requested from #5885, this PR removes the fatal log to safely skip unknown functions.
cc @mbaret @zhiics

[Relay] Skip Unknown Function Symbols

---

python/tvm/target/intrin.py

cc @windclarion @zhiics @yzhliu 
Fixes https://github.com/apache/incubator-tvm/issues/5891

HotFix the python intrin rule

---

vta/src/tsim/tsim_driver.cc

[BACKPORT-0.6][Bugfix][VTA] Fixed a crash issue in TSIM driver

---

python/tvm/relay/op/_tensor_grad.py
tests/python/relay/test_op_grad_level1.py
tests/python/relay/test_op_grad_level10.py
tests/python/relay/test_op_grad_level3.py
tests/python/relay/test_op_grad_level4.py

I don't think #2562 is up to date, but hey...

add a few gradients

---

python/tvm/relay/memory_alloc.py
src/relay/backend/vm/lambda_lift.cc
tests/python/frontend/tensorflow/test_control_flow.py
tests/python/relay/test_pass_lambda_lift.py

* Fix lambda lift
* clean up
* lint
* fix
* remove unused import
@yzhliu

[BACKPORT-0.6][Relay][Pass] Fix lambda lift pass for recursive call

---

topi/python/topi/x86/dense.py

[BACKPORT-0.6][Fix] Fix dense x86 schedule

---

src/relay/pass/alter_op_layout.cc
tests/python/relay/test_pass_alter_op_layout.py

* [Relay][Fix] Fix alter op layout when calling a global var
* add test case
@yzhliu

[BACKPORT-0.6][Relay][Fix] Fix alter op layout when calling a global var

---

topi/python/topi/arm_cpu/conv2d.py

[BACKPORT-0.6][Fix] Fix conv2d alter op for arm cpu

---

docs/langref/relay_pattern.rst
python/tvm/relay/dataflow_pattern/__init__.py
src/relay/ir/dataflow_matcher.cc
tests/python/relay/test_dataflow_pattern.py

Per discussion in https://discuss.tvm.ai/t/pattern-matching-for-tuplegetitem/7069, this PR supports arbitrary index matching for tuple get item node.
Document is also updated.
cc @mbrookhart @t-vi

[PatternLang] Support any index matching for TupleGetItem

---

vta/hardware/chisel/src/main/scala/core/TensorAlu.scala

[BACKPORT-0.6][VTA] End-to-end Inference with Chisel VTA

---

src/arithmetic/canonical_simplify.cc
tests/python/unittest/test_arith_canonical_simplify.py

[BACKPORT-0.6][Bugfix][Arith] keep div_mode during floordiv simplify

---

src/runtime/metadata_module.cc

To reduce the overhead of runtime symbol lookup, we should only initialize the runtime modules that include the symbol we need for executing this graph.
cc @zhiics @mbaret

[Runtime] Only initialize required module

---

NOTICE

[v0.6] Update date in the NOTICE

---

NOTICE

Update date in the NOTICE

---

docs/contribute/release_process.rst

[Doc] minor fix for release doc

---

include/tvm/tir/analysis.h
src/arith/canonical_simplify.cc
src/arith/ir_mutator_with_analyzer.cc
src/te/schedule/operation_inline.cc
src/te/schedule/schedule_ops.cc
src/tir/analysis/side_effect.cc
src/tir/transforms/remove_no_op.cc
src/tir/transforms/simplify.cc
src/tir/transforms/split_host_device.cc
tests/cpp/tir_analysis_side_effect.cc

cc @zhiics @ZihengJiang @junrushao1994

[TIR][ANALYSIS] Refine side effect analysis.

---

python/tvm/relay/backend/profiler_vm.py
python/tvm/relay/backend/vm.py

Signed-off-by: leonwanghui <wanghui71leon@gmail.com>

Fix some typo errors in license header

---

.github/workflows/main.yml

https://github.com/actions/setup-python/releases

GitHub Actions upgrade to actions/setup-python@v2

---

python/tvm/target/target.py

Undefined names: import os for line 324 & import re for line 308

---

tests/python/unittest/test_arith_solve_linear_inequality.py

I cannot reproduce locally, but let's give it a try.
#6009 
@tqchen @junrushao1994

[TEST][FLAKY] Fix test_arith_solve_linear_inequality.py::test_multi_equal

---

docker/with_the_same_user

Remove duplicate line `HOME=${CI_BUILD_HOME}`, and reformat the script

Remove duplicate line

---

docs/dev/codebase_walkthrough.rst
include/tvm/runtime/object.h
src/node/attr_registry.h
src/relay/op/tensor/binary.cc
tutorials/dev/relay_pass_infra.py

@zhiics
Hi Zhi,
Please review my pull request when you have time. It is related to typo fix in code comments and tutorial.
Thank you so much!
Zheng

fix typos in comments and relay tutorial

---

docker/install/ubuntu_install_tensorflow.sh

cc @zhiics @jroesch @tmoreau89

[DOCKER] Pin keras version

---

Jenkinsfile

cc @zhiics @comaniac @tmoreau89 
Docker Image with DNNL and keras pinned as in (https://github.com/apache/incubator-tvm/pull/6032)

[CI] Update ci-cpu to the latest

---

python/tvm/relay/frontend/pytorch.py

This PR is to fix the issue described here: https://github.com/apache/incubator-tvm/issues/6050

Fix pytorch frontend prim::Constant issue

---

include/tvm/tir/expr_functor.h
src/tir/ir/expr_functor.cc

[Fix] Add missing expr visitor for any

---

tests/python/relay/test_pass_fast_math.py

[Test] Add missing test for fast erf

---

tests/lint/check_file_type.py

add opencl .cl file type to lint

lint: add opencl .cl file type

---

docker/Dockerfile.ci_gpu
docs/README.txt
docs/conf.py

cc @yzhliu @tmoreau89 @ZihengJiang

[DOCS] Cleanup docs build instructions.

---

docs/install/from_source.rst

Make some minor improvements to the install from source doc
about flags to enable, package managers, and virtual environments.

Update installation doc with minor improvements

---

version.py

[Fix] Remove the tvm web from version update

---

docs/index.rst

This PR categorizes the docs into a few categories:
- How To
- Tutorials
- References
- Deep Dive
- MISC
Co-authored-by: Chris Hoge <chris@hogepodge.com>

[DOCS][REFACTOR] Clarify Docs Categorization

---

CONTRIBUTORS.md

Adding Thomas Viehmann  @t-vi to list of contributors.
Thomas has made valuable contributions to TVM, notably improving and maintaining the ROCm code generation backend and TOPI schedules for AMD GPUs. In addition Thomas has put together an impressive BERT training demo in Pytorch using TVM codegen by making steady enhancements to TVM including tunable schedules for batched mat mult, enhancements to the Pytorch frontend, adding a combine batch_matmul pass, and welcome improvements to Relays first order gradient graphs.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=t-vi)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3At-vi)
- [Community Forum Summary](https://discuss.tvm.ai/u/t-vi/summary)

[COMMUNITY] @t-vi  -> Reviewer

---

python/tvm/relay/frontend/common.py

@kevinthesun @zhiics Reduces the free_var warnings for TF object detection models.

[Parser] Typo in mod creation

---

docs/README.txt

cc @jroesch @electriclilies @tmoreau89

[DOCS] Improve the docs build instructions

---

CMakeLists.txt
apps/README.md
conda/tvm/meta.yaml
rust/tvm-rt/README.md
tests/scripts/task_python_nightly.sh

Final cleanup step cc @zhiics @ZihengJiang @yzhliu

[BUILD] Remove libtopi from the build

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

* Added implementation for PADV2 Operator.
* Added support for constant values in PAD Operator.
* Added tests for PADV2 Operator.

[TFLite] Implemented PADV2 Operator for TFLite and added support for constant values in PAD.

---

include/tvm/runtime/container.h
include/tvm/runtime/packed_func.h
tests/python/unittest/test_node_reflection.py

[RUNTIME] Enable auto conversion String->DLDataType

---

include/tvm/topi/transform.h
python/tvm/relay/op/dyn/_transform.py
python/tvm/relay/op/transform.py
src/relay/op/dyn/tensor/transform.cc
src/relay/op/make_op.h
src/relay/transforms/dynamic_to_static.cc
tests/python/relay/dyn/test_dynamic_op_level10.py
tests/python/relay/test_pass_dynamic_to_static.py

Also includes a refactor of the dynamic-to-static pass to make it a little more modular/a little faster at runtime.
cc: @icemelon9 @zhiics @yongwww @electriclilies 
Thanks!

[Relay][Dynamic] OneHot operation

---

CONTRIBUTORS.md

Please join us to welcome @jcf94  as a new reviewer. He has made a good chunk of contributions to the latest AutoScheduler(AutoTVMv2) as well as support for tensor core related codegen primitives.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=jcf94)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:jcf94)
- [Community Forum Summary](https://discuss.tvm.ai/u/jcf94/summary)

[COMMUNITY] jcf94 -> Reviewer

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

* Added implementation for ONE_HOT Operator.
* Added tests for ONE_HOT Operator.

[TFLite] Implemented ONE_HOT Operator for TFLite.

---

src/target/source/literal/cuda_half_t.h

Reverts apache/incubator-tvm#6225

Revert "fix cuda half math function is undefined: hpow, htanh"

---

python/tvm/relay/frontend/mxnet.py

This op can be mapped directly to batch norm.

[Mxnet] Support _contrib_SyncBatchNorm

---

include/tvm/runtime/packed_func.h

[LINT] Fix clang-format

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Should fix https://github.com/apache/incubator-tvm/issues/6282
Please review @siju-samuel

[Torch] Support index_select

---

tests/python/unittest/test_auto_scheduler_cost_model.py

[AutoScheduler] Fix flaky test

---

src/relay/backend/graph_plan_memory.cc

[Relay] fix typo

---

include/tvm/topi/transform.h
python/tvm/relay/op/_transform.py
src/relay/op/tensor/transform.cc
tests/python/relay/test_any.py

[Relay] Enhance relay.split(), allow splitted dim to be dynamic

---

python/tvm/relay/frontend/tensorflow.py

[Frontend][TensorFlow] Improve TensorFlow control flow nodes ordering

---

docs/install/docker.rst
src/relay/op/tensor/transform.cc

[DOCS] Fix the docker binary cache location

---

src/runtime/metal/metal_device_api.mm

[METAL] Use CFBridgeRetain for retaining the allocated resource

---

python/tvm/contrib/target/onnx.py
tests/python/contrib/test_onnx.py

This PR adds support for more operator support in onnx converter.
New operator added:
- layout_transform
- clip
- expand_dims

[TARGET] Add layout_transform, clip and expand_dims in onnx converter

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

Fix https://github.com/apache/incubator-tvm/issues/6407
please review @siju-samuel

[Torch] reshape op with non constant shape argument

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

* Added implementation for MATRIX_DIAG Operator.
* Added tests for MATRIX_DIAG Operator.

[TFLite] Implemented MATRIX_DIAG Operator for TFLite.

---

src/relay/transforms/pattern_util.h

Address issue #6415 as disscussed in PR #6416 opened by @tom-gall .
* Proposed fix comes by @tqchen proposal: https://github.com/apache/incubator-tvm/pull/6416#issuecomment-688527472
-----
@junrushao1994 , @u99127 , @tqchen please help with the review.
Thank You !

Address issue #6415 using compiler-rt half-float function.

---

src/auto_scheduler/compute_dag.cc

As title
Caused by #6297, actually @comaniac pointed out this line but it somehow was not addressed

[FIX] Hot fix for Windows CI

---

include/tvm/topi/detail/broadcast.h
tests/python/relay/test_any.py

Fix broadcast infer shape so that symbolic expression shape can be accepted.
@icemelon9 @zhiics

Fix broadcast shape

---

include/tvm/topi/transform.h
python/tvm/relay/frontend/pytorch.py
python/tvm/relay/op/_transform.py
python/tvm/relay/op/transform.py
python/tvm/topi/transform.py
src/relay/op/tensor/transform.cc
src/topi/transform.cc
tests/python/relay/test_any.py
tests/python/relay/test_op_level3.py
tests/python/topi/python/test_topi_transform.py

Add numpy style advanced indexing to topi and relay.
@zhiics @yongwww @masahi

[Relay][Topi][Op]Advanced indexing

---

docker/Dockerfile.ci_lint

@tqchen this adds black to dockerlint container, do we need to install it anywhere else?

[Format][CI] Add black to lint docker image

---

apps/howto_deploy/cpp_deploy.cc
apps/howto_deploy/prepare_test_libs.py
apps/howto_deploy/tvm_runtime_pack.cc

[APPS] Add How to deploy graph runtime example under new module factory

---

CONTRIBUTORS.md

Please join us to welcome Hao Yu (@comaniac) as a new Committer. Hao has been actively contributing to Relay, BYOC and Ansor. Hao is also quite active in reviewing and providing suggestions to a lot of pull requests, RFCs as well as answering questions in the forum.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=comaniac)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Acomaniac)
- [Community](https://discuss.tvm.ai/u/comaniac/summary)

[COMMUNITY] comaniac -> Committer

---

CONTRIBUTORS.md

Please join us to welcome @lhutton1 as a new reviewer. He has been actively contributing to bring-your-own-codegen (BYOC), ConvertLayout, and integrating the Arm Compute Library into TVM. He also helped review BYOC and Relay pass PRs.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=lhutton1)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:lhutton1)
- [Community Forum Summary](https://discuss.tvm.ai/u/lhutton1/summary)

[COMMUNITY] lhutton1 -> Reviewer

---

tests/python/relay/test_pass_convert_op_layout.py

After #6442 was merged, black started complaining about formatting of test_pass_convert_op_layout.py. Format here.
cc @masahi @comaniac

[Formatting] Fix python formatting issue

---

python/tvm/topi/bifrost/gemm.py

#6473 
Added the missing import.
I did not any new tests since I cannot fix pytest.
@tqchen please have a look.

[TOPI] Fix missing import in bifrost schedule

---

python/tvm/contrib/cc.py
python/tvm/micro/artifact.py
python/tvm/micro/build.py
python/tvm/micro/class_factory.py
python/tvm/micro/compiler.py
python/tvm/micro/debugger.py
python/tvm/micro/micro_binary.py
python/tvm/micro/micro_library.py
python/tvm/micro/session.py
python/tvm/micro/transport.py
python/tvm/relay/frontend/pytorch.py
python/tvm/relay/op/_transform.py
python/tvm/relay/op/nn/_nn.py
python/tvm/relay/op/vision/_vision.py
python/tvm/rpc/client.py
python/tvm/target/target.py
python/tvm/topi/x86/conv2d.py
tests/lint/add_asf_header.py
tests/lint/check_file_type.py
tests/python/frontend/pytorch/test_forward.py
tests/python/relay/test_any.py
tests/python/topi/python/test_topi_pooling.py
tests/python/unittest/test_crt.py
tests/python/unittest/test_runtime_rpc.py
tutorials/micro/micro_tflite.py

Rerun black on master to catch some formatting changes that merged as the CI test was going in.
cc @tqchen @jroesch

black format master

---

python/tvm/topi/bifrost/dense.py

Fixed #6492 
There should already be a test but not enabled in CI.
@tqchen please have a look.

[TOPI] Fixed a typo in topi key

---

tutorials/frontend/deploy_object_detection_pytorch.py

Need https://github.com/apache/incubator-tvm/pull/6449
@zhiics @yongwww @masahi @t-vi

[Frontend][Tutorial]Add Pytorch OD tutorial

---

python/tvm/hybrid/_ffi_api.py
python/tvm/hybrid/intrin.py
python/tvm/hybrid/parser.py
python/tvm/hybrid/registry.py
python/tvm/hybrid/scope_handler.py
python/tvm/hybrid/special_stmt.py
python/tvm/hybrid/ty.py
src/printer/tir_hybrid_printer.cc
tests/python/unittest/test_hybrid_error_report.py
tests/python/unittest/test_hybrid_roundtrip.py

- update the registration mechanism
- improve For syntax
- improve env thread syntax
cc @tqchen @junrushao1994 @Hzfengsy

[TIR][Hybrid] Hybrid Script Improvement

---

python/tvm/relay/op/nn/nn.py

#6490
@tqchen please have a look.

[RELAY] Improve doc for nn.dense

---

CONTRIBUTORS.md

Please join us to welcome @hypercubestart as a new reviewer. He has been contributing to non-trivial optimizations in Relay. Andrew also actively review PRs, anticipates and shares his thoughts in the discuss forum.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=hypercubestart)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%hypercubestart)
- [Community Forum
Summary](https://discuss.tvm.apache.org/u/hypercubestart/summary)

[COMMUNITY] hypercubestart -> Reviewer

---

python/tvm/relay/op/nn/_nn.py
python/tvm/topi/arm_cpu/conv2d.py
python/tvm/topi/arm_cpu/conv2d_spatial_pack.py
python/tvm/topi/arm_cpu/conv2d_transpose.py
python/tvm/topi/nn/pad.py
tests/python/relay/test_any.py

This PR enables Pytorch OD model compilation for arm cpu.
@zhiics @yongwww @icemelon9

[Relay]Allow dynamic batch for arm conv2d

---

README.md

cc @tmoreau89 @jroesch @yzhliu @zhiics

Update CI badge location

---

Jenkinsfile

cc @jroesch @tmoreau89 @ZihengJiang

[CI] Cancel previous build if a new commit is pushed to a PR

---

pyproject.toml
python/tvm/topi/nn/conv2d_transpose.py
python/tvm/topi/testing/pool3d_python.py
tests/python/topi/python/test_topi_conv2d_transpose_nchw.py

cc @jroesch @ZihengJiang @zhiics

[LINT] Use fmt off to disable problematic black fmt

---

tutorials/get_started/tensor_expr_get_started.py
tutorials/language/reduction.py
tutorials/language/scan.py
tutorials/topi/intro_topi.py

Now I have a CUDA machine, so I can run some tutorials target CUDA, these files have the same issue with those of previous PR #6454, the fixing is easy too.

[TUTORIAL] Fix Some Failed Tutorials of The Issue #6453

---

rust/tvm/examples/resnet/src/build_resnet.py

[FIX] fix the python script for building resnet (#6526)

---

python/tvm/relay/testing/yolo_detection.py
tutorials/frontend/from_darknet.py

Issue:
Current yolo detection test only provide a image drawing solution
to output detection result, but for console user, such result
would not available for a view.
Solution:
Here we add a text show function to show detection result in
text format for testing in console scenario.

[Relay] Show yolo detection result in text.

---

web/package.json
web/src/rpc_server.ts
web/src/webgpu.ts

This PR fixes the outdated WebGPU API and could fix https://github.com/tqchen/tvm-webgpu-example .
@vinx13

[WebGPU] update webgpu api

---

src/arith/rewrite_simplify.cc
tests/python/unittest/test_arith_rewrite_simplify.py

@tqchen Please take a look, thanks

[TIR] Fix rewrite_simplify tir::builtin::shift_left

---

apps/bundle_deploy/demo.cc

[APP] Fix misprint in demo.cc during initializing of picture tensor data

---

python/tvm/relay/frontend/mxnet.py
tests/python/frontend/mxnet/test_forward.py

Adds support in MXNet frontend for:
* [dot](https://mxnet.apache.org/versions/1.6/api/r/docs/api/mx.symbol.dot.html) AKA dense/matmul. Only 2-D input case is supported now.
* [LogisticRegressionOutput](https://mxnet.apache.org/versions/1.6/api/r/docs/api/mx.symbol.LogisticRegressionOutput.html) AKA sigmoid.
Both ops can be mapped to existing Relay operators.

[RELAY][MXNET][FRONTEND] Support "dot" and "LogisticRegressionOutput"

---

docs/contribute/release_process.rst

@tqchen @zhiics @ZihengJiang 
KEYS updated https://dist.apache.org/repos/dist/dev/incubator/tvm/KEYS

[Doc] Update release document

---

docker/lint.sh

add black-format to docker/lint.sh, suppport in-place format

---

docs/contribute/release_process.rst

[Doc] add KEYS to downloads.apache.org

---

conda/tvm-libs/meta.yaml
conda/tvm/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py

[RELEASE] Bump version to 0.7.0

---

NEWS.md

[RELEASE] Update NEWS.md for v0.7

---

conda/tvm-libs/meta.yaml
conda/tvm/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py

Now that v0.7 branch is officially cut.
cc @ZihengJiang @yzhliu @jroesch @zhiics

[VERSION] Version for v0.8 cycle

---

src/relay/op/tensor/transform.cc
tests/python/relay/test_pass_convert_op_layout.py

@zhiics @yongwww @anijain2305 @trevor-m

[Relay] Fix Strided Slice Infer Layout

---

include/tvm/runtime/object.h

The example code in the comment for Object had errors

Fix example code

---

CONTRIBUTORS.md

Please join us to welcome @areusch as a new reviewer. Andrew has been actively contributing to uTVM, on-device RPC server, and various runtime changes. He proposed the roadmap for uTVM and presented the work at the online meetup. Andrew has also been very actively sharing his thoughts at the discussion forum.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=areusch)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:areusch)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/areusch/summary)

[COMMUNITY] areusch -> Reviewer

---

python/tvm/autotvm/task/task.py

Simple PR to print out the autotvm task name when it was not found.

[FIX,AUTOTVM] More descriptive error message when an autotvm task is not found

---

src/relay/analysis/type_solver.cc
tests/python/relay/test_type_infer.py
tests/python/topi/python/test_topi_sparse.py

See the discussion in https://github.com/apache/incubator-tvm/issues/6594#issuecomment-706472689
@kevinthesun @lixiaoquan @jroesch @MarisaKirisame

Revert "[Relay] Keep fixed dim when unifying dynamic shape (#5795)"

---

python/tvm/relay/testing/vgg.py

Fix typographical error.

---

.github/workflows/main.yml

Hi @tqchen , this is a subsequence of #6665

[CI] Set main as default in github actions

---

docker/install/ubuntu_install_redis.sh

Fixes #6673
A bug found during #6395

[CI] Install xgboost>=1.1.0 in CI container

---

nnvm/src/core/graph.cc

As discussed in https://github.com/apache/incubator-tvm/pull/5238#issuecomment-707393506

Revert #5238

---

src/auto_scheduler/search_policy/sketch_policy_rules.cc

Fix for this bug https://discuss.tvm.apache.org/t/auto-scheduling-for-lstm-operator/8158

[AutoScheduler] Fix a bug in thread binding

---

tutorials/frontend/build_gcn.py

cc @tqchen @tmoreau89 this change is required for CI to pass on the new images.

[Docker] Fix tutorial broken by Docker build

---

src/support/socket.h

Resolve more warnings in msvc

---

tests/python/relay/test_any.py

https://ci.tlcpack.ai/job/tvm/job/main/28/execution/node/290/log/

[TEST] Address flaky error in test_any

---

src/tir/transforms/ir_utils.cc

Fix the Type bug in ConvertSSA.

---

tests/scripts/task_python_docs.sh
tutorials/auto_scheduler/tune_conv2d_layer_cuda.py
tutorials/auto_scheduler/tune_matmul_x86.py

[AutoScheduler] Use tempfile in tutorials

---

CONTRIBUTORS.md

Please join us to welcome Junru Shao(@junrushao1994) as a new Committer. Junru has been actively contributing to various aspects of the TVM codebase. He reimplemented and refactored the Target system which greatly helped code lowering and code generation. Junru also largely contributed to the runtime and node objects to improve the object passing. From the frontend side, Junru has also implemented some Relay operators.
In addition, Junru has been very actively sharing his thoughts in the discussion forum to help improve the design of new features and provide new developers with better understanding of TVM. He has been constantly providing suggestive comments to the pull request.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=junrushao1994)
- [Code …

[COMMUNITY] junrushao1994 -> committer

---

python/tvm/contrib/download.py
rust/Cargo.toml
rust/tvm/examples/resnet/build.rs
rust/tvm/examples/resnet/src/build_resnet.py
tests/scripts/task_python_docs.sh
tests/scripts/task_rust.sh

Tweak a few things in order to build some Rust tests cc @tmoreau89 and @tqchen.

[Docker] Turn on Rust docs and MxNet based ResNet

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Fixes a bug from https://discuss.tvm.apache.org/t/onnx-model-compilation-tvmerror-check-failed-n-defined/8098
cc @jwfromm @masahi

add onnx resize v10 and unit test

---

docker/install/ubuntu_install_emscripten.sh

[CI] Update wasm emcc to latest

---

include/tvm/arith/iter_affine_map.h
src/arith/iter_affine_map.cc
tests/python/unittest/test_arith_iter_affine_map.py

[ARITH] iter_affine_map bug fix, stride generalize

---

python/tvm/autotvm/tuner/ga_tuner.py
python/tvm/relay/frontend/onnx.py
python/tvm/relay/frontend/pytorch.py
python/tvm/relay/frontend/qnn_torch.py
python/tvm/relay/frontend/tensorflow_parser.py
python/tvm/relay/testing/darknet.py

These errors do not seem to show up in CI, but they show up locally.
@areusch

[FIX,PYLINT] Fix pylint errors on MacOS with Python 3.8

---

version.py

[VERSION] Make script path invariant

---

docker/install/ubuntu_install_vitis_ai_packages_ci.sh

Update PYXIR version from 0.1.2 to 0.1.3.
> Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

update pyxir version to 0.1.3

---

Jenkinsfile
tests/scripts/task_web_wasm.sh

[CI] Update ci-wasm to latest

---

src/tir/transforms/ir_utils.cc

fix a bug in convertSSA.

---

docker/install/ubuntu_install_tensorflow.sh

Please refer #6754 for background.
cc @leandron , @u99127 , @tqchen

[CI] Keras version upgraded from 2.3.1 to 2.4.3

---

Jenkinsfile
tutorials/frontend/from_keras.py

- Fix Keras related regression.

[CI] Update to latest

---

python/tvm/relay/frontend/tensorflow.py
tests/python/frontend/tensorflow/test_forward.py

Sparse2Dense support added to tf frontend.
@masahi @srkreddy1238 Please help to review and merge this PR. TIA

[TENSORFLOW]Sparse2Dense support

---

docs/vta/dev/hardware.rst
docs/vta/dev/index.rst
docs/vta/install.rst
vta/python/vta/bitstream.py
vta/tutorials/matrix_multiply.py
vta/tutorials/optimize/convolution_opt.py
vta/tutorials/optimize/matrix_multiply_opt.py
vta/tutorials/vta_get_started.py

Update stale link to new location

---

cmake/config.cmake
docker/README.md
tests/scripts/task_config_build_cpu.sh
tests/scripts/task_config_build_gpu.sh
tests/scripts/task_config_build_gpu_vulkan.sh
tests/scripts/task_config_build_i386.sh
tests/scripts/task_config_build_qemu.sh
tests/scripts/task_config_build_wasm.sh

[CI] remove unused environment var

---

docs/README.txt
docs/conf.py
python/tvm/relay/frontend/pytorch.py
tests/scripts/task_python_docs.sh
tests/scripts/task_sphinx_precheck.sh

- Enable header/footer with same style as the new homepage
- Also fixed a sphinx warning in pytorch.

[DOCS] Enable theme with header and footer.

---

python/tvm/autotvm/tophub.py

Bump the TopHub version according to https://github.com/uwsampl/tophub/pull/22 and https://github.com/uwsampl/tophub/pull/23
cc @tqchen @tmoreau89

[TopHub] Update version

---

include/tvm/relay/transform.h
python/tvm/relay/transform/transform.py

Update SimplifyInference documentation

---

docs/deploy/arm_compute_lib.rst

Updated correct [path](https://github.com/apache/incubator-tvm/blob/main/docker/install/ubuntu_install_arm_compute_lib.sh) in readme
@lhutton1 Please help to review and merge.

Update path in arm_compute_lib.rst

---

src/runtime/module.cc
tests/python/unittest/test_runtime_module_based_interface.py

[Backport][Bugfix][Module] Fix recursive GetFunction in runtime::Module

---

tutorials/get_started/tvmc_command_line_driver.py

The argsort command returns a new array that is the sorted
index rather than a new sorted value array. This patch
stores the sorted index in a new variable and uses it to
reference the predicted values.

Fix bug in processing script

---

CONTRIBUTORS.md

Please join us to welcome @mbaret  as a new committer 
Matt has been contributing to relay graph optimization, customized codegen(BYOC). 
He is also spending quite a good chunk of time interacting with other developers outside his 
organizations in the form of participating discussions, helping out others and creating proposals.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=mbaret)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ambaret)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/matt-arm/summary)

[COMMUNITY] New committer -- @mbaret

---

python/tvm/relay/op/strategy/cuda.py
tests/python/relay/test_auto_scheduler_task_extraction.py

Register auto-scheduler as an implementation for conv2d, conv3d, and depthwise conv2d in NHWC and NCHW layout.

[AutoScheduler] Register auto-scheduler to more ops

---

python/tvm/ir/module.py

[TIR] Do not show meta data when printing TIR 

---

include/tvm/topi/transform.h
python/tvm/topi/transform.py
python/tvm/topi/utils.py
src/relay/op/dyn/tensor/transform.cc
src/topi/transform.cc
tests/python/relay/dyn/test_dynamic_op_level10.py
tests/python/relay/dyn/test_dynamic_op_level2.py
tests/python/relay/dyn/test_dynamic_op_level3.py
tests/python/relay/dyn/test_dynamic_op_level4.py
tests/python/relay/dyn/test_dynamic_op_level5.py
tests/python/relay/dyn/test_dynamic_op_level6.py
tests/python/relay/test_op_level4.py
tests/python/topi/python/test_topi_transform.py

cc @zhiics 
Like I said, this is from my topk branch, which is still having issues with memory corruption, so I'm not actually using the topi version by this commit.
Let me know if this works for argwhere, I'll try to update it with a topi unit test this afternoon.

Dynamic gpu tests, add dynamic strided slice to topi

---

python/tvm/autotvm/tophub.py

Bump up tophup cuda version

---

src/arith/const_int_bound.cc
src/relay/transforms/fold_scale_axis.cc
tests/python/relay/test_pass_fold_scale_axis.py
tests/python/unittest/test_arith_const_int_bound.py

@tqchen follow up while we discuss #6906

Fix edge cases in const_int_bound and fold_scale_axis

---

include/tvm/topi/transform.h
python/tvm/relay/frontend/tensorflow.py
python/tvm/relay/op/dyn/_transform.py
python/tvm/relay/op/transform.py
src/relay/op/dyn/tensor/transform.cc
src/relay/op/make_op.h
src/relay/op/tensor/transform.cc
src/relay/transforms/dynamic_to_static.cc
tests/python/relay/dyn/test_dynamic_op_level3.py
tests/python/relay/test_pass_dynamic_to_static.py

@mbrookhart @electriclilies Please help to review, thanks.

[Relay] Add dynamic SparseToDense

---

.github/workflows/main.yml

[CI] Update actions miniconda

---

CONTRIBUTORS.md

Please join us to welcome @mbrookhart as a new committer.
Matthew is one of the major authors of pattern language in Relay, which has been one of the essential infrastructure tools and has made pattern matching much easier. Matthew has been quite active contributing to non-recursive graph visitors and ONNX frontend conversions. He also helped review many pull requests and provided design advice.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=mbrookhart)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ambrookhart)
- [Community Forum Summary](https://discuss.tvm.ai/u/mbrookhart/summary)

[COMMUNITY] New committer -- @mbrookhart

---

python/tvm/relay/op/contrib/tensorrt.py

This is a PR just to maintain parity between neo/tvm and apache/tvm. The corresponding PR(already merged) can be found here https://github.com/neo-ai/tvm/pull/154/files

Add Handling of Zero Len Arguments

---

cmake/config.cmake
conda/build-environment.yaml
docs/install/from_source.rst

Enables windows build with llvm support

[DOCS] Improve windows build instruction via conda

---

cmake/modules/ClangFlags.cmake

Fix code to work with cmake 3.2

---

src/relay/transforms/merge_compiler_regions.cc
src/relay/transforms/partition_graph.cc

Cleanup comments in partition pass

---

python/tvm/auto_scheduler/cost_model/xgb_model.py
python/tvm/autotvm/tuner/xgboost_cost_model.py

Raise ImportError for XGBoost

---

vta/python/vta/top/op.py

Fix the shape check for vta dense strategy.
@icemelon9

[VTA] Fix the shape check for vta dense strategy

---

python/tvm/auto_scheduler/search_policy.py

Retry for 10 times is too many.

[AutoScheduler] Use a smaller retry number

---

docker/install/ubuntu_install_rust.sh

This PR fixes rust installation in the CPU docker image (CI)
@jroesch @tmoreau89

[Docker] fix rust installation in CI

---

python/tvm/contrib/mkldnn.py

fix call mkl gemm in mkldnn.py
@cchung100m please kindly review

[Contrib] Fix call mkl gemm in mkldnn.py

---

tests/python/contrib/test_tensorrt.py

Fix trt Test

---

tutorials/micro/micro_reference_vm.py

A few minor fixes to the tutorial which could help new users.

[µTVM] Fix paths in the reference VM tutorial and add vbguest recommendation

---

tests/python/relay/test_pass_dead_code_elimination.py

This PR just cleans up DCE tests. cc @MarisaKirisame @mbrookhart

[Relay][Pass] Clean up DCE tests in preparation for refactoring. 

---

tests/python/topi/python/test_topi_argwhere.py

https://github.com/apache/tvm/issues/7041

[FIX] disable cuda test for argwhere

---

python/tvm/relay/op/op_attrs.py

[quantization] fix missing ffi binding of relay.attrs.DequantizeAttrs

---

cmake/modules/CUDA.cmake

https://github.com/apache/tvm/pull/7056#issuecomment-741444918
@comaniac

[NVCC] Fix nvcc compile option to be compatible with older cuda

---

python/tvm/relay/build_module.py
python/tvm/relay/op/contrib/arm_compute_lib.py
src/target/llvm/llvm_module.cc
src/tir/transforms/arg_binder.cc
src/tir/transforms/storage_rewrite.cc

- Better document tvm.relay.create_executor
- Print what was provided in src/target/llvm/llvm_module.cc,
src/tir/transforms/arg_binder.cc,
src/tir/transforms/storage_rewrite.cc
@hogepodge

[FIX] Improve error messages and docs

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

This PR adds an ability to handle axis as scalar value in reduce

[TFLite] added scalar axis value handling in reduce

---

python/tvm/relay/op/strategy/cuda.py

[VTA] update 3rdparty submodule

---

python/tvm/topi/cuda/conv2d_winograd.py
tests/python/relay/test_auto_scheduler_task_extraction.py

Fix https://github.com/apache/tvm/issues/7090

[AutoScheduler]Fix winograd infer tize

---

src/target/source/codegen_metal.cc

[metal] support int64

---

CONTRIBUTORS.md

Please join us to welcome @leandron as a new reviewer. He has made a contributions to the command line driver, as well as other things related to the frontends.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=leandron)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:leandron)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/leandron/summary)

[COMMUNITY] New reviewer @leandron

---

include/tvm/runtime/data_type.h

Rather than have these tag along in a larger PR I just make this simple PR

Fix spelling in some comments

---

python/tvm/topi/nn/batch_matmul.py
python/tvm/topi/testing/batch_matmul.py
python/tvm/topi/x86/batch_matmul.py
tests/python/topi/python/test_topi_batch_matmul.py

This PR attempts to solve #7102

Fix a bug in batch_matmul that te.max should be used

---

tutorials/frontend/from_onnx.py

As ONNX support improves, add more information about how the model importer works to aid new users.

Added additional information to the from_onnx tutorial

---

docs/conf.py
include/tvm/relay/attrs/nn.h
python/tvm/relay/op/strategy/generic.py
python/tvm/relay/op/strategy/x86.py
python/tvm/topi/cuda/conv2d_winograd.py
python/tvm/topi/nn/conv2d.py
python/tvm/topi/nn/conv3d.py
python/tvm/topi/x86/conv2d_alter_op.py
src/auto_scheduler/search_policy/sketch_policy_rules.cc
src/relay/op/nn/convolution.h
src/relay/transforms/auto_scheduler_layout_rewrite.cc
tests/python/relay/test_auto_scheduler_layout_rewrite.py
tests/python/relay/test_auto_scheduler_task_extraction.py
tests/python/relay/test_auto_scheduler_tuning.py

- Enable winograd conv2d for cpu targets
- Add layout rewrite for conv3d

[AutoScheduler] Enable winograd for conv2d and layout rewrite for conv3d

---

docker/Dockerfile.demo_cpu
docker/Dockerfile.demo_gpu
docs/contribute/code_guide.rst
docs/contribute/pull_request.rst
docs/dev/benchmark.rst
docs/dev/index.rst

Update the docs stale links

---

python/tvm/relay/op/strategy/mali.py

Signed-off-by: leowang1225 <810916296@qq.com>

[Auto Scheduler][fix] Add dense strategy for mali

---

include/tvm/support/logging.h

Fix ICHECK_NOTNULL in logging.h

---

Jenkinsfile

cc @tmoreau89 @junrushao1994 @comaniac

[CI] make sure submodule checkout in clean state

---

python/tvm/relay/op/nn/nn.py

Fix Issue #7244 
cc @luyaor @masahi @mbrookhart

[ONNX Frontend] add default value for leaky relu alpha

---

nnvm/include/nnvm/graph.h
nnvm/include/nnvm/layout.h
nnvm/include/nnvm/op.h
nnvm/include/nnvm/tuple.h
nnvm/src/core/graph.cc
nnvm/src/core/op.cc
nnvm/src/core/pass.cc
nnvm/src/core/symbolic.cc
nnvm/src/pass/correct_layout.cc
nnvm/src/pass/gradient.cc
nnvm/src/pass/graph_algorithm.h
nnvm/src/pass/infer_shape_type.cc
nnvm/src/pass/place_device.cc
nnvm/src/pass/plan_memory.cc
nnvm/src/pass/print_graph_ir.cc
nnvm/src/pass/saveload_json.cc
nnvm/tests/cpp/op_test.cc
nnvm/tests/cpp/tuple_test.cc

This PR reverts the changes from #6758 for NNVM subdirectory, since NNVM is separate project and does not know anything about the rest of TVM (including the ICHECK macro).

Do not use ICHECK in nnvm

---

src/runtime/contrib/cblas/gemm_common.h
src/runtime/vulkan/vulkan_common.h
src/runtime/vulkan/vulkan_module.h
src/runtime/vulkan/vulkan_shader.h
src/runtime/vulkan/vulkan_stream.h

These are all of the instances I could find outside of 3rdparty

Change the all #pragma once to ifdef include guard

---

docs/dev/index.rst

cc @junrushao1994 @tmoreau89 @zhiics

[DOCS] Fix figure links

---

tests/scripts/task_sphinx_precheck.sh

Fixing up task_sphinx_precheck on os x.

switch to more portable bash pipeline syntax

---

tests/scripts/task_ci_python_setup.sh

* Upstream fix in https://github.com/tlc-pack/tlcpack-sphinx-addon/commit/995178d81e6e38eabbc28da2b285b68583c88769
@tqchen @mdw-octoml

Bring back numbered lists to TVM docs.

---

tutorials/frontend/deploy_sparse.py

I've just mentioned that GPU + CUDA was supported and added some sample results.
@jwfromm @binarybana

[TUTORIAL] Add gpu instructions and results to deploy_sparse

---

CONTRIBUTORS.md

Please join us to welcome @Laurawly  as a new PMC member.  Leyuan has been contributing to the project since the very beginning. Throughout the course of her contributions, she has made significant improvements in the area of GPU optimizations,
created the intel graphics support, and pushed major irregular computation support(such as NMS) in GPU.
She also consistently picks up and manages PRs in the related areas and engage with the community under the apache way.
- [Commits History](https://github.com/apache/tvm/commits?author=Laurawly)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:Laurawly)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Laurawly/summary)

[COMMUNITY] @Laurawly => PMC

---

CONTRIBUTORS.md

Please join us to welcome Tristan Konolige (@tkonolige) as a new reviewer. Tristan has been actively contributing to TVM core compiler and TVM script.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=tkonolige)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:tkonolige)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/tkonolige/summary)

[COMMUNITY] @tkonolige -> Reviewer

---

CONTRIBUTORS.md

Please join us to welcome @jwfromm as a new committer
Josh has been to adding new operators and improving frontend support for ONNX. He also spends time interacting with other developers and actively reviewing other people's work.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=jwfromm)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ajwfromm)
- [Community Forum Summary](https://discuss.tvm.ai/u/jwfromm/summary)

[COMMUNITY] @jwfromm -> Committer

---

src/relay/analysis/type_solver.cc
src/relay/analysis/type_solver.h
src/relay/transforms/type_infer.cc
tests/python/relay/test_type_infer.py

cc @jroesch @altanh @tmoreau89

Fix an issue with dynamic functions overwritting call arg types

---

python/tvm/relay/op/_tensor.py
tests/python/relay/test_any.py

Add a shape function and dynamic test for round

---

tests/python/contrib/test_dlpack.py

Fixes https://github.com/apache/tvm/issues/7312
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7303/12/pipeline/
@tqchen @zhiics @junrushao1994

[TEST] Relax tolerance for dlpack <-> pytorch test

---

python/tvm/driver/tvmc/runner.py

get_top_results works on a copy of output

---

python/tvm/relay/op/_tensor_grad.py
tests/python/relay/test_op_grad_level1.py

fixed `tanh` gradient broken due to missing parens
cc @ZihengJiang @jroesch

[Relay][Training] Fix tanh gradient and update tests to use downstream gradient

---

CONTRIBUTORS.md

Please join us to welcome @trevor-m as a new reviewer. He has made multiple contributions to the BYOC, in particular the TensorRT support, which helps us to make use of both TVM compilation pipeline and TensorRT in an elegant way.
- [Commits History](https://github.com/apache/tvm/commits?author=trevor-m)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:trevor-m)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/trevor-m/summary)

[COMMUNITY] @trevor-m -> reviewer

---

python/tvm/contrib/graph_runtime.py
python/tvm/relay/build_module.py

Some docstring fixes.

---

tests/python/frontend/pytorch/test_object_detection.py

Let's see if this would mitigate flaky segfault problem https://github.com/apache/tvm/issues/7363
@tqchen @zhiics

[TEST] Disable one of graph rewrites in torch detection test

---

tests/python/frontend/pytorch/test_object_detection.py

Fixes https://github.com/apache/tvm/issues/7363
See the explanation in https://github.com/apache/tvm/issues/7363#issuecomment-770353594
@tqchen @zhiics

[TEST] Swap pytorch and tvm import order to fix flaky segfaults

---

CONTRIBUTORS.md

Dear Community.
Please join us to welcome @hzfan as a new reviewer.   He has brought very high quality fixes and improvements to the data type and arithmetic modules, both of which requires a lot of careful thoughts. These are important code changes that also requires a lot of thinking and polishments.
- [Commits History](https://github.com/apache/tvm/commits?author=hzfan)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:hzfan)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/hzfan/summary)

[COMMUNITY] @hzfan -> reviewer

---

Jenkinsfile
tests/scripts/task_python_frontend.sh
tests/scripts/task_python_integration.sh

To accomodate recent CI timeout outrages

[CI] Temporary increase ci timeout

---

tests/scripts/task_python_frontend.sh
tests/scripts/task_python_integration.sh

cc @junrushao1994 @zhiics @ZihengJiang

[CI] Add back the tests after timeout adjusted

---

src/relay/op/dyn/tensor/transform.cc

Check for dynamic rank before accessing value in Dynamic Reshape

---

src/runtime/contrib/sort/sort.cc

Signed-off-by: Matthew Bentham <matthew.bentham@arm.com>

Fix compilation when __ARM_FEATURE_FP16_SCALAR_ARITHMETIC

---

python/tvm/relay/op/contrib/tensorrt.py
tests/python/contrib/test_tensorrt.py

This PR fixes a bug in TRT dynamic reshape offload and adds test cases for coverage of the bug.

TRT Dynamic Reshape Fix

---

src/runtime/contrib/tensorrt/tensorrt_ops.cc

Small typo in code fixed.
@comaniac @anijain2305

[BYOC][TRT] Fix small bug preventing TRT runtime compilation for versions < 6

---

src/target/tag.cc

Fix minor tag inconsistency in previous PR.

[Target] Update tags with minor fix

---

python/tvm/target/target.py

Add the -mcpu information to complete the picture for the STM32MP1 microprocessor.
@tqchen

update stm32mp1 arm_cpu target configuration

---

include/tvm/relay/attrs/transform.h
python/tvm/relay/op/transform.py
src/relay/op/tensor/transform.cc
tutorials/language/schedule_primitives.py

This PR just fixes some typos I found while reading the docs!

Make spelling of "axes" consistent

---

include/tvm/ir/attrs.h
include/tvm/runtime/packed_func.h
include/tvm/topi/einsum.h
nnvm/src/core/symbolic.cc
python/tvm/micro/contrib/zephyr.py
python/tvm/relay/frontend/coreml.py
python/tvm/relay/testing/resnet.py
python/tvm/relay/testing/resnet_3d.py
python/tvm/relay/transform/transform.py
python/tvm/tir/stmt.py
python/tvm/tir/transform/function_pass.py
python/tvm/topi/arm_cpu/depthwise_conv2d.py
python/tvm/topi/cuda/batch_matmul_tensorcore.py
python/tvm/topi/cuda/rcnn/proposal.py
python/tvm/topi/nn/batch_matmul.py
python/tvm/topi/random/kernel.py
python/tvm/topi/testing/strided_slice_python.py
python/tvm/topi/utils.py
python/tvm/topi/vision/rcnn/proposal.py
python/tvm/topi/x86/batch_matmul.py
python/tvm/topi/x86/conv2d_avx_1x1.py
src/relay/ir/dataflow_matcher.cc
src/relay/ir/indexed_graph.cc
src/relay/transforms/partition_graph.cc
src/runtime/c_runtime_api.cc
src/tir/transforms/hoist_if_then_else.cc
tests/python/frontend/mxnet/model_zoo/resnet.py
tests/python/frontend/onnx/test_forward.py

Fixed misspelling which I found during walking through the codebase.

Fixed minor misspelling

---

CONTRIBUTORS.md

Dear Community.
Please join us to welcome @d-smirnov as a new reviewer. Dmitriy has contributed a lot to BYOC's ARM backend, quantization and TFLite frontend. Dmitriy also helps review PRs and provide a lot of suggestions to others.
- [Commits History](https://github.com/apache/tvm/commits?author=d-smirnov)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:d-smirnov)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/dmitriy-arm/summary)

[COMMUNITY] @d-smirnov -> reviewer

---

tests/python/frontend/tensorflow/test_forward.py

tf.sparse_to_dense() is deprecated. TF V2 sparse.todense() test added.

[Frontend] TF V2 sparse.todense() test added

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

This PR adds `torch.narrow` operator support.
Operator description: https://pytorch.org/docs/stable/generated/torch.narrow.html
@masahi @kevinthesun @anijain2305 @siju-samuel

[torch] Add narrow operator

---

tutorials/frontend/from_tflite.py

[Documentation][Tutorial][TFLite] add missing equal sign

---

python/tvm/runtime/vm.py

Small fix to make the example work.

Fix typo in relay.vm.Executable

---

docker/install/ubuntu_install_vitis_ai_packages_ci.sh

This updates the CI PyXIR version and is needed for testing another PR that adds Vitis AI support to TVMC.
@leandron @comaniac

[CI][VitisAI] Update CI Vitis AI PyXIR version

---

Jenkinsfile
docker/Dockerfile.ci_arm

Per https://github.com/apache/tvm/pull/7122#issuecomment-785453479
cc @u99127 @tqchen @mbaret

[CI] Bump ARM image version

---

python/tvm/relay/op/strategy/cuda.py
python/tvm/topi/cuda/conv2d_nhwc.py

This is a simple fix to prevent errors on dynamic batch conv2d nhwc (e.g. MaskRCNN).
@comaniac @merrymercy

Fix for dynamic batch size conv2d nhwc

---

src/runtime/contrib/tensorrt/tensorrt_ops.cc

@trevor-m Could you help review?

[BYOC][TRT]Fix groups cannot divide output channel count error for deconv when groups>1

---

tests/python/topi/python/test_topi_broadcast.py

https://github.com/apache/tvm/issues/7539

[TOPI] disable test_shift with i8 datatype

---

python/tvm/auto_scheduler/task_scheduler.py

Not sure why this bug is missed before..
cc @merrymercy

[Bugfix][AutoScheduler] Correctly resume status

---

src/runtime/contrib/verilator/verilator_runtime.cc

Hey @liangfu,
This is the fix you found in #7406. Thanks for catching that.
cc: @tmoreau89

[Runtime][Contrib][Verilator] remove explicit destructor call

---

src/runtime/rpc/rpc_module.cc

This PR uses the device timers introduced in #7472 to provide more accurate timing results when using the time evaluator. Specifically, synchronization time (between device and cpu) is no longer included in total runtime.
@areusch @tqchen

[RUNTIME] Switch time evaluator to use device specific timing.

---

tutorials/get_started/tvmc_command_line_driver.py

An update of the TVMC tutorial, follows the introduction and installation sections of the new getting started tutorial.

[docs] Getting Started with TVM: TVMC Tutorial

---

CONTRIBUTORS.md

Please join us to welcome @areusch as a new committer
Andrew has been heavily contributing to uTVM, on-device RPC server, various runtime features, enhancement to AutoTVM and Auto scheduler for uTVM, etc. Andrew has also been very actively sharing his thoughts at the discussion forum and reviewing pull requests provide suggestions to others.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=areusch)
- [Code Review](https://github.com/apache/incubator-tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:areusch)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/areusch/summary)

[COMMUNITY] @areusch -> Committer

---

src/runtime/contrib/miopen/conv_forward.cc

[ROCM] Fix missing <cassert> header, caused compilation failure.

---

tests/scripts/task_python_docs.sh

To temp work around CI outrage. 
cc @jroesch would be great to followup.

[CI] Temp disable rust docs build

---

Jenkinsfile

Updating ARM dependencies per @u99127.
cc @leandron @mbaret

Bump ci-cpu and ci-arm container versions

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Make Autopad static when possible

---

apps/android_camera/app/src/main/jni/tvm_runtime.h
apps/android_deploy/app/src/main/jni/tvm_runtime.h
apps/android_rpc/app/src/main/jni/tvm_runtime.h

src/runtime/logging.cc was missing from the runtime files list
@tqchen @junrushao1994

[FIX] Fix android projects

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

[ONNX] Dynamic Gather

---

docs/conf.py
tutorials/get_started/auto_tuning_with_python.py

Follows up on the TVMC tutorial, shows how to accomplish the same tasks using the python api
re-spin of https://github.com/apache/tvm/pull/7641

[docs] Getting Started with TVM: Auto Tuning with Python

---

docs/dev/runtime.rst

Hi @tqchen and community, here is a grammar fix for runtime document. Thanks! :D

[DOC] Grammar fix

---

CONTRIBUTORS.md

Please join us to welcome @spectrometerHBH as a new reviewer. He contributed to TVMScript, arithmetic analyzer, and the new TensorIR.
- [Commits History](https://github.com/apache/tvm/commits?author=spectrometerHBH)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:spectrometerHBH)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/spectrometerHBH/summary)

[COMMUNITY] Bohan Hou -> reviewer

---

CONTRIBUTORS.md

Please join us to welcome @Hzfengsy as a new reviewer.  He contributed tensor core support with intrinsic and the new TensorIR. He also actively participates in code review and forum discussion.
- [Commits History](https://github.com/apache/tvm/commits?author=Hzfengsy)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:Hzfengsy)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Hzfengsy/summary)

[COMMUNITY] Siyuan Feng -> reviewer

---

python/tvm/target/__init__.py
src/runtime/registry.cc

Fix two typos in comments.
Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>

Fix typos in comments

---

include/tvm/runtime/profiling.h
python/tvm/runtime/__init__.py
python/tvm/runtime/profiling.py
src/node/structural_hash.cc
src/runtime/graph_executor/debug/graph_executor_debug.cc
src/runtime/profiling.cc
src/runtime/vm/profiler/vm.cc
tests/python/unittest/test_runtime_profiling.py
tests/python/unittest/test_runtime_vm_profiler.py

This patch changes the profiler output from a string to a Report object. A Report can either output CSV or the usual human-readable table.
@icemelon9 @comaniac @junrushao1994

[PROFILER] Add CSV output to profiler

---

src/te/operation/tensorize.cc
tests/python/unittest/test_te_schedule_tensorize.py

As discussed in #7879, this PR fixes the reusing case.

[Tensorize] Fix compute reusing

---

CONTRIBUTORS.md

Please join us to welcome @Meteorix  as a new reviewer.
He contributed a few important improvements to TensorCore's enablement and brings
helpful discussions to performance optimizations for tensor core workloads.
- [Commits History](https://github.com/apache/tvm/commits?author=Meteorix)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:Meteorix)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Meteorix/summary)

[COMMUNITY] New Reviewer -- Meteorix

---

python/tvm/relay/build_module.py

[Relay] fix Relay build docstring

---

tutorials/frontend/deploy_sparse.py

[FIX] Fix deploy_sparse tutorial

---

docs/install/from_source.rst

[DOC] Add how to enable IR debug messages.

---

CONTRIBUTORS.md

Please join us to welcome @manupa-arm as a new reviewer.
Manupa made significant contributions towards the relay graph partitioner, built BYOC support with c-source module thus enabling BYOC for uTVM, and introduced a TIR analysis pass to calculate workspace size for primfuncs.
- [Commits History](https://github.com/apache/tvm/commits?author=manupa-arm)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:manupa-arm)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/manupa-arm/summary)

[COMMUNITY] New Reviewer -- Manupa Karunaratne

---

docker/Dockerfile.ci_cpu
docker/Dockerfile.ci_gpu
docker/install/ubuntu_install_papi.sh

This is needed for #7983.
@areusch @tqchen

[DOCKER,CI] Add PAPI to docker images

---

Jenkinsfile
docker/Dockerfile.ci_gpu
docker/Dockerfile.ci_i386

- CI GPU is updated to 18.04
- i386 remains on 16.04
- Includes #8016 #8020 #7970
@tqchen @areusch

Update CI images

---

python/tvm/driver/tvmc/autotuner.py

Fix minor issues in the tvmc tune CLI

---

python/tvm/relay/transform/recast.py
tests/python/relay/test_recast.py

Fix recast of relay ops without attributes

---

python/tvm/ir/container.py
tests/python/unittest/test_ir_container.py

[CONTAINER] Add default python iterator for Map.

---

include/tvm/tir/schedule/schedule.h
python/tvm/tir/schedule/__init__.py
python/tvm/tir/schedule/schedule.py
src/tir/schedule/concrete_schedule.h
src/tir/schedule/schedule.cc

change IntRV to ExprRV for getting PrimExpr in schedule primitive (e.g. pragma
cc @tqchen @junrushao1994

[TensorIR] change IntRV to ExprRV

---

apps/bundle_deploy/runtime.cc

Fixes https://github.com/apache/tvm/issues/7856

[APPS] Add logging to the bundle.

---

CONTRIBUTORS.md

Please join us to welcome @trevor-m as a new committer.
He is the creator of tvm's TensorRT backend and frequently helps to improve GPU support and BYOC related functionalities.
- [Commits History](https://github.com/apache/tvm/commits?author=trevor-m)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:trevor-m)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/trevor-m/summary)

[COMMUNITY] New committer -- trevor-m

---

python/tvm/relay/backend/vm.py
src/relay/backend/vm/compiler.cc

Currently, in some cases this round-trip cannot be completed.  For example, if an Integer value has a value outside a 32-bit signed integer range, or if a String value contains spaces.

[VM] Avoid round-trip Target->str->Target conversions

---

docs/contribute/code_guide.rst

Per `python/tvm/_ffi/_pyversion.py`, it seems like the minimal Python requirement is Python 3.6.

Update python code style to 3.6

---

tests/scripts/task_ci_setup.sh

[CI][DOCS] Fix the sphinx doc style for sphinx4

---

src/parser/parser.cc
src/parser/tokenizer.h
tests/python/relay/test_ir_parser.py

I've also improved the error handling.
@jroesch @masahi @tqchen

[FIX] Allow tokenizer to parse numbers greater than INT_MAX.

---

src/relay/qnn/op/dequantize.cc
tests/python/relay/test_op_qnn_dequantize.py

@anijain2305 @masahi 
I ran into this in a tflite model exported to ONNX.

[QNN] Support dequantizing scalar inputs

---

src/relay/backend/vm/compiler.cc
src/runtime/vm/vm.cc

cc: @ZihengJiang @masahi @junrushao1994

[VM] Improve error messages

---

python/tvm/autotvm/tophub.py

[Metal] Remove matching Metal to OpenCL in tophub

---

src/runtime/opencl/opencl_module.cc

Improve this ICHECK to avoid false positives

[OpenCL] Verify the number of parsed kernel sources against the expected number of kernel functions.

---

include/tvm/relay/attrs/transform.h
src/relay/op/tensor/transform.cc

Fix the issue in https://discuss.tvm.apache.org/t/cannt-pickle-irmodule-with-gather-nd-operator/10259 and https://github.com/apache/tvm/pull/8143#issuecomment-854444855
@comaniac @tmoreau89

Fix GatherND attribute registration

---

tests/python/relay/test_dataflow_pattern.py

Hi @tqchen @areusch:
Please help to review this minor change.
Thanks a lot. 
Regards,
Zack

[Relay][Dataflow] Fix test_rewrite_function_with_fuzzy_body test check

---

src/parser/span_check.cc

@comaniac @YuchenJin Please help to review this minor change reported by clang's warning.

[small fix] remove unused variable

---

apps/cpp_rpc/rpc_server.cc

Add support of cpp RPC-server for Apple platform.

[RPC][CPP] Add support of cpp RPC-server for Apple

---

docker/install/ubuntu_install_onnx.sh

This is a companion PR to #8193 , this just updates the ONNX versions, I will rebuild the images as part of #8031, and then merge #8193 with the new images.
cc @areusch

Update ONNX versions

---

docker/install/ubuntu_install_core.sh
docker/install/ubuntu_install_nodejs.sh
docker/install/ubuntu_install_rust.sh

Rationalize the installation of curl among all the docker install scripts.
@mbrookhart  , @leandron

Install curl in ubuntu_install_core.sh

---

docker/install/ubuntu_install_sphinx.sh

[DOCKER] fix sphinx install versions

---

CONTRIBUTORS.md

Please join us to welcome @wyc-ruiker  as a new reviewer. Yucheng has made various contributions to the TFLite importer, QNN and codegen components and helped to review code on the related frontends.
- [Commits History](https://github.com/apache/tvm/commits?author=wyc-ruiker)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:wyc-ruiker)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/reku/summary)

[COMMUNITY] Reviewer: wyc-ruiker

---

Jenkinsfile

[DOCKER] Update lint to reflect the latest state

---

docker/Dockerfile.ci_lint

Per https://github.com/apache/tvm/pull/8302

[CI] Pin mypy version

---

tests/python/relay/test_op_level10.py
tests/python/topi/python/test_topi_loss.py

Fixes the flaky test in https://github.com/apache/tvm/pull/8342

[TEST] Fix flaky test nll

---

tests/python/relay/test_ir_text_printer.py

Remove an extra print from the relay astext tests

---

python/tvm/relay/op/op_attrs.py

ffi: add missing binding for FixedPointMultiplyAttrs

---

jvm/core/src/main/java/org/apache/tvm/rpc/ConnectTrackerServerProcessor.java

After commit 0bbaf0e, android_rpc wasn't able connect to rpc_tracker.
Added addr field to cinfo.

[RPC] Fix android rpc connection to tracker

---

tests/python/frontend/tensorflow/test_forward.py

https://github.com/apache/tvm/issues/8140#issuecomment-870347980
I cannot reproduce this locally.
@tqchen @trevor-m

[TEST] Disable flaky TF combined NMS test

---

python/tvm/topi/cuda/depthwise_conv2d.py
tests/python/topi/python/test_topi_depthwise_conv2d.py

The depthwise_conv2d schedule had a bad check to make sure the iteration axis was not larger than max_num_threads. Now the iteration axis is bounded by its size or max_num_threads, whichever is smaller.
@masahi

[FIX] Fix depthwise conv2d on non-cuda GPU platforms

---

tutorials/get_started/tvmc_command_line_driver.py

Remove warning about macOS support from tutorial

macOS is now supported by TVMC

---

apps/microtvm/reference-vm/zephyr/Vagrantfile

This PR:
- fixes clock skew issue with reference virtual machine on Virtualbox
cc @areusch @gromero

[microTVM][RVM] Fix clock skew on virtualbox

---

jvm/core/src/main/java/org/apache/tvm/rpc/ConnectTrackerServerProcessor.java

Fix address and port reported by android_rpc to tracker

---

CONTRIBUTORS.md

Please join us to welcome @junrushao1994 as a new member of the PMC. Junru has been actively leading and contributing to various projects in the community that at least include:
- Design and implementation of Auto TensorIR.
- TensorIR scheduling.
- Refactoring of the `Target` system which greatly helped code lowering and code generation.
- Reimplementation of a number of runtime objects.
In addition, Junru has been very actively sharing his thoughts in the discussion forum to help improve the design of new features and guide new users to better use TVM. He has also been actively managing pull requests and engaging in the community under the apache guidelines.
- [Commits History](https://github.com/apache/incubator-tvm/commits?author=junrushao1994)
- [Code …

[COMMUNITY] @junrushao1994 -> PMC

---

CONTRIBUTORS.md

Please join us to welcome @comaniac as a new PMC member. Cody has been actively leading and contributing to various fronts in the community:
- Autoscheduler support
- Mentoring new contributors and reviewing code from others
- BYOC support
- Community outreach and discuss participations in the forum
He has also been engaging in the community under the apache guidelines.
- [Commits History](https://github.com/apache/tvm/commits?author=comaniac)
- [Code Review](https://github.com/apache/tvm/issues?q=reviewed-by+%40comaniac)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/comaniac/summary)

[COMMUNITY] comaniac added as new PMC member

---

python/tvm/auto_scheduler/task_scheduler.py

Fix auto-scheduling after 9c6658721

---

python/tvm/relay/frontend/common.py
python/tvm/relay/frontend/onnx.py
python/tvm/relay/frontend/pytorch_utils.py
python/tvm/relay/frontend/qnn_torch.py
python/tvm/relay/frontend/tensorflow.py
python/tvm/relay/frontend/tensorflow2.py
python/tvm/relay/frontend/tflite.py
python/tvm/relay/frontend/tflite_flexbuffer.py
tests/python/frontend/onnx/test_forward.py
tests/python/frontend/tflite/test_forward.py
tutorials/frontend/from_mxnet.py
tutorials/frontend/from_onnx.py

Fixed minor misspelling in frontend.

[Fix]Minor misspelling

---

src/runtime/vm/executable.cc
tests/python/unittest/test_runtime_vm_profiler.py

@mbrookhart @jroesch @anwang2009

[VM] Allow serialization of function attrs which are strings

---

src/tir/ir/buffer.cc
tests/python/unittest/test_tir_buffer.py

Fix #8093, Enhance Buffer Index Simplify

---

python/tvm/tir/transform/transform.py
src/driver/driver_api.cc
src/tir/transforms/make_packed_api.cc
tests/python/unittest/test_tir_base.py

[TIR] Bugfix for zero number arguments tir functions.

---

tests/python/relay/test_op_level3.py

Test case failed due to missing mode="add"

[Relay] Fix bug in test_op_level3

---

python/tvm/script/intrin.py
src/printer/tvmscript_printer.cc
tests/python/unittest/test_tvmscript_roundtrip.py

cc @Beya2019 @MasterJH5574 @junrushao1994 Followup of https://github.com/apache/tvm/pull/8499

[PRINTER] Fix the repeatitive cast in scripr printing

---

src/runtime/object.cc
tests/python/unittest/test_tir_base.py
tests/scripts/task_python_vta_tsim.sh

Fixes https://github.com/apache/tvm/issues/8264

[RUNTIME] Fix TypeKey2Index when for root Object

---

python/tvm/topi/cuda/conv2d_int8.py

minor change just replacing factoring number with `oc_block_factor`

[TOPI][CUDA] minor change on assert statement in conv2d_NCHWc_int8.cuda

---

tests/python/relay/test_external_codegen.py

This adds support for the external code generation tests to use AOT. As
part of this the existing logic in check_result was split out into
multiple functions, this allows selectively disabling those that aren't
supported such as JSON outputs not being supported in AOT. I've replaced
existing checks to skip tests with @pytest.mark.skipif macros as they've
been moved out of the `check_result` function.

Add support for AOT in external code generation tests

---

tests/python/relay/test_external_codegen.py

Fix test_external_codegen, broken by #8591

---

python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

@mbrookhart could you please review?

Add batch_matmul convertion to FQ2I pass

---

CONTRIBUTORS.md

Please join us to welcome [@electriclilies](https://github.com/electriclilies) as a new reviewer to TVM. She contributes to the dynamic namespace and quantization, etc.
* [Commits History](https://github.com/apache/incubator-tvm/commits?author=electriclilies)
* [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by%3Aelectriclilies)
* [Community Forum Summary](https://discuss.tvm.apache.org/u/electriclilies/summary)

[community] @electriclilies -> Reviewer

---

Jenkinsfile
rust/tvm-graph-rt/src/allocator.rs
rust/tvm-graph-rt/src/array.rs
rust/tvm-graph-rt/src/graph.rs
rust/tvm-graph-rt/src/workspace.rs
rust/tvm-graph-rt/tests/test_graph_serde.rs
tests/scripts/task_rust.sh

This PR turns Rust back on in the CI.

[Rust] Restore the Rust CI testing after Docker image update

---

python/tvm/relay/frontend/pytorch.py

Chunk in pytorch frontend was replaced by simpler implementation. It becomes 2.5 times faster.
unsafe_chunk was added to op map in pytorch frontend. It is the same chunk but in-place.

[Torch] chunk and unsafe chunk

---

python/tvm/auto_scheduler/measure.py

I was wondering what unit cooldown interval was so looked it up and wrote it in the docs.

[AutoScheduler] [Docs] [EZ] Update AutoScheduler Docs -- Units for cooldown_interval

---

tests/python/frontend/tensorflow/test_forward.py

@ANSHUMAN87 Could you please take a look?

[TF] Support TensorFlow < 1.13 for test_sparse_add

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

The celu onnx operator has been implemented. https://github.com/onnx/onnx/blob/master/docs/Operators.md#celu
@mbrookhart @jwfromm

[Onnx Operators] Celu

---

tests/lint/check_file_type.py

This is a source file type needed for https://github.com/apache/tvm/pull/8744
Co-authored-by: Grant Watson <grant.watson@arm.com>

Allow Linker script files to be committed

---

CONTRIBUTORS.md

Please join us to welcome @Mousius as a new reviewer to TVM. Christopher has been spearheading work to generate an embedded-friendly API for uTVM users, introducing user-friendly interfaces to TVM-generated models. He’s been an active participant in discussions around AOT and formalizing APIs for the C runtime.
- [Commits History](https://github.com/apache/tvm/commits?author=mousius)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Amousius+)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/mousius/summary)

[Community] @Mousius -> Reviewer

---

apps/microtvm/zephyr/template_project/microtvm_api_server.py

* suspect this should fix #8728 
* forgot to add a loop to write all the data
cc @gromero @junrushao1994

Update QemuTransport#write() to match new write API contract.

---

python/tvm/relay/testing/densenet.py

This is related [8704](https://github.com/apache/tvm/pull/8704).
Thanks

Restore License

---

apps/android_rpc/app/src/main/jni/tvm_runtime.h

Update Android RPC app to reflect the new
Vulkan source code tree structure.
closes https://github.com/apache/tvm/issues/8743

[Android][RPC] Fix Vulkan runtime support

---

python/tvm/contrib/popen_pool.py
python/tvm/testing/__init__.py
python/tvm/testing/popen_pool.py
src/support/ffi_testing.cc
tests/python/contrib/test_popen_pool.py
tutorials/autotvm/tune_conv2d_cuda.py

This PR intends to add `initializer` as well as `initargs` to `popenpool` api.
@tqchen @vinx13 @junrushao1994

[CONTRIB] Allow customized initializer in PopenPool

---

CONTRIBUTORS.md

Please join us to welcome @Lunderberg as a new reviewer to TVM. Eric has contributed many important features to the Vulkan backends. He also helps improve TVM docker images, unit tests and documents to make the CI more efficient and reliable.
- [Commits History](https://github.com/apache/tvm/commits?author=Lunderberg )
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by:Lunderberg )
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Lunderberg/summary)

[Community] @Lunderberg -> Reviewer

---

CONTRIBUTORS.md

Please join us to welcome @mdw-octoml as a new reviewer to TVM. Matt has contributed to microTVM, TVMC, etc. and has provided valuable feedback and suggestions to pull requests.
- [Commits History](https://github.com/apache/tvm/commits?author=mdw-octoml)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:mdw-octoml)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/mdw-octoml/summary)

[Community] @mdw-octoml -> Reviewer

---

apps/ios_rpc/tvmrpc/TVMRuntime.mm

[RPC] Fix ios_rpc build

---

CONTRIBUTORS.md

Please join us to welcome @Hzfengsy as a new committer to TVM. Siyuan has designed and made great contributions to TensorIR and TVMScript in TVM. He is one of the major contributors who enables initial tensor core support in TVM as well.
- [Commits History](https://github.com/apache/tvm/commits?author=Hzfengsy)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:Hzfengsy)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/Hzfengsy/summary)

[Community] @Hzfengsy -> Committer

---

.github/CODEOWNERS

[Community] Add @Hzfengsy as TIR/Auto Codeowner

---

python/tvm/te/operation.py

CC @Hzfengsy let me know if it makes sense to you

[TensorIR][Minor] Allow Tuple/Array in TE lowering

---

tests/python/frontend/onnx/test_forward.py

See issue https://github.com/apache/tvm/issues/8964. Working on https://github.com/apache/tvm/pull/8971 for a permanent fix.

[Onnx] Turn off one more flaky test

---

apps/ios_rpc/tvmrpc/TVMRuntime.mm

random_fill is used in measure.py

[RPC][IOS] Add random to ios_rpc

---

src/relay/op/nn/convolution.h
tests/python/relay/test_op_qnn_conv2_transpose.py

Fixes type inference error when data and weight have different dtype

[Relay][Op] fix conv transpose weight dtype inference

---

docs/contribute/code_review.rst

This PR updates the code review guideline
per community discussion.

[DOCS] Update code review guideline

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

[Onnx] Add Adagrad

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

The final in a series of simple onnx ops used for training

[Onnx] Add Adam

---

CONTRIBUTORS.md

Please join us to welcome @AndrewZhaoLuo as a new reviewer to TVM. Andrew has mainly contributed to automatic mixed precision (AMP) support and ONNX frontend improvements.
- [Commits History](https://github.com/apache/tvm/commits?author=AndrewZhaoLuo)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:AndrewZhaoLuo)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/AndrewZhaoLuo/summary)

[Community] @AndrewZhaoLuo -> Reviewer

---

python/tvm/topi/cuda/pooling.py
python/tvm/topi/x86/pooling.py

It's a follow-up update for #8957. In previous PR, I forgot to fix other pooling schedules in cuda and x86.

[TOPI] Fix more pooling schedule

---

python/setup.py

Fix one issue caused by #9005 in the packaging system.
cc @tqchen @manupa-arm @areusch for reviews

Fix line break in `setup.py`

---

tests/python/frontend/onnx/test_forward.py

[Onnx] Increase tolerances for reduce tests

---

python/tvm/te/operation.py

I noticed that the script is not runnable so I added some imports and definition for axis reducer to make it complete.

[Docs][TE] Minor Change in Create Prim Func function Docs

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

fix for padding calculation in transpose conv

[TFLite] Fix padding calculation in Transpose Conv

---

CONTRIBUTORS.md

Please join us to welcome @jtuyls as a new reviewer to TVM. Jorn has been maintaining the Xilinx Vitis AI integration with TVM.
- [Commits History](https://github.com/apache/tvm/commits?author=jtuyls)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:jtuyls)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/jtuyls/summary)

 [Community] @jtuyls -> Reviewer

---

cmake/utils/FindCUDA.cmake

Update find cublas so it searches the default path if needed.

---

src/target/llvm/codegen_cpu.cc
src/target/llvm/codegen_cpu.h
src/target/llvm/codegen_hexagon.cc

Follow the change from `DLContext` to `DLDevice`.

[LLVM] Rename t_tvm_context_ to t_tvm_device_, NFC

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/test_forward.py

https://pytorch.org/docs/stable/generated/torch.all.html
https://pytorch.org/docs/stable/generated/torch.any.html
cc @comaniac @jcf94 @junrushao1994 @interesaaat

[Torch] Support "all" and "any" op

---

python/tvm/topi/math.py

Tanhonential is a cool word though B)

[Typo] Correct fast_tanh description

---

python/tvm/meta_schedule/runner/local_runner.py
tests/python/unittest/test_meta_schedule_runner.py

This PR intends to add clean-up after each run of `LocalRunner`
cc: @junrushao1994 @vinx13

[Meta Scheduler] Add cleanup for localrunner

---

Jenkinsfile

* Close #9158
cc @Mousius @jtuyls

Update ci-cpu to v0.78

---

CONTRIBUTORS.md

Please join us to welcome @wrongtest as a new reviewer. They have been contributing a few high quality patches to arith pattern matchers and low level TIR. 
- [Commits History](https://github.com/apache/tvm/commits?author=wrongtest)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:wrongtest)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/wrongtest/summary)

[COMMUNITY] New reviewer -- wrongtest

---

python/tvm/contrib/cutlass/build.py
python/tvm/contrib/cutlass/gen_gemm.py

Adds huge QOL improvement features when applying CUTLASS byoc to real world models like `bert-large`:
* Cache profiling results so that we don't have to repeat profiling for the same `(M, N, K)` in a model.
* Use a new feature in CUDA 11.2 to support compiling all generated kernels in parallel. `bert-large` ends up generating hundreds of kernels after profiling, and all of them are compiled by a single invocation of `nvcc` running on a single thread. Without this feature, compiling is too slow and painful.  
@comaniac @Laurawly

[CUTLASS, Eazy] Cache profiling result and support compiling generated kernels in parallel 

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Added support for  quantized NEG operator in TFLite frontend.
cc @areusch @leandron @Mousius @gromero for reviews

Support quantized NEG operator in TFLite frontend

---

docker/install/ubuntu_download_arm_compute_lib_binaries.sh

This PR changes ACL version to v21.08
*ACL stands for "Compute Library for the Arm® Architecture"

[BYOC] [ACL] Update ACL to 21.08

---

Jenkinsfile

[CI] Hot fix the python integration script misplacement

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Added support for quantized ABS operator in TFLite frontend.
cc @areusch @leandron @Mousius @gromero for reviews
Co-authored-by: Matthew Barrett <Matthew.Barrett@arm.com>

Support quantized ABS operator in TFLite frontend

---

.github/CODEOWNERS
CONTRIBUTORS.md

[COMMUNITY] Update my github id

---

CONTRIBUTORS.md

Please join us to welcome Chris Sullivan (@ csullivan) as a reviewer. He has been working on TIR support, ONNX frontend, OpenCL support, etc., and has provided active code reviews
- [Commits History](https://github.com/apache/tvm/commits?author=csullivan)
- [Code Review](https://github.com/apache/tvm/pulls?q=reviewed-by%3Acsullivan)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/csullivan/summary)

[COMMUNITY] Chris Sullivan -> Reviewer

---

include/tvm/tir/schedule/schedule.h
python/tvm/tir/schedule/schedule.py
src/tir/schedule/analysis/analysis.cc
src/tir/schedule/concrete_schedule.cc
src/tir/schedule/concrete_schedule.h
src/tir/schedule/primitive.h
src/tir/schedule/primitive/sampling.cc
src/tir/schedule/schedule.cc
src/tir/schedule/traced_schedule.cc
src/tir/schedule/traced_schedule.h
src/tir/schedule/utils.h
src/tir/transforms/compact_buffer_region.cc
tests/python/unittest/test_tir_schedule_sampling.py

This PR add a schedule primitive `Sample-Perfect-Tile` that returns a random tiling plan of a given loop

[MetaSchedule] Sample-Perfect-Tile

---

include/tvm/tir/schedule/schedule.h
python/tvm/tir/schedule/schedule.py
src/tir/schedule/concrete_schedule.cc
src/tir/schedule/concrete_schedule.h
src/tir/schedule/primitive.h
src/tir/schedule/primitive/get_block_loop.cc
src/tir/schedule/schedule.cc
src/tir/schedule/traced_schedule.cc
src/tir/schedule/traced_schedule.h
tests/python/unittest/test_tir_schedule_utilities.py

[TIR][Schedule] Add get-child-blocks primitive

---

python/tvm/meta_schedule/utils.py
tests/python/unittest/test_meta_schedule_task_scheduler.py

Simply fixing the typo introduced in previous PR #9451 .

[Minor] Fix Typo

---

python/tvm/relay/backend/executor_factory.py

Fix function annotation

---

python/tvm/relay/frontend/onnx.py
tests/python/frontend/onnx/test_forward.py

Hit an issue with a model that had axes=[-1]

[ONNX] Normalize axes for Slice

---

python/tvm/relay/frontend/keras.py

This code change keeps compatibility with tflite 2.4
cc @areusch @leandron @gromero @Mousius for reviews

Improve the keras frontend to support tflite 2.6

---

LICENSE

This commit is ported from v0.8 branch.

Update license file to note libbacktrace

---

NEWS.md

This commit is ported from v0.8 branch.

Update NEWS to include v0.8 change log

---

conda/recipe/meta.yaml
include/tvm/runtime/c_runtime_api.h
python/tvm/_ffi/libinfo.py
version.py
web/package.json

Bump version to 0.9.dev0 as v0.8.0 has been released.

Bump version to 0.9.dev0

---

Jenkinsfile

Hotfix Jenkinsfile

---

CONTRIBUTORS.md

Dear community,
Please join us to welcome @areusch as a new member of the PMC. Andrew has been actively leading and contributing to the design and/or implementation of several components of the project in the community, which at least includes:
* µTVM: rolled out the roadmap of standalone µTVM and organized the µTVM community meetings.
* runtime: AoT runtime and module-based module runtime interface.
* Object systems: proposed to use `Artifact` for better code loading, debugging, and management of codegen.
* CI, documentation, and refactoring of various modules in the system.
In addition, Andrew has been very actively participating the design discussion and sharing his ideas in the forum. He He has been also actively managing the PRs and issues.
* [Commits History …

[COMMUNITY] @areusch -> PMC

---

apps/cpp_rpc/rpc_server.cc

If another server is already running on the port specified, the server
attempts to bind to the next available port.  Previously, the server
would report it's initial attempted port to the tracker, rather than
the port that it was able to bind to.  After this commit, the server
will report the correct port to the tracker.
In addition, this commit renames "port_" to "port_search_start_" to
avoid similar confusion in the future.

[RPC] Report correct port from C++ RPC to tracker.

---

cmake/config.cmake

This documents the cmsis-nn options in the config.cmake template.
@leandron @manupa-arm @areusch

Document CMSIS-NN Options.

---

python/tvm/micro/project.py

This commit removes prepare_options() helper function because it's now
superfluous since the default values for the project options are now set
correctly at the server side, hence there is no need to force settting
them at the client side.
Also prepare_options() can incorrectly set the default value of Zephyr's
'west_cmd' option when that option is not passed by the user. Hence by
removing that function this issue is resolved too. Here is a simple repro
for this issue:
```
gromero@amd:~/git/tvm$ bash -x t.sh 
+ TVMC='python3 -m tvm.driver.tvmc'
+ python3 -m tvm.driver.tvmc micro create --force /tmp/micro_speech /home/gromero/sandbox/micro_speech.tar zephyr --project-option project_type=host_driven zephyr_board=stm32f746g_disco
[23:13:40] …
```

[microTVM] Remove prepare_options()

---

docs/arch/index.rst
docs/arch/microtvm_project_api.rst
docs/arch/model_library_format.rst

@gromero @mehrdadh @guberti 
#8595

Document Project API server.

---

tests/python/unittest/test_crt.py

https://github.com/apache/tvm/issues/9084
@areusch @driazati

[CI][MicroTVM] Disable autotune log check since microtvm autotune has erros 

---

src/printer/tvmscript_printer.cc
tests/python/unittest/test_tvmscript_roundtrip.py

[TVMScript] fixing block attr printing bug

---

python/tvm/driver/tvmc/target.py
python/tvm/target/__init__.py
python/tvm/target/target.py
src/target/target_kind.cc

[Target][TVMC][UX] Avoid creation of dummy Target objects in TVMC

---

python/gen_requirements.py

Response to https://github.com/apache/tvm/pull/9519 
cc @areusch

Update gen_requirements.py with new onnx things 

---

python/tvm/relay/op/nn/_nn.py
tests/python/relay/test_pass_convert_op_layout.py

This PR support nchwc layout in ConvertLayout pass.

[Relay] Support nchwc layout in ConvertLayout pass

---

python/tvm/relay/op/contrib/tensorrt.py
python/tvm/relay/op/nn/_nn.py

WIP, need to dig deeper into whether this is a general problem with layout transforms.
Will solve https://github.com/apache/tvm/issues/9653 when merged

Fix conv2d_transpose layout transform issue in trt

---

python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

[FQ2I] Don't requantize if bias or quantize scales are approximately equal

---

python/tvm/driver/tvmc/compiler.py

Currently, `TVMC`  does not support the opt level option. I think it is very convenient for users if they can fully control the different optimization levels. :)
```python
-O [0-3], --opt-level [0-3]
specify which optimization level to use. Defaults to
'3'.
```

[TVMC] Add --opt-level to compile mode

---

Jenkinsfile

Due to the current setup jenkins file changes needs to go through docker staging branch
cc @driazati @areusch

[CI] Hotfix Jenkinsfile

---

gallery/how_to/extend_tvm/bring_your_own_datatypes.py
include/tvm/auto_scheduler/cost_model.h
include/tvm/auto_scheduler/measure.h
include/tvm/meta_schedule/space_generator.h
include/tvm/meta_schedule/task_scheduler.h
src/runtime/library_module.h
src/tir/transforms/convert_blocks_to_opaque.cc

Co-authored-by: Siyuan Feng <Hzfengsy@sjtu.edu.cn>
Co-authored-by: Bohan Hou <32121147+spectrometerHBH@users.noreply.github.com>
Co-authored-by: Hongyi Jin <3231950289@qq.com>
Co-authored-by: Ruihang Lai <lairuihangdongdong@qq.com>
Co-authored-by: Junru Shao <junrushao1994@gmail.com>
Co-authored-by: Wuwei Lin <wuwei@apache.org>
Co-authored-by: Xiyou Zhou <xiyou@octoml.ai>

Fix typo in comments

---

src/tir/schedule/analysis/analysis.cc
tests/python/unittest/test_tir_schedule_compute_at.py

Fix a small bug in `require_subtree_compact_dataflow`
Co-authored-by: Bohan Hou <32121147+spectrometerHBH@users.noreply.github.com>
Co-authored-by: Hongyi Jin <3231950289@qq.com>
Co-authored-by: Ruihang Lai <lairuihangdongdong@qq.com>
Co-authored-by: Junru Shao <junrushao1994@gmail.com>
Co-authored-by: Wuwei Lin <wuwei@apache.org>
Co-authored-by: Xiyou Zhou <xiyou@octoml.ai>

[TensorIR] fix compact_dataflow

---

docker/install/ubuntu_download_arm_compute_lib_binaries.sh

Update Compute Library for the Arm Architecture to v21.11

Move Compute library to 21.11

---

CONTRIBUTORS.md

Please join us to welcome @Lunderberg as a new committer to TVM.
Eric has greatly contributed to the testing framework and CI, TIR buffer allocation, and Vulkan backend etc. He has also been actively participating the RFC and forum discussions around the related areas, where he has shared many constructive thoughts and incorporated various helpful suggestions from the others. In addition, Eric has reviewed many PRs, provided various valuable comments, and exchanged ideas with others frequently, which greatly helped the growth of the community.
* [Commits History ](https://github.com/apache/incubator-tvm/commits?author=lunderberg)
* [Code Review](https://github.com/apache/incubator-tvm/issues?q=reviewed-by+%40lunderberg)
* [Community Forum …

[community] @lunderberg -> Committer

---

python/tvm/_ffi/libinfo.py

Ran into this when importing tvm without a build

Clarify error message for missing libraries

---

apps/microtvm/ethosu/Makefile
apps/microtvm/ethosu/include/ethosu_mod.h
docker/install/ubuntu_install_ethosu_driver_stack.sh
tests/python/contrib/test_ethosu/reference_system/ethosu_mod.h

This PR upgrades the Arm(R) Ethos(TM)-U55 NPU driver to version 21.11
@manupa-arm @ekalda @areusch @Mousius

[microNPU] Upgrade to 21.11 version of Arm(R) Ethos(TM)-U55 NPU driver

---

tests/python/frontend/tflite/test_forward.py

Updated the test input node name
cc @areusch @leandron @Mousius @gromero for reviews

Improve the frontend tflite _test_abs test to support tflite 2.6

---

CONTRIBUTORS.md

Please join us to welcome Ruihang Lai (@MasterJH5574) as a reviewer. He has contributed to TensorIR schedule primitives, tutorials, and TVMScripts.
- [Commits History](https://github.com/apache/tvm/commits?author=MasterJH5574)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:MasterJH5574)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/MasterJH5574/summary)

[COMMUNITY] Ruihang Lai -> Reviewer 

---

tests/python/frontend/paddlepaddle/test_forward.py

This pull request try to solve the problem of https://github.com/apache/tvm/issues/9713

disable signal capture in unit test of paddle frontend

---

docs/arch/inferbound.rst
version.py

This patch is to fix some minor typos in tvm

---

python/tvm/contrib/pipeline_executor.py

Fixed the deprecation warning issue

Fixed deprecation warning issue in pipeline executor

---

tests/python/relay/aot/aot_test_utils.py
tests/python/relay/utils/external_codegen.py

[TESTS] Fix running tests without MICRO

---

python/tvm/relay/frontend/common.py
python/tvm/relay/frontend/pytorch.py
python/tvm/relay/op/tensor.py
tests/python/frontend/pytorch/test_forward.py

This implements dot product as a composite of of multiply + sum, addresses part of #9843
cc @masahi

Add support for aten::dot

---

python/tvm/relay/frontend/onnx.py

The ONNX `Softmax` op does not convert one-to-one to `relay.nn.softmax` because older ONNX Softmax ops have [very strange spec](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Softmax-11): In particular, it cannot support doing softmax on the `C` dim in NCHW input, for example.
Our converter manually decomposes softmax into simpler ops. This prevents benefiting from future improvement in our softmax kernel implementation (fusing max, exp, sum etc into one kernel as in https://triton-lang.org/getting-started/tutorials/02-fused-softmax.html). So for cases that can convert to `relay.nn.softmax` directly, we should use it.
@mbrookhart @anwang2009 @AndrewZhaoLuo @elvin-n

[ONNX] Use relay softmax op to convert Softmax if posssible

---

CONTRIBUTORS.md

Please join us to welcome @AndrewZhaoLuo as a new committer to TVM.
Andrew has made great contributions, especially to automatic mixed precision (AMP) support and Relay frontends improvements. Andrew is also an easy-to-collaborate person. Specifically, when he files or reviews a PR, he is always open to discuss and accept comments from PR authors and reviewers, which results in a smooth discussion process and could efficiently push the discussion further. In addition, he has been actively participating the forum discussions to address related questions, provide his thought and experience. This greatly helps new community members and makes the community better.
- [Commits History](https://github.com/apache/tvm/commits?author=AndrewZhaoLuo)
- [Code …

[community] @AndrewZhaoLuo -> Committer

---

tests/python/frontend/tflite/test_forward.py

Updated the test for quantized graph creation to support tflite 2.6
cc @areusch @leandron @Mousius @gromero for reviews

Improve the frontend tflite _test_rsqrt test to support tflite 2.6

---

python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

Should be fairly uncontroversial.
cc @anwang2009

[FQ2I] Add Min/Max operator support

---

docker/install/ubuntu_install_oneflow.sh

@masahi  This pr for https://github.com/apache/tvm/pull/8790#issuecomment-1011631461.

change install version of gpu to cpu

---

docker/Dockerfile.ci_arm
docker/Dockerfile.ci_cpu
docker/Dockerfile.ci_gpu
docker/Dockerfile.ci_i386
docker/Dockerfile.ci_lint
docker/Dockerfile.ci_qemu
docker/Dockerfile.ci_wasm

[CI] Fix pip cache config bug

---

python/tvm/relay/frontend/tflite.py
tests/python/frontend/tflite/test_forward.py

Support TODO in convert_fully_connected in tflite

[Relay/Frontend][TFLite] Change the output shape calculation based on keep_dim option in fully connected

---

python/tvm/relay/backend/contrib/ethosu/legalize.py

In #9508 the decision was made to remove the UnsupportedLayout exception
and the checks that throw it, this PR is cleaning up some that remained.
cc @ekalda @dchauhan-arm @manupa-arm @mbaret @NicolaLancellotti

[microNPU] Remove remaining UnsupportedLayout checks

---

python/tvm/meta_schedule/postproc/rewrite_parallel_vectorize_unroll.py
src/meta_schedule/postproc/rewrite_parallel_vectorize_unroll.cc
tests/python/unittest/test_meta_schedule_postproc_rewrite_parallel_vectorize_unroll.py

This is one of postproc for meta-schedule.
Co-authored-by: Junru Shao <junrushao1994@gmail.com>
Co-authored-by: Xiyou Zhou <xiyou@octoml.ai>
Co-authored-by: Bohan Hou <32121147+spectrometerHBH@users.noreply.github.com>
Co-authored-by: Ruihang Lai <lairuihangdongdong@qq.com>
Co-authored-by: Hongyi Jin <3231950289@qq.com>
Co-authored-by: Wuwei Lin <wuwei@apache.org>
cc @junrushao1994 @comaniac @MasterJH5574 @jinhongyii

[MetaSchedule][M4a] PostProcessor: Rewrite-Parallel-Vectorize-Unroll

---

docker/install/ubuntu_install_zephyr.sh

This supports the reference system added in #9853

[microTVM] Update Zephyr to 2.7

---

python/tvm/relay/frontend/caffe.py
tests/python/frontend/caffe/test_forward.py

[Caffe Frontend] Add support for Power layer

---

python/tvm/relay/op/contrib/ethosn.py
src/relay/backend/contrib/ethosn/codegen.cc
src/relay/backend/contrib/ethosn/ethosn_api.cc
src/relay/backend/contrib/ethosn/ethosn_api.h
tests/python/contrib/test_ethosn/infrastructure.py
tests/python/contrib/test_ethosn/test_addition.py
tests/python/contrib/test_ethosn/test_concatenate.py
tests/python/contrib/test_ethosn/test_constant_duplication.py
tests/python/contrib/test_ethosn/test_conv2d.py
tests/python/contrib/test_ethosn/test_depth_to_space.py
tests/python/contrib/test_ethosn/test_fullyconnected.py
tests/python/contrib/test_ethosn/test_networks.py
tests/python/contrib/test_ethosn/test_pooling.py
tests/python/contrib/test_ethosn/test_relu.py
tests/python/contrib/test_ethosn/test_reshape.py
tests/python/contrib/test_ethosn/test_sigmoid.py
tests/python/contrib/test_ethosn/test_split.py
tests/python/contrib/test_ethosn/test_topologies.py

Per-axis quantization to follow

[ETHOSN] Per-tensor support for int8 operations

---

Jenkinsfile
gallery/how_to/work_with_relay/build_gcn.py

Reopening https://github.com/apache/tvm/pull/10105 from `apache` branch

[CI] Update DGL in gpu image

---

docker/install/ubuntu_install_rust.sh
docker/install/ubuntu_install_sccache.sh
docker/install/ubuntu_install_wasmtime.sh

Tested this with `./tests/scripts/task_rust.sh` to ensure it builds.

[CI] Further open up Rust permissions

---

python/tvm/meta_schedule/schedule_rule/__init__.py
src/meta_schedule/mutator/mutate_unroll.cc
src/tir/schedule/concrete_schedule.cc
src/tir/schedule/concrete_schedule.h
src/tir/schedule/instruction_traits.h
src/tir/schedule/primitive.h
src/tir/schedule/trace.cc
src/tir/schedule/traced_schedule.h

[Misc] typo and nit fixes

---

src/tir/usmp/transform/assign_pool_info.cc
tests/python/unittest/test_meta_schedule_mutator_mutate_tile_size.py

The issue pops up when building in DEBUG mode

[skip ci][BugFix] Linker: undefined reference to kTargetPoolReadWriteAccess

---

Jenkinsfile

This includes sccache, and these are the less troublesome images.
Also see #10120 for update issue.

[CI] Update ci_arm and ci_lint

---

tests/python/contrib/test_popen_pool.py

Remove flaky test as discussed here: https://github.com/apache/tvm/issues/10103
@driazati @vinx13 @tqchen

Remove flaky test - tests/python/contrib/test_popen_pool.py::test_popen_pool_executor_async

---

CMakeLists.txt
src/runtime/opencl/opencl_common.h
src/runtime/opencl/opencl_device_api.cc
src/runtime/opencl/opencl_module.cc

OpenCL debug runtime timer handler added.

---

python/tvm/relay/op/_transform.py
tests/python/relay/test_any.py

We recently found an issue in a model with static strided slice on a dynamic input. The slicing was done with negative strides and extremely large begin/end. This is apparently an edge case we already supported in the dynamic strided slice shape function, but not the static one, so I aligned the methodology between the two and added tests to hit the edge case. Thanks!

[Relay] Align strided slice shape functions

---

python/tvm/relay/frontend/pytorch.py
tests/python/frontend/pytorch/qnn_test.py

See the following discuss thread for details
https://discuss.tvm.apache.org/t/bug-frontend-pytorch-relay-ir-is-inconsistent-with-that-of-the-original-model/12010

[Torch] Run torch JIT pass lower_all_tuples before conversion.

---

tests/python/contrib/test_ethosn/test_addition.py
tests/python/contrib/test_ethosn/test_fullyconnected.py

The Ethos(TM)-N tests for addition had a poor choice of parameters for
the int8 case.

[ETHOSN] Fix quantization parameters in test

---

tests/python/unittest/test_tir_schedule_sampling.py

https://github.com/apache/tvm/issues/10107

resolve issue #10107 by setting eps larger

---

tests/python/contrib/test_ethosu/test_codegen.py
tests/python/contrib/test_ethosu/test_legalize.py

Simply migrates the Relay style tests to TFLite for unification among other tests.
cc @ekalda @manupa-arm

[microNPU] Use TFLite tests for strided_slice

---

apps/wasm-standalone/wasm-graph/tools/build_graph_lib.py
docs/arch/benchmark.rst
gallery/tutorial/autotvm_relay_x86.py
gallery/tutorial/tvmc_command_line_driver.py
gallery/tutorial/tvmc_python.py
python/tvm/relay/frontend/onnx.py
tests/python/contrib/test_bnns/test_onnx_topologies.py

PR #10218 was not enough for this fix so this should probably run through full CI to make sure it got everything. This keeps the use of HEAD for tutorials but pins the commit for things in tests.
cc @mousius @masahi

Fix more ONNX URLs

---

src/runtime/minrpc/minrpc_server.h

This way MinRPCServer can be instantiated with a custom PageAllocator.

[RPC] Take PageAllocator out of MinRPCServer, make it template parameter

---

tests/python/frontend/onnx/test_forward.py

Some tests appear to be supported so add them back. 
Only tested on CPU rn so wait for CI

[Onnx] add back supported tests

---

tests/python/frontend/tensorflow/test_forward.py

Skip some flaky tensorflow tests

---

python/tvm/relay/backend/contrib/ethosu/legalize.py
python/tvm/relay/op/contrib/ethosu.py
tests/python/contrib/test_ethosu/test_codegen.py
tests/python/contrib/test_ethosu/test_legalize.py

Adds support for offloading an int8 Leaky ReLU activation function to the NPU by leagalizing to a LUT.

[microNPU] Add support for LeakyReLU

---

tests/micro/zephyr/test_zephyr.py

[ci] Mark `test_autotune_conv2d` flaky

---

python/tvm/relay/qnn/op/legalizations.py
python/tvm/relay/transform/fake_quantization_to_integer.py
tests/python/relay/test_pass_fake_quantization_to_integer.py

Also by default legalizes them into table lookup operators.
cc @anwang2009

[FQ2I] Add support for some unary operators

---

tests/python/contrib/test_ethosu/test_codegen.py
tests/python/contrib/test_ethosu/test_lookup_table.py

[ci] Mark some ehtosu tests as flaky

---

tests/scripts/task_demo_microtvm.sh

[ci] Disable flaky microTVM tests

---

tests/python/contrib/test_cmsisnn/test_conv2d.py

[ci] Disable flaky cmsisnn tests

---

apps/microtvm/zephyr/template_project/microtvm_api_server.py

Fix issue where there are two versions of the nRF5340 development kit, 1.0.0 and 2.0.0. The 1.0.0 DK exposes three COM ports, where COM2 is used to communicate with the device while running tests. The 2.0.0 DK only has two COM ports as can be seen here:
```
$ nrfjprog --com
1050063518    /dev/ttyACM0    VCOM0
1050063518    /dev/ttyACM1    VCOM1
```
microtvm_api_server.py always uses VCOM2 which doesn't exist on the 2.0.0 DK.
To accommodate this, the USB product ID (PID) can be used to differentiate between the 1.0.0 and 2.0.0 DKs. The PID for 1.0.0 is 0x1055, while the PID for the 2.0.0 DK is 0x1051.
This PR fixes #10206
cc @mehrdadh @areusch

[microTVM][Zephyr] Add reading of nRF5340 DK product ID to determine which COM port to use while running tests

---

python/tvm/meta_schedule/cost_model/xgb_model.py
python/tvm/relay/frontend/qnn_torch.py
python/tvm/relay/qnn/op/legalizations.py
python/tvm/topi/arm_cpu/injective.py

[Lint] Fix Pylint Issues

---

src/tir/transforms/loop_partition.cc
tests/python/unittest/test_tir_transform_loop_partition.py

Currently LoopPartition has a limitation that the intersection of all conditions on var can not be none. In fact we can partition the loop when the intersection of all conditions on var is none in some cases.  For example:
```python
@T.prim_func
def concat_func(
placeholder: T.Buffer[(1, 64, 28, 28), "int8"],
placeholder_1: T.Buffer[(1, 32, 28, 28), "int8"],
placeholder_2: T.Buffer[(1, 32, 28, 28), "int8"],
T_concat: T.Buffer[(1, 128, 28, 28), "int8"],
) -> None:
for i1 in T.serial(128, annotations={"pragma_loop_partition_hint": 1}):
for i2, i3 in T.grid(28, 28):
if 96 <= i1:
T.store(
T_concat.data,
i1 * 784 + i2 * 28 + i3,
T.load("int8", placeholder_2.data, i1 * 784 + i2 * 28 + i3 - 75264),
True,
)
if 64 <= i1 and i1 < 96:
T.store(
T_concat.data,
i1 * 784 + i2 * 28 + i3,
T.load("int8", …
```

[TIR][Transform] relax LoopPartition restriction

---

docs/contribute/document.rst

Documents how to contribute TVM docs with images.

---

include/tvm/meta_schedule/builder.h
python/tvm/meta_schedule/builder/builder.py
python/tvm/meta_schedule/builder/local_builder.py

This PR adds some minor changes to Meta Schedule codebase.

[MetaSchedule] Meta Schedule Misc Update

---

src/runtime/pipeline/pipeline_struct.h

address the review comments in PR 10234

[Runtime][PipelineExecutor] Polish the name and comments of variable.

---

python/tvm/contrib/cudnn.py
python/tvm/relay/op/strategy/cuda.py
python/tvm/topi/cuda/conv2d_transpose.py
src/target/source/intrin_rule_cuda.cc
tests/python/frontend/pytorch/test_forward.py

Some discussion here: #10223
@masahi

Enable groups argument for conv2d_transpose on the cudnn backend

---

Jenkinsfile

[ci][2/2] Shard `frontend: GPU` job into 2 jobs

---

CONTRIBUTORS.md

Please join us to welcome @electriclilies as a new committer to TVM.
Lily has contributed to dynamic operators, quantization, core compiler infrastructure, frontend support, and many more fixes. She also actively reviews the PR and participates in the discussion forum.
- [Commits History](https://github.com/apache/tvm/commits?author=electriclilies)
- [Code Review](https://github.com/apache/tvm/pulls?utf8=%E2%9C%93&q=reviewed-by:electriclilies)
- [Community Forum Summary](https://discuss.tvm.apache.org/u/electriclilies/summary)

[COMMUNITY] electriclilies -> Committer

---

apps/microtvm/reference-vm/base-box-tool.py
python/tvm/autotvm/tuner/tuner.py
python/tvm/tir/transform/transform.py
tests/python/frontend/pytorch/test_forward.py
tests/python/unittest/test_arith_rewrite_simplify.py
tests/python/unittest/test_tir_schedule_split_fuse.py

Fix plint complain for some files.

Fix plint complain for some files.

---

include/tvm/runtime/data_type.h

There is a variable Unintialized Warning in building process, just fix it.

Fix a Uninitialized Variable Warnings.

---

Jenkinsfile

Modify Jenkinsfile to prevent builds from triggering on branch indexing

---

tests/python/contrib/test_ethosu/infra.py

Removing some legacy code from infra.py that is not called by anything.

[microNPU] Remove unused code from testing infra

---

src/meta_schedule/feature_extractor/per_store_feature.cc
src/meta_schedule/measure_callback/update_cost_model.cc
tests/python/unittest/test_tir_schedule_rfactor.py

This PR updated misc parts in meta-schedule. 

[MetaSchedule] update misc parts

---

src/arith/modular_set.cc
tests/python/unittest/test_arith_modular_set.py

cc @spectrometerHBH @jinhongyii @junrushao1994

[arith] Handle mod/floormod in modular set analysis

---

src/relay/backend/vm/manifest_lifetimes.cc
src/tir/transforms/renormalize_split_pattern.cc

[Minor][Build] Fix compiler warning: hidden overloaded virtual function

---

tests/python/integration/test_tuning.py

[ci] Disable flaky tuning test

---

tests/python/contrib/test_ethosu/test_codegen.py
tests/python/contrib/test_ethosu/test_networks.py

[ci] Disable flaky ethosu tests

---

python/tvm/contrib/hexagon/build.py
tests/python/contrib/test_hexagon/conftest.py
tests/python/contrib/test_hexagon/test_launcher.py
tests/scripts/task_python_hexagon.sh

- Enabling passing the adb server port
cc @kparzysz-quic

[Hexagon] Fix scripts to enable automated testing on hardware

---

Jenkinsfile
python/tvm/contrib/hexagon/hexagon.py
tests/python/contrib/test_hexagon/conftest.py
tests/python/contrib/test_hexagon/test_launcher.py
tests/scripts/task_python_hexagon_simulator.sh

[Hexagon] Enable running CI tests via simulator

---

tests/python/contrib/test_ethosu/infra.py
tests/python/relay/aot/aot_test_utils.py

In light of the flaky failures seen when running these sorts of tests (issues: #10300), adding a second attempt if the first attempt fails to try to help reduce the number of failures observed in CI.

[AOT] Rerun FVP test incase of first attempt failure

---

apps/microtvm/ethosu/corstone300.ld
apps/microtvm/ethosu/include/tvm_runtime.h
apps/microtvm/ethosu/run_demo.sh
apps/microtvm/ethosu/src/demo_bare_metal.c
apps/microtvm/ethosu/src/demo_freertos.c

This commit changes the demo to use USMP.

[microNPU] modify the demo to use USMP

---

.gitignore

Ignore these files so they are not accidentally committed.
@kparzysz-quic @adstraw @csullivan

[FIX,HEXAGON] Gitignore generated Hexagon files

---

cmake/modules/contrib/PT_TVMDSOOP.cmake

This PR fixes some usability issues for compiling PyTorch-TVM under conda environment
@Meteorix @masahi @t-vi

[PyTorch][BugFix] PyTorch-TVM Bridge Build Scripts

---

tests/python/unittest/test_meta_schedule_tune_relay.py

[Minor][MetaSchedule] Remove Unused Imports

---

python/tvm/relay/op/contrib/cmsisnn.py
src/relay/backend/contrib/cmsisnn/relay_to_tir.cc
tests/python/contrib/test_cmsisnn/test_binary_ops.py

Support clip op in qnn binary op patterns for CMSIS-NN

[CMSIS-NN] Include clip in the qnn binary op patterns

---

python/tvm/script/tir/__init__.pyi

Seems like this type annotation was missed with Eric's big PR.
@junrushao1994 @Lunderberg

[TVMSCRIPT] Add type definition for preflattened_buffer

---

.github/workflows/main.yml
conda/recipe/bld.bat

Upgrade Windows build to use windows-2019 runner

---

src/runtime/contrib/tensorrt/tensorrt_runtime.cc

I tried to build a vectornet model using Tensorrt with BYOC. I found if TVM_TENSORRT_CACHE_DIR is set, there will be a segmentation fault when loading the Tensorrt engine from the cache. This occurred during ```GetBatchSize()``` in function ```GetCachedEnginesFromDisk()```, and ```data_entry_``` is not initialized correctly.  
This issue is fixed by putting batchsize in the engine file instead of getting it by ```GetBatchSize()```. 
And during ```Init```, we should ```SetupConstants``` before ```GetCachedEnginesFromDisk```

[BYOC][TENSORRT] Fix bug of Segmentation Fault  when loading engine file.

---

src/printer/tvmscript_printer.cc
tests/python/unittest/test_tvmscript_roundtrip.py

A followup fix for https://github.com/apache/tvm/pull/9594

[TVMScript] fix print target's host

---

src/arith/rewrite_simplify.cc
tests/python/unittest/test_arith_rewrite_simplify.py

[Arith] Fix floormod rewrite simplify rule

---

python/tvm/target/target.py

Add explicit parameters to `tvm.target.hexagon()` to control LLVM code generation for floating point vector instructions.

[Hexagon] Add flags to control floating point support in HVX

---

python/tvm/relay/frontend/paddlepaddle.py

Optimize the implmentation of swish operator
@masahi @jiangjiajun 

Frontend] [PaddlePaddle] Optimize the implmentation of swish operator

---

python/tvm/topi/arm_cpu/tensor_intrin.py

As title,  this PR aims to fix some minor spelling mistakes and avoid confusion.

Fix some spell error in note
